OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meshCourantNo.H File Reference
Calculates and outputs the mean and maximum Courant Numbers.
Functions
if (mesh.nInternalFaces())
Variables
scalar meshCoNum = 0.0
scalar meanMeshCoNum = 0.0
Detailed Description
Calculates and outputs the mean and maximum Courant Numbers.
Original source file meshCourantNo.H
Definition in file meshCourantNo.H.
Function Documentation
if()
if (mesh. nInternalFaces())
Definition at line 32 of file meshCourantNo.H.
References Foam::endl(), Foam::gMax(), Foam::gSum(), Foam::Info, internalField(), Foam::mag(), meanMeshCoNum, mesh, meshCoNum, scalarField(), and Foam::fvc::surfaceSum().
Variable Documentation
meshCoNum
scalar meshCoNum = 0.0
Definition at line 29 of file meshCourantNo.H.
Referenced by if().
meanMeshCoNum
scalar meanMeshCoNum = 0.0
Definition at line 30 of file meshCourantNo.H.
Referenced by if().