OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createDynamicFvMesh.H File Reference
Functions
Info<< "Create mesh for time = "<< runTime.timeName()<< nl<< endl;autoPtr< dynamicFvMesh > meshPtr (dynamicFvMesh::New(IOobject(dynamicFvMesh::defaultRegion, runTime.timeName(), runTime, IOobject::MUST_READ)))
Variables
dynamicFvMesh & mesh = meshPtr()
Function Documentation
meshPtr()
Info<< "Create mesh for time = " << runTime.timeName() << nl << endl; autoPtr<dynamicFvMesh> meshPtr (dynamicFvMesh::New(IOobject(dynamicFvMesh::defaultRegion, runTime.timeName(), runTime, IOobject::MUST_READ)))
Variable Documentation
mesh
dynamicFvMesh& mesh = meshPtr()
Definition at line 18 of file createDynamicFvMesh.H.
Referenced by Foam::fvc::absolute(), greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), isoSurface::adaptPatchFields(), autoLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), ThermoCloud< Foam::DsmcCloud >::ap(), meshRefinement::appendPatch(), fieldToCell::applyToSet(), Foam::compressible::autoCreateAlphat(), Foam::incompressible::autoCreateEpsilon(), Foam::compressible::autoCreateEpsilon(), Foam::incompressible::autoCreateK(), Foam::compressible::autoCreateK(), Foam::compressible::autoCreateLowReMut(), Foam::incompressible::autoCreateLowReNut(), Foam::compressible::autoCreateMut(), Foam::incompressible::autoCreateNut(), Foam::incompressible::autoCreateOmega(), Foam::compressible::autoCreateOmega(), Foam::incompressible::autoCreateQ(), Foam::compressible::autoCreateQ(), Foam::incompressible::autoCreateR(), Foam::compressible::autoCreateR(), Foam::incompressible::autoCreateWallFunctionField(), Foam::compressible::autoCreateWallFunctionField(), autoRefineDriver::autoRefineDriver(), Foam::fvc::average(), functionObjectFile::baseFileDir(), basicMultiComponentMixture::basicMultiComponentMixture(), SRFForce< CloudType >::cacheFields(), Relaxation< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), ParamagneticForce< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), NonInertialFrameForce< CloudType >::cacheFields(), interpolate::calc(), mag::calc(), magSqr::calc(), div::calc(), magGrad::calc(), components::calc(), randomise::calc(), addSubtract::calc(), nearWallFields::calcAddressing(), curvatureSeparation::calcCosAngle(), faceZone::calcFaceZonePatch(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), processorPolyPatch::calcGeometry(), cellLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), ThermoParcel< ParcelType >::calcHeatTransfer(), curvatureSeparation::calcInvR1(), fieldMinMax::calcMinMaxFields(), sampledSet::calcSign(), ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), cyclicPolyPatch::calcTransforms(), Stochastic< CloudType >::calculate(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), KinematicParcel< ParcelType >::calcVelocity(), Foam::fvc::cellReduce(), CentredFitData< Polynomial >::CentredFitData(), layerAdditionRemoval::changeTopology(), attachDetach::changeTopology(), slidingInterface::changeTopology(), polyBoundaryMesh::checkDefinition(), faceZone::checkDefinition(), pointZone::checkParallelSync(), faceZone::checkParallelSync(), chemistryModel< CompType, ThermoType >::chemistryModel(), polyBoundaryMesh::clearAddressing(), SprayParcel< ParcelType >::clone(), ReactingParcel< ParcelType >::clone(), meshRefinement::collectAndPrint(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), pointConstraints::constrain(), GAMGAgglomeration::continueAgglomerating(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), reflectionVectors::correct(), directionalDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), inverseFaceDistanceDiffusivity::correct(), inverseDistanceDiffusivity::correct(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), laminar< Type >::correct(), wallDistData< wallPointData< vector > >::correct(), curvatureSeparation::correct(), patchDataWave< TransferType >::correct(), pointLinear< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), CourantNo::CourantNo(), heThermo< BasicSolidThermo, MixtureType >::Cp(), heThermo< BasicSolidThermo, MixtureType >::CpByCpv(), heThermo< BasicSolidThermo, MixtureType >::Cpv(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), displacementMeshMoverMotionSolver::curPoints(), displacementInterpolationMotionSolver::curPoints(), heThermo< BasicSolidThermo, MixtureType >::Cv(), manualDecomp::decompose(), decompositionMethod::decompose(), DESModelRegions::DESModelRegions(), fvFieldDecomposer::patchFieldDecomposer::directAddressing(), pointFieldReconstructor::pointPatchFieldReconstructor::directAddressing(), fvFieldReconstructor::fvPatchFieldReconstructor::directAddressing(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), pointTopoDistanceData::distance(), autoRefineDriver::doRefine(), noCombustion< CombThermoType >::dQ(), singleStepCombustion< CombThermoType, ThermoType >::dQ(), laminar< Type >::dQ(), wideBandAbsorptionEmission::ECont(), setTimeStepFunctionObject::enabled(), ThermoCloud< Foam::DsmcCloud >::Ep(), Lambda2::execute(), Peclet::execute(), Q::execute(), DESModelRegions::execute(), Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), polyPatch::faceAreas(), polyPatch::faceCells(), polyPatch::faceCentres(), mappedPatchBase::facePoints(), surfaceZonesInfo::faceType(), blendingFactor::factor(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::findFaceDirs(), sampledSet::findNearFace(), mappedPatchBase::findSamples(), polyMesh::findTetFacePt(), cellCuts::flip(), PatchFlowRateInjection< CloudType >::flowRate(), multivariateGaussConvectionScheme< Type >::flux(), for(), forAll(), forAllIter(), faceCorrectedSnGrad< Type >::fullGradCorrection(), correctedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), multivariateGaussConvectionScheme< Type >::fvcDiv(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), multivariateGaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), heThermo< BasicSolidThermo, MixtureType >::gamma(), GeometricField< vector, pointPatchField, pointMesh >::GeometricField(), get_edge_list(), get_geom_list(), get_mesh_dim(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), sampledSet::getBoundaryCell(), sampledSet::getCell(), cellLooper::getFirstVertEdge(), cellLooper::getMisAlignedEdge(), undoableMeshCutter::getSplitFaces(), sampledSet::getTrackingPoint(), cellLooper::getVertEdgesNonFace(), cellLooper::getVertFacesNonEdge(), calcFvcGrad::gradField(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), heThermo< BasicSolidThermo, MixtureType >::hc(), heThermo< BasicSolidThermo, MixtureType >::he(), if(), Foam::MULES::implicitSolve(), functionObject::iNew::iNew(), InflationInjection< CloudType >::InflationInjection(), FreeStream< CloudType >::inflow(), MPPICCloud< Foam::DsmcCloud >::info(), processorPolyPatch::initOrder(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::inject(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), multivariateGaussConvectionScheme< Type >::interpolate(), distanceSurface::interpolateField(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), sampledTriSurfaceMesh::interpolateField(), Foam::interpolatePointToCell(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), temperatureCoupledBase::kappa(), Lambda2::Lambda2(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::MULES::limit(), Foam::MULES::limitCorr(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), readFields::loadField(), basicThermo::lookupOrConstruct(), Foam::MULES::LTScorrect(), main(), meshRefinement::makeDisplacementField(), KinematicParcel< ParcelType >::massCell(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), faceZone::meshEdges(), polyPatch::meshEdges(), MeshedSurface< Foam::face >::MeshedSurface(), displacementMeshMoverMotionSolver::meshMover(), steadyStateDdtScheme< Type >::meshPhi(), EulerDdtScheme< Type >::meshPhi(), backwardDdtScheme< Type >::meshPhi(), localEulerDdtScheme< Type >::meshPhi(), CoEulerDdtScheme< Type >::meshPhi(), SLTSDdtScheme< Type >::meshPhi(), slidingInterface::modifyMotionPoints(), DsmcParcel< ParcelType >::move(), medialAxisMeshMover::move(), polyBoundaryMesh::movePoints(), NamedEnum< directionType, 3 >::names(), regionCoupledBaseGAMGInterface::nbrLduInterface(), sampledThresholdCellFaces::needsUpdate(), sampledIsoSurfaceCell::needsUpdate(), sampledIsoSurface::needsUpdate(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), basicChemistryModel::New(), psiReactionThermo::New(), rhoReactionThermo::New(), fluidThermo::New(), scatterModel::New(), psiuReactionThermo::New(), psiCombustionModel::New(), absorptionEmissionModel::New(), rhoCombustionModel::New(), psiThermo::New(), sootModel::New(), psiChemistryModel::New(), LESfilter::New(), basicSolidChemistryModel::New(), rhoChemistryModel::New(), solidReactionThermo::New(), snGradScheme< Type >::New(), gradScheme< Type >::New(), rhoThermo::New(), solidThermo::New(), AveragingMethod< Foam::Vector >::New(), surfaceInterpolationScheme< GType >::New(), ddtScheme< Type >::New(), d2dt2Scheme< Type >::New(), ParticleForce< CloudType >::New(), divScheme< Type >::New(), surfaceFilmModel::New(), reactionRateFlameArea::New(), multivariateSurfaceInterpolationScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), laplacianScheme< Type, GType >::New(), cellLooper::New(), thermalBaffleModel::New(), basicThermo::New(), pyrolysisModel::New(), porosityModel::New(), sampledSurface::New(), topoSet::New(), sampledSet::New(), option::New(), topoSetSource::New(), GAMGAgglomeration::New(), hexMatcher::nMaxVertPerFace(), prismMatcher::nMaxVertPerFace(), tetMatcher::nMaxVertPerFace(), tetWedgeMatcher::nMaxVertPerFace(), wedgeMatcher::nMaxVertPerFace(), pyrMatcher::nMaxVertPerFace(), cellCuts::nonAnchorPoints(), ListPlusEqOp< T, Size >::operator()(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), anisotropicFilter::operator()(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), cyclicPolyPatch::order(), OutputFilterFunctionObject< OutputFilter >::outputFilter(), metisDecomp::parallelAware(), scotchDecomp::parallelAware(), ptscotchDecomp::parallelAware(), InflationInjection< CloudType >::parcelsToInject(), sampledPatch::patchIDs(), boundaryMesh::patchNames(), Peclet::Peclet(), VoidFraction< CloudType >::postEvolve(), VoidFraction< CloudType >::preEvolve(), ParticleTrap< CloudType >::preEvolve(), ParticleErosion< CloudType >::preEvolve(), pressureTools::pressureTools(), fvMeshDistribute::printFieldInfo(), processorField::processorField(), sampledSet::pushIn(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), pyrolysisModelCollection::pyrolysisModelCollection(), Q::Q(), ReactingCloud< Foam::DsmcCloud >::ReactingCloud(), nearWallFields::read(), forces::read(), IOPosition< CloudType >::readData(), Foam::fvc::reconstruct(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::fvc::reconstructMag(), Foam::fvc::relative(), GeometricField< vector, pointPatchField, pointMesh >::relax(), undoableMeshCutter::removeSplitFaces(), manualRenumber::renumber(), zoltanRenumber::renumber(), fvMeshTools::reorderPatches(), cyclicAMIPolyPatch::resetAMI(), forces::rho(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg(), solidChemistryModel< CompType, SolidThermo >::RRs(), sampledTriSurfaceMesh::sampleField(), mappedPatchBase::sampleSize(), ThermoCloud< Foam::DsmcCloud >::setModels(), fvMeshTools::setPatchFields(), PatchInjection< CloudType >::setPositionAndCell(), PatchFlowRateInjection< CloudType >::setPositionAndCell(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setPropagationTol(), PointEdgeWave< Type, TrackingData >::setPropagationTol(), refinementIterator::setRefinement(), perfectInterface::setRefinement(), layerAdditionRemoval::setRefinement(), fixedTemperatureConstraint::setValue(), fvMatrix< Type >::setValuesFromList(), noCombustion< CombThermoType >::Sh(), laminar< Type >::Sh(), ThermoCloud< Foam::DsmcCloud >::Sh(), ThermoCloud< Foam::DsmcCloud >::sigmap(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), Foam::fvc::smooth(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), displacementMeshMoverMotionSolver::solve(), sixDoFRigidBodyMotionSolver::solve(), displacementLayeredMotionMotionSolver::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), GAMGSolver::solve(), fvMatrix< Type >::solve(), chemistryModel< CompType, ThermoType >::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregated(), SprayParcel< ParcelType >::solveTABEq(), ThermoSurfaceFilm< CloudType >::splashInteraction(), Foam::fvc::spread(), ReactingCloud< Foam::DsmcCloud >::Srho(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), regionCoupledBase::surfPtr(), cyclicAMIPolyPatch::surfPtr(), mappedPatchBase::surfPtr(), Foam::fvc::sweep(), ReactingCloud< Foam::DsmcCloud >::SYi(), GeometricField< vector, pointPatchField, pointMesh >::T(), chemistryModel< CompType, ThermoType >::tc(), externalPointEdgePoint::trackingData::trackingData(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), GradientDispersionRAS< CloudType >::update(), sampledPlane::update(), sampledPatch::update(), sampledTriSurfaceMesh::update(), cellMotionFvPatchField< Type >::updateCoeffs(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), ReactingParcel< ParcelType >::updateMassFraction(), PatchInjection< CloudType >::updateMesh(), PatchFlowRateInjection< CloudType >::updateMesh(), componentDisplacementMotionSolver::updateMesh(), displacementMotionSolver::updateMesh(), perfectInterface::updateMesh(), layerAdditionRemoval::updateMesh(), polyBoundaryMesh::updateMesh(), slidingInterface::updateMesh(), UpwindFitData< Polynomial >::UpwindFitData(), USERD_get_var_by_component(), USERD_get_var_value_at_specific(), Implicit< CloudType >::velocityCorrection(), Explicit< CloudType >::velocityCorrection(), vorticity::vorticity(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), wallShearStress::wallShearStress(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), limitedSurfaceInterpolationScheme< Type >::weights(), polyBoundaryMesh::whichPatch(), while(), PatchPostProcessing< CloudType >::write(), FacePostProcessing< CloudType >::write(), dsmcFields::write(), edgeMesh::write(), ParticleCollector< CloudType >::write(), regionSizeDistribution::write(), addSubtract::writeAddSubtractField(), addSubtract::writeAddSubtractValue(), components::writeComponentFields(), edgeVertex::writeCut(), div::writeDivField(), interpolate::writeInterpolateField(), mag::writeMagField(), magGrad::writeMagGradField(), magSqr::writeMagSqrField(), sixDoFRigidBodyMotionSolver::writeObject(), randomise::writeRandomField(), residuals::writeResidual(), yPlusLES::yPlusLES(), yPlusRAS::yPlusRAS(), fvMeshTools::zeroPatchFields(), cellMatcher::~cellMatcher(), coordinateRotation::~coordinateRotation(), CuthillMcKeeRenumber::~CuthillMcKeeRenumber(), FSD< CombThermoType, ThermoType >::~FSD(), gradScheme< Type >::~gradScheme(), greyMeanSolidAbsorptionEmission::~greyMeanSolidAbsorptionEmission(), inverseDistanceDiffusivity::~inverseDistanceDiffusivity(), localAxesRotation::~localAxesRotation(), manualDecomp::~manualDecomp(), manualRenumber::~manualRenumber(), medialAxisMeshMover::~medialAxisMeshMover(), multiLevelDecomp::~multiLevelDecomp(), randomRenumber::~randomRenumber(), renumberMethod::~renumberMethod(), SloanRenumber::~SloanRenumber(), springRenumber::~springRenumber(), structuredDecomp::~structuredDecomp(), structuredRenumber::~structuredRenumber(), and zoltanRenumber::~zoltanRenumber().