OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
StCorr.H File Reference
Functions
dimensionedScalar StCorr ("StCorr", dimless, 1.0)
if (ign.igniting())
Function Documentation
StCorr()
dimensionedScalar StCorr ("StCorr" , dimless , 1. 0)
Referenced by if().
if()
if (ign. igniting())
Definition at line 3 of file StCorr.H.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, Foam::dimArea, Foam::dimVolume, Foam::fvc::div(), Foam::endl(), Foam::gSum(), Foam::Info, Foam::max(), mesh, Foam::min(), Foam::constant::mathematical::pi(), Foam::pow(), readScalar, Foam::sqrt(), and StCorr().