OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createPcorrTypes.H File Reference
Functions
wordList pcorrTypes (p.boundaryField().size(), zeroGradientFvPatchScalarField::typeName)
for (label i=0;i< p.boundaryField().size();i++)
Function Documentation
pcorrTypes()
wordList pcorrTypes (p. boundaryField).size(, zeroGradientFvPatchScalarField::typeName)
Referenced by for(), and if().
for()
for ()
Definition at line 7 of file createPcorrTypes.H.
References p, and pcorrTypes().