OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
volContinuity.H File Reference
Functions
conserve internalField ()+
Variables
scalar sumLocalContErr
scalar globalContErr
Function Documentation
internalField()
conserve internalField ()
Referenced by pointPatchField< vector >::addToInternalField(), anisotropicFilter::anisotropicFilter(), Foam::fvc::average(), Foam::bound(), kinematicSingleLayer::CourantNumber(), displacementComponentLaplacianFvMotionSolver::curPoints(), displacementSBRStressFvMotionSolver::curPoints(), displacementLaplacianFvMotionSolver::curPoints(), fvFieldDecomposer::decomposeField(), basicSymmetryPointPatchField< Type >::evaluate(), cyclicSlipPointPatchField< Type >::evaluate(), nonuniformTransformCyclicPointPatchField< Type >::evaluate(), wedgePointPatchField< Type >::evaluate(), symmetryPlanePointPatchField< Type >::evaluate(), fixedNormalSlipPointPatchField< Type >::evaluate(), valuePointPatchField< vector >::evaluate(), CourantNo::execute(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), if(), MPPICCloud< Foam::DsmcCloud >::info(), GeometricField< vector, pointPatchField, pointMesh >::max(), GeometricField< vector, pointPatchField, pointMesh >::min(), GeometricField< vector, pointPatchField, pointMesh >::negate(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), pointPatchField< vector >::patchInternalField(), jumpCyclicFvPatchField< Type >::patchNeighbourField(), jumpCyclicAMIFvPatchField< Type >::patchNeighbourField(), cyclicFvPatchField< Type >::patchNeighbourField(), cyclicAMIFvPatchField< Type >::patchNeighbourField(), cyclicACMIFvPatchField< Type >::patchNeighbourField(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), fvFieldReconstructor::reconstructFvVolumeInternalField(), GeometricField< vector, pointPatchField, pointMesh >::replace(), pointPatchField< vector >::setInInternalField(), fvMatrix< Type >::setValuesFromList(), GeometricField< vector, pointPatchField, pointMesh >::T(), valuePointPatchField< vector >::updateCoeffs(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFixedPushedInternalValueFvPatchField< Type >::updateCoeffs(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), energyRegionCoupledFvPatchScalarField::updateInterfaceMatrix(), and regionSizeDistribution::write().
Variable Documentation
sumLocalContErr
scalar sumLocalContErr
Initial value:
= runTime.deltaTValue()*
        mag(conserve)().weightedAverage(mesh.V()).value()
Definition at line 9 of file volContinuity.H.
globalContErr
scalar globalContErr
Initial value:
= runTime.deltaTValue()*
        conserve.weightedAverage(mesh.V()).value()
Definition at line 12 of file volContinuity.H.