OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createMDFields.H File Reference
Functions
List< scalarField > allSpeciesN_RU (molecules.potential().nIds(), scalarField(mesh.nCells(), 0.0))
List< scalarField > allSpeciesM_RU (molecules.potential().nIds(), scalarField(mesh.nCells(), 0.0))
List< vectorField > allSpeciesVelocitySum_RU (molecules.potential().nIds(), vectorField(mesh.nCells(), vector::zero))
List< scalarField > allSpeciesVelocityMagSquaredSum_RU (molecules.potential().nIds(), scalarField(mesh.nCells(), 0.0))
Info<< nl<< "Creating fields."<< endl;PtrList< volScalarField > allSpeciesRhoN (molecules.potential().nIds())
forAll (allSpeciesRhoN, rN)
Info<< " Creating total number density field"<< endl;volScalarField totalRhoN(IOobject("rhoN_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimless/dimVolume, "zeroGradient");totalRhoN.internalField()=scalarField(mesh.nCells(), 0.0);totalRhoN.correctBoundaryConditions();PtrList< volScalarField > allSpeciesRhoM (molecules.potential().nIds())
forAll (allSpeciesRhoM, rM)
Info<< " Creating total mass density field"<< endl;volScalarField totalRhoM(IOobject("rhoM_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimMass/dimVolume, "zeroGradient");totalRhoM.internalField()=scalarField(mesh.nCells(), 0.0);totalRhoM.correctBoundaryConditions();PtrList< volVectorField > allSpeciesVelocity (molecules.potential().nIds())
forAll (allSpeciesVelocity, v)
Info<< " Creating total velocity field"<< endl;volVectorField totalVelocity(IOobject("velocity_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector("zero", dimVelocity, vector::zero));PtrList< volScalarField > allSpeciesTemperature (molecules.potential().nIds())
forAll (allSpeciesTemperature, t)
Info<< " Creating total temperature field"<< endl;volScalarField totalTemperature(IOobject("temperature_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimTemperature, "zeroGradient");totalTemperature.internalField()=scalarField(mesh.nCells(), 0.0);totalTemperature.correctBoundaryConditions();PtrList< volScalarField > allSpeciesMeanKE (molecules.potential().nIds())
forAll (allSpeciesMeanKE, mKE)
Function Documentation
allSpeciesN_RU()
List< scalarField > allSpeciesN_RU (molecules. potential).nIds(, scalarField(mesh.nCells(), 0.0))
Referenced by forAll(), and if().
allSpeciesM_RU()
List< scalarField > allSpeciesM_RU (molecules. potential).nIds(, scalarField(mesh.nCells(), 0.0))
Referenced by forAll(), and if().
allSpeciesVelocitySum_RU()
List< vectorField > allSpeciesVelocitySum_RU (molecules. potential).nIds(, vectorField(mesh.nCells(), vector::zero))
Referenced by forAll(), and if().
allSpeciesVelocityMagSquaredSum_RU()
List< scalarField > allSpeciesVelocityMagSquaredSum_RU (molecules. potential).nIds(, scalarField(mesh.nCells(), 0.0))
Referenced by forAll(), and if().
allSpeciesRhoN()
Info<< nl << "Creating fields." << endl;PtrList<volScalarField> allSpeciesRhoN (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [1/5]
forAll (allSpeciesRhoN , rN)
Definition at line 40 of file createMDFields.H.
References allSpeciesRhoM(), allSpeciesRhoN(), Foam::dimless, Foam::dimVolume, Foam::endl(), Foam::Info, mesh, and scalarField().
allSpeciesRhoM()
Info<< " Creating total number density field" << endl;volScalarField totalRhoN(IOobject ("rhoN_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimless/dimVolume, "zeroGradient");totalRhoN.internalField() = scalarField (mesh.nCells(), 0.0);totalRhoN.correctBoundaryConditions();PtrList<volScalarField> allSpeciesRhoM (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [2/5]
forAll (allSpeciesRhoM , rM)
Definition at line 95 of file createMDFields.H.
References allSpeciesRhoM(), allSpeciesVelocity(), Foam::dimMass, Foam::dimVolume, Foam::endl(), Foam::Info, mesh, and scalarField().
allSpeciesVelocity()
Info<< " Creating total mass density field" << endl;volScalarField totalRhoM(IOobject ("rhoM_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimMass/dimVolume, "zeroGradient");totalRhoM.internalField() = scalarField (mesh.nCells(), 0.0);totalRhoM.correctBoundaryConditions();PtrList<volVectorField> allSpeciesVelocity (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [3/5]
forAll (allSpeciesVelocity , v)
Definition at line 150 of file createMDFields.H.
References allSpeciesTemperature(), allSpeciesVelocity(), Foam::dimVelocity, Foam::endl(), Foam::Info, mesh, and vectorField().
allSpeciesTemperature()
Info<< " Creating total velocity field" << endl;volVectorField totalVelocity(IOobject ("velocity_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedVector("zero", dimVelocity, vector::zero));PtrList<volScalarField> allSpeciesTemperature (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [4/5]
forAll (allSpeciesTemperature , t)
Definition at line 224 of file createMDFields.H.
References allSpeciesMeanKE(), allSpeciesTemperature(), Foam::dimTemperature, Foam::endl(), Foam::Info, mesh, and scalarField().
allSpeciesMeanKE()
Info<< " Creating total temperature field" << endl;volScalarField totalTemperature(IOobject ("temperature_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimTemperature, "zeroGradient");totalTemperature.internalField() = scalarField (mesh.nCells(), 0.0);totalTemperature.correctBoundaryConditions();PtrList<volScalarField> allSpeciesMeanKE (molecules. potential).nIds()
Referenced by forAll(), and if().
forAll() [5/5]
forAll (allSpeciesMeanKE , mKE)
Definition at line 280 of file createMDFields.H.
References allSpeciesMeanKE(), Foam::endl(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, and scalarField().