OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
calculateMDFields.H File Reference
Functions
forAll (cellOccupancy, cell)
Variables
const List< DynamicList< molecule * > > & cellOccupancy = molecules.cellOccupancy()
Function Documentation
forAll()
forAll (cellOccupancy , cell)
Definition at line 3 of file calculateMDFields.H.
References allSpeciesM_RU(), allSpeciesN_RU(), allSpeciesVelocityMagSquaredSum_RU(), allSpeciesVelocitySum_RU(), and cellOccupancy.
Variable Documentation
cellOccupancy
const List<DynamicList<molecule*> >& cellOccupancy = molecules.cellOccupancy()
Definition at line 1 of file calculateMDFields.H.
Referenced by KinematicCloud< Foam::DsmcCloud >::buildCellOccupancy(), forAll(), MPPICCloud< Foam::DsmcCloud >::info(), InflationInjection< CloudType >::parcelsToInject(), and InteractionLists< typename CloudType::parcelType >::sendReferredData().