OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LISASMDCalcMethod2.H File Reference
Functions
if (maxValue - minValue< SMALL)
forAll (rrd, n)
while (!success &&(k< 500))
Variables
scalar delta = dD/factorGamma
scalar minValue = dD/10.0
scalar maxValue = dD
scalar range = maxValue - minValue
scalar nExp = 3
FixedList< scalar, 500 > rrd
scalar probFactorMin = exp(-pow(minValue/delta, nExp))
scalar probFactorMax = exp(-pow(maxValue/delta, nExp))
scalar probFactor = 1.0/(probFactorMin - probFactorMax)
bool success = false
scalar y = rndGen.sample01<scalar>()
label k = 0
Boltzmann constant.
x = minValue + range*(k - 0.5)/500.0
Function Documentation
if()
if ()
Definition at line 18 of file LISASMDCalcMethod2.H.
forAll()
forAll (rrd , n)
Definition at line 31 of file LISASMDCalcMethod2.H.
References Foam::exp(), n, and Foam::pow().
while()
while (!success && k< 500)
Definition at line 43 of file LISASMDCalcMethod2.H.
Variable Documentation
delta
scalar delta = dD/factorGamma
Definition at line 8 of file LISASMDCalcMethod2.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), patchInjection::correct(), drippingInjection::correct(), curvatureSeparation::correct(), kEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), standardPhaseChange::correctModel(), Smagorinsky< BasicTurbulenceModel >::correctNut(), kEqn< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), NicenoKEqn< BasicTurbulenceModel >::correctNut(), Foam::eigenValues(), LESeddyViscosity< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), kEqn< BasicTurbulenceModel >::epsilon(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), Smagorinsky< BasicTurbulenceModel >::k(), surfaceInterpolation::movePoints(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), standardRadiation::Shs(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), laminar::Su(), LISAAtomization< CloudType >::update(), reactingOneDim::updateQr(), regionSizeDistribution::write(), and FSD< CombThermoType, ThermoType >::~FSD().
minValue
scalar minValue = dD/10.0
Definition at line 12 of file LISASMDCalcMethod2.H.
Referenced by distributionModel::check(), InflationInjection< CloudType >::parcelsToInject(), and fixedValue::~fixedValue().
maxValue
scalar maxValue = dD
Definition at line 13 of file LISASMDCalcMethod2.H.
range
scalar range = maxValue - minValue
Definition at line 23 of file LISASMDCalcMethod2.H.
nExp
scalar nExp = 3
Definition at line 25 of file LISASMDCalcMethod2.H.
Referenced by while().
rrd
FixedList<scalar, 500> rrd
Definition at line 26 of file LISASMDCalcMethod2.H.
probFactorMin
scalar probFactorMin = exp(-pow(minValue/delta, nExp))
Definition at line 27 of file LISASMDCalcMethod2.H.
probFactorMax
scalar probFactorMax = exp(-pow(maxValue/delta, nExp))
Definition at line 28 of file LISASMDCalcMethod2.H.
probFactor
scalar probFactor = 1.0/(probFactorMin - probFactorMax)
Definition at line 29 of file LISASMDCalcMethod2.H.
success
bool success = false
Definition at line 38 of file LISASMDCalcMethod2.H.
y
scalar y = rndGen.sample01<scalar>()
Definition at line 40 of file LISASMDCalcMethod2.H.
k
label k = 0
Boltzmann constant.
Definition at line 41 of file LISASMDCalcMethod2.H.
Referenced by atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), block::blockDef(), mutkWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), addPatchCellLayer::calcSidePatch(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), viewFactor::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), CompactListList< T, Container >::CompactListList(), MixedDiffuseSpecular< CloudType >::correct(), radiativeIntensityRay::correct(), trackedParticle::correctAfterParallelTransfer(), Smagorinsky< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), dmat_uniform(), dtris2(), pairPotential::energy(), pairPotential::energyTable(), LESeddyViscosity< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), kEqn< BasicTurbulenceModel >::epsilon(), normal::erfInv(), pairPotential::force(), pairPotential::forceTable(), general::general(), if(), distribution::insertMissingKeys(), jenkins_hashbig(), jenkins_hashlittle(), Distribution< Type >::keys(), Foam::LUDecompose(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), distribution::mean(), Distribution< Type >::mean(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), distribution::normalised(), Distribution< Type >::normalised(), triad::operator+=(), points_delaunay_naive_2d(), Foam::printTable(), eddyViscosity< RASModel< BasicTurbulenceModel > >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), distribution::raw(), Distribution< Type >::raw(), general::sample(), pairPotential::setLookupTables(), seulex::seulex(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), Foam::solve(), SIBS::solve(), seulex::solve(), extendedEdgeMesh::sortPointsAndEdges(), SVD::SVD(), triangulation_plot_eps(), triangulation_print(), StochasticDispersionRAS< CloudType >::update(), GradientDispersionRAS< CloudType >::update(), LISAAtomization< CloudType >::update(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), block::vtxLabel(), nutkWallFunctionFvPatchScalarField::yPlus(), and mutkWallFunctionFvPatchScalarField::yPlus().
x
x = minValue + range*(k - 0.5)/500.0
Definition at line 52 of file LISASMDCalcMethod2.H.
Referenced by targetCoeffTrim::calcCoeffs(), treeBoundBox::calcExtremities(), cellLimitedGrad< Type >::calcGrad(), Stochastic< CloudType >::calculate(), polynomial::clone(), DataEntry< Foam::Vector >::clone(), rotorDiskSource::constructGeometry(), treeBoundBox::corner(), d_max(), d_min(), Polynomial< PolySize >::derivative(), normal::erfInv(), Foam::interpolateXY(), DiagonalMatrix< scalar >::invert(), Foam::kShellIntegration(), Foam::kShellMean(), multiNormal::multiNormal(), cellToCellStencil::unionEqOp::operator()(), cellToFaceStencil::unionEqOp::operator()(), combineReduceFileStates::operator()(), accessOp< T >::operator()(), AveragingMethod< Foam::Vector >::operator*=(), AveragingMethod< Foam::Vector >::operator+=(), AveragingMethod< Foam::Vector >::operator/=(), triad::operator=(), AveragingMethod< Foam::Vector >::operator=(), InflationInjection< CloudType >::parcelsToInject(), Foam::parseNASCoord(), Vector2D< scalar >::perp(), searchableCylinder::points(), quaternion::R(), fixedTrim::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), OFFsurfaceFormat< Face >::read(), STARCD::readPoints(), STARCDCore::readPoints(), general::sample(), RosinRammler::sample(), multiNormal::sample(), normal::sample(), liquidMixtureProperties::size(), ODESolver::solve(), triad::sortxyz(), SVD::SVD(), swapec(), targetCoeffTrim::thetag(), CV2D::toPoint2D(), tabulated6DoFMotion::transformation(), STARCDCoordinateRotation::transformVector(), triad::triad(), pointConstraint::unconstrainedDirections(), azizChen::unscaledEnergy(), LISAAtomization< CloudType >::update(), SHF< CloudType >::update(), KinematicLookupTableInjection< CloudType >::updateMesh(), ThermoLookupTableInjection< CloudType >::updateMesh(), ReactingLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), USERD_get_part_coords(), Polynomial< PolySize >::value(), polynomialFunction::value(), Tensor< scalar >::vectorComponent(), Relaxation< CloudType >::velocityCorrection(), block::vtxLabel(), while(), regionSizeDistribution::write(), dxSurfaceWriter::writeData(), adaptiveSolver::~adaptiveSolver(), ODESystem::~ODESystem(), RaviPetersen::~RaviPetersen(), and Stochastic< CloudType >::~Stochastic().