OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Scalar.H File Reference
Classes
class pTraits< Scalar >
Functions
word name (const Scalar)
Return a string representation of a Scalar.
Scalar & setComponent (Scalar &s, const direction)
Scalar component (const Scalar s, const direction)
Scalar sign (const Scalar s)
Scalar pos (const Scalar s)
Scalar neg (const Scalar s)
bool equal (const Scalar &s1, const Scalar &s2)
bool notEqual (const Scalar s1, const Scalar s2)
Scalar limit (const Scalar s1, const Scalar s2)
Scalar minMod (const Scalar s1, const Scalar s2)
Scalar magSqr (const Scalar s)
Scalar sqr (const Scalar s)
Scalar sqrtSumSqr (const Scalar a, const Scalar b)
Scalar pow3 (const Scalar s)
Scalar pow4 (const Scalar s)
Scalar pow5 (const Scalar s)
Scalar pow6 (const Scalar s)
Scalar pow025 (const Scalar s)
Scalar inv (const Scalar s)
Scalar dot (const Scalar s1, const Scalar s2)
Scalar cmptMultiply (const Scalar s1, const Scalar s2)
Scalar cmptDivide (const Scalar s1, const Scalar s2)
Scalar cmptMax (const Scalar s)
Scalar cmptMin (const Scalar s)
Scalar cmptAv (const Scalar s)
Scalar cmptMag (const Scalar s)
transFunc (sqrt) transFunc(cbrt) transFunc(exp) transFunc(log) transFunc(log10) transFunc(sin) transFunc(cos) transFunc(tan) transFunc(asin) transFunc(acos) transFunc(atan) transFunc(sinh) transFunc(cosh) transFunc(tanh) transFunc(asinh) transFunc(acosh) transFunc(atanh) transFunc(erf) transFunc(erfc) transFunc(lgamma) transFunc(j0) transFunc(j1) transFunc(y0) transFunc(y1) inline Scalar stabilise(const Scalar s
Istream & operator>> (Istream &, Scalar &)
Ostream & operator<< (Ostream &, const Scalar)
Variables
const Scalar small
Detailed Description
Original source file Scalar.H
Definition in file Scalar.H.
Function Documentation
name()
word name (const Scalar)
Return a string representation of a Scalar.
Definition at line 57 of file Scalar.C.
References Foam::readScalar(), and Scalar.
Referenced by adiabaticPerfectFluid< Specie >::adiabaticPerfectFluid(), KinematicCloud< Foam::DsmcCloud >::alpha(), Cloud< streamLineParticle >::autoMap(), Stochastic< CloudType >::calculate(), MeshedSurfaceProxy< Face >::canWriteType(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), chemistryModel< CompType, ThermoType >::chemistryModel(), KinematicCloud< Foam::DsmcCloud >::cloudReset(), coalCloudList::coalCloudList(), ZoneMesh< cellZone, polyMesh >::findIndex(), ZoneMesh< cellZone, polyMesh >::findIndices(), Time::findInstance(), ZoneMesh< cellZone, polyMesh >::findZoneID(), for(), forAll(), thermo< Thermo, Type >::heName(), icoPolynomial< Specie, PolySize >::icoPolynomial(), if(), incompressiblePerfectGas< Specie >::incompressiblePerfectGas(), KinematicCloud< Foam::DsmcCloud >::info(), uniformInterpolationTable< scalar >::interpolate(), uniformInterpolationTable< scalar >::interpolateLog10(), IOField< vector >::IOField(), IOList< labelList >::IOList(), STLASCIILexer::lex(), linear< Type >::linear(), LocalInteraction< CloudType >::LocalInteraction(), dimensioned< vector >::lookupOrAddToDict(), dimensioned< vector >::lookupOrDefault(), fvPatch::lookupPatchField(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), tetherPotential::New(), energyScalingFunction::New(), sixDoFRigidBodyMotionRestraint::New(), pairPotential::New(), sixDoFRigidBodyMotionConstraint::New(), polyMeshModifier::New(), fieldValue::New(), edgeMesh::New(), pointZone::New(), cellZone::New(), porosityModel::New(), UnsortedMeshedSurface< Face >::New(), coordinateSystem::New(), faceZone::New(), MeshedSurface< Foam::face >::New(), polyPatch::New(), GeometricField< vector, pointPatchField, pointMesh >::oldTime(), pTraits< Scalar >::operator Scalar &(), autoPtr< Foam::lduMatrix::solver >::operator()(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator()(), autoPtr< Foam::lduMatrix::solver >::operator->(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator->(), dimensioned< vector >::operator/=(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator=(), PtrList< MRFZone >::operator=(), PtrList< MRFZone >::operator[](), perfectFluid< Specie >::perfectFluid(), VoidFraction< CloudType >::preEvolve(), ParticleErosion< CloudType >::preEvolve(), ParticleTracks< CloudType >::preEvolve(), KinematicCloud< Foam::DsmcCloud >::preEvolve(), tmp< Foam::surfaceInterpolationScheme< GType > >::ptr(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), ReactingCloud< Foam::DsmcCloud >::ReactingCloud(), NamedEnum< directionType, 3 >::read(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), FTRsurfaceFormat< Face >::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), GeometricField< vector, pointPatchField, pointMesh >::relax(), PtrList< MRFZone >::reorder(), rhoConst< Specie >::rhoConst(), KinematicCloud< Foam::DsmcCloud >::rhoEff(), GeometricField< vector, pointPatchField, pointMesh >::select(), autoPtr< Foam::lduMatrix::solver >::set(), ThermoCloud< Foam::DsmcCloud >::setModels(), PtrList< MRFZone >::setSize(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), UnsortedMeshedSurface< Face >::sortedZones(), ReactingCloud< Foam::DsmcCloud >::Srho(), GeometricField< vector, pointPatchField, pointMesh >::storeOldTimes(), GeometricField< vector, pointPatchField, pointMesh >::storePrevIter(), MPPICCloud< Foam::DsmcCloud >::storeState(), CollidingCloud< Foam::DsmcCloud >::storeState(), SprayCloud< Foam::DsmcCloud >::storeState(), ReactingMultiphaseCloud< Foam::DsmcCloud >::storeState(), ReactingCloud< Foam::DsmcCloud >::storeState(), ThermoCloud< Foam::DsmcCloud >::storeState(), KinematicCloud< Foam::DsmcCloud >::storeState(), ReactingCloud< Foam::DsmcCloud >::SYi(), GeometricField< vector, pointPatchField, pointMesh >::T(), ThermoCloud< Foam::DsmcCloud >::ThermoCloud(), KinematicCloud< Foam::DsmcCloud >::theta(), tmp< Foam::surfaceInterpolationScheme< GType > >::tmp(), advectiveFvPatchField< Type >::updateCoeffs(), USERD_get_gold_variable_info(), KinematicCloud< Foam::DsmcCloud >::vDotSweep(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), AveragingMethod< Foam::Vector >::write(), MeshedSurfaceProxy< Face >::write(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), UnsortedMeshedSurface< Face >::write(), MeshedSurface< Foam::face >::write(), TableFile< Type >::writeData(), CSV< Type >::writeData(), ensightPart::writeHeader(), AMIMethod< SourcePatch, TargetPatch >::writeIntersectionOBJ(), GeometricField< vector, pointPatchField, pointMesh >::writeMinMax(), regIOobject::writeObject(), Cloud< streamLineParticle >::writePositions(), and gradScheme< Type >::~gradScheme().
setComponent()
Scalar& setComponent (Scalar & s, const direction) inline
Definition at line 99 of file Scalar.H.
References s().
component()
Scalar component (const Scalar s, const direction) inline
Definition at line 105 of file Scalar.H.
References s().
Referenced by fvMatrix< Type >::addBoundaryDiag(), correlationFunction< Type >::calculateCorrelationFunction(), SolverPerformance< Type >::checkSingularity(), FieldField< Foam::Field, LUType >::component(), Field< Foam::Vector2D >::component(), if(), FieldField< Foam::Field, LUType >::negate(), dimensioned< vector >::operator[](), and SolverPerformance< Type >::print().
sign()
Scalar sign (const Scalar s) inline
Definition at line 111 of file Scalar.H.
Referenced by if(), Foam::LUDecompose(), particle< Type >::movingTetLambda(), fvFieldDecomposer::processorSurfacePatchFieldDecomposer::processorSurfacePatchFieldDecomposer(), Foam::sumProd(), and particle< Type >::tetLambda().
pos()
Scalar pos (const Scalar s) inline
Definition at line 117 of file Scalar.H.
Referenced by PairCollisionRecord< Type >::accessed(), Cloud< streamLineParticle >::autoMap(), Foam::bound(), SprayParcel< ParcelType >::calcAtomization(), for(), if(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::inject(), Foam::sumProd(), ReactingCloud< Foam::DsmcCloud >::SYi(), TimePaths::TimePaths(), inletOutletFvPatchField< Type >::updateCoeffs(), outletInletFvPatchField< Type >::updateCoeffs(), uniformInletOutletFvPatchField< Type >::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), and while().
neg()
Scalar neg (const Scalar s) inline
Definition at line 123 of file Scalar.H.
Referenced by if(), Foam::sumProd(), and ReactingCloud< Foam::DsmcCloud >::SYi().
equal()
bool equal (const Scalar & s1, const Scalar & s2) inline
Definition at line 129 of file Scalar.H.
References Foam::mag(), and ScalarVSMALL.
Referenced by thermo< Thermo, Type >::Kc(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kx(), UILList< DLListBase, Foam::molecule >::operator==(), FixedList< bool, Foam::pTraits< Type >::nComponents >::operator==(), and UList< Foam::wordRe >::operator==().
notEqual()
bool notEqual (const Scalar s1, const Scalar s2) inline
Definition at line 135 of file Scalar.H.
References Foam::mag(), and ScalarVSMALL.
Referenced by janafThermo< EquationOfState >::operator+=(), janafThermo< EquationOfState >::operator-=(), and Foam::operator<<().
limit()
Scalar limit (const Scalar s1, const Scalar s2) inline
Definition at line 141 of file Scalar.H.
References Foam::mag().
Referenced by Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), and thermo< Thermo, Type >::thermo().
minMod()
Scalar minMod (const Scalar s1, const Scalar s2) inline
Definition at line 147 of file Scalar.H.
References Foam::mag().
magSqr()
Scalar magSqr (const Scalar s) inline
Definition at line 153 of file Scalar.H.
References s().
Referenced by enrichedPatch::calcEnrichedFaces(), Stochastic< CloudType >::calculate(), mapNearestAMI< SourcePatch, TargetPatch >::calculate(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkPointNearness(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), tetrahedron< Point, PointRef >::containmentSphere(), linearUpwindV< Type >::correction(), cellPointWeight::findTriangle(), for(), forAll(), treeDataPrimitivePatch< PatchType >::getVolumeType(), tetrahedron< Point, PointRef >::gradNiSquared(), if(), Foam::kShellMean(), Foam::matchPoints(), dimensioned< vector >::operator/=(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), while(), and LeastSquaresVectors< Stencil >::~LeastSquaresVectors().
sqr()
Scalar sqr (const Scalar s) inline
Definition at line 159 of file Scalar.H.
References s().
Referenced by SphereDragForce< CloudType >::calcCoupled(), ErgunWenYuDragForce< CloudType >::calcCoupled(), PlessisMasliyahDragForce< CloudType >::calcCoupled(), WenYuDragForce< CloudType >::calcCoupled(), NonSphereDragForce< CloudType >::calcCoupled(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), primitiveMeshTools::cellDeterminant(), primitiveMesh::checkEdgeLength(), TrajectoryCollision< CloudType >::collideParcels(), icoPolynomial< Specie, PolySize >::cpMcv(), laminar< BasicTurbulenceModel >::epsilon(), basicSymmetryPointPatchField< Type >::evaluate(), cyclicSlipPointPatchField< Type >::evaluate(), nonuniformTransformCyclicPointPatchField< Type >::evaluate(), basicSymmetryFvPatchField< Type >::evaluate(), symmetryPlaneFvPatchField< Type >::evaluate(), fixedNormalSlipFvPatchField< Type >::evaluate(), partialSlipFvPatchField< Type >::evaluate(), forAll(), geomDecomp::geomDecomp(), treeDataPrimitivePatch< PatchType >::getVolumeType(), tetrahedron< Point, PointRef >::gradNiGradNi(), if(), Foam::invariantII(), laminar< BasicTurbulenceModel >::k(), Foam::kShellIntegration(), Foam::LUDecompose(), Foam::matchPoints(), Moment< Type >::Moment(), particle< Type >::movingTetLambda(), LangmuirHinshelwoodReactionRate::operator()(), treeDataPrimitivePatch< PatchType >::findNearestOp::operator()(), dimensioned< vector >::operator/=(), treeDataPrimitivePatch< PatchType >::overlaps(), PairSpringSliderDashpot< CloudType >::PairSpringSliderDashpot(), ParticleErosion< CloudType >::postPatch(), pow3(), pow4(), pow6(), laminar< BasicTurbulenceModel >::R(), ThermoCloud< Foam::DsmcCloud >::setModels(), basicSymmetryFvPatchField< Type >::snGrad(), symmetryPlaneFvPatchField< Type >::snGrad(), fixedNormalSlipFvPatchField< Type >::snGrad(), partialSlipFvPatchField< Type >::snGrad(), sqrtSumSqr(), TAB< CloudType >::TAB(), BlobsSheetAtomization< CloudType >::update(), LISAAtomization< CloudType >::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot(), PengRobinsonGas< Specie >::Z(), and LeastSquaresVectors< Stencil >::~LeastSquaresVectors().
sqrtSumSqr()
Scalar sqrtSumSqr (const Scalar a, const Scalar b) inline
Definition at line 165 of file Scalar.H.
References Foam::mag(), Scalar, ScalarVSMALL, sqr(), and Foam::sqrt().
Referenced by SVD::SVD().
pow3()
Scalar pow3 (const Scalar s) inline
Definition at line 181 of file Scalar.H.
References sqr().
Referenced by SprayParcel< ParcelType >::calc(), PlessisMasliyahDragForce< CloudType >::calcCoupled(), pow6(), tetrahedron< Point, PointRef >::quality(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::setParcelProperties(), Foam::sumProd(), TAB< CloudType >::TAB(), LISAAtomization< CloudType >::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), CellZoneInjection< CloudType >::updateMesh(), and PengRobinsonGas< Specie >::Z().
pow4()
Scalar pow4 (const Scalar s) inline
Definition at line 187 of file Scalar.H.
References sqr().
Referenced by ETAB< CloudType >::ETAB(), MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField(), pow5(), ThermoCloud< Foam::DsmcCloud >::setModels(), Foam::sumProd(), and LISAAtomization< CloudType >::update().
pow5()
Scalar pow5 (const Scalar s) inline
Definition at line 193 of file Scalar.H.
References pow4().
Referenced by Foam::sumProd().
pow6()
Scalar pow6 (const Scalar s) inline
Definition at line 199 of file Scalar.H.
References pow3(), and sqr().
Referenced by Foam::sumProd().
pow025()
Scalar pow025 (const Scalar s) inline
Definition at line 205 of file Scalar.H.
References Foam::sqrt().
Referenced by PairSpringSliderDashpot< CloudType >::evaluatePair(), forAll(), and Foam::sumProd().
inv()
Scalar inv (const Scalar s) inline
Definition at line 211 of file Scalar.H.
References s().
Referenced by tetrahedron< Point, PointRef >::barycentric(), TDILUPreconditioner< Type, DType, LUType >::calcInvD(), DiagonalPreconditioner< Type, DType, LUType >::DiagonalPreconditioner(), if(), Dual< Type >::interpolateGrad(), Foam::inv(), Moment< Type >::Moment(), Foam::operator/(), TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother(), and LeastSquaresVectors< Stencil >::~LeastSquaresVectors().
dot()
Scalar dot (const Scalar s1, const Scalar s2) inline
Definition at line 217 of file Scalar.H.
Referenced by TDILUPreconditioner< Type, DType, LUType >::calcInvD(), TDILUPreconditioner< Type, DType, LUType >::precondition(), DiagonalPreconditioner< Type, DType, LUType >::precondition(), TDILUPreconditioner< Type, DType, LUType >::preconditionT(), and TGaussSeidelSmoother< Type, DType, LUType >::smooth().
cmptMultiply()
Scalar cmptMultiply (const Scalar s1, const Scalar s2) inline
Definition at line 223 of file Scalar.H.
Referenced by fvMatrix< Type >::addBoundarySource(), SolverPerformance< Type >::checkConvergence(), dimensioned< vector >::operator/=(), PCICG< Type, DType, LUType >::solve(), and PBiCICG< Type, DType, LUType >::solve().
cmptDivide()
Scalar cmptDivide (const Scalar s1, const Scalar s2) inline
Definition at line 229 of file Scalar.H.
Referenced by dimensioned< vector >::operator/=(), SmoothSolver< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), and PBiCCCG< Type, DType, LUType >::solve().
cmptMax()
Scalar cmptMax (const Scalar s) inline
Definition at line 235 of file Scalar.H.
References s().
Referenced by CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), and primitiveMesh::checkClosedBoundary().
cmptMin()
Scalar cmptMin (const Scalar s) inline
Definition at line 241 of file Scalar.H.
References s().
cmptAv()
Scalar cmptAv (const Scalar s) inline
Definition at line 247 of file Scalar.H.
References s().
Referenced by fvMatrix< Type >::addCmptAvBoundaryDiag().
cmptMag()
Scalar cmptMag (const Scalar s) inline
Definition at line 253 of file Scalar.H.
References Foam::acos(), Foam::acosh(), Foam::asin(), Foam::asinh(), Foam::atan(), Foam::atanh(), Foam::cbrt(), Foam::cos(), Foam::cosh(), Foam::erf(), Foam::erfc(), Foam::exp(), Foam::j0(), Foam::j1(), Foam::lgamma(), Foam::log(), Foam::log10(), Foam::mag(), s(), Scalar, Foam::sin(), Foam::sinh(), small, Foam::sqrt(), Foam::stabilise(), Foam::tan(), Foam::tanh(), transFunc(), Foam::y0(), and Foam::y1().
Referenced by CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), primitiveMeshTools::cellClosedness(), primitiveMesh::checkClosedBoundary(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), and LduMatrix< Type, DType, LUType >::sumMagOffDiag().
transFunc()
transFunc (sqrt) const
Referenced by cmptMag().
operator>>()
Istream& operator>> (Istream & , Scalar &)
Referenced by CompactListList< T, Container >::CompactListList(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), HashTable< Foam::phase *>::HashTable(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), and StaticHashTable< T, Key, Hash >::StaticHashTable().
operator<<()
Ostream& operator<< (Ostream & , const Scalar)
Variable Documentation
small
const Scalar small
Initial value:
{
    if (s >= 0)
    {
        return s + small;
    }
    else
    {
        return s - small;
    }
}
Scalar readScalar(Istream&)
Definition at line 293 of file Scalar.H.
Referenced by cmptMag().