OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
POSIX.C File Reference
POSIX versions of the functions declared in OSspecific.H.
Namespaces
Foam
Namespace for OpenFOAM.
Functions
defineTypeNameAndDebug (POSIX, 0)
static int collectLibsCallback (struct dl_phdr_info *info, size_t size, void *data)
Detailed Description
POSIX versions of the functions declared in OSspecific.H.
Original source file POSIX.C
Definition in file POSIX.C.
Function Documentation
collectLibsCallback()
static int collectLibsCallback (struct dl_phdr_info * info, size_t size, void * data) static
Definition at line 1264 of file POSIX.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append().
Referenced by Foam::dlLoaded(), and Foam::dlSymFound().