OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
postCalc.C File Reference
Generic wrapper for calculating a quantity at each time.
Namespaces
Foam
Namespace for OpenFOAM.
Functions
void tryCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
int main (int argc, char *argv[])
Detailed Description
Generic wrapper for calculating a quantity at each time.
Original source file postCalc.C
Definition in file postCalc.C.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 54 of file postCalc.C.
References argList::addBoolOption(), timeSelector::addOptions(), args, Foam::endl(), forAll, Foam::Info, mesh, fvMesh::readUpdate(), timeSelector::select0(), timeDirs, and Foam::tryCalc().