OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nonLinearWallFunctionsI.H File Reference
Calculate wall generation and dissipation from wall-functions for non-linear models.
Functions
forAll (patches, patchi)
Initialise the near-wall G and epsilon fields to zero.
const volScalarField nuLam (this->nu())
Variables
scalar yPlusLam
const fvPatchList & patches = mesh_.boundary()
Detailed Description
Calculate wall generation and dissipation from wall-functions for non-linear models.
Original source file nonLinearWallFunctionsI.H
Definition in file nonLinearWallFunctionsI.H.
Function Documentation
forAll()
forAll (patches , patchi)
Initialise the near-wall G and epsilon fields to zero.
Accumulate the wall face contributions to epsilon and G.
Increment cellBoundaryFaceCount for each face for averaging
using local Cmu !
Definition at line 42 of file nonLinearWallFunctionsI.H.
References Cmu75, Foam::constant::universal::G, Foam::mag(), nu, nuLam(), patchi, Foam::pow(), pow025(), scalarField(), Foam::sqrt(), and yPlus.
nuLam()
const volScalarField nuLam (this-> nu())
Referenced by forAll().
Variable Documentation
yPlusLam
scalar yPlusLam
Initial value:
= nutkWallFunctionFvPatchScalarField::yPlusLam
    (
        kappa_.value(),
        E_.value()
    )
Definition at line 33 of file nonLinearWallFunctionsI.H.
patches
const fvPatchList& patches = mesh_.boundary()
Definition at line 39 of file nonLinearWallFunctionsI.H.
Referenced by isoSurface::adaptPatchFields(), fvMeshAdder::add(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), decompositionMethod::calcCellCells(), cellToFaceStencil::calcFaceStencil(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), polyMeshGeometry::checkVolRatio(), reflectionVectors::correct(), LRR::correct(), LaunderGibsonRSTM::correct(), meshRefinement::createZoneBaffles(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), localPointRegion::findDuplicateFacePairs(), polyMeshTetDecomposition::findFaceBasePts(), fvBoundaryMesh::findPatchID(), polyBoundaryMesh::findPatchID(), forAll(), FreeStream< CloudType >::FreeStream(), fvBoundaryMeshMapper::fvBoundaryMeshMapper(), removeCells::getExposedFaces(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), particle< Type >::hitWallFaces(), localPointRegion::localPointRegion(), meshRefinement::makePatch(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFacesUndo(), meshRefinement::meshedPatches(), fvMesh::movePoints(), NamedEnum< directionType, 3 >::names(), polyBoundaryMesh::names(), ensightMesh::nFacePrimitives::nFacePrimitives(), nearestEqOp::operator()(), polyBoundaryMesh::physicalTypes(), pointBoundaryMeshMapper::pointBoundaryMeshMapper(), polyBoundaryMesh::polyBoundaryMesh(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), polyBoundaryMesh::reorder(), patchProbes::sample(), motionSmootherAlgo::scaleMesh(), meshRefinement::selectSeparatedCoupledFaces(), decompositionMethod::setConstraints(), polyBoundaryMesh::setGroup(), duplicatePoints::setRefinement(), removeCells::setRefinement(), perfectInterface::setRefinement(), removeFaces::setRefinement(), surfacePatchIOList::surfacePatchIOList(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), meshRefinement::testSyncBoundaryFaceList(), particle< Type >::trackToFace(), polyBoundaryMesh::types(), motionSmootherAlgo::updateMesh(), cellToFaceStencil::validBoundaryFaces(), cellToCellStencil::validBoundaryFaces(), polyBoundaryMesh::writeData(), meshRefinement::zonify(), and repatchPolyTopoChanger::~repatchPolyTopoChanger().