OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallNonlinearViscosityI.H File Reference
Calculate wall viscosity for non-linear models.
Functions
const volScalarField nuLam (this->nu())
forAll (patches, patchi)
Variables
const scalar yPlusLam
Detailed Description
Calculate wall viscosity for non-linear models.
Original source file wallNonlinearViscosityI.H
Definition in file wallNonlinearViscosityI.H.
Function Documentation
nuLam()
const volScalarField nuLam (this-> nu())
Referenced by forAll().
forAll()
forAll (patches , patchi)
Using local Cmu
Definition at line 40 of file wallNonlinearViscosityI.H.
References Foam::log(), nuLam(), patchi, pow025(), scalarField(), Foam::sqrt(), and yPlus.
Variable Documentation
yPlusLam
const scalar yPlusLam
Initial value:
= nutkWallFunctionFvPatchScalarField::yPlusLam
    (
        kappa_.value(),
        E_.value()
    )
Definition at line 32 of file wallNonlinearViscosityI.H.