OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LienLeschzinerLowReSetWallDissipation.H File Reference
Functions
forAll (patches, patchi)
Initialise the near-wall epsilon field to zero.
Variables
scalar Cmu75 = pow(Cmu_.value(), 0.75)
use constant Cmu for epsilon in the near-wall cell
const fvPatchList & patches = mesh_.boundary()
Function Documentation
forAll()
forAll (patches , patchi)
Initialise the near-wall epsilon field to zero.
Definition at line 13 of file LienLeschzinerLowReSetWallDissipation.H.
References Foam::exp(), patchi, Foam::pow(), and sqr().
Variable Documentation
Cmu75
scalar Cmu75 = pow(Cmu_.value(), 0.75)
use constant Cmu for epsilon in the near-wall cell
Definition at line 8 of file LienLeschzinerLowReSetWallDissipation.H.
patches
const fvPatchList& patches = mesh_.boundary()
Definition at line 10 of file LienLeschzinerLowReSetWallDissipation.H.