OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
getPatchFieldVector.H File Reference
Functions
if (nVar >=Num_variables - nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
if (!fieldObjectPtr.headerOk())
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volVectorField sf (fieldObject, mesh)
if (which_type==Z_TRI03)
Variables
label patchi = which_part - 2
const vectorField & sfb = sf.boundaryField()[patchi]
const polyBoundaryMesh & bMesh = meshPtr->boundaryMesh()
Function Documentation
if() [1/3]
if (nVar >=Num_variables - nSprayVariables)
Definition at line 3 of file getPatchFieldVector.H.
References fieldNames, fieldObjectPtr(), mesh, nVar, and var2field.
fieldObjectPtr()
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
Referenced by if().
if() [2/3]
if (!fieldObjectPtr. headerOk())
Definition at line 16 of file getPatchFieldVector.H.
References fieldNames, fieldObject(), mesh, sf(), and var2field.
fieldObject()
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by if().
sf()
volVectorField sf (fieldObject , mesh)
Referenced by if().
if() [3/3]
if (which_type = = Z_TRI03)
Definition at line 39 of file getPatchFieldVector.H.
References component(), forAll, nPoints, and patchi.
Variable Documentation
patchi
label patchi = which_part - 2
Definition at line 1 of file getPatchFieldVector.H.
Referenced by if().
sfb
const vectorField& sfb = sf.boundaryField()[patchi]
Definition at line 36 of file getPatchFieldVector.H.
bMesh
const polyBoundaryMesh& bMesh = meshPtr->boundaryMesh()
Definition at line 37 of file getPatchFieldVector.H.