OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
USERD_get_var_value_at_specific.H File Reference
Functions
int USERD_get_var_value_at_specific (int which_var, int which_node_or_elem, int which_part, int which_elem_type, int time_step, float values[3], int imag_data)
Function Documentation
USERD_get_var_value_at_specific()
int USERD_get_var_value_at_specific (int which_var, int which_node_or_elem, int which_part, int which_elem_type, int time_step, float values[3], int imag_data)
Definition at line 3 of file USERD_get_var_value_at_specific.H.
References Foam::endl(), fieldNames, fieldObject(), Foam::flush(), Foam::Info, isScalar, isVector, mesh, meshPtr, nSprayVariables, Num_variables, nVar, runTimePtr, scalarField(), var2field, and vectorField().