OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
YEEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,Yi_h)")))
combustion correct ()
volScalarField Yt (0.0 *Y[0])
forAll (Y, i)
Y [inertIndex] max (0.0)
fvScalarMatrix EEqn (fvm::ddt(rho, he)+mvConvection->fvmDiv(phi, he)+fvc::ddt(rho, K)+fvc::div(phi, K)+(he.name()=="e" ? fvc::div(fvc::absolute(phi/fvc::interpolate(rho), U), p, "div(phiv,p)") :-dpdt) - fvm::laplacian(turbulence->alphaEff(), he)==combustion->Sh()+radiation->Sh(thermo)+parcels.Sh(he)+surfaceFilm.Sh()+fvOptions(rho, he))
EEqn relax ()
fvOptions constrain (EEqn)
EEqn solve ()
fvOptions correct (he)
Variables
dQ = combustion->dQ()
label inertIndex = -1
Y [inertIndex] = scalar(1) - Yt
volScalarField & he = thermo.he()
Function Documentation
mvConvection()
tmp<fv::convectionScheme<scalar> > mvConvection (fv::convectionScheme< scalar > ::Newmesh, fields, phi, mesh.divScheme("div(phi,Yi_h)"))
Referenced by transport::correct(), forAll(), and if().
correct() [1/2]
combustion correct ()
Yt()
volScalarField Yt (0.0 * Y[0])
Referenced by forAll(), and reactingOneDim::solveSpeciesMass().
forAll()
forAll (Y , i)
Definition at line 18 of file YEEqn.H.
References combustion(), Foam::fvc::ddt(), fvOptions, inertSpecie(), Foam::fvc::laplacian(), mesh, mvConvection(), name(), phi, rho, surfaceFilm, turbulence, Y, and Yt().
max()
Y [inertIndex] max (0. 0)
EEqn()
fvScalarMatrix EEqn (fvm::ddt(rho, he)+mvConvection->fvmDiv(phi, he)+fvc::ddt(rho, K)+fvc::div(phi, K)+(he.name()=="e" ? fvc::div(fvc::absolute(phi/fvc::interpolate(rho), U), p, "div(phiv,p)") :-dpdt) - fvm::laplacian(turbulence->alphaEff(), he) = =combustion->Sh()+radiation->Sh(thermo)+parcels.Sh(he)+surfaceFilm.Sh()+fvOptions(rho, he))
relax()
EEqn relax ()
constrain()
fvOptions constrain (EEqn)
solve()
EEqn solve ()
correct() [2/2]
fvOptions correct (he)
Variable Documentation
dQ
dQ = combustion->dQ()
Definition at line 14 of file YEEqn.H.
Referenced by singleStepCombustion< CombThermoType, ThermoType >::dQ(), solidChemistryModel< CompType, SolidThermo >::dQ(), chemistryModel< CompType, ThermoType >::dQ(), greyMeanAbsorptionEmission::ECont(), and wideBandAbsorptionEmission::ECont().
inertIndex
label inertIndex = -1
Definition at line 15 of file YEEqn.H.
Y
Y[inertIndex] = scalar(1) - Yt
Definition at line 53 of file YEEqn.H.
Referenced by forAll().
he
volScalarField& he = thermo.he()
Definition at line 56 of file YEEqn.H.
Referenced by interRegionHeatTransferModel::addSup(), heThermo< BasicSolidThermo, MixtureType >::he(), thermo< Thermo, Type >::he(), heThermo< BasicSolidThermo, MixtureType >::heBoundaryCorrection(), basicThermo::lookupThermo(), radiationModel::Sh(), basicThermo::validate(), and temperatureLimitsConstraint::~temperatureLimitsConstraint().