OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readInitialConditions.H File Reference
Functions
word constProp (initialConditions.lookup("constantProperty"))
if ((constProp !="pressure") &&(constProp !="volume"))
word fractionBasis (initialConditions.lookup("fractionBasis"))
if ((fractionBasis !="mass") &&(fractionBasis !="mole"))
PtrList< gasHThermoPhysics > specieData (Y.size())
forAll (specieData, i)
scalarList Y0 (nSpecie, 0.0)
scalarList X0 (nSpecie, 0.0)
dictionary fractions (initialConditions.subDict("fractions"))
if (fractionBasis=="mole")
forAll (Y, i)
thermo he ()
thermo correct ()
Variables
label nSpecie = Y.size()
else
const scalar mTot = sum(Y0)
const scalar mw = 1.0/invW
scalar h0 = 0.0
rho = thermo.rho()
scalar rho0 = rho[0]
scalar u0 = h0 - p0/rho0
scalar R0 = p0/(rho0*T0)
Rspecific [0] = R0
scalar integratedHeat = 0.0
Function Documentation
constProp()
word constProp (initialConditions. lookup"constantProperty")
Referenced by if().
if() [1/3]
if ((constProp !="pressure") &&(constProp !="volume"))
Definition at line 2 of file readInitialConditions.H.
References Foam::abort(), constProp(), Foam::FatalError, fractionBasis(), and Foam::nl.
fractionBasis()
word fractionBasis (initialConditions. lookup"fractionBasis")
Referenced by if().
if() [2/3]
if ((fractionBasis !="mass") &&(fractionBasis !="mole"))
Definition at line 10 of file readInitialConditions.H.
References Foam::abort(), Foam::FatalError, fractionBasis(), and Foam::nl.
specieData()
PtrList<gasHThermoPhysics> specieData (Y. size())
Referenced by forAll(), and if().
forAll() [1/2]
forAll (specieData , i)
Definition at line 19 of file readInitialConditions.H.
References fractions(), specieData(), thermo, X0(), and Y0().
Referenced by if().
Y0()
scalarList Y0 (nSpecie , 0. 0)
Referenced by SprayParcel< ParcelType >::calc(), and forAll().
X0()
scalarList X0 (nSpecie , 0. 0)
Referenced by SprayParcel< ParcelType >::calc(), and forAll().
fractions()
dictionary fractions (initialConditions. subDict"fractions")
Referenced by forAll(), and if().
if() [3/3]
if (fractionBasis = = "mole")
Definition at line 36 of file readInitialConditions.H.
References forAll(), fractions(), mTot, mw, name(), readScalar, specieData(), Foam::sum(), and Y.
forAll() [2/2]
forAll (Y , i)
Definition at line 73 of file readInitialConditions.H.
References mTot, and specieData().
he()
thermo he ()
correct()
thermo correct ()
Variable Documentation
nSpecie
label nSpecie = Y.size()
Definition at line 17 of file readInitialConditions.H.
Referenced by chemistryModel< CompType, ThermoType >::jacobian(), ode< ChemistryModel >::solve(), and EulerImplicit< ChemistryModel >::solve().
else
else
Initial value:
{
        forAll(Y, i)
        {
            const word& name = Y[i].name();
            if (fractions.found(name))
            {
                Y0[i] = readScalar(fractions.lookup(name));
            }
        }
        scalar invW = 0.0
Definition at line 61 of file readInitialConditions.H.
mTot
const scalar mTot = sum(Y0)
Definition at line 72 of file readInitialConditions.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), forAll(), and if().
mw
const scalar mw = 1.0/invW
Definition at line 78 of file readInitialConditions.H.
Referenced by if().
h0
scalar h0 = 0.0
Definition at line 86 of file readInitialConditions.H.
rho
thermo rho = thermo.rho()
Definition at line 96 of file readInitialConditions.H.
Referenced by effectivenessHeatExchangerSource::addSup(), GenSGSStress::B(), CoBlended< Type >::blendingFactor(), Implicit< CloudType >::cacheFields(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), forces::calcForcesMoment(), ThermoParcel< ParcelType >::calcHeatTransfer(), mutURoughWallFunctionFvPatchScalarField::calcMut(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), NoAtomization< CloudType >::clone(), NoBreakup< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), exponential::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), AtomizationModel< Foam::SprayCloud< Foam::DsmcCloud > >::clone(), ETAB< CloudType >::clone(), Lun::clone(), PilchErdman< CloudType >::clone(), TAB< CloudType >::clone(), LISAAtomization< CloudType >::clone(), HarrisCrighton::clone(), SHF< CloudType >::clone(), ReactingCloud< Foam::DsmcCloud >::cloneBare(), KinematicCloud< Foam::DsmcCloud >::cloudReset(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), patchInjection::correct(), PaSR< Type >::correct(), relaxation::correct(), drippingInjection::correct(), curvatureSeparation::correct(), fixedCoeff::correct(), standardPhaseChange::correctModel(), Foam::fvc::ddt(), chemistryModel< CompType, ThermoType >::derivatives(), forces::devRhoReff(), actuationDiskSource::diskArea(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), thermo< Thermo, Type >::ea(), LamBremhorstKE::epsilon(), LienLeschzinerLowRe::epsilon(), LienCubicKE::epsilon(), NonlinearKEShih::epsilon(), kEpsilon::epsilon(), RNGkEpsilon::epsilon(), kOmega::epsilon(), realizableKE::epsilon(), LienCubicKELowRe::epsilon(), kOmegaSST::epsilon(), kkLOmega::epsilon(), thermo< Thermo, Type >::es(), Peclet::execute(), CourantNo::execute(), scalarTransport::execute(), v2f::f(), PatchFlowRateInjection< CloudType >::flowRate(), forAll(), if(), Foam::MULES::implicitSolve(), LaunderSharmaKE::k(), PhiScheme< Type, PhiLimiter >::limiter(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), ddtScheme< Type >::mesh(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), forces::mu(), turbulenceModel::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), turbulenceModel::nu(), laminar::nuEff(), mixedSmagorinsky::nuSgs(), GenEddyVisc::nuSgs(), SpalartAllmaras::nuSgs(), kOmegaSSTSAS::nuSgs(), SpalartAllmaras::nut(), CrankNicolsonDdtScheme< Type >::ocCoeff(), rhoMagSqr< Type >::operator()(), porosityModel::iNew::operator()(), option::iNew::operator()(), LRR::R(), LaunderGibsonRSTM::R(), KinematicParcel< ParcelType >::readFields(), InjectionModel< CloudType >::setNumberOfParticles(), ConeNozzleInjection< CloudType >::setProperties(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), chemistryModel< CompType, ThermoType >::solve(), SprayParcel< ParcelType >::solveTABEq(), BreakupModel< Foam::SprayCloud< Foam::DsmcCloud > >::TABWeCrit(), chemistryModel< CompType, ThermoType >::tc(), porosityModel::transformModelData(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), LISAAtomization< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), while(), KinematicParcel< ParcelType >::writeFields(), qZeta::zeta(), explicitPorositySource::~explicitPorositySource(), interRegionExplicitPorositySource::~interRegionExplicitPorositySource(), laminar::~laminar(), MRFSource::~MRFSource(), optionList::~optionList(), scaleSimilarity::~scaleSimilarity(), and Smagorinsky2::~Smagorinsky2().
rho0
scalar rho0 = rho[0]
Definition at line 97 of file readInitialConditions.H.
Referenced by SprayParcel< ParcelType >::calc().
u0
scalar u0 = h0 - p0/rho0
Definition at line 98 of file readInitialConditions.H.
Referenced by if(), and triangleFuncs::intersectAxesBundle().
R0
scalar R0 = p0/(rho0*T0)
Definition at line 99 of file readInitialConditions.H.
Rspecific
Rspecific[0] = R0
Definition at line 100 of file readInitialConditions.H.
Referenced by if().
integratedHeat
scalar integratedHeat = 0.0
Definition at line 102 of file readInitialConditions.H.
Referenced by if().