OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
evaluateNearWall.H File Reference
Variables
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Universal gas constant: default SI units: [J/mol/K].
scalar epsilon = turbulence->epsilon()()[cellId]
scalar k = turbulence->k()()[cellId]
Boltzmann constant.
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
scalar tauw = flowDirection & R & wallNormal
scalar uTau = ::sqrt(mag(tauw))
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
scalar uPlus = magUp/(uTau + ROOTVSMALL)
scalar nutPlus = nut/nu
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
scalar Rey = magUp*y[cellId]/nu
Variable Documentation
nut
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
Definition at line 5 of file evaluateNearWall.H.
Referenced by Foam::incompressible::autoCreateLowReNut(), Foam::incompressible::autoCreateNut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), incompressibleTurbulenceModel::mut(), LESModel< BasicTurbulenceModel >::nuEff(), and RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::nuEff().
R
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Universal gas constant: default SI units: [J/mol/K].
Definition at line 6 of file evaluateNearWall.H.
epsilon
scalar epsilon = turbulence->epsilon()()[cellId]
Definition at line 7 of file evaluateNearWall.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::ap(), atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), ThermoParcel< ParcelType >::calcHeatTransfer(), PaSR< Type >::correct(), ThermoCloud< Foam::DsmcCloud >::Ep(), if(), turbulenceModel::rhoEpsilonEff(), ThermoCloud< Foam::DsmcCloud >::sigmap(), StochasticDispersionRAS< CloudType >::update(), GradientDispersionRAS< CloudType >::update(), fWallFunctionFvPatchScalarField::updateCoeffs(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
k
scalar k = turbulence->k()()[cellId]
Boltzmann constant.
Definition at line 9 of file evaluateNearWall.H.
Referenced by MaxwellianThermal< CloudType >::correct(), DsmcCloud< DsmcParcel< ParcelType > >::equipartitionInternalEnergy(), DsmcCloud< DsmcParcel< ParcelType > >::equipartitionLinearVelocity(), FreeStream< CloudType >::inflow(), DsmcCloud< DsmcParcel< ParcelType > >::maxwellianAverageSpeed(), DsmcCloud< DsmcParcel< ParcelType > >::maxwellianMostProbableSpeed(), DsmcCloud< DsmcParcel< ParcelType > >::maxwellianRMSSpeed(), VariableHardSphere< CloudType >::sigmaTcR(), LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR(), and dsmcFields::write().
magUp
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
Definition at line 10 of file evaluateNearWall.H.
Referenced by mutUWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::calcMut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutUWallFunctionFvPatchScalarField::yPlus(), mutUWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), mutURoughWallFunctionFvPatchScalarField::yPlus(), and nutURoughWallFunctionFvPatchScalarField::yPlus().
tauw
scalar tauw = flowDirection & R & wallNormal
Definition at line 12 of file evaluateNearWall.H.
Referenced by LRR::correct(), and LaunderGibsonRSTM::correct().
uTau
scalar uTau = ::sqrt(mag(tauw))
Definition at line 14 of file evaluateNearWall.H.
Referenced by mutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
yPlus
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
Definition at line 16 of file evaluateNearWall.H.
Referenced by epsilonLowReWallFunctionFvPatchScalarField::calculate(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), mutUWallFunctionFvPatchScalarField::calcYPlus(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), forAll(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
uPlus
scalar uPlus = magUp/(uTau + ROOTVSMALL)
Definition at line 18 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus().
nutPlus
scalar nutPlus = nut/nu
Definition at line 20 of file evaluateNearWall.H.
kPlus
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
Definition at line 22 of file evaluateNearWall.H.
epsilonPlus
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
Definition at line 24 of file evaluateNearWall.H.
Rey
scalar Rey = magUp*y[cellId]/nu
Definition at line 28 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::yPlus().