OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRegionSolidFields.H File Reference
Functions
if (!thermo.isotropic())
Variables
fvMesh & mesh = solidRegions[i]
solidThermo & thermo = thermos[i]
const radiation::radiationModel & radiation = radiations[i]
tmp< volScalarField > trho = thermo.rho()
const volScalarField & rho = trho()
tmp< volScalarField > tcp = thermo.Cp()
const volScalarField & cp = tcp()
tmp< volSymmTensorField > taniAlpha
volScalarField & h = thermo.he()
Planck constant.
const volScalarField & betav = betavSolid[i]
fv::IOoptionList & fvOptions = solidHeatSources[i]
Function Documentation
if()
if (!thermo. isotropic())
Definition at line 12 of file setRegionSolidFields.H.
References aniAlphas(), coordinates(), cp, and thermo.
Variable Documentation
mesh
fvMesh& mesh = solidRegions[i]
Definition at line 1 of file setRegionSolidFields.H.
thermo
solidThermo& thermo = thermos[i]
Definition at line 2 of file setRegionSolidFields.H.
Referenced by if().
radiation
const radiation::radiationModel& radiation = radiations[i]
Definition at line 3 of file setRegionSolidFields.H.
Referenced by radiationCoupledBase::emissivity(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::write(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::write(), and greyDiffusiveRadiationMixedFvPatchScalarField::write().
trho
tmp<volScalarField> trho = thermo.rho()
Definition at line 5 of file setRegionSolidFields.H.
Referenced by PaSR< Type >::correct(), forAll(), liquidFilmThermo::rho(), and constantFilmThermo::rho().
rho
const volScalarField& rho = trho()
Definition at line 6 of file setRegionSolidFields.H.
tcp
tmp<volScalarField> tcp = thermo.Cp()
Definition at line 8 of file setRegionSolidFields.H.
Referenced by forAll().
cp
const volScalarField& cp = tcp()
Definition at line 9 of file setRegionSolidFields.H.
Referenced by heThermo< BasicSolidThermo, MixtureType >::Cp(), thermo< Thermo, Type >::Cp(), thermo< Thermo, Type >::cv(), chemistryModel< CompType, ThermoType >::derivatives(), forAll(), thermo< Thermo, Type >::gamma(), if(), triangle< Point, PointRef >::nearestPointClassify(), fvFieldReconstructor::reconstructFvSurfaceField(), and fvFieldReconstructor::reconstructFvVolumeField().
taniAlpha
tmp<volSymmTensorField> taniAlpha
Definition at line 11 of file setRegionSolidFields.H.
Referenced by if().
h
volScalarField& h = thermo.he()
Planck constant.
Definition at line 29 of file setRegionSolidFields.H.
Referenced by basicThermo::dpdt(), normal::erfInv(), twoPhaseMixtureThermo::he(), multiphaseMixtureThermo::he(), if(), SIBS::solve(), SVD::SVD(), and LISAAtomization< CloudType >::update().
betav
const volScalarField& betav = betavSolid[i]
Definition at line 31 of file setRegionSolidFields.H.
Referenced by if(), and while().
fvOptions
fv::IOoptionList& fvOptions = solidHeatSources[i]
Definition at line 33 of file setRegionSolidFields.H.