OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setAlphaEff.H File Reference
Functions
IOobject turbulenceHeader ("turbulenceProperties", runTime.constant(), mesh, IOobject::MUST_READ)
IOobject RASHeader ("RASProperties", runTime.constant(), mesh, IOobject::MUST_READ)
IOobject LESHeader ("LESProperties", runTime.constant(), mesh, IOobject::MUST_READ)
if (turbulenceHeader.headerOk())
else if (RASHeader.headerOk())
else if (LESHeader.headerOk())
Variables
Info<< "Creating turbulence model\"<< endl;tmp< volScalarField > talphaEff
else
const volScalarField & alphaEff = talphaEff()
Function Documentation
turbulenceHeader()
IOobject turbulenceHeader ("turbulenceProperties" , runTime. constant(), mesh , IOobject::MUST_READ)
RASHeader()
IOobject RASHeader ("RASProperties" , runTime. constant(), mesh , IOobject::MUST_READ)
LESHeader()
IOobject LESHeader ("LESProperties" , runTime. constant(), mesh , IOobject::MUST_READ)
if() [1/3]
if (turbulenceHeader. headerOk())
Definition at line 28 of file setAlphaEff.H.
References phi, rho, talphaEff, thermo, turbulence, and U.
if() [2/3]
else if (RASHeader. headerOk())
Definition at line 43 of file setAlphaEff.H.
References phi, rho, talphaEff, thermo, turbulence, and U.
if() [3/3]
else if (LESHeader. headerOk())
Definition at line 58 of file setAlphaEff.H.
References phi, rho, talphaEff, thermo, turbulence, and U.
Variable Documentation
talphaEff
Info<< "Creating turbulence model\n" << endl; tmp<volScalarField> talphaEff
Definition at line 2 of file setAlphaEff.H.
Referenced by if().
else
else
Initial value:
{
        talphaEff = tmp<volScalarField>
        (
            new volScalarField
            (
                IOobject
                (
                    "alphaEff",
                    runTime.timeName(),
                    mesh,
                    IOobject::NO_READ,
                    IOobject::NO_WRITE
                ),
                mesh,
                dimensionedScalar("0", dimMass/dimLength/dimTime, 0.0)
            )
        )
Definition at line 74 of file setAlphaEff.H.
alphaEff
const volScalarField& alphaEff = talphaEff()
Definition at line 93 of file setAlphaEff.H.
Referenced by heThermo< BasicSolidThermo, MixtureType >::alphaEff(), rotorDiskSource::calculate(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().