OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readMechanicalProperties.H File Reference
Functions
IOobject rhoIO ("rho", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
if (rhoType=="uniform")
const dictionary & EDict (mechanicalProperties.subDict("E"))
word EType (EDict.lookup("type"))
IOobject EHeader ("E", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
if (EType=="uniform")
IOobject nuIO ("nu", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & nuDict (mechanicalProperties.subDict("nu"))
word nuType (nuDict.lookup("type"))
if (nuType=="uniform")
Variables
Info<< "Reading mechanical properties\"<< endl;IOdictionary mechanicalProperties(IOobject("mechanicalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));const dictionary &rhoDict(mechanicalProperties.subDict("rho"));word rhoType(rhoDict.lookup("type"));autoPtr< volScalarField > rhoPtr
else
volScalarField & rho = rhoPtr()
autoPtr< volScalarField > EPtr
volScalarField & rhoE = EPtr()
autoPtr< volScalarField > nuPtr
volScalarField & nu = nuPtr()
Function Documentation
rhoIO()
IOobject rhoIO ("rho" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
if() [1/3]
else if (rhoType = = "uniform")
Definition at line 29 of file readMechanicalProperties.H.
References Foam::dimMass, Foam::dimVolume, mesh, readScalar, and rhoIO().
EDict()
const dictionary& EDict (mechanicalProperties. subDict"E")
Referenced by if().
EType()
word EType (EDict. lookup"type")
Referenced by if().
EHeader()
IOobject EHeader ("E" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
if() [2/3]
else if (EType = = "uniform")
Definition at line 87 of file readMechanicalProperties.H.
References Foam::abort(), Foam::dimLength, Foam::dimMass, Foam::dimTime, EDict(), EHeader(), EType(), Foam::FatalError, FatalErrorIn, mesh, readScalar, and sqr().
nuIO()
IOobject nuIO ("nu" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
nuDict()
const dictionary& nuDict (mechanicalProperties. subDict"nu")
Referenced by if().
nuType()
word nuType (nuDict. lookup"type")
Referenced by if().
if() [3/3]
else if (nuType = = "uniform")
Definition at line 145 of file readMechanicalProperties.H.
References Foam::abort(), Foam::dimless, Foam::FatalError, FatalErrorIn, mesh, nuDict(), nuIO(), nuType(), and readScalar.
Variable Documentation
rhoPtr
Info<< "Reading mechanical properties\n" << endl; IOdictionary mechanicalProperties (IOobject ("mechanicalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); const dictionary& rhoDict(mechanicalProperties.subDict("rho")); word rhoType(rhoDict.lookup("type")); autoPtr<volScalarField> rhoPtr
Definition at line 18 of file readMechanicalProperties.H.
else
else
Initial value:
{
        FatalErrorIn
        (
            "readMechanicalProperties.H"
        )   << "Valid type entries are uniform or field for rho"
            << abort(FatalError)
Definition at line 63 of file readMechanicalProperties.H.
rho
volScalarField& rho = rhoPtr()
Definition at line 71 of file readMechanicalProperties.H.
EPtr
autoPtr<volScalarField> EPtr
Definition at line 76 of file readMechanicalProperties.H.
rhoE
volScalarField& rhoE = EPtr()
Definition at line 129 of file readMechanicalProperties.H.
Referenced by if().
nuPtr
autoPtr<volScalarField> nuPtr
Definition at line 131 of file readMechanicalProperties.H.
nu
volScalarField& nu = nuPtr()
Definition at line 185 of file readMechanicalProperties.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), NoPhaseChange< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), PhaseChangeModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), ORourkeCollision< CloudType >::collideParcels(), DarcyForchheimer::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::DepsilonEff(), forces::devRhoReff(), kEqn< BasicTurbulenceModel >::DkEff(), kEpsilon< BasicTurbulenceModel >::DkEff(), forAll(), solidParticleCloud::move(), incompressibleTurbulenceModel::mu(), forces::mu(), laminar< BasicTurbulenceModel >::nuEff(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::nuEff(), PairSpringSliderDashpot< CloudType >::PairSpringSliderDashpot(), multiNormal::sample(), LISAAtomization< CloudType >::update(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().