OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::debug Namespace Reference
Namespace for handling debugging switches.
Functions
dictionary & controlDict ()
The central control dictionary.
dictionary & debugSwitches ()
The DebugSwitches sub-dictionary in the central controlDict.
dictionary & infoSwitches ()
The InfoSwitches sub-dictionary in the central controlDict.
dictionary & optimisationSwitches ()
The OptimisationSwitches sub-dictionary in the central controlDict.
int debugSwitch (const char *name, const int defaultValue=0)
Lookup debug switch or add default value.
int infoSwitch (const char *name, const int defaultValue=0)
Lookup info switch or add default value.
int optimisationSwitch (const char *name, const int defaultValue=0)
Lookup optimisation switch or add default value.
dictionary & switchSet (const char *subDictName, dictionary *&subDictPtr)
Internal function to lookup a sub-dictionary from controlDict.
void addDebugObject (const char *name, simpleRegIOobject *obj)
Register debug switch read/write object.
void addInfoObject (const char *name, simpleRegIOobject *obj)
Register info switch read/write object.
void addOptimisationObject (const char *name, simpleRegIOobject *obj)
Register optimisation switch read/write object.
void addDimensionSetObject (const char *name, simpleRegIOobject *obj)
Register DimensionSets read/write object.
void addDimensionedConstantObject (const char *name, simpleRegIOobject *)
Register DimensionedConstant read/write object.
simpleObjectRegistry & debugObjects ()
Get access to registered debug switch objects.
simpleObjectRegistry & infoObjects ()
Get access to registered info switch objects.
simpleObjectRegistry & optimisationObjects ()
Get access to registered optimisation switch objects.
simpleObjectRegistry & dimensionSetObjects ()
Get access to registered dimensionSets switch objects.
simpleObjectRegistry & dimensionedConstantObjects ()
Get access to registered dimensionedConstant switch objects.
Detailed Description
Namespace for handling debugging switches.
Source files
debug.H
debug.C
Function Documentation
controlDict()
Foam::dictionary & controlDict ()
The central control dictionary.
Located in ~/.OpenFOAM/VERSION or $WM_PROJECT_DIR/etc
See also
Foam::findEtcFile()
Definition at line 90 of file debug.C.
References Foam::findEtcFiles(), forAllReverse, IOstream::good(), SafeFatalIOErrorIn, and switchSet().
Referenced by argList::displayDoc(), GAMGProcAgglomeration::New(), GAMGAgglomeration::New(), setTimeStepFunctionObject::read(), and switchSet().
debugSwitches()
Foam::dictionary & debugSwitches ()
The DebugSwitches sub-dictionary in the central controlDict.
Definition at line 147 of file debug.C.
References switchSet().
Referenced by debugSwitch().
infoSwitches()
Foam::dictionary & infoSwitches ()
The InfoSwitches sub-dictionary in the central controlDict.
Definition at line 153 of file debug.C.
References switchSet().
Referenced by infoSwitch().
optimisationSwitches()
Foam::dictionary & optimisationSwitches ()
The OptimisationSwitches sub-dictionary in the central controlDict.
Definition at line 159 of file debug.C.
References switchSet().
Referenced by NamedEnum< directionType, 3 >::names(), optimisationSwitch(), and UPstream::procNo().
debugSwitch()
int debugSwitch (const char * name, const int defaultValue = 0)
Lookup debug switch or add default value.
Definition at line 165 of file debug.C.
References debugSwitches(), and dictionary::lookupOrAddDefault().
infoSwitch()
int infoSwitch (const char * name, const int defaultValue = 0)
Lookup info switch or add default value.
Definition at line 174 of file debug.C.
References infoSwitches(), and dictionary::lookupOrAddDefault().
optimisationSwitch()
int optimisationSwitch (const char * name, const int defaultValue = 0)
Lookup optimisation switch or add default value.
Definition at line 183 of file debug.C.
References dictionary::lookupOrAddDefault(), and optimisationSwitches().
Referenced by UPstream::procNo(), and addcommsTypeToOpt::writeData().
switchSet()
Foam::dictionary & switchSet (const char * subDictName, dictionary *& subDictPtr)
Internal function to lookup a sub-dictionary from controlDict.
Definition at line 118 of file debug.C.
References controlDict(), entry::dict(), Foam::endl(), Foam::exit(), entry::isDict(), dictionary::lookupEntryPtr(), and dictionaryName::name().
Referenced by controlDict(), debugSwitches(), Foam::dimensionedConstants(), Foam::dimensionSystems(), infoSwitches(), and optimisationSwitches().
addDebugObject()
void addDebugObject (const char * name, simpleRegIOobject * obj)
Register debug switch read/write object.
Definition at line 192 of file debug.C.
References DictionaryBase< IDLListType, T >::append(), List< T >::append(), debugObjects(), and DictionaryBase< IDLListType, T >::lookupPtr().
addInfoObject()
void addInfoObject (const char * name, simpleRegIOobject * obj)
Register info switch read/write object.
Definition at line 213 of file debug.C.
References addOptimisationObject(), DictionaryBase< IDLListType, T >::append(), List< T >::append(), infoObjects(), and DictionaryBase< IDLListType, T >::lookupPtr().
addOptimisationObject()
void addOptimisationObject (const char * name, simpleRegIOobject * obj)
Register optimisation switch read/write object.
Definition at line 235 of file debug.C.
References addDimensionSetObject(), DictionaryBase< IDLListType, T >::append(), List< T >::append(), DictionaryBase< IDLListType, T >::lookupPtr(), and optimisationObjects().
Referenced by addInfoObject().
addDimensionSetObject()
void addDimensionSetObject (const char * name, simpleRegIOobject * obj)
Register DimensionSets read/write object.
Definition at line 260 of file debug.C.
References addDimensionedConstantObject(), DictionaryBase< IDLListType, T >::append(), List< T >::append(), dimensionSetObjects(), and DictionaryBase< IDLListType, T >::lookupPtr().
Referenced by addOptimisationObject().
addDimensionedConstantObject()
void addDimensionedConstantObject (const char * name, simpleRegIOobject * obj)
Register DimensionedConstant read/write object.
Definition at line 285 of file debug.C.
References DictionaryBase< IDLListType, T >::append(), List< T >::append(), dimensionedConstantObjects(), and DictionaryBase< IDLListType, T >::lookupPtr().
Referenced by addDimensionSetObject().
debugObjects()
Foam::simpleObjectRegistry & debugObjects ()
Get access to registered debug switch objects.
Definition at line 312 of file debug.C.
Referenced by addDebugObject(), and Time::readDict().
infoObjects()
Foam::simpleObjectRegistry & infoObjects ()
Get access to registered info switch objects.
Definition at line 323 of file debug.C.
Referenced by addInfoObject().
optimisationObjects()
Foam::simpleObjectRegistry & optimisationObjects ()
Get access to registered optimisation switch objects.
Definition at line 334 of file debug.C.
Referenced by addOptimisationObject(), and Time::readDict().
dimensionSetObjects()
Foam::simpleObjectRegistry & dimensionSetObjects ()
Get access to registered dimensionSets switch objects.
Definition at line 345 of file debug.C.
Referenced by addDimensionSetObject(), and Time::readDict().
dimensionedConstantObjects()
Foam::simpleObjectRegistry & dimensionedConstantObjects ()
Get access to registered dimensionedConstant switch objects.
Definition at line 356 of file debug.C.
Referenced by addDimensionedConstantObject(), and Time::readDict().