OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::fv Namespace Reference
Namespace for finite-volume.
Classes
class actuationDiskSource
Actuation disk source.
class backwardDdtScheme
Second-order backward-differencing ddt using the current and two previous time-step values.
class boundedConvectionScheme
Bounded form of the selected convection scheme.
class boundedDdtScheme
Bounded form of the selected ddt scheme.
class cellLimitedGrad
cellLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class cellMDLimitedGrad
cellMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class CentredFitSnGradScheme
class CodedSource
class codedSource
Constructs on-the-fly fvOption source.
class CoEulerDdtScheme
Courant number limited first-order Euler implicit/explicit ddt.
class constantHeatTransfer
Constant heat transfer model. htcConst [W/m2/K] and area/volume [1/m] must be provided.
class convectionScheme
Abstract base class for convection schemes.
class correctedSnGrad
Simple central-difference snGrad scheme with non-orthogonal correction.
class CrankNicolsonDdtScheme
Second-oder Crank-Nicolson implicit ddt using the current and previous time-step fields as well as the previous time-step ddt.
class d2dt2Scheme
Abstract base class for d2dt2 schemes.
class ddtScheme
Abstract base class for ddt schemes.
class divScheme
Abstract base class for div schemes.
class effectivenessHeatExchangerSource
Heat exchanger source model, in which the heat exchanger is defined as a selection of cells.
class EulerD2dt2Scheme
First-order Euler implicit d2dt2 using the current and two previous time-step values.
class EulerDdtScheme
Basic first-order Euler implicit/explicit ddt using only the current and previous time-step values.
class explicitPorositySource
Explicit porosity source.
class ExplicitSetValue
class explicitSetValue
Set values field values explicity.
class faceCorrectedSnGrad
Simple central-difference snGrad scheme with non-orthogonal correction.
class faceLimitedGrad
faceLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class faceMDLimitedGrad
faceMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
class fixedTemperatureConstraint
Fixed temperature equation constraint.
class fourthGrad
Second-order gradient scheme using least-squares.
class gaussConvectionScheme
Basic second-order convection using face-gradients and Gauss' theorem.
class gaussDivScheme
Basic second-order div using face-gradients and Gauss' theorem.
class gaussGrad
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
class gaussLaplacianScheme
Basic second-order laplacian using face-gradients and Gauss' theorem.
class gradScheme
Abstract base class for gradient schemes.
class interRegionExplicitPorositySource
Inter-region explicit porosity source.
class interRegionHeatTransferModel
Base class for inter region heat exchange. The derived classes must provide the heat transfer coeffisine (htc) which is used as follows in the energy equation.
class IOoptionList
IOoptionList.
class laplacianScheme
Abstract base class for laplacian schemes.
class LeastSquaresGrad
Gradient calculated using weighted least-squares on an arbitrary stencil. The stencil type is provided via a template argument and any cell-based stencil is supported:
class leastSquaresGrad
Second-order gradient scheme using least-squares.
class LeastSquaresVectors
Least-squares gradient scheme vectors.
class limitedSnGrad
Run-time selected snGrad scheme with limited non-orthogonal correction.
class localEulerDdtScheme
Local time-step first-order Euler implicit/explicit ddt. The reciprocal of the local time-step field is looked-up from the database with the name provided.
class MRFSource
Multiple Reference Frame (MRF) source.
class multivariateGaussConvectionScheme
Basic second-order convection using face-gradients and Gauss' theorem.
class option
Finite volume options abtract base class. Provides a base set of controls, e.g.
class optionList
List of finite volume options.
class orthogonalSnGrad
Simple central-difference snGrad scheme without non-orthogonal correction.
class pressureGradientExplicitSource
Creates a pressure gradient source.
class radialActuationDiskSource
Actuation disk source including radial thrust.
class rotorDiskSource
Cell based momemtum source.
class SemiImplicitSource
Semi-implicit source, described using an input dictionary. The injection rate coefficients are specified as pairs of Su-Sp coefficients, i.e.
class SLTSDdtScheme
Stabilised local time-step first-order Euler implicit/explicit ddt. The time-step is adjusted locally so that an advective equations remains diagonally dominant.
class snGradScheme
Abstract base class for snGrad schemes.
class solidificationMeltingSource
This source is designed to model the effect of solidification and melting processes, e.g. windhield defrosting. The phase change occurs at the melting temperature, Tmelt.
class steadyStateD2dt2Scheme
SteadyState d2dt2 which returns 0.
class steadyStateDdtScheme
SteadyState implicit/explicit ddt which returns 0.
class tabulatedHeatTransfer
Tabulated heat transfer model. The heat exchange area per unit volume must be provided. The 2D table returns the heat transfer coefficient by querying the local and neighbour region velocities.
class temperatureLimitsConstraint
Constraint for temperature to apply limits between minimum and maximum values.
class uncorrectedSnGrad
Simple central-difference snGrad scheme without non-orthogonal correction.
class variableHeatTransfer
Variable heat transfer model depending on local values. The area of contact between regions (area) must be provided. The Nu number is calculated as:
Typedefs
typedef LeastSquaresVectors< centredCPCCellToCellStencilObject > LeastSquaresVectorscentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad< scalar, centredCPCCellToCellStencilObject > LeastSquaresGradscalarcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad< vector, centredCPCCellToCellStencilObject > LeastSquaresGradvectorcentredCPCCellToCellStencilObject_
typedef LeastSquaresVectors< centredCECCellToCellStencilObject > LeastSquaresVectorscentredCECCellToCellStencilObject_
typedef LeastSquaresGrad< scalar, centredCECCellToCellStencilObject > LeastSquaresGradscalarcentredCECCellToCellStencilObject_
typedef LeastSquaresGrad< vector, centredCECCellToCellStencilObject > LeastSquaresGradvectorcentredCECCellToCellStencilObject_
typedef laplacianScheme< scalar, scalar > laplacianSchemescalarscalar
typedef laplacianScheme< scalar, symmTensor > laplacianSchemescalarsymmTensor
typedef laplacianScheme< scalar, tensor > laplacianSchemescalartensor
typedef laplacianScheme< vector, scalar > laplacianSchemevectorscalar
typedef laplacianScheme< vector, symmTensor > laplacianSchemevectorsymmTensor
typedef laplacianScheme< vector, tensor > laplacianSchemevectortensor
typedef laplacianScheme< sphericalTensor, scalar > laplacianSchemesphericalTensorscalar
typedef laplacianScheme< sphericalTensor, symmTensor > laplacianSchemesphericalTensorsymmTensor
typedef laplacianScheme< sphericalTensor, tensor > laplacianSchemesphericalTensortensor
typedef laplacianScheme< symmTensor, scalar > laplacianSchemesymmTensorscalar
typedef laplacianScheme< symmTensor, symmTensor > laplacianSchemesymmTensorsymmTensor
typedef laplacianScheme< symmTensor, tensor > laplacianSchemesymmTensortensor
typedef laplacianScheme< tensor, scalar > laplacianSchemetensorscalar
typedef laplacianScheme< tensor, symmTensor > laplacianSchemetensorsymmTensor
typedef laplacianScheme< tensor, tensor > laplacianSchemetensortensor
Functions
defineTemplateRunTimeSelectionTable (convectionScheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< scalar >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< vector >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor >, Multivariate)
defineTemplateRunTimeSelectionTable (convectionScheme< tensor >, Istream)
defineTemplateRunTimeSelectionTable (convectionScheme< tensor >, Multivariate)
int warnUnboundedGauss (Foam::debug::debugSwitch("warnUnboundedGauss", true))
defineTemplateRunTimeSelectionTable (d2dt2Scheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (d2dt2Scheme< tensor >, Istream)
template<class Type >
const FieldField< fvPatchField, Type > & ff (const FieldField< fvPatchField, Type > &bf)
defineTemplateRunTimeSelectionTable (ddtScheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (ddtScheme< tensor >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< vector >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< sphericalTensor >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< symmTensor >, Istream)
defineTemplateRunTimeSelectionTable (divScheme< tensor >, Istream)
NamespaceName ("fv")
defineTemplateRunTimeSelectionTable (gradScheme< scalar >, Istream)
defineTemplateRunTimeSelectionTable (gradScheme< vector >, Istream)
defineTemplateTypeNameAndDebugWithName (LeastSquaresVectorscentredCPCCellToCellStencilObject_, "pointCellsLeastSquares", 0)
defineTemplateTypeNameAndDebugWithName (LeastSquaresGradscalarcentredCPCCellToCellStencilObject_, "pointCellsLeastSquares", 0)
defineTemplateTypeNameAndDebugWithName (LeastSquaresGradvectorcentredCPCCellToCellStencilObject_, "pointCellsLeastSquares", 0)
defineTemplateTypeNameAndDebugWithName (LeastSquaresVectorscentredCECCellToCellStencilObject_, "edgeCellsLeastSquares", 0)
defineTemplateTypeNameAndDebugWithName (LeastSquaresGradscalarcentredCECCellToCellStencilObject_, "edgeCellsLeastSquares", 0)
defineTemplateTypeNameAndDebugWithName (LeastSquaresGradvectorcentredCECCellToCellStencilObject_, "edgeCellsLeastSquares", 0)
defineTemplateRunTimeSelectionTable (laplacianSchemescalarscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemescalarsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemescalartensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemevectorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemevectorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemevectortensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensortensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensortensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemetensorscalar, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemetensorsymmTensor, Istream)
defineTemplateRunTimeSelectionTable (laplacianSchemetensortensor, Istream)
makeCentredFitSnGradScheme (linearFit, linearFitPolynomial, centredFECCellToFaceStencilObject)
makeCentredFitSnGradScheme (quadraticFit, quadraticFitPolynomial, centredCFCCellToFaceStencilObject)
defineTemplateRunTimeSelectionTable (snGradScheme< scalar >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< vector >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< sphericalTensor >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< symmTensor >, Mesh)
defineTemplateRunTimeSelectionTable (snGradScheme< tensor >, Mesh)
defineTypeNameAndDebug (fixedTemperatureConstraint, 0)
addToRunTimeSelectionTable (option, fixedTemperatureConstraint, dictionary)
defineTypeNameAndDebug (temperatureLimitsConstraint, 0)
addToRunTimeSelectionTable (option, temperatureLimitsConstraint, dictionary)
makeFvOption (ExplicitSetValue, scalar)
makeFvOption (ExplicitSetValue, vector)
makeFvOption (ExplicitSetValue, sphericalTensor)
makeFvOption (ExplicitSetValue, symmTensor)
makeFvOption (ExplicitSetValue, tensor)
defineTypeNameAndDebug (option, 0)
defineRunTimeSelectionTable (option, dictionary)
defineTypeNameAndDebug (optionList, 0)
defineTypeNameAndDebug (actuationDiskSource, 0)
addToRunTimeSelectionTable (option, actuationDiskSource, dictionary)
defineTypeNameAndDebug (effectivenessHeatExchangerSource, 0)
addToRunTimeSelectionTable (option, effectivenessHeatExchangerSource, dictionary)
defineTypeNameAndDebug (explicitPorositySource, 0)
addToRunTimeSelectionTable (option, explicitPorositySource, dictionary)
defineTypeNameAndDebug (MRFSource, 0)
addToRunTimeSelectionTable (option, MRFSource, dictionary)
defineTypeNameAndDebug (pressureGradientExplicitSource, 0)
addToRunTimeSelectionTable (option, pressureGradientExplicitSource, dictionary)
defineTypeNameAndDebug (radialActuationDiskSource, 0)
addToRunTimeSelectionTable (option, radialActuationDiskSource, dictionary)
defineTypeNameAndDebug (rotorDiskSource, 0)
addToRunTimeSelectionTable (option, rotorDiskSource, dictionary)
defineTypeNameAndDebug (solidificationMeltingSource, 0)
addToRunTimeSelectionTable (option, solidificationMeltingSource, dictionary)
makeFvOption (CodedSource, scalar)
makeFvOption (CodedSource, vector)
makeFvOption (CodedSource, sphericalTensor)
makeFvOption (CodedSource, symmTensor)
makeFvOption (CodedSource, tensor)
makeFvOption (SemiImplicitSource, scalar)
makeFvOption (SemiImplicitSource, vector)
makeFvOption (SemiImplicitSource, sphericalTensor)
makeFvOption (SemiImplicitSource, symmTensor)
makeFvOption (SemiImplicitSource, tensor)
template<class Type >
Ostream & operator<< (Ostream &, const SemiImplicitSource< Type > &)
defineTypeNameAndDebug (interRegionExplicitPorositySource, 0)
addToRunTimeSelectionTable (option, interRegionExplicitPorositySource, dictionary)
defineTypeNameAndDebug (constantHeatTransfer, 0)
addToRunTimeSelectionTable (option, constantHeatTransfer, dictionary)
defineTypeNameAndDebug (interRegionHeatTransferModel, 0)
defineTypeNameAndDebug (tabulatedHeatTransfer, 0)
addToRunTimeSelectionTable (option, tabulatedHeatTransfer, dictionary)
defineTypeNameAndDebug (variableHeatTransfer, 0)
addToRunTimeSelectionTable (option, variableHeatTransfer, dictionary)
Variables
int warnUnboundedGauss
Temporary debug switch to provide warning about backward-compatibility.
gradScheme< scalar >::addIstreamConstructorToTable< LeastSquaresGrad< scalar, centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme< vector >::addIstreamConstructorToTable< LeastSquaresGrad< vector, centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable< LeastSquaresGrad< scalar, centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme< vector >::addIstreamConstructorToTable< LeastSquaresGrad< vector, centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectvectorIstreamConstructorToTable_
Detailed Description
Namespace for finite-volume.
Typedef Documentation
LeastSquaresVectorscentredCPCCellToCellStencilObject_
typedef LeastSquaresVectors< centredCPCCellToCellStencilObject > LeastSquaresVectorscentredCPCCellToCellStencilObject_
Definition at line 47 of file LeastSquaresGrads.C.
LeastSquaresGradscalarcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad< scalar , centredCPCCellToCellStencilObject > LeastSquaresGradscalarcentredCPCCellToCellStencilObject_
Definition at line 47 of file LeastSquaresGrads.C.
LeastSquaresGradvectorcentredCPCCellToCellStencilObject_
typedef LeastSquaresGrad< vector , centredCPCCellToCellStencilObject > LeastSquaresGradvectorcentredCPCCellToCellStencilObject_
Definition at line 47 of file LeastSquaresGrads.C.
LeastSquaresVectorscentredCECCellToCellStencilObject_
typedef LeastSquaresVectors< centredCECCellToCellStencilObject > LeastSquaresVectorscentredCECCellToCellStencilObject_
Definition at line 53 of file LeastSquaresGrads.C.
LeastSquaresGradscalarcentredCECCellToCellStencilObject_
typedef LeastSquaresGrad< scalar , centredCECCellToCellStencilObject > LeastSquaresGradscalarcentredCECCellToCellStencilObject_
Definition at line 53 of file LeastSquaresGrads.C.
LeastSquaresGradvectorcentredCECCellToCellStencilObject_
typedef LeastSquaresGrad< vector , centredCECCellToCellStencilObject > LeastSquaresGradvectorcentredCECCellToCellStencilObject_
Definition at line 53 of file LeastSquaresGrads.C.
laplacianSchemescalarscalar
typedef laplacianScheme< scalar , scalar > laplacianSchemescalarscalar
Definition at line 50 of file laplacianSchemes.C.
laplacianSchemescalarsymmTensor
typedef laplacianScheme< scalar , symmTensor > laplacianSchemescalarsymmTensor
Definition at line 50 of file laplacianSchemes.C.
laplacianSchemescalartensor
typedef laplacianScheme< scalar , tensor > laplacianSchemescalartensor
Definition at line 50 of file laplacianSchemes.C.
laplacianSchemevectorscalar
typedef laplacianScheme< vector , scalar > laplacianSchemevectorscalar
Definition at line 50 of file laplacianSchemes.C.
laplacianSchemevectorsymmTensor
typedef laplacianScheme< vector , symmTensor > laplacianSchemevectorsymmTensor
Definition at line 51 of file laplacianSchemes.C.
laplacianSchemevectortensor
typedef laplacianScheme< vector , tensor > laplacianSchemevectortensor
Definition at line 51 of file laplacianSchemes.C.
laplacianSchemesphericalTensorscalar
typedef laplacianScheme< sphericalTensor , scalar > laplacianSchemesphericalTensorscalar
Definition at line 51 of file laplacianSchemes.C.
laplacianSchemesphericalTensorsymmTensor
typedef laplacianScheme< sphericalTensor , symmTensor > laplacianSchemesphericalTensorsymmTensor
Definition at line 52 of file laplacianSchemes.C.
laplacianSchemesphericalTensortensor
typedef laplacianScheme< sphericalTensor , tensor > laplacianSchemesphericalTensortensor
Definition at line 52 of file laplacianSchemes.C.
laplacianSchemesymmTensorscalar
typedef laplacianScheme< symmTensor , scalar > laplacianSchemesymmTensorscalar
Definition at line 52 of file laplacianSchemes.C.
laplacianSchemesymmTensorsymmTensor
typedef laplacianScheme< symmTensor , symmTensor > laplacianSchemesymmTensorsymmTensor
Definition at line 53 of file laplacianSchemes.C.
laplacianSchemesymmTensortensor
typedef laplacianScheme< symmTensor , tensor > laplacianSchemesymmTensortensor
Definition at line 53 of file laplacianSchemes.C.
laplacianSchemetensorscalar
typedef laplacianScheme< tensor , scalar > laplacianSchemetensorscalar
Definition at line 53 of file laplacianSchemes.C.
laplacianSchemetensorsymmTensor
typedef laplacianScheme< tensor , symmTensor > laplacianSchemetensorsymmTensor
Definition at line 54 of file laplacianSchemes.C.
laplacianSchemetensortensor
typedef laplacianScheme< tensor , tensor > laplacianSchemetensortensor
Definition at line 54 of file laplacianSchemes.C.
Function Documentation
defineTemplateRunTimeSelectionTable() [1/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [2/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< scalar > , Multivariate)
defineTemplateRunTimeSelectionTable() [3/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [4/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< vector > , Multivariate)
defineTemplateRunTimeSelectionTable() [5/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [6/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< sphericalTensor > , Multivariate)
defineTemplateRunTimeSelectionTable() [7/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [8/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< symmTensor > , Multivariate)
defineTemplateRunTimeSelectionTable() [9/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< tensor > , Istream)
defineTemplateRunTimeSelectionTable() [10/46]
Foam::fv::defineTemplateRunTimeSelectionTable (convectionScheme< tensor > , Multivariate)
warnUnboundedGauss()
int Foam::fv::warnUnboundedGauss (Foam::debug::debugSwitch("warnUnboundedGauss", true))
defineTemplateRunTimeSelectionTable() [11/46]
Foam::fv::defineTemplateRunTimeSelectionTable (d2dt2Scheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [12/46]
Foam::fv::defineTemplateRunTimeSelectionTable (d2dt2Scheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [13/46]
Foam::fv::defineTemplateRunTimeSelectionTable (d2dt2Scheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [14/46]
Foam::fv::defineTemplateRunTimeSelectionTable (d2dt2Scheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [15/46]
Foam::fv::defineTemplateRunTimeSelectionTable (d2dt2Scheme< tensor > , Istream)
ff()
const FieldField<fvPatchField, Type>& Foam::fv::ff (const FieldField< fvPatchField, Type > & bf)
Definition at line 272 of file CrankNicolsonDdtScheme.C.
References CrankNicolsonDdtScheme< Type >::fvcDdt().
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), GAMGAgglomeration::nFaces(), and pairPatchAgglomeration::restrictAddressing().
defineTemplateRunTimeSelectionTable() [16/46]
Foam::fv::defineTemplateRunTimeSelectionTable (ddtScheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [17/46]
Foam::fv::defineTemplateRunTimeSelectionTable (ddtScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [18/46]
Foam::fv::defineTemplateRunTimeSelectionTable (ddtScheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [19/46]
Foam::fv::defineTemplateRunTimeSelectionTable (ddtScheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [20/46]
Foam::fv::defineTemplateRunTimeSelectionTable (ddtScheme< tensor > , Istream)
defineTemplateRunTimeSelectionTable() [21/46]
Foam::fv::defineTemplateRunTimeSelectionTable (divScheme< vector > , Istream)
defineTemplateRunTimeSelectionTable() [22/46]
Foam::fv::defineTemplateRunTimeSelectionTable (divScheme< sphericalTensor > , Istream)
defineTemplateRunTimeSelectionTable() [23/46]
Foam::fv::defineTemplateRunTimeSelectionTable (divScheme< symmTensor > , Istream)
defineTemplateRunTimeSelectionTable() [24/46]
Foam::fv::defineTemplateRunTimeSelectionTable (divScheme< tensor > , Istream)
NamespaceName()
Foam::fv::NamespaceName ("fv")
defineTemplateRunTimeSelectionTable() [25/46]
Foam::fv::defineTemplateRunTimeSelectionTable (gradScheme< scalar > , Istream)
defineTemplateRunTimeSelectionTable() [26/46]
Foam::fv::defineTemplateRunTimeSelectionTable (gradScheme< vector > , Istream)
defineTemplateTypeNameAndDebugWithName() [1/6]
Foam::fv::defineTemplateTypeNameAndDebugWithName (LeastSquaresVectorscentredCPCCellToCellStencilObject_ , "pointCellsLeastSquares" , 0)
defineTemplateTypeNameAndDebugWithName() [2/6]
Foam::fv::defineTemplateTypeNameAndDebugWithName (LeastSquaresGradscalarcentredCPCCellToCellStencilObject_ , "pointCellsLeastSquares" , 0)
defineTemplateTypeNameAndDebugWithName() [3/6]
Foam::fv::defineTemplateTypeNameAndDebugWithName (LeastSquaresGradvectorcentredCPCCellToCellStencilObject_ , "pointCellsLeastSquares" , 0)
defineTemplateTypeNameAndDebugWithName() [4/6]
Foam::fv::defineTemplateTypeNameAndDebugWithName (LeastSquaresVectorscentredCECCellToCellStencilObject_ , "edgeCellsLeastSquares" , 0)
defineTemplateTypeNameAndDebugWithName() [5/6]
Foam::fv::defineTemplateTypeNameAndDebugWithName (LeastSquaresGradscalarcentredCECCellToCellStencilObject_ , "edgeCellsLeastSquares" , 0)
defineTemplateTypeNameAndDebugWithName() [6/6]
Foam::fv::defineTemplateTypeNameAndDebugWithName (LeastSquaresGradvectorcentredCECCellToCellStencilObject_ , "edgeCellsLeastSquares" , 0)
defineTemplateRunTimeSelectionTable() [27/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemescalarscalar , Istream)
defineTemplateRunTimeSelectionTable() [28/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemescalarsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [29/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemescalartensor , Istream)
defineTemplateRunTimeSelectionTable() [30/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemevectorscalar , Istream)
defineTemplateRunTimeSelectionTable() [31/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemevectorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [32/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemevectortensor , Istream)
defineTemplateRunTimeSelectionTable() [33/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorscalar , Istream)
defineTemplateRunTimeSelectionTable() [34/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [35/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemesphericalTensortensor , Istream)
defineTemplateRunTimeSelectionTable() [36/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorscalar , Istream)
defineTemplateRunTimeSelectionTable() [37/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [38/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemesymmTensortensor , Istream)
defineTemplateRunTimeSelectionTable() [39/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemetensorscalar , Istream)
defineTemplateRunTimeSelectionTable() [40/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemetensorsymmTensor , Istream)
defineTemplateRunTimeSelectionTable() [41/46]
Foam::fv::defineTemplateRunTimeSelectionTable (laplacianSchemetensortensor , Istream)
makeCentredFitSnGradScheme() [1/2]
Foam::fv::makeCentredFitSnGradScheme (linearFit , linearFitPolynomial , centredFECCellToFaceStencilObject)
makeCentredFitSnGradScheme() [2/2]
Foam::fv::makeCentredFitSnGradScheme (quadraticFit , quadraticFitPolynomial , centredCFCCellToFaceStencilObject)
defineTemplateRunTimeSelectionTable() [42/46]
Foam::fv::defineTemplateRunTimeSelectionTable (snGradScheme< scalar > , Mesh)
defineTemplateRunTimeSelectionTable() [43/46]
Foam::fv::defineTemplateRunTimeSelectionTable (snGradScheme< vector > , Mesh)
defineTemplateRunTimeSelectionTable() [44/46]
Foam::fv::defineTemplateRunTimeSelectionTable (snGradScheme< sphericalTensor > , Mesh)
defineTemplateRunTimeSelectionTable() [45/46]
Foam::fv::defineTemplateRunTimeSelectionTable (snGradScheme< symmTensor > , Mesh)
defineTemplateRunTimeSelectionTable() [46/46]
Foam::fv::defineTemplateRunTimeSelectionTable (snGradScheme< tensor > , Mesh)
defineTypeNameAndDebug() [1/17]
Foam::fv::defineTypeNameAndDebug (fixedTemperatureConstraint , 0)
Referenced by NamedEnum< directionType, 3 >::names().
addToRunTimeSelectionTable() [1/14]
Foam::fv::addToRunTimeSelectionTable (option , fixedTemperatureConstraint , dictionary)
Referenced by NamedEnum< directionType, 3 >::names().
defineTypeNameAndDebug() [2/17]
Foam::fv::defineTypeNameAndDebug (temperatureLimitsConstraint , 0)
addToRunTimeSelectionTable() [2/14]
Foam::fv::addToRunTimeSelectionTable (option , temperatureLimitsConstraint , dictionary)
makeFvOption() [1/15]
Foam::fv::makeFvOption (ExplicitSetValue , scalar)
makeFvOption() [2/15]
Foam::fv::makeFvOption (ExplicitSetValue , vector)
makeFvOption() [3/15]
Foam::fv::makeFvOption (ExplicitSetValue , sphericalTensor)
makeFvOption() [4/15]
Foam::fv::makeFvOption (ExplicitSetValue , symmTensor)
makeFvOption() [5/15]
Foam::fv::makeFvOption (ExplicitSetValue , tensor)
defineTypeNameAndDebug() [3/17]
Foam::fv::defineTypeNameAndDebug (option , 0)
defineRunTimeSelectionTable()
Foam::fv::defineRunTimeSelectionTable (option , dictionary)
defineTypeNameAndDebug() [4/17]
Foam::fv::defineTypeNameAndDebug (optionList , 0)
defineTypeNameAndDebug() [5/17]
Foam::fv::defineTypeNameAndDebug (actuationDiskSource , 0)
addToRunTimeSelectionTable() [3/14]
Foam::fv::addToRunTimeSelectionTable (option , actuationDiskSource , dictionary)
defineTypeNameAndDebug() [6/17]
Foam::fv::defineTypeNameAndDebug (effectivenessHeatExchangerSource , 0)
addToRunTimeSelectionTable() [4/14]
Foam::fv::addToRunTimeSelectionTable (option , effectivenessHeatExchangerSource , dictionary)
defineTypeNameAndDebug() [7/17]
Foam::fv::defineTypeNameAndDebug (explicitPorositySource , 0)
addToRunTimeSelectionTable() [5/14]
Foam::fv::addToRunTimeSelectionTable (option , explicitPorositySource , dictionary)
defineTypeNameAndDebug() [8/17]
Foam::fv::defineTypeNameAndDebug (MRFSource , 0)
addToRunTimeSelectionTable() [6/14]
Foam::fv::addToRunTimeSelectionTable (option , MRFSource , dictionary)
defineTypeNameAndDebug() [9/17]
Foam::fv::defineTypeNameAndDebug (pressureGradientExplicitSource , 0)
addToRunTimeSelectionTable() [7/14]
Foam::fv::addToRunTimeSelectionTable (option , pressureGradientExplicitSource , dictionary)
defineTypeNameAndDebug() [10/17]
Foam::fv::defineTypeNameAndDebug (radialActuationDiskSource , 0)
addToRunTimeSelectionTable() [8/14]
Foam::fv::addToRunTimeSelectionTable (option , radialActuationDiskSource , dictionary)
defineTypeNameAndDebug() [11/17]
Foam::fv::defineTypeNameAndDebug (rotorDiskSource , 0)
addToRunTimeSelectionTable() [9/14]
Foam::fv::addToRunTimeSelectionTable (option , rotorDiskSource , dictionary)
defineTypeNameAndDebug() [12/17]
Foam::fv::defineTypeNameAndDebug (solidificationMeltingSource , 0)
addToRunTimeSelectionTable() [10/14]
Foam::fv::addToRunTimeSelectionTable (option , solidificationMeltingSource , dictionary)
makeFvOption() [6/15]
Foam::fv::makeFvOption (CodedSource , scalar)
makeFvOption() [7/15]
Foam::fv::makeFvOption (CodedSource , vector)
makeFvOption() [8/15]
Foam::fv::makeFvOption (CodedSource , sphericalTensor)
makeFvOption() [9/15]
Foam::fv::makeFvOption (CodedSource , symmTensor)
makeFvOption() [10/15]
Foam::fv::makeFvOption (CodedSource , tensor)
makeFvOption() [11/15]
Foam::fv::makeFvOption (SemiImplicitSource , scalar)
makeFvOption() [12/15]
Foam::fv::makeFvOption (SemiImplicitSource , vector)
makeFvOption() [13/15]
Foam::fv::makeFvOption (SemiImplicitSource , sphericalTensor)
makeFvOption() [14/15]
Foam::fv::makeFvOption (SemiImplicitSource , symmTensor)
makeFvOption() [15/15]
Foam::fv::makeFvOption (SemiImplicitSource , tensor)
operator<<()
Ostream& Foam::fv::operator<< (Ostream & , const SemiImplicitSource< Type > &)
defineTypeNameAndDebug() [13/17]
Foam::fv::defineTypeNameAndDebug (interRegionExplicitPorositySource , 0)
addToRunTimeSelectionTable() [11/14]
Foam::fv::addToRunTimeSelectionTable (option , interRegionExplicitPorositySource , dictionary)
defineTypeNameAndDebug() [14/17]
Foam::fv::defineTypeNameAndDebug (constantHeatTransfer , 0)
addToRunTimeSelectionTable() [12/14]
Foam::fv::addToRunTimeSelectionTable (option , constantHeatTransfer , dictionary)
defineTypeNameAndDebug() [15/17]
Foam::fv::defineTypeNameAndDebug (interRegionHeatTransferModel , 0)
defineTypeNameAndDebug() [16/17]
Foam::fv::defineTypeNameAndDebug (tabulatedHeatTransfer , 0)
addToRunTimeSelectionTable() [13/14]
Foam::fv::addToRunTimeSelectionTable (option , tabulatedHeatTransfer , dictionary)
defineTypeNameAndDebug() [17/17]
Foam::fv::defineTypeNameAndDebug (variableHeatTransfer , 0)
addToRunTimeSelectionTable() [14/14]
Foam::fv::addToRunTimeSelectionTable (option , variableHeatTransfer , dictionary)
Variable Documentation
warnUnboundedGauss
int warnUnboundedGauss
Temporary debug switch to provide warning about backward-compatibility.
issue with setting div schemes for steady-state
addpointCellsLeastSquarescentredCPCCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable<LeastSquaresGrad< scalar , centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectscalarIstreamConstructorToTable_
Definition at line 47 of file LeastSquaresGrads.C.
addpointCellsLeastSquarescentredCPCCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme< vector >::addIstreamConstructorToTable<LeastSquaresGrad< vector , centredCPCCellToCellStencilObject > > addpointCellsLeastSquarescentredCPCCellToCellStencilObjectvectorIstreamConstructorToTable_
Definition at line 47 of file LeastSquaresGrads.C.
addedgeCellsLeastSquarescentredCECCellToCellStencilObjectscalarIstreamConstructorToTable_
gradScheme< scalar >::addIstreamConstructorToTable<LeastSquaresGrad< scalar , centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectscalarIstreamConstructorToTable_
Definition at line 53 of file LeastSquaresGrads.C.
addedgeCellsLeastSquarescentredCECCellToCellStencilObjectvectorIstreamConstructorToTable_
gradScheme< vector >::addIstreamConstructorToTable<LeastSquaresGrad< vector , centredCECCellToCellStencilObject > > addedgeCellsLeastSquarescentredCECCellToCellStencilObjectvectorIstreamConstructorToTable_
Definition at line 53 of file LeastSquaresGrads.C.