OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::incompressible Namespace Reference
Namespaces
LESModels
Namespace for incompressible LES models.
RASModels
Namespace for incompressible RAS turbulence models.
turbulenceModels
Namespace for incompressible turbulence turbulence models.
Classes
class alphatJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
class atmBoundaryLayer
This class provides functions to evaluate the velocity and turbulence distributions appropriate for atmospheric boundary layers (ABL).
class atmBoundaryLayerInletEpsilonFvPatchScalarField
This boundary condition specifies an inlet value for the turbulence dissipation, , appropriate for atmospheric boundary layers.
class atmBoundaryLayerInletKFvPatchScalarField
This boundary condition specifies an inlet value for the turbulence kinetic energy, , appropriate for atmospheric boundary layers.
class atmBoundaryLayerInletVelocityFvPatchVectorField
This boundary condition specifies a velocity inlet profile appropriate for atmospheric boundary layers (ABL).
class DESModel
Extension of LES models to provide an interface for Detached Eddy Simulation turbulence models.
class epsilonLowReWallFunctionFvPatchScalarField
This boundary condition provides a turbulence dissipation wall function condition for low- and high-Reynolds number turbulent flow cases.
class epsilonWallFunctionFvPatchScalarField
This boundary condition provides a turbulence dissipation wall function condition for high Reynolds number, turbulent flow cases.
class kLowReWallFunctionFvPatchScalarField
This boundary condition provides a turbulence kinetic energy wall function condition for low- and high-Reynolds number turbulent flow cases.
class kqRWallFunctionFvPatchField
This boundary condition provides a suitable condition for turbulence k, q, and R fields for the case of high Reynolds number flow using wall functions.
class laminar
Turbulence model for laminar incompressible flow.
class LESdelta
Abstract base class for incompressible LES deltas.
class LESModel
Base class for all incompressible flow LES SGS models.
class nutkAtmRoughWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity for atmospheric velocity profiles. It is desinged to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition. The values are calculated using:
class nutkRoughWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on turbulence kinetic energy. The condition manipulates the E parameter to account for roughness effects.
class nutkWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on turbulence kinetic energy.
class nutLowReWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition for use with low Reynolds number models. It sets nut to zero, and provides an access function to calculate y+.
class nutURoughWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on velocity.
class nutUSpaldingWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on velocity, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
class nutUTabulatedWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions. As input, the user specifies a look-up table of U+ as a function of near-wall Reynolds number. The table should be located in the $FOAM_CASE/constant directory.
class nutUWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on velocity.
class nutWallFunctionFvPatchScalarField
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on turbulence kinetic energy.
class omegaWallFunctionFvPatchScalarField
This boundary condition provides a wall function constraint on turbulnce specific dissipation, omega. The values are computed using:
class RASModel
Abstract base class for incompressible turbulence models.
class turbulenceModel
Abstract base class for incompressible turbulence models (RAS, LES and laminar).
class turbulentHeatFluxTemperatureFvPatchScalarField
Fixed heat boundary condition to specify temperature gradient. Input heat source either specified in terms of an absolute power [W], or as a flux [W/m^2].
class turbulentMixingLengthDissipationRateInletFvPatchScalarField
This boundary condition provides a turbulence dissipation, (epsilon) inlet condition based on a specified mixing length. The patch values are calculated using:
class turbulentMixingLengthFrequencyInletFvPatchScalarField
This boundary condition provides a turbulence specific dissipation, (omega) inlet condition based on a specified mixing length. The patch values are calculated using:
Functions
defineRunTimeSelectionTable (LESdelta, dictionary)
defineTypeNameAndDebug (LESModel, 0)
defineRunTimeSelectionTable (LESModel, dictionary)
addToRunTimeSelectionTable (turbulenceModel, LESModel, turbulenceModel)
tmp< volScalarField > autoCreateNut (const word &fieldName, const fvMesh &mesh)
nut
tmp< volScalarField > autoCreateLowReNut (const word &fieldName, const fvMesh &mesh)
nut for Low-Reynolds number models
tmp< volScalarField > autoCreateEpsilon (const word &fieldName, const fvMesh &mesh)
epsilon
tmp< volScalarField > autoCreateOmega (const word &fieldName, const fvMesh &mesh)
omega
tmp< volScalarField > autoCreateK (const word &fieldName, const fvMesh &mesh)
k
tmp< volScalarField > autoCreateQ (const word &fieldName, const fvMesh &mesh)
Q.
tmp< volSymmTensorField > autoCreateR (const word &fieldName, const fvMesh &mesh)
R.
template<class Type , class PatchType >
tmp< GeometricField< Type, fvPatchField, volMesh > > autoCreateWallFunctionField (const word &fieldName, const fvMesh &mesh)
Helper function to create the new field.
makePatchTypeField (fvPatchScalarField, atmBoundaryLayerInletEpsilonFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, atmBoundaryLayerInletKFvPatchScalarField)
makePatchTypeField (fvPatchVectorField, atmBoundaryLayerInletVelocityFvPatchVectorField)
makePatchTypeField (fvPatchScalarField, turbulentMixingLengthDissipationRateInletFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentMixingLengthFrequencyInletFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatJayatillekeWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, epsilonLowReWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, epsilonWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, kLowReWallFunctionFvPatchScalarField)
makePatchFields (kqRWallFunction)
makePatchTypeFieldTypedefs (kqRWallFunction)
makePatchTypeField (fvPatchScalarField, nutkAtmRoughWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutkWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutLowReWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutURoughWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, nutUWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (nutWallFunctionFvPatchScalarField, 0)
makePatchTypeField (fvPatchScalarField, omegaWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (RASModel, 0)
defineRunTimeSelectionTable (RASModel, dictionary)
addToRunTimeSelectionTable (turbulenceModel, RASModel, turbulenceModel)
makePatchTypeField (fvPatchScalarField, turbulentHeatFluxTemperatureFvPatchScalarField)
defineTypeNameAndDebug (laminar, 0)
addToRunTimeSelectionTable (turbulenceModel, laminar, turbulenceModel)
defineTypeNameAndDebug (turbulenceModel, 0)
defineRunTimeSelectionTable (turbulenceModel, turbulenceModel)
Function Documentation
defineRunTimeSelectionTable() [1/4]
Foam::incompressible::defineRunTimeSelectionTable (LESdelta , dictionary)
defineTypeNameAndDebug() [1/5]
Foam::incompressible::defineTypeNameAndDebug (LESModel , 0)
defineRunTimeSelectionTable() [2/4]
Foam::incompressible::defineRunTimeSelectionTable (LESModel , dictionary)
addToRunTimeSelectionTable() [1/3]
Foam::incompressible::addToRunTimeSelectionTable (turbulenceModel , LESModel , turbulenceModel)
autoCreateNut()
tmp<volScalarField> Foam::incompressible::autoCreateNut (const word & fieldName, const fvMesh & mesh)
nut
Definition at line 46 of file backwardsCompatibilityWallFunctions.C.
References autoCreateLowReNut(), fvMesh::boundary(), Foam::dimArea, Foam::dimTime, Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, nut, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
autoCreateLowReNut()
tmp<volScalarField> Foam::incompressible::autoCreateLowReNut (const word & fieldName, const fvMesh & mesh)
nut for Low-Reynolds number models
Definition at line 116 of file backwardsCompatibilityWallFunctions.C.
References autoCreateEpsilon(), fvMesh::boundary(), Foam::dimArea, Foam::dimTime, Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, nut, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
Referenced by autoCreateNut().
autoCreateEpsilon()
tmp<volScalarField> Foam::incompressible::autoCreateEpsilon (const word & fieldName, const fvMesh & mesh)
epsilon
Definition at line 186 of file backwardsCompatibilityWallFunctions.C.
References autoCreateOmega(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateLowReNut().
autoCreateOmega()
tmp<volScalarField> Foam::incompressible::autoCreateOmega (const word & fieldName, const fvMesh & mesh)
omega
Definition at line 205 of file backwardsCompatibilityWallFunctions.C.
References autoCreateK(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateEpsilon().
autoCreateK()
tmp<volScalarField> Foam::incompressible::autoCreateK (const word & fieldName, const fvMesh & mesh)
k
Definition at line 224 of file backwardsCompatibilityWallFunctions.C.
References autoCreateQ(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateOmega().
autoCreateQ()
tmp<volScalarField> Foam::incompressible::autoCreateQ (const word & fieldName, const fvMesh & mesh)
Q.
Definition at line 243 of file backwardsCompatibilityWallFunctions.C.
References autoCreateR(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateK().
autoCreateR()
tmp<volSymmTensorField> Foam::incompressible::autoCreateR (const word & fieldName, const fvMesh & mesh)
R.
Definition at line 262 of file backwardsCompatibilityWallFunctions.C.
References autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateQ().
autoCreateWallFunctionField()
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::incompressible::autoCreateWallFunctionField (const word & fieldName, const fvMesh & mesh)
Helper function to create the new field.
Definition at line 44 of file backwardsCompatibilityWallFunctionsTemplates.C.
References fvMesh::boundary(), boundaryField(), Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, Foam::mvBak(), IOobject::NO_READ, IOobject::NO_WRITE, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
Referenced by autoCreateEpsilon(), autoCreateK(), autoCreateOmega(), autoCreateQ(), and autoCreateR().
makePatchTypeField() [1/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , atmBoundaryLayerInletEpsilonFvPatchScalarField)
Referenced by epsilonLowReWallFunctionFvPatchScalarField::epsilonLowReWallFunctionFvPatchScalarField(), nutUWallFunctionFvPatchScalarField::write(), atmBoundaryLayerInletEpsilonFvPatchScalarField::write(), atmBoundaryLayerInletKFvPatchScalarField::write(), atmBoundaryLayerInletVelocityFvPatchVectorField::write(), nutUSpaldingWallFunctionFvPatchScalarField::write(), nutUTabulatedWallFunctionFvPatchScalarField::write(), kLowReWallFunctionFvPatchScalarField::write(), nutkRoughWallFunctionFvPatchScalarField::write(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::write(), turbulentMixingLengthFrequencyInletFvPatchScalarField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), turbulentHeatFluxTemperatureFvPatchScalarField::write(), nutURoughWallFunctionFvPatchScalarField::write(), epsilonWallFunctionFvPatchScalarField::write(), omegaWallFunctionFvPatchScalarField::write(), nutLowReWallFunctionFvPatchScalarField::yPlus(), and nutkWallFunctionFvPatchScalarField::yPlus().
makePatchTypeField() [2/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , atmBoundaryLayerInletKFvPatchScalarField)
makePatchTypeField() [3/19]
Foam::incompressible::makePatchTypeField (fvPatchVectorField , atmBoundaryLayerInletVelocityFvPatchVectorField)
makePatchTypeField() [4/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , turbulentMixingLengthDissipationRateInletFvPatchScalarField)
makePatchTypeField() [5/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , turbulentMixingLengthFrequencyInletFvPatchScalarField)
makePatchTypeField() [6/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , alphatJayatillekeWallFunctionFvPatchScalarField)
makePatchTypeField() [7/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , epsilonLowReWallFunctionFvPatchScalarField)
makePatchTypeField() [8/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , epsilonWallFunctionFvPatchScalarField)
makePatchTypeField() [9/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , kLowReWallFunctionFvPatchScalarField)
makePatchFields()
Foam::incompressible::makePatchFields (kqRWallFunction)
makePatchTypeFieldTypedefs()
Foam::incompressible::makePatchTypeFieldTypedefs (kqRWallFunction)
makePatchTypeField() [10/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutkAtmRoughWallFunctionFvPatchScalarField)
makePatchTypeField() [11/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutkRoughWallFunctionFvPatchScalarField)
makePatchTypeField() [12/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutkWallFunctionFvPatchScalarField)
makePatchTypeField() [13/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutLowReWallFunctionFvPatchScalarField)
makePatchTypeField() [14/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutURoughWallFunctionFvPatchScalarField)
makePatchTypeField() [15/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutUSpaldingWallFunctionFvPatchScalarField)
makePatchTypeField() [16/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutUTabulatedWallFunctionFvPatchScalarField)
makePatchTypeField() [17/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , nutUWallFunctionFvPatchScalarField)
defineTypeNameAndDebug() [2/5]
Foam::incompressible::defineTypeNameAndDebug (nutWallFunctionFvPatchScalarField , 0)
makePatchTypeField() [18/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , omegaWallFunctionFvPatchScalarField)
defineTypeNameAndDebug() [3/5]
Foam::incompressible::defineTypeNameAndDebug (RASModel , 0)
defineRunTimeSelectionTable() [3/4]
Foam::incompressible::defineRunTimeSelectionTable (RASModel , dictionary)
addToRunTimeSelectionTable() [2/3]
Foam::incompressible::addToRunTimeSelectionTable (turbulenceModel , RASModel , turbulenceModel)
makePatchTypeField() [19/19]
Foam::incompressible::makePatchTypeField (fvPatchScalarField , turbulentHeatFluxTemperatureFvPatchScalarField)
defineTypeNameAndDebug() [4/5]
Foam::incompressible::defineTypeNameAndDebug (laminar , 0)
addToRunTimeSelectionTable() [3/3]
Foam::incompressible::addToRunTimeSelectionTable (turbulenceModel , laminar , turbulenceModel)
defineTypeNameAndDebug() [5/5]
Foam::incompressible::defineTypeNameAndDebug (turbulenceModel , 0)
defineRunTimeSelectionTable() [4/4]
Foam::incompressible::defineRunTimeSelectionTable (turbulenceModel , turbulenceModel)