OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::MULES Namespace Reference
Functions
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void correct (const RdeltaTType &rDeltaT, const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su)
template<class RhoType , class SpType , class SuType >
void correct (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void correct (volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const scalar psiMax, const scalar psiMin)
template<class RhoType , class SpType , class SuType >
void LTScorrect (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void LTScorrect (volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const scalar psiMax, const scalar psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limiterCorr (scalarField &allLambda, const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limitCorr (const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter)
template<class RhoType , class SpType , class SuType >
void implicitSolve (const RhoType &rho, volScalarField &gamma, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void implicitSolve (volScalarField &gamma, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const scalar psiMax, const scalar psiMin)
template<class RhoType >
tmp< surfaceScalarField > interpolate (const RhoType &rho)
template<>
tmp< surfaceScalarField > interpolate (const volScalarField &rho)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void explicitSolve (const RdeltaTType &rDeltaT, const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su)
template<class RhoType , class SpType , class SuType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su)
template<class RhoType , class SpType , class SuType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void explicitSolve (volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const scalar psiMax, const scalar psiMin)
template<class RhoType , class SpType , class SuType >
void explicitLTSSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void explicitLTSSolve (volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const scalar psiMax, const scalar psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limiter (scalarField &allLambda, const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phiBD, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limit (const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter, const bool returnCorr)
void limitSum (UPtrList< scalarField > &phiPsiCorrs)
template<class SurfaceScalarFieldList >
void limitSum (SurfaceScalarFieldList &phiPsiCorrs)
Function Documentation
correct() [1/3]
void correct (const RdeltaTType & rDeltaT, const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su)
Definition at line 36 of file CMULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, DimensionedField< Type, GeoMesh >::mesh(), polyMesh::moving(), IOobject::name(), List< T >::size(), and Foam::fvc::surfaceIntegrate().
correct() [2/3]
void correct (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 78 of file CMULESTemplates.C.
References correct, TimeState::deltaTValue(), limitCorr(), dictionary::lookup(), LTScorrect(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), solution::solverDict(), and fvMesh::time().
correct() [3/3]
void correct (volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const scalar psiMax, const scalar psiMin)
Definition at line 31 of file CMULES.C.
References correct, and LTScorrect().
LTScorrect() [1/2]
void LTScorrect (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 117 of file CMULESTemplates.C.
References correct, limitCorr(), limiterCorr(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and solution::solverDict().
Referenced by correct(), for(), if(), and LTScorrect().
LTScorrect() [2/2]
void LTScorrect (volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const scalar psiMax, const scalar psiMin)
Definition at line 52 of file CMULES.C.
References LTScorrect().
limiterCorr()
void limiterCorr (scalarField & allLambda, const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter)
Definition at line 157 of file CMULESTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatchField< Type >::coupled(), Foam::dimless, forAll, GeometricField< Type, PatchField, GeoMesh >::internalField(), lambda(), limitCorr(), dictionary::lookupOrDefault(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), psi, rDeltaT(), List< T >::size(), solution::solverDict(), fvMesh::time(), Time::timeName(), and fvMesh::Vsc().
Referenced by limitCorr(), and LTScorrect().
limitCorr()
void limitCorr (const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter)
Definition at line 477 of file CMULESTemplates.C.
References Foam::dimless, lambda(), limiterCorr(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nFaces(), fvMesh::time(), and Time::timeName().
Referenced by correct(), limiterCorr(), and LTScorrect().
implicitSolve() [1/2]
void implicitSolve (const RhoType & rho, volScalarField & gamma, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
fv::gaussLaplacianScheme<scalar, scalar>(mesh, CDs, snGrads)
.fvmLaplacian(Dpsif, psi)
Definition at line 60 of file IMULESTemplates.C.
References Foam::fvm::ddt(), TimeState::deltaT(), TimeState::deltaTValue(), Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::dimVelocity, Foam::fvc::div(), Foam::endl(), fvMatrix< Type >::flux(), Foam::gMax(), Foam::gMin(), Foam::Info, interpolate(), lambda(), limiter(), dictionary::lookup(), Foam::mag(), fvMesh::magSf(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::name(), primitiveMesh::nFaces(), IOobject::NO_READ, IOobject::NO_WRITE, psi, Foam::readScalar(), rho, Foam::solve(), solution::solverDict(), Foam::fvc::Sp(), Foam::fvm::Sp(), Foam::fvc::Su(), fvMesh::time(), and Time::timeName().
Referenced by implicitSolve(), and interpolate().
implicitSolve() [2/2]
void implicitSolve (volScalarField & gamma, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const scalar psiMax, const scalar psiMin)
Definition at line 31 of file IMULES.C.
References implicitSolve().
interpolate() [1/2]
tmp<surfaceScalarField> Foam::MULES::interpolate (const RhoType & rho) inline
Definition at line 40 of file IMULESTemplates.C.
References notImplemented.
Referenced by Foam::fvc::absolute(), Implicit< CloudType >::cacheFields(), pointLinear< Type >::correction(), for(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), if(), implicitSolve(), interRegionHeatTransferModel::interpolate(), cyclicAMIPolyPatch::interpolate(), cyclicACMIPolyPatch::interpolate(), interpolationCellPointWallModified< Type >::interpolate(), interpolationCellPoint< Foam::Vector >::interpolate(), interpolationPointMVC< Type >::interpolate(), sampledCuttingPlane::interpolateField(), sampledIsoSurface::interpolateField(), distanceSurface::interpolateField(), uniformInterpolationTable< scalar >::interpolateLog10(), PhiScheme< Type, PhiLimiter >::limiter(), interpolationLookUpTable< scalar >::lookUp(), Foam::fvc::makeAbsolute(), Foam::fvc::makeRelative(), Foam::fvc::relative(), GAMGSolver::solve(), while(), AveragingMethod< Foam::Vector >::write(), and interpolate::writeInterpolateField().
interpolate() [2/2]
tmp<surfaceScalarField> Foam::MULES::interpolate (const volScalarField & rho) inline
Definition at line 50 of file IMULESTemplates.C.
References implicitSolve(), and Foam::fvc::interpolate().
explicitSolve() [1/4]
void explicitSolve (const RdeltaTType & rDeltaT, const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su)
Definition at line 37 of file MULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::Info, mesh, DimensionedField< Type, GeoMesh >::mesh(), polyMesh::moving(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), psi, Foam::fvc::surfaceIntegrate(), fvMesh::Vsc(), and fvMesh::Vsc0().
Referenced by explicitLTSSolve(), explicitSolve(), and for().
explicitSolve() [2/4]
void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su)
Definition at line 82 of file MULESTemplates.C.
References TimeState::deltaTValue(), explicitSolve(), mesh, DimensionedField< Type, GeoMesh >::mesh(), and fvMesh::time().
explicitSolve() [3/4]
void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 98 of file MULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), TimeState::deltaTValue(), explicitLTSSolve(), explicitSolve(), limit(), mesh, DimensionedField< Type, GeoMesh >::mesh(), and fvMesh::time().
explicitSolve() [4/4]
void explicitSolve (volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const scalar psiMax, const scalar psiMin)
Definition at line 31 of file MULES.C.
References explicitLTSSolve(), and explicitSolve().
explicitLTSSolve() [1/2]
void explicitLTSSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 119 of file MULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), explicitSolve(), limit(), limiter(), mesh, and DimensionedField< Type, GeoMesh >::mesh().
Referenced by explicitLTSSolve(), explicitSolve(), and for().
explicitLTSSolve() [2/2]
void explicitLTSSolve (volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const scalar psiMax, const scalar psiMin)
Definition at line 52 of file MULES.C.
References explicitLTSSolve().
limiter()
void limiter (scalarField & allLambda, const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phiBD, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter)
Definition at line 143 of file MULESTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatchField< Type >::coupled(), Foam::dimless, forAll, lambda(), limit(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), polyMesh::moving(), fvMesh::neighbour(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), psi, rDeltaT(), List< T >::size(), fvMesh::time(), Time::timeName(), fvMesh::Vsc(), and fvMesh::Vsc0().
Referenced by cellLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::cellLimitedGrad(), limitedSnGrad< Type >::correction(), limiterBlended< Type >::correction(), explicitLTSSolve(), for(), implicitSolve(), limiterBlended< Type >::interpolate(), limit(), PhiScheme< Type, PhiLimiter >::limiter(), multivariateScheme< Type, Scheme >::multivariateScheme(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), limitWith< Type >::weights(), limiterBlended< Type >::weights(), and limitedSurfaceInterpolationScheme< Type >::weights().
limit()
void limit (const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin, const label nLimiterIter, const bool returnCorr)
Definition at line 495 of file MULESTemplates.C.
References Foam::dimless, Foam::fvc::flux(), lambda(), limiter(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nFaces(), phi, fvMesh::time(), and Time::timeName().
Referenced by limiter().
limitSum() [1/2]
void limitSum (UPtrList< scalarField > & phiPsiCorrs)
Definition at line 72 of file MULES.C.
References forAll, lambda(), phasei, UPtrList< T >::size(), and Foam::sum().
Referenced by limitSum().
limitSum() [2/2]
void limitSum (SurfaceScalarFieldList & phiPsiCorrs)
Definition at line 562 of file MULESTemplates.C.
References boundaryField(), forAll, limitSum(), patchi, and phasei.