OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::fvc Namespace Reference
Namespace of functions to calculate explicit derivatives.
Functions
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Area-weighted average a surfaceField creating a volField.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf, const CombineOp &cop)
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > &> tssf, const CombineOp &cop)
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &, const CombineOp &cop)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh &mesh)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf, const one &)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
geometricZeroField ddt (const one &, const one &)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
tmp< surfaceScalarField > meshPhi (const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const dimensionedScalar &rho, const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const volScalarField &rho, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux relative.
void makeAbsolute (surfaceScalarField &phi, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux absolute.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given relative flux in absolute form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given relative flux in absolute form.
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
tmp< volScalarField > reconstructMag (const surfaceScalarField &)
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > &)
void smooth (volScalarField &field, const scalar coeff)
void spread (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2, const scalar alphaMax=0.99, const scalar alphaMin=0.01)
void sweep (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > &su, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tsu, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
void surfaceIntegrate (Field< Type > &ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class Type >
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class Type >
tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, Istream &streamData)
template<class Type >
tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
template<class Type >
tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, Istream &streamData)
Return weighting factors for scheme given from Istream.
template<class Type >
tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const surfaceScalarField &faceFlux, Istream &schemeData)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const surfaceScalarField &faceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const surfaceScalarField &faceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tFaceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const tmp< surfaceScalarField > &tFaceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf)
Interpolate field onto faces using 'interpolate(<name>)'.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
template<class Type >
tmp< FieldField< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
tmp< FieldField< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type > > &tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf)
Interpolate field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type > > &tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
one interpolate (const one &)
Interpolate 'one' returning 'one'.
Detailed Description
Namespace of functions to calculate explicit derivatives.
Function Documentation
average() [1/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 46 of file fvcAverage.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, and surfaceSum().
Referenced by average(), Dual< Type >::average(), Foam::bound(), if(), and PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints().
average() [2/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 93 of file fvcAverage.C.
References average().
average() [3/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > & vtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 109 of file fvcAverage.C.
References average(), and Foam::linearInterpolate().
average() [4/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 120 of file fvcAverage.C.
References average().
cellReduce() [1/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf, const CombineOp & cop)
Definition at line 46 of file fvcCellReduce.C.
References DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, and fvMesh::owner().
Referenced by cellReduce(), and blendingFactor::factor().
cellReduce() [2/3]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > &> tssf, const CombineOp & cop)
Definition at line 97 of file fvcCellReduce.C.
References cellReduce().
cellReduce() [3/3]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & , const CombineOp & cop)
curl() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcCurl.C.
References grad(), IOobject::name(), and Foam::skew().
Referenced by LiftForce< CloudType >::cacheFields(), curl(), and vorticity::execute().
curl() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 68 of file fvcCurl.C.
References curl().
d2dt2() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
d2dt2() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 60 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
DDt() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 45 of file fvcDDt.C.
References ddt(), div(), DimensionedField< Type, GeoMesh >::mesh(), and psi.
Referenced by DDt().
DDt() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 67 of file fvcDDt.C.
References tmp< T >::clear(), and DDt().
ddt() [1/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh & mesh)
Definition at line 45 of file fvcDdt.C.
References fvSchemes::ddtScheme(), dimensioned< Type >::name(), and ddtScheme< Type >::New().
Referenced by PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), DDt(), ddt(), for(), forAll(), forAllConstIter(), forAllIter(), boundedDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvmDdt(), if(), and while().
ddt() [2/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [3/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 76 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [4/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 92 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [5/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 108 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [6/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 131 of file fvcDdt.C.
References ddt().
ddt() [7/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf, const one &)
Definition at line 143 of file fvcDdt.C.
References ddt(), and ddtCorr().
ddtCorr() [1/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by ddt(), ddtCorr(), forAllIter(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and if().
ddtCorr() [2/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
ddtCorr() [3/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddtCorr() [4/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
ddt() [8/8]
geometricZeroField Foam::fvc::ddt (const one & , const one &) inline
Definition at line 106 of file fvcDdt.H.
References ddtCorr(), phi, rho, U, and Uf.
ddtCorr() [5/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by ddt(), ddtCorr(), forAllIter(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and if().
ddtCorr() [6/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
ddtCorr() [7/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddtCorr() [8/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
div() [1/18]
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 47 of file fvcDiv.C.
References IOobject::name(), and surfaceIntegrate().
Referenced by Implicit< CloudType >::cacheFields(), lowReOneEqEddy::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), thixotropicViscosity::correct(), kEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f::correct(), kOmegaSST::correct(), DDt(), div(), laminar::divDevReff(), Smagorinsky2::divDevReff(), scaleSimilarity::divDevReff(), GenEddyVisc::divDevReff(), LamBremhorstKE::divDevReff(), LienLeschzinerLowRe::divDevReff(), LienCubicKE::divDevReff(), NonlinearKEShih::divDevReff(), GenSGSStress::divDevReff(), LaunderSharmaKE::divDevReff(), kEpsilon::divDevReff(), RNGkEpsilon::divDevReff(), LRR::divDevReff(), realizableKE::divDevReff(), LaunderGibsonRSTM::divDevReff(), LienCubicKELowRe::divDevReff(), kOmega::divDevReff(), SpalartAllmaras::divDevReff(), qZeta::divDevReff(), v2f::divDevReff(), kOmegaSSTSAS::divDevReff(), kOmegaSST::divDevReff(), kkLOmega::divDevReff(), GenEddyVisc::divDevRhoBeff(), SpalartAllmaras::divDevRhoBeff(), GenSGSStress::divDevRhoBeff(), laminar::divDevRhoReff(), Smagorinsky2::divDevRhoReff(), scaleSimilarity::divDevRhoReff(), eddyViscosity< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), laminar< BasicTurbulenceModel >::divDevRhoReff(), GenEddyVisc::divDevRhoReff(), LamBremhorstKE::divDevRhoReff(), LienLeschzinerLowRe::divDevRhoReff(), LienCubicKE::divDevRhoReff(), NonlinearKEShih::divDevRhoReff(), GenSGSStress::divDevRhoReff(), kEpsilon::divDevRhoReff(), LRR::divDevRhoReff(), RNGkEpsilon::divDevRhoReff(), LienCubicKELowRe::divDevRhoReff(), LaunderSharmaKE::divDevRhoReff(), realizableKE::divDevRhoReff(), kOmega::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), SpalartAllmaras::divDevRhoReff(), qZeta::divDevRhoReff(), kOmegaSSTSAS::divDevRhoReff(), v2f::divDevRhoReff(), kOmegaSST::divDevRhoReff(), kkLOmega::divDevRhoReff(), for(), forAllConstIter(), forAllIter(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), if(), Foam::MULES::implicitSolve(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), kinematicSingleLayer::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), reactingOneDim::solveSpeciesMass(), while(), div::writeDivField(), and FSD< CombThermoType, ThermoType >::~FSD().
div() [2/18]
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 65 of file fvcDiv.C.
References div().
div() [3/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 84 of file fvcDiv.C.
References div(), DimensionedField< Type, GeoMesh >::mesh(), and divScheme< Type >::New().
div() [4/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvvf, const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
div() [5/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
div() [6/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvvf)
Definition at line 145 of file fvcDiv.C.
References div().
div() [7/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 159 of file fvcDiv.C.
References div(), flux(), DimensionedField< Type, GeoMesh >::mesh(), and convectionScheme< Type >::New().
div() [8/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 177 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [9/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 195 of file fvcDiv.C.
References div().
div() [10/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 213 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [11/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 232 of file fvcDiv.C.
References div(), and IOobject::name().
div() [12/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 247 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [13/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 264 of file fvcDiv.C.
References div().
div() [14/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 281 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [15/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 84 of file fvcDiv.C.
References div(), DimensionedField< Type, GeoMesh >::mesh(), and divScheme< Type >::New().
div() [16/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & , const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
div() [17/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
div() [18/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Definition at line 145 of file fvcDiv.C.
References div().
flux() [1/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcFlux.C.
References DimensionedField< Type, GeoMesh >::mesh(), convectionScheme< Type >::New(), and phi.
Referenced by Foam::fvm::div(), div(), flux(), for(), gaussConvectionScheme< Type >::fvcDiv(), and Foam::MULES::limit().
flux() [2/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 63 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
flux() [3/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 81 of file fvcFlux.C.
References flux().
flux() [4/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 99 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
flux() [5/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 118 of file fvcFlux.C.
References flux(), and IOobject::name().
flux() [6/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 133 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
flux() [7/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 150 of file fvcFlux.C.
References flux().
flux() [8/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 167 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
grad() [1/12]
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 52 of file fvcGrad.C.
References grad(), gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by Smagorinsky2::B(), GenEddyVisc::B(), SpalartAllmaras::B(), kOmegaSSTSAS::B(), GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), LamBremhorstKE::correct(), kEqn< BasicTurbulenceModel >::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), dynLagrangian::correct(), SpalartAllmaras::correct(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), kEpsilon< BasicTurbulenceModel >::correct(), LienCubicKELowRe::correct(), kOmega::correct(), LaunderGibsonRSTM::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f::correct(), kOmegaSSTSAS::correct(), LESModel::correct(), kOmegaSST::correct(), kkLOmega::correct(), cubic< Type >::correction(), Smagorinsky< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), curl(), laminar::devReff(), GenEddyVisc::devReff(), LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), GenSGSStress::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), LRR::devReff(), realizableKE::devReff(), LaunderGibsonRSTM::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSSTSAS::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), GenEddyVisc::devRhoBeff(), SpalartAllmaras::devRhoBeff(), GenSGSStress::devRhoBeff(), laminar::devRhoReff(), eddyViscosity< RASModel< BasicTurbulenceModel > >::devRhoReff(), laminar< BasicTurbulenceModel >::devRhoReff(), kEpsilon::devRhoReff(), LRR::devRhoReff(), RNGkEpsilon::devRhoReff(), LaunderSharmaKE::devRhoReff(), realizableKE::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), SpalartAllmaras::devRhoReff(), v2f::devRhoReff(), kOmegaSST::devRhoReff(), forces::devRhoReff(), laminar::divDevReff(), Smagorinsky2::divDevReff(), GenEddyVisc::divDevReff(), LamBremhorstKE::divDevReff(), LienLeschzinerLowRe::divDevReff(), LienCubicKE::divDevReff(), NonlinearKEShih::divDevReff(), GenSGSStress::divDevReff(), LaunderSharmaKE::divDevReff(), kEpsilon::divDevReff(), RNGkEpsilon::divDevReff(), LRR::divDevReff(), realizableKE::divDevReff(), LaunderGibsonRSTM::divDevReff(), LienCubicKELowRe::divDevReff(), kOmega::divDevReff(), SpalartAllmaras::divDevReff(), qZeta::divDevReff(), v2f::divDevReff(), kOmegaSSTSAS::divDevReff(), kOmegaSST::divDevReff(), kkLOmega::divDevReff(), GenEddyVisc::divDevRhoBeff(), GenSGSStress::divDevRhoBeff(), SpalartAllmaras::divDevRhoBeff(), laminar::divDevRhoReff(), Smagorinsky2::divDevRhoReff(), eddyViscosity< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), laminar< BasicTurbulenceModel >::divDevRhoReff(), GenEddyVisc::divDevRhoReff(), LamBremhorstKE::divDevRhoReff(), LienLeschzinerLowRe::divDevRhoReff(), LienCubicKE::divDevRhoReff(), NonlinearKEShih::divDevRhoReff(), GenSGSStress::divDevRhoReff(), kEpsilon::divDevRhoReff(), LRR::divDevRhoReff(), RNGkEpsilon::divDevRhoReff(), LienCubicKELowRe::divDevRhoReff(), LaunderSharmaKE::divDevRhoReff(), realizableKE::divDevRhoReff(), kOmega::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), SpalartAllmaras::divDevRhoReff(), qZeta::divDevRhoReff(), kOmegaSSTSAS::divDevRhoReff(), v2f::divDevRhoReff(), kOmegaSST::divDevRhoReff(), kkLOmega::divDevRhoReff(), dynLagrangian::dynLagrangian(), dynOneEqEddy::dynOneEqEddy(), laminar::epsilon(), scaleSimilarity::epsilon(), SpalartAllmaras::epsilon(), kOmegaSSTSAS::epsilon(), Lambda2::execute(), Q::execute(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), calcFvcGrad::gradField(), homogeneousDynOneEqEddy::homogeneousDynOneEqEddy(), homogeneousDynSmagorinsky::homogeneousDynSmagorinsky(), if(), spectEddyVisc::k(), Smagorinsky::k(), Smagorinsky< BasicTurbulenceModel >::k(), dynLagrangian::k(), SpalartAllmaras::k(), kOmegaSST::kOmegaSST(), kOmegaSSTSAS::kOmegaSSTSAS(), SpalartAllmaras::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), eddyViscosity< RASModel< BasicTurbulenceModel > >::R(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), kEpsilon::R(), RNGkEpsilon::R(), LienCubicKELowRe::R(), kOmega::R(), realizableKE::R(), LaunderSharmaKE::R(), qZeta::R(), SpalartAllmaras::R(), v2f::R(), kOmegaSST::R(), kkLOmega::R(), realizableKE::realizableKE(), turbulenceModel::rhoEpsilonEff(), skewCorrected< Type >::skewCorrection(), Smagorinsky::Smagorinsky(), displacementSBRStressFvMotionSolver::solve(), spectEddyVisc::spectEddyVisc(), viscosityModel::strainRate(), while(), magGrad::writeMagGradField(), Basic< Type >::~Basic(), FSD< CombThermoType, ThermoType >::~FSD(), and gradScheme< Type >::~gradScheme().
grad() [2/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 69 of file fvcGrad.C.
References grad().
grad() [3/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 92 of file fvcGrad.C.
References grad(), DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
grad() [4/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
grad() [5/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
grad() [6/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 160 of file fvcGrad.C.
References grad().
grad() [7/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 52 of file fvcGrad.C.
References grad(), gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by Smagorinsky2::B(), GenEddyVisc::B(), SpalartAllmaras::B(), kOmegaSSTSAS::B(), GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), LamBremhorstKE::correct(), kEqn< BasicTurbulenceModel >::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), dynLagrangian::correct(), SpalartAllmaras::correct(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), kEpsilon< BasicTurbulenceModel >::correct(), LienCubicKELowRe::correct(), kOmega::correct(), LaunderGibsonRSTM::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f::correct(), kOmegaSSTSAS::correct(), LESModel::correct(), kOmegaSST::correct(), kkLOmega::correct(), cubic< Type >::correction(), Smagorinsky< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), curl(), laminar::devReff(), GenEddyVisc::devReff(), LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), GenSGSStress::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), LRR::devReff(), realizableKE::devReff(), LaunderGibsonRSTM::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSSTSAS::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), GenEddyVisc::devRhoBeff(), SpalartAllmaras::devRhoBeff(), GenSGSStress::devRhoBeff(), laminar::devRhoReff(), eddyViscosity< RASModel< BasicTurbulenceModel > >::devRhoReff(), laminar< BasicTurbulenceModel >::devRhoReff(), kEpsilon::devRhoReff(), LRR::devRhoReff(), RNGkEpsilon::devRhoReff(), LaunderSharmaKE::devRhoReff(), realizableKE::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), SpalartAllmaras::devRhoReff(), v2f::devRhoReff(), kOmegaSST::devRhoReff(), forces::devRhoReff(), laminar::divDevReff(), Smagorinsky2::divDevReff(), GenEddyVisc::divDevReff(), LamBremhorstKE::divDevReff(), LienLeschzinerLowRe::divDevReff(), LienCubicKE::divDevReff(), NonlinearKEShih::divDevReff(), GenSGSStress::divDevReff(), LaunderSharmaKE::divDevReff(), kEpsilon::divDevReff(), RNGkEpsilon::divDevReff(), LRR::divDevReff(), realizableKE::divDevReff(), LaunderGibsonRSTM::divDevReff(), LienCubicKELowRe::divDevReff(), kOmega::divDevReff(), SpalartAllmaras::divDevReff(), qZeta::divDevReff(), v2f::divDevReff(), kOmegaSSTSAS::divDevReff(), kOmegaSST::divDevReff(), kkLOmega::divDevReff(), GenEddyVisc::divDevRhoBeff(), GenSGSStress::divDevRhoBeff(), SpalartAllmaras::divDevRhoBeff(), laminar::divDevRhoReff(), Smagorinsky2::divDevRhoReff(), eddyViscosity< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), laminar< BasicTurbulenceModel >::divDevRhoReff(), GenEddyVisc::divDevRhoReff(), LamBremhorstKE::divDevRhoReff(), LienLeschzinerLowRe::divDevRhoReff(), LienCubicKE::divDevRhoReff(), NonlinearKEShih::divDevRhoReff(), GenSGSStress::divDevRhoReff(), kEpsilon::divDevRhoReff(), LRR::divDevRhoReff(), RNGkEpsilon::divDevRhoReff(), LienCubicKELowRe::divDevRhoReff(), LaunderSharmaKE::divDevRhoReff(), realizableKE::divDevRhoReff(), kOmega::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), SpalartAllmaras::divDevRhoReff(), qZeta::divDevRhoReff(), kOmegaSSTSAS::divDevRhoReff(), v2f::divDevRhoReff(), kOmegaSST::divDevRhoReff(), kkLOmega::divDevRhoReff(), dynLagrangian::dynLagrangian(), dynOneEqEddy::dynOneEqEddy(), laminar::epsilon(), scaleSimilarity::epsilon(), SpalartAllmaras::epsilon(), kOmegaSSTSAS::epsilon(), Lambda2::execute(), Q::execute(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), calcFvcGrad::gradField(), homogeneousDynOneEqEddy::homogeneousDynOneEqEddy(), homogeneousDynSmagorinsky::homogeneousDynSmagorinsky(), if(), spectEddyVisc::k(), Smagorinsky::k(), Smagorinsky< BasicTurbulenceModel >::k(), dynLagrangian::k(), SpalartAllmaras::k(), kOmegaSST::kOmegaSST(), kOmegaSSTSAS::kOmegaSSTSAS(), SpalartAllmaras::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), eddyViscosity< RASModel< BasicTurbulenceModel > >::R(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), kEpsilon::R(), RNGkEpsilon::R(), LienCubicKELowRe::R(), kOmega::R(), realizableKE::R(), LaunderSharmaKE::R(), qZeta::R(), SpalartAllmaras::R(), v2f::R(), kOmegaSST::R(), kkLOmega::R(), realizableKE::realizableKE(), turbulenceModel::rhoEpsilonEff(), skewCorrected< Type >::skewCorrection(), Smagorinsky::Smagorinsky(), displacementSBRStressFvMotionSolver::solve(), spectEddyVisc::spectEddyVisc(), viscosityModel::strainRate(), while(), magGrad::writeMagGradField(), Basic< Type >::~Basic(), FSD< CombThermoType, ThermoType >::~FSD(), and gradScheme< Type >::~gradScheme().
grad() [8/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Definition at line 69 of file fvcGrad.C.
References grad().
grad() [9/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 92 of file fvcGrad.C.
References grad(), DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
grad() [10/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & , const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
grad() [11/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
grad() [12/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Definition at line 160 of file fvcGrad.C.
References grad().
laplacian() [1/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), and laplacianScheme< Type, GType >::New().
Referenced by Implicit< CloudType >::cacheFields(), GenSGSStress::divDevReff(), LRR::divDevReff(), LaunderGibsonRSTM::divDevReff(), GenSGSStress::divDevRhoBeff(), eddyViscosity< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), laminar< BasicTurbulenceModel >::divDevRhoReff(), GenSGSStress::divDevRhoReff(), LRR::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), for(), forAll(), forAllIter(), if(), laplacian(), kOmegaSSTSAS::Lvk2(), laplaceFilter::operator()(), kinematicSingleLayer::pu(), reactingOneDim::solveEnergy(), and while().
laplacian() [2/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 61 of file fvcLaplacian.C.
References laplacian().
laplacian() [3/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [4/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 89 of file fvcLaplacian.C.
References laplacian().
laplacian() [5/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 107 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
laplacian() [6/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 133 of file fvcLaplacian.C.
References laplacian().
laplacian() [7/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 151 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
laplacian() [8/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 176 of file fvcLaplacian.C.
References laplacian().
laplacian() [9/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 195 of file fvcLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), and laplacianScheme< Type, GType >::New().
laplacian() [10/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 212 of file fvcLaplacian.C.
References laplacian().
laplacian() [11/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 230 of file fvcLaplacian.C.
References laplacian().
laplacian() [12/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 248 of file fvcLaplacian.C.
References laplacian().
laplacian() [13/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 267 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [14/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 284 of file fvcLaplacian.C.
References laplacian(), Foam::name(), and IOobject::name().
laplacian() [15/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 301 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [16/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 318 of file fvcLaplacian.C.
References laplacian(), and Foam::name().
laplacian() [17/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 337 of file fvcLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), and laplacianScheme< Type, GType >::New().
laplacian() [18/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 354 of file fvcLaplacian.C.
References laplacian().
laplacian() [19/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 372 of file fvcLaplacian.C.
References laplacian().
laplacian() [20/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 389 of file fvcLaplacian.C.
References laplacian().
laplacian() [21/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 408 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [22/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 425 of file fvcLaplacian.C.
References laplacian().
laplacian() [23/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 442 of file fvcLaplacian.C.
References laplacian().
laplacian() [24/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 458 of file fvcLaplacian.C.
References laplacian().
magSqrGradGrad() [1/2]
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcMagSqrGradGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), grad(), and Foam::magSqr().
Referenced by LaunderSharmaKE::correct(), qZeta::correct(), and magSqrGradGrad().
magSqrGradGrad() [2/2]
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 66 of file fvcMagSqrGradGrad.C.
References magSqrGradGrad().
meshPhi() [1/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volVectorField & U)
Definition at line 33 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and IOobject::name().
Referenced by absolute(), if(), makeAbsolute(), makeRelative(), meshPhi(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), relative(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and while().
meshPhi() [2/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const dimensionedScalar & rho, const volVectorField & U)
Definition at line 46 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), dimensioned< Type >::name(), and IOobject::name().
meshPhi() [3/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volScalarField & rho, const volVectorField & U)
Definition at line 60 of file fvcMeshPhi.C.
References makeRelative(), DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), and IOobject::name().
makeRelative() [1/3]
void makeRelative (surfaceScalarField & phi, const volVectorField & U)
Make the given flux relative.
Definition at line 74 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
Referenced by makeRelative(), and meshPhi().
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux relative.
Definition at line 86 of file fvcMeshPhi.C.
References makeRelative(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
makeRelative() [3/3]
void makeRelative (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux relative.
Definition at line 99 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), makeAbsolute(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
makeAbsolute() [1/3]
void makeAbsolute (surfaceScalarField & phi, const volVectorField & U)
Make the given flux absolute.
Definition at line 113 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
Referenced by makeAbsolute(), and makeRelative().
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux absolute.
Definition at line 125 of file fvcMeshPhi.C.
References makeAbsolute(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
makeAbsolute() [3/3]
void makeAbsolute (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux absolute.
Definition at line 138 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), and relative().
relative() [1/2]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given absolute flux in relative form.
Definition at line 152 of file fvcMeshPhi.C.
References mesh, and meshPhi().
Referenced by pimpleControl::criteriaSatisfied(), and makeAbsolute().
relative() [2/2]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given absolute flux in relative form.
Definition at line 169 of file fvcMeshPhi.C.
References absolute(), Foam::MULES::interpolate(), mesh, and meshPhi().
absolute() [1/2]
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given relative flux in absolute form.
Definition at line 187 of file fvcMeshPhi.C.
References mesh, and meshPhi().
Referenced by kEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), if(), relative(), and while().
absolute() [2/2]
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given relative flux in absolute form.
Definition at line 204 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), mesh, and meshPhi().
reconstruct() [1/4]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, reconstruct(), fvMesh::Sf(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and while().
reconstruct() [2/4]
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
reconstruct() [3/4]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, reconstruct(), fvMesh::Sf(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and while().
reconstruct() [4/4]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
reconstructMag() [1/2]
tmp< volScalarField > reconstructMag (const surfaceScalarField & ssf)
Definition at line 44 of file fvcReconstructMag.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, fvMesh::Sf(), and fvMesh::V().
Referenced by reconstructMag().
reconstructMag() [2/2]
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > & tssf)
Definition at line 118 of file fvcReconstructMag.C.
References tmp< T >::clear(), and reconstructMag().
smooth()
void smooth (volScalarField & field, const scalar coeff)
Definition at line 35 of file fvcSmooth.C.
References List< T >::append(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, polyMesh::globalData(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), globalMeshData::nTotalCells(), fvMesh::owner(), patchi, spread(), and polyPatch::start().
Referenced by if(), lduMatrix::smoother::interfaces(), LduMatrix< Type, DType, LUType >::smoother::matrix(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
spread()
void spread (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2, const scalar alphaMax = 0.99, const scalar alphaMin = 0.01)
Definition at line 124 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), smoothData::trackData::maxRatio, mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), polyPatch::start(), and sweep().
Referenced by if(), and smooth().
sweep()
void sweep (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2)
Definition at line 222 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), FaceCellWave< Type, TrackingData >::data(), primitiveMesh::faceCentres(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), and polyPatch::start().
Referenced by if(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), DILUSmoother::smooth(), DICSmoother::smooth(), FDICSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), and spread().
snGrad() [1/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcSnGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), and snGradScheme< Type >::New().
Referenced by for(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), transformFvPatchField< Type >::gradientBoundaryCoeffs(), if(), anisotropicFilter::operator()(), snGradScheme< Type >::sndGrad(), snGrad(), snGradScheme< Type >::snGrad(), energyRegionCoupledFvPatchScalarField::snGrad(), cyclicACMIFvPatchField< Type >::snGrad(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), externalCoupledMixedFvPatchField< scalar >::transferData(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), and externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
snGrad() [2/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 61 of file fvcSnGrad.C.
References snGrad().
snGrad() [3/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSnGrad.C.
References IOobject::name(), and snGrad().
snGrad() [4/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 89 of file fvcSnGrad.C.
References snGrad().
Su() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > & su, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcSup.C.
Referenced by pressureGradientExplicitSource::addSup(), SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calcVelocity(), for(), forAll(), if(), Foam::MULES::implicitSolve(), laminar< Type >::R(), and RaviPetersen::~RaviPetersen().
Su() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvcSup.C.
References Sp().
Sp() [1/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 67 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), for(), forAllConstIter(), forAllIter(), if(), Foam::MULES::implicitSolve(), Foam::fvm::Sp(), Foam::fvm::Su(), KinematicCloud< Foam::DsmcCloud >::SU(), ReactingCloud< Foam::DsmcCloud >::SYi(), and while().
Sp() [2/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSup.C.
References Sp().
Sp() [3/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 90 of file fvcSup.C.
References SuSp().
SuSp() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 102 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), if(), Foam::fvm::Sp(), and ReactingCloud< Foam::DsmcCloud >::Srho().
SuSp() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 113 of file fvcSup.C.
surfaceIntegrate() [1/3]
void surfaceIntegrate (Field< Type > & ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 44 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, mesh, DimensionedField< Type, GeoMesh >::mesh(), fvMesh::neighbour(), fvMesh::owner(), patchi, and fvMesh::Vsc().
Referenced by Foam::MULES::correct(), div(), Foam::MULES::explicitSolve(), boundedConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvmDiv(), gaussConvectionScheme< Type >::fvmDiv(), anisotropicFilter::operator()(), and surfaceIntegrate().
surfaceIntegrate() [2/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 82 of file fvcSurfaceIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, and surfaceIntegrate().
surfaceIntegrate() [3/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 122 of file fvcSurfaceIntegrate.C.
References surfaceIntegrate(), and surfaceSum().
surfaceSum() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 138 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), and patchi.
Referenced by anisotropicFilter::anisotropicFilter(), average(), kinematicSingleLayer::CourantNumber(), CourantNo::execute(), if(), kinematicSingleLayer::netMass(), simpleFilter::operator()(), reconstruct(), surfaceIntegrate(), and surfaceSum().
surfaceSum() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 193 of file fvcSurfaceIntegrate.C.
References surfaceSum().
volumeIntegrate() [1/4]
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcVolumeIntegrate.C.
References GeometricField< Type, PatchField, GeoMesh >::internalField(), and DimensionedField< Type, GeoMesh >::mesh().
Referenced by domainIntegrate().
volumeIntegrate() [2/4]
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 56 of file fvcVolumeIntegrate.C.
References tmp< T >::clear().
volumeIntegrate() [3/4]
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 67 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::field(), and DimensionedField< Type, GeoMesh >::mesh().
volumeIntegrate() [4/4]
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 75 of file fvcVolumeIntegrate.C.
References tmp< T >::clear(), and domainIntegrate().
domainIntegrate() [1/4]
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 86 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, Foam::gSum(), IOobject::name(), and volumeIntegrate().
Referenced by interRegionHeatTransferModel::addSup(), reactingOneDim::calculateMassTransfer(), kinematicSingleLayer::continuityCheck(), domainIntegrate(), forAll(), if(), ListPlusEqOp< T, Size >::operator()(), volumeIntegrate(), and regionSizeDistribution::write().
domainIntegrate() [2/4]
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 101 of file fvcVolumeIntegrate.C.
References domainIntegrate().
domainIntegrate() [3/4]
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 113 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, domainIntegrate(), Foam::gSum(), IOobject::name(), and volumeIntegrate().
domainIntegrate() [4/4]
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 128 of file fvcVolumeIntegrate.C.
References domainIntegrate().
scheme() [1/8]
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, Istream & streamData)
Definition at line 43 of file surfaceInterpolate.C.
References DimensionedField< Type, GeoMesh >::mesh(), and surfaceInterpolationScheme< Type >::New().
Referenced by cloudSolution::read(), and scheme().
scheme() [2/8]
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, const word & name)
Definition at line 60 of file surfaceInterpolate.C.
References DimensionedField< Type, GeoMesh >::mesh(), surfaceInterpolationScheme< Type >::New(), and scheme().
scheme() [3/8]
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, Istream & streamData)
Return weighting factors for scheme given from Istream.
Definition at line 77 of file surfaceInterpolate.C.
References surfaceInterpolationScheme< Type >::New(), and scheme().
scheme() [4/8]
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, const word & name)
Return weighting factors for scheme given by name in dictionary.
Definition at line 93 of file surfaceInterpolate.C.
References interpolate(), fvSchemes::interpolationScheme(), and surfaceInterpolationScheme< Type >::New().
interpolate() [1/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & faceFlux, Istream & schemeData)
Definition at line 110 of file surfaceInterpolate.C.
References Foam::endl(), and Foam::Info.
Referenced by effectivenessHeatExchangerSource::addSup(), CoBlended< Type >::blendingFactor(), inverseVolumeDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inverseDistanceDiffusivity::correct(), lowReOneEqEddy::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), thixotropicViscosity::correct(), v2f::correct(), kOmegaSST::correct(), Peclet::execute(), ddtScheme< Type >::fvcDdtPhiCoeff(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), Foam::interpolate(), Foam::MULES::interpolate(), interpolate(), kinematicSingleLayer::kinematicSingleLayer(), mixtureKEpsilon< BasicTurbulenceModel >::mixFlux(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), incompressibleTwoPhaseMixture::muf(), kinematicSingleLayer::netMass(), incompressibleTwoPhaseMixture::nuf(), simpleFilter::operator()(), compressibleTurbulenceModel::phi(), dynamicRefineFvMesh::refine(), scheme(), reactingOneDim::solidRegionDiffNo(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), thermoSingleLayer::thermoSingleLayer(), and dynamicRefineFvMesh::unrefine().
interpolate() [2/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & faceFlux, const word & name)
Definition at line 133 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and Foam::name().
interpolate() [3/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const surfaceScalarField & faceFlux, const word & name)
Definition at line 156 of file surfaceInterpolate.C.
References interpolate().
interpolate() [4/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tFaceFlux, const word & name)
Definition at line 174 of file surfaceInterpolate.C.
References tmp< T >::clear(), and interpolate().
interpolate() [5/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const tmp< surfaceScalarField > & tFaceFlux, const word & name)
Definition at line 192 of file surfaceInterpolate.C.
References tmp< T >::clear(), and interpolate().
interpolate() [6/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, Istream & schemeData)
Interpolate field onto faces using scheme given by Istream.
Definition at line 212 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and DimensionedField< Type, GeoMesh >::mesh().
interpolate() [7/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 233 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), DimensionedField< Type, GeoMesh >::mesh(), and Foam::name().
interpolate() [8/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 255 of file surfaceInterpolate.C.
References interpolate().
interpolate() [9/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Interpolate field onto faces using 'interpolate(<name>)'.
Definition at line 273 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and IOobject::name().
interpolate() [10/25]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
Definition at line 294 of file surfaceInterpolate.C.
References interpolate().
interpolate() [11/25]
tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const FieldField< fvPatchField, Type > & fvpff)
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 307 of file surfaceInterpolate.C.
References forAll, interpolate(), patchi, PtrList< Field< Type > >::set(), and PtrList< Field< Type > >::size().
interpolate() [12/25]
tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const tmp< FieldField< fvPatchField, Type > > & tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 332 of file surfaceInterpolate.C.
References interpolate().
scheme() [5/8]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
scheme() [6/8]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, const word & name) static
Return weighting factors for scheme given by name in dictionary.
scheme() [7/8]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
Definition at line 77 of file surfaceInterpolate.C.
References surfaceInterpolationScheme< Type >::New(), and scheme().
scheme() [8/8]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, const word & name) static
Return weighting factors for scheme given by name in dictionary.
Definition at line 93 of file surfaceInterpolate.C.
References interpolate(), fvSchemes::interpolationScheme(), and surfaceInterpolationScheme< Type >::New().
interpolate() [13/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const surfaceScalarField & faceFlux, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
interpolate() [14/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & dir, const word & reconFieldName = word::null) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 7 of file directionInterpolate.H.
References interpolate(), IOobject::name(), word::null, and sf().
interpolate() [15/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const surfaceScalarField & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [16/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [17/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [18/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
Definition at line 212 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and DimensionedField< Type, GeoMesh >::mesh().
interpolate() [19/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 233 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), DimensionedField< Type, GeoMesh >::mesh(), and Foam::name().
interpolate() [20/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 255 of file surfaceInterpolate.C.
References interpolate().
interpolate() [21/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) static
Interpolate tmp field onto faces using 'interpolate(<name>)'.
Definition at line 294 of file surfaceInterpolate.C.
References interpolate().
interpolate() [22/25]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Interpolate field onto faces using 'interpolate(<name>)'.
Definition at line 273 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and IOobject::name().
interpolate() [23/25]
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const FieldField< fvPatchField, Type > & fvpff) static
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 307 of file surfaceInterpolate.C.
References forAll, interpolate(), patchi, PtrList< Field< Type > >::set(), and PtrList< Field< Type > >::size().
interpolate() [24/25]
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const tmp< FieldField< fvPatchField, Type > > & tfvpff) static
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 332 of file surfaceInterpolate.C.
References interpolate().
interpolate() [25/25]
one Foam::fvc::interpolate (const one &) inline
Interpolate 'one' returning 'one'.
Definition at line 189 of file surfaceInterpolate.H.