OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::compressible::RASModels Namespace Reference
Namespace for compressible RAS turbulence models.
Classes
class alphatFilmWallFunctionFvPatchScalarField
This boundary condition provides a turbulent thermal diffusivity condition when using wall functions, for use with surface film models. This condition varies from the standard wall function by taking into account any mass released from the film model.
class fWallFunctionFvPatchScalarField
This boundary condition provides a turbulence damping function, f, wall function condition for low- and high Reynolds number, turbulent flow cases.
class kEpsilon
Standard k-epsilon turbulence model for compressible flows including rapid distortion theory (RDT) based compression term.
class kOmegaSST
Implementation of the k-omega-SST turbulence model for compressible flows.
class laminar
Dummy turbulence model for laminar compressible flow.
class LaunderGibsonRSTM
Launder-Gibson Reynolds stress turbulence model for compressible flows.
class LaunderSharmaKE
Launder and Sharma low-Reynolds k-epsilon turbulence model for compressible and combusting flows including rapid distortion theory (RDT) based compression term.
class LRR
Launder, Reece and Rodi Reynolds-stress turbulence model for compressible flows.
class mutkFilmWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
class PDRkEpsilon
Standard k-epsilon turbulence model with additional source terms corresponding to PDR basic drag model (basic.H)
class realizableKE
Realizable k-epsilon turbulence model for compressible flows.
class RNGkEpsilon
Renormalisation group k-epsilon turbulence model for compressible flows including rapid distortion theory (RDT) based compression term.
class SpalartAllmaras
Spalart-Allmaras one-eqn mixing-length model for compressible external flows.
class v2f
Lien and Kalitzin's v2-f turbulence model for incompressible flows, with a limit imposed on the turbulent viscosity given by Davidson et al.
class v2WallFunctionFvPatchScalarField
This boundary condition provides a turbulence stress normal to streamlines wall function condition for low- and high-Reynolds number, turbulent flow cases.
Functions
makePatchTypeField (fvPatchScalarField, alphatFilmWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, mutkFilmWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, fWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, v2WallFunctionFvPatchScalarField)
defineTypeNameAndDebug (kEpsilon, 0)
addToRunTimeSelectionTable (RASModel, kEpsilon, dictionary)
defineTypeNameAndDebug (kOmegaSST, 0)
addToRunTimeSelectionTable (RASModel, kOmegaSST, dictionary)
defineTypeNameAndDebug (laminar, 0)
addToRunTimeSelectionTable (RASModel, laminar, dictionary)
defineTypeNameAndDebug (LaunderGibsonRSTM, 0)
addToRunTimeSelectionTable (RASModel, LaunderGibsonRSTM, dictionary)
defineTypeNameAndDebug (LaunderSharmaKE, 0)
addToRunTimeSelectionTable (RASModel, LaunderSharmaKE, dictionary)
defineTypeNameAndDebug (LRR, 0)
addToRunTimeSelectionTable (RASModel, LRR, dictionary)
defineTypeNameAndDebug (realizableKE, 0)
addToRunTimeSelectionTable (RASModel, realizableKE, dictionary)
defineTypeNameAndDebug (RNGkEpsilon, 0)
addToRunTimeSelectionTable (RASModel, RNGkEpsilon, dictionary)
defineTypeNameAndDebug (SpalartAllmaras, 0)
addToRunTimeSelectionTable (RASModel, SpalartAllmaras, dictionary)
defineTypeNameAndDebug (v2f, 0)
addToRunTimeSelectionTable (RASModel, v2f, dictionary)
Detailed Description
Namespace for compressible RAS turbulence models.
Function Documentation
makePatchTypeField() [1/4]
Foam::compressible::RASModels::makePatchTypeField (fvPatchScalarField , alphatFilmWallFunctionFvPatchScalarField)
Referenced by mutkFilmWallFunctionFvPatchScalarField::write(), fWallFunctionFvPatchScalarField::write(), v2WallFunctionFvPatchScalarField::write(), and alphatFilmWallFunctionFvPatchScalarField::write().
makePatchTypeField() [2/4]
Foam::compressible::RASModels::makePatchTypeField (fvPatchScalarField , mutkFilmWallFunctionFvPatchScalarField)
makePatchTypeField() [3/4]
Foam::compressible::RASModels::makePatchTypeField (fvPatchScalarField , fWallFunctionFvPatchScalarField)
makePatchTypeField() [4/4]
Foam::compressible::RASModels::makePatchTypeField (fvPatchScalarField , v2WallFunctionFvPatchScalarField)
defineTypeNameAndDebug() [1/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (kEpsilon , 0)
addToRunTimeSelectionTable() [1/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , kEpsilon , dictionary)
defineTypeNameAndDebug() [2/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (kOmegaSST , 0)
addToRunTimeSelectionTable() [2/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , kOmegaSST , dictionary)
defineTypeNameAndDebug() [3/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (laminar , 0)
addToRunTimeSelectionTable() [3/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , laminar , dictionary)
defineTypeNameAndDebug() [4/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (LaunderGibsonRSTM , 0)
addToRunTimeSelectionTable() [4/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , LaunderGibsonRSTM , dictionary)
defineTypeNameAndDebug() [5/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (LaunderSharmaKE , 0)
addToRunTimeSelectionTable() [5/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , LaunderSharmaKE , dictionary)
defineTypeNameAndDebug() [6/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (LRR , 0)
addToRunTimeSelectionTable() [6/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , LRR , dictionary)
defineTypeNameAndDebug() [7/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (realizableKE , 0)
addToRunTimeSelectionTable() [7/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , realizableKE , dictionary)
defineTypeNameAndDebug() [8/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (RNGkEpsilon , 0)
addToRunTimeSelectionTable() [8/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , RNGkEpsilon , dictionary)
defineTypeNameAndDebug() [9/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (SpalartAllmaras , 0)
addToRunTimeSelectionTable() [9/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , SpalartAllmaras , dictionary)
defineTypeNameAndDebug() [10/10]
Foam::compressible::RASModels::defineTypeNameAndDebug (v2f , 0)
addToRunTimeSelectionTable() [10/10]
Foam::compressible::RASModels::addToRunTimeSelectionTable (RASModel , v2f , dictionary)