OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::compressible Namespace Reference
Namespaces
LESModels
Namespace for compressible LES models.
RASModels
Namespace for compressible RAS turbulence models.
turbulenceModels
Namespace for compressible turbulence turbulence models.
Classes
class alphatJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
class alphatWallFunctionFvPatchScalarField
This boundary condition provides a turbulent thermal diffusivity conditon when using wall functions.
class convectiveHeatTransferFvPatchScalarField
This boundary condition provides a convective heat transfer coefficient condition.
class DESModel
Extension of LES models to provide an interface for Detached Eddy Simulation turbulence models.
class epsilonLowReWallFunctionFvPatchScalarField
This boundary condition provides a turbulence dissipation wall function condition for low- and high-Reynolds number turbulent flow cases.
class epsilonWallFunctionFvPatchScalarField
This boundary condition provides a turbulence dissipation wall function condition for high Reynolds number, turbulent flow cases.
class kLowReWallFunctionFvPatchScalarField
This boundary condition provides a turbulence kinetic energy wall function condition for low- and high-Reynolds number turbulent flow cases.
class kqRWallFunctionFvPatchField
This boundary condition is applied to turbulence k, q, and R when using wall functions, and simply enforces a zero-gradient condition.
class laminar
Turbulence model for laminar compressible flow.
class LESdelta
Abstract base class for compressible LES deltas.
class LESModel
Base class for all compressible flow LES SGS models.
class mutkRoughWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on turbulence kinetic energy. The condition manipulates the E parameter to account for roughness effects.
class mutkWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy.
class mutLowReWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition for use with low Reynolds number models. It sets nut to zero, and provides an access function to calculate y+.
class mutURoughWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on velocity.
class mutUSpaldingWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on velocity, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
class mutUWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions, based on velocity.
class mutWallFunctionFvPatchScalarField
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy.
class omegaWallFunctionFvPatchScalarField
This boundary condition provides a wall function constraint on turbulnce specific dissipation, omega. The values are computed using:
class RASModel
Abstract base class for turbulence models for compressible and combusting flows.
class thermalBaffle1DFvPatchScalarField
class thermalBaffleFvPatchScalarField
class turbulenceModel
Abstract base class for compressible turbulence models (RAS, LES and laminar).
class turbulentHeatFluxTemperatureFvPatchScalarField
class turbulentMixingLengthDissipationRateInletFvPatchScalarField
This boundary condition provides a turbulence dissipation, (epsilon) inlet condition based on a specified mixing length. The patch values are calculated using:
class turbulentMixingLengthFrequencyInletFvPatchScalarField
This boundary condition provides a turbulence specific dissipation, (omega) inlet condition based on a specified mixing length. The patch values are calculated using:
class turbulentTemperatureCoupledBaffleMixedFvPatchScalarField
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles.Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
class turbulentTemperatureRadCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
Functions
makePatchTypeField (fvPatchScalarField, thermalBaffleFvPatchScalarField)
defineRunTimeSelectionTable (LESdelta, dictionary)
defineTypeNameAndDebug (LESModel, 0)
defineRunTimeSelectionTable (LESModel, dictionary)
addToRunTimeSelectionTable (turbulenceModel, LESModel, turbulenceModel)
tmp< volScalarField > autoCreateAlphat (const word &fieldName, const fvMesh &mesh)
alphat
tmp< volScalarField > autoCreateMut (const word &fieldName, const fvMesh &mesh)
mut
tmp< volScalarField > autoCreateLowReMut (const word &fieldName, const fvMesh &mesh)
mut for Low-Reynolds number models
tmp< volScalarField > autoCreateEpsilon (const word &fieldName, const fvMesh &mesh)
epsilon
tmp< volScalarField > autoCreateOmega (const word &fieldName, const fvMesh &mesh)
omega
tmp< volScalarField > autoCreateK (const word &fieldName, const fvMesh &mesh)
k
tmp< volScalarField > autoCreateQ (const word &fieldName, const fvMesh &mesh)
Q.
tmp< volSymmTensorField > autoCreateR (const word &fieldName, const fvMesh &mesh)
R.
template<class Type , class PatchType >
tmp< GeometricField< Type, fvPatchField, volMesh > > autoCreateWallFunctionField (const word &fieldName, const fvMesh &mesh)
Helper function to create the new field.
makePatchTypeField (fvPatchScalarField, convectiveHeatTransferFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentMixingLengthDissipationRateInletFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentMixingLengthFrequencyInletFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatJayatillekeWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, epsilonLowReWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, epsilonWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, kLowReWallFunctionFvPatchScalarField)
makePatchFields (kqRWallFunction)
makePatchTypeFieldTypedefs (kqRWallFunction)
makePatchTypeField (fvPatchScalarField, mutkRoughWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, mutkWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, mutLowReWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, mutURoughWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, mutUSpaldingWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, mutUWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (mutWallFunctionFvPatchScalarField, 0)
makePatchTypeField (fvPatchScalarField, omegaWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (RASModel, 0)
defineRunTimeSelectionTable (RASModel, dictionary)
addToRunTimeSelectionTable (turbulenceModel, RASModel, turbulenceModel)
defineTemplateTypeNameAndDebugWithName (constSolid_thermalBaffle1DFvPatchScalarField, "compressible::thermalBaffle1D<hConstSolidThermoPhysics>", 0)
addToPatchFieldRunTimeSelection (fvPatchScalarField, constSolid_thermalBaffle1DFvPatchScalarField)
defineTemplateTypeNameAndDebugWithName (expoSolid_thermalBaffle1DFvPatchScalarField, "compressible::thermalBaffle1D<hExponentialSolidThermoPhysics>", 0)
addToPatchFieldRunTimeSelection (fvPatchScalarField, expoSolid_thermalBaffle1DFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentHeatFluxTemperatureFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureRadCoupledMixedFvPatchScalarField)
defineTypeNameAndDebug (laminar, 0)
addToRunTimeSelectionTable (turbulenceModel, laminar, turbulenceModel)
defineTypeNameAndDebug (turbulenceModel, 0)
defineRunTimeSelectionTable (turbulenceModel, turbulenceModel)
Function Documentation
makePatchTypeField() [1/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , thermalBaffleFvPatchScalarField)
Referenced by epsilonLowReWallFunctionFvPatchScalarField::epsilonLowReWallFunctionFvPatchScalarField(), mutUWallFunctionFvPatchScalarField::write(), mutUSpaldingWallFunctionFvPatchScalarField::write(), turbulentHeatFluxTemperatureFvPatchScalarField::write(), mutkRoughWallFunctionFvPatchScalarField::write(), alphatWallFunctionFvPatchScalarField::write(), convectiveHeatTransferFvPatchScalarField::write(), kLowReWallFunctionFvPatchScalarField::write(), turbulentMixingLengthFrequencyInletFvPatchScalarField::write(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), mutURoughWallFunctionFvPatchScalarField::write(), thermalBaffleFvPatchScalarField::write(), epsilonWallFunctionFvPatchScalarField::write(), omegaWallFunctionFvPatchScalarField::write(), mutkWallFunctionFvPatchScalarField::yPlus(), and mutLowReWallFunctionFvPatchScalarField::yPlus().
defineRunTimeSelectionTable() [1/4]
Foam::compressible::defineRunTimeSelectionTable (LESdelta , dictionary)
defineTypeNameAndDebug() [1/5]
Foam::compressible::defineTypeNameAndDebug (LESModel , 0)
defineRunTimeSelectionTable() [2/4]
Foam::compressible::defineRunTimeSelectionTable (LESModel , dictionary)
addToRunTimeSelectionTable() [1/3]
Foam::compressible::addToRunTimeSelectionTable (turbulenceModel , LESModel , turbulenceModel)
autoCreateAlphat()
tmp<volScalarField> Foam::compressible::autoCreateAlphat (const word & fieldName, const fvMesh & mesh)
alphat
Definition at line 47 of file backwardsCompatibilityWallFunctions.C.
References autoCreateMut(), fvMesh::boundary(), Foam::dimArea, Foam::dimDensity, Foam::dimTime, Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
autoCreateMut()
tmp<volScalarField> Foam::compressible::autoCreateMut (const word & fieldName, const fvMesh & mesh)
mut
Definition at line 117 of file backwardsCompatibilityWallFunctions.C.
References autoCreateLowReMut(), fvMesh::boundary(), Foam::dimArea, Foam::dimDensity, Foam::dimTime, Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
Referenced by autoCreateAlphat().
autoCreateLowReMut()
tmp<volScalarField> Foam::compressible::autoCreateLowReMut (const word & fieldName, const fvMesh & mesh)
mut for Low-Reynolds number models
Definition at line 187 of file backwardsCompatibilityWallFunctions.C.
References autoCreateEpsilon(), fvMesh::boundary(), Foam::dimArea, Foam::dimDensity, Foam::dimTime, Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
Referenced by autoCreateMut().
autoCreateEpsilon()
tmp<volScalarField> Foam::compressible::autoCreateEpsilon (const word & fieldName, const fvMesh & mesh)
epsilon
Definition at line 257 of file backwardsCompatibilityWallFunctions.C.
References autoCreateOmega(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateLowReMut().
autoCreateOmega()
tmp<volScalarField> Foam::compressible::autoCreateOmega (const word & fieldName, const fvMesh & mesh)
omega
Definition at line 276 of file backwardsCompatibilityWallFunctions.C.
References autoCreateK(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateEpsilon().
autoCreateK()
tmp<volScalarField> Foam::compressible::autoCreateK (const word & fieldName, const fvMesh & mesh)
k
Definition at line 295 of file backwardsCompatibilityWallFunctions.C.
References autoCreateQ(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateOmega().
autoCreateQ()
tmp<volScalarField> Foam::compressible::autoCreateQ (const word & fieldName, const fvMesh & mesh)
Q.
Definition at line 314 of file backwardsCompatibilityWallFunctions.C.
References autoCreateR(), autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateK().
autoCreateR()
tmp<volSymmTensorField> Foam::compressible::autoCreateR (const word & fieldName, const fvMesh & mesh)
R.
Definition at line 333 of file backwardsCompatibilityWallFunctions.C.
References autoCreateWallFunctionField(), and mesh.
Referenced by autoCreateQ().
autoCreateWallFunctionField()
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::compressible::autoCreateWallFunctionField (const word & fieldName, const fvMesh & mesh)
Helper function to create the new field.
Definition at line 44 of file backwardsCompatibilityWallFunctionsTemplates.C.
References fvMesh::boundary(), boundaryField(), Foam::endl(), forAll, Foam::Info, mesh, IOobject::MUST_READ, Foam::mvBak(), IOobject::NO_READ, IOobject::NO_WRITE, PtrList< T >::size(), fvMesh::time(), and Time::timeName().
Referenced by autoCreateEpsilon(), autoCreateK(), autoCreateOmega(), autoCreateQ(), and autoCreateR().
makePatchTypeField() [2/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , convectiveHeatTransferFvPatchScalarField)
makePatchTypeField() [3/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentMixingLengthDissipationRateInletFvPatchScalarField)
makePatchTypeField() [4/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentMixingLengthFrequencyInletFvPatchScalarField)
makePatchTypeField() [5/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatJayatillekeWallFunctionFvPatchScalarField)
makePatchTypeField() [6/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatWallFunctionFvPatchScalarField)
makePatchTypeField() [7/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , epsilonLowReWallFunctionFvPatchScalarField)
makePatchTypeField() [8/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , epsilonWallFunctionFvPatchScalarField)
makePatchTypeField() [9/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , kLowReWallFunctionFvPatchScalarField)
makePatchFields()
Foam::compressible::makePatchFields (kqRWallFunction)
makePatchTypeFieldTypedefs()
Foam::compressible::makePatchTypeFieldTypedefs (kqRWallFunction)
makePatchTypeField() [10/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , mutkRoughWallFunctionFvPatchScalarField)
makePatchTypeField() [11/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , mutkWallFunctionFvPatchScalarField)
makePatchTypeField() [12/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , mutLowReWallFunctionFvPatchScalarField)
makePatchTypeField() [13/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , mutURoughWallFunctionFvPatchScalarField)
makePatchTypeField() [14/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , mutUSpaldingWallFunctionFvPatchScalarField)
makePatchTypeField() [15/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , mutUWallFunctionFvPatchScalarField)
defineTypeNameAndDebug() [2/5]
Foam::compressible::defineTypeNameAndDebug (mutWallFunctionFvPatchScalarField , 0)
makePatchTypeField() [16/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , omegaWallFunctionFvPatchScalarField)
defineTypeNameAndDebug() [3/5]
Foam::compressible::defineTypeNameAndDebug (RASModel , 0)
defineRunTimeSelectionTable() [3/4]
Foam::compressible::defineRunTimeSelectionTable (RASModel , dictionary)
addToRunTimeSelectionTable() [2/3]
Foam::compressible::addToRunTimeSelectionTable (turbulenceModel , RASModel , turbulenceModel)
defineTemplateTypeNameAndDebugWithName() [1/2]
Foam::compressible::defineTemplateTypeNameAndDebugWithName (constSolid_thermalBaffle1DFvPatchScalarField , "compressible::thermalBaffle1D<hConstSolidThermoPhysics>" , 0)
addToPatchFieldRunTimeSelection() [1/2]
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , constSolid_thermalBaffle1DFvPatchScalarField)
defineTemplateTypeNameAndDebugWithName() [2/2]
Foam::compressible::defineTemplateTypeNameAndDebugWithName (expoSolid_thermalBaffle1DFvPatchScalarField , "compressible::thermalBaffle1D<hExponentialSolidThermoPhysics>" , 0)
addToPatchFieldRunTimeSelection() [2/2]
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , expoSolid_thermalBaffle1DFvPatchScalarField)
makePatchTypeField() [17/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentHeatFluxTemperatureFvPatchScalarField)
makePatchTypeField() [18/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
makePatchTypeField() [19/19]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureRadCoupledMixedFvPatchScalarField)
defineTypeNameAndDebug() [4/5]
Foam::compressible::defineTypeNameAndDebug (laminar , 0)
addToRunTimeSelectionTable() [3/3]
Foam::compressible::addToRunTimeSelectionTable (turbulenceModel , laminar , turbulenceModel)
defineTypeNameAndDebug() [5/5]
Foam::compressible::defineTypeNameAndDebug (turbulenceModel , 0)
defineRunTimeSelectionTable() [4/4]
Foam::compressible::defineRunTimeSelectionTable (turbulenceModel , turbulenceModel)