OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
consumptionSpeed Class Reference
Public Member Functions
TypeName ("consumptionSpeed")
Runtime type information.
consumptionSpeed (const dictionary &dict)
Construct from dictionary.
virtual ~consumptionSpeed ()
Destructor.
tmp< volScalarField > omega0Sigma (const volScalarField &sigma)
Return speed consumption rate temp.
scalar omega0 () const
scalar eta () const
scalar sigmaExt () const
scalar omegaMin () const
void read (const dictionary &dict)
Update properties.
Detailed Description
Definition at line 49 of file consumptionSpeed.H.
Constructor & Destructor Documentation
consumptionSpeed()
consumptionSpeed (const dictionary & dict)
Construct from dictionary.
Definition at line 39 of file consumptionSpeed.C.
~consumptionSpeed()
~consumptionSpeed () virtual
Destructor.
Definition at line 51 of file consumptionSpeed.C.
References Foam::exp(), Foam::max(), and Foam::constant::physicoChemical::sigma.
Member Function Documentation
TypeName()
TypeName ("consumptionSpeed")
Runtime type information.
omega0Sigma()
Foam::tmp< Foam::volScalarField > omega0Sigma (const volScalarField & sigma)
Return speed consumption rate temp.
Definition at line 78 of file consumptionSpeed.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), IOobject::db(), forAll, GeometricField< Type, PatchField, GeoMesh >::internalField(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, IOobject::time(), and Time::timeName().
omega0()
scalar omega0 () const inline
Definition at line 103 of file consumptionSpeed.H.
eta()
scalar eta () const inline
Definition at line 108 of file consumptionSpeed.H.
sigmaExt()
scalar sigmaExt () const inline
Definition at line 113 of file consumptionSpeed.H.
omegaMin()
scalar omegaMin () const inline
Definition at line 118 of file consumptionSpeed.H.
References consumptionSpeed::read().
read()
void read (const dictionary & dict)
Update properties.
Definition at line 132 of file consumptionSpeed.C.
References dictionary::lookup().
Referenced by consumptionSpeed::omegaMin().
The documentation for this class was generated from the following files:
src/combustionModels/FSD/reactionRateFlameAreaModels/consumptionSpeed/consumptionSpeed.H
src/combustionModels/FSD/reactionRateFlameAreaModels/consumptionSpeed/consumptionSpeed.C