OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
singleStepCombustion< CombThermoType, ThermoType > Class Template Reference
Base class for combustion models using singleStepReactingMixture.
Public Member Functions
singleStepCombustion (const word &modelType, const fvMesh &mesh)
Construct from components.
virtual ~singleStepCombustion ()
Destructor.
virtual tmp< fvScalarMatrix > R (volScalarField &Y) const
Fuel consumption rate matrix.
virtual tmp< volScalarField > dQ () const
Heat release rate calculated from fuel consumption rate matrix.
virtual tmp< volScalarField > Sh () const
Sensible enthalpy source term.
virtual bool read ()
Update properties from given dictionary.
Protected Attributes
singleStepReactingMixture< ThermoType > * singleMixturePtr_
Pointer to singleStepReactingMixture mixture.
volScalarField wFuel_
Fuel consumption rate.
bool semiImplicit_
Semi-implicit (true) or explicit (false) treatment.
Detailed Description
template<class CombThermoType, class ThermoType>
class Foam::combustionModels::singleStepCombustion< CombThermoType, ThermoType >
Base class for combustion models using singleStepReactingMixture.
Source files
singleStepCombustion.H
singleStepCombustion.C
Definition at line 51 of file singleStepCombustion.H.
Constructor & Destructor Documentation
singleStepCombustion()
singleStepCombustion (const word & modelType, const fvMesh & mesh)
Construct from components.
Definition at line 38 of file singleStepCombustion.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, Foam::isA(), Foam::nl, thermo, and Foam::type().
~singleStepCombustion()
~singleStepCombustion () virtual
Destructor.
Definition at line 99 of file singleStepCombustion.C.
References singleStepCombustion< CombThermoType, ThermoType >::R().
Member Function Documentation
R()
tmp< fvScalarMatrix > R (volScalarField & Y) const virtual
Fuel consumption rate matrix.
Definition at line 107 of file singleStepCombustion.C.
References Foam::e, Foam::max(), IOobject::name(), and Foam::fvm::Sp().
Referenced by singleStepCombustion< CombThermoType, ThermoType >::~singleStepCombustion().
dQ()
tmp< volScalarField > dQ () const virtual
Heat release rate calculated from fuel consumption rate matrix.
Definition at line 147 of file singleStepCombustion.C.
References Foam::dimEnergy, GeometricField< Type, PatchField, GeoMesh >::dimensionedInternalField(), Foam::dimTime, dQ, mesh, IOobject::NO_READ, IOobject::NO_WRITE, and Sh.
Sh()
tmp< volScalarField > Sh () const virtual
Sensible enthalpy source term.
Definition at line 135 of file singleStepCombustion.C.
References R.
read()
bool read () virtual
Update properties from given dictionary.
Reimplemented in FSD< CombThermoType, ThermoType >, diffusion< CombThermoType, ThermoType >, and infinitelyFastChemistry< CombThermoType, ThermoType >.
Definition at line 178 of file singleStepCombustion.C.
Member Data Documentation
singleMixturePtr_
singleStepReactingMixture<ThermoType>* singleMixturePtr_ protected
Pointer to singleStepReactingMixture mixture.
Definition at line 69 of file singleStepCombustion.H.
wFuel_
volScalarField wFuel_ protected
Fuel consumption rate.
Definition at line 72 of file singleStepCombustion.H.
semiImplicit_
bool semiImplicit_ protected
Semi-implicit (true) or explicit (false) treatment.
Definition at line 75 of file singleStepCombustion.H.
The documentation for this class was generated from the following files:
src/combustionModels/singleStepCombustion/singleStepCombustion.H
src/combustionModels/singleStepCombustion/singleStepCombustion.C