OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reactionRateFlameArea Class Reference abstract
Abstract class for reaction rate per flame area unit.
Public Member Functions
TypeName ("reactionRateFlameArea")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, reactionRateFlameArea, dictionary,(const word modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel),(modelType, dict, mesh, combModel))
reactionRateFlameArea (const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Construct from dictionary and psiReactionThermo.
reactionRateFlameArea (const word &modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Construct from components.
virtual ~reactionRateFlameArea ()
const volScalarField & omega () const
Access functions.
virtual void correct (const volScalarField &sigma)=0
Correct omega.
virtual bool read (const dictionary &dictProperties)
Update from dictionary.
Static Public Member Functions
static autoPtr< reactionRateFlameArea > New (const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Protected Attributes
dictionary coeffDict_
Dictionary.
const fvMesh & mesh_
Mesh reference.
const combustionModel & combModel_
Combstion model owner.
word fuel_
Fuel name.
volScalarField omega_
Fuel consumption rate per unit of flame area.
Detailed Description
Abstract class for reaction rate per flame area unit.
Source files
reactionRateFlameArea.H
reactionRateFlameArea.C
reactionRateFlameAreaNew.C
Definition at line 54 of file reactionRateFlameArea.H.
Constructor & Destructor Documentation
reactionRateFlameArea() [1/2]
reactionRateFlameArea (const dictionary & dict, const fvMesh & mesh, const combustionModel & combModel)
Construct from dictionary and psiReactionThermo.
Definition at line 40 of file reactionRateFlameArea.C.
reactionRateFlameArea() [2/2]
reactionRateFlameArea (const word & modelType, const dictionary & dict, const fvMesh & mesh, const combustionModel & combModel)
Construct from components.
Definition at line 67 of file reactionRateFlameArea.C.
~reactionRateFlameArea()
~reactionRateFlameArea () virtual
Definition at line 95 of file reactionRateFlameArea.C.
Member Function Documentation
TypeName()
TypeName ("reactionRateFlameArea")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , reactionRateFlameArea , dictionary , (const word modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel) , (modelType, dict, mesh, combModel))
New()
Foam::autoPtr< Foam::reactionRateFlameArea > New (const dictionary & dict, const fvMesh & mesh, const combustionModel & combModel) static
Definition at line 31 of file reactionRateFlameAreaNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, dictionary::lookup(), and mesh.
omega()
const volScalarField& omega () const inline
Access functions.
Return omega
Definition at line 151 of file reactionRateFlameArea.H.
References reactionRateFlameArea::correct(), reactionRateFlameArea::omega_, reactionRateFlameArea::read(), and Foam::constant::physicoChemical::sigma.
correct()
virtual void correct (const volScalarField & sigma) pure virtual
Correct omega.
Implemented in relaxation.
Referenced by reactionRateFlameArea::omega().
read()
bool read (const dictionary & dictProperties) virtual
Update from dictionary.
Reimplemented in relaxation.
Definition at line 101 of file reactionRateFlameArea.C.
References dictionary::lookup().
Referenced by reactionRateFlameArea::omega(), and relaxation::read().
Member Data Documentation
coeffDict_
dictionary coeffDict_ protected
Dictionary.
Definition at line 62 of file reactionRateFlameArea.H.
mesh_
const fvMesh& mesh_ protected
Mesh reference.
Definition at line 65 of file reactionRateFlameArea.H.
combModel_
const combustionModel& combModel_ protected
Combstion model owner.
Definition at line 68 of file reactionRateFlameArea.H.
fuel_
word fuel_ protected
Fuel name.
Definition at line 71 of file reactionRateFlameArea.H.
omega_
volScalarField omega_ protected
Fuel consumption rate per unit of flame area.
Definition at line 74 of file reactionRateFlameArea.H.
Referenced by reactionRateFlameArea::omega().
The documentation for this class was generated from the following files:
src/combustionModels/FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameArea.H
src/combustionModels/FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameArea.C
src/combustionModels/FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameAreaNew.C