OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
infinitelyFastChemistry< CombThermoType, ThermoType > Class Template Reference
Simple infinitely fast chemistry combustion model based on the principle mixed is burnt. Additional parameter C is used to distribute the heat release rate.in time.
Public Member Functions
TypeName ("infinitelyFastChemistry")
Runtime type information.
infinitelyFastChemistry (const word &modelType, const fvMesh &mesh)
Construct from components.
virtual ~infinitelyFastChemistry ()
Destructor.
virtual void correct ()
Correct combustion rate.
virtual bool read ()
Update properties.
Public Member Functions inherited from singleStepCombustion< CombThermoType, ThermoType >
singleStepCombustion (const word &modelType, const fvMesh &mesh)
Construct from components.
virtual ~singleStepCombustion ()
Destructor.
virtual tmp< fvScalarMatrix > R (volScalarField &Y) const
Fuel consumption rate matrix.
virtual tmp< volScalarField > dQ () const
Heat release rate calculated from fuel consumption rate matrix.
virtual tmp< volScalarField > Sh () const
Sensible enthalpy source term.
Additional Inherited Members
Protected Attributes inherited from singleStepCombustion< CombThermoType, ThermoType >
singleStepReactingMixture< ThermoType > * singleMixturePtr_
Pointer to singleStepReactingMixture mixture.
volScalarField wFuel_
Fuel consumption rate.
bool semiImplicit_
Semi-implicit (true) or explicit (false) treatment.
Detailed Description
template<class CombThermoType, class ThermoType>
class Foam::combustionModels::infinitelyFastChemistry< CombThermoType, ThermoType >
Simple infinitely fast chemistry combustion model based on the principle mixed is burnt. Additional parameter C is used to distribute the heat release rate.in time.
Source files
infinitelyFastChemistry.H
infinitelyFastChemistry.C
Definition at line 53 of file infinitelyFastChemistry.H.
Constructor & Destructor Documentation
infinitelyFastChemistry()
infinitelyFastChemistry (const word & modelType, const fvMesh & mesh)
Construct from components.
Definition at line 37 of file infinitelyFastChemistry.C.
~infinitelyFastChemistry()
~infinitelyFastChemistry () virtual
Destructor.
Definition at line 49 of file infinitelyFastChemistry.C.
Member Function Documentation
TypeName()
TypeName ("infinitelyFastChemistry< CombThermoType, ThermoType >")
Runtime type information.
correct()
void correct () virtual
Correct combustion rate.
Definition at line 56 of file infinitelyFastChemistry.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, mesh, Foam::min(), Foam::pow3(), rho, s(), and dimensioned< Type >::value().
read()
bool read () virtual
Update properties.
Reimplemented from singleStepCombustion< CombThermoType, ThermoType >.
Definition at line 85 of file infinitelyFastChemistry.C.
The documentation for this class was generated from the following files:
src/combustionModels/infinitelyFastChemistry/infinitelyFastChemistry.H
src/combustionModels/infinitelyFastChemistry/infinitelyFastChemistry.C