OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meshReader Class Reference abstract
This class supports creating polyMeshes with baffles.
Classes
class cellFaceIdentifier
Identify cell faces in terms of cell Id and face Id.
Public Member Functions
meshReader (const fileName &, const scalar scaleFactor=1.0)
Construct from fileName.
virtual ~meshReader ()
Destructor.
virtual autoPtr< polyMesh > mesh (const objectRegistry &)
Create and return polyMesh.
void writeAux (const objectRegistry &) const
Write auxiliary information.
void writeMesh (const polyMesh &, IOstream::streamFormat fmt=IOstream::BINARY) const
Write mesh.
Static Public Member Functions
static void warnDuplicates (const word &context, const wordList &)
Warn about repeated names.
Protected Member Functions
virtual bool readGeometry (const scalar scaleFactor=1.0)=0
Subclasses are required to supply this information.
Protected Attributes
fileName geometryFile_
Referenced filename.
scalar scaleFactor_
Geometry scaling.
pointField points_
Points supporting the mesh.
labelList origCellId_
Lookup original Cell number for a given cell.
List< List< cellFaceIdentifier > > boundaryIds_
Identify boundary faces by cells and their faces.
wordList patchTypes_
Boundary patch types.
wordList patchNames_
Boundary patch names.
wordList patchPhysicalTypes_
Boundary patch physical types.
faceListList cellFaces_
List of faces for every cell.
faceList baffleFaces_
List of each baffle face.
labelList cellTableId_
Cell table id for each cell.
cellTable cellTable_
Cell table persistent data saved as a dictionary.
Static Protected Attributes
static const cellModel * unknownModel
Pointers to cell shape models.
static const cellModel * tetModel
static const cellModel * pyrModel
static const cellModel * prismModel
static const cellModel * hexModel
Detailed Description
This class supports creating polyMeshes with baffles.
The derived classes are responsible for providing the protected data. This implementation is somewhat messy, but could/should be restructured to provide a more generalized reader (at the moment it has been written for converting pro-STAR data).
The meshReader supports cellTable information (see new user's guide entry).
Note
The boundary definitions are given as cell/face.
Source files
meshReader.H
calcPointCells.C
createPolyBoundary.C
createPolyCells.C
meshReader.C
meshReaderAux.C
Definition at line 73 of file meshReader.H.
Constructor & Destructor Documentation
meshReader()
meshReader (const fileName & fileOrPrefix, const scalar scaleFactor = 1.0)
Construct from fileName.
Definition at line 195 of file meshReader.C.
~meshReader()
~meshReader () virtual
Destructor.
Definition at line 225 of file meshReader.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
readGeometry()
virtual bool readGeometry (const scalar scaleFactor = 1.0) protected pure virtual
Subclasses are required to supply this information.
Implemented in STARCD.
Referenced by meshReader::mesh().
warnDuplicates()
void warnDuplicates (const word & context, const wordList & list) static
Warn about repeated names.
Definition at line 34 of file meshReaderAux.C.
References IOobject::AUTO_WRITE, TimePaths::constant(), IOstream::currentVersion, HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, forAllConstIter(), Foam::Info, HashTable< T, Key, Hash >::insert(), polyMesh::meshSubDir, IOobject::name(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, IOobject::note(), IOobject::objectPath(), List< T >::size(), objectRegistry::time(), IOstream::UNCOMPRESSED, IOobject::writeEndDivider(), IOobject::writeHeader(), and regIOobject::writeObject().
Referenced by meshReader::mesh().
mesh()
Foam::autoPtr< Foam::polyMesh > mesh (const objectRegistry & registry) virtual
Create and return polyMesh.
Definition at line 120 of file meshReader.C.
References TimePaths::constant(), polyMesh::defaultRegion, Foam::endl(), Foam::Info, meshReader::points_, meshReader::readGeometry(), objectRegistry::time(), meshReader::warnDuplicates(), meshReader::writeMesh(), and Foam::xferMove().
writeAux()
void writeAux (const objectRegistry & registry) const
Write auxiliary information.
Definition at line 147 of file meshReaderAux.C.
References IOstream::ASCII, IOstream::BINARY, meshReader::cellTable_, meshReader::cellTableId_, meshReader::origCellId_, and cellTable::writeDict().
Referenced by meshReader::writeMesh().
writeMesh()
void writeMesh (const polyMesh & mesh, IOstream::streamFormat fmt = IOstream::BINARY) const
Write mesh.
Definition at line 163 of file meshReader.C.
References meshReader::baffleFaces_, meshReader::boundaryIds_, meshReader::cellFaces_, List< T >::clear(), IOstream::currentVersion, Foam::deleteDemandDrivenData(), Foam::endl(), Foam::Info, polyMesh::removeFiles(), IOstream::UNCOMPRESSED, meshReader::writeAux(), and objectRegistry::writeObject().
Referenced by meshReader::mesh().
Member Data Documentation
unknownModel
const Foam::cellModel * unknownModel static protected
Initial value:
= Foam::cellModeller::
lookup
(
    "unknown"
)
Pointers to cell shape models.
Definition at line 243 of file meshReader.H.
Referenced by STARCD::readCells().
tetModel
const Foam::cellModel * tetModel static protected
Initial value:
= Foam::cellModeller::
lookup
(
    "tet"
)
Definition at line 244 of file meshReader.H.
Referenced by STARCD::readBoundary(), and STARCD::readCells().
pyrModel
const Foam::cellModel * pyrModel static protected
Initial value:
= Foam::cellModeller::
lookup
(
    "pyr"
)
Definition at line 245 of file meshReader.H.
Referenced by STARCD::readBoundary(), and STARCD::readCells().
prismModel
const Foam::cellModel * prismModel static protected
Initial value:
= Foam::cellModeller::
lookup
(
    "prism"
)
Definition at line 246 of file meshReader.H.
Referenced by STARCD::readBoundary(), and STARCD::readCells().
hexModel
const Foam::cellModel * hexModel static protected
Initial value:
= Foam::cellModeller::
lookup
(
    "hex"
)
Definition at line 247 of file meshReader.H.
Referenced by STARCD::readBoundary(), and STARCD::readCells().
geometryFile_
fileName geometryFile_ protected
Referenced filename.
Definition at line 250 of file meshReader.H.
Referenced by STARCD::readGeometry().
scaleFactor_
scalar scaleFactor_ protected
Geometry scaling.
Definition at line 253 of file meshReader.H.
points_
pointField points_ protected
Points supporting the mesh.
Definition at line 256 of file meshReader.H.
Referenced by STARCD::cullPoints(), meshReader::mesh(), and STARCD::readPoints().
origCellId_
labelList origCellId_ protected
Lookup original Cell number for a given cell.
Definition at line 259 of file meshReader.H.
Referenced by STARCD::readCells(), and meshReader::writeAux().
boundaryIds_
List<List<cellFaceIdentifier> > boundaryIds_ protected
Identify boundary faces by cells and their faces.
for each patch
Definition at line 263 of file meshReader.H.
Referenced by STARCD::readBoundary(), and meshReader::writeMesh().
patchTypes_
wordList patchTypes_ protected
Boundary patch types.
Definition at line 266 of file meshReader.H.
Referenced by STARCD::readBoundary().
patchNames_
wordList patchNames_ protected
Boundary patch names.
Definition at line 269 of file meshReader.H.
Referenced by STARCD::readBoundary().
patchPhysicalTypes_
wordList patchPhysicalTypes_ protected
Boundary patch physical types.
Definition at line 272 of file meshReader.H.
Referenced by STARCD::readBoundary().
cellFaces_
faceListList cellFaces_ protected
List of faces for every cell.
Definition at line 275 of file meshReader.H.
Referenced by STARCD::cullPoints(), STARCD::readCells(), and meshReader::writeMesh().
baffleFaces_
faceList baffleFaces_ protected
List of each baffle face.
Definition at line 278 of file meshReader.H.
Referenced by STARCD::cullPoints(), STARCD::readCells(), and meshReader::writeMesh().
cellTableId_
labelList cellTableId_ protected
Cell table id for each cell.
Definition at line 281 of file meshReader.H.
Referenced by STARCD::readCells(), and meshReader::writeAux().
cellTable_
cellTable cellTable_ protected
Cell table persistent data saved as a dictionary.
Definition at line 284 of file meshReader.H.
Referenced by STARCD::readAux(), STARCD::readCells(), and meshReader::writeAux().
The documentation for this class was generated from the following files:
src/conversion/meshReader/meshReader.H
src/conversion/meshReader/calcPointCells.C
src/conversion/meshReader/createPolyBoundary.C
src/conversion/meshReader/createPolyCells.C
src/conversion/meshReader/meshReader.C
src/conversion/meshReader/meshReaderAux.C