OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STARCD Class Reference
Writes polyMesh in pro-STAR (v4) bnd/cel/vrt format.
Public Member Functions
STARCD (const polyMesh &, const scalar scaleFactor=1.0)
Open a file for writing.
virtual ~STARCD ()
Destructor.
void rmFiles (const fileName &baseName) const
Remove STAR-CD files for the baseName.
virtual bool write (const fileName &meshName=fileName::null) const
Write volume mesh.
Public Member Functions inherited from meshWriter
meshWriter (const polyMesh &, const scalar scaleFactor=1.0)
Create a writer obejct.
virtual ~meshWriter ()
Destructor.
void scaleFactor (const scalar scaling)
Set points scaling.
void noBoundary ()
Suppress writing bnd file.
Static Public Attributes
static const label foamToStarFaceAddr [4][6]
Face addressing from OpenFOAM faces -> pro-STAR faces.
Static Public Attributes inherited from meshWriter
static string defaultMeshName = "meshExport"
Specify a default mesh name.
Additional Inherited Members
Protected Attributes inherited from meshWriter
const polyMesh & mesh_
Mesh reference.
scalar scaleFactor_
Scaling factor for points (eg, [m] -> [mm])
bool writeBoundary_
Write bnd file.
boundaryRegion boundaryRegion_
boundaryRegion persistent data saved as a dictionary
cellTable cellTable_
cellTable persistent data saved as a dictionary
labelList cellTableId_
cellTable IDs for each cell
Static Protected Attributes inherited from meshWriter
static const cellModel * unknownModel
Pointers to cell shape models.
static const cellModel * tetModel
static const cellModel * pyrModel
static const cellModel * prismModel
static const cellModel * hexModel
Detailed Description
Writes polyMesh in pro-STAR (v4) bnd/cel/vrt format.
The cellTableId and cellTable information are used (if available). Otherwise the cellZones are used (if available).
Source files
STARCDMeshWriter.H
STARCDMeshWriter.C
Definition at line 55 of file STARCDMeshWriter.H.
Constructor & Destructor Documentation
STARCD()
STARCD (const polyMesh & mesh, const scalar scaleFactor = 1.0)
Open a file for writing.
Definition at line 468 of file STARCDMeshWriter.C.
References meshWriter::boundaryRegion_, meshWriter::cellTable_, meshWriter::mesh_, boundaryRegion::readDict(), and cellTable::readDict().
~STARCD()
~STARCD () virtual
Destructor.
Definition at line 483 of file STARCDMeshWriter.C.
Member Function Documentation
rmFiles()
void rmFiles (const fileName & baseName) const
Remove STAR-CD files for the baseName.
Definition at line 489 of file STARCDMeshWriter.C.
References Foam::rm().
Referenced by STARCD::write().
write()
bool write (const fileName & meshName = fileName::null) const virtual
Write volume mesh.
Implements meshWriter.
Definition at line 498 of file STARCDMeshWriter.C.
References TimePaths::constant(), meshWriter::defaultMeshName, meshWriter::mesh_, STARCD::rmFiles(), objectRegistry::time(), Time::timeName(), and meshWriter::writeBoundary_.
Member Data Documentation
foamToStarFaceAddr
const Foam::label foamToStarFaceAddr static
Initial value:
=
{
    { 4, 5, 2, 3, 0, 1 },
    { 0, 1, 4, 5, 2, -1 },
    { 5, 4, 2, 0, -1, -1 },
    { 0, 4, 3, 5, 2, -1 }
}
Face addressing from OpenFOAM faces -> pro-STAR faces.
Definition at line 94 of file STARCDMeshWriter.H.
The documentation for this class was generated from the following files:
src/conversion/meshWriter/starcd/STARCDMeshWriter.H
src/conversion/meshWriter/starcd/STARCDMeshWriter.C