OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SDA Class Reference
Ship design analysis (SDA) 3DoF motion function.
Public Member Functions
TypeName ("SDA")
Runtime type information.
SDA (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from components.
virtual autoPtr< solidBodyMotionFunction > clone () const
Construct and return a clone.
virtual ~SDA ()
Destructor.
virtual septernion transformation () const
Return the solid-body motion transformation septernion.
virtual bool read (const dictionary &SBMFCoeffs)
Update properties from given dictionary.
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from the SBMFCoeffs dictionary and Time.
virtual ~solidBodyMotionFunction ()
Destructor.
virtual void writeData (Ostream &) const
Write in dictionary format.
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Select constructed from the SBMFCoeffs dictionary and Time.
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Ship design analysis (SDA) 3DoF motion function.
Comprising sinusoidal roll (rotation about x), heave (z-translation) and sway (y-translation) motions with changing amplitude and phase.
See also
Foam::solidBodyMotionFunctions::tabulated6DoFMotion
Source files
SDA.H
SDA.C
Definition at line 56 of file SDA.H.
Constructor & Destructor Documentation
SDA()
SDA (const dictionary & SBMFCoeffs, const Time & runTime)
Construct from components.
Definition at line 47 of file SDA.C.
~SDA()
~SDA () virtual
Destructor.
Definition at line 61 of file SDA.C.
Referenced by SDA::clone().
Member Function Documentation
TypeName()
TypeName ("SDA")
Runtime type information.
clone()
virtual autoPtr<solidBodyMotionFunction> clone () const inline virtual
Construct and return a clone.
Implements solidBodyMotionFunction.
Definition at line 121 of file SDA.H.
References SDA::read(), solidBodyMotionFunction::SBMFCoeffs_, solidBodyMotionFunction::time_, SDA::transformation(), and SDA::~SDA().
transformation()
Foam::septernion transformation () const virtual
Return the solid-body motion transformation septernion.
Implements solidBodyMotionFunction.
Definition at line 67 of file SDA.C.
References Foam::endl(), Foam::exp(), Foam::Info, Foam::log(), Foam::mag(), Foam::max(), Foam::constant::mathematical::pi(), Foam::constant::mathematical::piByTwo(), R, Foam::sin(), Foam::sqr(), Foam::T(), and Foam::constant::mathematical::twoPi().
Referenced by SDA::clone().
read()
bool read (const dictionary & SBMFCoeffs) virtual
Update properties from given dictionary.
Implements solidBodyMotionFunction.
Definition at line 103 of file SDA.C.
References solidBodyMotionFunction::read(), and Foam::sqrt().
Referenced by SDA::clone().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/SDA/SDA.H
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/SDA/SDA.C