OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
attachDetach Class Reference
Attach/detach boundary mesh modifier. This modifier takes a set of internal faces and converts them into boundary faces and vice versa based on the given activation switch.
Public Member Functions
TypeName ("attachDetach")
Runtime type information.
attachDetach (const word &name, const label index, const polyTopoChanger &mme, const word &faceZoneName, const word &masterPatchName, const word &slavePatchName, const scalarField &triggerTimes, const bool manualTrigger=false)
Construct from components.
attachDetach (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mesh)
Construct from dictionary.
virtual ~attachDetach ()
Destructor.
const polyPatchID & masterPatchID () const
Return master patch ID.
const polyPatchID & slavePatchID () const
Return slave patch ID.
bool attached () const
Is the interface attached?
const Switch & manualTrigger () const
bool setAttach () const
bool setDetach () const
virtual bool changeTopology () const
Check for topology change.
virtual void setRefinement (polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const scalarField & triggerTimes () const
Get reference to trigger times.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Detailed Description
Attach/detach boundary mesh modifier. This modifier takes a set of internal faces and converts them into boundary faces and vice versa based on the given activation switch.
The patch is oriented using the flip map in the face zone. The oriented faces are put into the master patch and their mirror images into the slave.
Source files
attachDetach.H
attachDetach.C
attachInterface.C
detachInterface.C
attachDetachPointMatchMap.C
Definition at line 59 of file attachDetach.H.
Constructor & Destructor Documentation
attachDetach() [1/2]
attachDetach (const word & name, const label index, const polyTopoChanger & mme, const word & faceZoneName, const word & masterPatchName, const word & slavePatchName, const scalarField & triggerTimes, const bool manualTrigger = false)
Construct from components.
Definition at line 247 of file attachDetach.C.
attachDetach() [2/2]
attachDetach (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mesh)
Construct from dictionary.
Definition at line 275 of file attachDetach.C.
~attachDetach()
~attachDetach () virtual
Destructor.
Definition at line 311 of file attachDetach.C.
Member Function Documentation
TypeName()
TypeName ("attachDetach")
Runtime type information.
masterPatchID()
const polyPatchID& masterPatchID () const inline
Return master patch ID.
Definition at line 180 of file attachDetach.H.
slavePatchID()
const polyPatchID& slavePatchID () const inline
Return slave patch ID.
Definition at line 186 of file attachDetach.H.
attached()
bool attached () const inline
Is the interface attached?
Definition at line 192 of file attachDetach.H.
manualTrigger()
const Switch& manualTrigger () const inline
Definition at line 197 of file attachDetach.H.
References attachDetach::changeTopology(), attachDetach::modifyMotionPoints(), attachDetach::setAttach(), attachDetach::setDetach(), attachDetach::setRefinement(), and attachDetach::updateMesh().
setAttach()
bool setAttach () const
Definition at line 319 of file attachDetach.C.
Referenced by attachDetach::manualTrigger().
setDetach()
bool setDetach () const
Definition at line 334 of file attachDetach.C.
Referenced by attachDetach::manualTrigger().
changeTopology()
bool changeTopology () const virtual
Check for topology change.
Implements polyMeshModifier.
Definition at line 349 of file attachDetach.C.
References Foam::endl(), mesh, Foam::name(), Foam::nl, and Foam::Pout.
Referenced by attachDetach::manualTrigger().
setRefinement()
void setRefinement (polyTopoChange & ref) const virtual
Insert the layer addition/removal instructions.
into the topological change
Implements polyMeshModifier.
Definition at line 417 of file attachDetach.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by attachDetach::manualTrigger().
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Modify motion points to comply with the topological change.
Implements polyMeshModifier.
Definition at line 267 of file attachInterface.C.
References Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, Foam::mag(), polyMeshModifier::name(), Foam::Pout, List< T >::size(), and HashTable< T, Key, Hash >::toc().
Referenced by attachDetach::manualTrigger().
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Force recalculation of locally stored data on topological change.
Implements polyMeshModifier.
Definition at line 455 of file attachDetach.C.
References polyMesh::boundaryMesh(), and polyMesh::faceZones().
Referenced by attachDetach::manualTrigger().
triggerTimes()
const scalarField& triggerTimes () const inline
Get reference to trigger times.
Definition at line 222 of file attachDetach.H.
References attachDetach::write(), and attachDetach::writeDict().
write()
void write (Ostream & os) const virtual
Write.
Implements polyMeshModifier.
Definition at line 468 of file attachDetach.C.
References Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
Referenced by attachDetach::triggerTimes().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements polyMeshModifier.
Definition at line 479 of file attachDetach.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
Referenced by attachDetach::triggerTimes().
The documentation for this class was generated from the following files:
src/dynamicMesh/attachDetach/attachDetach.H
src/dynamicMesh/attachDetach/attachDetach.C
src/dynamicMesh/attachDetach/attachDetachPointMatchMap.C
src/dynamicMesh/attachDetach/attachInterface.C
src/dynamicMesh/attachDetach/detachInterface.C