OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
hexCellLooper Class Reference
Implementation of cellLooper.
Public Member Functions
TypeName ("hexCellLooper")
Runtime type information.
hexCellLooper (const polyMesh &mesh)
Construct from components.
virtual ~hexCellLooper ()
Destructor.
virtual bool cut (const vector &refDir, const label cellI, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const
Create cut along circumference of cellI. Gets current mesh cuts.
virtual bool cut (const plane &cutPlane, const label cellI, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const
Same but now also base point of cut provided (instead of always.
Public Member Functions inherited from geomCellLooper
TypeName ("geomCellLooper")
Runtime type information.
geomCellLooper (const polyMesh &mesh)
Construct from components.
virtual ~geomCellLooper ()
Destructor.
Public Member Functions inherited from cellLooper
TypeName ("cellLooper")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellLooper, word,(const polyMesh &mesh),(mesh))
cellLooper (const polyMesh &mesh)
Construct from components.
autoPtr< cellLooper > clone () const
Clone.
virtual ~cellLooper ()
Destructor.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Protected Attributes
const cellModel & hex_
Reference to hex cell shape.
Additional Inherited Members
Static Public Member Functions inherited from geomCellLooper
static scalar snapTol ()
static void setSnapTol (const scalar tol)
Static Public Member Functions inherited from cellLooper
static autoPtr< cellLooper > New (const word &type, const polyMesh &mesh)
Return a reference to the selected cellLooper.
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
convert eVert to edge label
static label getVertex (const primitiveMesh &mesh, const label eVert)
convert eVert to vertex label
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointI to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Protected Member Functions inherited from cellLooper
labelList getVertFacesNonEdge (const label cellI, const label edgeI, const label vertI) const
Get faces (on cell) connected to vertI which are not using edgeI.
label getFirstVertEdge (const label faceI, const label vertI) const
Get first edge connected to vertI and on faceI.
labelList getVertEdgesNonFace (const label cellI, const label faceI, const label vertI) const
Get edges (on cell) connected to vertI which are not on faceI.
label getMisAlignedEdge (const vector &refDir, const label cellI) const
Return edge from cellEdges that is most perpendicular.
Detailed Description
Implementation of cellLooper.
This one walks hexes in a topological way:
cross edge to other face
cross face by walking edge-point-edge across to reach the other side. (edges are always cut through the middle)
For anything else (tet, prism, .. poly) it will use geomCellLooper (which does a purely geometric cut using a plane through cell centre)
Source files
hexCellLooper.H
hexCellLooper.C
Definition at line 60 of file hexCellLooper.H.
Constructor & Destructor Documentation
hexCellLooper()
hexCellLooper (const polyMesh & mesh)
Construct from components.
Definition at line 153 of file hexCellLooper.C.
~hexCellLooper()
~hexCellLooper () virtual
Destructor.
Definition at line 162 of file hexCellLooper.C.
References hexCellLooper::cut().
Member Function Documentation
TypeName()
TypeName ("hexCellLooper")
Runtime type information.
cut() [1/2]
bool cut (const vector & refDir, const label cellI, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const virtual
Create cut along circumference of cellI. Gets current mesh cuts.
Cut along circumference is expressed as loop of cuts plus weights for cuts along edges (only valid for edge cuts). Return true if successful cut.
Reimplemented from geomCellLooper.
Reimplemented in topoCellLooper.
Definition at line 169 of file hexCellLooper.C.
References Foam::abort(), cells, cellShapes, geomCellLooper::cut(), Foam::meshTools::cutDirToEdge(), UList< T >::empty(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, Foam::meshTools::getEdgeFaces(), hexCellLooper::hex_, edgeVertex::mesh(), Foam::name(), points, Foam::Pout, List< T >::setSize(), List< T >::size(), success, WarningIn, and Foam::meshTools::writeOBJ().
Referenced by topoCellLooper::cut(), and hexCellLooper::~hexCellLooper().
cut() [2/2]
bool cut (const plane & cutPlane, const label cellI, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const virtual
Same but now also base point of cut provided (instead of always.
cell centre)
Reimplemented from geomCellLooper.
Reimplemented in topoCellLooper.
Definition at line 274 of file hexCellLooper.C.
References geomCellLooper::cut().
Member Data Documentation
hex_
const cellModel& hex_ protected
Reference to hex cell shape.
Definition at line 70 of file hexCellLooper.H.
Referenced by hexCellLooper::cut(), and topoCellLooper::cut().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/cellLooper/hexCellLooper.H
src/dynamicMesh/meshCut/cellLooper/hexCellLooper.C