OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellLooper Class Reference abstract
Abstract base class. Concrete implementations know how to cut a cell (i.e. determine a loop around the circumference).
Public Member Functions
TypeName ("cellLooper")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellLooper, word,(const polyMesh &mesh),(mesh))
cellLooper (const polyMesh &mesh)
Construct from components.
autoPtr< cellLooper > clone () const
Clone.
virtual ~cellLooper ()
Destructor.
virtual bool cut (const vector &refDir, const label cellI, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const =0
Create cut along circumference of cellI. Gets current mesh cuts.
virtual bool cut (const plane &cutPlane, const label cellI, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const =0
Same but now also base point of cut provided (instead of always.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Static Public Member Functions
static autoPtr< cellLooper > New (const word &type, const polyMesh &mesh)
Return a reference to the selected cellLooper.
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
convert eVert to edge label
static label getVertex (const primitiveMesh &mesh, const label eVert)
convert eVert to vertex label
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointI to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Protected Member Functions
labelList getVertFacesNonEdge (const label cellI, const label edgeI, const label vertI) const
Get faces (on cell) connected to vertI which are not using edgeI.
label getFirstVertEdge (const label faceI, const label vertI) const
Get first edge connected to vertI and on faceI.
labelList getVertEdgesNonFace (const label cellI, const label faceI, const label vertI) const
Get edges (on cell) connected to vertI which are not on faceI.
label getMisAlignedEdge (const vector &refDir, const label cellI) const
Return edge from cellEdges that is most perpendicular.
Detailed Description
Abstract base class. Concrete implementations know how to cut a cell (i.e. determine a loop around the circumference).
Loop around the cell is given as the vertices to be cut and edges to be cut (and a weight between 0 and 1 giving where the cut is to be made). Main routine is 'cut' which gets called for every cell and gets the current cut situation and expects to return a loop on the cell circumference.
Calling function needs to determine whether cellLooper is compatible with existing set of cuts.
Also contains various utility functions which implementations might want to use.
Source files
cellLooper.H
cellLooper.C
Definition at line 69 of file cellLooper.H.
Constructor & Destructor Documentation
cellLooper()
cellLooper (const polyMesh & mesh)
Construct from components.
Definition at line 206 of file cellLooper.C.
~cellLooper()
~cellLooper () virtual
Destructor.
Definition at line 214 of file cellLooper.C.
Referenced by cellLooper::clone().
Member Function Documentation
getVertFacesNonEdge()
Foam::labelList getVertFacesNonEdge (const label cellI, const label edgeI, const label vertI) const protected
Get faces (on cell) connected to vertI which are not using edgeI.
Definition at line 71 of file cellLooper.C.
References Foam::meshTools::faceOnCell(), forAll, Foam::meshTools::getEdgeFaces(), cellLooper::getFirstVertEdge(), mesh, pFaces, primitiveMesh::pointFaces(), List< T >::setSize(), and List< T >::size().
Referenced by cellLooper::New().
getFirstVertEdge()
Foam::label getFirstVertEdge (const label faceI, const label vertI) const protected
Get first edge connected to vertI and on faceI.
Definition at line 108 of file cellLooper.C.
References Foam::abort(), Foam::e, primitiveMesh::edges(), edge::end(), primitiveMesh::faceEdges(), Foam::FatalError, FatalErrorIn, forAll, cellLooper::getVertEdgesNonFace(), mesh, and edge::start().
Referenced by cellLooper::getVertFacesNonEdge().
getVertEdgesNonFace()
Foam::labelList getVertEdgesNonFace (const label cellI, const label faceI, const label vertI) const protected
Get edges (on cell) connected to vertI which are not on faceI.
Definition at line 140 of file cellLooper.C.
References Foam::meshTools::edgeOnCell(), primitiveMesh::faceEdges(), Foam::findIndex(), forAll, cellLooper::getMisAlignedEdge(), mesh, primitiveMesh::pointEdges(), List< T >::setSize(), and List< T >::size().
Referenced by cellLooper::getFirstVertEdge().
getMisAlignedEdge()
Foam::label getMisAlignedEdge (const vector & refDir, const label cellI) const protected
Return edge from cellEdges that is most perpendicular.
to refinement direction.
Definition at line 176 of file cellLooper.C.
References primitiveMesh::cellEdges(), forAll, Foam::mag(), mesh, and Foam::meshTools::normEdgeVec().
Referenced by topoCellLooper::cut(), and cellLooper::getVertEdgesNonFace().
TypeName()
TypeName ("cellLooper")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , cellLooper , word , (const polyMesh &mesh) , (mesh))
clone()
autoPtr<cellLooper> clone () const inline
Clone.
Definition at line 145 of file cellLooper.H.
References cellLooper::cut(), cellLooper::New(), notImplemented, Foam::type(), and cellLooper::~cellLooper().
New()
Foam::autoPtr< Foam::cellLooper > New (const word & type, const polyMesh & mesh) static
Return a reference to the selected cellLooper.
Definition at line 43 of file cellLooper.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, cellLooper::getVertFacesNonEdge(), mesh, and Foam::nl.
Referenced by cellLooper::clone().
cut() [1/2]
virtual bool cut (const vector & refDir, const label cellI, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const pure virtual
Create cut along circumference of cellI. Gets current mesh cuts.
vertIsCut, edgeIsCut, edgeWeight). Cut along circumference is expressed as cellVertCut, cellEdgeToWeight. Returns true if succesfull. Still might not be compatible with existing cuts but this should be handled by caller).
Implemented in topoCellLooper, geomCellLooper, and hexCellLooper.
Referenced by cellLooper::clone(), and cellCuts::nonAnchorPoints().
cut() [2/2]
virtual bool cut (const plane & cutPlane, const label cellI, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const pure virtual
Same but now also base point of cut provided (instead of always.
cell centre)
Implemented in topoCellLooper, geomCellLooper, and hexCellLooper.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/cellLooper/cellLooper.H
src/dynamicMesh/meshCut/cellLooper/cellLooper.C