OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
boundaryCutter Class Reference
Does modifications to boundary faces.
Public Member Functions
ClassName ("boundaryCutter")
Runtime type information.
boundaryCutter (const polyMesh &mesh)
Construct from mesh.
~boundaryCutter ()
Destructor.
void setRefinement (const Map< point > &pointToPos, const Map< List< point > > &edgeToCuts, const Map< labelPair > &faceToSplit, const Map< point > &faceToFeaturePoint, polyTopoChange &meshMod)
Do actual cutting with cut description. Inserts mesh changes.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const HashTable< labelList, edge, Hash< edge > > & edgeAddedPoints () const
Per edge a sorted list (start to end) of added points.
const Map< label > & faceAddedPoint () const
Per face the mid point added.
Detailed Description
Does modifications to boundary faces.
Does
move boundary points
split boundary edges (multiple per edge if necessary)
face-centre decomposes boundary faces
diagonal split of boundary faces
Source files
boundaryCutter.H
boundaryCutter.C
Definition at line 65 of file boundaryCutter.H.
Constructor & Destructor Documentation
boundaryCutter()
boundaryCutter (const polyMesh & mesh)
Construct from mesh.
Definition at line 389 of file boundaryCutter.C.
~boundaryCutter()
~boundaryCutter ()
Destructor.
Definition at line 399 of file boundaryCutter.C.
References boundaryCutter::setRefinement().
Member Function Documentation
ClassName()
ClassName ("boundaryCutter")
Runtime type information.
setRefinement()
void setRefinement (const Map< point > & pointToPos, const Map< List< point > > & edgeToCuts, const Map< labelPair > & faceToSplit, const Map< point > & faceToFeaturePoint, polyTopoChange & meshMod)
Do actual cutting with cut description. Inserts mesh changes.
into meshMod. pointToPos : new position for selected points edgeToCuts : per edge set of points that need to be introduced faceToSplit : per face the diagonal split faceToFeaturePoint : per face the feature point. Triangulation around this feature point.
Definition at line 406 of file boundaryCutter.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), HashTable< T, Key, Hash >::clear(), Foam::diag(), Foam::e, primitiveMesh::edgeFaces(), primitiveMesh::edges(), Foam::endl(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), forAll, forAllConstIter(), HashTable< T, label, Hash< label > >::found(), HashTable< T, Key, Hash >::found(), HashTable< T, Key, Hash >::insert(), primitiveMesh::isInternalFace(), face::nextLabel(), primitiveMesh::nFaces(), Foam::Pout, HashTable< T, Key, Hash >::resize(), polyTopoChange::setAction(), List< T >::setSize(), List< T >::size(), HashTable< T, label, Hash< label > >::size(), and edge::start().
Referenced by boundaryCutter::~boundaryCutter().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap)
Force recalculation of locally stored data on topological change.
Definition at line 832 of file boundaryCutter.C.
References HashTable< T, Key, Hash >::begin(), Foam::e, edge::end(), HashTableCore::end(), forAll, forAllConstIter(), mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), List< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), edge::start(), and HashTable< T, Key, Hash >::transfer().
edgeAddedPoints()
const HashTable<labelList, edge, Hash<edge> >& edgeAddedPoints () const inline
Per edge a sorted list (start to end) of added points.
Definition at line 161 of file boundaryCutter.H.
faceAddedPoint()
const Map<label>& faceAddedPoint () const inline
Per face the mid point added.
Definition at line 168 of file boundaryCutter.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/boundaryCutter/boundaryCutter.H
src/dynamicMesh/meshCut/meshModifiers/boundaryCutter/boundaryCutter.C