OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
boundaryPatch Class Reference
Like polyPatch but without reference to mesh. patchIdentifier::index is not used. Used in boundaryMesh to hold data on patches.
Public Member Functions
boundaryPatch (const word &name, const label index, const label size, const label start, const word &physicalType=word::null)
Construct from components.
boundaryPatch (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
boundaryPatch (const boundaryPatch &)
Construct as copy.
boundaryPatch (const boundaryPatch &, const label index)
Construct as copy, resetting the index.
autoPtr< boundaryPatch > clone () const
Clone.
~boundaryPatch ()
Destructor.
label size () const
label & size ()
label start () const
label & start ()
virtual void write (Ostream &) const
Write dictionary.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Friends
Ostream & operator<< (Ostream &, const boundaryPatch &)
Detailed Description
Like polyPatch but without reference to mesh. patchIdentifier::index is not used. Used in boundaryMesh to hold data on patches.
Source files
boundaryPatch.H
boundaryPatch.C
Definition at line 50 of file boundaryPatch.H.
Constructor & Destructor Documentation
boundaryPatch() [1/4]
boundaryPatch (const word & name, const label index, const label size, const label start, const word & physicalType = word::null)
Construct from components.
Definition at line 33 of file boundaryPatch.C.
Referenced by boundaryPatch::clone().
boundaryPatch() [2/4]
boundaryPatch (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 48 of file boundaryPatch.C.
boundaryPatch() [3/4]
boundaryPatch (const boundaryPatch & p)
Construct as copy.
Definition at line 60 of file boundaryPatch.C.
boundaryPatch() [4/4]
boundaryPatch (const boundaryPatch & p, const label index)
Construct as copy, resetting the index.
Definition at line 68 of file boundaryPatch.C.
~boundaryPatch()
~boundaryPatch ()
Destructor.
Definition at line 84 of file boundaryPatch.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::boundaryPatch > clone () const
Clone.
Definition at line 76 of file boundaryPatch.C.
References boundaryPatch::boundaryPatch().
size() [1/2]
label size () const inline
Definition at line 97 of file boundaryPatch.H.
Referenced by boundaryMesh::addPatch(), boundaryMesh::changeFaces(), boundaryMesh::changePatchType(), boundaryMesh::deletePatch(), boundaryMesh::read(), boundaryMesh::readTriSurface(), and boundaryMesh::whichPatch().
size() [2/2]
label& size () inline
Definition at line 102 of file boundaryPatch.H.
start() [1/2]
label start () const inline
Definition at line 107 of file boundaryPatch.H.
Referenced by boundaryMesh::addPatch(), boundaryMesh::changeFaces(), boundaryMesh::changePatchType(), boundaryMesh::deletePatch(), boundaryMesh::read(), boundaryMesh::readTriSurface(), boundaryMesh::whichPatch(), and boundaryMesh::writeTriSurface().
start() [2/2]
label& start () inline
Definition at line 112 of file boundaryPatch.H.
References boundaryPatch::operator<<, and boundaryPatch::write().
write()
void write (Ostream & os) const virtual
Write dictionary.
Definition at line 90 of file boundaryPatch.C.
References IOstream::check(), token::END_STATEMENT, Foam::nl, Foam::operator<<(), p, boundaryPatch::write(), patchIdentifier::write(), and Ostream::writeKeyword().
Referenced by boundaryPatch::start(), and boundaryPatch::write().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const boundaryPatch &) friend
Referenced by boundaryPatch::start().
The documentation for this class was generated from the following files:
src/dynamicMesh/boundaryPatch/boundaryPatch.H
src/dynamicMesh/boundaryPatch/boundaryPatch.C