OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
motionSmootherData Class Reference
Public Member Functions
motionSmootherData (const pointMesh &)
Construct read.
motionSmootherData (const pointVectorField &)
Construct from pointDisplacement.
pointVectorField & displacement ()
Reference to displacement field.
const pointVectorField & displacement () const
Reference to displacement field.
const pointScalarField & scale () const
Reference to scale field.
const pointField & oldPoints () const
Starting mesh position.
Protected Attributes
pointVectorField displacement_
Displacement field.
pointScalarField scale_
Scale factor for displacement.
pointField oldPoints_
Starting mesh position.
Detailed Description
Source files
motionSmootherData.H
motionSmootherData.C
Definition at line 47 of file motionSmootherData.H.
Constructor & Destructor Documentation
motionSmootherData() [1/2]
motionSmootherData (const pointMesh & pMesh)
Construct read.
Definition at line 31 of file motionSmootherData.C.
motionSmootherData() [2/2]
motionSmootherData (const pointVectorField & displacement)
Construct from pointDisplacement.
Definition at line 65 of file motionSmootherData.C.
Member Function Documentation
displacement() [1/2]
Foam::pointVectorField & displacement ()
Reference to displacement field.
Definition at line 100 of file motionSmootherData.C.
References motionSmootherData::displacement_.
Referenced by motionSmootherAlgo::correct(), autoSnapDriver::doSnap(), autoSnapDriver::scaleMesh(), and autoSnapDriver::smoothDisplacement().
displacement() [2/2]
const Foam::pointVectorField & displacement () const
Reference to displacement field.
Definition at line 106 of file motionSmootherData.C.
References motionSmootherData::displacement_.
scale()
const Foam::pointScalarField & scale () const
Reference to scale field.
Definition at line 112 of file motionSmootherData.C.
References motionSmootherData::scale_.
oldPoints()
const Foam::pointField & oldPoints () const
Starting mesh position.
Definition at line 118 of file motionSmootherData.C.
References motionSmootherData::oldPoints_.
Referenced by motionSmootherAlgo::modifyMotionPoints().
Member Data Documentation
displacement_
pointVectorField displacement_ protected
Displacement field.
Definition at line 54 of file motionSmootherData.H.
Referenced by motionSmootherData::displacement().
scale_
pointScalarField scale_ protected
Scale factor for displacement.
Definition at line 57 of file motionSmootherData.H.
Referenced by motionSmootherData::scale().
oldPoints_
pointField oldPoints_ protected
Starting mesh position.
Definition at line 60 of file motionSmootherData.H.
Referenced by motionSmootherData::oldPoints().
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/motionSmootherData.H
src/dynamicMesh/motionSmoother/motionSmootherData.C