OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
refinementIterator Class Reference
Utility class to do iterating meshCutter until all requests satisfied.
Public Member Functions
ClassName ("refinementIterator")
Runtime type information.
refinementIterator (polyMesh &mesh, undoableMeshCutter &meshRefiner, const cellLooper &cellWalker, const bool writeMesh=false)
Construct from mesh, refinementEngine and cell walking routine.
~refinementIterator ()
Destructor.
Map< label > setRefinement (const List< refineCell > &)
Try to refine cells in given direction. Constructs intermediate.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
convert eVert to edge label
static label getVertex (const primitiveMesh &mesh, const label eVert)
convert eVert to vertex label
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointI to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
Utility class to do iterating meshCutter until all requests satisfied.
Needed since cell cutting can only cut cell once in one go so if refinement pattern is not compatible on a cell by cell basis it will refuse to cut.
Parallel: communicates. All decisions done on 'reduce'd variable.
Source files
refinementIterator.H
refinementIterator.C
Definition at line 64 of file refinementIterator.H.
Constructor & Destructor Documentation
refinementIterator()
refinementIterator (polyMesh & mesh, undoableMeshCutter & meshRefiner, const cellLooper & cellWalker, const bool writeMesh = false)
Construct from mesh, refinementEngine and cell walking routine.
If writeMesh = true increments runTime and writes intermediate meshes.
Definition at line 49 of file refinementIterator.C.
~refinementIterator()
~refinementIterator ()
Destructor.
Definition at line 66 of file refinementIterator.C.
References refinementIterator::setRefinement().
Member Function Documentation
ClassName()
ClassName ("refinementIterator")
Runtime type information.
setRefinement()
Foam::Map< Foam::label > setRefinement (const List< refineCell > & refCells)
Try to refine cells in given direction. Constructs intermediate.
meshes. Returns map from old to added cells.
Definition at line 73 of file refinementIterator.C.
References Foam::abort(), refineCell::cellNo(), cells, polyTopoChange::changeMesh(), refineCell::direction(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, forAllConstIter(), mesh, cellCuts::nLoops(), points, Foam::Pout, Foam::reduce(), mapPolyMesh::reverseCellMap(), List< T >::setSize(), List< T >::size(), WarningIn, Ostream::write(), and Foam::meshTools::writeOBJ().
Referenced by refinementIterator::~refinementIterator().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/refinementIterator/refinementIterator.H
src/dynamicMesh/meshCut/meshModifiers/refinementIterator/refinementIterator.C