OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallNormalInfo Class Reference
Holds information regarding nearest wall point. Used in wall refinement.
Public Member Functions
wallNormalInfo ()
Construct null.
wallNormalInfo (const vector &normal)
Construct from normal.
wallNormalInfo (const wallNormalInfo &)
Construct as copy.
const vector & normal () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallNormalInfo &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const wallNormalInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const wallNormalInfo &) const
bool operator!= (const wallNormalInfo &) const
Friends
Ostream & operator<< (Ostream &, const wallNormalInfo &)
Istream & operator>> (Istream &, wallNormalInfo &)
Detailed Description
Holds information regarding nearest wall point. Used in wall refinement.
Source files
wallNormalInfo.H
wallNormalInfoI.H
wallNormalInfo.C
Definition at line 57 of file wallNormalInfo.H.
Constructor & Destructor Documentation
wallNormalInfo() [1/3]
wallNormalInfo () inline
Construct null.
Definition at line 64 of file wallNormalInfoI.H.
wallNormalInfo() [2/3]
wallNormalInfo (const vector & normal) inline
Construct from normal.
Definition at line 71 of file wallNormalInfoI.H.
wallNormalInfo() [3/3]
wallNormalInfo (const wallNormalInfo & wpt) inline
Construct as copy.
Definition at line 78 of file wallNormalInfoI.H.
Member Function Documentation
normal()
const Foam::vector & normal () const inline
Definition at line 86 of file wallNormalInfoI.H.
Referenced by wallNormalInfo::operator==(), and wallLayerCells::wallLayerCells().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 93 of file wallNormalInfoI.H.
References Vector< scalar >::max, and wallNormalInfo::sameGeometry().
Referenced by wallLayerCells::wallLayerCells().
sameGeometry()
bool sameGeometry (const polyMesh & , const wallNormalInfo & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 102 of file wallNormalInfoI.H.
References wallNormalInfo::leaveDomain().
Referenced by wallNormalInfo::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 116 of file wallNormalInfoI.H.
References wallNormalInfo::transform().
Referenced by wallNormalInfo::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 140 of file wallNormalInfoI.H.
References wallNormalInfo::updateCell().
Referenced by wallNormalInfo::transform().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 129 of file wallNormalInfoI.H.
References wallNormalInfo::enterDomain().
Referenced by wallNormalInfo::leaveDomain().
updateCell()
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 153 of file wallNormalInfoI.H.
References wallNormalInfo::updateFace().
Referenced by wallNormalInfo::enterDomain().
updateFace() [1/2]
bool updateFace (const polyMesh & , const label thisFaceI, const label neighbourCellI, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 169 of file wallNormalInfoI.H.
Referenced by wallNormalInfo::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & , const label thisFaceI, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 185 of file wallNormalInfoI.H.
References wallNormalInfo::equal().
equal()
bool equal (const wallNormalInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 199 of file wallNormalInfoI.H.
References wallNormalInfo::operator==().
Referenced by wallNormalInfo::updateFace().
operator==()
bool operator== (const wallNormalInfo & rhs) const inline
Definition at line 210 of file wallNormalInfoI.H.
References wallNormalInfo::normal().
Referenced by wallNormalInfo::equal().
operator!=()
bool operator!= (const wallNormalInfo & rhs) const inline
Definition at line 217 of file wallNormalInfoI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const wallNormalInfo &) friend
operator>>
Istream& operator>> (Istream & , wallNormalInfo &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/wallLayerCells/wallNormalInfo/wallNormalInfo.H
src/dynamicMesh/meshCut/wallLayerCells/wallNormalInfo/wallNormalInfoI.H