OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
perfectInterface Class Reference
Hack of attachDetach to couple patches when they perfectly align. Does not decouple. Used by stitchMesh app. Does geometric matching.
Public Member Functions
TypeName ("perfectInterface")
Runtime type information.
perfectInterface (const word &name, const label index, const polyTopoChanger &mme, const word &faceZoneName, const word &masterPatchName, const word &slavePatchName)
Construct from components.
perfectInterface (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Construct from dictionary.
virtual ~perfectInterface ()
Destructor.
virtual bool changeTopology () const
Check for topology change.
virtual void setRefinement (polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void setRefinement (const indirectPrimitivePatch &pp0, const indirectPrimitivePatch &pp1, polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Detailed Description
Hack of attachDetach to couple patches when they perfectly align. Does not decouple. Used by stitchMesh app. Does geometric matching.
Source files
perfectInterface.H
perfectInterface.C
Definition at line 55 of file perfectInterface.H.
Constructor & Destructor Documentation
perfectInterface() [1/2]
perfectInterface (const word & name, const label index, const polyTopoChanger & mme, const word & faceZoneName, const word & masterPatchName, const word & slavePatchName)
Construct from components.
Definition at line 84 of file perfectInterface.C.
perfectInterface() [2/2]
perfectInterface (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Construct from dictionary.
Definition at line 102 of file perfectInterface.C.
~perfectInterface()
~perfectInterface () virtual
Destructor.
Definition at line 130 of file perfectInterface.C.
Member Function Documentation
TypeName()
TypeName ("perfectInterface")
Runtime type information.
changeTopology()
bool changeTopology () const virtual
Check for topology change.
Implements polyMeshModifier.
Definition at line 136 of file perfectInterface.C.
References Foam::endl(), Foam::name(), Foam::Pout, and perfectInterface::setRefinement().
setRefinement() [1/2]
void setRefinement (polyTopoChange & ref) const virtual
Insert the layer addition/removal instructions.
into the topological change
Implements polyMeshModifier.
Definition at line 441 of file perfectInterface.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faces(), Foam::identity(), mesh, Foam::name(), patches, polyMesh::points(), Foam::Pout, and polyPatch::start().
Referenced by perfectInterface::changeTopology().
setRefinement() [2/2]
void setRefinement (const indirectPrimitivePatch & pp0, const indirectPrimitivePatch & pp1, polyTopoChange & ref) const virtual
Insert the layer addition/removal instructions.
into the topological change. Uses only mesh, not any of the patch and zone indices. Bit of a workaround - used in extruding a mesh.
Definition at line 159 of file perfectInterface.C.
References polyMesh::boundaryMesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), Foam::endl(), Foam::exit(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorIn, faceZone::flipMap(), forAll, forAllConstIter(), primitiveMesh::isInternalFace(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::matchPoints(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), Foam::min(), patches, pFaces, primitiveMesh::pointFaces(), polyMesh::points(), Foam::Pout, polyTopoChange::setAction(), List< T >::size(), WarningIn, faceZone::whichFace(), polyBoundaryMesh::whichPatch(), and ZoneMesh< ZoneType, MeshType >::whichZone().
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Modify motion points to comply with the topological change.
Implements polyMeshModifier.
Definition at line 485 of file perfectInterface.C.
updateMesh()
void updateMesh (const mapPolyMesh & morphMap) virtual
Force recalculation of locally stored data on topological change.
Implements polyMeshModifier.
Definition at line 492 of file perfectInterface.C.
References polyMesh::boundaryMesh(), polyMesh::faceZones(), mesh, and dynamicFvMesh::update().
write()
void write (Ostream & os) const virtual
Write.
Implements polyMeshModifier.
Definition at line 503 of file perfectInterface.C.
References Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements polyMeshModifier.
Definition at line 513 of file perfectInterface.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
The documentation for this class was generated from the following files:
src/dynamicMesh/perfectInterface/perfectInterface.H
src/dynamicMesh/perfectInterface/perfectInterface.C