OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
splitCell Class Reference
Description of cell after splitting. Contains cellLabel and pointers to cells it it split in. See directedRefinement.
Public Member Functions
splitCell (const label cellI, splitCell *parent)
Construct from cell number and parent.
~splitCell ()
Destructor.
label cellLabel () const
label & cellLabel ()
splitCell * parent () const
splitCell *& parent ()
splitCell * master () const
splitCell *& master ()
splitCell * slave () const
splitCell *& slave ()
bool isMaster () const
Check if this is master cell of split.
bool isUnrefined () const
Check if this is unrefined (i.e. has no master or slave)
splitCell * getOther () const
Returns other half of split cell. I.e. slave if this is master.
Detailed Description
Description of cell after splitting. Contains cellLabel and pointers to cells it it split in. See directedRefinement.
Source files
splitCell.H
splitCell.C
Definition at line 51 of file splitCell.H.
Constructor & Destructor Documentation
splitCell()
splitCell (const label cellI, splitCell * parent)
Construct from cell number and parent.
Definition at line 32 of file splitCell.C.
~splitCell()
~splitCell ()
Destructor.
Definition at line 43 of file splitCell.C.
References Foam::abort(), splitCell::cellLabel(), Foam::endl(), Foam::FatalError, FatalErrorIn, splitCell::master(), splitCell::parent(), and splitCell::slave().
Member Function Documentation
cellLabel() [1/2]
label cellLabel () const inline
Definition at line 93 of file splitCell.H.
Referenced by undoableMeshCutter::getAddedCells(), splitCell::getOther(), undoableMeshCutter::getSplitFaces(), splitCell::isMaster(), undoableMeshCutter::removeSplitFaces(), and splitCell::~splitCell().
cellLabel() [2/2]
label& cellLabel () inline
Definition at line 98 of file splitCell.H.
parent() [1/2]
splitCell* parent () const inline
Definition at line 103 of file splitCell.H.
Referenced by undoableMeshCutter::getAddedCells(), splitCell::getOther(), undoableMeshCutter::getSplitFaces(), splitCell::isMaster(), undoableMeshCutter::removeSplitFaces(), splitCell::~splitCell(), and undoableMeshCutter::~undoableMeshCutter().
parent() [2/2]
splitCell*& parent () inline
Definition at line 108 of file splitCell.H.
master() [1/2]
splitCell* master () const inline
Definition at line 113 of file splitCell.H.
Referenced by splitCell::getOther(), splitCell::isMaster(), splitCell::isUnrefined(), undoableMeshCutter::setRefinement(), and splitCell::~splitCell().
master() [2/2]
splitCell*& master () inline
Definition at line 118 of file splitCell.H.
slave() [1/2]
splitCell* slave () const inline
Definition at line 123 of file splitCell.H.
Referenced by splitCell::getOther(), splitCell::isMaster(), splitCell::isUnrefined(), undoableMeshCutter::setRefinement(), and splitCell::~splitCell().
slave() [2/2]
splitCell*& slave () inline
Definition at line 128 of file splitCell.H.
References splitCell::getOther(), splitCell::isMaster(), and splitCell::isUnrefined().
isMaster()
bool isMaster () const
Check if this is master cell of split.
Definition at line 70 of file splitCell.C.
References Foam::abort(), splitCell::cellLabel(), Foam::endl(), Foam::FatalError, FatalErrorIn, splitCell::master(), splitCell::parent(), and splitCell::slave().
Referenced by undoableMeshCutter::getAddedCells(), undoableMeshCutter::getSplitFaces(), and splitCell::slave().
isUnrefined()
bool isUnrefined () const
Check if this is unrefined (i.e. has no master or slave)
Definition at line 100 of file splitCell.C.
References splitCell::master(), and splitCell::slave().
Referenced by undoableMeshCutter::getAddedCells(), undoableMeshCutter::getSplitFaces(), undoableMeshCutter::removeSplitFaces(), and splitCell::slave().
getOther()
Foam::splitCell * getOther () const
Returns other half of split cell. I.e. slave if this is master.
Definition at line 106 of file splitCell.C.
References Foam::abort(), splitCell::cellLabel(), Foam::endl(), Foam::FatalError, FatalErrorIn, splitCell::master(), splitCell::parent(), and splitCell::slave().
Referenced by undoableMeshCutter::getAddedCells(), undoableMeshCutter::getSplitFaces(), splitCell::slave(), and undoableMeshCutter::~undoableMeshCutter().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/splitCell/splitCell.H
src/dynamicMesh/meshCut/splitCell/splitCell.C