OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
refineCell Class Reference
Container with cells to refine. Refinement given as single direction.
Public Member Functions
refineCell ()
Null.
refineCell (const label, const vector &)
from components. Vector will be normalized upon construction.
refineCell (Istream &is)
from Istream. Vector will be normalized upon construction.
label cellNo () const
const vector & direction () const
Friends
bool operator== (const refineCell &rc1, const refineCell &rc2)
bool operator!= (const refineCell &rc1, const refineCell &rc2)
Ostream & operator<< (Ostream &, const refineCell &)
Detailed Description
Container with cells to refine. Refinement given as single direction.
Source files
refineCell.H
refineCell.C
Definition at line 52 of file refineCell.H.
Constructor & Destructor Documentation
refineCell() [1/3]
refineCell ()
Null.
Definition at line 31 of file refineCell.C.
refineCell() [2/3]
refineCell (const label cellI, const vector & direction)
from components. Vector will be normalized upon construction.
Definition at line 38 of file refineCell.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and Foam::mag().
refineCell() [3/3]
refineCell (Istream & is)
from Istream. Vector will be normalized upon construction.
Definition at line 59 of file refineCell.C.
References Foam::abort(), IOstream::ASCII, refineCell::cellNo(), refineCell::direction(), Foam::FatalError, FatalErrorIn, IOstream::format(), Foam::mag(), Foam::operator<<(), and token::SPACE.
Member Function Documentation
cellNo()
label cellNo () const inline
Definition at line 78 of file refineCell.H.
Referenced by cellCuts::nonAnchorPoints(), refineCell::refineCell(), refinementIterator::setRefinement(), and edgeVertex::updateLabels().
direction()
const vector& direction () const inline
Definition at line 83 of file refineCell.H.
Referenced by cellCuts::nonAnchorPoints(), refineCell::refineCell(), refinementIterator::setRefinement(), and edgeVertex::updateLabels().
Friends And Related Function Documentation
operator==
bool operator== (const refineCell & rc1, const refineCell & rc2) friend
Definition at line 92 of file refineCell.H.
operator!=
bool operator!= (const refineCell & rc1, const refineCell & rc2) friend
Definition at line 101 of file refineCell.H.
operator<<
Ostream& operator<< (Ostream & , const refineCell &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/refineCell/refineCell.H
src/dynamicMesh/meshCut/refineCell/refineCell.C