OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyModifyFace Class Reference
Class describing modification of a face.
Public Member Functions
TypeName ("modifyFace")
Runtime type information.
polyModifyFace ()
Construct null. Used in constructing lists.
polyModifyFace (const face &f, const label faceID, const label owner, const label neighbour, const bool flipFaceFlux, const label patchID, const bool removeFromZone, const label zoneID, const bool zoneFlip)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
const face & newFace () const
Return face.
label faceID () const
Return master face ID.
label owner () const
Return owner cell ID.
label neighbour () const
Return owner cell ID.
bool flipFaceFlux () const
Does the face flux need to be flipped.
bool isInPatch () const
Does the face belong to a boundary patch?
label patchID () const
Boundary patch ID.
bool isInZone () const
Does the face belong to a zone?
bool onlyInZone () const
Is the face only a zone face (i.e. not belonging to a cell)
bool removeFromZone () const
label zoneID () const
Face zone ID.
label zoneFlip () const
Face zone flip.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class describing modification of a face.
Definition at line 48 of file polyModifyFace.H.
Constructor & Destructor Documentation
polyModifyFace() [1/2]
polyModifyFace () inline
Construct null. Used in constructing lists.
Definition at line 93 of file polyModifyFace.H.
Referenced by polyModifyFace::clone().
polyModifyFace() [2/2]
polyModifyFace (const face & f, const label faceID, const label owner, const label neighbour, const bool flipFaceFlux, const label patchID, const bool removeFromZone, const label zoneID, const bool zoneFlip) inline
Construct from components.
Definition at line 108 of file polyModifyFace.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::min(), and List< T >::size().
Member Function Documentation
TypeName()
TypeName ("modifyFace")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 256 of file polyModifyFace.H.
References polyModifyFace::polyModifyFace().
newFace()
const face& newFace () const inline
Return face.
Definition at line 267 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
faceID()
label faceID () const inline
Return master face ID.
Definition at line 273 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
owner()
label owner () const inline
Return owner cell ID.
Definition at line 279 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
neighbour()
label neighbour () const inline
Return owner cell ID.
Definition at line 285 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
flipFaceFlux()
bool flipFaceFlux () const inline
Does the face flux need to be flipped.
Definition at line 291 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
isInPatch()
bool isInPatch () const inline
Does the face belong to a boundary patch?
Definition at line 297 of file polyModifyFace.H.
patchID()
label patchID () const inline
Boundary patch ID.
Definition at line 303 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
isInZone()
bool isInZone () const inline
Does the face belong to a zone?
Definition at line 309 of file polyModifyFace.H.
onlyInZone()
bool onlyInZone () const inline
Is the face only a zone face (i.e. not belonging to a cell)
Definition at line 315 of file polyModifyFace.H.
removeFromZone()
bool removeFromZone () const inline
Definition at line 320 of file polyModifyFace.H.
zoneID()
label zoneID () const inline
Face zone ID.
Definition at line 326 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
zoneFlip()
label zoneFlip () const inline
Face zone flip.
Definition at line 332 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/modifyObject/polyModifyFace.H