OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointEdgeCollapse Class Reference
Determines length of string of edges walked to point.
Public Member Functions
pointEdgeCollapse ()
Construct null.
pointEdgeCollapse (const point &collapsePoint, const label collapseIndex, const label collapsePriority)
Construct from components.
const point & collapsePoint () const
label collapseIndex () const
label collapsePriority () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const label edgeI, const pointEdgeCollapse &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const pointEdgeCollapse &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointEdgeCollapse &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointI, const pointEdgeCollapse &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const pointEdgeCollapse &, TrackingData &) const
Same (like operator==)
bool operator== (const pointEdgeCollapse &) const
bool operator!= (const pointEdgeCollapse &) const
Friends
Ostream & operator<< (Ostream &, const pointEdgeCollapse &)
Istream & operator>> (Istream &, pointEdgeCollapse &)
Detailed Description
Determines length of string of edges walked to point.
Source files
pointEdgeCollapse.H
pointEdgeCollapseI.H
pointEdgeCollapse.C
Definition at line 54 of file pointEdgeCollapse.H.
Constructor & Destructor Documentation
pointEdgeCollapse() [1/2]
pointEdgeCollapse () inline
Construct null.
Definition at line 104 of file pointEdgeCollapseI.H.
pointEdgeCollapse() [2/2]
pointEdgeCollapse (const point & collapsePoint, const label collapseIndex, const label collapsePriority) inline
Construct from components.
Definition at line 114 of file pointEdgeCollapseI.H.
Member Function Documentation
collapsePoint()
const Foam::point & collapsePoint () const inline
Definition at line 128 of file pointEdgeCollapseI.H.
collapseIndex()
Foam::label collapseIndex () const inline
Definition at line 134 of file pointEdgeCollapseI.H.
Referenced by edgeCollapser::setRefinement().
collapsePriority()
Foam::label collapsePriority () const inline
Definition at line 140 of file pointEdgeCollapseI.H.
References Foam::cmptMin(), Foam::e, and Foam::mag().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 163 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::leaveDomain().
leaveDomain()
void leaveDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 171 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::transform().
Referenced by pointEdgeCollapse::valid().
enterDomain()
void enterDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 197 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::updatePoint().
Referenced by pointEdgeCollapse::transform().
transform()
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 184 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::enterDomain(), and Foam::transform().
Referenced by pointEdgeCollapse::leaveDomain().
updatePoint() [1/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const label edgeI, const pointEdgeCollapse & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 212 of file pointEdgeCollapseI.H.
Referenced by pointEdgeCollapse::enterDomain(), and pointEdgeCollapse::updatePoint().
updatePoint() [2/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const pointEdgeCollapse & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 228 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::updatePoint().
updatePoint() [3/3]
bool updatePoint (const pointEdgeCollapse & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 243 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::updateEdge().
updateEdge()
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointI, const pointEdgeCollapse & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 256 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::equal().
Referenced by pointEdgeCollapse::updatePoint().
equal()
bool equal (const pointEdgeCollapse & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 271 of file pointEdgeCollapseI.H.
References pointEdgeCollapse::operator==().
Referenced by pointEdgeCollapse::updateEdge().
operator==()
bool operator== (const pointEdgeCollapse & rhs) const inline
Definition at line 283 of file pointEdgeCollapseI.H.
Referenced by pointEdgeCollapse::equal().
operator!=()
bool operator!= (const pointEdgeCollapse & rhs) const inline
Definition at line 295 of file pointEdgeCollapseI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const pointEdgeCollapse &) friend
operator>>
Istream& operator>> (Istream & , pointEdgeCollapse &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/pointEdgeCollapse/pointEdgeCollapse.H
src/dynamicMesh/polyTopoChange/polyTopoChange/pointEdgeCollapse/pointEdgeCollapseI.H