OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyAddFace Class Reference
A face addition data class. A face can be inflated either from a point or from another face and can either be in internal or a boundary face.
Public Member Functions
TypeName ("addFace")
Runtime type information.
polyAddFace ()
Construct null. Used for constructing lists.
polyAddFace (const face &f, const label owner, const label neighbour, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
const face & newFace () const
Return face.
label owner () const
Return owner cell.
label neighbour () const
Return neighour cell.
bool isPointMaster () const
Is the face mastered by a point.
bool isEdgeMaster () const
Is the face mastered by an edge.
bool isFaceMaster () const
Is the face mastered by another face.
bool appended () const
Is the face appended with no master.
label masterPointID () const
Return master point ID.
label masterEdgeID () const
Return master edge ID.
label masterFaceID () const
Return master face ID.
bool flipFaceFlux () const
Does the face flux need to be flipped.
bool isInPatch () const
Does the face belong to a boundary patch?
label patchID () const
Boundary patch ID.
bool isInZone () const
Does the face belong to a zone?
bool onlyInZone () const
Is the face only a zone face (i.e. not belonging to a cell)
label zoneID () const
Face zone ID.
label zoneFlip () const
Face zone flip.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
A face addition data class. A face can be inflated either from a point or from another face and can either be in internal or a boundary face.
Definition at line 51 of file polyAddFace.H.
Constructor & Destructor Documentation
polyAddFace() [1/2]
polyAddFace () inline
Construct null. Used for constructing lists.
Definition at line 99 of file polyAddFace.H.
Referenced by polyAddFace::clone().
polyAddFace() [2/2]
polyAddFace (const face & f, const label owner, const label neighbour, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip) inline
Construct from components.
Definition at line 116 of file polyAddFace.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::min(), and List< T >::size().
Member Function Documentation
TypeName()
TypeName ("addFace")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 316 of file polyAddFace.H.
References polyAddFace::polyAddFace().
newFace()
const face& newFace () const inline
Return face.
Definition at line 327 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
owner()
label owner () const inline
Return owner cell.
Definition at line 333 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
neighbour()
label neighbour () const inline
Return neighour cell.
Definition at line 339 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
isPointMaster()
bool isPointMaster () const inline
Is the face mastered by a point.
Definition at line 345 of file polyAddFace.H.
Referenced by polyAddFace::appended().
isEdgeMaster()
bool isEdgeMaster () const inline
Is the face mastered by an edge.
Definition at line 351 of file polyAddFace.H.
Referenced by polyAddFace::appended().
isFaceMaster()
bool isFaceMaster () const inline
Is the face mastered by another face.
Definition at line 357 of file polyAddFace.H.
Referenced by polyAddFace::appended().
appended()
bool appended () const inline
Is the face appended with no master.
Definition at line 363 of file polyAddFace.H.
References polyAddFace::isEdgeMaster(), polyAddFace::isFaceMaster(), and polyAddFace::isPointMaster().
masterPointID()
label masterPointID () const inline
Return master point ID.
Definition at line 369 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
masterEdgeID()
label masterEdgeID () const inline
Return master edge ID.
Definition at line 375 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
masterFaceID()
label masterFaceID () const inline
Return master face ID.
Definition at line 381 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
flipFaceFlux()
bool flipFaceFlux () const inline
Does the face flux need to be flipped.
Definition at line 387 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
isInPatch()
bool isInPatch () const inline
Does the face belong to a boundary patch?
Definition at line 393 of file polyAddFace.H.
patchID()
label patchID () const inline
Boundary patch ID.
Definition at line 399 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
isInZone()
bool isInZone () const inline
Does the face belong to a zone?
Definition at line 405 of file polyAddFace.H.
onlyInZone()
bool onlyInZone () const inline
Is the face only a zone face (i.e. not belonging to a cell)
Definition at line 411 of file polyAddFace.H.
zoneID()
label zoneID () const inline
Face zone ID.
Definition at line 417 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
zoneFlip()
label zoneFlip () const inline
Face zone flip.
Definition at line 423 of file polyAddFace.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/addObject/polyAddFace.H