OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CompactListList< T, Container > Class Template Reference
A packed storage unstructured matrix of objects of type <T> using an offset table for access.
Public Member Functions
CompactListList ()
Null constructor.
CompactListList (const List< Container > &)
Construct by converting given List<List<T> >
CompactListList (const label nRows, const label nData)
Construct given size of offset table (number of rows)
CompactListList (const label nRows, const label nData, const T &)
Construct given size of offset table (number of rows),.
CompactListList (const labelUList &rowSizes)
Construct given list of row-sizes.
CompactListList (const labelUList &rowSizes, const T &)
Construct given list of row-sizes.
CompactListList (const Xfer< CompactListList< T, Container > > &)
Construct by transferring the parameter contents.
CompactListList (CompactListList< T, Container > &, bool reUse)
Construct as copy or re-use as specified.
CompactListList (Istream &)
Construct from Istream.
autoPtr< CompactListList< T, Container > > clone () const
Clone.
label size () const
Return the primary size, i.e. the number of rows.
bool empty () const
Return true if the number of rows is zero.
const List< label > & offsets () const
Return the offset table (= size()+1)
List< label > & offsets ()
Return non-const access to the offset table.
const List< T > & m () const
Return the packed matrix of data.
List< T > & m ()
Return non-const access to the packed matrix of data.
void setSize (const label nRows)
Reset size of CompactListList.
void setSize (const label nRows, const label nData)
Reset size of CompactListList.
void setSize (const label nRows, const label nData, const T &)
Reset sizes of CompactListList and value for new elements.
void setSize (const labelUList &rowSizes)
Reset size of CompactListList.
void resize (const label nRows)
Reset size of CompactListList.
void resize (const label nRows, const label nData)
Reset size of CompactListList.
void resize (const label nRows, const label nData, const T &)
Reset sizes of CompactListList and value for new elements.
void resize (const labelUList &rowSizes)
Reset size of CompactListList.
void clear ()
Clear the CompactListList, i.e. set sizes to zero.
labelList sizes () const
Return sizes (to be used e.g. for construction)
void transfer (CompactListList< T, Container > &)
Transfer the contents of the argument CompactListList.
Xfer< CompactListList< T, Container > > xfer ()
Transfer the contents to the Xfer container.
label index (const label row, const label col) const
Return index into m.
label whichRow (const label index) const
Get row for index into m.
label whichColumn (const label row, const label index) const
Get column index (j) given above row.
UList< T > operator[] (const label i)
Return subscript-checked row as UList.
const UList< T > operator[] (const label i) const
Return const subscript-checked row as UList.
T & operator() (const label i, const label j)
Return subscript-checked element.
const T & operator() (const label i, const label j) const
Return const subscript-checked element.
List< Container > operator() () const
Return as List<Container>
void operator= (const T &)
Assignment of all entries to the given value.
Static Public Member Functions
static const CompactListList< T, Container > & null ()
Return a null CompactListList.
Friends
Istream & operator>> (Istream &, CompactListList< T, Container > &)
Read CompactListList from Istream, discarding contents.
Ostream & operator (Ostream &, const CompactListList< T, Container > &)
Detailed Description
template<class T, class Container = List<T>>
class Foam::CompactListList< T, Container >
A packed storage unstructured matrix of objects of type <T> using an offset table for access.
The offset table is the size of the number of rows+1 whose elements are the accumulated sizes of the rows, i.e.
offset[i] gives the index of first element of row i
offset[i+1] - offset[i] is the number of elements in row i
Storage is allocated on free-store during construction.
As a special case a null-constructed CompactListList has an empty offsets_ (instead of size 1).
Source files
CompactListList.H
CompactListList.C
CompactListListI.H
CompactListListIO.C
Definition at line 91 of file polyTopoChange.H.
Constructor & Destructor Documentation
CompactListList() [1/9]
CompactListList () inline
Null constructor.
Definition at line 32 of file CompactListListI.H.
Referenced by CompactListList< T, Container >::CompactListList().
CompactListList() [2/9]
CompactListList (const List< Container > & ll) explicit
Construct by converting given List<List<T> >
Definition at line 31 of file CompactListList.C.
References CompactListList< T, Container >::CompactListList(), forAll, k, and List< T >::size().
CompactListList() [3/9]
CompactListList (const label nRows, const label nData) inline
Construct given size of offset table (number of rows)
and number of data.
Definition at line 40 of file CompactListListI.H.
References CompactListList< T, Container >::CompactListList().
CompactListList() [4/9]
CompactListList (const label nRows, const label nData, const T & t) inline
Construct given size of offset table (number of rows),.
the number of data and a value for all elements.
Definition at line 53 of file CompactListListI.H.
CompactListList() [5/9]
CompactListList (const labelUList & rowSizes) explicit
Construct given list of row-sizes.
Definition at line 61 of file CompactListList.C.
References CompactListList< T, Container >::CompactListList(), and forAll.
CompactListList() [6/9]
CompactListList (const labelUList & rowSizes, const T & t)
Construct given list of row-sizes.
Definition at line 82 of file CompactListList.C.
References CompactListList< T, Container >::CompactListList(), and forAll.
CompactListList() [7/9]
CompactListList (const Xfer< CompactListList< T, Container > > & lst) explicit
Construct by transferring the parameter contents.
Definition at line 104 of file CompactListList.C.
References CompactListList< T, Container >::CompactListList(), and CompactListList< T, Container >::transfer().
CompactListList() [8/9]
CompactListList (CompactListList< T, Container > & lst, bool reUse)
Construct as copy or re-use as specified.
Definition at line 114 of file CompactListList.C.
CompactListList() [9/9]
CompactListList (Istream & is)
Construct from Istream.
Definition at line 32 of file CompactListListIO.C.
References Foam::operator>>(), operator>>(), and List< T >::size().
Member Function Documentation
null()
const Foam::CompactListList< T, Container > & null () inline static
Return a null CompactListList.
Definition at line 80 of file CompactListListI.H.
clone()
Foam::autoPtr< Foam::CompactListList< T, Container > > clone () const inline
Clone.
Definition at line 67 of file CompactListListI.H.
size()
Foam::label size () const inline
Return the primary size, i.e. the number of rows.
Definition at line 87 of file CompactListListI.H.
Referenced by decompositionMethod::calcCellCells(), CompactListList< T, Container >::operator()(), CompactListList< T, Container >::setSize(), and CompactListList< T, Container >::sizes().
empty()
bool empty () const inline
Return true if the number of rows is zero.
Definition at line 94 of file CompactListListI.H.
offsets() [1/2]
const Foam::List< Foam::label > & offsets () const inline
Return the offset table (= size()+1)
Definition at line 102 of file CompactListListI.H.
Referenced by decompositionMethod::calcCellCells().
offsets() [2/2]
Foam::List< Foam::label > & offsets () inline
Return non-const access to the offset table.
Definition at line 109 of file CompactListListI.H.
m() [1/2]
const Foam::List< T > & m () const inline
Return the packed matrix of data.
Definition at line 116 of file CompactListListI.H.
Referenced by decompositionMethod::calcCellCells().
m() [2/2]
Foam::List< T > & m () inline
Return non-const access to the packed matrix of data.
Definition at line 124 of file CompactListListI.H.
References CompactListList< T, Container >::index().
setSize() [1/4]
void setSize (const label nRows)
Reset size of CompactListList.
This form only allows contraction of the CompactListList.
Definition at line 128 of file CompactListList.C.
References Foam::abort(), CompactListList< T, Container >::clear(), Foam::FatalError, FatalErrorIn, Foam::nl, List< T >::setSize(), List< T >::size(), and CompactListList< T, Container >::size().
Referenced by decompositionMethod::calcCellCells(), fvMeshDistribute::printCoupleInfo(), CompactListList< T, Container >::resize(), and CompactListList< T, Container >::setSize().
setSize() [2/4]
void setSize (const label nRows, const label nData)
Reset size of CompactListList.
Definition at line 155 of file CompactListList.C.
References CompactListList< T, Container >::setSize(), and List< T >::setSize().
setSize() [3/4]
void setSize (const label nRows, const label nData, const T & t)
Reset sizes of CompactListList and value for new elements.
Definition at line 168 of file CompactListList.C.
References List< T >::setSize().
setSize() [4/4]
void setSize (const labelUList & rowSizes)
Reset size of CompactListList.
Definition at line 181 of file CompactListList.C.
References forAll, List< T >::setSize(), and UList< T >::size().
resize() [1/4]
void resize (const label nRows) inline
Reset size of CompactListList.
This form only allows contraction of the CompactListList.
Definition at line 178 of file CompactListListI.H.
References CompactListList< T, Container >::setSize().
Referenced by CompactListList< T, Container >::resize().
resize() [2/4]
void resize (const label nRows, const label nData) inline
Reset size of CompactListList.
Definition at line 186 of file CompactListListI.H.
References CompactListList< T, Container >::resize(), and CompactListList< T, Container >::setSize().
resize() [3/4]
void resize (const label nRows, const label nData, const T & t) inline
Reset sizes of CompactListList and value for new elements.
Definition at line 197 of file CompactListListI.H.
References CompactListList< T, Container >::resize(), and CompactListList< T, Container >::setSize().
resize() [4/4]
void resize (const labelUList & rowSizes) inline
Reset size of CompactListList.
Definition at line 209 of file CompactListListI.H.
References CompactListList< T, Container >::setSize().
clear()
void clear ()
Clear the CompactListList, i.e. set sizes to zero.
Definition at line 215 of file CompactListList.C.
References List< T >::clear(), and CompactListList< T, Container >::transfer().
Referenced by CompactListList< T, Container >::setSize().
sizes()
Foam::labelList sizes () const
Return sizes (to be used e.g. for construction)
Definition at line 199 of file CompactListList.C.
References forAll, List< T >::size(), and CompactListList< T, Container >::size().
transfer()
void transfer (CompactListList< T, Container > & a)
Transfer the contents of the argument CompactListList.
into this CompactListList and annul the argument list.
Definition at line 225 of file CompactListList.C.
References List< T >::transfer().
Referenced by CompactListList< T, Container >::clear(), and CompactListList< T, Container >::CompactListList().
xfer()
Foam::Xfer< Foam::CompactListList< T, Container > > xfer () inline
Transfer the contents to the Xfer container.
Definition at line 171 of file CompactListListI.H.
References Foam::xferMove().
index()
Foam::label index (const label row, const label col) const inline
Return index into m.
Definition at line 132 of file CompactListListI.H.
Referenced by CompactListList< T, Container >::m(), CompactListList< T, Container >::operator()(), and CompactListList< T, Container >::whichColumn().
whichRow()
Foam::label whichRow (const label index) const inline
Get row for index into m.
Definition at line 142 of file CompactListListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::findLower(), and CompactListList< T, Container >::whichColumn().
whichColumn()
Foam::label whichColumn (const label row, const label index) const inline
Get column index (j) given above row.
Definition at line 160 of file CompactListListI.H.
References CompactListList< T, Container >::index().
Referenced by CompactListList< T, Container >::whichRow().
operator[]() [1/2]
Foam::UList< T > operator[] (const label i) inline
Return subscript-checked row as UList.
Definition at line 221 of file CompactListListI.H.
operator[]() [2/2]
const Foam::UList< T > operator[] (const label i) const inline
Return const subscript-checked row as UList.
Definition at line 233 of file CompactListListI.H.
References CompactListList< T, Container >::operator, and Foam::T().
operator()() [1/3]
T & operator() (const label i, const label j) inline
Return subscript-checked element.
Definition at line 248 of file CompactListListI.H.
References CompactListList< T, Container >::index(), CompactListList< T, Container >::operator, and Foam::T().
operator()() [2/3]
const T & operator() (const label i, const label j) const inline
Return const subscript-checked element.
Definition at line 259 of file CompactListListI.H.
References CompactListList< T, Container >::index().
operator()() [3/3]
Foam::List< Container > operator() () const
Return as List<Container>
Definition at line 238 of file CompactListList.C.
References forAll, and CompactListList< T, Container >::size().
operator=()
void operator= (const T & t) inline
Assignment of all entries to the given value.
Definition at line 269 of file CompactListListI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , CompactListList< T, Container > &) friend
Read CompactListList from Istream, discarding contents.
of existing CompactListList.
operator
Ostream& operator (Ostream & , const CompactListList< T, Container > &) friend
Referenced by CompactListList< T, Container >::operator()(), and CompactListList< T, Container >::operator[]().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChange.H
src/OpenFOAM/containers/Lists/CompactListList/CompactListList.H
src/OpenFOAM/containers/Lists/CompactListList/CompactListList.C
src/OpenFOAM/containers/Lists/CompactListList/CompactListListI.H
src/OpenFOAM/containers/Lists/CompactListList/CompactListListIO.C