OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyAddCell Class Reference
Class containing data for cell addition.
Public Member Functions
TypeName ("addCell")
Runtime type information.
polyAddCell ()
Construct null. Used for constructing lists.
polyAddCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
bool isPointMaster () const
Is the cell mastered by a point.
bool isEdgeMaster () const
Is the cell mastered by an edge.
bool isFaceMaster () const
Is the cell mastered by another face.
bool isCellMaster () const
Is the cell mastered by another cell.
bool appended () const
Is the cell appended with no master.
label masterPointID () const
Return master point ID.
label masterEdgeID () const
Return master edge ID.
label masterFaceID () const
Return master face ID.
label masterCellID () const
Return master cell ID.
bool isInZone () const
Does the cell belong to a zone?
label zoneID () const
Cell zone ID.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class containing data for cell addition.
Definition at line 46 of file polyAddCell.H.
Constructor & Destructor Documentation
polyAddCell() [1/2]
polyAddCell () inline
Construct null. Used for constructing lists.
Definition at line 79 of file polyAddCell.H.
Referenced by polyAddCell::clone().
polyAddCell() [2/2]
polyAddCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID) inline
Construct from components.
Definition at line 90 of file polyAddCell.H.
Member Function Documentation
TypeName()
TypeName ("addCell")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 106 of file polyAddCell.H.
References polyAddCell::polyAddCell().
isPointMaster()
bool isPointMaster () const inline
Is the cell mastered by a point.
Definition at line 118 of file polyAddCell.H.
Referenced by polyAddCell::appended().
isEdgeMaster()
bool isEdgeMaster () const inline
Is the cell mastered by an edge.
Definition at line 124 of file polyAddCell.H.
Referenced by polyAddCell::appended().
isFaceMaster()
bool isFaceMaster () const inline
Is the cell mastered by another face.
Definition at line 130 of file polyAddCell.H.
Referenced by polyAddCell::appended().
isCellMaster()
bool isCellMaster () const inline
Is the cell mastered by another cell.
Definition at line 136 of file polyAddCell.H.
Referenced by polyAddCell::appended().
appended()
bool appended () const inline
Is the cell appended with no master.
Definition at line 142 of file polyAddCell.H.
References polyAddCell::isCellMaster(), polyAddCell::isEdgeMaster(), polyAddCell::isFaceMaster(), and polyAddCell::isPointMaster().
masterPointID()
label masterPointID () const inline
Return master point ID.
Definition at line 150 of file polyAddCell.H.
Referenced by polyTopoChange::setAction().
masterEdgeID()
label masterEdgeID () const inline
Return master edge ID.
Definition at line 156 of file polyAddCell.H.
Referenced by polyTopoChange::setAction().
masterFaceID()
label masterFaceID () const inline
Return master face ID.
Definition at line 162 of file polyAddCell.H.
Referenced by polyTopoChange::setAction().
masterCellID()
label masterCellID () const inline
Return master cell ID.
Definition at line 168 of file polyAddCell.H.
Referenced by polyTopoChange::setAction().
isInZone()
bool isInZone () const inline
Does the cell belong to a zone?
Definition at line 174 of file polyAddCell.H.
zoneID()
label zoneID () const inline
Cell zone ID.
Definition at line 180 of file polyAddCell.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/addObject/polyAddCell.H