OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
duplicatePoints Class Reference
Duplicate points.
Public Member Functions
ClassName ("duplicatePoints")
Runtime type information.
duplicatePoints (const polyMesh &mesh)
Construct from mesh.
const labelListList & duplicates () const
Per point in regionSide.pointRegions() the points created.
void setRefinement (const localPointRegion &regionSide, polyTopoChange &)
Play commands into polyTopoChange to duplicate points. Gets.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
Detailed Description
Duplicate points.
Source files
duplicatePoints.H
duplicatePoints.C
Definition at line 57 of file duplicatePoints.H.
Constructor & Destructor Documentation
duplicatePoints()
duplicatePoints (const polyMesh & mesh)
Construct from mesh.
Definition at line 49 of file duplicatePoints.C.
References duplicatePoints::setRefinement().
Member Function Documentation
ClassName()
ClassName ("duplicatePoints")
Runtime type information.
duplicates()
const labelListList& duplicates () const inline
Per point in regionSide.pointRegions() the points created.
Definition at line 95 of file duplicatePoints.H.
References duplicatePoints::setRefinement(), and duplicatePoints::updateMesh().
setRefinement()
void setRefinement (const localPointRegion & regionSide, polyTopoChange & meshMod)
Play commands into polyTopoChange to duplicate points. Gets.
localPointRegion structure which is per non-manifold point the regions per point.
Definition at line 59 of file duplicatePoints.C.
References polyTopoChange::addPoint(), polyMesh::boundaryMesh(), HashTableCore::end(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), localPointRegion::faceRegions(), polyMesh::faces(), polyMesh::faceZones(), HashTable< T, Key, Hash >::find(), Foam::findIndex(), faceZone::flipMap(), forAll, forAllConstIter(), primitiveMesh::isInternalFace(), localPointRegion::meshFaceMap(), localPointRegion::meshPointMap(), polyTopoChange::modifyFace(), patches, Time::path(), localPointRegion::pointRegions(), polyMesh::points(), polyTopoChange::points(), List< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), objectRegistry::time(), faceZone::whichFace(), polyBoundaryMesh::whichPatch(), ZoneMesh< ZoneType, MeshType >::whichZone(), and Foam::meshTools::writeOBJ().
Referenced by duplicatePoints::duplicatePoints(), duplicatePoints::duplicates(), and meshRefinement::dupNonManifoldPoints().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 209 of file duplicatePoints.C.
References forAll, Foam::inplaceRenumber(), and mapPolyMesh::reversePointMap().
Referenced by duplicatePoints::duplicates().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/duplicatePoints.H
src/dynamicMesh/polyTopoChange/polyTopoChange/duplicatePoints.C