OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
refinementHistory Class Reference
All refinement history. Used in unrefinement.
Classes
class splitCell8
Public Member Functions
TypeName ("refinementHistory")
refinementHistory (const IOobject &)
Construct (read) given an IOobject.
refinementHistory (const IOobject &, const List< splitCell8 > &splitCells, const labelList &visibleCells)
Construct (read) or construct null.
refinementHistory (const IOobject &, const label nCells)
Construct (read) or construct from initial number of cells.
refinementHistory (const IOobject &, const refinementHistory &)
Construct as copy.
refinementHistory (const IOobject &, Istream &)
Construct from Istream.
const labelList & visibleCells () const
Per cell in the current mesh (i.e. visible) either -1 (unrefined)
const DynamicList< splitCell8 > & splitCells () const
Storage for splitCell8s.
const DynamicList< label > & freeSplitCells () const
Cache of unused indices in splitCells.
bool active () const
Is there unrefinement history. Note that this will fall over if.
label parentIndex (const label cellI) const
Get parent of cell.
void storeSplit (const label cellI, const labelList &addedCells)
Store splitting of cell into 8.
void combineCells (const label masterCellI, const labelList &combinedCells)
Store combining 8 cells into master.
void updateMesh (const mapPolyMesh &)
Update numbering for mesh changes.
void subset (const labelList &pointMap, const labelList &faceMap, const labelList &cellMap)
Update numbering for subsetting.
void distribute (const mapDistributePolyMesh &)
Update local numbering for mesh redistribution.
void compact ()
Compact splitCells_. Removes all freeSplitCells_ elements.
void resize (const label nCells)
Extend/shrink storage. additional visibleCells_ elements get.
void writeDebug () const
Debug write.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation.
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Friends
Istream & operator>> (Istream &, refinementHistory &)
Ostream & operator<< (Ostream &, const refinementHistory &)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
All refinement history. Used in unrefinement.
- visibleCells: valid for the current mesh and contains per cell -1 (cell unrefined) or an index into splitCells_.
splitCells: for every split contains the parent (also index into splitCells) and optionally a subsplit as 8 indices into splitCells. Note that the numbers in splitCells are not cell labels, they are purely indices into splitCells.
E.g. 2 cells, cell 1 gets refined so end up with 9 cells:
    // splitCells
    9
    (
    -1 (1 2 3 4 5 6 7 8)
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    )
    // visibleCells
    9(-1 1 2 3 4 5 6 7 8)
So cell0 (visibleCells=-1) is unrefined. Cells 1-8 have all valid splitCells entries which are:
parent:0
subsplits:0()
The parent 0 refers back to the splitcell entries.
Source files
refinementHistory.H
refinementHistory.C
Definition at line 93 of file refinementHistory.H.
Constructor & Destructor Documentation
refinementHistory() [1/5]
refinementHistory (const IOobject & io)
Construct (read) given an IOobject.
Definition at line 330 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), List< T >::size(), and WarningIn.
Referenced by refinementHistory::splitCell8::operator!=(), and refinementHistory::refinementHistory().
refinementHistory() [2/5]
refinementHistory (const IOobject & io, const List< splitCell8 > & splitCells, const labelList & visibleCells)
Construct (read) or construct null.
Read or construct.
Definition at line 369 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), refinementHistory::refinementHistory(), List< T >::size(), and WarningIn.
refinementHistory() [3/5]
refinementHistory (const IOobject & io, const label nCells)
Construct (read) or construct from initial number of cells.
(all visible)
Definition at line 419 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), refinementHistory::refinementHistory(), List< T >::setSize(), List< T >::size(), and WarningIn.
refinementHistory() [4/5]
refinementHistory (const IOobject & io, const refinementHistory & rh)
Construct as copy.
Definition at line 477 of file refinementHistory.C.
References Foam::endl(), and Foam::Pout.
refinementHistory() [5/5]
refinementHistory (const IOobject & io, Istream & is)
Construct from Istream.
Definition at line 496 of file refinementHistory.C.
References Foam::endl(), Foam::Pout, and List< T >::size().
Member Function Documentation
TypeName()
TypeName ("refinementHistory")
Referenced by refinementHistory::splitCell8::operator!=().
visibleCells()
const labelList& visibleCells () const inline
Per cell in the current mesh (i.e. visible) either -1 (unrefined)
or an index into splitCells.
Definition at line 263 of file refinementHistory.H.
Referenced by hexRef8::getSplitPoints(), hexRef8::hexRef8(), and refinementHistory::splitCell8::operator!=().
splitCells()
const DynamicList<splitCell8>& splitCells () const inline
Storage for splitCell8s.
Definition at line 269 of file refinementHistory.H.
Referenced by refinementHistory::splitCell8::operator!=().
freeSplitCells()
const DynamicList<label>& freeSplitCells () const inline
Cache of unused indices in splitCells.
Definition at line 275 of file refinementHistory.H.
References refinementHistory::active(), and List< T >::size().
active()
bool active () const inline
Is there unrefinement history. Note that this will fall over if.
there are 0 cells in the mesh. But this gives problems with lots of other programs anyway.
Definition at line 283 of file refinementHistory.H.
Referenced by refinementHistory::distribute(), hexRef8::distribute(), refinementHistory::freeSplitCells(), hexRef8::getSplitPoints(), hexRef8::hexRef8(), hexRef8::setRefinement(), hexRef8::setUnrefinement(), refinementHistory::subset(), hexRef8::subset(), refinementHistory::updateMesh(), hexRef8::updateMesh(), and hexRef8::write().
parentIndex()
label parentIndex (const label cellI) const inline
Get parent of cell.
Definition at line 289 of file refinementHistory.H.
References Foam::abort(), refinementHistory::combineCells(), refinementHistory::compact(), refinementHistory::distribute(), Foam::FatalError, FatalErrorIn, refinementHistory::splitCell8::operator<<, refinementHistory::splitCell8::operator>>, refinementHistory::readData(), refinementHistory::resize(), refinementHistory::storeSplit(), refinementHistory::subset(), refinementHistory::updateMesh(), refinementHistory::writeData(), and refinementHistory::writeDebug().
Referenced by refinementHistory::combineCells(), hexRef8::getSplitPoints(), and refinementHistory::storeSplit().
storeSplit()
void storeSplit (const label cellI, const labelList & addedCells)
Store splitting of cell into 8.
Definition at line 1102 of file refinementHistory.C.
References refinementHistory::combineCells(), forAll, and refinementHistory::parentIndex().
Referenced by refinementHistory::parentIndex(), hexRef8::setRefinement(), and refinementHistory::writeDebug().
combineCells()
void combineCells (const label masterCellI, const labelList & combinedCells)
Store combining 8 cells into master.
Definition at line 1140 of file refinementHistory.C.
References refinementHistory::splitCell8::addedCellsPtr_, forAll, and refinementHistory::parentIndex().
Referenced by refinementHistory::parentIndex(), hexRef8::setUnrefinement(), and refinementHistory::storeSplit().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Update numbering for mesh changes.
Definition at line 539 of file refinementHistory.C.
References Foam::abort(), refinementHistory::active(), mapPolyMesh::cellMap(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, Foam::Pout, mapPolyMesh::reverseCellMap(), List< T >::size(), refinementHistory::subset(), and List< T >::transfer().
Referenced by refinementHistory::parentIndex(), and hexRef8::updateMesh().
subset()
void subset (const labelList & pointMap, const labelList & faceMap, const labelList & cellMap)
Update numbering for subsetting.
Definition at line 588 of file refinementHistory.C.
References Foam::abort(), refinementHistory::active(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, UPstream::myProcNo(), Foam::Pout, List< T >::size(), and List< T >::transfer().
Referenced by refinementHistory::parentIndex(), hexRef8::subset(), and refinementHistory::updateMesh().
distribute()
void distribute (const mapDistributePolyMesh & map)
Update local numbering for mesh redistribution.
Can only distribute clusters sent across in one go; cannot handle parts recombined in multiple passes.
Definition at line 672 of file refinementHistory.C.
References Foam::abort(), refinementHistory::active(), refinementHistory::splitCell8::addedCellsPtr_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), UPstream::blocking, mapDistributePolyMesh::cellMap(), refinementHistory::compact(), mapDistribute::constructMap(), Foam::FatalError, FatalErrorIn, forAll, mapDistributePolyMesh::mesh(), primitiveMesh::nCells(), UPstream::nProcs(), refinementHistory::splitCell8::parent_, UPstream::parRun(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), and mapDistribute::subMap().
Referenced by hexRef8::distribute(), and refinementHistory::parentIndex().
compact()
void compact ()
Compact splitCells_. Removes all freeSplitCells_ elements.
Definition at line 939 of file refinementHistory.C.
References Foam::abort(), refinementHistory::splitCell8::addedCellsPtr_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, refinementHistory::splitCell8::parent_, Foam::Pout, and List< T >::size().
Referenced by refinementHistory::distribute(), refinementHistory::parentIndex(), and refinementHistory::writeData().
resize()
void resize (const label nCells)
Extend/shrink storage. additional visibleCells_ elements get.
set to -1.
Definition at line 519 of file refinementHistory.C.
References Foam::endl(), Foam::Pout, List< T >::setSize(), and List< T >::size().
Referenced by refinementHistory::parentIndex(), and hexRef8::setRefinement().
writeDebug()
void writeDebug () const
Debug write.
Definition at line 1095 of file refinementHistory.C.
References refinementHistory::storeSplit().
Referenced by refinementHistory::splitCell8::operator!=(), and refinementHistory::parentIndex().
readData()
bool readData (Istream & is) virtual
ReadData function required for regIOobject read operation.
Reimplemented from regIOobject.
Definition at line 1163 of file refinementHistory.C.
References IOstream::bad().
Referenced by refinementHistory::parentIndex().
writeData()
bool writeData (Ostream & os) const virtual
WriteData function required for regIOobject write operation.
Implements regIOobject.
Definition at line 1170 of file refinementHistory.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), refinementHistory::compact(), IOstream::good(), Foam::nl, Foam::operator<<(), and Foam::operator>>().
Referenced by refinementHistory::parentIndex().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , refinementHistory &) friend
operator<<
Ostream& operator<< (Ostream & , const refinementHistory &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementHistory.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementHistory.C