OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
faceCollapser Class Reference
Collapses faces into edges. Used to remove sliver faces (faces with small area but non-zero span).
Public Member Functions
ClassName ("faceCollapser")
Runtime type information.
faceCollapser (const polyMesh &mesh)
Construct from mesh.
void setRefinement (const labelList &faceLabels, const labelList &fpA, const labelList &fpB, polyTopoChange &) const
Collapse faces along endpoints. Play commands into.
void updateMesh (const mapPolyMesh &)
Update stored quantities for new mesh labels.
Detailed Description
Collapses faces into edges. Used to remove sliver faces (faces with small area but non-zero span).
Passed in as
face label
the two indices in the face (fpA, fpB) which delimit the vertices to be kept.
Takes the vertices outside the range fpA..fpB and projects them onto the kept edges (edges using kept vertices only).
Note:
Use in combination with edge collapse to cleanup meshes.
Can not remove cells so will mess up trying to remove a face on a tet.
WIP. Should be combined with edge collapsing and cell collapsing into proper 'collapser'.
Caller is responsible for making sure kept vertices (fpA..fpB) for one face are not the vertices to be removed for another face.
Source files
faceCollapser.H
faceCollapser.C
Definition at line 75 of file faceCollapser.H.
Constructor & Destructor Documentation
faceCollapser()
faceCollapser (const polyMesh & mesh)
Construct from mesh.
Definition at line 201 of file faceCollapser.C.
References faceCollapser::setRefinement().
Member Function Documentation
ClassName()
ClassName ("faceCollapser")
Runtime type information.
setRefinement()
void setRefinement (const labelList & faceLabels, const labelList & fpA, const labelList & fpB, polyTopoChange & meshMod) const
Collapse faces along endpoints. Play commands into.
polyTopoChange to create mesh.
Definition at line 210 of file faceCollapser.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), primitiveMesh::edgeFaces(), primitiveMesh::edges(), Foam::endl(), primitiveMesh::faceEdges(), polyMesh::faces(), Foam::FatalError, FatalErrorIn, UList< T >::fcIndex(), forAll, forAllConstIter(), SortableList< T >::indices(), Foam::magSqr(), line< Point, PointRef >::nearestDist(), Foam::nl, points, polyMesh::points(), Foam::Pout, PointHit< Point >::rawPoint(), UList< T >::rcIndex(), Foam::reverse(), polyTopoChange::setAction(), PointHit< Point >::setPoint(), List< T >::size(), SortableList< T >::sort(), Foam::sqrt(), edge::start(), and Foam::meshTools::writeOBJ().
Referenced by faceCollapser::faceCollapser().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Update stored quantities for new mesh labels.
Definition at line 148 of file faceCollapser.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/faceCollapser.H
src/dynamicMesh/polyTopoChange/polyTopoChange/faceCollapser.C