OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyModifyCell Class Reference
Class describing modification of a cell.
Public Member Functions
TypeName ("modifyCell")
Runtime type information.
polyModifyCell ()
Construct null. Used only for list construction.
polyModifyCell (const label cellID, const bool removeFromZone, const label newZoneID)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
label cellID () const
Cell ID.
bool isInZone () const
Does the cell belong to a zone?
bool removeFromZone () const
label zoneID () const
Cell zone ID.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class describing modification of a cell.
Definition at line 46 of file polyModifyCell.H.
Constructor & Destructor Documentation
polyModifyCell() [1/2]
polyModifyCell () inline
Construct null. Used only for list construction.
Definition at line 73 of file polyModifyCell.H.
Referenced by polyModifyCell::clone().
polyModifyCell() [2/2]
polyModifyCell (const label cellID, const bool removeFromZone, const label newZoneID) inline
Construct from components.
Definition at line 82 of file polyModifyCell.H.
Member Function Documentation
TypeName()
TypeName ("modifyCell")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 94 of file polyModifyCell.H.
References polyModifyCell::polyModifyCell().
cellID()
label cellID () const inline
Cell ID.
Definition at line 105 of file polyModifyCell.H.
Referenced by polyTopoChange::setAction().
isInZone()
bool isInZone () const inline
Does the cell belong to a zone?
Definition at line 111 of file polyModifyCell.H.
removeFromZone()
bool removeFromZone () const inline
Definition at line 116 of file polyModifyCell.H.
Referenced by polyTopoChange::setAction().
zoneID()
label zoneID () const inline
Cell zone ID.
Definition at line 122 of file polyModifyCell.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/modifyObject/polyModifyCell.H