OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
refinementHistory::splitCell8 Class Reference
Public Member Functions
splitCell8 ()
Construct null (parent = -1)
splitCell8 (const label parent)
Construct from parent.
splitCell8 (Istream &is)
Construct from Istream.
splitCell8 (const splitCell8 &)
Construct as deep copy.
void operator= (const splitCell8 &s)
Copy operator since autoPtr otherwise 'steals' storage.
bool operator== (const splitCell8 &s) const
bool operator!= (const splitCell8 &s) const
Public Attributes
label parent_
autoPtr< FixedList< label, 8 > > addedCellsPtr_
cells this cell was refined into
Friends
Istream & operator>> (Istream &, splitCell8 &)
Ostream & operator<< (Ostream &, const splitCell8 &)
Detailed Description
Definition at line 99 of file refinementHistory.H.
Constructor & Destructor Documentation
splitCell8() [1/4]
splitCell8 ()
Construct null (parent = -1)
Construct null.
Definition at line 112 of file refinementHistory.C.
Referenced by refinementHistory::splitCell8::splitCell8().
splitCell8() [2/4]
splitCell8 (const label parent)
Construct from parent.
Construct as child element of parent.
Definition at line 120 of file refinementHistory.C.
splitCell8() [3/4]
splitCell8 (Istream & is)
Construct from Istream.
Definition at line 128 of file refinementHistory.C.
splitCell8() [4/4]
splitCell8 (const splitCell8 & sc)
Construct as deep copy.
Construct as (deep) copy.
Definition at line 135 of file refinementHistory.C.
References Foam::abort(), refinementHistory::splitCell8::addedCellsPtr_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), forAll, Foam::nl, Foam::operator>>(), refinementHistory::splitCell8::parent_, List< T >::size(), token::SPACE, refinementHistory::splitCell8::splitCell8(), and autoPtr< T >::valid().
Member Function Documentation
operator=()
void operator= (const splitCell8 & s) inline
Copy operator since autoPtr otherwise 'steals' storage.
Definition at line 124 of file refinementHistory.H.
References Foam::abort(), refinementHistory::splitCell8::addedCellsPtr_, Foam::FatalError, FatalErrorIn, refinementHistory::splitCell8::parent_, and autoPtr< T >::reset().
operator==()
bool operator== (const splitCell8 & s) const inline
Definition at line 144 of file refinementHistory.H.
References refinementHistory::splitCell8::addedCellsPtr_, refinementHistory::splitCell8::parent_, and autoPtr< T >::valid().
Referenced by refinementHistory::splitCell8::operator!=().
operator!=()
bool operator!= (const splitCell8 & s) const inline
Definition at line 164 of file refinementHistory.H.
References refinementHistory::splitCell8::operator<<, refinementHistory::splitCell8::operator==(), refinementHistory::splitCell8::operator>>, refinementHistory::refinementHistory(), refinementHistory::splitCells(), refinementHistory::TypeName(), refinementHistory::visibleCells(), and refinementHistory::writeDebug().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , splitCell8 &) friend
Referenced by refinementHistory::splitCell8::operator!=(), and refinementHistory::parentIndex().
operator<<
Ostream& operator<< (Ostream & , const splitCell8 &) friend
Referenced by refinementHistory::splitCell8::operator!=(), and refinementHistory::parentIndex().
Member Data Documentation
parent_
label parent_
Definition at line 106 of file refinementHistory.H.
Referenced by refinementHistory::compact(), refinementHistory::distribute(), refinementHistory::splitCell8::operator=(), refinementHistory::splitCell8::operator==(), and refinementHistory::splitCell8::splitCell8().
addedCellsPtr_
autoPtr<FixedList<label, 8> > addedCellsPtr_
cells this cell was refined into
Definition at line 109 of file refinementHistory.H.
Referenced by refinementHistory::combineCells(), refinementHistory::compact(), refinementHistory::distribute(), refinementHistory::splitCell8::operator=(), refinementHistory::splitCell8::operator==(), and refinementHistory::splitCell8::splitCell8().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementHistory.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementHistory.C