OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
refinementDistanceData Class Reference
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Public Member Functions
refinementDistanceData ()
Construct null.
refinementDistanceData (const scalar level0Size, const point &origin, const label level)
Construct from count.
scalar level0Size () const
scalar & level0Size ()
const point & origin () const
point & origin ()
label originLevel () const
label & originLevel ()
label wantedLevel (const point &pt) const
Calculates the wanted level at a given point. Walks out from.
template<class TrackingData >
bool valid (TrackingData &) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const refinementDistanceData &, const scalar, TrackingData &) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
Influence of different value on same face.
template<class TrackingData >
bool equal (const refinementDistanceData &, TrackingData &) const
Same (like operator==)
bool operator== (const refinementDistanceData &) const
bool operator!= (const refinementDistanceData &) const
Friends
Ostream & operator<< (Ostream &, const refinementDistanceData &)
Istream & operator>> (Istream &, refinementDistanceData &)
Detailed Description
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Source files
refinementDistanceData.H
refinementDistanceDataI.H
refinementDistanceData.C
Definition at line 54 of file refinementDistanceData.H.
Constructor & Destructor Documentation
refinementDistanceData() [1/2]
refinementDistanceData () inline
Construct null.
Definition at line 125 of file refinementDistanceDataI.H.
refinementDistanceData() [2/2]
refinementDistanceData (const scalar level0Size, const point & origin, const label level) inline
Construct from count.
Definition at line 133 of file refinementDistanceDataI.H.
Member Function Documentation
level0Size() [1/2]
scalar level0Size () const inline
Definition at line 99 of file refinementDistanceData.H.
level0Size() [2/2]
scalar& level0Size () inline
Definition at line 104 of file refinementDistanceData.H.
origin() [1/2]
const point& origin () const inline
Definition at line 109 of file refinementDistanceData.H.
Referenced by refinementDistanceData::wantedLevel().
origin() [2/2]
point& origin () inline
Definition at line 114 of file refinementDistanceData.H.
originLevel() [1/2]
label originLevel () const inline
Definition at line 119 of file refinementDistanceData.H.
originLevel() [2/2]
label& originLevel () inline
Definition at line 124 of file refinementDistanceData.H.
References refinementDistanceData::enterDomain(), refinementDistanceData::equal(), refinementDistanceData::leaveDomain(), refinementDistanceData::operator!=(), refinementDistanceData::operator<<, refinementDistanceData::operator==(), refinementDistanceData::operator>>, refinementDistanceData::sameGeometry(), refinementDistanceData::transform(), refinementDistanceData::updateCell(), refinementDistanceData::updateFace(), refinementDistanceData::valid(), and refinementDistanceData::wantedLevel().
wantedLevel()
Foam::label wantedLevel (const point & pt) const inline
Calculates the wanted level at a given point. Walks out from.
the origin.
Definition at line 32 of file refinementDistanceDataI.H.
References Foam::abort(), Foam::diff(), Foam::FatalError, FatalErrorIn, Foam::magSqr(), refinementDistanceData::origin(), Foam::pos(), Foam::sqr(), refinementDistanceData::valid(), and refinementDistanceData::wantedLevel().
Referenced by refinementDistanceData::originLevel(), and refinementDistanceData::wantedLevel().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 148 of file refinementDistanceDataI.H.
References refinementDistanceData::sameGeometry().
Referenced by refinementDistanceData::equal(), refinementDistanceData::originLevel(), and refinementDistanceData::wantedLevel().
sameGeometry()
bool sameGeometry (const polyMesh & , const refinementDistanceData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 157 of file refinementDistanceDataI.H.
References refinementDistanceData::leaveDomain().
Referenced by refinementDistanceData::originLevel(), and refinementDistanceData::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 170 of file refinementDistanceDataI.H.
References refinementDistanceData::transform().
Referenced by refinementDistanceData::originLevel(), and refinementDistanceData::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 197 of file refinementDistanceDataI.H.
References refinementDistanceData::updateCell().
Referenced by refinementDistanceData::originLevel(), and refinementDistanceData::transform().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 184 of file refinementDistanceDataI.H.
References refinementDistanceData::enterDomain(), and Foam::transform().
Referenced by refinementDistanceData::leaveDomain(), and refinementDistanceData::originLevel().
updateCell()
bool updateCell (const polyMesh & mesh, const label thisCellI, const label neighbourFaceI, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 213 of file refinementDistanceDataI.H.
References primitiveMesh::cellCentres(), and refinementDistanceData::updateFace().
Referenced by refinementDistanceData::enterDomain(), and refinementDistanceData::originLevel().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const label neighbourCellI, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 231 of file refinementDistanceDataI.H.
References primitiveMesh::faceCentres().
Referenced by refinementDistanceData::originLevel(), and refinementDistanceData::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 249 of file refinementDistanceDataI.H.
References refinementDistanceData::equal(), and primitiveMesh::faceCentres().
equal()
bool equal (const refinementDistanceData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 265 of file refinementDistanceDataI.H.
References refinementDistanceData::operator==(), and refinementDistanceData::valid().
Referenced by refinementDistanceData::originLevel(), and refinementDistanceData::updateFace().
operator==()
bool operator== (const refinementDistanceData & rhs) const inline
Definition at line 291 of file refinementDistanceDataI.H.
Referenced by refinementDistanceData::equal(), and refinementDistanceData::originLevel().
operator!=()
bool operator!= (const refinementDistanceData & rhs) const inline
Definition at line 304 of file refinementDistanceDataI.H.
Referenced by refinementDistanceData::originLevel().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const refinementDistanceData &) friend
Referenced by refinementDistanceData::originLevel().
operator>>
Istream& operator>> (Istream & , refinementDistanceData &) friend
Referenced by refinementDistanceData::originLevel().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDistanceData.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDistanceDataI.H