OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
edgeMeshFormatsCore Class Reference
A collection of helper functions for reading/writing edge formats.
Public Member Functions
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Static Public Member Functions
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Attributes
static word nativeExt
The file extension corresponding to 'native' edge format.
Static Protected Member Functions
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
A collection of helper functions for reading/writing edge formats.
Source files
edgeMeshFormatsCore.H
edgeMeshFormatsCore.C
Definition at line 58 of file edgeMeshFormatsCore.H.
Constructor & Destructor Documentation
edgeMeshFormatsCore()
edgeMeshFormatsCore ()
Construct null.
Definition at line 189 of file edgeMeshFormatsCore.C.
~edgeMeshFormatsCore()
~edgeMeshFormatsCore () virtual
Destructor.
Definition at line 195 of file edgeMeshFormatsCore.C.
Member Function Documentation
getLineNoComment()
Foam::string getLineNoComment (IFstream & is) static protected
Read non-comment line.
Definition at line 41 of file edgeMeshFormatsCore.C.
References edgeMeshFormatsCore::checkSupport(), TimePaths::constant(), surfaceRegistry::defaultName, ISstream::getLine(), IOstream::good(), Foam::isFile(), meshName, surfMesh::meshSubDir, Foam::name(), edgeMeshFormatsCore::nativeExt, Time::path(), surfaceRegistry::prefix, List< T >::size(), TimeState::timeOutputValue(), and Time::times().
Referenced by OBJedgeFormat::read().
checkSupport()
bool checkSupport (const wordHashSet & available, const word & ext, const bool verbose, const word & functionName) static
Definition at line 157 of file edgeMeshFormatsCore.C.
References Foam::endl(), forAll, HashTable< T, Key, Hash >::found(), Foam::Info, Foam::nl, and HashTable< T, Key, Hash >::sortedToc().
Referenced by edgeMeshFormatsCore::getLineNoComment().
Member Data Documentation
nativeExt
Foam::word nativeExt static
The file extension corresponding to 'native' edge format.
Normally "eMesh" (edge-mesh)
Definition at line 73 of file edgeMeshFormatsCore.H.
Referenced by edgeMeshFormatsCore::getLineNoComment().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMeshFormats/edgeMeshFormatsCore.H
src/edgeMesh/edgeMeshFormats/edgeMeshFormatsCore.C