OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
slidingInterface Class Reference
Sliding interface mesh modifier. Given two face zones, couple the master and slave side using a cutting procedure.
Public Types
enum typeOfMatch { INTEGRAL, PARTIAL }
Type of match.
Public Member Functions
TypeName ("slidingInterface")
Runtime type information.
slidingInterface (const word &name, const label index, const polyTopoChanger &mme, const word &masterFaceZoneName, const word &slaveFaceZoneName, const word &cutPointZoneName, const word &cutFaceZoneName, const word &masterPatchName, const word &slavePatchName, const typeOfMatch tom, const bool coupleDecouple=false, const intersection::algorithm algo=intersection::VISIBLE)
Construct from components.
slidingInterface (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Construct from dictionary.
virtual ~slidingInterface ()
Destructor.
const faceZoneID & masterFaceZoneID () const
Return master face zone ID.
const faceZoneID & slaveFaceZoneID () const
Return slave face zone ID.
bool attached () const
Return true if attached.
virtual bool changeTopology () const
Check for topology change.
virtual void setRefinement (polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const pointField & pointProjection () const
Return projected points for a slave patch.
void setTolerances (const dictionary &, bool report=false)
Set the tolerances from the values in a dictionary.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
Static Public Attributes
static const NamedEnum< typeOfMatch, 2 > typeOfMatchNames_
Direction names.
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Detailed Description
Sliding interface mesh modifier. Given two face zones, couple the master and slave side using a cutting procedure.
The coupled faces are collected into the "coupled" zone and can become either internal or placed into a master and slave coupled zone. The remaining faces (uncovered master or slave) are placed into the master and slave patch.
The definition of the sliding interface can be either integral or partial. Integral interface implies that the slave side completely covers the master (i.e. no faces are uncovered); partial interface implies that the uncovered part of master/slave face zone should become boundary faces.
Source files
slidingInterface.H
slidingInterface.C
coupleSlidingInterface.C
decoupleSlidingInterface.C
slidingInterfaceProjectPoints.C
slidingInterfaceAttachedAddressing.C
slidingInterfaceClearCouple.C
Definition at line 71 of file slidingInterface.H.
Member Enumeration Documentation
typeOfMatch
enum typeOfMatch
Type of match.
Enumerator
INTEGRAL
PARTIAL
Definition at line 80 of file slidingInterface.H.
Constructor & Destructor Documentation
slidingInterface() [1/2]
slidingInterface (const word & name, const label index, const polyTopoChanger & mme, const word & masterFaceZoneName, const word & slaveFaceZoneName, const word & cutPointZoneName, const word & cutFaceZoneName, const word & masterPatchName, const word & slavePatchName, const typeOfMatch tom, const bool coupleDecouple = false, const intersection::algorithm algo = intersection::VISIBLE)
Construct from components.
Definition at line 125 of file slidingInterface.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
slidingInterface() [2/2]
slidingInterface (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Construct from dictionary.
Definition at line 231 of file slidingInterface.C.
References Foam::endl(), dictionary::lookup(), and Foam::Pout.
~slidingInterface()
~slidingInterface () virtual
Destructor.
Definition at line 330 of file slidingInterface.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
TypeName()
TypeName ("slidingInterface")
Runtime type information.
masterFaceZoneID()
const Foam::faceZoneID & masterFaceZoneID () const
Return master face zone ID.
Definition at line 345 of file slidingInterface.C.
slaveFaceZoneID()
const Foam::faceZoneID & slaveFaceZoneID () const
Return slave face zone ID.
Definition at line 351 of file slidingInterface.C.
attached()
bool attached () const inline
Return true if attached.
Definition at line 353 of file slidingInterface.H.
References slidingInterface::changeTopology(), slidingInterface::modifyMotionPoints(), slidingInterface::pointProjection(), slidingInterface::setRefinement(), slidingInterface::setTolerances(), slidingInterface::updateMesh(), slidingInterface::write(), and slidingInterface::writeDict().
changeTopology()
bool changeTopology () const virtual
Check for topology change.
Implements polyMeshModifier.
Definition at line 357 of file slidingInterface.C.
References Foam::endl(), mesh, Foam::name(), and Foam::Pout.
Referenced by slidingInterface::attached().
setRefinement()
void setRefinement (polyTopoChange & ref) const virtual
Insert the layer addition/removal instructions.
into the topological change
Implements polyMeshModifier.
Definition at line 398 of file slidingInterface.C.
Referenced by slidingInterface::attached().
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Modify motion points to comply with the topological change.
Implements polyMeshModifier.
Definition at line 431 of file slidingInterface.C.
References Foam::abort(), Foam::constant::physicoChemical::b, Foam::constant::universal::c, PointHit< Point >::distance(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), HashTableCore::end(), Foam::endl(), polyMesh::faceZones(), Foam::FatalError, FatalErrorIn, HashTable< T, Key, Hash >::find(), HashTable< T, label, Hash< label > >::find(), forAll, PointHit< Point >::hit(), PointHit< Point >::hitPoint(), edge::line(), plane::lineIntersect(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), line< Point, PointRef >::mag(), Foam::mag(), mesh, PointHit< Point >::missPoint(), Foam::name(), line< Point, PointRef >::nearestDist(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointNormals(), polyMesh::pointZones(), Foam::Pout, List< T >::size(), Foam::sqr(), edge::start(), line< Point, PointRef >::start(), edge::vec(), line< Point, PointRef >::vec(), PrimitivePatch< Face, FaceList, PointField, PointType >::whichEdge(), and PrimitivePatch< Face, FaceList, PointField, PointType >::whichPoint().
Referenced by slidingInterface::attached().
updateMesh()
void updateMesh (const mapPolyMesh & m) virtual
Force recalculation of locally stored data on topological change.
Implements polyMeshModifier.
Definition at line 667 of file slidingInterface.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceZones(), mesh, Foam::name(), polyMesh::pointZones(), Foam::Pout, and dynamicFvMesh::update().
Referenced by slidingInterface::attached().
pointProjection()
const Foam::pointField & pointProjection () const
Return projected points for a slave patch.
Definition at line 699 of file slidingInterface.C.
Referenced by slidingInterface::attached().
setTolerances()
void setTolerances (const dictionary & dict, bool report = false)
Set the tolerances from the values in a dictionary.
Definition at line 709 of file slidingInterface.C.
References Foam::endl(), Foam::Info, dictionary::lookupOrDefault(), and Foam::nl.
Referenced by slidingInterface::attached().
write()
void write (Ostream & os) const virtual
Write.
Implements polyMeshModifier.
Definition at line 767 of file slidingInterface.C.
References Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
Referenced by slidingInterface::attached().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements polyMeshModifier.
Definition at line 791 of file slidingInterface.C.
References intersection::algorithmNames_, token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, Foam::type(), and WRITE_NON_DEFAULT.
Referenced by slidingInterface::attached().
Member Data Documentation
typeOfMatchNames_
const Foam::NamedEnum< Foam::slidingInterface::typeOfMatch, 2 > typeOfMatchNames_ static
Direction names.
Definition at line 87 of file slidingInterface.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/dynamicMesh/slidingInterface/slidingInterface.H
src/dynamicMesh/slidingInterface/coupleSlidingInterface.C
src/dynamicMesh/slidingInterface/decoupleSlidingInterface.C
src/dynamicMesh/slidingInterface/slidingInterface.C
src/dynamicMesh/slidingInterface/slidingInterfaceAttachedAddressing.C
src/dynamicMesh/slidingInterface/slidingInterfaceClearCouple.C
src/dynamicMesh/slidingInterface/slidingInterfaceProjectPoints.C