OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyRemoveCell Class Reference
Class containing data for cell removal.
Public Member Functions
TypeName ("removeCell")
Runtime type information.
polyRemoveCell ()
Construct null. Used for constructing lists.
polyRemoveCell (const label cellID, const label mergeCellID=-1)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
label cellID () const
Return cell ID.
label mergeCellID () const
Return cell ID.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class containing data for cell removal.
Definition at line 46 of file polyRemoveCell.H.
Constructor & Destructor Documentation
polyRemoveCell() [1/2]
polyRemoveCell () inline
Construct null. Used for constructing lists.
Definition at line 69 of file polyRemoveCell.H.
Referenced by polyRemoveCell::clone().
polyRemoveCell() [2/2]
polyRemoveCell (const label cellID, const label mergeCellID = -1) inline
Construct from components.
Definition at line 76 of file polyRemoveCell.H.
Member Function Documentation
TypeName()
TypeName ("removeCell")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 83 of file polyRemoveCell.H.
References polyRemoveCell::polyRemoveCell().
cellID()
label cellID () const inline
Return cell ID.
Definition at line 95 of file polyRemoveCell.H.
Referenced by polyTopoChange::setAction().
mergeCellID()
label mergeCellID () const inline
Return cell ID.
Definition at line 101 of file polyRemoveCell.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeObject/polyRemoveCell.H