OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setUpdater Class Reference
Keeps cell/face/vertex sets uptodate. Both the ones loaded and the ones on disk.
Public Member Functions
TypeName ("setUpdater")
Runtime type information.
setUpdater (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Construct from dictionary.
virtual ~setUpdater ()
Destructor.
virtual bool changeTopology () const
Check for topology change.
virtual void setRefinement (polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Detailed Description
Keeps cell/face/vertex sets uptodate. Both the ones loaded and the ones on disk.
Source files
setUpdater.H
setUpdater.C
setUpdaterTemplates.C
Definition at line 50 of file setUpdater.H.
Constructor & Destructor Documentation
setUpdater()
setUpdater (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Construct from dictionary.
Definition at line 57 of file setUpdater.C.
~setUpdater()
~setUpdater () virtual
Destructor.
Definition at line 70 of file setUpdater.C.
Member Function Documentation
TypeName()
TypeName ("setUpdater")
Runtime type information.
changeTopology()
bool changeTopology () const virtual
Check for topology change.
Implements polyMeshModifier.
Definition at line 76 of file setUpdater.C.
setRefinement()
void setRefinement (polyTopoChange &) const virtual
Insert the layer addition/removal instructions.
into the topological change
Implements polyMeshModifier.
Definition at line 83 of file setUpdater.C.
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Modify motion points to comply with the topological change.
Implements polyMeshModifier.
Definition at line 87 of file setUpdater.C.
updateMesh()
void updateMesh (const mapPolyMesh & morphMap) virtual
Force recalculation of locally stored data on topological change.
Implements polyMeshModifier.
Definition at line 91 of file setUpdater.C.
References Foam::endl(), and Foam::Pout.
write()
void write (Ostream & os) const virtual
Write.
Implements polyMeshModifier.
Definition at line 106 of file setUpdater.C.
References Foam::nl, and Foam::type().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements polyMeshModifier.
Definition at line 112 of file setUpdater.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
The documentation for this class was generated from the following files:
src/dynamicMesh/setUpdater/setUpdater.H
src/dynamicMesh/setUpdater/setUpdater.C
src/dynamicMesh/setUpdater/setUpdaterTemplates.C