OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyRemoveFace Class Reference
Class containing data for face removal.
Public Member Functions
TypeName ("removeFace")
Runtime type information.
polyRemoveFace ()
Construct null. Used for constructing lists.
polyRemoveFace (const label faceID, const label mergeFaceID=-1)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
label faceID () const
Return face ID.
label mergeFaceID () const
Return merge face ID.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class containing data for face removal.
Definition at line 46 of file polyRemoveFace.H.
Constructor & Destructor Documentation
polyRemoveFace() [1/2]
polyRemoveFace () inline
Construct null. Used for constructing lists.
Definition at line 69 of file polyRemoveFace.H.
Referenced by polyRemoveFace::clone().
polyRemoveFace() [2/2]
polyRemoveFace (const label faceID, const label mergeFaceID = -1) inline
Construct from components.
Definition at line 76 of file polyRemoveFace.H.
Member Function Documentation
TypeName()
TypeName ("removeFace")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 83 of file polyRemoveFace.H.
References polyRemoveFace::polyRemoveFace().
faceID()
label faceID () const inline
Return face ID.
Definition at line 95 of file polyRemoveFace.H.
Referenced by polyTopoChange::setAction().
mergeFaceID()
label mergeFaceID () const inline
Return merge face ID.
Definition at line 101 of file polyRemoveFace.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeObject/polyRemoveFace.H