OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
enginePiston Class Reference
Foam::enginePiston.
Public Member Functions
enginePiston (const polyMesh &mesh, const word &pistonPatchName, const autoPtr< coordinateSystem > &pistonCS, const scalar minLayer, const scalar maxLayer)
Construct from components.
enginePiston (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
const coordinateSystem & cs () const
Return coordinate system.
const polyPatchID & patchID () const
Return ID of piston patch.
scalar minLayer () const
scalar maxLayer () const
void writeDict (Ostream &) const
Write dictionary.
Detailed Description
Foam::enginePiston.
Source files
enginePiston.H
enginePiston.C
Definition at line 53 of file enginePiston.H.
Constructor & Destructor Documentation
enginePiston() [1/2]
enginePiston (const polyMesh & mesh, const word & pistonPatchName, const autoPtr< coordinateSystem > & pistonCS, const scalar minLayer, const scalar maxLayer)
Construct from components.
Definition at line 35 of file enginePiston.C.
enginePiston() [2/2]
enginePiston (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 54 of file enginePiston.C.
Member Function Documentation
cs()
const coordinateSystem& cs () const inline
Return coordinate system.
Definition at line 120 of file enginePiston.H.
patchID()
const polyPatchID& patchID () const inline
Return ID of piston patch.
Definition at line 126 of file enginePiston.H.
minLayer()
scalar minLayer () const inline
Definition at line 133 of file enginePiston.H.
maxLayer()
scalar maxLayer () const inline
Definition at line 138 of file enginePiston.H.
References enginePiston::writeDict().
writeDict()
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 80 of file enginePiston.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), DynamicID< ObjectType >::name(), and Foam::nl.
Referenced by enginePiston::maxLayer().
The documentation for this class was generated from the following files:
src/engine/enginePiston/enginePiston.H
src/engine/enginePiston/enginePiston.C