OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
engineValve Class Reference
Foam::engineValve.
Public Member Functions
engineValve (const word &name, const polyMesh &mesh, const autoPtr< coordinateSystem > &valveCS, const word &bottomPatchName, const word &poppetPatchName, const word &stemPatchName, const word &curtainInPortPatchName, const word &curtainInCylinderPatchName, const word &detachInCylinderPatchName, const word &detachInPortPatchName, const labelList &detachFaces, const graph &liftProfile, const scalar minLift, const scalar minTopLayer, const scalar maxTopLayer, const scalar minBottomLayer, const scalar maxBottomLayer, const scalar diameter)
Construct from components.
engineValve (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
const word & name () const
Return name.
const coordinateSystem & cs () const
Return coordinate system.
const graph & liftProfile () const
Return lift profile.
scalar diameter () const
Return valve diameter.
const polyPatchID & bottomPatchID () const
Return ID of bottom patch.
const polyPatchID & poppetPatchID () const
Return ID of poppet patch.
const polyPatchID & stemPatchID () const
Return ID of stem patch.
const polyPatchID & curtainInCylinderPatchID () const
Return ID of curtain in cylinder patch.
const polyPatchID & curtainInPortPatchID () const
Return ID of curtain in port patch.
const polyPatchID & detachInCylinderPatchID () const
Return ID of detach in cylinder patch.
const polyPatchID & detachInPortPatchID () const
Return ID of detach in port patch.
const labelList & detachFaces () const
Return face labels of detach curtain.
scalar minTopLayer () const
scalar maxTopLayer () const
scalar minBottomLayer () const
scalar maxBottomLayer () const
scalar lift (const scalar theta) const
Return valve lift given crank angle in degrees.
bool isOpen () const
Is the valve open?
scalar curLift () const
Return current lift.
scalar curVelocity () const
Return valve velocity for current time-step.
labelList movingPatchIDs () const
Return list of active patch labels for the valve head.
void writeDict (Ostream &) const
Write dictionary.
Detailed Description
Foam::engineValve.
Source files
engineValve.H
engineValve.C
Definition at line 55 of file engineValve.H.
Constructor & Destructor Documentation
engineValve() [1/2]
engineValve (const word & name, const polyMesh & mesh, const autoPtr< coordinateSystem > & valveCS, const word & bottomPatchName, const word & poppetPatchName, const word & stemPatchName, const word & curtainInPortPatchName, const word & curtainInCylinderPatchName, const word & detachInCylinderPatchName, const word & detachInPortPatchName, const labelList & detachFaces, const graph & liftProfile, const scalar minLift, const scalar minTopLayer, const scalar maxTopLayer, const scalar minBottomLayer, const scalar maxBottomLayer, const scalar diameter)
Construct from components.
Definition at line 68 of file engineValve.C.
engineValve() [2/2]
engineValve (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 115 of file engineValve.C.
Member Function Documentation
name()
const word& name () const inline
Return name.
Definition at line 191 of file engineValve.H.
Referenced by engineValve::writeDict().
cs()
const coordinateSystem& cs () const inline
Return coordinate system.
Definition at line 197 of file engineValve.H.
Referenced by engineValve::writeDict().
liftProfile()
const graph& liftProfile () const inline
Return lift profile.
Definition at line 203 of file engineValve.H.
diameter()
scalar diameter () const inline
Return valve diameter.
Definition at line 209 of file engineValve.H.
bottomPatchID()
const polyPatchID& bottomPatchID () const inline
Return ID of bottom patch.
Definition at line 218 of file engineValve.H.
poppetPatchID()
const polyPatchID& poppetPatchID () const inline
Return ID of poppet patch.
Definition at line 224 of file engineValve.H.
stemPatchID()
const polyPatchID& stemPatchID () const inline
Return ID of stem patch.
Definition at line 230 of file engineValve.H.
curtainInCylinderPatchID()
const polyPatchID& curtainInCylinderPatchID () const inline
Return ID of curtain in cylinder patch.
Definition at line 236 of file engineValve.H.
curtainInPortPatchID()
const polyPatchID& curtainInPortPatchID () const inline
Return ID of curtain in port patch.
Definition at line 242 of file engineValve.H.
detachInCylinderPatchID()
const polyPatchID& detachInCylinderPatchID () const inline
Return ID of detach in cylinder patch.
Definition at line 249 of file engineValve.H.
detachInPortPatchID()
const polyPatchID& detachInPortPatchID () const inline
Return ID of detach in port patch.
Definition at line 255 of file engineValve.H.
detachFaces()
const labelList& detachFaces () const inline
Return face labels of detach curtain.
Definition at line 261 of file engineValve.H.
minTopLayer()
scalar minTopLayer () const inline
Definition at line 269 of file engineValve.H.
maxTopLayer()
scalar maxTopLayer () const inline
Definition at line 274 of file engineValve.H.
minBottomLayer()
scalar minBottomLayer () const inline
Definition at line 279 of file engineValve.H.
maxBottomLayer()
scalar maxBottomLayer () const inline
Definition at line 284 of file engineValve.H.
References engineValve::curLift(), engineValve::curVelocity(), engineValve::isOpen(), engineValve::lift(), engineValve::movingPatchIDs(), and engineValve::writeDict().
lift()
Foam::scalar lift (const scalar theta) const
Return valve lift given crank angle in degrees.
Definition at line 173 of file engineValve.C.
References Foam::interpolateXY(), graph::x(), and graph::y().
Referenced by engineValve::curLift(), engineValve::curVelocity(), engineValve::isOpen(), and engineValve::maxBottomLayer().
isOpen()
bool isOpen () const
Is the valve open?
Definition at line 184 of file engineValve.C.
References engineValve::lift(), and engineTime::theta().
Referenced by engineValve::maxBottomLayer().
curLift()
Foam::scalar curLift () const
Return current lift.
Definition at line 190 of file engineValve.C.
References engineValve::lift(), Foam::max(), and engineTime::theta().
Referenced by engineValve::curVelocity(), and engineValve::maxBottomLayer().
curVelocity()
Foam::scalar curVelocity () const
Return valve velocity for current time-step.
Definition at line 200 of file engineValve.C.
References engineValve::curLift(), engineTime::deltaTheta(), TimeState::deltaTValue(), engineValve::lift(), Foam::max(), and engineTime::theta().
Referenced by engineValve::maxBottomLayer().
movingPatchIDs()
Foam::labelList movingPatchIDs () const
Return list of active patch labels for the valve head.
(stem is excluded)
Definition at line 214 of file engineValve.C.
References DynamicID< ObjectType >::active(), DynamicID< ObjectType >::index(), and List< T >::setSize().
Referenced by engineValve::maxBottomLayer().
writeDict()
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 237 of file engineValve.C.
References token::BEGIN_BLOCK, engineValve::cs(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), DynamicID< ObjectType >::name(), engineValve::name(), Foam::nl, and coordinateSystem::writeDict().
Referenced by engineValve::maxBottomLayer().
The documentation for this class was generated from the following files:
src/engine/engineValve/engineValve.H
src/engine/engineValve/engineValve.C