OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ignition Class Reference
Foam::ignition.
Public Member Functions
ignition (const dictionary &, const Time &, const fvMesh &)
Construct from Istream and database.
ignition (const dictionary &, const engineTime &, const fvMesh &)
Construct from Istream and engineTime.
const PtrList< ignitionSite > & sites ()
Return the set of ignition sites.
bool ignite () const
bool igniting () const
Are any of the ignition site currently igniting.
bool ignited () const
Has the mixture been ignited?
Detailed Description
Foam::ignition.
Source files
ignition.H
ignition.C
ignitionIO.C
Definition at line 52 of file ignition.H.
Constructor & Destructor Documentation
ignition() [1/2]
ignition (const dictionary & combustionProperties, const Time & db, const fvMesh & mesh)
Construct from Istream and database.
Definition at line 32 of file ignitionIO.C.
References Foam::endl(), and Foam::Info.
ignition() [2/2]
ignition (const dictionary & combustionProperties, const engineTime & edb, const fvMesh & mesh)
Construct from Istream and engineTime.
Definition at line 58 of file ignitionIO.C.
References Foam::endl(), and Foam::Info.
Member Function Documentation
sites()
const PtrList<ignitionSite>& sites () inline
Return the set of ignition sites.
Definition at line 86 of file ignition.H.
ignite()
bool ignite () const inline
Definition at line 94 of file ignition.H.
References ignition::ignited(), and ignition::igniting().
Referenced by ignition::ignited(), and ignition::igniting().
igniting()
bool igniting () const
Are any of the ignition site currently igniting.
Definition at line 32 of file ignition.C.
References forAll, and ignition::ignite().
Referenced by ignition::ignite().
ignited()
bool ignited () const
Has the mixture been ignited?
Definition at line 53 of file ignition.C.
References forAll, and ignition::ignite().
Referenced by ignition::ignite().
The documentation for this class was generated from the following files:
src/engine/ignition/ignition.H
src/engine/ignition/ignition.C
src/engine/ignition/ignitionIO.C