OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MRFZone Class Reference
MRF zone definition based on cell zone and parameters obtained from a control dictionary constructed from the given stream.
Public Member Functions
ClassName ("MRFZone")
MRFZone (const word &name, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName=word::null)
Construct from fvMesh.
autoPtr< MRFZone > clone () const
Return clone.
const word & name () const
Return const access to the MRF region name.
bool active () const
Return const access to the MRF active flag.
vector Omega () const
Return the current Omega vector.
void updateMesh (const mapPolyMesh &mpm)
Update the mesh corresponding to given map.
void addCoriolis (const volVectorField &U, volVectorField &ddtU) const
Add the Coriolis force contribution to the acceleration field.
void addCoriolis (fvVectorMatrix &UEqn, const bool rhs=false) const
Add the Coriolis force contribution to the momentum equation.
void addCoriolis (const volScalarField &rho, fvVectorMatrix &UEqn, const bool rhs=false) const
Add the Coriolis force contribution to the momentum equation.
void makeRelative (volVectorField &U) const
Make the given absolute velocity relative within the MRF region.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative within the MRF region.
void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative within the MRF region.
void makeAbsolute (volVectorField &U) const
Make the given relative velocity absolute within the MRF region.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute within the MRF region.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute within the MRF region.
void correctBoundaryVelocity (volVectorField &U) const
Correct the boundary velocity for the roation of the MRF region.
void writeData (Ostream &os) const
Write.
bool read (const dictionary &dict)
Read MRF dictionary.
Detailed Description
MRF zone definition based on cell zone and parameters obtained from a control dictionary constructed from the given stream.
The rotation of the MRF region is defined by an origin and axis of rotation and an angular speed.
Source files
MRFZone.H
MRFZone.C
Definition at line 65 of file MRFZone.H.
Constructor & Destructor Documentation
MRFZone()
MRFZone (const word & name, const fvMesh & mesh, const dictionary & dict, const word & cellZoneName = word::null)
Construct from fvMesh.
Definition at line 237 of file MRFZone.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, forAllConstIter(), Foam::mag(), word::null, and Foam::reduce().
Member Function Documentation
ClassName()
ClassName ("MRFZone")
clone()
autoPtr<MRFZone> clone () const inline
Return clone.
Definition at line 164 of file MRFZone.H.
References MRFZone::active(), MRFZone::name(), notImplemented, and MRFZone::Omega().
name()
const Foam::word & name () const inline
Return const access to the MRF region name.
Definition at line 26 of file MRFZoneI.H.
Referenced by MRFZone::clone(), and MRFZoneList::read().
active()
bool active () const inline
Return const access to the MRF active flag.
Definition at line 32 of file MRFZoneI.H.
Referenced by MRFZoneList::active(), and MRFZone::clone().
Omega()
Foam::vector Omega () const
Return the current Omega vector.
Definition at line 313 of file MRFZone.C.
References MRFZone::addCoriolis().
Referenced by MRFZone::clone().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) inline
Update the mesh corresponding to given map.
Definition at line 188 of file MRFZone.H.
References MRFZone::addCoriolis(), MRFZone::correctBoundaryVelocity(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), MRFZone::read(), U, UEqn(), and MRFZone::writeData().
addCoriolis() [1/3]
void addCoriolis (const volVectorField & U, volVectorField & ddtU) const
Add the Coriolis force contribution to the acceleration field.
Definition at line 320 of file MRFZone.C.
References cells, forAll, and GeometricField< Type, PatchField, GeoMesh >::internalField().
Referenced by MRFZoneList::addCoriolis(), MRFZone::addCoriolis(), MRFZone::Omega(), MRFZoneList::operator()(), and MRFZone::updateMesh().
addCoriolis() [2/3]
void addCoriolis (fvVectorMatrix & UEqn, const bool rhs = false) const
Add the Coriolis force contribution to the momentum equation.
Adds to the lhs of the equation; optionally add to rhs
Definition at line 344 of file MRFZone.C.
References MRFZone::addCoriolis(), cells, forAll, fvMatrix< Type >::psi(), and fvMatrix< Type >::source().
addCoriolis() [3/3]
void addCoriolis (const volScalarField & rho, fvVectorMatrix & UEqn, const bool rhs = false) const
Add the Coriolis force contribution to the momentum equation.
Adds to the lhs of the equation; optionally add to rhs
Definition at line 378 of file MRFZone.C.
References cells, forAll, fvMatrix< Type >::psi(), and fvMatrix< Type >::source().
makeRelative() [1/4]
void makeRelative (volVectorField & U) const
Make the given absolute velocity relative within the MRF region.
Definition at line 415 of file MRFZone.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), C::C(), cells, forAll, patchi, and Vector< Cmpt >::zero.
Referenced by MRFZoneList::makeRelative(), MRFZone::makeRelative(), MRFZoneList::relative(), and MRFZone::updateMesh().
makeRelative() [2/4]
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative within the MRF region.
Definition at line 453 of file MRFZone.C.
makeRelative() [3/4]
void makeRelative (FieldField< fvsPatchField, scalar > & phi) const
Make the given absolute boundary flux relative.
within the MRF region
Definition at line 459 of file MRFZone.C.
References MRFZone::makeRelative().
makeRelative() [4/4]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative within the MRF region.
Definition at line 466 of file MRFZone.C.
makeAbsolute() [1/3]
void makeAbsolute (volVectorField & U) const
Make the given relative velocity absolute within the MRF region.
Definition at line 475 of file MRFZone.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), C::C(), cells, forAll, and patchi.
Referenced by MRFZoneList::makeAbsolute(), MRFZone::makeAbsolute(), and MRFZone::updateMesh().
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute within the MRF region.
Definition at line 513 of file MRFZone.C.
References MRFZone::makeAbsolute().
makeAbsolute() [3/3]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute within the MRF region.
Definition at line 520 of file MRFZone.C.
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Correct the boundary velocity for the roation of the MRF region.
Definition at line 529 of file MRFZone.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, and patchi.
Referenced by MRFZoneList::correctBoundaryVelocity(), and MRFZone::updateMesh().
writeData()
void writeData (Ostream & os) const
Write.
Definition at line 553 of file MRFZone.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::incrIndent(), Foam::nl, Ostream::write(), and Ostream::writeKeyword().
Referenced by MRFZone::updateMesh(), and MRFZoneList::writeData().
read()
bool read (const dictionary & dict)
Read MRF dictionary.
Definition at line 574 of file MRFZone.C.
References dict, and dictionary::lookupOrDefault().
Referenced by MRFZoneList::read(), and MRFZone::updateMesh().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZone.H
src/finiteVolume/cfdTools/general/MRF/MRFZone.C
src/finiteVolume/cfdTools/general/MRF/MRFZoneI.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneTemplates.C