OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
writer< Type > Class Template Reference abstract
Base class for graphics format writing. Entry points are.
Public Member Functions
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
writer ()
Construct null.
virtual ~writer ()=0
Destructor.
virtual fileName getFileName (const coordSet &, const wordList &) const =0
Generate file name with correct extension.
virtual void write (const coordSet &, const wordList &, const List< const Field< Type > *> &, Ostream &) const =0
General entry point for writing.
virtual void write (const coordSet &, const wordList &, const List< Field< Type > > &, Ostream &) const
General entry point for writing.
virtual void write (const bool writeTracks, const PtrList< coordSet > &, const wordList &valueSetNames, const List< List< Field< Type > > > &, Ostream &) const =0
General entry point for writing of multiple coordSets.
virtual Ostream & write (const scalar, Ostream &) const
Write scalar as ascii.
template<class VSType >
Ostream & writeVS (const VSType &, Ostream &) const
virtual Ostream & write (const vector &, Ostream &) const
Write vector. Tab separated ascii.
virtual Ostream & write (const sphericalTensor &, Ostream &) const
Write sphericalTensor. Tab separated ascii.
virtual Ostream & write (const symmTensor &, Ostream &) const
Write symmTensor. Tab separated ascii.
virtual Ostream & write (const tensor &, Ostream &) const
Write tensor. Tab separated ascii.
template<class VSType >
Foam::Ostream & writeVS (const VSType &value, Ostream &os) const
Static Public Member Functions
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Protected Member Functions
fileName getBaseName (const coordSet &, const wordList &) const
Generates filename from coordSet and sampled fields.
void writeCoord (const coordSet &, const label sampleI, Ostream &) const
void writeTable (const coordSet &, const List< Type > &, Ostream &) const
Writes single-column ascii write. Column 1 is coordSet coordinate,.
void writeTable (const coordSet &, const List< const List< Type > *> &, Ostream &os) const
Writes multi-column ascii write. Column 1 is coordSet coordinate,.
virtual void writeSeparator (Ostream &os) const
Writes a separator. Used by write functions.
Detailed Description
template<class Type>
class Foam::writer< Type >
Base class for graphics format writing. Entry points are.
- write(..).
Write to an Ostream a table of points with corresponding values.
write(scalar/vector/sphericalTensor/symmTensor/tensor).
Write single scalar/vector/sphericalTensor/symmTensor/tensor. Default is to write space separated components.
Example:
    // Construct writer of xmgr type
    autoPtr<writer<scalar> > scalarFormatter(writer<scalar>::New("xmgr"));
    // Output list of points and corresponding values
    scalarFormatter().write
    (
        coordSet(...)
        "U.component(0)",   // name of values
        vals                // values
    );
Source files
writer.H
writer.C
Definition at line 78 of file writer.H.
Constructor & Destructor Documentation
writer()
writer ()
Construct null.
Definition at line 142 of file writer.C.
~writer()
~writer () pure virtual
Destructor.
Definition at line 149 of file writer.C.
Member Function Documentation
getBaseName()
Foam::fileName getBaseName (const coordSet & points, const wordList & valueSets) const protected
Generates filename from coordSet and sampled fields.
Definition at line 62 of file writer.C.
Referenced by ensightSetWriter< Type >::getFileName(), rawSetWriter< Type >::getFileName(), xmgraceSetWriter< Type >::getFileName(), vtkSetWriter< Type >::getFileName(), gnuplotSetWriter< Type >::getFileName(), jplotSetWriter< Type >::getFileName(), csvSetWriter< Type >::getFileName(), and writer< Foam::SphericalTensor >::New().
writeCoord()
void writeCoord (const coordSet & points, const label sampleI, Ostream & os) const protected
Definition at line 80 of file writer.C.
Referenced by writer< Foam::SphericalTensor >::getBaseName().
writeTable() [1/2]
void writeTable (const coordSet & points, const List< Type > & values, Ostream & os) const protected
Writes single-column ascii write. Column 1 is coordSet coordinate,.
columns 2 is the value. Uses write() function to write coordinate in correct format.
Definition at line 99 of file writer.C.
Referenced by gnuplotSetWriter< Type >::write(), rawSetWriter< Type >::write(), xmgraceSetWriter< Type >::write(), jplotSetWriter< Type >::write(), csvSetWriter< Type >::write(), writer< Foam::SphericalTensor >::writeCoord(), and writer< Foam::SphericalTensor >::writeTable().
writeTable() [2/2]
void writeTable (const coordSet & points, const List< const List< Type > *> & valuesPtrList, Ostream & os) const protected
Writes multi-column ascii write. Column 1 is coordSet coordinate,.
columns 2..n are the values. Uses write() function to write coordinate in correct format.
Definition at line 117 of file writer.C.
writeSeparator()
void writeSeparator (Ostream & os) const protected virtual
Writes a separator. Used by write functions.
Reimplemented in csvSetWriter< Type >.
Definition at line 207 of file writer.C.
Referenced by writer< Foam::SphericalTensor >::writeVS().
TypeName()
TypeName ("writer< Type >")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , writer< Type > , word , () , ())
New()
Foam::autoPtr< Foam::writer< Type > > New (const word & writeFormat) static
Return a reference to the selected writer.
Definition at line 35 of file writer.C.
Referenced by streamLine::read(), regionSizeDistribution::read(), and wallBoundedStreamLine::read().
getFileName()
virtual fileName getFileName (const coordSet & , const wordList &) const pure virtual
Generate file name with correct extension.
Implemented in csvSetWriter< Type >, jplotSetWriter< Type >, ensightSetWriter< Type >, gnuplotSetWriter< Type >, rawSetWriter< Type >, vtkSetWriter< Type >, and xmgraceSetWriter< Type >.
write() [1/8]
virtual void write (const coordSet & , const wordList & , const List< const Field< Type > *> & , Ostream &) const pure virtual
General entry point for writing.
The data is organized in a set of point with one or more values per point
Implemented in csvSetWriter< Type >, jplotSetWriter< Type >, ensightSetWriter< Type >, gnuplotSetWriter< Type >, rawSetWriter< Type >, vtkSetWriter< Type >, and xmgraceSetWriter< Type >.
Referenced by vtkSetWriter< Type >::write(), writer< Foam::SphericalTensor >::write(), writer< Foam::SphericalTensor >::writeSeparator(), and writer< Foam::SphericalTensor >::~writer().
write() [2/8]
void write (const coordSet & points, const wordList & valueSetNames, const List< Field< Type > > & valueSets, Ostream & os) const virtual
General entry point for writing.
The data is organized in a set of point with one or more values per point
Definition at line 157 of file writer.C.
write() [3/8]
virtual void write (const bool writeTracks, const PtrList< coordSet > & , const wordList & valueSetNames, const List< List< Field< Type > > > & , Ostream &) const pure virtual
General entry point for writing of multiple coordSets.
Each coordSet (track) has same data variables. The data is per variable, per track, per point of track. If writeTracks adds connecting lines (wherever applicable)
Implemented in csvSetWriter< Type >, jplotSetWriter< Type >, ensightSetWriter< Type >, gnuplotSetWriter< Type >, rawSetWriter< Type >, vtkSetWriter< Type >, and xmgraceSetWriter< Type >.
write() [4/8]
Foam::Ostream & write (const scalar value, Ostream & os) const virtual
Write scalar as ascii.
Definition at line 175 of file writer.C.
writeVS() [1/2]
Ostream& writeVS (const VSType & , Ostream &) const
Referenced by writer< Foam::SphericalTensor >::write().
write() [5/8]
Foam::Ostream & write (const vector & value, Ostream & os) const virtual
Write vector. Tab separated ascii.
Definition at line 217 of file writer.C.
write() [6/8]
Foam::Ostream & write (const sphericalTensor & value, Ostream & os) const virtual
Write sphericalTensor. Tab separated ascii.
Definition at line 228 of file writer.C.
write() [7/8]
Foam::Ostream & write (const symmTensor & value, Ostream & os) const virtual
Write symmTensor. Tab separated ascii.
Definition at line 239 of file writer.C.
write() [8/8]
Foam::Ostream & write (const tensor & value, Ostream & os) const virtual
Write tensor. Tab separated ascii.
Definition at line 250 of file writer.C.
writeVS() [2/2]
Foam::Ostream& writeVS (const VSType & value, Ostream & os) const
Definition at line 187 of file writer.C.
The documentation for this class was generated from the following files:
src/fileFormats/sampledSetWriters/writer.H
src/fileFormats/sampledSetWriters/writer.C