OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NASCore Class Reference
Core routines used when reading/writing NASTRAN files.
Public Member Functions
NASCore ()
Construct null.
Static Public Member Functions
static scalar parseNASCoord (const string &)
Do weird things to extract number.
Detailed Description
Core routines used when reading/writing NASTRAN files.
Source files
NASCore.H
NASCore.C
Definition at line 51 of file NASCore.H.
Constructor & Destructor Documentation
NASCore()
NASCore ()
Construct null.
Definition at line 31 of file NASCore.C.
References NASCore::parseNASCoord().
Member Function Documentation
parseNASCoord()
Foam::scalar parseNASCoord (const string & s) static
Do weird things to extract number.
Definition at line 38 of file NASCore.C.
References Foam::isspace(), Foam::pow(), and Foam::readScalar().
Referenced by NASCore::NASCore().
The documentation for this class was generated from the following files:
src/fileFormats/nas/NASCore.H
src/fileFormats/nas/NASCore.C