OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
porosityModel::iNew Class Reference
Return pointer to new porosityModel object created on the freestore.
Public Member Functions
iNew (const fvMesh &mesh, const word &name)
autoPtr< porosityModel > operator() (Istream &is) const
Detailed Description
Return pointer to new porosityModel object created on the freestore.
from an Istream
Definition at line 169 of file porosityModel.H.
Constructor & Destructor Documentation
iNew()
iNew (const fvMesh & mesh, const word & name) inline
Definition at line 178 of file porosityModel.H.
Member Function Documentation
operator()()
autoPtr<porosityModel> operator() (Istream & is) const inline
Definition at line 187 of file porosityModel.H.
References porosityModel::active(), porosityModel::addResistance(), porosityModel::cellZoneIDs(), dict, porosityModel::force(), Foam::constant::physicoChemical::mu, porosityModel::name(), porosityModel::New(), word::null, regIOobject::read(), rho, porosityModel::transformModelData(), U, UEqn(), porosityModel::writeData(), and porosityModel::~porosityModel().
The documentation for this class was generated from the following file:
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModel.H