OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pimpleControl Class Reference
PIMPLE control class to supply convergence information/checks for the PIMPLE loop.
Public Member Functions
TypeName ("pimpleControl")
Run-time type information.
pimpleControl (fvMesh &mesh)
Construct from mesh.
virtual ~pimpleControl ()
Destructor.
label nCorrPIMPLE () const
Maximum number of PIMPLE correctors.
label nCorrPISO () const
Maximum number of PISO correctors.
label corrPISO () const
Current PISO corrector index.
virtual bool loop ()
PIMPLE loop.
bool correct ()
Pressure corrector loop.
bool storeInitialResiduals () const
Helper function to identify when to store the intial residuals.
bool firstIter () const
Helper function to identify first PIMPLE (outer) iteration.
bool finalIter () const
Helper function to identify final PIMPLE (outer) iteration.
bool finalInnerIter () const
Helper function to identify final inner iteration.
bool turbCorr () const
Helper function to identify whether to solve for turbulence.
Public Member Functions inherited from solutionControl
TypeName ("solutionControl")
Run-time type information.
solutionControl (fvMesh &mesh, const word &algorithmName)
Construct from mesh.
virtual ~solutionControl ()
Destructor.
const dictionary & dict () const
Return the solution dictionary.
label corr () const
Current corrector loop index.
label corrNonOrtho () const
Current non-orthogonal corrector index.
label nNonOrthCorr () const
Maximum number of non-orthogonal correctors.
bool finalNonOrthogonalIter () const
Helper function to identify final non-orthogonal iteration.
bool momentumPredictor () const
Flag to indicate to solve for momentum.
bool transonic () const
Flag to indicate to solve using transonic algorithm.
bool correctNonOrthogonal ()
Non-orthogonal corrector loop.
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
virtual void rename (const word &newName)
Rename.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Protected Member Functions
virtual void read ()
Read controls from fvSolution dictionary.
virtual bool criteriaSatisfied ()
Return true if all convergence checks are satisfied.
pimpleControl (const pimpleControl &)
Disallow default bitwise copy construct.
void operator= (const pimpleControl &)
Disallow default bitwise assignment.
Protected Member Functions inherited from solutionControl
virtual void read (const bool absTolOnly)
Read controls from fvSolution dictionary.
virtual label applyToField (const word &fieldName, const bool useRegEx=true) const
Return index of field in residualControl_ if present.
virtual void storePrevIterFields () const
Store previous iteration fields.
template<class Type >
void storePrevIter () const
Store previous iteration field for vol<Type>Fields.
solutionControl (const solutionControl &)
Disallow default bitwise copy construct.
void operator= (const solutionControl &)
Disallow default bitwise assignment.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
label nCorrPIMPLE_
Maximum number of PIMPLE correctors.
label nCorrPISO_
Maximum number of PISO correctors.
label corrPISO_
Current PISO corrector.
bool turbOnFinalIterOnly_
Flag to indicate whether to only solve turbulence on final iter.
bool converged_
Converged flag.
Protected Attributes inherited from solutionControl
fvMesh & mesh_
Reference to the mesh database.
List< fieldData > residualControl_
List of residual data per field.
const word algorithmName_
The dictionary name, e.g. SIMPLE, PIMPLE.
label nNonOrthCorr_
Maximum number of non-orthogonal correctors.
bool momentumPredictor_
Flag to indicate to solve for momentum.
bool transonic_
Flag to indicate to solve using transonic algorithm.
label corr_
Current corrector loop index.
label corrNonOrtho_
Current non-orthogonal corrector loop index.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Detailed Description
PIMPLE control class to supply convergence information/checks for the PIMPLE loop.
Definition at line 46 of file pimpleControl.H.
Constructor & Destructor Documentation
pimpleControl() [1/2]
pimpleControl (const pimpleControl &) protected
Disallow default bitwise copy construct.
pimpleControl() [2/2]
pimpleControl (fvMesh & mesh)
Construct from mesh.
Definition at line 123 of file pimpleControl.C.
References solutionControl::algorithmName_, Foam::endl(), forAll, Foam::Info, pimpleControl::nCorrPIMPLE_, Foam::nl, pimpleControl::read(), solutionControl::residualControl_, and token::TAB.
~pimpleControl()
~pimpleControl () virtual
Destructor.
Definition at line 167 of file pimpleControl.C.
Member Function Documentation
read()
void read () protected virtual
Read controls from fvSolution dictionary.
Definition at line 39 of file pimpleControl.C.
References dict, dictionary::lookupOrDefault(), and solutionControl::read().
Referenced by pimpleControl::loop(), and pimpleControl::pimpleControl().
criteriaSatisfied()
bool criteriaSatisfied () protected virtual
Return true if all convergence checks are satisfied.
Implements solutionControl.
Definition at line 52 of file pimpleControl.C.
References Foam::endl(), UList< T >::first(), forAllConstIter(), Foam::Info, SolverPerformance< Type >::initialResidual(), UList< T >::last(), and Foam::fvc::relative().
Referenced by pimpleControl::loop().
operator=()
void operator= (const pimpleControl &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("pimpleControl")
Run-time type information.
nCorrPIMPLE()
Foam::label nCorrPIMPLE () const inline
Maximum number of PIMPLE correctors.
Definition at line 28 of file pimpleControlI.H.
References pimpleControl::nCorrPIMPLE_.
nCorrPISO()
Foam::label nCorrPISO () const inline
Maximum number of PISO correctors.
Definition at line 34 of file pimpleControlI.H.
References pimpleControl::nCorrPISO_.
corrPISO()
Foam::label corrPISO () const inline
Current PISO corrector index.
Definition at line 40 of file pimpleControlI.H.
References pimpleControl::corrPISO_.
loop()
bool loop () virtual
PIMPLE loop.
Implements solutionControl.
Definition at line 173 of file pimpleControl.C.
References solutionControl::algorithmName_, pimpleControl::converged_, solutionControl::corr_, pimpleControl::criteriaSatisfied(), Foam::endl(), pimpleControl::finalIter(), Foam::Info, solutionControl::mesh_, pimpleControl::nCorrPIMPLE_, pimpleControl::read(), solutionControl::residualControl_, and solutionControl::storePrevIterFields().
correct()
bool correct () inline
Pressure corrector loop.
Definition at line 46 of file pimpleControlI.H.
References solutionControl::algorithmName_, pimpleControl::corrPISO_, Foam::endl(), Foam::Info, and pimpleControl::nCorrPISO_.
storeInitialResiduals()
bool storeInitialResiduals () const inline
Helper function to identify when to store the intial residuals.
Definition at line 67 of file pimpleControlI.H.
References solutionControl::corr_, solutionControl::corrNonOrtho_, and pimpleControl::corrPISO_.
firstIter()
bool firstIter () const inline
Helper function to identify first PIMPLE (outer) iteration.
Definition at line 74 of file pimpleControlI.H.
References solutionControl::corr_.
finalIter()
bool finalIter () const inline
Helper function to identify final PIMPLE (outer) iteration.
Definition at line 80 of file pimpleControlI.H.
References pimpleControl::converged_, solutionControl::corr_, and pimpleControl::nCorrPIMPLE_.
Referenced by pimpleControl::finalInnerIter(), pimpleControl::loop(), and pimpleControl::turbCorr().
finalInnerIter()
bool finalInnerIter () const inline
Helper function to identify final inner iteration.
Definition at line 86 of file pimpleControlI.H.
References solutionControl::corrNonOrtho_, pimpleControl::corrPISO_, pimpleControl::finalIter(), pimpleControl::nCorrPISO_, and solutionControl::nNonOrthCorr_.
turbCorr()
bool turbCorr () const inline
Helper function to identify whether to solve for turbulence.
Definition at line 95 of file pimpleControlI.H.
References pimpleControl::finalIter(), and pimpleControl::turbOnFinalIterOnly_.
Member Data Documentation
nCorrPIMPLE_
label nCorrPIMPLE_ protected
Maximum number of PIMPLE correctors.
Definition at line 57 of file pimpleControl.H.
Referenced by pimpleControl::finalIter(), pimpleControl::loop(), pimpleControl::nCorrPIMPLE(), and pimpleControl::pimpleControl().
nCorrPISO_
label nCorrPISO_ protected
Maximum number of PISO correctors.
Definition at line 60 of file pimpleControl.H.
Referenced by pimpleControl::correct(), pimpleControl::finalInnerIter(), and pimpleControl::nCorrPISO().
corrPISO_
label corrPISO_ protected
Current PISO corrector.
Definition at line 63 of file pimpleControl.H.
Referenced by pimpleControl::correct(), pimpleControl::corrPISO(), pimpleControl::finalInnerIter(), and pimpleControl::storeInitialResiduals().
turbOnFinalIterOnly_
bool turbOnFinalIterOnly_ protected
Flag to indicate whether to only solve turbulence on final iter.
Definition at line 66 of file pimpleControl.H.
Referenced by pimpleControl::turbCorr().
converged_
bool converged_ protected
Converged flag.
Definition at line 69 of file pimpleControl.H.
Referenced by pimpleControl::finalIter(), and pimpleControl::loop().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/solutionControl/pimpleControl/pimpleControl.H
src/finiteVolume/cfdTools/general/solutionControl/pimpleControl/pimpleControl.C
src/finiteVolume/cfdTools/general/solutionControl/pimpleControl/pimpleControlI.H