OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MRFZoneList Class Reference
List container for MRF zomes.
Public Member Functions
MRFZoneList (const fvMesh &mesh, const dictionary &dict)
Constructor.
~MRFZoneList ()
Destructor.
bool active (const bool warn=false) const
Return active status.
void reset (const dictionary &dict)
Reset the source list.
void addCoriolis (const volVectorField &U, volVectorField &ddtU) const
Add the Coriolis force contribution to the acceleration field.
void addCoriolis (fvVectorMatrix &UEqn) const
Add the Coriolis force contribution to the momentum equation.
void addCoriolis (const volScalarField &rho, fvVectorMatrix &UEqn) const
Add the Coriolis force contribution to the momentum equation.
tmp< volVectorField > operator() (const volVectorField &U)
Return the frame acceleration.
tmp< volVectorField > operator() (const volScalarField &rho, const volVectorField &U)
Return the frame acceleration force.
void makeRelative (volVectorField &U) const
Make the given absolute velocity relative within the MRF region.
void makeAbsolute (volVectorField &U) const
Make the given relative velocity absolute within the MRF region.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative within the MRF region.
tmp< FieldField< fvsPatchField, scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > &tphi) const
Return the given absolute boundary flux relative within.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative within the MRF region.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute within the MRF region.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute within the MRF region.
void correctBoundaryVelocity (volVectorField &U) const
Correct the boundary velocity for the roation of the MRF region.
bool read (const dictionary &dict)
Read dictionary.
bool writeData (Ostream &os) const
Write data to Ostream.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
Friends
Ostream & operator<< (Ostream &os, const MRFZoneList &models)
Ostream operator.
Detailed Description
List container for MRF zomes.
Source files
MRFZoneList.H
MRFZoneList.C
Definition at line 55 of file MRFZoneList.H.
Constructor & Destructor Documentation
MRFZoneList()
MRFZoneList (const fvMesh & mesh, const dictionary & dict)
Constructor.
Definition at line 32 of file MRFZoneList.C.
~MRFZoneList()
~MRFZoneList ()
Destructor.
Definition at line 48 of file MRFZoneList.C.
Member Function Documentation
active()
bool active (const bool warn = false) const
Return active status.
Definition at line 54 of file MRFZoneList.C.
References MRFZone::active(), Foam::endl(), forAll, Foam::Info, PtrList< MRFZone >::operator[](), and PtrList< MRFZone >::size().
reset()
void reset (const dictionary & dict)
Reset the source list.
Definition at line 71 of file MRFZoneList.C.
References Foam::endl(), forAllConstIter(), Foam::Info, MRFZoneList::mesh_, Foam::name(), and PtrList< MRFZone >::setSize().
addCoriolis() [1/3]
void addCoriolis (const volVectorField & U, volVectorField & ddtU) const
Add the Coriolis force contribution to the acceleration field.
Definition at line 129 of file MRFZoneList.C.
References MRFZone::addCoriolis(), forAll, and PtrList< MRFZone >::operator[]().
Referenced by MRFZoneList::addCoriolis(), and MRFZoneList::writeData().
addCoriolis() [2/3]
void addCoriolis (fvVectorMatrix & UEqn) const
Add the Coriolis force contribution to the momentum equation.
Definition at line 141 of file MRFZoneList.C.
References MRFZoneList::addCoriolis(), MRFZone::addCoriolis(), forAll, and PtrList< MRFZone >::operator[]().
addCoriolis() [3/3]
void addCoriolis (const volScalarField & rho, fvVectorMatrix & UEqn) const
Add the Coriolis force contribution to the momentum equation.
Definition at line 151 of file MRFZoneList.C.
References MRFZone::addCoriolis(), forAll, PtrList< MRFZone >::operator, and PtrList< MRFZone >::operator[]().
operator()() [1/2]
Foam::tmp< Foam::volVectorField > operator() (const volVectorField & U)
Return the frame acceleration.
Definition at line 164 of file MRFZoneList.C.
References MRFZone::addCoriolis(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, forAll, DimensionedField< Type, GeoMesh >::mesh(), PtrList< MRFZone >::operator, PtrList< MRFZone >::operator[](), and Vector< Cmpt >::zero.
Referenced by MRFZoneList::operator()().
operator()() [2/2]
Foam::tmp< Foam::volVectorField > operator() (const volScalarField & rho, const volVectorField & U)
Return the frame acceleration force.
Definition at line 194 of file MRFZoneList.C.
References MRFZoneList::operator()(), and U.
makeRelative() [1/3]
void makeRelative (volVectorField & U) const
Make the given absolute velocity relative within the MRF region.
Definition at line 203 of file MRFZoneList.C.
References forAll, MRFZone::makeRelative(), and PtrList< MRFZone >::operator[]().
Referenced by MRFZoneList::relative().
makeAbsolute() [1/3]
void makeAbsolute (volVectorField & U) const
Make the given relative velocity absolute within the MRF region.
Definition at line 251 of file MRFZoneList.C.
References forAll, MRFZone::makeAbsolute(), and PtrList< MRFZone >::operator[]().
Referenced by MRFZoneList::makeAbsolute().
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative within the MRF region.
Definition at line 212 of file MRFZoneList.C.
References forAll, MRFZone::makeRelative(), PtrList< MRFZone >::operator[](), and MRFZoneList::relative().
relative()
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > & tphi) const
Return the given absolute boundary flux relative within.
the MRF region
Definition at line 223 of file MRFZoneList.C.
References forAll, MRFZoneList::makeRelative(), MRFZone::makeRelative(), PtrList< MRFZone >::operator[](), and phi.
Referenced by MRFZoneList::makeRelative().
makeRelative() [3/3]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative within the MRF region.
Definition at line 239 of file MRFZoneList.C.
References forAll, MRFZone::makeRelative(), and PtrList< MRFZone >::operator[]().
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute within the MRF region.
Definition at line 260 of file MRFZoneList.C.
References forAll, MRFZoneList::makeAbsolute(), MRFZone::makeAbsolute(), and PtrList< MRFZone >::operator[]().
makeAbsolute() [3/3]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute within the MRF region.
Definition at line 270 of file MRFZoneList.C.
References forAll, MRFZone::makeAbsolute(), and PtrList< MRFZone >::operator[]().
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Correct the boundary velocity for the roation of the MRF region.
Definition at line 282 of file MRFZoneList.C.
References MRFZone::correctBoundaryVelocity(), forAll, and PtrList< MRFZone >::operator[]().
read()
bool read (const dictionary & dict)
Read dictionary.
Definition at line 103 of file MRFZoneList.C.
References forAll, MRFZone::name(), PtrList< MRFZone >::operator[](), MRFZone::read(), and dictionary::subDict().
Referenced by IOMRFZoneList::read().
writeData()
bool writeData (Ostream & os) const
Write data to Ostream.
Definition at line 116 of file MRFZoneList.C.
References MRFZoneList::addCoriolis(), forAll, IOstream::good(), Foam::nl, PtrList< MRFZone >::operator[](), and MRFZone::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const MRFZoneList & models) friend
Ostream operator.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 75 of file MRFZoneList.H.
Referenced by MRFZoneList::reset().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.C