OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SRFVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Wall boundary Conditions
Freestream velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
Public Member Functions
TypeName ("SRFVelocity")
Runtime type information.
SRFVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
SRFVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given SRFVelocityFvPatchVectorField.
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const Switch & relative () const
Return const access to the relative flag.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Freestream velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
Velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: SRFModel class)
Given the free stream velocity in the absolute frame, the condition applies the appropriate rotation transformation in time and space to determine the local velocity using:
where
=
=
=
=
=
Patch usage
Property Description Required Default value
UInf freestream velocity yes
relative UInf relative to the SRF? no
Example of the boundary condition specification:
    myPatch
    {
        type            SRFFreestreamVelocity;
        UInf            uniform (0 0 0);
        relative        no;
        value           uniform (0 0 0);    // initial value
    }
See also
Foam::freestreamFvPatchField Foam::SRFVelocityFvPatchVectorField
Source files
SRFFreestreamVelocityFvPatchVectorField.H
SRFFreestreamVelocityFvPatchVectorField.C
Given the free stream velocity in the absolute frame, the condition applies the appropriate rotation transformation in time and space to determine the local velocity.
The optional relative flag switches the behaviour of the patch such that:
relative = yes: inlet velocity applied 'as is':
relative = no : SRF velocity is subtracted from the inlet velocity:
where
=
=
=
Patch usage
Property Description Required Default value
inletValue inlet velocity yes
relative inletValue relative motion to the SRF? yes
Example of the boundary condition specification:
    myPatch
    {
        type            SRFVelocity;
        inletValue      uniform (0 0 0);
        relative        yes;
        value           uniform (0 0 0);    // initial value
    }
See also
Foam::fixedValueFvPatchField
Source files
SRFVelocityFvPatchVectorField.H
SRFVelocityFvPatchVectorField.C
Definition at line 127 of file SRFVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFVelocityFvPatchVectorField() [1/5]
SRFVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file SRFVelocityFvPatchVectorField.C.
Referenced by SRFVelocityFvPatchVectorField::clone(), and SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField().
SRFVelocityFvPatchVectorField() [2/5]
SRFVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 61 of file SRFVelocityFvPatchVectorField.C.
References fvPatch::size(), SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField(), and vectorField().
SRFVelocityFvPatchVectorField() [3/5]
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given SRFVelocityFvPatchVectorField.
onto a new patch
Definition at line 47 of file SRFVelocityFvPatchVectorField.C.
References SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField().
SRFVelocityFvPatchVectorField() [4/5]
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField & srfvpvf)
Construct as copy.
Definition at line 76 of file SRFVelocityFvPatchVectorField.C.
References SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField().
SRFVelocityFvPatchVectorField() [5/5]
SRFVelocityFvPatchVectorField (const SRFVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 87 of file SRFVelocityFvPatchVectorField.C.
References SRFVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("SRFVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 180 of file SRFVelocityFvPatchVectorField.H.
References SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 197 of file SRFVelocityFvPatchVectorField.H.
References SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField().
relative()
const Switch& relative () const inline
Return const access to the relative flag.
Definition at line 213 of file SRFVelocityFvPatchVectorField.H.
References SRFVelocityFvPatchVectorField::autoMap(), SRFVelocityFvPatchVectorField::rmap(), SRFVelocityFvPatchVectorField::updateCoeffs(), and SRFVelocityFvPatchVectorField::write().
Referenced by SRFModel::Uabs().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 101 of file SRFVelocityFvPatchVectorField.C.
References SRFVelocityFvPatchVectorField::rmap().
Referenced by SRFVelocityFvPatchVectorField::relative(), and SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 111 of file SRFVelocityFvPatchVectorField.C.
References SRFVelocityFvPatchVectorField::rmap().
Referenced by SRFVelocityFvPatchVectorField::autoMap(), SRFVelocityFvPatchVectorField::relative(), and SRFVelocityFvPatchVectorField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 125 of file SRFVelocityFvPatchVectorField.C.
References Foam::operator==(), and SRFModel::velocity().
Referenced by SRFVelocityFvPatchVectorField::relative().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 155 of file SRFVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by SRFVelocityFvPatchVectorField::relative().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFVelocityFvPatchVectorField/SRFVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFVelocityFvPatchVectorField/SRFVelocityFvPatchVectorField.C