OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
activePressureForceBaffleVelocityFvPatchVectorField Class Reference
Boundary Conditions » Coupled boundary Conditions
This boundary condition is applied to the flow velocity, to simulate the opening of a baffle due to local flow conditions, by merging the behaviours of wall and cyclic conditions.
Public Member Functions
TypeName ("activePressureForceBaffleVelocity")
Runtime type information.
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping.
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition is applied to the flow velocity, to simulate the opening of a baffle due to local flow conditions, by merging the behaviours of wall and cyclic conditions.
The baffle joins two mesh regions, where the open fraction determines the interpolation weights applied to each cyclic- and neighbour-patch contribution.
Once opened the baffle continues to open at a fixed rate using
where
= baffle open fraction [0-1]
= baffle open fraction on previous evaluation
= simulation time step
= time taken to open the baffle
The open fraction is then applied to scale the patch areas.
Patch usage
Property Description Required Default value
p pressure field name no p
cyclicPatch cylclic patch name yes
orientation 1 or -1 used to switch flow direction yes
openFraction current opatch open fraction [0-1] yes
openingTime time taken to open the baffle yes
maxOpenFractionDelta max open fraction change per timestep yes
minThresholdValue minimum open fraction for activation yes
forceBased force (true) or pressure-based (false) activation yes
Example of the boundary condition specification:
    myPatch
    {
        type            activePressureForceBaffleVelocity;
        p               p;
        cyclicPatch     cyclic1;
        orientation     1;
        openFraction    0.2;
        openingTime     5.0;
        maxOpenFractionDelta 0.1;
        minThresholdValue 0.01;
        forceBased      false;
    }
Source files
activePressureForceBaffleVelocityFvPatchVectorField.H
activePressureForceBaffleVelocityFvPatchVectorField.C
Definition at line 166 of file activePressureForceBaffleVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
activePressureForceBaffleVelocityFvPatchVectorField() [1/5]
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), and activePressureForceBaffleVelocityFvPatchVectorField::clone().
activePressureForceBaffleVelocityFvPatchVectorField() [2/5]
activePressureForceBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 88 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), fvPatch::boundaryMesh(), dictionary::found(), dictionary::lookup(), fvPatch::Sf(), and fvPatch::size().
activePressureForceBaffleVelocityFvPatchVectorField() [3/5]
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping.
Definition at line 61 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField().
activePressureForceBaffleVelocityFvPatchVectorField() [4/5]
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 131 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField().
activePressureForceBaffleVelocityFvPatchVectorField() [5/5]
activePressureForceBaffleVelocityFvPatchVectorField (const activePressureForceBaffleVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 155 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
References activePressureForceBaffleVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("activePressureForceBaffleVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 257 of file activePressureForceBaffleVelocityFvPatchVectorField.H.
References activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 274 of file activePressureForceBaffleVelocityFvPatchVectorField.H.
References activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), activePressureForceBaffleVelocityFvPatchVectorField::autoMap(), activePressureForceBaffleVelocityFvPatchVectorField::rmap(), activePressureForceBaffleVelocityFvPatchVectorField::updateCoeffs(), and activePressureForceBaffleVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Note: cannot map field from cyclic patch anyway so just recalculate
Areas should be consistent when doing autoMap except in case of topo changes. ! Note: we don't want to use Sf here since triggers rebuilding of /*! fvMesh::S() which will give problems when mapped (since already on new mesh)
Definition at line 181 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), and activePressureForceBaffleVelocityFvPatchVectorField::clone().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 219 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::clone().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 243 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 354 of file activePressureForceBaffleVelocityFvPatchVectorField.C.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/activePressureForceBaffleVelocity/activePressureForceBaffleVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/activePressureForceBaffleVelocity/activePressureForceBaffleVelocityFvPatchVectorField.C