OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fanPressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This boundary condition can be applied to assign either a pressure inlet or outlet total pressure condition for a fan.
Public Types
enum fanFlowDirection { ffdIn, ffdOut }
Fan flow direction.
Public Member Functions
TypeName ("fanPressure")
Runtime type information.
fanPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fanPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from totalPressureFvPatchScalarField
TypeName ("totalPressure")
Runtime type information.
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given totalPressureFvPatchScalarField.
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &)
Construct as copy.
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const word & UName () const
Return the name of the velocity field.
word & UName ()
Return reference to the name of the velocity field.
const word & phiName () const
Return the name of the flux field.
word & phiName ()
Return reference to the name of the flux field.
const word & rhoName () const
Return the name of the density field.
word & rhoName ()
Return reference to the name of the density field.
const word & psiName () const
Return the name of the compressibility field.
word & psiName ()
Return reference to the name of the compressibility field.
scalar gamma () const
Return the heat capacity ratio.
scalar & gamma ()
Return reference to the heat capacity ratio to allow adjustment.
const scalarField & p0 () const
Return the total pressure.
scalarField & p0 ()
Return reference to the total pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs (const scalarField &p0p, const vectorField &Up)
Update the coefficients associated with the patch field.
Static Public Attributes
static const NamedEnum< fanFlowDirection, 2 > fanFlowDirectionNames_
Fan flow directions names.
Detailed Description
This boundary condition can be applied to assign either a pressure inlet or outlet total pressure condition for a fan.
Patch usage
Property Description Required Default value
fileName fan curve file name yes
outOfBounds out of bounds handling yes
direction direction of flow through fan [in/out] yes
p0 environmental total pressure yes
Example of the boundary condition specification:
    inlet
    {
        type            fanPressure;
        fileName        "fanCurve";
        outOfBounds     clamp;
        direction       in;
        p0              uniform 0;
        value           uniform 0;
    }
    outlet
    {
        type            fanPressure;
        fileName        "fanCurve";
        outOfBounds     clamp;
        direction       out;
        p0              uniform 0;
        value           uniform 0;
    }
See also
Foam::fanFvPatchField Foam::totalPressureFvPatchScalarField Foam::interpolationTable
Source files
fanPressureFvPatchScalarField.H
fanPressureFvPatchScalarField.C
Definition at line 116 of file fanPressureFvPatchScalarField.H.
Member Enumeration Documentation
fanFlowDirection
enum fanFlowDirection
Fan flow direction.
Enumerator
ffdIn
ffdOut
Definition at line 124 of file fanPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
fanPressureFvPatchScalarField() [1/5]
fanPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 57 of file fanPressureFvPatchScalarField.C.
Referenced by fanPressureFvPatchScalarField::clone(), fanPressureFvPatchScalarField::fanPressureFvPatchScalarField(), and NamedEnum< directionType, 3 >::names().
fanPressureFvPatchScalarField() [2/5]
fanPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 83 of file fanPressureFvPatchScalarField.C.
References fanPressureFvPatchScalarField::fanPressureFvPatchScalarField().
fanPressureFvPatchScalarField() [3/5]
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
fanPressureFvPatchScalarField onto a new patch
Definition at line 69 of file fanPressureFvPatchScalarField.C.
References fanPressureFvPatchScalarField::fanPressureFvPatchScalarField().
fanPressureFvPatchScalarField() [4/5]
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField & pfopsf)
Construct as copy.
Definition at line 96 of file fanPressureFvPatchScalarField.C.
References fanPressureFvPatchScalarField::fanPressureFvPatchScalarField().
fanPressureFvPatchScalarField() [5/5]
fanPressureFvPatchScalarField (const fanPressureFvPatchScalarField & pfopsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 107 of file fanPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fanPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 186 of file fanPressureFvPatchScalarField.H.
References fanPressureFvPatchScalarField::fanPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 203 of file fanPressureFvPatchScalarField.H.
References fanPressureFvPatchScalarField::fanPressureFvPatchScalarField(), fanPressureFvPatchScalarField::updateCoeffs(), and fanPressureFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 120 of file fanPressureFvPatchScalarField.C.
References Foam::dimArea, Foam::dimDensity, dimensionedInternalField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::gSum(), Foam::max(), Foam::nl, phi, and totalPressureFvPatchScalarField::updateCoeffs().
Referenced by fanPressureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 170 of file fanPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, totalPressureFvPatchScalarField::write(), and Ostream::writeKeyword().
Referenced by fanPressureFvPatchScalarField::clone().
Member Data Documentation
fanFlowDirectionNames_
const Foam::NamedEnum< Foam::fanPressureFvPatchScalarField::fanFlowDirection, 2 > fanFlowDirectionNames_ static
Fan flow directions names.
Definition at line 131 of file fanPressureFvPatchScalarField.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fanPressure/fanPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/fanPressure/fanPressureFvPatchScalarField.C