OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mappedPatchFieldBase< Type > Class Template Reference
Functionality for sampling fields using mappedPatchBase. Every call to mappedField() returns a sampled field, optionally scaled to maintain an area-weighted average.
Public Member Functions
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const word &fieldName, const bool setAverage, const Type average, const word &interpolationScheme)
Construct from components.
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const dictionary &dict)
Construct from dictionary.
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField)
Construct empty.
mappedPatchFieldBase (const mappedPatchFieldBase< Type > &mapper)
Construct copy.
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const mappedPatchFieldBase< Type > &base)
Construct copy, resetting patch and field.
virtual ~mappedPatchFieldBase ()
Destructor.
const GeometricField< Type, fvPatchField, volMesh > & sampleField () const
Field to sample. Either on my or nbr mesh.
virtual tmp< Field< Type > > mappedField () const
Map sampleField onto *this patch.
virtual void write (Ostream &) const
Write.
Protected Attributes
const mappedPatchBase & mapper_
Mapping engine.
const fvPatchField< Type > & patchField_
Underlying patch field.
word fieldName_
Name of field to sample.
const bool setAverage_
If true adjust the mapped field to maintain average value average_.
const Type average_
Average value the mapped field is adjusted to maintain if.
word interpolationScheme_
Interpolation scheme to use for nearestcell mode.
Detailed Description
template<class Type>
class Foam::mappedPatchFieldBase< Type >
Functionality for sampling fields using mappedPatchBase. Every call to mappedField() returns a sampled field, optionally scaled to maintain an area-weighted average.
Example usage:
{ fieldName T; // default is same as fvPatchField setAverage false; average 1.0; // only if setAverage=true interpolationScheme cellPoint; // default is cell }
Source files
mappedPatchFieldBase.H
mappedPatchFieldBase.C
Definition at line 64 of file mappedPatchFieldBase.H.
Constructor & Destructor Documentation
mappedPatchFieldBase() [1/5]
mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const word & fieldName, const bool setAverage, const Type average, const word & interpolationScheme)
Construct from components.
Definition at line 39 of file mappedPatchFieldBase.C.
Referenced by mappedPatchFieldBase< Type >::mappedPatchFieldBase().
mappedPatchFieldBase() [2/5]
mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const dictionary & dict)
Construct from dictionary.
Definition at line 59 of file mappedPatchFieldBase.C.
References dictionary::lookup(), mappedPatchFieldBase< Type >::mappedPatchFieldBase(), and mappedPatchBase::NEARESTCELL.
mappedPatchFieldBase() [3/5]
mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField)
Construct empty.
Definition at line 88 of file mappedPatchFieldBase.C.
References mappedPatchFieldBase< Type >::mappedPatchFieldBase().
mappedPatchFieldBase() [4/5]
mappedPatchFieldBase (const mappedPatchFieldBase< Type > & mapper)
Construct copy.
Definition at line 104 of file mappedPatchFieldBase.C.
References mappedPatchFieldBase< Type >::mappedPatchFieldBase().
mappedPatchFieldBase() [5/5]
mappedPatchFieldBase (const mappedPatchBase & mapper, const fvPatchField< Type > & patchField, const mappedPatchFieldBase< Type > & base)
Construct copy, resetting patch and field.
Definition at line 119 of file mappedPatchFieldBase.C.
~mappedPatchFieldBase()
virtual ~mappedPatchFieldBase () inline virtual
Destructor.
Definition at line 137 of file mappedPatchFieldBase.H.
References mappedPatchFieldBase< Type >::mappedField(), mappedPatchFieldBase< Type >::sampleField(), and mappedPatchFieldBase< Type >::write().
Member Function Documentation
sampleField()
const GeometricField< Type, fvPatchField, volMesh > & sampleField () const
Field to sample. Either on my or nbr mesh.
Definition at line 138 of file mappedPatchFieldBase.C.
References polyMesh::boundaryMesh(), and polyBoundaryMesh::mesh().
Referenced by mappedPatchFieldBase< Type >::~mappedPatchFieldBase().
mappedField()
tmp< Field< Type > > mappedField () const virtual
Map sampleField onto *this patch.
Definition at line 169 of file mappedPatchFieldBase.C.
References Foam::abort(), polyMesh::boundaryMesh(), mapDistribute::distribute(), Foam::FatalError, FatalErrorIn, polyBoundaryMesh::findPatchID(), forAll, Foam::gSum(), interpolation< Type >::interpolate(), Foam::mag(), Vector< scalar >::max, polyBoundaryMesh::mesh(), UPstream::msgType(), primitiveMesh::nCells(), mappedPatchBase::NEARESTCELL, mappedPatchBase::NEARESTFACE, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, primitiveMesh::nFaces(), Foam::nl, fvPatchField< Type >::patch(), mapDistribute::reverseDistribute(), samples(), List< Type >::setSize(), List< T >::size(), fvPatch::start(), and List< Type >::transfer().
Referenced by mappedPatchFieldBase< Type >::~mappedPatchFieldBase().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in mappedFieldFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, and mappedFixedInternalValueFvPatchField< Type >.
Definition at line 319 of file mappedPatchFieldBase.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by mappedFixedValueFvPatchField< Type >::write(), mappedFieldFvPatchField< Type >::write(), and mappedPatchFieldBase< Type >::~mappedPatchFieldBase().
Member Data Documentation
mapper_
const mappedPatchBase& mapper_ protected
Mapping engine.
Definition at line 72 of file mappedPatchFieldBase.H.
patchField_
const fvPatchField<Type>& patchField_ protected
Underlying patch field.
Definition at line 75 of file mappedPatchFieldBase.H.
fieldName_
word fieldName_ protected
Name of field to sample.
Definition at line 78 of file mappedPatchFieldBase.H.
setAverage_
const bool setAverage_ protected
If true adjust the mapped field to maintain average value average_.
Definition at line 81 of file mappedPatchFieldBase.H.
average_
const Type average_ protected
Average value the mapped field is adjusted to maintain if.
setAverage_ is set true
Definition at line 85 of file mappedPatchFieldBase.H.
interpolationScheme_
word interpolationScheme_ protected
Interpolation scheme to use for nearestcell mode.
Definition at line 88 of file mappedPatchFieldBase.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedPatchFieldBase.H
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedPatchFieldBase.C