OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mappedVelocityFluxFixedValueFvPatchField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Coupled boundary Conditions
This boundary condition maps the velocity and flux from a neighbour patch to this patch.
Public Member Functions
TypeName ("mappedVelocityFlux")
Runtime type information.
mappedVelocityFluxFixedValueFvPatchField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
mappedVelocityFluxFixedValueFvPatchField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition maps the velocity and flux from a neighbour patch to this patch.
Patch usage
Property Description Required Default value
phi flux field name no phi
Example of the boundary condition specification:
    myPatch
    {
        type            mappedVelocityFlux;
        phi             phi;
        value           uniform 0;  // place holder
    }
The underlying sample mode should be set to nearestPatchFace or nearestFace
Note
This boundary condition can only be applied to patches that are of the mappedPolyPatch type.
See also
Foam::mappedPatchBase Foam::mappedPolyPatch Foam::mappedFvPatch Foam::fixedValueFvPatchVectorField
Source files
mappedVelocityFluxFixedValueFvPatchField.H
mappedVelocityFluxFixedValueFvPatchField.C
Definition at line 93 of file mappedVelocityFluxFixedValueFvPatchField.H.
Constructor & Destructor Documentation
mappedVelocityFluxFixedValueFvPatchField() [1/5]
mappedVelocityFluxFixedValueFvPatchField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 38 of file mappedVelocityFluxFixedValueFvPatchField.C.
Referenced by mappedVelocityFluxFixedValueFvPatchField::clone(), and mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField().
mappedVelocityFluxFixedValueFvPatchField() [2/5]
mappedVelocityFluxFixedValueFvPatchField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 84 of file mappedVelocityFluxFixedValueFvPatchField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), mappedPatchBase::mode(), and fvPatch::name().
mappedVelocityFluxFixedValueFvPatchField() [3/5]
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mappedVelocityFluxFixedValueFvPatchField onto a new patch
Definition at line 50 of file mappedVelocityFluxFixedValueFvPatchField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), and fvPatch::name().
mappedVelocityFluxFixedValueFvPatchField() [4/5]
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField & ptf)
Construct as copy.
Definition at line 139 of file mappedVelocityFluxFixedValueFvPatchField.C.
References mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField().
mappedVelocityFluxFixedValueFvPatchField() [5/5]
mappedVelocityFluxFixedValueFvPatchField (const mappedVelocityFluxFixedValueFvPatchField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 150 of file mappedVelocityFluxFixedValueFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("mappedVelocityFlux")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 143 of file mappedVelocityFluxFixedValueFvPatchField.H.
References mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 160 of file mappedVelocityFluxFixedValueFvPatchField.H.
References mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), and mappedVelocityFluxFixedValueFvPatchField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 162 of file mappedVelocityFluxFixedValueFvPatchField.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensionedInternalField(), mappedPatchBase::distribute(), Foam::FatalError, FatalErrorIn, forAll, mappedPatchBase::mode(), UPstream::msgType(), mappedPatchBase::NEARESTFACE, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, Foam::nl, Foam::operator==(), fvPatchField< Type >::patch(), mappedPatchBase::sampleMesh(), mappedPatchBase::samplePatch(), fvPatch::start(), List< T >::transfer(), mappedVelocityFluxFixedValueFvPatchField::write(), and Vector< Cmpt >::zero.
Referenced by mappedVelocityFluxFixedValueFvPatchField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 258 of file mappedVelocityFluxFixedValueFvPatchField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by mappedVelocityFluxFixedValueFvPatchField::clone(), and mappedVelocityFluxFixedValueFvPatchField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedVelocityFluxFixedValue/mappedVelocityFluxFixedValueFvPatchField.H
src/finiteVolume/fields/fvPatchFields/derived/mappedVelocityFluxFixedValue/mappedVelocityFluxFixedValueFvPatchField.C