OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fluxCorrectedVelocityFvPatchVectorField Class Reference
Boundary Conditions » Outlet boundary Conditions
This boundary condition provides a velocity outlet boundary condition for patches where the pressure is specified. The outflow velocity is obtained by "zeroGradient" and then corrected from the flux:
Public Member Functions
TypeName ("fluxCorrectedVelocity")
Runtime type information.
fluxCorrectedVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
fluxCorrectedVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given fluxCorrectedVelocityFvPatchVectorField.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity outlet boundary condition for patches where the pressure is specified. The outflow velocity is obtained by "zeroGradient" and then corrected from the flux:
where
= velocity at the patch [m/s]
= velocity in cells adjacent to the patch [m/s]
= patch normal vectors
= flux at the patch [m3/s or kg/s]
= patch face area vectors [m2]
where
Property Description Required Default value
phi name of flux field no phi
rho name of density field no rho
Example of the boundary condition specification:
    myPatch
    {
        type            fluxCorrectedVelocity;
        phi             phi;
        rho             rho;
    }
Note
If reverse flow is possible or expected use the pressureInletOutletVelocity condition instead.
See also
Foam::zeroGradientFvPatchField Foam::pressureInletOutletVelocityFvPatchVectorField
Source files
fluxCorrectedVelocityFvPatchVectorField.H
fluxCorrectedVelocityFvPatchVectorField.C
Definition at line 129 of file fluxCorrectedVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
fluxCorrectedVelocityFvPatchVectorField() [1/4]
fluxCorrectedVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fluxCorrectedVelocityFvPatchVectorField.C.
Referenced by fluxCorrectedVelocityFvPatchVectorField::clone(), and fluxCorrectedVelocityFvPatchVectorField::fluxCorrectedVelocityFvPatchVectorField().
fluxCorrectedVelocityFvPatchVectorField() [2/4]
fluxCorrectedVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 64 of file fluxCorrectedVelocityFvPatchVectorField.C.
References fluxCorrectedVelocityFvPatchVectorField::fluxCorrectedVelocityFvPatchVectorField().
fluxCorrectedVelocityFvPatchVectorField() [3/4]
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given fluxCorrectedVelocityFvPatchVectorField.
onto a new patch
Definition at line 49 of file fluxCorrectedVelocityFvPatchVectorField.C.
References fluxCorrectedVelocityFvPatchVectorField::fluxCorrectedVelocityFvPatchVectorField().
fluxCorrectedVelocityFvPatchVectorField() [4/4]
fluxCorrectedVelocityFvPatchVectorField (const fluxCorrectedVelocityFvPatchVectorField & fcvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 80 of file fluxCorrectedVelocityFvPatchVectorField.C.
References fluxCorrectedVelocityFvPatchVectorField::evaluate().
Member Function Documentation
TypeName()
TypeName ("fluxCorrectedVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 176 of file fluxCorrectedVelocityFvPatchVectorField.H.
References fluxCorrectedVelocityFvPatchVectorField::fluxCorrectedVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 193 of file fluxCorrectedVelocityFvPatchVectorField.H.
References UPstream::blocking, fluxCorrectedVelocityFvPatchVectorField::evaluate(), fluxCorrectedVelocityFvPatchVectorField::fluxCorrectedVelocityFvPatchVectorField(), and fluxCorrectedVelocityFvPatchVectorField::write().
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Definition at line 94 of file fluxCorrectedVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, dimensionedInternalField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorIn, n, Foam::operator==(), and phi.
Referenced by fluxCorrectedVelocityFvPatchVectorField::clone(), and fluxCorrectedVelocityFvPatchVectorField::fluxCorrectedVelocityFvPatchVectorField().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 140 of file fluxCorrectedVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by fluxCorrectedVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fluxCorrectedVelocity/fluxCorrectedVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/fluxCorrectedVelocity/fluxCorrectedVelocityFvPatchVectorField.C