OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mappedFlowRateFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Coupled boundary Conditions
Describes a volumetric/mass flow normal vector boundary condition by its magnitude as an integral over its area.
Public Member Functions
TypeName ("mappedFlowRate")
Runtime type information.
mappedFlowRateFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
mappedFlowRateFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Describes a volumetric/mass flow normal vector boundary condition by its magnitude as an integral over its area.
The inlet mass flux is taken from the neighbour region.
The basis of the patch (volumetric or mass) is determined by the dimensions of the flux, phi. The current density is used to correct the velocity when applying the mass basis.
Patch usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
neigPhi name of flux field on neighbour mesh yes
Example of the boundary condition specification:
    myPatch
    {
        type            mappedFlowRate;
        phi             phi;
        rho             rho;
        neigPhi         phi;
        value           uniform (0 0 0); // placeholder
    }
Source files
mappedFlowRateFvPatchVectorField.H
mappedFlowRateFvPatchVectorField.C
Definition at line 98 of file mappedFlowRateFvPatchVectorField.H.
Constructor & Destructor Documentation
mappedFlowRateFvPatchVectorField() [1/5]
mappedFlowRateFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file mappedFlowRateFvPatchVectorField.C.
Referenced by mappedFlowRateFvPatchVectorField::clone(), and mappedFlowRateFvPatchVectorField::mappedFlowRateFvPatchVectorField().
mappedFlowRateFvPatchVectorField() [2/5]
mappedFlowRateFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 64 of file mappedFlowRateFvPatchVectorField.C.
References mappedFlowRateFvPatchVectorField::mappedFlowRateFvPatchVectorField().
mappedFlowRateFvPatchVectorField() [3/5]
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mappedFlowRateFvPatchVectorField onto a new patch
Definition at line 49 of file mappedFlowRateFvPatchVectorField.C.
References mappedFlowRateFvPatchVectorField::mappedFlowRateFvPatchVectorField().
mappedFlowRateFvPatchVectorField() [4/5]
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField & ptf)
Construct as copy.
Definition at line 78 of file mappedFlowRateFvPatchVectorField.C.
References mappedFlowRateFvPatchVectorField::mappedFlowRateFvPatchVectorField().
mappedFlowRateFvPatchVectorField() [5/5]
mappedFlowRateFvPatchVectorField (const mappedFlowRateFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 90 of file mappedFlowRateFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("mappedFlowRate")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 155 of file mappedFlowRateFvPatchVectorField.H.
References mappedFlowRateFvPatchVectorField::mappedFlowRateFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 172 of file mappedFlowRateFvPatchVectorField.H.
References mappedFlowRateFvPatchVectorField::mappedFlowRateFvPatchVectorField(), mappedFlowRateFvPatchVectorField::updateCoeffs(), and mappedFlowRateFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 104 of file mappedFlowRateFvPatchVectorField.C.
References boundary(), Foam::dimArea, Foam::dimDensity, dimensionedInternalField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, mappedPatchBase::distribute(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::gSum(), patchIdentifier::index(), Foam::Info, fvPatch::lookupPatchField(), UPstream::msgType(), n, fvPatch::name(), Foam::nl, Foam::operator==(), phi, mappedPatchBase::sampleMesh(), mappedPatchBase::samplePolyPatch(), U, fvPatchField< Type >::updateCoeffs(), and mappedFlowRateFvPatchVectorField::write().
Referenced by mappedFlowRateFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 186 of file mappedFlowRateFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, and fvPatchField< Type >::write().
Referenced by mappedFlowRateFvPatchVectorField::clone(), and mappedFlowRateFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedFlowRate/mappedFlowRateFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/mappedFlowRate/mappedFlowRateFvPatchVectorField.C