OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interpolation< Type > Class Template Reference abstract
Abstract base class for interpolation.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolation, dictionary,(const GeometricField< Type, fvPatchField, volMesh > &psi),(psi))
interpolation (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
virtual ~interpolation ()
Destructor.
const GeometricField< Type, fvPatchField, volMesh > & psi () const
Return the field to be interpolated.
virtual Type interpolate (const vector &position, const label cellI, const label faceI=-1) const =0
Interpolate field to the given point in the given cell.
virtual Type interpolate (const vector &position, const tetIndices &tetIs, const label faceI=-1) const
Interpolate field to the given point in the tetrahedron.
Static Public Member Functions
static autoPtr< interpolation< Type > > New (const word &interpolationType, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the specified interpolation scheme.
static autoPtr< interpolation< Type > > New (const dictionary &interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the selected interpolation scheme.
Protected Attributes
const GeometricField< Type, fvPatchField, volMesh > & psi_
const polyMesh & pMesh_
const vectorField & pMeshPoints_
const faceList & pMeshFaces_
const vectorField & pMeshFaceCentres_
const vectorField & pMeshFaceAreas_
Detailed Description
template<class Type>
class Foam::interpolation< Type >
Abstract base class for interpolation.
Definition at line 57 of file mappedPatchFieldBase.H.
Constructor & Destructor Documentation
interpolation()
interpolation (const GeometricField< Type, fvPatchField, volMesh > & psi)
Construct from components.
Definition at line 40 of file interpolation.C.
~interpolation()
virtual ~interpolation () inline virtual
Destructor.
Definition at line 117 of file interpolation.H.
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , interpolation< Type > , dictionary , (const GeometricField< Type, fvPatchField, volMesh > &psi) , (psi))
New() [1/2]
Foam::autoPtr< Foam::interpolation< Type > > New (const word & interpolationType, const GeometricField< Type, fvPatchField, volMesh > & psi) static
Return a reference to the specified interpolation scheme.
Definition at line 33 of file interpolationNew.C.
Referenced by interpolation< Foam::Vector >::New().
New() [2/2]
Foam::autoPtr< Foam::interpolation< Type > > New (const dictionary & interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > & psi) static
Return a reference to the selected interpolation scheme.
Definition at line 60 of file interpolationNew.C.
psi()
const GeometricField<Type, fvPatchField, volMesh>& psi () const inline
Return the field to be interpolated.
Definition at line 124 of file interpolation.H.
Referenced by sampledCuttingPlane::interpolateField(), sampledIsoSurface::interpolateField(), and distanceSurface::interpolateField().
interpolate() [1/2]
virtual Type interpolate (const vector & position, const label cellI, const label faceI = -1) const pure virtual
Interpolate field to the given point in the given cell.
Implemented in interpolationCellPointFace< Type >, interpolationCellPoint< Type >, interpolationPointMVC< Type >, interpolationCellPoint< scalar >, interpolationCellPoint< Foam::Vector >, interpolationCellPatchConstrained< Type >, interpolationCellPointWallModified< Type >, and interpolationCell< Type >.
Referenced by ParamagneticForce< CloudType >::calcNonCoupled(), interpolation< Foam::Vector >::interpolate(), sampledPlane::interpolateField(), sampledIsoSurfaceCell::interpolateField(), sampledThresholdCellFaces::interpolateField(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), sampledTriSurfaceMesh::interpolateField(), mappedPatchFieldBase< Type >::mappedField(), and interpolation< Foam::Vector >::psi().
interpolate() [2/2]
virtual Type interpolate (const vector & position, const tetIndices & tetIs, const label faceI = -1) const inline virtual
Interpolate field to the given point in the tetrahedron.
defined by the given indices. Calls interpolate function above here execpt where overridden by derived interpolation types.
Reimplemented in interpolationCellPoint< Type >, interpolationCellPoint< scalar >, interpolationCellPoint< Foam::Vector >, and interpolationCellPointWallModified< Type >.
Definition at line 142 of file interpolation.H.
Member Data Documentation
psi_
const GeometricField<Type, fvPatchField, volMesh>& psi_ protected
Definition at line 61 of file interpolation.H.
Referenced by interpolation< Foam::Vector >::psi().
pMesh_
const polyMesh& pMesh_ protected
Definition at line 63 of file interpolation.H.
pMeshPoints_
const vectorField& pMeshPoints_ protected
Definition at line 64 of file interpolation.H.
pMeshFaces_
const faceList& pMeshFaces_ protected
Definition at line 65 of file interpolation.H.
pMeshFaceCentres_
const vectorField& pMeshFaceCentres_ protected
Definition at line 66 of file interpolation.H.
pMeshFaceAreas_
const vectorField& pMeshFaceAreas_ protected
Definition at line 67 of file interpolation.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedPatchFieldBase.H
src/finiteVolume/interpolation/interpolation/interpolation/interpolation.H
src/finiteVolume/interpolation/interpolation/interpolation/interpolation.C
src/finiteVolume/interpolation/interpolation/interpolation/interpolationNew.C