OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
phaseHydrostaticPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides a phase-based hydrostatic pressure condition, calculated as:
Public Member Functions
TypeName ("phaseHydrostaticPressure")
Runtime type information.
phaseHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
phaseHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & phaseName () const
Return the phaseName.
word & phaseName ()
Return reference to the phaseName to allow adjustment.
scalar rho () const
Return the constant density in the far-field.
scalar & rho ()
Return reference to the constant density in the far-field.
scalar pRefValue () const
Return the reference pressure.
scalar & pRefValue ()
Return reference to the reference pressure to allow adjustment.
const vector & pRefPoint () const
Return the pressure reference location.
vector & pRefPoint ()
Return reference to the pressure reference location.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchScalarField &pvf)
Protected Attributes
word phaseName_
Name of phase-fraction field.
scalar rho_
Constant density in the far-field.
scalar pRefValue_
Reference pressure.
vector pRefPoint_
Reference pressure location.
Detailed Description
This boundary condition provides a phase-based hydrostatic pressure condition, calculated as:
where
= hyrostatic pressure [Pa]
= reference pressure [Pa]
= reference point in Cartesian co-ordinates
= density (assumed uniform)
= acceleration due to gravity [m/s2]
The values are assigned according to the phase-fraction field:
1: apply $fp_{hyd}$f
0: apply a zero-gradient condition
Patch usage
Property Description Required Default value
phaseName phase field name no alpha
rho density field name no rho
pRefValue reference pressure [Pa] yes
pRefPoint reference pressure location yes
Example of the boundary condition specification:
    myPatch
    {
        type            phaseHydrostaticPressure;
        phaseName       alpha1;
        rho             rho;
        pRefValue       1e5;
        pRefPoint       (0 0 0);
        value           uniform 0; // optional initial value
    }
See also
Foam::mixedFvPatchScalarField
Source files
phaseHydrostaticPressureFvPatchScalarField.H
phaseHydrostaticPressureFvPatchScalarField.C
Definition at line 140 of file phaseHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
phaseHydrostaticPressureFvPatchScalarField() [1/5]
phaseHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file phaseHydrostaticPressureFvPatchScalarField.C.
Referenced by phaseHydrostaticPressureFvPatchScalarField::clone(), and phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseHydrostaticPressureFvPatchScalarField() [2/5]
phaseHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 56 of file phaseHydrostaticPressureFvPatchScalarField.C.
References dictionary::found(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), scalarField(), and fvPatch::size().
phaseHydrostaticPressureFvPatchScalarField() [3/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
phaseHydrostaticPressureFvPatchScalarField onto a new patch
Definition at line 89 of file phaseHydrostaticPressureFvPatchScalarField.C.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseHydrostaticPressureFvPatchScalarField() [4/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 106 of file phaseHydrostaticPressureFvPatchScalarField.C.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseHydrostaticPressureFvPatchScalarField() [5/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 117 of file phaseHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("phaseHydrostaticPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 202 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 219 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseName() [1/2]
const word& phaseName () const inline
Return the phaseName.
Definition at line 235 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseName_.
phaseName() [2/2]
word& phaseName () inline
Return reference to the phaseName to allow adjustment.
Definition at line 241 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseName_.
rho() [1/2]
scalar rho () const inline
Return the constant density in the far-field.
Definition at line 247 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::rho_.
rho() [2/2]
scalar& rho () inline
Return reference to the constant density in the far-field.
to allow adjustment
Definition at line 254 of file phaseHydrostaticPressureFvPatchScalarField.H.
pRefValue() [1/2]
scalar pRefValue () const inline
Return the reference pressure.
Definition at line 260 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefValue_.
pRefValue() [2/2]
scalar& pRefValue () inline
Return reference to the reference pressure to allow adjustment.
Definition at line 266 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefValue_.
pRefPoint() [1/2]
const vector& pRefPoint () const inline
Return the pressure reference location.
Definition at line 272 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::operator=(), phaseHydrostaticPressureFvPatchScalarField::pRefPoint_, phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
pRefPoint() [2/2]
vector& pRefPoint () inline
Return reference to the pressure reference location.
to allow adjustment
Definition at line 279 of file phaseHydrostaticPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 132 of file phaseHydrostaticPressureFvPatchScalarField.C.
References Foam::max(), Foam::min(), phaseHydrostaticPressureFvPatchScalarField::phaseName_, phaseHydrostaticPressureFvPatchScalarField::pRefPoint_, phaseHydrostaticPressureFvPatchScalarField::pRefValue_, and phaseHydrostaticPressureFvPatchScalarField::rho_.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 161 of file phaseHydrostaticPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::nl, phaseHydrostaticPressureFvPatchScalarField::phaseName_, phaseHydrostaticPressureFvPatchScalarField::pRefPoint_, phaseHydrostaticPressureFvPatchScalarField::pRefValue_, phaseHydrostaticPressureFvPatchScalarField::rho_, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
operator=()
void operator= (const fvPatchScalarField & pvf) virtual
Definition at line 179 of file phaseHydrostaticPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::operator.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
Member Data Documentation
phaseName_
word phaseName_ protected
Name of phase-fraction field.
Definition at line 150 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::phaseName(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
rho_
scalar rho_ protected
Constant density in the far-field.
Definition at line 153 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::rho(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
pRefValue_
scalar pRefValue_ protected
Reference pressure.
Definition at line 156 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefValue(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
pRefPoint_
vector pRefPoint_ protected
Reference pressure location.
Definition at line 159 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/phaseHydrostaticPressure/phaseHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/phaseHydrostaticPressure/phaseHydrostaticPressureFvPatchScalarField.C