OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pressureInletUniformVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This velocity inlet boundary condition is applied to patches where the pressure is specified. The uniform inflow velocity is obtained by averaging the flux over the patch, and then applying it in the direction normal to the patch faces.
Public Member Functions
TypeName ("pressureInletUniformVelocity")
Runtime type information.
pressureInletUniformVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureInletUniformVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void operator= (const fvPatchField< vector > &pvf)
Public Member Functions inherited from pressureInletVelocityFvPatchVectorField
TypeName ("pressureInletVelocity")
Runtime type information.
pressureInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given pressureInletVelocityFvPatchVectorField.
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &)
Construct as copy.
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
virtual void write (Ostream &) const
Write.
Detailed Description
This velocity inlet boundary condition is applied to patches where the pressure is specified. The uniform inflow velocity is obtained by averaging the flux over the patch, and then applying it in the direction normal to the patch faces.
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            pressureInletUniformVelocity;
    value           uniform 0;
}
Source files
pressureInletUniformVelocityFvPatchVectorField.H
pressureInletUniformVelocityFvPatchVectorField.C
Definition at line 65 of file pressureInletUniformVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletUniformVelocityFvPatchVectorField() [1/5]
pressureInletUniformVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file pressureInletUniformVelocityFvPatchVectorField.C.
Referenced by pressureInletUniformVelocityFvPatchVectorField::clone(), and pressureInletUniformVelocityFvPatchVectorField::pressureInletUniformVelocityFvPatchVectorField().
pressureInletUniformVelocityFvPatchVectorField() [2/5]
pressureInletUniformVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 59 of file pressureInletUniformVelocityFvPatchVectorField.C.
References pressureInletUniformVelocityFvPatchVectorField::pressureInletUniformVelocityFvPatchVectorField().
pressureInletUniformVelocityFvPatchVectorField() [3/5]
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
pressureInletUniformVelocityFvPatchVectorField onto a new patch
Definition at line 46 of file pressureInletUniformVelocityFvPatchVectorField.C.
References pressureInletUniformVelocityFvPatchVectorField::pressureInletUniformVelocityFvPatchVectorField().
pressureInletUniformVelocityFvPatchVectorField() [4/5]
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 71 of file pressureInletUniformVelocityFvPatchVectorField.C.
References pressureInletUniformVelocityFvPatchVectorField::pressureInletUniformVelocityFvPatchVectorField().
pressureInletUniformVelocityFvPatchVectorField() [5/5]
pressureInletUniformVelocityFvPatchVectorField (const pressureInletUniformVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 81 of file pressureInletUniformVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureInletUniformVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 110 of file pressureInletUniformVelocityFvPatchVectorField.H.
References pressureInletUniformVelocityFvPatchVectorField::pressureInletUniformVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 127 of file pressureInletUniformVelocityFvPatchVectorField.H.
References pressureInletUniformVelocityFvPatchVectorField::operator=(), pressureInletUniformVelocityFvPatchVectorField::pressureInletUniformVelocityFvPatchVectorField(), and pressureInletUniformVelocityFvPatchVectorField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 92 of file pressureInletUniformVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::operator==(), and pressureInletVelocityFvPatchVectorField::updateCoeffs().
Referenced by pressureInletUniformVelocityFvPatchVectorField::clone().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Reimplemented from pressureInletVelocityFvPatchVectorField.
Definition at line 108 of file pressureInletUniformVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::makePatchTypeField(), and Foam::operator==().
Referenced by pressureInletUniformVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletUniformVelocity/pressureInletUniformVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletUniformVelocity/pressureInletUniformVelocityFvPatchVectorField.C