OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceNormalFixedValueFvPatchVectorField Class Reference
Boundary Conditions » Generic boundary ConditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition provides a surface-normal vector boundary condition by its magnitude.
Public Member Functions
TypeName ("surfaceNormalFixedValue")
Runtime type information.
surfaceNormalFixedValueFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
surfaceNormalFixedValueFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a surface-normal vector boundary condition by its magnitude.
Patch usage
Property Description Required Default value
refValue reference value yes
Example of the boundary condition specification:
    myPatch
    {
        type            surfaceNormalFixedValue;
        refValue        uniform -10;           // 10 INTO the domain
    }
Note
Sign conventions:
the value is positive for outward-pointing vectors
See also
Foam::fixedValueFvPatchField
Source files
surfaceNormalFixedValueFvPatchVectorField.H
surfaceNormalFixedValueFvPatchVectorField.C
Definition at line 86 of file surfaceNormalFixedValueFvPatchVectorField.H.
Constructor & Destructor Documentation
surfaceNormalFixedValueFvPatchVectorField() [1/5]
surfaceNormalFixedValueFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file surfaceNormalFixedValueFvPatchVectorField.C.
Referenced by surfaceNormalFixedValueFvPatchVectorField::clone(), and surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField().
surfaceNormalFixedValueFvPatchVectorField() [2/5]
surfaceNormalFixedValueFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 72 of file surfaceNormalFixedValueFvPatchVectorField.C.
References surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField().
surfaceNormalFixedValueFvPatchVectorField() [3/5]
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
surfaceNormalFixedValueFvPatchVectorField onto a new patch
Definition at line 47 of file surfaceNormalFixedValueFvPatchVectorField.C.
References surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField(), and vectorField().
surfaceNormalFixedValueFvPatchVectorField() [4/5]
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 87 of file surfaceNormalFixedValueFvPatchVectorField.C.
References surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField().
surfaceNormalFixedValueFvPatchVectorField() [5/5]
surfaceNormalFixedValueFvPatchVectorField (const surfaceNormalFixedValueFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 98 of file surfaceNormalFixedValueFvPatchVectorField.C.
References surfaceNormalFixedValueFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("surfaceNormalFixedValue")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 136 of file surfaceNormalFixedValueFvPatchVectorField.H.
References surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 153 of file surfaceNormalFixedValueFvPatchVectorField.H.
References surfaceNormalFixedValueFvPatchVectorField::autoMap(), surfaceNormalFixedValueFvPatchVectorField::rmap(), surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField(), surfaceNormalFixedValueFvPatchVectorField::updateCoeffs(), and surfaceNormalFixedValueFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 111 of file surfaceNormalFixedValueFvPatchVectorField.C.
References surfaceNormalFixedValueFvPatchVectorField::rmap().
Referenced by surfaceNormalFixedValueFvPatchVectorField::clone(), and surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 121 of file surfaceNormalFixedValueFvPatchVectorField.C.
References surfaceNormalFixedValueFvPatchVectorField::rmap().
Referenced by surfaceNormalFixedValueFvPatchVectorField::autoMap(), surfaceNormalFixedValueFvPatchVectorField::clone(), and surfaceNormalFixedValueFvPatchVectorField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 135 of file surfaceNormalFixedValueFvPatchVectorField.C.
References fvPatchField< Type >::operator=(), and fvPatchField< Type >::updateCoeffs().
Referenced by surfaceNormalFixedValueFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 147 of file surfaceNormalFixedValueFvPatchVectorField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by surfaceNormalFixedValueFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/surfaceNormalFixedValue/surfaceNormalFixedValueFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/surfaceNormalFixedValue/surfaceNormalFixedValueFvPatchVectorField.C