OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
totalTemperatureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This boundary condition provides a total temperature condition.
Public Member Functions
TypeName ("totalTemperature")
Runtime type information.
totalTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
totalTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
totalTemperatureFvPatchScalarField (const totalTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given totalTemperatureFvPatchScalarField.
totalTemperatureFvPatchScalarField (const totalTemperatureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
totalTemperatureFvPatchScalarField (const totalTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & T0 () const
Return the total pressure.
scalarField & T0 ()
Return reference to the total pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a total temperature condition.
Patch usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
psi Compressibility field name no thermo:psi
gamma ratio of specific heats (Cp/Cv) yes
T0 reference temperature yes
Example of the boundary condition specification:
    myPatch
    {
        type            totalTemperature;
        T0              uniform 300;
    }
Source files
totalTemperatureFvPatchScalarField.H
totalTemperatureFvPatchScalarField.C
See also
Foam::fixedValueFvPatchField
Definition at line 104 of file totalTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
totalTemperatureFvPatchScalarField() [1/5]
totalTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file totalTemperatureFvPatchScalarField.C.
Referenced by totalTemperatureFvPatchScalarField::clone(), and totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
totalTemperatureFvPatchScalarField() [2/5]
totalTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 67 of file totalTemperatureFvPatchScalarField.C.
References dictionary::found(), scalarField(), fvPatch::size(), and totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
totalTemperatureFvPatchScalarField() [3/5]
totalTemperatureFvPatchScalarField (const totalTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given totalTemperatureFvPatchScalarField.
onto a new patch
Definition at line 50 of file totalTemperatureFvPatchScalarField.C.
References totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
totalTemperatureFvPatchScalarField() [4/5]
totalTemperatureFvPatchScalarField (const totalTemperatureFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 95 of file totalTemperatureFvPatchScalarField.C.
References totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
totalTemperatureFvPatchScalarField() [5/5]
totalTemperatureFvPatchScalarField (const totalTemperatureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 109 of file totalTemperatureFvPatchScalarField.C.
References totalTemperatureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("totalTemperature")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 166 of file totalTemperatureFvPatchScalarField.H.
References totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 183 of file totalTemperatureFvPatchScalarField.H.
References totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
T0() [1/2]
const scalarField& T0 () const inline
Return the total pressure.
Definition at line 199 of file totalTemperatureFvPatchScalarField.H.
T0() [2/2]
scalarField& T0 () inline
Return reference to the total pressure to allow adjustment.
Definition at line 205 of file totalTemperatureFvPatchScalarField.H.
References totalTemperatureFvPatchScalarField::autoMap(), totalTemperatureFvPatchScalarField::rmap(), totalTemperatureFvPatchScalarField::updateCoeffs(), and totalTemperatureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 126 of file totalTemperatureFvPatchScalarField.C.
References totalTemperatureFvPatchScalarField::rmap().
Referenced by totalTemperatureFvPatchScalarField::T0(), and totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 136 of file totalTemperatureFvPatchScalarField.C.
References totalTemperatureFvPatchScalarField::rmap().
Referenced by totalTemperatureFvPatchScalarField::autoMap(), totalTemperatureFvPatchScalarField::rmap(), and totalTemperatureFvPatchScalarField::T0().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 150 of file totalTemperatureFvPatchScalarField.C.
References Foam::magSqr(), and Foam::pos().
Referenced by totalTemperatureFvPatchScalarField::T0().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 177 of file totalTemperatureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by totalTemperatureFvPatchScalarField::T0().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/totalTemperature/totalTemperatureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/totalTemperature/totalTemperatureFvPatchScalarField.C