OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
prghPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides static pressure condition for p_rgh, calculated as:
Public Member Functions
TypeName ("prghPressure")
Runtime type information.
prghPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
prghPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & rhoName () const
Return the rhoName.
word & rhoName ()
Return reference to the rhoName to allow adjustment.
const scalarField & p () const
Return the static pressure.
scalarField & p ()
Return reference to the static pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
word rhoName_
Name of phase-fraction field.
scalarField p_
Static pressure.
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pseudo hydrostatic pressure [Pa]
= Static pressure [Pa]
= Height in the opposite direction to gravity
= density
= acceleration due to gravity [m/s2]
Patch usage
Property Description Required Default value
rhoName rho field name no rho
p static pressure yes
Example of the boundary condition specification:
    myPatch
    {
        type            prghPressure;
        rhoName         rho;
        p               uniform 0;
        value           uniform 0; // optional initial value
    }
See also
Foam::fixedValueFvPatchScalarField
Source files
prghPressureFvPatchScalarField.H
prghPressureFvPatchScalarField.C
Definition at line 122 of file prghPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghPressureFvPatchScalarField() [1/5]
prghPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file prghPressureFvPatchScalarField.C.
Referenced by prghPressureFvPatchScalarField::clone(), and prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
prghPressureFvPatchScalarField() [2/5]
prghPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 49 of file prghPressureFvPatchScalarField.C.
References dictionary::found(), prghPressureFvPatchScalarField::prghPressureFvPatchScalarField(), scalarField(), and fvPatch::size().
prghPressureFvPatchScalarField() [3/5]
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
prghPressureFvPatchScalarField onto a new patch
Definition at line 75 of file prghPressureFvPatchScalarField.C.
References prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
prghPressureFvPatchScalarField() [4/5]
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 90 of file prghPressureFvPatchScalarField.C.
References prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
prghPressureFvPatchScalarField() [5/5]
prghPressureFvPatchScalarField (const prghPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 102 of file prghPressureFvPatchScalarField.C.
References prghPressureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("prghPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 178 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 195 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
rhoName() [1/2]
const word& rhoName () const inline
Return the rhoName.
Definition at line 211 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::rhoName_.
rhoName() [2/2]
word& rhoName () inline
Return reference to the rhoName to allow adjustment.
Definition at line 217 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::rhoName_.
p() [1/2]
const scalarField& p () const inline
Return the static pressure.
Definition at line 223 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::p_.
p() [2/2]
scalarField& p () inline
Return reference to the static pressure to allow adjustment.
Definition at line 229 of file prghPressureFvPatchScalarField.H.
References prghPressureFvPatchScalarField::autoMap(), prghPressureFvPatchScalarField::p_, prghPressureFvPatchScalarField::rmap(), prghPressureFvPatchScalarField::updateCoeffs(), and prghPressureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 116 of file prghPressureFvPatchScalarField.C.
References prghPressureFvPatchScalarField::rmap().
Referenced by prghPressureFvPatchScalarField::p(), and prghPressureFvPatchScalarField::prghPressureFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 126 of file prghPressureFvPatchScalarField.C.
References prghPressureFvPatchScalarField::p_, and prghPressureFvPatchScalarField::rmap().
Referenced by prghPressureFvPatchScalarField::autoMap(), prghPressureFvPatchScalarField::p(), and prghPressureFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 140 of file prghPressureFvPatchScalarField.C.
References Foam::operator==(), prghPressureFvPatchScalarField::p_, and prghPressureFvPatchScalarField::rhoName_.
Referenced by prghPressureFvPatchScalarField::p().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 161 of file prghPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, prghPressureFvPatchScalarField::p_, prghPressureFvPatchScalarField::rhoName_, fvPatchField< Type >::write(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by prghPressureFvPatchScalarField::p().
Member Data Documentation
rhoName_
word rhoName_ protected
Name of phase-fraction field.
Definition at line 132 of file prghPressureFvPatchScalarField.H.
Referenced by prghPressureFvPatchScalarField::rhoName(), prghPressureFvPatchScalarField::updateCoeffs(), and prghPressureFvPatchScalarField::write().
p_
scalarField p_ protected
Static pressure.
Definition at line 135 of file prghPressureFvPatchScalarField.H.
Referenced by prghPressureFvPatchScalarField::p(), prghPressureFvPatchScalarField::rmap(), prghPressureFvPatchScalarField::updateCoeffs(), and prghPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghPressure/prghPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghPressure/prghPressureFvPatchScalarField.C