OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
syringePressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a pressure condition, obtained from a zero-D model of the cylinder of a syringe.
Public Member Functions
TypeName ("syringePressure")
Runtime type information.
syringePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
syringePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given syringePressureFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField &)
Construct as copy.
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a pressure condition, obtained from a zero-D model of the cylinder of a syringe.
The syringe cylinder is defined by its initial volume, piston area and velocity profile specified by regions of constant acceleration, speed and deceleration. The gas in the cylinder is described by its initial pressure and compressibility which is assumed constant, i.e. isothermal expansion/compression.
Patch usage
Property Description Required Default value
Ap syringe piston area [m2] yes
Sp syringe piston speed [m/s] yes
VsI initial syringe volume [m3] yes
tas start of piston acceleration [s] yes
tae end of piston acceleration [s] yes
tds start of piston deceleration [s] yes
tde end of piston deceleration [s] yes
psI initial syringe pressure [Pa] yes
psi gas compressibility [m2/s2] yes
ams added (or removed) gas mass [kg] yes
Example of the BC specification:
    myPatch
    {
        type            syringePressure;
        Ap              1.388e-6;
        Sp              0.01;
        VsI             1.388e-8;
        tas             0.001;
        tae             0.002;
        tds             0.005;
        tde             0.006;
        psI             1e5;
        psi             1e-5;
        ams             0;
        value           uniform 0;
    }
See also
Foam::fixedValueFvPatchField
Source files
syringePressureFvPatchScalarField.H
syringePressureFvPatchScalarField.C
Definition at line 151 of file syringePressureFvPatchScalarField.H.
Constructor & Destructor Documentation
syringePressureFvPatchScalarField() [1/5]
syringePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file syringePressureFvPatchScalarField.C.
Referenced by syringePressureFvPatchScalarField::clone(), and syringePressureFvPatchScalarField::syringePressureFvPatchScalarField().
syringePressureFvPatchScalarField() [2/5]
syringePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 70 of file syringePressureFvPatchScalarField.C.
References syringePressureFvPatchScalarField::syringePressureFvPatchScalarField().
syringePressureFvPatchScalarField() [3/5]
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField & sppsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given syringePressureFvPatchScalarField.
onto a new patch
Definition at line 46 of file syringePressureFvPatchScalarField.C.
References syringePressureFvPatchScalarField::syringePressureFvPatchScalarField().
syringePressureFvPatchScalarField() [4/5]
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField & sppsf)
Construct as copy.
Definition at line 118 of file syringePressureFvPatchScalarField.C.
References Foam::sqr().
syringePressureFvPatchScalarField() [5/5]
syringePressureFvPatchScalarField (const syringePressureFvPatchScalarField & sppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 96 of file syringePressureFvPatchScalarField.C.
References syringePressureFvPatchScalarField::syringePressureFvPatchScalarField().
Member Function Documentation
TypeName()
TypeName ("syringePressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 234 of file syringePressureFvPatchScalarField.H.
References syringePressureFvPatchScalarField::syringePressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 257 of file syringePressureFvPatchScalarField.H.
References syringePressureFvPatchScalarField::syringePressureFvPatchScalarField(), syringePressureFvPatchScalarField::updateCoeffs(), and syringePressureFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 179 of file syringePressureFvPatchScalarField.C.
References Foam::dimArea, Foam::dimDensity, dimensionedInternalField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::operator==(), phi, Foam::sum(), and timeIndex.
Referenced by syringePressureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 227 of file syringePressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by syringePressureFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/syringePressure/syringePressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/syringePressure/syringePressureFvPatchScalarField.C