OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
rotatingPressureInletOutletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This velocity inlet/outlet boundary condition is applied to patches in a rotating frame where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
Public Member Functions
TypeName ("rotatingPressureInletOutletVelocity")
Runtime type information.
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from pressureInletOutletVelocityFvPatchVectorField
TypeName ("pressureInletOutletVelocity")
Runtime type information.
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &)
Construct as copy.
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
const vectorField & tangentialVelocity () const
Return the tangential velocity.
void setTangentialVelocity (const vectorField &tangentialVelocity)
Reset the tangential velocity.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to patches in a rotating frame where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
Patch usage
Property Description Required Default value
phi flux field name no phi
tangentialVelocity tangential velocity field no
omega angular velocty of the frame [rad/s] yes
Example of the boundary condition specification:
    myPatch
    {
        type            rotatingPressureInletOutletVelocity;
        phi             phi;
        tangentialVelocity uniform (0 0 0);
        omega           100;
    }
The omega entry is a DataEntry type, able to describe time varying functions.
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux in the patch-normal direction
See also
Foam::pressureInletOutletVelocityFvPatchVectorField
Source files
rotatingPressureInletOutletVelocityFvPatchVectorField.H
rotatingPressureInletOutletVelocityFvPatchVectorField.C
Definition at line 108 of file rotatingPressureInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
rotatingPressureInletOutletVelocityFvPatchVectorField() [1/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 54 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
Referenced by rotatingPressureInletOutletVelocityFvPatchVectorField::clone(), and rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField().
rotatingPressureInletOutletVelocityFvPatchVectorField() [2/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 82 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
References rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField().
rotatingPressureInletOutletVelocityFvPatchVectorField() [3/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
rotatingPressureInletOutletVelocityFvPatchVectorField onto a new patch
Definition at line 66 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
References rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField().
rotatingPressureInletOutletVelocityFvPatchVectorField() [4/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField & rppvf)
Construct as copy.
Definition at line 97 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
References rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField().
rotatingPressureInletOutletVelocityFvPatchVectorField() [5/5]
rotatingPressureInletOutletVelocityFvPatchVectorField (const rotatingPressureInletOutletVelocityFvPatchVectorField & rppvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 110 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
References rotatingPressureInletOutletVelocityFvPatchVectorField::write().
Member Function Documentation
TypeName()
TypeName ("rotatingPressureInletOutletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Reimplemented from pressureInletOutletVelocityFvPatchVectorField.
Definition at line 165 of file rotatingPressureInletOutletVelocityFvPatchVectorField.H.
References rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from pressureInletOutletVelocityFvPatchVectorField.
Definition at line 182 of file rotatingPressureInletOutletVelocityFvPatchVectorField.H.
References rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField(), and rotatingPressureInletOutletVelocityFvPatchVectorField::write().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from pressureInletOutletVelocityFvPatchVectorField.
Definition at line 125 of file rotatingPressureInletOutletVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, pressureInletOutletVelocityFvPatchVectorField::phiName(), fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by rotatingPressureInletOutletVelocityFvPatchVectorField::clone(), and rotatingPressureInletOutletVelocityFvPatchVectorField::rotatingPressureInletOutletVelocityFvPatchVectorField().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/rotatingPressureInletOutletVelocity/rotatingPressureInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/rotatingPressureInletOutletVelocity/rotatingPressureInletOutletVelocityFvPatchVectorField.C