OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
rotatingWallVelocityFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary ConditionsBoundary Conditions » | Generic boundary Conditions
This boundary condition provides a rotational velocity condition.
Public Member Functions
TypeName ("rotatingWallVelocity")
Runtime type information.
rotatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
rotatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given rotatingWallVelocityFvPatchVectorField.
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const vector & origin () const
Return the origin of the rotation.
const vector & axis () const
Return the axis of the rotation.
vector & origin ()
Return non-const access to the origin of the rotation.
vector & axis ()
Return non-const access to the axis of the rotation.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a rotational velocity condition.
Patch usage
Property Description Required Default value
origin origin of rotation in Cartesian co-ordinates yes
axis axis of rotation yes
omega angular velocty of the frame [rad/s] yes
Example of the boundary condition specification:
    myPatch
    {
        type            rotatingWallVelocity;
        origin          (0 0 0);
        axis            (0 0 1);
        omega           100;
    }
The omega entry is a DataEntry type, able to describe time varying functions.
See also
Foam::DataEntry Foam::fixedValueFvPatchField
Source files
rotatingWallVelocityFvPatchVectorField.H
rotatingWallVelocityFvPatchVectorField.C
Definition at line 99 of file rotatingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
rotatingWallVelocityFvPatchVectorField() [1/5]
rotatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file rotatingWallVelocityFvPatchVectorField.C.
Referenced by rotatingWallVelocityFvPatchVectorField::clone(), and rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField().
rotatingWallVelocityFvPatchVectorField() [2/5]
rotatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 65 of file rotatingWallVelocityFvPatchVectorField.C.
References dictionary::found(), rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField(), List< Type >::size(), and vectorField().
rotatingWallVelocityFvPatchVectorField() [3/5]
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given rotatingWallVelocityFvPatchVectorField.
onto a new patch
Definition at line 49 of file rotatingWallVelocityFvPatchVectorField.C.
References rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField().
rotatingWallVelocityFvPatchVectorField() [4/5]
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField & rwvpvf)
Construct as copy.
Definition at line 93 of file rotatingWallVelocityFvPatchVectorField.C.
References rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField().
rotatingWallVelocityFvPatchVectorField() [5/5]
rotatingWallVelocityFvPatchVectorField (const rotatingWallVelocityFvPatchVectorField & rwvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 106 of file rotatingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("rotatingWallVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 155 of file rotatingWallVelocityFvPatchVectorField.H.
References rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 172 of file rotatingWallVelocityFvPatchVectorField.H.
References rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField().
origin() [1/2]
const vector& origin () const inline
Return the origin of the rotation.
Definition at line 189 of file rotatingWallVelocityFvPatchVectorField.H.
axis() [1/2]
const vector& axis () const inline
Return the axis of the rotation.
Definition at line 195 of file rotatingWallVelocityFvPatchVectorField.H.
origin() [2/2]
vector& origin () inline
Return non-const access to the origin of the rotation.
Definition at line 201 of file rotatingWallVelocityFvPatchVectorField.H.
axis() [2/2]
vector& axis () inline
Return non-const access to the axis of the rotation.
Definition at line 207 of file rotatingWallVelocityFvPatchVectorField.H.
References rotatingWallVelocityFvPatchVectorField::updateCoeffs(), and rotatingWallVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 120 of file rotatingWallVelocityFvPatchVectorField.C.
References Foam::mag(), n, and Field< vector >::operator=().
Referenced by rotatingWallVelocityFvPatchVectorField::axis().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 145 of file rotatingWallVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by rotatingWallVelocityFvPatchVectorField::axis().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/rotatingWallVelocity/rotatingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/rotatingWallVelocity/rotatingWallVelocityFvPatchVectorField.C