OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvPatchField< Type > Class Template Reference
Abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
Public Types
typedef fvPatch Patch
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=false)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
virtual tmp< fvPatchField< Type > > clone () const
Construct and return a clone.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~fvPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient for coupled-patches.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void updateCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > patchNeighbourField () const
Return patchField on the opposite patch of a coupled patch.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field, sets Updated to false.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< Field< scalar > > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< Field< scalar > > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
virtual void write (Ostream &) const
Write.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type > > &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reUse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type > > &)
Construct by transferring the Field contents.
Field (Istream &)
Construct as copy of tmp<Field>
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType > > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const Type &)
template<class Form , class Cmpt , int nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type > > &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Friends
Ostream & operator (Ostream &, const fvPatchField< Type > &)
Additional Inherited Members
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::fvPatchField< Type >
Abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
The first level of derivation is to basic patchFields which cover zero-gradient, fixed-gradient, fixed-value and mixed conditions.
The next level of derivation covers all the specialised types with specific evaluation proceedures, particularly with respect to specific fields.
Source files
fvPatchField.H
fvPatchField.C
fvPatchFieldNew.C
Definition at line 65 of file fvPatchField.H.
Member Typedef Documentation
Patch
typedef fvPatch Patch
Definition at line 107 of file fvPatchField.H.
Constructor & Destructor Documentation
fvPatchField() [1/7]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fvPatchField.C.
Referenced by fvPatchField< Type >::clone(), and fvPatchField< Type >::fvPatchField().
fvPatchField() [2/7]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const word & patchType)
Construct from patch and internal field and patch type.
Definition at line 52 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [3/7]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const Field< Type > & f)
Construct from patch and internal field and patch field.
Definition at line 69 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [4/7]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict, const bool valueRequired = false)
Construct from patch, internal field and dictionary.
Definition at line 111 of file fvPatchField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::found(), fvPatchField< Type >::fvPatchField(), and fvPatch::size().
fvPatchField() [5/7]
fvPatchField (const fvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given fvPatchField onto a new patch.
Definition at line 86 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField(), and List< Type >::size().
fvPatchField() [6/7]
fvPatchField (const fvPatchField< Type > & ptf)
Construct as copy.
Definition at line 156 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [7/7]
fvPatchField (const fvPatchField< Type > & ptf, const DimensionedField< Type, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 171 of file fvPatchField.C.
~fvPatchField()
virtual ~fvPatchField () inline virtual
Destructor.
Definition at line 288 of file fvPatchField.H.
References fvPatchField< Type >::db().
Member Function Documentation
TypeName()
TypeName ("fvPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (tmp , fvPatchField< Type > , patch , (const fvPatch &p, const DimensionedField< Type, volMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (tmp , fvPatchField< Type > , patchMapper , (const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m) , (dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (tmp , fvPatchField< Type > , dictionary , (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
virtual tmp<fvPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented in externalCoupledMixedFvPatchField< Type >, externalCoupledMixedFvPatchField< scalar >, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, porousBafflePressureFvPatchField< Type >, oscillatingFixedValueFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, externalCoupledTemperatureMixedFvPatchScalarField, porousBafflePressureFvPatchField< Type >, codedMixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, waveTransmissiveFvPatchField< Type >, codedFixedValueFvPatchField< Type >, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, advectiveFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, mappedFieldFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, epsilonLowReWallFunctionFvPatchScalarField, epsilonLowReWallFunctionFvPatchScalarField, epsilonLowReWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fanFvPatchField< Type >, fixedGradientFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, inletOutletFvPatchField< Type >, outletInletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, fixedJumpAMIFvPatchField< scalar >, fixedJumpFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, fixedJumpFvPatchField< scalar >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, processorFvPatchField< Type >, fixedMeanFvPatchField< Type >, freestreamFvPatchField< Type >, partialSlipFvPatchField< Type >, cyclicAMIFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicACMIFvPatchField< Type >, fixedValueFvPatchField< Type >, processorCyclicFvPatchField< Type >, fixedValueFvPatchField< scalar >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, fixedInternalValueFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, slicedFvPatchField< Type >, cyclicSlipFvPatchField< Type >, wedgeFvPatchField< Type >, calculatedFvPatchField< Type >, emptyFvPatchField< Type >, symmetryFvPatchField< Type >, genericFvPatchField< Type >, surfaceSlipDisplacementFvPatchField< Type >, zeroGradientFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, slipFvPatchField< Type >, nonuniformTransformCyclicFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, energyJumpFvPatchScalarField, energyJumpAMIFvPatchScalarField, transformFvPatchField< Type >, cellMotionFvPatchField< Type >, and basicSymmetryFvPatchField< Type >.
Definition at line 206 of file fvPatchField.H.
References fvPatchField< Type >::fvPatchField().
clone() [2/2]
virtual tmp<fvPatchField<Type> > clone (const DimensionedField< Type, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in externalCoupledMixedFvPatchField< Type >, oscillatingFixedValueFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, codedMixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, waveTransmissiveFvPatchField< Type >, codedFixedValueFvPatchField< Type >, mappedFieldFvPatchField< Type >, mixedFvPatchField< Type >, advectiveFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, fanFvPatchField< Type >, fixedGradientFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, inletOutletFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, outletInletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, fixedJumpFvPatchField< Type >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, processorFvPatchField< Type >, fixedMeanFvPatchField< Type >, freestreamFvPatchField< Type >, partialSlipFvPatchField< Type >, cyclicAMIFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicACMIFvPatchField< Type >, fixedValueFvPatchField< Type >, processorCyclicFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, fixedInternalValueFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, surfaceSlipDisplacementFvPatchField< Type >, cyclicSlipFvPatchField< Type >, wedgeFvPatchField< Type >, calculatedFvPatchField< Type >, emptyFvPatchField< Type >, symmetryFvPatchField< Type >, genericFvPatchField< Type >, zeroGradientFvPatchField< Type >, slipFvPatchField< Type >, slicedFvPatchField< Type >, nonuniformTransformCyclicFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, coupledFvPatchField< Type >, cellMotionFvPatchField< Type >, basicSymmetryFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 220 of file fvPatchField.H.
References fvPatchField< Type >::New(), and fvPatchField< Type >::NewCalculatedType().
New() [1/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const word & patchFieldType, const fvPatch & p, const DimensionedField< Type, volMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 97 of file fvPatchFieldNew.C.
Referenced by fvPatchField< Type >::clone(), nearWallDist::correct(), and fvPatchField< Type >::New().
New() [2/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const fvPatch & p, const DimensionedField< Type, volMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values). Allows override of constraint type
Definition at line 30 of file fvPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, fvPatchField< Type >::New(), Foam::nl, and p.
New() [3/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const fvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given fvPatchField mapped onto a new patch
Definition at line 185 of file fvPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, Foam::nl, and p.
New() [4/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 109 of file fvPatchFieldNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::found(), Foam::Info, dictionary::lookup(), fvPatchField< Type >::New(), Foam::nl, and p.
NewCalculatedType() [1/3]
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatch & p) static
Return a pointer to a new calculatedFvPatchField created on.
freestore without setting patchField values
Definition at line 101 of file calculatedFvPatchField.C.
References p.
Referenced by calculatedFvPatchField< Type >::calculatedFvPatchField(), and fvPatchField< Type >::clone().
NewCalculatedType() [2/3]
static tmp<fvPatchField<Type> > NewCalculatedType (const fvPatchField< Type2 > &) static
Return a pointer to a new calculatedFvPatchField created on.
freestore without setting patchField values
db()
const Foam::objectRegistry & db () const
Return local objectRegistry.
Definition at line 188 of file fvPatchField.C.
Referenced by basicThermo::lookupThermo(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), and fvPatchField< Type >::~fvPatchField().
patch()
const fvPatch& patch () const inline
Return patch.
Definition at line 300 of file fvPatchField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), fWallFunctionFvPatchScalarField::checkType(), v2WallFunctionFvPatchScalarField::checkType(), kLowReWallFunctionFvPatchScalarField::checkType(), epsilonWallFunctionFvPatchScalarField::checkType(), omegaWallFunctionFvPatchScalarField::checkType(), extendedCellToFaceStencil::collectData(), contactAngleForce::correct(), epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::G(), omegaWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), mappedPatchFieldBase< Type >::mappedField(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvPatchField< Type >::NewCalculatedType(), omegaWallFunctionFvPatchScalarField::omega(), fvPatchField< Type >::operator*=(), fvPatchField< Type >::operator/=(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), and regionSizeDistribution::write().
dimensionedInternalField()
const DimensionedField<Type, volMesh>& dimensionedInternalField () const inline
Return dimensioned internal field reference.
Definition at line 307 of file fvPatchField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), basicThermo::lookupThermo(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::omegaPatch(), epsilonWallFunctionFvPatchScalarField::setMaster(), omegaWallFunctionFvPatchScalarField::setMaster(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
internalField()
const Field<Type>& internalField () const inline
Return internal field reference.
Definition at line 313 of file fvPatchField.H.
patchType() [1/2]
const word& patchType () const inline
Optional patch type.
Definition at line 319 of file fvPatchField.H.
Referenced by uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField().
patchType() [2/2]
word& patchType () inline
Optional patch type.
Definition at line 325 of file fvPatchField.H.
References fvPatchField< Type >::calculatedType(), and fvPatchField< Type >::fixesValue().
calculatedType()
const Foam::word & calculatedType () static
Return the type of the calculated for of fvPatchField.
Definition at line 32 of file calculatedFvPatchField.C.
References calculatedFvPatchField< Type >::calculatedFvPatchField().
Referenced by fvPatchField< Type >::patchType().
fixesValue()
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Needed to check if a level has to be specified while solving Poissons equations.
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, calculatedFvPatchField< Type >, slicedFvPatchField< Type >, and directionMixedFvPatchField< Type >.
Definition at line 336 of file fvPatchField.H.
Referenced by Foam::adjustPhi(), faceMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), temperatureLimitsConstraint::correct(), and fvPatchField< Type >::patchType().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicACMIFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 342 of file fvPatchField.H.
Referenced by fvMatrix< Type >::addBoundarySource(), cellLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), fvMatrix< Type >::DD(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), fvMatrix< Type >::H1(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), fvMatrix< Type >::relax(), snGradScheme< Type >::snGrad(), and regionSizeDistribution::write().
updated()
bool updated () const inline
Return true if the boundary condition has already been updated.
Definition at line 348 of file fvPatchField.H.
Referenced by cyclicACMIFvPatchField< Type >::initEvaluate(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
manipulatedMatrix()
bool manipulatedMatrix () const inline
Return true if the matrix has already been manipulated.
Definition at line 354 of file fvPatchField.H.
References fvPatchField< Type >::autoMap(), fvPatchField< Type >::rmap(), and fvPatchField< Type >::snGrad().
Referenced by epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), and omegaWallFunctionFvPatchScalarField::manipulateMatrix().
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in oscillatingFixedValueFvPatchField< Type >, mixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, mixedFvPatchField< scalar >, timeVaryingMappedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, fixedJumpFvPatchField< Type >, fixedJumpFvPatchField< scalar >, uniformInletOutletFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, directionMixedFvPatchField< Type >, emptyFvPatchField< Type >, genericFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 230 of file fvPatchField.C.
References FieldMapper::addressing(), FieldMapper::direct(), FieldMapper::directAddressing(), forAll, fvPatchField< Type >::rmap(), List< Type >::setSize(), FieldMapper::size(), List< Type >::size(), List< T >::size(), and UList< T >::size().
Referenced by fixedGradientFvPatchField< Type >::autoMap(), timeVaryingMappedFixedValueFvPatchField< Type >::autoMap(), mixedFvPatchField< scalar >::autoMap(), turbulentInletFvPatchField< Type >::autoMap(), oscillatingFixedValueFvPatchField< Type >::autoMap(), fvPatchField< Type >::manipulatedMatrix(), and fvPatchField< Type >::patchInternalField().
rmap()
void rmap (const fvPatchField< Type > & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Reimplemented in oscillatingFixedValueFvPatchField< Type >, mixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, fixedJumpFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, emptyFvPatchField< Type >, genericFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 291 of file fvPatchField.C.
Referenced by fvPatchField< Type >::autoMap(), fvPatchField< Type >::manipulatedMatrix(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fixedGradientFvPatchField< Type >::rmap(), timeVaryingMappedFixedValueFvPatchField< Type >::rmap(), mixedFvPatchField< scalar >::rmap(), turbulentInletFvPatchField< Type >::rmap(), and oscillatingFixedValueFvPatchField< Type >::rmap().
snGrad() [1/2]
Foam::tmp< Foam::Field< Type > > snGrad () const virtual
Return patch-normal gradient.
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, fixedGradientFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, directionMixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, wedgeFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, coupledFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< scalar >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, zeroGradientFvPatchField< Type >, basicSymmetryFvPatchField< Type >, transformFvPatchField< Type >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, and symmetryPlaneFvPatchField< Type >.
Definition at line 207 of file fvPatchField.C.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), thermalBaffle::info(), fvPatchField< Type >::manipulatedMatrix(), snGradScheme< Type >::snGrad(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs(), gradientEnergyFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutLowReWallFunctionFvPatchScalarField::yPlus(), mutkFilmWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and mutUSpaldingWallFunctionFvPatchScalarField::yPlus().
snGrad() [2/2]
virtual tmp<Field<Type> > snGrad (const scalarField & deltaCoeffs) const inline virtual
Return patch-normal gradient for coupled-patches.
using the deltaCoeffs provided
Reimplemented in cyclicACMIFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, processorFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 384 of file fvPatchField.H.
References notImplemented, fvPatchField< Type >::patchInternalField(), Foam::type(), and fvPatchField< Type >::updateCoeffs().
updateCoeffs() [1/2]
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Sets Updated to true
Reimplemented in oscillatingFixedValueFvPatchField< Type >, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, timeVaryingMappedFixedValueFvPatchField< Type >, turbulentInletFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, advectiveFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, codedMixedFvPatchField< Type >, cyclicACMIFvPatchField< Type >, codedFixedValueFvPatchField< Type >, mappedFieldFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, uniformInletOutletFvPatchField< Type >, fWallFunctionFvPatchScalarField, fanFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, inletOutletFvPatchField< Type >, outletInletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, fixedMeanFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, emptyFvPatchField< Type >, slicedFvPatchField< Type >, energyJumpFvPatchScalarField, energyJumpAMIFvPatchScalarField, and cellMotionFvPatchField< Type >.
Definition at line 301 of file fvPatchField.C.
Referenced by fvPatchField< Type >::snGrad(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fixedMeanFvPatchField< Type >::updateCoeffs(), uniformFixedValueFvPatchField< Type >::updateCoeffs(), uniformFixedGradientFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), surfaceNormalFixedValueFvPatchVectorField::updateCoeffs(), outletPhaseMeanVelocityFvPatchVectorField::updateCoeffs(), fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), cylindricalInletVelocityFvPatchVectorField::updateCoeffs(), mappedFixedValueFvPatchField< Type >::updateCoeffs(), mappedFieldFvPatchField< Type >::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), turbulentInletFvPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), and oscillatingFixedValueFvPatchField< Type >::updateCoeffs().
updateCoeffs() [2/2]
void updateCoeffs (const scalarField & weights) virtual
Update the coefficients associated with the patch field.
and apply weight field Sets Updated to true
Reimplemented in omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, and epsilonWallFunctionFvPatchScalarField.
Definition at line 308 of file fvPatchField.C.
References fld().
patchInternalField() [1/2]
Foam::tmp< Foam::Field< Type > > patchInternalField () const virtual
Return internal field next to patch as patch field.
Reimplemented in slicedFvPatchField< Type >.
Definition at line 215 of file fvPatchField.C.
Referenced by isoSurface::adaptPatchFields(), mutURoughWallFunctionFvPatchScalarField::calcMut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), fvPatchField< Type >::snGrad(), dynamicAlphaContactAngleFvPatchScalarField::theta(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), regionSizeDistribution::write(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
patchInternalField() [2/2]
void patchInternalField (Field< Type > & pif) const virtual
Return internal field next to patch as patch field.
Reimplemented in slicedFvPatchField< Type >.
Definition at line 222 of file fvPatchField.C.
References fvPatchField< Type >::autoMap().
patchNeighbourField()
virtual tmp<Field<Type> > patchNeighbourField () const inline virtual
Return patchField on the opposite patch of a coupled patch.
Reimplemented in energyRegionCoupledFvPatchScalarField, cyclicACMIFvPatchField< Type >, processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Definition at line 411 of file fvPatchField.H.
References fvPatchField< Type >::initEvaluate(), notImplemented, and Foam::type().
Referenced by isoSurface::adaptPatchFields(), fvMatrix< Type >::addBoundarySource(), cellLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), and regionSizeDistribution::write().
initEvaluate()
virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::blocking) inline virtual
Initialise the evaluation of the patch field.
Reimplemented in cyclicACMIFvPatchField< Type >, processorFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 419 of file fvPatchField.H.
References UPstream::blocking, fvPatchField< Type >::evaluate(), and fvPatchField< Type >::valueInternalCoeffs().
Referenced by fvPatchField< Type >::patchNeighbourField().
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field, sets Updated to false.
Reimplemented in externalCoupledMixedFvPatchField< Type >, externalCoupledMixedFvPatchField< scalar >, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, externalCoupledTemperatureMixedFvPatchScalarField, codedMixedFvPatchField< Type >, cyclicACMIFvPatchField< Type >, codedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, energyRegionCoupledFvPatchScalarField, v2WallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, directionMixedFvPatchField< Type >, processorFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, coupledFvPatchField< Type >, wedgeFvPatchField< Type >, coupledFvPatchField< scalar >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, zeroGradientFvPatchField< Type >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, basicSymmetryFvPatchField< Type >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, and symmetryPlaneFvPatchField< Type >.
Definition at line 323 of file fvPatchField.C.
Referenced by zeroGradientFvPatchField< Type >::evaluate(), fWallFunctionFvPatchScalarField::evaluate(), v2WallFunctionFvPatchScalarField::evaluate(), energyRegionCoupledFvPatchScalarField::evaluate(), kLowReWallFunctionFvPatchScalarField::evaluate(), fixedGradientFvPatchField< Type >::evaluate(), mixedFvPatchField< scalar >::evaluate(), cyclicACMIFvPatchField< Type >::initEvaluate(), fvPatchField< Type >::initEvaluate(), gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs(), fixedUnburntEnthalpyFvPatchScalarField::updateCoeffs(), fixedEnergyFvPatchScalarField::updateCoeffs(), and gradientEnergyFvPatchScalarField::updateCoeffs().
valueInternalCoeffs()
virtual tmp<Field<Type> > valueInternalCoeffs (const tmp< Field< scalar > > &) const inline virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, fixedGradientFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, emptyFvPatchField< Type >, genericFvPatchField< Type >, zeroGradientFvPatchField< Type >, calculatedFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 434 of file fvPatchField.H.
References notImplemented, Foam::type(), and fvPatchField< Type >::valueBoundaryCoeffs().
Referenced by gaussConvectionScheme< Type >::fvmDiv(), and fvPatchField< Type >::initEvaluate().
valueBoundaryCoeffs()
virtual tmp<Field<Type> > valueBoundaryCoeffs (const tmp< Field< scalar > > &) const inline virtual
Return the matrix source coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, fixedGradientFvPatchField< Type >, slicedFvPatchField< Type >, emptyFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, genericFvPatchField< Type >, zeroGradientFvPatchField< Type >, calculatedFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 449 of file fvPatchField.H.
References fvPatchField< Type >::gradientInternalCoeffs(), notImplemented, and Foam::type().
Referenced by gaussConvectionScheme< Type >::fvmDiv(), and fvPatchField< Type >::valueInternalCoeffs().
gradientInternalCoeffs() [1/2]
virtual tmp<Field<Type> > gradientInternalCoeffs () const inline virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, fixedGradientFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, emptyFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, genericFvPatchField< Type >, zeroGradientFvPatchField< Type >, calculatedFvPatchField< Type >, transformFvPatchField< Type >, transformFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 463 of file fvPatchField.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and fvPatchField< Type >::valueBoundaryCoeffs().
gradientInternalCoeffs() [2/2]
virtual tmp<Field<Type> > gradientInternalCoeffs (const scalarField & deltaCoeffs) const inline virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this coupled patchField using the deltaCoeffs provided
Reimplemented in cyclicACMIFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 473 of file fvPatchField.H.
References fvPatchField< Type >::gradientBoundaryCoeffs(), notImplemented, and Foam::type().
gradientBoundaryCoeffs() [1/2]
virtual tmp<Field<Type> > gradientBoundaryCoeffs () const inline virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, fixedGradientFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, emptyFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, genericFvPatchField< Type >, zeroGradientFvPatchField< Type >, calculatedFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 487 of file fvPatchField.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and fvPatchField< Type >::gradientInternalCoeffs().
gradientBoundaryCoeffs() [2/2]
virtual tmp<Field<Type> > gradientBoundaryCoeffs (const scalarField & deltaCoeffs) const inline virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this coupled patchField using the deltaCoeffs provided
Reimplemented in cyclicACMIFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 497 of file fvPatchField.H.
References fvPatchField< Type >::check(), fvPatchField< Type >::manipulateMatrix(), notImplemented, fvPatchField< Type >::operator*=(), fvPatchField< Type >::operator+=(), fvPatchField< Type >::operator-=(), fvPatchField< Type >::operator/=(), fvPatchField< Type >::operator=(), fvPatchField< Type >::operator==(), Foam::type(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeEntryIfDifferent().
manipulateMatrix() [1/2]
void manipulateMatrix (fvMatrix< Type > & matrix) virtual
Manipulate matrix.
Reimplemented in cyclicACMIFvPatchField< Type >, and fixedInternalValueFvPatchField< Type >.
Definition at line 336 of file fvPatchField.C.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), and omegaWallFunctionFvPatchScalarField::manipulateMatrix().
manipulateMatrix() [2/2]
void manipulateMatrix (fvMatrix< Type > & matrix, const scalarField & weights) virtual
Manipulate matrix with given weights.
Definition at line 344 of file fvPatchField.C.
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in externalCoupledMixedFvPatchField< Type >, externalCoupledMixedFvPatchField< scalar >, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, omegaWallFunctionFvPatchScalarField, cyclicACMIFvPatchField< Type >, oscillatingFixedValueFvPatchField< Type >, mixedFvPatchField< Type >, epsilonWallFunctionFvPatchScalarField, mixedFvPatchField< scalar >, epsilonWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, timeVaryingMappedFixedValueFvPatchField< Type >, turbulentInletFvPatchField< Type >, externalCoupledTemperatureMixedFvPatchScalarField, porousBafflePressureFvPatchField< Type >, fixedGradientFvPatchField< Type >, advectiveFvPatchField< Type >, codedMixedFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, waveTransmissiveFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, codedFixedValueFvPatchField< Type >, cyclicAMIFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, cyclicFvPatchField< Type >, mappedFieldFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, mappedFixedValueFvPatchField< Type >, v2WallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, directionMixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, fixedJumpFvPatchField< Type >, fixedJumpFvPatchField< scalar >, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, mappedFixedPushedInternalValueFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, outletMappedUniformInletFvPatchField< Type >, inletOutletFvPatchField< Type >, outletInletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, genericFvPatchField< Type >, freestreamFvPatchField< Type >, calculatedFvPatchField< Type >, fixedMeanFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, surfaceSlipDisplacementFvPatchField< Type >, energyJumpFvPatchScalarField, energyJumpAMIFvPatchScalarField, and cellMotionFvPatchField< Type >.
Definition at line 354 of file fvPatchField.C.
References Foam::nl, Foam::type(), fvPatchField< Type >::writeEntryIfDifferent(), and Ostream::writeKeyword().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs(), fvPatchField< Type >::operator==(), surfaceSlipDisplacementFvPatchField< Type >::write(), inclinedFilmNusseltInletVelocityFvPatchVectorField::write(), kqRWallFunctionFvPatchField< Type >::write(), mutUWallFunctionFvPatchScalarField::write(), nutUWallFunctionFvPatchScalarField::write(), atmBoundaryLayerInletEpsilonFvPatchScalarField::write(), atmBoundaryLayerInletKFvPatchScalarField::write(), atmBoundaryLayerInletVelocityFvPatchVectorField::write(), interstitialInletVelocityFvPatchVectorField::write(), alphaFixedPressureFvPatchScalarField::write(), mutWallFunctionFvPatchScalarField::write(), nutWallFunctionFvPatchScalarField::write(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::write(), movingWallVelocityFvPatchVectorField::write(), fixedMeanFvPatchField< Type >::write(), translatingWallVelocityFvPatchVectorField::write(), mutkFilmWallFunctionFvPatchScalarField::write(), freestreamFvPatchField< Type >::write(), mappedVelocityFluxFixedValueFvPatchField::write(), uniformFixedValueFvPatchField< Type >::write(), filmPyrolysisVelocityCoupledFvPatchVectorField::write(), filmPyrolysisTemperatureCoupledFvPatchScalarField::write(), mutUSpaldingWallFunctionFvPatchScalarField::write(), nutUSpaldingWallFunctionFvPatchScalarField::write(), pressureInletVelocityFvPatchVectorField::write(), mappedFlowRateFvPatchVectorField::write(), fixedValueFvPatchField< scalar >::write(), surfaceNormalFixedValueFvPatchVectorField::write(), nutUTabulatedWallFunctionFvPatchScalarField::write(), variableHeightFlowRateFvPatchScalarField::write(), outletPhaseMeanVelocityFvPatchVectorField::write(), rotatingPressureInletOutletVelocityFvPatchVectorField::write(), mutkRoughWallFunctionFvPatchScalarField::write(), slicedFvPatchField< Type >::write(), swirlFlowRateInletVelocityFvPatchVectorField::write(), fixedPressureCompressibleDensityFvPatchScalarField::write(), alphatWallFunctionFvPatchScalarField::write(), cylindricalInletVelocityFvPatchVectorField::write(), convectiveHeatTransferFvPatchScalarField::write(), turbulentIntensityKineticEnergyInletFvPatchScalarField::write(), mappedFixedValueFvPatchField< Type >::write(), fluxCorrectedVelocityFvPatchVectorField::write(), rotatingWallVelocityFvPatchVectorField::write(), kLowReWallFunctionFvPatchScalarField::write(), wallHeatTransferFvPatchScalarField::write(), alphatFilmWallFunctionFvPatchScalarField::write(), pressureNormalInletOutletVelocityFvPatchVectorField::write(), pressureInletOutletParSlipVelocityFvPatchVectorField::write(), flowRateInletVelocityFvPatchVectorField::write(), nutkRoughWallFunctionFvPatchScalarField::write(), mappedFieldFvPatchField< Type >::write(), turbulentMixingLengthFrequencyInletFvPatchScalarField::write(), pressureInletOutletVelocityFvPatchVectorField::write(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::write(), SRFFreestreamVelocityFvPatchVectorField::write(), cyclicFvPatchField< Type >::write(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), totalTemperatureFvPatchScalarField::write(), waveSurfacePressureFvPatchScalarField::write(), pressureDirectedInletVelocityFvPatchVectorField::write(), SRFVelocityFvPatchVectorField::write(), inletOutletTotalTemperatureFvPatchScalarField::write(), energyRegionCoupledFvPatchScalarField::write(), pressureDirectedInletOutletVelocityFvPatchVectorField::write(), nutURoughWallFunctionFvPatchScalarField::write(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), fixedGradientFvPatchField< Type >::write(), prghPressureFvPatchScalarField::write(), uniformTotalPressureFvPatchScalarField::write(), uniformDensityHydrostaticPressureFvPatchScalarField::write(), filmHeightInletVelocityFvPatchVectorField::write(), supersonicFreestreamFvPatchVectorField::write(), syringePressureFvPatchScalarField::write(), turbulentInletFvPatchField< Type >::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), phaseHydrostaticPressureFvPatchScalarField::write(), mixedFvPatchField< scalar >::write(), and totalPressureFvPatchScalarField::write().
writeEntryIfDifferent()
void writeEntryIfDifferent (Ostream & os, const word & entryName, const EntryType & value1, const EntryType & value2) const
Helper function to write the keyword and entry only if the.
values are not equal. The value is then output as value2
Definition at line 369 of file fvPatchField.C.
References Foam::nl, and Ostream::writeKeyword().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs(), and fvPatchField< Type >::write().
check()
void check (const fvPatchField< Type > & ptf) const
Check fvPatchField<Type> against given fvPatchField<Type>
Definition at line 195 of file fvPatchField.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator=() [1/3]
void operator= (const UList< Type > & ul) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 387 of file fvPatchField.C.
Referenced by alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), freestreamFvPatchField< Type >::freestreamFvPatchField(), fvPatchField< Type >::gradientBoundaryCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), pressureInletVelocityFvPatchVectorField::operator=(), pressureInletOutletParSlipVelocityFvPatchVectorField::operator=(), pressureInletOutletVelocityFvPatchVectorField::operator=(), pressureDirectedInletVelocityFvPatchVectorField::operator=(), fixedNormalInletOutletVelocityFvPatchVectorField::operator=(), filmHeightInletVelocityFvPatchVectorField::operator=(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField(), turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), surfaceNormalFixedValueFvPatchVectorField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField(), and zeroGradientFvPatchField< Type >::zeroGradientFvPatchField().
operator=() [2/3]
void operator= (const fvPatchField< Type > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, fixedValueFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, inletOutletFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 397 of file fvPatchField.C.
operator+=() [1/3]
void operator+= (const fvPatchField< Type > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 408 of file fvPatchField.C.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator-=() [1/3]
void operator-= (const fvPatchField< Type > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 419 of file fvPatchField.C.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator*=() [1/3]
void operator*= (const fvPatchField< scalar > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 430 of file fvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and fvPatchField< Type >::patch().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator/=() [1/3]
void operator/= (const fvPatchField< scalar > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 449 of file fvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and fvPatchField< Type >::patch().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator+=() [2/3]
void operator+= (const Field< Type > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, directionMixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 468 of file fvPatchField.C.
References tf.
operator-=() [2/3]
void operator-= (const Field< Type > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, directionMixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 478 of file fvPatchField.C.
References tf.
operator*=() [2/3]
void operator*= (const Field< scalar > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 488 of file fvPatchField.C.
References tf.
operator/=() [2/3]
void operator/= (const Field< scalar > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 498 of file fvPatchField.C.
References tf.
operator=() [3/3]
void operator= (const Type & t) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 508 of file fvPatchField.C.
operator+=() [3/3]
void operator+= (const Type & t) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 518 of file fvPatchField.C.
operator-=() [3/3]
void operator-= (const Type & t) virtual
Reimplemented in mixedFvPatchField< Type >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 528 of file fvPatchField.C.
operator*=() [3/3]
void operator*= (const scalar s) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 538 of file fvPatchField.C.
References s().
operator/=() [3/3]
void operator/= (const scalar s) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, slicedFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 548 of file fvPatchField.C.
References s().
operator==() [1/3]
void operator== (const fvPatchField< Type > & ptf) virtual
Definition at line 559 of file fvPatchField.C.
Referenced by epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), zeroGradientFvPatchField< Type >::evaluate(), fvPatchField< Type >::gradientBoundaryCoeffs(), omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), timeVaryingMappedFixedValueFvPatchField< Type >::timeVaryingMappedFixedValueFvPatchField(), turbulentInletFvPatchField< Type >::turbulentInletFvPatchField(), uniformFixedValueFvPatchField< Type >::uniformFixedValueFvPatchField(), and uniformFixedValueFvPatchField< Type >::updateCoeffs().
operator==() [2/3]
void operator== (const Field< Type > & tf) virtual
Definition at line 569 of file fvPatchField.C.
References tf.
operator==() [3/3]
void operator== (const Type & t) virtual
Definition at line 579 of file fvPatchField.C.
References IOstream::check(), and fvPatchField< Type >::write().
NewCalculatedType() [3/3]
Foam::tmp<Foam::fvPatchField<Type> > NewCalculatedType (const fvPatchField< Type2 > & pf)
Definition at line 133 of file calculatedFvPatchField.C.
References fvPatchField< Type >::patch(), and calculatedFvPatchField< Type >::valueInternalCoeffs().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const fvPatchField< Type > &) friend
Referenced by fanFvPatchField< Type >::fanFvPatchField(), greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), phaseHydrostaticPressureFvPatchScalarField::operator=(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
Member Data Documentation
disallowGenericFvPatchField
int disallowGenericFvPatchField static
Debug switch to disallow the use of genericFvPatchField.
Definition at line 114 of file fvPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fields/fvPatchFields/basic/calculated/calculatedFvPatchField.C
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.C
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchFieldNew.C
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchFields.C