OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentIntensityKineticEnergyInletFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a turbulent kinetic energy condition, based on user-supplied turbulence intensity, defined as a fraction of the mean velocity:
Public Member Functions
TypeName ("turbulentIntensityKineticEnergyInlet")
Runtime type information.
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a turbulent kinetic energy condition, based on user-supplied turbulence intensity, defined as a fraction of the mean velocity:
where
= kinetic energy at the patch
= turbulence intensity
= velocity field
In the event of reverse flow, a zero-gradient condition is applied.
Patch usage
Property Description Required Default value
intensity fraction of mean field [0-1] yes
U velocity field name no U
phi flux field name no phi
Example of the boundary condition specification:
    myPatch
    {
        type        turbulentIntensityKineticEnergyInlet;
        intensity   0.05;           // 5% turbulence
        value       uniform 1;      // placeholder
    }
See also
Foam::inletOutletFvPatchField
Source files
turbulentIntensityKineticEnergyInletFvPatchScalarField.H
turbulentIntensityKineticEnergyInletFvPatchScalarField.C
Definition at line 121 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentIntensityKineticEnergyInletFvPatchScalarField() [1/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
Referenced by turbulentIntensityKineticEnergyInletFvPatchScalarField::clone(), and turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField().
turbulentIntensityKineticEnergyInletFvPatchScalarField() [2/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 66 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, dictionary::lookupOrDefault(), Foam::nl, scalarField(), fvPatch::size(), and turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField().
turbulentIntensityKineticEnergyInletFvPatchScalarField() [3/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentIntensityKineticEnergyInletFvPatchScalarField onto a new patch
Definition at line 52 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField().
turbulentIntensityKineticEnergyInletFvPatchScalarField() [4/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField & ptf)
Construct as copy.
Definition at line 107 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField().
turbulentIntensityKineticEnergyInletFvPatchScalarField() [5/5]
turbulentIntensityKineticEnergyInletFvPatchScalarField (const turbulentIntensityKineticEnergyInletFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 119 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References turbulentIntensityKineticEnergyInletFvPatchScalarField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("turbulentIntensityKineticEnergyInlet")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 175 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.H.
References turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 195 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.H.
References turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::updateCoeffs(), and turbulentIntensityKineticEnergyInletFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 133 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References Foam::magSqr(), Foam::pos(), Foam::sqr(), and turbulentIntensityKineticEnergyInletFvPatchScalarField::write().
Referenced by turbulentIntensityKineticEnergyInletFvPatchScalarField::clone(), and turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 154 of file turbulentIntensityKineticEnergyInletFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by turbulentIntensityKineticEnergyInletFvPatchScalarField::clone(), and turbulentIntensityKineticEnergyInletFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchScalarField.C