OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
variableHeightFlowRateFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a phase fraction condition based on the local flow conditions, whereby the values are constrained to lay between user-specified upper and lower bounds. The behaviour is described by:
Public Member Functions
TypeName ("variableHeightFlowRate")
Runtime scalar information.
variableHeightFlowRateFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
variableHeightFlowRateFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchField< scalar > > clone () const
Construct and return a clone.
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< scalar > > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
word phiName_
Name of flux field.
scalar lowerBound_
Lower bound for alpha1.
scalar upperBound_
Upper bound for alpha1.
Detailed Description
This boundary condition provides a phase fraction condition based on the local flow conditions, whereby the values are constrained to lay between user-specified upper and lower bounds. The behaviour is described by:
if alpha > upperBound:
apply a fixed value condition, with a uniform level of the upper bound
if lower bound <= alpha <= upper bound:
apply a zero-gradient condition
if alpha < lowerBound:
apply a fixed value condition, with a uniform level of the lower bound
Patch usage
Property Description Required Default value
phi flux field name no phi
lowerBound lower bound for clipping yes
upperBound upper bound for clipping yes
Example of the boundary condition specification:
    myPatch
    {
        type            variableHeightFlowRate;
        lowerBound      0.0;
        upperBound      0.9;
        value           uniform 0;
    }
Source files
variableHeightFlowRateFvPatchField.H
variableHeightFlowRateFvPatchScalarField.C
Definition at line 102 of file variableHeightFlowRateFvPatchField.H.
Constructor & Destructor Documentation
variableHeightFlowRateFvPatchScalarField() [1/5]
variableHeightFlowRateFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file variableHeightFlowRateFvPatchField.C.
Referenced by variableHeightFlowRateFvPatchScalarField::clone(), and variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField().
variableHeightFlowRateFvPatchScalarField() [2/5]
variableHeightFlowRateFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 70 of file variableHeightFlowRateFvPatchField.C.
References dictionary::found(), scalarField(), fvPatch::size(), and variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField().
variableHeightFlowRateFvPatchScalarField() [3/5]
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
variableHeightFlowRateFvPatchScalarField onto a new patch
Definition at line 54 of file variableHeightFlowRateFvPatchField.C.
References variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField().
variableHeightFlowRateFvPatchScalarField() [4/5]
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField & ptf)
Construct as copy.
Definition at line 102 of file variableHeightFlowRateFvPatchField.C.
References variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField().
variableHeightFlowRateFvPatchScalarField() [5/5]
variableHeightFlowRateFvPatchScalarField (const variableHeightFlowRateFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 115 of file variableHeightFlowRateFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("variableHeightFlowRate")
Runtime scalar information.
clone() [1/2]
virtual tmp<fvPatchField<scalar> > clone () const inline virtual
Construct and return a clone.
Definition at line 161 of file variableHeightFlowRateFvPatchField.H.
References variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchField<scalar> > clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 178 of file variableHeightFlowRateFvPatchField.H.
References variableHeightFlowRateFvPatchScalarField::updateCoeffs(), variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField(), and variableHeightFlowRateFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 129 of file variableHeightFlowRateFvPatchField.C.
References forAll, variableHeightFlowRateFvPatchScalarField::lowerBound_, variableHeightFlowRateFvPatchScalarField::phiName_, and variableHeightFlowRateFvPatchScalarField::upperBound_.
Referenced by variableHeightFlowRateFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 172 of file variableHeightFlowRateFvPatchField.C.
References token::END_STATEMENT, variableHeightFlowRateFvPatchScalarField::lowerBound_, Foam::makePatchTypeField(), Foam::nl, variableHeightFlowRateFvPatchScalarField::phiName_, variableHeightFlowRateFvPatchScalarField::upperBound_, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by variableHeightFlowRateFvPatchScalarField::clone().
Member Data Documentation
phiName_
word phiName_ protected
Name of flux field.
Definition at line 112 of file variableHeightFlowRateFvPatchField.H.
Referenced by variableHeightFlowRateFvPatchScalarField::updateCoeffs(), and variableHeightFlowRateFvPatchScalarField::write().
lowerBound_
scalar lowerBound_ protected
Lower bound for alpha1.
Definition at line 115 of file variableHeightFlowRateFvPatchField.H.
Referenced by variableHeightFlowRateFvPatchScalarField::updateCoeffs(), and variableHeightFlowRateFvPatchScalarField::write().
upperBound_
scalar upperBound_ protected
Upper bound for alpha1.
Definition at line 118 of file variableHeightFlowRateFvPatchField.H.
Referenced by variableHeightFlowRateFvPatchScalarField::updateCoeffs(), and variableHeightFlowRateFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRate/variableHeightFlowRateFvPatchField.H
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRate/variableHeightFlowRateFvPatchField.C