OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
variableHeightFlowRateInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a velocity boundary condition for multphase flow based on a user-specified volumetric flow rate.
Public Member Functions
TypeName ("variableHeightFlowRateInletVelocity")
Runtime type information.
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalar flowRate () const
Return the flux.
scalar & flowRate ()
Return reference to the flux to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity boundary condition for multphase flow based on a user-specified volumetric flow rate.
The flow rate is made proportional to the phase fraction alpha at each face of the patch and alpha is ensured to be bound between 0 and 1.
Patch usage
Property Description Required Default value
flowRate volumetric flow rate [m3/s] yes
alpha phase-fraction field yes
Example of the boundary condition specification:
    myPatch
    {
        type            variableHeightFlowRateInletVelocity;
        flowRate        0.2;
        alpha           alpha.water;
        value           uniform (0 0 0); // placeholder
    }
Note
the value is positive into the domain
may not work correctly for transonic inlets
strange behaviour with potentialFoam since the momentum equation is not solved
See also
Foam::fixedValueFvPatchField
Source files
variableHeightFlowRateInletVelocityFvPatchVectorField.H
variableHeightFlowRateInletVelocityFvPatchVectorField.C
Definition at line 97 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
variableHeightFlowRateInletVelocityFvPatchVectorField() [1/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
Referenced by variableHeightFlowRateInletVelocityFvPatchVectorField::clone(), and variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [2/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 64 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [3/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
variableHeightFlowRateInletVelocityFvPatchVectorField onto a new patch
Definition at line 49 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [4/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 78 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [5/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 90 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("variableHeightFlowRateInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 151 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 168 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
flowRate() [1/2]
scalar flowRate () const inline
Return the flux.
Definition at line 188 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
flowRate() [2/2]
scalar& flowRate () inline
Return reference to the flux to allow adjustment.
Definition at line 194 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
References variableHeightFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), and variableHeightFlowRateInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 104 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::max(), Foam::min(), n, Foam::operator==(), and variableHeightFlowRateInletVelocityFvPatchVectorField::write().
Referenced by variableHeightFlowRateInletVelocityFvPatchVectorField::flowRate(), and variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 129 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), Foam::nl, write(), and Ostream::writeKeyword().
Referenced by variableHeightFlowRateInletVelocityFvPatchVectorField::flowRate(), and variableHeightFlowRateInletVelocityFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRateInletVelocity/variableHeightFlowRateInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRateInletVelocity/variableHeightFlowRateInletVelocityFvPatchVectorField.C