OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
uniformTotalPressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This boundary condition provides a time-varying form of the uniform total pressure boundary condition.
Public Member Functions
TypeName ("uniformTotalPressure")
Runtime type information.
uniformTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
uniformTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given patch field onto a new patch.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & UName () const
Return the name of the velocity field.
word & UName ()
Return reference to the name of the velocity field.
scalar gamma () const
Return the heat capacity ratio.
scalar & gamma ()
Return reference to the heat capacity ratio to allow adjustment.
virtual void updateCoeffs (const vectorField &Up)
Update the coefficients associated with the patch field.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a time-varying form of the uniform total pressure boundary condition.
Patch usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
rho density field name no none
psi compressibility field name no none
gamma ratio of specific heats (Cp/Cv) yes
pressure total pressure as a function of time yes
Example of the boundary condition specification:
    myPatch
    {
        type            uniformTotalPressure;
        U               U;
        phi             phi;
        rho             rho;
        psi             psi;
        gamma           1.4;
        pressure        uniform 1e5;
    }
The pressure entry is specified as a DataEntry type, able to describe time varying functions.
Note
The default boundary behaviour is for subsonic, incompressible flow.
See also
Foam::DataEntry Foam::uniformFixedValueFvPatchField Foam::totalPressureFvPatchField
Source files
uniformTotalPressureFvPatchScalarField.H
uniformTotalPressureFvPatchScalarField.C
Definition at line 126 of file uniformTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
uniformTotalPressureFvPatchScalarField() [1/5]
uniformTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file uniformTotalPressureFvPatchScalarField.C.
Referenced by uniformTotalPressureFvPatchScalarField::clone(), and uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
uniformTotalPressureFvPatchScalarField() [2/5]
uniformTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 53 of file uniformTotalPressureFvPatchScalarField.C.
References dictionary::found(), scalarField(), fvPatch::size(), and uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
uniformTotalPressureFvPatchScalarField() [3/5]
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given patch field onto a new patch.
Definition at line 84 of file uniformTotalPressureFvPatchScalarField.C.
References Foam::operator==(), and uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
uniformTotalPressureFvPatchScalarField() [4/5]
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 107 of file uniformTotalPressureFvPatchScalarField.C.
References uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
uniformTotalPressureFvPatchScalarField() [5/5]
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 128 of file uniformTotalPressureFvPatchScalarField.C.
References uniformTotalPressureFvPatchScalarField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("uniformTotalPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 191 of file uniformTotalPressureFvPatchScalarField.H.
References uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 208 of file uniformTotalPressureFvPatchScalarField.H.
References uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
UName() [1/2]
const word& UName () const inline
Return the name of the velocity field.
Definition at line 224 of file uniformTotalPressureFvPatchScalarField.H.
UName() [2/2]
word& UName () inline
Return reference to the name of the velocity field.
to allow adjustment
Definition at line 231 of file uniformTotalPressureFvPatchScalarField.H.
gamma() [1/2]
scalar gamma () const inline
Return the heat capacity ratio.
Definition at line 237 of file uniformTotalPressureFvPatchScalarField.H.
gamma() [2/2]
scalar& gamma () inline
Return reference to the heat capacity ratio to allow adjustment.
Definition at line 243 of file uniformTotalPressureFvPatchScalarField.H.
References uniformTotalPressureFvPatchScalarField::updateCoeffs(), and uniformTotalPressureFvPatchScalarField::write().
updateCoeffs() [1/2]
void updateCoeffs (const vectorField & Up) virtual
Update the coefficients associated with the patch field.
using the given patch velocity field
Definition at line 151 of file uniformTotalPressureFvPatchScalarField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, magSqr(), Foam::operator==(), pos(), Foam::pow(), and rho.
updateCoeffs() [2/2]
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 218 of file uniformTotalPressureFvPatchScalarField.C.
Referenced by uniformTotalPressureFvPatchScalarField::gamma(), and uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 224 of file uniformTotalPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, and fvPatchField< Type >::write().
Referenced by uniformTotalPressureFvPatchScalarField::gamma().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/uniformTotalPressure/uniformTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/uniformTotalPressure/uniformTotalPressureFvPatchScalarField.C