OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
EulerD2dt2Scheme< Type > Class Template Reference
First-order Euler implicit d2dt2 using the current and two previous time-step values.
Public Member Functions
TypeName ("Euler")
Runtime type information.
EulerD2dt2Scheme (const fvMesh &mesh)
Construct from mesh.
EulerD2dt2Scheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from d2dt2Scheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, d2dt2Scheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
d2dt2Scheme (const fvMesh &mesh)
Construct from mesh.
d2dt2Scheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~d2dt2Scheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from d2dt2Scheme< Type >
static tmp< d2dt2Scheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new d2dt2Scheme created on freestore.
Protected Member Functions inherited from d2dt2Scheme< Type >
d2dt2Scheme (const d2dt2Scheme &)
Disallow copy construct.
void operator= (const d2dt2Scheme &)
Disallow default bitwise assignment.
Protected Attributes inherited from d2dt2Scheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::EulerD2dt2Scheme< Type >
First-order Euler implicit d2dt2 using the current and two previous time-step values.
Source files
EulerD2dt2Scheme.H
EulerD2dt2Scheme.C
Definition at line 55 of file EulerD2dt2Scheme.H.
Constructor & Destructor Documentation
EulerD2dt2Scheme() [1/2]
EulerD2dt2Scheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 77 of file EulerD2dt2Scheme.H.
EulerD2dt2Scheme() [2/2]
EulerD2dt2Scheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 83 of file EulerD2dt2Scheme.H.
Member Function Documentation
TypeName()
TypeName ("Euler")
Runtime type information.
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 92 of file EulerD2dt2Scheme.H.
References EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvmD2dt2(), and d2dt2Scheme< Type >::mesh().
fvcD2dt2() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 45 of file EulerD2dt2Scheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::oldTime(), Foam::sqr(), and dimensioned< Type >::value().
Referenced by EulerD2dt2Scheme< Type >::mesh().
fvcD2dt2() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 122 of file EulerD2dt2Scheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), EulerD2dt2Scheme< Type >::fvmD2dt2(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::oldTime(), Foam::sqr(), and dimensioned< Type >::value().
fvmD2dt2() [1/3]
tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 237 of file EulerD2dt2Scheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), fvMatrix< Type >::source(), and Foam::sqr().
Referenced by EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvmD2dt2(), and EulerD2dt2Scheme< Type >::mesh().
fvmD2dt2() [2/3]
tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 296 of file EulerD2dt2Scheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, EulerD2dt2Scheme< Type >::fvmD2dt2(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), fvMatrix< Type >::source(), Foam::sqr(), and dimensioned< Type >::value().
fvmD2dt2() [3/3]
tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 356 of file EulerD2dt2Scheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), fvMatrix< Type >::source(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/d2dt2Schemes/EulerD2dt2Scheme/EulerD2dt2Scheme.H
src/finiteVolume/finiteVolume/d2dt2Schemes/EulerD2dt2Scheme/EulerD2dt2Scheme.C