OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
EulerDdtScheme< Type > Class Template Reference
Basic first-order Euler implicit/explicit ddt using only the current and previous time-step values.
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("Euler")
Runtime type information.
EulerDdtScheme (const fvMesh &mesh)
Construct from mesh.
EulerDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::EulerDdtScheme< Type >
Basic first-order Euler implicit/explicit ddt using only the current and previous time-step values.
Source files
EulerDdtScheme.H
EulerDdtScheme.C
Definition at line 55 of file EulerDdtScheme.H.
Member Typedef Documentation
fluxFieldType
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 150 of file EulerDdtScheme.H.
Constructor & Destructor Documentation
EulerDdtScheme() [1/2]
EulerDdtScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 77 of file EulerDdtScheme.H.
EulerDdtScheme() [2/2]
EulerDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 83 of file EulerDdtScheme.H.
Member Function Documentation
TypeName()
TypeName ("Euler")
Runtime type information.
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 92 of file EulerDdtScheme.H.
References Foam::constant::atomic::alpha, EulerDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh(), psi, and rho.
fvcDdt() [1/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 46 of file EulerDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, mesh, dimensioned< Type >::name(), rDeltaT(), and dimensioned< Type >::value().
Referenced by EulerDdtScheme< Type >::fvcDdt(), and EulerDdtScheme< Type >::mesh().
fvcDdt() [2/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 105 of file EulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), EulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and dimensioned< Type >::value().
fvcDdt() [3/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 156 of file EulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), EulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and dimensioned< Type >::value().
fvcDdt() [4/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 208 of file EulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), EulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and dimensioned< Type >::value().
fvcDdt() [5/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 263 of file EulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), EulerDdtScheme< Type >::fvmDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and dimensioned< Type >::value().
fvmDdt() [1/4]
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 332 of file EulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
Referenced by EulerDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvmDdt(), and EulerDdtScheme< Type >::mesh().
fvmDdt() [2/4]
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 367 of file EulerDdtScheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, EulerDdtScheme< Type >::fvmDdt(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), fvMatrix< Type >::source(), and dimensioned< Type >::value().
fvmDdt() [3/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 404 of file EulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, EulerDdtScheme< Type >::fvmDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
fvmDdt() [4/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 443 of file EulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, EulerDdtScheme< Type >::fvcDdtUfCorr(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
fvcDdtUfCorr() [1/4]
tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 485 of file EulerDdtScheme.C.
References EulerDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
Referenced by EulerDdtScheme< Type >::fvcDdtPhiCorr(), and EulerDdtScheme< Type >::fvmDdt().
fvcDdtPhiCorr() [1/4]
tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 522 of file EulerDdtScheme.C.
References EulerDdtScheme< Type >::fvcDdtUfCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
Referenced by EulerDdtScheme< Type >::fvcDdtUfCorr().
fvcDdtUfCorr() [2/4]
tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 554 of file EulerDdtScheme.C.
References Foam::abort(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, EulerDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdtPhiCorr() [2/4]
tmp< typename EulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 623 of file EulerDdtScheme.C.
References Foam::abort(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, Foam::fvc::interpolate(), mesh, EulerDdtScheme< Type >::meshPhi(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
meshPhi()
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) virtual
Implements ddtScheme< Type >.
Definition at line 686 of file EulerDdtScheme.C.
References mesh.
Referenced by EulerDdtScheme< Type >::fvcDdtPhiCorr().
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/EulerDdtScheme/EulerDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/EulerDdtScheme/EulerDdtScheme.C