OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gaussConvectionScheme< Type > Class Template Reference
Basic second-order convection using face-gradients and Gauss' theorem.
Public Member Functions
TypeName ("Gauss")
Runtime type information.
gaussConvectionScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, const tmp< surfaceInterpolationScheme< Type > > &scheme)
Construct from flux and interpolation scheme.
gaussConvectionScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from flux and Istream.
const surfaceInterpolationScheme< Type > & interpScheme () const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from convectionScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
Copy construct.
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
Construct from mesh, flux and Istream.
virtual ~convectionScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from convectionScheme< Type >
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new convectionScheme created on freestore.
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new multivariate convectionScheme.
Detailed Description
template<class Type>
class Foam::fv::gaussConvectionScheme< Type >
Basic second-order convection using face-gradients and Gauss' theorem.
Source files
gaussConvectionScheme.H
gaussConvectionScheme.C
Definition at line 58 of file gaussConvectionScheme.H.
Constructor & Destructor Documentation
gaussConvectionScheme() [1/2]
gaussConvectionScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, const tmp< surfaceInterpolationScheme< Type > > & scheme) inline
Construct from flux and interpolation scheme.
Definition at line 86 of file gaussConvectionScheme.H.
gaussConvectionScheme() [2/2]
gaussConvectionScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from flux and Istream.
Definition at line 98 of file gaussConvectionScheme.H.
References Foam::endl(), Foam::findEtcFiles(), gaussConvectionScheme< Type >::flux(), gaussConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvmDiv(), gaussConvectionScheme< Type >::interpolate(), gaussConvectionScheme< Type >::interpScheme(), IOWarningIn, Istream::rewind(), and List< T >::size().
Member Function Documentation
TypeName()
TypeName ("Gauss")
Runtime type information.
interpScheme()
const surfaceInterpolationScheme< Type > & interpScheme () const
Definition at line 44 of file gaussConvectionScheme.C.
References gaussConvectionScheme< Type >::interpolate().
Referenced by blendingFactor::factor(), and gaussConvectionScheme< Type >::gaussConvectionScheme().
interpolate()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 53 of file gaussConvectionScheme.C.
References gaussConvectionScheme< Type >::flux().
Referenced by gaussConvectionScheme< Type >::gaussConvectionScheme(), multivariateGaussConvectionScheme< Type >::interpolate(), and gaussConvectionScheme< Type >::interpScheme().
flux()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 65 of file gaussConvectionScheme.C.
References gaussConvectionScheme< Type >::fvmDiv(), and Foam::interpolate().
Referenced by multivariateGaussConvectionScheme< Type >::flux(), gaussConvectionScheme< Type >::gaussConvectionScheme(), and gaussConvectionScheme< Type >::interpolate().
fvmDiv()
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 77 of file gaussConvectionScheme.C.
References fvMatrix< Type >::boundaryCoeffs(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::correction(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, gaussConvectionScheme< Type >::fvcDiv(), fvMatrix< Type >::internalCoeffs(), GeometricField< Type, PatchField, GeoMesh >::internalField(), lduMatrix::lower(), lduMatrix::negSumDiag(), Foam::fvc::surfaceIntegrate(), lduMatrix::upper(), fvPatchField< Type >::valueBoundaryCoeffs(), and fvPatchField< Type >::valueInternalCoeffs().
Referenced by gaussConvectionScheme< Type >::flux(), multivariateGaussConvectionScheme< Type >::fvmDiv(), and gaussConvectionScheme< Type >::gaussConvectionScheme().
fvcDiv()
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 121 of file gaussConvectionScheme.C.
References Foam::fvc::flux(), IOobject::name(), and Foam::fvc::surfaceIntegrate().
Referenced by multivariateGaussConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvmDiv(), and gaussConvectionScheme< Type >::gaussConvectionScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/gaussConvectionScheme/gaussConvectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/gaussConvectionScheme/gaussConvectionScheme.C