OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvsPatchField< Type > Class Template Reference
An abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
Public Types
typedef fvPatch Patch
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("fvsPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvsPatchField, patch,(const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvsPatchField, patchMapper,(const fvsPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvsPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvsPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const dictionary &dict),(p, iF, dict))
fvsPatchField (const fvPatch &, const DimensionedField< Type, surfaceMesh > &)
Construct from patch and internal field.
fvsPatchField (const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvsPatchField (const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fvsPatchField (const fvsPatchField< Type > &, const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvsPatchField onto a new patch.
fvsPatchField (const fvsPatchField< Type > &)
Construct as copy.
virtual tmp< fvsPatchField< Type > > clone () const
Construct and return a clone.
fvsPatchField (const fvsPatchField< Type > &, const DimensionedField< Type, surfaceMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvsPatchField< Type > > clone (const DimensionedField< Type, surfaceMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~fvsPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, surfaceMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvsPatchField< Type > &, const labelList &)
Reverse map the given fvsPatchField onto this fvsPatchField.
virtual void write (Ostream &) const
Write.
void check (const fvsPatchField< Type > &) const
Check fvsPatchField<Type> against given fvsPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvsPatchField< Type > &)
virtual void operator+= (const fvsPatchField< Type > &)
virtual void operator-= (const fvsPatchField< Type > &)
virtual void operator*= (const fvsPatchField< scalar > &)
virtual void operator/= (const fvsPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvsPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type > > &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reUse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type > > &)
Construct by transferring the Field contents.
Field (Istream &)
Construct as copy of tmp<Field>
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType > > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const Type &)
template<class Form , class Cmpt , int nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type > > &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static tmp< fvsPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, surfaceMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvsPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, surfaceMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvsPatchField< Type > > New (const fvsPatchField< Type > &, const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvsPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvsPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvsPatchField created on.
template<class Type2 >
static tmp< fvsPatchField< Type > > NewCalculatedType (const fvsPatchField< Type2 > &)
Return a pointer to a new calculatedFvsPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvsPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes
static int disallowGenericFvsPatchField
Debug switch to disallow the use of genericFvsPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Friends
Ostream & operator (Ostream &, const fvsPatchField< Type > &)
Additional Inherited Members
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::fvsPatchField< Type >
An abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
The first level of derivation is to basic patchFields which cover zero-gradient, fixed-gradient, fixed-value and mixed conditions.
The next level of derivation covers all the specialised typed with specific evaluation proceedures, particularly with respect to specific fields.
Source files
fvsPatchField.H
fvsPatchField.C
fvsPatchFieldNew.C
Definition at line 65 of file fvsPatchField.H.
Member Typedef Documentation
Patch
typedef fvPatch Patch
Definition at line 91 of file fvsPatchField.H.
Constructor & Destructor Documentation
fvsPatchField() [1/6]
fvsPatchField (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF)
Construct from patch and internal field.
Definition at line 40 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::clone(), and fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [2/6]
fvsPatchField (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const Field< Type > & f)
Construct from patch and internal field and patch field.
Definition at line 53 of file fvsPatchField.C.
References fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [3/6]
fvsPatchField (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 82 of file fvsPatchField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::found(), fvsPatchField< Type >::fvsPatchField(), and fvPatch::size().
fvsPatchField() [4/6]
fvsPatchField (const fvsPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given fvsPatchField onto a new patch.
Definition at line 67 of file fvsPatchField.C.
References fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [5/6]
fvsPatchField (const fvsPatchField< Type > & ptf)
Construct as copy.
Definition at line 118 of file fvsPatchField.C.
References fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [6/6]
fvsPatchField (const fvsPatchField< Type > & ptf, const DimensionedField< Type, surfaceMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 130 of file fvsPatchField.C.
~fvsPatchField()
virtual ~fvsPatchField () inline virtual
Destructor.
Definition at line 266 of file fvsPatchField.H.
References fvsPatchField< Type >::db().
Member Function Documentation
TypeName()
TypeName ("fvsPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (tmp , fvsPatchField< Type > , patch , (const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (tmp , fvsPatchField< Type > , patchMapper , (const fvsPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const fvPatchFieldMapper &m) , (dynamic_cast< const fvsPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (tmp , fvsPatchField< Type > , dictionary , (const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
virtual tmp<fvsPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented in slicedFvsPatchField< Type >, processorCyclicFvsPatchField< Type >, processorFvsPatchField< Type >, coupledFvsPatchField< Type >, cyclicFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, nonuniformTransformCyclicFvsPatchField< Type >, symmetryPlaneFvsPatchField< Type >, fixedValueFvsPatchField< Type >, cyclicSlipFvsPatchField< Type >, emptyFvsPatchField< Type >, symmetryFvsPatchField< Type >, wedgeFvsPatchField< Type >, and calculatedFvsPatchField< Type >.
Definition at line 181 of file fvsPatchField.H.
References fvsPatchField< Type >::fvsPatchField().
clone() [2/2]
virtual tmp<fvsPatchField<Type> > clone (const DimensionedField< Type, surfaceMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in processorCyclicFvsPatchField< Type >, processorFvsPatchField< Type >, slicedFvsPatchField< Type >, cyclicFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, coupledFvsPatchField< Type >, nonuniformTransformCyclicFvsPatchField< Type >, symmetryPlaneFvsPatchField< Type >, fixedValueFvsPatchField< Type >, cyclicSlipFvsPatchField< Type >, emptyFvsPatchField< Type >, symmetryFvsPatchField< Type >, wedgeFvsPatchField< Type >, and calculatedFvsPatchField< Type >.
Definition at line 195 of file fvsPatchField.H.
References fvsPatchField< Type >::New(), and fvsPatchField< Type >::NewCalculatedType().
New() [1/4]
tmp< fvsPatchField< Type > > New (const word & patchFieldType, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 93 of file fvsPatchFieldNew.C.
References word::null.
Referenced by fvsPatchField< Type >::clone(), and fvsPatchField< Type >::New().
New() [2/4]
tmp< fvsPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values) Allows override of constraint type
Definition at line 35 of file fvsPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, fvsPatchField< Type >::New(), Foam::nl, word::null, and p.
New() [3/4]
tmp< fvsPatchField< Type > > New (const fvsPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const fvPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given fvsPatchField mapped onto a new patch
Definition at line 181 of file fvsPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, Foam::nl, and p.
New() [4/4]
tmp< fvsPatchField< Type > > New (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 105 of file fvsPatchFieldNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::found(), Foam::Info, dictionary::lookup(), fvsPatchField< Type >::New(), Foam::nl, and p.
NewCalculatedType() [1/2]
tmp< fvsPatchField< Type > > NewCalculatedType (const fvPatch & p) static
Return a pointer to a new calculatedFvsPatchField created on.
freestore without setting patchField values
Definition at line 101 of file calculatedFvsPatchField.C.
References DimensionedField< Type, GeoMesh >::null(), and p.
Referenced by calculatedFvsPatchField< Type >::calculatedFvsPatchField(), and fvsPatchField< Type >::clone().
NewCalculatedType() [2/2]
tmp< fvsPatchField< Type > > NewCalculatedType (const fvsPatchField< Type2 > & pf) static
Return a pointer to a new calculatedFvsPatchField created on.
freestore without setting patchField values
Definition at line 133 of file calculatedFvsPatchField.C.
References fvsPatchField< Type >::patch().
db()
const objectRegistry & db () const
Return local objectRegistry.
Definition at line 144 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::~fvsPatchField().
patch()
const fvPatch& patch () const inline
Return patch.
Definition at line 278 of file fvsPatchField.H.
Referenced by curvatureSeparation::calcCosAngle(), CentredFitSnGradData< Polynomial >::calcFit(), CentredFitData< Polynomial >::CentredFitData(), extendedFaceToCellStencil::collectData(), inversePointDistanceDiffusivity::correct(), inverseFaceDistanceDiffusivity::correct(), surfaceInterpolation::movePoints(), fvsPatchField< Type >::NewCalculatedType(), fvsPatchField< Type >::operator*=(), fvsPatchField< Type >::operator/=(), fvMeshDistribute::printFieldInfo(), dynamicRefineFvMesh::refine(), UpwindFitData< Polynomial >::UpwindFitData(), extendedUpwindCellToFaceStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
dimensionedInternalField()
const DimensionedField<Type, surfaceMesh>& dimensionedInternalField () const inline
Return dimensioned internal field reference.
Definition at line 285 of file fvsPatchField.H.
internalField()
const Field<Type>& internalField () const inline
Return internal field reference.
Definition at line 291 of file fvsPatchField.H.
References fvsPatchField< Type >::calculatedType(), and fvsPatchField< Type >::fixesValue().
calculatedType()
const word & calculatedType () static
Return the type of the calculated for of fvsPatchField.
Definition at line 35 of file calculatedFvsPatchField.C.
References calculatedFvsPatchField< Type >::calculatedFvsPatchField().
Referenced by fvsPatchField< Type >::internalField().
fixesValue()
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Needed to check if a level has to be specified while solving Poissons equations.
Reimplemented in slicedFvsPatchField< Type >, fixedValueFvsPatchField< Type >, and calculatedFvsPatchField< Type >.
Definition at line 302 of file fvsPatchField.H.
Referenced by fvsPatchField< Type >::internalField().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorCyclicFvsPatchField< Type >, processorFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, and coupledFvsPatchField< Type >.
Definition at line 308 of file fvsPatchField.H.
References fvsPatchField< Type >::autoMap(), fvsPatchField< Type >::check(), fvsPatchField< Type >::operator*=(), fvsPatchField< Type >::operator+=(), fvsPatchField< Type >::operator-=(), fvsPatchField< Type >::operator/=(), fvsPatchField< Type >::operator=(), fvsPatchField< Type >::operator==(), fvsPatchField< Type >::rmap(), and fvsPatchField< Type >::write().
Referenced by Foam::adjustPhi(), CentredFitSnGradData< Polynomial >::calcFit(), CentredFitData< Polynomial >::CentredFitData(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), surfaceInterpolation::movePoints(), UpwindFitData< Polynomial >::UpwindFitData(), extendedUpwindCellToFaceStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), and skewCorrectionVectors::~skewCorrectionVectors().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in emptyFvsPatchField< Type >.
Definition at line 165 of file fvsPatchField.C.
References Field< Type >::autoMap(), and fvsPatchField< Type >::rmap().
Referenced by fvsPatchField< Type >::check(), and fvsPatchField< Type >::coupled().
rmap()
void rmap (const fvsPatchField< Type > & ptf, const labelList & addr) virtual
Reverse map the given fvsPatchField onto this fvsPatchField.
Definition at line 176 of file fvsPatchField.C.
References Field< Type >::rmap().
Referenced by fvsPatchField< Type >::autoMap(), and fvsPatchField< Type >::coupled().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 187 of file fvsPatchField.C.
References token::END_STATEMENT, Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by fvsPatchField< Type >::coupled(), and Foam::operator<<().
check()
void check (const fvsPatchField< Type > & ptf) const
Check fvsPatchField<Type> against given fvsPatchField<Type>
Definition at line 151 of file fvsPatchField.C.
References Foam::abort(), fvsPatchField< Type >::autoMap(), Foam::FatalError, and FatalErrorIn.
Referenced by fvsPatchField< Type >::coupled().
operator=() [1/3]
void operator= (const UList< Type > & ul) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 198 of file fvsPatchField.C.
References Field< Type >::operator=().
Referenced by fvsPatchField< Type >::coupled().
operator=() [2/3]
void operator= (const fvsPatchField< Type > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 208 of file fvsPatchField.C.
References Field< Type >::operator=().
operator+=() [1/3]
void operator+= (const fvsPatchField< Type > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 219 of file fvsPatchField.C.
References Field< Type >::operator+=().
Referenced by fvsPatchField< Type >::coupled().
operator-=() [1/3]
void operator-= (const fvsPatchField< Type > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 230 of file fvsPatchField.C.
References Field< Type >::operator-=().
Referenced by fvsPatchField< Type >::coupled().
operator*=() [1/3]
void operator*= (const fvsPatchField< scalar > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 241 of file fvsPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Field< Type >::operator*=(), and fvsPatchField< Type >::patch().
Referenced by fvsPatchField< Type >::coupled().
operator/=() [1/3]
void operator/= (const fvsPatchField< scalar > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 260 of file fvsPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Field< Type >::operator/=(), and fvsPatchField< Type >::patch().
Referenced by fvsPatchField< Type >::coupled().
operator+=() [2/3]
void operator+= (const Field< Type > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 279 of file fvsPatchField.C.
References Field< Type >::operator+=(), and tf.
operator-=() [2/3]
void operator-= (const Field< Type > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 289 of file fvsPatchField.C.
References Field< Type >::operator-=(), and tf.
operator*=() [2/3]
void operator*= (const Field< scalar > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 299 of file fvsPatchField.C.
References Field< Type >::operator*=(), and tf.
operator/=() [2/3]
void operator/= (const Field< scalar > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 309 of file fvsPatchField.C.
References Field< Type >::operator/=(), and tf.
operator=() [3/3]
void operator= (const Type & t) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 319 of file fvsPatchField.C.
References Field< Type >::operator=().
operator+=() [3/3]
void operator+= (const Type & t) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 329 of file fvsPatchField.C.
References Field< Type >::operator+=().
operator-=() [3/3]
void operator-= (const Type & t) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 339 of file fvsPatchField.C.
References Field< Type >::operator-=().
operator*=() [3/3]
void operator*= (const scalar s) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 349 of file fvsPatchField.C.
References Field< Type >::operator*=(), and s().
operator/=() [3/3]
void operator/= (const scalar s) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 359 of file fvsPatchField.C.
References Field< Type >::operator/=(), and s().
operator==() [1/3]
void operator== (const fvsPatchField< Type > & ptf) virtual
Definition at line 370 of file fvsPatchField.C.
References Field< Type >::operator=().
Referenced by fvsPatchField< Type >::coupled().
operator==() [2/3]
void operator== (const Field< Type > & tf) virtual
Definition at line 380 of file fvsPatchField.C.
References Field< Type >::operator=(), and tf.
operator==() [3/3]
void operator== (const Type & t) virtual
Definition at line 390 of file fvsPatchField.C.
References Field< Type >::operator=().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const fvsPatchField< Type > &) friend
Member Data Documentation
disallowGenericFvsPatchField
int disallowGenericFvsPatchField static
Debug switch to disallow the use of genericFvsPatchField.
Definition at line 98 of file fvsPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchField.H
src/finiteVolume/fields/fvsPatchFields/basic/calculated/calculatedFvsPatchField.C
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchField.C
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchFieldNew.C
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchFields.C