OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GeometricField< Type, PatchField, GeoMesh > Class Template Reference
Generic GeometricField class.
Classes
class GeometricBoundaryField
Public Types
typedef GeoMesh::Mesh Mesh
typedef GeoMesh::BoundaryMesh BoundaryMesh
typedef DimensionedField< Type, GeoMesh > DimensionedInternalField
typedef Field< Type > InternalField
typedef PatchField< Type > PatchFieldType
typedef Field< Type >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
typedef Field< Type >::cmptType cmptType
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("GeometricField")
Runtime type information.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const word &patchFieldType=PatchField< Type >::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensions and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensioned< Type > &, const word &patchFieldType=PatchField< Type >::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensioned< Type > &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const Field< Type > &, const PtrList< PatchField< Type > > &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &)
Construct and read given IOobject.
GeometricField (const IOobject &, const Mesh &, const dictionary &)
Construct from dictionary.
GeometricField (const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy of tmp<GeometricField> deleting argument.
GeometricField (const word &newName, const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &, const word &patchFieldType)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
virtual ~GeometricField ()
Destructor.
DimensionedInternalField & dimensionedInternalField ()
Return dimensioned internal field.
const DimensionedInternalField & dimensionedInternalField () const
Return dimensioned internal field.
InternalField & internalField ()
Return internal field.
const InternalField & internalField () const
Return internal field.
GeometricBoundaryField & boundaryField ()
Return reference to GeometricBoundaryField.
const GeometricBoundaryField & boundaryField () const
Return reference to GeometricBoundaryField for const field.
label timeIndex () const
Return the time index of the field.
label & timeIndex ()
Return the time index of the field.
void storeOldTimes () const
Store the old-time fields.
void storeOldTime () const
Store the old-time field.
label nOldTimes () const
Return the number of old time fields stored.
const GeometricField< Type, PatchField, GeoMesh > & oldTime () const
Return old time field.
GeometricField< Type, PatchField, GeoMesh > & oldTime ()
Return non-const old time field.
void storePrevIter () const
Store the field as the previous iteration value.
const GeometricField< Type, PatchField, GeoMesh > & prevIter () const
Return previous iteration field.
void correctBoundaryConditions ()
Correct boundary field.
bool needReference () const
Does the field need a reference level for solution.
tmp< GeometricField< cmptType, PatchField, GeoMesh > > component (const direction) const
Return a component of the field.
bool writeData (Ostream &) const
WriteData member function required by regIOobject.
tmp< GeometricField< Type, PatchField, GeoMesh > > T () const
Return transpose (only if it is a tensor field)
void relax (const scalar alpha)
Relax field (for steady-state solution).
void relax ()
Relax field (for steady-state solution).
word select (bool final) const
Select the final iteration parameters if `final' is true.
void writeMinMax (Ostream &os) const
Helper function to write the min and max to an Ostream.
void negate ()
void replace (const direction, const GeometricField< cmptType, PatchField, GeoMesh > &)
void replace (const direction, const dimensioned< cmptType > &)
void max (const dimensioned< Type > &)
void min (const dimensioned< Type > &)
void max (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void min (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > &, const GeometricField< Type, PatchField, GeoMesh > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void operator= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator= (const tmp< GeometricField< Type, PatchField, GeoMesh > > &)
void operator= (const dimensioned< Type > &)
void operator== (const tmp< GeometricField< Type, PatchField, GeoMesh > > &)
void operator== (const dimensioned< Type > &)
void operator+= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator+= (const tmp< GeometricField< Type, PatchField, GeoMesh > > &)
void operator-= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator-= (const tmp< GeometricField< Type, PatchField, GeoMesh > > &)
void operator*= (const GeometricField< scalar, PatchField, GeoMesh > &)
void operator*= (const tmp< GeometricField< scalar, PatchField, GeoMesh > > &)
void operator/= (const GeometricField< scalar, PatchField, GeoMesh > &)
void operator/= (const tmp< GeometricField< scalar, PatchField, GeoMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
template<>
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
template<>
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const Field< Type > &)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensioned< Type > &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const DimensionedField< Type, GeoMesh > &)
Construct as copy.
DimensionedField (DimensionedField< Type, GeoMesh > &, bool reUse)
Construct as copy or re-use as specified.
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh > > &)
Construct by transferring the DimensionedField.
DimensionedField (const IOobject &, const DimensionedField< Type, GeoMesh > &)
Construct as copy of tmp<DimensionedField> deleting argument.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &, bool reUse)
Construct as copy resetting name and re-use as specified.
DimensionedField (const word &newName, const Xfer< DimensionedField< Type, GeoMesh > > &)
Construct by transferring the DimensionedField with a new name.
tmp< DimensionedField< Type, GeoMesh > > clone () const
Construct as copy resetting name.
virtual ~DimensionedField ()
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const Field< Type > & field () const
Field< Type > & field ()
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
void replace (const direction, const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
void replace (const direction, const tmp< DimensionedField< cmptType, GeoMesh > > &)
Replace a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh > > &) const
Calculate and return weighted average.
bool writeData (Ostream &, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &)
void operator= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator= (const dimensioned< Type > &)
void operator+= (const DimensionedField< Type, GeoMesh > &)
void operator+= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator-= (const DimensionedField< Type, GeoMesh > &)
void operator-= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator*= (const DimensionedField< scalar, GeoMesh > &)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh > > &)
void operator/= (const DimensionedField< scalar, GeoMesh > &)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type > > &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reUse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type > > &)
Construct by transferring the Field contents.
Field (Istream &)
Construct as copy of tmp<Field>
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType > > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const Type &)
template<class Form , class Cmpt , int nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type > > &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static const GeometricField< Type, PatchField, GeoMesh > & null ()
Return a null geometric field.
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
Return a null DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Friends
Ostream & operator (Ostream &, const GeometricField< Type, PatchField, GeoMesh > &)
Ostream & operator (Ostream &, const tmp< GeometricField< Type, PatchField, GeoMesh > > &)
Additional Inherited Members
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type, template< class > class PatchField, class GeoMesh>
class Foam::GeometricField< Type, PatchField, GeoMesh >
Generic GeometricField class.
Source files
GeometricField.H
GeometricFieldI.H
GeometricField.C
GeometricBoundaryField.C
GeometricFieldFunctions.H
GeometricFieldFunctions.C
Definition at line 52 of file surfaceFieldsFwd.H.
Member Typedef Documentation
Mesh
typedef GeoMesh::Mesh Mesh
Definition at line 97 of file GeometricField.H.
BoundaryMesh
typedef GeoMesh::BoundaryMesh BoundaryMesh
Definition at line 98 of file GeometricField.H.
DimensionedInternalField
typedef DimensionedField<Type, GeoMesh> DimensionedInternalField
Definition at line 100 of file GeometricField.H.
InternalField
typedef Field<Type> InternalField
Definition at line 101 of file GeometricField.H.
PatchFieldType
typedef PatchField<Type> PatchFieldType
Definition at line 102 of file GeometricField.H.
cmptType
typedef Field<Type>::cmptType cmptType
Definition at line 273 of file GeometricField.H.
Constructor & Destructor Documentation
GeometricField() [1/12]
GeometricField (const IOobject & io, const Mesh & mesh, const dimensionSet & ds, const word & patchFieldType = PatchField<Type>::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
This allocates storage for the field but not values. Used only within this class to create TEMPORARY variables
Definition at line 189 of file GeometricField.C.
Referenced by GeometricField< vector, pointPatchField, pointMesh >::GeometricField().
GeometricField() [2/12]
GeometricField (const IOobject & io, const Mesh & mesh, const dimensionSet & ds, const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
Constructor given IOobject, mesh, dimensions and patch types.
This allocates storage for the field but not values. Used only within this class to create TEMPORARY variables
Definition at line 219 of file GeometricField.C.
GeometricField() [3/12]
GeometricField (const IOobject & io, const Mesh & mesh, const dimensioned< Type > & dt, const word & patchFieldType = PatchField<Type>::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
Definition at line 247 of file GeometricField.C.
GeometricField() [4/12]
GeometricField (const IOobject & io, const Mesh & mesh, const dimensioned< Type > & dt, const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
Definition at line 276 of file GeometricField.C.
GeometricField() [5/12]
GeometricField (const IOobject & io, const Mesh & mesh, const dimensionSet & ds, const Field< Type > & iField, const PtrList< PatchField< Type > > & ptfl)
Constructor from components.
Definition at line 306 of file GeometricField.C.
GeometricField() [6/12]
GeometricField (const IOobject & io, const Mesh & mesh)
Construct and read given IOobject.
Definition at line 333 of file GeometricField.C.
GeometricField() [7/12]
GeometricField (const IOobject & io, const Mesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 373 of file GeometricField.C.
GeometricField() [8/12]
GeometricField (const GeometricField< Type, PatchField, GeoMesh > & gf)
Construct as copy.
Definition at line 414 of file GeometricField.C.
GeometricField() [9/12]
GeometricField (const IOobject & io, const GeometricField< Type, PatchField, GeoMesh > & gf)
Construct as copy of tmp<GeometricField> deleting argument.
Construct as copy resetting IO parameters
Definition at line 477 of file GeometricField.C.
GeometricField() [10/12]
GeometricField (const word & newName, const GeometricField< Type, PatchField, GeoMesh > & gf)
Construct as copy resetting name.
Definition at line 509 of file GeometricField.C.
GeometricField() [11/12]
GeometricField (const IOobject & io, const GeometricField< Type, PatchField, GeoMesh > & gf, const word & patchFieldType)
Construct as copy resetting name.
Construct as copy resetting IO parameters and patch type
Definition at line 572 of file GeometricField.C.
GeometricField() [12/12]
GeometricField (const IOobject & io, const GeometricField< Type, PatchField, GeoMesh > & gf, const wordList & patchFieldTypes, const wordList & actualPatchTypes = wordList())
Construct as copy resetting IO parameters and boundary types.
Definition at line 607 of file GeometricField.C.
~GeometricField()
~GeometricField () virtual
Destructor.
Definition at line 650 of file GeometricField.C.
Member Function Documentation
TypeName()
TypeName ("GeometricField< Type, PatchField, GeoMesh >")
Runtime type information.
null()
const Foam::GeometricField< Type, PatchField, GeoMesh > & null () inline static
Return a null geometric field.
Definition at line 30 of file GeometricFieldI.H.
Referenced by ddtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), and CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr().
dimensionedInternalField() [1/2]
Foam::GeometricField< Type, PatchField, GeoMesh >::DimensionedInternalField & dimensionedInternalField ()
Return dimensioned internal field.
Definition at line 662 of file GeometricField.C.
Referenced by singleStepCombustion< CombThermoType, ThermoType >::dQ(), solidChemistryModel< CompType, SolidThermo >::dQ(), chemistryModel< CompType, ThermoType >::dQ(), fvMeshSubset::interpolate(), laplaceFilter::laplaceFilter(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), GeometricField< vector, pointPatchField, pointMesh >::null(), GeometricField< vector, pointPatchField, pointMesh >::operator/=(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator==(), P1::Ru(), fvDOM::Ru(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
dimensionedInternalField() [2/2]
const Foam::GeometricField< Type, PatchField, GeoMesh >::DimensionedInternalField & dimensionedInternalField () const inline
Return dimensioned internal field.
Definition at line 41 of file GeometricFieldI.H.
internalField() [1/2]
Foam::GeometricField< Type, PatchField, GeoMesh >::InternalField & internalField ()
Return internal field.
Definition at line 673 of file GeometricField.C.
Referenced by MRFZone::addCoriolis(), interRegionExplicitPorositySource::addSup(), Foam::atan2(), Foam::fvc::average(), Foam::bound(), Implicit< CloudType >::cacheFields(), curvatureSeparation::calcCosAngle(), Foam::calcEk(), cellLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), Foam::checkMethod(), Foam::cmptAv(), Foam::component(), pointConstraints::constrain(), pointConstraints::constrainDisplacement(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), inverseDistanceDiffusivity::correct(), temperatureLimitsConstraint::correct(), phaseChangeModel::correct(), curvatureSeparation::correct(), SpalartAllmaras::correct(), wideBandAbsorptionEmission::correct(), pointLinear< Type >::correction(), limitedSnGrad< Type >::correction(), kinematicSingleLayer::CourantNumber(), motionSmootherAlgo::curPoints(), fvFieldDecomposer::decomposeField(), wideBandAbsorptionEmission::ECont(), reactingOneDim::evolveRegion(), DESModelRegions::execute(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), fvMatrix< Type >::flux(), forAll(), faceCorrectedSnGrad< Type >::fullGradCorrection(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), fvMatrix< Type >::H(), heThermo< BasicSolidThermo, MixtureType >::hc(), heThermo< BasicSolidThermo, MixtureType >::he(), rotorDiskSource::inflowVelocity(), thermoSingleLayer::info(), kinematicSingleLayer::info(), surfaceInterpolationScheme< GType >::interpolate(), fvMeshSubset::interpolate(), volPointInterpolation::interpolateBoundaryField(), isoSurface::isoSurface(), Kmesh::Kmesh(), Foam::MULES::limiterCorr(), Foam::mag(), Foam::magSqr(), Foam::makeGraph(), Foam::MapGeometricFields(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), surfaceInterpolation::movePoints(), fvMesh::movePoints(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), heheuPsiThermo< BasicPsiThermo, MixtureType >::muu(), consumptionSpeed::omega0Sigma(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), VoidFraction< CloudType >::postEvolve(), Foam::pow(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psiu(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), dynamicRefineFvMesh::refine(), sampledPatchInternalField::sampleField(), motionSmootherAlgo::scaleMesh(), primaryRadiation::Shs(), standardRadiation::Shs(), constantRadiation::Shs(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), reactingOneDim::solidRegionDiffNo(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveSegregated(), Foam::sqr(), Foam::stabilise(), ReactingCloud< Foam::DsmcCloud >::SYi(), Foam::T(), KinematicCloud< Foam::DsmcCloud >::theta(), Foam::transform(), KinematicCloud< Foam::DsmcCloud >::vDotSweep(), Foam::fvc::volumeIntegrate(), limitedSurfaceInterpolationScheme< Type >::weights(), AveragingMethod< Foam::Vector >::write(), regionSizeDistribution::write(), Foam::writeCellGraph(), Basic< Type >::~Basic(), and skewCorrectionVectors::~skewCorrectionVectors().
internalField() [2/2]
const Foam::GeometricField< Type, PatchField, GeoMesh >::InternalField & internalField () const inline
Return internal field.
Definition at line 51 of file GeometricFieldI.H.
boundaryField() [1/2]
Foam::GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField & boundaryField ()
Return reference to GeometricBoundaryField.
Definition at line 685 of file GeometricField.C.
Referenced by isoSurface::adaptPatchFields(), reactingOneDim::addMassSources(), thermoSingleLayer::addSources(), kinematicSingleLayer::addSources(), effectivenessHeatExchangerSource::addSup(), Foam::adjustPhi(), basicThermo::alpha(), Foam::atan2(), Foam::fvc::average(), Foam::bound(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::cacheFilmFields(), ThermoSurfaceFilm< CloudType >::cacheFilmFields(), curvatureSeparation::calcCosAngle(), CentredFitSnGradData< Polynomial >::calcFit(), forces::calcForcesMoment(), cellLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), fieldMinMax::calcMinMaxFields(), mutkWallFunctionFvPatchScalarField::calcMut(), mutUWallFunctionFvPatchScalarField::calcMut(), mutkFilmWallFunctionFvPatchScalarField::calcMut(), mutUSpaldingWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::calcMut(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), wallShearStress::calcShearStress(), P1::calculate(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), viewFactor::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), reactingOneDim::calculateMassTransfer(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), mutUWallFunctionFvPatchScalarField::calcYPlus(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), CentredFitData< Polynomial >::CentredFitData(), fvPatch::Cf(), Foam::cmptAv(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), Foam::component(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), reflectionVectors::correct(), injectionModelList::correct(), contactAngleForce::correct(), temperatureLimitsConstraint::correct(), LienCubicKE::correct(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), realizableKE::correct(), kOmega::correct(), LaunderGibsonRSTM::correct(), SpalartAllmaras::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), motionSmootherAlgo::correct(), gaussGrad< Type >::correctBoundaryConditions(), motionSmootherAlgo::correctBoundaryConditions(), MRFZone::correctBoundaryVelocity(), thermoSingleLayer::correctHsForMappedT(), mixtureKEpsilon< BasicTurbulenceModel >::correctInletOutlet(), cubic< Type >::correction(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), outletStabilised< Type >::correction(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), motionSmootherAlgo::curPoints(), fvFieldDecomposer::decomposeField(), fvMesh::delta(), fvPatch::deltaCoeffs(), kOmega::epsilon(), kOmegaSST::epsilon(), mixtureKEpsilon< BasicTurbulenceModel >::epsilonBoundaryTypes(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), FacePostProcessing< CloudType >::FacePostProcessing(), faceSource::filterField(), PatchFlowRateInjection< CloudType >::flowRate(), fvMatrix< Type >::flux(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), fvMatrix< Type >::fvMatrix(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), SpalartAllmaras::fw(), isoSurface::generateFaceTriPoints(), heThermo< BasicSolidThermo, MixtureType >::hc(), heThermo< BasicSolidThermo, MixtureType >::he(), heThermo< BasicSolidThermo, MixtureType >::heBoundaryCorrection(), psiuReactionThermo::heuBoundaryCorrection(), psiuReactionThermo::heuBoundaryTypes(), thermoSingleLayer::hs(), FreeStream< CloudType >::inflow(), thermalBaffle::info(), mixtureKEpsilon< BasicTurbulenceModel >::initMixtureFields(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::inject(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< GType >::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), volPointInterpolation::interpolateInternalField(), kkLOmega::k(), temperatureCoupledBase::kappa(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), Foam::mag(), fvPatch::magSf(), Foam::magSqr(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), Foam::MapGeometricFields(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), fvMotionSolverEngineMesh::move(), surfaceInterpolation::movePoints(), fvMesh::movePoints(), psiThermo::mu(), rhoThermo::mu(), incompressibleTwoPhaseInteractingMixture::mu(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), laminar::muEff(), CompressibleTurbulenceModel< TransportModel >::mut(), PhaseCompressibleTurbulenceModel< phaseModel >::mut(), heheuPsiThermo< BasicPsiThermo, MixtureType >::muu(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), Newtonian::nu(), CrossPowerLaw::nu(), powerLaw::nu(), HerschelBulkley::nu(), BirdCarreau::nu(), incompressibleTwoPhaseMixture::nu(), incompressibleTwoPhaseInteractingMixture::nu(), incompressibleThreePhaseMixture::nu(), eddyViscosity< RASModel< BasicTurbulenceModel > >::nut(), consumptionSpeed::omega0Sigma(), omegaWallFunctionFvPatchScalarField::omegaPatch(), GeometricField< vector, pointPatchField, pointMesh >::operator/=(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator==(), KinematicCloud< Foam::DsmcCloud >::patchData(), homogeneousMixture< ThermoType >::patchFaceMixture(), inhomogeneousMixture< ThermoType >::patchFaceMixture(), veryInhomogeneousMixture< ThermoType >::patchFaceMixture(), egrMixture< ThermoType >::patchFaceMixture(), inhomogeneousMixture< ThermoType >::patchFaceProducts(), veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), egrMixture< ThermoType >::patchFaceProducts(), inhomogeneousMixture< ThermoType >::patchFaceReactants(), veryInhomogeneousMixture< ThermoType >::patchFaceReactants(), egrMixture< ThermoType >::patchFaceReactants(), fvPatch::patchField(), Foam::pow(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psiu(), thermoSingleLayer::Qconvp(), thermoSingleLayer::Qconvw(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), kEpsilon::R(), LienCubicKELowRe::R(), RNGkEpsilon::R(), kOmega::R(), LaunderSharmaKE::R(), realizableKE::R(), qZeta::R(), kOmegaSST::R(), kkLOmega::R(), v2f::RBoundaryTypes(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), Foam::fvc::reconstructMag(), dynamicRefineFvMesh::refine(), psiThermo::rho(), rhoThermo::rho(), incompressibleTwoPhaseInteractingMixture::rho(), patchProbes::sample(), nearWallFields::sampleBoundaryField(), sampledPatch::sampleField(), sampledTriSurfaceMesh::sampleField(), epsilonWallFunctionFvPatchScalarField::setMaster(), omegaWallFunctionFvPatchScalarField::setMaster(), pointConstraints::setPatchFields(), fvPatch::Sf(), snGradScheme< Type >::snGrad(), fvMatrix< Type >::solveCoupled(), thermalBaffle::solveEnergy(), fvMatrix< Type >::solveSegregated(), ThermoSurfaceFilm< CloudType >::splashInteraction(), Foam::fvc::spread(), Foam::sqr(), thermoSingleLayer::Srho(), Foam::stabilise(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), cyclicPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), Foam::fvc::sweep(), Foam::T(), thermoSingleLayer::thermoSingleLayer(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), Foam::transform(), dynamicRefineFvMesh::unrefine(), gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs(), mixedUnburntEnthalpyFvPatchScalarField::updateCoeffs(), fixedUnburntEnthalpyFvPatchScalarField::updateCoeffs(), mixedEnergyFvPatchScalarField::updateCoeffs(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), fixedEnergyFvPatchScalarField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), gradientEnergyFvPatchScalarField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), fvDOM::updateG(), motionSmootherAlgo::updateMesh(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), UpwindFitData< Polynomial >::UpwindFitData(), extendedUpwindCellToFaceStencil::weightedSum(), outletStabilised< Type >::weights(), limitedSurfaceInterpolationScheme< Type >::weights(), fvPatch::weights(), while(), regionSizeDistribution::write(), externalCoupledMixedFvPatchField< scalar >::writeData(), ensightParts::writeField(), externalCoupledMixedFvPatchField< scalar >::writeGeometry(), Foam::writePatchGraph(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), mutkWallFunctionFvPatchScalarField::yPlus(), mutLowReWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), mutUWallFunctionFvPatchScalarField::yPlus(), mutkFilmWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), mutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), mutURoughWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), externalCoupledMixedFvPatchField< scalar >::~externalCoupledMixedFvPatchField(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), leastSquaresVectors::~leastSquaresVectors(), skewCorrectionVectors::~skewCorrectionVectors(), and thermalBaffle::~thermalBaffle().
boundaryField() [2/2]
const Foam::GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField & boundaryField () const inline
Return reference to GeometricBoundaryField for const field.
Definition at line 60 of file GeometricFieldI.H.
timeIndex() [1/2]
Foam::label timeIndex () const inline
Return the time index of the field.
Definition at line 68 of file GeometricFieldI.H.
Referenced by fvMesh::movePoints(), fvMesh::phi(), and subCycleField< GeometricField >::~subCycleField().
timeIndex() [2/2]
Foam::label & timeIndex () inline
Return the time index of the field.
Definition at line 76 of file GeometricFieldI.H.
storeOldTimes()
void storeOldTimes () const
Store the old-time fields.
Definition at line 695 of file GeometricField.C.
Referenced by Foam::MapGeometricFields().
storeOldTime()
void storeOldTime () const
Store the old-time field.
Definition at line 716 of file GeometricField.C.
nOldTimes()
Foam::label nOldTimes () const
Return the number of old time fields stored.
Definition at line 740 of file GeometricField.C.
oldTime() [1/2]
const Foam::GeometricField< Type, PatchField, GeoMesh > & oldTime () const
Return old time field.
Definition at line 755 of file GeometricField.C.
Referenced by Foam::MULES::explicitSolve(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::MULES::limiter(), CrankNicolsonDdtScheme< Type >::meshPhi(), fvMesh::movePoints(), GeometricField< vector, pointPatchField, pointMesh >::oldTime(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), and advectiveFvPatchField< Type >::updateCoeffs().
oldTime() [2/2]
Foam::GeometricField< Type, PatchField, GeoMesh > & oldTime ()
Return non-const old time field.
(Not a good idea but it is used for sub-cycling)
Definition at line 784 of file GeometricField.C.
storePrevIter()
void storePrevIter () const
Store the field as the previous iteration value.
Definition at line 795 of file GeometricField.C.
Referenced by viewFactor::calculate().
prevIter()
const Foam::GeometricField< Type, PatchField, GeoMesh > & prevIter () const
Return previous iteration field.
Definition at line 821 of file GeometricField.C.
correctBoundaryConditions()
void correctBoundaryConditions ()
Correct boundary field.
Definition at line 841 of file GeometricField.C.
Referenced by porosityModel::addResistance(), Foam::fvc::average(), Implicit< CloudType >::cacheFields(), cellLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), Foam::checkMethod(), pointConstraints::constrain(), pointConstraints::constrainDisplacement(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), inverseDistanceDiffusivity::correct(), injectionModelList::correct(), primaryRadiation::correct(), mappedConvectiveHeatTransfer::correct(), standardRadiation::correct(), phaseChangeModel::correct(), LienCubicKE::correct(), SpalartAllmaras::correct(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), kOmega::correct(), LaunderGibsonRSTM::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), thermoSingleLayer::correctAlpha(), thermoSingleLayer::correctHsForMappedT(), Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), forAllIter(), fvMatrix< Type >::H(), kkLOmega::kkLOmega(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), sampledSurface::pointAverage(), GeometricField< vector, pointPatchField, pointMesh >::prevIter(), qZeta::qZeta(), standardRadiation::Shs(), Foam::fvc::smooth(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), kinematicSingleLayer::solveMomentum(), fvMatrix< Type >::solveSegregated(), kinematicSingleLayer::solveThickness(), SpalartAllmaras::SpalartAllmaras(), Foam::fvc::spread(), Foam::fvc::sweep(), KinematicCloud< Foam::DsmcCloud >::theta(), thixotropicViscosity::thixotropicViscosity(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), thermoSingleLayer::transferPrimaryRegionThermoFields(), kinematicSingleLayer::transferPrimaryRegionThermoFields(), dynamicMotionSolverFvMesh::update(), dynamicInkJetFvMesh::update(), multiSolidBodyMotionFvMesh::update(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), thixotropicViscosity::updateMu(), reactingOneDim::updateQr(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), v2f::v2f(), KinematicCloud< Foam::DsmcCloud >::vDotSweep(), and Basic< Type >::~Basic().
needReference()
bool needReference () const
Does the field need a reference level for solution.
Definition at line 851 of file GeometricField.C.
Referenced by Foam::adjustPhi(), and Foam::setRefCell().
component() [1/3]
tmp<GeometricField<cmptType, PatchField, GeoMesh> > component (const direction) const
Return a component of the field.
Referenced by anisotropicFilter::anisotropicFilter(), LRRDiffStress::correct(), DeardorffDiffStress::correct(), cubic< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), Foam::fvc::magSqrGradGrad(), skewCorrected< Type >::skewCorrection(), and GeometricField< vector, pointPatchField, pointMesh >::T().
writeData()
bool writeData (Ostream & os) const virtual
WriteData member function required by regIOobject.
Reimplemented from DimensionedField< Type, GeoMesh >.
Definition at line 946 of file GeometricField.C.
Referenced by GeometricField< vector, pointPatchField, pointMesh >::writeMinMax().
T()
Foam::tmp< Foam::GeometricField< Type, PatchField, GeoMesh > > T () const
Return transpose (only if it is a tensor field)
Definition at line 957 of file GeometricField.C.
Referenced by LienCubicKE::correct(), LienCubicKELowRe::correct(), and displacementSBRStressFvMotionSolver::solve().
relax() [1/2]
void relax (const scalar alpha)
Relax field (for steady-state solution).
alpha = 1 : no relaxation alpha < 1 : relaxation alpha = 0 : do nothing
Definition at line 874 of file GeometricField.C.
Referenced by viewFactor::calculate().
relax() [2/2]
void relax ()
Relax field (for steady-state solution).
alpha is read from controlDict
Definition at line 890 of file GeometricField.C.
select()
Foam::word select (bool final) const
Select the final iteration parameters if `final' is true.
by returning the field name + "Final" otherwise the standard parameters by returning the field name
Definition at line 915 of file GeometricField.C.
Referenced by GeometricField< vector, pointPatchField, pointMesh >::relax().
writeMinMax()
void writeMinMax (Ostream & os) const
Helper function to write the min and max to an Ostream.
Definition at line 932 of file GeometricField.C.
Referenced by GeometricField< vector, pointPatchField, pointMesh >::select().
negate()
void negate ()
Definition at line 1070 of file GeometricField.C.
replace() [1/4]
void replace (const direction , const GeometricField< cmptType, PatchField, GeoMesh > &)
Referenced by GeometricField< vector, pointPatchField, pointMesh >::component(), cubic< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), fvMatrix< Type >::H(), and GeometricField< vector, pointPatchField, pointMesh >::T().
replace() [2/4]
void replace (const direction d, const dimensioned< cmptType > & ds)
Definition at line 1037 of file GeometricField.C.
max() [1/2]
void max (const dimensioned< Type > & dt)
Definition at line 1049 of file GeometricField.C.
Referenced by dynOneEqEddy::correct(), LRR::correct(), thixotropicViscosity::correct(), LaunderGibsonRSTM::correct(), GeometricField< vector, pointPatchField, pointMesh >::replace(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), and thixotropicViscosity::thixotropicViscosity().
min() [1/2]
void min (const dimensioned< Type > & dt)
Definition at line 1060 of file GeometricField.C.
Referenced by thixotropicViscosity::correct(), kinematicSingleLayer::gNormClipped(), GeometricField< vector, pointPatchField, pointMesh >::max(), laminar::Su(), and thixotropicViscosity::thixotropicViscosity().
max() [2/2]
void max (const GeometricField< Type, PatchField, GeoMesh > & , const dimensioned< Type > &)
min() [2/2]
void min (const GeometricField< Type, PatchField, GeoMesh > & , const dimensioned< Type > &)
scale() [1/2]
void scale (const GeometricField< Type, PatchField, GeoMesh > & , const GeometricField< Type, PatchField, GeoMesh > &)
scale() [2/2]
void scale (const GeometricField< Type, PatchField, GeoMesh > & , const dimensioned< Type > &)
operator=() [1/3]
void operator= (const GeometricField< Type, PatchField, GeoMesh > & gf)
Definition at line 1081 of file GeometricField.C.
operator=() [2/3]
void operator= (const tmp< GeometricField< Type, PatchField, GeoMesh > > & tgf)
Definition at line 1106 of file GeometricField.C.
operator=() [3/3]
void operator= (const dimensioned< Type > & dt)
Definition at line 1142 of file GeometricField.C.
operator==() [1/2]
void operator== (const tmp< GeometricField< Type, PatchField, GeoMesh > > & tgf)
Definition at line 1153 of file GeometricField.C.
operator==() [2/2]
void operator== (const dimensioned< Type > & dt)
Definition at line 1172 of file GeometricField.C.
operator+=() [1/3]
void operator+= (const GeometricField< Type, PatchField, GeoMesh > & gf)
Definition at line 1215 of file GeometricField.C.
operator+=() [2/3]
void operator+= (const tmp< GeometricField< Type, PatchField, GeoMesh > > & tgf)
Definition at line 1215 of file GeometricField.C.
operator-=() [1/3]
void operator-= (const GeometricField< Type, PatchField, GeoMesh > & gf)
Definition at line 1216 of file GeometricField.C.
operator-=() [2/3]
void operator-= (const tmp< GeometricField< Type, PatchField, GeoMesh > > & tgf)
Definition at line 1216 of file GeometricField.C.
operator*=() [1/3]
void operator*= (const GeometricField< scalar, PatchField, GeoMesh > & gf)
Definition at line 1217 of file GeometricField.C.
operator*=() [2/3]
void operator*= (const tmp< GeometricField< scalar, PatchField, GeoMesh > > & tgf)
Definition at line 1217 of file GeometricField.C.
operator/=() [1/3]
void operator/= (const GeometricField< scalar, PatchField, GeoMesh > & gf)
Definition at line 1218 of file GeometricField.C.
operator/=() [2/3]
void operator/= (const tmp< GeometricField< scalar, PatchField, GeoMesh > > & tgf)
Definition at line 1218 of file GeometricField.C.
operator+=() [3/3]
void operator+= (const dimensioned< Type > & dt)
Definition at line 1215 of file GeometricField.C.
operator-=() [3/3]
void operator-= (const dimensioned< Type > & dt)
Definition at line 1216 of file GeometricField.C.
operator*=() [3/3]
void operator*= (const dimensioned< scalar > & dt)
Definition at line 1217 of file GeometricField.C.
operator/=() [3/3]
void operator/= (const dimensioned< scalar > & dt)
Definition at line 1218 of file GeometricField.C.
component() [2/3]
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
Definition at line 62 of file volFields.C.
replace() [3/4]
void replace (const direction , const GeometricField< scalar, fvPatchField, volMesh > & gsf)
Definition at line 73 of file volFields.C.
component() [3/3]
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
replace() [4/4]
void replace (const direction , const GeometricField< scalar, fvPatchField, volMesh > & sf)
Friends And Related Function Documentation
operator [1/2]
Ostream& operator (Ostream & , const GeometricField< Type, PatchField, GeoMesh > &) friend
operator [2/2]
Ostream& operator (Ostream & , const tmp< GeometricField< Type, PatchField, GeoMesh > > &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fields/surfaceFields/surfaceFieldsFwd.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricField.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricField.C
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricFieldI.H