OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
localEulerDdtScheme< Type > Class Template Reference
Local time-step first-order Euler implicit/explicit ddt. The reciprocal of the local time-step field is looked-up from the database with the name provided.
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("localEuler")
Runtime type information.
localEulerDdtScheme (const fvMesh &mesh, const word &rDeltaTName)
Construct from mesh and name of the rDeltaT field.
localEulerDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::localEulerDdtScheme< Type >
Local time-step first-order Euler implicit/explicit ddt. The reciprocal of the local time-step field is looked-up from the database with the name provided.
This scheme should only be used for steady-state computations using transient codes where local time-stepping is preferably to under-relaxation for transport consistency reasons.
See also CoEulerDdtScheme.
Source files
localEulerDdtScheme.H
localEulerDdtScheme.C
localEulerDdtSchemes.C
Definition at line 63 of file localEulerDdtScheme.H.
Member Typedef Documentation
fluxFieldType
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 169 of file localEulerDdtScheme.H.
Constructor & Destructor Documentation
localEulerDdtScheme() [1/2]
localEulerDdtScheme (const fvMesh & mesh, const word & rDeltaTName) inline
Construct from mesh and name of the rDeltaT field.
Definition at line 94 of file localEulerDdtScheme.H.
localEulerDdtScheme() [2/2]
localEulerDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 101 of file localEulerDdtScheme.H.
Member Function Documentation
TypeName()
TypeName ("localEuler")
Runtime type information.
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 111 of file localEulerDdtScheme.H.
References Foam::constant::atomic::alpha, localEulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh(), psi, and rho.
fvcDdt() [1/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 53 of file localEulerDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, dimensioned< Type >::name(), rDeltaT(), and dimensioned< Type >::value().
Referenced by localEulerDdtScheme< Type >::fvcDdt(), and localEulerDdtScheme< Type >::mesh().
fvcDdt() [2/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 113 of file localEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), localEulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdt() [3/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 164 of file localEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), localEulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and dimensioned< Type >::value().
fvcDdt() [4/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 216 of file localEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), localEulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdt() [5/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 271 of file localEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), localEulerDdtScheme< Type >::fvmDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvmDdt() [1/4]
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 340 of file localEulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
Referenced by localEulerDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvmDdt(), and localEulerDdtScheme< Type >::mesh().
fvmDdt() [2/4]
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 375 of file localEulerDdtScheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, localEulerDdtScheme< Type >::fvmDdt(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), fvMatrix< Type >::source(), and dimensioned< Type >::value().
fvmDdt() [3/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 412 of file localEulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, localEulerDdtScheme< Type >::fvmDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
fvmDdt() [4/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 451 of file localEulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, localEulerDdtScheme< Type >::fvcDdtUfCorr(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
fvcDdtUfCorr() [1/4]
tmp< typename localEulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 493 of file localEulerDdtScheme.C.
References localEulerDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
Referenced by localEulerDdtScheme< Type >::fvcDdtPhiCorr(), and localEulerDdtScheme< Type >::fvmDdt().
fvcDdtPhiCorr() [1/4]
tmp< typename localEulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 530 of file localEulerDdtScheme.C.
References localEulerDdtScheme< Type >::fvcDdtUfCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
Referenced by localEulerDdtScheme< Type >::fvcDdtUfCorr().
fvcDdtUfCorr() [2/4]
tmp< typename localEulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 562 of file localEulerDdtScheme.C.
References Foam::abort(), Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, localEulerDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdtPhiCorr() [2/4]
tmp< typename localEulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 631 of file localEulerDdtScheme.C.
References Foam::abort(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, Foam::fvc::interpolate(), mesh, localEulerDdtScheme< Type >::meshPhi(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
meshPhi()
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) virtual
Implements ddtScheme< Type >.
Definition at line 694 of file localEulerDdtScheme.C.
References Foam::dimTime, Foam::dimVolume, mesh, IOobject::NO_READ, IOobject::NO_WRITE, and timeName.
Referenced by localEulerDdtScheme< Type >::fvcDdtPhiCorr().
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/localEulerDdtScheme/localEulerDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/localEulerDdtScheme/localEulerDdtScheme.C