OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CoEulerDdtScheme< Type > Class Template Reference
Courant number limited first-order Euler implicit/explicit ddt.
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("CoEuler")
Runtime type information.
CoEulerDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::CoEulerDdtScheme< Type >
Courant number limited first-order Euler implicit/explicit ddt.
The time-step is adjusted locally so that the local Courant number does not exceed the specified value.
This scheme should only be used for steady-state computations using transient codes where local time-stepping is preferable to under-relaxation for transport consistency reasons.
Source files
CoEulerDdtScheme.H
CoEulerDdtScheme.C
Definition at line 61 of file CoEulerDdtScheme.H.
Member Typedef Documentation
fluxFieldType
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 172 of file CoEulerDdtScheme.H.
Constructor & Destructor Documentation
CoEulerDdtScheme()
CoEulerDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 102 of file CoEulerDdtScheme.H.
Member Function Documentation
TypeName()
TypeName ("CoEuler")
Runtime type information.
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 114 of file CoEulerDdtScheme.H.
References Foam::constant::atomic::alpha, CoEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh(), psi, and rho.
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvmDdt(), and CrankNicolsonDdtScheme< Type >::meshPhi().
fvcDdt() [1/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 156 of file CoEulerDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, dimensioned< Type >::name(), rDeltaT(), and dimensioned< Type >::value().
Referenced by CoEulerDdtScheme< Type >::fvcDdt(), and CoEulerDdtScheme< Type >::mesh().
fvcDdt() [2/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 216 of file CoEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), CoEulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdt() [3/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 267 of file CoEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), CoEulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and dimensioned< Type >::value().
fvcDdt() [4/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 319 of file CoEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), CoEulerDdtScheme< Type >::fvcDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdt() [5/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 374 of file CoEulerDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), CoEulerDdtScheme< Type >::fvmDdt(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvmDdt() [1/4]
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 443 of file CoEulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
Referenced by CoEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvmDdt(), and CoEulerDdtScheme< Type >::mesh().
fvmDdt() [2/4]
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 478 of file CoEulerDdtScheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, CoEulerDdtScheme< Type >::fvmDdt(), internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), fvMatrix< Type >::source(), and dimensioned< Type >::value().
fvmDdt() [3/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 515 of file CoEulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, CoEulerDdtScheme< Type >::fvmDdt(), internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
fvmDdt() [4/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 554 of file CoEulerDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, CoEulerDdtScheme< Type >::fvcDdtUfCorr(), internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), rDeltaT(), and fvMatrix< Type >::source().
fvcDdtUfCorr() [1/4]
tmp< typename CoEulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 596 of file CoEulerDdtScheme.C.
References CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
Referenced by CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and CoEulerDdtScheme< Type >::fvmDdt().
fvcDdtPhiCorr() [1/4]
tmp< typename CoEulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 633 of file CoEulerDdtScheme.C.
References CoEulerDdtScheme< Type >::fvcDdtUfCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), and CoEulerDdtScheme< Type >::fvcDdtUfCorr().
fvcDdtUfCorr() [2/4]
tmp< typename CoEulerDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 665 of file CoEulerDdtScheme.C.
References Foam::abort(), Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
fvcDdtPhiCorr() [2/4]
tmp< typename CoEulerDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 734 of file CoEulerDdtScheme.C.
References Foam::abort(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, Foam::fvc::interpolate(), mesh, CoEulerDdtScheme< Type >::meshPhi(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and rDeltaT().
meshPhi()
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) virtual
Implements ddtScheme< Type >.
Definition at line 797 of file CoEulerDdtScheme.C.
References Foam::dimTime, Foam::dimVolume, mesh, IOobject::NO_READ, IOobject::NO_WRITE, and timeName.
Referenced by CoEulerDdtScheme< Type >::fvcDdtPhiCorr().
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/CoEulerDdtScheme/CoEulerDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/CoEulerDdtScheme/CoEulerDdtScheme.C