OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sweepData Class Reference
Helper class used by fvc::sweep function.
Public Member Functions
sweepData ()
Construct null.
sweepData (const scalar value, const point &origin)
Construct from component.
scalar value () const
Return value.
const point & origin () const
Return origin.
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const sweepData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const sweepData &, TrackingData &td) const
Same (like operator==)
void operator= (const scalar value)
bool operator== (const sweepData &) const
bool operator!= (const sweepData &) const
Friends
Ostream & operator<< (Ostream &os, const sweepData &svf)
Istream & operator>> (Istream &is, sweepData &svf)
Detailed Description
Helper class used by fvc::sweep function.
Source files
sweepData.H
sweepData.H
sweepDataI.H
Definition at line 47 of file sweepData.H.
Constructor & Destructor Documentation
sweepData() [1/2]
sweepData () inline
Construct null.
Definition at line 74 of file sweepDataI.H.
sweepData() [2/2]
sweepData (const scalar value, const point & origin) inline
Construct from component.
Definition at line 81 of file sweepDataI.H.
Member Function Documentation
value()
scalar value () const inline
Return value.
Definition at line 82 of file sweepData.H.
Referenced by sweepData::operator=().
origin()
const point& origin () const inline
Return origin.
Definition at line 88 of file sweepData.H.
References sweepData::enterDomain(), sweepData::equal(), sweepData::leaveDomain(), sweepData::operator!=(), sweepData::operator=(), sweepData::operator==(), sweepData::sameGeometry(), sweepData::transform(), sweepData::updateCell(), sweepData::updateFace(), and sweepData::valid().
Referenced by sweepData::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value
Definition at line 91 of file sweepDataI.H.
References sweepData::sameGeometry().
Referenced by sweepData::origin().
sameGeometry()
bool sameGeometry (const polyMesh & , const sweepData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking
Definition at line 99 of file sweepDataI.H.
References sweepData::leaveDomain().
Referenced by sweepData::origin(), and sweepData::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
Definition at line 112 of file sweepDataI.H.
References sweepData::transform().
Referenced by sweepData::origin(), and sweepData::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 138 of file sweepDataI.H.
References sweepData::updateCell().
Referenced by sweepData::origin(), and sweepData::transform().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 126 of file sweepDataI.H.
References sweepData::enterDomain(), and Foam::transform().
Referenced by sweepData::leaveDomain(), and sweepData::origin().
updateCell()
bool updateCell (const polyMesh & mesh, const label thisCellI, const label neighbourFaceI, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 153 of file sweepDataI.H.
References primitiveMesh::cellCentres(), and sweepData::updateFace().
Referenced by sweepData::enterDomain(), and sweepData::origin().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const label neighbourCellI, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 168 of file sweepDataI.H.
References primitiveMesh::faceCentres().
Referenced by sweepData::origin(), and sweepData::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 184 of file sweepDataI.H.
References sweepData::equal(), and primitiveMesh::faceCentres().
equal()
bool equal (const sweepData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 198 of file sweepDataI.H.
References sweepData::operator==().
Referenced by sweepData::origin(), and sweepData::updateFace().
operator=()
void operator= (const scalar value) inline
Definition at line 210 of file sweepDataI.H.
References sweepData::value().
Referenced by sweepData::origin().
operator==()
bool operator== (const sweepData & rhs) const inline
Definition at line 219 of file sweepDataI.H.
References sweepData::origin().
Referenced by sweepData::equal(), and sweepData::origin().
operator!=()
bool operator!= (const sweepData & rhs) const inline
Definition at line 228 of file sweepDataI.H.
Referenced by sweepData::origin().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const sweepData & svf) friend
Definition at line 197 of file sweepData.H.
operator>>
Istream& operator>> (Istream & is, sweepData & svf) friend
Definition at line 205 of file sweepData.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepData.H
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepDataI.H