OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
faceLimitedGrad< Type > Class Template Reference
faceLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
Public Member Functions
TypeName ("faceLimited")
RunTime type information.
faceLimitedGrad (const fvMesh &mesh, Istream &schemeData)
Construct from mesh and schemeData.
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
template<>
tmp< volVectorField > calcGrad (const volScalarField &vsf, const word &name) const
template<>
tmp< volTensorField > calcGrad (const volVectorField &vsf, const word &name) const
template<>
Foam::tmp< Foam::volVectorField > calcGrad (const volScalarField &vsf, const word &name) const
template<>
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField &vvf, const word &name) const
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type>
class Foam::fv::faceLimitedGrad< Type >
faceLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
The scalar limiter based on limiting the extrapolated face values between the face-neighbour cell values and is applied to all components of the gradient.
Source files
faceLimitedGrad.H
faceLimitedGrad.C
Definition at line 59 of file faceLimitedGrad.H.
Constructor & Destructor Documentation
faceLimitedGrad()
faceLimitedGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from mesh and schemeData.
Definition at line 98 of file faceLimitedGrad.H.
References faceLimitedGrad< Type >::calcGrad(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorIn.
Member Function Documentation
TypeName()
TypeName ("faceLimited")
RunTime type information.
calcGrad() [1/5]
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const inline virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
Definition at line 126 of file faceLimitedGrad.H.
References gradScheme< Type >::grad(), Foam::min(), and Foam::name().
Referenced by faceLimitedGrad< Type >::calcGrad(), and faceLimitedGrad< Type >::faceLimitedGrad().
calcGrad() [2/5]
tmp< volVectorField > calcGrad (const volScalarField & vsf, const word & name) const
calcGrad() [3/5]
tmp< volTensorField > calcGrad (const volVectorField & vsf, const word & name) const
calcGrad() [4/5]
Foam::tmp< Foam::volVectorField > calcGrad (const volScalarField & vsf, const word & name) const
Definition at line 50 of file faceLimitedGrads.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), faceLimitedGrad< Type >::calcGrad(), fvMesh::Cf(), gaussGrad< Type >::correctBoundaryConditions(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), fvPatchField< Type >::coupled(), Foam::endl(), fvPatchField< Type >::fixesValue(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::MULES::limiter(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), and List< T >::size().
calcGrad() [5/5]
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField & vvf, const word & name) const
Definition at line 186 of file faceLimitedGrads.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), gaussGrad< Type >::correctBoundaryConditions(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), fvPatchField< Type >::coupled(), Foam::endl(), fvPatchField< Type >::fixesValue(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::MULES::limiter(), Foam::magSqr(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), and List< T >::size().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/faceLimitedGrad/faceLimitedGrad.H