OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gaussLaplacianScheme< Type, GType > Class Template Reference
Basic second-order laplacian using face-gradients and Gauss' theorem.
Public Member Functions
TypeName ("Gauss")
Runtime type information.
gaussLaplacianScheme (const fvMesh &mesh)
Construct null.
gaussLaplacianScheme (const fvMesh &mesh, Istream &is)
Construct from Istream.
gaussLaplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType > > &igs, const tmp< snGradScheme< Type > > &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~gaussLaplacianScheme ()
Destructor.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< scalar, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< scalar, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< vector, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< vector, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< vector, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< sphericalTensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< symmTensor, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< symmTensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< symmTensor, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< tensor, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< tensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< tensor, fvPatchField, volMesh > &)
template<>
Foam::tmp< Foam::fvMatrix< Foam::scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< scalar, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::GeometricField< Foam::scalar, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< scalar, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix< Foam::vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< vector, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::GeometricField< Foam::vector, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< vector, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix< Foam::sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::GeometricField< Foam::sphericalTensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix< Foam::symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< symmTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::GeometricField< Foam::symmTensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< symmTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix< Foam::tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< tensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::GeometricField< Foam::tensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< tensor, fvPatchField, volMesh > &vf)
Public Member Functions inherited from laplacianScheme< Type, GType >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const fvMesh &mesh)
Construct from mesh.
laplacianScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
laplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType > > &igs, const tmp< snGradScheme< Type > > &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~laplacianScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< fvMatrix< Type > > fvmLaplacianUncorrected (const surfaceScalarField &gammaMagSf, const surfaceScalarField &deltaCoeffs, const GeometricField< Type, fvPatchField, volMesh > &)
Static Public Member Functions inherited from laplacianScheme< Type, GType >
static tmp< laplacianScheme< Type, GType > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new laplacianScheme created on freestore.
Additional Inherited Members
Protected Member Functions inherited from laplacianScheme< Type, GType >
laplacianScheme (const laplacianScheme &)
Disallow copy construct.
void operator= (const laplacianScheme &)
Disallow default bitwise assignment.
Protected Attributes inherited from laplacianScheme< Type, GType >
const fvMesh & mesh_
tmp< surfaceInterpolationScheme< GType > > tinterpGammaScheme_
tmp< snGradScheme< Type > > tsnGradScheme_
Detailed Description
template<class Type, class GType>
class Foam::fv::gaussLaplacianScheme< Type, GType >
Basic second-order laplacian using face-gradients and Gauss' theorem.
Source files
gaussLaplacianScheme.H
gaussLaplacianScheme.C
Definition at line 54 of file gaussLaplacianScheme.H.
Constructor & Destructor Documentation
gaussLaplacianScheme() [1/3]
gaussLaplacianScheme (const fvMesh & mesh) inline
Construct null.
Definition at line 82 of file gaussLaplacianScheme.H.
gaussLaplacianScheme() [2/3]
gaussLaplacianScheme (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
Definition at line 88 of file gaussLaplacianScheme.H.
gaussLaplacianScheme() [3/3]
gaussLaplacianScheme (const fvMesh & mesh, const tmp< surfaceInterpolationScheme< GType > > & igs, const tmp< snGradScheme< Type > > & sngs) inline
Construct from mesh, interpolation and snGradScheme schemes.
Definition at line 95 of file gaussLaplacianScheme.H.
~gaussLaplacianScheme()
virtual ~gaussLaplacianScheme () inline virtual
Destructor.
Definition at line 106 of file gaussLaplacianScheme.H.
References gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), and gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
Member Function Documentation
TypeName()
TypeName ("Gauss")
Runtime type information.
fvmLaplacianUncorrected()
tmp< fvMatrix< Type > > fvmLaplacianUncorrected (const surfaceScalarField & gammaMagSf, const surfaceScalarField & deltaCoeffs, const GeometricField< Type, fvPatchField, volMesh > & vf) static
Definition at line 47 of file gaussLaplacianScheme.C.
References fvMatrix< Type >::boundaryCoeffs(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::component(), fvPatchField< Type >::coupled(), surfaceInterpolation::deltaCoeffs(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, gaussLaplacianScheme< Type, GType >::fvcLaplacian(), Foam::fvc::grad(), fvPatchField< Type >::gradientBoundaryCoeffs(), fvPatchField< Type >::gradientInternalCoeffs(), IOobject::instance(), fvMatrix< Type >::internalCoeffs(), GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::fvc::interpolate(), mesh, IOobject::name(), lduMatrix::negSumDiag(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, and lduMatrix::upper().
Referenced by gaussLaplacianScheme< Type, GType >::~gaussLaplacianScheme().
fvcLaplacian() [1/12]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements laplacianScheme< Type, GType >.
Definition at line 137 of file gaussLaplacianScheme.C.
References Foam::fvc::div(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), fvMesh::magSf(), mesh, IOobject::name(), and Foam::fvc::snGrad().
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and gaussLaplacianScheme< Type, GType >::~gaussLaplacianScheme().
fvmLaplacian() [1/11]
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements laplacianScheme< Type, GType >.
Definition at line 157 of file gaussLaplacianScheme.C.
References Foam::fvc::div(), fvMatrix< Type >::faceFluxCorrectionPtr(), fvSchemes::fluxRequired(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), internalField(), fvMesh::magSf(), mesh, IOobject::name(), tmp< T >::ptr(), fvMesh::Sf(), fvMatrix< Type >::source(), and fvMesh::V().
Referenced by gaussLaplacianScheme< Type, GType >::fvcLaplacian(), and gaussLaplacianScheme< Type, GType >::~gaussLaplacianScheme().
fvcLaplacian() [2/12]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements laplacianScheme< Type, GType >.
Definition at line 204 of file gaussLaplacianScheme.C.
References Foam::fvc::div(), fvMesh::magSf(), mesh, IOobject::name(), fvMesh::Sf(), and Foam::fvc::snGrad().
fvmLaplacian() [2/11]
tmp< fvMatrix< scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< scalar, fvPatchField, volMesh > &)
fvcLaplacian() [3/12]
tmp< GeometricField< scalar, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< scalar, fvPatchField, volMesh > &)
fvmLaplacian() [3/11]
tmp< fvMatrix< vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< vector, fvPatchField, volMesh > &)
fvcLaplacian() [4/12]
tmp< GeometricField< vector, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< vector, fvPatchField, volMesh > &)
fvmLaplacian() [4/11]
tmp< fvMatrix< sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
fvcLaplacian() [5/12]
tmp< GeometricField< sphericalTensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
fvmLaplacian() [5/11]
tmp< fvMatrix< symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< symmTensor, fvPatchField, volMesh > &)
fvcLaplacian() [6/12]
tmp< GeometricField< symmTensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< symmTensor, fvPatchField, volMesh > &)
fvmLaplacian() [6/11]
tmp< fvMatrix< tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< tensor, fvPatchField, volMesh > &)
fvcLaplacian() [7/12]
tmp< GeometricField< tensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< tensor, fvPatchField, volMesh > &)
fvmLaplacian() [7/11]
Foam::tmp< Foam::fvMatrix< Foam::scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< scalar, fvPatchField, volMesh > & vf)
Definition at line 117 of file gaussLaplacianSchemes.C.
fvcLaplacian() [8/12]
Foam::tmp< Foam::GeometricField< Foam::scalar, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< scalar, fvPatchField, volMesh > & vf)
Definition at line 117 of file gaussLaplacianSchemes.C.
fvmLaplacian() [8/11]
Foam::tmp< Foam::fvMatrix< Foam::vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< vector, fvPatchField, volMesh > & vf)
Definition at line 118 of file gaussLaplacianSchemes.C.
fvcLaplacian() [9/12]
Foam::tmp< Foam::GeometricField< Foam::vector, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< vector, fvPatchField, volMesh > & vf)
Definition at line 118 of file gaussLaplacianSchemes.C.
fvmLaplacian() [9/11]
Foam::tmp< Foam::fvMatrix< Foam::sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > & vf)
Definition at line 119 of file gaussLaplacianSchemes.C.
fvcLaplacian() [10/12]
Foam::tmp< Foam::GeometricField< Foam::sphericalTensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > & vf)
Definition at line 119 of file gaussLaplacianSchemes.C.
fvmLaplacian() [10/11]
Foam::tmp< Foam::fvMatrix< Foam::symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< symmTensor, fvPatchField, volMesh > & vf)
Definition at line 120 of file gaussLaplacianSchemes.C.
fvcLaplacian() [11/12]
Foam::tmp< Foam::GeometricField< Foam::symmTensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< symmTensor, fvPatchField, volMesh > & vf)
Definition at line 120 of file gaussLaplacianSchemes.C.
fvmLaplacian() [11/11]
Foam::tmp< Foam::fvMatrix< Foam::tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< tensor, fvPatchField, volMesh > & vf)
Definition at line 121 of file gaussLaplacianSchemes.C.
fvcLaplacian() [12/12]
Foam::tmp< Foam::GeometricField< Foam::tensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< tensor, fvPatchField, volMesh > & vf)
Definition at line 121 of file gaussLaplacianSchemes.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/laplacianSchemes/gaussLaplacianScheme/gaussLaplacianScheme.H
src/finiteVolume/finiteVolume/laplacianSchemes/gaussLaplacianScheme/gaussLaplacianScheme.C