OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
faceCorrectedSnGrad< Type > Class Template Reference
Simple central-difference snGrad scheme with non-orthogonal correction.
Public Member Functions
TypeName ("faceCorrected")
Runtime type information.
faceCorrectedSnGrad (const fvMesh &mesh)
Construct from mesh.
faceCorrectedSnGrad (const fvMesh &mesh, Istream &)
Construct from mesh and data stream.
virtual ~faceCorrectedSnGrad ()
Destructor.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fullGradCorrection (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the faceCorrectedSnGrad.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the faceCorrectedSnGrad.
template<>
tmp< surfaceScalarField > correction (const volScalarField &vsf) const
template<>
tmp< surfaceVectorField > correction (const volVectorField &vvf) const
template<>
Foam::tmp< Foam::surfaceScalarField > correction (const volScalarField &vsf) const
template<>
Foam::tmp< Foam::surfaceVectorField > correction (const volVectorField &vvf) const
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Detailed Description
template<class Type>
class Foam::fv::faceCorrectedSnGrad< Type >
Simple central-difference snGrad scheme with non-orthogonal correction.
Source files
faceCorrectedSnGrad.H
faceCorrectedSnGrad.C
Definition at line 54 of file faceCorrectedSnGrad.H.
Constructor & Destructor Documentation
faceCorrectedSnGrad() [1/2]
faceCorrectedSnGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 73 of file faceCorrectedSnGrad.H.
faceCorrectedSnGrad() [2/2]
faceCorrectedSnGrad (const fvMesh & mesh, Istream &) inline
Construct from mesh and data stream.
Definition at line 80 of file faceCorrectedSnGrad.H.
References faceCorrectedSnGrad< Type >::deltaCoeffs(), and faceCorrectedSnGrad< Type >::~faceCorrectedSnGrad().
~faceCorrectedSnGrad()
~faceCorrectedSnGrad () virtual
Destructor.
Definition at line 33 of file faceCorrectedSnGrad.C.
References faceCorrectedSnGrad< Type >::fullGradCorrection().
Referenced by faceCorrectedSnGrad< Type >::faceCorrectedSnGrad().
Member Function Documentation
TypeName()
TypeName ("faceCorrected")
Runtime type information.
deltaCoeffs()
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 94 of file faceCorrectedSnGrad.H.
References snGradScheme< Type >::mesh(), and surfaceInterpolation::nonOrthDeltaCoeffs().
Referenced by faceCorrectedSnGrad< Type >::faceCorrectedSnGrad().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 102 of file faceCorrectedSnGrad.H.
References faceCorrectedSnGrad< Type >::correction(), and faceCorrectedSnGrad< Type >::fullGradCorrection().
fullGradCorrection()
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > fullGradCorrection (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Return the explicit correction to the faceCorrectedSnGrad.
for the given field using the gradient of the field
Definition at line 42 of file faceCorrectedSnGrad.C.
References fvMesh::C(), faceCorrectedSnGrad< Type >::correction(), DimensionedField< Type, GeoMesh >::dimensions(), polyMesh::faces(), forAll, IOobject::instance(), GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::MULES::interpolate(), fvMesh::magSf(), mesh, IOobject::name(), fvMesh::neighbour(), surfaceInterpolation::nonOrthDeltaCoeffs(), fvMesh::owner(), Foam::constant::mathematical::pi(), points, polyMesh::points(), fvMesh::Sf(), and List< T >::size().
Referenced by faceCorrectedSnGrad< Type >::corrected(), and faceCorrectedSnGrad< Type >::~faceCorrectedSnGrad().
correction() [1/5]
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the faceCorrectedSnGrad.
for the given field using the gradients of the field components
Reimplemented from snGradScheme< Type >.
Definition at line 128 of file faceCorrectedSnGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), DimensionedField< Type, GeoMesh >::dimensions(), IOobject::instance(), mesh, IOobject::name(), surfaceInterpolation::nonOrthDeltaCoeffs(), and GeometricField< Type, PatchField, GeoMesh >::replace().
Referenced by faceCorrectedSnGrad< Type >::corrected(), faceCorrectedSnGrad< Type >::correction(), and faceCorrectedSnGrad< Type >::fullGradCorrection().
correction() [2/5]
tmp< surfaceScalarField > correction (const volScalarField & vsf) const
correction() [3/5]
tmp< surfaceVectorField > correction (const volVectorField & vvf) const
correction() [4/5]
Foam::tmp< Foam::surfaceScalarField > correction (const volScalarField & vsf) const
Definition at line 43 of file faceCorrectedSnGrads.C.
References faceCorrectedSnGrad< Type >::correction().
correction() [5/5]
Foam::tmp< Foam::surfaceVectorField > correction (const volVectorField & vvf) const
Definition at line 54 of file faceCorrectedSnGrads.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/faceCorrectedSnGrad/faceCorrectedSnGrad.H
src/finiteVolume/finiteVolume/snGradSchemes/faceCorrectedSnGrad/faceCorrectedSnGrad.C