OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
smoothData Class Reference
Helper class used by the fvc::smooth and fvc::spread functions.
Classes
class trackData
Class used to pass additional data in.
Public Member Functions
smoothData ()
Construct null.
smoothData (const scalar value)
Construct from inverse field value.
scalar value () const
Return value.
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const smoothData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const smoothData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const smoothData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const smoothData &svf, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const smoothData &, TrackingData &td) const
Same (like operator==)
void operator= (const scalar value)
bool operator== (const smoothData &) const
bool operator!= (const smoothData &) const
Friends
Ostream & operator<< (Ostream &os, const smoothData &svf)
Istream & operator>> (Istream &is, smoothData &svf)
Detailed Description
Helper class used by the fvc::smooth and fvc::spread functions.
Source files
smoothData.H
smoothData.H
smoothDataI.H
Definition at line 47 of file smoothData.H.
Constructor & Destructor Documentation
smoothData() [1/2]
smoothData () inline
Construct null.
Definition at line 64 of file smoothDataI.H.
smoothData() [2/2]
smoothData (const scalar value) inline
Construct from inverse field value.
Definition at line 70 of file smoothDataI.H.
Member Function Documentation
value()
scalar value () const inline
Return value.
Definition at line 97 of file smoothData.H.
References smoothData::enterDomain(), smoothData::equal(), smoothData::leaveDomain(), smoothData::operator!=(), smoothData::operator=(), smoothData::operator==(), smoothData::sameGeometry(), smoothData::transform(), smoothData::updateCell(), smoothData::updateFace(), and smoothData::valid().
Referenced by smoothData::operator=(), and smoothData::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value
Definition at line 79 of file smoothDataI.H.
References smoothData::sameGeometry().
Referenced by smoothData::value().
sameGeometry()
bool sameGeometry (const polyMesh & , const smoothData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking
Definition at line 87 of file smoothDataI.H.
References smoothData::leaveDomain().
Referenced by smoothData::valid(), and smoothData::value().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
Definition at line 100 of file smoothDataI.H.
References smoothData::transform().
Referenced by smoothData::sameGeometry(), and smoothData::value().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 122 of file smoothDataI.H.
References smoothData::updateCell().
Referenced by smoothData::transform(), and smoothData::value().
transform()
void transform (const polyMesh & , const tensor & , TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 112 of file smoothDataI.H.
References smoothData::enterDomain().
Referenced by smoothData::leaveDomain(), and smoothData::value().
updateCell()
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const smoothData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 134 of file smoothDataI.H.
References smoothData::updateFace().
Referenced by smoothData::enterDomain(), and smoothData::value().
updateFace() [1/2]
bool updateFace (const polyMesh & , const label thisFaceI, const label neighbourCellI, const smoothData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 150 of file smoothDataI.H.
Referenced by smoothData::updateCell(), and smoothData::value().
updateFace() [2/2]
bool updateFace (const polyMesh & , const label thisFaceI, const smoothData & svf, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 167 of file smoothDataI.H.
References smoothData::equal().
equal()
bool equal (const smoothData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 182 of file smoothDataI.H.
References smoothData::operator==().
Referenced by smoothData::updateFace(), and smoothData::value().
operator=()
void operator= (const scalar value) inline
Definition at line 194 of file smoothDataI.H.
References smoothData::value().
Referenced by smoothData::value().
operator==()
bool operator== (const smoothData & rhs) const inline
Definition at line 203 of file smoothDataI.H.
References smoothData::value().
Referenced by smoothData::equal(), and smoothData::value().
operator!=()
bool operator!= (const smoothData & rhs) const inline
Definition at line 212 of file smoothDataI.H.
Referenced by smoothData::value().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const smoothData & svf) friend
Definition at line 206 of file smoothData.H.
operator>>
Istream& operator>> (Istream & is, smoothData & svf) friend
Definition at line 214 of file smoothData.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/fvc/fvcSmooth/smoothData.H
src/finiteVolume/finiteVolume/fvc/fvcSmooth/smoothDataI.H