OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
correctedSnGrad< Type > Class Template Reference
Simple central-difference snGrad scheme with non-orthogonal correction.
Public Member Functions
TypeName ("corrected")
Runtime type information.
correctedSnGrad (const fvMesh &mesh)
Construct from mesh.
correctedSnGrad (const fvMesh &mesh, Istream &)
Construct from mesh and data stream.
virtual ~correctedSnGrad ()
Destructor.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fullGradCorrection (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the correctedSnGrad.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the correctedSnGrad.
template<>
tmp< surfaceScalarField > correction (const volScalarField &vsf) const
template<>
tmp< surfaceVectorField > correction (const volVectorField &vvf) const
template<>
Foam::tmp< Foam::surfaceScalarField > correction (const volScalarField &vsf) const
template<>
Foam::tmp< Foam::surfaceVectorField > correction (const volVectorField &vvf) const
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Detailed Description
template<class Type>
class Foam::fv::correctedSnGrad< Type >
Simple central-difference snGrad scheme with non-orthogonal correction.
Source files
correctedSnGrad.H
correctedSnGrad.C
Definition at line 54 of file correctedSnGrad.H.
Constructor & Destructor Documentation
correctedSnGrad() [1/2]
correctedSnGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 73 of file correctedSnGrad.H.
correctedSnGrad() [2/2]
correctedSnGrad (const fvMesh & mesh, Istream &) inline
Construct from mesh and data stream.
Definition at line 80 of file correctedSnGrad.H.
References correctedSnGrad< Type >::deltaCoeffs(), and correctedSnGrad< Type >::~correctedSnGrad().
~correctedSnGrad()
~correctedSnGrad () virtual
Destructor.
Definition at line 36 of file correctedSnGrad.C.
References correctedSnGrad< Type >::fullGradCorrection().
Referenced by correctedSnGrad< Type >::correctedSnGrad().
Member Function Documentation
TypeName()
TypeName ("corrected")
Runtime type information.
deltaCoeffs()
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 94 of file correctedSnGrad.H.
References snGradScheme< Type >::mesh(), and surfaceInterpolation::nonOrthDeltaCoeffs().
Referenced by correctedSnGrad< Type >::correctedSnGrad().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 102 of file correctedSnGrad.H.
References correctedSnGrad< Type >::correction(), and correctedSnGrad< Type >::fullGradCorrection().
fullGradCorrection()
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > fullGradCorrection (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Return the explicit correction to the correctedSnGrad.
for the given field using the gradient of the field
Definition at line 45 of file correctedSnGrad.C.
References correctedSnGrad< Type >::correction(), Foam::fvc::grad(), fvSchemes::gradScheme(), Foam::MULES::interpolate(), mesh, IOobject::name(), and surfaceInterpolation::nonOrthCorrectionVectors().
Referenced by correctedSnGrad< Type >::corrected(), and correctedSnGrad< Type >::~correctedSnGrad().
correction() [1/5]
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the correctedSnGrad.
for the given field using the gradients of the field components
Reimplemented from snGradScheme< Type >.
Definition at line 71 of file correctedSnGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), DimensionedField< Type, GeoMesh >::dimensions(), IOobject::instance(), mesh, IOobject::name(), surfaceInterpolation::nonOrthDeltaCoeffs(), and GeometricField< Type, PatchField, GeoMesh >::replace().
Referenced by correctedSnGrad< Type >::corrected(), correctedSnGrad< Type >::correction(), and correctedSnGrad< Type >::fullGradCorrection().
correction() [2/5]
tmp< surfaceScalarField > correction (const volScalarField & vsf) const
correction() [3/5]
tmp< surfaceVectorField > correction (const volVectorField & vvf) const
correction() [4/5]
Foam::tmp< Foam::surfaceScalarField > correction (const volScalarField & vsf) const
Definition at line 43 of file correctedSnGrads.C.
References correctedSnGrad< Type >::correction().
correction() [5/5]
Foam::tmp< Foam::surfaceVectorField > correction (const volVectorField & vvf) const
Definition at line 54 of file correctedSnGrads.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/correctedSnGrad/correctedSnGrad.H
src/finiteVolume/finiteVolume/snGradSchemes/correctedSnGrad/correctedSnGrad.C