OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
extendedCentredCellToFaceStencil Class Reference
Public Member Functions
extendedCentredCellToFaceStencil (const cellToFaceStencil &)
Construct from uncompacted face stencil.
const mapDistribute & map () const
Return reference to the parallel distribution map.
const labelListList & stencil () const
Return reference to the stencil.
void compact ()
After removing elements from the stencil adapt the schedule (map).
template<class T >
void collectData (const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld) const
Use map to get the data into stencil order.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights) const
Sum vol field contributions to create face values.
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Source files
extendedCentredCellToFaceStencil.H
extendedCentredCellToFaceStencil.C
Definition at line 49 of file extendedCentredCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedCentredCellToFaceStencil()
extendedCentredCellToFaceStencil (const cellToFaceStencil & stencil) explicit
Construct from uncompacted face stencil.
Definition at line 33 of file extendedCentredCellToFaceStencil.C.
References cellToFaceStencil::globalNumbering().
Member Function Documentation
map()
const mapDistribute& map () const inline
Return reference to the parallel distribution map.
Definition at line 85 of file extendedCentredCellToFaceStencil.H.
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), extendedCentredCellToFaceStencil::collectData(), extendedCentredCellToFaceStencil::compact(), and extendedCentredCellToFaceStencil::weightedSum().
stencil()
const labelListList& stencil () const inline
Return reference to the stencil.
Definition at line 91 of file extendedCentredCellToFaceStencil.H.
References extendedCentredCellToFaceStencil::collectData(), and extendedCentredCellToFaceStencil::compact().
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), extendedCentredCellToFaceStencil::collectData(), and extendedCentredCellToFaceStencil::weightedSum().
compact()
void compact ()
After removing elements from the stencil adapt the schedule (map).
Definition at line 57 of file extendedCentredCellToFaceStencil.C.
References forAll, extendedCentredCellToFaceStencil::map(), and UPstream::msgType().
Referenced by extendedCentredCellToFaceStencil::stencil().
collectData()
void collectData (const GeometricField< T, fvPatchField, volMesh > & fld, List< List< T > > & stencilFld) const inline
Use map to get the data into stencil order.
Definition at line 102 of file extendedCentredCellToFaceStencil.H.
References extendedCellToFaceStencil::collectData(), extendedCentredCellToFaceStencil::map(), extendedCentredCellToFaceStencil::stencil(), and extendedCentredCellToFaceStencil::weightedSum().
Referenced by extendedCentredCellToFaceStencil::stencil().
weightedSum()
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > weightedSum (const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & stencilWeights) const inline
Sum vol field contributions to create face values.
Definition at line 119 of file extendedCentredCellToFaceStencil.H.
References extendedCentredCellToFaceStencil::map(), extendedCentredCellToFaceStencil::stencil(), and extendedCellToFaceStencil::weightedSum().
Referenced by extendedCentredCellToFaceStencil::collectData(), CentredFitScheme< Type, Polynomial, Stencil >::correction(), and CentredFitSnGradScheme< Type, Polynomial, Stencil >::correction().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCentredCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCentredCellToFaceStencil.C