OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellToCellStencil Class Reference
baseclass for extended cell centred addressing. Contains per cell a list of neighbouring cells and/or boundaryfaces in global addressing.
Classes
class unionEqOp
Combine operator for labelLists.
Public Member Functions
cellToCellStencil (const polyMesh &)
Construct from mesh.
const polyMesh & mesh () const
const globalIndex & globalNumbering () const
Global numbering for cells and boundary faces.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const List< T > &)
Copy constructor.
List (const Xfer< List< T > > &)
Construct by transferring the parameter contents.
List (List< T > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< T > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const T &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< T > &)
Assign elements to those from UList.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Protected Member Functions
void validBoundaryFaces (boolList &isValidBFace) const
Valid boundary faces (not empty and not coupled)
autoPtr< indirectPrimitivePatch > allCoupledFacesPatch () const
Return patch of all coupled faces.
void insertFaceCells (const label exclude0, const label exclude1, const boolList &nonEmptyFace, const labelList &faceLabels, labelHashSet &globals) const
Collect cell neighbours of faces in global numbering.
labelList calcFaceCells (const boolList &nonEmptyFace, const labelList &faceLabels, labelHashSet &globals) const
Collect cell neighbours of faces in global numbering.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Member Functions
static void merge (const label, const label, const labelList &, labelList &)
Merge two lists.
static void merge (const label, const labelList &, labelList &)
Merge two lists.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Detailed Description
baseclass for extended cell centred addressing. Contains per cell a list of neighbouring cells and/or boundaryfaces in global addressing.
Source files
cellToCellStencil.H
cellToCellStencil.C
Definition at line 54 of file cellToCellStencil.H.
Constructor & Destructor Documentation
cellToCellStencil()
cellToCellStencil (const polyMesh & mesh) explicit
Construct from mesh.
Definition at line 342 of file cellToCellStencil.C.
Member Function Documentation
merge() [1/2]
void merge (const label global0, const label global1, const labelList & listA, labelList & listB) static protected
Merge two lists.
Definition at line 35 of file cellToCellStencil.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::findSortedIndex(), forAll, List< T >::size(), Foam::sort(), and List< T >::transfer().
merge() [2/2]
void merge (const label globalI, const labelList & pGlobals, labelList & cCells) static protected
Merge two lists.
Definition at line 136 of file cellToCellStencil.C.
References forAll, forAllConstIter(), n, and List< T >::setSize().
validBoundaryFaces()
void validBoundaryFaces (boolList & isValidBFace) const protected
Valid boundary faces (not empty and not coupled)
Definition at line 170 of file cellToCellStencil.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), forAll, cellToCellStencil::mesh(), primitiveMesh::nInternalFaces(), patches, List< T >::setSize(), and polyPatch::start().
allCoupledFacesPatch()
Foam::autoPtr< Foam::indirectPrimitivePatch > allCoupledFacesPatch () const protected
Return patch of all coupled faces.
Definition at line 193 of file cellToCellStencil.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), forAll, cellToCellStencil::mesh(), patches, points, and polyPatch::start().
insertFaceCells()
void insertFaceCells (const label exclude0, const label exclude1, const boolList & nonEmptyFace, const labelList & faceLabels, labelHashSet & globals) const protected
Collect cell neighbours of faces in global numbering.
Definition at line 267 of file cellToCellStencil.C.
References cellToCellStencil::calcFaceCells(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, cellToCellStencil::globalNumbering(), HashSet< Key, Hash >::insert(), cellToCellStencil::mesh(), primitiveMesh::nInternalFaces(), and globalIndex::toGlobal().
Referenced by cellToCellStencil::calcFaceCells(), and cellToCellStencil::unionEqOp::operator()().
calcFaceCells()
Foam::labelList calcFaceCells (const boolList & nonEmptyFace, const labelList & faceLabels, labelHashSet & globals) const protected
Collect cell neighbours of faces in global numbering.
Definition at line 319 of file cellToCellStencil.C.
References HashTable< T, Key, Hash >::clear(), cellToCellStencil::insertFaceCells(), and HashTable< T, Key, Hash >::toc().
Referenced by cellToCellStencil::insertFaceCells().
mesh()
const polyMesh& mesh () const inline
Definition at line 122 of file cellToCellStencil.H.
Referenced by cellToCellStencil::allCoupledFacesPatch(), cellToCellStencil::insertFaceCells(), and cellToCellStencil::validBoundaryFaces().
globalNumbering()
const globalIndex& globalNumbering () const inline
Global numbering for cells and boundary faces.
Definition at line 128 of file cellToCellStencil.H.
Referenced by extendedCentredCellToCellStencil::extendedCentredCellToCellStencil(), and cellToCellStencil::insertFaceCells().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToCell/globalIndexStencils/cellToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToCell/globalIndexStencils/cellToCellStencil.C