OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
extendedUpwindCellToFaceStencil Class Reference
Creates upwind stencil by shifting a centred stencil to upwind and downwind faces and optionally removing all non-(up/down)wind faces ('pureUpwind').
Public Member Functions
extendedUpwindCellToFaceStencil (const cellToFaceStencil &, const bool pureUpwind, const scalar minOpposedness)
Construct from mesh and uncompacted centred face stencil.
extendedUpwindCellToFaceStencil (const cellToFaceStencil &)
Construct from mesh and uncompacted centred face stencil. Splits.
bool pureUpwind () const
const mapDistribute & ownMap () const
Return reference to the parallel distribution map.
const mapDistribute & neiMap () const
Return reference to the parallel distribution map.
const labelListList & ownStencil () const
Return reference to the stencil.
const labelListList & neiStencil () const
Return reference to the stencil.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &ownWeights, const List< List< scalar > > &neiWeights) const
Sum vol field contributions to create face values.
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &ownWeights, const List< List< scalar > > &neiWeights) const
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Creates upwind stencil by shifting a centred stencil to upwind and downwind faces and optionally removing all non-(up/down)wind faces ('pureUpwind').
Note: the minOpposedness parameter is to decide which upwind and downwind faces to combine the stencils from. If myArea is the local area and upwindArea the area of the possible upwind candidate it will be included if (upwindArea & myArea)/magSqr(myArea) > minOpposedness so this includes both cosine and area. WIP.
Source files
extendedUpwindCellToFaceStencil.H
extendedUpwindCellToFaceStencil.C
extendedUpwindCellToFaceStencilTemplates.C
Definition at line 59 of file extendedUpwindCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedUpwindCellToFaceStencil() [1/2]
extendedUpwindCellToFaceStencil (const cellToFaceStencil & stencil, const bool pureUpwind, const scalar minOpposedness)
Construct from mesh and uncompacted centred face stencil.
Transports facestencil to create owner and neighbour versions. pureUpwind to remove any remaining downwind cells.
Definition at line 384 of file extendedUpwindCellToFaceStencil.C.
References fvMesh::C(), extendedCellToFaceStencil::collectData(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), forAll, cellToFaceStencil::globalNumbering(), mesh, cellToFaceStencil::mesh(), UPstream::nProcs(), points, List< T >::size(), and List< T >::transfer().
extendedUpwindCellToFaceStencil() [2/2]
extendedUpwindCellToFaceStencil (const cellToFaceStencil & stencil)
Construct from mesh and uncompacted centred face stencil. Splits.
stencil into owner and neighbour (so always pure upwind)
Definition at line 528 of file extendedUpwindCellToFaceStencil.C.
References fvMesh::C(), extendedCellToFaceStencil::collectData(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), forAll, cellToFaceStencil::globalNumbering(), mesh, cellToFaceStencil::mesh(), UPstream::nProcs(), points, List< T >::setSize(), List< T >::size(), and List< T >::transfer().
Member Function Documentation
pureUpwind()
bool pureUpwind () const inline
Definition at line 146 of file extendedUpwindCellToFaceStencil.H.
ownMap()
const mapDistribute& ownMap () const inline
Return reference to the parallel distribution map.
Definition at line 152 of file extendedUpwindCellToFaceStencil.H.
Referenced by pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), and upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject().
neiMap()
const mapDistribute& neiMap () const inline
Return reference to the parallel distribution map.
Definition at line 158 of file extendedUpwindCellToFaceStencil.H.
ownStencil()
const labelListList& ownStencil () const inline
Return reference to the stencil.
Definition at line 164 of file extendedUpwindCellToFaceStencil.H.
Referenced by pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), and upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject().
neiStencil()
const labelListList& neiStencil () const inline
Return reference to the stencil.
Definition at line 170 of file extendedUpwindCellToFaceStencil.H.
References fld(), phi, and extendedUpwindCellToFaceStencil::weightedSum().
weightedSum() [1/2]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > weightedSum (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & ownWeights, const List< List< scalar > > & neiWeights) const
Sum vol field contributions to create face values.
Referenced by PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), UpwindFitScheme< Type, Polynomial, Stencil >::correction(), and extendedUpwindCellToFaceStencil::neiStencil().
weightedSum() [2/2]
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > weightedSum (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & ownWeights, const List< List< scalar > > & neiWeights) const
Definition at line 33 of file extendedUpwindCellToFaceStencilTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvsPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), primitiveMesh::nInternalFaces(), fvsPatchField< Type >::patch(), patchi, sf(), fvMesh::time(), and Time::timeName().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencilTemplates.C