OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
extendedCentredCellToCellStencil Class Reference
Public Member Functions
extendedCentredCellToCellStencil (const cellToCellStencil &)
Construct from uncompacted cell stencil.
const mapDistribute & map () const
Return reference to the parallel distribution map.
const labelListList & stencil () const
Return reference to the stencil.
void compact ()
After removing elements from the stencil adapt the schedule (map).
template<class Type >
void collectData (const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld) const
Use map to get the data into stencil order.
template<class Type , class WeightType >
tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights) const
Sum vol field contributions to create cell values.
Public Member Functions inherited from extendedCellToCellStencil
extendedCellToCellStencil (const polyMesh &)
Construct from mesh.
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToCellStencil
template<class Type , class WeightType >
static tmp< GeometricField< typename outerProduct< WeightType, Type >::type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType > > &stencilWeights)
Sum surface field contributions to create cell values.
Protected Attributes inherited from extendedCellToCellStencil
const polyMesh & mesh_
Detailed Description
Source files
extendedCentredCellToCellStencil.H
extendedCentredCellToCellStencil.C
Definition at line 50 of file extendedCentredCellToCellStencil.H.
Constructor & Destructor Documentation
extendedCentredCellToCellStencil()
extendedCentredCellToCellStencil (const cellToCellStencil & stencil) explicit
Construct from uncompacted cell stencil.
Definition at line 33 of file extendedCentredCellToCellStencil.C.
References cellToCellStencil::globalNumbering().
Member Function Documentation
map()
const mapDistribute& map () const inline
Return reference to the parallel distribution map.
Definition at line 86 of file extendedCentredCellToCellStencil.H.
Referenced by extendedCentredCellToCellStencil::collectData(), extendedCentredCellToCellStencil::compact(), and extendedCentredCellToCellStencil::weightedSum().
stencil()
const labelListList& stencil () const inline
Return reference to the stencil.
Definition at line 92 of file extendedCentredCellToCellStencil.H.
References extendedCentredCellToCellStencil::collectData(), and extendedCentredCellToCellStencil::compact().
Referenced by extendedCentredCellToCellStencil::collectData(), and extendedCentredCellToCellStencil::weightedSum().
compact()
void compact ()
After removing elements from the stencil adapt the schedule (map).
Definition at line 57 of file extendedCentredCellToCellStencil.C.
References forAll, extendedCentredCellToCellStencil::map(), and UPstream::msgType().
Referenced by extendedCentredCellToCellStencil::stencil().
collectData()
void collectData (const GeometricField< Type, fvPatchField, volMesh > & fld, List< List< Type > > & stencilFld) const inline
Use map to get the data into stencil order.
Definition at line 103 of file extendedCentredCellToCellStencil.H.
References extendedCellToFaceStencil::collectData(), extendedCentredCellToCellStencil::map(), extendedCentredCellToCellStencil::stencil(), and extendedCentredCellToCellStencil::weightedSum().
Referenced by extendedCentredCellToCellStencil::stencil(), and LeastSquaresVectors< Stencil >::~LeastSquaresVectors().
weightedSum()
tmp< GeometricField < typename outerProduct<WeightType, Type>::type, fvPatchField, volMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< WeightType > > & stencilWeights) const inline
Sum vol field contributions to create cell values.
Definition at line 128 of file extendedCentredCellToCellStencil.H.
References extendedCentredCellToCellStencil::map(), extendedCentredCellToCellStencil::stencil(), and extendedCellToCellStencil::weightedSum().
Referenced by extendedCentredCellToCellStencil::collectData().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCentredCellToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCentredCellToCellStencil.C