OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
extendedCentredFaceToCellStencil Class Reference
Public Member Functions
extendedCentredFaceToCellStencil (const faceToCellStencil &)
Construct from uncompacted face stencil.
const mapDistribute & map () const
Return reference to the parallel distribution map.
const labelListList & stencil () const
Return reference to the stencil.
void compact ()
After removing elements from the stencil adapt the schedule (map).
template<class T >
void collectData (const GeometricField< T, fvsPatchField, surfaceMesh > &fld, List< List< T > > &stencilFld) const
Use map to get the data into stencil order.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > weightedSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar > > &stencilWeights) const
Sum surface field contributions to create cell values.
Public Member Functions inherited from extendedFaceToCellStencil
extendedFaceToCellStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar > > &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedFaceToCellStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvsPatchField, surfaceMesh > &fld, List< List< T > > &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar > > &stencilWeights)
Sum surface field contributions to create cell values.
Protected Attributes inherited from extendedFaceToCellStencil
const polyMesh & mesh_
Detailed Description
Source files
extendedCentredFaceToCellStencil.H
extendedCentredFaceToCellStencil.C
Definition at line 49 of file extendedCentredFaceToCellStencil.H.
Constructor & Destructor Documentation
extendedCentredFaceToCellStencil()
extendedCentredFaceToCellStencil (const faceToCellStencil & stencil) explicit
Construct from uncompacted face stencil.
Definition at line 33 of file extendedCentredFaceToCellStencil.C.
References faceToCellStencil::globalNumbering().
Member Function Documentation
map()
const mapDistribute& map () const inline
Return reference to the parallel distribution map.
Definition at line 85 of file extendedCentredFaceToCellStencil.H.
Referenced by extendedCentredFaceToCellStencil::collectData(), extendedCentredFaceToCellStencil::compact(), and extendedCentredFaceToCellStencil::weightedSum().
stencil()
const labelListList& stencil () const inline
Return reference to the stencil.
Definition at line 91 of file extendedCentredFaceToCellStencil.H.
References extendedCentredFaceToCellStencil::collectData(), and extendedCentredFaceToCellStencil::compact().
Referenced by extendedCentredFaceToCellStencil::collectData(), and extendedCentredFaceToCellStencil::weightedSum().
compact()
void compact ()
After removing elements from the stencil adapt the schedule (map).
Definition at line 57 of file extendedCentredFaceToCellStencil.C.
References forAll, extendedCentredFaceToCellStencil::map(), and UPstream::msgType().
Referenced by extendedCentredFaceToCellStencil::stencil().
collectData()
void collectData (const GeometricField< T, fvsPatchField, surfaceMesh > & fld, List< List< T > > & stencilFld) const inline
Use map to get the data into stencil order.
Definition at line 102 of file extendedCentredFaceToCellStencil.H.
References extendedFaceToCellStencil::collectData(), extendedCentredFaceToCellStencil::map(), extendedCentredFaceToCellStencil::stencil(), and extendedCentredFaceToCellStencil::weightedSum().
Referenced by extendedCentredFaceToCellStencil::stencil().
weightedSum()
tmp<GeometricField<Type, fvPatchField, volMesh> > weightedSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, const List< List< scalar > > & stencilWeights) const inline
Sum surface field contributions to create cell values.
Definition at line 119 of file extendedCentredFaceToCellStencil.H.
References extendedCentredFaceToCellStencil::map(), extendedCentredFaceToCellStencil::stencil(), and extendedFaceToCellStencil::weightedSum().
Referenced by extendedCentredFaceToCellStencil::collectData().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedCentredFaceToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedCentredFaceToCellStencil.C