OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvPatchMapper Class Reference
Mapping class for a fvPatchField.
Public Member Functions
fvPatchMapper (const fvPatch &patch, const faceMapper &faceMap)
Construct from mappers.
virtual ~fvPatchMapper ()
Destructor.
virtual label size () const
Return size.
virtual label sizeBeforeMapping () const
Return size of field before mapping.
virtual bool direct () const
Is the mapping direct.
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
Return direct addressing.
virtual const labelListList & addressing () const
Return interpolated addressing.
virtual const scalarListList & weights () const
Return interpolaion weights.
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Mapping class for a fvPatchField.
Source files
fvPatchMapper.H
fvPatchMapper.C
Definition at line 55 of file fvPatchMapper.H.
Constructor & Destructor Documentation
fvPatchMapper()
fvPatchMapper (const fvPatch & patch, const faceMapper & faceMap)
Construct from mappers.
Definition at line 224 of file fvPatchMapper.C.
~fvPatchMapper()
~fvPatchMapper () virtual
Destructor.
Definition at line 241 of file fvPatchMapper.C.
Member Function Documentation
size()
virtual label size () const inline virtual
Return size.
Implements FieldMapper.
Definition at line 125 of file fvPatchMapper.H.
References fvPatch::size().
sizeBeforeMapping()
virtual label sizeBeforeMapping () const inline virtual
Return size of field before mapping.
Definition at line 131 of file fvPatchMapper.H.
direct()
virtual bool direct () const inline virtual
Is the mapping direct.
Implements FieldMapper.
Definition at line 137 of file fvPatchMapper.H.
References faceMapper::direct().
Referenced by fvPatchMapper::addressing(), fvPatchMapper::directAddressing(), and fvPatchMapper::weights().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 142 of file fvPatchMapper.H.
References fvPatchMapper::addressing(), fvPatchMapper::directAddressing(), and fvPatchMapper::weights().
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Return direct addressing.
Reimplemented from FieldMapper.
Definition at line 249 of file fvPatchMapper.C.
References Foam::abort(), fvPatchMapper::direct(), Foam::FatalError, and FatalErrorIn.
Referenced by fvPatchMapper::hasUnmapped().
addressing()
const Foam::labelListList & addressing () const virtual
Return interpolated addressing.
Reimplemented from FieldMapper.
Definition at line 269 of file fvPatchMapper.C.
References Foam::abort(), fvPatchMapper::direct(), Foam::FatalError, and FatalErrorIn.
Referenced by fvPatchMapper::hasUnmapped().
weights()
const Foam::scalarListList & weights () const virtual
Return interpolaion weights.
Reimplemented from FieldMapper.
Definition at line 289 of file fvPatchMapper.C.
References Foam::abort(), fvPatchMapper::direct(), Foam::FatalError, and FatalErrorIn.
Referenced by fvPatchMapper::hasUnmapped().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMeshMapper/fvPatchMapper.H
src/finiteVolume/fvMesh/fvMeshMapper/fvPatchMapper.C