OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionCoupledWallFvPatch Class Reference
Foam::regionCoupledWallFvPatch.
Public Member Functions
TypeName (regionCoupledWallPolyPatch::typeName_())
Runtime type information.
regionCoupledWallFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from components.
~regionCoupledWallFvPatch ()
Destructor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual bool coupled () const
Return true because this patch is coupled.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Return neighbour field.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from wallFvPatch
TypeName (wallPolyPatch::typeName_())
Runtime type information.
wallFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from components.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
const word & name () const
Return name.
label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
virtual tmp< vectorField > delta () const
Return cell-centre to face-centre vector.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::PatchFieldType & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::PatchFieldType & lookupPatchField (const word &name, const GeometricField *=NULL, const Type *=NULL) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from regionCoupledBaseFvPatch
TypeName ("regionCoupledBase")
Runtime type information.
regionCoupledBaseFvPatch (const polyPatch &pp, const fvPatch &patch)
Construct from polyPatch.
virtual ~regionCoupledBaseFvPatch ()
Destructor.
virtual label neighbPatchID () const
Return neighbour.
virtual bool owner () const
Is it the owner?
virtual const regionCoupledBaseFvPatch & neighbPatch () const
Return regionCoupledBase neighb Patch.
virtual const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
virtual const polyMesh & nbrMesh () const
Returns neighbour polyMesh.
const fvPatch & patch () const
Return fvPatch.
bool sameRegion () const
Returns if it is the same Region.
const regionCoupledBase & regionCoupledPatch () const
Return regionCoupledPolyPatch.
const fvPatch & neighbFvPatch () const
Return neighbor fvPatch.
const word & regionCoupleType () const
Return the interface type.
Public Member Functions inherited from regionCoupledLduInterface
TypeName ("regionCoupledLduInterface")
Runtime type information.
regionCoupledLduInterface ()
Construct null.
virtual ~regionCoupledLduInterface ()
Destructor.
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions inherited from fvPatch
virtual void makeWeights (scalarField &) const
Make patch weighting factors.
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Protected Member Functions inherited from regionCoupledBaseFvPatch
const fvMesh & nbrFvMesh () const
Returns fvMesh.
Protected Attributes inherited from regionCoupledBaseFvPatch
const regionCoupledBase & regionCoupledBase_
Reference to regionCoupledBase.
const fvPatch & patch_
Reference to fvPatch.
Detailed Description
Foam::regionCoupledWallFvPatch.
Source files
regionCoupledWallFvPatch.H
regionCoupledWallFvPatch.C
Definition at line 52 of file regionCoupledWallFvPatch.H.
Constructor & Destructor Documentation
regionCoupledWallFvPatch()
regionCoupledWallFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from components.
Definition at line 87 of file regionCoupledWallFvPatch.H.
~regionCoupledWallFvPatch()
~regionCoupledWallFvPatch () inline
Destructor.
Definition at line 106 of file regionCoupledWallFvPatch.H.
Member Function Documentation
TypeName()
TypeName (regionCoupledWallPolyPatch::typeName_())
Runtime type information.
faceCells()
virtual const labelUList& faceCells () const inline virtual
Return faceCell addressing.
Implements regionCoupledBaseFvPatch.
Definition at line 116 of file regionCoupledWallFvPatch.H.
References fvPatch::faceCells().
coupled()
virtual bool coupled () const inline virtual
Return true because this patch is coupled.
Reimplemented from fvPatch.
Definition at line 122 of file regionCoupledWallFvPatch.H.
References polyPatch::coupled(), regionCoupledWallFvPatch::initInternalFieldTransfer(), and regionCoupledWallFvPatch::interfaceInternalField().
interfaceInternalField()
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements lduInterface.
Definition at line 42 of file regionCoupledWallFvPatch.C.
References regionCoupledWallFvPatch::internalFieldTransfer().
Referenced by regionCoupledWallFvPatch::coupled().
initInternalFieldTransfer()
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList & iF) const inline virtual
Initialise neighbour field transfer.
Definition at line 140 of file regionCoupledWallFvPatch.H.
References regionCoupledWallFvPatch::internalFieldTransfer().
Referenced by regionCoupledWallFvPatch::coupled().
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Return neighbour field.
Implements lduInterface.
Definition at line 52 of file regionCoupledWallFvPatch.C.
References UList< T >::size().
Referenced by regionCoupledWallFvPatch::initInternalFieldTransfer(), and regionCoupledWallFvPatch::interfaceInternalField().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/derived/regionCoupled/regionCoupledWallFvPatch.H
src/finiteVolume/fvMesh/fvPatches/derived/regionCoupled/regionCoupledWallFvPatch.C