OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionCoupledBaseFvPatch Class Reference abstract
Base class of regionCoupledFvPatch with common functionality for regionCoupledFvPatch and regionCoupledWallFvPatch.
Public Member Functions
TypeName ("regionCoupledBase")
Runtime type information.
regionCoupledBaseFvPatch (const polyPatch &pp, const fvPatch &patch)
Construct from polyPatch.
virtual ~regionCoupledBaseFvPatch ()
Destructor.
virtual label neighbPatchID () const
Return neighbour.
virtual bool owner () const
Is it the owner?
virtual const regionCoupledBaseFvPatch & neighbPatch () const
Return regionCoupledBase neighb Patch.
virtual const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
virtual const polyMesh & nbrMesh () const
Returns neighbour polyMesh.
const fvPatch & patch () const
Return fvPatch.
bool sameRegion () const
Returns if it is the same Region.
const regionCoupledBase & regionCoupledPatch () const
Return regionCoupledPolyPatch.
const fvPatch & neighbFvPatch () const
Return neighbor fvPatch.
const word & regionCoupleType () const
Return the interface type.
virtual const labelUList & faceCells () const =0
Return faceCell addressing.
Public Member Functions inherited from regionCoupledLduInterface
TypeName ("regionCoupledLduInterface")
Runtime type information.
regionCoupledLduInterface ()
Construct null.
virtual ~regionCoupledLduInterface ()
Destructor.
Protected Member Functions
const fvMesh & nbrFvMesh () const
Returns fvMesh.
Protected Attributes
const regionCoupledBase & regionCoupledBase_
Reference to regionCoupledBase.
const fvPatch & patch_
Reference to fvPatch.
Detailed Description
Base class of regionCoupledFvPatch with common functionality for regionCoupledFvPatch and regionCoupledWallFvPatch.
Source files
regionCoupledBaseFvPatch.H
regionCoupledBaseFvPatch.C
Definition at line 53 of file regionCoupledBaseFvPatch.H.
Constructor & Destructor Documentation
regionCoupledBaseFvPatch()
regionCoupledBaseFvPatch (const polyPatch & pp, const fvPatch & patch) inline
Construct from polyPatch.
Definition at line 93 of file regionCoupledBaseFvPatch.H.
Referenced by regionCoupledBaseFvPatch::nbrFvMesh().
~regionCoupledBaseFvPatch()
virtual ~regionCoupledBaseFvPatch () inline virtual
Destructor.
Definition at line 108 of file regionCoupledBaseFvPatch.H.
Member Function Documentation
nbrFvMesh()
const fvMesh& nbrFvMesh () const inline protected
Returns fvMesh.
Definition at line 71 of file regionCoupledBaseFvPatch.H.
References fvPatch::boundaryMesh(), objectRegistry::lookupObject(), fvBoundaryMesh::mesh(), regionCoupledBase::nbrRegionName(), regionCoupledBaseFvPatch::regionCoupledBaseFvPatch(), fvMesh::time(), and regionCoupledBaseFvPatch::TypeName().
Referenced by regionCoupledBaseFvPatch::neighbFvPatch(), and regionCoupledBaseFvPatch::neighbPatch().
TypeName()
TypeName ("regionCoupledBase")
Runtime type information.
Referenced by regionCoupledBaseFvPatch::nbrFvMesh().
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Return neighbour.
Implements regionCoupledLduInterface.
Definition at line 117 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::neighbPatchID().
owner()
virtual bool owner () const inline virtual
Is it the owner?
Implements regionCoupledLduInterface.
Definition at line 123 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::owner().
neighbPatch()
virtual const regionCoupledBaseFvPatch& neighbPatch () const inline virtual
Return regionCoupledBase neighb Patch.
Implements regionCoupledLduInterface.
Definition at line 129 of file regionCoupledBaseFvPatch.H.
References fvMesh::boundary(), regionCoupledBaseFvPatch::nbrFvMesh(), and regionCoupledBase::neighbPatchID().
AMI()
virtual const AMIPatchToPatchInterpolation& AMI () const inline virtual
Return a reference to the AMI interpolator.
Definition at line 141 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::AMI().
nbrMesh()
virtual const polyMesh& nbrMesh () const inline virtual
Returns neighbour polyMesh.
Implements regionCoupledLduInterface.
Definition at line 147 of file regionCoupledBaseFvPatch.H.
References fvPatch::boundaryMesh(), objectRegistry::lookupObject(), fvBoundaryMesh::mesh(), regionCoupledBase::nbrRegionName(), and fvMesh::time().
patch()
const fvPatch& patch () const inline
Return fvPatch.
Definition at line 159 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::patch_.
sameRegion()
bool sameRegion () const inline
Returns if it is the same Region.
Definition at line 165 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::sameRegion().
regionCoupledPatch()
const regionCoupledBase& regionCoupledPatch () const inline
Return regionCoupledPolyPatch.
Definition at line 171 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::regionCoupledBase_.
neighbFvPatch()
const fvPatch& neighbFvPatch () const inline
Return neighbor fvPatch.
Definition at line 177 of file regionCoupledBaseFvPatch.H.
References fvMesh::boundary(), regionCoupledBaseFvPatch::nbrFvMesh(), and regionCoupledBase::neighbPatchID().
regionCoupleType()
const word& regionCoupleType () const inline
Return the interface type.
Definition at line 189 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::faceCells(), and regionCoupledBase::regionCoupleType().
Referenced by energyRegionCoupledFvPatchScalarField::interfaceFieldType().
faceCells()
virtual const labelUList& faceCells () const pure virtual
Return faceCell addressing.
Implemented in regionCoupledWallFvPatch, and regionCoupledFvPatch.
Referenced by regionCoupledBaseFvPatch::regionCoupleType().
Member Data Documentation
regionCoupledBase_
const regionCoupledBase& regionCoupledBase_ protected
Reference to regionCoupledBase.
Definition at line 62 of file regionCoupledBaseFvPatch.H.
Referenced by regionCoupledBaseFvPatch::regionCoupledPatch().
patch_
const fvPatch& patch_ protected
Reference to fvPatch.
Definition at line 65 of file regionCoupledBaseFvPatch.H.
Referenced by regionCoupledBaseFvPatch::patch().
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/fvPatches/derived/regionCoupled/regionCoupledBaseFvPatch.H