OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicACMIFvPatch Class Reference
Cyclic patch for Arbitrarily Coupled Mesh Interface (ACMI)
Public Member Functions
TypeName (cyclicACMIPolyPatch::typeName_())
Runtime type information.
cyclicACMIFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
const cyclicACMIPolyPatch & cyclicACMIPatch () const
Return local reference cast into the cyclic patch.
virtual label neighbPatchID () const
Return neighbour.
virtual bool owner () const
virtual const cyclicACMIFvPatch & neighbPatch () const
Return neighbour fvPatch.
virtual label nonOverlapPatchID () const
Return neighbour.
virtual const fvPatch & nonOverlapPatch () const
Return non-overlapping fvPatch.
virtual const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
const cyclicACMIFvPatch & neighbFvPatch () const
virtual bool coupled () const
Return true if this patch is coupled. This is equivalent.
virtual tmp< vectorField > delta () const
Return delta (P to N) vectors across coupled patch.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fldCoupled) const
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tfldCoupled) const
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fldCoupled, const Field< Type > &fldNonOverlap) const
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tFldCoupled, const tmp< Field< Type > > &tFldNonOverlap) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Return neighbour field.
Public Member Functions inherited from coupledFvPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
virtual ~coupledFvPatch ()
Destructor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
const word & name () const
Return name.
label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::PatchFieldType & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::PatchFieldType & lookupPatchField (const word &name, const GeometricField *=NULL, const Type *=NULL) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from cyclicACMILduInterface
TypeName ("cyclicACMILduInterface")
Runtime type information.
cyclicACMILduInterface ()
Construct null.
virtual ~cyclicACMILduInterface ()
Destructor.
Public Member Functions inherited from cyclicAMILduInterface
TypeName ("cyclicAMILduInterface")
Runtime type information.
cyclicAMILduInterface ()
Construct null.
virtual ~cyclicAMILduInterface ()
Destructor.
Protected Member Functions
void updateAreas () const
Update the patch areas after AMI update.
void makeWeights (scalarField &) const
Make patch weighting factors.
Protected Member Functions inherited from fvPatch
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Detailed Description
Cyclic patch for Arbitrarily Coupled Mesh Interface (ACMI)
Source files
cyclicACMIFvPatch.H
cyclicACMIFvPatch.C
Definition at line 51 of file cyclicACMIFvPatch.H.
Constructor & Destructor Documentation
cyclicACMIFvPatch()
cyclicACMIFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from polyPatch.
Definition at line 81 of file cyclicACMIFvPatch.H.
Member Function Documentation
updateAreas()
void updateAreas () const protected
Update the patch areas after AMI update.
Definition at line 42 of file cyclicACMIFvPatch.C.
References polyPatch::faceAreas(), Foam::mag(), fvPatch::magSf(), cyclicACMIFvPatch::nonOverlapPatch(), fvPatch::patch(), and fvPatch::Sf().
Referenced by cyclicACMIFvPatch::AMI(), and cyclicACMIFvPatch::interpolate().
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Make patch weighting factors.
Implements coupledFvPatch.
Definition at line 79 of file cyclicACMIFvPatch.C.
References coupledFvPatch::delta(), fvPatch::delta(), forAll, Foam::interpolate(), fvPatch::makeWeights(), and fvPatch::nf().
TypeName()
TypeName (cyclicACMIPolyPatch::typeName_())
Runtime type information.
cyclicACMIPatch()
const cyclicACMIPolyPatch& cyclicACMIPatch () const inline
Return local reference cast into the cyclic patch.
Definition at line 94 of file cyclicACMIFvPatch.H.
Referenced by cyclicACMIFvPatchField< Type >::cyclicACMIPatch().
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Return neighbour.
Implements cyclicAMILduInterface.
Definition at line 100 of file cyclicACMIFvPatch.H.
References cyclicAMIPolyPatch::neighbPatchID().
owner()
virtual bool owner () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 105 of file cyclicACMIFvPatch.H.
References cyclicAMIPolyPatch::owner().
neighbPatch()
virtual const cyclicACMIFvPatch& neighbPatch () const inline virtual
Return neighbour fvPatch.
Implements cyclicAMILduInterface.
Definition at line 111 of file cyclicACMIFvPatch.H.
References fvPatch::boundaryMesh(), and cyclicAMIPolyPatch::neighbPatchID().
nonOverlapPatchID()
virtual label nonOverlapPatchID () const inline virtual
Return neighbour.
Definition at line 120 of file cyclicACMIFvPatch.H.
References cyclicACMIPolyPatch::nonOverlapPatchID().
Referenced by cyclicACMIFvPatch::nonOverlapPatch().
nonOverlapPatch()
virtual const fvPatch& nonOverlapPatch () const inline virtual
Return non-overlapping fvPatch.
Definition at line 126 of file cyclicACMIFvPatch.H.
References fvPatch::boundaryMesh(), and cyclicACMIFvPatch::nonOverlapPatchID().
Referenced by cyclicACMIFvPatch::updateAreas().
AMI()
virtual const AMIPatchToPatchInterpolation& AMI () const inline virtual
Return a reference to the AMI interpolator.
Implements cyclicAMILduInterface.
Definition at line 132 of file cyclicACMIFvPatch.H.
References cyclicAMIPolyPatch::AMI(), and cyclicACMIFvPatch::updateAreas().
parallel()
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Implements coupledFvPatch.
Definition at line 143 of file cyclicACMIFvPatch.H.
References coupledPolyPatch::parallel().
Referenced by cyclicACMIFvPatchField< Type >::doTransform().
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements coupledFvPatch.
Definition at line 149 of file cyclicACMIFvPatch.H.
References coupledPolyPatch::forwardT().
Referenced by cyclicACMIFvPatchField< Type >::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements coupledFvPatch.
Definition at line 155 of file cyclicACMIFvPatch.H.
References coupledPolyPatch::reverseT().
Referenced by cyclicACMIFvPatchField< Type >::reverseT().
neighbFvPatch()
const cyclicACMIFvPatch& neighbFvPatch () const inline
Definition at line 160 of file cyclicACMIFvPatch.H.
References fvPatch::boundaryMesh(), cyclicACMIFvPatch::coupled(), cyclicACMIFvPatch::delta(), cyclicACMIFvPatch::interpolate(), and cyclicAMIPolyPatch::neighbPatchID().
coupled()
bool coupled () const virtual
Return true if this patch is coupled. This is equivalent.
to the coupledPolyPatch::coupled() if parallel running or both sides present, false otherwise
Reimplemented from coupledFvPatch.
Definition at line 115 of file cyclicACMIFvPatch.C.
References UPstream::parRun().
Referenced by cyclicACMIFvPatch::neighbFvPatch().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Return delta (P to N) vectors across coupled patch.
Implements coupledFvPatch.
Definition at line 121 of file cyclicACMIFvPatch.C.
References coupledFvPatch::delta(), fvPatch::delta(), forAll, cyclicACMIFvPatch::interfaceInternalField(), Foam::interpolate(), List< T >::size(), fvPatch::size(), Foam::transform(), and Vector< Cmpt >::zero.
Referenced by cyclicACMIFvPatch::neighbFvPatch().
interpolate() [1/4]
tmp<Field<Type> > interpolate (const Field< Type > & fldCoupled) const inline
Definition at line 178 of file cyclicACMIFvPatch.H.
References cyclicACMIFvPatch::updateAreas().
Referenced by cyclicACMIFvPatch::interpolate(), and cyclicACMIFvPatch::neighbFvPatch().
interpolate() [2/4]
tmp<Field<Type> > interpolate (const tmp< Field< Type > > & tfldCoupled) const inline
Definition at line 193 of file cyclicACMIFvPatch.H.
References cyclicACMIFvPatch::interpolate(), and cyclicACMIFvPatch::updateAreas().
interpolate() [3/4]
tmp<Field<Type> > interpolate (const Field< Type > & fldCoupled, const Field< Type > & fldNonOverlap) const inline
Definition at line 208 of file cyclicACMIFvPatch.H.
References cyclicACMIFvPatch::interpolate(), cyclicACMIPolyPatch::interpolate(), and cyclicACMIFvPatch::updateAreas().
interpolate() [4/4]
tmp<Field<Type> > interpolate (const tmp< Field< Type > > & tFldCoupled, const tmp< Field< Type > > & tFldNonOverlap) const inline
Definition at line 225 of file cyclicACMIFvPatch.H.
References cyclicACMIFvPatch::interfaceInternalField(), cyclicACMIFvPatch::internalFieldTransfer(), cyclicACMIPolyPatch::interpolate(), and cyclicACMIFvPatch::updateAreas().
interfaceInternalField()
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements coupledFvPatch.
Definition at line 185 of file cyclicACMIFvPatch.C.
References cyclicACMIFvPatch::internalFieldTransfer().
Referenced by cyclicACMIFvPatch::delta(), and cyclicACMIFvPatch::interpolate().
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Return neighbour field.
Implements coupledFvPatch.
Definition at line 194 of file cyclicACMIFvPatch.C.
Referenced by cyclicACMIFvPatch::interfaceInternalField(), and cyclicACMIFvPatch::interpolate().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/constraint/cyclicACMI/cyclicACMIFvPatch.H
src/finiteVolume/fvMesh/fvPatches/constraint/cyclicACMI/cyclicACMIFvPatch.C