OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reflectionVectors Class Reference
Container for reflection vectors (= unit normal of nearest wall)
Public Member Functions
reflectionVectors (const fvMesh &mesh)
Construct from mesh.
const volVectorField & n () const
void correct ()
Correct for mesh geom/topo changes.
Protected Attributes
volVectorField n_
Detailed Description
Container for reflection vectors (= unit normal of nearest wall)
Source files
reflectionVectors.H
reflectionVectors.C
Definition at line 47 of file reflectionVectors.H.
Constructor & Destructor Documentation
reflectionVectors()
reflectionVectors (const fvMesh & mesh)
Construct from mesh.
Definition at line 33 of file reflectionVectors.C.
References reflectionVectors::correct().
Member Function Documentation
n()
const volVectorField& n () const inline
Definition at line 78 of file reflectionVectors.H.
References reflectionVectors::correct(), and reflectionVectors::n_.
Referenced by LaunderGibsonRSTM::correct().
correct()
void correct ()
Correct for mesh geom/topo changes.
Definition at line 54 of file reflectionVectors.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), reflectionVectors::n_, patches, patchi, and fvMesh::Sf().
Referenced by wallDistReflection::correct(), reflectionVectors::n(), and reflectionVectors::reflectionVectors().
Member Data Documentation
n_
volVectorField n_ protected
Definition at line 54 of file reflectionVectors.H.
Referenced by reflectionVectors::correct(), and reflectionVectors::n().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/reflectionVectors.H
src/finiteVolume/fvMesh/wallDist/reflectionVectors.C