OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nearWallDist Class Reference
Distance calculation for cells with face on a wall. Searches pointNeighbours to find closest.
Public Member Functions
nearWallDist (const fvMesh &mesh)
Construct from components.
virtual ~nearWallDist ()
Destructor.
const volScalarField::GeometricBoundaryField & y () const
virtual void correct ()
Correct for mesh geom/topo changes.
Public Member Functions inherited from GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField
GeometricBoundaryField (const BoundaryMesh &)
Construct from a BoundaryMesh.
GeometricBoundaryField (const BoundaryMesh &, const DimensionedInternalField &, const word &)
Construct from a BoundaryMesh,.
GeometricBoundaryField (const BoundaryMesh &, const DimensionedInternalField &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Construct from a BoundaryMesh,.
GeometricBoundaryField (const BoundaryMesh &, const DimensionedInternalField &, const PtrList< PatchField< Type > > &)
Construct from a BoundaryMesh,.
GeometricBoundaryField (const DimensionedInternalField &, const GeometricBoundaryField &)
Construct as copy setting the reference to the internal field.
GeometricBoundaryField (const GeometricBoundaryField &)
Construct as copy.
GeometricBoundaryField (const BoundaryMesh &, const DimensionedInternalField &, const dictionary &)
Construct from dictionary.
void readField (const DimensionedField< Type, GeoMesh > &field, const dictionary &dict)
Read the boundary field.
void updateCoeffs ()
Update the boundary condition coefficients.
void evaluate ()
Evaluate boundary conditions.
wordList types () const
Return a list of the patch types.
GeometricBoundaryField boundaryInternalField () const
Return BoundaryField of the cell values neighbouring.
LduInterfaceFieldPtrsList< Type > interfaces () const
Return a list of pointers for each patch field with only those.
lduInterfaceFieldPtrsList scalarInterfaces () const
Return a list of pointers for each patch field with only those.
void writeEntry (const word &keyword, Ostream &os) const
Write boundary field as dictionary entry.
void operator= (const GeometricBoundaryField &)
Assignment to BoundaryField<Type, PatchField, BoundaryMesh>
void operator= (const FieldField< PatchField, Type > &)
Assignment to FieldField<PatchField, Type>
void operator= (const Type &)
Assignment to Type.
void operator== (const GeometricBoundaryField &)
Forced assignment to.
void operator== (const FieldField< PatchField, Type > &)
Forced assignment to FieldField<PatchField, Type>
void operator== (const Type &)
Forced assignment to Type.
Public Member Functions inherited from FieldField< PatchField, Type >
FieldField ()
Construct null.
FieldField (const label)
Construct given size.
FieldField (const word &, const FieldField< PatchField, Type > &)
Construct using the Field sizes from the given FieldField.
FieldField (const FieldField< PatchField, Type > &)
Construct as copy.
FieldField (FieldField< PatchField, Type > &, bool reUse)
Construct as copy or re-use as specified.
FieldField (const PtrList< PatchField< Type > > &)
Construct as copy of a PtrList<Field, Type>
FieldField (Istream &)
Construct as copy of tmp<FieldField>
tmp< FieldField< PatchField, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< PatchField, cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< PatchField, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< PatchField, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< PatchField, Type > &)
void operator= (const tmp< FieldField< PatchField, Type > > &)
void operator= (const Type &)
void operator+= (const FieldField< PatchField, Type > &)
void operator+= (const tmp< FieldField< PatchField, Type > > &)
void operator+= (const Type &)
void operator-= (const FieldField< PatchField, Type > &)
void operator-= (const tmp< FieldField< PatchField, Type > > &)
void operator-= (const Type &)
void operator*= (const FieldField< PatchField, scalar > &)
void operator*= (const tmp< FieldField< PatchField, scalar > > &)
void operator*= (const scalar &)
void operator/= (const FieldField< PatchField, scalar > &)
void operator/= (const tmp< FieldField< PatchField, scalar > > &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from PtrList< PatchField< Type > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< PatchField< Type > > &)
Copy constructor.
PtrList (const PtrList< PatchField< Type > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< PatchField< Type > > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< PatchField< Type > > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< PatchField< Type > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
PatchField< Type > & first ()
Return reference to the first element of the list.
const PatchField< Type > & first () const
Return reference to first element of the list.
PatchField< Type > & last ()
Return reference to the last element of the list.
const PatchField< Type > & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (PatchField< Type > *)
Append an element at the end of the list.
void append (const autoPtr< PatchField< Type > > &)
void append (const tmp< PatchField< Type > > &)
void transfer (PtrList< PatchField< Type > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< PatchField< Type > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< PatchField< Type > > set (const label, PatchField< Type > *)
Set element. Return old element (can be NULL).
autoPtr< PatchField< Type > > set (const label, const autoPtr< PatchField< Type > > &)
autoPtr< PatchField< Type > > set (const label, const tmp< PatchField< Type > > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const PatchField< Type > & operator[] (const label) const
Return element const reference.
PatchField< Type > & operator[] (const label)
Return element reference.
const PatchField< Type > * operator() (const label) const
Return element const pointer.
PtrList< PatchField< Type > > & operator= (const PtrList< PatchField< Type > > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
Additional Inherited Members
Public Types inherited from FieldField< PatchField, Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from PtrList< PatchField< Type > >
typedef PatchField< Type > value_type
Type of values the PtrList contains.
typedef PatchField< Type > & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const PatchField< Type > & const_reference
Type that can be used for storing into constant PtrList::value_type.
Static Public Member Functions inherited from FieldField< PatchField, Type >
static tmp< FieldField< PatchField, Type > > NewCalculatedType (const FieldField< PatchField, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Protected Member Functions inherited from PtrList< PatchField< Type > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Distance calculation for cells with face on a wall. Searches pointNeighbours to find closest.
Source files
nearWallDist.H
nearWallDist.C
Definition at line 51 of file nearWallDist.H.
Constructor & Destructor Documentation
nearWallDist()
nearWallDist (const fvMesh & mesh)
Construct from components.
Definition at line 94 of file nearWallDist.C.
~nearWallDist()
~nearWallDist () virtual
Destructor.
Definition at line 110 of file nearWallDist.C.
Member Function Documentation
y()
const volScalarField::GeometricBoundaryField& y () const inline
Definition at line 87 of file nearWallDist.H.
References nearWallDist::correct().
correct()
void correct () virtual
Correct for mesh geom/topo changes.
Definition at line 116 of file nearWallDist.C.
References fvMesh::boundary(), forAll, fvPatchField< Type >::New(), PtrList< PatchField< Type > >::setSize(), PtrList< T >::size(), polyMesh::topoChanging(), and fvMesh::V().
Referenced by turbulenceModel::correct(), and nearWallDist::y().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/nearWallDist.H
src/finiteVolume/fvMesh/wallDist/nearWallDist.C