OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvPatch Class Reference
A finiteVolume patch using a polyPatch and a fvBoundaryMesh.
Public Types
typedef fvBoundaryMesh BoundaryMesh
Public Member Functions
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
const word & name () const
Return name.
label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
virtual bool coupled () const
Return true if this patch is coupled.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
virtual const labelUList & faceCells () const
Return faceCells.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
virtual tmp< vectorField > delta () const
Return cell-centre to face-centre vector.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::PatchFieldType & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::PatchFieldType & lookupPatchField (const word &name, const GeometricField *=NULL, const Type *=NULL) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Static Public Member Functions
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions
virtual void makeWeights (scalarField &) const
Make patch weighting factors.
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Friends
class fvBoundaryMesh
class surfaceInterpolation
Detailed Description
A finiteVolume patch using a polyPatch and a fvBoundaryMesh.
Source files
fvPatch.H
fvPatch.C
fvPatchNew.C
Definition at line 61 of file fvPatch.H.
Member Typedef Documentation
BoundaryMesh
typedef fvBoundaryMesh BoundaryMesh
Definition at line 97 of file fvPatch.H.
Constructor & Destructor Documentation
fvPatch()
fvPatch (const polyPatch & p, const fvBoundaryMesh & bm)
Construct from polyPatch and fvBoundaryMesh.
Definition at line 46 of file fvPatch.C.
~fvPatch()
~fvPatch () virtual
Destructor.
Definition at line 55 of file fvPatch.C.
Member Function Documentation
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Make patch weighting factors.
Reimplemented in cyclicACMIFvPatch, coupledFvPatch, cyclicFvPatch, cyclicAMIFvPatch, and processorFvPatch.
Definition at line 150 of file fvPatch.C.
Referenced by cyclicAMIFvPatch::makeWeights(), and cyclicACMIFvPatch::makeWeights().
initMovePoints()
void initMovePoints () protected virtual
Initialise the patches for moving points.
Definition at line 156 of file fvPatch.C.
Referenced by fvBoundaryMesh::movePoints().
movePoints()
void movePoints () protected virtual
Correct patches after moving points.
Definition at line 160 of file fvPatch.C.
Referenced by fvBoundaryMesh::movePoints().
TypeName()
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , fvPatch , polyPatch , (const polyPatch &patch, const fvBoundaryMesh &bm) , (patch, bm))
New()
Foam::autoPtr< Foam::fvPatch > New (const polyPatch & patch, const fvBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from polyPatch.
Definition at line 33 of file fvPatchNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
Referenced by fvMeshAdder::add(), and meshRefinement::appendPatch().
patch()
const polyPatch& patch () const inline
Return the polyPatch.
Definition at line 143 of file fvPatch.H.
Referenced by nearWallFields::calcAddressing(), fvMeshSubset::interpolate(), mappedFixedValueFvPatchField< Type >::mapper(), NamedEnum< directionType, 3 >::names(), cyclicACMIFvPatch::updateAreas(), cellMotionFvPatchField< Type >::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), regionSizeDistribution::write(), and leastSquaresVectors::~leastSquaresVectors().
name()
const word& name () const inline
Return name.
Definition at line 149 of file fvPatch.H.
References patchIdentifier::name().
Referenced by fWallFunctionFvPatchScalarField::checkType(), v2WallFunctionFvPatchScalarField::checkType(), kLowReWallFunctionFvPatchScalarField::checkType(), epsilonWallFunctionFvPatchScalarField::checkType(), omegaWallFunctionFvPatchScalarField::checkType(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), fvPatch::patchSlice(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), and thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs().
start()
label start () const inline
Return start label of this patch in the polyMesh face list.
Definition at line 155 of file fvPatch.H.
References polyPatch::start().
Referenced by nearWallFields::calcAddressing(), CentredFitSnGradData< Polynomial >::calcFit(), CentredFitData< Polynomial >::CentredFitData(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), pointLinear< Type >::correction(), fvMeshSubset::interpolate(), mappedPatchFieldBase< Type >::mappedField(), fvPatch::patchSlice(), dynamicRefineFvMesh::refine(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), and UpwindFitData< Polynomial >::UpwindFitData().
size()
virtual label size () const inline virtual
Return size.
Reimplemented in emptyFvPatch.
Definition at line 161 of file fvPatch.H.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), fvPatch::Cn(), cyclicACMIFvPatch::delta(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField(), filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField(), fvPatchField< Type >::fvPatchField(), fvsPatchField< Type >::fvsPatchField(), greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField(), inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), fvMeshSubset::interpolate(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField(), fvPatch::patchSlice(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField(), pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField(), pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField(), pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField(), prghPressureFvPatchScalarField::prghPressureFvPatchScalarField(), fvPatchMapper::size(), SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField(), SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), totalPressureFvPatchScalarField::totalPressureFvPatchScalarField(), totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField(), turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField(), turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField(), uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField(), variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField(), wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField(), waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch is coupled.
Reimplemented in cyclicACMIFvPatch, cyclicAMIFvPatch, regionCoupledWallFvPatch, regionCoupledFvPatch, processorFvPatch, and coupledFvPatch.
Definition at line 167 of file fvPatch.H.
References fvPatch::constraintType(), fvPatch::constraintTypes(), and polyPatch::coupled().
constraintType()
bool constraintType (const word & pt) static
Return true if the given type is a constraint type.
Definition at line 61 of file fvPatch.C.
Referenced by fvPatch::constraintTypes(), and fvPatch::coupled().
constraintTypes()
Foam::wordList constraintTypes () static
Return a list of all the constraint patch types.
Definition at line 67 of file fvPatch.C.
References fvPatch::constraintType(), and List< T >::setSize().
Referenced by fvPatch::coupled().
index()
label index () const inline
Return the index of this patch in the fvBoundaryMesh.
Definition at line 179 of file fvPatch.H.
References patchIdentifier::index().
Referenced by epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), fvPatch::Cf(), fvPatch::deltaCoeffs(), fvPatch::magSf(), fvPatch::Sf(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), energyJumpAMIFvPatchScalarField::updateCoeffs(), energyJumpFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), and fvPatch::weights().
boundaryMesh()
const fvBoundaryMesh& boundaryMesh () const inline
Return boundaryMesh reference.
Definition at line 185 of file fvPatch.H.
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), fvPatch::Cf(), fvPatch::Cn(), fvPatch::deltaCoeffs(), fvPatch::magSf(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBaseFvPatch::nbrMesh(), cyclicFvPatch::neighbFvPatch(), cyclicAMIFvPatch::neighbFvPatch(), cyclicACMIFvPatch::neighbFvPatch(), cyclicFvPatch::neighbPatch(), cyclicAMIFvPatch::neighbPatch(), cyclicACMIFvPatch::neighbPatch(), cyclicACMIFvPatch::nonOverlapPatch(), fvPatch::Sf(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), and fvPatch::weights().
patchSlice()
const List<T>::subList patchSlice (const List< T > & l) const inline
Slice list to patch.
Definition at line 192 of file fvPatch.H.
References fvPatch::Cf(), fvPatch::Cn(), fvPatch::delta(), fvPatch::deltaCoeffs(), fvPatch::faceCells(), fvPatch::lookupPatchField(), fvPatch::magSf(), fvPatch::name(), fvPatch::nf(), fvPatch::patchField(), fvPatch::patchInternalField(), fvPatch::Sf(), fvPatch::size(), fvPatch::start(), and fvPatch::weights().
faceCells()
const Foam::labelUList & faceCells () const virtual
Return faceCells.
Reimplemented in regionCoupledWallFvPatch, regionCoupledFvPatch, coupledFvPatch, and emptyFvPatch.
Definition at line 93 of file fvPatch.C.
References polyPatch::faceCells().
Referenced by curvatureSeparation::calcCosAngle(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), fvPatch::Cn(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), LRR::correct(), LaunderGibsonRSTM::correct(), pointLinear< Type >::correction(), coupledFvPatch::faceCells(), regionCoupledFvPatch::faceCells(), regionCoupledWallFvPatch::faceCells(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), energyRegionCoupledFvPatchScalarField::patchNeighbourField(), fvPatch::patchSlice(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
Cf()
const Foam::vectorField & Cf () const
Return face centres.
Definition at line 99 of file fvPatch.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatch::boundaryMesh(), fvMesh::Cf(), fvPatch::index(), and fvBoundaryMesh::mesh().
Referenced by fvPatch::delta(), and fvPatch::patchSlice().
Cn()
Foam::tmp< Foam::vectorField > Cn () const
Return neighbour cell centres.
Definition at line 105 of file fvPatch.C.
References fvPatch::boundaryMesh(), primitiveMesh::cellCentres(), fvPatch::faceCells(), forAll, fvBoundaryMesh::mesh(), and fvPatch::size().
Referenced by fvPatch::delta(), and fvPatch::patchSlice().
Sf()
const Foam::vectorField & Sf () const
Return face area vectors.
Definition at line 130 of file fvPatch.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatch::boundaryMesh(), fvPatch::index(), fvBoundaryMesh::mesh(), and fvMesh::Sf().
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), fvPatch::nf(), fvPatch::patchSlice(), and cyclicACMIFvPatch::updateAreas().
magSf()
const Foam::scalarField & magSf () const
Return face area magnitudes.
Definition at line 136 of file fvPatch.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatch::boundaryMesh(), fvPatch::index(), fvMesh::magSf(), and fvBoundaryMesh::mesh().
Referenced by fvPatch::nf(), fvPatch::patchSlice(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), cyclicACMIFvPatch::updateAreas(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and outletMappedUniformInletFvPatchField< Type >::updateCoeffs().
nf()
Foam::tmp< Foam::vectorField > nf () const
Return face normals.
Definition at line 124 of file fvPatch.C.
References fvPatch::magSf(), and fvPatch::Sf().
Referenced by nearWallFields::calcAddressing(), curvatureSeparation::calcCosAngle(), fvPatch::delta(), cyclicFvPatch::makeWeights(), cyclicAMIFvPatch::makeWeights(), cyclicACMIFvPatch::makeWeights(), NamedEnum< directionType, 3 >::names(), fvPatch::patchSlice(), and movingWallVelocityFvPatchVectorField::updateCoeffs().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Return cell-centre to face-centre vector.
except for coupled patches for which the cell-centre to coupled-cell-centre vector is returned
Reimplemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, and coupledFvPatch.
Definition at line 142 of file fvPatch.C.
References fvPatch::Cf(), fvPatch::Cn(), and fvPatch::nf().
Referenced by cyclicACMIFvPatch::delta(), cyclicACMIFvPatch::makeWeights(), NamedEnum< directionType, 3 >::names(), fvPatch::patchSlice(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
weights()
const Foam::scalarField & weights () const
Return patch weighting factors.
Definition at line 170 of file fvPatch.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatch::boundaryMesh(), fvPatch::index(), fvBoundaryMesh::mesh(), and surfaceInterpolation::weights().
Referenced by fvPatch::patchSlice().
deltaCoeffs()
const Foam::scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
except for coupled patches for which the cell-centre to coupled-cell-centre distance coeffient is returned
Definition at line 164 of file fvPatch.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatch::boundaryMesh(), surfaceInterpolation::deltaCoeffs(), fvPatch::index(), and fvBoundaryMesh::mesh().
Referenced by fvPatch::patchSlice(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
patchInternalField() [1/3]
tmp<Field<Type> > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
Referenced by fvPatch::patchInternalField(), and fvPatch::patchSlice().
patchInternalField() [2/3]
void patchInternalField (const UList< Type > & f, Field< Type > & pif) const
Return given internal field next to patch as patch field.
Definition at line 52 of file fvPatchTemplates.C.
References forAll, fvPatch::patchField(), and List< Type >::setSize().
patchField()
const GeometricField::PatchFieldType & patchField (const GeometricField & gf) const
Return the corresponding patchField of the named field.
Definition at line 70 of file fvPatchTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField().
Referenced by fvPatch::patchInternalField(), fvPatch::patchSlice(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and porousBafflePressureFvPatchField< Type >::updateCoeffs().
lookupPatchField()
const GeometricField::PatchFieldType & lookupPatchField (const word & name, const GeometricField * = NULL, const Type * = NULL) const
Lookup and return the patchField of the named field from the.
local objectRegistry. N.B. The dummy pointer arguments are used if this function is instantiated within a templated function to avoid a bug in gcc. See inletOutletFvPatchField.C and outletInletFvPatchField.C
Definition at line 32 of file fvPatchFvMeshTemplates.C.
References boundaryMesh::mesh(), and name().
Referenced by NamedEnum< directionType, 3 >::names(), fvPatch::patchSlice(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
patchInternalField() [3/3]
Foam::tmp<Foam::Field<Type> > patchInternalField (const UList< Type > & f) const
Definition at line 32 of file fvPatchTemplates.C.
References forAll, and fvPatch::patchInternalField().
Friends And Related Function Documentation
fvBoundaryMesh
friend class fvBoundaryMesh friend
Definition at line 99 of file fvPatch.H.
surfaceInterpolation
friend class surfaceInterpolation friend
Definition at line 100 of file fvPatch.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatch.H
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatch.C
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatchFvMeshTemplates.C
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatchNew.C
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatchTemplates.C