OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
blendedSchemeBase< Type > Class Template Reference abstract
Base class for blended schemes to provide access to the blending factor surface field.
Public Member Functions
blendedSchemeBase ()
Constructor.
virtual ~blendedSchemeBase ()
Destructor.
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const =0
Return the face-based blending factor.
Detailed Description
template<class Type>
class Foam::blendedSchemeBase< Type >
Base class for blended schemes to provide access to the blending factor surface field.
Definition at line 52 of file blendedSchemeBase.H.
Constructor & Destructor Documentation
blendedSchemeBase()
blendedSchemeBase () inline
Constructor.
Definition at line 60 of file blendedSchemeBase.H.
~blendedSchemeBase()
virtual ~blendedSchemeBase () inline virtual
Destructor.
Definition at line 64 of file blendedSchemeBase.H.
References blendedSchemeBase< Type >::blendingFactor().
Member Function Documentation
blendingFactor()
virtual tmp<surfaceScalarField> blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const pure virtual
Return the face-based blending factor.
Implemented in CoBlended< Type >, localBlended< Type >, and blended< Type >.
Referenced by blendingFactor::factor(), and blendedSchemeBase< Type >::~blendedSchemeBase().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/blendedSchemeBase/blendedSchemeBase.H