OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellPointWeight Class Reference
Foam::cellPointWeight.
Public Member Functions
cellPointWeight (const polyMesh &mesh, const vector &position, const label cellI, const label faceI=-1)
Construct from components.
label cell () const
Cell index.
const List< scalar > & weights () const
interpolation weights
const List< label > & faceVertices () const
interpolation addressing for points on face
Static Public Attributes
static int debug
Debug switch.
static scalar tol
Tolerance used in calculating barycentric co-ordinates.
Protected Member Functions
void findTetrahedron (const polyMesh &mesh, const vector &position, const label cellI)
void findTriangle (const polyMesh &mesh, const vector &position, const label faceI)
Protected Attributes
const label cellI_
Cell index.
List< scalar > weights_
Weights applied to tet vertices.
List< label > faceVertices_
Face vertex indices.
Detailed Description
Foam::cellPointWeight.
Source files
cellPointWeight.H
cellPointWeight.C
Definition at line 50 of file cellPointWeight.H.
Constructor & Destructor Documentation
cellPointWeight()
cellPointWeight (const polyMesh & mesh, const vector & position, const label cellI, const label faceI = -1)
Construct from components.
Definition at line 256 of file cellPointWeight.C.
Referenced by cellPointWeight::findTriangle().
Member Function Documentation
findTetrahedron()
void findTetrahedron (const polyMesh & mesh, const vector & position, const label cellI) protected
Definition at line 39 of file cellPointWeight.C.
References tetrahedron< Point, PointRef >::barycentric(), primitiveMesh::cellVolumes(), Foam::det(), PointHit< Point >::distance(), Foam::endl(), f(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), polyMesh::faces(), cellPointWeight::findTriangle(), forAll, Foam::mag(), tetrahedron< Point, PointRef >::nearestPoint(), Foam::nl, pFaces, Foam::Pout, and tetIndices::tet().
findTriangle()
void findTriangle (const polyMesh & mesh, const vector & position, const label faceI) protected
Definition at line 141 of file cellPointWeight.C.
References triangle< Point, PointRef >::barycentric(), cellPointWeight::cellPointWeight(), Foam::det(), PointHit< Point >::distance(), Foam::endl(), f(), primitiveMesh::faceAreas(), tetIndices::faceBasePt(), polyMesh::faceOwner(), tetIndices::facePtA(), tetIndices::facePtB(), polyMesh::faces(), tetIndices::faceTri(), forAll, Foam::mag(), magSqr(), triangle< Point, PointRef >::nearestPoint(), Foam::nl, and Foam::Pout.
Referenced by cellPointWeight::findTetrahedron().
cell()
label cell () const inline
Cell index.
Definition at line 108 of file cellPointWeight.H.
References cellPointWeight::cellI_.
Referenced by interpolationCellPointWallModified< Type >::interpolate(), and interpolationCellPoint< Foam::Vector >::interpolate().
weights()
const List<scalar>& weights () const inline
interpolation weights
Definition at line 114 of file cellPointWeight.H.
References cellPointWeight::weights_.
Referenced by interpolationCellPointWallModified< Type >::interpolate(), and interpolationCellPoint< Foam::Vector >::interpolate().
faceVertices()
const List<label>& faceVertices () const inline
interpolation addressing for points on face
Definition at line 120 of file cellPointWeight.H.
References cellPointWeight::faceVertices_.
Referenced by interpolationCellPointWallModified< Type >::interpolate(), and interpolationCellPoint< Foam::Vector >::interpolate().
Member Data Documentation
cellI_
const label cellI_ protected
Cell index.
Definition at line 57 of file cellPointWeight.H.
Referenced by cellPointWeight::cell().
weights_
List<scalar> weights_ protected
Weights applied to tet vertices.
Definition at line 60 of file cellPointWeight.H.
Referenced by cellPointWeight::weights().
faceVertices_
List<label> faceVertices_ protected
Face vertex indices.
Definition at line 63 of file cellPointWeight.H.
Referenced by cellPointWeight::faceVertices().
debug
int debug static
Debug switch.
Definition at line 86 of file cellPointWeight.H.
tol
Foam::scalar tol static
Tolerance used in calculating barycentric co-ordinates.
(applied to normalised values)
Definition at line 90 of file cellPointWeight.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/cellPointWeight/cellPointWeight.H
src/finiteVolume/interpolation/interpolation/interpolationCellPoint/cellPointWeight/cellPointWeight.C