OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
filteredLinear3VLimiter< LimiterFunc > Class Template Reference
Class to generate weighting factors for the filteredLinear3V differencing scheme.
Public Member Functions
filteredLinear3VLimiter (Istream &is)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::filteredLinear3VLimiter< LimiterFunc >
Class to generate weighting factors for the filteredLinear3V differencing scheme.
The aim is to remove high-frequency modes with "staggering" characteristics from vector fields by comparing the face gradient in the direction of maximum gradient with both neighbouring cell gradients and introduce small amounts of upwind in order to damp these modes.
Used in conjunction with the template class LimitedScheme.
Source files
filteredLinear3V.H
filteredLinear3V.C
Definition at line 57 of file filteredLinear3V.H.
Constructor & Destructor Documentation
filteredLinear3VLimiter()
filteredLinear3VLimiter (Istream & is) inline
Definition at line 70 of file filteredLinear3V.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, and filteredLinear3VLimiter< LimiterFunc >::limiter().
Member Function Documentation
limiter()
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 84 of file filteredLinear3V.H.
References Foam::max(), Foam::min(), and Foam::sqr().
Referenced by filteredLinear3VLimiter< LimiterFunc >::filteredLinear3VLimiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/filteredLinear3/filteredLinear3V.H