OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointPatchField< Type > Class Template Reference abstract
Abstract base class for point-mesh patch fields.
Public Types
typedef pointPatch Patch
Public Member Functions
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
virtual autoPtr< pointPatchField< Type > > clone () const =0
Construct and return a clone.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const =0
Construct and return a clone setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
Static Public Member Functions
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new CalculatedpointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Friends
Ostream & operator (Ostream &, const pointPatchField< Type > &)
Detailed Description
template<class Type>
class Foam::pointPatchField< Type >
Abstract base class for point-mesh patch fields.
The base-field does not store values as they are part of the "internal field". There are derived classes to store constraint values e.g. fixedValuePointPatchField derived from the generic valuePointPatchField which ensures the values in the "internal field" are reset to the fixed-values by applying the stored values.
Source files
pointPatchField.H
pointPatchField.C
newPointPatchField.C
Definition at line 58 of file pointMVCWeight.H.
Member Typedef Documentation
Patch
typedef pointPatch Patch
Definition at line 100 of file pointPatchField.H.
Constructor & Destructor Documentation
pointPatchField() [1/5]
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 39 of file pointPatchField.C.
Referenced by pointPatchField< vector >::pointPatchField().
pointPatchField() [2/5]
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 53 of file pointPatchField.C.
pointPatchField() [3/5]
pointPatchField (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 68 of file pointPatchField.C.
pointPatchField() [4/5]
pointPatchField (const pointPatchField< Type > & ptf)
Construct as copy.
Definition at line 84 of file pointPatchField.C.
pointPatchField() [5/5]
pointPatchField (const pointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 97 of file pointPatchField.C.
~pointPatchField()
virtual ~pointPatchField () inline virtual
Destructor.
Definition at line 253 of file pointPatchField.H.
Member Function Documentation
TypeName()
TypeName ("pointPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , pointPatch , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , patchMapper , (const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m) , (dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , dictionary , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
virtual autoPtr<pointPatchField<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, processorCyclicPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, valuePointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, valuePointPatchField< vector >, waveDisplacementPointPatchVectorField, processorPointPatchField< Type >, oscillatingDisplacementPointPatchVectorField, coupledPointPatchField< Type >, fixedValuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, calculatedPointPatchField< Type >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, and basicSymmetryPointPatchField< Type >.
clone() [2/2]
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const pure virtual
Construct and return a clone setting internal field reference.
Implemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, processorCyclicPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, valuePointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, valuePointPatchField< vector >, waveDisplacementPointPatchVectorField, processorPointPatchField< Type >, oscillatingDisplacementPointPatchVectorField, calculatedPointPatchField< Type >, fixedValuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
New() [1/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 108 of file pointPatchFieldNew.C.
Referenced by pointPatchField< vector >::New().
New() [2/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values). Allows override of constraint type
Definition at line 32 of file pointPatchFieldNew.C.
New() [3/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given pointPatchField mapped onto a new patch
Definition at line 206 of file pointPatchFieldNew.C.
New() [4/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 120 of file pointPatchFieldNew.C.
NewCalculatedType()
autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > & pf) static
Return a pointer to a new CalculatedpointPatchField created on.
freestore without setting patchField values
Definition at line 93 of file calculatedPointPatchField.C.
Referenced by calculatedPointPatchField< Type >::calculatedPointPatchField().
db()
const objectRegistry & db () const
Return local objectRegistry.
Definition at line 112 of file pointPatchField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::surfaces(), and pointPatchField< vector >::~pointPatchField().
size()
label size () const inline
Return size.
Definition at line 265 of file pointPatchField.H.
Referenced by valuePointPatchField< vector >::valuePointPatchField().
patch()
const pointPatch& patch () const inline
Return patch.
Definition at line 271 of file pointPatchField.H.
Referenced by NamedEnum< directionType, 3 >::names(), pointPatchField< vector >::NewCalculatedType(), and pointPatchField< vector >::size().
dimensionedInternalField()
const DimensionedField<Type, pointMesh>& dimensionedInternalField () const inline
Return dimensioned internal field reference.
Definition at line 278 of file pointPatchField.H.
internalField()
const Field<Type>& internalField () const inline
Return internal field reference.
Definition at line 284 of file pointPatchField.H.
Referenced by surfaceSlipDisplacementPointPatchVectorField::evaluate().
patchType() [1/2]
const word& patchType () const inline
Optional patch type.
Definition at line 290 of file pointPatchField.H.
patchType() [2/2]
word& patchType () inline
Optional patch type.
Definition at line 296 of file pointPatchField.H.
fixesValue()
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 302 of file pointPatchField.H.
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorCyclicPointPatchField< Type >, processorPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 308 of file pointPatchField.H.
updated()
bool updated () const inline
Return true if the boundary condition has already been updated.
Definition at line 314 of file pointPatchField.H.
patchInternalField() [1/3]
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
Definition at line 132 of file pointPatchField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::evaluate(), valuePointPatchField< vector >::operator=(), valuePointPatchField< vector >::operator==(), pointPatchField< vector >::patchInternalField(), pointConstraints::setPatchFields(), and pointPatchField< vector >::updated().
patchInternalField() [2/3]
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > & iF) const
Return field created from appropriate internal field values.
given internal field reference
Definition at line 167 of file pointPatchField.C.
patchInternalField() [3/3]
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Return field created from selected internal field values.
given internal field reference
Definition at line 141 of file pointPatchField.C.
addToInternalField() [1/2]
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
add the patch field to the internal field
Definition at line 178 of file pointPatchField.C.
Referenced by pointPatchField< vector >::addToInternalField(), pointPatchField< vector >::patchInternalField(), and pointPatchField< vector >::updated().
addToInternalField() [2/2]
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & points) const
Given the internal field and a patch field,.
add selected elements of the patch field to the internal field
Definition at line 223 of file pointPatchField.C.
setInInternalField() [1/2]
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & meshPoints) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 270 of file pointPatchField.C.
Referenced by pointPatchField< vector >::addToInternalField(), surfaceSlipDisplacementPointPatchVectorField::evaluate(), pointPatchField< vector >::setInInternalField(), and pointPatchField< vector >::updated().
setInInternalField() [2/2]
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 313 of file pointPatchField.C.
calculatedType()
const word & calculatedType () static
Return the type of the calculated form of pointPatchField.
Definition at line 34 of file calculatedPointPatchField.C.
Referenced by pointPatchField< vector >::updated().
constraintType()
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatchField implements.
Reimplemented in cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, processorPointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, emptyPointPatchField< Type >, wedgePointPatchField< Type >, and symmetryPointPatchField< Type >.
Definition at line 381 of file pointPatchField.H.
autoMap()
virtual void autoMap (const pointPatchFieldMapper &) inline virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 391 of file pointPatchField.H.
Referenced by pointPatchField< vector >::constraintType().
rmap()
virtual void rmap (const pointPatchField< Type > & , const labelList &) inline virtual
Reverse map the given pointPatchField onto this pointPatchField.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 398 of file pointPatchField.H.
Referenced by pointPatchField< vector >::autoMap().
updateCoeffs()
virtual void updateCoeffs () inline virtual
Update the coefficients associated with the patch field.
Sets Updated to true
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 409 of file pointPatchField.H.
Referenced by pointPatchField< vector >::rmap().
initEvaluate()
virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::blocking) inline virtual
Initialise evaluation of the patch field (do nothing)
Definition at line 416 of file pointPatchField.H.
Referenced by pointPatchField< vector >::rmap().
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Reimplemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, cyclicPointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, cyclicSlipPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 323 of file pointPatchField.C.
Referenced by pointPatchField< vector >::initEvaluate().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, uniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, genericPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 119 of file pointPatchField.C.
Referenced by pointPatchField< vector >::initEvaluate(), Foam::operator<<(), oscillatingDisplacementPointPatchVectorField::write(), waveDisplacementPointPatchVectorField::write(), oscillatingVelocityPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), angularOscillatingDisplacementPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), uniformInterpolatedDisplacementPointPatchVectorField::write(), and sixDoFRigidBodyDisplacementPointPatchVectorField::write().
operator=() [1/3]
virtual void operator= (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 435 of file pointPatchField.H.
operator+=() [1/3]
virtual void operator+= (const pointPatchField< Type > &) inline virtual
Definition at line 441 of file pointPatchField.H.
operator-=() [1/3]
virtual void operator-= (const pointPatchField< Type > &) inline virtual
Definition at line 447 of file pointPatchField.H.
operator*=() [1/3]
virtual void operator*= (const pointPatchField< scalar > &) inline virtual
Definition at line 453 of file pointPatchField.H.
operator/=() [1/3]
virtual void operator/= (const pointPatchField< scalar > &) inline virtual
Definition at line 459 of file pointPatchField.H.
operator=() [2/3]
virtual void operator= (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, valuePointPatchField< vector >, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 464 of file pointPatchField.H.
operator+=() [2/3]
virtual void operator+= (const Field< Type > &) inline virtual
Definition at line 465 of file pointPatchField.H.
operator-=() [2/3]
virtual void operator-= (const Field< Type > &) inline virtual
Definition at line 466 of file pointPatchField.H.
operator*=() [2/3]
virtual void operator*= (const Field< scalar > &) inline virtual
Definition at line 468 of file pointPatchField.H.
operator/=() [2/3]
virtual void operator/= (const Field< scalar > &) inline virtual
Definition at line 469 of file pointPatchField.H.
operator=() [3/3]
virtual void operator= (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, valuePointPatchField< vector >, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 471 of file pointPatchField.H.
operator+=() [3/3]
virtual void operator+= (const Type &) inline virtual
Definition at line 472 of file pointPatchField.H.
operator-=() [3/3]
virtual void operator-= (const Type &) inline virtual
Definition at line 473 of file pointPatchField.H.
operator*=() [3/3]
virtual void operator*= (const scalar) inline virtual
Definition at line 474 of file pointPatchField.H.
operator/=() [3/3]
virtual void operator/= (const scalar) inline virtual
Definition at line 475 of file pointPatchField.H.
operator==() [1/3]
virtual void operator== (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 483 of file pointPatchField.H.
operator==() [2/3]
virtual void operator== (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 488 of file pointPatchField.H.
operator==() [3/3]
virtual void operator== (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 489 of file pointPatchField.H.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const pointPatchField< Type > &) friend
Member Data Documentation
disallowGenericPointPatchField
int disallowGenericPointPatchField static
Debug switch to disallow the use of genericPointPatchField.
Definition at line 107 of file pointPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/calculated/calculatedPointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFieldNew.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFields.C