OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallPointYPlus Class Reference
Holds information (coordinate and yStar) regarding nearest wall point.
Public Member Functions
wallPointYPlus ()
Construct null.
wallPointYPlus (const point &origin, const scalar yStar, const scalar distSqr)
Construct from origin, yStar, distance.
template<class TrackingData >
bool updateCell (const polyMesh &mesh, const label thisCellI, const label neighbourFaceI, const wallPointYPlus &neighbourWallInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const label thisFaceI, const label neighbourCellI, const wallPointYPlus &neighbourWallInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const label thisFaceI, const wallPointYPlus &neighbourWallInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
Public Member Functions inherited from wallPointData< scalar >
wallPointData ()
Construct null.
wallPointData (const point &origin, const scalar &data, const scalar distSqr)
Construct from origin, normal, distance.
const scalar & data () const
scalar & data ()
bool updateCell (const polyMesh &mesh, const label thisCellI, const label neighbourFaceI, const wallPointData< scalar > &neighbourWallInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
bool updateFace (const polyMesh &mesh, const label thisFaceI, const label neighbourCellI, const wallPointData< scalar > &neighbourWallInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
bool updateFace (const polyMesh &mesh, const label thisFaceI, const wallPointData< scalar > &neighbourWallInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
Public Member Functions inherited from wallPoint
wallPoint ()
Construct null.
wallPoint (const point &origin, const scalar distSqr)
Construct from origin, distance.
wallPoint (const wallPoint &)
Construct as copy.
const point & origin () const
point & origin ()
scalar distSqr () const
scalar & distSqr ()
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoint &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const wallPoint &, TrackingData &td) const
Same (like operator==)
bool operator== (const wallPoint &) const
bool operator!= (const wallPoint &) const
Static Public Attributes
static scalar yPlusCutOff = 200
cut-off value for y+
Additional Inherited Members
Public Types inherited from wallPointData< scalar >
typedef scalar dataType
Detailed Description
Holds information (coordinate and yStar) regarding nearest wall point.
Used in VanDriest wall damping where the interest is in y+ but only needs to be calculated up to e.g. y+ < 200. In all other cells/faces the damping function becomes 1, since y gets initialized to GREAT and yStar to 1.
Note: should feed the additional argument (yPlusCutoff) through as a template argument into FaceCellWave
Source files
wallPointYPlus.H
wallPointYPlusI.H
wallPointYPlus.C
Definition at line 58 of file wallPointYPlus.H.
Constructor & Destructor Documentation
wallPointYPlus() [1/2]
wallPointYPlus () inline
Construct null.
Definition at line 88 of file wallPointYPlusI.H.
References wallPointData< scalar >::data().
wallPointYPlus() [2/2]
wallPointYPlus (const point & origin, const scalar yStar, const scalar distSqr) inline
Construct from origin, yStar, distance.
Definition at line 99 of file wallPointYPlusI.H.
References wallPointYPlus::updateCell().
Member Function Documentation
updateCell()
bool updateCell (const polyMesh & mesh, const label thisCellI, const label neighbourFaceI, const wallPointYPlus & neighbourWallInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Calls update(...) with cellCentre of cellI
Definition at line 114 of file wallPointYPlusI.H.
References wallPointYPlus::updateFace().
Referenced by wallPointYPlus::wallPointYPlus().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const label neighbourCellI, const wallPointYPlus & neighbourWallInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Calls update(...) with faceCentre of faceI
Definition at line 138 of file wallPointYPlusI.H.
References primitiveMesh::faceCentres().
Referenced by wallPointYPlus::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const wallPointYPlus & neighbourWallInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Merge new and old info. Calls update(...) with faceCentre of faceI
Definition at line 162 of file wallPointYPlusI.H.
References primitiveMesh::faceCentres().
Member Data Documentation
yPlusCutOff
Foam::scalar yPlusCutOff = 200 static
cut-off value for y+
Definition at line 84 of file wallPointYPlus.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/wallPointYPlus/wallPointYPlus.H
src/finiteVolume/fvMesh/wallDist/wallPointYPlus/wallPointYPlus.C
src/finiteVolume/fvMesh/wallDist/wallPointYPlus/wallPointYPlusI.H