OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NVDVTVDV Class Reference
Foam::NVDVTVDV.
Public Types
typedef vector phiType
typedef tensor gradPhiType
Public Member Functions
NVDVTVDV ()
scalar phict (const scalar faceFlux, const vector &phiP, const vector &phiN, const tensor &gradcP, const tensor &gradcN, const vector &d) const
scalar r (const scalar faceFlux, const vector &phiP, const vector &phiN, const tensor &gradcP, const tensor &gradcN, const vector &d) const
Detailed Description
Foam::NVDVTVDV.
Definition at line 43 of file NVDVTVDV.H.
Member Typedef Documentation
phiType
typedef vector phiType
Definition at line 48 of file NVDVTVDV.H.
gradPhiType
typedef tensor gradPhiType
Definition at line 49 of file NVDVTVDV.H.
Constructor & Destructor Documentation
NVDVTVDV()
NVDVTVDV () inline
Definition at line 53 of file NVDVTVDV.H.
References NVDVTVDV::phict().
Member Function Documentation
phict()
scalar phict (const scalar faceFlux, const vector & phiP, const vector & phiN, const tensor & gradcP, const tensor & gradcN, const vector & d) const inline
Definition at line 60 of file NVDVTVDV.H.
References Foam::mag(), NVDVTVDV::r(), and Foam::sign().
Referenced by NVDVTVDV::NVDVTVDV().
r()
scalar r (const scalar faceFlux, const vector & phiP, const vector & phiN, const tensor & gradcP, const tensor & gradcN, const vector & d) const inline
Definition at line 95 of file NVDVTVDV.H.
References Foam::mag(), and Foam::sign().
Referenced by NVDVTVDV::phict().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/NVDVTVDV.H