OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
upwind< Type > Class Template Reference
Upwind differencing scheme class.
Public Member Functions
TypeName ("upwind")
Runtime type information.
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from faceFlux.
upwind (const fvMesh &mesh, Istream &is)
Construct from Istream.
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &)
Construct from faceFlux and Istream.
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation limiter.
tmp< surfaceScalarField > weights () const
Return the interpolation weighting factors.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
TypeName ("limitedSurfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from mesh and faceFlux.
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~limitedSurfaceInterpolationScheme ()
Destructor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
Return the interpolation weighting factors for the given field,.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Attributes inherited from limitedSurfaceInterpolationScheme< Type >
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type>
class Foam::upwind< Type >
Upwind differencing scheme class.
Source files
upwind.H
upwind.C
Definition at line 51 of file upwind.H.
Constructor & Destructor Documentation
upwind() [1/3]
upwind (const fvMesh & mesh, const surfaceScalarField & faceFlux) inline
Construct from faceFlux.
Definition at line 71 of file upwind.H.
Referenced by upwind< Type >::upwind().
upwind() [2/3]
upwind (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 83 of file upwind.H.
References upwind< Type >::upwind().
upwind() [3/3]
upwind (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream &) inline
Construct from faceFlux and Istream.
Definition at line 93 of file upwind.H.
References upwind< Type >::limiter().
Member Function Documentation
TypeName()
TypeName ("upwind< Type >")
Runtime type information.
limiter()
virtual tmp<surfaceScalarField> limiter (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation limiter.
Implements limitedSurfaceInterpolationScheme< Type >.
Definition at line 107 of file upwind.H.
References Foam::dimless, surfaceInterpolationScheme< Type >::mesh(), and timeName.
Referenced by upwind< Type >::upwind().
weights() [1/2]
tmp<surfaceScalarField> weights () const inline
Return the interpolation weighting factors.
Definition at line 128 of file upwind.H.
References limitedSurfaceInterpolationScheme< Type >::faceFlux_, and Foam::pos().
Referenced by LUST< Type >::LUST(), multivariateScheme< Type, Scheme >::multivariateScheme(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), LUST< Type >::weights(), and upwind< Type >::weights().
weights() [2/2]
virtual tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Reimplemented from limitedSurfaceInterpolationScheme< Type >.
Reimplemented in LUST< Type >.
Definition at line 135 of file upwind.H.
References upwind< Type >::weights().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/upwind/upwind.H