OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NVDTVD Class Reference
Foam::NVDTVD.
Public Types
typedef scalar phiType
typedef vector gradPhiType
Public Member Functions
NVDTVD ()
scalar phict (const scalar faceFlux, const scalar phiP, const scalar phiN, const vector &gradcP, const vector &gradcN, const vector &d) const
scalar r (const scalar faceFlux, const scalar phiP, const scalar phiN, const vector &gradcP, const vector &gradcN, const vector &d) const
Detailed Description
Foam::NVDTVD.
Definition at line 43 of file NVDTVD.H.
Member Typedef Documentation
phiType
typedef scalar phiType
Definition at line 48 of file NVDTVD.H.
gradPhiType
typedef vector gradPhiType
Definition at line 49 of file NVDTVD.H.
Constructor & Destructor Documentation
NVDTVD()
NVDTVD () inline
Definition at line 54 of file NVDTVD.H.
References NVDTVD::phict().
Member Function Documentation
phict()
scalar phict (const scalar faceFlux, const scalar phiP, const scalar phiN, const vector & gradcP, const vector & gradcN, const vector & d) const inline
Definition at line 61 of file NVDTVD.H.
References Foam::mag(), NVDTVD::r(), and Foam::sign().
Referenced by NVDTVD::NVDTVD().
r()
scalar r (const scalar faceFlux, const scalar phiP, const scalar phiN, const vector & gradcP, const vector & gradcN, const vector & d) const inline
Definition at line 95 of file NVDTVD.H.
References Foam::mag(), and Foam::sign().
Referenced by NVDTVD::phict().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/LimitedScheme/NVDTVD.H