OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CoBlended< Type > Class Template Reference
Two-scheme Courant number based blending differencing scheme.
Public Member Functions
TypeName ("CoBlended")
Runtime type information.
CoBlended (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
CoBlended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-based blending factor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()
Constructor.
virtual ~blendedSchemeBase ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::CoBlended< Type >
Two-scheme Courant number based blending differencing scheme.
Similar to localBlended but uses a blending factor computed from the face-based Courant number and the lower and upper Courant number limits supplied:
where
= Courant number below which scheme1 is used
= Courant number above which scheme2 is used
The weight applies to the first scheme and 1-weight to the second scheme.
Example of the CoBlended scheme specification using LUST for Courant numbers less than 1 and linearUpwind for Courant numbers greater than 10:
    divSchemes
    {
        .
        .
        div(phi,U)      Gauss CoBlended 1 LUST grad(U) 10 linearUpwind grad(U);
        .
        .
    }
Source files
CoBlended.H
CoBlended.C
Definition at line 86 of file CoBlended.H.
Constructor & Destructor Documentation
CoBlended() [1/2]
CoBlended (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 130 of file CoBlended.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorIn.
CoBlended() [2/2]
CoBlended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 163 of file CoBlended.H.
References CoBlended< Type >::blendingFactor(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorIn.
Member Function Documentation
TypeName()
TypeName ("CoBlended< Type >")
Runtime type information.
blendingFactor()
virtual tmp<surfaceScalarField> blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-based blending factor.
Implements blendedSchemeBase< Type >.
Definition at line 196 of file CoBlended.H.
References surfaceInterpolation::deltaCoeffs(), TimeState::deltaT(), Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::fvc::interpolate(), Foam::mag(), fvMesh::magSf(), Foam::max(), surfaceInterpolationScheme< Type >::mesh(), Foam::min(), IOobject::name(), rho, fvMesh::time(), and CoBlended< Type >::weights().
Referenced by CoBlended< Type >::CoBlended(), CoBlended< Type >::correction(), CoBlended< Type >::interpolate(), and CoBlended< Type >::weights().
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 249 of file CoBlended.H.
References CoBlended< Type >::blendingFactor(), and CoBlended< Type >::interpolate().
Referenced by CoBlended< Type >::blendingFactor().
interpolate()
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-interpolate of the given cell field.
with explicit correction
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 265 of file CoBlended.H.
References CoBlended< Type >::blendingFactor().
Referenced by CoBlended< Type >::weights().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 278 of file CoBlended.H.
References CoBlended< Type >::correction().
Referenced by CoBlended< Type >::correction().
correction()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
for the given field
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 288 of file CoBlended.H.
References CoBlended< Type >::blendingFactor(), and CoBlended< Type >::corrected().
Referenced by CoBlended< Type >::corrected().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/CoBlended/CoBlended.H