OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
harmonic Class Reference
Harmonic-mean differencing scheme class.
Public Member Functions
TypeName ("harmonic")
Runtime type information.
harmonic (const fvMesh &mesh)
Construct from mesh.
harmonic (const fvMesh &mesh, Istream &is)
Construct from Istream.
harmonic (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from faceFlux and Istream.
virtual tmp< surfaceScalarField > weights (const GeometricField< scalar, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
virtual tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< scalar, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
Public Member Functions inherited from surfaceInterpolationScheme< scalar >
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > correction (const GeometricField< scalar, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< scalar >
static tmp< surfaceInterpolationScheme< scalar > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< scalar > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< scalar, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< scalar, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< scalar, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
Harmonic-mean differencing scheme class.
This scheme interpolates 1/field using a scheme specified at run-time and return the reciprocal of the interpolate.
Source files
harmonic.H
harmonic.C
Definition at line 54 of file harmonic.H.
Constructor & Destructor Documentation
harmonic() [1/3]
harmonic (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 73 of file harmonic.H.
Referenced by harmonic::harmonic().
harmonic() [2/3]
harmonic (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 82 of file harmonic.H.
References harmonic::harmonic().
harmonic() [3/3]
harmonic (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from faceFlux and Istream.
Definition at line 92 of file harmonic.H.
References harmonic::weights().
Member Function Documentation
TypeName()
TypeName ("harmonic")
Runtime type information.
weights()
virtual tmp<surfaceScalarField> weights (const GeometricField< scalar, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< scalar >.
Definition at line 106 of file harmonic.H.
References harmonic::interpolate(), and notImplemented.
Referenced by harmonic::harmonic().
interpolate()
virtual tmp<GeometricField<scalar, fvsPatchField, surfaceMesh> > interpolate (const GeometricField< scalar, fvPatchField, volMesh > & vf) const inline virtual
Return the face-interpolate of the given cell field.
Reimplemented from surfaceInterpolationScheme< scalar >.
Definition at line 122 of file harmonic.H.
References DimensionedField< Type, GeoMesh >::mesh().
Referenced by harmonic::weights().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/harmonic/harmonic.H