OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
clippedLinear< Type > Class Template Reference
Central-differencing interpolation scheme using clipped-weights to improve stability on meshes with very rapid variations in cell size.
Public Member Functions
TypeName ("clippedLinear")
Runtime type information.
clippedLinear (const fvMesh &mesh, const scalar cellSizeRatio)
Construct from mesh and cellSizeRatio.
clippedLinear (const fvMesh &mesh, Istream &is)
Construct from Istream.
clippedLinear (const fvMesh &mesh, const surfaceScalarField &, Istream &is)
Construct from faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::clippedLinear< Type >
Central-differencing interpolation scheme using clipped-weights to improve stability on meshes with very rapid variations in cell size.
Source files
clippedLinear.H
clippedLinear.C
Definition at line 51 of file clippedLinear.H.
Constructor & Destructor Documentation
clippedLinear() [1/3]
clippedLinear (const fvMesh & mesh, const scalar cellSizeRatio) inline
Construct from mesh and cellSizeRatio.
Definition at line 90 of file clippedLinear.H.
Referenced by clippedLinear< Type >::clippedLinear().
clippedLinear() [2/3]
clippedLinear (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
Definition at line 99 of file clippedLinear.H.
References clippedLinear< Type >::clippedLinear().
clippedLinear() [3/3]
clippedLinear (const fvMesh & mesh, const surfaceScalarField & , Istream & is) inline
Construct from faceFlux and Istream.
Definition at line 109 of file clippedLinear.H.
References clippedLinear< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("clippedLinear< Type >")
Runtime type information.
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 126 of file clippedLinear.H.
References fvMesh::boundary(), Foam::dimless, forAll, Foam::max(), surfaceInterpolationScheme< Type >::mesh(), Foam::min(), patchi, fvMesh::time(), and Time::timeName().
Referenced by clippedLinear< Type >::clippedLinear().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/clippedLinear/clippedLinear.H