OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
outletStabilised< Type > Class Template Reference
Outlet-stabilised interpolation scheme which applies upwind differencing to the faces of the cells adjacent to outlets.
Public Member Functions
TypeName ("outletStabilised")
Runtime type information.
outletStabilised (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
outletStabilised (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::outletStabilised< Type >
Outlet-stabilised interpolation scheme which applies upwind differencing to the faces of the cells adjacent to outlets.
This is particularly useful to stabilise the velocity at entrainment boundaries for LES cases using linear or other centred differencing schemes.
Source files
outletStabilised.H
outletStabilised.C
Definition at line 59 of file outletStabilised.H.
Constructor & Destructor Documentation
outletStabilised() [1/2]
outletStabilised (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 88 of file outletStabilised.H.
outletStabilised() [2/2]
outletStabilised (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 110 of file outletStabilised.H.
References outletStabilised< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("outletStabilised< Type >")
Runtime type information.
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 129 of file outletStabilised.H.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, primitiveMesh::cells(), forAll, Foam::isA(), primitiveMesh::isInternalFace(), surfaceInterpolationScheme< Type >::mesh(), patchi, and Foam::pos().
Referenced by outletStabilised< Type >::outletStabilised().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 175 of file outletStabilised.H.
References outletStabilised< Type >::correction().
Referenced by outletStabilised< Type >::correction().
correction()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
set to zero on the near-boundary faces where upwinf is applied
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 184 of file outletStabilised.H.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, primitiveMesh::cells(), outletStabilised< Type >::corrected(), forAll, Foam::isA(), primitiveMesh::isInternalFace(), surfaceInterpolationScheme< Type >::mesh(), and patchi.
Referenced by outletStabilised< Type >::corrected().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/outletStabilised/outletStabilised.H