OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
weighted< Type > Class Template Reference
Interpolation scheme class using weights looked-up from the objectRegistry.
Public Member Functions
TypeName ("weighted")
Runtime type information.
weighted (const surfaceScalarField &weights)
Construct from weights.
weighted (const fvMesh &mesh, Istream &is)
Construct from Istream.
weighted (const fvMesh &mesh, const surfaceScalarField &, Istream &is)
Construct from faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::weighted< Type >
Interpolation scheme class using weights looked-up from the objectRegistry.
Source files
weighted.H
weighted.C
Definition at line 50 of file weighted.H.
Constructor & Destructor Documentation
weighted() [1/3]
weighted (const surfaceScalarField & weights) inline
Construct from weights.
Definition at line 74 of file weighted.H.
Referenced by weighted< Type >::weighted().
weighted() [2/3]
weighted (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
Definition at line 81 of file weighted.H.
References weighted< Type >::weighted().
weighted() [3/3]
weighted (const fvMesh & mesh, const surfaceScalarField & , Istream & is) inline
Construct from faceFlux and Istream.
Definition at line 96 of file weighted.H.
References weighted< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("weighted< Type >")
Runtime type information.
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 118 of file weighted.H.
Referenced by weighted< Type >::weighted().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/weighted/weighted.H