OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reverseLinear< Type > Class Template Reference
Inversed weight central-differencing interpolation scheme class.
Public Member Functions
TypeName ("reverseLinear")
Runtime type information.
reverseLinear (const fvMesh &mesh)
Construct from mesh.
reverseLinear (const fvMesh &mesh, Istream &)
Construct from Istream.
reverseLinear (const fvMesh &mesh, const surfaceScalarField &, Istream &)
Construct from faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::reverseLinear< Type >
Inversed weight central-differencing interpolation scheme class.
Useful for inverse weighted and harmonic interpolations.
Source files
reverseLinear.H
reverseLinear.C
Definition at line 52 of file reverseLinear.H.
Constructor & Destructor Documentation
reverseLinear() [1/3]
reverseLinear (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 71 of file reverseLinear.H.
Referenced by reverseLinear< Type >::reverseLinear().
reverseLinear() [2/3]
reverseLinear (const fvMesh & mesh, Istream &) inline
Construct from Istream.
Definition at line 77 of file reverseLinear.H.
References reverseLinear< Type >::reverseLinear().
reverseLinear() [3/3]
reverseLinear (const fvMesh & mesh, const surfaceScalarField & , Istream &) inline
Construct from faceFlux and Istream.
Definition at line 84 of file reverseLinear.H.
References reverseLinear< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("reverseLinear< Type >")
Runtime type information.
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 98 of file reverseLinear.H.
References fvMesh::boundary(), Foam::dimless, forAll, surfaceInterpolationScheme< Type >::mesh(), fvMesh::time(), and Time::timeName().
Referenced by reverseLinear< Type >::reverseLinear().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/reverseLinear/reverseLinear.H