OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
localMax< Type > Class Template Reference
LocalMax-mean differencing scheme class.
Public Member Functions
TypeName ("localMax")
Runtime type information.
localMax (const fvMesh &mesh)
Construct from mesh.
localMax (const fvMesh &mesh, Istream &is)
Construct from Istream.
localMax (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from faceFlux and Istream.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::localMax< Type >
LocalMax-mean differencing scheme class.
This scheme interpolates 1/field using a scheme specified at run-time and return the reciprocal of the interpolate.
Source files
localMax.H
localMax.C
Definition at line 54 of file localMax.H.
Constructor & Destructor Documentation
localMax() [1/3]
localMax (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 73 of file localMax.H.
Referenced by localMax< Type >::localMax().
localMax() [2/3]
localMax (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 82 of file localMax.H.
References localMax< Type >::localMax().
localMax() [3/3]
localMax (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from faceFlux and Istream.
Definition at line 92 of file localMax.H.
References localMax< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("localMax< Type >")
Runtime type information.
weights()
virtual tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 106 of file localMax.H.
References localMax< Type >::interpolate(), and notImplemented.
Referenced by localMax< Type >::localMax().
interpolate()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-interpolate of the given cell field.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 122 of file localMax.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, Foam::max(), surfaceInterpolationScheme< Type >::mesh(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), patchi, fvMesh::time(), and Time::timeName().
Referenced by localMax< Type >::weights().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/localMax/localMax.H