OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
quadraticUpwindFitPolynomial Class Reference
Quadratic polynomial for upwind biased interpolation fitting.
Static Public Member Functions
static label nTerms (const direction dim)
static void addCoeffs (scalar *coeffs, const vector &d, const scalar weight, const direction dim)
Detailed Description
Quadratic polynomial for upwind biased interpolation fitting.
Can be used with the UpwindFit scheme to create a quadratic surface interpolation scheme
Definition at line 48 of file quadraticUpwindFitPolynomial.H.
Member Function Documentation
nTerms()
static label nTerms (const direction dim) inline static
Definition at line 54 of file quadraticUpwindFitPolynomial.H.
References quadraticUpwindFitPolynomial::addCoeffs().
addCoeffs()
static void addCoeffs (scalar * coeffs, const vector & d, const scalar weight, const direction dim) inline static
Definition at line 65 of file quadraticUpwindFitPolynomial.H.
References Foam::sqr(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by quadraticUpwindFitPolynomial::nTerms().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/quadraticUpwindFit/quadraticUpwindFitPolynomial.H