OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
motionDiffusivity Class Reference abstract
Abstract base class for cell-centre mesh motion diffusivity.
Public Member Functions
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
Construct for the given fvMesh.
virtual ~motionDiffusivity ()
Destructor.
const fvMesh & mesh () const
Return reference to the mesh.
virtual tmp< surfaceScalarField > operator() () const =0
Return diffusivity field.
virtual void correct ()=0
Correct the motion diffusivity.
Static Public Member Functions
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Select null constructed.
Detailed Description
Abstract base class for cell-centre mesh motion diffusivity.
Source files
motionDiffusivity.H
motionDiffusivity.C
Definition at line 49 of file motionDiffusivity.H.
Constructor & Destructor Documentation
motionDiffusivity()
motionDiffusivity (const fvMesh & mesh)
Construct for the given fvMesh.
Definition at line 39 of file motionDiffusivity.C.
References motionDiffusivity::New().
~motionDiffusivity()
~motionDiffusivity () virtual
Destructor.
Definition at line 79 of file motionDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , motionDiffusivity , Istream , (const fvMesh &mesh, Istream &mdData) , (mesh, mdData))
New()
Foam::autoPtr< Foam::motionDiffusivity > New (const fvMesh & mesh, Istream & mdData) static
Select null constructed.
Definition at line 48 of file motionDiffusivity.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, motionDiffusivity::mesh(), and Foam::nl.
Referenced by displacementLaplacianFvMotionSolver::diffusivity(), motionDiffusivity::motionDiffusivity(), velocityComponentLaplacianFvMotionSolver::updateMesh(), velocityLaplacianFvMotionSolver::updateMesh(), displacementComponentLaplacianFvMotionSolver::updateMesh(), and displacementSBRStressFvMotionSolver::updateMesh().
mesh()
const fvMesh& mesh () const inline
Return reference to the mesh.
Definition at line 100 of file motionDiffusivity.H.
References motionDiffusivity::correct(), and motionDiffusivity::operator()().
Referenced by motionDiffusivity::New().
operator()()
virtual tmp<surfaceScalarField> operator() () const pure virtual
Return diffusivity field.
Implemented in fileDiffusivity, uniformDiffusivity, exponentialDiffusivity, and quadraticDiffusivity.
Referenced by motionDiffusivity::mesh().
correct()
virtual void correct () pure virtual
Correct the motion diffusivity.
Implemented in fileDiffusivity, uniformDiffusivity, inverseDistanceDiffusivity, exponentialDiffusivity, quadraticDiffusivity, inverseFaceDistanceDiffusivity, inversePointDistanceDiffusivity, directionalDiffusivity, motionDirectionalDiffusivity, and inverseVolumeDiffusivity.
Referenced by motionDiffusivity::mesh().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/motionDiffusivity/motionDiffusivity.H
src/fvMotionSolver/motionDiffusivity/motionDiffusivity/motionDiffusivity.C