OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvMotionSolverCore Class Reference
Base class for fvMesh based motionSolvers.
Public Member Functions
ClassName ("displacementMotionSolver")
Runtime type information.
fvMotionSolverCore (const polyMesh &)
Construct from polyMesh.
const fvMesh & mesh () const
Return reference to the fvMesh to be moved.
template<class Type >
Foam::wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::GeometricBoundaryField &pmUbf) const
Protected Member Functions
template<class Type >
wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::GeometricBoundaryField &pmUbf) const
Create the corresponding patch types for cellMotion from those.
Protected Attributes
const fvMesh & fvMesh_
The fvMesh to be moved.
Detailed Description
Base class for fvMesh based motionSolvers.
Source files
fvMotionSolverCore.H
fvMotionSolverCore.C
Definition at line 48 of file fvMotionSolverCore.H.
Constructor & Destructor Documentation
fvMotionSolverCore()
fvMotionSolverCore (const polyMesh & mesh)
Construct from polyMesh.
Definition at line 38 of file fvMotionSolverCore.C.
Member Function Documentation
cellMotionBoundaryTypes() [1/2]
wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::GeometricBoundaryField & pmUbf) const protected
Create the corresponding patch types for cellMotion from those.
of the given pointMotion
ClassName()
ClassName ("displacementMotionSolver")
Runtime type information.
mesh()
const fvMesh& mesh () const inline
Return reference to the fvMesh to be moved.
Definition at line 84 of file fvMotionSolverCore.H.
References fvMotionSolverCore::fvMesh_.
cellMotionBoundaryTypes() [2/2]
Foam::wordList cellMotionBoundaryTypes (const typename GeometricField< Type, pointPatchField, pointMesh >::GeometricBoundaryField & pmUbf) const
Definition at line 34 of file fvMotionSolverCoreTemplates.C.
References Foam::endl(), forAll, Foam::isA(), OSstream::name(), patchi, Foam::Pout, and List< T >::setSize().
Member Data Documentation
fvMesh_
const fvMesh& fvMesh_ protected
The fvMesh to be moved.
Definition at line 56 of file fvMotionSolverCore.H.
Referenced by fvMotionSolverCore::mesh().
The documentation for this class was generated from the following files:
src/fvMotionSolver/fvMotionSolvers/fvMotionSolverCore/fvMotionSolverCore.H
src/fvMotionSolver/fvMotionSolvers/fvMotionSolverCore/fvMotionSolverCore.C
src/fvMotionSolver/fvMotionSolvers/fvMotionSolverCore/fvMotionSolverCoreTemplates.C