OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
motionDirectionalDiffusivity Class Reference
MotionDirectional finite volume mesh motion diffusivity.
Public Member Functions
TypeName ("motionDirectional")
Runtime type information.
motionDirectionalDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~motionDirectionalDiffusivity ()
Destructor.
virtual void correct ()
Correct the motion diffusivity.
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
Runtime type information.
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~uniformDiffusivity ()
Destructor.
virtual tmp< surfaceScalarField > operator() () const
Return diffusivity field.
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
Construct for the given fvMesh.
virtual ~motionDiffusivity ()
Destructor.
const fvMesh & mesh () const
Return reference to the mesh.
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Select null constructed.
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
MotionDirectional finite volume mesh motion diffusivity.
Source files
motionDirectionalDiffusivity.H
motionDirectionalDiffusivity.C
Definition at line 48 of file motionDirectionalDiffusivity.H.
Constructor & Destructor Documentation
motionDirectionalDiffusivity()
motionDirectionalDiffusivity (const fvMesh & mesh, Istream & mdData)
Construct for the given fvMesh and data Istream.
Definition at line 50 of file motionDirectionalDiffusivity.C.
~motionDirectionalDiffusivity()
~motionDirectionalDiffusivity () virtual
Destructor.
Definition at line 62 of file motionDirectionalDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("motionDirectional")
Runtime type information.
correct()
void correct () virtual
Correct the motion diffusivity.
Reimplemented from uniformDiffusivity.
Definition at line 68 of file motionDirectionalDiffusivity.C.
References Foam::cmptMultiply(), correct, Foam::dimVelocity, Foam::fvc::interpolate(), objectRegistry::lookupObject(), Foam::mag(), mesh, n, Vector< Cmpt >::one, Foam::solve(), and timeName.
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/motionDirectional/motionDirectionalDiffusivity.H
src/fvMotionSolver/motionDiffusivity/motionDirectional/motionDirectionalDiffusivity.C