OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
inversePointDistanceDiffusivity Class Reference
Inverse distance to the given patches motion diffusivity.
Public Member Functions
TypeName ("inversePointDistance")
Runtime type information.
inversePointDistanceDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~inversePointDistanceDiffusivity ()
Destructor.
virtual void correct ()
Correct the motion diffusivity.
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
Runtime type information.
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~uniformDiffusivity ()
Destructor.
virtual tmp< surfaceScalarField > operator() () const
Return diffusivity field.
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
Construct for the given fvMesh.
virtual ~motionDiffusivity ()
Destructor.
const fvMesh & mesh () const
Return reference to the mesh.
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Select null constructed.
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse distance to the given patches motion diffusivity.
Source files
inversePointDistanceDiffusivity.H
inversePointDistanceDiffusivity.C
Definition at line 48 of file inversePointDistanceDiffusivity.H.
Constructor & Destructor Documentation
inversePointDistanceDiffusivity()
inversePointDistanceDiffusivity (const fvMesh & mesh, Istream & mdData)
Construct for the given fvMesh and data Istream.
Definition at line 50 of file inversePointDistanceDiffusivity.C.
References correct.
~inversePointDistanceDiffusivity()
~inversePointDistanceDiffusivity () virtual
Destructor.
Definition at line 64 of file inversePointDistanceDiffusivity.C.
Member Function Documentation
TypeName()
TypeName ("inversePointDistance")
Runtime type information.
correct()
void correct () virtual
Correct the motion diffusivity.
Reimplemented from uniformDiffusivity.
Definition at line 70 of file inversePointDistanceDiffusivity.C.
References polyMesh::boundaryMesh(), primitiveMesh::cells(), f(), fvPatch::faceCells(), polyMesh::faces(), forAll, forAllConstIter(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), primitiveMesh::nInternalFaces(), nPoints, fvsPatchField< Type >::patch(), polyBoundaryMesh::patchSet(), points, List< T >::setSize(), List< T >::size(), Foam::sqrt(), and fvPatch::start().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inversePointDistance/inversePointDistanceDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inversePointDistance/inversePointDistanceDiffusivity.C