OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
option Class Reference
Finite volume options abtract base class. Provides a base set of controls, e.g.
Classes
class iNew
Return pointer to new fvOption object created.
Public Types
enum selectionModeType {
smPoints, smCellSet, smCellZone, smMapRegion,
smAll
}
Enumeration for selection mode types.
Public Member Functions
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh, const bool master=false)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const labelList & cells () const
Return const access to the cell set.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
bool & active ()
Return access to the source active flag.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void correct (volScalarField &fld)
Scalar.
virtual void correct (volVectorField &fld)
Vector.
virtual void correct (volSphericalTensorField &fld)
Spherical tensor.
virtual void correct (volSymmTensorField &fld)
Symmetric tensor.
virtual void correct (volTensorField &fld)
Tensor.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void setValue (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void setValue (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void setValue (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void setValue (fvMatrix< symmTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void setValue (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
virtual void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
virtual void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
virtual void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
virtual void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
virtual bool read (const dictionary &dict)
Read source dictionary.
Static Public Member Functions
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes
static const NamedEnum< selectionModeType, 5 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions
virtual bool alwaysApply () const
Flag to bypass the apply flag list checking.
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
bool active_
Source active flag.
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
word nbrRegionName_
Name of the neighbour region to map.
bool master_
Master or slave region.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Detailed Description
Finite volume options abtract base class. Provides a base set of controls, e.g.
type scalarExplicitSource // source type active on; // on/off switch timeStart 0.0; // start time duration 1000.0; // duration selectionMode cellSet; // cellSet // points //cellZone mapRegion Note: On evaluation, source/sink options are to be added to the equation rhs
Source files
fvOption.H
fvOption.C
fvOptionIO.C
Definition at line 70 of file fvOption.H.
Member Enumeration Documentation
selectionModeType
enum selectionModeType
Enumeration for selection mode types.
Enumerator
smPoints
smCellSet
smCellZone
smMapRegion
smAll
Definition at line 77 of file fvOption.H.
Constructor & Destructor Documentation
option()
option (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh, const bool master = false)
Construct from components.
Definition at line 253 of file fvOption.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, and option::New().
Referenced by option::setCellSet().
~option()
~option () virtual
Destructor.
Definition at line 331 of file fvOption.C.
Referenced by option::iNew::operator()().
Member Function Documentation
alwaysApply()
bool alwaysApply () const protected virtual
Flag to bypass the apply flag list checking.
Reimplemented in solidificationMeltingSource, effectivenessHeatExchangerSource, fixedTemperatureConstraint, and temperatureLimitsConstraint.
Definition at line 64 of file fvOption.C.
setSelection()
void setSelection (const dictionary & dict) protected
Set the cellSet or points selection.
Definition at line 70 of file fvOption.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, and dictionary::lookup().
setCellSet()
void setCellSet () protected
Set the cell set based on the user input selection mode.
Definition at line 110 of file fvOption.C.
References polyMesh::bounds(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, Foam::identity(), Foam::indent(), Foam::Info, HashSet< Key, Hash >::insert(), meshToMesh::interpolationMethodNames_, objectRegistry::lookupObject(), fvMesh::name(), Foam::nl, option::option(), Foam::reduce(), Foam::returnReduce(), fvMesh::time(), HashTable< T, Key, Hash >::toc(), and WarningIn.
TypeName()
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , option , dictionary , (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh) , (name, modelType, dict, mesh))
clone()
autoPtr<option> clone () const inline
Return clone.
Definition at line 201 of file fvOption.H.
References option::iNew::iNew(), and notImplemented.
New()
Foam::autoPtr< Foam::fv::option > New (const word & name, const dictionary & dict, const fvMesh & mesh) static
Return a reference to the selected fvOption model.
Definition at line 302 of file fvOption.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::indent(), Foam::Info, dictionary::lookup(), mesh, Foam::name(), and Foam::nl.
Referenced by option::iNew::operator()(), option::option(), and optionList::reset().
name()
const Foam::word & name () const inline
Return const access to the source name.
Definition at line 30 of file fvOptionI.H.
References option::name_.
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), option::iNew::operator()(), and optionList::readOptions().
mesh()
const Foam::fvMesh & mesh () const inline
Return const access to the mesh database.
Definition at line 36 of file fvOptionI.H.
References option::mesh_.
Referenced by option::iNew::operator()().
coeffs()
const Foam::dictionary & coeffs () const inline
Return dictionary.
Definition at line 42 of file fvOptionI.H.
References option::coeffs_.
Referenced by option::iNew::operator()().
active() [1/2]
bool active () const inline
Return const access to the source active flag.
Definition at line 48 of file fvOptionI.H.
References option::active_.
Referenced by option::iNew::operator()().
timeStart() [1/2]
Foam::scalar timeStart () const inline
Return const access to the time start.
Definition at line 54 of file fvOptionI.H.
References option::timeStart_.
Referenced by option::iNew::operator()().
duration() [1/2]
Foam::scalar duration () const inline
Return const access to the duration.
Definition at line 60 of file fvOptionI.H.
References option::duration_.
Referenced by option::iNew::operator()().
inTimeLimits()
bool inTimeLimits (const scalar time) const inline
Return true if within time limits.
Definition at line 66 of file fvOptionI.H.
References option::duration_, option::mesh_, fvMesh::time(), option::timeStart_, and dimensioned< Type >::value().
Referenced by option::iNew::operator()().
selectionMode()
const Foam::fv::option::selectionModeType & selectionMode () const inline
Return const access to the cell selection mode.
Definition at line 81 of file fvOptionI.H.
References option::selectionMode_.
Referenced by option::iNew::operator()().
cellSetName()
const Foam::word & cellSetName () const inline
Return const access to the name of cell set for "cellSet".
selectionMode
Definition at line 87 of file fvOptionI.H.
References option::cellSetName_.
Referenced by option::iNew::operator()().
V()
Foam::scalar V () const inline
Return const access to the total cell volume.
Definition at line 93 of file fvOptionI.H.
References option::V_.
Referenced by option::iNew::operator()().
nbrRegionName()
const Foam::word & nbrRegionName () const inline
Return const access to the neighbour region name.
Definition at line 129 of file fvOptionI.H.
References option::nbrRegionName_.
Referenced by option::iNew::operator()().
meshInterp()
const Foam::meshToMesh & meshInterp () const inline
Return const access to the mapToMap pointer.
Definition at line 135 of file fvOptionI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and option::meshInterpPtr_.
Referenced by interRegionHeatTransferModel::interpolate(), and option::iNew::operator()().
cells()
const Foam::labelList & cells () const inline
Return const access to the cell set.
Definition at line 99 of file fvOptionI.H.
References option::cells_.
Referenced by option::iNew::operator()().
setApplied()
void setApplied (const label fieldI) inline
Set the applied flag to true for field index fieldI.
Definition at line 105 of file fvOptionI.H.
References option::applied_.
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), and option::iNew::operator()().
active() [2/2]
bool & active () inline
Return access to the source active flag.
Definition at line 111 of file fvOptionI.H.
References option::active_.
timeStart() [2/2]
Foam::scalar & timeStart () inline
Return access to the time start.
Definition at line 117 of file fvOptionI.H.
References option::timeStart_.
duration() [2/2]
Foam::scalar & duration () inline
Return access to the duration.
Definition at line 123 of file fvOptionI.H.
References option::duration_.
isActive()
bool isActive () virtual
Is the source active?
Definition at line 337 of file fvOption.C.
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), and option::iNew::operator()().
applyToField()
Foam::label applyToField (const word & fieldName) const virtual
Return index of field name if found in fieldNames list.
Definition at line 355 of file fvOption.C.
References Foam::findIndex().
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), and option::iNew::operator()().
checkApplied()
void checkApplied () const virtual
Check that the source has been applied.
Definition at line 366 of file fvOption.C.
References Foam::endl(), forAll, and WarningIn.
Referenced by optionList::checkApplied(), and option::iNew::operator()().
correct() [1/5]
void correct (volScalarField & fld) virtual
Scalar.
Reimplemented in temperatureLimitsConstraint.
Definition at line 380 of file fvOption.C.
Referenced by optionList::correct(), and option::iNew::operator()().
correct() [2/5]
void correct (volVectorField & fld) virtual
Vector.
Reimplemented in pressureGradientExplicitSource.
Definition at line 386 of file fvOption.C.
correct() [3/5]
void correct (volSphericalTensorField & fld) virtual
Spherical tensor.
Definition at line 392 of file fvOption.C.
correct() [4/5]
void correct (volSymmTensorField & fld) virtual
Symmetric tensor.
Definition at line 398 of file fvOption.C.
correct() [5/5]
void correct (volTensorField & fld) virtual
Tensor.
Definition at line 404 of file fvOption.C.
References option::addSup().
addSup() [1/15]
void addSup (fvMatrix< scalar > & eqn, const label fieldI) virtual
Scalar.
Reimplemented in solidificationMeltingSource, effectivenessHeatExchangerSource, and interRegionHeatTransferModel.
Definition at line 411 of file fvOption.C.
Referenced by option::addSup(), option::correct(), optionList::operator()(), and option::iNew::operator()().
addSup() [2/15]
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Vector.
Reimplemented in solidificationMeltingSource, rotorDiskSource, actuationDiskSource, radialActuationDiskSource, interRegionExplicitPorositySource, explicitPorositySource, pressureGradientExplicitSource, and MRFSource.
Definition at line 421 of file fvOption.C.
References option::addSup().
addSup() [3/15]
void addSup (fvMatrix< symmTensor > & eqn, const label fieldI) virtual
Spherical tensor.
Definition at line 441 of file fvOption.C.
References option::addSup().
addSup() [4/15]
void addSup (fvMatrix< sphericalTensor > & eqn, const label fieldI) virtual
Symmetric tensor.
Definition at line 431 of file fvOption.C.
References option::addSup().
addSup() [5/15]
void addSup (fvMatrix< tensor > & eqn, const label fieldI) virtual
Tensor.
Definition at line 451 of file fvOption.C.
References option::addSup().
addSup() [6/15]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldI) virtual
Scalar.
Reimplemented in effectivenessHeatExchangerSource, solidificationMeltingSource, and interRegionHeatTransferModel.
Definition at line 461 of file fvOption.C.
References option::addSup().
addSup() [7/15]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Vector.
Reimplemented in solidificationMeltingSource, rotorDiskSource, actuationDiskSource, radialActuationDiskSource, interRegionExplicitPorositySource, explicitPorositySource, pressureGradientExplicitSource, and MRFSource.
Definition at line 472 of file fvOption.C.
References option::addSup().
addSup() [8/15]
void addSup (const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldI) virtual
Spherical tensor.
Definition at line 494 of file fvOption.C.
References option::addSup().
addSup() [9/15]
void addSup (const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldI) virtual
Symmetric tensor.
Definition at line 483 of file fvOption.C.
References option::addSup().
addSup() [10/15]
void addSup (const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldI) virtual
Tensor.
Definition at line 505 of file fvOption.C.
References option::addSup().
addSup() [11/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldI) virtual
Scalar.
Definition at line 516 of file fvOption.C.
References option::addSup().
addSup() [12/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Vector.
Reimplemented in explicitPorositySource.
Definition at line 528 of file fvOption.C.
References option::addSup().
addSup() [13/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldI) virtual
Spherical tensor.
Definition at line 552 of file fvOption.C.
References option::addSup().
addSup() [14/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldI) virtual
Symmetric tensor.
Definition at line 540 of file fvOption.C.
References option::addSup().
addSup() [15/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldI) virtual
Tensor.
Definition at line 564 of file fvOption.C.
setValue() [1/5]
void setValue (fvMatrix< scalar > & eqn, const label fieldI) virtual
Scalar.
Reimplemented in fixedTemperatureConstraint.
Definition at line 575 of file fvOption.C.
Referenced by optionList::constrain(), option::iNew::operator()(), and option::setValue().
setValue() [2/5]
void setValue (fvMatrix< vector > & eqn, const label fieldI) virtual
Vector.
Reimplemented in pressureGradientExplicitSource.
Definition at line 581 of file fvOption.C.
References option::setValue().
setValue() [3/5]
void setValue (fvMatrix< sphericalTensor > & eqn, const label fieldI) virtual
Spherical tensor.
Definition at line 588 of file fvOption.C.
References option::setValue().
setValue() [4/5]
void setValue (fvMatrix< symmTensor > & eqn, const label fieldI) virtual
Symmetric tensor.
Definition at line 598 of file fvOption.C.
setValue() [5/5]
void setValue (fvMatrix< tensor > & eqn, const label fieldI) virtual
Tensor.
Definition at line 607 of file fvOption.C.
makeRelative() [1/3]
void makeRelative (surfaceScalarField & phi) const virtual
Make the given absolute flux relative.
Reimplemented in MRFSource.
Definition at line 613 of file fvOption.C.
Referenced by option::makeRelative(), and option::iNew::operator()().
makeRelative() [2/3]
void makeRelative (FieldField< fvsPatchField, scalar > & phi) const virtual
Make the given absolute boundary flux relative.
Reimplemented in MRFSource.
Definition at line 620 of file fvOption.C.
References option::makeRelative().
makeRelative() [3/3]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const virtual
Make the given absolute mass-flux relative.
Reimplemented in MRFSource.
Definition at line 629 of file fvOption.C.
makeAbsolute() [1/2]
void makeAbsolute (surfaceScalarField & phi) const virtual
Make the given relative flux absolute.
Reimplemented in MRFSource.
Definition at line 638 of file fvOption.C.
Referenced by option::iNew::operator()().
makeAbsolute() [2/2]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const virtual
Make the given relative mass-flux absolute.
Reimplemented in MRFSource.
Definition at line 645 of file fvOption.C.
writeHeader()
void writeHeader (Ostream & os) const virtual
Write the source header information.
Definition at line 30 of file fvOptionIO.C.
References token::BEGIN_BLOCK, Foam::incrIndent(), Foam::indent(), option::name_, and Foam::nl.
Referenced by option::iNew::operator()().
writeFooter()
void writeFooter (Ostream & os) const virtual
Write the source footer information.
Definition at line 37 of file fvOptionIO.C.
References Foam::decrIndent(), token::END_BLOCK, Foam::endl(), and Foam::indent().
Referenced by option::iNew::operator()().
writeData()
void writeData (Ostream & os) const virtual
Write the source properties.
Reimplemented in solidificationMeltingSource, effectivenessHeatExchangerSource, rotorDiskSource, CodedSource< Type >, actuationDiskSource, SemiImplicitSource< Type >, interRegionHeatTransferModel, radialActuationDiskSource, MRFSource, interRegionExplicitPorositySource, explicitPorositySource, pressureGradientExplicitSource, fixedTemperatureConstraint, temperatureLimitsConstraint, ExplicitSetValue< Type >, variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
Definition at line 43 of file fvOptionIO.C.
References Foam::abort(), option::active_, option::cellSetName_, option::duration_, token::END_STATEMENT, Foam::FatalError, FatalErrorIn, Foam::nl, option::points_, option::selectionMode_, option::selectionModeTypeNames_, option::smAll, option::smCellSet, option::smCellZone, option::smMapRegion, option::smPoints, option::timeStart_, and Ostream::writeKeyword().
Referenced by option::iNew::operator()().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented in solidificationMeltingSource, effectivenessHeatExchangerSource, rotorDiskSource, CodedSource< Type >, actuationDiskSource, SemiImplicitSource< Type >, interRegionHeatTransferModel, radialActuationDiskSource, MRFSource, interRegionExplicitPorositySource, explicitPorositySource, pressureGradientExplicitSource, fixedTemperatureConstraint, temperatureLimitsConstraint, ExplicitSetValue< Type >, variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
Definition at line 90 of file fvOptionIO.C.
References option::active_, option::coeffs_, option::duration_, dictionary::lookup(), option::modelType_, Foam::readBool(), dictionary::readIfPresent(), dictionary::subDict(), and option::timeStart_.
Referenced by option::iNew::operator()(), constantHeatTransfer::read(), tabulatedHeatTransfer::read(), variableHeatTransfer::read(), temperatureLimitsConstraint::read(), fixedTemperatureConstraint::read(), explicitPorositySource::read(), interRegionExplicitPorositySource::read(), MRFSource::read(), radialActuationDiskSource::read(), interRegionHeatTransferModel::read(), actuationDiskSource::read(), effectivenessHeatExchangerSource::read(), solidificationMeltingSource::read(), and optionList::readOptions().
Member Data Documentation
selectionModeTypeNames_
const NamedEnum< fv::option::selectionModeType, 5 > selectionModeTypeNames_ static
Word list of selection mode type names.
Definition at line 88 of file fvOption.H.
Referenced by NamedEnum< directionType, 3 >::names(), and option::writeData().
name_
const word name_ protected
Source name.
Definition at line 96 of file fvOption.H.
Referenced by option::name(), solidificationMeltingSource::writeData(), and option::writeHeader().
modelType_
const word modelType_ protected
Model type.
Definition at line 99 of file fvOption.H.
Referenced by option::read().
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 102 of file fvOption.H.
Referenced by option::inTimeLimits(), and option::mesh().
dict_
dictionary dict_ protected
Top level source dictionary.
Definition at line 105 of file fvOption.H.
Referenced by solidificationMeltingSource::writeData().
coeffs_
dictionary coeffs_ protected
Dictionary containing source coefficients.
Definition at line 108 of file fvOption.H.
Referenced by option::coeffs(), solidificationMeltingSource::read(), and option::read().
active_
bool active_ protected
Source active flag.
Definition at line 111 of file fvOption.H.
Referenced by option::active(), option::read(), and option::writeData().
timeStart_
scalar timeStart_ protected
Time start.
Definition at line 114 of file fvOption.H.
Referenced by option::inTimeLimits(), option::read(), option::timeStart(), and option::writeData().
duration_
scalar duration_ protected
Duration.
Definition at line 117 of file fvOption.H.
Referenced by option::duration(), option::inTimeLimits(), option::read(), and option::writeData().
selectionMode_
selectionModeType selectionMode_ protected
Cell selection mode.
Definition at line 120 of file fvOption.H.
Referenced by option::selectionMode(), and option::writeData().
cellSetName_
word cellSetName_ protected
Name of cell set for "cellSet" and "cellZone" selectionMode.
Definition at line 123 of file fvOption.H.
Referenced by option::cellSetName(), and option::writeData().
points_
List<point> points_ protected
List of points for "points" selectionMode.
Definition at line 126 of file fvOption.H.
Referenced by option::writeData().
cells_
labelList cells_ protected
Set of cells to apply source to.
Definition at line 129 of file fvOption.H.
Referenced by option::cells().
V_
scalar V_ protected
Sum of cell volumes.
Definition at line 132 of file fvOption.H.
Referenced by option::V().
meshInterpPtr_
autoPtr<meshToMesh> meshInterpPtr_ protected
Mesh to mesh interpolation object.
Definition at line 137 of file fvOption.H.
Referenced by option::meshInterp().
nbrRegionName_
word nbrRegionName_ protected
Name of the neighbour region to map.
Definition at line 140 of file fvOption.H.
Referenced by option::nbrRegionName().
master_
bool master_ protected
Master or slave region.
Definition at line 143 of file fvOption.H.
fieldNames_
wordList fieldNames_ protected
Field names to apply source to - populated by derived models.
Definition at line 147 of file fvOption.H.
applied_
List<bool> applied_ protected
Applied flag list - corresponds to each fieldNames_ entry.
Definition at line 150 of file fvOption.H.
Referenced by option::setApplied().
The documentation for this class was generated from the following files:
src/fvOptions/fvOptions/fvOption.H
src/fvOptions/fvOptions/fvOption.C
src/fvOptions/fvOptions/fvOptionI.H
src/fvOptions/fvOptions/fvOptionIO.C