OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
profileModel Class Reference abstract
Base class for profile models.
Public Member Functions
TypeName ("profileModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, profileModel, dictionary,(const dictionary &dict, const word &modelName),(dict, modelName))
profileModel (const dictionary &dict, const word &modelName)
Constructor.
virtual ~profileModel ()
Destructor.
const word & name () const
Return const access to the source name.
virtual void Cdl (const scalar alpha, scalar &Cd, scalar &Cl) const =0
Return the Cd and Cl for a given angle-of-attack.
Static Public Member Functions
static autoPtr< profileModel > New (const dictionary &dict)
Return a reference to the selected fvOption model.
Protected Member Functions
bool readFromFile () const
Return ture if file name is set.
Protected Attributes
const dictionary dict_
Coefficients dictionary.
const word name_
Name of profile model.
fileName fName_
File name (optional)
Detailed Description
Base class for profile models.
Source files
profileModel.H
profileModel.C
Definition at line 50 of file profileModel.H.
Constructor & Destructor Documentation
profileModel()
profileModel (const dictionary & dict, const word & modelName)
Constructor.
Definition at line 48 of file profileModel.C.
References profileModel::fName_, and dictionary::readIfPresent().
~profileModel()
~profileModel () virtual
Destructor.
Definition at line 59 of file profileModel.C.
Member Function Documentation
readFromFile()
bool readFromFile () const protected
Return ture if file name is set.
Definition at line 40 of file profileModel.C.
References fileName::null.
TypeName()
TypeName ("profileModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , profileModel , dictionary , (const dictionary &dict, const word &modelName) , (dict, modelName))
New()
Foam::autoPtr< Foam::profileModel > New (const dictionary & dict) static
Return a reference to the selected fvOption model.
Definition at line 72 of file profileModel.C.
References dict, dictionaryName::dictName(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by profileModel::name().
name()
const Foam::word & name () const
Return const access to the source name.
Definition at line 65 of file profileModel.C.
References profileModel::name_, and profileModel::New().
Referenced by profileModelList::connectBlades().
Cdl()
virtual void Cdl (const scalar alpha, scalar & Cd, scalar & Cl) const pure virtual
Return the Cd and Cl for a given angle-of-attack.
Implemented in seriesProfile, and lookupProfile.
Member Data Documentation
dict_
const dictionary dict_ protected
Coefficients dictionary.
Definition at line 58 of file profileModel.H.
name_
const word name_ protected
Name of profile model.
Definition at line 61 of file profileModel.H.
Referenced by profileModel::name().
fName_
fileName fName_ protected
File name (optional)
Definition at line 64 of file profileModel.H.
Referenced by profileModel::profileModel().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/profileModel.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/profileModel.C