OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
optionList Class Reference
List of finite volume options.
Public Member Functions
TypeName ("optionList")
Runtime type information.
optionList (const fvMesh &mesh)
Construct null.
optionList (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
virtual ~optionList ()
Destructor.
void reset (const dictionary &dict)
Reset the source list.
template<class Type >
void correct (GeometricField< Type, fvPatchField, volMesh > &fld)
Correct.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Return source for equation with specified name.
template<class Type >
void constrain (fvMatrix< Type > &eqn)
Apply constraints to equation.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
tmp< FieldField< fvsPatchField, scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > &tphi) const
Return the given absolute boundary flux relative.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual bool read (const dictionary &dict)
Read dictionary.
virtual bool writeData (Ostream &os) const
Write data to Ostream.
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Public Member Functions inherited from PtrList< option >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< option > &)
Copy constructor.
PtrList (const PtrList< option > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< option > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< option > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< option > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
option & first ()
Return reference to the first element of the list.
const option & first () const
Return reference to first element of the list.
option & last ()
Return reference to the last element of the list.
const option & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (option *)
Append an element at the end of the list.
void append (const autoPtr< option > &)
void append (const tmp< option > &)
void transfer (PtrList< option > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< option > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< option > set (const label, option *)
Set element. Return old element (can be NULL).
autoPtr< option > set (const label, const autoPtr< option > &)
autoPtr< option > set (const label, const tmp< option > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const option & operator[] (const label) const
Return element const reference.
option & operator[] (const label)
Return element reference.
const option * operator() (const label) const
Return element const pointer.
PtrList< option > & operator= (const PtrList< option > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
Protected Member Functions
const dictionary & optionsDict (const dictionary &dict) const
Return the "options" sub-dictionary if present otherwise return dict.
bool readOptions (const dictionary &dict)
Read options dictionary.
void checkApplied () const
Check that all sources have been applied.
optionList (const optionList &)
Disallow default bitwise copy construct.
void operator= (const optionList &)
Disallow default bitwise assignment.
Protected Member Functions inherited from PtrList< option >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
label checkTimeIndex_
Time index to check that all defined sources have been applied.
Friends
Ostream & operator<< (Ostream &os, const optionList &options)
Ostream operator.
Additional Inherited Members
Public Types inherited from PtrList< option >
typedef option value_type
Type of values the PtrList contains.
typedef option & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const option & const_reference
Type that can be used for storing into constant PtrList::value_type.
Detailed Description
List of finite volume options.
SourceFile optionList.C
Definition at line 53 of file fvOptionList.H.
Constructor & Destructor Documentation
optionList() [1/3]
optionList (const optionList &) protected
Disallow default bitwise copy construct.
optionList() [2/3]
optionList (const fvMesh & mesh)
Construct null.
Definition at line 98 of file fvOptionList.C.
optionList() [3/3]
optionList (const fvMesh & mesh, const dictionary & dict)
Construct from mesh and dictionary.
Definition at line 88 of file fvOptionList.C.
References optionList::optionsDict(), and optionList::reset().
~optionList()
virtual ~optionList () inline virtual
Destructor.
Definition at line 102 of file fvOptionList.H.
References Foam::constant::atomic::alpha, optionList::constrain(), optionList::correct(), dict, fld(), optionList::makeAbsolute(), optionList::makeRelative(), PtrList< option >::operator, phi, optionList::read(), optionList::relative(), optionList::reset(), rho, and optionList::writeData().
Member Function Documentation
optionsDict()
const Foam::dictionary & optionsDict (const dictionary & dict) const protected
Return the "options" sub-dictionary if present otherwise return dict.
Definition at line 43 of file fvOptionList.C.
References dict, dictionary::found(), and dictionary::subDict().
Referenced by optionList::optionList(), and optionList::read().
readOptions()
bool readOptions (const dictionary & dict) protected
Read options dictionary.
Definition at line 58 of file fvOptionList.C.
References forAll, option::name(), option::read(), and dictionary::subDict().
Referenced by optionList::read().
checkApplied()
void checkApplied () const protected
Check that all sources have been applied.
Definition at line 73 of file fvOptionList.C.
References option::checkApplied(), and forAll.
Referenced by optionList::constrain().
operator=()
void operator= (const optionList &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("optionList")
Runtime type information.
reset()
void reset (const dictionary & dict)
Reset the source list.
Definition at line 108 of file fvOptionList.C.
References forAllConstIter(), optionList::mesh_, Foam::name(), option::New(), and PtrList< option >::setSize().
Referenced by optionList::optionList(), and optionList::~optionList().
correct()
void correct (GeometricField< Type, fvPatchField, volMesh > & fld)
Correct.
Definition at line 30 of file fvOptionListTemplates.C.
References option::applyToField(), option::correct(), Foam::endl(), forAll, Foam::Info, option::isActive(), IOobject::name(), option::name(), PtrList< option >::operator, and option::setApplied().
Referenced by optionList::~optionList().
operator()() [1/12]
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld)
Return source for equation.
operator()() [2/12]
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Return source for equation with specified name.
operator()() [3/12]
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Return source for equation.
operator()() [4/12]
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Return source for equation with specified name.
operator()() [5/12]
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Return source for equation.
operator()() [6/12]
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Return source for equation with specified name.
constrain()
void constrain (fvMatrix< Type > & eqn)
Apply constraints to equation.
Definition at line 222 of file fvOptionListTemplates.C.
References option::applyToField(), optionList::checkApplied(), Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), PtrList< option >::operator[](), fvMatrix< Type >::psi(), option::setApplied(), and option::setValue().
Referenced by optionList::~optionList().
makeRelative() [1/2]
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative.
Definition at line 139 of file fvOptionList.C.
References forAll, and PtrList< option >::operator[]().
Referenced by optionList::~optionList().
makeRelative() [2/2]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative.
Definition at line 149 of file fvOptionList.C.
References forAll, PtrList< option >::operator[](), and optionList::relative().
relative()
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > & tphi) const
Return the given absolute boundary flux relative.
Definition at line 163 of file fvOptionList.C.
References forAll, and PtrList< option >::operator[]().
Referenced by optionList::makeRelative(), and optionList::~optionList().
makeAbsolute() [1/2]
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute.
Definition at line 178 of file fvOptionList.C.
References forAll, and PtrList< option >::operator[]().
Referenced by optionList::~optionList().
makeAbsolute() [2/2]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute.
Definition at line 188 of file fvOptionList.C.
References forAll, and PtrList< option >::operator[]().
read()
bool read (const dictionary & dict) virtual
Read dictionary.
Definition at line 200 of file fvOptionList.C.
References optionList::optionsDict(), and optionList::readOptions().
Referenced by IOoptionList::read(), and optionList::~optionList().
writeData()
bool writeData (Ostream & os) const virtual
Write data to Ostream.
Definition at line 206 of file fvOptionList.C.
References forAll, IOstream::good(), Foam::nl, and PtrList< option >::operator[]().
Referenced by optionList::~optionList().
operator()() [7/12]
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld)
Definition at line 63 of file fvOptionListTemplates.C.
References fld(), and PtrList< option >::operator.
operator()() [8/12]
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Definition at line 73 of file fvOptionListTemplates.C.
References option::addSup(), option::applyToField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), PtrList< option >::operator, and option::setApplied().
operator()() [9/12]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Definition at line 114 of file fvOptionListTemplates.C.
References IOobject::name(), and PtrList< option >::operator.
operator()() [10/12]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Definition at line 125 of file fvOptionListTemplates.C.
References option::addSup(), option::applyToField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), PtrList< option >::operator, and option::setApplied().
operator()() [11/12]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Definition at line 167 of file fvOptionListTemplates.C.
References IOobject::name(), and PtrList< option >::operator.
operator()() [12/12]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Definition at line 179 of file fvOptionListTemplates.C.
References option::addSup(), option::applyToField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), and option::setApplied().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const optionList & options) friend
Ostream operator.
Definition at line 225 of file fvOptionList.C.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 62 of file fvOptionList.H.
Referenced by optionList::reset().
checkTimeIndex_
label checkTimeIndex_ protected
Time index to check that all defined sources have been applied.
Definition at line 65 of file fvOptionList.H.
The documentation for this class was generated from the following files:
src/fvOptions/fvOptions/fvOptionList.H
src/fvOptions/fvOptions/fvOptionList.C
src/fvOptions/fvOptions/fvOptionListTemplates.C