OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
option::iNew Class Reference
Return pointer to new fvOption object created.
Public Member Functions
iNew (const fvMesh &mesh, const word &name)
autoPtr< option > operator() (Istream &is) const
Detailed Description
Return pointer to new fvOption object created.
on the freestore from an Istream
Definition at line 209 of file fvOption.H.
Constructor & Destructor Documentation
iNew()
iNew (const fvMesh & mesh, const word & name) inline
Definition at line 218 of file fvOption.H.
Referenced by option::clone().
Member Function Documentation
operator()()
autoPtr<option> operator() (Istream & is) const inline
Definition at line 227 of file fvOption.H.
References option::active(), option::addSup(), Foam::constant::atomic::alpha, option::applyToField(), option::cells(), option::cellSetName(), option::checkApplied(), option::coeffs(), option::correct(), dict, option::duration(), fld(), option::inTimeLimits(), option::isActive(), option::makeAbsolute(), option::makeRelative(), option::mesh(), option::meshInterp(), option::name(), option::nbrRegionName(), option::New(), phi, option::read(), rho, option::selectionMode(), option::setApplied(), option::setValue(), option::timeStart(), option::V(), option::writeData(), option::writeFooter(), option::writeHeader(), and option::~option().
The documentation for this class was generated from the following file:
src/fvOptions/fvOptions/fvOption.H