OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
explicitPorositySource Class Reference
Explicit porosity source.
Public Member Functions
TypeName ("explicitPorositySource")
Runtime type information.
explicitPorositySource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~explicitPorositySource ()
Destructor.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Add implicit contribution to momentum equation.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Add implicit contribution to compressible momentum equation.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Add implicit contribution to phase momentum equation.
virtual void writeData (Ostream &) const
Write data.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh, const bool master=false)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const labelList & cells () const
Return const access to the cell set.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
bool & active ()
Return access to the source active flag.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void correct (volScalarField &fld)
Scalar.
virtual void correct (volVectorField &fld)
Vector.
virtual void correct (volSphericalTensorField &fld)
Spherical tensor.
virtual void correct (volSymmTensorField &fld)
Symmetric tensor.
virtual void correct (volTensorField &fld)
Tensor.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void setValue (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void setValue (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void setValue (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void setValue (fvMatrix< symmTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void setValue (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
virtual void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
virtual void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
virtual void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
virtual void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
Protected Attributes
autoPtr< porosityModel > porosityPtr_
Run-time selectable porosity model.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
bool active_
Source active flag.
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
word nbrRegionName_
Name of the neighbour region to map.
bool master_
Master or slave region.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from option
enum selectionModeType {
smPoints, smCellSet, smCellZone, smMapRegion,
smAll
}
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from option
static const NamedEnum< selectionModeType, 5 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions inherited from option
virtual bool alwaysApply () const
Flag to bypass the apply flag list checking.
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Detailed Description
Explicit porosity source.
Source usage
Example usage, here employing the Darcy-Forchheimer model:
explicitPorositySourceCoeffs
{
    type            DarcyForchheimer;
    DarcyForchheimerCoeffs
    {
        d   d [0 -2 0 0 0 0 0] (5e7 -1000 -1000);
        f   f [0 -1 0 0 0 0 0] (0 0 0);
        coordinateSystem
        {
            type    cartesian;
            origin  (0 0 0);
            coordinateRotation
            {
                type    axesRotation;
                e1  (0.70710678 0.70710678 0);
                e2  (0 0 1);
            }
        }
    }
}
Note: The porous region must be selected as a cellZone.
Source files
explicitPorositySource.H
explicitPorositySource.C
Definition at line 85 of file explicitPorositySource.H.
Constructor & Destructor Documentation
explicitPorositySource()
explicitPorositySource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 52 of file explicitPorositySource.C.
References explicitPorositySource::addSup(), Foam::exit(), Foam::FatalError, FatalErrorIn, and porosityModel::New().
~explicitPorositySource()
virtual ~explicitPorositySource () inline virtual
Destructor.
Definition at line 128 of file explicitPorositySource.H.
References explicitPorositySource::addSup(), Foam::constant::atomic::alpha, dict, explicitPorositySource::read(), rho, and explicitPorositySource::writeData().
Member Function Documentation
TypeName()
TypeName ("explicitPorositySource")
Runtime type information.
addSup() [1/3]
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Add implicit contribution to momentum equation.
Reimplemented from option.
Definition at line 88 of file explicitPorositySource.C.
References fvMatrix< Type >::dimensions(), and fvMatrix< Type >::psi().
Referenced by explicitPorositySource::addSup(), explicitPorositySource::explicitPorositySource(), and explicitPorositySource::~explicitPorositySource().
addSup() [2/3]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Add implicit contribution to compressible momentum equation.
Reimplemented from option.
Definition at line 100 of file explicitPorositySource.C.
References explicitPorositySource::addSup(), fvMatrix< Type >::dimensions(), and fvMatrix< Type >::psi().
addSup() [3/3]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Add implicit contribution to phase momentum equation.
Reimplemented from option.
Definition at line 113 of file explicitPorositySource.C.
References fvMatrix< Type >::dimensions(), and fvMatrix< Type >::psi().
writeData()
void writeData (Ostream & os) const virtual
Write data.
Reimplemented from option.
Definition at line 126 of file explicitPorositySource.C.
References Foam::endl(), Foam::indent(), and Ostream::write().
Referenced by explicitPorositySource::~explicitPorositySource().
read()
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from option.
Definition at line 133 of file explicitPorositySource.C.
References option::read().
Referenced by explicitPorositySource::~explicitPorositySource().
Member Data Documentation
porosityPtr_
autoPtr<porosityModel> porosityPtr_ protected
Run-time selectable porosity model.
Definition at line 95 of file explicitPorositySource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/explicitPorositySource/explicitPorositySource.H
src/fvOptions/sources/derived/explicitPorositySource/explicitPorositySource.C