OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
lookupProfile Class Reference
Look-up based profile data - drag and lift coefficients are lineraly interpolated based on the supplied angle of attack.
Public Member Functions
TypeName ("lookup")
Runtime type information.
lookupProfile (const dictionary &dict, const word &modelName)
Constructor.
virtual void Cdl (const scalar alpha, scalar &Cd, scalar &Cl) const
Return the Cd and Cl for a given angle-of-attack.
Public Member Functions inherited from profileModel
TypeName ("profileModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, profileModel, dictionary,(const dictionary &dict, const word &modelName),(dict, modelName))
profileModel (const dictionary &dict, const word &modelName)
Constructor.
virtual ~profileModel ()
Destructor.
const word & name () const
Return const access to the source name.
Protected Member Functions
void interpolateWeights (const scalar &xIn, const List< scalar > &values, label &i1, label &i2, scalar &ddx) const
Return the interpolation indices and gradient.
Protected Member Functions inherited from profileModel
bool readFromFile () const
Return ture if file name is set.
Protected Attributes
List< scalar > AOA_
List of angle-of-attack values [deg] on input, converted to [rad].
List< scalar > Cd_
List of drag coefficient values.
List< scalar > Cl_
List of lift coefficient values.
Protected Attributes inherited from profileModel
const dictionary dict_
Coefficients dictionary.
const word name_
Name of profile model.
fileName fName_
File name (optional)
Additional Inherited Members
Static Public Member Functions inherited from profileModel
static autoPtr< profileModel > New (const dictionary &dict)
Return a reference to the selected fvOption model.
Detailed Description
Look-up based profile data - drag and lift coefficients are lineraly interpolated based on the supplied angle of attack.
Input in list format:
data ((AOA1 Cd1 Cl2) (AOA2 Cd2 Cl2) ... (AOAN CdN CdN));
where: AOA = angle of attack [deg] converted to [rad] internally Cd = drag coefficient Cl = lift coefficient
Source files
lookupProfile.H
lookupProfile.C
Definition at line 65 of file lookupProfile.H.
Constructor & Destructor Documentation
lookupProfile()
lookupProfile (const dictionary & dict, const word & modelName)
Constructor.
Definition at line 87 of file lookupProfile.C.
References Foam::degToRad(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, dictionary::lookup(), List< T >::setSize(), and List< T >::size().
Referenced by lookupProfile::interpolateWeights().
Member Function Documentation
interpolateWeights()
void interpolateWeights (const scalar & xIn, const List< scalar > & values, label & i1, label & i2, scalar & ddx) const protected
Return the interpolation indices and gradient.
Definition at line 44 of file lookupProfile.C.
References lookupProfile::lookupProfile(), and List< T >::size().
TypeName()
TypeName ("lookup")
Runtime type information.
Cdl()
void Cdl (const scalar alpha, scalar & Cd, scalar & Cl) const virtual
Return the Cd and Cl for a given angle-of-attack.
Implements profileModel.
Definition at line 137 of file lookupProfile.C.
Member Data Documentation
AOA_
List<scalar> AOA_ protected
List of angle-of-attack values [deg] on input, converted to [rad].
Definition at line 75 of file lookupProfile.H.
Cd_
List<scalar> Cd_ protected
List of drag coefficient values.
Definition at line 78 of file lookupProfile.H.
Cl_
List<scalar> Cl_ protected
List of lift coefficient values.
Definition at line 81 of file lookupProfile.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/lookup/lookupProfile.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/lookup/lookupProfile.C