OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
seriesProfile Class Reference
Series-up based profile data - drag and lift coefficients computed as sum of cosine series.
Public Member Functions
TypeName ("series")
Runtime type information.
seriesProfile (const dictionary &dict, const word &modelName)
Constructor.
virtual void Cdl (const scalar alpha, scalar &Cd, scalar &Cl) const
Return the Cd and Cl for a given angle-of-attack.
Public Member Functions inherited from profileModel
TypeName ("profileModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, profileModel, dictionary,(const dictionary &dict, const word &modelName),(dict, modelName))
profileModel (const dictionary &dict, const word &modelName)
Constructor.
virtual ~profileModel ()
Destructor.
const word & name () const
Return const access to the source name.
Protected Member Functions
scalar evaluateDrag (const scalar &xIn, const List< scalar > &values) const
Drag.
scalar evaluateLift (const scalar &xIn, const List< scalar > &values) const
Lift.
Protected Member Functions inherited from profileModel
bool readFromFile () const
Return ture if file name is set.
Protected Attributes
List< scalar > CdCoeffs_
List of drag coefficient values.
List< scalar > ClCoeffs_
List of lift coefficient values.
Protected Attributes inherited from profileModel
const dictionary dict_
Coefficients dictionary.
const word name_
Name of profile model.
fileName fName_
File name (optional)
Additional Inherited Members
Static Public Member Functions inherited from profileModel
static autoPtr< profileModel > New (const dictionary &dict)
Return a reference to the selected fvOption model.
Detailed Description
Series-up based profile data - drag and lift coefficients computed as sum of cosine series.
Cd = sum_i(CdCoeff)*cos(i*AOA) Cl = sum_i(ClCoeff)*sin(i*AOA)
where: AOA = angle of attack [deg] converted to [rad] internally Cd = drag coefficent Cl = lift coefficent
Input in two (arbitrary length) lists:
CdCoeffs (coeff1 coeff2 ... coeffN); ClCoeffs (coeff1 coeff2 ... coeffN);
Source files
seriesProfile.H
seriesProfile.C
Definition at line 63 of file seriesProfile.H.
Constructor & Destructor Documentation
seriesProfile()
seriesProfile (const dictionary & dict, const word & modelName)
Constructor.
Definition at line 80 of file seriesProfile.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, and dictionary::lookup().
Referenced by seriesProfile::evaluateLift().
Member Function Documentation
evaluateDrag()
Foam::scalar evaluateDrag (const scalar & xIn, const List< scalar > & values) const protected
Drag.
Definition at line 42 of file seriesProfile.C.
References Foam::cos(), seriesProfile::evaluateLift(), and forAll.
evaluateLift()
Foam::scalar evaluateLift (const scalar & xIn, const List< scalar > & values) const protected
Lift.
Definition at line 59 of file seriesProfile.C.
References forAll, seriesProfile::seriesProfile(), and Foam::sin().
Referenced by seriesProfile::evaluateDrag().
TypeName()
TypeName ("series")
Runtime type information.
Cdl()
void Cdl (const scalar alpha, scalar & Cd, scalar & Cl) const virtual
Return the Cd and Cl for a given angle-of-attack.
Implements profileModel.
Definition at line 128 of file seriesProfile.C.
Member Data Documentation
CdCoeffs_
List<scalar> CdCoeffs_ protected
List of drag coefficient values.
Definition at line 73 of file seriesProfile.H.
ClCoeffs_
List<scalar> ClCoeffs_ protected
List of lift coefficient values.
Definition at line 76 of file seriesProfile.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/series/seriesProfile.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/series/seriesProfile.C