OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interRegionHeatTransferModel Class Reference abstract
Base class for inter region heat exchange. The derived classes must provide the heat transfer coeffisine (htc) which is used as follows in the energy equation.
Public Member Functions
TypeName ("interRegionHeatTransferModel")
Runtime type information.
interRegionHeatTransferModel (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~interRegionHeatTransferModel ()
Destructor.
const volScalarField & htc () const
Return the heat transfer coefficient.
const interRegionHeatTransferModel & nbrModel () const
Return const access to the neighbour model.
interRegionHeatTransferModel & nbrModel ()
Return access to the neighbour model.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Source term to energy equation.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Source term to compressible energy equation.
virtual void calculateHtc ()=0
Calculate heat transfer coefficient.
virtual void writeData (Ostream &) const
Write data.
virtual bool read (const dictionary &dict)
Read dictionary.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &field) const
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh, const bool master=false)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const labelList & cells () const
Return const access to the cell set.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
bool & active ()
Return access to the source active flag.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void correct (volScalarField &fld)
Scalar.
virtual void correct (volVectorField &fld)
Vector.
virtual void correct (volSphericalTensorField &fld)
Spherical tensor.
virtual void correct (volSymmTensorField &fld)
Symmetric tensor.
virtual void correct (volTensorField &fld)
Tensor.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void setValue (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void setValue (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void setValue (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void setValue (fvMatrix< symmTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void setValue (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
virtual void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
virtual void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
virtual void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
virtual void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
Protected Member Functions
void setNbrModel ()
Set the neighbour interRegionHeatTransferModel.
void correct ()
Correct to calculate the inter-region heat transfer coefficient.
template<class Type >
tmp< Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
Interpolate field with nbrModel specified.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &field) const
Interpolate field without nbrModel specified.
template<class Type >
void interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field, Field< Type > &result) const
Interpolate field with nbrModel specified.
template<class Type >
void interpolate (const Field< Type > &field, Field< Type > &result) const
Interpolate field without nbrModel specified.
Protected Member Functions inherited from option
virtual bool alwaysApply () const
Flag to bypass the apply flag list checking.
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes
volScalarField htc_
Heat transfer coefficient [W/m2/k] times area/volume [1/m].
bool semiImplicit_
Flag to activate semi-implicit coupling.
word TName_
Name of temperature field; default = "T".
word TNbrName_
Name of neighbour temperature field; default = "T".
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
bool active_
Source active flag.
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
word nbrRegionName_
Name of the neighbour region to map.
bool master_
Master or slave region.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from option
enum selectionModeType {
smPoints, smCellSet, smCellZone, smMapRegion,
smAll
}
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from option
static const NamedEnum< selectionModeType, 5 > selectionModeTypeNames_
Word list of selection mode type names.
Detailed Description
Base class for inter region heat exchange. The derived classes must provide the heat transfer coeffisine (htc) which is used as follows in the energy equation.
Definition at line 55 of file interRegionHeatTransferModel.H.
Constructor & Destructor Documentation
interRegionHeatTransferModel()
interRegionHeatTransferModel (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from dictionary.
Definition at line 108 of file interRegionHeatTransferModel.C.
Referenced by interRegionHeatTransferModel::correct().
~interRegionHeatTransferModel()
~interRegionHeatTransferModel () virtual
Destructor.
Definition at line 157 of file interRegionHeatTransferModel.C.
References interRegionHeatTransferModel::addSup().
Member Function Documentation
setNbrModel()
void setNbrModel () protected
Set the neighbour interRegionHeatTransferModel.
Definition at line 46 of file interRegionHeatTransferModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, fvOptions, objectRegistry::lookupObject(), Foam::name(), fvMesh::name(), Foam::nl, and fvMesh::time().
correct()
void correct () protected
Correct to calculate the inter-region heat transfer coefficient.
Definition at line 87 of file interRegionHeatTransferModel.C.
References Foam::interpolate(), and interRegionHeatTransferModel::interRegionHeatTransferModel().
interpolate() [1/6]
tmp<Field<Type> > interpolate (const interRegionHeatTransferModel & nbrModel, const Field< Type > & field) const protected
Interpolate field with nbrModel specified.
Referenced by interRegionHeatTransferModel::interpolate().
interpolate() [2/6]
tmp<Field<Type> > interpolate (const Field< Type > & field) const protected
Interpolate field without nbrModel specified.
interpolate() [3/6]
void interpolate (const interRegionHeatTransferModel & nbrModel, const Field< Type > & field, Field< Type > & result) const protected
Interpolate field with nbrModel specified.
Definition at line 58 of file interRegionHeatTransferModelTemplates.C.
References interRegionHeatTransferModel::interpolate(), meshToMesh::mapSrcToTgt(), and option::meshInterp().
interpolate() [4/6]
void interpolate (const Field< Type > & field, Field< Type > & result) const protected
Interpolate field without nbrModel specified.
Definition at line 77 of file interRegionHeatTransferModelTemplates.C.
References Foam::MULES::interpolate().
TypeName()
TypeName ("interRegionHeatTransferModel")
Runtime type information.
htc()
const Foam::volScalarField & htc () const inline
Return the heat transfer coefficient.
Definition at line 30 of file interRegionHeatTransferModelI.H.
References interRegionHeatTransferModel::htc_.
nbrModel() [1/2]
const Foam::fv::interRegionHeatTransferModel & nbrModel () const inline
Return const access to the neighbour model.
Definition at line 37 of file interRegionHeatTransferModelI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
nbrModel() [2/2]
Foam::fv::interRegionHeatTransferModel & nbrModel () inline
Return access to the neighbour model.
Definition at line 51 of file interRegionHeatTransferModelI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
addSup() [1/2]
void addSup (fvMatrix< scalar > & eqn, const label fieldI) virtual
Source term to energy equation.
Reimplemented from option.
Definition at line 164 of file interRegionHeatTransferModel.C.
References correct, basicThermo::Cp(), basicThermo::Cpv(), Foam::dimEnergy, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimMass, Foam::dimTemperature, Foam::fvc::domainIntegrate(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, he, Foam::Info, Foam::interpolate(), objectRegistry::lookupObject(), fvMesh::name(), IOobject::NO_READ, IOobject::NO_WRITE, fvMatrix< Type >::psi(), Foam::fvm::Sp(), Foam::T(), fvMesh::time(), Foam::type(), dimensioned< Type >::value(), and Ostream::write().
Referenced by interRegionHeatTransferModel::~interRegionHeatTransferModel().
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldI) virtual
Source term to compressible energy equation.
Reimplemented from option.
Definition at line 267 of file interRegionHeatTransferModel.C.
calculateHtc()
virtual void calculateHtc () pure virtual
Calculate heat transfer coefficient.
Implemented in variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
writeData()
void writeData (Ostream & os) const virtual
Write data.
Reimplemented from option.
Reimplemented in variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
Definition at line 277 of file interRegionHeatTransferModel.C.
References token::END_STATEMENT, Foam::name(), Foam::nl, and Ostream::writeKeyword().
Referenced by constantHeatTransfer::writeData(), tabulatedHeatTransfer::writeData(), and variableHeatTransfer::writeData().
read()
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from option.
Reimplemented in variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
Definition at line 296 of file interRegionHeatTransferModel.C.
References option::read().
interpolate() [5/6]
Foam::tmp<Foam::Field<Type> > interpolate (const interRegionHeatTransferModel & nbrModel, const Field< Type > & field) const
Definition at line 29 of file interRegionHeatTransferModelTemplates.C.
References interRegionHeatTransferModel::interpolate(), meshToMesh::mapSrcToTgt(), and option::meshInterp().
interpolate() [6/6]
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & field) const
Definition at line 48 of file interRegionHeatTransferModelTemplates.C.
References Foam::MULES::interpolate(), and interRegionHeatTransferModel::interpolate().
Member Data Documentation
htc_
volScalarField htc_ protected
Heat transfer coefficient [W/m2/k] times area/volume [1/m].
Definition at line 82 of file interRegionHeatTransferModel.H.
Referenced by interRegionHeatTransferModel::htc().
semiImplicit_
bool semiImplicit_ protected
Flag to activate semi-implicit coupling.
Definition at line 85 of file interRegionHeatTransferModel.H.
TName_
word TName_ protected
Name of temperature field; default = "T".
Definition at line 88 of file interRegionHeatTransferModel.H.
TNbrName_
word TNbrName_ protected
Name of neighbour temperature field; default = "T".
Definition at line 91 of file interRegionHeatTransferModel.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/interRegion/interRegionHeatTransferModel/interRegionHeatTransferModel/interRegionHeatTransferModel.H
src/fvOptions/sources/interRegion/interRegionHeatTransferModel/interRegionHeatTransferModel/interRegionHeatTransferModel.C
src/fvOptions/sources/interRegion/interRegionHeatTransferModel/interRegionHeatTransferModel/interRegionHeatTransferModelI.H
src/fvOptions/sources/interRegion/interRegionHeatTransferModel/interRegionHeatTransferModel/interRegionHeatTransferModelTemplates.C