OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
rotorDiskSource Class Reference
Cell based momemtum source.
Classes
struct flapData
Public Types
enum geometryModeType { gmAuto, gmSpecified }
enum inletFlowType { ifFixed, ifSurfaceNormal, ifLocal }
Public Types inherited from option
enum selectionModeType {
smPoints, smCellSet, smCellZone, smMapRegion,
smAll
}
Enumeration for selection mode types.
Public Member Functions
TypeName ("rotorDisk")
Runtime type information.
rotorDiskSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~rotorDiskSource ()
Destructor.
scalar rhoRef () const
Return the reference density for incompressible case.
scalar omega () const
Return the rotational speed [rad/s].
const List< point > & x () const
Return the cell centre positions in local rotor frame.
const cylindricalCS & coordSys () const
Return the rotor co-ordinate system (r, theta, z)
template<class RhoFieldType >
void calculate (const RhoFieldType &rho, const vectorField &U, const scalarField &thetag, vectorField &force, const bool divideVolume=true, const bool output=true) const
Calculate forces.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Source term to momentum equation.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Source term to compressible momentum equation.
virtual void writeData (Ostream &) const
Write the source properties.
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh, const bool master=false)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const labelList & cells () const
Return const access to the cell set.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
bool & active ()
Return access to the source active flag.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void correct (volScalarField &fld)
Scalar.
virtual void correct (volVectorField &fld)
Vector.
virtual void correct (volSphericalTensorField &fld)
Spherical tensor.
virtual void correct (volSymmTensorField &fld)
Symmetric tensor.
virtual void correct (volTensorField &fld)
Tensor.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void setValue (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void setValue (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void setValue (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void setValue (fvMatrix< symmTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void setValue (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
virtual void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
virtual void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
virtual void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
virtual void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
Static Public Attributes
static const NamedEnum< geometryModeType, 2 > geometryModeTypeNames_
static const NamedEnum< inletFlowType, 3 > inletFlowTypeNames_
Static Public Attributes inherited from option
static const NamedEnum< selectionModeType, 5 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions
void checkData ()
Check data.
void setFaceArea (vector &axis, const bool correct)
Set the face areas per cell, and optionally correct the rotor axis.
void createCoordinateSystem ()
Create the co-ordinate system.
void constructGeometry ()
Construct geometry.
tmp< vectorField > inflowVelocity (const volVectorField &U) const
Return the inlet flow field.
template<class Type >
void writeField (const word &name, const List< Type > &values, const bool writeNow=false) const
Helper function to write rotor values.
Protected Member Functions inherited from option
virtual bool alwaysApply () const
Flag to bypass the apply flag list checking.
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes
scalar rhoRef_
Reference density for incompressible case.
scalar omega_
Rotational speed [rad/s].
label nBlades_
Number of blades.
inletFlowType inletFlow_
Inlet flow type.
vector inletVelocity_
Inlet velocity for specified iinflow.
scalar tipEffect_
Tip effect [0-1].
flapData flap_
Blade flap coefficients [rad/s].
List< point > x_
Cell centre positions in local rotor frame.
List< tensor > R_
Rotation tensor for flap angle.
List< tensor > invR_
Inverse rotation tensor for flap angle.
List< scalar > area_
Area [m2].
cylindricalCS coordSys_
Rotor local cylindrical co-ordinate system (r, theta, z)
autoPtr< localAxesRotation > localAxesRotation_
Rotor transformation co-ordinate system.
scalar rMax_
Maximum radius.
autoPtr< trimModel > trim_
Trim model.
bladeModel blade_
Blade data.
profileModelList profiles_
Profile data.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
bool active_
Source active flag.
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
word nbrRegionName_
Name of the neighbour region to map.
bool master_
Master or slave region.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Detailed Description
Cell based momemtum source.
Source approximates the mean effects of rotor forces on a cylindrical region within the domain
Source usage
Example usage:
rotorDiskSourceCoeffs
{
    fieldNames      (U);    // names of fields on which to apply source
    nBlades         3;      // number of blades
    tipEffect       0.96;   // normalised radius above which lift = 0
    inletFlowType   local;  // inlet flow type specification
    geometryMode    auto;   // geometry specification
    refDirection    (-1 0 0); // reference direction
                              // - used as reference for psi angle
    trimModel       fixed;  // fixed || targetForce
    flapCoeffs
    {
        beta0           0;  // coning angle [deg]
        beta1c          0;  // lateral flapping coeff (cos coeff)
        beta2s          0;  // longitudinal flapping coeff (sin coeff)
    }
    blade
    {
        ...
    }
    profiles
    {
        ...
    }
}
Where: Valid options for the geometryMode entry include:
auto : determine rototor co-ord system from cells
specified : specified co-ord system
Valid options for the inletFlowType entry include:
fixed : specified velocity
local : use local flow conditions
surfaceNormal : specified normal velocity (positive towards rotor)
Source files
rotorDiskSource.H
rotorDiskSource.C
rotorDiskSourceTemplates.C
Definition at line 113 of file rotorDiskSource.H.
Member Enumeration Documentation
geometryModeType
enum geometryModeType
Enumerator
gmAuto
gmSpecified
Definition at line 119 of file rotorDiskSource.H.
inletFlowType
enum inletFlowType
Enumerator
ifFixed
ifSurfaceNormal
ifLocal
Definition at line 126 of file rotorDiskSource.H.
Constructor & Destructor Documentation
rotorDiskSource()
rotorDiskSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 473 of file rotorDiskSource.C.
Referenced by rotorDiskSource::inflowVelocity().
~rotorDiskSource()
~rotorDiskSource () virtual
Destructor.
Definition at line 506 of file rotorDiskSource.C.
References rotorDiskSource::addSup().
Member Function Documentation
checkData()
void checkData () protected
Check data.
Definition at line 70 of file rotorDiskSource.C.
References Foam::abort(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, and Foam::readScalar().
setFaceArea()
void setFaceArea (vector & axis, const bool correct) protected
Set the face areas per cell, and optionally correct the rotor axis.
Definition at line 127 of file rotorDiskSource.C.
References polyPatch::coupled(), Foam::dimArea, Foam::endl(), forAll, Foam::identity(), Foam::Info, Foam::mag(), n, IOobject::NO_READ, IOobject::NO_WRITE, Foam::reduce(), polyPatch::start(), syncTools::swapBoundaryFaceList(), Foam::type(), Ostream::write(), and Vector< Cmpt >::zero.
createCoordinateSystem()
void createCoordinateSystem () protected
Create the co-ordinate system.
Definition at line 263 of file rotorDiskSource.C.
References C::C(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, Foam::gSum(), Foam::Info, Foam::mag(), Foam::nl, Foam::constant::mathematical::pi(), Foam::reduce(), Foam::sqrt(), and Vector< Cmpt >::zero.
constructGeometry()
void constructGeometry () protected
Construct geometry.
Definition at line 398 of file rotorDiskSource.C.
References beta(), Foam::constant::universal::c, C::C(), Foam::cos(), forAll, rotorDiskSource::inflowVelocity(), Foam::max(), psi, s(), Foam::sin(), and x.
inflowVelocity()
Foam::tmp< Foam::vectorField > inflowVelocity (const volVectorField & U) const protected
Return the inlet flow field.
Definition at line 433 of file rotorDiskSource.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, GeometricField< Type, PatchField, GeoMesh >::internalField(), rotorDiskSource::rotorDiskSource(), and Vector< Cmpt >::zero.
Referenced by rotorDiskSource::constructGeometry().
writeField()
void writeField (const word & name, const List< Type > & values, const bool writeNow = false) const protected
Helper function to write rotor values.
Definition at line 161 of file rotorDiskSourceTemplates.C.
References Foam::abort(), Foam::dimless, Foam::FatalError, FatalErrorIn, fld(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, and List< T >::size().
Referenced by rotorDiskSource::calculate().
TypeName()
TypeName ("rotorDisk")
Runtime type information.
rhoRef()
Foam::scalar rhoRef () const inline
Return the reference density for incompressible case.
Definition at line 30 of file rotorDiskSourceI.H.
References rotorDiskSource::rhoRef_.
omega()
Foam::scalar omega () const inline
Return the rotational speed [rad/s].
Positive anti-clockwise when looking along -ve lift direction
Definition at line 36 of file rotorDiskSourceI.H.
References rotorDiskSource::omega_.
x()
const Foam::List< Foam::point > & x () const inline
Return the cell centre positions in local rotor frame.
(Cylindrical r, theta, z)
Definition at line 42 of file rotorDiskSourceI.H.
References rotorDiskSource::x_.
coordSys()
const Foam::cylindricalCS & coordSys () const inline
Return the rotor co-ordinate system (r, theta, z)
Definition at line 48 of file rotorDiskSourceI.H.
References rotorDiskSource::coordSys_.
calculate()
void calculate (const RhoFieldType & rho, const vectorField & U, const scalarField & thetag, vectorField & force, const bool divideVolume = true, const bool output = true) const
Calculate forces.
Definition at line 35 of file rotorDiskSourceTemplates.C.
References alphaEff, Foam::atan2(), Foam::endl(), f(), forAll, Foam::Info, Foam::magSqr(), Foam::max(), Foam::min(), Foam::neg(), Foam::nl, pDyn(), Foam::constant::mathematical::pi(), Foam::radToDeg(), Foam::reduce(), Foam::constant::mathematical::twoPi(), Foam::type(), rotorDiskSource::writeField(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
addSup() [1/2]
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Source term to momentum equation.
Reimplemented from option.
Definition at line 513 of file rotorDiskSource.C.
References fvMatrix< Type >::dimensions(), Foam::dimVolume, fvMatrix< Type >::psi(), regIOobject::write(), and Vector< Cmpt >::zero.
Referenced by rotorDiskSource::~rotorDiskSource().
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Source term to compressible momentum equation.
Reimplemented from option.
Definition at line 553 of file rotorDiskSource.C.
References fvMatrix< Type >::dimensions(), Foam::dimVolume, fvMatrix< Type >::psi(), regIOobject::write(), and Vector< Cmpt >::zero.
writeData()
void writeData (Ostream & os) const virtual
Write the source properties.
Reimplemented from option.
Definition at line 590 of file rotorDiskSource.C.
References Foam::endl(), Foam::indent(), and Ostream::write().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from option.
Definition at line 597 of file rotorDiskSource.C.
References Foam::degToRad(), dictionary::lookup(), Foam::readScalar(), and Foam::constant::mathematical::twoPi().
Member Data Documentation
geometryModeTypeNames_
const NamedEnum< fv::rotorDiskSource::geometryModeType, 2 > geometryModeTypeNames_ static
Definition at line 124 of file rotorDiskSource.H.
inletFlowTypeNames_
const NamedEnum< fv::rotorDiskSource::inletFlowType, 3 > inletFlowTypeNames_ static
Definition at line 132 of file rotorDiskSource.H.
rhoRef_
scalar rhoRef_ protected
Reference density for incompressible case.
Definition at line 151 of file rotorDiskSource.H.
Referenced by rotorDiskSource::rhoRef().
omega_
scalar omega_ protected
Rotational speed [rad/s].
Positive anti-clockwise when looking along -ve lift direction
Definition at line 155 of file rotorDiskSource.H.
Referenced by rotorDiskSource::omega().
nBlades_
label nBlades_ protected
Number of blades.
Definition at line 158 of file rotorDiskSource.H.
inletFlow_
inletFlowType inletFlow_ protected
Inlet flow type.
Definition at line 161 of file rotorDiskSource.H.
inletVelocity_
vector inletVelocity_ protected
Inlet velocity for specified iinflow.
Definition at line 164 of file rotorDiskSource.H.
tipEffect_
scalar tipEffect_ protected
Tip effect [0-1].
Ratio of blade radius beyond which lift=0
Definition at line 168 of file rotorDiskSource.H.
flap_
flapData flap_ protected
Blade flap coefficients [rad/s].
Definition at line 171 of file rotorDiskSource.H.
x_
List<point> x_ protected
Cell centre positions in local rotor frame.
(Cylindrical r, theta, z)
Definition at line 175 of file rotorDiskSource.H.
Referenced by rotorDiskSource::x().
R_
List<tensor> R_ protected
Rotation tensor for flap angle.
Definition at line 178 of file rotorDiskSource.H.
invR_
List<tensor> invR_ protected
Inverse rotation tensor for flap angle.
Definition at line 181 of file rotorDiskSource.H.
area_
List<scalar> area_ protected
Area [m2].
Definition at line 184 of file rotorDiskSource.H.
coordSys_
cylindricalCS coordSys_ protected
Rotor local cylindrical co-ordinate system (r, theta, z)
Definition at line 187 of file rotorDiskSource.H.
Referenced by rotorDiskSource::coordSys().
localAxesRotation_
autoPtr<localAxesRotation> localAxesRotation_ protected
Rotor transformation co-ordinate system.
Definition at line 190 of file rotorDiskSource.H.
rMax_
scalar rMax_ protected
Maximum radius.
Definition at line 193 of file rotorDiskSource.H.
trim_
autoPtr<trimModel> trim_ protected
Trim model.
Definition at line 196 of file rotorDiskSource.H.
blade_
bladeModel blade_ protected
Blade data.
Definition at line 199 of file rotorDiskSource.H.
profiles_
profileModelList profiles_ protected
Profile data.
Definition at line 202 of file rotorDiskSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/rotorDiskSource.H
src/fvOptions/sources/derived/rotorDiskSource/rotorDiskSource.C
src/fvOptions/sources/derived/rotorDiskSource/rotorDiskSourceI.H
src/fvOptions/sources/derived/rotorDiskSource/rotorDiskSourceTemplates.C