OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CodedSource< Type > Class Template Reference
Public Member Functions
TypeName ("coded")
Runtime type information.
CodedSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
option & redirectFvOption () const
Dynamically compiled fvOption.
virtual void correct (GeometricField< Type, fvPatchField, volMesh > &)
Correct field.
virtual void addSup (fvMatrix< Type > &eqn, const label fieldI)
Explicit and implicit matrix contributions.
virtual void addSup (const volScalarField &rho, fvMatrix< Type > &eqn, const label fieldI)
Explicit and implicit matrix contributions.
virtual void setValue (fvMatrix< Type > &eqn, const label fieldI)
Set value.
virtual void writeData (Ostream &) const
Write the source properties.
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh, const bool master=false)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const labelList & cells () const
Return const access to the cell set.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
bool & active ()
Return access to the source active flag.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void correct (volScalarField &fld)
Scalar.
virtual void correct (volVectorField &fld)
Vector.
virtual void correct (volSphericalTensorField &fld)
Spherical tensor.
virtual void correct (volSymmTensorField &fld)
Symmetric tensor.
virtual void correct (volTensorField &fld)
Tensor.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void setValue (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void setValue (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void setValue (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void setValue (fvMatrix< symmTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void setValue (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
virtual void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
virtual void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
virtual void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
virtual void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
Public Member Functions inherited from codedBase
ClassName ("codedBase")
Runtime type information.
codedBase ()
Construct null.
virtual ~codedBase ()
Destructor.
Protected Member Functions
virtual dlLibraryTable & libs () const
get the loaded dynamic libraries
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
adapt the context for the current object
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeDict () const
Protected Member Functions inherited from option
virtual bool alwaysApply () const
Flag to bypass the apply flag list checking.
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Member Functions inherited from codedBase
void updateLibrary (const word &redirectType) const
Update library as required.
Protected Attributes
word redirectType_
string codeCorrect_
string codeAddSup_
string codeSetValue_
autoPtr< option > redirectFvOptionPtr_
Underlying functionObject.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
bool active_
Source active flag.
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
word nbrRegionName_
Name of the neighbour region to map.
bool master_
Master or slave region.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from option
enum selectionModeType {
smPoints, smCellSet, smCellZone, smMapRegion,
smAll
}
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from option
static const NamedEnum< selectionModeType, 5 > selectionModeTypeNames_
Word list of selection mode type names.
Detailed Description
template<class Type>
class Foam::fv::CodedSource< Type >
Definition at line 132 of file CodedSource.H.
Constructor & Destructor Documentation
CodedSource()
CodedSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 115 of file CodedSource.C.
Referenced by CodedSource< Type >::codeDict().
Member Function Documentation
libs()
Foam::dlLibraryTable & libs () const protected virtual
get the loaded dynamic libraries
Implements codedBase.
Definition at line 84 of file CodedSource.C.
prepare()
void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
adapt the context for the current object
Implements codedBase.
Definition at line 36 of file CodedSource.C.
References dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), dynamicCodeContext::libs(), dynamicCodeContext::options(), dynamicCode::setFilterVariable(), and dynamicCode::setMakeOptions().
description()
Foam::string description () const protected virtual
Implements codedBase.
Definition at line 91 of file CodedSource.C.
clearRedirect()
void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 98 of file CodedSource.C.
codeDict()
const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 105 of file CodedSource.C.
References CodedSource< Type >::CodedSource().
TypeName()
TypeName ("coded")
Runtime type information.
redirectFvOption()
Foam::fv::option & redirectFvOption () const
Dynamically compiled fvOption.
Definition at line 131 of file CodedSource.C.
References CodedSource< Type >::correct(), and dictionary::set().
correct()
void correct (GeometricField< Type, fvPatchField, volMesh > & fld) virtual
Correct field.
Definition at line 151 of file CodedSource.C.
References CodedSource< Type >::addSup(), Foam::endl(), and Foam::Info.
Referenced by CodedSource< Type >::redirectFvOption().
addSup() [1/2]
void addSup (fvMatrix< Type > & eqn, const label fieldI) virtual
Explicit and implicit matrix contributions.
Definition at line 168 of file CodedSource.C.
References Foam::endl(), and Foam::Info.
Referenced by CodedSource< Type >::correct().
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< Type > & eqn, const label fieldI) virtual
Explicit and implicit matrix contributions.
to compressible equation
Definition at line 186 of file CodedSource.C.
References Foam::endl(), Foam::Info, and CodedSource< Type >::setValue().
setValue()
void setValue (fvMatrix< Type > & eqn, const label fieldI) virtual
Set value.
Definition at line 205 of file CodedSource.C.
References Foam::endl(), and Foam::Info.
Referenced by CodedSource< Type >::addSup().
writeData()
void writeData (Ostream & os) const virtual
Write the source properties.
Reimplemented from option.
Definition at line 32 of file CodedSourceIO.C.
References Foam::endl(), Foam::indent(), and Ostream::write().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from option.
Definition at line 40 of file CodedSourceIO.C.
References Foam::constant::electromagnetic::e, Foam::stringOps::inplaceExpand(), entry::startLineNumber(), entry::stream(), and Foam::stringOps::trim().
Member Data Documentation
redirectType_
word redirectType_ protected
Definition at line 142 of file CodedSource.H.
codeCorrect_
string codeCorrect_ protected
Definition at line 144 of file CodedSource.H.
codeAddSup_
string codeAddSup_ protected
Definition at line 145 of file CodedSource.H.
codeSetValue_
string codeSetValue_ protected
Definition at line 146 of file CodedSource.H.
redirectFvOptionPtr_
autoPtr<option> redirectFvOptionPtr_ mutable protected
Underlying functionObject.
Definition at line 149 of file CodedSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/general/codedSource/CodedSource.H
src/fvOptions/sources/general/codedSource/CodedSource.C
src/fvOptions/sources/general/codedSource/CodedSourceIO.C