OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DsmcParcel< ParcelType > Class Template Reference
DSMC parcel class.
Classes
class constantProperties
Class to hold DSMC particle constant properties.
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass kinematic tracking data to the trackToFace function.
Public Member Functions
TypeName ("DsmcParcel")
Runtime type information.
DsmcParcel (const polyMesh &mesh, const vector &position, const vector &U, const scalar Ei, const label cellI, const label tetFaceI, const label tetPtI, const label typeId)
Construct from components.
DsmcParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
virtual autoPtr< particle > clone () const
Construct and return a clone.
label typeId () const
Return type id.
const vector & U () const
Return const access to velocity.
scalar Ei () const
Return const access to internal energy.
vector & U ()
Return access to velocity.
scalar & Ei ()
Return access to internal energy.
template<class TrackData >
bool move (TrackData &td, const scalar trackTime)
Move the parcel.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a polyPatch.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
Static Public Member Functions
static void readFields (Cloud< DsmcParcel< ParcelType > > &c)
static void writeFields (const Cloud< DsmcParcel< ParcelType > > &c)
Protected Attributes
vector U_
Velocity of Parcel [m/s].
scalar Ei_
Internal energy of the Parcel, covering all non-translational.
label typeId_
Parcel type id.
Friends
class Cloud< ParcelType >
Ostream & operator (Ostream &, const DsmcParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::DsmcParcel< ParcelType >
DSMC parcel class.
Source files
DsmcParcel.H
DsmcParcelI.H
DsmcParcel.C
DsmcParcelIO.C
Definition at line 52 of file DsmcParcel.H.
Constructor & Destructor Documentation
DsmcParcel() [1/2]
DsmcParcel (const polyMesh & mesh, const vector & position, const vector & U, const scalar Ei, const label cellI, const label tetFaceI, const label tetPtI, const label typeId) inline
Construct from components.
Definition at line 56 of file DsmcParcelI.H.
Referenced by DsmcParcel< ParcelType >::constantProperties::constantProperties().
DsmcParcel() [2/2]
DsmcParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 35 of file DsmcParcelIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), and readScalar.
Member Function Documentation
TypeName()
TypeName ("DsmcParcel< ParcelType >")
Runtime type information.
clone()
virtual autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Definition at line 193 of file DsmcParcel.H.
typeId()
Foam::label typeId () const inline
Return type id.
Definition at line 119 of file DsmcParcelI.H.
References DsmcParcel< ParcelType >::typeId_.
Referenced by DsmcParcel< ParcelType >::iNew::operator()(), and DsmcParcel< ParcelType >::writeFields().
U() [1/2]
const Foam::vector & U () const inline
Return const access to velocity.
Definition at line 126 of file DsmcParcelI.H.
References DsmcParcel< ParcelType >::U_.
Referenced by DsmcParcel< ParcelType >::iNew::operator()(), and DsmcParcel< ParcelType >::writeFields().
Ei() [1/2]
Foam::scalar Ei () const inline
Return const access to internal energy.
Definition at line 133 of file DsmcParcelI.H.
References DsmcParcel< ParcelType >::Ei_.
Referenced by DsmcParcel< ParcelType >::iNew::operator()(), and DsmcParcel< ParcelType >::writeFields().
U() [2/2]
Foam::vector & U () inline
Return access to velocity.
Definition at line 140 of file DsmcParcelI.H.
References DsmcParcel< ParcelType >::U_.
Ei() [2/2]
Foam::scalar & Ei () inline
Return access to internal energy.
Definition at line 147 of file DsmcParcelI.H.
References DsmcParcel< ParcelType >::Ei_.
move()
bool move (TrackData & td, const scalar trackTime)
Move the parcel.
Definition at line 33 of file DsmcParcel.C.
References polyMesh::boundaryMesh(), Foam::meshTools::constrainDirection(), Foam::meshTools::constrainToMeshCentre(), DsmcParcel< ParcelType >::hitPatch(), mesh, Foam::min(), p, and polyMesh::solutionD().
Referenced by DsmcParcel< ParcelType >::iNew::operator()().
hitPatch() [1/2]
bool hitPatch (const polyPatch & , TrackData & td, const label patchI, const scalar trackFraction, const tetIndices & tetIs)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 89 of file DsmcParcel.C.
References DsmcParcel< ParcelType >::hitProcessorPatch().
Referenced by DsmcParcel< ParcelType >::move(), and DsmcParcel< ParcelType >::iNew::operator()().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & , TrackData & td)
Overridable function to handle the particle hitting a.
processorPatch
Definition at line 104 of file DsmcParcel.C.
References DsmcParcel< ParcelType >::hitWallPatch().
Referenced by DsmcParcel< ParcelType >::hitPatch(), and DsmcParcel< ParcelType >::iNew::operator()().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & wpp, TrackData & td, const tetIndices & tetIs)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 116 of file DsmcParcel.C.
References polyPatch::faceAreas(), patchIdentifier::index(), Foam::mag(), DsmcParcel< ParcelType >::constantProperties::mass(), Foam::max(), nw, and polyPatch::whichFace().
Referenced by DsmcParcel< ParcelType >::hitProcessorPatch(), and DsmcParcel< ParcelType >::iNew::operator()().
hitPatch() [2/2]
void hitPatch (const polyPatch & , TrackData & td)
Overridable function to handle the particle hitting a polyPatch.
Definition at line 208 of file DsmcParcel.C.
transformProperties() [1/2]
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Definition at line 215 of file DsmcParcel.C.
References Foam::transform().
Referenced by DsmcParcel< ParcelType >::iNew::operator()().
transformProperties() [2/2]
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Definition at line 224 of file DsmcParcel.C.
readFields()
void readFields (Cloud< DsmcParcel< ParcelType > > & c) static
Definition at line 76 of file DsmcParcelIO.C.
References Foam::constant::universal::c, DsmcParcel< ParcelType >::Ei_, forAllIter, p, Foam::readFields(), DsmcParcel< ParcelType >::typeId_, U, DsmcParcel< ParcelType >::U_, and DsmcParcel< ParcelType >::writeFields().
Referenced by DsmcParcel< ParcelType >::iNew::operator()().
writeFields()
void writeFields (const Cloud< DsmcParcel< ParcelType > > & c) static
Definition at line 109 of file DsmcParcelIO.C.
References Foam::constant::universal::c, DsmcParcel< ParcelType >::Ei(), forAllConstIter(), p, DsmcParcel< ParcelType >::typeId(), U, and DsmcParcel< ParcelType >::U().
Referenced by DsmcParcel< ParcelType >::iNew::operator()(), and DsmcParcel< ParcelType >::readFields().
Friends And Related Function Documentation
Cloud< ParcelType >
friend class Cloud< ParcelType > friend
Definition at line 166 of file DsmcParcel.H.
operator
Ostream& operator (Ostream & , const DsmcParcel< ParcelType > &) friend
Member Data Documentation
U_
vector U_ protected
Velocity of Parcel [m/s].
Definition at line 151 of file DsmcParcel.H.
Referenced by DsmcParcel< ParcelType >::readFields(), and DsmcParcel< ParcelType >::U().
Ei_
scalar Ei_ protected
Internal energy of the Parcel, covering all non-translational.
degrees of freedom [J]
Definition at line 155 of file DsmcParcel.H.
Referenced by DsmcParcel< ParcelType >::Ei(), and DsmcParcel< ParcelType >::readFields().
typeId_
label typeId_ protected
Parcel type id.
Definition at line 158 of file DsmcParcel.H.
Referenced by DsmcParcel< ParcelType >::readFields(), and DsmcParcel< ParcelType >::typeId().
The documentation for this class was generated from the following files:
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcel.H
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcel.C
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcelI.H
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcelIO.C