OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
uniform Class Reference
Public Member Functions
TypeName ("uniform")
Runtime type information.
uniform (const dictionary &dict, cachedRandom &rndGen)
Construct from components.
uniform (const uniform &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const
Construct and return a clone.
virtual ~uniform ()
Destructor.
virtual scalar sample () const
Sample the distributionModel.
virtual scalar minValue () const
Return the minimum value.
virtual scalar maxValue () const
Return the maximum value.
virtual scalar meanValue () const
Return the mean value.
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual ~distributionModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions inherited from distributionModel
virtual void check () const
Check that the distribution model is valid.
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 50 of file uniform.H.
Constructor & Destructor Documentation
uniform() [1/2]
uniform (const dictionary & dict, cachedRandom & rndGen)
Construct from components.
Definition at line 43 of file uniform.C.
Referenced by uniform::clone().
uniform() [2/2]
uniform (const uniform & p)
Construct copy.
Definition at line 56 of file uniform.C.
~uniform()
~uniform () virtual
Destructor.
Definition at line 66 of file uniform.C.
Referenced by uniform::clone().
Member Function Documentation
TypeName()
TypeName ("uniform")
Runtime type information.
clone()
virtual autoPtr<distributionModel> clone () const inline virtual
Construct and return a clone.
Reimplemented from distributionModel.
Definition at line 78 of file uniform.H.
References uniform::maxValue(), uniform::meanValue(), uniform::minValue(), uniform::sample(), uniform::uniform(), and uniform::~uniform().
sample()
Foam::scalar sample () const virtual
Sample the distributionModel.
Reimplemented from distributionModel.
Definition at line 72 of file uniform.C.
References cachedRandom::position(), and distributionModel::rndGen_.
Referenced by uniform::clone().
minValue()
Foam::scalar minValue () const virtual
Return the minimum value.
Reimplemented from distributionModel.
Definition at line 78 of file uniform.C.
Referenced by uniform::clone().
maxValue()
Foam::scalar maxValue () const virtual
Return the maximum value.
Reimplemented from distributionModel.
Definition at line 84 of file uniform.C.
Referenced by uniform::clone().
meanValue()
Foam::scalar meanValue () const virtual
Return the mean value.
Reimplemented from distributionModel.
Definition at line 90 of file uniform.C.
Referenced by uniform::clone().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/uniform/uniform.H
src/lagrangian/distributionModels/uniform/uniform.C