OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
distributionModel Class Reference
Public Member Functions
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const
Construct and return a clone.
virtual ~distributionModel ()
Destructor.
virtual scalar sample () const
Sample the distributionModel.
virtual scalar minValue () const
Return the minimum value.
virtual scalar maxValue () const
Return the maximum value.
virtual scalar meanValue () const
Return the maximum value.
Static Public Member Functions
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions
virtual void check () const
Check that the distribution model is valid.
Protected Attributes
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 69 of file distributionModel.H.
Constructor & Destructor Documentation
distributionModel() [1/2]
distributionModel (const word & name, const dictionary & dict, cachedRandom & rndGen)
Construct from dictionary.
Definition at line 65 of file distributionModel.C.
Referenced by distributionModel::check(), and distributionModel::clone().
distributionModel() [2/2]
distributionModel (const distributionModel & p)
Construct copy.
Definition at line 77 of file distributionModel.C.
~distributionModel()
~distributionModel () virtual
Destructor.
Definition at line 88 of file distributionModel.C.
Referenced by distributionModel::clone().
Member Function Documentation
check()
void check () const protected virtual
Check that the distribution model is valid.
Definition at line 41 of file distributionModel.C.
References Foam::abort(), distributionModel::distributionModel(), Foam::FatalError, FatalErrorIn, maxValue, minValue, Foam::nl, and Foam::type().
TypeName()
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , distributionModel , dictionary , (const dictionary &dict, cachedRandom &rndGen) , (dict, rndGen))
Declare runtime constructor selection table.
clone()
virtual autoPtr<distributionModel> clone () const inline virtual
Construct and return a clone.
Reimplemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
Definition at line 123 of file distributionModel.H.
References distributionModel::distributionModel(), distributionModel::maxValue(), distributionModel::meanValue(), distributionModel::minValue(), distributionModel::New(), distributionModel::sample(), and distributionModel::~distributionModel().
New()
Foam::autoPtr< Foam::distributionModels::distributionModel > New (const dictionary & dict, cachedRandom & rndGen) static
Selector.
Definition at line 32 of file distributionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), Foam::nl, and rndGen().
Referenced by distributionModel::clone().
sample()
Foam::scalar sample () const virtual
Sample the distributionModel.
Reimplemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
Definition at line 94 of file distributionModel.C.
References notImplemented.
Referenced by distributionModel::clone().
minValue()
Foam::scalar minValue () const virtual
Return the minimum value.
Reimplemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
Definition at line 105 of file distributionModel.C.
References notImplemented.
Referenced by distributionModel::clone().
maxValue()
Foam::scalar maxValue () const virtual
Return the maximum value.
Reimplemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
Definition at line 116 of file distributionModel.C.
References notImplemented.
Referenced by distributionModel::clone().
meanValue()
Foam::scalar meanValue () const virtual
Return the maximum value.
Reimplemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
Definition at line 127 of file distributionModel.C.
References notImplemented.
Referenced by distributionModel::clone().
Member Data Documentation
distributionModelDict_
const dictionary distributionModelDict_ protected
Coefficients dictionary.
Definition at line 77 of file distributionModel.H.
rndGen_
cachedRandom& rndGen_ protected
Reference to the random number generator.
Definition at line 80 of file distributionModel.H.
Referenced by uniform::sample(), exponential::sample(), general::sample(), RosinRammler::sample(), multiNormal::sample(), and normal::sample().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/distributionModel/distributionModel.H
src/lagrangian/distributionModels/distributionModel/distributionModel.C
src/lagrangian/distributionModels/distributionModel/distributionModelNew.C