OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DsmcParcel< ParcelType >::constantProperties Class Reference
Class to hold DSMC particle constant properties.
Public Member Functions
constantProperties ()
Null constructor, allows List of constantProperties to be.
constantProperties (const dictionary &dict)
Constructor from dictionary.
scalar mass () const
Return const access to the particle density.
scalar d () const
Return const access to the minimum particle mass.
scalar sigmaT () const
Return the reference total collision cross section.
scalar internalDegreesOfFreedom () const
Return the internalDegreesOfFreedom.
scalar omega () const
Return the viscosity index.
Detailed Description
template<class ParcelType>
class Foam::DsmcParcel< ParcelType >::constantProperties
Class to hold DSMC particle constant properties.
Definition at line 75 of file DsmcParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/2]
constantProperties () inline
Null constructor, allows List of constantProperties to be.
created before the contents is initialised
Definition at line 31 of file DsmcParcelI.H.
constantProperties() [2/2]
constantProperties (const dictionary & dict) inline
Constructor from dictionary.
Definition at line 40 of file DsmcParcelI.H.
References DsmcParcel< ParcelType >::DsmcParcel().
Member Function Documentation
mass()
Foam::scalar mass () const inline
Return const access to the particle density.
Definition at line 78 of file DsmcParcelI.H.
Referenced by DsmcParcel< ParcelType >::hitWallPatch().
d()
Foam::scalar d () const inline
Return const access to the minimum particle mass.
Definition at line 85 of file DsmcParcelI.H.
sigmaT()
Foam::scalar sigmaT () const inline
Return the reference total collision cross section.
Definition at line 93 of file DsmcParcelI.H.
References Foam::constant::mathematical::pi().
internalDegreesOfFreedom()
Foam::scalar internalDegreesOfFreedom () const inline
Return the internalDegreesOfFreedom.
Definition at line 101 of file DsmcParcelI.H.
omega()
Foam::scalar omega () const inline
Return the viscosity index.
Definition at line 110 of file DsmcParcelI.H.
The documentation for this class was generated from the following files:
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcel.H
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcelI.H