OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
RosinRammler Class Reference
Public Member Functions
TypeName ("RosinRammler")
Runtime type information.
RosinRammler (const dictionary &dict, cachedRandom &rndGen)
Construct from components.
RosinRammler (const RosinRammler &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const
Construct and return a clone.
virtual ~RosinRammler ()
Destructor.
virtual scalar sample () const
Sample the distributionModel.
virtual scalar minValue () const
Return the minimum value.
virtual scalar maxValue () const
Return the maximum value.
virtual scalar meanValue () const
Return the mean value.
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual ~distributionModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions inherited from distributionModel
virtual void check () const
Check that the distribution model is valid.
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 57 of file RosinRammler.H.
Constructor & Destructor Documentation
RosinRammler() [1/2]
RosinRammler (const dictionary & dict, cachedRandom & rndGen)
Construct from components.
Definition at line 43 of file RosinRammler.C.
Referenced by RosinRammler::clone().
RosinRammler() [2/2]
RosinRammler (const RosinRammler & p)
Construct copy.
Definition at line 58 of file RosinRammler.C.
~RosinRammler()
~RosinRammler () virtual
Destructor.
Definition at line 70 of file RosinRammler.C.
Referenced by RosinRammler::clone().
Member Function Documentation
TypeName()
TypeName ("RosinRammler")
Runtime type information.
clone()
virtual autoPtr<distributionModel> clone () const inline virtual
Construct and return a clone.
Reimplemented from distributionModel.
Definition at line 90 of file RosinRammler.H.
References RosinRammler::maxValue(), RosinRammler::meanValue(), RosinRammler::minValue(), RosinRammler::RosinRammler(), RosinRammler::sample(), and RosinRammler::~RosinRammler().
sample()
Foam::scalar sample () const virtual
Sample the distributionModel.
Reimplemented from distributionModel.
Definition at line 76 of file RosinRammler.C.
References Foam::exp(), Foam::log(), Foam::pow(), distributionModel::rndGen_, cachedRandom::sample01(), x, and y.
Referenced by RosinRammler::clone().
minValue()
Foam::scalar minValue () const virtual
Return the minimum value.
Reimplemented from distributionModel.
Definition at line 85 of file RosinRammler.C.
Referenced by RosinRammler::clone().
maxValue()
Foam::scalar maxValue () const virtual
Return the maximum value.
Reimplemented from distributionModel.
Definition at line 91 of file RosinRammler.C.
Referenced by RosinRammler::clone().
meanValue()
Foam::scalar meanValue () const virtual
Return the mean value.
Reimplemented from distributionModel.
Definition at line 97 of file RosinRammler.C.
Referenced by RosinRammler::clone().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/RosinRammler/RosinRammler.H
src/lagrangian/distributionModels/RosinRammler/RosinRammler.C