OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fixedValue Class Reference
Public Member Functions
TypeName ("fixedValue")
Runtime type information.
fixedValue (const dictionary &dict, cachedRandom &rndGen)
Construct from components.
fixedValue (const fixedValue &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const
Construct and return a clone.
virtual ~fixedValue ()
Destructor.
virtual scalar sample () const
Sample the distributionModel.
virtual scalar minValue () const
Return the minimum value.
virtual scalar maxValue () const
Return the maximum value.
virtual scalar meanValue () const
Return the mean value.
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual ~distributionModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions inherited from distributionModel
virtual void check () const
Check that the distribution model is valid.
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 49 of file fixedValue.H.
Constructor & Destructor Documentation
fixedValue() [1/2]
fixedValue (const dictionary & dict, cachedRandom & rndGen)
Construct from components.
Definition at line 43 of file fixedValue.C.
Referenced by fixedValue::clone().
fixedValue() [2/2]
fixedValue (const fixedValue & p)
Construct copy.
Definition at line 53 of file fixedValue.C.
~fixedValue()
~fixedValue () virtual
Destructor.
Definition at line 62 of file fixedValue.C.
References maxValue, and minValue.
Referenced by fixedValue::clone().
Member Function Documentation
TypeName()
TypeName ("fixedValue")
Runtime type information.
clone()
virtual autoPtr<distributionModel> clone () const inline virtual
Construct and return a clone.
Reimplemented from distributionModel.
Definition at line 74 of file fixedValue.H.
References fixedValue::fixedValue(), fixedValue::maxValue(), fixedValue::meanValue(), fixedValue::minValue(), fixedValue::sample(), and fixedValue::~fixedValue().
sample()
virtual scalar sample () const virtual
Sample the distributionModel.
Reimplemented from distributionModel.
Referenced by fixedValue::clone().
minValue()
virtual scalar minValue () const virtual
Return the minimum value.
Reimplemented from distributionModel.
Referenced by fixedValue::clone().
maxValue()
virtual scalar maxValue () const virtual
Return the maximum value.
Reimplemented from distributionModel.
Referenced by fixedValue::clone().
meanValue()
virtual scalar meanValue () const virtual
Return the mean value.
Reimplemented from distributionModel.
Referenced by fixedValue::clone().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/fixedValue/fixedValue.H
src/lagrangian/distributionModels/fixedValue/fixedValue.C