OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
normal Class Reference
Public Member Functions
TypeName ("normal")
Runtime type information.
normal (const dictionary &dict, cachedRandom &rndGen)
Construct from components.
normal (const normal &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const
Construct and return a clone.
virtual ~normal ()
Destructor.
virtual scalar sample () const
Sample the distributionModel.
virtual scalar minValue () const
Return the minimum value.
virtual scalar maxValue () const
Return the maximum value.
virtual scalar meanValue () const
Return the mean value.
virtual scalar erfInv (const scalar y) const
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual ~distributionModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions inherited from distributionModel
virtual void check () const
Check that the distribution model is valid.
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 56 of file normal.H.
Constructor & Destructor Documentation
normal() [1/2]
normal (const dictionary & dict, cachedRandom & rndGen)
Construct from components.
Definition at line 44 of file normal.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by normal::clone().
normal() [2/2]
normal (const normal & p)
Construct copy.
Definition at line 74 of file normal.C.
~normal()
~normal () virtual
Destructor.
Definition at line 87 of file normal.C.
Referenced by normal::clone().
Member Function Documentation
TypeName()
TypeName ("normal")
Runtime type information.
clone()
virtual autoPtr<distributionModel> clone () const inline virtual
Construct and return a clone.
Reimplemented from distributionModel.
Definition at line 93 of file normal.H.
References normal::erfInv(), normal::maxValue(), normal::meanValue(), normal::minValue(), normal::normal(), normal::sample(), y, and normal::~normal().
sample()
Foam::scalar sample () const virtual
Sample the distributionModel.
Reimplemented from distributionModel.
Definition at line 93 of file normal.C.
References Foam::constant::physicoChemical::b, Foam::erf(), normal::erfInv(), Foam::max(), Foam::min(), distributionModel::rndGen_, cachedRandom::sample01(), x, and y.
Referenced by normal::clone().
minValue()
Foam::scalar minValue () const virtual
Return the minimum value.
Reimplemented from distributionModel.
Definition at line 111 of file normal.C.
Referenced by normal::clone().
maxValue()
Foam::scalar maxValue () const virtual
Return the maximum value.
Reimplemented from distributionModel.
Definition at line 117 of file normal.C.
Referenced by normal::clone().
meanValue()
Foam::scalar meanValue () const virtual
Return the mean value.
Reimplemented from distributionModel.
Definition at line 123 of file normal.C.
Referenced by normal::clone().
erfInv()
Foam::scalar erfInv (const scalar y) const virtual
Definition at line 129 of file normal.C.
References Foam::constant::universal::h, k, Foam::log(), Foam::constant::mathematical::pi(), Foam::sqrt(), and x.
Referenced by normal::clone(), and normal::sample().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/normal/normal.H
src/lagrangian/distributionModels/normal/normal.C