OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
thermoCloud Class Reference abstract
Virtual abstract base class for templated ThermoCloud.
Public Member Functions
TypeName ("thermoCloud")
Runtime type information.
thermoCloud ()
Null constructor.
virtual ~thermoCloud ()
Destructor.
virtual tmp< volScalarField > Ep () const =0
Return tmp equivalent particulate emission.
virtual tmp< volScalarField > ap () const =0
Return tmp equivalent particulate absorption.
virtual tmp< volScalarField > sigmap () const =0
Return tmp equivalent particulate scattering factor.
Detailed Description
Virtual abstract base class for templated ThermoCloud.
Source files
thermoCloud.H
thermoCloud.C
Definition at line 48 of file thermoCloud.H.
Constructor & Destructor Documentation
thermoCloud()
thermoCloud ()
Null constructor.
Definition at line 38 of file thermoCloud.C.
~thermoCloud()
~thermoCloud () virtual
Destructor.
Definition at line 44 of file thermoCloud.C.
Member Function Documentation
TypeName()
TypeName ("thermoCloud")
Runtime type information.
Ep()
virtual tmp<volScalarField> Ep () const pure virtual
Return tmp equivalent particulate emission.
Implemented in ThermoCloud< CloudType >, and ThermoCloud< Foam::DsmcCloud >.
Referenced by cloudAbsorptionEmission::EDisp().
ap()
virtual tmp<volScalarField> ap () const pure virtual
Return tmp equivalent particulate absorption.
Implemented in ThermoCloud< CloudType >, and ThermoCloud< Foam::DsmcCloud >.
Referenced by cloudAbsorptionEmission::aDisp().
sigmap()
virtual tmp<volScalarField> sigmap () const pure virtual
Return tmp equivalent particulate scattering factor.
Implemented in ThermoCloud< CloudType >, and ThermoCloud< Foam::DsmcCloud >.
Referenced by cloudScatter::sigmaEff().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/baseClasses/thermoCloud/thermoCloud.H
src/lagrangian/intermediate/clouds/baseClasses/thermoCloud/thermoCloud.C