OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DsmcParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< DsmcParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::DsmcParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 201 of file DsmcParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 207 of file DsmcParcel.H.
Member Function Documentation
operator()()
autoPtr<DsmcParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 212 of file DsmcParcel.H.
References Foam::constant::universal::c, DsmcParcel< ParcelType >::Ei(), DsmcParcel< ParcelType >::hitPatch(), DsmcParcel< ParcelType >::hitProcessorPatch(), DsmcParcel< ParcelType >::hitWallPatch(), DsmcParcel< ParcelType >::move(), DsmcParcel< ParcelType >::readFields(), Foam::T(), DsmcParcel< ParcelType >::transformProperties(), DsmcParcel< ParcelType >::typeId(), DsmcParcel< ParcelType >::U(), and DsmcParcel< ParcelType >::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/dsmc/parcels/Templates/DsmcParcel/DsmcParcel.H