OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LarsenBorgnakkeVariableHardSphere< CloudType > Class Template Reference
Variable Hard Sphere BinaryCollision Model with Larsen Borgnakke internal energy redistribution. Based on the INELRS subroutine in Bird's DSMC0R.FOR.
Public Member Functions
TypeName ("LarsenBorgnakkeVariableHardSphere")
Runtime type information.
LarsenBorgnakkeVariableHardSphere (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~LarsenBorgnakkeVariableHardSphere ()
Destructor.
virtual bool active () const
Flag to indicate whether model activates collision model.
virtual scalar sigmaTcR (const typename CloudType::parcelType &pP, const typename CloudType::parcelType &pQ) const
Return the collision cross section * relative velocity product.
virtual void collide (typename CloudType::parcelType &pP, typename CloudType::parcelType &pQ)
Apply collision.
Public Member Functions inherited from BinaryCollisionModel< CloudType >
TypeName ("BinaryCollisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, BinaryCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
BinaryCollisionModel (CloudType &owner)
Construct null from owner.
BinaryCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~BinaryCollisionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from BinaryCollisionModel< CloudType >
static autoPtr< BinaryCollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::LarsenBorgnakkeVariableHardSphere< CloudType >
Variable Hard Sphere BinaryCollision Model with Larsen Borgnakke internal energy redistribution. Based on the INELRS subroutine in Bird's DSMC0R.FOR.
Definition at line 46 of file LarsenBorgnakkeVariableHardSphere.H.
Constructor & Destructor Documentation
LarsenBorgnakkeVariableHardSphere()
LarsenBorgnakkeVariableHardSphere (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 97 of file LarsenBorgnakkeVariableHardSphere.C.
References LarsenBorgnakkeVariableHardSphere< CloudType >::~LarsenBorgnakkeVariableHardSphere().
~LarsenBorgnakkeVariableHardSphere()
~LarsenBorgnakkeVariableHardSphere () virtual
Destructor.
Definition at line 115 of file LarsenBorgnakkeVariableHardSphere.C.
Referenced by LarsenBorgnakkeVariableHardSphere< CloudType >::LarsenBorgnakkeVariableHardSphere().
Member Function Documentation
TypeName()
TypeName ("LarsenBorgnakkeVariableHardSphere< CloudType >")
Runtime type information.
active()
bool active () const virtual
Flag to indicate whether model activates collision model.
Implements BinaryCollisionModel< CloudType >.
Definition at line 122 of file LarsenBorgnakkeVariableHardSphere.C.
References LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR().
sigmaTcR()
Foam::scalar sigmaTcR (const typename CloudType::parcelType & pP, const typename CloudType::parcelType & pQ) const virtual
Return the collision cross section * relative velocity product.
Implements BinaryCollisionModel< CloudType >.
Definition at line 130 of file LarsenBorgnakkeVariableHardSphere.C.
References LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), DsmcCloud< ParcelType >::constProps(), Foam::exp(), Foam::constant::physicoChemical::k, Foam::lgamma(), Foam::mag(), Foam::constant::mathematical::pi(), and Foam::pow().
Referenced by LarsenBorgnakkeVariableHardSphere< CloudType >::active().
collide()
void collide (typename CloudType::parcelType & pP, typename CloudType::parcelType & pQ) virtual
Apply collision.
Implements BinaryCollisionModel< CloudType >.
Definition at line 179 of file LarsenBorgnakkeVariableHardSphere.C.
References DsmcCloud< ParcelType >::constProps(), Foam::cos(), Foam::magSqr(), phi, Foam::pow(), rndGen(), DsmcCloud< ParcelType >::rndGen(), Foam::sin(), Foam::sqrt(), and Foam::constant::mathematical::twoPi().
Referenced by LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR().
The documentation for this class was generated from the following files:
src/lagrangian/dsmc/submodels/BinaryCollisionModel/LarsenBorgnakkeVariableHardSphere/LarsenBorgnakkeVariableHardSphere.H
src/lagrangian/dsmc/submodels/BinaryCollisionModel/LarsenBorgnakkeVariableHardSphere/LarsenBorgnakkeVariableHardSphere.C