OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IntegrationScheme< Type > Class Template Reference
Top level model for Integration schemes.
Classes
class integrationResult
Helper class to supply results of integration.
Public Member Functions
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IntegrationScheme, dictionary,(const word &phiName, const dictionary &dict),(phiName, dict))
Declare runtime constructor selection table.
IntegrationScheme (const word &phiName, const dictionary &dict)
Construct from components.
IntegrationScheme (const IntegrationScheme &is)
Copy constructor.
virtual autoPtr< IntegrationScheme< Type > > clone () const
Construct and return clone.
virtual ~IntegrationScheme ()
Destructor.
virtual integrationResult integrate (const Type &phi, const scalar dt, const Type &alphaBeta, const scalar beta) const
Perform the Integration.
Static Public Member Functions
static autoPtr< IntegrationScheme > New (const word &phiName, const dictionary &dict)
Return a reference to the selected radiation model.
Detailed Description
template<class Type>
class Foam::IntegrationScheme< Type >
Top level model for Integration schemes.
Source files
IntegrationScheme.H
IntegrationScheme.C
Definition at line 51 of file IntegrationScheme.H.
Constructor & Destructor Documentation
IntegrationScheme() [1/2]
IntegrationScheme (const word & phiName, const dictionary & dict)
Construct from components.
Definition at line 32 of file IntegrationScheme.C.
Referenced by IntegrationScheme< Type >::integrationResult::average().
IntegrationScheme() [2/2]
IntegrationScheme (const IntegrationScheme< Type > & is)
Copy constructor.
Definition at line 43 of file IntegrationScheme.C.
~IntegrationScheme()
~IntegrationScheme () virtual
Destructor.
Definition at line 53 of file IntegrationScheme.C.
References IntegrationScheme< Type >::integrate().
Referenced by IntegrationScheme< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("integrationScheme")
Runtime type information.
Referenced by IntegrationScheme< Type >::integrationResult::average().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , IntegrationScheme< Type > , dictionary , (const word &phiName, const dictionary &dict) , (phiName, dict))
Declare runtime constructor selection table.
Referenced by IntegrationScheme< Type >::integrationResult::average().
clone()
virtual autoPtr<IntegrationScheme<Type> > clone () const inline virtual
Construct and return clone.
Reimplemented in Analytical< Type >, and Euler< Type >.
Definition at line 156 of file IntegrationScheme.H.
References beta(), IntegrationScheme< Type >::integrate(), IntegrationScheme< Type >::New(), phi, and IntegrationScheme< Type >::~IntegrationScheme().
New()
Foam::autoPtr< Foam::IntegrationScheme< Type > > New (const word & phiName, const dictionary & dict) static
Return a reference to the selected radiation model.
Definition at line 34 of file IntegrationSchemeNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by IntegrationScheme< Type >::clone().
integrate()
Foam::IntegrationScheme< Type >::integrationResult integrate (const Type & phi, const scalar dt, const Type & alphaBeta, const scalar beta) const virtual
Perform the Integration.
Reimplemented in Analytical< Type >, and Euler< Type >.
Definition at line 62 of file IntegrationScheme.C.
References IntegrationScheme< Type >::integrationResult::average(), notImplemented, and IntegrationScheme< Type >::integrationResult::value().
Referenced by IntegrationScheme< Type >::clone(), and IntegrationScheme< Type >::~IntegrationScheme().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationScheme.H
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationScheme.C
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationSchemeNew.C