OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MPPICParcel< ParcelType > Class Template Reference
Wrapper around kinematic parcel types to add MPPIC modelling.
Classes
class iNew
Factory class to read-construct particles used for.
class TrackingData
Public Member Functions
TypeName ("MPPICParcel")
Runtime type information.
AddToPropertyList (ParcelType, "(UCorrectx UCorrecty UCorrectz)")
String representation of properties.
MPPICParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from owner, position, and cloud owner.
MPPICParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &UCorrect0, const typename ParcelType::constantProperties &constProps)
Construct from components.
MPPICParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
MPPICParcel (const MPPICParcel &p)
Construct as a copy.
MPPICParcel (const MPPICParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
const vector & UCorrect () const
Return const access to correction velocity.
vector & UCorrect ()
Return access to correction velocity.
template<class TrackData >
bool move (TrackData &td, const scalar trackTime)
Move the parcel.
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
Read.
template<class CloudType >
static void writeFields (const CloudType &c)
Write.
Protected Attributes
vector UCorrect_
Velocity correction due to collisions [m/s].
Friends
Ostream & operator (Ostream &, const MPPICParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::MPPICParcel< ParcelType >
Wrapper around kinematic parcel types to add MPPIC modelling.
Source files
MPPICParcel.H
MPPICParcelI.H
MPPICParcelTrackingDataI.H
MPPICParcel.C
MPPICParcelIO.C
Definition at line 52 of file MPPICParcel.H.
Constructor & Destructor Documentation
MPPICParcel() [1/5]
MPPICParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 30 of file MPPICParcelI.H.
Referenced by MPPICParcel< ParcelType >::clone().
MPPICParcel() [2/5]
MPPICParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & UCorrect0, const typename ParcelType::constantProperties & constProps) inline
Construct from components.
Definition at line 45 of file MPPICParcelI.H.
MPPICParcel() [3/5]
MPPICParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 41 of file MPPICParcelIO.C.
References IOstream::check(), IOstream::format(), and Istream::read().
MPPICParcel() [4/5]
MPPICParcel (const MPPICParcel< ParcelType > & p)
Construct as a copy.
MPPICParcel() [5/5]
MPPICParcel (const MPPICParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
TypeName()
TypeName ("MPPICParcel< ParcelType >")
Runtime type information.
AddToPropertyList()
AddToPropertyList (ParcelType , "(UCorrectx UCorrecty UCorrectz)")
String representation of properties.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 220 of file MPPICParcel.H.
References MPPICParcel< ParcelType >::MPPICParcel().
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 226 of file MPPICParcel.H.
References MPPICParcel< ParcelType >::MPPICParcel().
UCorrect() [1/2]
const Foam::vector & UCorrect () const inline
Return const access to correction velocity.
Definition at line 81 of file MPPICParcelI.H.
Referenced by MPPICParcel< ParcelType >::iNew::operator()(), and MPPICParcel< ParcelType >::writeFields().
UCorrect() [2/2]
Foam::vector & UCorrect () inline
Return access to correction velocity.
Definition at line 88 of file MPPICParcelI.H.
move()
bool move (TrackData & td, const scalar trackTime)
Move the parcel.
Definition at line 58 of file MPPICParcel.C.
References f(), p, and KinematicParcel< ParcelType >::U().
Referenced by MPPICParcel< ParcelType >::iNew::operator()().
readFields()
void readFields (CloudType & c) static
Read.
Definition at line 76 of file MPPICParcelIO.C.
References Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAllIter, p, Foam::readFields(), Cloud< ParticleType >::size(), and MPPICParcel< ParcelType >::UCorrect_.
Referenced by MPPICParcel< ParcelType >::iNew::operator()().
writeFields()
void writeFields (const CloudType & c) static
Write.
Definition at line 103 of file MPPICParcelIO.C.
References Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), p, Cloud< ParticleType >::size(), MPPICParcel< ParcelType >::UCorrect(), and regIOobject::write().
Referenced by MPPICParcel< ParcelType >::iNew::operator()().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const MPPICParcel< ParcelType > &) friend
Member Data Documentation
UCorrect_
vector UCorrect_ protected
Velocity correction due to collisions [m/s].
Definition at line 157 of file MPPICParcel.H.
Referenced by MPPICParcel< ParcelType >::readFields().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.C
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelI.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelIO.C