OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ThermoCloud< CloudType > Class Template Reference
Templated base class for thermodynamic cloud.
Public Types
typedef CloudType cloudType
Type of cloud this cloud was instantiated for.
typedef CloudType::particleType parcelType
Type of parcel the cloud was instantiated for.
typedef ThermoCloud< CloudType > thermoCloudType
Convenience typedef for this cloud type.
Public Types inherited from DsmcCloud< ParcelType >
typedef ParcelType parcelType
Type of parcel the cloud was instantiated for.
Public Types inherited from Cloud< ParcelType >
typedef ParcelType particleType
typedef IDLList< ParcelType >::iterator iterator
typedef IDLList< ParcelType >::const_iterator const_iterator
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from UILList< DLListBase, ParcelType >
typedef ParcelType value_type
Type of values the DLList contains.
typedef ParcelType & reference
Type that can be used for storing into DLList::value_type.
typedef const ParcelType & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase ::iterator LListBase_iterator
typedef DLListBase ::const_iterator LListBase_const_iterator
typedef DLListBase ::const_reverse_iterator LListBase_const_reverse_iterator
Public Member Functions
ThermoCloud (const word &cloudName, const volScalarField &rho, const volVectorField &U, const dimensionedVector &g, const SLGThermo &thermo, bool readFields=true)
Construct given carrier gas fields.
ThermoCloud (ThermoCloud< CloudType > &c, const word &name)
Copy constructor with new name.
ThermoCloud (const fvMesh &mesh, const word &name, const ThermoCloud< CloudType > &c)
Copy constructor with new name - creates bare cloud.
virtual autoPtr< Cloud< parcelType > > clone (const word &name)
Construct and return clone based on (this) with new name.
virtual autoPtr< Cloud< parcelType > > cloneBare (const word &name) const
Construct and return bare clone based on (this) with new name.
virtual ~ThermoCloud ()
Destructor.
const ThermoCloud & cloudCopy () const
Return a reference to the cloud copy.
const parcelType::constantProperties & constProps () const
Return the constant properties.
parcelType::constantProperties & constProps ()
Return access to the constant properties.
const SLGThermo & thermo () const
Return const access to thermo package.
const volScalarField & T () const
Return const access to the carrier temperature field.
const volScalarField & p () const
Return const access to the carrier prressure field.
const HeatTransferModel< ThermoCloud< CloudType > > & heatTransfer () const
Return reference to heat transfer model.
const scalarIntegrationScheme & TIntegrator () const
Return reference to velocity integration.
bool radiation () const
Radiation flag.
DimensionedField< scalar, volMesh > & radAreaP ()
Radiation sum of parcel projected areas [m2].
const DimensionedField< scalar, volMesh > & radAreaP () const
Radiation sum of parcel projected areas [m2].
DimensionedField< scalar, volMesh > & radT4 ()
Radiation sum of parcel temperature^4 [K4].
const DimensionedField< scalar, volMesh > & radT4 () const
Radiation sum of parcel temperature^4 [K4].
DimensionedField< scalar, volMesh > & radAreaPT4 ()
Radiation sum of parcel projected area*temperature^4 [m2K4].
const DimensionedField< scalar, volMesh > & radAreaPT4 () const
Radiation sum of parcel temperature^4 [m2K4].
DimensionedField< scalar, volMesh > & hsTrans ()
Sensible enthalpy transfer [J/kg].
const DimensionedField< scalar, volMesh > & hsTrans () const
Sensible enthalpy transfer [J/kg].
DimensionedField< scalar, volMesh > & hsCoeff ()
Return coefficient for carrier phase hs equation.
const DimensionedField< scalar, volMesh > & hsCoeff () const
Return const coefficient for carrier phase hs equation.
tmp< fvScalarMatrix > Sh (volScalarField &hs) const
Return sensible enthalpy source term [J/kg/m3/s].
tmp< volScalarField > Ep () const
Return tmp equivalent particulate emission.
tmp< volScalarField > ap () const
Return tmp equivalent particulate absorption.
tmp< volScalarField > sigmap () const
Return tmp equivalent particulate scattering factor.
scalar Tmax () const
Maximum temperature.
scalar Tmin () const
Minimum temperature.
void setParcelThermoProperties (parcelType &parcel, const scalar lagrangianDt)
Set parcel thermo properties.
void checkParcelProperties (parcelType &parcel, const scalar lagrangianDt, const bool fullyDescribed)
Check parcel properties.
void storeState ()
Store the current cloud state.
void restoreState ()
Reset the current cloud to the previously stored state.
void resetSourceTerms ()
Reset the cloud source terms.
void relaxSources (const ThermoCloud< CloudType > &cloudOldTime)
Apply relaxation to (steady state) cloud sources.
void scaleSources ()
Apply scaling to (transient) cloud sources.
void preEvolve ()
Pre-evolve.
void evolve ()
Evolve the cloud.
virtual void autoMap (const mapPolyMesh &)
Remap the cells of particles corresponding to the.
void info ()
Print cloud information.
Public Member Functions inherited from DsmcCloud< ParcelType >
DsmcCloud (const word &cloudName, const fvMesh &mesh, bool readFields=true)
Construct given name and mesh, will read Parcels and fields from.
DsmcCloud (const word &cloudName, const fvMesh &mesh, const IOdictionary &dsmcInitialiseDict)
Construct given name, mesh and initialisation dictionary.
virtual ~DsmcCloud ()
Destructor.
const word & cloudName () const
Return the cloud type.
const fvMesh & mesh () const
Return refernce to the mesh.
const IOdictionary & particleProperties () const
Return particle properties dictionary.
const List< word > & typeIdList () const
Return the idList.
scalar nParticle () const
Return the number of real particles represented by one.
const List< DynamicList< ParcelType * > > & cellOccupancy () const
Return the cell occupancy addressing.
volScalarField & sigmaTcRMax ()
Return the sigmaTcRMax field. non-const access to allow.
scalarField & collisionSelectionRemainder ()
Return the collision selection remainder field. non-const.
const List< typename ParcelType::constantProperties > & constProps () const
Return all of the constant properties.
const ParcelType::constantProperties & constProps (label typeId) const
Return the constant properties of the given typeId.
Random & rndGen ()
Return refernce to the random object.
volScalarField::GeometricBoundaryField & qBF ()
Return non-const heat flux boundary field reference.
volVectorField::GeometricBoundaryField & fDBF ()
Return non-const force density at boundary field reference.
volScalarField::GeometricBoundaryField & rhoNBF ()
Return non-const number density boundary field reference.
volScalarField::GeometricBoundaryField & rhoMBF ()
Return non-const mass density boundary field reference.
volScalarField::GeometricBoundaryField & linearKEBF ()
Return non-const linear kinetic energy density boundary.
volScalarField::GeometricBoundaryField & internalEBF ()
Return non-const internal energy density boundary field.
volScalarField::GeometricBoundaryField & iDofBF ()
Return non-const internal degree of freedom density boundary.
volVectorField::GeometricBoundaryField & momentumBF ()
Return non-const momentum density boundary field reference.
const volScalarField & boundaryT () const
Return macroscopic temperature.
const volVectorField & boundaryU () const
Return macroscopic velocity.
const volScalarField & q () const
Return heat flux at surface field.
const volVectorField & fD () const
Return force density at surface field.
const volScalarField & rhoN () const
Return the real particle number density field.
const volScalarField & rhoM () const
Return the particle mass density field.
const volScalarField & dsmcRhoN () const
Return the field of number of DSMC particles.
const volScalarField & linearKE () const
Return the total linear kinetic energy (translational and.
const volScalarField & internalE () const
Return the internal energy density field.
const volScalarField & iDof () const
Return the average internal degrees of freedom field.
const volVectorField & momentum () const
Return the momentum density field.
vector equipartitionLinearVelocity (scalar temperature, scalar mass)
Generate a random velocity sampled from the Maxwellian speed.
scalar equipartitionInternalEnergy (scalar temperature, scalar internalDegreesOfFreedom)
Generate a random internal energy, sampled from the.
scalar maxwellianAverageSpeed (scalar temperature, scalar mass) const
Average particle speed.
scalarField maxwellianAverageSpeed (scalarField temperature, scalar mass) const
scalar maxwellianRMSSpeed (scalar temperature, scalar mass) const
RMS particle speed.
scalarField maxwellianRMSSpeed (scalarField temperature, scalar mass) const
scalar maxwellianMostProbableSpeed (scalar temperature, scalar mass) const
Most probable speed.
scalarField maxwellianMostProbableSpeed (scalarField temperature, scalar mass) const
const BinaryCollisionModel< DsmcCloud< ParcelType > > & binaryCollision () const
Return reference to binary elastic collision model.
BinaryCollisionModel< DsmcCloud< ParcelType > > & binaryCollision ()
Return non-const reference to binary elastic collision model.
const WallInteractionModel< DsmcCloud< ParcelType > > & wallInteraction () const
Return reference to wall interaction model.
WallInteractionModel< DsmcCloud< ParcelType > > & wallInteraction ()
Return non-const reference to wall interaction model.
const InflowBoundaryModel< DsmcCloud< ParcelType > > & inflowBoundary () const
Return reference to wall interaction model.
InflowBoundaryModel< DsmcCloud< ParcelType > > & inflowBoundary ()
Return non-const reference to wall interaction model.
scalar massInSystem () const
Total mass in system.
vector linearMomentumOfSystem () const
Total linear momentum of the system.
scalar linearKineticEnergyOfSystem () const
Total linear kinetic energy in the system.
scalar internalEnergyOfSystem () const
Total internal energy in the system.
void info () const
Print cloud information.
void dumpParticlePositions () const
Dump particle positions to .obj file.
void addNewParcel (const vector &position, const vector &U, const scalar Ei, const label cellI, const label tetFaceI, const label tetPtI, const label typeId)
Add new parcel.
void evolve ()
Evolve the cloud (move, collide)
void clear ()
Clear the Cloud.
Public Member Functions inherited from Cloud< ParcelType >
TypeName ("Cloud")
Runtime type information.
Cloud (const polyMesh &mesh, const IDLList< ParcelType > &particles)
Construct from mesh and a list of particles.
Cloud (const polyMesh &mesh, const word &cloudName, const IDLList< ParcelType > &particles)
Construct from mesh, cloud name, and a list of particles.
Cloud (const polyMesh &mesh, const bool checkClass=true)
Construct from mesh by reading from file.
Cloud (const polyMesh &pMesh, const word &cloudName, const bool checkClass=true)
Construct from mesh by reading from file with given cloud instance.
const polyMesh & pMesh () const
Return the polyMesh reference.
label size () const
DynamicList< label > & labels ()
label nTrackingRescues () const
Return nTrackingRescues.
void trackingRescue () const
Increment the nTrackingRescues counter.
const PackedBoolList & cellHasWallFaces () const
Whether each cell has any wall faces (demand driven data)
virtual bool hasWallImpactDistance () const
Switch to specify if particles of the cloud can return.
const const_iterator begin () const
iterator begin ()
const const_iterator cbegin () const
const const_iterator end () const
iterator end ()
const const_iterator cend () const
void clear ()
void addParticle (ParcelType *pPtr)
Transfer particle to cloud.
void deleteParticle (ParcelType &)
Remove particle from cloud and delete.
void cloudReset (const Cloud< ParcelType > &c)
Reset the particles.
void move (TrackData &td, const scalar trackTime)
Move the particles.
void autoMap (TrackData &td, const mapPolyMesh &)
Remap the cells of particles corresponding to the.
IOobject fieldIOobject (const word &fieldName, const IOobject::readOption r) const
Helper to construct IOobject for field and current time.
void checkFieldIOobject (const Cloud< ParcelType > &c, const IOField< DataType > &data) const
Check lagrangian data field.
void checkFieldFieldIOobject (const Cloud< ParcelType > &c, const CompactIOField< Field< DataType >, DataType > &data) const
Check lagrangian data fieldfield.
virtual void readFields ()
Read the field data for the cloud of particles. Dummy at.
virtual void writeFields () const
Write the field data for the cloud of particles Dummy at.
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write using given format, version and compression.
void writePositions () const
Write positions to <cloudName>_positions.obj file.
Public Member Functions inherited from cloud
TypeName ("cloud")
Runtime type information.
cloud (const objectRegistry &, const word &cloudName="")
Construct for the given objectRegistry and named cloud instance.
virtual ~cloud ()
Destructor.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash > > &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from IDLList< ParcelType >
IDLList ()
Null construct.
IDLList (const ParcelType &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< ParcelType > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, ParcelType >
ILList ()
Null construct.
ILList (ParcelType *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, ParcelType > &)
Construct as copy.
ILList (const ILList< DLListBase, ParcelType > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (ParcelType *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, ParcelType > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, ParcelType > &)
Public Member Functions inherited from UILList< DLListBase, ParcelType >
UILList ()
Null construct.
UILList (ParcelType *a)
Construct given initial T.
UILList (const UILList< DLListBase, ParcelType > &)
Construct as copy.
ParcelType * first ()
Return the first entry.
const ParcelType * first () const
Return the first entry.
ParcelType * last ()
Return the last entry.
const ParcelType * last () const
Return the last entry.
ParcelType * removeHead ()
Remove and return head.
ParcelType * remove (ParcelType *p)
Remove and return element.
ParcelType * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, ParcelType > &)
bool operator== (const UILList< DLListBase, ParcelType > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, ParcelType > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Public Member Functions inherited from DsmcBaseCloud
TypeName ("DsmcBaseCloud")
Runtime type information.
DsmcBaseCloud ()
Null constructor.
virtual ~DsmcBaseCloud ()
Destructor.
Public Member Functions inherited from thermoCloud
TypeName ("thermoCloud")
Runtime type information.
thermoCloud ()
Null constructor.
virtual ~thermoCloud ()
Destructor.
Protected Member Functions
void setModels ()
Set cloud sub-models.
void cloudReset (ThermoCloud< CloudType > &c)
Reset state of cloud.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
parcelType::constantProperties constProps_
Thermo parcel constant properties.
const SLGThermo & thermo_
SLG thermodynamics package.
const volScalarField & T_
Temperature [K].
const volScalarField & p_
Pressure [Pa].
autoPtr< HeatTransferModel< ThermoCloud< CloudType > > > heatTransferModel_
Heat transfer model.
autoPtr< scalarIntegrationScheme > TIntegrator_
Temperature integration.
Switch radiation_
Include radiation.
autoPtr< DimensionedField< scalar, volMesh > > radAreaP_
Radiation sum of parcel projected areas.
autoPtr< DimensionedField< scalar, volMesh > > radT4_
Radiation sum of parcel temperature^4.
autoPtr< DimensionedField< scalar, volMesh > > radAreaPT4_
Radiation sum of parcel projected areas * temperature^4.
autoPtr< DimensionedField< scalar, volMesh > > hsTrans_
Sensible enthalpy transfer [J/kg].
autoPtr< DimensionedField< scalar, volMesh > > hsCoeff_
Coefficient for carrier phase hs equation [W/K].
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from Cloud< ParcelType >
static word cloudPropertiesName
Name of cloud properties dictionary.
Static Public Attributes inherited from cloud
static const word prefix
The prefix to local: lagrangian.
static word defaultName
The default cloud name: defaultCloud.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class CloudType>
class Foam::ThermoCloud< CloudType >
Templated base class for thermodynamic cloud.
- Adds to kinematic cloud
Heat transfer
Source files
ThermoCloud.H
ThermoCloudI.H
ThermoCloud.C
Definition at line 60 of file ThermoCloud.H.
Member Typedef Documentation
cloudType
typedef CloudType cloudType
Type of cloud this cloud was instantiated for.
Definition at line 70 of file ThermoCloud.H.
parcelType
typedef CloudType::particleType parcelType
Type of parcel the cloud was instantiated for.
Definition at line 73 of file ThermoCloud.H.
thermoCloudType
typedef ThermoCloud<CloudType> thermoCloudType
Convenience typedef for this cloud type.
Definition at line 76 of file ThermoCloud.H.
Constructor & Destructor Documentation
ThermoCloud() [1/3]
ThermoCloud (const word & cloudName, const volScalarField & rho, const volVectorField & U, const dimensionedVector & g, const SLGThermo & thermo, bool readFields = true)
Construct given carrier gas fields.
Definition at line 136 of file ThermoCloud.C.
ThermoCloud() [2/3]
ThermoCloud (ThermoCloud< CloudType > & c, const word & name)
Copy constructor with new name.
Definition at line 218 of file ThermoCloud.C.
ThermoCloud() [3/3]
ThermoCloud (const fvMesh & mesh, const word & name, const ThermoCloud< CloudType > & c)
Copy constructor with new name - creates bare cloud.
Definition at line 327 of file ThermoCloud.C.
~ThermoCloud()
~ThermoCloud () virtual
Destructor.
Definition at line 354 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
Member Function Documentation
setModels()
void setModels () protected
Set cloud sub-models.
Definition at line 34 of file ThermoCloud.C.
cloudReset()
void cloudReset (ThermoCloud< CloudType > & c) protected
Reset state of cloud.
Definition at line 121 of file ThermoCloud.C.
clone()
virtual autoPtr<Cloud<parcelType> > clone (const word & name) inline virtual
Construct and return clone based on (this) with new name.
Definition at line 194 of file ThermoCloud.H.
cloneBare()
virtual autoPtr<Cloud<parcelType> > cloneBare (const word & name) const inline virtual
Construct and return bare clone based on (this) with new name.
Definition at line 203 of file ThermoCloud.H.
cloudCopy()
const Foam::ThermoCloud< CloudType > & cloudCopy () const inline
Return a reference to the cloud copy.
Definition at line 34 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
constProps() [1/2]
const CloudType::particleType::constantProperties & constProps () const inline
Return the constant properties.
Definition at line 42 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
constProps() [2/2]
CloudType::particleType::constantProperties & constProps () inline
Return access to the constant properties.
Definition at line 50 of file ThermoCloudI.H.
thermo()
const Foam::SLGThermo & thermo () const inline
Return const access to thermo package.
Definition at line 57 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
T()
const Foam::volScalarField & T () const inline
Return const access to the carrier temperature field.
Definition at line 64 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
p()
const Foam::volScalarField & p () const inline
Return const access to the carrier prressure field.
Definition at line 71 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
heatTransfer()
const Foam::HeatTransferModel< Foam::ThermoCloud< CloudType > > & heatTransfer () const inline
Return reference to heat transfer model.
Definition at line 79 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
TIntegrator()
const Foam::scalarIntegrationScheme & TIntegrator () const inline
Return reference to velocity integration.
Definition at line 87 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
radiation()
bool radiation () const inline
Radiation flag.
Definition at line 94 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
radAreaP() [1/2]
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & radAreaP () inline
Radiation sum of parcel projected areas [m2].
Definition at line 102 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), ThermoCloud< Foam::DsmcCloud >::relaxSources(), and ThermoCloud< Foam::DsmcCloud >::ThermoCloud().
radAreaP() [2/2]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & radAreaP () const inline
Radiation sum of parcel projected areas [m2].
Definition at line 120 of file ThermoCloudI.H.
radT4() [1/2]
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & radT4 () inline
Radiation sum of parcel temperature^4 [K4].
Definition at line 138 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), ThermoCloud< Foam::DsmcCloud >::relaxSources(), and ThermoCloud< Foam::DsmcCloud >::ThermoCloud().
radT4() [2/2]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & radT4 () const inline
Radiation sum of parcel temperature^4 [K4].
Definition at line 156 of file ThermoCloudI.H.
radAreaPT4() [1/2]
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & radAreaPT4 () inline
Radiation sum of parcel projected area*temperature^4 [m2K4].
Definition at line 174 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), ThermoCloud< Foam::DsmcCloud >::relaxSources(), and ThermoCloud< Foam::DsmcCloud >::ThermoCloud().
radAreaPT4() [2/2]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & radAreaPT4 () const inline
Radiation sum of parcel temperature^4 [m2K4].
Definition at line 192 of file ThermoCloudI.H.
hsTrans() [1/2]
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & hsTrans () inline
Sensible enthalpy transfer [J/kg].
Definition at line 210 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), and ThermoCloud< Foam::DsmcCloud >::relaxSources().
hsTrans() [2/2]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & hsTrans () const inline
Sensible enthalpy transfer [J/kg].
Definition at line 218 of file ThermoCloudI.H.
hsCoeff() [1/2]
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & hsCoeff () inline
Return coefficient for carrier phase hs equation.
Definition at line 226 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), and ThermoCloud< Foam::DsmcCloud >::relaxSources().
hsCoeff() [2/2]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & hsCoeff () const inline
Return const coefficient for carrier phase hs equation.
Definition at line 234 of file ThermoCloudI.H.
Sh()
Foam::tmp< Foam::fvScalarMatrix > Sh (volScalarField & hs) const inline
Return sensible enthalpy source term [J/kg/m3/s].
Definition at line 242 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
Ep()
Foam::tmp< Foam::volScalarField > Ep () const inline virtual
Return tmp equivalent particulate emission.
Implements thermoCloud.
Definition at line 281 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
ap()
Foam::tmp< Foam::volScalarField > ap () const inline virtual
Return tmp equivalent particulate absorption.
Implements thermoCloud.
Definition at line 317 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
sigmap()
Foam::tmp< Foam::volScalarField > sigmap () const inline virtual
Return tmp equivalent particulate scattering factor.
Implements thermoCloud.
Definition at line 354 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
Tmax()
Foam::scalar Tmax () const inline
Maximum temperature.
Definition at line 391 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
Tmin()
Foam::scalar Tmin () const inline
Minimum temperature.
Definition at line 417 of file ThermoCloudI.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
setParcelThermoProperties()
void setParcelThermoProperties (parcelType & parcel, const scalar lagrangianDt)
Set parcel thermo properties.
Definition at line 362 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), and ThermoCloud< Foam::DsmcCloud >::~ThermoCloud().
checkParcelProperties()
void checkParcelProperties (parcelType & parcel, const scalar lagrangianDt, const bool fullyDescribed)
Check parcel properties.
Definition at line 376 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), and ThermoCloud< Foam::DsmcCloud >::setParcelThermoProperties().
storeState()
void storeState ()
Store the current cloud state.
Definition at line 387 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
restoreState()
void restoreState ()
Reset the current cloud to the previously stored state.
Definition at line 400 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
resetSourceTerms()
void resetSourceTerms ()
Reset the cloud source terms.
Definition at line 408 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
relaxSources()
void relaxSources (const ThermoCloud< CloudType > & cloudOldTime)
Apply relaxation to (steady state) cloud sources.
Definition at line 425 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare(), and ThermoCloud< Foam::DsmcCloud >::resetSourceTerms().
scaleSources()
void scaleSources ()
Apply scaling to (transient) cloud sources.
Definition at line 444 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
preEvolve()
void preEvolve ()
Pre-evolve.
Definition at line 461 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
evolve()
void evolve ()
Evolve the cloud.
Definition at line 470 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
autoMap()
void autoMap (const mapPolyMesh & mapper) virtual
Remap the cells of particles corresponding to the.
mesh topology change with a default tracking data object
Reimplemented from cloud.
Definition at line 483 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
info()
void info ()
Print cloud information.
Definition at line 496 of file ThermoCloud.C.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloneBare().
Member Data Documentation
constProps_
parcelType::constantProperties constProps_ protected
Thermo parcel constant properties.
Definition at line 101 of file ThermoCloud.H.
thermo_
const SLGThermo& thermo_ protected
SLG thermodynamics package.
Definition at line 107 of file ThermoCloud.H.
T_
const volScalarField& T_ protected
Temperature [K].
Definition at line 110 of file ThermoCloud.H.
p_
const volScalarField& p_ protected
Pressure [Pa].
Definition at line 113 of file ThermoCloud.H.
heatTransferModel_
autoPtr<HeatTransferModel<ThermoCloud<CloudType> > > heatTransferModel_ protected
Heat transfer model.
Definition at line 120 of file ThermoCloud.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloudReset().
TIntegrator_
autoPtr<scalarIntegrationScheme> TIntegrator_ protected
Temperature integration.
Definition at line 126 of file ThermoCloud.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloudReset().
radiation_
Switch radiation_ protected
Include radiation.
Definition at line 132 of file ThermoCloud.H.
Referenced by ThermoCloud< Foam::DsmcCloud >::cloudReset().
radAreaP_
autoPtr<DimensionedField<scalar, volMesh> > radAreaP_ protected
Radiation sum of parcel projected areas.
Definition at line 135 of file ThermoCloud.H.
radT4_
autoPtr<DimensionedField<scalar, volMesh> > radT4_ protected
Radiation sum of parcel temperature^4.
Definition at line 138 of file ThermoCloud.H.
radAreaPT4_
autoPtr<DimensionedField<scalar, volMesh> > radAreaPT4_ protected
Radiation sum of parcel projected areas * temperature^4.
Definition at line 141 of file ThermoCloud.H.
hsTrans_
autoPtr<DimensionedField<scalar, volMesh> > hsTrans_ protected
Sensible enthalpy transfer [J/kg].
Definition at line 147 of file ThermoCloud.H.
hsCoeff_
autoPtr<DimensionedField<scalar, volMesh> > hsCoeff_ protected
Coefficient for carrier phase hs equation [W/K].
Definition at line 150 of file ThermoCloud.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ThermoCloud/ThermoCloud.H
src/lagrangian/intermediate/clouds/Templates/ThermoCloud/ThermoCloud.C
src/lagrangian/intermediate/clouds/Templates/ThermoCloud/ThermoCloudI.H