OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Euler< Type > Class Template Reference
Euler-implicit integration.
Public Member Functions
TypeName ("Euler")
Runtime type information.
Euler (const word &phiName, const dictionary &dict)
Construct from components.
Euler (const Euler &is)
Copy constructor.
virtual autoPtr< IntegrationScheme< Type > > clone () const
Construct and return clone.
virtual ~Euler ()
Destructor.
virtual IntegrationScheme< Type >::integrationResult integrate (const Type &phi, const scalar dt, const Type &alphaBeta, const scalar beta) const
Perform the integration.
TypeName ("Euler")
Runtime type information.
Euler (const ODESystem &ode, const dictionary &dict)
Construct from ODE.
scalar solve (const scalar x0, const scalarField &y0, const scalarField &dydx0, const scalar dx, scalarField &y) const
Solve a single step dx and return the error.
void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
scalarField & absTol ()
scalarField & relTol ()
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Public Member Functions inherited from adaptiveSolver
adaptiveSolver (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~adaptiveSolver ()
Destructor.
void solve (const ODESystem &ode, scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Public Member Functions inherited from IntegrationScheme< Type >
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IntegrationScheme, dictionary,(const word &phiName, const dictionary &dict),(phiName, dict))
Declare runtime constructor selection table.
IntegrationScheme (const word &phiName, const dictionary &dict)
Construct from components.
IntegrationScheme (const IntegrationScheme &is)
Copy constructor.
virtual ~IntegrationScheme ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
Static Public Member Functions inherited from IntegrationScheme< Type >
static autoPtr< IntegrationScheme > New (const word &phiName, const dictionary &dict)
Return a reference to the selected radiation model.
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
label n_
Size of the ODESystem.
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
template<class Type>
class Foam::Euler< Type >
Euler-implicit integration.
Euler ODE solver of order (0)1.
The method calculates the new state from:
The error is estimated directly from the change in the solution, i.e. the difference between the 0th and 1st order solutions:
Source files
Euler.H
Euler.C
Definition at line 46 of file Euler.H.
Constructor & Destructor Documentation
Euler() [1/3]
Euler (const word & phiName, const dictionary & dict)
Construct from components.
Definition at line 32 of file Euler.C.
Euler() [2/3]
Euler (const Euler< Type > & is)
Copy constructor.
Definition at line 42 of file Euler.C.
~Euler()
~Euler () virtual
Destructor.
Definition at line 51 of file Euler.C.
References Euler< Type >::integrate().
Referenced by Euler< Type >::clone().
Euler() [3/3]
Euler (const ODESystem & ode, const dictionary & dict)
Construct from ODE.
Definition at line 40 of file Euler.C.
References Euler< Type >::solve().
Member Function Documentation
TypeName() [1/2]
TypeName ("Euler< Type >")
Runtime type information.
clone()
virtual autoPtr<IntegrationScheme<Type> > clone () const inline virtual
Construct and return clone.
Reimplemented from IntegrationScheme< Type >.
Definition at line 65 of file Euler.H.
References beta(), Euler< Type >::integrate(), phi, and Euler< Type >::~Euler().
integrate()
Foam::IntegrationScheme< Type >::integrationResult integrate (const Type & phi, const scalar dt, const Type & alphaBeta, const scalar beta) const virtual
Perform the integration.
Reimplemented from IntegrationScheme< Type >.
Definition at line 60 of file Euler.C.
References IntegrationScheme< Type >::integrationResult::average(), and IntegrationScheme< Type >::integrationResult::value().
Referenced by Euler< Type >::clone(), and Euler< Type >::~Euler().
TypeName() [2/2]
TypeName ("Euler< Type >")
Runtime type information.
solve() [1/2]
Foam::scalar solve (const scalar x0, const scalarField & y0, const scalarField & dydx0, const scalar dx, scalarField & y) const virtual
Solve a single step dx and return the error.
Implements adaptiveSolver.
Definition at line 51 of file Euler.C.
References forAll, and ODESolver::normalizeError().
Referenced by Euler< Type >::Euler().
solve() [2/2]
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system and the update the state.
Reimplemented from ODESolver.
Definition at line 76 of file Euler.C.
References ODESolver::odes_, and adaptiveSolver::solve().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/IntegrationScheme/Euler/Euler.H
src/lagrangian/intermediate/IntegrationScheme/Euler/Euler.C