OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CompositionModel< CloudType > Class Template Reference
Templated reacting parcel composition model class Consists of carrier species (via thermo package), and additional liquids and solids.
Public Member Functions
TypeName ("compositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CompositionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
CompositionModel (CloudType &owner)
Construct null from owner.
CompositionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
CompositionModel (const CompositionModel< CloudType > &cm)
Construct copy.
virtual autoPtr< CompositionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~CompositionModel ()
Destructor.
const SLGThermo & thermo () const
Return the thermo database.
const basicMultiComponentMixture & carrier () const
Return the carrier components (wrapper function)
const liquidMixtureProperties & liquids () const
Return the global (additional) liquids.
const solidMixtureProperties & solids () const
Return the global (additional) solids.
const phasePropertiesList & phaseProps () const
Return the list of phase properties.
label nPhase () const
Return the number of phases.
const wordList & phaseTypes () const
Return the list of phase type names.
const wordList & stateLabels () const
Return the list of state labels (s), (l), (g) etc.
const wordList & componentNames (const label phaseI) const
Return the list of component names for phaseI.
label globalCarrierId (const word &cmptName, const bool allowNotFound=false) const
Return global id of component cmptName in carrier thermo.
label globalId (const label phaseI, const word &cmptName, const bool allowNotFound=false) const
Return global id of component cmptName in phase phaseI.
const labelList & globalIds (const label phaseI) const
Return global ids of for phase phaseI.
label localId (const label phaseI, const word &cmptName, const bool allowNotFound=false) const
Return local id of component cmptName in phase phaseI.
label localToGlobalCarrierId (const label phaseI, const label id, const bool allowNotFound=false) const
Return global carrier id of component given local id.
const scalarField & Y0 (const label phaseI) const
Return the list of phase phaseI mass fractions.
scalarField X (const label phaseI, const scalarField &Y) const
Return the list of phase phaseI volume fractions fractions.
virtual const scalarField & YMixture0 () const
Return the list of mixture mass fractions.
virtual label idGas () const
Gas id.
virtual label idLiquid () const
Liquid id.
virtual label idSolid () const
Solid id.
virtual scalar H (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return total enthalpy for the phase phaseI.
virtual scalar Hs (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return sensible enthalpy for the phase phaseI.
virtual scalar Hc (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return chemical enthalpy for the phase phaseI.
virtual scalar Cp (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return specific heat caoacity for the phase phaseI.
virtual scalar L (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return latent heat for the phase phaseI.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< CompositionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::CompositionModel< CloudType >
Templated reacting parcel composition model class Consists of carrier species (via thermo package), and additional liquids and solids.
Source files
CompositionModel.H
CompositionModel.C
CompositionModelNew.C
Definition at line 52 of file ReactingCloud.H.
Constructor & Destructor Documentation
CompositionModel() [1/3]
CompositionModel (CloudType & owner)
Construct null from owner.
Definition at line 31 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::CompositionModel().
CompositionModel() [2/3]
CompositionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 41 of file CompositionModel.C.
CompositionModel() [3/3]
CompositionModel (const CompositionModel< CloudType > & cm)
Construct copy.
Definition at line 61 of file CompositionModel.C.
~CompositionModel()
~CompositionModel () virtual
Destructor.
Definition at line 74 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
Member Function Documentation
TypeName()
TypeName ("compositionModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , CompositionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
clone()
virtual autoPtr<CompositionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented in SingleMixtureFraction< CloudType >, SinglePhaseMixture< CloudType >, and NoComposition< CloudType >.
Definition at line 108 of file CompositionModel.H.
New()
Foam::autoPtr< Foam::CompositionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file CompositionModelNew.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
thermo()
const Foam::SLGThermo & thermo () const
Return the thermo database.
Definition at line 81 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
carrier()
const Foam::basicMultiComponentMixture & carrier () const
Return the carrier components (wrapper function)
Definition at line 89 of file CompositionModel.C.
Referenced by ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
liquids()
const Foam::liquidMixtureProperties & liquids () const
Return the global (additional) liquids.
Definition at line 97 of file CompositionModel.C.
Referenced by SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), ReactingParcel< ParcelType >::calcPhaseChange(), SprayParcel< ParcelType >::chi(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
solids()
const Foam::solidMixtureProperties & solids () const
Return the global (additional) solids.
Definition at line 105 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
phaseProps()
const Foam::phasePropertiesList & phaseProps () const
Return the list of phase properties.
Definition at line 113 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
nPhase()
Foam::label nPhase () const
Return the number of phases.
Definition at line 120 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
phaseTypes()
const Foam::wordList & phaseTypes () const
Return the list of phase type names.
If only 1 phase, return the component names of that phase
Definition at line 127 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
stateLabels()
const Foam::wordList & stateLabels () const
Return the list of state labels (s), (l), (g) etc.
Definition at line 142 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
componentNames()
const Foam::wordList & componentNames (const label phaseI) const
Return the list of component names for phaseI.
Definition at line 150 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
globalCarrierId()
Foam::label globalCarrierId (const word & cmptName, const bool allowNotFound = false) const
Return global id of component cmptName in carrier thermo.
Definition at line 158 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::componentNames().
globalId()
Foam::label globalId (const label phaseI, const word & cmptName, const bool allowNotFound = false) const
Return global id of component cmptName in phase phaseI.
Definition at line 185 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::globalCarrierId().
globalIds()
const Foam::labelList & globalIds (const label phaseI) const
Return global ids of for phase phaseI.
Definition at line 213 of file CompositionModel.C.
Referenced by ReactingParcel< ParcelType >::calcPhaseChange(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::globalId().
localId()
Foam::label localId (const label phaseI, const word & cmptName, const bool allowNotFound = false) const
Return local id of component cmptName in phase phaseI.
Definition at line 223 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::globalIds().
localToGlobalCarrierId()
Foam::label localToGlobalCarrierId (const label phaseI, const label id, const bool allowNotFound = false) const
Return global carrier id of component given local id.
Definition at line 251 of file CompositionModel.C.
Referenced by ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::localId().
Y0()
const Foam::scalarField & Y0 (const label phaseI) const
Return the list of phase phaseI mass fractions.
Definition at line 281 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::localToGlobalCarrierId().
X()
Foam::scalarField X (const label phaseI, const scalarField & Y) const
Return the list of phase phaseI volume fractions fractions.
based on supplied mass fractions Y
Definition at line 291 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Y0().
YMixture0()
const Foam::scalarField & YMixture0 () const virtual
Return the list of mixture mass fractions.
If only 1 phase, return component fractions of that phase
Reimplemented in SingleMixtureFraction< CloudType >, and SinglePhaseMixture< CloudType >.
Definition at line 341 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
idGas()
Foam::label idGas () const virtual
Gas id.
Reimplemented in SingleMixtureFraction< CloudType >, and SinglePhaseMixture< CloudType >.
Definition at line 354 of file CompositionModel.C.
Referenced by ReactingMultiphaseParcel< ParcelType >::calc(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
idLiquid()
Foam::label idLiquid () const virtual
Liquid id.
Reimplemented in SingleMixtureFraction< CloudType >, and SinglePhaseMixture< CloudType >.
Definition at line 366 of file CompositionModel.C.
Referenced by ReactingMultiphaseParcel< ParcelType >::calc(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
idSolid()
Foam::label idSolid () const virtual
Solid id.
Reimplemented in SingleMixtureFraction< CloudType >, and SinglePhaseMixture< CloudType >.
Definition at line 378 of file CompositionModel.C.
Referenced by ReactingMultiphaseParcel< ParcelType >::calc(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone().
H()
Foam::scalar H (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return total enthalpy for the phase phaseI.
Definition at line 391 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::idSolid().
Hs()
Foam::scalar Hs (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return sensible enthalpy for the phase phaseI.
Definition at line 455 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::H().
Hc()
Foam::scalar Hc (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return chemical enthalpy for the phase phaseI.
Definition at line 519 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hs().
Cp()
Foam::scalar Cp (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return specific heat caoacity for the phase phaseI.
Definition at line 579 of file CompositionModel.C.
Referenced by ReactingParcel< ParcelType >::calc(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hc().
L()
Foam::scalar L (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return latent heat for the phase phaseI.
Definition at line 638 of file CompositionModel.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Cp().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ReactingCloud/ReactingCloud.H
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/CompositionModel/CompositionModel.H
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/CompositionModel/CompositionModel.C
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/CompositionModel/CompositionModelNew.C