OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Analytical< Type > Class Template Reference
Analytical integration.
Public Member Functions
TypeName ("analytical")
Runtime type information.
Analytical (const word &phiName, const dictionary &dict)
Construct from components.
Analytical (const Analytical &is)
Copy constructor.
virtual autoPtr< IntegrationScheme< Type > > clone () const
Construct and return clone.
virtual ~Analytical ()
Destructor.
virtual IntegrationScheme< Type >::integrationResult integrate (const Type &phi, const scalar dt, const Type &alphaBeta, const scalar beta) const
Perform the integration.
Public Member Functions inherited from IntegrationScheme< Type >
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IntegrationScheme, dictionary,(const word &phiName, const dictionary &dict),(phiName, dict))
Declare runtime constructor selection table.
IntegrationScheme (const word &phiName, const dictionary &dict)
Construct from components.
IntegrationScheme (const IntegrationScheme &is)
Copy constructor.
virtual ~IntegrationScheme ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from IntegrationScheme< Type >
static autoPtr< IntegrationScheme > New (const word &phiName, const dictionary &dict)
Return a reference to the selected radiation model.
Detailed Description
template<class Type>
class Foam::Analytical< Type >
Analytical integration.
Definition at line 46 of file Analytical.H.
Constructor & Destructor Documentation
Analytical() [1/2]
Analytical (const word & phiName, const dictionary & dict)
Construct from components.
Definition at line 32 of file Analytical.C.
Analytical() [2/2]
Analytical (const Analytical< Type > & is)
Copy constructor.
Definition at line 42 of file Analytical.C.
~Analytical()
~Analytical () virtual
Destructor.
Definition at line 51 of file Analytical.C.
References Analytical< Type >::integrate().
Referenced by Analytical< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("analytical")
Runtime type information.
clone()
virtual autoPtr<IntegrationScheme<Type> > clone () const inline virtual
Construct and return clone.
Reimplemented from IntegrationScheme< Type >.
Definition at line 65 of file Analytical.H.
References beta(), Analytical< Type >::integrate(), phi, and Analytical< Type >::~Analytical().
integrate()
Foam::IntegrationScheme< Type >::integrationResult integrate (const Type & phi, const scalar dt, const Type & alphaBeta, const scalar beta) const virtual
Perform the integration.
Reimplemented from IntegrationScheme< Type >.
Definition at line 60 of file Analytical.C.
References Foam::constant::atomic::alpha, IntegrationScheme< Type >::integrationResult::average(), beta(), Foam::exp(), Foam::min(), phi, and IntegrationScheme< Type >::integrationResult::value().
Referenced by Analytical< Type >::clone(), and Analytical< Type >::~Analytical().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/IntegrationScheme/Analytical/Analytical.H
src/lagrangian/intermediate/IntegrationScheme/Analytical/Analytical.C