OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MPPICParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< MPPICParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::MPPICParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 233 of file MPPICParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 239 of file MPPICParcel.H.
Member Function Documentation
operator()()
autoPtr<MPPICParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 244 of file MPPICParcel.H.
References Foam::constant::universal::c, MPPICParcel< ParcelType >::move(), MPPICParcel< ParcelType >::readFields(), MPPICParcel< ParcelType >::UCorrect(), and MPPICParcel< ParcelType >::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.H