OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ReactingParcel< ParcelType > Class Template Reference
Reacting parcel class with one/two-way coupling with the continuous phase.
Classes
class constantProperties
Class to hold reacting particle constant properties.
class iNew
Factory class to read-construct particles used for.
class TrackingData
Public Member Functions
TypeName ("ReactingParcel")
Runtime type information.
AddToPropertyList (ParcelType, " mass0"+" nPhases(Y1..YN)")
String representation of properties.
ReactingParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from owner, position, and cloud owner.
ReactingParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const constantProperties &constProps)
Construct from components.
ReactingParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
ReactingParcel (const ReactingParcel &p, const polyMesh &mesh)
Construct as a copy.
ReactingParcel (const ReactingParcel &p)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
scalar mass0 () const
Return const access to initial particle mass [kg].
const scalarField & Y () const
Return const access to mass fractions of mixture [].
scalar pc () const
Return the owner cell pressure [Pa].
scalar & pc ()
Return reference to the owner cell pressure [Pa].
scalar & mass0 ()
Return access to initial particle mass [kg].
scalarField & Y ()
Return access to mass fractions of mixture [].
template<class TrackData >
void setCellValues (TrackData &td, const scalar dt, const label cellI)
Set cell values.
template<class TrackData >
void cellValueSourceCorrection (TrackData &td, const scalar dt, const label cellI)
Correct cell values using latest transfer information.
template<class TrackData >
void correctSurfaceValues (TrackData &td, const label cellI, const scalar T, const scalarField &Cs, scalar &rhos, scalar &mus, scalar &Prs, scalar &kappas)
Correct surface values due to emitted species.
template<class TrackData >
void calc (TrackData &td, const scalar dt, const label cellI)
Update parcel properties over the time interval.
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
Read.
template<class CloudType >
static void readFields (CloudType &c)
Read - no composition.
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
Write.
template<class CloudType >
static void writeFields (const CloudType &c)
Write - composition supplied.
Protected Member Functions
template<class TrackData >
void calcPhaseChange (TrackData &td, const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar Ts, const scalar nus, const scalar d, const scalar T, const scalar mass, const label idPhase, const scalar YPhase, const scalarField &YComponents, scalarField &dMassPC, scalar &Sh, scalar &N, scalar &NCpW, scalarField &Cs)
Calculate Phase change.
scalar updateMassFraction (const scalar mass0, const scalarField &dMass, scalarField &Y) const
Update mass fraction.
Protected Attributes
scalar mass0_
Initial particle mass [kg].
scalarField Y_
Mass fractions of mixture [].
scalar pc_
Pressure [Pa].
Friends
Ostream & operator (Ostream &, const ReactingParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingParcel< ParcelType >
Reacting parcel class with one/two-way coupling with the continuous phase.
Source files
ReactingParcel.H
ReactingParcelI.H
ReactingParcel.C
ReactingParcelIO.C
Definition at line 50 of file ReactingParcel.H.
Constructor & Destructor Documentation
ReactingParcel() [1/5]
ReactingParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 64 of file ReactingParcelI.H.
Referenced by ReactingParcel< ParcelType >::constantProperties::constantProperties(), and ReactingParcel< ParcelType >::updateMassFraction().
ReactingParcel() [2/5]
ReactingParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const constantProperties & constProps) inline
Construct from components.
Definition at line 81 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::mass0_.
ReactingParcel() [3/5]
ReactingParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 40 of file ReactingParcelIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer().
ReactingParcel() [4/5]
ReactingParcel (const ReactingParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
ReactingParcel() [5/5]
ReactingParcel (const ReactingParcel< ParcelType > & p)
Construct as a copy.
Member Function Documentation
calcPhaseChange()
void calcPhaseChange (TrackData & td, const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar Ts, const scalar nus, const scalar d, const scalar T, const scalar mass, const label idPhase, const scalar YPhase, const scalarField & YComponents, scalarField & dMassPC, scalar & Sh, scalar & N, scalar & NCpW, scalarField & Cs) protected
Calculate Phase change.
Definition at line 39 of file ReactingParcel.C.
References subModelBase::active(), PhaseChangeModel< CloudType >::addToPhaseChangeMass(), PhaseChangeModel< CloudType >::calculate(), CompositionModel< CloudType >::carrier(), composition, PhaseChangeModel< CloudType >::dh(), forAll, CompositionModel< CloudType >::globalIds(), CompositionModel< CloudType >::liquids(), CompositionModel< CloudType >::localToGlobalCarrierId(), Foam::min(), specie::RR, Foam::sum(), PhaseChangeModel< CloudType >::TMax(), PhaseChangeModel< CloudType >::Tvap(), and ReactingParcel< ParcelType >::updateMassFraction().
updateMassFraction()
Foam::scalar updateMassFraction (const scalar mass0, const scalarField & dMass, scalarField & Y) const protected
Update mass fraction.
Definition at line 150 of file ReactingParcel.C.
References forAll, ReactingParcel< ParcelType >::mass0_, mesh, p, ReactingParcel< ParcelType >::pc_, ReactingParcel< ParcelType >::ReactingParcel(), ReactingParcel< ParcelType >::setCellValues(), Foam::sum(), and ReactingParcel< ParcelType >::Y_.
Referenced by ReactingParcel< ParcelType >::calcPhaseChange().
TypeName()
TypeName ("ReactingParcel< ParcelType >")
Runtime type information.
AddToPropertyList()
AddToPropertyList (ParcelType , " mass0"+" nPhases(Y1..YN)")
String representation of properties.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 269 of file ReactingParcel.H.
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 275 of file ReactingParcel.H.
References mesh.
mass0() [1/2]
Foam::scalar mass0 () const inline
Return const access to initial particle mass [kg].
Definition at line 146 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::mass0_.
Referenced by ReactingParcel< ParcelType >::iNew::operator()().
Y() [1/2]
const Foam::scalarField & Y () const inline
Return const access to mass fractions of mixture [].
Definition at line 153 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::Y_.
Referenced by ReactingParcel< ParcelType >::iNew::operator()(), and ReactingParcel< ParcelType >::writeFields().
pc() [1/2]
Foam::scalar pc () const inline
Return the owner cell pressure [Pa].
Definition at line 160 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::pc_.
Referenced by ReactingParcel< ParcelType >::iNew::operator()().
pc() [2/2]
Foam::scalar & pc () inline
Return reference to the owner cell pressure [Pa].
Definition at line 167 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::pc_.
mass0() [2/2]
Foam::scalar & mass0 () inline
Return access to initial particle mass [kg].
Definition at line 174 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::mass0_.
Y() [2/2]
Foam::scalarField & Y () inline
Return access to mass fractions of mixture [].
Definition at line 181 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::Y_.
setCellValues()
void setCellValues (TrackData & td, const scalar dt, const label cellI)
Set cell values.
Definition at line 205 of file ReactingParcel.C.
References ReactingParcel< ParcelType >::cellValueSourceCorrection(), Foam::endl(), Foam::nl, and WarningIn.
Referenced by ReactingParcel< ParcelType >::iNew::operator()(), and ReactingParcel< ParcelType >::updateMassFraction().
cellValueSourceCorrection()
void cellValueSourceCorrection (TrackData & td, const scalar dt, const label cellI)
Correct cell values using latest transfer information.
Definition at line 243 of file ReactingParcel.C.
References ReactingParcel< ParcelType >::correctSurfaceValues(), Foam::endl(), forAll, Foam::mag(), Foam::max(), Foam::nl, and WarningIn.
Referenced by ReactingParcel< ParcelType >::iNew::operator()(), and ReactingParcel< ParcelType >::setCellValues().
correctSurfaceValues()
void correctSurfaceValues (TrackData & td, const label cellI, const scalar T, const scalarField & Cs, scalar & rhos, scalar & mus, scalar & Prs, scalar & kappas)
Correct surface values due to emitted species.
Definition at line 315 of file ReactingParcel.C.
References ReactingParcel< ParcelType >::calc(), SLGThermo::carrier(), Foam::cbrt(), basicMultiComponentMixture::Cp(), forAll, basicMultiComponentMixture::kappa(), Foam::max(), Foam::min(), basicMultiComponentMixture::mu(), specie::RR, List< T >::size(), basicMultiComponentMixture::species(), Foam::sqrt(), Foam::sum(), Foam::T(), basicMultiComponentMixture::W(), and basicMultiComponentMixture::Y().
Referenced by ReactingParcel< ParcelType >::cellValueSourceCorrection(), and ReactingParcel< ParcelType >::iNew::operator()().
calc()
void calc (TrackData & td, const scalar dt, const label cellI)
Update parcel properties over the time interval.
Definition at line 407 of file ReactingParcel.C.
References CompositionModel< CloudType >::carrier(), Foam::cbrt(), composition, CompositionModel< CloudType >::Cp(), forAll, CompositionModel< CloudType >::localToGlobalCarrierId(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::Re(), Foam::fvc::Su(), and Vector< Cmpt >::zero.
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), and ReactingParcel< ParcelType >::iNew::operator()().
readFields() [1/2]
void readFields (CloudType & c, const CompositionType & compModel) static
Read.
Definition at line 101 of file ReactingParcelIO.C.
References Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAll, forAllIter, ReactingParcel< ParcelType >::mass0_, p, Foam::readFields(), List< T >::size(), Cloud< ParticleType >::size(), Y, and ReactingParcel< ParcelType >::Y_.
Referenced by ReactingParcel< ParcelType >::iNew::operator()(), and ReactingParcel< ParcelType >::readFields().
readFields() [2/2]
void readFields (CloudType & c) static
Read - no composition.
Definition at line 87 of file ReactingParcelIO.C.
References Foam::readFields(), ReactingParcel< ParcelType >::readFields(), and Cloud< ParticleType >::size().
writeFields() [1/2]
void writeFields (const CloudType & c, const CompositionType & compModel) static
Write.
Definition at line 173 of file ReactingParcelIO.C.
References Cloud< ParticleType >::fieldIOobject(), forAll, forAllConstIter(), ReactingParcel< ParcelType >::mass0_, p, List< T >::size(), Cloud< ParticleType >::size(), Y, and ReactingParcel< ParcelType >::Y().
Referenced by ReactingParcel< ParcelType >::iNew::operator()(), and ReactingParcel< ParcelType >::writeFields().
writeFields() [2/2]
void writeFields (const CloudType & c) static
Write - composition supplied.
Definition at line 164 of file ReactingParcelIO.C.
References ReactingParcel< ParcelType >::writeFields().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const ReactingParcel< ParcelType > &) friend
Member Data Documentation
mass0_
scalar mass0_ protected
Initial particle mass [kg].
Definition at line 154 of file ReactingParcel.H.
Referenced by ReactingParcel< ParcelType >::mass0(), ReactingParcel< ParcelType >::ReactingParcel(), ReactingParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::updateMassFraction(), and ReactingParcel< ParcelType >::writeFields().
Y_
scalarField Y_ protected
Mass fractions of mixture [].
Definition at line 157 of file ReactingParcel.H.
Referenced by ReactingParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::updateMassFraction(), and ReactingParcel< ParcelType >::Y().
pc_
scalar pc_ protected
Pressure [Pa].
Definition at line 163 of file ReactingParcel.H.
Referenced by ReactingParcel< ParcelType >::pc(), and ReactingParcel< ParcelType >::updateMassFraction().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelIO.C