OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
phaseProperties Class Reference
Helper class to manage multi-component phase properties.
Public Types
enum phaseType { GAS, LIQUID, SOLID, UNKNOWN }
Phase type enumeration.
Public Member Functions
phaseProperties ()
Null constructor.
phaseProperties (Istream &)
Construct from Istream.
phaseProperties (const phaseProperties &)
Construct as copy.
~phaseProperties ()
Destructor.
void initialiseGlobalIds (const wordList &gasNames, const wordList &liquidNames, const wordList &solidNames)
Initialise the global ids.
phaseType phase () const
Return const access to the phase type.
const word & stateLabel () const
Return const access to the phase state label.
word phaseTypeName () const
Return word representation of the phase type.
const List< word > & names () const
Return the list of component names.
const word & name (const label cmptI) const
Return const access to a component name.
const scalarField & Y () const
Return const access to all component mass fractions.
scalar & Y (const label cmptI)
Return non-const access to a component mass fraction.
const labelList & globalIds () const
Return const access to the global ids.
const labelList & globalCarrierIds () const
Return const access to the map to the carrier global ids.
label globalId (const word &cmptName) const
Return the global id of a component in the local list by name.
label id (const word &cmptName) const
Return the id of a component in the local list by name.
Static Public Attributes
static const NamedEnum< phaseType, 4 > phaseTypeNames_
Corresponding word representations for phase type enumerations.
Friends
Istream & operator>> (Istream &, phaseProperties &)
Ostream & operator<< (Ostream &, const phaseProperties &)
Detailed Description
Helper class to manage multi-component phase properties.
Source files
phaseProperties.H
phaseProperties.C
phasePropertiesIO.C
Definition at line 52 of file phaseProperties.H.
Member Enumeration Documentation
phaseType
enum phaseType
Phase type enumeration.
Enumerator
GAS
LIQUID
SOLID
UNKNOWN
Definition at line 59 of file phaseProperties.H.
Constructor & Destructor Documentation
phaseProperties() [1/3]
phaseProperties ()
Null constructor.
Definition at line 169 of file phaseProperties.C.
phaseProperties() [2/3]
phaseProperties (Istream & is)
Construct from Istream.
Definition at line 31 of file phasePropertiesIO.C.
References token::BEGIN_BLOCK, IOstream::check(), Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, forAll, forAllConstIter(), Foam::incrIndent(), entry::keyword(), dictionary::lookup(), Foam::nl, dictionary::null, Foam::operator<<(), Foam::operator>>(), phaseProperties::phaseTypeNames_, Foam::readScalar(), List< T >::setSize(), DLListBase::size(), and Ostream::writeKeyword().
phaseProperties() [3/3]
phaseProperties (const phaseProperties & pp)
Construct as copy.
Definition at line 180 of file phaseProperties.C.
~phaseProperties()
~phaseProperties ()
Destructor.
Definition at line 193 of file phaseProperties.C.
References phaseProperties::initialiseGlobalIds().
Member Function Documentation
initialiseGlobalIds()
void initialiseGlobalIds (const wordList & gasNames, const wordList & liquidNames, const wordList & solidNames)
Initialise the global ids.
Definition at line 200 of file phaseProperties.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, phaseProperties::GAS, phaseProperties::LIQUID, Foam::nl, phaseProperties::phaseTypeNames_, phaseProperties::SOLID, and WarningIn.
Referenced by phaseProperties::~phaseProperties().
phase()
Foam::phaseProperties::phaseType phase () const
Return const access to the phase type.
Definition at line 254 of file phaseProperties.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Cp(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::H(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hs(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::L(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::X().
stateLabel()
const Foam::word & stateLabel () const
Return const access to the phase state label.
Definition at line 260 of file phaseProperties.C.
phaseTypeName()
Foam::word phaseTypeName () const
Return word representation of the phase type.
Definition at line 266 of file phaseProperties.C.
References phaseProperties::phaseTypeNames_.
names()
const Foam::List< Foam::word > & names () const
Return the list of component names.
Definition at line 272 of file phaseProperties.C.
name()
const Foam::word & name (const label cmptI) const
Return const access to a component name.
Definition at line 278 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, and List< T >::size().
Y() [1/2]
const Foam::scalarField & Y () const
Return const access to all component mass fractions.
Definition at line 297 of file phaseProperties.C.
Y() [2/2]
Foam::scalar & Y (const label cmptI)
Return non-const access to a component mass fraction.
Definition at line 303 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, and List< T >::size().
globalIds()
const Foam::labelList & globalIds () const
Return const access to the global ids.
Definition at line 338 of file phaseProperties.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Cp(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::H(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hs(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::L(), and CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::X().
globalCarrierIds()
const Foam::labelList & globalCarrierIds () const
Return const access to the map to the carrier global ids.
Definition at line 344 of file phaseProperties.C.
globalId()
Foam::label globalId (const word & cmptName) const
Return the global id of a component in the local list by name.
Returns -1 if not found
Definition at line 322 of file phaseProperties.C.
References phaseProperties::id().
id()
Foam::label id (const word & cmptName) const
Return the id of a component in the local list by name.
Returns -1 if not found
Definition at line 350 of file phaseProperties.C.
References forAll.
Referenced by phaseProperties::globalId().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , phaseProperties &) friend
operator<<
Ostream& operator<< (Ostream & , const phaseProperties &) friend
Member Data Documentation
phaseTypeNames_
const Foam::NamedEnum< Foam::phaseProperties::phaseType, 4 > phaseTypeNames_ static
Corresponding word representations for phase type enumerations.
Definition at line 68 of file phaseProperties.H.
Referenced by phaseProperties::initialiseGlobalIds(), NamedEnum< directionType, 3 >::names(), phaseProperties::phaseProperties(), and phaseProperties::phaseTypeName().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/phaseProperties/phaseProperties/phaseProperties.H
src/lagrangian/intermediate/phaseProperties/phaseProperties/phaseProperties.C
src/lagrangian/intermediate/phaseProperties/phaseProperties/phasePropertiesIO.C