OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ThermoParcel< ParcelType > Class Template Reference
Thermodynamic parcel class with one/two-way coupling with the continuous phase. Includes Kinematic parcel sub-models, plus:
Classes
class constantProperties
Class to hold thermo particle constant properties.
class iNew
Factory class to read-construct particles used for.
class TrackingData
Public Member Functions
TypeName ("ThermoParcel")
Runtime type information.
AddToPropertyList (ParcelType, " T"+" Cp")
String representation of properties.
ThermoParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from owner, position, and cloud owner.
ThermoParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const constantProperties &constProps)
Construct from components.
ThermoParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
ThermoParcel (const ThermoParcel &p)
Construct as a copy.
ThermoParcel (const ThermoParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
scalar T () const
Return const access to temperature.
scalar Cp () const
Return const access to specific heat capacity.
scalar hs () const
Return the parcel sensible enthalpy.
scalar Tc () const
Return const access to carrier temperature.
scalar Cpc () const
Return const access to carrier specific heat capacity.
scalar & T ()
Return access to temperature.
scalar & Cp ()
Return access to specific heat capacity.
template<class TrackData >
void setCellValues (TrackData &td, const scalar dt, const label cellI)
Set cell values.
template<class TrackData >
void cellValueSourceCorrection (TrackData &td, const scalar dt, const label cellI)
Correct cell values using latest transfer information.
template<class TrackData >
void calcSurfaceValues (TrackData &td, const label cellI, const scalar T, scalar &Ts, scalar &rhos, scalar &mus, scalar &Pr, scalar &kappas) const
Calculate surface thermo properties.
template<class TrackData >
void calc (TrackData &td, const scalar dt, const label cellI)
Update parcel properties over the time interval.
template<class TrackData >
Foam::scalar calcHeatTransfer (TrackData &td, const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar &dhsTrans, scalar &Sph)
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
Read.
template<class CloudType >
static void writeFields (const CloudType &c)
Write.
Protected Member Functions
template<class TrackData >
scalar calcHeatTransfer (TrackData &td, const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar &dhsTrans, scalar &Sph)
Calculate new particle temperature.
Protected Attributes
scalar T_
Temperature [K].
scalar Cp_
Specific heat capacity [J/(kg.K)].
scalar Tc_
Temperature [K].
scalar Cpc_
Specific heat capacity [J/(kg.K)].
Friends
Ostream & operator (Ostream &, const ThermoParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ThermoParcel< ParcelType >
Thermodynamic parcel class with one/two-way coupling with the continuous phase. Includes Kinematic parcel sub-models, plus:
- heat transfer
Source files
ThermoParcel.H
ThermoParcelI.H
ThermoParcel.C
ThermoParcelIO.C
Definition at line 51 of file ThermoParcel.H.
Constructor & Destructor Documentation
ThermoParcel() [1/5]
ThermoParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 75 of file ThermoParcelI.H.
Referenced by ThermoParcel< ParcelType >::calcHeatTransfer(), ThermoParcel< ParcelType >::clone(), and ThermoParcel< ParcelType >::constantProperties::constantProperties().
ThermoParcel() [2/5]
ThermoParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const constantProperties & constProps) inline
Construct from components.
Definition at line 93 of file ThermoParcelI.H.
ThermoParcel() [3/5]
ThermoParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 40 of file ThermoParcelIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), and readScalar.
ThermoParcel() [4/5]
ThermoParcel (const ThermoParcel< ParcelType > & p)
Construct as a copy.
ThermoParcel() [5/5]
ThermoParcel (const ThermoParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
calcHeatTransfer() [1/2]
scalar calcHeatTransfer (TrackData & td, const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar & dhsTrans, scalar & Sph) protected
Calculate new particle temperature.
Referenced by ThermoParcel< ParcelType >::calc().
TypeName()
TypeName ("ThermoParcel< ParcelType >")
Runtime type information.
AddToPropertyList()
AddToPropertyList (ParcelType , " T"+" Cp")
String representation of properties.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 321 of file ThermoParcel.H.
References ThermoParcel< ParcelType >::ThermoParcel().
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 327 of file ThermoParcel.H.
References ThermoParcel< ParcelType >::ThermoParcel().
T() [1/2]
Foam::scalar T () const inline
Return const access to temperature.
Definition at line 195 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::T_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
Cp() [1/2]
Foam::scalar Cp () const inline
Return const access to specific heat capacity.
Definition at line 202 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Cp_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
hs()
Foam::scalar hs () const inline
Return the parcel sensible enthalpy.
Definition at line 209 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Cp_, and ThermoParcel< ParcelType >::T_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
Tc()
Foam::scalar Tc () const inline
Return const access to carrier temperature.
Definition at line 216 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Tc_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
Cpc()
Foam::scalar Cpc () const inline
Return const access to carrier specific heat capacity.
Definition at line 223 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Cpc_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
T() [2/2]
Foam::scalar & T () inline
Return access to temperature.
Definition at line 230 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::T_.
Cp() [2/2]
Foam::scalar & Cp () inline
Return access to specific heat capacity.
Definition at line 237 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Cp_.
setCellValues()
void setCellValues (TrackData & td, const scalar dt, const label cellI)
Set cell values.
Definition at line 36 of file ThermoParcel.C.
References ThermoParcel< ParcelType >::cellValueSourceCorrection(), Foam::endl(), Foam::nl, and WarningIn.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
cellValueSourceCorrection()
void cellValueSourceCorrection (TrackData & td, const scalar dt, const label cellI)
Correct cell values using latest transfer information.
Definition at line 74 of file ThermoParcel.C.
References ThermoParcel< ParcelType >::calcSurfaceValues(), Foam::endl(), Foam::nl, and WarningIn.
Referenced by ThermoParcel< ParcelType >::iNew::operator()(), and ThermoParcel< ParcelType >::setCellValues().
calcSurfaceValues()
void calcSurfaceValues (TrackData & td, const label cellI, const scalar T, scalar & Ts, scalar & rhos, scalar & mus, scalar & Pr, scalar & kappas) const
Calculate surface thermo properties.
Definition at line 109 of file ThermoParcel.C.
References ThermoParcel< ParcelType >::calc(), Foam::endl(), Foam::max(), Foam::nl, and WarningIn.
Referenced by ThermoParcel< ParcelType >::cellValueSourceCorrection(), and ThermoParcel< ParcelType >::iNew::operator()().
calc()
void calc (TrackData & td, const scalar dt, const label cellI)
Update parcel properties over the time interval.
Definition at line 164 of file ThermoParcel.C.
References ThermoParcel< ParcelType >::calcHeatTransfer(), Foam::pow4(), Pr(), Foam::Re(), Sh, Foam::fvc::Su(), and Vector< Cmpt >::zero.
Referenced by ThermoParcel< ParcelType >::calcSurfaceValues(), and ThermoParcel< ParcelType >::iNew::operator()().
readFields()
void readFields (CloudType & c) static
Read.
Definition at line 76 of file ThermoParcelIO.C.
References Cloud< ParticleType >::checkFieldIOobject(), ThermoParcel< ParcelType >::Cp_, Cloud< ParticleType >::fieldIOobject(), forAllIter, p, Foam::readFields(), Cloud< ParticleType >::size(), T, and ThermoParcel< ParcelType >::T_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
writeFields()
void writeFields (const CloudType & c) static
Write.
Definition at line 106 of file ThermoParcelIO.C.
References ThermoParcel< ParcelType >::Cp_, Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), p, Cloud< ParticleType >::size(), T, and ThermoParcel< ParcelType >::T_.
Referenced by ThermoParcel< ParcelType >::iNew::operator()().
calcHeatTransfer() [2/2]
Foam::scalar calcHeatTransfer (TrackData & td, const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar & dhsTrans, scalar & Sph)
Definition at line 270 of file ThermoParcel.C.
References ThermoParcel< ParcelType >::Cp_, ThermoParcel< ParcelType >::Cpc_, d(), epsilon, Foam::mag(), Foam::max(), mesh, Foam::min(), p, Foam::pow3(), Foam::pow4(), rho, Foam::constant::physicoChemical::sigma, ThermoParcel< ParcelType >::T_, ThermoParcel< ParcelType >::Tc_, ThermoParcel< ParcelType >::ThermoParcel(), and dimensioned< Type >::value().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const ThermoParcel< ParcelType > &) friend
Member Data Documentation
T_
scalar T_ protected
Temperature [K].
Definition at line 224 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::calcHeatTransfer(), ThermoParcel< ParcelType >::hs(), ThermoParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::T(), and ThermoParcel< ParcelType >::writeFields().
Cp_
scalar Cp_ protected
Specific heat capacity [J/(kg.K)].
Definition at line 227 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::calcHeatTransfer(), ThermoParcel< ParcelType >::Cp(), ThermoParcel< ParcelType >::hs(), ThermoParcel< ParcelType >::readFields(), and ThermoParcel< ParcelType >::writeFields().
Tc_
scalar Tc_ protected
Temperature [K].
Definition at line 233 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::calcHeatTransfer(), and ThermoParcel< ParcelType >::Tc().
Cpc_
scalar Cpc_ protected
Specific heat capacity [J/(kg.K)].
Definition at line 236 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::calcHeatTransfer(), and ThermoParcel< ParcelType >::Cpc().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.C
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelI.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelIO.C