OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ParticleTracks< CloudType > Class Template Reference
Records particle state (all variables) on each call to postFace.
Public Member Functions
TypeName ("particleTracks")
Runtime type information.
ParticleTracks (const dictionary &dict, CloudType &owner, const word &modelName)
Construct from dictionary.
ParticleTracks (const ParticleTracks< CloudType > &ppm)
Construct copy.
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
Construct and return a clone.
virtual ~ParticleTracks ()
Destructor.
label trackInterval () const
Return const access to the track interval.
label maxSamples () const
Return const access to the max samples.
const Switch & resetOnWrite () const
Return const access to the reset on write flag.
const hitTableType & faceHitCounter () const
Rerurn the table of number of times a particle has hit a face.
const Cloud< parcelType > & cloud () const
Return const access to the cloud.
virtual void preEvolve ()
Pre-evolve hook.
virtual void postFace (const parcelType &p, const label faceI, bool &keepParticle)
Post-face hook.
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
Declare runtime constructor selection table.
CloudFunctionObject (CloudType &owner)
Construct null from owner.
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Construct from dictionary.
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
Construct copy.
virtual ~CloudFunctionObject ()
Destructor.
virtual void postEvolve ()
Post-evolve hook.
virtual void postMove (typename CloudType::parcelType &p, const label cellI, const scalar dt, const point &position0, bool &keepParticle)
Post-move hook.
virtual void postPatch (const typename CloudType::parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &testIs, bool &keepParticle)
Post-patch hook.
virtual void postFace (const typename CloudType::parcelType &p, const label faceI, bool &keepParticle)
Post-face hook.
const fileName & outputDir () const
Return the output path.
fileName outputTimeDir () const
Return the output time path.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
void write ()
Write post-processing info.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Selector.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::ParticleTracks< CloudType >
Records particle state (all variables) on each call to postFace.
Source files
ParticleTracks.H
ParticleTracks.C
Definition at line 49 of file ParticleTracks.H.
Constructor & Destructor Documentation
ParticleTracks() [1/2]
ParticleTracks (const dictionary & dict, CloudType & owner, const word & modelName)
Construct from dictionary.
Definition at line 60 of file ParticleTracks.C.
Referenced by ParticleTracks< CloudType >::write().
ParticleTracks() [2/2]
ParticleTracks (const ParticleTracks< CloudType > & ppm)
Construct copy.
Definition at line 77 of file ParticleTracks.C.
~ParticleTracks()
~ParticleTracks () virtual
Destructor.
Definition at line 93 of file ParticleTracks.C.
Referenced by ParticleTracks< CloudType >::clone().
Member Function Documentation
write()
void write () protected virtual
Write post-processing info.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 34 of file ParticleTracks.C.
References Foam::endl(), Foam::Info, Foam::nl, and ParticleTracks< CloudType >::ParticleTracks().
TypeName()
TypeName ("particleTracks")
Runtime type information.
clone()
virtual autoPtr<CloudFunctionObject<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 108 of file ParticleTracks.H.
References ParticleTracks< CloudType >::cloud(), ParticleTracks< CloudType >::faceHitCounter(), ParticleTracks< CloudType >::maxSamples(), p, ParticleTracks< CloudType >::postFace(), ParticleTracks< CloudType >::preEvolve(), ParticleTracks< CloudType >::resetOnWrite(), ParticleTracks< CloudType >::trackInterval(), and ParticleTracks< CloudType >::~ParticleTracks().
trackInterval()
Foam::label trackInterval () const inline
Return const access to the track interval.
Definition at line 31 of file ParticleTracksI.H.
Referenced by ParticleTracks< CloudType >::clone().
maxSamples()
Foam::label maxSamples () const inline
Return const access to the max samples.
Definition at line 38 of file ParticleTracksI.H.
Referenced by ParticleTracks< CloudType >::clone().
resetOnWrite()
const Foam::Switch & resetOnWrite () const inline
Return const access to the reset on write flag.
Definition at line 45 of file ParticleTracksI.H.
Referenced by ParticleTracks< CloudType >::clone().
faceHitCounter()
const Foam::ParticleTracks< CloudType >::hitTableType & faceHitCounter () const inline
Rerurn the table of number of times a particle has hit a face.
Definition at line 53 of file ParticleTracksI.H.
Referenced by ParticleTracks< CloudType >::clone().
cloud()
const Foam::Cloud< typename CloudType::parcelType > & cloud () const inline
Return const access to the cloud.
Definition at line 61 of file ParticleTracksI.H.
Referenced by ParticleTracks< CloudType >::clone().
preEvolve()
void preEvolve () virtual
Pre-evolve hook.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 100 of file ParticleTracks.C.
References name(), and ParticleTracks< CloudType >::postFace().
Referenced by ParticleTracks< CloudType >::clone().
postFace()
void postFace (const parcelType & p, const label faceI, bool & keepParticle) virtual
Post-face hook.
Definition at line 114 of file ParticleTracks.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and nSamples().
Referenced by ParticleTracks< CloudType >::clone(), and ParticleTracks< CloudType >::preEvolve().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleTracks/ParticleTracks.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleTracks/ParticleTracks.C
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleTracks/ParticleTracksI.H