OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
TimeDataEntry< Type > Class Template Reference
Light wrapper around DataEntry to provide a mechanism to update time-based entries.
Public Member Functions
TimeDataEntry (const Time &t, const word &name, const dictionary &dict)
Construct from entry name.
TimeDataEntry (const Time &t, const word &entryName)
Construct null from entry name.
TimeDataEntry (const TimeDataEntry< Type > &tde)
Copy constructor.
virtual ~TimeDataEntry ()
Destructor.
void reset (const dictionary &dict)
Reset entry by re-reading from dictionary.
const word & name () const
Return the name of the entry.
virtual Type value (const scalar x) const
Return value as a function of (scalar) independent variable.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Protected Attributes
const Time & time_
Reference to the time database.
const word name_
Name of the data entry.
autoPtr< DataEntry< Type > > entry_
The underlying DataEntry.
Friends
Ostream & operator (Ostream &os, const TimeDataEntry< Type > &de)
Ostream Operator.
Detailed Description
template<class Type>
class Foam::TimeDataEntry< Type >
Light wrapper around DataEntry to provide a mechanism to update time-based entries.
Source files
TimeDataEntry.H
TimeDataEntry.C
Definition at line 65 of file ConeNozzleInjection.H.
Constructor & Destructor Documentation
TimeDataEntry() [1/3]
TimeDataEntry (const Time & t, const word & name, const dictionary & dict)
Construct from entry name.
Definition at line 32 of file TimeDataEntry.C.
Referenced by TimeDataEntry< scalar >::TimeDataEntry().
TimeDataEntry() [2/3]
TimeDataEntry (const Time & t, const word & entryName)
Construct null from entry name.
Definition at line 47 of file TimeDataEntry.C.
TimeDataEntry() [3/3]
TimeDataEntry (const TimeDataEntry< Type > & tde)
Copy constructor.
Definition at line 57 of file TimeDataEntry.C.
~TimeDataEntry()
~TimeDataEntry () virtual
Destructor.
Definition at line 75 of file TimeDataEntry.C.
Member Function Documentation
reset()
void reset (const dictionary & dict)
Reset entry by re-reading from dictionary.
Definition at line 82 of file TimeDataEntry.C.
Referenced by InjectionModel< CloudType >::InjectionModel().
name()
const Foam::word & name () const
Return the name of the entry.
Definition at line 98 of file TimeDataEntry.C.
value()
Type value (const scalar x) const virtual
Return value as a function of (scalar) independent variable.
Definition at line 105 of file TimeDataEntry.C.
Referenced by InjectionModel< CloudType >::InjectionModel(), and InjectionModel< CloudType >::injectSteadyState().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Definition at line 113 of file TimeDataEntry.C.
Referenced by TimeDataEntry< scalar >::value().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Definition at line 136 of file TimeDataEntry.C.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const TimeDataEntry< Type > & de) friend
Ostream Operator.
Member Data Documentation
time_
const Time& time_ protected
Reference to the time database.
Definition at line 68 of file TimeDataEntry.H.
name_
const word name_ protected
Name of the data entry.
Definition at line 71 of file TimeDataEntry.H.
entry_
autoPtr<DataEntry<Type> > entry_ protected
The underlying DataEntry.
Definition at line 74 of file TimeDataEntry.H.
Referenced by TimeDataEntry< scalar >::TimeDataEntry().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/ConeNozzleInjection/ConeNozzleInjection.H
src/OpenFOAM/primitives/functions/TimeDataEntry/TimeDataEntry/TimeDataEntry.H
src/OpenFOAM/primitives/functions/TimeDataEntry/TimeDataEntry/TimeDataEntry.C