OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
InjectionModel< CloudType > Class Template Reference
Templated injection model class.
Public Types
enum parcelBasis { pbNumber, pbMass, pbFixed }
Parcel basis representation options.
typedef CloudType::parcelType parcelType
Convenience typedef for parcelType.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
TypeName ("injectionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, InjectionModel, dictionary,(const dictionary &dict, CloudType &owner, const word &modelType),(dict, owner, modelType))
Declare runtime constructor selection table.
InjectionModel (CloudType &owner)
Construct null from owner.
InjectionModel (const dictionary &dict, CloudType &owner, const word &modelName, const word &modelType)
Construct from dictionary.
InjectionModel (const InjectionModel< CloudType > &im)
Construct copy.
virtual autoPtr< InjectionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~InjectionModel ()
Destructor.
virtual void updateMesh ()
Update mesh.
scalar timeStart () const
Return the start-of-injection time.
scalar volumeTotal () const
Return the total volume to be injected across the event.
scalar massTotal () const
Return mass of particles to introduce.
scalar massInjected () const
Return mass of particles injected (cumulative)
virtual scalar timeEnd () const
Return the end-of-injection time.
virtual label parcelsToInject (const scalar time0, const scalar time1)
Number of parcels to introduce relative to SOI.
virtual scalar volumeToInject (const scalar time0, const scalar time1)
Volume of parcels to introduce relative to SOI.
virtual scalar averageParcelMass ()
Return the average parcel mass over the injection period.
label nInjections () const
Return the number of injections.
label parcelsAddedTotal () const
Return the total number parcels added.
template<class TrackData >
void inject (TrackData &td)
Main injection loop.
template<class TrackData >
void injectSteadyState (TrackData &td, const scalar trackTime)
Main injection loop - steady-state.
virtual void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector &position, label &cellOwner, label &tetFaceI, label &tetPtI)
Set the injection position and owner cell, tetFace and tetPt.
virtual void setProperties (const label parcelI, const label nParcels, const scalar time, parcelType &parcel)
Set the parcel properties.
virtual bool fullyDescribed () const
Flag to identify whether model fully describes the parcel.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector with lookup from dictionary.
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, const word &modelName, const word &modelType, CloudType &owner)
Selector with name and type.
Protected Member Functions
virtual bool validInjection (const label parcelI)
Additional flag to identify whether or not injection of parcelI is.
virtual bool prepareForNextTimeStep (const scalar time, label &newParcels, scalar &newVolumeFraction)
Determine properties for next time step/injection interval.
virtual bool findCellAtPosition (label &cellI, label &tetFaceI, label &tetPtI, vector &position, bool errorOnNotFound=true)
Find the cell that contains the supplied position.
virtual scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho)
Set number of particles to inject given parcel properties.
virtual void postInjectCheck (const label parcelsAdded, const scalar massAdded)
Post injection checks.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
scalar SOI_
Start of injection [s].
scalar volumeTotal_
Total volume of particles introduced by this injector [m^3].
scalar massTotal_
Total mass to inject [kg].
TimeDataEntry< scalar > massFlowRate_
Mass flow rate profile for steady calculations.
scalar massInjected_
Total mass injected to date [kg].
label nInjections_
Number of injections counter.
label parcelsAddedTotal_
Running counter of total number of parcels added.
parcelBasis parcelBasis_
Parcel basis enumeration.
scalar nParticleFixed_
nParticle to assign to parcels when the 'fixed' basis
scalar time0_
Continuous phase time at start of injection time step [s].
scalar timeStep0_
Time at start of injection time step [s].
scalar delayedVolume_
Volume that should have been injected, but would lead to.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::InjectionModel< CloudType >
Templated injection model class.
The injection model nominally describes the parcel:
position
diameter
velocity In this case, the fullyDescribed() flag should be set to 0 (false). When the parcel is then added to the cloud, the remaining properties are populated using values supplied in the constant properties.
If, however, all of a parcel's properties are described in the model, the fullDescribed() flag should be set to 1 (true).
Source files
InjectionModel.H
InjectionModel.C
InjectionModelNew.C
Definition at line 67 of file InjectionModel.H.
Member Typedef Documentation
parcelType
typedef CloudType::parcelType parcelType
Convenience typedef for parcelType.
Definition at line 74 of file InjectionModel.H.
Member Enumeration Documentation
parcelBasis
enum parcelBasis
Parcel basis representation options.
i.e constant number of particles OR constant mass per parcel
Enumerator
pbNumber
pbMass
pbFixed
Definition at line 81 of file InjectionModel.H.
Constructor & Destructor Documentation
InjectionModel() [1/3]
InjectionModel (CloudType & owner)
Construct null from owner.
Definition at line 283 of file InjectionModel.C.
Referenced by InjectionModel< CloudType >::InjectionModel().
InjectionModel() [2/3]
InjectionModel (const dictionary & dict, CloudType & owner, const word & modelName, const word & modelType)
Construct from dictionary.
Definition at line 306 of file InjectionModel.C.
References subModelBase::coeffDict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, InjectionModel< CloudType >::InjectionModel(), dictionary::lookup(), InjectionModel< CloudType >::massFlowRate_, InjectionModel< CloudType >::massTotal_, Foam::nl, InjectionModel< CloudType >::nParticleFixed_, InjectionModel< CloudType >::parcelBasis_, InjectionModel< CloudType >::pbFixed, InjectionModel< CloudType >::pbMass, InjectionModel< CloudType >::pbNumber, Foam::readScalar(), TimeDataEntry< Type >::reset(), InjectionModel< CloudType >::SOI_, and TimeDataEntry< Type >::value().
InjectionModel() [3/3]
InjectionModel (const InjectionModel< CloudType > & im)
Construct copy.
Definition at line 386 of file InjectionModel.C.
~InjectionModel()
~InjectionModel () virtual
Destructor.
Definition at line 409 of file InjectionModel.C.
Referenced by InjectionModel< CloudType >::clone().
Member Function Documentation
validInjection()
bool validInjection (const label parcelI) protected virtual
Additional flag to identify whether or not injection of parcelI is.
permitted
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ThermoLookupTableInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 36 of file InjectionModel.C.
References notImplemented, and InjectionModel< CloudType >::prepareForNextTimeStep().
Referenced by InjectionModel< CloudType >::inject().
prepareForNextTimeStep()
bool prepareForNextTimeStep (const scalar time, label & newParcels, scalar & newVolumeFraction) protected virtual
Determine properties for next time step/injection interval.
Definition at line 49 of file InjectionModel.C.
References InjectionModel< CloudType >::findCellAtPosition().
Referenced by InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::validInjection().
findCellAtPosition()
bool findCellAtPosition (label & cellI, label & tetFaceI, label & tetPtI, vector & position, bool errorOnNotFound = true) protected virtual
Find the cell that contains the supplied position.
Will modify position slightly towards the owner cell centroid to ensure that it lies in a cell and not edge/face
Definition at line 105 of file InjectionModel.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, DimensionedField< Type, GeoMesh >::mesh(), UPstream::myProcNo(), Foam::nl, Foam::reduce(), and InjectionModel< CloudType >::setNumberOfParticles().
Referenced by InjectionModel< CloudType >::prepareForNextTimeStep().
setNumberOfParticles()
Foam::scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho) protected virtual
Set number of particles to inject given parcel properties.
Definition at line 199 of file InjectionModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, Foam::constant::mathematical::pi(), InjectionModel< CloudType >::postInjectCheck(), Foam::pow3(), and rho.
Referenced by InjectionModel< CloudType >::findCellAtPosition(), InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::injectSteadyState().
postInjectCheck()
void postInjectCheck (const label parcelsAdded, const scalar massAdded) protected virtual
Post injection checks.
Definition at line 251 of file InjectionModel.C.
References Foam::endl(), Foam::Info, Foam::nl, and Foam::returnReduce().
Referenced by InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), and InjectionModel< CloudType >::setNumberOfParticles().
TypeName()
TypeName ("injectionModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , InjectionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner, const word &modelType) , (dict, owner, modelType))
Declare runtime constructor selection table.
clone()
virtual autoPtr<InjectionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 222 of file InjectionModel.H.
References InjectionModel< CloudType >::averageParcelMass(), InjectionModel< CloudType >::fullyDescribed(), InjectionModel< CloudType >::info(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), InjectionModel< CloudType >::massInjected(), InjectionModel< CloudType >::massTotal(), subModelBase::modelName(), InjectionModel< CloudType >::New(), InjectionModel< CloudType >::nInjections(), InjectionModel< CloudType >::parcelsAddedTotal(), InjectionModel< CloudType >::parcelsToInject(), InjectionModel< CloudType >::setPositionAndCell(), InjectionModel< CloudType >::setProperties(), InjectionModel< CloudType >::timeEnd(), InjectionModel< CloudType >::timeStart(), InjectionModel< CloudType >::updateMesh(), InjectionModel< CloudType >::volumeToInject(), InjectionModel< CloudType >::volumeTotal(), and InjectionModel< CloudType >::~InjectionModel().
New() [1/2]
Foam::autoPtr< Foam::InjectionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector with lookup from dictionary.
Definition at line 33 of file InjectionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by InjectionModel< CloudType >::clone().
New() [2/2]
Foam::autoPtr< Foam::InjectionModel< CloudType > > New (const dictionary & dict, const word & modelName, const word & modelType, CloudType & owner) static
Selector with name and type.
Definition at line 67 of file InjectionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
updateMesh()
void updateMesh () virtual
Update mesh.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, and PatchInjection< CloudType >.
Definition at line 416 of file InjectionModel.C.
Referenced by InjectionModel< CloudType >::clone().
timeStart()
Foam::scalar timeStart () const inline
Return the start-of-injection time.
Definition at line 31 of file InjectionModelI.H.
Referenced by InjectionModel< CloudType >::averageParcelMass(), and InjectionModel< CloudType >::clone().
volumeTotal()
Foam::scalar volumeTotal () const inline
Return the total volume to be injected across the event.
Definition at line 38 of file InjectionModelI.H.
Referenced by InjectionModel< CloudType >::clone().
massTotal()
Foam::scalar massTotal () const inline
Return mass of particles to introduce.
Definition at line 45 of file InjectionModelI.H.
Referenced by InjectionModel< CloudType >::clone().
massInjected()
Foam::scalar massInjected () const inline
Return mass of particles injected (cumulative)
Definition at line 52 of file InjectionModelI.H.
Referenced by InjectionModel< CloudType >::clone().
timeEnd()
Foam::scalar timeEnd () const virtual
Return the end-of-injection time.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 423 of file InjectionModel.C.
References notImplemented, and InjectionModel< CloudType >::parcelsToInject().
Referenced by InjectionModel< CloudType >::averageParcelMass(), InjectionModel< CloudType >::clone(), and InjectionModel< CloudType >::inject().
parcelsToInject()
Foam::label parcelsToInject (const scalar time0, const scalar time1) virtual
Number of parcels to introduce relative to SOI.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, PatchFlowRateInjection< CloudType >, ManualInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 436 of file InjectionModel.C.
References notImplemented, and InjectionModel< CloudType >::volumeToInject().
Referenced by InjectionModel< CloudType >::averageParcelMass(), InjectionModel< CloudType >::clone(), InjectionModel< CloudType >::injectSteadyState(), and InjectionModel< CloudType >::timeEnd().
volumeToInject()
Foam::scalar volumeToInject (const scalar time0, const scalar time1) virtual
Volume of parcels to introduce relative to SOI.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, PatchFlowRateInjection< CloudType >, ManualInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 456 of file InjectionModel.C.
References notImplemented.
Referenced by InjectionModel< CloudType >::clone(), and InjectionModel< CloudType >::parcelsToInject().
averageParcelMass()
Foam::scalar averageParcelMass () virtual
Return the average parcel mass over the injection period.
Definition at line 475 of file InjectionModel.C.
References InjectionModel< CloudType >::massTotal_, CloudSubModelBase< CloudType >::owner(), InjectionModel< CloudType >::parcelsToInject(), InjectionModel< CloudType >::timeEnd(), and InjectionModel< CloudType >::timeStart().
Referenced by InjectionModel< CloudType >::clone().
nInjections()
Foam::label nInjections () const inline
Return the number of injections.
Definition at line 59 of file InjectionModelI.H.
Referenced by InjectionModel< CloudType >::clone().
parcelsAddedTotal()
Foam::label parcelsAddedTotal () const inline
Return the total number parcels added.
Definition at line 66 of file InjectionModelI.H.
Referenced by InjectionModel< CloudType >::clone().
inject()
void inject (TrackData & td)
Main injection loop.
Definition at line 493 of file InjectionModel.C.
References subModelBase::active(), Foam::meshTools::constrainDirection(), Foam::meshTools::constrainToMeshCentre(), IOobject::db(), InjectionModel< CloudType >::delayedVolume_, InjectionModel< CloudType >::fullyDescribed(), InjectionModel< CloudType >::injectSteadyState(), Foam::max(), mesh, DsmcCloud< ParcelType >::mesh(), Foam::min(), CloudSubModelBase< CloudType >::owner(), Foam::pos(), InjectionModel< CloudType >::postInjectCheck(), InjectionModel< CloudType >::prepareForNextTimeStep(), InjectionModel< CloudType >::setNumberOfParticles(), InjectionModel< CloudType >::setPositionAndCell(), InjectionModel< CloudType >::setProperties(), InjectionModel< CloudType >::SOI_, polyMesh::solutionD(), objectRegistry::time(), InjectionModel< CloudType >::time0_, InjectionModel< CloudType >::timeEnd(), InjectionModel< CloudType >::validInjection(), dimensioned< Type >::value(), and Vector< Cmpt >::zero.
Referenced by InjectionModel< CloudType >::clone().
injectSteadyState()
void injectSteadyState (TrackData & td, const scalar trackTime)
Main injection loop - steady-state.
Definition at line 622 of file InjectionModel.C.
References subModelBase::active(), Foam::meshTools::constrainDirection(), Foam::meshTools::constrainToMeshCentre(), InjectionModel< CloudType >::fullyDescribed(), InjectionModel< CloudType >::massFlowRate_, InjectionModel< CloudType >::massTotal_, mesh, DsmcCloud< ParcelType >::mesh(), CloudSubModelBase< CloudType >::owner(), InjectionModel< CloudType >::parcelsToInject(), Foam::pos(), InjectionModel< CloudType >::postInjectCheck(), InjectionModel< CloudType >::setNumberOfParticles(), InjectionModel< CloudType >::setPositionAndCell(), InjectionModel< CloudType >::setProperties(), polyMesh::solutionD(), objectRegistry::time(), InjectionModel< CloudType >::time0_, TimeDataEntry< Type >::value(), dimensioned< Type >::value(), and Vector< Cmpt >::zero.
Referenced by InjectionModel< CloudType >::clone(), and InjectionModel< CloudType >::inject().
setPositionAndCell()
void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector & position, label & cellOwner, label & tetFaceI, label & tetPtI) virtual
Set the injection position and owner cell, tetFace and tetPt.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, PatchFlowRateInjection< CloudType >, ManualInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 715 of file InjectionModel.C.
References notImplemented, and InjectionModel< CloudType >::setProperties().
Referenced by InjectionModel< CloudType >::clone(), InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::injectSteadyState().
setProperties()
void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType & parcel) virtual
Set the parcel properties.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 743 of file InjectionModel.C.
References notImplemented.
Referenced by InjectionModel< CloudType >::clone(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), and InjectionModel< CloudType >::setPositionAndCell().
fullyDescribed()
bool fullyDescribed () const virtual
Flag to identify whether model fully describes the parcel.
Reimplemented in ConeNozzleInjection< CloudType >, FieldActivatedInjection< CloudType >, InflationInjection< CloudType >, ConeInjection< CloudType >, ReactingMultiphaseLookupTableInjection< CloudType >, ReactingLookupTableInjection< CloudType >, ThermoLookupTableInjection< CloudType >, KinematicLookupTableInjection< CloudType >, CellZoneInjection< CloudType >, ManualInjection< CloudType >, PatchFlowRateInjection< CloudType >, PatchInjection< CloudType >, and NoInjection< CloudType >.
Definition at line 764 of file InjectionModel.C.
References notImplemented.
Referenced by InjectionModel< CloudType >::clone(), InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::injectSteadyState().
info()
void info (Ostream & os) virtual
Write injection info to stream.
Definition at line 776 of file InjectionModel.C.
References InjectionModel< CloudType >::massInjected_, subModelBase::modelName(), InjectionModel< CloudType >::nInjections_, Foam::nl, CloudSubModelBase< CloudType >::outputTime(), InjectionModel< CloudType >::parcelsAddedTotal_, subModelBase::setModelProperty(), and InjectionModel< CloudType >::timeStep0_.
Referenced by InjectionModel< CloudType >::clone().
Member Data Documentation
SOI_
scalar SOI_ protected
Start of injection [s].
Definition at line 96 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::InjectionModel().
volumeTotal_
scalar volumeTotal_ protected
Total volume of particles introduced by this injector [m^3].
scaled to ensure massTotal is achieved
Definition at line 100 of file InjectionModel.H.
massTotal_
scalar massTotal_ protected
Total mass to inject [kg].
Definition at line 103 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::averageParcelMass(), InjectionModel< CloudType >::InjectionModel(), and InjectionModel< CloudType >::injectSteadyState().
massFlowRate_
TimeDataEntry<scalar> massFlowRate_ protected
Mass flow rate profile for steady calculations.
Definition at line 106 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::InjectionModel(), and InjectionModel< CloudType >::injectSteadyState().
massInjected_
scalar massInjected_ protected
Total mass injected to date [kg].
Definition at line 109 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::info().
nInjections_
label nInjections_ protected
Number of injections counter.
Definition at line 115 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::info().
parcelsAddedTotal_
label parcelsAddedTotal_ protected
Running counter of total number of parcels added.
Definition at line 118 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::info().
parcelBasis_
parcelBasis parcelBasis_ protected
Parcel basis enumeration.
Definition at line 124 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::InjectionModel().
nParticleFixed_
scalar nParticleFixed_ protected
nParticle to assign to parcels when the 'fixed' basis
is selected
Definition at line 128 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::InjectionModel().
time0_
scalar time0_ protected
Continuous phase time at start of injection time step [s].
Definition at line 131 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::inject(), and InjectionModel< CloudType >::injectSteadyState().
timeStep0_
scalar timeStep0_ protected
Time at start of injection time step [s].
Definition at line 134 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::info().
delayedVolume_
scalar delayedVolume_ protected
Volume that should have been injected, but would lead to.
less than 1 particle per parcel
Definition at line 138 of file InjectionModel.H.
Referenced by InjectionModel< CloudType >::inject().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModel.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModel.C
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModelI.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModelNew.C