OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GravityForce< CloudType > Class Template Reference
Calculates particle gravity force.
Public Member Functions
TypeName ("gravity")
Runtime type information.
GravityForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
GravityForce (const GravityForce &gf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~GravityForce ()
Destructor.
const vector & g () const
Return the acceleration due to gravity.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::GravityForce< CloudType >
Calculates particle gravity force.
Source files
GravityForce.H
GravityForceI.H
GravityForce.C
Definition at line 52 of file GravityForce.H.
Constructor & Destructor Documentation
GravityForce() [1/2]
GravityForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 32 of file GravityForce.C.
GravityForce() [2/2]
GravityForce (const GravityForce< CloudType > & gf)
Construct copy.
Definition at line 44 of file GravityForce.C.
~GravityForce()
~GravityForce () virtual
Destructor.
Definition at line 54 of file GravityForce.C.
References GravityForce< CloudType >::calcNonCoupled().
Referenced by GravityForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("gravity")
Runtime type information.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 82 of file GravityForce.H.
References GravityForce< CloudType >::calcNonCoupled(), GravityForce< CloudType >::g(), p, Foam::Re(), and GravityForce< CloudType >::~GravityForce().
g()
const Foam::vector & g () const inline
Return the acceleration due to gravity.
Definition at line 29 of file GravityForceI.H.
Referenced by GravityForce< CloudType >::clone().
calcNonCoupled()
Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 62 of file GravityForce.C.
References forceSuSp::Su(), and Vector< Cmpt >::zero.
Referenced by GravityForce< CloudType >::clone(), and GravityForce< CloudType >::~GravityForce().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Gravity/GravityForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Gravity/GravityForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Gravity/GravityForceI.H