OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LiftForce< CloudType > Class Template Reference
Base class for particle lift force models.
Public Member Functions
LiftForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Construct from mesh.
LiftForce (const LiftForce &lf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~LiftForce ()
Destructor.
const interpolation< vector > & curlUcInterp () const
Return the curl of the carrier phase velocity interpolator.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Protected Member Functions
virtual scalar Cl (const typename CloudType::parcelType &p, const vector &curlUc, const scalar Re, const scalar muc) const
Calculate the lift coefficient.
Protected Attributes
const word UName_
Name of velocity field.
autoPtr< interpolation< vector > > curlUcInterpPtr_
Curk of carrier phase velocity interpolator.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::LiftForce< CloudType >
Base class for particle lift force models.
Source files
LiftForce.H
LiftForceI.H
LiftForce.C
Definition at line 52 of file LiftForce.H.
Constructor & Destructor Documentation
LiftForce() [1/2]
LiftForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType)
Construct from mesh.
Definition at line 49 of file LiftForce.C.
LiftForce() [2/2]
LiftForce (const LiftForce< CloudType > & lf)
Construct copy.
Definition at line 63 of file LiftForce.C.
~LiftForce()
~LiftForce () virtual
Destructor.
Definition at line 74 of file LiftForce.C.
Referenced by LiftForce< CloudType >::clone().
Member Function Documentation
Cl()
virtual scalar Cl (const typename CloudType::parcelType & p, const vector & curlUc, const scalar Re, const scalar muc) const protected virtual
Calculate the lift coefficient.
Reimplemented in TomiyamaLiftForce< CloudType >, and SaffmanMeiLiftForce< CloudType >.
Referenced by LiftForce< CloudType >::calcCoupled().
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Reimplemented in TomiyamaLiftForce< CloudType >, and SaffmanMeiLiftForce< CloudType >.
Definition at line 96 of file LiftForce.H.
References LiftForce< CloudType >::cacheFields(), LiftForce< CloudType >::calcCoupled(), LiftForce< CloudType >::curlUcInterp(), p, Foam::Re(), and LiftForce< CloudType >::~LiftForce().
curlUcInterp()
const Foam::interpolation< Foam::vector > & curlUcInterp () const inline
Return the curl of the carrier phase velocity interpolator.
Definition at line 30 of file LiftForceI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by LiftForce< CloudType >::calcCoupled(), and LiftForce< CloudType >::clone().
cacheFields()
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented from ParticleForce< CloudType >.
Definition at line 81 of file LiftForce.C.
References LiftForce< CloudType >::calcCoupled(), Foam::fvc::curl(), LiftForce< CloudType >::curlUcInterpPtr_, ParticleForce< CloudType >::mesh(), ParticleForce< CloudType >::owner(), and LiftForce< CloudType >::UName_.
Referenced by LiftForce< CloudType >::clone().
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 129 of file LiftForce.C.
References LiftForce< CloudType >::Cl(), LiftForce< CloudType >::curlUcInterp(), forceSuSp::Su(), and Vector< Cmpt >::zero.
Referenced by LiftForce< CloudType >::cacheFields(), and LiftForce< CloudType >::clone().
Member Data Documentation
UName_
const word UName_ protected
Name of velocity field.
Definition at line 61 of file LiftForce.H.
Referenced by LiftForce< CloudType >::cacheFields().
curlUcInterpPtr_
autoPtr<interpolation<vector> > curlUcInterpPtr_ protected
Curk of carrier phase velocity interpolator.
Definition at line 64 of file LiftForce.H.
Referenced by LiftForce< CloudType >::cacheFields().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Lift/LiftForce/LiftForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Lift/LiftForce/LiftForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Lift/LiftForce/LiftForceI.H