OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
WenYuDragForce< CloudType > Class Template Reference
Wen-Yu drag model for solid spheres.
Public Member Functions
TypeName ("WenYuDrag")
Runtime type information.
WenYuDragForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
WenYuDragForce (const WenYuDragForce< CloudType > &df)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~WenYuDragForce ()
Destructor.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::WenYuDragForce< CloudType >
Wen-Yu drag model for solid spheres.
Definition at line 47 of file WenYuDragForce.H.
Constructor & Destructor Documentation
WenYuDragForce() [1/2]
WenYuDragForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 49 of file WenYuDragForce.C.
WenYuDragForce() [2/2]
WenYuDragForce (const WenYuDragForce< CloudType > & df)
Construct copy.
Definition at line 68 of file WenYuDragForce.C.
~WenYuDragForce()
~WenYuDragForce () virtual
Destructor.
Definition at line 86 of file WenYuDragForce.C.
References WenYuDragForce< CloudType >::calcCoupled().
Referenced by WenYuDragForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("WenYuDrag")
Runtime type information.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 83 of file WenYuDragForce.H.
References WenYuDragForce< CloudType >::calcCoupled(), p, and WenYuDragForce< CloudType >::~WenYuDragForce().
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 94 of file WenYuDragForce.C.
References Foam::pow(), and sqr().
Referenced by WenYuDragForce< CloudType >::clone(), and WenYuDragForce< CloudType >::~WenYuDragForce().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/WenYuDrag/WenYuDragForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/WenYuDrag/WenYuDragForce.C