OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
TimeScaleModel Class Reference abstract
Base class for time scale models.
Public Member Functions
TypeName ("timeScaleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
TimeScaleModel (const dictionary &dict)
Constructors.
TimeScaleModel (const TimeScaleModel &sm)
Construct a copy.
virtual autoPtr< TimeScaleModel > clone () const =0
Construct and return a clone.
virtual ~TimeScaleModel ()
Destructor.
virtual tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const =0
Member Functions.
Static Public Member Functions
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Selector.
Protected Attributes
scalar alphaPacked_
Close pack volume fraction.
scalar e_
Coefficient of restitution.
Detailed Description
Base class for time scale models.
Source files
TimeScaleModel.H
TimeScaleModel.C
Definition at line 52 of file TimeScaleModel.H.
Constructor & Destructor Documentation
TimeScaleModel() [1/2]
TimeScaleModel (const dictionary & dict)
Constructors.
Construct from components
Definition at line 40 of file TimeScaleModel.C.
TimeScaleModel() [2/2]
TimeScaleModel (const TimeScaleModel & sm)
Construct a copy.
Definition at line 51 of file TimeScaleModel.C.
References TimeScaleModel::New().
~TimeScaleModel()
~TimeScaleModel () virtual
Destructor.
Definition at line 96 of file TimeScaleModel.C.
Member Function Documentation
TypeName()
TypeName ("timeScaleModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , TimeScaleModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime constructor selection table.
clone()
virtual autoPtr<TimeScaleModel> clone () const pure virtual
Construct and return a clone.
Implemented in nonEquilibrium, equilibrium, and isotropic.
New()
Foam::autoPtr< Foam::TimeScaleModel > New (const dictionary & dict) static
Selector.
Definition at line 64 of file TimeScaleModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by TimeScaleModel::TimeScaleModel().
oneByTau()
virtual tmp<FieldField<Field, scalar> > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const pure virtual
Member Functions.
Time scale
Implemented in nonEquilibrium, equilibrium, and isotropic.
Member Data Documentation
alphaPacked_
scalar alphaPacked_ protected
Close pack volume fraction.
Definition at line 67 of file TimeScaleModel.H.
e_
scalar e_ protected
Coefficient of restitution.
Definition at line 70 of file TimeScaleModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/TimeScaleModel/TimeScaleModel.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/TimeScaleModel/TimeScaleModel.C