OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nonEquilibrium Class Reference
Non-Equlibrium model for the time scale over which properties of a dispersed phase tend towards the mean value.
Public Member Functions
TypeName ("nonEquilibrium")
Runtime type information.
nonEquilibrium (const dictionary &dict)
Constructors.
nonEquilibrium (const nonEquilibrium &hc)
Construct a copy.
virtual autoPtr< TimeScaleModel > clone () const
Construct and return a clone.
virtual ~nonEquilibrium ()
Destructor.
tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const
Member Functions.
Public Member Functions inherited from TimeScaleModel
TypeName ("timeScaleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
TimeScaleModel (const dictionary &dict)
Constructors.
TimeScaleModel (const TimeScaleModel &sm)
Construct a copy.
virtual ~TimeScaleModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from TimeScaleModel
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Selector.
Protected Attributes inherited from TimeScaleModel
scalar alphaPacked_
Close pack volume fraction.
scalar e_
Coefficient of restitution.
Detailed Description
Non-Equlibrium model for the time scale over which properties of a dispersed phase tend towards the mean value.
Reference:
    "An improved collision damping time for MP-PIC calculations of dense
    particle flows with applications to polydisperse sedimenting beds and
    colliding particle jets"
    P O'Rourke and D Snider
    Chemical Engineering Science
    Volume 65, Issue 22, Pages 6014-6028, November 2010
Source files
nonEquilibrium.H
nonEquilibrium.C
Definition at line 61 of file nonEquilibrium.H.
Constructor & Destructor Documentation
nonEquilibrium() [1/2]
nonEquilibrium (const dictionary & dict)
Constructors.
Construct from components
Definition at line 50 of file nonEquilibrium.C.
Referenced by nonEquilibrium::clone().
nonEquilibrium() [2/2]
nonEquilibrium (const nonEquilibrium & hc)
Construct a copy.
Definition at line 59 of file nonEquilibrium.C.
~nonEquilibrium()
~nonEquilibrium () virtual
Destructor.
Definition at line 69 of file nonEquilibrium.C.
References nonEquilibrium::oneByTau().
Referenced by nonEquilibrium::clone().
Member Function Documentation
TypeName()
TypeName ("nonEquilibrium")
Runtime type information.
clone()
virtual autoPtr<TimeScaleModel> clone () const inline virtual
Construct and return a clone.
Implements TimeScaleModel.
Definition at line 80 of file nonEquilibrium.H.
References Foam::constant::atomic::alpha, f(), nonEquilibrium::nonEquilibrium(), nonEquilibrium::oneByTau(), and nonEquilibrium::~nonEquilibrium().
oneByTau()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const virtual
Member Functions.
Time scale
Implements TimeScaleModel.
Definition at line 77 of file nonEquilibrium.C.
References Foam::max(), Foam::constant::mathematical::pi(), and Foam::sqrt().
Referenced by nonEquilibrium::clone(), and nonEquilibrium::~nonEquilibrium().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/nonEquilibrium/nonEquilibrium.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/nonEquilibrium/nonEquilibrium.C