OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
isotropic Class Reference
Model for the time scale over which the velocity field of a dispersed phase tends towards an isotropic distribution.
Public Member Functions
TypeName ("isotropic")
Runtime type information.
isotropic (const dictionary &dict)
Constructors.
isotropic (const isotropic &hc)
Construct a copy.
virtual autoPtr< TimeScaleModel > clone () const
Construct and return a clone.
virtual ~isotropic ()
Destructor.
tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const
Member Functions.
Public Member Functions inherited from TimeScaleModel
TypeName ("timeScaleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
TimeScaleModel (const dictionary &dict)
Constructors.
TimeScaleModel (const TimeScaleModel &sm)
Construct a copy.
virtual ~TimeScaleModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from TimeScaleModel
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Selector.
Protected Attributes inherited from TimeScaleModel
scalar alphaPacked_
Close pack volume fraction.
scalar e_
Coefficient of restitution.
Detailed Description
Model for the time scale over which the velocity field of a dispersed phase tends towards an isotropic distribution.
Reference:
    "Inclusion of collisional return-to-isotropy in the MP-PIC method"
    P O'Rourke and D Snider
    Chemical Engineering Science
    Volume 80, Issue 0, Pages 39-54, December 2012
Source files
isotropic.H
isotropic.C
Definition at line 59 of file isotropic.H.
Constructor & Destructor Documentation
isotropic() [1/2]
isotropic (const dictionary & dict)
Constructors.
Construct from components
Definition at line 50 of file isotropic.C.
Referenced by isotropic::clone().
isotropic() [2/2]
isotropic (const isotropic & hc)
Construct a copy.
Definition at line 59 of file isotropic.C.
~isotropic()
~isotropic () virtual
Destructor.
Definition at line 69 of file isotropic.C.
References isotropic::oneByTau().
Referenced by isotropic::clone().
Member Function Documentation
TypeName()
TypeName ("isotropic")
Runtime type information.
clone()
virtual autoPtr<TimeScaleModel> clone () const inline virtual
Construct and return a clone.
Implements TimeScaleModel.
Definition at line 78 of file isotropic.H.
References Foam::constant::atomic::alpha, f(), isotropic::isotropic(), isotropic::oneByTau(), and isotropic::~isotropic().
oneByTau()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const virtual
Member Functions.
Time scale
Implements TimeScaleModel.
Definition at line 77 of file isotropic.C.
References Foam::max(), Foam::constant::mathematical::pi(), and Foam::sqrt().
Referenced by isotropic::clone(), and isotropic::~isotropic().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/isotropic/isotropic.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/isotropic/isotropic.C