OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CorrectionLimitingMethod Class Reference abstract
Base class for correction limiting methods.
Public Member Functions
TypeName ("correctionLimitingMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CorrectionLimitingMethod, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
CorrectionLimitingMethod (const dictionary &dict)
Construct from components.
CorrectionLimitingMethod (const CorrectionLimitingMethod &cl)
Construct as copy.
virtual autoPtr< CorrectionLimitingMethod > clone () const =0
Construct and return a clone.
virtual ~CorrectionLimitingMethod ()
Destructor.
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const =0
Return the limited velocity.
Static Public Member Functions
static autoPtr< CorrectionLimitingMethod > New (const dictionary &dict)
Selector.
Detailed Description
Base class for correction limiting methods.
Source files
CorrectionLimitingMethod.H
CorrectionLimitingMethod.C
Definition at line 50 of file CorrectionLimitingMethod.H.
Constructor & Destructor Documentation
CorrectionLimitingMethod() [1/2]
CorrectionLimitingMethod (const dictionary & dict)
Construct from components.
Definition at line 38 of file CorrectionLimitingMethod.C.
CorrectionLimitingMethod() [2/2]
CorrectionLimitingMethod (const CorrectionLimitingMethod & cl)
Construct as copy.
Definition at line 45 of file CorrectionLimitingMethod.C.
References CorrectionLimitingMethod::New().
~CorrectionLimitingMethod()
~CorrectionLimitingMethod () virtual
Destructor.
Definition at line 87 of file CorrectionLimitingMethod.C.
Member Function Documentation
TypeName()
TypeName ("correctionLimitingMethod")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , CorrectionLimitingMethod , dictionary , (const dictionary &dict) , (dict))
Declare runtime constructor selection table.
clone()
virtual autoPtr<CorrectionLimitingMethod> clone () const pure virtual
Construct and return a clone.
Implemented in absolute, relative, and noCorrectionLimiting.
New()
Foam::autoPtr< Foam::CorrectionLimitingMethod > New (const dictionary & dict) static
Selector.
Definition at line 55 of file CorrectionLimitingMethod.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by CorrectionLimitingMethod::CorrectionLimitingMethod().
limitedVelocity()
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const pure virtual
Return the limited velocity.
Implemented in absolute, relative, and noCorrectionLimiting.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/CorrectionLimitingMethod/CorrectionLimitingMethod.H
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/CorrectionLimitingMethod/CorrectionLimitingMethod.C