OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
exponential Class Reference
Exponential inter-particle stress model of the same form as used in twoPhaseEulerFoam.
Public Member Functions
TypeName ("exponential")
Runtime type information.
exponential (const dictionary &dict)
Constructors.
exponential (const exponential &hc)
Construct copy.
virtual autoPtr< ParticleStressModel > clone () const
Clone.
virtual ~exponential ()
Destructor.
tmp< Field< scalar > > tau (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const
Member Functions.
tmp< Field< scalar > > dTaudTheta (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const
Collision stress derivaive w.r.t. the volume fraction.
Public Member Functions inherited from ParticleStressModel
TypeName ("particleStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleStressModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
ParticleStressModel (const dictionary &dict)
Constructors.
ParticleStressModel (const ParticleStressModel &sm)
Construct a copy.
virtual ~ParticleStressModel ()
Destructor.
scalar alphaPacked () const
Member Functions.
tmp< FieldField< Field, scalar > > tau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &rho, const FieldField< Field, scalar > &uRms) const
Collision stress using FieldFields.
Additional Inherited Members
Static Public Member Functions inherited from ParticleStressModel
static autoPtr< ParticleStressModel > New (const dictionary &dict)
Selector.
Protected Attributes inherited from ParticleStressModel
scalar alphaPacked_
Close pack volume fraction.
Detailed Description
Exponential inter-particle stress model of the same form as used in twoPhaseEulerFoam.
Source files
exponential.H
exponential.C
Definition at line 51 of file exponential.H.
Constructor & Destructor Documentation
exponential() [1/2]
exponential (const dictionary & dict)
Constructors.
Construct from components
Definition at line 50 of file exponential.C.
Referenced by exponential::clone().
exponential() [2/2]
exponential (const exponential & hc)
Construct copy.
Definition at line 62 of file exponential.C.
~exponential()
~exponential () virtual
Destructor.
Definition at line 75 of file exponential.C.
References exponential::tau().
Referenced by exponential::clone().
Member Function Documentation
TypeName()
TypeName ("exponential")
Runtime type information.
clone()
virtual autoPtr<ParticleStressModel> clone () const inline virtual
Clone.
Implements ParticleStressModel.
Definition at line 82 of file exponential.H.
References Foam::constant::atomic::alpha, exponential::dTaudTheta(), exponential::exponential(), rho, exponential::tau(), and exponential::~exponential().
tau()
Foam::tmp< Foam::Field< Foam::scalar > > tau (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const virtual
Member Functions.
Collision stress
Implements ParticleStressModel.
Definition at line 83 of file exponential.C.
References exponential::dTaudTheta().
Referenced by exponential::clone(), and exponential::~exponential().
dTaudTheta()
Foam::tmp< Foam::Field< Foam::scalar > > dTaudTheta (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const virtual
Collision stress derivaive w.r.t. the volume fraction.
Implements ParticleStressModel.
Definition at line 95 of file exponential.C.
References Foam::exp(), and Foam::min().
Referenced by exponential::clone(), and exponential::tau().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/exponential/exponential.H
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/exponential/exponential.C