OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ParticleStressModel Class Reference abstract
Base class for inter-particle stress models.
Public Member Functions
TypeName ("particleStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleStressModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
ParticleStressModel (const dictionary &dict)
Constructors.
ParticleStressModel (const ParticleStressModel &sm)
Construct a copy.
virtual autoPtr< ParticleStressModel > clone () const =0
Construct and return a clone.
virtual ~ParticleStressModel ()
Destructor.
scalar alphaPacked () const
Member Functions.
virtual tmp< Field< scalar > > tau (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const =0
Collision stress.
virtual tmp< Field< scalar > > dTaudTheta (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const =0
Collision stress derivaive w.r.t. the volume fraction.
tmp< FieldField< Field, scalar > > tau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &rho, const FieldField< Field, scalar > &uRms) const
Collision stress using FieldFields.
Static Public Member Functions
static autoPtr< ParticleStressModel > New (const dictionary &dict)
Selector.
Protected Attributes
scalar alphaPacked_
Close pack volume fraction.
Detailed Description
Base class for inter-particle stress models.
Source files
ParticleStressModel.H
exponential.C
Definition at line 51 of file ParticleStressModel.H.
Constructor & Destructor Documentation
ParticleStressModel() [1/2]
ParticleStressModel (const dictionary & dict)
Constructors.
Construct from components
Definition at line 40 of file ParticleStressModel.C.
ParticleStressModel() [2/2]
ParticleStressModel (const ParticleStressModel & sm)
Construct a copy.
Definition at line 50 of file ParticleStressModel.C.
References ParticleStressModel::New().
~ParticleStressModel()
~ParticleStressModel () virtual
Destructor.
Definition at line 94 of file ParticleStressModel.C.
Member Function Documentation
TypeName()
TypeName ("particleStressModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , ParticleStressModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime constructor selection table.
clone()
virtual autoPtr<ParticleStressModel> clone () const pure virtual
Construct and return a clone.
Implemented in HarrisCrighton, Lun, and exponential.
New()
Foam::autoPtr< Foam::ParticleStressModel > New (const dictionary & dict) static
Selector.
Definition at line 62 of file ParticleStressModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by ParticleStressModel::ParticleStressModel().
alphaPacked()
Foam::scalar alphaPacked () const
Member Functions.
Access max volume fraction
Definition at line 100 of file ParticleStressModel.C.
References ParticleStressModel::tau().
tau() [1/2]
virtual tmp<Field<scalar> > tau (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const pure virtual
Collision stress.
Implemented in HarrisCrighton, Lun, and exponential.
Referenced by ParticleStressModel::alphaPacked().
dTaudTheta()
virtual tmp<Field<scalar> > dTaudTheta (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const pure virtual
Collision stress derivaive w.r.t. the volume fraction.
Implemented in HarrisCrighton, Lun, and exponential.
tau() [2/2]
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > tau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & rho, const FieldField< Field, scalar > & uRms) const
Collision stress using FieldFields.
Definition at line 108 of file ParticleStressModel.C.
References forAll, and PtrList< Field< Type > >::size().
Member Data Documentation
alphaPacked_
scalar alphaPacked_ protected
Close pack volume fraction.
Definition at line 66 of file ParticleStressModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/ParticleStressModel/ParticleStressModel.H
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/ParticleStressModel/ParticleStressModel.C