OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
relative Class Reference
Correction limiting method based on the relative particle velocity.
Public Member Functions
TypeName ("relative")
Runtime type information.
relative (const dictionary &dict)
Construct from components.
relative (const relative &cl)
Construct as copy.
virtual autoPtr< CorrectionLimitingMethod > clone () const
Construct and return a clone.
virtual ~relative ()
Destructor.
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const
Return the limited velocity.
Public Member Functions inherited from CorrectionLimitingMethod
TypeName ("correctionLimitingMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CorrectionLimitingMethod, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
CorrectionLimitingMethod (const dictionary &dict)
Construct from components.
CorrectionLimitingMethod (const CorrectionLimitingMethod &cl)
Construct as copy.
virtual ~CorrectionLimitingMethod ()
Destructor.
Protected Attributes
scalar e_
Coefficient of restitution.
Additional Inherited Members
Static Public Member Functions inherited from CorrectionLimitingMethod
static autoPtr< CorrectionLimitingMethod > New (const dictionary &dict)
Selector.
Detailed Description
Correction limiting method based on the relative particle velocity.
This method limits the velocity correction to that of a rebound with a coefficient of restitution . The relative velocity of the particle with respect to the mean value is used to calculate the direction and magnitude of the limited velocity.
Source files
relative.H
relative.C
Definition at line 55 of file relative.H.
Constructor & Destructor Documentation
relative() [1/2]
relative (const dictionary & dict)
Construct from components.
Definition at line 46 of file relative.C.
Referenced by relative::clone().
relative() [2/2]
relative (const relative & cl)
Construct as copy.
Definition at line 53 of file relative.C.
~relative()
~relative () virtual
Destructor.
Definition at line 62 of file relative.C.
References relative::limitedVelocity().
Referenced by relative::clone().
Member Function Documentation
TypeName()
TypeName ("relative")
Runtime type information.
clone()
virtual autoPtr<CorrectionLimitingMethod> clone () const inline virtual
Construct and return a clone.
Implements CorrectionLimitingMethod.
Definition at line 82 of file relative.H.
References relative::limitedVelocity(), relative::relative(), and relative::~relative().
limitedVelocity()
Foam::vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const virtual
Return the limited velocity.
Implements CorrectionLimitingMethod.
Definition at line 69 of file relative.C.
References relative::e_, and Foam::minMod().
Referenced by relative::clone(), and relative::~relative().
Member Data Documentation
e_
scalar e_ protected
Coefficient of restitution.
Definition at line 64 of file relative.H.
Referenced by relative::limitedVelocity().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/relative/relative.H
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/relative/relative.C