OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NoDamping< CloudType > Class Template Reference
Public Member Functions
TypeName ("none")
Runtime type information.
NoDamping (const dictionary &dict, CloudType &owner)
Construct from components.
NoDamping (const NoDamping< CloudType > &cm)
Construct copy.
virtual autoPtr< DampingModel< CloudType > > clone () const
Construct and return a clone.
virtual ~NoDamping ()
Destructor.
virtual vector velocityCorrection (typename CloudType::parcelType &p, const scalar deltaT) const
Member Functions.
virtual bool active () const
Return the model 'active' status.
Public Member Functions inherited from DampingModel< CloudType >
TypeName ("dampingModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DampingModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
DampingModel (CloudType &owner)
Construct null from owner.
DampingModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
DampingModel (const DampingModel< CloudType > &cm)
Construct copy.
virtual ~DampingModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from DampingModel< CloudType >
static autoPtr< DampingModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from DampingModel< CloudType >
autoPtr< TimeScaleModel > timeScaleModel_
Time scale model.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::DampingModels::NoDamping< CloudType >
Source files
NoDamping.H
NoDamping.C
Definition at line 50 of file NoDamping.H.
Constructor & Destructor Documentation
NoDamping() [1/2]
NoDamping (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 32 of file NoDamping.C.
NoDamping() [2/2]
NoDamping (const NoDamping< CloudType > & cm)
Construct copy.
Definition at line 43 of file NoDamping.C.
~NoDamping()
~NoDamping () virtual
Destructor.
Definition at line 54 of file NoDamping.C.
References NoDamping< CloudType >::velocityCorrection().
Referenced by NoDamping< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
clone()
virtual autoPtr<DampingModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements DampingModel< CloudType >.
Definition at line 68 of file NoDamping.H.
References NoDamping< CloudType >::active(), p, NoDamping< CloudType >::velocityCorrection(), and NoDamping< CloudType >::~NoDamping().
velocityCorrection()
Foam::vector velocityCorrection (typename CloudType::parcelType & p, const scalar deltaT) const virtual
Member Functions.
Calculate the velocity correction
Implements DampingModel< CloudType >.
Definition at line 61 of file NoDamping.C.
Referenced by NoDamping< CloudType >::clone(), and NoDamping< CloudType >::~NoDamping().
active()
bool active () const virtual
Return the model 'active' status.
Reimplemented from subModelBase.
Definition at line 71 of file NoDamping.C.
Referenced by NoDamping< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/DampingModels/NoDamping/NoDamping.H
src/lagrangian/intermediate/submodels/MPPIC/DampingModels/NoDamping/NoDamping.C