OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
HarrisCrighton Class Reference
Inter-particle stress model of Harris and Crighton.
Public Member Functions
TypeName ("HarrisCrighton")
Runtime type information.
HarrisCrighton (const dictionary &dict)
Constructors.
HarrisCrighton (const HarrisCrighton &hc)
Construct copy.
virtual autoPtr< ParticleStressModel > clone () const
Clone.
virtual ~HarrisCrighton ()
Destructor.
tmp< Field< scalar > > tau (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const
Member Functions.
tmp< Field< scalar > > dTaudTheta (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const
Collision stress derivaive w.r.t. the volume fraction.
Public Member Functions inherited from ParticleStressModel
TypeName ("particleStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleStressModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
ParticleStressModel (const dictionary &dict)
Constructors.
ParticleStressModel (const ParticleStressModel &sm)
Construct a copy.
virtual ~ParticleStressModel ()
Destructor.
scalar alphaPacked () const
Member Functions.
tmp< FieldField< Field, scalar > > tau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &rho, const FieldField< Field, scalar > &uRms) const
Collision stress using FieldFields.
Additional Inherited Members
Static Public Member Functions inherited from ParticleStressModel
static autoPtr< ParticleStressModel > New (const dictionary &dict)
Selector.
Protected Attributes inherited from ParticleStressModel
scalar alphaPacked_
Close pack volume fraction.
Detailed Description
Inter-particle stress model of Harris and Crighton.
The stress value takes the following form:
Here, is the volume fraction of the dispersed phase, and the other values are modelling constants. A small value is used to limit the denominator to ensure numerical stability.
Reference:
    "Solitons, solitary waves, and voidage disturbances in gas-fluidized
    beds"
    S Harris and D Crighton,
    Journal of Fluid Mechanics
    Volume 266, Pages 243-276, 1994
Source files
HarrisCrighton.H
HarrisCrighton.C
Definition at line 68 of file HarrisCrighton.H.
Constructor & Destructor Documentation
HarrisCrighton() [1/2]
HarrisCrighton (const dictionary & dict)
Constructors.
Construct from components
Definition at line 50 of file HarrisCrighton.C.
Referenced by HarrisCrighton::clone().
HarrisCrighton() [2/2]
HarrisCrighton (const HarrisCrighton & hc)
Construct copy.
Definition at line 62 of file HarrisCrighton.C.
~HarrisCrighton()
~HarrisCrighton () virtual
Destructor.
Definition at line 75 of file HarrisCrighton.C.
References Foam::constant::atomic::alpha, Foam::max(), and HarrisCrighton::tau().
Referenced by HarrisCrighton::clone().
Member Function Documentation
TypeName()
TypeName ("HarrisCrighton")
Runtime type information.
clone()
virtual autoPtr<ParticleStressModel> clone () const inline virtual
Clone.
Implements ParticleStressModel.
Definition at line 105 of file HarrisCrighton.H.
References HarrisCrighton::dTaudTheta(), HarrisCrighton::HarrisCrighton(), rho, HarrisCrighton::tau(), and HarrisCrighton::~HarrisCrighton().
tau()
Foam::tmp< Foam::Field< Foam::scalar > > tau (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const virtual
Member Functions.
Collision stress
Implements ParticleStressModel.
Definition at line 100 of file HarrisCrighton.C.
References HarrisCrighton::dTaudTheta(), and Foam::pow().
Referenced by HarrisCrighton::clone(), and HarrisCrighton::~HarrisCrighton().
dTaudTheta()
Foam::tmp< Foam::Field< Foam::scalar > > dTaudTheta (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const virtual
Collision stress derivaive w.r.t. the volume fraction.
Implements ParticleStressModel.
Definition at line 117 of file HarrisCrighton.C.
References d(), and Foam::pow().
Referenced by HarrisCrighton::clone(), and HarrisCrighton::tau().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/HarrisCrighton/HarrisCrighton.H
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/HarrisCrighton/HarrisCrighton.C