OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Lun Class Reference
Inter-particle stress model of Lun et al.
Public Member Functions
TypeName ("Lun")
Runtime type information.
Lun (const dictionary &dict)
Constructors.
Lun (const Lun &hc)
Construct copy.
virtual autoPtr< ParticleStressModel > clone () const
Clone.
virtual ~Lun ()
Destructor.
tmp< Field< scalar > > tau (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const
Member Functions.
tmp< Field< scalar > > dTaudTheta (const Field< scalar > &alpha, const Field< scalar > &rho, const Field< scalar > &uRms) const
Collision stress derivaive w.r.t. the volume fraction.
Public Member Functions inherited from ParticleStressModel
TypeName ("particleStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleStressModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
ParticleStressModel (const dictionary &dict)
Constructors.
ParticleStressModel (const ParticleStressModel &sm)
Construct a copy.
virtual ~ParticleStressModel ()
Destructor.
scalar alphaPacked () const
Member Functions.
tmp< FieldField< Field, scalar > > tau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &rho, const FieldField< Field, scalar > &uRms) const
Collision stress using FieldFields.
Additional Inherited Members
Static Public Member Functions inherited from ParticleStressModel
static autoPtr< ParticleStressModel > New (const dictionary &dict)
Selector.
Protected Attributes inherited from ParticleStressModel
scalar alphaPacked_
Close pack volume fraction.
Detailed Description
Inter-particle stress model of Lun et al.
The stress value takes the following form:
Here, is the volume fraction of the dispersed phase, is the density of the dispersed phase, is a coefficient of restitution, and is the RMS velocity fluctuation.
Reference:
    "Kinetic theories for granular flow: inelastic particles in Couette
    flow and slightly inelastic particles in a general flowfield"
    C Lun, S Savage, G Jeffrey, N Chepurniy
    Journal of Fluid Mechanics
    Volume 140, Pages 223-256, 1984
Source files
Lun.H
Lun.C
Definition at line 69 of file Lun.H.
Constructor & Destructor Documentation
Lun() [1/2]
Lun (const dictionary & dict)
Constructors.
Construct from components
Definition at line 50 of file Lun.C.
Referenced by Lun::clone().
Lun() [2/2]
Lun (const Lun & hc)
Construct copy.
Definition at line 61 of file Lun.C.
~Lun()
~Lun () virtual
Destructor.
Definition at line 73 of file Lun.C.
References Lun::tau().
Referenced by Lun::clone().
Member Function Documentation
TypeName()
TypeName ("Lun")
Runtime type information.
clone()
virtual autoPtr<ParticleStressModel> clone () const inline virtual
Clone.
Implements ParticleStressModel.
Definition at line 97 of file Lun.H.
References Foam::constant::atomic::alpha, Lun::dTaudTheta(), Lun::Lun(), rho, Lun::tau(), and Lun::~Lun().
tau()
Foam::tmp< Foam::Field< Foam::scalar > > tau (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const virtual
Member Functions.
Collision stress
Implements ParticleStressModel.
Definition at line 81 of file Lun.C.
References Lun::dTaudTheta(), Foam::max(), and Foam::pow().
Referenced by Lun::clone(), and Lun::~Lun().
dTaudTheta()
Foam::tmp< Foam::Field< Foam::scalar > > dTaudTheta (const Field< scalar > & alpha, const Field< scalar > & rho, const Field< scalar > & uRms) const virtual
Collision stress derivaive w.r.t. the volume fraction.
Implements ParticleStressModel.
Definition at line 105 of file Lun.C.
References notImplemented.
Referenced by Lun::clone(), and Lun::tau().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/Lun/Lun.H
src/lagrangian/intermediate/submodels/MPPIC/ParticleStressModels/Lun/Lun.C