OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
absolute Class Reference
Correction limiting method based on the absolute particle velocity.
Public Member Functions
TypeName ("absolute")
Runtime type information.
absolute (const dictionary &dict)
Construct from components.
absolute (const absolute &cl)
Construct as copy.
virtual autoPtr< CorrectionLimitingMethod > clone () const
Construct and return a clone.
virtual ~absolute ()
Destructor.
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const
Return the limited velocity.
Public Member Functions inherited from CorrectionLimitingMethod
TypeName ("correctionLimitingMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CorrectionLimitingMethod, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
CorrectionLimitingMethod (const dictionary &dict)
Construct from components.
CorrectionLimitingMethod (const CorrectionLimitingMethod &cl)
Construct as copy.
virtual ~CorrectionLimitingMethod ()
Destructor.
Protected Attributes
scalar e_
Coefficient of restitution.
Additional Inherited Members
Static Public Member Functions inherited from CorrectionLimitingMethod
static autoPtr< CorrectionLimitingMethod > New (const dictionary &dict)
Selector.
Detailed Description
Correction limiting method based on the absolute particle velocity.
This method that limits the velocity correction to that of a rebound with a coefficient of restitution . The absolute velocity of the particle is used when calculating the magnitude of the limited correction. The direction is calculated using the relative velocity.
Source files
absolute.H
absolute.C
Definition at line 55 of file absolute.H.
Constructor & Destructor Documentation
absolute() [1/2]
absolute (const dictionary & dict)
Construct from components.
Definition at line 46 of file absolute.C.
Referenced by absolute::clone().
absolute() [2/2]
absolute (const absolute & cl)
Construct as copy.
Definition at line 53 of file absolute.C.
~absolute()
~absolute () virtual
Destructor.
Definition at line 62 of file absolute.C.
References absolute::limitedVelocity().
Referenced by absolute::clone().
Member Function Documentation
TypeName()
TypeName ("absolute")
Runtime type information.
clone()
virtual autoPtr<CorrectionLimitingMethod> clone () const inline virtual
Construct and return a clone.
Implements CorrectionLimitingMethod.
Definition at line 82 of file absolute.H.
References absolute::absolute(), absolute::limitedVelocity(), and absolute::~absolute().
limitedVelocity()
Foam::vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const virtual
Return the limited velocity.
Implements CorrectionLimitingMethod.
Definition at line 69 of file absolute.C.
References absolute::e_, Foam::mag(), Foam::max(), and Foam::minMod().
Referenced by absolute::clone(), and absolute::~absolute().
Member Data Documentation
e_
scalar e_ protected
Coefficient of restitution.
Definition at line 64 of file absolute.H.
Referenced by absolute::limitedVelocity().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/absolute/absolute.H
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/absolute/absolute.C