OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
molecule::constantProperties Class Reference
Class to hold molecule constant properties.
Public Member Functions
constantProperties ()
constantProperties (const dictionary &dict)
Construct from dictionary.
const Field< vector > & siteReferencePositions () const
const List< scalar > & siteMasses () const
const List< scalar > & siteCharges () const
const List< label > & siteIds () const
List< label > & siteIds ()
const List< bool > & pairPotentialSites () const
bool pairPotentialSite (label sId) const
const List< bool > & electrostaticSites () const
bool electrostaticSite (label sId) const
const diagTensor & momentOfInertia () const
bool linearMolecule () const
bool pointMolecule () const
label degreesOfFreedom () const
scalar mass () const
label nSites () const
Detailed Description
Class to hold molecule constant properties.
Definition at line 76 of file molecule.H.
Constructor & Destructor Documentation
constantProperties() [1/2]
constantProperties () inline
Definition at line 28 of file moleculeI.H.
constantProperties() [2/2]
constantProperties (const dictionary & dict) inline
Construct from dictionary.
Definition at line 42 of file moleculeI.H.
References Foam::abort(), Foam::e, Foam::eigenValues(), Foam::eigenVectors(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, Foam::Info, dictionary::lookup(), Foam::mag(), molecule::molecule(), dictionaryName::name(), Foam::nl, p, Foam::rotationTensor(), List< T >::size(), Foam::sum(), Vector< Cmpt >::x(), Tensor< Cmpt >::x(), Tensor< Cmpt >::xx(), Vector< Cmpt >::y(), Tensor< Cmpt >::y(), DiagTensor< Cmpt >::yy(), Tensor< Cmpt >::yy(), Vector< Cmpt >::z(), Tensor< Cmpt >::z(), DiagTensor< scalar >::zero, Vector< Cmpt >::zero, Tensor< scalar >::zero, DiagTensor< Cmpt >::zz(), and Tensor< Cmpt >::zz().
Member Function Documentation
siteReferencePositions()
const Foam::Field< Foam::vector > & siteReferencePositions () const inline
Definition at line 331 of file moleculeI.H.
Referenced by molecule::setSitePositions().
siteMasses()
const Foam::List< Foam::scalar > & siteMasses () const inline
Definition at line 338 of file moleculeI.H.
siteCharges()
const Foam::List< Foam::scalar > & siteCharges () const inline
Definition at line 345 of file moleculeI.H.
siteIds() [1/2]
const Foam::List< Foam::label > & siteIds () const inline
Definition at line 352 of file moleculeI.H.
Referenced by molecule::molecule(), and moleculeCloud::writeXYZ().
siteIds() [2/2]
Foam::List< Foam::label > & siteIds () inline
Definition at line 359 of file moleculeI.H.
pairPotentialSites()
const Foam::List< bool > & pairPotentialSites () const inline
Definition at line 366 of file moleculeI.H.
References molecule::constantProperties::pairPotentialSite().
pairPotentialSite()
bool pairPotentialSite (label sId) const inline
Definition at line 373 of file moleculeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), Foam::nl, and s().
Referenced by molecule::constantProperties::pairPotentialSites().
electrostaticSites()
const Foam::List< bool > & electrostaticSites () const inline
Definition at line 391 of file moleculeI.H.
References molecule::constantProperties::electrostaticSite().
electrostaticSite()
bool electrostaticSite (label sId) const inline
Definition at line 398 of file moleculeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), Foam::nl, and s().
Referenced by molecule::constantProperties::electrostaticSites().
momentOfInertia()
const Foam::diagTensor & momentOfInertia () const inline
Definition at line 418 of file moleculeI.H.
linearMolecule()
bool linearMolecule () const inline
Definition at line 424 of file moleculeI.H.
References DiagTensor< Cmpt >::xx(), and DiagTensor< Cmpt >::yy().
Referenced by molecule::constantProperties::degreesOfFreedom().
pointMolecule()
bool pointMolecule () const inline
Definition at line 430 of file moleculeI.H.
References DiagTensor< Cmpt >::zz().
Referenced by molecule::constantProperties::degreesOfFreedom().
degreesOfFreedom()
Foam::label degreesOfFreedom () const inline
Definition at line 436 of file moleculeI.H.
References molecule::constantProperties::linearMolecule(), and molecule::constantProperties::pointMolecule().
mass()
Foam::scalar mass () const inline
Definition at line 453 of file moleculeI.H.
nSites()
Foam::label nSites () const inline
Definition at line 459 of file moleculeI.H.
References List< T >::size().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/molecule/molecule.H
src/lagrangian/molecularDynamics/molecule/molecule/moleculeI.H