OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ThermoSurfaceFilm< CloudType > Class Template Reference
Thermo parcel surface film model.
Public Types
enum interactionType { itAbsorb, itBounce, itSplashBai }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
interactionType interactionTypeEnum (const word &it) const
word interactionTypeStr (const interactionType &it) const
TypeName ("thermoSurfaceFilm")
Runtime type information.
ThermoSurfaceFilm (const dictionary &dict, CloudType &owner)
Construct from components.
ThermoSurfaceFilm (const ThermoSurfaceFilm< CloudType > &sfm)
Construct copy.
virtual autoPtr< SurfaceFilmModel< CloudType > > clone ()
Construct and return a clone using supplied owner cloud.
virtual ~ThermoSurfaceFilm ()
Destructor.
virtual bool transferParcel (parcelType &p, const polyPatch &pp, bool &keepParticle)
Transfer parcel from cloud to surface film.
virtual void info (Ostream &os)
Write surface film info to stream.
Public Member Functions inherited from SurfaceFilmModel< CloudType >
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, SurfaceFilmModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
SurfaceFilmModel (CloudType &owner)
Construct null from owner.
SurfaceFilmModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
SurfaceFilmModel (const SurfaceFilmModel< CloudType > &sfm)
Construct copy.
virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const
Construct and return a clone.
virtual ~SurfaceFilmModel ()
Destructor.
const dimensionedVector & g () const
Return gravitational acceleration constant.
label nParcelsTransferred () const
Return const access to the number of parcels transferred to the.
label & nParcelsTransferred ()
Return non-const access to the number of parcels transferred to.
label nParcelsInjected () const
Return const access to the number of parcels injected from the.
label & nParcelsInjected ()
Return non-const access to the number of parcels injected from.
template<class TrackData >
void inject (TrackData &td)
Inject parcels into the cloud.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Attributes
static wordList interactionTypeNames_
Word descriptions of interaction type names.
Protected Types
typedef CloudType::parcelType parcelType
Convenience typedef to the cloud's parcel type.
Protected Types inherited from SurfaceFilmModel< CloudType >
typedef CloudType::parcelType parcelType
Convenience typedef to the cloud's parcel type.
Protected Member Functions
vector tangentVector (const vector &v) const
Return a vector tangential to input vector, v.
vector splashDirection (const vector &tanVec1, const vector &tanVec2, const vector &nf) const
Return splashed parcel direction.
void absorbInteraction (regionModels::surfaceFilmModels::surfaceFilmModel &filmModel, const parcelType &p, const polyPatch &pp, const label faceI, const scalar mass, bool &keepParticle)
Absorb parcel into film.
void bounceInteraction (parcelType &p, const polyPatch &pp, const label faceI, bool &keepParticle) const
Bounce parcel (flip parcel normal velocity)
void drySplashInteraction (regionModels::surfaceFilmModels::surfaceFilmModel &filmModel, const parcelType &p, const polyPatch &pp, const label faceI, bool &keepParticle)
Parcel interaction with dry surface.
void wetSplashInteraction (regionModels::surfaceFilmModels::surfaceFilmModel &filmModel, parcelType &p, const polyPatch &pp, const label faceI, bool &keepParticle)
Parcel interaction with wetted surface.
void splashInteraction (regionModels::surfaceFilmModels::surfaceFilmModel &filmModel, const parcelType &p, const polyPatch &pp, const label faceI, const scalar mRatio, const scalar We, const scalar Wec, const scalar sigma, bool &keepParticle)
Bai parcel splash interaction model.
virtual void cacheFilmFields (const label filmPatchI, const label primaryPatchI, const regionModels::surfaceFilmModels::surfaceFilmModel &filmModel)
Cache the film fields in preparation for injection.
virtual void setParcelProperties (parcelType &p, const label filmFaceI) const
Set the individual parcel properties.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
cachedRandom & rndGen_
Reference to the cloud random number generator.
const SLGThermo & thermo_
Reference to the cloud thermo package.
scalarList TFilmPatch_
Film temperature / patch face.
scalarList CpFilmPatch_
Film specific heat capacity / patch face.
interactionType interactionType_
Interaction type enumeration.
scalar deltaWet_
Film thickness beyond which patch is assumed to be wet.
label splashParcelType_
Splash parcel type label - id assigned to identify parcel for.
label parcelsPerSplash_
Number of new parcels resulting from splash event.
scalar Adry_
Dry surface roughness coefficient.
scalar Awet_
Wet surface roughness coefficient.
scalar Cf_
Skin friction typically in the range 0.6 < Cf < 0.8.
label nParcelsSplashed_
Counter for number of new splash parcels.
Protected Attributes inherited from SurfaceFilmModel< CloudType >
const dimensionedVector & g_
Gravitational acceleration constant.
label ejectedParcelType_
Ejected parcel type label - id assigned to identify parcel for.
scalarList massParcelPatch_
Parcel mass / patch face.
scalarList diameterParcelPatch_
Parcel diameter / patch face.
List< vector > UFilmPatch_
Film velocity / patch face.
scalarList rhoFilmPatch_
Film density / patch face.
scalarListList deltaFilmPatch_
Film height of all film patches / patch face.
label nParcelsTransferred_
Number of parcels transferred to the film model.
label nParcelsInjected_
Number of parcels injected from the film model.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from SurfaceFilmModel< CloudType >
static autoPtr< SurfaceFilmModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::ThermoSurfaceFilm< CloudType >
Thermo parcel surface film model.
Responsible for:
injecting parcelss from the film model into the cloud, e.g. for dripping
parcel interaction with the film, e.g absorb, bounce, splash
Splash model references:
Bai and Gosman, `Mathematical modelling of wall films formed by impinging sprays', SAE 960626, 1996
Bai et al, `Modelling off gasoline spray impingement', Atom. Sprays, vol 12, pp 1-27, 2002
Source files
ThermoSurfaceFilm.H
ThermoSurfaceFilm.C
ThermoSurfaceFilmI.H
Definition at line 63 of file ThermoSurfaceFilm.H.
Member Typedef Documentation
parcelType
typedef CloudType::parcelType parcelType protected
Convenience typedef to the cloud's parcel type.
Definition at line 97 of file ThermoSurfaceFilm.H.
Member Enumeration Documentation
interactionType
enum interactionType
Enumerator
itAbsorb
itBounce
itSplashBai
Definition at line 72 of file ThermoSurfaceFilm.H.
Constructor & Destructor Documentation
ThermoSurfaceFilm() [1/2]
ThermoSurfaceFilm (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 490 of file ThermoSurfaceFilm.C.
References Foam::endl(), and Foam::Info.
Referenced by ThermoSurfaceFilm< CloudType >::splashInteraction().
ThermoSurfaceFilm() [2/2]
ThermoSurfaceFilm (const ThermoSurfaceFilm< CloudType > & sfm)
Construct copy.
Definition at line 534 of file ThermoSurfaceFilm.C.
~ThermoSurfaceFilm()
~ThermoSurfaceFilm () virtual
Destructor.
Definition at line 557 of file ThermoSurfaceFilm.C.
References ThermoSurfaceFilm< CloudType >::transferParcel().
Referenced by ThermoSurfaceFilm< CloudType >::clone().
Member Function Documentation
interactionTypeEnum()
Foam::ThermoSurfaceFilm< CloudType >::interactionType interactionTypeEnum (const word & it) const
Definition at line 49 of file ThermoSurfaceFilm.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, and ThermoSurfaceFilm< CloudType >::interactionTypeStr().
interactionTypeStr()
Foam::word interactionTypeStr (const interactionType & it) const
Definition at line 76 of file ThermoSurfaceFilm.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and ThermoSurfaceFilm< CloudType >::tangentVector().
Referenced by ThermoSurfaceFilm< CloudType >::interactionTypeEnum().
tangentVector()
Foam::vector tangentVector (const vector & v) const protected
Return a vector tangential to input vector, v.
Definition at line 98 of file ThermoSurfaceFilm.C.
References Foam::mag(), ThermoSurfaceFilm< CloudType >::splashDirection(), and Vector< Cmpt >::zero.
Referenced by ThermoSurfaceFilm< CloudType >::interactionTypeStr().
splashDirection()
Foam::vector splashDirection (const vector & tanVec1, const vector & tanVec2, const vector & nf) const protected
Return splashed parcel direction.
Definition at line 118 of file ThermoSurfaceFilm.C.
References ThermoSurfaceFilm< CloudType >::absorbInteraction(), Foam::constant::atomic::alpha, Foam::cos(), Foam::mag(), Foam::constant::mathematical::pi(), Foam::sin(), and Foam::constant::mathematical::twoPi().
Referenced by ThermoSurfaceFilm< CloudType >::tangentVector().
absorbInteraction()
void absorbInteraction (regionModels::surfaceFilmModels::surfaceFilmModel & filmModel, const parcelType & p, const polyPatch & pp, const label faceI, const scalar mass, bool & keepParticle) protected
Absorb parcel into film.
Definition at line 143 of file ThermoSurfaceFilm.C.
References surfaceFilmModel::addSources(), ThermoSurfaceFilm< CloudType >::bounceInteraction(), Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), patchIdentifier::index(), Foam::Info, Foam::mag(), and Urel.
Referenced by ThermoSurfaceFilm< CloudType >::splashDirection().
bounceInteraction()
void bounceInteraction (parcelType & p, const polyPatch & pp, const label faceI, bool & keepParticle) const protected
Bounce parcel (flip parcel normal velocity)
Definition at line 190 of file ThermoSurfaceFilm.C.
References ThermoSurfaceFilm< CloudType >::drySplashInteraction(), Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), patchIdentifier::index(), Foam::Info, and Urel.
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction().
drySplashInteraction()
void drySplashInteraction (regionModels::surfaceFilmModels::surfaceFilmModel & filmModel, const parcelType & p, const polyPatch & pp, const label faceI, bool & keepParticle) protected
Parcel interaction with dry surface.
Definition at line 220 of file ThermoSurfaceFilm.C.
References d(), Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), patchIdentifier::index(), Foam::Info, Foam::magSqr(), Foam::constant::physicoChemical::mu, liquidProperties::mu(), Foam::pow(), rho, Foam::constant::physicoChemical::sigma, liquidProperties::sigma(), Foam::sqr(), Urel, and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
Referenced by ThermoSurfaceFilm< CloudType >::bounceInteraction().
wetSplashInteraction()
void wetSplashInteraction (regionModels::surfaceFilmModels::surfaceFilmModel & filmModel, parcelType & p, const polyPatch & pp, const label faceI, bool & keepParticle) protected
Parcel interaction with wetted surface.
Definition at line 276 of file ThermoSurfaceFilm.C.
References Foam::acos(), d(), Foam::endl(), epsilon, PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), patchIdentifier::index(), Foam::Info, Foam::mag(), Foam::magSqr(), Foam::constant::physicoChemical::mu, liquidProperties::mu(), Foam::constant::mathematical::pi(), Foam::pow(), rho, Foam::constant::physicoChemical::sigma, liquidProperties::sigma(), ThermoSurfaceFilm< CloudType >::splashInteraction(), Foam::sqr(), U, and Urel.
Referenced by ThermoSurfaceFilm< CloudType >::drySplashInteraction().
splashInteraction()
void splashInteraction (regionModels::surfaceFilmModels::surfaceFilmModel & filmModel, const parcelType & p, const polyPatch & pp, const label faceI, const scalar mRatio, const scalar We, const scalar Wec, const scalar sigma, bool & keepParticle) protected
Bai parcel splash interaction model.
Definition at line 353 of file ThermoSurfaceFilm.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), Foam::cbrt(), fvMesh::Cf(), Foam::meshTools::constrainDirection(), d(), Foam::exp(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), forAll, patchIdentifier::index(), Foam::log(), Foam::mag(), Foam::magSqr(), Foam::max(), mesh, UPstream::myProcNo(), Foam::constant::mathematical::pi(), Foam::pow3(), polyMesh::solutionD(), Foam::sqr(), Foam::sqrt(), ThermoSurfaceFilm< CloudType >::ThermoSurfaceFilm(), Urel, and y.
Referenced by ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
cacheFilmFields()
void cacheFilmFields (const label filmPatchI, const label primaryPatchI, const regionModels::surfaceFilmModels::surfaceFilmModel & filmModel) protected virtual
Cache the film fields in preparation for injection.
Reimplemented from SurfaceFilmModel< CloudType >.
Definition at line 644 of file ThermoSurfaceFilm.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), SurfaceFilmModel< CloudType >::cacheFilmFields(), surfaceFilmModel::Cp(), ThermoSurfaceFilm< CloudType >::setParcelProperties(), regionModel::toPrimary(), and surfaceFilmModel::Ts().
Referenced by ThermoSurfaceFilm< CloudType >::transferParcel().
setParcelProperties()
void setParcelProperties (parcelType & p, const label filmFaceI) const protected virtual
Set the individual parcel properties.
Reimplemented from SurfaceFilmModel< CloudType >.
Definition at line 667 of file ThermoSurfaceFilm.C.
References SurfaceFilmModel< CloudType >::setParcelProperties().
Referenced by ThermoSurfaceFilm< CloudType >::cacheFilmFields().
TypeName()
TypeName ("thermoSurfaceFilm")
Runtime type information.
clone()
virtual autoPtr<SurfaceFilmModel<CloudType> > clone () inline virtual
Construct and return a clone using supplied owner cloud.
Definition at line 256 of file ThermoSurfaceFilm.H.
References ThermoSurfaceFilm< CloudType >::info(), p, ThermoSurfaceFilm< CloudType >::transferParcel(), and ThermoSurfaceFilm< CloudType >::~ThermoSurfaceFilm().
transferParcel()
bool transferParcel (parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Transfer parcel from cloud to surface film.
Returns true if parcel is to be transferred
Reimplemented from SurfaceFilmModel< CloudType >.
Definition at line 565 of file ThermoSurfaceFilm.C.
References Foam::abort(), ThermoSurfaceFilm< CloudType >::cacheFilmFields(), Foam::FatalError, FatalErrorIn, patchIdentifier::index(), regionModel::isRegionPatch(), and polyPatch::whichFace().
Referenced by ThermoSurfaceFilm< CloudType >::clone(), and ThermoSurfaceFilm< CloudType >::~ThermoSurfaceFilm().
info()
void info (Ostream & os) virtual
Write surface film info to stream.
Reimplemented from SurfaceFilmModel< CloudType >.
Definition at line 681 of file ThermoSurfaceFilm.C.
References Foam::endl(), SurfaceFilmModel< CloudType >::info(), and Foam::returnReduce().
Referenced by ThermoSurfaceFilm< CloudType >::clone().
Member Data Documentation
interactionTypeNames_
Foam::wordList interactionTypeNames_ static
Word descriptions of interaction type names.
Definition at line 80 of file ThermoSurfaceFilm.H.
rndGen_
cachedRandom& rndGen_ protected
Reference to the cloud random number generator.
Definition at line 100 of file ThermoSurfaceFilm.H.
thermo_
const SLGThermo& thermo_ protected
Reference to the cloud thermo package.
Definition at line 103 of file ThermoSurfaceFilm.H.
TFilmPatch_
scalarList TFilmPatch_ protected
Film temperature / patch face.
Definition at line 109 of file ThermoSurfaceFilm.H.
CpFilmPatch_
scalarList CpFilmPatch_ protected
Film specific heat capacity / patch face.
Definition at line 112 of file ThermoSurfaceFilm.H.
interactionType_
interactionType interactionType_ protected
Interaction type enumeration.
Definition at line 118 of file ThermoSurfaceFilm.H.
deltaWet_
scalar deltaWet_ protected
Film thickness beyond which patch is assumed to be wet.
Definition at line 121 of file ThermoSurfaceFilm.H.
splashParcelType_
label splashParcelType_ protected
Splash parcel type label - id assigned to identify parcel for.
post-processing. If not specified, defaults to originating cloud type
Definition at line 126 of file ThermoSurfaceFilm.H.
parcelsPerSplash_
label parcelsPerSplash_ protected
Number of new parcels resulting from splash event.
Definition at line 129 of file ThermoSurfaceFilm.H.
Adry_
scalar Adry_ protected
Dry surface roughness coefficient.
= 2630 for dry interaction (ref. Bai)
Definition at line 137 of file ThermoSurfaceFilm.H.
Awet_
scalar Awet_ protected
Wet surface roughness coefficient.
= 1320 for wet interaction (ref. Bai)
Definition at line 141 of file ThermoSurfaceFilm.H.
Cf_
scalar Cf_ protected
Skin friction typically in the range 0.6 < Cf < 0.8.
Definition at line 145 of file ThermoSurfaceFilm.H.
nParcelsSplashed_
label nParcelsSplashed_ protected
Counter for number of new splash parcels.
Definition at line 148 of file ThermoSurfaceFilm.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Thermodynamic/SurfaceFilmModel/ThermoSurfaceFilm/ThermoSurfaceFilm.H
src/lagrangian/intermediate/submodels/Thermodynamic/SurfaceFilmModel/ThermoSurfaceFilm/ThermoSurfaceFilm.C