OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NoPhaseChange< CloudType > Class Template Reference
Dummy phase change model for 'none'.
Public Member Functions
TypeName ("none")
Runtime type information.
NoPhaseChange (const dictionary &, CloudType &)
Construct from dictionary.
NoPhaseChange (const NoPhaseChange< CloudType > &pcm)
Construct copy.
virtual autoPtr< PhaseChangeModel< CloudType > > clone () const
Construct and return a clone.
virtual ~NoPhaseChange ()
Destructor.
virtual bool active () const
Flag to indicate whether model activates phase change model.
virtual void calculate (const scalar dt, const label cellI, const scalar Re, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, scalarField &dMassPC) const
Update model.
Public Member Functions inherited from PhaseChangeModel< CloudType >
TypeName ("phaseChangeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PhaseChangeModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PhaseChangeModel (CloudType &owner)
Construct null from owner.
PhaseChangeModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
PhaseChangeModel (const PhaseChangeModel< CloudType > &pcm)
Construct copy.
virtual ~PhaseChangeModel ()
Destructor.
const enthalpyTransferType & enthalpyTransfer () const
Return the enthalpy transfer type enumeration.
virtual void calculate (const scalar dt, const label cellI, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField &Yl, scalarField &dMassPC) const
Update model.
virtual scalar dh (const label idc, const label idl, const scalar p, const scalar T) const
Return the enthalpy per unit mass.
virtual scalar Tvap (const scalarField &Y) const
Return vapourisation temperature.
virtual scalar TMax (const scalar p, const scalarField &Y) const
Return maximum/limiting temperature.
void addToPhaseChangeMass (const scalar dMass)
Add to phase change mass.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from PhaseChangeModel< CloudType >
enum enthalpyTransferType { etLatentHeat, etEnthalpyDifference }
Enthalpy transfer type.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from PhaseChangeModel< CloudType >
static autoPtr< PhaseChangeModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Static Public Attributes inherited from PhaseChangeModel< CloudType >
static const Foam::wordList enthalpyTransferTypeNames
Name representations of enthalpy transfer types.
Protected Member Functions inherited from PhaseChangeModel< CloudType >
enthalpyTransferType wordToEnthalpyTransfer (const word &etName) const
Convert word to enthalpy transfer type.
scalar Sh () const
Sherwood number.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from PhaseChangeModel< CloudType >
enthalpyTransferType enthalpyTransfer_
Enthalpy transfer type enumeration.
scalar dMass_
Mass of lagrangian phase converted.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::NoPhaseChange< CloudType >
Dummy phase change model for 'none'.
Definition at line 45 of file NoPhaseChange.H.
Constructor & Destructor Documentation
NoPhaseChange() [1/2]
NoPhaseChange (const dictionary & , CloudType & owner)
Construct from dictionary.
Definition at line 32 of file NoPhaseChange.C.
NoPhaseChange() [2/2]
NoPhaseChange (const NoPhaseChange< CloudType > & pcm)
Construct copy.
Definition at line 43 of file NoPhaseChange.C.
~NoPhaseChange()
~NoPhaseChange () virtual
Destructor.
Definition at line 54 of file NoPhaseChange.C.
Referenced by NoPhaseChange< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
clone()
virtual autoPtr<PhaseChangeModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 64 of file NoPhaseChange.H.
References NoPhaseChange< CloudType >::active(), NoPhaseChange< CloudType >::calculate(), d(), nu, Foam::Re(), Foam::T(), and NoPhaseChange< CloudType >::~NoPhaseChange().
active()
bool active () const virtual
Flag to indicate whether model activates phase change model.
Reimplemented from subModelBase.
Definition at line 61 of file NoPhaseChange.C.
References NoPhaseChange< CloudType >::calculate().
Referenced by NoPhaseChange< CloudType >::clone().
calculate()
void calculate (const scalar dt, const label cellI, const scalar Re, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, scalarField & dMassPC) const virtual
Update model.
Definition at line 69 of file NoPhaseChange.C.
Referenced by NoPhaseChange< CloudType >::active(), and NoPhaseChange< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/NoPhaseChange/NoPhaseChange.H
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/NoPhaseChange/NoPhaseChange.C