OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reactingMultiphaseParcelInjectionData Class Reference
Container class to provide injection data for reacting multiphase parcels.
Public Member Functions
TypeName ("reactingMultiphaseParcelInjectionData")
Runtime type information.
reactingMultiphaseParcelInjectionData ()
Null constructor.
reactingMultiphaseParcelInjectionData (const dictionary &dict)
Construct from dictionary.
reactingMultiphaseParcelInjectionData (Istream &is)
Construct from Istream.
virtual ~reactingMultiphaseParcelInjectionData ()
Destructor.
const scalarList & YGas () const
Return const access to the list of gaseous mass fractions.
const scalarList & YLiquid () const
Return const access to the list of liquid mass fractions.
const scalarList & YSolid () const
Return const access to the list of solid mass fractions.
scalarList & YGas ()
Return access to the gaseous mass fractions.
scalarList & YLiquid ()
Return access to the liquid mass fractions.
scalarList & YSolid ()
Return access to the solid mass fractions.
Public Member Functions inherited from reactingParcelInjectionData
TypeName ("reactingParcelInjectionData")
Runtime type information.
reactingParcelInjectionData ()
Null constructor.
reactingParcelInjectionData (const dictionary &dict)
Construct from dictionary.
reactingParcelInjectionData (Istream &is)
Construct from Istream.
virtual ~reactingParcelInjectionData ()
Destructor.
const scalarList & Y () const
Return const access to the list of mass fractions.
scalarList & Y ()
Return access to the mass fractions.
Public Member Functions inherited from thermoParcelInjectionData
TypeName ("thermoParcelInjectionData")
Runtime type information.
thermoParcelInjectionData ()
Null constructor.
thermoParcelInjectionData (const dictionary &dict)
Construct from dictionary.
thermoParcelInjectionData (Istream &is)
Construct from Istream.
virtual ~thermoParcelInjectionData ()
Destructor.
scalar T () const
Return const access to the temperature.
scalar Cp () const
Return const access to the specific heat capacity.
scalar & T ()
Return access to the temperature.
scalar & Cp ()
Return access to the specific heat capacity.
Public Member Functions inherited from kinematicParcelInjectionData
TypeName ("kinematicParcelInjectionData")
Runtime type information.
kinematicParcelInjectionData ()
Null constructor.
kinematicParcelInjectionData (const dictionary &dict)
Construct from dictionary.
kinematicParcelInjectionData (Istream &is)
Construct from Istream.
virtual ~kinematicParcelInjectionData ()
Destructor.
const point & x () const
Return const access to the position.
const vector & U () const
Return const access to the velocity.
scalar d () const
Return const access to the diameter.
scalar rho () const
Return const access to the density.
scalar mDot () const
Return const access to the mass flow rate.
point & x ()
Return access to the position.
vector & U ()
Return access to the velocity.
scalar & d ()
Return access to the diameter.
scalar & rho ()
Return access to the density.
scalar & mDot ()
Return access to the mass flow rate.
Protected Attributes
scalarList YGas_
List of gaseous mass fractions.
scalarList YLiquid_
List of liquid mass fractions.
scalarList YSolid_
List of solid mass fractions.
Protected Attributes inherited from reactingParcelInjectionData
scalarList Y_
List of mass fractions.
Protected Attributes inherited from thermoParcelInjectionData
scalar T_
Temperature [K].
scalar Cp_
Specific heat capacity [J/kg/K].
Protected Attributes inherited from kinematicParcelInjectionData
point x_
Position [m].
vector U_
Velocity [m/s].
scalar d_
Diameter [m].
scalar rho_
Density [kg/m3].
scalar mDot_
Mass flow rate [kg/s].
Friends
bool operator== (const reactingMultiphaseParcelInjectionData &a, const reactingMultiphaseParcelInjectionData &b)
bool operator!= (const reactingMultiphaseParcelInjectionData &a, const reactingMultiphaseParcelInjectionData &b)
Ostream & operator<< (Ostream &os, const reactingMultiphaseParcelInjectionData &data)
Ostream operator.
Istream & operator>> (Istream &is, reactingMultiphaseParcelInjectionData &data)
Istream operator.
Detailed Description
Container class to provide injection data for reacting multiphase parcels.
Source files
reactingMultiphaseParcelInjectionData.H
reactingMultiphaseParcelInjectionData.C
Definition at line 65 of file reactingMultiphaseParcelInjectionData.H.
Constructor & Destructor Documentation
reactingMultiphaseParcelInjectionData() [1/3]
reactingMultiphaseParcelInjectionData ()
Null constructor.
Definition at line 38 of file reactingMultiphaseParcelInjectionData.C.
reactingMultiphaseParcelInjectionData() [2/3]
reactingMultiphaseParcelInjectionData (const dictionary & dict)
Construct from dictionary.
Definition at line 49 of file reactingMultiphaseParcelInjectionData.C.
References reactingMultiphaseParcelInjectionData::~reactingMultiphaseParcelInjectionData().
reactingMultiphaseParcelInjectionData() [3/3]
reactingMultiphaseParcelInjectionData (Istream & is)
Construct from Istream.
Definition at line 31 of file reactingMultiphaseParcelInjectionDataIO.C.
References IOstream::check(), reactingMultiphaseParcelInjectionData::YGas_, reactingMultiphaseParcelInjectionData::YLiquid_, and reactingMultiphaseParcelInjectionData::YSolid_.
~reactingMultiphaseParcelInjectionData()
~reactingMultiphaseParcelInjectionData () virtual
Destructor.
Definition at line 62 of file reactingMultiphaseParcelInjectionData.C.
Referenced by reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData().
Member Function Documentation
TypeName()
TypeName ("reactingMultiphaseParcelInjectionData")
Runtime type information.
YGas() [1/2]
const Foam::scalarList & YGas () const inline
Return const access to the list of gaseous mass fractions.
Definition at line 31 of file reactingMultiphaseParcelInjectionDataI.H.
References reactingMultiphaseParcelInjectionData::YGas_.
YLiquid() [1/2]
const Foam::scalarList & YLiquid () const inline
Return const access to the list of liquid mass fractions.
Definition at line 38 of file reactingMultiphaseParcelInjectionDataI.H.
References reactingMultiphaseParcelInjectionData::YLiquid_.
YSolid() [1/2]
const Foam::scalarList & YSolid () const inline
Return const access to the list of solid mass fractions.
Definition at line 45 of file reactingMultiphaseParcelInjectionDataI.H.
References reactingMultiphaseParcelInjectionData::YSolid_.
YGas() [2/2]
Foam::scalarList & YGas () inline
Return access to the gaseous mass fractions.
Definition at line 51 of file reactingMultiphaseParcelInjectionDataI.H.
References reactingMultiphaseParcelInjectionData::YGas_.
YLiquid() [2/2]
Foam::scalarList & YLiquid () inline
Return access to the liquid mass fractions.
Definition at line 57 of file reactingMultiphaseParcelInjectionDataI.H.
References reactingMultiphaseParcelInjectionData::YLiquid_.
YSolid() [2/2]
Foam::scalarList & YSolid () inline
Return access to the solid mass fractions.
Definition at line 63 of file reactingMultiphaseParcelInjectionDataI.H.
References reactingMultiphaseParcelInjectionData::YSolid_.
Friends And Related Function Documentation
operator==
bool operator== (const reactingMultiphaseParcelInjectionData & a, const reactingMultiphaseParcelInjectionData & b) friend
Definition at line 133 of file reactingMultiphaseParcelInjectionData.H.
operator!=
bool operator!= (const reactingMultiphaseParcelInjectionData & a, const reactingMultiphaseParcelInjectionData & b) friend
Definition at line 151 of file reactingMultiphaseParcelInjectionData.H.
operator<<
Ostream& operator<< (Ostream & os, const reactingMultiphaseParcelInjectionData & data) friend
Ostream operator.
operator>>
Istream& operator>> (Istream & is, reactingMultiphaseParcelInjectionData & data) friend
Istream operator.
Member Data Documentation
YGas_
scalarList YGas_ protected
List of gaseous mass fractions.
Definition at line 74 of file reactingMultiphaseParcelInjectionData.H.
Referenced by reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData(), and reactingMultiphaseParcelInjectionData::YGas().
YLiquid_
scalarList YLiquid_ protected
List of liquid mass fractions.
Definition at line 77 of file reactingMultiphaseParcelInjectionData.H.
Referenced by reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData(), and reactingMultiphaseParcelInjectionData::YLiquid().
YSolid_
scalarList YSolid_ protected
List of solid mass fractions.
Definition at line 80 of file reactingMultiphaseParcelInjectionData.H.
Referenced by reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData(), and reactingMultiphaseParcelInjectionData::YSolid().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/ReactingMultiphase/InjectionModel/ReactingMultiphaseLookupTableInjection/reactingMultiphaseParcelInjectionData.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/InjectionModel/ReactingMultiphaseLookupTableInjection/reactingMultiphaseParcelInjectionData.C
src/lagrangian/intermediate/submodels/ReactingMultiphase/InjectionModel/ReactingMultiphaseLookupTableInjection/reactingMultiphaseParcelInjectionDataI.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/InjectionModel/ReactingMultiphaseLookupTableInjection/reactingMultiphaseParcelInjectionDataIO.C