OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NoHeatTransfer< CloudType > Class Template Reference
Dummy heat transfer model for 'none'.
Public Member Functions
TypeName ("none")
Runtime type information.
NoHeatTransfer (const dictionary &, CloudType &owner)
Construct from dictionary.
NoHeatTransfer (const NoHeatTransfer< CloudType > &im)
Construct copy.
virtual autoPtr< HeatTransferModel< CloudType > > clone () const
Construct and return a clone.
virtual ~NoHeatTransfer ()
Destructor.
virtual bool active () const
Flag to indicate whether model activates heat transfer model.
virtual scalar Nu (const scalar, const scalar) const
Nusselt number.
virtual scalar Pr () const
Prandtl number.
Public Member Functions inherited from HeatTransferModel< CloudType >
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, HeatTransferModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
HeatTransferModel (CloudType &owner)
Construct null from owner.
HeatTransferModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
HeatTransferModel (const HeatTransferModel< CloudType > &htm)
Construct copy.
virtual ~HeatTransferModel ()
Destructor.
const Switch & BirdCorrection () const
Return the Bird htc correction flag.
virtual scalar htc (const scalar dp, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW) const
Return heat transfer coefficient.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from HeatTransferModel< CloudType >
static autoPtr< HeatTransferModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::NoHeatTransfer< CloudType >
Dummy heat transfer model for 'none'.
Definition at line 46 of file NoHeatTransfer.H.
Constructor & Destructor Documentation
NoHeatTransfer() [1/2]
NoHeatTransfer (const dictionary & , CloudType & owner)
Construct from dictionary.
Definition at line 32 of file NoHeatTransfer.C.
NoHeatTransfer() [2/2]
NoHeatTransfer (const NoHeatTransfer< CloudType > & im)
Construct copy.
Definition at line 43 of file NoHeatTransfer.C.
~NoHeatTransfer()
~NoHeatTransfer () virtual
Destructor.
Definition at line 54 of file NoHeatTransfer.C.
Referenced by NoHeatTransfer< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
clone()
virtual autoPtr<HeatTransferModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from HeatTransferModel< CloudType >.
Definition at line 65 of file NoHeatTransfer.H.
References NoHeatTransfer< CloudType >::active(), NoHeatTransfer< CloudType >::Nu(), NoHeatTransfer< CloudType >::Pr(), and NoHeatTransfer< CloudType >::~NoHeatTransfer().
active()
bool active () const virtual
Flag to indicate whether model activates heat transfer model.
Reimplemented from subModelBase.
Definition at line 61 of file NoHeatTransfer.C.
References NoHeatTransfer< CloudType >::Nu().
Referenced by NoHeatTransfer< CloudType >::clone().
Nu()
Foam::scalar Nu (const scalar , const scalar) const virtual
Nusselt number.
Reimplemented from HeatTransferModel< CloudType >.
Definition at line 69 of file NoHeatTransfer.C.
Referenced by NoHeatTransfer< CloudType >::active(), and NoHeatTransfer< CloudType >::clone().
Pr()
Foam::scalar Pr () const virtual
Prandtl number.
Definition at line 79 of file NoHeatTransfer.C.
Referenced by NoHeatTransfer< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/NoHeatTransfer/NoHeatTransfer.H
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/NoHeatTransfer/NoHeatTransfer.C