OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
molecule Class Reference
Foam::molecule.
Classes
class constantProperties
Class to hold molecule constant properties.
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToFace function.
Public Types
enum specialTypes { SPECIAL_TETHERED = -1, SPECIAL_FROZEN = -2, NOT_SPECIAL = 0, SPECIAL_USER = 1 }
Public Member Functions
molecule (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const tensor &Q, const vector &v, const vector &a, const vector &pi, const vector &tau, const vector &specialPosition, const constantProperties &constProps, const label special, const label id)
Construct from components.
molecule (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
autoPtr< particle > clone () const
Construct and return a clone.
bool move (trackingData &, const scalar trackTime)
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
void setSitePositions (const constantProperties &constProps)
void setSiteSizes (label size)
const tensor & Q () const
tensor & Q ()
const vector & v () const
vector & v ()
const vector & a () const
vector & a ()
const vector & pi () const
vector & pi ()
const vector & tau () const
vector & tau ()
const List< vector > & siteForces () const
List< vector > & siteForces ()
const List< vector > & sitePositions () const
List< vector > & sitePositions ()
const vector & specialPosition () const
vector & specialPosition ()
scalar potentialEnergy () const
scalar & potentialEnergy ()
const tensor & rf () const
tensor & rf ()
label special () const
bool tethered () const
label id () const
bool hitPatch (const polyPatch &, trackingData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
void hitProcessorPatch (const processorPolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a processorPatch.
void hitWallPatch (const wallPolyPatch &, trackingData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
void hitPatch (const polyPatch &, trackingData &td)
Overridable function to handle the particle hitting a polyPatch.
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label cellI, bool doCellFacePt=true)
Construct from components, tetFaceI_ and tetPtI_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFaceI_ for the.
vector oldNormal () const
Return the normal of the tri on tetFaceI_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label faceI) const
Is this global face an internal face?
bool boundaryFace (const label faceI) const
Is this global face a boundary face?
label patch (const label faceI) const
Which patch is particle on.
label patchFace (const label patchI, const label faceI) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchI, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchI, TrackData &td)
Convert processor patch addressing to the global equivalents.
void write (Ostream &os, bool writeFields) const
Write the particle data.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Public Member Functions inherited from DLListBase::link
link ()
Null construct.
bool registered () const
Check if the link is registered with the DLListBase.
void deregister ()
Deregister the link after removal.
Static Public Member Functions
static void readFields (Cloud< molecule > &mC)
static void writeFields (const Cloud< molecule > &mC)
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Friends
class Cloud< molecule >
Ostream & operator<< (Ostream &, const molecule &)
Additional Inherited Members
Public Attributes inherited from DLListBase::link
link * prev_
Pointer to next entry in list.
link * next_
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions inherited from particle< Type >
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &cellI, label &tetFaceI, label &tetPtI, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes inherited from particle< Type >
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label cellI_
Index of the cell it is in.
label faceI_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFaceI_
Index of the face that owns the decomposed tet that the.
label tetPtI_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Detailed Description
Foam::molecule.
Source files
molecule.H
moleculeI.H
molecule.C
moleculeIO.C
Definition at line 56 of file molecule.H.
Member Enumeration Documentation
specialTypes
enum specialTypes
Enumerator
SPECIAL_TETHERED
SPECIAL_FROZEN
NOT_SPECIAL
SPECIAL_USER
Definition at line 67 of file molecule.H.
Constructor & Destructor Documentation
molecule() [1/2]
molecule (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const tensor & Q, const vector & v, const vector & a, const vector & pi, const vector & tau, const vector & specialPosition, const constantProperties & constProps, const label special, const label id) inline
Construct from components.
Definition at line 221 of file moleculeI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), forAll, molecule::id(), Foam::mag(), Foam::nl, molecule::setSitePositions(), List< T >::setSize(), molecule::constantProperties::siteIds(), and List< T >::size().
Referenced by molecule::clone(), molecule::constantProperties::constantProperties(), and molecule::iNew::operator()().
molecule() [2/2]
molecule (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 33 of file moleculeIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), and readScalar.
Member Function Documentation
clone()
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from particle< Type >.
Definition at line 252 of file molecule.H.
References particle< Type >::mesh_, and molecule::molecule().
move()
bool move (molecule::trackingData & td, const scalar trackTime)
Definition at line 68 of file molecule.C.
References Foam::abort(), particle< Type >::TrackingData< CloudType >::cloud(), moleculeCloud::constProps(), f(), Foam::FatalError, FatalErrorIn, forAll, particle< Type >::TrackingData< CloudType >::keepParticle, Foam::min(), Foam::nl, molecule::trackingData::part(), particle< Type >::position(), R, s(), molecule::setSitePositions(), particle< Type >::stepFraction(), particle< Type >::TrackingData< CloudType >::switchProcessor, Tensor< Cmpt >::T(), particle< Type >::trackToFace(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::zero.
Referenced by molecule::iNew::operator()().
transformProperties() [1/2]
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Reimplemented from particle< Type >.
Definition at line 192 of file molecule.C.
References particle< Type >::position_, Foam::transform(), and particle< Type >::transformProperties().
Referenced by molecule::iNew::operator()().
transformProperties() [2/2]
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Reimplemented from particle< Type >.
Definition at line 214 of file molecule.C.
References molecule::SPECIAL_TETHERED, and particle< Type >::transformProperties().
setSitePositions()
void setSitePositions (const constantProperties & constProps)
Definition at line 227 of file molecule.C.
References particle< Type >::position_, and molecule::constantProperties::siteReferencePositions().
Referenced by molecule::molecule(), molecule::move(), and molecule::iNew::operator()().
setSiteSizes()
void setSiteSizes (label size)
Definition at line 233 of file molecule.C.
References molecule::hitPatch(), and List< T >::setSize().
Referenced by molecule::iNew::operator()().
Q() [1/2]
const Foam::tensor & Q () const inline
Definition at line 468 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
Q() [2/2]
Foam::tensor & Q () inline
Definition at line 474 of file moleculeI.H.
v() [1/2]
const Foam::vector & v () const inline
Definition at line 480 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
v() [2/2]
Foam::vector & v () inline
Definition at line 486 of file moleculeI.H.
a() [1/2]
const Foam::vector & a () const inline
Definition at line 492 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
a() [2/2]
Foam::vector & a () inline
Definition at line 498 of file moleculeI.H.
pi() [1/2]
const Foam::vector & pi () const inline
Definition at line 504 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
pi() [2/2]
Foam::vector & pi () inline
Definition at line 510 of file moleculeI.H.
tau() [1/2]
const Foam::vector & tau () const inline
Definition at line 516 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
tau() [2/2]
Foam::vector & tau () inline
Definition at line 522 of file moleculeI.H.
siteForces() [1/2]
const Foam::List< Foam::vector > & siteForces () const inline
Definition at line 528 of file moleculeI.H.
Referenced by molecule::iNew::operator()().
siteForces() [2/2]
Foam::List< Foam::vector > & siteForces () inline
Definition at line 534 of file moleculeI.H.
sitePositions() [1/2]
const Foam::List< Foam::vector > & sitePositions () const inline
Definition at line 540 of file moleculeI.H.
Referenced by molecule::iNew::operator()().
sitePositions() [2/2]
Foam::List< Foam::vector > & sitePositions () inline
Definition at line 546 of file moleculeI.H.
specialPosition() [1/2]
const Foam::vector & specialPosition () const inline
Definition at line 552 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
specialPosition() [2/2]
Foam::vector & specialPosition () inline
Definition at line 558 of file moleculeI.H.
potentialEnergy() [1/2]
Foam::scalar potentialEnergy () const inline
Definition at line 564 of file moleculeI.H.
Referenced by molecule::iNew::operator()().
potentialEnergy() [2/2]
Foam::scalar & potentialEnergy () inline
Definition at line 570 of file moleculeI.H.
rf() [1/2]
const Foam::tensor & rf () const inline
Definition at line 576 of file moleculeI.H.
Referenced by molecule::iNew::operator()().
rf() [2/2]
Foam::tensor & rf () inline
Definition at line 582 of file moleculeI.H.
special()
Foam::label special () const inline
Definition at line 588 of file moleculeI.H.
Referenced by molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
tethered()
bool tethered () const inline
Definition at line 594 of file moleculeI.H.
References molecule::SPECIAL_TETHERED.
Referenced by molecule::iNew::operator()().
id()
Foam::label id () const inline
Definition at line 600 of file moleculeI.H.
Referenced by molecule::molecule(), molecule::iNew::operator()(), molecule::readFields(), and molecule::writeFields().
hitPatch() [1/2]
bool hitPatch (const polyPatch & , trackingData & td, const label patchI, const scalar trackFraction, const tetIndices & tetIs)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 242 of file molecule.C.
References molecule::hitProcessorPatch().
Referenced by molecule::hitWallPatch(), molecule::iNew::operator()(), and molecule::setSiteSizes().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a processorPatch.
Definition at line 255 of file molecule.C.
References molecule::hitWallPatch(), and particle< Type >::TrackingData< CloudType >::switchProcessor.
Referenced by molecule::hitPatch(), and molecule::iNew::operator()().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & wpp, trackingData & td, const tetIndices & tetIs)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 265 of file molecule.C.
References molecule::hitPatch(), Foam::mag(), particle< Type >::normal(), and nw.
Referenced by molecule::hitProcessorPatch(), and molecule::iNew::operator()().
hitPatch() [2/2]
void hitPatch (const polyPatch & , trackingData & td)
Overridable function to handle the particle hitting a polyPatch.
Definition at line 287 of file molecule.C.
References particle< Type >::TrackingData< CloudType >::keepParticle.
readFields()
void readFields (Cloud< molecule > & mC) static
Definition at line 100 of file moleculeIO.C.
References molecule::a(), Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAllIter, molecule::id(), IOobject::MUST_READ, molecule::pi(), molecule::Q(), particle< Type >::readFields(), Cloud< ParticleType >::size(), molecule::special(), molecule::specialPosition(), molecule::tau(), and molecule::v().
Referenced by moleculeCloud::moleculeCloud(), and molecule::iNew::operator()().
writeFields()
void writeFields (const Cloud< molecule > & mC) static
Definition at line 154 of file moleculeIO.C.
References molecule::a(), IOstream::ASCII, IOstream::check(), Foam::endl(), particle< Type >::face(), Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), IOstream::format(), molecule::id(), Foam::Info, moleculeCloud::mesh(), IOobject::name(), IOobject::NO_READ, Foam::operator<<(), molecule::pi(), cloud::prefix, molecule::Q(), Cloud< ParticleType >::size(), token::SPACE, molecule::special(), molecule::specialPosition(), particle< Type >::stepFraction(), molecule::tau(), objectRegistry::time(), Time::timePath(), molecule::v(), Ostream::write(), Q::write(), particle< Type >::writeFields(), and moleculeCloud::writeXYZ().
Referenced by molecule::iNew::operator()().
Friends And Related Function Documentation
Cloud< molecule >
friend class Cloud< molecule > friend
Definition at line 220 of file molecule.H.
operator<<
Ostream& operator<< (Ostream & , const molecule &) friend
Referenced by molecule::iNew::operator()().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/molecule/molecule.H
src/lagrangian/molecularDynamics/molecule/molecule/molecule.C
src/lagrangian/molecularDynamics/molecule/molecule/moleculeI.H
src/lagrangian/molecularDynamics/molecule/molecule/moleculeIO.C