OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SinglePhaseMixture< CloudType > Class Template Reference
Templated parcel single phase, multi-component class.
Public Member Functions
TypeName ("singlePhaseMixture")
Runtime type information.
SinglePhaseMixture (const dictionary &dict, CloudType &owner)
Construct from dictionary.
SinglePhaseMixture (const SinglePhaseMixture< CloudType > &cm)
Construct copy.
virtual autoPtr< CompositionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~SinglePhaseMixture ()
Destructor.
const scalarField & YGas0 () const
Return the list of gas mass fractions.
scalar YGasTot0 () const
Return the total gas mass fraction.
const scalarField & YLiquid0 () const
Return the list of liquid mass fractions.
scalar YLiquidTot0 () const
Return the total liquid mass fraction.
const scalarField & YSolid0 () const
Return the list of solid mass fractions.
scalar YSolidTot0 () const
Return the total solid mass fraction.
virtual const scalarField & YMixture0 () const
Return the list of mixture mass fractions.
virtual label idGas () const
Gas id.
virtual label idLiquid () const
Liquid id.
virtual label idSolid () const
Solid id.
Public Member Functions inherited from CompositionModel< CloudType >
TypeName ("compositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CompositionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
CompositionModel (CloudType &owner)
Construct null from owner.
CompositionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
CompositionModel (const CompositionModel< CloudType > &cm)
Construct copy.
virtual ~CompositionModel ()
Destructor.
const SLGThermo & thermo () const
Return the thermo database.
const basicMultiComponentMixture & carrier () const
Return the carrier components (wrapper function)
const liquidMixtureProperties & liquids () const
Return the global (additional) liquids.
const solidMixtureProperties & solids () const
Return the global (additional) solids.
const phasePropertiesList & phaseProps () const
Return the list of phase properties.
label nPhase () const
Return the number of phases.
const wordList & phaseTypes () const
Return the list of phase type names.
const wordList & stateLabels () const
Return the list of state labels (s), (l), (g) etc.
const wordList & componentNames (const label phaseI) const
Return the list of component names for phaseI.
label globalCarrierId (const word &cmptName, const bool allowNotFound=false) const
Return global id of component cmptName in carrier thermo.
label globalId (const label phaseI, const word &cmptName, const bool allowNotFound=false) const
Return global id of component cmptName in phase phaseI.
const labelList & globalIds (const label phaseI) const
Return global ids of for phase phaseI.
label localId (const label phaseI, const word &cmptName, const bool allowNotFound=false) const
Return local id of component cmptName in phase phaseI.
label localToGlobalCarrierId (const label phaseI, const label id, const bool allowNotFound=false) const
Return global carrier id of component given local id.
const scalarField & Y0 (const label phaseI) const
Return the list of phase phaseI mass fractions.
scalarField X (const label phaseI, const scalarField &Y) const
Return the list of phase phaseI volume fractions fractions.
virtual scalar H (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return total enthalpy for the phase phaseI.
virtual scalar Hs (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return sensible enthalpy for the phase phaseI.
virtual scalar Hc (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return chemical enthalpy for the phase phaseI.
virtual scalar Cp (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return specific heat caoacity for the phase phaseI.
virtual scalar L (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return latent heat for the phase phaseI.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from CompositionModel< CloudType >
static autoPtr< CompositionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::SinglePhaseMixture< CloudType >
Templated parcel single phase, multi-component class.
Source files
SinglePhaseMixture.H
SinglePhaseMixture.C
Definition at line 49 of file SinglePhaseMixture.H.
Constructor & Destructor Documentation
SinglePhaseMixture() [1/2]
SinglePhaseMixture (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 80 of file SinglePhaseMixture.C.
SinglePhaseMixture() [2/2]
SinglePhaseMixture (const SinglePhaseMixture< CloudType > & cm)
Construct copy.
Definition at line 96 of file SinglePhaseMixture.C.
~SinglePhaseMixture()
~SinglePhaseMixture () virtual
Destructor.
Definition at line 110 of file SinglePhaseMixture.C.
Referenced by SinglePhaseMixture< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("singlePhaseMixture")
Runtime type information.
clone()
virtual autoPtr<CompositionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from CompositionModel< CloudType >.
Definition at line 89 of file SinglePhaseMixture.H.
References SinglePhaseMixture< CloudType >::idGas(), SinglePhaseMixture< CloudType >::idLiquid(), SinglePhaseMixture< CloudType >::idSolid(), SinglePhaseMixture< CloudType >::YGas0(), SinglePhaseMixture< CloudType >::YGasTot0(), SinglePhaseMixture< CloudType >::YLiquid0(), SinglePhaseMixture< CloudType >::YLiquidTot0(), SinglePhaseMixture< CloudType >::YMixture0(), SinglePhaseMixture< CloudType >::YSolid0(), SinglePhaseMixture< CloudType >::YSolidTot0(), and SinglePhaseMixture< CloudType >::~SinglePhaseMixture().
YGas0()
const Foam::scalarField & YGas0 () const
Return the list of gas mass fractions.
Definition at line 118 of file SinglePhaseMixture.C.
References notImplemented.
Referenced by SinglePhaseMixture< CloudType >::clone().
YGasTot0()
scalar YGasTot0 () const
Return the total gas mass fraction.
Referenced by SinglePhaseMixture< CloudType >::clone().
YLiquid0()
const Foam::scalarField & YLiquid0 () const
Return the list of liquid mass fractions.
Definition at line 131 of file SinglePhaseMixture.C.
References notImplemented.
Referenced by SinglePhaseMixture< CloudType >::clone().
YLiquidTot0()
scalar YLiquidTot0 () const
Return the total liquid mass fraction.
Referenced by SinglePhaseMixture< CloudType >::clone().
YSolid0()
const Foam::scalarField & YSolid0 () const
Return the list of solid mass fractions.
Definition at line 144 of file SinglePhaseMixture.C.
References notImplemented.
Referenced by SinglePhaseMixture< CloudType >::clone().
YSolidTot0()
scalar YSolidTot0 () const
Return the total solid mass fraction.
Referenced by SinglePhaseMixture< CloudType >::clone().
YMixture0()
const Foam::scalarField & YMixture0 () const virtual
Return the list of mixture mass fractions.
Reimplemented from CompositionModel< CloudType >.
Definition at line 157 of file SinglePhaseMixture.C.
Referenced by SinglePhaseMixture< CloudType >::clone().
idGas()
Foam::label idGas () const virtual
Gas id.
Reimplemented from CompositionModel< CloudType >.
Definition at line 164 of file SinglePhaseMixture.C.
Referenced by SinglePhaseMixture< CloudType >::clone().
idLiquid()
Foam::label idLiquid () const virtual
Liquid id.
Reimplemented from CompositionModel< CloudType >.
Definition at line 171 of file SinglePhaseMixture.C.
Referenced by SinglePhaseMixture< CloudType >::clone().
idSolid()
Foam::label idSolid () const virtual
Solid id.
Reimplemented from CompositionModel< CloudType >.
Definition at line 178 of file SinglePhaseMixture.C.
Referenced by SinglePhaseMixture< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/SinglePhaseMixture/SinglePhaseMixture.H
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/SinglePhaseMixture/SinglePhaseMixture.C