OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
energyScalingFunction Class Reference abstract
Public Member Functions
TypeName ("energyScalingFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, energyScalingFunction, dictionary,(const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot),(name, energyScalingFunctionProperties, pairPot))
energyScalingFunction (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Construct from components.
virtual ~energyScalingFunction ()
Destructor.
virtual void scaleEnergy (scalar &e, const scalar r) const =0
const dictionary & energyScalingFunctionProperties () const
virtual bool read (const dictionary &energyScalingFunctionProperties)=0
Read energyScalingFunction dictionary.
Static Public Member Functions
static autoPtr< energyScalingFunction > New (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Return a reference to the selected viscosity model.
Protected Member Functions
energyScalingFunction (const energyScalingFunction &)
Disallow copy construct.
void operator= (const energyScalingFunction &)
Disallow default bitwise assignment.
Protected Attributes
word name_
dictionary energyScalingFunctionProperties_
const pairPotential & pairPot_
Detailed Description
Source files
energyScalingFunction.H
energyScalingFunction.C
energyScalingFunctionNew.C
Definition at line 52 of file energyScalingFunction.H.
Constructor & Destructor Documentation
energyScalingFunction() [1/2]
energyScalingFunction (const energyScalingFunction &) protected
Disallow copy construct.
energyScalingFunction() [2/2]
energyScalingFunction (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot)
Construct from components.
Definition at line 40 of file energyScalingFunction.C.
References energyScalingFunction::read().
~energyScalingFunction()
virtual ~energyScalingFunction () inline virtual
Destructor.
Definition at line 120 of file energyScalingFunction.H.
References Foam::e, and energyScalingFunction::scaleEnergy().
Member Function Documentation
operator=()
void operator= (const energyScalingFunction &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("energyScalingFunction")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , energyScalingFunction , dictionary , (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot) , (name, energyScalingFunctionProperties, pairPot))
New()
Foam::autoPtr< Foam::energyScalingFunction > New (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot) static
Return a reference to the selected viscosity model.
Definition at line 32 of file energyScalingFunctionNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), name(), and Foam::nl.
Referenced by pairPotential::scaleEnergy().
scaleEnergy()
virtual void scaleEnergy (scalar & e, const scalar r) const pure virtual
Implemented in doubleSigmoid, sigmoid, shiftedForce, shifted, and noScaling.
Referenced by energyScalingFunction::~energyScalingFunction().
energyScalingFunctionProperties()
const dictionary& energyScalingFunctionProperties () const inline
Definition at line 128 of file energyScalingFunction.H.
References energyScalingFunction::energyScalingFunctionProperties_, and energyScalingFunction::read().
read()
bool read (const dictionary & energyScalingFunctionProperties) pure virtual
Read energyScalingFunction dictionary.
Implemented in doubleSigmoid, sigmoid, shiftedForce, shifted, and noScaling.
Definition at line 56 of file energyScalingFunction.C.
Referenced by energyScalingFunction::energyScalingFunction(), energyScalingFunction::energyScalingFunctionProperties(), noScaling::read(), shifted::read(), shiftedForce::read(), sigmoid::read(), and doubleSigmoid::read().
Member Data Documentation
name_
word name_ protected
Definition at line 59 of file energyScalingFunction.H.
energyScalingFunctionProperties_
dictionary energyScalingFunctionProperties_ protected
Definition at line 61 of file energyScalingFunction.H.
Referenced by energyScalingFunction::energyScalingFunctionProperties().
pairPot_
const pairPotential& pairPot_ protected
Definition at line 63 of file energyScalingFunction.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/energyScalingFunction/basic/energyScalingFunction.H
src/lagrangian/molecularDynamics/potential/energyScalingFunction/basic/energyScalingFunction.C
src/lagrangian/molecularDynamics/potential/energyScalingFunction/basic/energyScalingFunctionNew.C