OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
electrostaticPotential Class Reference
Public Member Functions
electrostaticPotential ()
Construct and set prefactor.
~electrostaticPotential ()
Destructor.
scalar energy (const scalar r) const
scalar force (const scalar r) const
Detailed Description
Definition at line 48 of file electrostaticPotential.H.
Constructor & Destructor Documentation
electrostaticPotential()
electrostaticPotential ()
Construct and set prefactor.
Definition at line 31 of file electrostaticPotential.C.
~electrostaticPotential()
~electrostaticPotential () inline
Destructor.
Definition at line 64 of file electrostaticPotential.H.
References electrostaticPotential::energy(), and electrostaticPotential::force().
Member Function Documentation
energy()
Foam::scalar energy (const scalar r) const
Definition at line 38 of file electrostaticPotential.C.
Referenced by electrostaticPotential::~electrostaticPotential().
force()
Foam::scalar force (const scalar r) const
Definition at line 44 of file electrostaticPotential.C.
Referenced by electrostaticPotential::~electrostaticPotential().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/electrostaticPotential/electrostaticPotential.H
src/lagrangian/molecularDynamics/potential/electrostaticPotential/electrostaticPotential.C