OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
doubleSigmoid Class Reference
Public Member Functions
TypeName ("doubleSigmoid")
Runtime type information.
doubleSigmoid (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Construct from components.
~doubleSigmoid ()
Destructor.
void scaleEnergy (scalar &e, const scalar r) const
bool read (const dictionary &energyScalingFunctionProperties)
Read dictionary.
Public Member Functions inherited from energyScalingFunction
TypeName ("energyScalingFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, energyScalingFunction, dictionary,(const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot),(name, energyScalingFunctionProperties, pairPot))
energyScalingFunction (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Construct from components.
virtual ~energyScalingFunction ()
Destructor.
const dictionary & energyScalingFunctionProperties () const
Additional Inherited Members
Static Public Member Functions inherited from energyScalingFunction
static autoPtr< energyScalingFunction > New (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from energyScalingFunction
energyScalingFunction (const energyScalingFunction &)
Disallow copy construct.
void operator= (const energyScalingFunction &)
Disallow default bitwise assignment.
Protected Attributes inherited from energyScalingFunction
word name_
dictionary energyScalingFunctionProperties_
const pairPotential & pairPot_
Detailed Description
Source files
doubleSigmoid.H
doubleSigmoid.C
Definition at line 50 of file doubleSigmoid.H.
Constructor & Destructor Documentation
doubleSigmoid()
doubleSigmoid (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot)
Construct from components.
Definition at line 63 of file doubleSigmoid.C.
~doubleSigmoid()
~doubleSigmoid () inline
Destructor.
Definition at line 92 of file doubleSigmoid.H.
References Foam::e, doubleSigmoid::read(), and doubleSigmoid::scaleEnergy().
Member Function Documentation
TypeName()
TypeName ("doubleSigmoid")
Runtime type information.
scaleEnergy()
void scaleEnergy (scalar & e, const scalar r) const virtual
Implements energyScalingFunction.
Definition at line 83 of file doubleSigmoid.C.
Referenced by doubleSigmoid::~doubleSigmoid().
read()
bool read (const dictionary & energyScalingFunctionProperties) virtual
Read dictionary.
Implements energyScalingFunction.
Definition at line 89 of file doubleSigmoid.C.
References dictionary::lookup(), energyScalingFunction::read(), and dictionary::subDict().
Referenced by doubleSigmoid::~doubleSigmoid().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/doubleSigmoid/doubleSigmoid.H
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/doubleSigmoid/doubleSigmoid.C