OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tetherPotential Class Reference abstract
Public Member Functions
TypeName ("tetherPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, tetherPotential, dictionary,(const word &name, const dictionary &tetherPotentialProperties),(name, tetherPotentialProperties))
tetherPotential (const word &name, const dictionary &tetherPotentialProperties)
Construct from components.
virtual ~tetherPotential ()
Destructor.
virtual scalar energy (const vector r) const =0
virtual vector force (const vector r) const =0
const dictionary & tetherPotentialProperties () const
virtual bool read (const dictionary &tetherPotentialProperties)=0
Read tetherPotential dictionary.
Static Public Member Functions
static autoPtr< tetherPotential > New (const word &name, const dictionary &tetherPotentialProperties)
Return a reference to the selected viscosity model.
Protected Member Functions
tetherPotential (const tetherPotential &)
Disallow copy construct.
void operator= (const tetherPotential &)
Disallow default bitwise assignment.
Protected Attributes
word name_
dictionary tetherPotentialProperties_
Detailed Description
Source files
tetherPotential.H
tetherPotential.C
tetherPotentialNew.C
Definition at line 52 of file tetherPotential.H.
Constructor & Destructor Documentation
tetherPotential() [1/2]
tetherPotential (const tetherPotential &) protected
Disallow copy construct.
tetherPotential() [2/2]
tetherPotential (const word & name, const dictionary & tetherPotentialProperties)
Construct from components.
Definition at line 40 of file tetherPotential.C.
~tetherPotential()
virtual ~tetherPotential () inline virtual
Destructor.
Definition at line 114 of file tetherPotential.H.
References tetherPotential::energy(), and tetherPotential::force().
Member Function Documentation
operator=()
void operator= (const tetherPotential &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("tetherPotential")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , tetherPotential , dictionary , (const word &name, const dictionary &tetherPotentialProperties) , (name, tetherPotentialProperties))
New()
Foam::autoPtr< Foam::tetherPotential > New (const word & name, const dictionary & tetherPotentialProperties) static
Return a reference to the selected viscosity model.
Definition at line 31 of file tetherPotentialNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), name(), and Foam::nl.
energy()
virtual scalar energy (const vector r) const pure virtual
Implemented in pitchForkRing, restrainedHarmonicSpring, and harmonicSpring.
Referenced by tetherPotential::~tetherPotential().
force()
virtual vector force (const vector r) const pure virtual
Implemented in pitchForkRing, restrainedHarmonicSpring, and harmonicSpring.
Referenced by tetherPotential::~tetherPotential().
tetherPotentialProperties()
const dictionary& tetherPotentialProperties () const inline
Definition at line 124 of file tetherPotential.H.
References tetherPotential::read(), and tetherPotential::tetherPotentialProperties_.
read()
bool read (const dictionary & tetherPotentialProperties) pure virtual
Read tetherPotential dictionary.
Implemented in pitchForkRing, restrainedHarmonicSpring, and harmonicSpring.
Definition at line 53 of file tetherPotential.C.
Referenced by harmonicSpring::read(), restrainedHarmonicSpring::read(), pitchForkRing::read(), and tetherPotential::tetherPotentialProperties().
Member Data Documentation
name_
word name_ protected
Definition at line 59 of file tetherPotential.H.
tetherPotentialProperties_
dictionary tetherPotentialProperties_ protected
Definition at line 60 of file tetherPotential.H.
Referenced by tetherPotential::tetherPotentialProperties().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/basic/tetherPotential.H
src/lagrangian/molecularDynamics/potential/tetherPotential/basic/tetherPotential.C
src/lagrangian/molecularDynamics/potential/tetherPotential/basic/tetherPotentialNew.C