OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SprayParcel< ParcelType > Class Template Reference
Reacing spray parcel, with added functionality for atomization and breakup.
Classes
class constantProperties
Class to hold reacting particle constant properties.
class iNew
Factory class to read-construct particles used for.
Public Member Functions
TypeName ("SprayParcel")
Runtime type information.
SprayParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from owner, position, and cloud owner.
SprayParcel (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const scalar liquidCore, const scalar KHindex, const scalar y, const scalar yDot, const scalar tc, const scalar ms, const scalar injector, const scalar tMom, const scalar user, const typename ParcelType::constantProperties &constProps)
Construct from components.
SprayParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
SprayParcel (const SprayParcel &p, const polyMesh &mesh)
Construct as a copy.
SprayParcel (const SprayParcel &p)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
scalar d0 () const
Return const access to initial droplet diameter.
const vector & position0 () const
Return const access to initial droplet position.
scalar sigma () const
Return const access to the liquid surface tension.
scalar mu () const
Return const access to the liquid dynamic viscosity.
scalar liquidCore () const
Return const access to liquid core.
scalar KHindex () const
Return const access to Kelvin-Helmholtz breakup index.
scalar y () const
Return const access to spherical deviation.
scalar yDot () const
Return const access to rate of change of spherical deviation.
scalar tc () const
Return const access to atomization characteristic time.
scalar ms () const
Return const access to stripped parcel mass.
scalar injector () const
Return const access to injector id.
scalar tMom () const
Return const access to momentum relaxation time.
scalar user () const
Return const access to passive user scalar.
scalar & d0 ()
Return access to initial droplet diameter.
vector & position0 ()
Return access to initial droplet position.
scalar & sigma ()
Return access to the liquid surface tension.
scalar & mu ()
Return access to the liquid dynamic viscosity.
scalar & liquidCore ()
Return access to liquid core.
scalar & KHindex ()
Return access to Kelvin-Helmholtz breakup index.
scalar & y ()
Return access to spherical deviation.
scalar & yDot ()
Return access to rate of change of spherical deviation.
scalar & tc ()
Return access to atomization characteristic time.
scalar & ms ()
Return access to stripped parcel mass.
scalar & injector ()
Return access to injector id.
scalar & tMom ()
Return access to momentum relaxation time.
scalar & user ()
Return access to passive user scalar.
template<class TrackData >
void setCellValues (TrackData &td, const scalar dt, const label cellI)
Set cell values.
template<class TrackData >
void calcAtomization (TrackData &td, const scalar dt, const label cellI)
Correct parcel properties according to atomization model.
template<class TrackData >
void calcBreakup (TrackData &td, const scalar dt, const label cellI)
Correct parcel properties according to breakup model.
template<class TrackData >
void cellValueSourceCorrection (TrackData &td, const scalar dt, const label cellI)
Correct cell values using latest transfer information.
template<class TrackData >
void correctSurfaceValues (TrackData &td, const label cellI, const scalar T, const scalarField &Cs, scalar &rhos, scalar &mus, scalar &Pr, scalar &kappa)
Correct surface values due to emitted species.
template<class TrackData >
void calc (TrackData &td, const scalar dt, const label cellI)
Update parcel properties over the time interval.
template<class TrackData >
scalar chi (TrackData &td, const scalarField &X) const
Calculate the chi-factor for flash-boiling for the.
template<class TrackData >
void solveTABEq (TrackData &td, const scalar dt)
Solve the TAB equation.
template<class TrackData >
Foam::scalar chi (TrackData &td, const scalarField &X) const
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
Read.
template<class CloudType >
static void readFields (CloudType &c)
Read - no composition.
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
Write.
template<class CloudType >
static void writeFields (const CloudType &c)
Write - composition supplied.
Static Public Attributes
static string propHeader
String representation of properties.
Protected Attributes
scalar d0_
Initial droplet diameter.
vector position0_
Injection position.
scalar sigma_
Liquid surface tension [N/m].
scalar mu_
Liquid dynamic viscosity [Pa.s].
scalar liquidCore_
Part of liquid core (>0.5=liquid, <0.5=droplet)
scalar KHindex_
Index for KH Breakup.
scalar y_
Spherical deviation.
scalar yDot_
Rate of change of spherical deviation.
scalar tc_
Characteristic time (used in atomization and/or breakup model)
scalar ms_
Stripped parcel mass due to breakup.
scalar injector_
Injected from injector (needed e.g. for calculating distance.
scalar tMom_
Momentum relaxation time (needed for calculating parcel acc.)
scalar user_
Passive scalar (extra variable to be defined by user)
Friends
Ostream & operator (Ostream &, const SprayParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::SprayParcel< ParcelType >
Reacing spray parcel, with added functionality for atomization and breakup.
Definition at line 43 of file SprayParcel.H.
Constructor & Destructor Documentation
SprayParcel() [1/5]
SprayParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 108 of file SprayParcelI.H.
Referenced by SprayParcel< ParcelType >::constantProperties::constantProperties(), and SprayParcel< ParcelType >::solveTABEq().
SprayParcel() [2/5]
SprayParcel (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const scalar liquidCore, const scalar KHindex, const scalar y, const scalar yDot, const scalar tc, const scalar ms, const scalar injector, const scalar tMom, const scalar user, const typename ParcelType::constantProperties & constProps) inline
Construct from components.
Definition at line 135 of file SprayParcelI.H.
SprayParcel() [3/5]
SprayParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 53 of file SprayParcelIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), and readScalar.
SprayParcel() [4/5]
SprayParcel (const SprayParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
SprayParcel() [5/5]
SprayParcel (const SprayParcel< ParcelType > & p)
Construct as a copy.
Member Function Documentation
TypeName()
TypeName ("SprayParcel< ParcelType >")
Runtime type information.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 243 of file SprayParcel.H.
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 249 of file SprayParcel.H.
References mesh.
d0() [1/2]
Foam::scalar d0 () const inline
Return const access to initial droplet diameter.
Definition at line 217 of file SprayParcelI.H.
References SprayParcel< ParcelType >::d0_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
position0() [1/2]
const Foam::vector & position0 () const inline
Return const access to initial droplet position.
Definition at line 224 of file SprayParcelI.H.
References SprayParcel< ParcelType >::position0_.
Referenced by SprayParcel< ParcelType >::iNew::operator()().
sigma() [1/2]
Foam::scalar sigma () const inline
Return const access to the liquid surface tension.
Definition at line 231 of file SprayParcelI.H.
References SprayParcel< ParcelType >::sigma_.
Referenced by SprayParcel< ParcelType >::iNew::operator()().
mu() [1/2]
Foam::scalar mu () const inline
Return const access to the liquid dynamic viscosity.
Definition at line 238 of file SprayParcelI.H.
References SprayParcel< ParcelType >::mu_.
Referenced by SprayParcel< ParcelType >::iNew::operator()().
liquidCore() [1/2]
Foam::scalar liquidCore () const inline
Return const access to liquid core.
Definition at line 245 of file SprayParcelI.H.
References SprayParcel< ParcelType >::liquidCore_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
KHindex() [1/2]
Foam::scalar KHindex () const inline
Return const access to Kelvin-Helmholtz breakup index.
Definition at line 252 of file SprayParcelI.H.
References SprayParcel< ParcelType >::KHindex_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
y() [1/2]
Foam::scalar y () const inline
Return const access to spherical deviation.
Definition at line 259 of file SprayParcelI.H.
References SprayParcel< ParcelType >::y_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
yDot() [1/2]
Foam::scalar yDot () const inline
Return const access to rate of change of spherical deviation.
Definition at line 266 of file SprayParcelI.H.
References SprayParcel< ParcelType >::yDot_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
tc() [1/2]
Foam::scalar tc () const inline
Return const access to atomization characteristic time.
Definition at line 273 of file SprayParcelI.H.
References SprayParcel< ParcelType >::tc_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
ms() [1/2]
Foam::scalar ms () const inline
Return const access to stripped parcel mass.
Definition at line 280 of file SprayParcelI.H.
References SprayParcel< ParcelType >::ms_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
injector() [1/2]
Foam::scalar injector () const inline
Return const access to injector id.
Definition at line 287 of file SprayParcelI.H.
References SprayParcel< ParcelType >::injector_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
tMom() [1/2]
Foam::scalar tMom () const inline
Return const access to momentum relaxation time.
Definition at line 294 of file SprayParcelI.H.
References SprayParcel< ParcelType >::tMom_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
user() [1/2]
Foam::scalar user () const inline
Return const access to passive user scalar.
Definition at line 301 of file SprayParcelI.H.
References SprayParcel< ParcelType >::user_.
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
d0() [2/2]
Foam::scalar & d0 () inline
Return access to initial droplet diameter.
Definition at line 308 of file SprayParcelI.H.
References SprayParcel< ParcelType >::d0_.
position0() [2/2]
Foam::vector & position0 () inline
Return access to initial droplet position.
Definition at line 315 of file SprayParcelI.H.
References SprayParcel< ParcelType >::position0_.
sigma() [2/2]
Foam::scalar & sigma () inline
Return access to the liquid surface tension.
Definition at line 322 of file SprayParcelI.H.
References SprayParcel< ParcelType >::sigma_.
mu() [2/2]
Foam::scalar & mu () inline
Return access to the liquid dynamic viscosity.
Definition at line 329 of file SprayParcelI.H.
References SprayParcel< ParcelType >::mu_.
liquidCore() [2/2]
Foam::scalar & liquidCore () inline
Return access to liquid core.
Definition at line 336 of file SprayParcelI.H.
References SprayParcel< ParcelType >::liquidCore_.
KHindex() [2/2]
Foam::scalar & KHindex () inline
Return access to Kelvin-Helmholtz breakup index.
Definition at line 343 of file SprayParcelI.H.
References SprayParcel< ParcelType >::KHindex_.
y() [2/2]
Foam::scalar & y () inline
Return access to spherical deviation.
Definition at line 350 of file SprayParcelI.H.
References SprayParcel< ParcelType >::y_.
yDot() [2/2]
Foam::scalar & yDot () inline
Return access to rate of change of spherical deviation.
Definition at line 357 of file SprayParcelI.H.
References SprayParcel< ParcelType >::yDot_.
tc() [2/2]
Foam::scalar & tc () inline
Return access to atomization characteristic time.
Definition at line 364 of file SprayParcelI.H.
References SprayParcel< ParcelType >::tc_.
ms() [2/2]
Foam::scalar & ms () inline
Return access to stripped parcel mass.
Definition at line 371 of file SprayParcelI.H.
References SprayParcel< ParcelType >::ms_.
injector() [2/2]
Foam::scalar & injector () inline
Return access to injector id.
Definition at line 378 of file SprayParcelI.H.
References SprayParcel< ParcelType >::injector_.
tMom() [2/2]
Foam::scalar & tMom () inline
Return access to momentum relaxation time.
Definition at line 385 of file SprayParcelI.H.
References SprayParcel< ParcelType >::tMom_.
user() [2/2]
Foam::scalar & user () inline
Return access to passive user scalar.
Definition at line 392 of file SprayParcelI.H.
References SprayParcel< ParcelType >::user_.
setCellValues()
void setCellValues (TrackData & td, const scalar dt, const label cellI)
Set cell values.
Definition at line 35 of file SprayParcel.C.
References SprayParcel< ParcelType >::cellValueSourceCorrection().
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
calcAtomization()
void calcAtomization (TrackData & td, const scalar dt, const label cellI)
Correct parcel properties according to atomization model.
Definition at line 152 of file SprayParcel.C.
References SprayParcel< ParcelType >::calcBreakup(), AtomizationModel< CloudType >::calcChi(), composition, d(), CompositionModel< CloudType >::liquids(), Foam::mag(), Foam::max(), Foam::min(), pos(), R, rho, T, AtomizationModel< CloudType >::Taverage(), U, AtomizationModel< CloudType >::update(), Urel, and Y.
Referenced by SprayParcel< ParcelType >::calc(), and SprayParcel< ParcelType >::iNew::operator()().
calcBreakup()
void calcBreakup (TrackData & td, const scalar dt, const label cellI)
Correct parcel properties according to breakup model.
Definition at line 219 of file SprayParcel.C.
References SprayParcel< ParcelType >::chi(), d(), SprayParcel< ParcelType >::d0(), forces::forces(), SprayParcel< ParcelType >::injector(), SprayParcel< ParcelType >::KHindex(), SprayParcel< ParcelType >::liquidCore(), Foam::mag(), SprayParcel< ParcelType >::ms(), p, R, Foam::Re(), rho, SprayParcel< ParcelType >::setCellValues(), forceSuSp::Sp(), T, SprayParcel< ParcelType >::tc(), SprayParcel< ParcelType >::tMom(), U, Urel, SprayParcel< ParcelType >::user(), y, SprayParcel< ParcelType >::y(), and SprayParcel< ParcelType >::yDot().
Referenced by SprayParcel< ParcelType >::calcAtomization(), and SprayParcel< ParcelType >::iNew::operator()().
cellValueSourceCorrection()
void cellValueSourceCorrection (TrackData & td, const scalar dt, const label cellI)
Correct cell values using latest transfer information.
Definition at line 48 of file SprayParcel.C.
References SprayParcel< ParcelType >::calc().
Referenced by SprayParcel< ParcelType >::iNew::operator()(), and SprayParcel< ParcelType >::setCellValues().
correctSurfaceValues()
void correctSurfaceValues (TrackData & td, const label cellI, const scalar T, const scalarField & Cs, scalar & rhos, scalar & mus, scalar & Pr, scalar & kappa)
Correct surface values due to emitted species.
Referenced by SprayParcel< ParcelType >::iNew::operator()().
calc()
void calc (TrackData & td, const scalar dt, const label cellI)
Update parcel properties over the time interval.
Definition at line 61 of file SprayParcel.C.
References Foam::calc(), SprayParcel< ParcelType >::calcAtomization(), Foam::cbrt(), composition, d(), CompositionModel< CloudType >::liquids(), pow3(), rho, rho0, rho1, T, X0(), Y, and Y0().
Referenced by SprayParcel< ParcelType >::cellValueSourceCorrection(), and SprayParcel< ParcelType >::iNew::operator()().
chi() [1/2]
scalar chi (TrackData & td, const scalarField & X) const
Calculate the chi-factor for flash-boiling for the.
atomization model
Referenced by SprayParcel< ParcelType >::calcBreakup(), and SprayParcel< ParcelType >::iNew::operator()().
solveTABEq()
void solveTABEq (TrackData & td, const scalar dt)
Solve the TAB equation.
Definition at line 365 of file SprayParcel.C.
References Foam::constant::universal::c, Foam::cos(), d(), SprayParcel< ParcelType >::d0_, Foam::constant::electromagnetic::e, Foam::exp(), SprayParcel< ParcelType >::injector_, SprayParcel< ParcelType >::KHindex_, SprayParcel< ParcelType >::liquidCore_, mesh, SprayParcel< ParcelType >::ms_, SprayParcel< ParcelType >::mu_, p, SprayParcel< ParcelType >::position0_, rho, s(), SprayParcel< ParcelType >::sigma_, Foam::sin(), SprayParcel< ParcelType >::SprayParcel(), Foam::sqrt(), SprayParcel< ParcelType >::tc_, SprayParcel< ParcelType >::tMom_, U, SprayParcel< ParcelType >::user_, y, Foam::y1(), SprayParcel< ParcelType >::y_, and SprayParcel< ParcelType >::yDot_.
Referenced by SprayParcel< ParcelType >::chi(), and SprayParcel< ParcelType >::iNew::operator()().
readFields() [1/2]
void readFields (CloudType & c, const CompositionType & compModel) static
Read.
Definition at line 144 of file SprayParcelIO.C.
References Cloud< ParticleType >::checkFieldIOobject(), SprayParcel< ParcelType >::d0_, Cloud< ParticleType >::fieldIOobject(), forAllIter, SprayParcel< ParcelType >::injector_, SprayParcel< ParcelType >::KHindex_, SprayParcel< ParcelType >::liquidCore_, SprayParcel< ParcelType >::ms_, Foam::constant::physicoChemical::mu, SprayParcel< ParcelType >::mu_, p, SprayParcel< ParcelType >::position0_, Foam::readFields(), Foam::constant::physicoChemical::sigma, SprayParcel< ParcelType >::sigma_, Cloud< ParticleType >::size(), SprayParcel< ParcelType >::tc_, SprayParcel< ParcelType >::tMom_, SprayParcel< ParcelType >::user_, y, SprayParcel< ParcelType >::y_, and SprayParcel< ParcelType >::yDot_.
Referenced by SprayParcel< ParcelType >::iNew::operator()(), and SprayParcel< ParcelType >::readFields().
readFields() [2/2]
void readFields (CloudType & c) static
Read - no composition.
Definition at line 130 of file SprayParcelIO.C.
References Foam::readFields(), SprayParcel< ParcelType >::readFields(), and Cloud< ParticleType >::size().
writeFields() [1/2]
void writeFields (const CloudType & c, const CompositionType & compModel) static
Write.
Definition at line 234 of file SprayParcelIO.C.
References SprayParcel< ParcelType >::d0_, Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), SprayParcel< ParcelType >::injector_, SprayParcel< ParcelType >::KHindex_, SprayParcel< ParcelType >::liquidCore_, SprayParcel< ParcelType >::ms_, Foam::constant::physicoChemical::mu, SprayParcel< ParcelType >::mu_, p, SprayParcel< ParcelType >::position0_, Foam::constant::physicoChemical::sigma, SprayParcel< ParcelType >::sigma_, Cloud< ParticleType >::size(), SprayParcel< ParcelType >::tc_, SprayParcel< ParcelType >::tMom_, SprayParcel< ParcelType >::user_, regIOobject::write(), y, SprayParcel< ParcelType >::y_, and SprayParcel< ParcelType >::yDot_.
Referenced by SprayParcel< ParcelType >::iNew::operator()(), and SprayParcel< ParcelType >::writeFields().
writeFields() [2/2]
void writeFields (const CloudType & c) static
Write - composition supplied.
Definition at line 225 of file SprayParcelIO.C.
References SprayParcel< ParcelType >::writeFields().
chi() [2/2]
Foam::scalar chi (TrackData & td, const scalarField & X) const
Definition at line 321 of file SprayParcel.C.
References composition, forAll, liquidProperties::h(), liquidProperties::hl(), CompositionModel< CloudType >::liquids(), Foam::max(), Foam::min(), liquidProperties::pvInvert(), liquidProperties::rho(), SprayParcel< ParcelType >::solveTABEq(), and T.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const SprayParcel< ParcelType > &) friend
Member Data Documentation
d0_
scalar d0_ protected
Initial droplet diameter.
Definition at line 131 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::d0(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
position0_
vector position0_ protected
Injection position.
Definition at line 134 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::position0(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
sigma_
scalar sigma_ protected
Liquid surface tension [N/m].
Definition at line 137 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::sigma(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
mu_
scalar mu_ protected
Liquid dynamic viscosity [Pa.s].
Definition at line 140 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::mu(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
liquidCore_
scalar liquidCore_ protected
Part of liquid core (>0.5=liquid, <0.5=droplet)
Definition at line 143 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::liquidCore(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
KHindex_
scalar KHindex_ protected
Index for KH Breakup.
Definition at line 146 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::KHindex(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
y_
scalar y_ protected
Spherical deviation.
Definition at line 149 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), SprayParcel< ParcelType >::writeFields(), and SprayParcel< ParcelType >::y().
yDot_
scalar yDot_ protected
Rate of change of spherical deviation.
Definition at line 152 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), SprayParcel< ParcelType >::writeFields(), and SprayParcel< ParcelType >::yDot().
tc_
scalar tc_ protected
Characteristic time (used in atomization and/or breakup model)
Definition at line 155 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), SprayParcel< ParcelType >::tc(), and SprayParcel< ParcelType >::writeFields().
ms_
scalar ms_ protected
Stripped parcel mass due to breakup.
Definition at line 158 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::ms(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
injector_
scalar injector_ protected
Injected from injector (needed e.g. for calculating distance.
from injector)
Definition at line 162 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::injector(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), and SprayParcel< ParcelType >::writeFields().
tMom_
scalar tMom_ protected
Momentum relaxation time (needed for calculating parcel acc.)
Definition at line 165 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), SprayParcel< ParcelType >::tMom(), and SprayParcel< ParcelType >::writeFields().
user_
scalar user_ protected
Passive scalar (extra variable to be defined by user)
Definition at line 168 of file SprayParcel.H.
Referenced by SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), SprayParcel< ParcelType >::user(), and SprayParcel< ParcelType >::writeFields().
propHeader
Foam::string propHeader static
Initial value:
=
    ParcelType::propHeader
  + " d0"
  + " position0"
  + " sigma"
  + " mu"
  + " liquidCore"
  + " KHindex"
  + " y"
  + " yDot"
  + " tc"
  + " ms"
  + " injector"
  + " tMom"
  + " user"
String representation of properties.
Definition at line 176 of file SprayParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcel.H
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcel.C
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcelI.H
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcelIO.C