OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SprayParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< SprayParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::SprayParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 259 of file SprayParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 265 of file SprayParcel.H.
Member Function Documentation
operator()()
autoPtr<SprayParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 270 of file SprayParcel.H.
References Foam::constant::universal::c, SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), SprayParcel< ParcelType >::cellValueSourceCorrection(), SprayParcel< ParcelType >::chi(), SprayParcel< ParcelType >::correctSurfaceValues(), SprayParcel< ParcelType >::d0(), SprayParcel< ParcelType >::injector(), Foam::constant::electromagnetic::kappa, SprayParcel< ParcelType >::KHindex(), SprayParcel< ParcelType >::liquidCore(), SprayParcel< ParcelType >::ms(), SprayParcel< ParcelType >::mu(), SprayParcel< ParcelType >::position0(), Pr(), SprayParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::setCellValues(), SprayParcel< ParcelType >::sigma(), SprayParcel< ParcelType >::solveTABEq(), Foam::T(), SprayParcel< ParcelType >::tc(), SprayParcel< ParcelType >::tMom(), SprayParcel< ParcelType >::user(), SprayParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::y(), and SprayParcel< ParcelType >::yDot().
The documentation for this class was generated from the following file:
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcel.H