OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GradientDispersionRAS< CloudType > Class Template Reference
The velocity is perturbed in the direction of -grad(k), with a Gaussian random number distribution with variance sigma. where sigma is defined below.
Public Member Functions
TypeName ("gradientDispersionRAS")
Runtime type information.
GradientDispersionRAS (const dictionary &dict, CloudType &owner)
Construct from components.
GradientDispersionRAS (GradientDispersionRAS< CloudType > &dm)
Construct copy.
virtual autoPtr< DispersionModel< CloudType > > clone ()
Construct and return a clone.
virtual ~GradientDispersionRAS ()
Destructor.
virtual void cacheFields (const bool store)
Cache carrier fields.
virtual vector update (const scalar dt, const label cellI, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)
Update (disperse particles)
TypeName ("gradientDispersionRAS")
Runtime type information.
GradientDispersionRAS (const dictionary &dict, CloudType &owner)
Construct from components.
GradientDispersionRAS (GradientDispersionRAS< CloudType > &dm)
Construct copy.
virtual autoPtr< DispersionModel< CloudType > > clone ()
Construct and return a clone.
virtual ~GradientDispersionRAS ()
Destructor.
virtual void cacheFields (const bool store)
Cache carrier fields.
virtual vector update (const scalar dt, const label cellI, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)
Update (disperse particles)
Public Member Functions inherited from DispersionRASModel< CloudType >
TypeName ("dispersionRASModel")
Runtime type information.
DispersionRASModel (const dictionary &dict, CloudType &owner)
Construct from components.
DispersionRASModel (DispersionRASModel< CloudType > &dm)
Construct copy.
virtual ~DispersionRASModel ()
Destructor.
virtual void write (Ostream &os) const
Write.
TypeName ("dispersionRASModel")
Runtime type information.
DispersionRASModel (const dictionary &dict, CloudType &owner)
Construct from components.
DispersionRASModel (DispersionRASModel< CloudType > &dm)
Construct copy.
virtual ~DispersionRASModel ()
Destructor.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from DispersionModel< CloudType >
TypeName ("dispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DispersionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
DispersionModel (CloudType &owner)
Construct null from owner.
DispersionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
DispersionModel (DispersionModel< CloudType > &dm)
Construct copy.
virtual ~DispersionModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Attributes
const volVectorField * gradkPtr_
Gradient of k.
bool ownGradK_
Take ownership of the grad(k)
Protected Attributes inherited from DispersionRASModel< CloudType >
const volScalarField * kPtr_
Turbulence k.
bool ownK_
Take ownership of the k field.
const volScalarField * epsilonPtr_
Turbulence epsilon.
bool ownEpsilon_
Take ownership of the epsilon field.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from DispersionModel< CloudType >
static autoPtr< DispersionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from DispersionRASModel< CloudType >
tmp< volScalarField > kModel () const
Return the k field from the turbulence model.
tmp< volScalarField > epsilonModel () const
Return the epsilon field from the turbulence model.
tmp< volScalarField > kModel () const
Return the k field from the turbulence model.
tmp< volScalarField > epsilonModel () const
Return the epsilon field from the turbulence model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
template<class CloudType>
class Foam::GradientDispersionRAS< CloudType >
The velocity is perturbed in the direction of -grad(k), with a Gaussian random number distribution with variance sigma. where sigma is defined below.
Definition at line 48 of file GradientDispersionRAS.H.
Constructor & Destructor Documentation
GradientDispersionRAS() [1/4]
GradientDispersionRAS (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 34 of file GradientDispersionRAS.C.
GradientDispersionRAS() [2/4]
GradientDispersionRAS (GradientDispersionRAS< CloudType > & dm)
Construct copy.
Definition at line 47 of file GradientDispersionRAS.C.
References GradientDispersionRAS< CloudType >::ownGradK_.
~GradientDispersionRAS() [1/2]
~GradientDispersionRAS () virtual
Destructor.
Definition at line 62 of file GradientDispersionRAS.C.
Referenced by GradientDispersionRAS< CloudType >::clone().
GradientDispersionRAS() [3/4]
GradientDispersionRAS (const dictionary & dict, CloudType & owner)
Construct from components.
GradientDispersionRAS() [4/4]
GradientDispersionRAS (GradientDispersionRAS< CloudType > & dm)
Construct copy.
~GradientDispersionRAS() [2/2]
virtual ~GradientDispersionRAS () virtual
Destructor.
Member Function Documentation
TypeName() [1/2]
TypeName ("gradientDispersionRAS")
Runtime type information.
clone() [1/2]
virtual autoPtr<DispersionModel<CloudType> > clone () inline virtual
Construct and return a clone.
Reimplemented from DispersionRASModel< CloudType >.
Definition at line 80 of file GradientDispersionRAS.H.
References GradientDispersionRAS< CloudType >::cacheFields(), U, GradientDispersionRAS< CloudType >::update(), and GradientDispersionRAS< CloudType >::~GradientDispersionRAS().
cacheFields() [1/2]
void cacheFields (const bool store) virtual
Cache carrier fields.
Reimplemented from DispersionRASModel< CloudType >.
Definition at line 71 of file GradientDispersionRAS.C.
References Foam::deleteDemandDrivenData(), Foam::fvc::grad(), and GradientDispersionRAS< CloudType >::update().
Referenced by GradientDispersionRAS< CloudType >::clone().
update() [1/2]
Foam::vector update (const scalar dt, const label cellI, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) virtual
Update (disperse particles)
Reimplemented from DispersionModel< CloudType >.
Definition at line 94 of file GradientDispersionRAS.C.
References epsilon, k, Foam::log(), Foam::mag(), mesh, Foam::min(), Foam::pow(), DsmcCloud< ParcelType >::rndGen(), cachedRandom::sample01(), Foam::constant::physicoChemical::sigma, and Foam::sqrt().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), and GradientDispersionRAS< CloudType >::clone().
TypeName() [2/2]
TypeName ("gradientDispersionRAS")
Runtime type information.
clone() [2/2]
virtual autoPtr<DispersionModel<CloudType> > clone () inline virtual
Construct and return a clone.
Reimplemented from DispersionRASModel< CloudType >.
Definition at line 80 of file GradientDispersionRAS.H.
References GradientDispersionRAS< CloudType >::cacheFields(), U, GradientDispersionRAS< CloudType >::update(), and GradientDispersionRAS< CloudType >::~GradientDispersionRAS().
cacheFields() [2/2]
virtual void cacheFields (const bool store) virtual
Cache carrier fields.
Reimplemented from DispersionRASModel< CloudType >.
update() [2/2]
virtual vector update (const scalar dt, const label cellI, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) virtual
Update (disperse particles)
Reimplemented from DispersionModel< CloudType >.
Member Data Documentation
gradkPtr_
const volVectorField * gradkPtr_ protected
Gradient of k.
Definition at line 59 of file GradientDispersionRAS.H.
ownGradK_
bool ownGradK_ protected
Take ownership of the grad(k)
Definition at line 62 of file GradientDispersionRAS.H.
Referenced by GradientDispersionRAS< CloudType >::GradientDispersionRAS().
The documentation for this class was generated from the following files:
src/lagrangian/Turbulence/submodels/Kinematic/DispersionModel/GradientDispersionRAS/GradientDispersionRAS.H
src/lagrangian/Turbulence/submodels/Kinematic/DispersionModel/GradientDispersionRAS/GradientDispersionRAS.C