OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
trackedParticle Class Reference
Particle class that marks cells it passes through. Used to mark cells visited by feature edges.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToFace function.
Public Member Functions
trackedParticle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const point &end, const label level, const label i, const label j, const label k)
Construct from components.
trackedParticle (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
autoPtr< particle > clone () const
Construct and return a clone.
point & end ()
point to track to
label i () const
transported label
label & i ()
transported label
label j () const
transported label
label & j ()
transported label
label k () const
transported label
label & k ()
transported label
bool move (trackingData &, const scalar)
Track all particles to their end point.
bool hitPatch (const polyPatch &, trackingData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
void hitWedgePatch (const wedgePolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a wedge.
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a.
void hitSymmetryPatch (const symmetryPolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a.
void hitCyclicPatch (const cyclicPolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a cyclic.
void hitProcessorPatch (const processorPolyPatch &, trackingData &td)
void hitWallPatch (const wallPolyPatch &, trackingData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
void hitPatch (const polyPatch &, trackingData &td)
Overridable function to handle the particle hitting a polyPatch.
void correctAfterParallelTransfer (const label, trackingData &)
Convert processor patch addressing to the global equivalents.
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label cellI, bool doCellFacePt=true)
Construct from components, tetFaceI_ and tetPtI_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFaceI_ for the.
vector oldNormal () const
Return the normal of the tri on tetFaceI_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label faceI) const
Is this global face an internal face?
bool boundaryFace (const label faceI) const
Is this global face a boundary face?
label patch (const label faceI) const
Which patch is particle on.
label patchFace (const label patchI, const label faceI) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchI, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchI, TrackData &td)
Convert processor patch addressing to the global equivalents.
void write (Ostream &os, bool writeFields) const
Write the particle data.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Public Member Functions inherited from DLListBase::link
link ()
Null construct.
bool registered () const
Check if the link is registered with the DLListBase.
void deregister ()
Deregister the link after removal.
Friends
class Cloud< trackedParticle >
Ostream & operator<< (Ostream &, const trackedParticle &)
Additional Inherited Members
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Public Attributes inherited from DLListBase::link
link * prev_
Pointer to next entry in list.
link * next_
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions inherited from particle< Type >
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &cellI, label &tetFaceI, label &tetPtI, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes inherited from particle< Type >
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label cellI_
Index of the cell it is in.
label faceI_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFaceI_
Index of the face that owns the decomposed tet that the.
label tetPtI_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Detailed Description
Particle class that marks cells it passes through. Used to mark cells visited by feature edges.
Source files
trackedParticle.H
trackedParticle.C
Definition at line 52 of file trackedParticle.H.
Constructor & Destructor Documentation
trackedParticle() [1/2]
trackedParticle (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const point & end, const label level, const label i, const label j, const label k)
Construct from components.
Definition at line 32 of file trackedParticle.C.
Referenced by trackedParticle::clone(), trackedParticle::iNew::operator()(), and trackedParticle::trackingData::trackingData().
trackedParticle() [2/2]
trackedParticle (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 55 of file trackedParticle.C.
References IOstream::check(), IOstream::format(), trackedParticle::move(), and Istream::read().
Member Function Documentation
clone()
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from particle< Type >.
Definition at line 134 of file trackedParticle.H.
References particle< Type >::mesh_, and trackedParticle::trackedParticle().
end()
point& end () inline
point to track to
Definition at line 165 of file trackedParticle.H.
Referenced by trackedParticle::trackingData::trackingData().
i() [1/2]
label i () const inline
transported label
Definition at line 171 of file trackedParticle.H.
Referenced by trackedParticle::trackingData::trackingData().
i() [2/2]
label& i () inline
transported label
Definition at line 177 of file trackedParticle.H.
j() [1/2]
label j () const inline
transported label
Definition at line 183 of file trackedParticle.H.
Referenced by trackedParticle::trackingData::trackingData().
j() [2/2]
label& j () inline
transported label
Definition at line 189 of file trackedParticle.H.
k() [1/2]
label k () const inline
transported label
Definition at line 195 of file trackedParticle.H.
Referenced by trackedParticle::trackingData::trackingData().
k() [2/2]
label& k () inline
transported label
Definition at line 201 of file trackedParticle.H.
References trackedParticle::correctAfterParallelTransfer(), trackedParticle::hitCyclicPatch(), trackedParticle::hitPatch(), trackedParticle::hitProcessorPatch(), trackedParticle::hitSymmetryPatch(), trackedParticle::hitSymmetryPlanePatch(), trackedParticle::hitWallPatch(), trackedParticle::hitWedgePatch(), trackedParticle::move(), and trackedParticle::operator<<.
move()
bool move (trackingData & td, const scalar trackTime)
Track all particles to their end point.
Definition at line 96 of file trackedParticle.C.
References trackedParticle::hitPatch(), particle< Type >::TrackingData< CloudType >::keepParticle, Foam::max(), trackedParticle::trackingData::maxLevel_, Foam::min(), and particle< Type >::TrackingData< CloudType >::switchProcessor.
Referenced by trackedParticle::k(), and trackedParticle::trackedParticle().
hitPatch() [1/2]
bool hitPatch (const polyPatch & , trackingData & td, const label patchI, const scalar trackFraction, const tetIndices & tetIs)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 139 of file trackedParticle.C.
References trackedParticle::hitWedgePatch().
Referenced by trackedParticle::hitWallPatch(), trackedParticle::k(), and trackedParticle::move().
hitWedgePatch()
void hitWedgePatch (const wedgePolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a wedge.
Definition at line 152 of file trackedParticle.C.
References trackedParticle::hitSymmetryPlanePatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by trackedParticle::hitPatch(), and trackedParticle::k().
hitSymmetryPlanePatch()
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a.
symmetry plane
Definition at line 163 of file trackedParticle.C.
References trackedParticle::hitSymmetryPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by trackedParticle::hitWedgePatch(), and trackedParticle::k().
hitSymmetryPatch()
void hitSymmetryPatch (const symmetryPolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a.
symmetry patch
Definition at line 174 of file trackedParticle.C.
References trackedParticle::hitCyclicPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by trackedParticle::hitSymmetryPlanePatch(), and trackedParticle::k().
hitCyclicPatch()
void hitCyclicPatch (const cyclicPolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a cyclic.
Definition at line 185 of file trackedParticle.C.
References trackedParticle::hitProcessorPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by trackedParticle::hitSymmetryPatch(), and trackedParticle::k().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a processorPatch
Definition at line 196 of file trackedParticle.C.
References trackedParticle::hitWallPatch(), and particle< Type >::TrackingData< CloudType >::switchProcessor.
Referenced by trackedParticle::hitCyclicPatch(), and trackedParticle::k().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & wpp, trackingData & td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 207 of file trackedParticle.C.
References trackedParticle::hitPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by trackedParticle::hitProcessorPatch(), and trackedParticle::k().
hitPatch() [2/2]
void hitPatch (const polyPatch & wpp, trackingData & td)
Overridable function to handle the particle hitting a polyPatch.
Definition at line 219 of file trackedParticle.C.
References trackedParticle::correctAfterParallelTransfer(), and particle< Type >::TrackingData< CloudType >::keepParticle.
correctAfterParallelTransfer()
void correctAfterParallelTransfer (const label patchI, trackingData & td)
Convert processor patch addressing to the global equivalents.
and set the cellI to the face-neighbour
Definition at line 230 of file trackedParticle.C.
References IOstream::check(), trackedParticle::trackingData::featureEdgeVisited_, IOstream::format(), k, Foam::operator<<(), p, and Ostream::write().
Referenced by trackedParticle::hitPatch(), and trackedParticle::k().
Friends And Related Function Documentation
Cloud< trackedParticle >
friend class Cloud< trackedParticle > friend
Definition at line 76 of file trackedParticle.H.
operator<<
Ostream& operator<< (Ostream & , const trackedParticle &) friend
Referenced by trackedParticle::k().
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/trackedParticle/trackedParticle.H
src/mesh/autoMesh/autoHexMesh/trackedParticle/trackedParticle.C