OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
externalDisplacementMeshMover Class Reference abstract
Virtual base class for mesh movers with externally provided displacement field giving the boundary conditions. Move the mesh from the current location to a new location (so modify the mesh; v.s. motionSolver that only returns the new location).
Public Member Functions
TypeName ("externalDisplacementMeshMover")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, externalDisplacementMeshMover, dictionary,(const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement),(dict, baffles, pointDisplacement))
externalDisplacementMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement)
Construct from dictionary and displacement field. Dictionary is.
virtual ~externalDisplacementMeshMover ()
Destructor.
pointVectorField & pointDisplacement ()
Return reference to the point motion displacement field.
const pointVectorField & pointDisplacement () const
Return const reference to the point motion displacement field.
const pointMesh & pMesh () const
const polyMesh & mesh () const
virtual bool move (const dictionary &, const label nAllowableErrors, labelList &checkFaces)=0
Move mesh using current pointDisplacement boundary values.
virtual void movePoints (const pointField &)
Update local data for geometry changes.
virtual void updateMesh (const mapPolyMesh &)
Update local data for topology changes.
Static Public Member Functions
static autoPtr< externalDisplacementMeshMover > New (const word &type, const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement)
Return a reference to the selected meshMover model.
Protected Attributes
List< labelPair > baffles_
Baffles in the mesh.
pointVectorField & pointDisplacement_
Reference to point motion field.
Detailed Description
Virtual base class for mesh movers with externally provided displacement field giving the boundary conditions. Move the mesh from the current location to a new location (so modify the mesh; v.s. motionSolver that only returns the new location).
All mesh movers are expected to read the dictionary settings at invocation of move(), i.e. not cache any settings.
Source files
externalDisplacementMeshMover.H
externalDisplacementMeshMover.C
Definition at line 56 of file externalDisplacementMeshMover.H.
Constructor & Destructor Documentation
externalDisplacementMeshMover()
externalDisplacementMeshMover (const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement)
Construct from dictionary and displacement field. Dictionary is.
allowed to go out of scope!
Definition at line 41 of file externalDisplacementMeshMover.C.
References externalDisplacementMeshMover::New().
~externalDisplacementMeshMover()
~externalDisplacementMeshMover () virtual
Destructor.
Definition at line 91 of file externalDisplacementMeshMover.C.
Member Function Documentation
TypeName()
TypeName ("externalDisplacementMeshMover")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , externalDisplacementMeshMover , dictionary , (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement) , (dict, baffles, pointDisplacement))
New()
Foam::autoPtr< Foam::externalDisplacementMeshMover > New (const word & type, const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement) static
Return a reference to the selected meshMover model.
Definition at line 56 of file externalDisplacementMeshMover.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
Referenced by autoLayerDriver::addLayers(), externalDisplacementMeshMover::externalDisplacementMeshMover(), and displacementMeshMoverMotionSolver::meshMover().
pointDisplacement() [1/2]
pointVectorField& pointDisplacement () inline
Return reference to the point motion displacement field.
Definition at line 137 of file externalDisplacementMeshMover.H.
References externalDisplacementMeshMover::pointDisplacement_.
pointDisplacement() [2/2]
const pointVectorField& pointDisplacement () const inline
Return const reference to the point motion displacement field.
Definition at line 143 of file externalDisplacementMeshMover.H.
References externalDisplacementMeshMover::pointDisplacement_.
pMesh()
const pointMesh& pMesh () const inline
Definition at line 148 of file externalDisplacementMeshMover.H.
References DimensionedField< Type, GeoMesh >::mesh().
Referenced by externalDisplacementMeshMover::mesh().
mesh()
const polyMesh& mesh () const inline
Definition at line 153 of file externalDisplacementMeshMover.H.
References externalDisplacementMeshMover::move(), externalDisplacementMeshMover::movePoints(), externalDisplacementMeshMover::pMesh(), and externalDisplacementMeshMover::updateMesh().
move()
virtual bool move (const dictionary & , const label nAllowableErrors, labelList & checkFaces) pure virtual
Move mesh using current pointDisplacement boundary values.
and current dictionary settings. Return true if succesful (errors on checkFaces less than allowable). Updates pointDisplacement.
Implemented in medialAxisMeshMover.
Referenced by externalDisplacementMeshMover::mesh().
movePoints()
void movePoints (const pointField &) virtual
Update local data for geometry changes.
Reimplemented in medialAxisMeshMover.
Definition at line 97 of file externalDisplacementMeshMover.C.
Referenced by externalDisplacementMeshMover::mesh(), and medialAxisMeshMover::movePoints().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update local data for topology changes.
Reimplemented in medialAxisMeshMover.
Definition at line 103 of file externalDisplacementMeshMover.C.
References List< T >::append(), f1, forAll, and mapPolyMesh::reverseFaceMap().
Referenced by externalDisplacementMeshMover::mesh().
Member Data Documentation
baffles_
List<labelPair> baffles_ protected
Baffles in the mesh.
Definition at line 63 of file externalDisplacementMeshMover.H.
pointDisplacement_
pointVectorField& pointDisplacement_ protected
Reference to point motion field.
Definition at line 66 of file externalDisplacementMeshMover.H.
Referenced by externalDisplacementMeshMover::pointDisplacement().
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/externalDisplacementMeshMover/externalDisplacementMeshMover.H
src/mesh/autoMesh/autoHexMesh/externalDisplacementMeshMover/externalDisplacementMeshMover.C