OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
patchFaceOrientation Class Reference
Transport of orientation for use in PatchEdgeFaceWave.
Public Member Functions
patchFaceOrientation ()
Construct null.
patchFaceOrientation (const label)
Construct from components.
label flipStatus () const
Orientation.
void flip ()
Reverse orientation.
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
void transform (const polyMesh &mesh, const indirectPrimitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
Apply rotation matrix.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label edgeI, const label faceI, const patchFaceOrientation &faceInfo, const scalar tol, TrackingData &td)
Influence of face on edge.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const patchFaceOrientation &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
New information for edge (from e.g. coupled edge)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label faceI, const label edgeI, const patchFaceOrientation &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on face.
template<class TrackingData >
bool equal (const patchFaceOrientation &, TrackingData &) const
Same (like operator==)
bool operator== (const patchFaceOrientation &) const
bool operator!= (const patchFaceOrientation &) const
Friends
Ostream & operator<< (Ostream &, const patchFaceOrientation &)
Istream & operator>> (Istream &, patchFaceOrientation &)
Detailed Description
Transport of orientation for use in PatchEdgeFaceWave.
Source files
patchFaceOrientation.H
patchFaceOrientationI.H
patchFaceOrientation.C
Definition at line 53 of file patchFaceOrientation.H.
Constructor & Destructor Documentation
patchFaceOrientation() [1/2]
patchFaceOrientation () inline
Construct null.
Definition at line 32 of file patchFaceOrientationI.H.
patchFaceOrientation() [2/2]
patchFaceOrientation (const label flipStatus) inline
Construct from components.
Definition at line 39 of file patchFaceOrientationI.H.
Member Function Documentation
flipStatus()
Foam::label flipStatus () const inline
Orientation.
Definition at line 49 of file patchFaceOrientationI.H.
Referenced by patchFaceOrientation::operator==().
flip()
void flip () inline
Reverse orientation.
Definition at line 55 of file patchFaceOrientationI.H.
References orientedSurface::FLIP, and orientedSurface::NOFLIP.
Referenced by meshRefinement::mergeBaffles(), patchFaceOrientation::updateEdge(), and patchFaceOrientation::updateFace().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 69 of file patchFaceOrientationI.H.
References patchFaceOrientation::transform(), and orientedSurface::UNVISITED.
Referenced by patchFaceOrientation::updateEdge(), and patchFaceOrientation::updateFace().
transform()
void transform (const polyMesh & mesh, const indirectPrimitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Apply rotation matrix.
Definition at line 77 of file patchFaceOrientationI.H.
References patchFaceOrientation::updateEdge().
Referenced by patchFaceOrientation::valid().
updateEdge() [1/2]
bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label edgeI, const label faceI, const patchFaceOrientation & faceInfo, const scalar tol, TrackingData & td) inline
Influence of face on edge.
Definition at line 89 of file patchFaceOrientationI.H.
References Foam::e, face::edgeDirection(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), f(), patchFaceOrientation::flip(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), and patchFaceOrientation::valid().
Referenced by meshRefinement::mergeBaffles(), and patchFaceOrientation::transform().
updateEdge() [2/2]
bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const patchFaceOrientation & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
New information for edge (from e.g. coupled edge)
Definition at line 127 of file patchFaceOrientationI.H.
References patchFaceOrientation::flip(), patchFaceOrientation::updateFace(), and patchFaceOrientation::valid().
updateFace()
bool updateFace (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label faceI, const label edgeI, const patchFaceOrientation & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on face.
Definition at line 156 of file patchFaceOrientationI.H.
References Foam::e, face::edgeDirection(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), patchFaceOrientation::equal(), f(), patchFaceOrientation::flip(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), and patchFaceOrientation::valid().
Referenced by patchFaceOrientation::updateEdge().
equal()
bool equal (const patchFaceOrientation & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 198 of file patchFaceOrientationI.H.
References patchFaceOrientation::operator==().
Referenced by patchFaceOrientation::updateFace().
operator==()
bool operator== (const patchFaceOrientation & rhs) const inline
Definition at line 210 of file patchFaceOrientationI.H.
References patchFaceOrientation::flipStatus().
Referenced by patchFaceOrientation::equal().
operator!=()
bool operator!= (const patchFaceOrientation & rhs) const inline
Definition at line 219 of file patchFaceOrientationI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const patchFaceOrientation &) friend
operator>>
Istream& operator>> (Istream & , patchFaceOrientation &) friend
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/meshRefinement/patchFaceOrientation.H
src/mesh/autoMesh/autoHexMesh/meshRefinement/patchFaceOrientationI.H