OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
medialAxisMeshMover Class Reference
Mesh motion solver that uses a medial axis algorithm to work out a fraction between the (nearest point on a) moving surface and the (nearest point on a) fixed surface. This fraction is then used to scale the motion. Use.
Public Member Functions
TypeName ("displacementMedialAxis")
Runtime type information.
medialAxisMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement)
Construct from dictionary and displacement field.
virtual ~medialAxisMeshMover ()
virtual bool move (const dictionary &, const label nAllowableErrors, labelList &checkFaces)
Move mesh using current pointDisplacement boundary values.
virtual void movePoints (const pointField &)
Update local data for geometry changes.
virtual void updateMesh (const mapPolyMesh &)
Update local data for topology changes.
Public Member Functions inherited from externalDisplacementMeshMover
TypeName ("externalDisplacementMeshMover")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, externalDisplacementMeshMover, dictionary,(const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement),(dict, baffles, pointDisplacement))
externalDisplacementMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement)
Construct from dictionary and displacement field. Dictionary is.
virtual ~externalDisplacementMeshMover ()
Destructor.
pointVectorField & pointDisplacement ()
Return reference to the point motion displacement field.
const pointVectorField & pointDisplacement () const
Return const reference to the point motion displacement field.
const pointMesh & pMesh () const
const polyMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from externalDisplacementMeshMover
static autoPtr< externalDisplacementMeshMover > New (const word &type, const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement)
Return a reference to the selected meshMover model.
Protected Attributes inherited from externalDisplacementMeshMover
List< labelPair > baffles_
Baffles in the mesh.
pointVectorField & pointDisplacement_
Reference to point motion field.
Detailed Description
Mesh motion solver that uses a medial axis algorithm to work out a fraction between the (nearest point on a) moving surface and the (nearest point on a) fixed surface. This fraction is then used to scale the motion. Use.
- fixedValue on all moving patches
zeroFixedValue on stationary patches
slip on all slipping patches
Source files
medialAxisMeshMover.H
medialAxisMeshMover.C
Definition at line 58 of file medialAxisMeshMover.H.
Constructor & Destructor Documentation
medialAxisMeshMover()
medialAxisMeshMover (const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement)
Construct from dictionary and displacement field.
Definition at line 1599 of file medialAxisMeshMover.C.
~medialAxisMeshMover()
~medialAxisMeshMover () virtual
Definition at line 1696 of file medialAxisMeshMover.C.
References Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, syncTools::getMasterEdges(), meshRefinement::getMasterEdges(), syncTools::getMasterPoints(), meshRefinement::getMasterPoints(), polyMesh::globalData(), Foam::Info, PointEdgeWave< Type, TrackingData >::iterate(), dictionary::lookup(), dictionary::lookupOrDefault(), Foam::mag(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), medialAxisMeshMover::move(), n, autoLayerDriver::NOEXTRUDE, nPoints, globalMeshData::nTotalPoints(), path(), polyMesh::points(), Foam::Pout, Foam::readScalar(), Foam::reduce(), autoPtr< T >::reset(), List< T >::size(), timeName, autoPtr< T >::valid(), and Vector< Cmpt >::zero.
Member Function Documentation
TypeName()
TypeName ("displacementMedialAxis")
Runtime type information.
move()
bool move (const dictionary & moveDict, const label nAllowableErrors, labelList & checkFaces) virtual
Move mesh using current pointDisplacement boundary values.
Return true if succesful (errors on checkFaces less than allowable). Updates pointDisplacement.
Name of field specifying min thickness
Move mesh according to calculated displacement
Implements externalDisplacementMeshMover.
Definition at line 2109 of file medialAxisMeshMover.C.
References autoLayerDriver::EXTRUDE, forAll, dictionary::lookup(), objectRegistry::lookupObject(), Foam::mag(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), autoLayerDriver::NOEXTRUDE, PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), and points.
Referenced by medialAxisMeshMover::~medialAxisMeshMover().
movePoints()
void movePoints (const pointField & p) virtual
Update local data for geometry changes.
Reimplemented from externalDisplacementMeshMover.
Definition at line 2179 of file medialAxisMeshMover.C.
References externalDisplacementMeshMover::movePoints().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update local data for topology changes.
Reimplemented from externalDisplacementMeshMover.
Definition at line 271 of file medialAxisMeshMover.H.
References notImplemented.
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/externalDisplacementMeshMover/medialAxisMeshMover.H
src/mesh/autoMesh/autoHexMesh/externalDisplacementMeshMover/medialAxisMeshMover.C