OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
snapParameters Class Reference
Simple container to keep together snap specific information.
Public Member Functions
snapParameters (const dictionary &dict)
Construct from dictionary.
label nSmoothPatch () const
Number of patch smoothing iterations before finding.
scalar snapTol () const
Relative distance for points to be attracted by surface.
label nSmoothDispl () const
Number of mesh displacement smoothing iterations.
label nSnap () const
Maximum number of snapping relaxation iterations. Should stop.
label nFeatureSnap () const
Switch explicitFeatureSnap () const
Switch implicitFeatureSnap () const
Switch multiRegionFeatureSnap () const
Switch detectNearSurfacesSnap () const
Detailed Description
Simple container to keep together snap specific information.
Source files
snapParameters.H
snapParameters.C
Definition at line 52 of file snapParameters.H.
Constructor & Destructor Documentation
snapParameters()
snapParameters (const dictionary & dict)
Construct from dictionary.
Definition at line 31 of file snapParameters.C.
Member Function Documentation
nSmoothPatch()
label nSmoothPatch () const inline
Number of patch smoothing iterations before finding.
correspondence to surface
Definition at line 98 of file snapParameters.H.
Referenced by autoSnapDriver::preSmoothPatch().
snapTol()
scalar snapTol () const inline
Relative distance for points to be attracted by surface.
feature point or edge. True distance is this factor times local maximum edge length.
Definition at line 107 of file snapParameters.H.
Referenced by autoSnapDriver::calcSnapDistance().
nSmoothDispl()
label nSmoothDispl () const inline
Number of mesh displacement smoothing iterations.
Definition at line 113 of file snapParameters.H.
References snapParameters::nSnap().
Referenced by autoSnapDriver::smoothDisplacement().
nSnap()
label nSnap () const inline
Maximum number of snapping relaxation iterations. Should stop.
before upon reaching a correct mesh.
Definition at line 120 of file snapParameters.H.
Referenced by snapParameters::nSmoothDispl(), autoSnapDriver::preSmoothPatch(), and autoSnapDriver::scaleMesh().
nFeatureSnap()
label nFeatureSnap () const inline
Definition at line 125 of file snapParameters.H.
Referenced by autoSnapDriver::doSnap().
explicitFeatureSnap()
Switch explicitFeatureSnap () const inline
Definition at line 130 of file snapParameters.H.
Referenced by listPlusEqOp< T >::operator()().
implicitFeatureSnap()
Switch implicitFeatureSnap () const inline
Definition at line 135 of file snapParameters.H.
Referenced by listPlusEqOp< T >::operator()().
multiRegionFeatureSnap()
Switch multiRegionFeatureSnap () const inline
Definition at line 140 of file snapParameters.H.
Referenced by listPlusEqOp< T >::operator()().
detectNearSurfacesSnap()
Switch detectNearSurfacesSnap () const inline
Definition at line 145 of file snapParameters.H.
Referenced by autoSnapDriver::doSnap().
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/snapParameters/snapParameters.H
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/snapParameters/snapParameters.C