OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
shellSurfaces Class Reference
Encapsulates queries for volume refinement ('refine all cells within shell').
Public Types
enum refineMode { INSIDE, OUTSIDE, DISTANCE }
Volume refinement controls.
Public Member Functions
shellSurfaces (const searchableSurfaces &allGeometry, const dictionary &shellsDict)
Construct from geometry and dictionary.
label maxLevel () const
Highest shell level.
void findHigherLevel (const pointField &pt, const labelList &ptLevel, labelList &maxLevel) const
Find shell level higher than ptLevel.
Detailed Description
Encapsulates queries for volume refinement ('refine all cells within shell').
Source files
shellSurfaces.H
shellSurfaces.C
Definition at line 52 of file shellSurfaces.H.
Member Enumeration Documentation
refineMode
enum refineMode
Volume refinement controls.
Enumerator
INSIDE
OUTSIDE
DISTANCE
Definition at line 59 of file shellSurfaces.H.
Constructor & Destructor Documentation
shellSurfaces()
shellSurfaces (const searchableSurfaces & allGeometry, const dictionary & shellsDict)
Construct from geometry and dictionary.
Definition at line 362 of file shellSurfaces.C.
References dict, entry::dict(), Foam::endl(), ILList< LListBase, T >::erase(), forAll, dictionary::found(), IOWarningIn, entry::keyword(), dictionary::lookup(), dictionary::lookupEntryPtr(), searchableSurfaces::names(), and dictionary::toc().
Referenced by NamedEnum< directionType, 3 >::names().
Member Function Documentation
maxLevel()
Foam::label maxLevel () const
Highest shell level.
Definition at line 436 of file shellSurfaces.C.
References forAll, and Foam::max().
findHigherLevel()
void findHigherLevel (const pointField & pt, const labelList & ptLevel, labelList & maxLevel) const
Find shell level higher than ptLevel.
Definition at line 448 of file shellSurfaces.C.
References forAll.
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/shellSurfaces/shellSurfaces.H
src/mesh/autoMesh/autoHexMesh/shellSurfaces/shellSurfaces.C