OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
autoLayerDriver Class Reference
All to do with adding layers.
Public Types
enum extrudeMode { NOEXTRUDE, EXTRUDE, EXTRUDEREMOVE }
Extrusion controls.
Public Member Functions
ClassName ("autoLayerDriver")
Runtime type information.
autoLayerDriver (meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch)
Construct from components.
void mergePatchFacesUndo (const layerParameters &layerParams, const dictionary &motionDict)
Merge patch faces on same cell.
void addLayers (const layerParameters &layerParams, const dictionary &motionDict, const labelList &patchIDs, const label nAllowableErrors, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Add cell layers.
void doLayers (const dictionary &shrinkDict, const dictionary &motionDict, const layerParameters &layerParams, const bool preBalance, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Add layers according to the dictionary settings.
Detailed Description
All to do with adding layers.
Source files
autoLayerDriver.H
autoLayerDriver.C
Definition at line 57 of file autoLayerDriver.H.
Member Enumeration Documentation
extrudeMode
enum extrudeMode
Extrusion controls.
Enumerator
NOEXTRUDE
Do not extrude. No layers added.
EXTRUDE
Extrude
EXTRUDEREMOVE
Extrude but afterwards remove added faces locally
Definition at line 64 of file autoLayerDriver.H.
Constructor & Destructor Documentation
autoLayerDriver()
autoLayerDriver (meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch)
Construct from components.
Definition at line 2784 of file autoLayerDriver.C.
References autoLayerDriver::mergePatchFacesUndo().
Member Function Documentation
ClassName()
ClassName ("autoLayerDriver")
Runtime type information.
mergePatchFacesUndo()
void mergePatchFacesUndo (const layerParameters & layerParams, const dictionary & motionDict)
Merge patch faces on same cell.
Definition at line 2799 of file autoLayerDriver.C.
References autoLayerDriver::addLayers(), layerParameters::concaveAngle(), Foam::cos(), Foam::degToRad(), Foam::endl(), layerParameters::featureAngle(), localPointRegion::findDuplicateFacePairs(), forAll, Foam::Info, and primitiveMesh::nFaces().
Referenced by autoLayerDriver::autoLayerDriver().
addLayers()
void addLayers (const layerParameters & layerParams, const dictionary & motionDict, const labelList & patchIDs, const label nAllowableErrors, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Add cell layers.
Definition at line 2851 of file autoLayerDriver.C.
References layerParameters::additionalReporting(), polyMesh::boundaryMesh(), fvMesh::clearOut(), Foam::degToRad(), layerParameters::dict(), autoLayerDriver::doLayers(), primitiveMesh::edges(), Foam::endl(), layerParameters::featureAngle(), layerParameters::finalLayerThicknessRatio(), forAll, addPatchCellLayer::globalEdgeFaces(), Foam::identity(), Foam::Info, Foam::inplaceReorder(), HashSet< Key, Hash >::insert(), IOobject::instance(), meshRefinement::LAYERINFO, Foam::mag(), polyTopoChange::makeMesh(), meshRefinement::makePatch(), layerParameters::maxFaceThicknessRatio(), dictionary::merge(), mesh, layerParameters::meshShrinker(), fvMesh::movePoints(), IOobject::name(), fvMesh::name(), layerParameters::nBufferCellsNoExtrude(), primitiveMesh::nCells(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), externalDisplacementMeshMover::New(), primitiveMesh::nFaces(), layerParameters::nGrow(), primitiveMesh::nInternalFaces(), layerParameters::nLayerIter(), IOobject::NO_READ, nPoints, layerParameters::nRelaxedIter(), layerParameters::numLayers(), Vector< Cmpt >::one, p, UPstream::parRun(), Time::path(), primitiveMesh::pointEdges(), polyMesh::points(), layerParameters::relativeSizes(), Foam::returnReduce(), motionSmootherAlgo::setDisplacement(), polyMesh::setInstance(), addPatchCellLayer::setRefinement(), List< T >::size(), PtrList< T >::size(), HashTable< T, Key, Hash >::size(), dictionary::subDict(), fvMesh::time(), meshRefinement::updateList(), fvMesh::updateMesh(), addPatchCellLayer::updateMesh(), Ostream::write(), regIOobject::write(), fvMesh::write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, and Vector< Cmpt >::zero.
Referenced by autoLayerDriver::mergePatchFacesUndo().
doLayers()
void doLayers (const dictionary & shrinkDict, const dictionary & motionDict, const layerParameters & layerParams, const bool preBalance, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Add layers according to the dictionary settings.
Definition at line 3593 of file autoLayerDriver.C.
References List< T >::append(), polyMesh::boundaryMesh(), motionSmootherAlgo::checkMesh(), polyPatch::coupled(), Foam::endl(), polyPatch::faceCells(), forAll, Foam::Info, patchIdentifier::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), layerParameters::numLayers(), UPstream::parRun(), Foam::returnReduce(), List< T >::size(), PtrList< T >::size(), and WarningIn.
Referenced by autoLayerDriver::addLayers().
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/autoLayerDriver.H
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/autoLayerDriver.C
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/autoLayerDriverShrink.C
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/autoLayerDriverTemplates.C