OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
autoRefineDriver Class Reference
Public Member Functions
ClassName ("autoRefineDriver")
Runtime type information.
autoRefineDriver (meshRefinement &meshRefiner, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch)
Construct from components.
void doRefine (const dictionary &refineDict, const refinementParameters &refineParams, const snapParameters &snapParams, const bool prepareForSnapping, const dictionary &motionDict)
Do all the refinement.
Detailed Description
Source files
autoRefineDriver.H
autoRefineDriver.C
Definition at line 55 of file autoRefineDriver.H.
Constructor & Destructor Documentation
autoRefineDriver()
autoRefineDriver (meshRefinement & meshRefiner, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch)
Construct from components.
Definition at line 55 of file autoRefineDriver.C.
References refinementParameters::allowFreeStandingZoneFaces(), polyMesh::boundaryMesh(), Foam::constant::universal::c, cells, primitiveMesh::cells(), meshRefinement::checkCoupledFaceZones(), HashTable< T, Key, Hash >::clear(), Foam::cos(), cpuTime::cpuTimeIncrement(), refinementParameters::curvature(), Foam::degToRad(), autoRefineDriver::doRefine(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), localPointRegion::findDuplicateFacePairs(), Foam::findIndices(), UILList< LListBase, T >::first(), forAll, surfaceZonesInfo::getNamedSurfaces(), polyMesh::globalData(), Foam::Info, IOobject::instance(), refinementParameters::keepPoints(), Foam::max(), refinementParameters::maxGlobalCells(), refinementParameters::maxLoadUnbalance(), refinementParameters::maxLocalCells(), mesh, meshRefinement::MESH, refinementParameters::minRefineCells(), n, Foam::name(), refinementParameters::nBufferLayers(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, globalMeshData::nTotalCells(), polyBoundaryMesh::patchID(), Time::path(), refinementParameters::planarAngle(), Foam::Pout, Foam::reduce(), meshRefinement::REMOVE, Foam::returnReduce(), List< T >::setSize(), List< T >::size(), syncTools::swapBoundaryCellList(), fvMesh::time(), List< T >::transfer(), refinementParameters::useTopologicalSnapDetection(), Ostream::write(), regIOobject::write(), meshRefinement::writeLevel(), and meshRefinement::WRITEMESH.
Member Function Documentation
ClassName()
ClassName ("autoRefineDriver")
Runtime type information.
doRefine()
void doRefine (const dictionary & refineDict, const refinementParameters & refineParams, const snapParameters & snapParams, const bool prepareForSnapping, const dictionary & motionDict)
Do all the refinement.
Definition at line 1132 of file autoRefineDriver.C.
References Foam::endl(), refinementParameters::findCells(), Foam::Info, mesh, primitiveMesh::nCells(), Foam::nl, and UPstream::parRun().
Referenced by autoRefineDriver::autoRefineDriver().
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/autoRefineDriver.H
src/mesh/autoMesh/autoHexMesh/autoHexMeshDriver/autoRefineDriver.C