OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
lineDivide Class Reference
Divides a line into segments.
Public Member Functions
lineDivide (const curvedEdge &, const label ndiv, const gradingDescriptors &gd=gradingDescriptors())
Construct from components.
const pointField & points () const
Return the points.
const scalarList & lambdaDivisions () const
Return the list of lambda values.
Detailed Description
Divides a line into segments.
Source files
lineDivide.H
lineDivide.C
Definition at line 52 of file lineDivide.H.
Constructor & Destructor Documentation
lineDivide()
lineDivide (const curvedEdge & cedge, const label ndiv, const gradingDescriptors & gd = gradingDescriptors())
Construct from components.
Definition at line 44 of file lineDivide.C.
References Foam::calcGexp(), forAll, curvedEdge::position(), Foam::pow(), and List< T >::size().
Referenced by Foam::calcGexp().
Member Function Documentation
points()
const Foam::pointField & points () const
Return the points.
Definition at line 123 of file lineDivide.C.
lambdaDivisions()
const Foam::scalarList & lambdaDivisions () const
Return the list of lambda values.
Definition at line 129 of file lineDivide.C.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/curvedEdges/lineDivide.H
src/mesh/blockMesh/curvedEdges/lineDivide.C