OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
block Class Reference
Creates a single block of cells from point coordinates, numbers of cells in each direction and an expansion ratio.
Public Member Functions
block (const pointField &blockPointField, const curvedEdgeList &, Istream &)
Construct from components with Istream.
block (const blockDescriptor &)
Construct from a block definition.
autoPtr< block > clone () const
Clone.
~block ()
Destructor.
const blockDescriptor & blockDef () const
Return the block definition.
label vtxLabel (label i, label j, label k) const
Vertex label offset for a particular i,j,k position.
const pointField & points () const
Return the points for filling the block.
const labelListList & cells () const
Return the cells for filling the block.
const labelListListList & boundaryPatches () const
Return the boundary patch faces for the block.
void clearGeom ()
Clear geometry (internal points, cells, boundaryPatches)
Public Member Functions inherited from blockDescriptor
blockDescriptor (const cellShape &, const pointField &blockPointField, const curvedEdgeList &, const Vector< label > &meshDensity, const UList< gradingDescriptors > &expand, const word &zoneName="")
Construct from components. Optional cellSet/zone name.
blockDescriptor (const pointField &blockPointField, const curvedEdgeList &, Istream &)
Construct from Istream.
autoPtr< blockDescriptor > clone () const
Clone.
~blockDescriptor ()
Destructor.
const pointField & blockPointField () const
Reference to point field defining the block mesh.
const cellShape & blockShape () const
Return the block shape.
const List< List< point > > & blockEdgePoints () const
Return the block points along each edge.
const scalarListList & blockEdgeWeights () const
Return the weightings along each edge.
const Vector< label > & meshDensity () const
Return the mesh density (number of cells) in the i,j,k directions.
const word & zoneName () const
Return the (optional) zone name.
label nPoints () const
Return the number of points.
label nCells () const
Return the number of cells.
const point & blockPoint (const label i) const
Return block point at local label i.
Friends
Ostream & operator<< (Ostream &, const block &)
Detailed Description
Creates a single block of cells from point coordinates, numbers of cells in each direction and an expansion ratio.
Note
The vertices and cells for filling the block are demand-driven.
Source files
block.H
block.C
blockCreate.C
Definition at line 63 of file block.H.
Constructor & Destructor Documentation
block() [1/2]
block (const pointField & blockPointField, const curvedEdgeList & edges, Istream & is)
Construct from components with Istream.
Definition at line 32 of file block.C.
block() [2/2]
block (const blockDescriptor & blockDesc)
Construct from a block definition.
Definition at line 45 of file block.C.
~block()
~block ()
Destructor.
Definition at line 56 of file block.C.
Referenced by block::clone().
Member Function Documentation
clone()
autoPtr<block> clone () const inline
Clone.
Definition at line 112 of file block.H.
References notImplemented, and block::~block().
blockDef()
const blockDescriptor& blockDef () const inline
Return the block definition.
Definition at line 128 of file block.H.
References block::boundaryPatches(), block::cells(), block::clearGeom(), k, block::operator<<, block::points(), and block::vtxLabel().
vtxLabel()
Foam::label vtxLabel (label i, label j, label k) const
Vertex label offset for a particular i,j,k position.
Definition at line 31 of file blockCreate.C.
References blockDescriptor::blockEdgePoints(), blockDescriptor::blockEdgeWeights(), blockDescriptor::blockPoint(), List< T >::clear(), k, blockDescriptor::meshDensity(), blockDescriptor::nCells(), blockDescriptor::nPoints(), p, List< T >::setSize(), x, Vector< Cmpt >::x(), y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by block::blockDef().
points()
const Foam::pointField & points () const
Return the points for filling the block.
Definition at line 62 of file block.C.
References UList< T >::empty().
Referenced by block::blockDef(), and Foam::operator<<().
cells()
const Foam::labelListList & cells () const
Return the cells for filling the block.
Definition at line 73 of file block.C.
References UList< T >::empty().
Referenced by block::blockDef(), and Foam::operator<<().
boundaryPatches()
const Foam::labelListListList & boundaryPatches () const
Return the boundary patch faces for the block.
Definition at line 84 of file block.C.
References UList< T >::empty().
Referenced by block::blockDef(), and Foam::operator<<().
clearGeom()
void clearGeom ()
Clear geometry (internal points, cells, boundaryPatches)
Definition at line 469 of file blockCreate.C.
References List< T >::clear().
Referenced by block::blockDef().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const block &) friend
Referenced by block::blockDef().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/block/block.H
src/mesh/blockMesh/block/block.C
src/mesh/blockMesh/block/blockCreate.C