OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
blockMesh Class Reference
A multi-block mesh generator.
Public Member Functions
blockMesh (const IOdictionary &, const word &regionName)
Construct from IOdictionary.
~blockMesh ()
Destructor.
const pointField & blockPointField () const
Reference to point field defining the block mesh.
const polyMesh & topology () const
const curvedEdgeList & edges () const
scalar scaleFactor () const
The scaling factor used to convert to metres.
const pointField & points () const
The points for the entire mesh.
const cellShapeList & cells () const
const faceListList & patches () const
PtrList< dictionary > patchDicts () const
Get patch information from the topology mesh.
wordList patchNames () const
label numZonedBlocks () const
Number of blocks with specified zones.
void clearGeom ()
Clear geometry (internal points, cells, boundaryPatches)
void writeTopology (Ostream &) const
Writes edges of blockMesh in OBJ format.
Public Member Functions inherited from PtrList< T >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element. Return old element (can be NULL).
autoPtr< T > set (const label, const autoPtr< T > &)
autoPtr< T > set (const label, const tmp< T > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
PtrList< T > & operator= (const PtrList< T > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
Static Public Member Functions
static void verbose (const bool on=true)
Enable/disable verbose information about the progress.
Additional Inherited Members
Public Types inherited from PtrList< T >
typedef T value_type
Type of values the PtrList contains.
typedef T & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from PtrList< T >
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
A multi-block mesh generator.
Note
The vertices, cells and patches for filling the blocks are demand-driven.
Source files
blockMesh.H
blockMesh.C
blockMeshCheck.C
blockMeshCreate.C
blockMeshMerge.C
blockMeshTopology.C
Definition at line 58 of file blockMesh.H.
Constructor & Destructor Documentation
blockMesh()
blockMesh (const IOdictionary & dict, const word & regionName)
Construct from IOdictionary.
Definition at line 35 of file blockMesh.C.
~blockMesh()
~blockMesh ()
Destructor.
Definition at line 47 of file blockMesh.C.
Member Function Documentation
blockPointField()
const Foam::pointField & blockPointField () const
Reference to point field defining the block mesh.
these points have not been scaled by scaleFactor
Definition at line 61 of file blockMesh.C.
topology()
const Foam::polyMesh & topology () const
Definition at line 67 of file blockMesh.C.
References Foam::exit(), Foam::FatalError, and FatalErrorIn.
Referenced by blockMesh::patchDicts(), blockMesh::patchNames(), and blockMesh::writeTopology().
edges()
const curvedEdgeList& edges () const inline
Definition at line 168 of file blockMesh.H.
References blockMesh::cells(), blockMesh::clearGeom(), blockMesh::numZonedBlocks(), blockMesh::patchDicts(), blockMesh::patches(), blockMesh::patchNames(), blockMesh::points(), blockMesh::scaleFactor(), blockMesh::verbose(), and blockMesh::writeTopology().
Referenced by blockMesh::writeTopology().
scaleFactor()
Foam::scalar scaleFactor () const
The scaling factor used to convert to metres.
Definition at line 97 of file blockMesh.C.
Referenced by blockMesh::edges().
points()
const Foam::pointField & points () const
The points for the entire mesh.
these points have been scaled by scaleFactor
Definition at line 103 of file blockMesh.C.
References UList< T >::empty().
Referenced by blockMesh::edges().
cells()
const Foam::cellShapeList & cells () const
Definition at line 114 of file blockMesh.C.
References UList< T >::empty().
Referenced by blockMesh::edges().
patches()
const Foam::faceListList & patches () const
Definition at line 125 of file blockMesh.C.
References UList< T >::empty().
Referenced by blockMesh::edges().
patchDicts()
Foam::PtrList< Foam::dictionary > patchDicts () const
Get patch information from the topology mesh.
Definition at line 80 of file blockMesh.C.
References polyMesh::boundaryMesh(), forAll, PtrList< T >::size(), OStringStream::str(), and blockMesh::topology().
Referenced by blockMesh::edges().
patchNames()
Foam::wordList patchNames () const
Definition at line 136 of file blockMesh.C.
References polyMesh::boundaryMesh(), polyBoundaryMesh::names(), and blockMesh::topology().
Referenced by blockMesh::edges().
numZonedBlocks()
Foam::label numZonedBlocks () const
Number of blocks with specified zones.
Definition at line 154 of file blockMesh.C.
References forAll, and PtrList< T >::size().
Referenced by blockMesh::edges().
clearGeom()
void clearGeom ()
Clear geometry (internal points, cells, boundaryPatches)
Definition at line 283 of file blockMeshCreate.C.
References forAll.
Referenced by blockMesh::edges().
verbose()
void verbose (const bool on = true) static
Enable/disable verbose information about the progress.
Definition at line 55 of file blockMesh.C.
Referenced by blockMesh::edges().
writeTopology()
void writeTopology (Ostream & os) const
Writes edges of blockMesh in OBJ format.
Definition at line 170 of file blockMesh.C.
References Foam::e, blockMesh::edges(), primitiveMesh::edges(), edge::end(), Foam::endl(), forAll, polyMesh::points(), edge::start(), blockMesh::topology(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by blockMesh::edges().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockMesh/blockMesh.H
src/mesh/blockMesh/blockMesh/blockMesh.C
src/mesh/blockMesh/blockMesh/blockMeshCheck.C
src/mesh/blockMesh/blockMesh/blockMeshCreate.C
src/mesh/blockMesh/blockMesh/blockMeshMerge.C
src/mesh/blockMesh/blockMesh/blockMeshTopology.C