OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MeshWave< Type, TrackingData > Class Template Reference
FaceCellWave plus data.
Public Member Functions
MeshWave (const polyMesh &mesh, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
MeshWave (const polyMesh &mesh, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, const List< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh, list of changed faces with the Type.
const List< Type > & allFaceInfo () const
Get allFaceInfo.
const List< Type > & allCellInfo () const
Get allCellInfo.
const TrackingData & data () const
Additional data to be passed into container.
label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
label getUnsetCells () const
Get number of unvisited cells, i.e. cells that were not (yet)
label getUnsetFaces () const
Get number of unvisited faces.
Detailed Description
template<class Type, class TrackingData = int>
class Foam::MeshWave< Type, TrackingData >
FaceCellWave plus data.
Source files
MeshWave.H
MeshWave.C
Definition at line 56 of file MeshWave.H.
Constructor & Destructor Documentation
MeshWave() [1/2]
MeshWave (const polyMesh & mesh, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 42 of file MeshWave.C.
MeshWave() [2/2]
MeshWave (const polyMesh & mesh, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, const List< Type > & allCellInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh, list of changed faces with the Type.
for these faces and initial field. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 69 of file MeshWave.C.
Member Function Documentation
allFaceInfo()
const List<Type>& allFaceInfo () const inline
Get allFaceInfo.
Definition at line 119 of file MeshWave.H.
Referenced by inverseFaceDistanceDiffusivity::correct(), patchDataWave< TransferType >::correct(), and wallLayerCells::wallLayerCells().
allCellInfo()
const List<Type>& allCellInfo () const inline
Get allCellInfo.
Definition at line 125 of file MeshWave.H.
Referenced by inverseFaceDistanceDiffusivity::correct(), and wallLayerCells::wallLayerCells().
data()
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 131 of file MeshWave.H.
References FaceCellWave< Type, TrackingData >::data(), MeshWave< Type, TrackingData >::getUnsetCells(), FaceCellWave< Type, TrackingData >::getUnsetCells(), MeshWave< Type, TrackingData >::iterate(), and FaceCellWave< Type, TrackingData >::iterate().
Referenced by wallLayerCells::wallLayerCells().
iterate()
label iterate (const label maxIter) inline
Iterate until no changes or maxIter reached. Returns actual.
number of iterations.
Definition at line 138 of file MeshWave.H.
Referenced by MeshWave< Type, TrackingData >::data(), and wallLayerCells::wallLayerCells().
getUnsetCells()
label getUnsetCells () const inline
Get number of unvisited cells, i.e. cells that were not (yet)
reached from walking across mesh. This can happen from
not enough iterations done
a disconnected mesh
a mesh without walls in it
Definition at line 148 of file MeshWave.H.
Referenced by MeshWave< Type, TrackingData >::data().
getUnsetFaces()
label getUnsetFaces () const inline
Get number of unvisited faces.
Definition at line 154 of file MeshWave.H.
References FaceCellWave< Type, TrackingData >::getUnsetFaces().
The documentation for this class was generated from the following files:
src/meshTools/algorithms/MeshWave/MeshWave.H
src/meshTools/algorithms/MeshWave/MeshWave.C