OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
combine< Type, TrackingData > Class Template Reference
Combine operator for AMIInterpolation.
Public Member Functions
combine (FaceCellWave< Type, TrackingData > &solver, const cyclicAMIPolyPatch &patch)
void operator() (Type &x, const label faceI, const Type &y, const scalar weight) const
Detailed Description
template<class Type, class TrackingData>
class Foam::combine< Type, TrackingData >
Combine operator for AMIInterpolation.
Definition at line 54 of file FaceCellWave.C.
Constructor & Destructor Documentation
combine()
combine (FaceCellWave< Type, TrackingData > & solver, const cyclicAMIPolyPatch & patch) inline
Definition at line 63 of file FaceCellWave.C.
Member Function Documentation
operator()()
void operator() (Type & x, const label faceI, const Type & y, const scalar weight) const inline
Definition at line 74 of file FaceCellWave.C.
References Foam::abort(), FaceCellWave< Type, TrackingData >::data(), Foam::FatalError, FatalErrorIn, forAll, FaceCellWave< Type, TrackingData >::mesh(), cyclicAMIPolyPatch::neighbPatch(), cyclicAMIPolyPatch::owner(), FaceCellWave< Type, TrackingData >::propagationTol(), FaceCellWave< Type, TrackingData >::setFaceInfo(), polyPatch::start(), and y.
The documentation for this class was generated from the following file:
src/meshTools/algorithms/MeshWave/FaceCellWave.C