OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
FaceCellWave< Type, TrackingData > Class Template Reference
Wave propagation of information through grid. Every iteration information goes through one layer of cells. Templated on information that is transferred.
Public Member Functions
FaceCellWave (const polyMesh &, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, TrackingData &td=dummyTrackData_)
FaceCellWave (const polyMesh &, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
UList< Type > & allFaceInfo ()
Access allFaceInfo.
UList< Type > & allCellInfo ()
Access allCellInfo.
const TrackingData & data () const
Additional data to be passed into container.
const polyMesh & mesh () const
Access mesh.
label getUnsetCells () const
Get number of unvisited cells, i.e. cells that were not (yet)
label getUnsetFaces () const
Get number of unvisited faces.
void setFaceInfo (const labelList &changedFaces, const List< Type > &changedFacesInfo)
Set initial changed faces.
label faceToCell ()
Propagate from face to cell. Returns total number of cells.
label cellToFace ()
Propagate from cell to face. Returns total number of faces.
label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
Static Public Member Functions
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Detailed Description
template<class Type, class TrackingData = int>
class Foam::FaceCellWave< Type, TrackingData >
Wave propagation of information through grid. Every iteration information goes through one layer of cells. Templated on information that is transferred.
Handles parallel and cyclics and non-parallel cyclics.
Note: whether to propagate depends on the return value of Type::update which returns true (i.e. propagate) if the value changes by more than a certain tolerance. This tolerance can be very strict for normal face-cell and parallel cyclics (we use a value of 0.01 just to limit propagation of small changes) but for non-parallel cyclics this tolerance can be critical and if chosen too small can lead to non-convergence.
Source files
FaceCellWave.H
FaceCellWave.C
Definition at line 74 of file FaceCellWave.H.
Constructor & Destructor Documentation
FaceCellWave() [1/2]
FaceCellWave (const polyMesh & mesh, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, TrackingData & td = dummyTrackData_)
Definition at line 818 of file FaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, and UList< T >::size().
FaceCellWave() [2/2]
FaceCellWave (const polyMesh & mesh, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 870 of file FaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, and UList< T >::size().
Member Function Documentation
propagationTol()
static scalar propagationTol () inline static
Access to tolerance.
Definition at line 250 of file FaceCellWave.H.
Referenced by combine< Type, TrackingData >::operator()().
setPropagationTol()
static void setPropagationTol (const scalar tol) inline static
Change tolerance.
Definition at line 256 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::allCellInfo(), and FaceCellWave< Type, TrackingData >::allFaceInfo().
allFaceInfo()
UList<Type>& allFaceInfo () inline
Access allFaceInfo.
Definition at line 294 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::setPropagationTol().
allCellInfo()
UList<Type>& allCellInfo () inline
Access allCellInfo.
Definition at line 300 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::setPropagationTol().
data()
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 306 of file FaceCellWave.H.
Referenced by MeshWave< Type, TrackingData >::data(), structuredDecomp::decompose(), combine< Type, TrackingData >::operator()(), and Foam::fvc::sweep().
mesh()
const polyMesh& mesh () const inline
Access mesh.
Definition at line 312 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::cellToFace(), FaceCellWave< Type, TrackingData >::faceToCell(), FaceCellWave< Type, TrackingData >::getUnsetCells(), FaceCellWave< Type, TrackingData >::getUnsetFaces(), FaceCellWave< Type, TrackingData >::iterate(), and FaceCellWave< Type, TrackingData >::setFaceInfo().
Referenced by combine< Type, TrackingData >::operator()().
getUnsetCells()
Foam::label getUnsetCells () const
Get number of unvisited cells, i.e. cells that were not (yet)
reached from walking across mesh. This can happen from
not enough iterations done
a disconnected mesh
a mesh without walls in it
Definition at line 946 of file FaceCellWave.C.
Referenced by MeshWave< Type, TrackingData >::data(), and FaceCellWave< Type, TrackingData >::mesh().
getUnsetFaces()
Foam::label getUnsetFaces () const
Get number of unvisited faces.
Definition at line 953 of file FaceCellWave.C.
Referenced by MeshWave< Type, TrackingData >::getUnsetFaces(), and FaceCellWave< Type, TrackingData >::mesh().
setFaceInfo()
void setFaceInfo (const labelList & changedFaces, const List< Type > & changedFacesInfo)
Set initial changed faces.
Definition at line 323 of file FaceCellWave.C.
References cyclicAMIPolyPatch::applyLowWeightCorrection(), polyPatch::boundaryMesh(), Foam::endl(), polyPatch::faceCentres(), PstreamBuffers::finishedSends(), forAll, coupledPolyPatch::forwardT(), cyclicAMIPolyPatch::interpolate(), patchIdentifier::name(), processorPolyPatch::neighbProcNo(), UPstream::nonBlocking, coupledPolyPatch::parallel(), polyPatch::patchInternalList(), polyPatch::patchSlice(), Foam::Pout, globalMeshData::processorPatches(), coupledPolyPatch::separated(), List< T >::size(), polyPatch::start(), Foam::T(), and Foam::transform().
Referenced by hexRef8::consistentSlowRefinement(), FaceCellWave< Type, TrackingData >::mesh(), combine< Type, TrackingData >::operator()(), Foam::fvc::spread(), and Foam::fvc::sweep().
faceToCell()
Foam::label faceToCell ()
Propagate from face to cell. Returns total number of cells.
(over all processors) changed.
Definition at line 962 of file FaceCellWave.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, Foam::Pout, and Foam::reduce().
Referenced by FaceCellWave< Type, TrackingData >::mesh().
cellToFace()
Foam::label cellToFace ()
Propagate from cell to face. Returns total number of faces.
(over all processors) changed. (Faces on processorpatches are counted double)
Definition at line 1047 of file FaceCellWave.C.
References Foam::abort(), cells, Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, UPstream::parRun(), Foam::Pout, and Foam::reduce().
Referenced by FaceCellWave< Type, TrackingData >::mesh().
iterate()
Foam::label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
number of iterations.
Definition at line 1129 of file FaceCellWave.C.
References Foam::endl(), Foam::Info, Foam::nl, and UPstream::parRun().
Referenced by hexRef8::consistentSlowRefinement(), MeshWave< Type, TrackingData >::data(), FaceCellWave< Type, TrackingData >::mesh(), Foam::fvc::spread(), and Foam::fvc::sweep().
The documentation for this class was generated from the following files:
src/meshTools/algorithms/MeshWave/FaceCellWave.H
src/meshTools/algorithms/MeshWave/FaceCellWave.C