OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
patchEdgeFaceRegion Class Reference
Transport of region for use in PatchEdgeFaceWave.
Public Member Functions
patchEdgeFaceRegion ()
Construct null.
patchEdgeFaceRegion (const label)
Construct from origin, distance.
label region () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
void transform (const polyMesh &mesh, const indirectPrimitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
Apply rotation matrix.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label edgeI, const label faceI, const patchEdgeFaceRegion &faceInfo, const scalar tol, TrackingData &td)
Influence of face on edge.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const patchEdgeFaceRegion &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
New information for edge (from e.g. coupled edge)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label faceI, const label edgeI, const patchEdgeFaceRegion &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on face.
template<class TrackingData >
bool equal (const patchEdgeFaceRegion &, TrackingData &) const
Same (like operator==)
bool operator== (const patchEdgeFaceRegion &) const
bool operator!= (const patchEdgeFaceRegion &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceRegion &)
Istream & operator>> (Istream &, patchEdgeFaceRegion &)
Detailed Description
Transport of region for use in PatchEdgeFaceWave.
Set element to -2 to denote blocked.
Source files
patchEdgeFaceRegion.H
patchEdgeFaceRegionI.H
patchEdgeFaceRegion.C
Definition at line 59 of file patchEdgeFaceRegion.H.
Constructor & Destructor Documentation
patchEdgeFaceRegion() [1/2]
patchEdgeFaceRegion () inline
Construct null.
Definition at line 76 of file patchEdgeFaceRegionI.H.
patchEdgeFaceRegion() [2/2]
patchEdgeFaceRegion (const label region) inline
Construct from origin, distance.
Definition at line 84 of file patchEdgeFaceRegionI.H.
Member Function Documentation
region()
Foam::label region () const inline
Definition at line 94 of file patchEdgeFaceRegionI.H.
Referenced by patchEdgeFaceRegion::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 101 of file patchEdgeFaceRegionI.H.
References patchEdgeFaceRegion::transform().
transform()
void transform (const polyMesh & mesh, const indirectPrimitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Apply rotation matrix.
Definition at line 109 of file patchEdgeFaceRegionI.H.
References patchEdgeFaceRegion::updateEdge().
Referenced by patchEdgeFaceRegion::valid().
updateEdge() [1/2]
bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label edgeI, const label faceI, const patchEdgeFaceRegion & faceInfo, const scalar tol, TrackingData & td) inline
Influence of face on edge.
Definition at line 121 of file patchEdgeFaceRegionI.H.
Referenced by meshRefinement::mergeBaffles(), and patchEdgeFaceRegion::transform().
updateEdge() [2/2]
bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const patchEdgeFaceRegion & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
New information for edge (from e.g. coupled edge)
Definition at line 137 of file patchEdgeFaceRegionI.H.
References patchEdgeFaceRegion::updateFace().
updateFace()
bool updateFace (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label faceI, const label edgeI, const patchEdgeFaceRegion & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on face.
Definition at line 152 of file patchEdgeFaceRegionI.H.
References patchEdgeFaceRegion::equal().
Referenced by patchEdgeFaceRegion::updateEdge().
equal()
bool equal (const patchEdgeFaceRegion & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 168 of file patchEdgeFaceRegionI.H.
References patchEdgeFaceRegion::operator==().
Referenced by patchEdgeFaceRegion::updateFace().
operator==()
bool operator== (const patchEdgeFaceRegion & rhs) const inline
Definition at line 180 of file patchEdgeFaceRegionI.H.
References patchEdgeFaceRegion::region().
Referenced by patchEdgeFaceRegion::equal().
operator!=()
bool operator!= (const patchEdgeFaceRegion & rhs) const inline
Definition at line 189 of file patchEdgeFaceRegionI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const patchEdgeFaceRegion &) friend
operator>>
Istream& operator>> (Istream & , patchEdgeFaceRegion &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegion.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegionI.H