OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointEdgePoint Class Reference
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Public Member Functions
pointEdgePoint ()
Construct null.
pointEdgePoint (const point &, const scalar)
Construct from origin, distance.
pointEdgePoint (const pointEdgePoint &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const pointEdgePoint &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const label edgeI, const pointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointI, const pointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const pointEdgePoint &, TrackingData &td) const
Same (like operator==)
bool operator== (const pointEdgePoint &) const
bool operator!= (const pointEdgePoint &) const
Friends
Ostream & operator<< (Ostream &, const pointEdgePoint &)
Istream & operator>> (Istream &, pointEdgePoint &)
Detailed Description
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Source files
pointEdgePoint.H
pointEdgePointI.H
pointEdgePoint.C
Definition at line 59 of file pointEdgePoint.H.
Constructor & Destructor Documentation
pointEdgePoint() [1/3]
pointEdgePoint () inline
Construct null.
Definition at line 121 of file pointEdgePointI.H.
pointEdgePoint() [2/3]
pointEdgePoint (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 130 of file pointEdgePointI.H.
pointEdgePoint() [3/3]
pointEdgePoint (const pointEdgePoint & wpt) inline
Construct as copy.
Definition at line 141 of file pointEdgePointI.H.
Member Function Documentation
origin()
const Foam::point & origin () const inline
Definition at line 150 of file pointEdgePointI.H.
Referenced by pointEdgePoint::operator==().
distSqr()
Foam::scalar distSqr () const inline
Definition at line 156 of file pointEdgePointI.H.
Referenced by pointEdgePoint::operator==(), and pointEdgePoint::sameGeometry().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 163 of file pointEdgePointI.H.
References Vector< scalar >::max, and pointEdgePoint::sameGeometry().
sameGeometry()
bool sameGeometry (const pointEdgePoint & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 172 of file pointEdgePointI.H.
References pointEdgePoint::distSqr(), pointEdgePoint::leaveDomain(), and Foam::mag().
Referenced by pointEdgePoint::valid().
leaveDomain()
void leaveDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 200 of file pointEdgePointI.H.
References pointEdgePoint::transform().
Referenced by pointEdgePoint::sameGeometry().
enterDomain()
void enterDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 226 of file pointEdgePointI.H.
References pointEdgePoint::updatePoint().
Referenced by pointEdgePoint::transform().
transform()
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 213 of file pointEdgePointI.H.
References pointEdgePoint::enterDomain(), and Foam::transform().
Referenced by pointEdgePoint::leaveDomain(), and pointData::transform().
updatePoint() [1/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const label edgeI, const pointEdgePoint & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 241 of file pointEdgePointI.H.
References polyMesh::points().
Referenced by pointEdgePoint::enterDomain(), pointData::updatePoint(), and pointEdgePoint::updatePoint().
updatePoint() [2/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const pointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 257 of file pointEdgePointI.H.
References polyMesh::points(), and pointEdgePoint::updatePoint().
updatePoint() [3/3]
bool updatePoint (const pointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 272 of file pointEdgePointI.H.
References pointEdgePoint::updateEdge().
updateEdge()
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointI, const pointEdgePoint & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 285 of file pointEdgePointI.H.
References edge::centre(), Foam::e, primitiveMesh::edges(), pointEdgePoint::equal(), and polyMesh::points().
Referenced by pointData::updateEdge(), and pointEdgePoint::updatePoint().
equal()
bool equal (const pointEdgePoint & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 301 of file pointEdgePointI.H.
References pointEdgePoint::operator==().
Referenced by pointEdgePoint::updateEdge().
operator==()
bool operator== (const pointEdgePoint & rhs) const inline
Definition at line 312 of file pointEdgePointI.H.
References pointEdgePoint::distSqr(), and pointEdgePoint::origin().
Referenced by pointEdgePoint::equal(), and pointData::operator==().
operator!=()
bool operator!= (const pointEdgePoint & rhs) const inline
Definition at line 319 of file pointEdgePointI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const pointEdgePoint &) friend
operator>>
Istream& operator>> (Istream & , pointEdgePoint &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PointEdgeWave/pointEdgePoint.H
src/meshTools/algorithms/PointEdgeWave/pointEdgePointI.H