OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicACMILduInterfaceField Class Reference
Abstract base class for cyclic ACMI coupled interfaces.
Public Member Functions
TypeName ("cyclicACMILduInterfaceField")
Runtime type information.
cyclicACMILduInterfaceField ()
Construct null.
virtual ~cyclicACMILduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &psiInternal, const direction cmpt) const
Transform given patch internal field.
Public Member Functions inherited from cyclicAMILduInterfaceField
TypeName ("cyclicAMILduInterfaceField")
Runtime type information.
cyclicAMILduInterfaceField ()
Construct null.
virtual ~cyclicAMILduInterfaceField ()
Destructor.
virtual bool doTransform () const =0
Is the transform required.
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual const tensorField & reverseT () const =0
Return neighbour-cell transformation tensor.
virtual int rank () const =0
Return rank of component for transform.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &psiInternal, const direction cmpt) const
Transform given patch internal field.
Detailed Description
Abstract base class for cyclic ACMI coupled interfaces.
Source files
cyclicACMILduInterfaceField.H
cyclicACMILduInterfaceField.C
Definition at line 48 of file cyclicACMILduInterfaceField.H.
Constructor & Destructor Documentation
cyclicACMILduInterfaceField()
cyclicACMILduInterfaceField () inline
Construct null.
Definition at line 62 of file cyclicACMILduInterfaceField.H.
References f(), cyclicACMILduInterfaceField::transformCoupleField(), and cyclicACMILduInterfaceField::~cyclicACMILduInterfaceField().
~cyclicACMILduInterfaceField()
~cyclicACMILduInterfaceField () virtual
Destructor.
Definition at line 39 of file cyclicACMILduInterfaceField.C.
References cyclicACMILduInterfaceField::transformCoupleField().
Referenced by cyclicACMILduInterfaceField::cyclicACMILduInterfaceField().
Member Function Documentation
TypeName()
TypeName ("cyclicACMILduInterfaceField")
Runtime type information.
transformCoupleField() [1/2]
void transformCoupleField (Field< Type > & f) const
Transform given patch field.
Definition at line 95 of file cyclicACMILduInterfaceField.H.
References cyclicAMILduInterfaceField::transformCoupleField().
Referenced by cyclicACMILduInterfaceField::cyclicACMILduInterfaceField(), and cyclicACMILduInterfaceField::~cyclicACMILduInterfaceField().
transformCoupleField() [2/2]
void transformCoupleField (scalarField & psiInternal, const direction cmpt) const
Transform given patch internal field.
Definition at line 46 of file cyclicACMILduInterfaceField.C.
References cyclicAMILduInterfaceField::transformCoupleField().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMILduInterfaceField/cyclicACMILduInterfaceField.H
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMILduInterfaceField/cyclicACMILduInterfaceField.C