OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellInfo Class Reference
Holds information regarding type of cell. Used in inside/outside determination in cellClassification.
Public Member Functions
cellInfo ()
Construct null.
cellInfo (const label)
Construct from cType.
cellInfo (const cellInfo &)
Construct as copy.
label type () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const cellInfo &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &patch, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &patch, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const cellInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const cellInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const cellInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const cellInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const cellInfo &) const
bool operator!= (const cellInfo &) const
Friends
Ostream & operator<< (Ostream &, const cellInfo &)
Istream & operator>> (Istream &, cellInfo &)
Detailed Description
Holds information regarding type of cell. Used in inside/outside determination in cellClassification.
Source files
cellInfo.H
cellInfoI.H
cellInfo.C
Definition at line 54 of file cellInfo.H.
Constructor & Destructor Documentation
cellInfo() [1/3]
cellInfo () inline
Construct null.
Definition at line 96 of file cellInfoI.H.
cellInfo() [2/3]
cellInfo (const label type) inline
Construct from cType.
Definition at line 103 of file cellInfoI.H.
cellInfo() [3/3]
cellInfo (const cellInfo & w2) inline
Construct as copy.
Definition at line 110 of file cellInfoI.H.
Member Function Documentation
type()
label type () const inline
Definition at line 94 of file cellInfo.H.
References cellInfo::enterDomain(), cellInfo::equal(), cellInfo::leaveDomain(), cellInfo::operator!=(), cellInfo::operator<<, cellInfo::operator==(), cellInfo::operator>>, cellInfo::sameGeometry(), cellInfo::transform(), cellInfo::updateCell(), cellInfo::updateFace(), and cellInfo::valid().
Referenced by cellInfo::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 119 of file cellInfoI.H.
References cellClassification::NOTSET, and cellInfo::sameGeometry().
Referenced by cellInfo::type().
sameGeometry()
bool sameGeometry (const polyMesh & , const cellInfo & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 128 of file cellInfoI.H.
References cellInfo::leaveDomain().
Referenced by cellInfo::type(), and cellInfo::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 143 of file cellInfoI.H.
References cellInfo::transform().
Referenced by cellInfo::sameGeometry(), and cellInfo::type().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 167 of file cellInfoI.H.
References cellInfo::updateCell().
Referenced by cellInfo::transform(), and cellInfo::type().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 156 of file cellInfoI.H.
References cellInfo::enterDomain().
Referenced by cellInfo::leaveDomain(), and cellInfo::type().
updateCell()
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const cellInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 180 of file cellInfoI.H.
References cellInfo::updateFace().
Referenced by cellInfo::enterDomain(), and cellInfo::type().
updateFace() [1/2]
bool updateFace (const polyMesh & , const label thisFaceI, const label neighbourCellI, const cellInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 204 of file cellInfoI.H.
Referenced by cellInfo::type(), and cellInfo::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & , const label thisFaceI, const cellInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 227 of file cellInfoI.H.
References cellInfo::equal().
equal()
bool equal (const cellInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 249 of file cellInfoI.H.
References cellInfo::operator==().
Referenced by cellInfo::type(), and cellInfo::updateFace().
operator==()
bool operator== (const cellInfo & rhs) const inline
Definition at line 260 of file cellInfoI.H.
References cellInfo::type().
Referenced by cellInfo::equal(), and cellInfo::type().
operator!=()
bool operator!= (const cellInfo & rhs) const inline
Definition at line 266 of file cellInfoI.H.
Referenced by cellInfo::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const cellInfo &) friend
Referenced by cellInfo::type().
operator>>
Istream& operator>> (Istream & , cellInfo &) friend
Referenced by cellInfo::type().
The documentation for this class was generated from the following files:
src/meshTools/cellClassification/cellInfo.H
src/meshTools/cellClassification/cellInfoI.H