OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
patchWave Class Reference
Takes a set of patches to start MeshWave from. After construction holds distance at cells and distance at patches. Is e.g. used by wallDist to construct volScalarField with correct distance to wall.
Public Member Functions
patchWave (const polyMesh &mesh, const labelHashSet &patchIDs, bool correctWalls=true)
Construct from mesh and patches to initialize to 0 and flag.
virtual ~patchWave ()
Destructor.
virtual void correct ()
Correct for mesh geom/topo changes.
label nUnset () const
const scalarField & distance () const
scalarField & distance ()
Non const access so we can 'transfer' contents for efficiency.
const FieldField< Field, scalar > & patchDistance () const
FieldField< Field, scalar > & patchDistance ()
Public Member Functions inherited from cellDistFuncs
ClassName ("cellDistFuncs")
cellDistFuncs (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
Access mesh.
labelHashSet getPatchIDs (const wordReList &patchNames) const
Return the set of patch IDs corresponding to the given names.
template<class Type >
labelHashSet getPatchIDs () const
Get patchIDs of/derived off certain type (e.g. 'processorPolyPatch')
scalar smallestDist (const point &p, const polyPatch &patch, const label nWallFaces, const labelList &wallFaces, label &meshFaceI) const
Calculate smallest true distance (and face index)
label getPointNeighbours (const primitivePatch &, const label patchFaceI, labelList &) const
Get faces sharing point with face on patch.
label maxPatchSize (const labelHashSet &patchIDs) const
Size of largest patch (out of supplied subset of patches)
label sumPatchSize (const labelHashSet &patchIDs) const
Sum of patch sizes (out of supplied subset of patches).
void correctBoundaryFaceCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
Correct all cells connected to boundary (via face). Sets values in.
void correctBoundaryPointCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
Correct all cells connected to wall (via point). Sets values in.
template<class Type >
Foam::labelHashSet getPatchIDs () const
Detailed Description
Takes a set of patches to start MeshWave from. After construction holds distance at cells and distance at patches. Is e.g. used by wallDist to construct volScalarField with correct distance to wall.
Source files
patchWave.H
patchWave.C
Definition at line 56 of file patchWave.H.
Constructor & Destructor Documentation
patchWave()
patchWave (const polyMesh & mesh, const labelHashSet & patchIDs, bool correctWalls = true)
Construct from mesh and patches to initialize to 0 and flag.
whether or not to correct wall. Calculate for all cells. correctWalls : correct wall (face&point) cells for correct distance, searching neighbours.
Definition at line 135 of file patchWave.C.
References patchWave::correct().
~patchWave()
~patchWave () virtual
Destructor.
Definition at line 154 of file patchWave.C.
Member Function Documentation
correct()
void correct () virtual
Correct for mesh geom/topo changes.
Definition at line 160 of file patchWave.C.
References cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), cellDistFuncs::mesh(), and cellDistFuncs::sumPatchSize().
Referenced by patchWave::patchWave().
nUnset()
label nUnset () const inline
Definition at line 120 of file patchWave.H.
Referenced by patchDist::correct().
distance() [1/2]
const scalarField& distance () const inline
Definition at line 125 of file patchWave.H.
Referenced by patchDist::correct().
distance() [2/2]
scalarField& distance () inline
Non const access so we can 'transfer' contents for efficiency.
Definition at line 131 of file patchWave.H.
patchDistance() [1/2]
const FieldField<Field, scalar>& patchDistance () const inline
Definition at line 136 of file patchWave.H.
Referenced by patchDist::correct().
patchDistance() [2/2]
FieldField<Field, scalar>& patchDistance () inline
Definition at line 141 of file patchWave.H.
The documentation for this class was generated from the following files:
src/meshTools/cellDist/patchWave/patchWave.H
src/meshTools/cellDist/patchWave/patchWave.C