OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellFeatures Class Reference
Cell analysis class.
Public Member Functions
cellFeatures (const primitiveMesh &, const scalar minCos, const label cellI)
Construct from cell in mesh.
~cellFeatures ()
Destructor.
const labelHashSet & featureEdge () const
const faceList & faces () const
const List< DynamicList< label > > & faceMap () const
New to old faceMap. Guaranteed to be shrunk.
bool isFeatureEdge (const label edgeI) const
Is edge a feature edge (uniquely determined since on cell.
bool isFeaturePoint (const label edge0, const label edge1) const
Are two edges connected at feature point?
bool isFeatureVertex (const label faceI, const label vertI) const
Is vertexI on faceI used by two edges that form feature.
Detailed Description
Cell analysis class.
Constructs feature edges and feature points, which are edges/points with and angle > given specification. Can be asked for 'superFaces' which can be used to see if a cell is a 'splitHex'.
Source files
cellFeatures.H
cellFeatures.C
Definition at line 61 of file cellFeatures.H.
Constructor & Destructor Documentation
cellFeatures()
cellFeatures (const primitiveMesh & mesh, const scalar minCos, const label cellI)
Construct from cell in mesh.
Definition at line 381 of file cellFeatures.C.
References primitiveMesh::cellEdges(), forAll, and HashSet< Key, Hash >::insert().
~cellFeatures()
~cellFeatures ()
Destructor.
Definition at line 411 of file cellFeatures.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
featureEdge()
const labelHashSet& featureEdge () const inline
Definition at line 134 of file cellFeatures.H.
Referenced by cellFeatures::faceMap().
faces()
const faceList& faces () const inline
Definition at line 139 of file cellFeatures.H.
Referenced by topoCellLooper::cut().
faceMap()
const List<DynamicList<label> >& faceMap () const inline
New to old faceMap. Guaranteed to be shrunk.
Definition at line 149 of file cellFeatures.H.
References cellFeatures::featureEdge(), HashTable< T, Key, Hash >::found(), cellFeatures::isFeatureEdge(), cellFeatures::isFeaturePoint(), and cellFeatures::isFeatureVertex().
isFeatureEdge()
bool isFeatureEdge (const label edgeI) const inline
Is edge a feature edge (uniquely determined since on cell.
only two faces sharing edge)
Definition at line 163 of file cellFeatures.H.
Referenced by cellFeatures::faceMap().
isFeaturePoint()
bool isFeaturePoint (const label edge0, const label edge1) const
Are two edges connected at feature point?
Is local to face since point might be seen as feature point from one face but not from another.
Definition at line 419 of file cellFeatures.C.
References Foam::abort(), primitiveMesh::edges(), edge::end(), Foam::FatalError, FatalErrorIn, Foam::mag(), primitiveMesh::nEdges(), primitiveMesh::points(), edge::start(), and edge::vec().
Referenced by cellFeatures::faceMap(), and cellFeatures::isFeatureVertex().
isFeatureVertex()
bool isFeatureVertex (const label faceI, const label vertI) const
Is vertexI on faceI used by two edges that form feature.
point
Definition at line 491 of file cellFeatures.C.
References Foam::abort(), Foam::meshTools::edgeOnFace(), primitiveMesh::faces(), Foam::FatalError, FatalErrorIn, forAll, cellFeatures::isFeaturePoint(), primitiveMesh::nFaces(), primitiveMesh::nPoints(), and primitiveMesh::pointEdges().
Referenced by cellFeatures::faceMap().
The documentation for this class was generated from the following files:
src/meshTools/cellFeatures/cellFeatures.H
src/meshTools/cellFeatures/cellFeatures.C