OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
coordinateRotation Class Reference abstract
Abstract base class for coordinate rotation.
Public Member Functions
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, objectRegistry,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()
Destructor.
virtual void clear ()=0
Reset rotation to an identity rotation.
virtual void updateCells (const polyMesh &mesh, const labelList &cells)=0
Update the rotation for a list of cells.
virtual const tensor & R () const =0
Return local-to-global transformation tensor.
virtual const tensor & Rtr () const =0
Return global-to-local transformation tensor.
virtual const vector e1 () const =0
Return local Cartesian x-axis.
virtual const vector e2 () const =0
Return local Cartesian y-axis.
virtual const vector e3 () const =0
Return local Cartesian z-axis.
virtual const tensorField & Tr () const =0
Return local-to-global transformation tensor.
virtual bool uniform () const
Return true if the rotation tensor is uniform.
virtual tmp< vectorField > transform (const vectorField &st) const =0
Transform vectorField using transformation tensor field.
virtual vector transform (const vector &st) const =0
Transform vector using transformation tensor.
virtual tmp< vectorField > invTransform (const vectorField &st) const =0
Inverse transform vectorField using transformation tensor field.
virtual vector invTransform (const vector &st) const =0
Inverse transform vector using transformation tensor.
virtual tmp< tensorField > transformTensor (const tensorField &st) const =0
Transform tensor field using transformation tensorField.
virtual tmp< tensorField > transformTensor (const tensorField &st, const labelList &cellMap) const =0
Transform tensor sub-field using transformation tensorField.
virtual tensor transformTensor (const tensor &st) const =0
Transform tensor using transformation tensorField.
virtual tmp< symmTensorField > transformVector (const vectorField &st) const =0
Transform vectorField using transformation tensorField and return.
virtual symmTensor transformVector (const vector &st) const =0
Transform vector using transformation tensor and return.
virtual void write (Ostream &) const =0
Write.
Static Public Member Functions
static autoPtr< coordinateRotation > New (const dictionary &dict, const objectRegistry &obr)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Protected Member Functions
symmTensor transformPrincipal (const tensor &, const vector &) const
Transform principal.
Detailed Description
Abstract base class for coordinate rotation.
    coordinateRotation
    {
        type        axesRotation
        e1          (1 0 0);
        e2          (0 1 0);
    }
Types of coordinateRotation: 1) axesRotation 2) STARCDRotation 3) localAxesRotation 4) EulerCoordinateRotation
Definition at line 68 of file coordinateRotation.H.
Constructor & Destructor Documentation
~coordinateRotation()
virtual ~coordinateRotation () inline virtual
Destructor.
Definition at line 129 of file coordinateRotation.H.
References cells, coordinateRotation::clear(), coordinateRotation::e1(), coordinateRotation::e2(), coordinateRotation::e3(), mesh, coordinateRotation::R(), coordinateRotation::Rtr(), coordinateRotation::Tr(), and coordinateRotation::updateCells().
Member Function Documentation
transformPrincipal()
Foam::symmTensor transformPrincipal (const tensor & tt, const vector & st) const protected
Transform principal.
Definition at line 43 of file coordinateRotation.C.
References Vector< Cmpt >::x(), Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Vector< Cmpt >::y(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Vector< Cmpt >::z(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
Referenced by axesRotation::transformVector(), and localAxesRotation::transformVector().
TypeName()
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , coordinateRotation , objectRegistry , (const dictionary &dict, const objectRegistry &obr) , (dict, obr))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , coordinateRotation , dictionary , (const dictionary &dict) , (dict))
New() [1/2]
Foam::autoPtr< Foam::coordinateRotation > New (const dictionary & dict, const objectRegistry & obr) static
Select constructed from dictionary and objectRegistry.
Definition at line 32 of file coordinateRotationNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), Foam::nl, and Foam::Pout.
Referenced by coordinateSystem::init().
New() [2/2]
Foam::autoPtr< Foam::coordinateRotation > New (const dictionary & dict) static
Select constructed from dictionary.
Definition at line 71 of file coordinateRotationNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), Foam::nl, and Foam::Pout.
clear()
virtual void clear () pure virtual
Reset rotation to an identity rotation.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
updateCells()
virtual void updateCells (const polyMesh & mesh, const labelList & cells) pure virtual
Update the rotation for a list of cells.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
R()
virtual const tensor& R () const pure virtual
Return local-to-global transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateSystem::init(), and coordinateRotation::~coordinateRotation().
Rtr()
virtual const tensor& Rtr () const pure virtual
Return global-to-local transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
e1()
virtual const vector e1 () const pure virtual
Return local Cartesian x-axis.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
e2()
virtual const vector e2 () const pure virtual
Return local Cartesian y-axis.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
e3()
virtual const vector e3 () const pure virtual
Return local Cartesian z-axis.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
Tr()
virtual const tensorField& Tr () const pure virtual
Return local-to-global transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::~coordinateRotation().
uniform()
virtual bool uniform () const inline virtual
Return true if the rotation tensor is uniform.
Reimplemented in localAxesRotation.
Definition at line 164 of file coordinateRotation.H.
References coordinateRotation::invTransform(), coordinateRotation::transform(), coordinateRotation::transformTensor(), coordinateRotation::transformVector(), and coordinateRotation::write().
transform() [1/2]
virtual tmp<vectorField> transform (const vectorField & st) const pure virtual
Transform vectorField using transformation tensor field.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::uniform().
transform() [2/2]
virtual vector transform (const vector & st) const pure virtual
Transform vector using transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
invTransform() [1/2]
virtual tmp<vectorField> invTransform (const vectorField & st) const pure virtual
Inverse transform vectorField using transformation tensor field.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::uniform().
invTransform() [2/2]
virtual vector invTransform (const vector & st) const pure virtual
Inverse transform vector using transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
transformTensor() [1/3]
virtual tmp<tensorField> transformTensor (const tensorField & st) const pure virtual
Transform tensor field using transformation tensorField.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by fixedCoeff::calcTranformModelData(), DarcyForchheimer::calcTranformModelData(), and coordinateRotation::uniform().
transformTensor() [2/3]
virtual tmp<tensorField> transformTensor (const tensorField & st, const labelList & cellMap) const pure virtual
Transform tensor sub-field using transformation tensorField.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
transformTensor() [3/3]
virtual tensor transformTensor (const tensor & st) const pure virtual
Transform tensor using transformation tensorField.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
transformVector() [1/2]
virtual tmp<symmTensorField> transformVector (const vectorField & st) const pure virtual
Transform vectorField using transformation tensorField and return.
symmetrical tensorField
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::uniform().
transformVector() [2/2]
virtual symmTensor transformVector (const vector & st) const pure virtual
Transform vector using transformation tensor and return.
symmetrical tensor
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
write()
virtual void write (Ostream &) const pure virtual
Write.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by coordinateRotation::uniform().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateRotation/coordinateRotation.H
src/meshTools/coordinateSystems/coordinateRotation/coordinateRotation.C
src/meshTools/coordinateSystems/coordinateRotation/coordinateRotationNew.C