OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallPoint Class Reference
Holds information regarding nearest wall point. Used in wall distance calculation.
Public Member Functions
wallPoint ()
Construct null.
wallPoint (const point &origin, const scalar distSqr)
Construct from origin, distance.
wallPoint (const wallPoint &)
Construct as copy.
const point & origin () const
point & origin ()
scalar distSqr () const
scalar & distSqr ()
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoint &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const wallPoint &, TrackingData &td) const
Same (like operator==)
bool operator== (const wallPoint &) const
bool operator!= (const wallPoint &) const
Friends
Ostream & operator<< (Ostream &, const wallPoint &)
Istream & operator>> (Istream &, wallPoint &)
Detailed Description
Holds information regarding nearest wall point. Used in wall distance calculation.
Source files
wallPoint.H
wallPointI.H
wallPoint.C
Definition at line 63 of file wallPoint.H.
Constructor & Destructor Documentation
wallPoint() [1/3]
wallPoint () inline
Construct null.
Definition at line 85 of file wallPointI.H.
wallPoint() [2/3]
wallPoint (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 92 of file wallPointI.H.
wallPoint() [3/3]
wallPoint (const wallPoint & wpt) inline
Construct as copy.
Definition at line 99 of file wallPointI.H.
Member Function Documentation
origin() [1/2]
const Foam::point & origin () const inline
Definition at line 108 of file wallPointI.H.
Referenced by Foam::operator<<(), wallPoint::operator==(), and Foam::operator>>().
origin() [2/2]
Foam::point & origin () inline
Definition at line 114 of file wallPointI.H.
distSqr() [1/2]
Foam::scalar distSqr () const inline
Definition at line 120 of file wallPointI.H.
Referenced by Foam::operator<<(), Foam::operator>>(), and wallPoint::sameGeometry().
distSqr() [2/2]
Foam::scalar & distSqr () inline
Definition at line 126 of file wallPointI.H.
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 133 of file wallPointI.H.
References wallPoint::sameGeometry().
sameGeometry()
bool sameGeometry (const polyMesh & , const wallPoint & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 142 of file wallPointI.H.
References wallPoint::distSqr(), wallPoint::leaveDomain(), and Foam::mag().
Referenced by wallPoint::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 171 of file wallPointI.H.
References wallPoint::transform().
Referenced by wallPoint::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 199 of file wallPointI.H.
References wallPoint::updateCell().
Referenced by wallPoint::transform().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 185 of file wallPointI.H.
References wallPoint::enterDomain(), and Foam::transform().
Referenced by wallPoint::leaveDomain().
updateCell()
bool updateCell (const polyMesh & mesh, const label thisCellI, const label neighbourFaceI, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 215 of file wallPointI.H.
References primitiveMesh::cellCentres(), and wallPoint::updateFace().
Referenced by wallPoint::enterDomain().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const label neighbourCellI, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 238 of file wallPointI.H.
References primitiveMesh::faceCentres().
Referenced by wallPoint::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 260 of file wallPointI.H.
References wallPoint::equal(), and primitiveMesh::faceCentres().
equal()
bool equal (const wallPoint & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 281 of file wallPointI.H.
References wallPoint::operator==().
Referenced by wallPoint::updateFace().
operator==()
bool operator== (const wallPoint & rhs) const inline
Definition at line 292 of file wallPointI.H.
References wallPoint::origin().
Referenced by wallPoint::equal().
operator!=()
bool operator!= (const wallPoint & rhs) const inline
Definition at line 298 of file wallPointI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const wallPoint &) friend
operator>>
Istream& operator>> (Istream & , wallPoint &) friend
The documentation for this class was generated from the following files:
src/meshTools/cellDist/wallPoint/wallPoint.H
src/meshTools/cellDist/wallPoint/wallPointI.H