OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicAMILduInterfaceField Class Reference abstract
Abstract base class for cyclic AMI coupled interfaces.
Public Member Functions
TypeName ("cyclicAMILduInterfaceField")
Runtime type information.
cyclicAMILduInterfaceField ()
Construct null.
virtual ~cyclicAMILduInterfaceField ()
Destructor.
virtual bool doTransform () const =0
Is the transform required.
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual const tensorField & reverseT () const =0
Return neighbour-cell transformation tensor.
virtual int rank () const =0
Return rank of component for transform.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &psiInternal, const direction cmpt) const
Transform given patch internal field.
Detailed Description
Abstract base class for cyclic AMI coupled interfaces.
Source files
cyclicAMILduInterfaceField.H
cyclicAMILduInterfaceField.C
Definition at line 48 of file cyclicAMILduInterfaceField.H.
Constructor & Destructor Documentation
cyclicAMILduInterfaceField()
cyclicAMILduInterfaceField () inline
Construct null.
Definition at line 60 of file cyclicAMILduInterfaceField.H.
References cyclicAMILduInterfaceField::doTransform(), f(), cyclicAMILduInterfaceField::forwardT(), cyclicAMILduInterfaceField::rank(), cyclicAMILduInterfaceField::reverseT(), cyclicAMILduInterfaceField::transformCoupleField(), and cyclicAMILduInterfaceField::~cyclicAMILduInterfaceField().
~cyclicAMILduInterfaceField()
~cyclicAMILduInterfaceField () virtual
Destructor.
Definition at line 39 of file cyclicAMILduInterfaceField.C.
References cyclicAMILduInterfaceField::transformCoupleField().
Referenced by cyclicAMILduInterfaceField::cyclicAMILduInterfaceField().
Member Function Documentation
TypeName()
TypeName ("cyclicAMILduInterfaceField")
Runtime type information.
doTransform()
virtual bool doTransform () const pure virtual
Is the transform required.
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
Referenced by cyclicACMIGAMGInterfaceField::cyclicACMIGAMGInterfaceField(), cyclicAMIGAMGInterfaceField::cyclicAMIGAMGInterfaceField(), cyclicAMILduInterfaceField::cyclicAMILduInterfaceField(), and cyclicAMILduInterfaceField::transformCoupleField().
forwardT()
virtual const tensorField& forwardT () const pure virtual
Return face transformation tensor.
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
Referenced by cyclicAMILduInterfaceField::cyclicAMILduInterfaceField(), and cyclicAMILduInterfaceField::transformCoupleField().
reverseT()
virtual const tensorField& reverseT () const pure virtual
Return neighbour-cell transformation tensor.
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
Referenced by cyclicAMILduInterfaceField::cyclicAMILduInterfaceField().
rank()
virtual int rank () const pure virtual
Return rank of component for transform.
Implemented in cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicACMIGAMGInterfaceField, and cyclicAMIGAMGInterfaceField.
Referenced by cyclicACMIGAMGInterfaceField::cyclicACMIGAMGInterfaceField(), cyclicAMIGAMGInterfaceField::cyclicAMIGAMGInterfaceField(), and cyclicAMILduInterfaceField::cyclicAMILduInterfaceField().
transformCoupleField() [1/2]
void transformCoupleField (Field< Type > & f) const
Transform given patch field.
Definition at line 108 of file cyclicAMILduInterfaceField.H.
References cyclicAMILduInterfaceField::doTransform(), cyclicAMILduInterfaceField::forwardT(), and Foam::transform().
Referenced by cyclicAMILduInterfaceField::cyclicAMILduInterfaceField(), cyclicACMILduInterfaceField::transformCoupleField(), and cyclicAMILduInterfaceField::~cyclicAMILduInterfaceField().
transformCoupleField() [2/2]
void transformCoupleField (scalarField & psiInternal, const direction cmpt) const
Transform given patch internal field.
Definition at line 46 of file cyclicAMILduInterfaceField.C.
References Foam::component(), Foam::diag(), and Foam::pow().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterfaceField.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterfaceField.C