OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicAMILduInterface Class Reference abstract
An abstract base class for cyclic AMI coupled interfaces.
Public Member Functions
TypeName ("cyclicAMILduInterface")
Runtime type information.
cyclicAMILduInterface ()
Construct null.
virtual ~cyclicAMILduInterface ()
Destructor.
virtual label neighbPatchID () const =0
Return neighbour.
virtual bool owner () const =0
virtual const cyclicAMILduInterface & neighbPatch () const =0
Return processor number.
virtual const AMIPatchToPatchInterpolation & AMI () const =0
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual const tensorField & reverseT () const =0
Return face reverse transformation tensor.
Detailed Description
An abstract base class for cyclic AMI coupled interfaces.
Source files
cyclicAMILduInterface.H
cyclicAMILduInterface.C
Definition at line 49 of file cyclicAMILduInterface.H.
Constructor & Destructor Documentation
cyclicAMILduInterface()
cyclicAMILduInterface () inline
Construct null.
Definition at line 61 of file cyclicAMILduInterface.H.
References cyclicAMILduInterface::AMI(), cyclicAMILduInterface::forwardT(), cyclicAMILduInterface::neighbPatch(), cyclicAMILduInterface::neighbPatchID(), cyclicAMILduInterface::owner(), cyclicAMILduInterface::reverseT(), and cyclicAMILduInterface::~cyclicAMILduInterface().
~cyclicAMILduInterface()
~cyclicAMILduInterface () virtual
Destructor.
Definition at line 38 of file cyclicAMILduInterface.C.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface().
Member Function Documentation
TypeName()
TypeName ("cyclicAMILduInterface")
Runtime type information.
neighbPatchID()
virtual label neighbPatchID () const pure virtual
Return neighbour.
Implemented in cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, cyclicACMIFvPatch, and cyclicAMIFvPatch.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface(), cyclicACMIGAMGInterface::neighbPatchID(), and cyclicAMIGAMGInterface::neighbPatchID().
owner()
virtual bool owner () const pure virtual
Implemented in cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, cyclicACMIFvPatch, and cyclicAMIFvPatch.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface(), cyclicACMIGAMGInterface::owner(), and cyclicAMIGAMGInterface::owner().
neighbPatch()
virtual const cyclicAMILduInterface& neighbPatch () const pure virtual
Return processor number.
Implemented in cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, cyclicACMIFvPatch, and cyclicAMIFvPatch.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface().
AMI()
virtual const AMIPatchToPatchInterpolation& AMI () const pure virtual
Implemented in cyclicACMIFvPatch, cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, and cyclicAMIFvPatch.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface().
forwardT()
virtual const tensorField& forwardT () const pure virtual
Return face transformation tensor.
Implemented in cyclicACMIFvPatch, cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, and cyclicAMIFvPatch.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface(), cyclicACMIGAMGInterface::forwardT(), and cyclicAMIGAMGInterface::forwardT().
reverseT()
virtual const tensorField& reverseT () const pure virtual
Return face reverse transformation tensor.
Implemented in cyclicACMIFvPatch, cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, and cyclicAMIFvPatch.
Referenced by cyclicAMILduInterface::cyclicAMILduInterface(), cyclicACMIGAMGInterface::reverseT(), and cyclicAMIGAMGInterface::reverseT().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterface.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField/cyclicAMILduInterface.C