OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
treeDataFace Class Reference
Encapsulation of data needed to search for faces.
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassName ("treeDataFace")
treeDataFace (const bool cacheBb, const primitiveMesh &, const labelUList &)
Construct from mesh and subset of faces.
treeDataFace (const bool cacheBb, const primitiveMesh &, const Xfer< labelList > &)
Construct from mesh and subset of faces, transferring contents.
treeDataFace (const bool cacheBb, const primitiveMesh &)
Construct from mesh. Uses all faces in mesh.
treeDataFace (const bool cacheBb, const polyPatch &)
Construct from mesh. Uses all faces in patch.
const labelList & faceLabels () const
const primitiveMesh & mesh () const
label size () const
pointField shapePoints () const
Get representative point cloud for all shapes inside.
volumeType getVolumeType (const indexedOctree< treeDataFace > &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does (bb of) shape at index overlap bb.
Detailed Description
Encapsulation of data needed to search for faces.
Source files
treeDataFace.H
treeDataFace.C
Definition at line 58 of file treeDataFace.H.
Constructor & Destructor Documentation
treeDataFace() [1/4]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, const labelUList & faceLabels)
Construct from mesh and subset of faces.
Definition at line 83 of file treeDataFace.C.
Referenced by treeDataFace::treeDataFace().
treeDataFace() [2/4]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, const Xfer< labelList > & faceLabels)
Construct from mesh and subset of faces, transferring contents.
Definition at line 99 of file treeDataFace.C.
References treeDataFace::treeDataFace().
treeDataFace() [3/4]
treeDataFace (const bool cacheBb, const primitiveMesh & mesh)
Construct from mesh. Uses all faces in mesh.
Definition at line 115 of file treeDataFace.C.
References treeDataFace::treeDataFace().
treeDataFace() [4/4]
treeDataFace (const bool cacheBb, const polyPatch & patch)
Construct from mesh. Uses all faces in patch.
Definition at line 130 of file treeDataFace.C.
References treeDataFace::findNearestOp::findNearestOp().
Member Function Documentation
ClassName()
ClassName ("treeDataFace")
faceLabels()
const labelList& faceLabels () const inline
Definition at line 179 of file treeDataFace.H.
Referenced by patchProbes::findElements(), meshSearch::findNearestBoundaryFace(), and treeDataFace::findNearestOp::operator()().
mesh()
const primitiveMesh& mesh () const inline
Definition at line 184 of file treeDataFace.H.
Referenced by treeDataFace::findNearestOp::operator()().
size()
label size () const inline
Definition at line 189 of file treeDataFace.H.
References treeDataFace::getVolumeType(), treeDataFace::overlaps(), treeDataFace::shapePoints(), and List< T >::size().
shapePoints()
Foam::pointField shapePoints () const
Get representative point cloud for all shapes inside.
(one point per shape)
Definition at line 168 of file treeDataFace.C.
References forAll, and treeDataFace::getVolumeType().
Referenced by treeDataFace::size().
getVolumeType()
Foam::volumeType getVolumeType (const indexedOctree< treeDataFace > & oc, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 184 of file treeDataFace.C.
References Foam::abort(), Foam::e, edge::end(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, indexedOctree< Type >::getSide(), PointHit< Point >::hit(), PointIndexHit< Point >::index(), Foam::mag(), Foam::magSqr(), n, face::nearestPoint(), treeDataFace::overlaps(), pFaces, Foam::Pout, PointHit< Point >::rawPoint(), Foam::sqr(), edge::start(), volumeType::UNKNOWN, and Vector< Cmpt >::zero.
Referenced by treeDataFace::shapePoints(), and treeDataFace::size().
overlaps()
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does (bb of) shape at index overlap bb.
Definition at line 442 of file treeDataFace.C.
References boundBox::containsAny(), UList< T >::fcIndex(), forAll, triangleFuncs::intersectBb(), and boundBox::overlaps().
Referenced by treeDataFace::getVolumeType(), and treeDataFace::size().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataFace.H
src/meshTools/indexedOctree/treeDataFace.C