OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
treeDataFace::findNearestOp Class Reference
Public Member Functions
findNearestOp (const indexedOctree< treeDataFace > &tree)
void operator() (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &minIndex, point &nearestPoint) const
void operator() (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
Detailed Description
Definition at line 95 of file treeDataFace.H.
Constructor & Destructor Documentation
findNearestOp()
findNearestOp (const indexedOctree< treeDataFace > & tree)
Definition at line 149 of file treeDataFace.C.
References treeDataFace::findIntersectOp::findIntersectOp().
Referenced by treeDataFace::treeDataFace().
Member Function Documentation
operator()() [1/2]
void operator() (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & minIndex, point & nearestPoint) const
Definition at line 499 of file treeDataFace.C.
References PointHit< Point >::distance(), treeDataFace::faceLabels(), primitiveMesh::faces(), forAll, treeDataFace::mesh(), face::nearestPoint(), primitiveMesh::points(), PointHit< Point >::rawPoint(), and Foam::sqr().
operator()() [2/2]
void operator() (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Definition at line 530 of file treeDataFace.C.
References notImplemented.
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataFace.H
src/meshTools/indexedOctree/treeDataFace.C