OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
treeDataPoint::findNearestOp Class Reference
Public Member Functions
findNearestOp (const indexedOctree< treeDataPoint > &tree)
void operator() (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &minIndex, point &nearestPoint) const
void operator() (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
Detailed Description
Definition at line 73 of file treeDataPoint.H.
Constructor & Destructor Documentation
findNearestOp()
findNearestOp (const indexedOctree< treeDataPoint > & tree)
Definition at line 61 of file treeDataPoint.C.
References treeDataPoint::findIntersectOp::findIntersectOp().
Referenced by treeDataPoint::treeDataPoint().
Member Function Documentation
operator()() [1/2]
void operator() (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & minIndex, point & nearestPoint) const
Definition at line 135 of file treeDataPoint.C.
References forAll, Foam::magSqr(), treeDataPoint::pointLabels(), treeDataPoint::points(), and treeDataPoint::useSubset().
operator()() [2/2]
void operator() (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Definition at line 171 of file treeDataPoint.C.
References PointHit< Point >::distance(), forAll, Foam::magSqr(), Vector< Cmpt >::max, Foam::max(), Vector< Cmpt >::min, Foam::min(), treeDataPoint::pointLabels(), treeDataPoint::points(), PointHit< Point >::rawPoint(), Foam::sqr(), treeDataPoint::useSubset(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPoint.H
src/meshTools/indexedOctree/treeDataPoint.C