OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
treeDataFace::findIntersectOp Class Reference
Public Member Functions
findIntersectOp (const indexedOctree< treeDataFace > &tree)
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Calculate intersection of triangle with ray. Sets result.
Detailed Description
Definition at line 126 of file treeDataFace.H.
Constructor & Destructor Documentation
findIntersectOp()
findIntersectOp (const indexedOctree< treeDataFace > & tree)
Definition at line 158 of file treeDataFace.C.
Referenced by treeDataFace::findNearestOp::findNearestOp().
Member Function Documentation
operator()()
bool operator() (const label index, const point & start, const point & end, point & intersectionPoint) const
Calculate intersection of triangle with ray. Sets result.
accordingly
Definition at line 556 of file treeDataFace.C.
References PointHit< Point >::distance(), primitiveMesh::faceCentres(), primitiveMesh::faces(), intersection::HALF_RAY, PointHit< Point >::hit(), PointHit< Point >::hitPoint(), primitiveMesh::points(), and treeBoundBox::posBits().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataFace.H
src/meshTools/indexedOctree/treeDataFace.C