OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
coordinateSystem Class Reference
Base class for other coordinate system specifications.
Public Member Functions
TypeName ("coordinateSystem")
Runtime type information.
coordinateSystem ()
Construct null. This is equivalent to an identity coordinateSystem.
coordinateSystem (const word &name, const coordinateSystem &)
Construct copy with a different name.
coordinateSystem (const word &name, const point &origin, const coordinateRotation &)
Construct from origin and rotation.
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const dictionary &)
Construct from dictionary with a given name.
coordinateSystem (const dictionary &)
Construct from dictionary with default name.
coordinateSystem (const objectRegistry &, const dictionary &)
Construct from dictionary (default name)
coordinateSystem (Istream &)
Construct from Istream.
autoPtr< coordinateSystem > clone () const
Return clone.
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const objectRegistry &obr, const dictionary &dict),(obr, dict))
virtual ~coordinateSystem ()
Destructor.
const word & name () const
Return name.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
const point & origin () const
Return origin.
const coordinateRotation & R () const
Return const reference to co-ordinate rotation.
coordinateRotation & R ()
Return non const reference to co-ordinate rotation.
const coordinateRotation & R (const polyMesh &mesh, const labelList &cells)
Update and return the co-ordinate roation for a list of cells.
virtual dictionary dict (bool ignoreType=false) const
Return as dictionary of entries.
void rename (const word &newName)
Rename.
point & origin ()
Edit access to origin.
virtual void clear ()
Reset origin and rotation to an identity coordinateSystem.
virtual void write (Ostream &) const
Write.
void writeDict (Ostream &, bool subDict=true) const
Write dictionary.
point globalPosition (const point &local) const
Convert from position in local coordinate system to global.
tmp< pointField > globalPosition (const pointField &local) const
Convert from position in local coordinate system to global.
vector globalVector (const vector &local) const
Convert from vector components in local coordinate system to.
tmp< vectorField > globalVector (const vectorField &local) const
Convert from vector components in local coordinate system to.
point localPosition (const point &global) const
Convert from global Cartesian position to position in local.
tmp< pointField > localPosition (const pointField &global) const
Convert from global Cartesian position to position in local.
vector localVector (const vector &global) const
Convert from global Cartesian vector to components in local.
tmp< vectorField > localVector (const vectorField &global) const
Convert from global Cartesian vector to components in local.
Static Public Member Functions
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateSystem > New (const dictionary &dict)
Select constructed from dictionary.
static autoPtr< coordinateSystem > New (Istream &is)
Select constructed from Istream.
Protected Member Functions
virtual vector localToGlobal (const vector &, bool translate) const
Convert from local coordinate system to the global Cartesian system.
virtual tmp< vectorField > localToGlobal (const vectorField &, bool translate) const
Convert from local coordinate system to the global Cartesian system.
virtual vector globalToLocal (const vector &, bool translate) const
Convert from global Cartesian system to the local coordinate system.
virtual tmp< vectorField > globalToLocal (const vectorField &, bool translate) const
Convert from global Cartesian system to the local coordinate system.
void init (const dictionary &)
Init from dict and obr.
void init (const dictionary &, const objectRegistry &)
Init from dictionary.
Friends
bool operator!= (const coordinateSystem &, const coordinateSystem &)
Ostream & operator<< (Ostream &, const coordinateSystem &)
Detailed Description
Base class for other coordinate system specifications.
All systems are defined by an origin point and a co-ordinate rotation.
    coordinateSystem
    {
        type    cartesian;
        origin  (0 0 0);
        coordinateRotation
        {
            type        localAxesRotation;
            e3          (0 0 1);
        }
    }
Types of coordinateRotation: 1) axesRotation 2) STARCDRotation 3) localAxesRotation 4) EulerCoordinateRotation
Type of co-ordinates: 1) cartesian
See also
coordinateSystem and coordinateSystem::New
Source files
coordinateSystem.H
coordinateSystem.C
coordinateSystemNew.C
Definition at line 85 of file coordinateSystem.H.
Constructor & Destructor Documentation
coordinateSystem() [1/8]
coordinateSystem ()
Construct null. This is equivalent to an identity coordinateSystem.
Definition at line 42 of file coordinateSystem.C.
Referenced by coordinateSystem::clone(), and coordinateSystem::coordinateSystem().
coordinateSystem() [2/8]
coordinateSystem (const word & name, const coordinateSystem & cs)
Construct copy with a different name.
Definition at line 52 of file coordinateSystem.C.
References coordinateSystem::coordinateSystem().
coordinateSystem() [3/8]
coordinateSystem (const word & name, const point & origin, const coordinateRotation & cr)
Construct from origin and rotation.
Definition at line 65 of file coordinateSystem.C.
References coordinateSystem::coordinateSystem().
coordinateSystem() [4/8]
coordinateSystem (const word & name, const point & origin, const vector & axis, const vector & dirn)
Construct from origin and 2 axes.
Definition at line 79 of file coordinateSystem.C.
References coordinateSystem::coordinateSystem().
coordinateSystem() [5/8]
coordinateSystem (const word & name, const dictionary & dict)
Construct from dictionary with a given name.
Definition at line 94 of file coordinateSystem.C.
References coordinateSystem::init().
coordinateSystem() [6/8]
coordinateSystem (const dictionary & dict)
Construct from dictionary with default name.
Definition at line 108 of file coordinateSystem.C.
References coordinateSystem::coordinateSystem(), and coordinateSystem::init().
coordinateSystem() [7/8]
coordinateSystem (const objectRegistry & obr, const dictionary & dict)
Construct from dictionary (default name)
With the ability to reference global coordinateSystems
Definition at line 120 of file coordinateSystem.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, coordinateSystem::init(), entry::isDict(), dictionary::lookupEntryPtr(), coordinateSystems::New(), Foam::nl, and entry::stream().
coordinateSystem() [8/8]
coordinateSystem (Istream & is)
Construct from Istream.
The Istream contains a word followed by a dictionary
Definition at line 171 of file coordinateSystem.C.
References coordinateSystem::dict(), and coordinateSystem::init().
~coordinateSystem()
~coordinateSystem () virtual
Destructor.
Definition at line 185 of file coordinateSystem.C.
Referenced by coordinateSystem::clone().
Member Function Documentation
localToGlobal() [1/2]
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
Convert from local coordinate system to the global Cartesian system.
with optional translation for the origin
Reimplemented in cylindricalCS, and cartesianCS.
Definition at line 218 of file coordinateSystem.C.
Referenced by coordinateSystem::dict(), cartesianCS::localToGlobal(), cylindricalCS::localToGlobal(), and coordinateSystem::origin().
localToGlobal() [2/2]
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
Convert from local coordinate system to the global Cartesian system.
with optional translation for the origin
Reimplemented in cylindricalCS, and cartesianCS.
Definition at line 235 of file coordinateSystem.C.
References coordinateSystem::globalToLocal().
globalToLocal() [1/2]
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system.
with optional translation for the origin
Reimplemented in cylindricalCS, and cartesianCS.
Definition at line 252 of file coordinateSystem.C.
Referenced by cartesianCS::globalToLocal(), cylindricalCS::globalToLocal(), coordinateSystem::localToGlobal(), and coordinateSystem::origin().
globalToLocal() [2/2]
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system.
with optional translation for the origin
Reimplemented in cylindricalCS, and cartesianCS.
Definition at line 269 of file coordinateSystem.C.
init() [1/2]
void init (const dictionary & rhs) protected
Init from dict and obr.
Definition at line 329 of file coordinateSystem.C.
References dictionary::lookup(), coordinateRotation::New(), dictionary::readIfPresent(), and dictionary::subDict().
Referenced by coordinateSystem::coordinateSystem().
init() [2/2]
void init (const dictionary & rhs, const objectRegistry & obr) protected
Init from dictionary.
Definition at line 339 of file coordinateSystem.C.
References Foam::constant::physicoChemical::b, IOstream::check(), Foam::endl(), dictionary::lookup(), coordinateRotation::New(), Foam::operator!=(), Foam::operator<<(), coordinateSystem::origin(), Foam::Pout, coordinateRotation::R(), coordinateSystem::R(), dictionary::readIfPresent(), dictionary::subDict(), and coordinateSystem::write().
TypeName()
TypeName ("coordinateSystem")
Runtime type information.
clone()
autoPtr<coordinateSystem> clone () const inline
Return clone.
Definition at line 188 of file coordinateSystem.H.
References coordinateSystem::coordinateSystem(), coordinateSystem::declareRunTimeSelectionTable(), coordinateSystem::dict(), coordinateSystem::New(), and coordinateSystem::~coordinateSystem().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , coordinateSystem , dictionary , (const objectRegistry &obr, const dictionary &dict) , (obr, dict))
Referenced by coordinateSystem::clone().
New() [1/3]
Foam::autoPtr< Foam::coordinateSystem > New (const objectRegistry & obr, const dictionary & dict) static
Select constructed from dictionary and objectRegistry.
Definition at line 32 of file coordinateSystemNew.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), Foam::nl, and dictionary::subDict().
Referenced by coordinateSystem::clone(), coordinateSystem::New(), and searchableSurfaceCollection::searchableSurfaceCollection().
New() [2/3]
Foam::autoPtr< Foam::coordinateSystem > New (const dictionary & dict) static
Select constructed from dictionary.
Definition at line 61 of file coordinateSystemNew.C.
References coordinateSystem::New(), and dictionary::subDict().
New() [3/3]
Foam::autoPtr< Foam::coordinateSystem > New (Istream & is) static
Select constructed from Istream.
Definition at line 72 of file coordinateSystemNew.C.
References dict, and name().
name()
const word& name () const inline
Return name.
Definition at line 236 of file coordinateSystem.H.
Referenced by coordinateSystems::toc().
note() [1/2]
string& note () inline
Return non-constant access to the optional note.
Definition at line 242 of file coordinateSystem.H.
note() [2/2]
const string& note () const inline
Return the optional note.
Definition at line 248 of file coordinateSystem.H.
origin() [1/2]
const point& origin () const inline
Return origin.
Definition at line 254 of file coordinateSystem.H.
Referenced by coordinateSystem::init(), and coordinateSystem::write().
R() [1/3]
const coordinateRotation& R () const inline
Return const reference to co-ordinate rotation.
Definition at line 260 of file coordinateSystem.H.
Referenced by coordinateSystem::init(), and coordinateSystem::R().
R() [2/3]
coordinateRotation& R () inline
Return non const reference to co-ordinate rotation.
Definition at line 266 of file coordinateSystem.H.
References coordinateSystem::R().
R() [3/3]
const coordinateRotation& R (const polyMesh & mesh, const labelList & cells) inline
Update and return the co-ordinate roation for a list of cells.
Definition at line 273 of file coordinateSystem.H.
References coordinateSystem::dict().
dict()
Foam::dictionary dict (bool ignoreType = false) const virtual
Return as dictionary of entries.
Parameters
[in] ignoreType drop type (cartesian, cylindrical, etc) when generating the dictionary
Definition at line 191 of file coordinateSystem.C.
References dictionary::add(), coordinateSystem::localToGlobal(), and Foam::type().
Referenced by coordinateSystem::clone(), coordinateSystem::coordinateSystem(), and coordinateSystem::R().
rename()
void rename (const word & newName) inline
Rename.
Definition at line 291 of file coordinateSystem.H.
origin() [2/2]
point& origin () inline
Edit access to origin.
Definition at line 297 of file coordinateSystem.H.
References coordinateSystem::clear(), coordinateSystem::globalPosition(), coordinateSystem::globalToLocal(), coordinateSystem::globalVector(), coordinateSystem::localPosition(), coordinateSystem::localToGlobal(), coordinateSystem::localVector(), coordinateSystem::operator<<, coordinateSystem::write(), and coordinateSystem::writeDict().
clear()
void clear () virtual
Reset origin and rotation to an identity coordinateSystem.
Also resets the note
Definition at line 285 of file coordinateSystem.C.
References Vector< scalar >::zero.
Referenced by coordinateSystem::origin().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 293 of file coordinateSystem.C.
References Foam::nl, coordinateSystem::origin(), and Foam::type().
Referenced by coordinateSystem::init(), and coordinateSystem::origin().
writeDict()
void writeDict (Ostream & os, bool subDict = true) const
Write dictionary.
Definition at line 300 of file coordinateSystem.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by coordinateSystem::origin(), coordinateSystems::writeData(), and engineValve::writeDict().
globalPosition() [1/2]
point globalPosition (const point & local) const inline
Convert from position in local coordinate system to global.
Cartesian position
Definition at line 320 of file coordinateSystem.H.
Referenced by coordinateSystem::origin(), arcEdge::position(), and sampledPlane::sampledPlane().
globalPosition() [2/2]
tmp<pointField> globalPosition (const pointField & local) const inline
Convert from position in local coordinate system to global.
Cartesian position
Definition at line 327 of file coordinateSystem.H.
globalVector() [1/2]
vector globalVector (const vector & local) const inline
Convert from vector components in local coordinate system to.
global Cartesian vector
Definition at line 334 of file coordinateSystem.H.
Referenced by coordinateSystem::origin(), and sampledPlane::sampledPlane().
globalVector() [2/2]
tmp<vectorField> globalVector (const vectorField & local) const inline
Convert from vector components in local coordinate system to.
global Cartesian vector
Definition at line 341 of file coordinateSystem.H.
localPosition() [1/2]
point localPosition (const point & global) const inline
Convert from global Cartesian position to position in local.
coordinate system
Definition at line 348 of file coordinateSystem.H.
Referenced by coordinateSystem::origin().
localPosition() [2/2]
tmp<pointField> localPosition (const pointField & global) const inline
Convert from global Cartesian position to position in local.
coordinate system
Definition at line 355 of file coordinateSystem.H.
localVector() [1/2]
vector localVector (const vector & global) const inline
Convert from global Cartesian vector to components in local.
coordinate system
Definition at line 362 of file coordinateSystem.H.
Referenced by coordinateSystem::origin().
localVector() [2/2]
tmp<vectorField> localVector (const vectorField & global) const inline
Convert from global Cartesian vector to components in local.
coordinate system
Definition at line 369 of file coordinateSystem.H.
Friends And Related Function Documentation
operator!=
bool operator!= (const coordinateSystem & , const coordinateSystem &) friend
operator<<
Ostream& operator<< (Ostream & , const coordinateSystem &) friend
Referenced by coordinateSystem::origin().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateSystem.H
src/meshTools/coordinateSystems/coordinateSystem.C
src/meshTools/coordinateSystems/coordinateSystemNew.C