OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
treeDataEdge Class Reference
Holds data for octree to work on an edges subset.
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassName ("treeDataEdge")
treeDataEdge (const bool cacheBb, const edgeList &edges, const pointField &points, const labelUList &edgeLabels)
Construct from selected edges. !Holds references to edges and points.
treeDataEdge (const bool cacheBb, const edgeList &edges, const pointField &points, const Xfer< labelList > &edgeLabels)
Construct from selected edges, transferring contents.
const edgeList & edges () const
const pointField & points () const
const labelList & edgeLabels () const
label size () const
pointField shapePoints () const
Get representative point cloud for all shapes inside.
volumeType getVolumeType (const indexedOctree< treeDataEdge > &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does (bb of) shape at index overlap bb.
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
Does (bb of) shape at index overlap bb.
Detailed Description
Holds data for octree to work on an edges subset.
Source files
treeDataEdge.H
treeDataEdge.C
Definition at line 53 of file treeDataEdge.H.
Constructor & Destructor Documentation
treeDataEdge() [1/2]
treeDataEdge (const bool cacheBb, const edgeList & edges, const pointField & points, const labelUList & edgeLabels)
Construct from selected edges. !Holds references to edges and points.
Definition at line 66 of file treeDataEdge.C.
treeDataEdge() [2/2]
treeDataEdge (const bool cacheBb, const edgeList & edges, const pointField & points, const Xfer< labelList > & edgeLabels)
Construct from selected edges, transferring contents.
!Holds references to edges and points
Definition at line 83 of file treeDataEdge.C.
References treeDataEdge::findNearestOp::findNearestOp().
Member Function Documentation
ClassName()
ClassName ("treeDataEdge")
edges()
const edgeList& edges () const inline
Definition at line 169 of file treeDataEdge.H.
Referenced by refinementFeatures::findNearestRegionEdge(), and treeDataEdge::findNearestOp::operator()().
points()
const pointField& points () const inline
Definition at line 174 of file treeDataEdge.H.
Referenced by refinementFeatures::findNearestRegionEdge(), and treeDataEdge::findNearestOp::operator()().
edgeLabels()
const labelList& edgeLabels () const inline
Definition at line 179 of file treeDataEdge.H.
Referenced by treeDataEdge::findNearestOp::operator()().
size()
label size () const inline
Definition at line 184 of file treeDataEdge.H.
References treeDataEdge::getVolumeType(), treeDataEdge::overlaps(), treeDataEdge::shapePoints(), and List< T >::size().
shapePoints()
Foam::pointField shapePoints () const
Get representative point cloud for all shapes inside.
(one point per shape)
Definition at line 117 of file treeDataEdge.C.
References edge::centre(), forAll, and treeDataEdge::getVolumeType().
Referenced by treeDataEdge::size().
getVolumeType()
Foam::volumeType getVolumeType (const indexedOctree< treeDataEdge > & oc, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 134 of file treeDataEdge.C.
References treeDataEdge::overlaps(), and volumeType::UNKNOWN.
Referenced by treeDataEdge::shapePoints(), and treeDataEdge::size().
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does (bb of) shape at index overlap bb.
Definition at line 145 of file treeDataEdge.C.
References edge::end(), treeBoundBox::intersects(), and edge::start().
Referenced by treeDataEdge::getVolumeType(), and treeDataEdge::size().
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Does (bb of) shape at index overlap bb.
Definition at line 163 of file treeDataEdge.C.
References PointHit< Point >::distance(), edge::line(), line< Point, PointRef >::nearestDist(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataEdge.H
src/meshTools/indexedOctree/treeDataEdge.C