OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
localAxesRotation Class Reference
A local coordinate rotation. The cell based rotational field can be created in two ways:
Public Member Functions
TypeName ("localAxesRotation")
Runtime type information.
localAxesRotation (const dictionary &, const objectRegistry &)
Construct from dictionary and objectRegistry.
localAxesRotation (const objectRegistry &, const vector &axis, const point &origin)
Construct from components for all cells.
localAxesRotation (const objectRegistry &, const vector &axis, const point &origin, const List< label > &cells)
Construct from components for list of cells.
localAxesRotation (const dictionary &)
Construct from dictionary.
localAxesRotation (const tensorField &)
Construct from tensor Field.
autoPtr< localAxesRotation > clone () const
Return clone.
virtual ~localAxesRotation ()
Destructor.
virtual void clear ()
Reset rotation to an identity rotation.
virtual void updateCells (const polyMesh &mesh, const labelList &cells)
Update the rotation for a list of cells.
virtual const tensor & R () const
Return local-to-global transformation tensor.
virtual const tensor & Rtr () const
Return global-to-local transformation tensor.
virtual const vector e1 () const
Return local Cartesian x-axis.
virtual const vector e2 () const
Return local Cartesian y-axis.
virtual const vector e3 () const
Return local Cartesian z-axis.
virtual const tensorField & Tr () const
Return local-to-global transformation tensor.
virtual tmp< vectorField > transform (const vectorField &tf) const
Transform vectorField using transformation tensor field.
virtual vector transform (const vector &v) const
Transform vector using transformation tensor.
virtual vector transform (const vector &v, const label cmptI) const
Transform vector using transformation tensor for component.
virtual tmp< vectorField > invTransform (const vectorField &vf) const
Inverse transform vectorField using transformation tensor field.
virtual vector invTransform (const vector &v) const
Inverse transform vector using transformation tensor.
virtual vector invTransform (const vector &v, const label cmptI) const
Inverse transform vector using transformation tensor for component.
virtual bool uniform () const
Return if the rotation is uniform.
virtual tmp< tensorField > transformTensor (const tensorField &tf) const
Transform tensor field using transformation tensorField.
virtual tensor transformTensor (const tensor &t) const
Transform tensor using transformation tensorField.
virtual tmp< tensorField > transformTensor (const tensorField &tf, const labelList &cellMap) const
Transform tensor sub-field using transformation tensorField.
virtual tmp< symmTensorField > transformVector (const vectorField &vf) const
Transform vectorField using transformation tensorField and return.
virtual symmTensor transformVector (const vector &v) const
Transform vector using transformation tensor and return.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from coordinateRotation
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, objectRegistry,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from coordinateRotation
static autoPtr< coordinateRotation > New (const dictionary &dict, const objectRegistry &obr)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Protected Member Functions inherited from coordinateRotation
symmTensor transformPrincipal (const tensor &, const vector &) const
Transform principal.
Detailed Description
A local coordinate rotation. The cell based rotational field can be created in two ways:
1) Each rotational tensor is defined with two vectors (dir and e3) where dir = cellC - origin and e3 is the rotation axis. Per each cell an axesRotation type of rotation is created (cylindrical coordinates)
        localAxesRotation
        {
            type        localAxes;
            e3          (0 0 1);
        }
2) The rotational tensor field is provided at construction
Definition at line 63 of file localAxesRotation.H.
Constructor & Destructor Documentation
localAxesRotation() [1/5]
localAxesRotation (const dictionary & dict, const objectRegistry & obr)
Construct from dictionary and objectRegistry.
Definition at line 96 of file localAxesRotation.C.
References dictionary::found(), dictionary::lookup(), and dictionary::parent().
Referenced by localAxesRotation::clone(), and localAxesRotation::localAxesRotation().
localAxesRotation() [2/5]
localAxesRotation (const objectRegistry & obr, const vector & axis, const point & origin)
Construct from components for all cells.
Definition at line 119 of file localAxesRotation.C.
References localAxesRotation::localAxesRotation().
localAxesRotation() [3/5]
localAxesRotation (const objectRegistry & obr, const vector & axis, const point & origin, const List< label > & cells)
Construct from components for list of cells.
Definition at line 134 of file localAxesRotation.C.
localAxesRotation() [4/5]
localAxesRotation (const dictionary & dict)
Construct from dictionary.
Definition at line 149 of file localAxesRotation.C.
References Foam::exit(), FatalErrorIn, and Foam::FatalIOError.
localAxesRotation() [5/5]
localAxesRotation (const tensorField & R)
Construct from tensor Field.
Definition at line 165 of file localAxesRotation.C.
References localAxesRotation::R().
~localAxesRotation()
virtual ~localAxesRotation () inline virtual
Destructor.
Definition at line 130 of file localAxesRotation.H.
References localAxesRotation::clear(), mesh, and localAxesRotation::updateCells().
Member Function Documentation
TypeName()
TypeName ("localAxesRotation")
Runtime type information.
clone()
autoPtr<localAxesRotation> clone () const inline
Return clone.
Definition at line 123 of file localAxesRotation.H.
References localAxesRotation::localAxesRotation().
clear()
void clear () virtual
Reset rotation to an identity rotation.
Implements coordinateRotation.
Definition at line 177 of file localAxesRotation.C.
References localAxesRotation::updateCells().
Referenced by localAxesRotation::~localAxesRotation().
updateCells()
void updateCells (const polyMesh & mesh, const labelList & cells) virtual
Update the rotation for a list of cells.
Implements coordinateRotation.
Definition at line 187 of file localAxesRotation.C.
References primitiveMesh::cellCentres(), forAll, Foam::mag(), axesRotation::R(), and localAxesRotation::transform().
Referenced by localAxesRotation::clear(), and localAxesRotation::~localAxesRotation().
R()
virtual const tensor& R () const inline virtual
Return local-to-global transformation tensor.
Implements coordinateRotation.
Definition at line 143 of file localAxesRotation.H.
References notImplemented, and Tensor< scalar >::zero.
Referenced by localAxesRotation::localAxesRotation().
Rtr()
virtual const tensor& Rtr () const inline virtual
Return global-to-local transformation tensor.
Implements coordinateRotation.
Definition at line 150 of file localAxesRotation.H.
References notImplemented, and Tensor< scalar >::zero.
Referenced by localAxesRotation::transformTensor().
e1()
virtual const vector e1 () const inline virtual
Return local Cartesian x-axis.
Implements coordinateRotation.
Definition at line 157 of file localAxesRotation.H.
References notImplemented, and Vector< Cmpt >::zero.
e2()
virtual const vector e2 () const inline virtual
Return local Cartesian y-axis.
Implements coordinateRotation.
Definition at line 164 of file localAxesRotation.H.
References notImplemented, and Vector< Cmpt >::zero.
e3()
virtual const vector e3 () const inline virtual
Return local Cartesian z-axis.
Implements coordinateRotation.
Definition at line 171 of file localAxesRotation.H.
Referenced by localAxesRotation::write().
Tr()
virtual const tensorField& Tr () const inline virtual
Return local-to-global transformation tensor.
Implements coordinateRotation.
Definition at line 176 of file localAxesRotation.H.
References localAxesRotation::invTransform(), tf, and localAxesRotation::transform().
transform() [1/3]
Foam::tmp< Foam::vectorField > transform (const vectorField & tf) const virtual
Transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 207 of file localAxesRotation.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and List< T >::size().
Referenced by localAxesRotation::Tr(), localAxesRotation::transform(), and localAxesRotation::updateCells().
transform() [2/3]
Foam::vector transform (const vector & v) const virtual
Transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 225 of file localAxesRotation.C.
References notImplemented, localAxesRotation::transform(), and Vector< Cmpt >::zero.
transform() [3/3]
Foam::vector transform (const vector & v, const label cmptI) const virtual
Transform vector using transformation tensor for component.
Definition at line 236 of file localAxesRotation.C.
References localAxesRotation::invTransform().
invTransform() [1/3]
Foam::tmp< Foam::vectorField > invTransform (const vectorField & vf) const virtual
Inverse transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 246 of file localAxesRotation.C.
References Foam::T().
Referenced by localAxesRotation::invTransform(), localAxesRotation::Tr(), and localAxesRotation::transform().
invTransform() [2/3]
Foam::vector invTransform (const vector & v) const virtual
Inverse transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 254 of file localAxesRotation.C.
References localAxesRotation::invTransform(), notImplemented, and Vector< Cmpt >::zero.
invTransform() [3/3]
Foam::vector invTransform (const vector & v, const label cmptI) const virtual
Inverse transform vector using transformation tensor for component.
Definition at line 265 of file localAxesRotation.C.
References Foam::T(), and localAxesRotation::transformTensor().
uniform()
virtual bool uniform () const inline virtual
Return if the rotation is uniform.
Reimplemented from coordinateRotation.
Definition at line 200 of file localAxesRotation.H.
References localAxesRotation::transformTensor(), localAxesRotation::transformVector(), and localAxesRotation::write().
transformTensor() [1/3]
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & tf) const virtual
Transform tensor field using transformation tensorField.
Implements coordinateRotation.
Definition at line 275 of file localAxesRotation.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, List< T >::size(), and Foam::T().
Referenced by localAxesRotation::invTransform(), localAxesRotation::transformTensor(), and localAxesRotation::uniform().
transformTensor() [2/3]
Foam::tensor transformTensor (const tensor & t) const virtual
Transform tensor using transformation tensorField.
Implements coordinateRotation.
Definition at line 296 of file localAxesRotation.C.
References notImplemented, localAxesRotation::transformTensor(), and Tensor< scalar >::zero.
transformTensor() [3/3]
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & tf, const labelList & cellMap) const virtual
Transform tensor sub-field using transformation tensorField.
Implements coordinateRotation.
Definition at line 310 of file localAxesRotation.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, localAxesRotation::Rtr(), List< T >::size(), Field< Type >::T(), and localAxesRotation::transformVector().
transformVector() [1/2]
Foam::tmp< Foam::symmTensorField > transformVector (const vectorField & vf) const virtual
Transform vectorField using transformation tensorField and return.
symmetrical tensorField
Implements coordinateRotation.
Definition at line 344 of file localAxesRotation.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, fld(), forAll, List< T >::size(), and coordinateRotation::transformPrincipal().
Referenced by localAxesRotation::transformTensor(), and localAxesRotation::uniform().
transformVector() [2/2]
Foam::symmTensor transformVector (const vector & v) const virtual
Transform vector using transformation tensor and return.
symmetrical tensor (R & st & R.T())
Implements coordinateRotation.
Definition at line 368 of file localAxesRotation.C.
References notImplemented, and SymmTensor< Cmpt >::zero.
write()
void write (Ostream & os) const virtual
Write.
Implements coordinateRotation.
Definition at line 380 of file localAxesRotation.C.
References localAxesRotation::e3(), token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by localAxesRotation::uniform().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateRotation/localAxesRotation.H
src/meshTools/coordinateSystems/coordinateRotation/localAxesRotation.C