OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meshSearch Class Reference
Various (local, not parallel) searches on polyMesh; uses (demand driven) octree to search.
Public Member Functions
ClassName ("meshSearch")
meshSearch (const polyMesh &mesh, const polyMesh::cellRepresentation=polyMesh::FACEDIAGTETS)
Construct from components. Constructs bb slightly bigger than.
meshSearch (const polyMesh &mesh, const treeBoundBox &bb, const polyMesh::cellRepresentation=polyMesh::FACEDIAGTETS)
Construct with a custom bounding box. Any mesh element outside.
~meshSearch ()
Destructor.
const polyMesh & mesh () const
polyMesh::cellRepresentation decompMode () const
const indexedOctree< treeDataFace > & boundaryTree () const
Get (demand driven) reference to octree holding all.
const indexedOctree< treeDataCell > & cellTree () const
Get (demand driven) reference to octree holding all cells.
label findNearestCell (const point &location, const label seedCellI=-1, const bool useTreeSearch=true) const
Find nearest cell in terms of cell centre.
label findNearestFace (const point &location, const label seedFaceI=-1, const bool useTreeSearch=true) const
label findCell (const point &location, const label seedCellI=-1, const bool useTreeSearch=true) const
Find cell containing location.
label findNearestBoundaryFace (const point &location, const label seedFaceI=-1, const bool useTreeSearch=true) const
Find nearest boundary face.
pointIndexHit intersection (const point &pStart, const point &pEnd) const
Find first intersection of boundary in segment [pStart, pEnd].
List< pointIndexHit > intersections (const point &pStart, const point &pEnd) const
Find all intersections of boundary within segment pStart .. pEnd.
bool isInside (const point &) const
Determine inside/outside status.
void clearOut ()
delete all storage
void correct ()
Correct for mesh geom/topo changes.
Static Public Attributes
static scalar tol_ = 1e-3
tolerance on linear dimensions
Detailed Description
Various (local, not parallel) searches on polyMesh; uses (demand driven) octree to search.
Source files
meshSearch.H
meshSearch.C
Definition at line 57 of file meshSearch.H.
Constructor & Destructor Documentation
meshSearch() [1/2]
meshSearch (const polyMesh & mesh, const polyMesh::cellRepresentation cellDecompMode = polyMesh::FACEDIAGTETS)
Construct from components. Constructs bb slightly bigger than.
mesh points bb.
Definition at line 507 of file meshSearch.C.
References polyMesh::FACEDIAGTETS, and polyMesh::tetBasePtIs().
meshSearch() [2/2]
meshSearch (const polyMesh & mesh, const treeBoundBox & bb, const polyMesh::cellRepresentation cellDecompMode = polyMesh::FACEDIAGTETS)
Construct with a custom bounding box. Any mesh element outside.
bb will not be found. Up to user to make sure bb extends slightly beyond wanted elements.
Definition at line 525 of file meshSearch.C.
References polyMesh::FACEDIAGTETS, and polyMesh::tetBasePtIs().
~meshSearch()
~meshSearch ()
Destructor.
Definition at line 546 of file meshSearch.C.
Member Function Documentation
ClassName()
ClassName ("meshSearch")
mesh()
const polyMesh& mesh () const inline
Definition at line 194 of file meshSearch.H.
decompMode()
polyMesh::cellRepresentation decompMode () const inline
Definition at line 199 of file meshSearch.H.
References meshSearch::boundaryTree(), meshSearch::cellTree(), meshSearch::clearOut(), meshSearch::correct(), meshSearch::findCell(), meshSearch::findNearestBoundaryFace(), meshSearch::findNearestCell(), meshSearch::findNearestFace(), meshSearch::intersection(), meshSearch::intersections(), and meshSearch::isInside().
Referenced by nearestEqOp::operator()().
boundaryTree()
const Foam::indexedOctree< Foam::treeDataFace > & boundaryTree () const
Get (demand driven) reference to octree holding all.
boundary faces
Definition at line 554 of file meshSearch.C.
References Foam::e, treeBoundBox::extend(), forAll, boundBox::max(), boundBox::min(), and rndGen().
Referenced by meshSearch::decompMode().
cellTree()
const Foam::indexedOctree< Foam::treeDataCell > & cellTree () const
Get (demand driven) reference to octree holding all cells.
Definition at line 607 of file meshSearch.C.
References Foam::e, treeBoundBox::extend(), meshSearch::findNearestCell(), boundBox::max(), boundBox::min(), and rndGen().
Referenced by meshSearch::decompMode(), and nearestEqOp::operator()().
findNearestCell()
Foam::label findNearestCell (const point & location, const label seedCellI = -1, const bool useTreeSearch = true) const
Find nearest cell in terms of cell centre.
Options:
use octree
use linear search
if seed is provided walk. (uses findNearestCellWalk; does not handle holes in domain)
Definition at line 740 of file meshSearch.C.
References meshSearch::findNearestFace().
Referenced by meshSearch::cellTree(), and meshSearch::decompMode().
findNearestFace()
Foam::label findNearestFace (const point & location, const label seedFaceI = -1, const bool useTreeSearch = true) const
Definition at line 765 of file meshSearch.C.
References meshSearch::findCell().
Referenced by meshSearch::decompMode(), meshSearch::findNearestCell(), and mappedPatchBase::findSamples().
findCell()
Foam::label findCell (const point & location, const label seedCellI = -1, const bool useTreeSearch = true) const
Find cell containing location.
If seed provided walks and falls back to linear/tree search. (so handles holes correctly)s Returns -1 if not in domain.
Definition at line 790 of file meshSearch.C.
References meshSearch::findNearestBoundaryFace().
Referenced by meshSearch::decompMode(), and meshSearch::findNearestFace().
findNearestBoundaryFace()
Foam::label findNearestBoundaryFace (const point & location, const label seedFaceI = -1, const bool useTreeSearch = true) const
Find nearest boundary face.
If seed provided walks but then does not pass local minima in distance. Also does not jump from one connected region to the next.
Definition at line 816 of file meshSearch.C.
References indexedOctree< Type >::bb(), PointHit< Point >::distance(), treeDataFace::faceLabels(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), meshSearch::intersection(), Foam::magSqr(), boundBox::max(), boundBox::min(), face::nearestPoint(), indexedOctree< Type >::shapes(), and Foam::sqr().
Referenced by meshSearch::decompMode(), and meshSearch::findCell().
intersection()
Foam::pointIndexHit intersection (const point & pStart, const point & pEnd) const
Find first intersection of boundary in segment [pStart, pEnd].
(so inclusive of endpoints). Always octree for now
Definition at line 884 of file meshSearch.C.
References PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), meshSearch::intersections(), and PointIndexHit< Point >::setIndex().
Referenced by meshSearch::decompMode(), and meshSearch::findNearestBoundaryFace().
intersections()
Foam::List< Foam::pointIndexHit > intersections (const point & pStart, const point & pEnd) const
Find all intersections of boundary within segment pStart .. pEnd.
Always octree for now
Definition at line 901 of file meshSearch.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), Foam::mag(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), and Foam::sqrt().
Referenced by meshSearch::decompMode(), and meshSearch::intersection().
isInside()
bool isInside (const point & p) const
Determine inside/outside status.
Definition at line 948 of file meshSearch.C.
References volumeType::INSIDE.
Referenced by meshSearch::decompMode().
clearOut()
void clearOut ()
delete all storage
Definition at line 955 of file meshSearch.C.
Referenced by meshSearch::decompMode().
correct()
void correct ()
Correct for mesh geom/topo changes.
Definition at line 963 of file meshSearch.C.
Referenced by meshSearch::decompMode().
Member Data Documentation
tol_
scalar tol_ = 1e-3 static
tolerance on linear dimensions
Definition at line 163 of file meshSearch.H.
The documentation for this class was generated from the following files:
src/meshTools/meshSearch/meshSearch.H
src/meshTools/meshSearch/meshSearch.C