OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
minEqOpFace Class Reference
Public Member Functions
void operator() (face &x, const face &y) const
Detailed Description
Definition at line 42 of file localPointRegion.C.
Member Function Documentation
operator()()
void operator() (face & x, const face & y) const inline
Definition at line 46 of file localPointRegion.C.
References Foam::abort(), List< T >::append(), primitiveMesh::cells(), List< T >::clear(), HashTable< T, Key, Hash >::clear(), HashTableCore::end(), Foam::endl(), f(), f1, primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorIn, UList< T >::fcIndex(), HashTable< T, Key, Hash >::find(), Foam::findIndex(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::insert(), primitiveMesh::isInternalFace(), mesh, Foam::min(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), primitiveMesh::nPoints(), UList< T >::rcIndex(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::resize(), List< T >::resize(), Foam::returnReduce(), List< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), syncTools::syncBoundaryFaceList(), and syncTools::syncPointList().
The documentation for this class was generated from the following file:
src/meshTools/regionSplit/localPointRegion.C