OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionCoupledWallGAMGInterfaceField Class Reference
GAMG agglomerated region coupled interface field.
Public Member Functions
TypeName ("regionCoupledWall")
Runtime type information.
regionCoupledWallGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterfaceField)
Construct from GAMG interface and fine level interface field.
regionCoupledWallGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
virtual ~regionCoupledWallGAMGInterfaceField ()
Destructor.
label size () const
Return size.
virtual void updateInterfaceMatrix (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Interface matrix update.
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
GAMG agglomerated region coupled interface field.
Source files
regionCoupledWallGAMGInterfaceField.H
regionCoupledWallGAMGInterfaceField.C
Definition at line 50 of file regionCoupledWallGAMGInterfaceField.H.
Constructor & Destructor Documentation
regionCoupledWallGAMGInterfaceField() [1/2]
regionCoupledWallGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterfaceField)
Construct from GAMG interface and fine level interface field.
Definition at line 53 of file regionCoupledWallGAMGInterfaceField.C.
regionCoupledWallGAMGInterfaceField() [2/2]
regionCoupledWallGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
Definition at line 67 of file regionCoupledWallGAMGInterfaceField.C.
References regionCoupledWallGAMGInterfaceField::~regionCoupledWallGAMGInterfaceField().
~regionCoupledWallGAMGInterfaceField()
~regionCoupledWallGAMGInterfaceField () virtual
Destructor.
Definition at line 84 of file regionCoupledWallGAMGInterfaceField.C.
Referenced by regionCoupledWallGAMGInterfaceField::regionCoupledWallGAMGInterfaceField().
Member Function Documentation
TypeName()
TypeName ("regionCoupledWall")
Runtime type information.
size()
label size () const inline
Return size.
Definition at line 105 of file regionCoupledWallGAMGInterfaceField.H.
References GAMGInterface::size(), and regionCoupledWallGAMGInterfaceField::updateInterfaceMatrix().
updateInterfaceMatrix()
virtual void updateInterfaceMatrix (scalarField & , const scalarField & , const scalarField & , const direction , const Pstream::commsTypes commsType) const inline virtual
Interface matrix update.
Implements lduInterfaceField.
Definition at line 113 of file regionCoupledWallGAMGInterfaceField.H.
Referenced by regionCoupledWallGAMGInterfaceField::size().
The documentation for this class was generated from the following files:
src/meshTools/regionCoupled/GAMG/interfaceFields/regionCoupledGAMGInterfaceField/regionCoupledWallGAMGInterfaceField.H
src/meshTools/regionCoupled/GAMG/interfaceFields/regionCoupledGAMGInterfaceField/regionCoupledWallGAMGInterfaceField.C