OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointTopoDistanceData Class Reference
For use with PointEdgeWave. Determines topological distance to starting points.
Public Member Functions
pointTopoDistanceData ()
Construct null.
pointTopoDistanceData (const label data, const label distance)
Construct from count.
label data () const
label distance () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const pointTopoDistanceData &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const label edgeI, const pointTopoDistanceData &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const pointTopoDistanceData &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointTopoDistanceData &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointI, const pointTopoDistanceData &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const pointTopoDistanceData &, TrackingData &) const
Same (like operator==)
bool operator== (const pointTopoDistanceData &) const
bool operator!= (const pointTopoDistanceData &) const
Friends
Ostream & operator<< (Ostream &, const pointTopoDistanceData &)
Istream & operator>> (Istream &, pointTopoDistanceData &)
Detailed Description
For use with PointEdgeWave. Determines topological distance to starting points.
Source files
pointTopoDistanceData.H
pointTopoDistanceDataI.H
pointTopoDistanceData.C
Definition at line 54 of file pointTopoDistanceData.H.
Constructor & Destructor Documentation
pointTopoDistanceData() [1/2]
pointTopoDistanceData () inline
Construct null.
Definition at line 34 of file pointTopoDistanceDataI.H.
pointTopoDistanceData() [2/2]
pointTopoDistanceData (const label data, const label distance) inline
Construct from count.
Definition at line 43 of file pointTopoDistanceDataI.H.
Member Function Documentation
data()
label data () const inline
Definition at line 85 of file pointTopoDistanceData.H.
Referenced by pointTopoDistanceData::operator==().
distance()
label distance () const inline
Definition at line 89 of file pointTopoDistanceData.H.
References pointTopoDistanceData::enterDomain(), pointTopoDistanceData::equal(), pointTopoDistanceData::leaveDomain(), mesh, pointTopoDistanceData::operator!=(), pointTopoDistanceData::operator<<, pointTopoDistanceData::operator==(), pointTopoDistanceData::operator>>, Foam::pos(), pointTopoDistanceData::sameGeometry(), pointTopoDistanceData::transform(), pointTopoDistanceData::updateEdge(), pointTopoDistanceData::updatePoint(), and pointTopoDistanceData::valid().
Referenced by pointTopoDistanceData::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 56 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::sameGeometry().
Referenced by pointTopoDistanceData::distance().
sameGeometry()
bool sameGeometry (const pointTopoDistanceData & , const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 65 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::leaveDomain().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::valid().
leaveDomain()
void leaveDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 78 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::transform().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::sameGeometry().
enterDomain()
void enterDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 100 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::updatePoint().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::transform().
transform()
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 90 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::enterDomain().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::leaveDomain().
updatePoint() [1/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const label edgeI, const pointTopoDistanceData & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 112 of file pointTopoDistanceDataI.H.
Referenced by pointTopoDistanceData::distance(), pointTopoDistanceData::enterDomain(), and pointTopoDistanceData::updatePoint().
updatePoint() [2/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const pointTopoDistanceData & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 137 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::updatePoint().
updatePoint() [3/3]
bool updatePoint (const pointTopoDistanceData & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 160 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::updateEdge().
updateEdge()
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointI, const pointTopoDistanceData & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 181 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::equal().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::updatePoint().
equal()
bool equal (const pointTopoDistanceData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 204 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::operator==().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::updateEdge().
operator==()
bool operator== (const pointTopoDistanceData & rhs) const inline
Definition at line 216 of file pointTopoDistanceDataI.H.
References pointTopoDistanceData::data(), and pointTopoDistanceData::distance().
Referenced by pointTopoDistanceData::distance(), and pointTopoDistanceData::equal().
operator!=()
bool operator!= (const pointTopoDistanceData & rhs) const inline
Definition at line 225 of file pointTopoDistanceDataI.H.
Referenced by pointTopoDistanceData::distance().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const pointTopoDistanceData &) friend
Referenced by pointTopoDistanceData::distance().
operator>>
Istream& operator>> (Istream & , pointTopoDistanceData &) friend
Referenced by pointTopoDistanceData::distance().
The documentation for this class was generated from the following files:
src/meshTools/meshStructure/pointTopoDistanceData.H
src/meshTools/meshStructure/pointTopoDistanceDataI.H