OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionCoupledLduInterface Class Reference abstract
An abstract base class for region coupled interfaces.
Public Member Functions
TypeName ("regionCoupledLduInterface")
Runtime type information.
regionCoupledLduInterface ()
Construct null.
virtual ~regionCoupledLduInterface ()
Destructor.
virtual label neighbPatchID () const =0
Return neighbour.
virtual bool owner () const =0
Is it owner?
virtual const regionCoupledLduInterface & neighbPatch () const =0
Return neighb regionCoupledLduInterface.
virtual const polyMesh & nbrMesh () const =0
Return AMI.
Detailed Description
An abstract base class for region coupled interfaces.
Source files
regionCoupledLduInterface.H
regionCoupledLduInterface.C
Definition at line 51 of file regionCoupledLduInterface.H.
Constructor & Destructor Documentation
regionCoupledLduInterface()
regionCoupledLduInterface () inline
Construct null.
Definition at line 63 of file regionCoupledLduInterface.H.
References regionCoupledLduInterface::nbrMesh(), regionCoupledLduInterface::neighbPatch(), regionCoupledLduInterface::neighbPatchID(), regionCoupledLduInterface::owner(), and regionCoupledLduInterface::~regionCoupledLduInterface().
~regionCoupledLduInterface()
~regionCoupledLduInterface () virtual
Destructor.
Definition at line 36 of file regionCoupledLduInterface.C.
Referenced by regionCoupledLduInterface::regionCoupledLduInterface().
Member Function Documentation
TypeName()
TypeName ("regionCoupledLduInterface")
Runtime type information.
neighbPatchID()
virtual label neighbPatchID () const pure virtual
Return neighbour.
Implemented in regionCoupledBaseFvPatch, and regionCoupledBaseGAMGInterface.
Referenced by regionCoupledBaseGAMGInterface::neighbPatchID(), and regionCoupledLduInterface::regionCoupledLduInterface().
owner()
virtual bool owner () const pure virtual
Is it owner?
Implemented in regionCoupledBaseFvPatch, and regionCoupledBaseGAMGInterface.
Referenced by regionCoupledBaseGAMGInterface::owner(), and regionCoupledLduInterface::regionCoupledLduInterface().
neighbPatch()
virtual const regionCoupledLduInterface& neighbPatch () const pure virtual
Return neighb regionCoupledLduInterface.
Implemented in regionCoupledBaseFvPatch, and regionCoupledBaseGAMGInterface.
Referenced by regionCoupledBaseGAMGInterface::neighbPatch(), and regionCoupledLduInterface::regionCoupledLduInterface().
nbrMesh()
virtual const polyMesh& nbrMesh () const pure virtual
Return AMI.
virtual const AMIPatchToPatchInterpolation& AMI() const = 0;Return nbrMesh
Implemented in regionCoupledBaseFvPatch, and regionCoupledBaseGAMGInterface.
Referenced by regionCoupledBaseGAMGInterface::nbrMesh(), and regionCoupledLduInterface::regionCoupledLduInterface().
The documentation for this class was generated from the following files:
src/meshTools/regionCoupled/patches/regionCoupledLduInterface/regionCoupledLduInterface.H
src/meshTools/regionCoupled/patches/regionCoupledLduInterface/regionCoupledLduInterface.C