OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
searchableSurfaceCollection Class Reference
Set of transformed searchableSurfaces. Does not do boolean operations. So when meshing might find parts 'inside'.
Public Member Functions
TypeName ("searchableSurfaceCollection")
Runtime type information.
searchableSurfaceCollection (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface)
virtual ~searchableSurfaceCollection ()
Destructor.
const vectorField & scale () const
scaling vector per subsurface
vectorField & scale ()
scaling vector per subsurface
const PtrList< coordinateSystem > & transform () const
coordinate system per subsurface
PtrList< coordinateSystem > & transform ()
coordinate system per subsurface
virtual const wordList & regions () const
Names of regions.
virtual bool hasVolumeType () const
Whether supports volume type below.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit > > &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &, List< volumeType > &) const
Determine type (inside/outside/mixed) for point. unknown if.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
virtual void setField (const labelList &values)
WIP. Store element-wise field.
virtual void getField (const List< pointIndexHit > &, labelList &) const
WIP. From a set of hits (points and.
bool writeData (Ostream &) const
Pure virtual writaData function.
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()
Destructor.
const boundBox & bounds () const
Return const reference to boundBox.
boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Set of transformed searchableSurfaces. Does not do boolean operations. So when meshing might find parts 'inside'.
Source files
searchableSurfaceCollection.H
searchableSurfaceCollection.C
Definition at line 55 of file searchableSurfaceCollection.H.
Constructor & Destructor Documentation
searchableSurfaceCollection()
searchableSurfaceCollection (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface)
Definition at line 175 of file searchableSurfaceCollection.C.
References Foam::cmptMultiply(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, forAllConstIter(), Foam::Info, dictionary::isDict(), dictionary::lookup(), objectRegistry::lookupObject(), Vector< scalar >::max, boundBox::max(), Foam::max(), Vector< scalar >::min, Vector< Cmpt >::min, boundBox::min(), Foam::min(), Foam::name(), coordinateSystem::New(), s(), and dictionary::subDict().
~searchableSurfaceCollection()
~searchableSurfaceCollection () virtual
Destructor.
Definition at line 283 of file searchableSurfaceCollection.C.
Member Function Documentation
TypeName()
TypeName ("searchableSurfaceCollection")
Runtime type information.
scale() [1/2]
const vectorField& scale () const inline
scaling vector per subsurface
Definition at line 139 of file searchableSurfaceCollection.H.
scale() [2/2]
vectorField& scale () inline
scaling vector per subsurface
Definition at line 145 of file searchableSurfaceCollection.H.
transform() [1/2]
const PtrList<coordinateSystem>& transform () const inline
coordinate system per subsurface
Definition at line 151 of file searchableSurfaceCollection.H.
transform() [2/2]
PtrList<coordinateSystem>& transform () inline
coordinate system per subsurface
Definition at line 157 of file searchableSurfaceCollection.H.
References searchableSurfaceCollection::regions().
regions()
const Foam::wordList & regions () const virtual
Names of regions.
Implements searchableSurface.
Definition at line 289 of file searchableSurfaceCollection.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), forAll, Foam::name(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), and List< T >::size().
Referenced by searchableSurfaceCollection::transform().
hasVolumeType()
virtual bool hasVolumeType () const inline virtual
Whether supports volume type below.
Implements searchableSurface.
Definition at line 166 of file searchableSurfaceCollection.H.
References searchableSurfaceCollection::boundingSpheres(), searchableSurfaceCollection::coordinates(), searchableSurfaceCollection::points(), and searchableSurfaceCollection::size().
size()
Foam::label size () const virtual
Range of local indices that can be returned.
Implements searchableSurface.
Definition at line 321 of file searchableSurfaceCollection.C.
Referenced by searchableSurfaceCollection::hasVolumeType().
coordinates()
Foam::tmp< Foam::pointField > coordinates () const virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implements searchableSurface.
Definition at line 328 of file searchableSurfaceCollection.C.
References searchableSurfaceCollection::boundingSpheres(), Foam::cmptMultiply(), coordinates(), and forAll.
Referenced by searchableSurfaceCollection::hasVolumeType().
boundingSpheres()
void boundingSpheres (pointField & centres, scalarField & radiusSqr) const virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside.
Implements searchableSurface.
Definition at line 358 of file searchableSurfaceCollection.C.
References Foam::cmptMax(), Foam::cmptMultiply(), forAll, List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceCollection::coordinates(), and searchableSurfaceCollection::hasVolumeType().
points()
Foam::tmp< Foam::pointField > points () const virtual
Get the points that define the surface.
Implements searchableSurface.
Definition at line 395 of file searchableSurfaceCollection.C.
References Foam::cmptMultiply(), forAll, nPoints, and points.
Referenced by searchableSurfaceCollection::hasVolumeType().
overlaps()
virtual bool overlaps (const boundBox & bb) const inline virtual
Does any part of the surface overlap the supplied bound box?
Implements searchableSurface.
Definition at line 190 of file searchableSurfaceCollection.H.
References searchableSurfaceCollection::distribute(), searchableSurfaceCollection::findLine(), searchableSurfaceCollection::findLineAll(), searchableSurfaceCollection::findLineAny(), searchableSurfaceCollection::getField(), searchableSurfaceCollection::getNormal(), searchableSurfaceCollection::getRegion(), searchableSurfaceCollection::getVolumeType(), notImplemented, and searchableSurfaceCollection::setField().
findNearest()
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & nearestInfo) const virtual
Implements searchableSurface.
Definition at line 433 of file searchableSurfaceCollection.C.
References searchableSurfaceCollection::findLine().
findLine()
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implements searchableSurface.
Definition at line 454 of file searchableSurfaceCollection.C.
References Foam::abort(), Foam::cmptDivide(), Foam::cmptMultiply(), Foam::FatalError, FatalErrorIn, searchableSurfaceCollection::findLineAny(), forAll, Foam::mag(), n, s(), List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceCollection::findNearest(), and searchableSurfaceCollection::overlaps().
findLineAny()
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Implements searchableSurface.
Definition at line 553 of file searchableSurfaceCollection.C.
References searchableSurfaceCollection::findLineAll().
Referenced by searchableSurfaceCollection::findLine(), and searchableSurfaceCollection::overlaps().
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit > > & info) const virtual
Get all intersections in order from start to end.
Implements searchableSurface.
Definition at line 565 of file searchableSurfaceCollection.C.
References List< T >::clear(), forAll, searchableSurfaceCollection::getRegion(), List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceCollection::findLineAny(), and searchableSurfaceCollection::overlaps().
getRegion()
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
From a set of points and indices get the region.
Implements searchableSurface.
Definition at line 592 of file searchableSurfaceCollection.C.
References forAll, searchableSurfaceCollection::getNormal(), List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceCollection::findLineAll(), and searchableSurfaceCollection::overlaps().
getNormal()
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
From a set of points and indices get the normal.
Implements searchableSurface.
Definition at line 657 of file searchableSurfaceCollection.C.
References forAll, searchableSurfaceCollection::getVolumeType(), List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceCollection::getRegion(), and searchableSurfaceCollection::overlaps().
getVolumeType()
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Implements searchableSurface.
Definition at line 700 of file searchableSurfaceCollection.C.
References searchableSurfaceCollection::distribute(), Foam::exit(), Foam::FatalError, and FatalErrorIn.
Referenced by searchableSurfaceCollection::getNormal(), and searchableSurfaceCollection::overlaps().
distribute()
void distribute (const List< treeBoundBox > & bbs, const bool keepNonLocal, autoPtr< mapDistribute > & faceMap, autoPtr< mapDistribute > & pointMap) virtual
Set bounds of surface. Bounds currently set as list of.
bounding boxes. The bounds are hints to the surface as for the range of queries it can expect. faceMap/pointMap can be set if the surface has done any redistribution.
Reimplemented from searchableSurface.
Definition at line 715 of file searchableSurfaceCollection.C.
References forAll.
Referenced by searchableSurfaceCollection::getVolumeType(), and searchableSurfaceCollection::overlaps().
setField()
void setField (const labelList & values) virtual
WIP. Store element-wise field.
Reimplemented from searchableSurface.
Definition at line 748 of file searchableSurfaceCollection.C.
References forAll, and searchableSurfaceCollection::getField().
Referenced by searchableSurfaceCollection::overlaps().
getField()
void getField (const List< pointIndexHit > & info, labelList & values) const virtual
WIP. From a set of hits (points and.
indices) get the specified field. Misses do not get set. Return empty field if not supported.
Reimplemented from searchableSurface.
Definition at line 769 of file searchableSurfaceCollection.C.
References forAll, List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceCollection::overlaps(), and searchableSurfaceCollection::setField().
writeData()
bool writeData (Ostream &) const inline virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 278 of file searchableSurfaceCollection.H.
References notImplemented.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurface/searchableSurfaceCollection.H
src/meshTools/searchableSurface/searchableSurfaceCollection.C