OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sphereToCell Class Reference
A topoSetSource to select cells based on cell centres inside sphere.
Public Member Functions
TypeName ("sphereToCell")
Runtime type information.
sphereToCell (const polyMesh &mesh, const vector &centre, const scalar radius)
Construct from components.
sphereToCell (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
sphereToCell (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~sphereToCell ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label cellI, const bool) const
Add (if bool) cellI to set or delete cellI from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select cells based on cell centres inside sphere.
Source files
sphereToCell.H
sphereToCell.C
Definition at line 48 of file sphereToCell.H.
Constructor & Destructor Documentation
sphereToCell() [1/3]
sphereToCell (const polyMesh & mesh, const vector & centre, const scalar radius)
Construct from components.
Definition at line 70 of file sphereToCell.C.
Referenced by sphereToCell::sphereToCell().
sphereToCell() [2/3]
sphereToCell (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 83 of file sphereToCell.C.
References sphereToCell::sphereToCell().
sphereToCell() [3/3]
sphereToCell (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 96 of file sphereToCell.C.
~sphereToCell()
~sphereToCell () virtual
Destructor.
Definition at line 109 of file sphereToCell.C.
References sphereToCell::applyToSet().
Member Function Documentation
TypeName()
TypeName ("sphereToCell")
Runtime type information.
setType()
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 107 of file sphereToCell.H.
References sphereToCell::applyToSet(), and topoSetSource::CELLSETSOURCE.
applyToSet()
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 116 of file sphereToCell.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by sphereToCell::setType(), and sphereToCell::~sphereToCell().
The documentation for this class was generated from the following files:
src/meshTools/sets/cellSources/sphereToCell/sphereToCell.H
src/meshTools/sets/cellSources/sphereToCell/sphereToCell.C