OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tetOverlapVolume Class Reference
Calculates the overlap volume of two cells using tetrahedral decomposition.
Public Member Functions
ClassName ("tetOverlapVolume")
Runtime type information.
tetOverlapVolume ()
Null constructor.
labelList overlappingCells (const polyMesh &meshA, const polyMesh &meshB, const label cellBI) const
Return a list of cells in meshA which overlaps with cellBI in.
bool cellCellOverlapMinDecomp (const primitiveMesh &meshA, const label cellAI, const primitiveMesh &meshB, const label cellBI, const treeBoundBox &cellBbB, const scalar threshold=0.0) const
Return true if olverlap volume is greater than threshold.
scalar cellCellOverlapVolumeMinDecomp (const primitiveMesh &meshA, const label cellAI, const primitiveMesh &meshB, const label cellBI, const treeBoundBox &cellBbB) const
Calculates the overlap volume.
Detailed Description
Calculates the overlap volume of two cells using tetrahedral decomposition.
Source files
tetOverlapVolume.H
tetOverlapVolume.C
Definition at line 52 of file tetOverlapVolume.H.
Constructor & Destructor Documentation
tetOverlapVolume()
tetOverlapVolume ()
Null constructor.
Definition at line 45 of file tetOverlapVolume.C.
References tetOverlapVolume::cellCellOverlapMinDecomp(), f(), forAll, tetrahedron< Point, PointRef >::mag(), boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), points, tetrahedron< Point, PointRef >::sliceWithPlane(), tetPoints::tet(), and tetrahedron< Point, PointRef >::sumVolOp::vol_.
Member Function Documentation
ClassName()
ClassName ("tetOverlapVolume")
Runtime type information.
overlappingCells()
Foam::labelList overlappingCells (const polyMesh & meshA, const polyMesh & meshB, const label cellBI) const
Return a list of cells in meshA which overlaps with cellBI in.
meshB
Definition at line 390 of file tetOverlapVolume.C.
References primitiveMesh::cellPoints(), polyMesh::cellTree(), and polyMesh::points().
Referenced by tetOverlapVolume::cellCellOverlapVolumeMinDecomp().
cellCellOverlapMinDecomp()
bool cellCellOverlapMinDecomp (const primitiveMesh & meshA, const label cellAI, const primitiveMesh & meshB, const label cellBI, const treeBoundBox & cellBbB, const scalar threshold = 0.0) const
Return true if olverlap volume is greater than threshold.
Definition at line 139 of file tetOverlapVolume.C.
References tetPoints::bounds(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMesh::cellCentres(), primitiveMesh::cells(), primitiveMesh::faceOwner(), primitiveMesh::faces(), UList< T >::fcIndex(), forAll, boundBox::overlaps(), primitiveMesh::points(), and List< T >::size().
Referenced by meshToMeshMethod::intersect(), and tetOverlapVolume::tetOverlapVolume().
cellCellOverlapVolumeMinDecomp()
Foam::scalar cellCellOverlapVolumeMinDecomp (const primitiveMesh & meshA, const label cellAI, const primitiveMesh & meshB, const label cellBI, const treeBoundBox & cellBbB) const
Calculates the overlap volume.
Definition at line 268 of file tetOverlapVolume.C.
References tetPoints::bounds(), primitiveMesh::cellCentres(), primitiveMesh::cells(), primitiveMesh::faceOwner(), primitiveMesh::faces(), UList< T >::fcIndex(), forAll, tetOverlapVolume::overlappingCells(), boundBox::overlaps(), primitiveMesh::points(), and List< T >::size().
Referenced by tetOverlapVolume::cellCellOverlapMinDecomp(), and meshToMeshMethod::interVol().
The documentation for this class was generated from the following files:
src/meshTools/tetOverlapVolume/tetOverlapVolume.H
src/meshTools/tetOverlapVolume/tetOverlapVolume.C