OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceSets Class Reference
Various utilities to handle sets relating mesh to surface. Note: work in progress. Used in meshing tools.
Static Public Member Functions
static void getSurfaceSets (const polyMesh &mesh, const fileName &surfName, const triSurface &surf, const triSurfaceSearch &querySurf, const pointField &outsidePts, const label nCutLayers, labelHashSet &inside, labelHashSet &outside, labelHashSet &cut)
Divide cells into cut,inside and outside.
static labelHashSet getHangingCells (const primitiveMesh &mesh, const labelHashSet &internalCells)
Get cells using points on 'outside' only.
Detailed Description
Various utilities to handle sets relating mesh to surface. Note: work in progress. Used in meshing tools.
Source files
surfaceSets.H
surfaceSets.C
Definition at line 62 of file surfaceSets.H.
Member Function Documentation
getSurfaceSets()
void getSurfaceSets (const polyMesh & mesh, const fileName & surfName, const triSurface & surf, const triSurfaceSearch & querySurf, const pointField & outsidePts, const label nCutLayers, labelHashSet & inside, labelHashSet & outside, labelHashSet & cut) static
Divide cells into cut,inside and outside.
nCutLayers>0 : remove cutCells (set to type inside) if further than nCutLayers away from outside type cell.
Definition at line 223 of file surfaceSets.C.
References forAll, surfaceSets::getHangingCells(), HashSet< Key, Hash >::insert(), and cellClassification::trimCutCells().
getHangingCells()
Foam::labelHashSet getHangingCells (const primitiveMesh & mesh, const labelHashSet & internalCells) static
Get cells using points on 'outside' only.
Definition at line 282 of file surfaceSets.C.
References cells, primitiveMesh::cells(), f(), primitiveMesh::faces(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), primitiveMesh::nCells(), primitiveMesh::nPoints(), and HashTable< T, Key, Hash >::size().
Referenced by surfaceSets::getSurfaceSets().
The documentation for this class was generated from the following files:
src/meshTools/surfaceSets/surfaceSets.H
src/meshTools/surfaceSets/surfaceSets.C