OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Rosenbrock12 Class Reference
L-stable embedded Rosenbrock ODE solver of order (1)2.
Public Member Functions
TypeName ("Rosenbrock12")
Runtime type information.
Rosenbrock12 (const ODESystem &ode, const dictionary &dict)
Construct from ODE.
scalar solve (const scalar x0, const scalarField &y0, const scalarField &dydx0, const scalar dx, scalarField &y) const
Solve a single step dx and return the error.
void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
scalarField & absTol ()
scalarField & relTol ()
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Public Member Functions inherited from adaptiveSolver
adaptiveSolver (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~adaptiveSolver ()
Destructor.
void solve (const ODESystem &ode, scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
label n_
Size of the ODESystem.
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
L-stable embedded Rosenbrock ODE solver of order (1)2.
References:
    "A second-order Rosenbrock method applied to
     photochemical dispersion problems",
    J. G. Verwer,
    E. J. Spee,
    J. G. Blom,
    W. Hundsdorfer,
    Siam Journal on Scientific Computing 01/1999; 20(4):1456-1480.
Source files
Rosenbrock12.H
Rosenbrock12.C
Definition at line 60 of file Rosenbrock12.H.
Constructor & Destructor Documentation
Rosenbrock12()
Rosenbrock12 (const ODESystem & ode, const dictionary & dict)
Construct from ODE.
Definition at line 52 of file Rosenbrock12.C.
References Rosenbrock12::solve().
Member Function Documentation
TypeName()
TypeName ("Rosenbrock12")
Runtime type information.
solve() [1/2]
Foam::scalar solve (const scalar x0, const scalarField & y0, const scalarField & dydx0, const scalar dx, scalarField & y) const virtual
Solve a single step dx and return the error.
Implements adaptiveSolver.
Definition at line 70 of file Rosenbrock12.C.
References ODESystem::derivatives(), forAll, ODESystem::jacobian(), Foam::LUBacksubstitute(), Foam::LUDecompose(), ODESolver::n_, ODESolver::normalizeError(), and ODESolver::odes_.
Referenced by Rosenbrock12::Rosenbrock12().
solve() [2/2]
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system and the update the state.
Reimplemented from ODESolver.
Definition at line 127 of file Rosenbrock12.C.
References ODESolver::odes_, and adaptiveSolver::solve().
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/Rosenbrock12/Rosenbrock12.H
src/ODE/ODESolvers/Rosenbrock12/Rosenbrock12.C