OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointToPointPlanarInterpolation Class Reference
Interpolates between two sets of unstructured points using 2D Delaunay triangulation. Used in e.g. timeVaryingMapped bcs.
Public Member Functions
ClassName ("pointToPointPlanarInterpolation")
pointToPointPlanarInterpolation (const pointField &sourcePoints, const pointField &destPoints, const scalar perturb, const bool nearestOnly=false)
Construct from 3D locations. Determines local coordinate system.
pointToPointPlanarInterpolation (const coordinateSystem &referenceCS, const pointField &sourcePoints, const pointField &destPoints, const scalar perturb)
Construct from coordinate system and locations.
const coordinateSystem & referenceCS () const
Return the coordinateSystem.
label sourceSize () const
Number of source points.
const List< FixedList< label, 3 > > & nearestVertex () const
const List< FixedList< scalar, 3 > > & nearestVertexWeight () const
Current interpolation factors to face centres of underlying.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &sourceFld) const
Interpolate from field on source points to dest points.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &sourceFld) const
Static Public Member Functions
static wordList timeNames (const instantList &)
Helper: extract words of times.
static bool findTime (const instantList &times, const label startSampleTime, const scalar timeVal, label &lo, label &hi)
Helper: find time. Return true if succesful.
Detailed Description
Interpolates between two sets of unstructured points using 2D Delaunay triangulation. Used in e.g. timeVaryingMapped bcs.
Source files
pointToPointPlanarInterpolation.H
pointToPointPlanarInterpolation.C
Definition at line 51 of file pointToPointPlanarInterpolation.H.
Constructor & Destructor Documentation
pointToPointPlanarInterpolation() [1/2]
pointToPointPlanarInterpolation (const pointField & sourcePoints, const pointField & destPoints, const scalar perturb, const bool nearestOnly = false)
Construct from 3D locations. Determines local coordinate system.
from sourcePoints and maps onto that. If nearestOnly skips any local coordinate system and triangulation and uses nearest vertex only
Definition at line 317 of file pointToPointPlanarInterpolation.C.
pointToPointPlanarInterpolation() [2/2]
pointToPointPlanarInterpolation (const coordinateSystem & referenceCS, const pointField & sourcePoints, const pointField & destPoints, const scalar perturb)
Construct from coordinate system and locations.
Definition at line 334 of file pointToPointPlanarInterpolation.C.
References pointToPointPlanarInterpolation::timeNames().
Member Function Documentation
ClassName()
ClassName ("pointToPointPlanarInterpolation")
referenceCS()
const coordinateSystem& referenceCS () const inline
Return the coordinateSystem.
Definition at line 120 of file pointToPointPlanarInterpolation.H.
sourceSize()
label sourceSize () const inline
Number of source points.
Definition at line 126 of file pointToPointPlanarInterpolation.H.
nearestVertex()
const List<FixedList<label, 3> >& nearestVertex () const inline
Definition at line 132 of file pointToPointPlanarInterpolation.H.
References pointToPointPlanarInterpolation::findTime(), pointToPointPlanarInterpolation::interpolate(), pointToPointPlanarInterpolation::nearestVertexWeight(), and pointToPointPlanarInterpolation::timeNames().
nearestVertexWeight()
const List<FixedList<scalar, 3> >& nearestVertexWeight () const inline
Current interpolation factors to face centres of underlying.
patch
Definition at line 139 of file pointToPointPlanarInterpolation.H.
Referenced by pointToPointPlanarInterpolation::nearestVertex().
timeNames()
Foam::wordList timeNames (const instantList & times) static
Helper: extract words of times.
Definition at line 353 of file pointToPointPlanarInterpolation.C.
References pointToPointPlanarInterpolation::findTime(), forAll, and List< T >::size().
Referenced by timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), pointToPointPlanarInterpolation::nearestVertex(), and pointToPointPlanarInterpolation::pointToPointPlanarInterpolation().
findTime()
bool findTime (const instantList & times, const label startSampleTime, const scalar timeVal, label & lo, label & hi) static
Helper: find time. Return true if succesful.
Definition at line 368 of file pointToPointPlanarInterpolation.C.
References Foam::endl(), Foam::Pout, and List< T >::size().
Referenced by pointToPointPlanarInterpolation::nearestVertex(), and pointToPointPlanarInterpolation::timeNames().
interpolate() [1/2]
tmp<Field<Type> > interpolate (const Field< Type > & sourceFld) const
Interpolate from field on source points to dest points.
Referenced by pointToPointPlanarInterpolation::nearestVertex().
interpolate() [2/2]
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & sourceFld) const
Definition at line 32 of file pointToPointPlanarInterpolationTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, fld(), forAll, and List< Type >::size().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolation.H
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolation.C
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolationTemplates.C