OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
triangleFuncs Class Reference
Various triangle functions.
Public Types
enum proxType { NONE, POINT, EDGE }
Enumeration defining nearness classification.
Static Public Member Functions
static bool intersectAxesBundle (const point &V0, const point &V10, const point &V20, const label i0, const pointField &origin, const scalar maxLength, point &pInter)
Intersect triangle with parallel edges aligned with axis i0.
static bool intersectBb (const point &p0, const point &p1, const point &p2, const treeBoundBox &cubeBb)
Does triangle intersect bounding box.
static bool intersect (const point &va0, const point &va10, const point &va20, const point &basePoint, const vector &normal, point &pInter0, point &pInter1)
Does triangle intersect plane. Return bool and set intersection segment.
static bool intersect (const point &va0, const point &va10, const point &va20, const point &vb0, const point &vb10, const point &vb20, point &pInter0, point &pInter1)
Do triangles intersect. Return bool and set intersection segment.
Detailed Description
Various triangle functions.
Source files
triangleFuncs.H
triangleFuncs.C
Definition at line 54 of file triangleFuncs.H.
Member Enumeration Documentation
proxType
enum proxType
Enumeration defining nearness classification.
Enumerator
NONE
POINT
EDGE
Definition at line 62 of file triangleFuncs.H.
Member Function Documentation
intersectAxesBundle()
bool intersectAxesBundle (const point & V0, const point & V10, const point & V20, const label i0, const pointField & origin, const scalar maxLength, point & pInter) static
Intersect triangle with parallel edges aligned with axis i0.
Returns true (and intersection in pInter) if any of them intersects triangle. Used in intersectBb.
Definition at line 85 of file triangleFuncs.C.
References Foam::constant::atomic::alpha, beta(), Foam::det(), forAll, triangleFuncs::intersectBb(), Foam::mag(), s(), and u0.
Referenced by triangleFuncs::intersectBb().
intersectBb()
bool intersectBb (const point & p0, const point & p1, const point & p2, const treeBoundBox & cubeBb) static
Does triangle intersect bounding box.
Definition at line 172 of file triangleFuncs.C.
References triangleFuncs::intersect(), triangleFuncs::intersectAxesBundle(), treeBoundBox::intersects(), boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by triangleFuncs::intersectAxesBundle(), NamedEnum< directionType, 3 >::names(), and treeDataFace::overlaps().
intersect() [1/2]
bool intersect (const point & va0, const point & va10, const point & va20, const point & basePoint, const vector & normal, point & pInter0, point & pInter1) static
Does triangle intersect plane. Return bool and set intersection segment.
Definition at line 526 of file triangleFuncs.C.
References Foam::mag(), and Foam::sqrt().
Referenced by triangleFuncs::intersect(), and triangleFuncs::intersectBb().
intersect() [2/2]
bool intersect (const point & va0, const point & va10, const point & va20, const point & vb0, const point & vb10, const point & vb20, point & pInter0, point & pInter1) static
Do triangles intersect. Return bool and set intersection segment.
Definition at line 644 of file triangleFuncs.C.
References SortableList< T >::indices(), triangleFuncs::intersect(), Foam::mag(), and SortableList< T >::sort().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triangleFuncs/triangleFuncs.H
src/meshTools/triSurface/triangleFuncs/triangleFuncs.C