OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceIntersection Class Reference
Basic surface-surface intersection description. Constructed from two surfaces it creates a description of the intersection.
Public Member Functions
ClassName ("surfaceIntersection")
surfaceIntersection ()
Construct null.
surfaceIntersection (const triSurface &surf1, const edgeIntersections &intersections1, const triSurface &surf2, const edgeIntersections &intersections2)
Construct from precalculated intersection information.
surfaceIntersection (const triSurfaceSearch &querySurf1, const triSurfaceSearch &querySurf2)
Construct from two surfaces. Does all its own cutting.
surfaceIntersection (const triSurfaceSearch &querySurf1)
Special: intersect surface with itself. Used to check for.
const pointField & cutPoints () const
const edgeList & cutEdges () const
const labelPairLookup & facePairToVertex () const
const labelPairLookup & facePairToEdge () const
const labelListList & edgeCuts (const bool) const
Access either surf1EdgeCuts (isFirstSurface = true) or.
const labelListList & surf1EdgeCuts () const
const labelListList & surf2EdgeCuts () const
Detailed Description
Basic surface-surface intersection description. Constructed from two surfaces it creates a description of the intersection.
The intersection information consists of the intersection line(s) with new points, new edges between points (note that these edges and points are on both surfaces) and various addressing from original surface faces/edges to intersection and vice versa.
Gets either precalculated intersection information or calculates it itself. Algorithm works by intersecting all edges of one surface with the other surface and storing a reference from both faces (one on surface1, one on surface 2) to the vertex. If the reference re-occurs we have the second hit of both faces and an edge is created between the retrieved vertex and the new one.
Note: when doing intersecting itself uses intersection::planarTol() as a fraction of current edge length to determine if intersection is a point-touching one instead of an edge-piercing action.
Source files
surfaceIntersection.H
surfaceIntersection.C
surfaceIntersectionFuncs.C
surfaceIntersectionTemplates.C
Definition at line 80 of file surfaceIntersection.H.
Constructor & Destructor Documentation
surfaceIntersection() [1/4]
surfaceIntersection ()
Construct null.
Definition at line 704 of file surfaceIntersection.C.
Referenced by surfaceIntersection::surfaceIntersection().
surfaceIntersection() [2/4]
surfaceIntersection (const triSurface & surf1, const edgeIntersections & intersections1, const triSurface & surf2, const edgeIntersections & intersections2)
Construct from precalculated intersection information.
Advantage: intersection information is guaranteed to have no degenerate cuts.
Definition at line 820 of file surfaceIntersection.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), Foam::endl(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), HashSet< Key, Hash >::insert(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), Foam::Pout, List< T >::size(), surfaceIntersection::surfaceIntersection(), List< T >::transfer(), and WarningIn.
surfaceIntersection() [3/4]
surfaceIntersection (const triSurfaceSearch & querySurf1, const triSurfaceSearch & querySurf2)
Construct from two surfaces. Does all its own cutting.
Has problems with degenerate cuts
Definition at line 717 of file surfaceIntersection.C.
References Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), Foam::Pout, List< T >::size(), triSurfaceSearch::surface(), surfaceIntersection::surfaceIntersection(), and List< T >::transfer().
surfaceIntersection() [4/4]
surfaceIntersection (const triSurfaceSearch & querySurf1)
Special: intersect surface with itself. Used to check for.
self-intersection.
Definition at line 983 of file surfaceIntersection.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), UList< T >::empty(), edge::end(), Foam::endl(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), edge::mag(), Foam::mergePoints(), Foam::min(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), intersection::planarTol(), Foam::Pout, List< T >::size(), edge::start(), triSurfaceSearch::surface(), and List< T >::transfer().
Member Function Documentation
ClassName()
ClassName ("surfaceIntersection")
cutPoints()
const Foam::pointField & cutPoints () const
Definition at line 1137 of file surfaceIntersection.C.
Referenced by edgeSurface::edgeSurface(), and intersectedSurface::intersectedSurface().
cutEdges()
const Foam::edgeList & cutEdges () const
Definition at line 1143 of file surfaceIntersection.C.
Referenced by edgeSurface::edgeSurface(), and intersectedSurface::intersectedSurface().
facePairToVertex()
const Foam::labelPairLookup & facePairToVertex () const
Definition at line 1149 of file surfaceIntersection.C.
facePairToEdge()
const Foam::labelPairLookup & facePairToEdge () const
Definition at line 1155 of file surfaceIntersection.C.
References surfaceIntersection::edgeCuts().
Referenced by edgeSurface::edgeSurface().
edgeCuts()
const Foam::labelListList & edgeCuts (const bool isFirstSurf) const
Access either surf1EdgeCuts (isFirstSurface = true) or.
surf2EdgeCuts
Definition at line 1162 of file surfaceIntersection.C.
Referenced by edgeSurface::edgeSurface(), and surfaceIntersection::facePairToEdge().
surf1EdgeCuts()
const Foam::labelListList & surf1EdgeCuts () const
Definition at line 1177 of file surfaceIntersection.C.
surf2EdgeCuts()
const Foam::labelListList & surf2EdgeCuts () const
Definition at line 1183 of file surfaceIntersection.C.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersection.H
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersection.C
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersectionFuncs.C
src/meshTools/triSurface/booleanOps/surfaceIntersection/surfaceIntersectionTemplates.C