OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceLocation Class Reference
Contains information about location on a triSurface:
Public Member Functions
surfaceLocation ()
Construct null.
surfaceLocation (const pointIndexHit &pih, const triPointRef::proxType elementType, const label triangle)
Construct from components.
surfaceLocation (Istream &is)
Construct from Istream.
triPointRef::proxType & elementType ()
triPointRef::proxType elementType () const
label & triangle ()
label triangle () const
vector normal (const triSurface &s) const
Normal. Approximate for points.
InfoProxy< surfaceLocation > info () const
Return info proxy.
void write (Ostream &os, const triSurface &s) const
Write info to os.
Public Member Functions inherited from PointIndexHit< Point >
PointIndexHit (const bool success, const Point &p, const label index)
Construct from components.
PointIndexHit (const Point &p)
Construct from point. Hit and distance set later.
PointIndexHit ()
Construct null.
PointIndexHit (Istream &is)
Construct from Istream.
bool hit () const
Is there a hit.
label index () const
Return index.
const Point & hitPoint () const
Return hit point.
const Point & missPoint () const
Return miss point.
const Point & rawPoint () const
Return point with no checking.
Point & rawPoint ()
void setHit ()
void setMiss ()
void setPoint (const Point &p)
void setIndex (const label index)
bool operator== (const PointIndexHit &rhs) const
bool operator!= (const PointIndexHit &rhs) const
void write (Ostream &os)
Friends
Istream & operator>> (Istream &is, surfaceLocation &sl)
Ostream & operator<< (Ostream &os, const surfaceLocation &sl)
Ostream & operator<< (Ostream &, const InfoProxy< surfaceLocation > &)
Detailed Description
Contains information about location on a triSurface:
- pointIndexHit:
location
bool: hit/miss
index (of triangle/point/edge)
elementType():
what index above relates to. In triangle::proxType
triangle():
last known triangle
Source files
surfaceLocation.H
Definition at line 60 of file surfaceLocation.H.
Constructor & Destructor Documentation
surfaceLocation() [1/3]
surfaceLocation () inline
Construct null.
Definition at line 76 of file surfaceLocation.H.
surfaceLocation() [2/3]
surfaceLocation (const pointIndexHit & pih, const triPointRef::proxType elementType, const label triangle) inline
Construct from components.
Definition at line 85 of file surfaceLocation.H.
surfaceLocation() [3/3]
surfaceLocation (Istream & is) inline
Construct from Istream.
Definition at line 97 of file surfaceLocation.H.
Member Function Documentation
elementType() [1/2]
triPointRef::proxType& elementType () inline
Definition at line 107 of file surfaceLocation.H.
Referenced by triSurfaceTools::classify(), triSurfaceTools::trackToEdge(), and surfaceLocation::write().
elementType() [2/2]
triPointRef::proxType elementType () const inline
Definition at line 112 of file surfaceLocation.H.
triangle() [1/2]
label& triangle () inline
Definition at line 117 of file surfaceLocation.H.
Referenced by triSurfaceTools::track(), triSurfaceTools::trackToEdge(), and surfaceLocation::write().
triangle() [2/2]
label triangle () const inline
Definition at line 122 of file surfaceLocation.H.
References surfaceLocation::info(), surfaceLocation::normal(), surfaceLocation::operator<<, surfaceLocation::operator>>, s(), and surfaceLocation::write().
normal()
Foam::vector normal (const triSurface & s) const
Normal. Approximate for points.
Definition at line 31 of file surfaceLocation.C.
References triangle< Point, PointRef >::EDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), forAll, PointIndexHit< Point >::index(), Foam::mag(), n, triangle< Point, PointRef >::NONE, PrimitivePatch< Face, FaceList, PointField, PointType >::pointNormals(), List< T >::size(), and Vector< Cmpt >::zero.
Referenced by surfaceLocation::triangle().
info()
InfoProxy<surfaceLocation> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 132 of file surfaceLocation.H.
Referenced by surfaceLocation::triangle().
write()
void write (Ostream & os, const triSurface & s) const
Write info to os.
Definition at line 67 of file surfaceLocation.C.
References Foam::e, triangle< Point, PointRef >::EDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), surfaceLocation::elementType(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), edge::line(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), triangle< Point, PointRef >::NONE, Foam::operator<<(), Foam::operator>>(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), PointIndexHit< Point >::rawPoint(), token::SPACE, and surfaceLocation::triangle().
Referenced by surfaceLocation::triangle().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & is, surfaceLocation & sl) friend
Referenced by surfaceLocation::triangle().
operator<< [1/2]
Ostream& operator<< (Ostream & os, const surfaceLocation & sl) friend
Referenced by surfaceLocation::triangle().
operator<< [2/2]
Ostream& operator<< (Ostream & , const InfoProxy< surfaceLocation > &) friend
The documentation for this class was generated from the following files:
src/meshTools/triSurface/surfaceLocation/surfaceLocation.H
src/meshTools/triSurface/surfaceLocation/surfaceLocation.C