OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
subCycleField< GeometricField > Class Template Reference
Public Member Functions
subCycleField (GeometricField &gf)
Construct field and number of sub-cycles.
~subCycleField ()
Destructor.
void updateTimeIndex ()
Correct the time index of the field to correspond to.
Detailed Description
template<class GeometricField>
class Foam::subCycleField< GeometricField >
Definition at line 46 of file subCycle.H.
Constructor & Destructor Documentation
subCycleField()
subCycleField (GeometricField & gf) inline
Construct field and number of sub-cycles.
Definition at line 67 of file subCycle.H.
~subCycleField()
~subCycleField () inline
Destructor.
Definition at line 76 of file subCycle.H.
References IOobject::time(), TimeState::timeIndex(), GeometricField< Type, PatchField, GeoMesh >::timeIndex(), and subCycleField< GeometricField >::updateTimeIndex().
Member Function Documentation
updateTimeIndex()
void updateTimeIndex () inline
Correct the time index of the field to correspond to.
the sub-cycling time.
The time index is incremented to protect the old-time value from being updated at the beginning of the time-loop in the case of outer iteration
Definition at line 93 of file subCycle.H.
Referenced by subCycle< GeometricField >::subCycle(), and subCycleField< GeometricField >::~subCycleField().
The documentation for this class was generated from the following file:
src/OpenFOAM/algorithms/subCycle/subCycle.H