OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
treeDataCell Class Reference
Encapsulation of data needed to search in/for cells. Used to find the cell containing a point (e.g. cell-cell mapping).
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassName ("treeDataCell")
treeDataCell (const bool cacheBb, const polyMesh &, const labelUList &, const polyMesh::cellRepresentation decompMode)
Construct from mesh and subset of cells.
treeDataCell (const bool cacheBb, const polyMesh &, const Xfer< labelList > &, const polyMesh::cellRepresentation decompMode)
Construct from mesh and subset of cells, transferring contents.
treeDataCell (const bool cacheBb, const polyMesh &, const polyMesh::cellRepresentation decompMode)
Construct from mesh. Uses all cells in mesh.
const labelList & cellLabels () const
const polyMesh & mesh () const
polyMesh::cellRepresentation decompMode () const
label size () const
pointField shapePoints () const
Get representative point cloud for all shapes inside.
volumeType getVolumeType (const indexedOctree< treeDataCell > &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does (bb of) shape at index overlap bb.
bool contains (const label index, const point &sample) const
Does shape at index contain sample.
Detailed Description
Encapsulation of data needed to search in/for cells. Used to find the cell containing a point (e.g. cell-cell mapping).
Source files
treeDataCell.H
treeDataCell.C
Definition at line 54 of file treeDataCell.H.
Constructor & Destructor Documentation
treeDataCell() [1/3]
treeDataCell (const bool cacheBb, const polyMesh & mesh, const labelUList & cellLabels, const polyMesh::cellRepresentation decompMode)
Construct from mesh and subset of cells.
Definition at line 87 of file treeDataCell.C.
Referenced by treeDataCell::treeDataCell().
treeDataCell() [2/3]
treeDataCell (const bool cacheBb, const polyMesh & mesh, const Xfer< labelList > & cellLabels, const polyMesh::cellRepresentation decompMode)
Construct from mesh and subset of cells, transferring contents.
Definition at line 104 of file treeDataCell.C.
References treeDataCell::treeDataCell().
treeDataCell() [3/3]
treeDataCell (const bool cacheBb, const polyMesh & mesh, const polyMesh::cellRepresentation decompMode)
Construct from mesh. Uses all cells in mesh.
Definition at line 121 of file treeDataCell.C.
References treeDataCell::findNearestOp::findNearestOp().
Member Function Documentation
ClassName()
ClassName ("treeDataCell")
cellLabels()
const labelList& cellLabels () const inline
Definition at line 170 of file treeDataCell.H.
Referenced by treeDataCell::findNearestOp::operator()().
mesh()
const polyMesh& mesh () const inline
Definition at line 175 of file treeDataCell.H.
Referenced by treeDataCell::findNearestOp::operator()().
decompMode()
polyMesh::cellRepresentation decompMode () const inline
Definition at line 180 of file treeDataCell.H.
size()
label size () const inline
Definition at line 185 of file treeDataCell.H.
References treeDataCell::getVolumeType(), treeDataCell::shapePoints(), and List< T >::size().
shapePoints()
Foam::pointField shapePoints () const
Get representative point cloud for all shapes inside.
(one point per shape)
Definition at line 156 of file treeDataCell.C.
References forAll, and treeDataCell::overlaps().
Referenced by treeDataCell::size().
getVolumeType()
volumeType getVolumeType (const indexedOctree< treeDataCell > & , const point &) const inline
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 200 of file treeDataCell.H.
References treeDataCell::contains(), notImplemented, treeDataCell::overlaps(), and volumeType::UNKNOWN.
Referenced by treeDataCell::size().
overlaps()
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does (bb of) shape at index overlap bb.
Definition at line 170 of file treeDataCell.C.
References treeDataCell::contains(), and boundBox::overlaps().
Referenced by treeDataCell::getVolumeType(), and treeDataCell::shapePoints().
contains()
bool contains (const label index, const point & sample) const
Does shape at index contain sample.
Definition at line 187 of file treeDataCell.C.
Referenced by treeDataCell::getVolumeType(), and treeDataCell::overlaps().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.H
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.C