OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
const_circulator< ContainerType > Class Template Reference
Walks over a container as if it were circular. The container must have the following members defined:
Public Types
typedef ContainerType::value_type value_type
Type of values ContainerType contains.
typedef ContainerType::size_type size_type
The type that can represent the size of ContainerType.
typedef ContainerType::difference_type difference_type
The type that can represent the difference between any two.
typedef ContainerType::const_iterator const_iterator
Random access iterator for traversing ContainerType.
typedef ContainerType::const_reference const_reference
Type that can be used for storing into.
Public Types inherited from CirculatorBase
enum direction { NONE, CLOCKWISE, ANTICLOCKWISE }
Direction type enumeration.
Public Member Functions
const_circulator ()
Construct null.
const_circulator (const ContainerType &container)
Construct from a container.
const_circulator (const const_iterator &begin, const const_iterator &end)
Construct from two iterators.
const_circulator (const const_circulator< ContainerType > &)
Construct as copy.
~const_circulator ()
Destructor.
size_type size () const
Return the range of the iterator.
bool circulate (const CirculatorBase::direction dir=NONE)
Circulate around the list in the given direction.
void setFulcrumToIterator ()
Set the fulcrum to the current position of the iterator.
void setIteratorToFulcrum ()
Set the iterator to the current position of the fulcrum.
difference_type nRotations () const
Return the distance between the iterator and the fulcrum. This is.
const_reference next () const
Dereference the next iterator and return.
const_reference prev () const
Dereference the previous iterator and return.
void operator= (const const_circulator< ContainerType > &)
Assignment operator for circulators that operate on the same.
const_circulator< ContainerType > & operator++ ()
Prefix increment. Increments the iterator.
const_circulator< ContainerType > operator++ (int)
Postfix increment. Increments the iterator.
const_circulator< ContainerType > & operator-- ()
Prefix decrement. Decrements the iterator.
const_circulator< ContainerType > operator-- (int)
Postfix decrement. Decrements the iterator.
bool operator== (const const_circulator< ContainerType > &c) const
Check for equality of this iterator with another iterator that.
bool operator!= (const const_circulator< ContainerType > &c) const
Check for inequality of this iterator with another iterator that.
const_reference operator* () const
Dereference the iterator and return.
const_reference operator() () const
Dereference the iterator and return.
difference_type operator- (const const_circulator< ContainerType > &c) const
Return the difference between this iterator and another iterator.
Public Member Functions inherited from CirculatorBase
CirculatorBase ()
Construct null.
Protected Attributes
ContainerType::const_iterator begin_
Iterator pointing to the beginning of the container.
ContainerType::const_iterator end_
Iterator pointing to the end of the container.
ContainerType::const_iterator iter_
Iterator.
ContainerType::const_iterator fulcrum_
Iterator holding the location of the fulcrum (start and end) of.
Detailed Description
template<class ContainerType>
class Foam::const_circulator< ContainerType >
Walks over a container as if it were circular. The container must have the following members defined:
- value_type
size_type
difference_type
const_iterator
const_reference
Examples:
face f(identity(5));
// Construct circulator from the face
const_circulator<face> circ(f);
// First check that the circulator has a size to iterate over.
// Then circulate around the list starting and finishing at the fulcrum.
if (circ.size()) do
{
    Info<< "Iterate forwards over face : " << circ() << endl;
} while (circ.circulate(CirculatorBase::CLOCKWISE));
face f(identity(5));
const_circulator<face> circClockwise(f);
const_circulator<face> circAnticlockwise(f);
if (circClockwise.size() && circAnticlockwise.size()) do
{
    Info<< "Iterate forward over face :" << circClockwise() << endl;
    Info<< "Iterate backward over face:" << circAnticlockwise() << endl;
}
while
(
    circClockwise.circulate(CirculatorBase::CLOCKWISE),
    circAnticlockwise.circulate(CirculatorBase::ANTICLOCKWISE)
);
Source files
const_circulator.H const_
circulatorI.H
Definition at line 91 of file const_circulator.H.
Member Typedef Documentation
value_type
typedef ContainerType::value_type value_type
Type of values ContainerType contains.
Definition at line 120 of file const_circulator.H.
size_type
typedef ContainerType::size_type size_type
The type that can represent the size of ContainerType.
Definition at line 123 of file const_circulator.H.
difference_type
typedef ContainerType::difference_type difference_type
The type that can represent the difference between any two.
iterator objects.
Definition at line 127 of file const_circulator.H.
const_iterator
typedef ContainerType::const_iterator const_iterator
Random access iterator for traversing ContainerType.
Definition at line 130 of file const_circulator.H.
const_reference
typedef ContainerType::const_reference const_reference
Type that can be used for storing into.
const ContainerType::value_type objects.
Definition at line 134 of file const_circulator.H.
Constructor & Destructor Documentation
const_circulator() [1/4]
const_circulator () inline
Construct null.
Definition at line 29 of file const_circulatorI.H.
Referenced by const_circulator< ContainerType >::const_circulator().
const_circulator() [2/4]
const_circulator (const ContainerType & container) inline explicit
Construct from a container.
Definition at line 41 of file const_circulatorI.H.
References const_circulator< ContainerType >::const_circulator().
const_circulator() [3/4]
const_circulator (const const_iterator & begin, const const_iterator & end) inline
Construct from two iterators.
Definition at line 55 of file const_circulatorI.H.
References const_circulator< ContainerType >::const_circulator().
const_circulator() [4/4]
const_circulator (const const_circulator< ContainerType > & rhs) inline
Construct as copy.
Definition at line 70 of file const_circulatorI.H.
~const_circulator()
~const_circulator ()
Destructor.
Definition at line 85 of file const_circulatorI.H.
Member Function Documentation
size()
Foam::const_circulator< ContainerType >::size_type size () const inline
Return the range of the iterator.
Definition at line 93 of file const_circulatorI.H.
References const_circulator< ContainerType >::begin_, const_circulator< ContainerType >::circulate(), and const_circulator< ContainerType >::end_.
circulate()
bool circulate (const CirculatorBase::direction dir = NONE) inline
Circulate around the list in the given direction.
Definition at line 101 of file const_circulatorI.H.
References CirculatorBase::ANTICLOCKWISE, CirculatorBase::CLOCKWISE, const_circulator< ContainerType >::fulcrum_, const_circulator< ContainerType >::iter_, const_circulator< ContainerType >::operator++(), and const_circulator< ContainerType >::operator--().
Referenced by face::compare(), processorPolyPatch::matchFace(), and const_circulator< ContainerType >::size().
setFulcrumToIterator()
void setFulcrumToIterator () inline
Set the fulcrum to the current position of the iterator.
Definition at line 119 of file const_circulatorI.H.
References const_circulator< ContainerType >::fulcrum_, and const_circulator< ContainerType >::iter_.
Referenced by face::compare(), and processorPolyPatch::matchFace().
setIteratorToFulcrum()
void setIteratorToFulcrum () inline
Set the iterator to the current position of the fulcrum.
Definition at line 126 of file const_circulatorI.H.
References const_circulator< ContainerType >::fulcrum_, and const_circulator< ContainerType >::iter_.
Referenced by face::compare(), and processorPolyPatch::matchFace().
nRotations()
Foam::const_circulator< ContainerType >::difference_type nRotations () const inline
Return the distance between the iterator and the fulcrum. This is.
equivalent to the number of rotations of the circulator.
Definition at line 134 of file const_circulatorI.H.
References const_circulator< ContainerType >::fulcrum_, and const_circulator< ContainerType >::iter_.
Referenced by processorPolyPatch::matchFace().
next()
Foam::const_circulator< ContainerType >::const_reference next () const inline
Dereference the next iterator and return.
Definition at line 142 of file const_circulatorI.H.
References const_circulator< ContainerType >::begin_, const_circulator< ContainerType >::end_, and const_circulator< ContainerType >::iter_.
prev()
Foam::const_circulator< ContainerType >::const_reference prev () const inline
Dereference the previous iterator and return.
Definition at line 155 of file const_circulatorI.H.
References const_circulator< ContainerType >::begin_, const_circulator< ContainerType >::end_, and const_circulator< ContainerType >::iter_.
operator=()
void operator= (const const_circulator< ContainerType > & rhs) inline
Assignment operator for circulators that operate on the same.
container type
Definition at line 170 of file const_circulatorI.H.
References Foam::abort(), const_circulator< ContainerType >::begin_, const_circulator< ContainerType >::end_, Foam::FatalError, FatalErrorIn, const_circulator< ContainerType >::fulcrum_, and const_circulator< ContainerType >::iter_.
operator++() [1/2]
Foam::const_circulator< ContainerType > & operator++ () inline
Prefix increment. Increments the iterator.
Sets the iterator to the beginning of the container if it reaches the end
Definition at line 194 of file const_circulatorI.H.
References const_circulator< ContainerType >::begin_, const_circulator< ContainerType >::end_, and const_circulator< ContainerType >::iter_.
Referenced by const_circulator< ContainerType >::circulate().
operator++() [2/2]
Foam::const_circulator< ContainerType > operator++ (int) inline
Postfix increment. Increments the iterator.
Sets the iterator to the beginning of the container if it reaches the end
Definition at line 208 of file const_circulatorI.H.
operator--() [1/2]
Foam::const_circulator< ContainerType > & operator-- () inline
Prefix decrement. Decrements the iterator.
Sets the iterator to the end of the container if it reaches the beginning
Definition at line 218 of file const_circulatorI.H.
References const_circulator< ContainerType >::begin_, const_circulator< ContainerType >::end_, and const_circulator< ContainerType >::iter_.
Referenced by const_circulator< ContainerType >::circulate().
operator--() [2/2]
Foam::const_circulator< ContainerType > operator-- (int) inline
Postfix decrement. Decrements the iterator.
Sets the iterator to the end of the container if it reaches the beginning
Definition at line 232 of file const_circulatorI.H.
operator==()
bool operator== (const const_circulator< ContainerType > & c) const inline
Check for equality of this iterator with another iterator that.
operate on the same container type
Definition at line 242 of file const_circulatorI.H.
References const_circulator< ContainerType >::begin_, Foam::constant::universal::c, const_circulator< ContainerType >::end_, const_circulator< ContainerType >::fulcrum_, and const_circulator< ContainerType >::iter_.
operator!=()
bool operator!= (const const_circulator< ContainerType > & c) const inline
Check for inequality of this iterator with another iterator that.
operate on the same container type
Definition at line 258 of file const_circulatorI.H.
References Foam::constant::universal::c.
operator*()
Foam::const_circulator< ContainerType >::const_reference operator* () const inline
Dereference the iterator and return.
Definition at line 268 of file const_circulatorI.H.
References const_circulator< ContainerType >::iter_.
Referenced by const_circulator< ContainerType >::operator()().
operator()()
Foam::const_circulator< ContainerType >::const_reference operator() () const inline
Dereference the iterator and return.
Definition at line 276 of file const_circulatorI.H.
References const_circulator< ContainerType >::operator*().
operator-()
Foam::const_circulator< ContainerType >::difference_type operator- (const const_circulator< ContainerType > & c) const inline
Return the difference between this iterator and another iterator.
that operate on the same container type
Definition at line 285 of file const_circulatorI.H.
References Foam::constant::universal::c, and const_circulator< ContainerType >::iter_.
Member Data Documentation
begin_
ContainerType::const_iterator begin_ protected
Iterator pointing to the beginning of the container.
Definition at line 101 of file const_circulator.H.
Referenced by const_circulator< ContainerType >::next(), const_circulator< ContainerType >::operator++(), const_circulator< ContainerType >::operator--(), const_circulator< ContainerType >::operator=(), const_circulator< ContainerType >::operator==(), const_circulator< ContainerType >::prev(), and const_circulator< ContainerType >::size().
end_
ContainerType::const_iterator end_ protected
Iterator pointing to the end of the container.
Definition at line 104 of file const_circulator.H.
Referenced by const_circulator< ContainerType >::next(), const_circulator< ContainerType >::operator++(), const_circulator< ContainerType >::operator--(), const_circulator< ContainerType >::operator=(), const_circulator< ContainerType >::operator==(), const_circulator< ContainerType >::prev(), and const_circulator< ContainerType >::size().
iter_
ContainerType::const_iterator iter_ protected
Iterator.
Definition at line 107 of file const_circulator.H.
Referenced by const_circulator< ContainerType >::circulate(), const_circulator< ContainerType >::next(), const_circulator< ContainerType >::nRotations(), const_circulator< ContainerType >::operator*(), const_circulator< ContainerType >::operator++(), const_circulator< ContainerType >::operator-(), const_circulator< ContainerType >::operator--(), const_circulator< ContainerType >::operator=(), const_circulator< ContainerType >::operator==(), const_circulator< ContainerType >::prev(), const_circulator< ContainerType >::setFulcrumToIterator(), and const_circulator< ContainerType >::setIteratorToFulcrum().
fulcrum_
ContainerType::const_iterator fulcrum_ protected
Iterator holding the location of the fulcrum (start and end) of.
the container. Used to decide when the iterator should stop circulating over the container
Definition at line 112 of file const_circulator.H.
Referenced by const_circulator< ContainerType >::circulate(), const_circulator< ContainerType >::nRotations(), const_circulator< ContainerType >::operator=(), const_circulator< ContainerType >::operator==(), const_circulator< ContainerType >::setFulcrumToIterator(), and const_circulator< ContainerType >::setIteratorToFulcrum().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Circulators/const_circulator/const_circulator.H
src/OpenFOAM/containers/Circulators/const_circulator/const_circulatorI.H