OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dynamicTreeDataPoint Class Reference
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
Public Member Functions
ClassName ("dynamicTreeDataPoint")
dynamicTreeDataPoint (const DynamicList< point > &points)
Construct from List. Holds reference!
label size () const
const DynamicList< point > & shapePoints () const
Get representative point cloud for all shapes inside.
volumeType getVolumeType (const dynamicIndexedOctree< dynamicTreeDataPoint > &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does (bb of) shape at index overlap bb.
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
Check if any point on shape is inside sphere.
void findNearest (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &nearestIndex, point &nearestPoint) const
Calculates nearest (to sample) point in shape.
void findNearest (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
Calculates nearest (to line) point in shape.
bool intersects (const label index, const point &start, const point &end, point &result) const
Calculate intersection of shape with ray. Sets result.
Detailed Description
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
Optionally works on subset of points.
Source files
dynamicTreeDataPoint.H
dynamicTreeDataPoint.C
Definition at line 59 of file dynamicTreeDataPoint.H.
Constructor & Destructor Documentation
dynamicTreeDataPoint()
dynamicTreeDataPoint (const DynamicList< point > & points)
Construct from List. Holds reference!
Definition at line 41 of file dynamicTreeDataPoint.C.
Member Function Documentation
ClassName()
ClassName ("dynamicTreeDataPoint")
size()
label size () const inline
Definition at line 81 of file dynamicTreeDataPoint.H.
References dynamicTreeDataPoint::findNearest(), dynamicTreeDataPoint::getVolumeType(), dynamicTreeDataPoint::intersects(), Foam::ln(), dynamicTreeDataPoint::overlaps(), dynamicTreeDataPoint::shapePoints(), and List< T >::size().
shapePoints()
const Foam::DynamicList< Foam::point > & shapePoints () const
Get representative point cloud for all shapes inside.
(one point per shape)
Definition at line 52 of file dynamicTreeDataPoint.C.
References dynamicTreeDataPoint::getVolumeType().
Referenced by dynamicTreeDataPoint::size().
getVolumeType()
Foam::volumeType getVolumeType (const dynamicIndexedOctree< dynamicTreeDataPoint > & oc, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 61 of file dynamicTreeDataPoint.C.
References dynamicTreeDataPoint::overlaps(), and volumeType::UNKNOWN.
Referenced by dynamicTreeDataPoint::shapePoints(), and dynamicTreeDataPoint::size().
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does (bb of) shape at index overlap bb.
Definition at line 72 of file dynamicTreeDataPoint.C.
References treeBoundBox::contains().
Referenced by dynamicTreeDataPoint::getVolumeType(), and dynamicTreeDataPoint::size().
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Check if any point on shape is inside sphere.
Definition at line 83 of file dynamicTreeDataPoint.C.
References dynamicTreeDataPoint::findNearest(), Foam::magSqr(), and p.
findNearest() [1/2]
void findNearest (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & nearestIndex, point & nearestPoint) const
Calculates nearest (to sample) point in shape.
Returns actual point and distance (squared)
Definition at line 105 of file dynamicTreeDataPoint.C.
References forAll, and Foam::magSqr().
Referenced by dynamicTreeDataPoint::overlaps(), and dynamicTreeDataPoint::size().
findNearest() [2/2]
void findNearest (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Calculates nearest (to line) point in shape.
Returns point and distance (squared)
Definition at line 135 of file dynamicTreeDataPoint.C.
References treeBoundBox::contains(), PointHit< Point >::distance(), line< Point, PointRef >::end(), forAll, Foam::magSqr(), boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), line< Point, PointRef >::nearestDist(), PointHit< Point >::rawPoint(), Foam::sqr(), line< Point, PointRef >::start(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
intersects()
bool intersects (const label index, const point & start, const point & end, point & result) const inline
Calculate intersection of shape with ray. Sets result.
accordingly
Definition at line 144 of file dynamicTreeDataPoint.H.
References notImplemented.
Referenced by dynamicTreeDataPoint::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicTreeDataPoint.H
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicTreeDataPoint.C