OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dynamicIndexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Classes
class node
Tree node. Has up pointer and down pointers.
Public Member Functions
dynamicIndexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
autoPtr< dynamicIndexedOctree< Type > > clone () const
Clone.
const Type & shapes () const
Reference to shape.
const List< node > & nodes () const
List of all nodes.
const contentListList & contents () const
List of all contents (referenced by those nodes that are.
const treeBoundBox & bb () const
Top bounding box.
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on nearest shape.
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint) const
Low level: calculate nearest starting from subnode.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to line.
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
labelList findBox (const treeBoundBox &bb) const
Find (in no particular order) indices of all shapes inside or.
labelList findSphere (const point &centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
labelBits findNode (const label nodeI, const point &) const
Find deepest node (as parent+octant) containing point. Starts.
label findInside (const point &) const
Find shape containing point. Only implemented for certain.
const labelList & findIndices (const point &) const
Find the shape indices that occupy the result of findNode.
volumeType getVolumeType (const point &) const
Determine type (inside/outside/mixed) for point. unknown if.
template<class CompareOp >
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > &tree2, CompareOp &cop) const
Find near pairs and apply CompareOp to them.
bool insert (label startIndex, label endIndex)
Insert a new object into the tree.
bool insertIndex (const label nodIndex, const label index, label &nLevels)
bool remove (const label index)
Remove an object from the tree.
label removeIndex (const label nodIndex, const label index)
void print (prefixOSstream &, const bool printContents, const label) const
Print tree. Either print all indices (printContent = true) or.
bool write (Ostream &os) const
void writeTreeInfo () const
Static Public Member Functions
static scalar & perturbTol ()
Get the perturbation tolerance.
static bool isContent (const labelBits i)
static bool isEmpty (const labelBits i)
static bool isNode (const labelBits i)
static label getContent (const labelBits i)
static label getNode (const labelBits i)
static direction getOctant (const labelBits i)
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Helper function to return the side. Returns outside if.
static bool overlaps (const point &bbMin, const point &bbMax, const scalar nearestDistSqr, const point &sample)
Helper: does bb intersect a sphere around sample? Or is any.
Friends
Ostream & operator (Ostream &, const dynamicIndexedOctree< Type > &)
Detailed Description
template<class Type>
class Foam::dynamicIndexedOctree< Type >
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Source files
dynamicIndexedOctree.H
dynamicIndexedOctree.C
Definition at line 55 of file dynamicIndexedOctree.H.
Constructor & Destructor Documentation
dynamicIndexedOctree()
dynamicIndexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
Definition at line 2312 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest().
Member Function Documentation
perturbTol()
Foam::scalar & perturbTol () static
Get the perturbation tolerance.
Definition at line 2348 of file dynamicIndexedOctree.C.
clone()
autoPtr<dynamicIndexedOctree<Type> > clone () const inline
Clone.
Definition at line 437 of file dynamicIndexedOctree.H.
shapes()
const Type& shapes () const inline
Reference to shape.
Definition at line 451 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest().
nodes()
const List<node>& nodes () const inline
List of all nodes.
Definition at line 457 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest().
contents()
const contentListList& contents () const inline
List of all contents (referenced by those nodes that are.
contents)
Definition at line 464 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::nodes().
bb()
const treeBoundBox& bb () const inline
Top bounding box.
Definition at line 470 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNear().
isContent()
static bool isContent (const labelBits i) inline static
Definition at line 483 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getContent().
isEmpty()
static bool isEmpty (const labelBits i) inline static
Definition at line 488 of file dynamicIndexedOctree.H.
isNode()
static bool isNode (const labelBits i) inline static
Definition at line 493 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getNode().
getContent()
static label getContent (const labelBits i) inline static
Definition at line 498 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest().
getNode()
static label getNode (const labelBits i) inline static
Definition at line 508 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest().
getOctant()
static direction getOctant (const labelBits i) inline static
Definition at line 518 of file dynamicIndexedOctree.H.
findNearest() [1/3]
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on nearest shape.
Returns
bool : any point found nearer than nearestDistSqr
label: index in shapes
point: actual nearest point found
Definition at line 2356 of file dynamicIndexedOctree.C.
findNearest() [2/3]
void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint) const
Low level: calculate nearest starting from subnode.
Definition at line 494 of file dynamicIndexedOctree.C.
findNearest() [3/3]
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to line.
Returns
bool : any point found?
label: index in shapes
point: actual nearest point found sets:
linePoint : corresponding nearest point on line
Definition at line 2384 of file dynamicIndexedOctree.C.
findLine()
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 2418 of file dynamicIndexedOctree.C.
findLineAny()
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 2430 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findLine(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
findBox()
Foam::labelList findBox (const treeBoundBox & bb) const
Find (in no particular order) indices of all shapes inside or.
overlapping bounding box (i.e. all shapes not outside box)
Definition at line 2441 of file dynamicIndexedOctree.C.
findSphere()
Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
overlapping a bounding sphere (i.e. all shapes not outside sphere)
Definition at line 2459 of file dynamicIndexedOctree.C.
findNode()
Foam::labelBits findNode (const label nodeI, const point & sample) const
Find deepest node (as parent+octant) containing point. Starts.
off from starting index in nodes_ (use 0 to start from top) Use getNode and getOctant to extract info, or call findIndices.
Definition at line 2479 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findSphere(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
findInside()
Foam::label findInside (const point & sample) const
Find shape containing point. Only implemented for certain.
shapes.
Definition at line 2526 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNode(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
findIndices()
const Foam::labelList & findIndices (const point & sample) const
Find the shape indices that occupy the result of findNode.
Definition at line 2558 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findInside(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
getVolumeType()
Foam::volumeType getVolumeType (const point & sample) const
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Definition at line 2583 of file dynamicIndexedOctree.C.
getSide()
Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Helper function to return the side. Returns outside if.
outsideNormal&vec >= 0, inside otherwise
Definition at line 470 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps().
overlaps()
bool overlaps (const point & bbMin, const point & bbMax, const scalar nearestDistSqr, const point & sample) static
Helper: does bb intersect a sphere around sample? Or is any.
corner point of bb closer than nearestDistSqr to sample.
Definition at line 43 of file dynamicIndexedOctree.C.
findNear()
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > & tree2, CompareOp & cop) const
Find near pairs and apply CompareOp to them.
tree2 can be *this or different tree.
Definition at line 2653 of file dynamicIndexedOctree.C.
insert()
bool insert (label startIndex, label endIndex)
Insert a new object into the tree.
Definition at line 2675 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
insertIndex()
bool insertIndex (const label nodIndex, const label index, label & nLevels)
Definition at line 2722 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::insert().
remove()
bool remove (const label index)
Remove an object from the tree.
Definition at line 2798 of file dynamicIndexedOctree.C.
removeIndex()
Foam::label removeIndex (const label nodIndex, const label index)
Definition at line 2813 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::remove().
print()
void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Print tree. Either print all indices (printContent = true) or.
just size of contents nodes.
Definition at line 2897 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::removeIndex().
write()
bool write (Ostream & os) const
Definition at line 2996 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
writeTreeInfo()
void writeTreeInfo () const
Definition at line 2969 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const dynamicIndexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.H
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.C