OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
HashTableCore Struct Reference
Template-invariant bits for HashTable.
Classes
struct iteratorEnd
A zero-sized end iterator.
Public Member Functions
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Static Public Member Functions
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes
static const label maxTableSize
Maximum allowable table size.
Detailed Description
Template-invariant bits for HashTable.
Definition at line 76 of file HashTable.H.
Constructor & Destructor Documentation
HashTableCore()
HashTableCore () inline
Construct null.
Definition at line 85 of file HashTable.H.
References HashTableCore::ClassName().
Member Function Documentation
canonicalSize()
Foam::label canonicalSize (const label size) static
Return a canonical (power-of-two) size.
Definition at line 47 of file HashTableCore.C.
Referenced by HashTableCore::end().
ClassName()
ClassName ("HashTable")
Define template name and debug.
Referenced by HashTableCore::HashTableCore().
cend()
static iteratorEnd cend () inline static
iteratorEnd set to beyond the end of any HashTable
Definition at line 100 of file HashTable.H.
References HashTableCore::iteratorEnd::iteratorEnd().
Referenced by HashSet< Foam::word >::HashSet(), HashTable< Foam::phase *>::HashTable(), HashSet< Foam::word >::operator-=(), HashTable< Foam::phase *>::operator=(), HashSet< Foam::word >::operator==(), HashTable< Foam::phase *>::operator==(), HashTable< Foam::phase *>::operator[](), HashSet< Foam::word >::operator^=(), and HashSet< Foam::word >::operator|=().
end()
static iteratorEnd end () inline static
iteratorEnd set to beyond the end of any HashTable
Definition at line 106 of file HashTable.H.
References HashTableCore::canonicalSize(), HashTableCore::iteratorEnd::iteratorEnd(), and Foam::T().
Referenced by distribution::add(), cellTable::addCellZones(), faceZoneSet::addSet(), enrichedPatch::calcEnrichedFaces(), cellMatcher::calcLocalFaces(), createShellMesh::calcPointRegions(), GAMGAgglomeration::calculateRegionMaster(), primitiveMesh::checkFaceFaces(), patchPatchDist::correct(), cyclicPolyPatch::coupledEdges(), meshRefinement::createZoneBaffles(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), faceZoneSet::deleteSet(), objectRegistry::foundObject(), hexRef8::getAnchorLevel(), autoSnapDriver::getZoneSurfacePoints(), distributedTriSurfaceMesh::globalSize(), polyBoundaryMesh::groupPatchIDs(), HashPtrTable< ThermoType >::HashPtrTable(), distribution::insertMissingKeys(), fvMeshSubset::interpolate(), lduPrimitiveMesh::lduPrimitiveMesh(), STLASCIILexer::lex(), zone::localID(), IOobjectList::lookup(), objectRegistry::lookupObject(), basicThermo::lookupThermo(), Foam::MapGeometricFields(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), polyBoundaryMesh::matchGroups(), PatchTools::matchPoints(), polyMeshAdder::mergePoints(), globalMeshData::mergePoints(), polyTopoChange::modifyFace(), slidingInterface::modifyMotionPoints(), polyTopoChange::modifyPoint(), cellTable::name(), NamedEnum< directionType, 3 >::names(), polyBoundaryMesh::neighbourEdges(), isNotEqOp< T >::operator()(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), HashTable< Foam::phase *>::operator()(), HashTable< Foam::phase *>::operator[](), Foam::parseNASCoord(), PatchTools::pointNormals(), fvMeshDistribute::printCoupleInfo(), processorGAMGInterface::processorGAMGInterface(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), wallBoundedStreamLine::read(), STARCD::readBoundary(), regionCoupledBaseGAMGInterface::regionCoupledBaseGAMGInterface(), IOobjectList::remove(), cellTable::setName(), duplicatePoints::setRefinement(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), combineFaces::setUnrefinement(), UnsortedMeshedSurface< Face >::sortedZones(), faceZoneSet::subset(), surfaceFeatures::surfaceFeatures(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncPointList(), syncTools::syncPointMap(), boundaryCutter::updateMesh(), hexRef8::updateMesh(), meshReader::warnDuplicates(), ZoneMesh< cellZone, polyMesh >::whichZone(), regionSizeDistribution::write(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
Member Data Documentation
maxTableSize
const Foam::label maxTableSize static
Maximum allowable table size.
Definition at line 82 of file HashTable.H.
The documentation for this struct was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableCore.C