OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LList< LListBase, T > Class Template Reference
Template class for non-intrusive linked lists.
Classes
class const_iterator
An STL-conforming const_iterator.
class iterator
An STL-conforming iterator.
struct link
Link structure.
Public Types
typedef T value_type
Type of values the LList contains.
typedef T & reference
Type that can be used for storing into value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a LList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Public Member Functions
LList ()
Null construct.
LList (T a)
Construct given initial T.
LList (Istream &)
Construct from Istream.
LList (const LList< LListBase, T > &)
Construct as copy.
~LList ()
Destructor.
T & first ()
Return the first entry added.
const T & first () const
Return const access to the first entry added.
T & last ()
Return the last entry added.
const T & last () const
Return const access to the last entry added.
void insert (const T &a)
Add at head of list.
void append (const T &a)
Add at tail of list.
T removeHead ()
Remove and return head.
T remove (link *l)
Remove and return element.
T remove (iterator &it)
Remove and return element specified by iterator.
void clear ()
Delete contents of list.
void transfer (LList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const LList< LListBase, T > &)
Friends
class iterator
class const_iterator
Istream & operator>> (Istream &, LList< LListBase, T > &)
Ostream & operator (Ostream &, const LList< LListBase, T > &)
Detailed Description
template<class LListBase, class T>
class Foam::LList< LListBase, T >
Template class for non-intrusive linked lists.
Source files
LList.H
LList.C
LListIO.C
Definition at line 51 of file LList.H.
Member Typedef Documentation
value_type
typedef T value_type
Type of values the LList contains.
Definition at line 213 of file LList.H.
reference
typedef T& reference
Type that can be used for storing into value_type.
objects.
Definition at line 217 of file LList.H.
const_reference
typedef const T& const_reference
Type that can be used for storing into constant.
LList::value_type objects.
Definition at line 221 of file LList.H.
size_type
typedef label size_type
The type that can represent the size of a LList.
Definition at line 224 of file LList.H.
LListBase_iterator
typedef LListBase::iterator LListBase_iterator
Definition at line 229 of file LList.H.
LListBase_const_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Definition at line 270 of file LList.H.
Constructor & Destructor Documentation
LList() [1/4]
LList () inline
Null construct.
Definition at line 108 of file LList.H.
Referenced by LList< DLListBase, Foam::entry * >::LList().
LList() [2/4]
LList (T a) inline
Construct given initial T.
Definition at line 112 of file LList.H.
LList() [3/4]
LList (Istream & is)
Construct from Istream.
Definition at line 33 of file LListIO.C.
LList() [4/4]
LList (const LList< LListBase, T > & lst)
Construct as copy.
Definition at line 32 of file LList.C.
~LList()
~LList ()
Destructor.
Definition at line 44 of file LList.C.
Referenced by LList< DLListBase, Foam::entry * >::LList().
Member Function Documentation
first() [1/2]
T& first () inline
Return the first entry added.
Definition at line 133 of file LList.H.
Referenced by LPtrList< DLListBase, Foam::phaseModel >::first(), and Foam::polyMeshZipUpCells().
first() [2/2]
const T& first () const inline
Return const access to the first entry added.
Definition at line 139 of file LList.H.
last() [1/2]
T& last () inline
Return the last entry added.
Definition at line 145 of file LList.H.
Referenced by LPtrList< DLListBase, Foam::phaseModel >::last(), and Foam::polyMeshZipUpCells().
last() [2/2]
const T& last () const inline
Return const access to the last entry added.
Definition at line 151 of file LList.H.
insert()
void insert (const T & a) inline
Add at head of list.
Definition at line 160 of file LList.H.
Referenced by Foam::polyMeshZipUpCells().
append()
void append (const T & a) inline
Add at tail of list.
Definition at line 166 of file LList.H.
Referenced by LList< DLListBase, Foam::entry * >::LList(), and Foam::polyMeshZipUpCells().
removeHead()
T removeHead () inline
Remove and return head.
Definition at line 172 of file LList.H.
Referenced by Foam::polyMeshZipUpCells().
remove() [1/2]
T remove (link * l) inline
Remove and return element.
Definition at line 181 of file LList.H.
remove() [2/2]
T remove (iterator & it) inline
Remove and return element specified by iterator.
Definition at line 190 of file LList.H.
clear()
void clear ()
Delete contents of list.
Definition at line 53 of file LList.C.
Referenced by LList< DLListBase, Foam::entry * >::LList(), and LList< DLListBase, Foam::entry * >::remove().
transfer()
void transfer (LList< LListBase, T > & lst)
Transfer the contents of the argument into this List.
and annul the argument list.
Definition at line 66 of file LList.C.
Referenced by LList< DLListBase, Foam::entry * >::remove().
operator=()
void operator= (const LList< LListBase, T > & lst)
Definition at line 76 of file LList.C.
Referenced by LList< DLListBase, Foam::entry * >::remove().
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 82 of file LList.H.
const_iterator
friend class const_iterator friend
Definition at line 85 of file LList.H.
operator>>
Istream& operator>> (Istream & , LList< LListBase, T > &) friend
operator
Ostream& operator (Ostream & , const LList< LListBase, T > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LListIO.C