OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LPtrList< LListBase, T >::const_iterator Class Reference
An STL-conforming const_iterator.
Public Member Functions
const_iterator (LListBase_const_iterator baseIter)
Construct from base const_iterator.
const_iterator (LListBase_iterator baseIter)
Construct from base iterator.
const T & operator* ()
const T & operator() ()
Public Member Functions inherited from LList< LListBase, T >::const_iterator
const_iterator (LListBase_const_iterator baseIter)
Construct from base const_iterator.
const_iterator (LListBase_iterator baseIter)
Construct from base iterator.
const T & operator* ()
const T & operator() ()
const_iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::LPtrList< LListBase, T >::const_iterator
An STL-conforming const_iterator.
Definition at line 215 of file LPtrList.H.
Constructor & Destructor Documentation
const_iterator() [1/2]
const_iterator (LListBase_const_iterator baseIter) inline
Construct from base const_iterator.
Definition at line 223 of file LPtrList.H.
const_iterator() [2/2]
const_iterator (LListBase_iterator baseIter) inline
Construct from base iterator.
Definition at line 229 of file LPtrList.H.
Member Function Documentation
operator*()
const T& operator* () inline
Definition at line 237 of file LPtrList.H.
References LList< LListBase, T >::const_iterator::operator*().
operator()()
const T& operator() () inline
Definition at line 242 of file LPtrList.H.
References LPtrList< LListBase, T >::iterator::operator*(), and Foam::T().
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrList.H