OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ILList< LListBase, T > Class Template Reference
Template class for intrusive linked lists.
Public Member Functions
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Friends
Istream & operator>> (Istream &, ILList< LListBase, T > &)
Read List from Istream, discarding contents of existing List.
Additional Inherited Members
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
typedef LListBase::const_reverse_iterator LListBase_const_reverse_iterator
Detailed Description
template<class LListBase, class T>
class Foam::ILList< LListBase, T >
Template class for intrusive linked lists.
Source files
ILList.H
ILList.C
ILListIO.C
Definition at line 50 of file ILList.H.
Constructor & Destructor Documentation
ILList() [1/6]
ILList () inline
Null construct.
Definition at line 80 of file ILList.H.
Referenced by ILList< DLListBase, Foam::molecule >::ILList().
ILList() [2/6]
ILList (T * a) inline
Construct given initial T.
Definition at line 84 of file ILList.H.
ILList() [3/6]
ILList (Istream & is)
Construct from Istream.
Definition at line 139 of file ILListIO.C.
ILList() [4/6]
ILList (const ILList< LListBase, T > & lst)
Construct as copy.
Definition at line 31 of file ILList.C.
ILList() [5/6]
ILList (const ILList< LListBase, T > & lst, const CloneArg & cloneArg)
Copy constructor with additional argument for clone.
Definition at line 51 of file ILList.C.
ILList() [6/6]
ILList (Istream & is, const INew & iNew)
Construct from Istream using given Istream constructor class.
Definition at line 132 of file ILListIO.C.
~ILList()
~ILList ()
Destructor.
Definition at line 74 of file ILList.C.
Referenced by ILList< DLListBase, Foam::molecule >::ILList().
Member Function Documentation
eraseHead()
bool eraseHead ()
Remove the head element specified from the list and delete it.
Definition at line 83 of file ILList.C.
Referenced by ILList< DLListBase, Foam::molecule >::ILList().
erase()
bool erase (T * p)
Remove the specified element from the list and delete it.
Definition at line 98 of file ILList.C.
Referenced by ILList< DLListBase, Foam::molecule >::ILList(), refinementSurfaces::refinementSurfaces(), and shellSurfaces::shellSurfaces().
clear()
void clear ()
Clear the contents of the list.
Definition at line 114 of file ILList.C.
Referenced by ILList< DLListBase, Foam::molecule >::ILList().
transfer()
void transfer (ILList< LListBase, T > & lst)
Transfer the contents of the argument into this List.
and annul the argument list.
Definition at line 127 of file ILList.C.
Referenced by ILList< DLListBase, Foam::molecule >::ILList().
operator=()
void operator= (const ILList< LListBase, T > & lst)
Definition at line 137 of file ILList.C.
Referenced by ILList< DLListBase, Foam::molecule >::ILList().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , ILList< LListBase, T > &) friend
Read List from Istream, discarding contents of existing List.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/ILList/ILList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/ILList/ILList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/ILList/ILListIO.C