OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LList< LListBase, T >::iterator Class Reference
An STL-conforming iterator.
Public Member Functions
iterator (LListBase_iterator baseIter)
Construct from base iterator.
T & operator* ()
T & operator() ()
iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::LList< LListBase, T >::iterator
An STL-conforming iterator.
Definition at line 232 of file LList.H.
Constructor & Destructor Documentation
iterator()
iterator (LListBase_iterator baseIter) inline
Construct from base iterator.
Definition at line 240 of file LList.H.
Member Function Documentation
operator*()
T& operator* () inline
Definition at line 248 of file LList.H.
References LList< LListBase, T >::link::obj_, and Foam::operator*().
Referenced by LPtrList< LListBase, T >::iterator::operator*().
operator()()
T& operator() () inline
Definition at line 255 of file LList.H.
References Foam::operator*().
operator++()
iterator& operator++ () inline
Definition at line 260 of file LList.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H