OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DLListBase Class Reference
Base doubly-linked list.
Classes
class const_iterator
An STL-conforming const_iterator.
class const_reverse_iterator
An STL-conforming const_reverse_iterator.
class iterator
An STL-conforming iterator.
struct link
Link structure.
Public Member Functions
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Friends
class iterator
class const_iterator
class const_reverse_iterator
Detailed Description
Base doubly-linked list.
Source files
DLListBase.H
DLListBase.C
Definition at line 50 of file DLListBase.H.
Constructor & Destructor Documentation
DLListBase() [1/2]
DLListBase () inline
Null construct.
Definition at line 37 of file DLListBaseI.H.
DLListBase() [2/2]
DLListBase (link * a) inline
Construct given initial entry.
Definition at line 45 of file DLListBaseI.H.
References DLListBase::link::next_, and DLListBase::link::prev_.
~DLListBase()
~DLListBase () inline
Destructor.
Definition at line 58 of file DLListBaseI.H.
Member Function Documentation
size()
Foam::label size () const inline
Return number of elements in list.
Definition at line 77 of file DLListBaseI.H.
Referenced by sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), DLListBase::begin(), DLListBase::cbegin(), cellSizeFunction::coeffsDict(), DLListBase::crbegin(), dictionaryEntry::endLineNumber(), dictionary::endLineNumber(), interpolation2DTable< scalar >::interpolation2DTable(), dictionary::keys(), singleLayerRegion::mappedFieldAndInternalPatchTypes(), mappedPatchBase::mappedPatchBase(), singleLayerRegion::mappedPushedFieldPatchTypes(), multiLevelDecomp::multiLevelDecomp(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), phaseProperties::phaseProperties(), radiationCoupledBase::radiationCoupledBase(), thermalBaffleModel::read(), functionObjectList::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), Cloud< streamLineParticle >::size(), tolerances::solverRelativeTolerances(), dictionaryEntry::startLineNumber(), dictionary::startLineNumber(), dictionary::toc(), Foam::unitSet(), linearDistance::~linearDistance(), linearSpatial::~linearSpatial(), surfaceOffsetLinearDistance::~surfaceOffsetLinearDistance(), uniform::~uniform(), and uniformDistance::~uniformDistance().
empty()
bool empty () const inline
Return true if the list is empty.
Definition at line 83 of file DLListBaseI.H.
Referenced by cellTable::combine(), and boundaryRegion::rename().
first() [1/2]
Foam::DLListBase::link * first () inline
Return first entry.
Definition at line 90 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by DLListBase::begin(), and DLListBase::cbegin().
first() [2/2]
const Foam::DLListBase::link * first () const inline
Return const access to first entry.
Definition at line 103 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
last() [1/2]
Foam::DLListBase::link * last () inline
Return last entry.
Definition at line 116 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by DLListBase::crbegin().
last() [2/2]
const Foam::DLListBase::link * last () const inline
Return const access to last entry.
Definition at line 129 of file DLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
insert()
void insert (DLListBase::link * a)
Add at head of list.
Definition at line 54 of file DLListBase.C.
References DLListBase::link::next_, and DLListBase::link::prev_.
append()
void append (DLListBase::link * a)
Add at tail of list.
Definition at line 74 of file DLListBase.C.
References DLListBase::link::next_, and DLListBase::link::prev_.
Referenced by dictionary::add(), IOPosition< CloudType >::readData(), and Foam::reconstructLagrangianPositions().
swapUp()
bool swapUp (DLListBase::link * a)
Swap this element with the one above unless it is at the top.
Definition at line 94 of file DLListBase.C.
References DLListBase::link::next_, and DLListBase::link::prev_.
swapDown()
bool swapDown (DLListBase::link * a)
Swap this element with the one below unless it is at the bottom.
Definition at line 135 of file DLListBase.C.
References DLListBase::link::next_, and DLListBase::link::prev_.
removeHead()
Foam::DLListBase::link * removeHead ()
Remove and return head.
Definition at line 176 of file DLListBase.C.
References Foam::abort(), DLListBase::link::deregister(), f(), Foam::FatalError, FatalErrorIn, and DLListBase::link::next_.
remove() [1/2]
Foam::DLListBase::link * remove (DLListBase::link * l)
Remove and return element.
Definition at line 200 of file DLListBase.C.
References DLListBase::link::deregister(), DLListBase::link::next_, DLListBase::link::prev_, and DLListBase::replace().
Referenced by DLListBase::transfer().
remove() [2/2]
Foam::DLListBase::link * remove (DLListBase::iterator & it) inline
Definition at line 161 of file DLListBaseI.H.
References DLListBase::replace().
replace() [1/2]
Foam::DLListBase::link * replace (DLListBase::link * oldLink, DLListBase::link * newLink)
Replace oldLink with newLink and return element.
Definition at line 233 of file DLListBase.C.
References DLListBase::link::deregister(), DLListBase::link::next_, and DLListBase::link::prev_.
Referenced by dictionary::add(), dictionary::changeKeyword(), DLListBase::remove(), and DLListBase::replace().
replace() [2/2]
Foam::DLListBase::link * replace (DLListBase::iterator & oldIter, DLListBase::link * newLink) inline
Replace oldIter with newLink and return element.
Definition at line 171 of file DLListBaseI.H.
References DLListBase::replace().
clear()
void clear () inline
Clear the list.
Definition at line 141 of file DLListBaseI.H.
Referenced by DLListBase::transfer().
transfer()
void transfer (DLListBase & lst) inline
Transfer the contents of the argument into this List.
and annul the argument list.
Definition at line 149 of file DLListBaseI.H.
References DLListBase::clear(), and DLListBase::remove().
begin() [1/2]
Foam::DLListBase::iterator begin () inline
Definition at line 253 of file DLListBaseI.H.
References DLListBase::first(), and DLListBase::size().
Referenced by Cloud< streamLineParticle >::begin().
end() [1/2]
const Foam::DLListBase::iterator & end () inline
Definition at line 266 of file DLListBaseI.H.
References DLListBase::const_iterator::const_iterator().
Referenced by Cloud< streamLineParticle >::end().
cbegin()
Foam::DLListBase::const_iterator cbegin () const inline
Definition at line 352 of file DLListBaseI.H.
References DLListBase::const_iterator::const_iterator(), DLListBase::first(), and DLListBase::size().
Referenced by DLListBase::begin(), and Cloud< streamLineParticle >::cbegin().
cend()
const Foam::DLListBase::const_iterator & cend () const inline
Definition at line 366 of file DLListBaseI.H.
Referenced by Cloud< streamLineParticle >::cend().
begin() [2/2]
Foam::DLListBase::const_iterator begin () const inline
Definition at line 373 of file DLListBaseI.H.
References DLListBase::cbegin().
end() [2/2]
const Foam::DLListBase::const_iterator & end () const inline
Definition at line 380 of file DLListBaseI.H.
References DLListBase::const_reverse_iterator::const_reverse_iterator().
crbegin()
Foam::DLListBase::const_reverse_iterator crbegin () const inline
Definition at line 459 of file DLListBaseI.H.
References DLListBase::const_reverse_iterator, DLListBase::last(), and DLListBase::size().
Referenced by DLListBase::rbegin().
crend()
const Foam::DLListBase::const_reverse_iterator & crend () const inline
Definition at line 473 of file DLListBaseI.H.
rbegin()
Foam::DLListBase::const_reverse_iterator rbegin () const inline
Definition at line 480 of file DLListBaseI.H.
References DLListBase::crbegin().
Referenced by GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField().
rend()
const Foam::DLListBase::const_reverse_iterator & rend () const inline
Definition at line 487 of file DLListBaseI.H.
Referenced by GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField().
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 96 of file DLListBase.H.
const_iterator
friend class const_iterator friend
Definition at line 99 of file DLListBase.H.
const_reverse_iterator
friend class const_reverse_iterator friend
Definition at line 102 of file DLListBase.H.
Referenced by DLListBase::crbegin().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/linkTypes/DLListBase/DLListBase.H
src/OpenFOAM/containers/LinkedLists/linkTypes/DLListBase/DLListBase.C
src/OpenFOAM/containers/LinkedLists/linkTypes/DLListBase/DLListBaseI.H