OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SLListBase Class Reference
Base singly-linked list.
Classes
class const_iterator
An STL-conforming const_iterator.
class iterator
An STL-conforming iterator.
struct link
Link structure.
Public Member Functions
SLListBase ()
Null construct.
SLListBase (link *)
Construct given initial entry.
~SLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
link * removeHead ()
Remove and return head.
link * remove (link *)
link * remove (iterator &)
void clear ()
Clear the list.
void transfer (SLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
Friends
class iterator
class const_iterator
Detailed Description
Base singly-linked list.
Source files
SLListBase.H
SLListBase.C
Definition at line 50 of file SLListBase.H.
Constructor & Destructor Documentation
SLListBase() [1/2]
SLListBase () inline
Null construct.
Definition at line 45 of file SLListBaseI.H.
SLListBase() [2/2]
SLListBase (link * a) inline
Construct given initial entry.
Definition at line 52 of file SLListBaseI.H.
~SLListBase()
~SLListBase () inline
Destructor.
Definition at line 61 of file SLListBaseI.H.
Member Function Documentation
size()
Foam::label size () const inline
Return number of elements in list.
Definition at line 67 of file SLListBaseI.H.
Referenced by SLListBase::begin(), SLListBase::cbegin(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), FixedList< bool, Foam::pTraits< Type >::nComponents >::operator=(), List< functionObject *>::operator=(), PtrList< MRFZone >::PtrList(), PtrList< MRFZone >::read(), and UList< Foam::wordRe >::writeEntry().
empty()
bool empty () const inline
Return true if the list is empty.
Definition at line 73 of file SLListBaseI.H.
first() [1/2]
Foam::SLListBase::link * first () inline
Return first entry.
Definition at line 80 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and SLListBase::link::next_.
Referenced by SLListBase::begin(), and SLListBase::cbegin().
first() [2/2]
const Foam::SLListBase::link * first () const inline
Return const access to first entry.
Definition at line 93 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and SLListBase::link::next_.
last() [1/2]
Foam::SLListBase::link * last () inline
Return last entry.
Definition at line 106 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
last() [2/2]
const Foam::SLListBase::link * last () const inline
Return const access to last entry.
Definition at line 119 of file SLListBaseI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
insert()
void insert (SLListBase::link * a)
Add at head of list.
Definition at line 45 of file SLListBase.C.
References SLListBase::link::next_.
append()
void append (SLListBase::link * a)
Add at tail of list.
Definition at line 62 of file SLListBase.C.
References SLListBase::link::next_.
removeHead()
Foam::SLListBase::link * removeHead ()
Remove and return head.
Definition at line 78 of file SLListBase.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorIn, and SLListBase::link::next_.
Referenced by SLListBase::remove().
remove() [1/2]
Foam::SLListBase::link * remove (SLListBase::link * it)
Definition at line 104 of file SLListBase.C.
References SLListBase::begin(), SLListBase::end(), SLListBase::link::next_, p, and SLListBase::removeHead().
Referenced by SLListBase::transfer().
remove() [2/2]
Foam::SLListBase::link * remove (SLListBase::iterator & it) inline
Definition at line 148 of file SLListBaseI.H.
clear()
void clear () inline
Clear the list.
Definition at line 131 of file SLListBaseI.H.
Referenced by SLListBase::transfer().
transfer()
void transfer (SLListBase & lst) inline
Transfer the contents of the argument into this List.
and annul the argument list.
Definition at line 138 of file SLListBaseI.H.
References SLListBase::clear(), and SLListBase::remove().
begin() [1/2]
Foam::SLListBase::iterator begin () inline
Definition at line 225 of file SLListBaseI.H.
References SLListBase::first(), and SLListBase::size().
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), List< functionObject *>::List(), List< functionObject *>::operator=(), FixedList< bool, Foam::pTraits< Type >::nComponents >::operator=(), PtrList< MRFZone >::PtrList(), PtrList< MRFZone >::read(), SLListBase::remove(), and UList< Foam::wordRe >::writeEntry().
end() [1/2]
const Foam::SLListBase::iterator & end () inline
Definition at line 239 of file SLListBaseI.H.
References SLListBase::const_iterator::const_iterator().
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), List< functionObject *>::List(), List< functionObject *>::operator=(), FixedList< bool, Foam::pTraits< Type >::nComponents >::operator=(), PtrList< MRFZone >::PtrList(), PtrList< MRFZone >::read(), SLListBase::remove(), and UList< Foam::wordRe >::writeEntry().
cbegin()
Foam::SLListBase::const_iterator cbegin () const inline
Definition at line 325 of file SLListBaseI.H.
References SLListBase::const_iterator::const_iterator(), SLListBase::first(), and SLListBase::size().
Referenced by SLListBase::begin().
cend()
const Foam::SLListBase::const_iterator & cend () const inline
Definition at line 339 of file SLListBaseI.H.
begin() [2/2]
Foam::SLListBase::const_iterator begin () const inline
Definition at line 346 of file SLListBaseI.H.
References SLListBase::cbegin().
end() [2/2]
const Foam::SLListBase::const_iterator & end () const inline
Definition at line 353 of file SLListBaseI.H.
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 93 of file SLListBase.H.
const_iterator
friend class const_iterator friend
Definition at line 96 of file SLListBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/linkTypes/SLListBase/SLListBase.H
src/OpenFOAM/containers/LinkedLists/linkTypes/SLListBase/SLListBase.C
src/OpenFOAM/containers/LinkedLists/linkTypes/SLListBase/SLListBaseI.H