OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
BiIndirectList< T > Class Template Reference
Indexes into negList (negative index) or posList (zero or positive index).
Public Member Functions
BiIndirectList (const UList< T > &posList, const UList< T > &negList, const labelUList &)
Construct given the complete lists and the addressing array.
BiIndirectList (const UList< T > &posList, const UList< T > &negList, const Xfer< List< label > > &)
Construct given the complete list and by transferring addressing.
label size () const
Return the number of elements in the list.
bool empty () const
Return true if the list is empty (ie, size() is zero).
const UList< T > & posList () const
const UList< T > & negList () const
const List< label > & addressing () const
Return the list addressing.
void resetAddressing (const labelUList &)
Reset addressing.
void resetAddressing (const Xfer< List< label > > &)
List< T > operator() () const
Return the addressed elements as a List.
T & operator[] (const label)
Return non-const access to an element.
const T & operator[] (const label) const
Return const access to an element.
void operator= (const UList< T > &)
Assignment from UList of addressed elements.
void operator= (const T &)
Assignment of all entries to the given value.
Static Public Member Functions
static label posIndex (const label)
Calculate index given whether index is into posList or negList.
static label negIndex (const label)
Detailed Description
template<class T>
class Foam::BiIndirectList< T >
Indexes into negList (negative index) or posList (zero or positive index).
Source files
BiIndirectList.H
BiIndirectListI.H
Definition at line 49 of file BiIndirectList.H.
Constructor & Destructor Documentation
BiIndirectList() [1/2]
BiIndirectList (const UList< T > & posList, const UList< T > & negList, const labelUList & addr) inline
Construct given the complete lists and the addressing array.
Definition at line 30 of file BiIndirectListI.H.
BiIndirectList() [2/2]
BiIndirectList (const UList< T > & posList, const UList< T > & negList, const Xfer< List< label > > & addr) inline
Construct given the complete list and by transferring addressing.
Definition at line 44 of file BiIndirectListI.H.
Member Function Documentation
size()
Foam::label size () const inline
Return the number of elements in the list.
Definition at line 59 of file BiIndirectListI.H.
Referenced by List< functionObject *>::operator=().
empty()
bool empty () const inline
Return true if the list is empty (ie, size() is zero).
Definition at line 66 of file BiIndirectListI.H.
posList()
const Foam::UList< T > & posList () const inline
Definition at line 73 of file BiIndirectListI.H.
negList()
const Foam::UList< T > & negList () const inline
Definition at line 80 of file BiIndirectListI.H.
addressing()
const Foam::List< Foam::label > & addressing () const inline
Return the list addressing.
Definition at line 87 of file BiIndirectListI.H.
References BiIndirectList< T >::resetAddressing().
posIndex()
Foam::label posIndex (const label i) inline static
Calculate index given whether index is into posList or negList.
Definition at line 115 of file BiIndirectListI.H.
negIndex()
Foam::label negIndex (const label i) inline static
Definition at line 122 of file BiIndirectListI.H.
resetAddressing() [1/2]
void resetAddressing (const labelUList & addr) inline
Reset addressing.
Definition at line 96 of file BiIndirectListI.H.
Referenced by BiIndirectList< T >::addressing().
resetAddressing() [2/2]
void resetAddressing (const Xfer< List< label > > & addr) inline
Definition at line 106 of file BiIndirectListI.H.
operator()()
Foam::List< T > operator() () const inline
Return the addressed elements as a List.
Definition at line 131 of file BiIndirectListI.H.
References forAll.
operator[]() [1/2]
T & operator[] (const label i) inline
Return non-const access to an element.
Definition at line 145 of file BiIndirectListI.H.
operator[]() [2/2]
const T & operator[] (const label i) const inline
Return const access to an element.
Definition at line 161 of file BiIndirectListI.H.
operator=() [1/2]
void operator= (const UList< T > & ae) inline
Assignment from UList of addressed elements.
Definition at line 177 of file BiIndirectListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, and UList< T >::size().
operator=() [2/2]
void operator= (const T & t) inline
Assignment of all entries to the given value.
Definition at line 196 of file BiIndirectListI.H.
References forAll.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/BiIndirectList/BiIndirectList.H
src/OpenFOAM/containers/Lists/BiIndirectList/BiIndirectListI.H