OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Histogram< List > Class Template Reference
Calculates the counts per bin of a list.
Public Member Functions
Histogram (const List &bins, const List &l)
Construct given bin values and input list.
Histogram (const typename List::const_reference min, const typename List::const_reference max, const label nBins, const List &l)
Construct given min, max, number of bins and input list.
const labelList & counts () const
Return the counts per bin.
label nLow () const
Return the number of elements <= bins[0].
label nHigh () const
Return the number of elements > bins[bins.size()-1].
Detailed Description
template<class List>
class Foam::Histogram< List >
Calculates the counts per bin of a list.
Source files
Histogram.H
Histogram.C
Definition at line 50 of file Histogram.H.
Constructor & Destructor Documentation
Histogram() [1/2]
Histogram (const List & bins, const List & l)
Construct given bin values and input list.
Definition at line 71 of file Histogram.C.
Histogram() [2/2]
Histogram (const typename List::const_reference min, const typename List::const_reference max, const label nBins, const List & l)
Construct given min, max, number of bins and input list.
Definition at line 79 of file Histogram.C.
References Foam::max(), and Foam::min().
Member Function Documentation
counts()
const labelList& counts () const inline
Return the counts per bin.
Definition at line 95 of file Histogram.H.
References Histogram< List >::nHigh(), and Histogram< List >::nLow().
nLow()
label nLow () const inline
Return the number of elements <= bins[0].
(so inclusive lowest bin value)
Definition at line 102 of file Histogram.H.
Referenced by Histogram< List >::counts().
nHigh()
label nHigh () const inline
Return the number of elements > bins[bins.size()-1].
(so exclusive highest bin value)
Definition at line 109 of file Histogram.H.
Referenced by Histogram< List >::counts().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/Histogram/Histogram.H
src/OpenFOAM/containers/Lists/Histogram/Histogram.C