OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PtrList< T > Class Template Reference
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
Inherited by blockMesh, fvBoundaryMesh, IOPtrList< T >, pointBoundaryMesh, and polyBoundaryMesh.
Classes
class iterator
An STL-conforming iterator.
Public Types
typedef T value_type
Type of values the PtrList contains.
typedef T & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant PtrList::value_type.
Public Member Functions
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element. Return old element (can be NULL).
autoPtr< T > set (const label, const autoPtr< T > &)
autoPtr< T > set (const label, const tmp< T > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
PtrList< T > & operator= (const PtrList< T > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
Protected Member Functions
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Friends
class iterator
Istream & operator>> (Istream &, PtrList< T > &)
Read List from Istream, discarding contents of existing List.
Ostream & operator (Ostream &, const PtrList< T > &)
Detailed Description
template<class T>
class Foam::PtrList< T >
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
The element operator [] returns a reference to the object rather than a pointer.
Source files
PtrList.H
PtrList.C
PtrListIO.C
Definition at line 61 of file List.H.
Member Typedef Documentation
value_type
typedef T value_type
Type of values the PtrList contains.
Definition at line 233 of file PtrList.H.
reference
typedef T& reference
Type that can be used for storing into PtrList::value_type objects.
Definition at line 236 of file PtrList.H.
const_reference
typedef const T& const_reference
Type that can be used for storing into constant PtrList::value_type.
objects.
Definition at line 240 of file PtrList.H.
Constructor & Destructor Documentation
PtrList() [1/9]
PtrList ()
Null Constructor.
Definition at line 34 of file PtrList.C.
PtrList() [2/9]
PtrList (const label s) explicit
Construct with size specified.
Definition at line 41 of file PtrList.C.
PtrList() [3/9]
PtrList (const PtrList< T > & a)
Copy constructor.
Definition at line 48 of file PtrList.C.
PtrList() [4/9]
PtrList (const PtrList< T > & a, const CloneArg & cloneArg)
Copy constructor with additional argument for clone.
Definition at line 61 of file PtrList.C.
PtrList() [5/9]
PtrList (const Xfer< PtrList< T > > & lst)
Construct by transferring the parameter contents.
Definition at line 73 of file PtrList.C.
PtrList() [6/9]
PtrList (PtrList< T > & a, bool reUse)
Construct as copy or re-use as specified.
Definition at line 80 of file PtrList.C.
PtrList() [7/9]
PtrList (const SLPtrList< T > & sll) explicit
Construct as copy of SLPtrList<T>
Definition at line 104 of file PtrList.C.
PtrList() [8/9]
PtrList (Istream & is, const INew & inewt)
Construct from Istream using given Istream constructor class.
Definition at line 163 of file PtrListIO.C.
PtrList() [9/9]
PtrList (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 170 of file PtrListIO.C.
~PtrList()
~PtrList ()
Destructor.
Definition at line 127 of file PtrList.C.
Member Function Documentation
read()
void read (Istream & is, const INew & inewt) protected
Read from Istream using given Istream constructor class.
Definition at line 36 of file PtrListIO.C.
Referenced by PtrList< MRFZone >::PtrList().
size()
Foam::label size () const inline
Return the number of elements in the PtrList.
Definition at line 34 of file PtrListI.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), autoLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), extendedEdgeMesh::allNearestFeatureEdges(), meshRefinement::appendPatch(), attachPolyTopoChanger::attach(), Foam::compressible::autoCreateAlphat(), Foam::compressible::autoCreateLowReMut(), Foam::incompressible::autoCreateLowReNut(), Foam::compressible::autoCreateMut(), Foam::incompressible::autoCreateNut(), Foam::incompressible::autoCreateWallFunctionField(), Foam::compressible::autoCreateWallFunctionField(), nearWallFields::calcAddressing(), addPatchCellLayer::calcSidePatch(), polyTopoChange::changeMesh(), repatchPolyTopoChanger::changePatchID(), polyBoundaryMesh::checkDefinition(), polyBoundaryMesh::checkParallelSync(), inverseFaceDistanceDiffusivity::correct(), nearWallDistNoSearch::correct(), nearWallDist::correct(), pointPatchDist::correct(), wallDistData< wallPointData< vector > >::correct(), motionSmootherAlgo::curPoints(), structuredDecomp::decompose(), decompositionMethod::decompose(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), fvMeshDistribute::distribute(), autoLayerDriver::doLayers(), polyBoundaryMesh::findPatchIDs(), fvFieldReconstructor::fvFieldReconstructor(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), cellDistFuncs::getPatchIDs(), surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), injectionModelList::info(), interRegionExplicitPorositySource::initialise(), fvBoundaryMesh::interfaces(), meshToMesh::interpolationMethodAMI(), regionModel::interRegionAMI(), layerParameters::layerParameters(), lduPrimitiveMesh::lduPrimitiveMesh(), LUscalarMatrix::LUscalarMatrix(), meshRefinement::makeDisplacementField(), polyTopoChange::makeMesh(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), MeshedSurface< Foam::face >::MeshedSurface(), meshTriangulation::meshTriangulation(), polyTopoChanger::names(), ZoneMesh< cellZone, polyMesh >::names(), polyBoundaryMesh::names(), regionModel::nbrCoupledPatchID(), extendedEdgeMesh::nearestFeatureEdgeByType(), potential::nPairPotentials(), blockMesh::numZonedBlocks(), ListPlusEqOp< T, Size >::operator()(), procLess::operator()(), listPlusEqOp< T >::operator()(), PtrList< MRFZone >::operator=(), polyTopoChanger::operator==(), blockMesh::patchDicts(), patchInjection::patchInjection(), polyBoundaryMesh::physicalTypes(), pointFieldReconstructor::pointFieldReconstructor(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), polyTopoChange::polyTopoChange(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), PtrList< MRFZone >::PtrList(), thermalBaffleModel::read(), boundaryMesh::read(), polyMesh::readUpdate(), ensightParts::recalculate(), pointFieldReconstructor::reconstructField(), SloanRenumber::renumber(), structuredRenumber::renumber(), fvMeshSubset::setCellSubset(), polyBoundaryMesh::setGroup(), fvMeshSubset::setLargeCellSubset(), removeCells::setRefinement(), meshCutAndRemove::setRefinement(), singleCellFvMesh::singleCellFvMesh(), ensightParts::size(), pairPatchAgglomeration::size(), GAMGAgglomeration::size(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), polyTopoChanger::types(), ZoneMesh< cellZone, polyMesh >::types(), polyBoundaryMesh::types(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::types(), valveBank::valveBank(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), xmgraceSetWriter< Type >::write(), vtkSetWriter< Type >::write(), gnuplotSetWriter< Type >::write(), polyBoundaryMesh::writeData(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), fvMeshTools::zeroPatchFields(), ZoneMesh< cellZone, polyMesh >::ZoneMesh(), and meshRefinement::zonify().
empty()
bool empty () const inline
Return true if the PtrList is empty (ie, size() is zero).
Definition at line 41 of file PtrListI.H.
Referenced by NamedEnum< directionType, 3 >::names(), and fvMeshTools::zeroPatchFields().
first() [1/2]
T & first () inline
Return reference to the first element of the list.
Definition at line 48 of file PtrListI.H.
first() [2/2]
const T & first () const inline
Return reference to first element of the list.
Definition at line 55 of file PtrListI.H.
last() [1/2]
T & last () inline
Return reference to the last element of the list.
Definition at line 62 of file PtrListI.H.
last() [2/2]
const T & last () const inline
Return reference to the last element of the list.
Definition at line 69 of file PtrListI.H.
setSize()
void setSize (const label newSize)
Reset size of PtrList. If extending the PtrList, new entries are.
set to NULL. If truncating the PtrList, removed entries are deleted.
Definition at line 142 of file PtrList.C.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), cellTable::addCellZones(), fvMeshTools::addPatch(), polyMesh::addPatches(), polyMesh::addZones(), meshRefinement::appendPatch(), polyBoundaryMesh::checkParallelSync(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), FacePostProcessing< CloudType >::FacePostProcessing(), lduPrimitiveMesh::gather(), interRegionExplicitPorositySource::initialise(), patchInjection::patchInjection(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::preservePatchTypes(), fvMeshDistribute::printFieldInfo(), PtrList< MRFZone >::PtrList(), functionObjectList::read(), polyMesh::readUpdate(), polyMesh::removeBoundary(), fvMesh::removeFvBoundary(), searchableSurfaces::searchableSurfaces(), decompositionMethod::setConstraints(), GAMGSolver::solve(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), fvMeshTools::zeroPatchFields(), and ZoneMesh< cellZone, polyMesh >::ZoneMesh().
resize()
void resize (const label newSize) inline
Alias for setSize(const label)
Definition at line 76 of file PtrListI.H.
clear()
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
allocated entries.
Definition at line 185 of file PtrList.C.
Referenced by functionObjectList::clear(), PtrList< MRFZone >::PtrList(), functionObjectList::read(), fvBoundaryMesh::readUpdate(), polyMesh::readUpdate(), polyMesh::removeBoundary(), fvMesh::removeFvBoundary(), and decompositionMethod::setConstraints().
append() [1/3]
void append (T * ptr) inline
Append an element at the end of the list.
Definition at line 83 of file PtrListI.H.
Referenced by PtrList< MRFZone >::append(), and meshToMesh::interpolationMethodAMI().
append() [2/3]
void append (const autoPtr< T > & aptr) inline
Definition at line 92 of file PtrListI.H.
append() [3/3]
void append (const tmp< T > & t) inline
Definition at line 100 of file PtrListI.H.
transfer()
void transfer (PtrList< T > & a)
Transfer the contents of the argument PtrList into this PtrList.
and annul the argument list.
Definition at line 200 of file PtrList.C.
Referenced by functionObjectList::read().
xfer()
Foam::Xfer< Foam::PtrList< T > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 147 of file PtrListI.H.
set() [1/4]
bool set (const label i) const inline
Is element set.
Definition at line 109 of file PtrListI.H.
Referenced by fvMeshAdder::add(), cellTable::addCellZones(), fvMeshTools::addPatch(), polyMesh::addPatches(), polyMesh::addZones(), meshRefinement::appendPatch(), boundaryMesh::deletePatch(), forAll(), lduPrimitiveMesh::gather(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnclosedNamedSurfaces(), interRegionExplicitPorositySource::initialise(), isoSurface::isoSurface(), LUscalarMatrix::LUscalarMatrix(), pointBoundaryMesh::pointBoundaryMesh(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::preservePatchTypes(), fvMeshDistribute::printFieldInfo(), functionObjectList::read(), polyMesh::readUpdate(), refinementSurfaces::refinementSurfaces(), refinementFeatures::regionEdgeTrees(), PtrList< MRFZone >::set(), decompositionMethod::setConstraints(), GAMGSolver::solve(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), and ZoneMesh< cellZone, polyMesh >::ZoneMesh().
set() [2/4]
Foam::autoPtr< T > set (const label i, T * ptr) inline
Set element. Return old element (can be NULL).
No checks on new element.
Definition at line 116 of file PtrListI.H.
set() [3/4]
Foam::autoPtr< T > set (const label i, const autoPtr< T > & aptr) inline
Definition at line 126 of file PtrListI.H.
set() [4/4]
Foam::autoPtr< T > set (const label i, const tmp< T > & t) inline
Definition at line 137 of file PtrListI.H.
reorder()
void reorder (const labelUList & oldToNew)
Reorders elements. Ordering does not have to be done in.
ascending or descending order. Reordering has to be unique. (is shuffle)
Definition at line 208 of file PtrList.C.
Referenced by fvMeshTools::addPatch(), meshRefinement::addPatch(), polyBoundaryMesh::reorder(), and fvMeshTools::reorderPatches().
operator[]() [1/2]
const T & operator[] (const label i) const inline
Return element const reference.
Definition at line 156 of file PtrListI.H.
Referenced by pointBoundaryMesh::findIndices(), pointBoundaryMesh::movePoints(), and pointBoundaryMesh::updateMesh().
operator[]() [2/2]
T & operator[] (const label i) inline
Return element reference.
Definition at line 173 of file PtrListI.H.
operator()()
const T * operator() (const label i) const inline
Return element const pointer.
Definition at line 190 of file PtrListI.H.
operator=()
Foam::PtrList< T > & operator= (const PtrList< T > & a)
Assignment.
Definition at line 261 of file PtrList.C.
begin()
Foam::PtrList< T >::iterator begin () inline
Return an iterator to begin traversing the PtrList.
Definition at line 363 of file PtrListI.H.
end()
Foam::PtrList< T >::iterator end () inline
Return an iterator to end traversing the PtrList.
Definition at line 370 of file PtrListI.H.
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 246 of file PtrList.H.
operator>>
Istream& operator>> (Istream & , PtrList< T > &) friend
Read List from Istream, discarding contents of existing List.
operator
Ostream& operator (Ostream & , const PtrList< T > &) friend
Referenced by fvBoundaryMesh::mesh(), polyBoundaryMesh::mesh(), fvBoundaryMesh::operator[](), polyBoundaryMesh::operator[](), fvBoundaryMesh::readUpdate(), and polyBoundaryMesh::writeObject().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/Lists/PtrList/PtrList.H
src/OpenFOAM/containers/Lists/PtrList/PtrList.C
src/OpenFOAM/containers/Lists/PtrList/PtrListI.H
src/OpenFOAM/containers/Lists/PtrList/PtrListIO.C