OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UList< T >::greater Class Reference
Greater function class that can be used for sorting.
Public Member Functions
greater (const UList< T > &values)
bool operator() (const label a, const label b)
Detailed Description
template<class T>
class Foam::UList< T >::greater
Greater function class that can be used for sorting.
Definition at line 116 of file UList.H.
Constructor & Destructor Documentation
greater()
greater (const UList< T > & values) inline
Definition at line 122 of file UList.H.
Member Function Documentation
operator()()
bool operator() (const label a, const label b) inline
Definition at line 127 of file UList.H.
References UList< T >::assign(), Foam::constant::physicoChemical::b, UList< T >::byteSize(), UList< T >::cdata(), UList< T >::checkIndex(), UList< T >::checkSize(), UList< T >::checkStart(), UList< T >::data(), UList< T >::fcIndex(), UList< T >::first(), UList< T >::last(), UList< T >::operator=(), UList< T >::operator[](), UList< T >::rcIndex(), UList< T >::size(), Foam::T(), UList< T >::UList(), and UList< T >::writeEntry().
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/Lists/UList/UList.H