OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PackedList< nBits >::iteratorBase Class Reference
The iterator base for PackedList.
Public Member Functions
label key () const
Return the element index corresponding to the iterator.
bool writeIfSet (Ostream &) const
Write index/value for a non-zero entry.
bool operator== (const iteratorBase &) const
Compare values (not positions)
bool operator!= (const iteratorBase &) const
unsigned int operator= (const iteratorBase &)
Assign value, not position.
unsigned int operator= (const unsigned int val)
Assign value.
operator unsigned int () const
Conversion operator.
Ostream & printInfo (Ostream &) const
Print information and values.
template<>
bool writeIfSet (Ostream &os) const
Protected Member Functions
unsigned int get () const
Get value as unsigned, no range-checking.
bool set (unsigned int)
Set value, returning true if changed, no range-checking.
iteratorBase ()
Construct null.
iteratorBase (const PackedList *, const label)
Construct from base list and position index.
Protected Attributes
PackedList * list_
Pointer to original list.
label index_
Element index.
Friends
class PackedList
Detailed Description
template<unsigned nBits = 1>
class Foam::PackedList< nBits >::iteratorBase
The iterator base for PackedList.
Note: data and functions are protected, to allow reuse by iterator and prevent most external usage.
Definition at line 417 of file PackedList.H.
Constructor & Destructor Documentation
iteratorBase() [1/2]
iteratorBase () inline protected
Construct null.
Definition at line 280 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_, and PackedList< nBits >::iteratorBase::list_.
Referenced by PackedList< 2 >::append(), PackedList< nBits >::const_iterator::const_iterator(), PackedList< 2 >::get(), PackedList< 2 >::operator[](), PackedList< 2 >::remove(), PackedList< 2 >::set(), and PackedList< 2 >::unset().
iteratorBase() [2/2]
iteratorBase (const PackedList * , const label) inline protected
Construct from base list and position index.
Member Function Documentation
get()
unsigned int get () const inline protected
Get value as unsigned, no range-checking.
Definition at line 301 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_, PackedList< nBits >::iteratorBase::list_, PackedList< nBits >::max_value(), and PackedList< nBits >::packing().
Referenced by PackedList< nBits >::iteratorBase::operator=().
set()
bool set (unsigned int val) inline protected
Set value, returning true if changed, no range-checking.
Definition at line 313 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_, PackedList< nBits >::iteratorBase::list_, PackedList< nBits >::max_value(), and PackedList< nBits >::packing().
key()
Foam::label key () const inline
Return the element index corresponding to the iterator.
Definition at line 340 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
writeIfSet() [1/2]
bool writeIfSet (Ostream & os) const inline
Write index/value for a non-zero entry.
The bool specialization writes the index only
Definition at line 155 of file PackedListI.H.
References token::BEGIN_LIST, token::END_LIST, and token::SPACE.
operator==()
bool operator== (const iteratorBase & iter) const inline
Compare values (not positions)
Definition at line 348 of file PackedListI.H.
References PackedList< nBits >::get().
operator!=()
bool operator!= (const iteratorBase & iter) const inline
Definition at line 358 of file PackedListI.H.
References PackedList< nBits >::get().
operator=() [1/2]
unsigned int operator= (const iteratorBase & iter) inline
Assign value, not position.
This allows packed[0] = packed[3] for assigning values
Definition at line 368 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::get().
operator=() [2/2]
unsigned int operator= (const unsigned int val) inline
Assign value.
A non-existent entry will be auto-vivified.
Definition at line 378 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_, PackedList< nBits >::iteratorBase::list_, and PackedList< nBits >::resize().
operator unsigned int()
operator unsigned int () const inline
Conversion operator.
Never auto-vivify entries.
Definition at line 393 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_, and PackedList< nBits >::iteratorBase::list_.
printInfo()
Foam::Ostream & printInfo (Ostream & os) const
Print information and values.
Definition at line 149 of file PackedList.C.
References Foam::nl, and PackedList< nBits >::printBits().
Referenced by PackedList< 2 >::values().
writeIfSet() [2/2]
bool writeIfSet (Ostream & os) const inline
Definition at line 87 of file PackedListI.H.
Friends And Related Function Documentation
PackedList
friend class PackedList friend
Definition at line 419 of file PackedList.H.
Member Data Documentation
list_
PackedList* list_ protected
Pointer to original list.
This also lets us use the default bitwise copy/assignment
Definition at line 427 of file PackedList.H.
Referenced by PackedList< nBits >::const_iterator::const_iterator(), PackedList< nBits >::iteratorBase::get(), PackedList< nBits >::iterator::iterator(), PackedList< nBits >::iteratorBase::iteratorBase(), PackedList< nBits >::iteratorBase::operator unsigned int(), PackedList< nBits >::iteratorBase::operator=(), PackedList< nBits >::iterator::operator=(), PackedList< nBits >::const_iterator::operator=(), and PackedList< nBits >::iteratorBase::set().
index_
label index_ protected
Element index.
Definition at line 430 of file PackedList.H.
Referenced by PackedList< nBits >::const_iterator::const_iterator(), PackedList< nBits >::iteratorBase::get(), PackedList< nBits >::iterator::iterator(), PackedList< nBits >::iteratorBase::iteratorBase(), PackedList< nBits >::iteratorBase::key(), PackedList< nBits >::iteratorBase::operator unsigned int(), PackedList< nBits >::iterator::operator!=(), PackedList< nBits >::const_iterator::operator!=(), PackedList< nBits >::iterator::operator++(), PackedList< nBits >::const_iterator::operator++(), PackedList< nBits >::iterator::operator--(), PackedList< nBits >::const_iterator::operator--(), PackedList< nBits >::iteratorBase::operator=(), PackedList< nBits >::iterator::operator=(), PackedList< nBits >::const_iterator::operator=(), PackedList< nBits >::iterator::operator==(), PackedList< nBits >::const_iterator::operator==(), and PackedList< nBits >::iteratorBase::set().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/PackedList/PackedList.H
src/OpenFOAM/containers/Lists/PackedList/PackedList.C
src/OpenFOAM/containers/Lists/PackedList/PackedListI.H