OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IndirectList< T > Class Template Reference
A List with indirect addressing.
Public Member Functions
IndirectList (const UList< T > &, const labelUList &)
Construct given the complete list and the addressing array.
IndirectList (const UList< T > &, const Xfer< List< label > > &)
Construct given the complete list and by transferring addressing.
IndirectList (const IndirectList< T > &)
Copy constructor.
IndirectList (const UIndirectList< T > &)
Construct from UIndirectList.
Public Member Functions inherited from UIndirectList< T >
UIndirectList (const UList< T > &, const labelUList &)
Construct given the complete list and the addressing array.
label size () const
Return the number of elements in the list.
bool empty () const
Return true if the list is empty (ie, size() is zero).
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
const UList< T > & completeList () const
Return the complete list.
const List< label > & addressing () const
Return the list addressing.
List< T > operator() () const
Return the addressed elements as a List.
T & operator[] (const label)
Return non-const access to an element.
const T & operator[] (const label) const
Return const access to an element.
void operator= (const UList< T > &)
Assignment from UList of addressed elements.
void operator= (const UIndirectList< T > &)
Assignment from UIndirectList of addressed elements.
void operator= (const T &)
Assignment of all entries to the given value.
Additional Inherited Members
Public Types inherited from UIndirectList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
Detailed Description
template<class T>
class Foam::IndirectList< T >
A List with indirect addressing.
See also
Foam::UIndirectList for a version without any allocation for the addressing.
Source files
IndirectList.H
IndirectListI.H
Definition at line 102 of file IndirectList.H.
Constructor & Destructor Documentation
IndirectList() [1/4]
IndirectList (const UList< T > & completeList, const labelUList & addr) inline
Construct given the complete list and the addressing array.
Definition at line 49 of file IndirectListI.H.
Referenced by IndirectList< T >::IndirectList(), and IndirectListAddressing::IndirectListAddressing().
IndirectList() [2/4]
IndirectList (const UList< T > & completeList, const Xfer< List< label > > & addr) inline
Construct given the complete list and by transferring addressing.
Definition at line 65 of file IndirectListI.H.
References IndirectList< T >::IndirectList().
IndirectList() [3/4]
IndirectList (const IndirectList< T > & lst) inline
Copy constructor.
Definition at line 81 of file IndirectListI.H.
References IndirectList< T >::IndirectList().
IndirectList() [4/4]
IndirectList (const UIndirectList< T > & lst) inline explicit
Construct from UIndirectList.
Definition at line 96 of file IndirectListI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/IndirectList/IndirectList.H
src/OpenFOAM/containers/Lists/IndirectList/IndirectListI.H