OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UPtrList< T > Class Template Reference
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
Classes
class iterator
An STL iterator.
Public Types
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Member Functions
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T > > &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reUse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero).
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
Friends
class iterator
Ostream & operator (Ostream &, const UPtrList< T > &)
Detailed Description
template<class T>
class Foam::UPtrList< T >
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
The element operator [] returns a reference to the object rather than a pointer. Storage is not allocated during construction or use but is supplied to the constructor as an argument.
Source files
UPtrList.H
UPtrList.C
UPtrListIO.C
Definition at line 52 of file UPtrList.H.
Member Typedef Documentation
value_type
typedef T value_type
Type of values the UPtrList contains.
Definition at line 191 of file UPtrList.H.
reference
typedef T& reference
Type that can be used for storing into UPtrList::value_type objects.
Definition at line 194 of file UPtrList.H.
const_reference
typedef const T& const_reference
Type that can be used for storing into constant UPtrList::value_type.
objects.
Definition at line 198 of file UPtrList.H.
Constructor & Destructor Documentation
UPtrList() [1/4]
UPtrList ()
Null Constructor.
Definition at line 33 of file UPtrList.C.
UPtrList() [2/4]
UPtrList (const label s) explicit
Construct with size specified.
Definition at line 40 of file UPtrList.C.
UPtrList() [3/4]
UPtrList (const Xfer< UPtrList< T > > & lst)
Construct by transferring the parameter contents.
Definition at line 47 of file UPtrList.C.
UPtrList() [4/4]
UPtrList (UPtrList< T > & a, bool reUse)
Construct as copy or re-use as specified.
Definition at line 54 of file UPtrList.C.
Member Function Documentation
size()
Foam::label size () const inline
Return the number of elements in the UPtrList.
Definition at line 31 of file UPtrListI.H.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), GAMGSolver::GAMGSolver(), lduPrimitiveMesh::gather(), GAMGProcAgglomeration::globalCellCells(), lduMatrix::initMatrixInterfaces(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::MULES::limitSum(), lduPrimitiveMesh::nonBlockingSchedule(), lduMesh::thisDb(), and lduMatrix::updateMatrixInterfaces().
empty()
bool empty () const inline
Return true if the UPtrList is empty (ie, size() is zero).
Definition at line 38 of file UPtrListI.H.
first() [1/2]
T & first () inline
Return reference to the first element of the list.
Definition at line 45 of file UPtrListI.H.
first() [2/2]
const T & first () const inline
Return reference to first element of the list.
Definition at line 52 of file UPtrListI.H.
last() [1/2]
T & last () inline
Return reference to the last element of the list.
Definition at line 59 of file UPtrListI.H.
last() [2/2]
const T & last () const inline
Return reference to the last element of the list.
Definition at line 66 of file UPtrListI.H.
setSize()
void setSize (const label newSize)
Reset size of UPtrList. This can only be used to set the size.
of an empty UPtrList, extend a UPtrList, remove entries from the end of a UPtrList.
Definition at line 63 of file UPtrList.C.
resize()
void resize (const label newSize) inline
Reset size of UPtrList. This can only be used to set the size.
of an empty UPtrList, extend a UPtrList, remove entries from the end of a UPtrList.
Definition at line 73 of file UPtrListI.H.
clear()
void clear ()
Clear the UPtrList, i.e. set size to zero.
Definition at line 89 of file UPtrList.C.
transfer()
void transfer (UPtrList< T > & a)
Transfer the contents of the argument UPtrList into this.
UPtrList and annul the argument list.
Definition at line 96 of file UPtrList.C.
xfer()
Foam::Xfer< Foam::UPtrList< T > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 96 of file UPtrListI.H.
set() [1/2]
bool set (const label i) const inline
Is element set.
Definition at line 80 of file UPtrListI.H.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::combineLevels(), GAMGSolver::GAMGSolver(), lduPrimitiveMesh::gather(), GAMGProcAgglomeration::globalCellCells(), lduMatrix::initMatrixInterfaces(), fvBoundaryMesh::interfaces(), lduPrimitiveMesh::lduPrimitiveMesh(), LUscalarMatrix::LUscalarMatrix(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), lduPrimitiveMesh::nonBlockingSchedule(), procLduMatrix::procLduMatrix(), lduMatrix::residual(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::scalarInterfaces(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), lduMatrix::sumA(), lduMesh::thisDb(), and lduMatrix::updateMatrixInterfaces().
set() [2/2]
T * set (const label i, T * ptr) inline
Set element. Return old element (can be NULL).
No checks on new element.
Definition at line 87 of file UPtrListI.H.
reorder()
void reorder (const labelUList & oldToNew)
Reorders elements. Ordering does not have to be done in.
ascending or descending order. Reordering has to be unique. (is shuffle)
Definition at line 103 of file UPtrList.C.
operator[]() [1/2]
const T & operator[] (const label i) const inline
Return element const reference.
Definition at line 105 of file UPtrListI.H.
operator[]() [2/2]
T & operator[] (const label i) inline
Return element reference.
Definition at line 121 of file UPtrListI.H.
operator()()
const T * operator() (const label i) const inline
Return element const pointer.
Definition at line 137 of file UPtrListI.H.
begin()
Foam::UPtrList< T >::iterator begin () inline
Return an iterator to begin traversing the UPtrList.
Definition at line 291 of file UPtrListI.H.
Referenced by LUscalarMatrix::LUscalarMatrix().
end()
Foam::UPtrList< T >::iterator end () inline
Return an iterator to end traversing the UPtrList.
Definition at line 298 of file UPtrListI.H.
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 204 of file UPtrList.H.
operator
Ostream& operator (Ostream & , const UPtrList< T > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/UPtrList/UPtrList.H
src/OpenFOAM/containers/Lists/UPtrList/UPtrList.C
src/OpenFOAM/containers/Lists/UPtrList/UPtrListI.H