OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UPtrList< T >::iterator Class Reference
An STL iterator.
Public Member Functions
iterator (T **)
Construct for a given UPtrList entry.
bool operator== (const iterator &) const
bool operator!= (const iterator &) const
T & operator* ()
T & operator() ()
iterator operator++ ()
iterator operator++ (int)
iterator operator-- ()
iterator operator-- (int)
iterator operator+= (label)
iterator operator-= (label)
T & operator[] (label)
bool operator< (const iterator &) const
bool operator> (const iterator &) const
bool operator<= (const iterator &) const
bool operator>= (const iterator &) const
Friends
iterator operator+ (const iterator &, label)
iterator operator+ (label, const iterator &)
iterator operator- (const iterator &, label)
label operator- (const iterator &, const iterator &)
Detailed Description
template<class T>
class Foam::UPtrList< T >::iterator
An STL iterator.
Definition at line 208 of file UPtrList.H.
Constructor & Destructor Documentation
iterator()
iterator (T ** ptr) inline
Construct for a given UPtrList entry.
Definition at line 146 of file UPtrListI.H.
Member Function Documentation
operator==()
bool operator== (const iterator & iter) const inline
Definition at line 152 of file UPtrListI.H.
operator!=()
bool operator!= (const iterator & iter) const inline
Definition at line 158 of file UPtrListI.H.
operator*()
T & operator* () inline
Definition at line 164 of file UPtrListI.H.
Referenced by UPtrList< T >::iterator::operator()().
operator()()
T & operator() () inline
Definition at line 170 of file UPtrListI.H.
References UPtrList< T >::iterator::operator*().
operator++() [1/2]
Foam::UPtrList< T >::iterator operator++ () inline
Definition at line 177 of file UPtrListI.H.
operator++() [2/2]
Foam::UPtrList< T >::iterator operator++ (int) inline
Definition at line 185 of file UPtrListI.H.
operator--() [1/2]
Foam::UPtrList< T >::iterator operator-- () inline
Definition at line 194 of file UPtrListI.H.
operator--() [2/2]
Foam::UPtrList< T >::iterator operator-- (int) inline
Definition at line 202 of file UPtrListI.H.
operator+=()
Foam::UPtrList< T >::iterator operator+= (label n) inline
Definition at line 211 of file UPtrListI.H.
References n, and Foam::operator+().
operator-=()
Foam::UPtrList< T >::iterator operator-= (label n) inline
Definition at line 235 of file UPtrListI.H.
References n, Foam::operator-(), and Foam::T().
operator[]()
T & operator[] (label n) inline
Definition at line 260 of file UPtrListI.H.
References n.
operator<()
bool operator< (const iterator & iter) const inline
Definition at line 266 of file UPtrListI.H.
operator>()
bool operator> (const iterator & iter) const inline
Definition at line 272 of file UPtrListI.H.
operator<=()
bool operator<= (const iterator & iter) const inline
Definition at line 278 of file UPtrListI.H.
operator>=()
bool operator>= (const iterator & iter) const inline
Definition at line 284 of file UPtrListI.H.
Friends And Related Function Documentation
operator+ [1/2]
iterator operator+ (const iterator & , label) friend
operator+ [2/2]
iterator operator+ (label , const iterator &) friend
operator- [1/2]
iterator operator- (const iterator & , label) friend
operator- [2/2]
label operator- (const iterator & , const iterator &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/UPtrList/UPtrList.H
src/OpenFOAM/containers/Lists/UPtrList/UPtrListI.H