OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PackedList< nBits >::const_iterator Class Reference
The const_iterator for PackedList.
Public Member Functions
const_iterator ()
Construct null.
const_iterator (const iteratorBase &)
Construct from iterator base, eg iter(packedlist[i])
const_iterator (const PackedList *, const label)
Construct from base list and position index.
const_iterator (const iterator &)
Construct from iterator.
bool operator== (const iteratorBase &) const
Compare positions (not values)
bool operator!= (const iteratorBase &) const
const_iterator & operator= (const iteratorBase &)
Assign from iteratorBase or derived.
unsigned int operator* () const
Return referenced value directly.
unsigned int operator() () const
Return referenced value directly.
const_iterator & operator++ ()
const_iterator operator++ (int)
const_iterator & operator-- ()
const_iterator operator-- (int)
Public Member Functions inherited from PackedList< nBits >::iteratorBase
label key () const
Return the element index corresponding to the iterator.
bool writeIfSet (Ostream &) const
Write index/value for a non-zero entry.
bool operator== (const iteratorBase &) const
Compare values (not positions)
bool operator!= (const iteratorBase &) const
unsigned int operator= (const iteratorBase &)
Assign value, not position.
unsigned int operator= (const unsigned int val)
Assign value.
operator unsigned int () const
Conversion operator.
Ostream & printInfo (Ostream &) const
Print information and values.
template<>
bool writeIfSet (Ostream &os) const
Additional Inherited Members
Protected Member Functions inherited from PackedList< nBits >::iteratorBase
unsigned int get () const
Get value as unsigned, no range-checking.
bool set (unsigned int)
Set value, returning true if changed, no range-checking.
iteratorBase ()
Construct null.
iteratorBase (const PackedList *, const label)
Construct from base list and position index.
Protected Attributes inherited from PackedList< nBits >::iteratorBase
PackedList * list_
Pointer to original list.
label index_
Element index.
Detailed Description
template<unsigned nBits = 1>
class Foam::PackedList< nBits >::const_iterator
The const_iterator for PackedList.
Definition at line 554 of file PackedList.H.
Constructor & Destructor Documentation
const_iterator() [1/4]
const_iterator () inline
Construct null.
Definition at line 415 of file PackedListI.H.
References PackedList< nBits >::iterator::iterator().
Referenced by PackedList< 2 >::begin(), PackedList< 2 >::cbegin(), PackedList< 2 >::cend(), PackedList< nBits >::const_iterator::const_iterator(), PackedList< 2 >::end(), and PackedList< nBits >::iterator::iterator().
const_iterator() [2/4]
const_iterator (const iteratorBase & iter) inline
Construct from iterator base, eg iter(packedlist[i])
but also "const_iterator iter = packedlist[i];" An out-of-range iterator is assigned cend()
Definition at line 440 of file PackedListI.H.
References PackedList< nBits >::const_iterator::const_iterator(), PackedList< nBits >::iteratorBase::index_, PackedList< nBits >::iterator::iterator(), PackedList< nBits >::iteratorBase::iteratorBase(), and PackedList< nBits >::iteratorBase::list_.
const_iterator() [3/4]
const_iterator (const PackedList * , const label) inline
Construct from base list and position index.
const_iterator() [4/4]
const_iterator (const iterator & iter) inline
Construct from iterator.
Definition at line 479 of file PackedListI.H.
Member Function Documentation
operator==()
bool operator== (const iteratorBase & iter) const inline
Compare positions (not values)
Definition at line 509 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
operator!=()
bool operator!= (const iteratorBase & iter) const inline
Definition at line 519 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
operator=()
Foam::PackedList< nBits >::const_iterator & operator= (const iteratorBase & iter) inline
Assign from iteratorBase or derived.
eg, iter = packedlist[i] or even iter = list.begin()
Definition at line 547 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_, and PackedList< nBits >::iteratorBase::list_.
operator*()
unsigned int operator* () const inline
Return referenced value directly.
Definition at line 657 of file PackedListI.H.
operator()()
unsigned int operator() () const inline
Return referenced value directly.
Definition at line 665 of file PackedListI.H.
operator++() [1/2]
Foam::PackedList< nBits >::const_iterator & operator++ () inline
Definition at line 574 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
operator++() [2/2]
Foam::PackedList< nBits >::const_iterator operator++ (int) inline
Definition at line 593 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
operator--() [1/2]
Foam::PackedList< nBits >::const_iterator & operator-- () inline
Definition at line 612 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
operator--() [2/2]
Foam::PackedList< nBits >::const_iterator operator-- (int) inline
Definition at line 631 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::index_.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/PackedList/PackedList.H
src/OpenFOAM/containers/Lists/PackedList/PackedListI.H