OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IndirectListAddressing Class Reference
A helper class for storing addresses.
Protected Member Functions
IndirectListAddressing (const labelUList &addr)
Construct by copying the addressing array.
IndirectListAddressing (const Xfer< List< label > > &addr)
Construct by transferring addressing array.
const List< label > & addressing () const
Return the list addressing.
void resetAddressing (const labelUList &)
Reset addressing.
void resetAddressing (const Xfer< List< label > > &)
Detailed Description
A helper class for storing addresses.
Definition at line 53 of file IndirectList.H.
Constructor & Destructor Documentation
IndirectListAddressing() [1/2]
IndirectListAddressing (const labelUList & addr) inline explicit protected
Construct by copying the addressing array.
Definition at line 30 of file IndirectListI.H.
IndirectListAddressing() [2/2]
IndirectListAddressing (const Xfer< List< label > > & addr) inline explicit protected
Construct by transferring addressing array.
Definition at line 39 of file IndirectListI.H.
References IndirectList< T >::IndirectList().
Member Function Documentation
addressing()
const Foam::List< Foam::label > & addressing () const inline protected
Return the list addressing.
Definition at line 112 of file IndirectListI.H.
References IndirectListAddressing::resetAddressing().
resetAddressing() [1/2]
void resetAddressing (const labelUList & addr) inline protected
Reset addressing.
Definition at line 119 of file IndirectListI.H.
Referenced by IndirectListAddressing::addressing().
resetAddressing() [2/2]
void resetAddressing (const Xfer< List< label > > & addr) inline protected
Definition at line 128 of file IndirectListI.H.
References List< T >::transfer().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/IndirectList/IndirectList.H
src/OpenFOAM/containers/Lists/IndirectList/IndirectListI.H