OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dictionary Class Reference
A list of keyword definitions, which are a keyword followed by any number of values (e.g. words and numbers). The keywords can represent patterns which are matched using Posix regular expressions. The general order for searching is as follows:
Public Member Functions
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Static Public Member Functions
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes
static const dictionary null
Null dictionary.
Friends
class entry
Declare friendship with the entry class for IO.
Istream & operator>> (Istream &, dictionary &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const dictionary &)
Write dictionary to Ostream.
Additional Inherited Members
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase ::iterator LListBase_iterator
typedef DLListBase ::const_iterator LListBase_const_iterator
typedef DLListBase ::const_reverse_iterator LListBase_const_reverse_iterator
Detailed Description
A list of keyword definitions, which are a keyword followed by any number of values (e.g. words and numbers). The keywords can represent patterns which are matched using Posix regular expressions. The general order for searching is as follows:
- exact match
pattern match (in reverse order)
optional recursion into the enclosing (parent) dictionaries
The dictionary class is the base class for IOdictionary. It also serves as a bootstrap dictionary for the objectRegistry data dictionaries since, unlike the IOdictionary class, it does not use an objectRegistry itself to work.
To add - a merge() member function with a non-const dictionary parameter? This would avoid unnecessary cloning in the add(entry*, bool) method.
Source files
dictionary.H
dictionary.C
dictionaryIO.C
Definition at line 137 of file dictionary.H.
Constructor & Destructor Documentation
dictionary() [1/10]
dictionary ()
Construct top-level dictionary null.
Definition at line 113 of file dictionary.C.
Referenced by dictionary::clone(), data::data(), dictionary::dictionary(), dictionary::New(), and dictionary::subOrEmptyDict().
dictionary() [2/10]
dictionary (const fileName & name)
Construct top-level empty dictionary with given name.
Definition at line 119 of file dictionary.C.
References dictionary::dictionary().
dictionary() [3/10]
dictionary (const fileName & name, const dictionary & parentDict, Istream & is)
Construct given the entry name, parent dictionary and Istream,.
reading entries until lastEntry or EOF
Definition at line 34 of file dictionaryIO.C.
dictionary() [4/10]
dictionary (Istream & is)
Construct top-level dictionary from Istream,.
reading entries until EOF
Definition at line 47 of file dictionaryIO.C.
References inputModeEntry::clear(), and dictionary::read().
dictionary() [5/10]
dictionary (Istream & is, const bool keepHeader)
Construct top-level dictionary from Istream,.
reading entries until EOF, optionally keeping the header
Definition at line 59 of file dictionaryIO.C.
References inputModeEntry::clear(), and dictionary::read().
dictionary() [6/10]
dictionary (const dictionary & parentDict, const dictionary & dict)
Construct as copy given the parent dictionary.
Definition at line 127 of file dictionary.C.
References dictionary::dictionary(), and forAllIter.
dictionary() [7/10]
dictionary (const dictionary & dict)
Construct top-level dictionary as copy.
Definition at line 153 of file dictionary.C.
References dictionary::dictionary(), and forAllIter.
dictionary() [8/10]
dictionary (const dictionary * dictPtr)
Construct top-level dictionary as copy from pointer to dictionary.
A null pointer is treated like an empty dictionary.
Definition at line 178 of file dictionary.C.
References dictionary::dictionary(), and dictionary::operator=().
dictionary() [9/10]
dictionary (const dictionary & parentDict, const Xfer< dictionary > & dict)
Construct by transferring parameter contents given parent dictionary.
Definition at line 192 of file dictionary.C.
References dict, dictionary::dictionary(), dictionaryName::name(), and dictionary::transfer().
dictionary() [10/10]
dictionary (const Xfer< dictionary > & dict)
Construct top-level dictionary by transferring parameter contents.
Definition at line 205 of file dictionary.C.
References dict, and dictionary::transfer().
~dictionary()
~dictionary () virtual
Destructor.
Definition at line 223 of file dictionary.C.
Member Function Documentation
ClassName()
ClassName ("dictionary")
clone()
Foam::autoPtr< Foam::dictionary > clone () const
Construct and return clone.
Definition at line 215 of file dictionary.C.
References dictionary::dictionary().
Referenced by dictionary::merge(), dictionary::operator+=(), dictionary::operator=(), dictionary::operator|=(), Foam::preservePatchTypes(), and refinementSurfaces::refinementSurfaces().
New()
Foam::autoPtr< Foam::dictionary > New (Istream & is) static
Construct top-level dictionary on freestore from Istream.
Definition at line 73 of file dictionaryIO.C.
References dictionary::dictionary().
parent()
const dictionary& parent () const inline
Return the parent dictionary.
Definition at line 251 of file dictionary.H.
References Foam::add(), clear(), found, Foam::operator+(), Foam::operator<<(), Foam::operator>>(), Foam::operator|(), Foam::T(), and write().
Referenced by localAxesRotation::localAxesRotation(), dictionary::topDict(), and dictionary::write().
topDict()
const Foam::dictionary & topDict () const
Return the top of the tree.
Definition at line 231 of file dictionary.C.
References dictionaryName::name(), p, dictionary::parent(), and dictionary::topDict().
Referenced by dictionary::topDict().
startLineNumber()
Foam::label startLineNumber () const
Return line number of first token in dictionary.
Definition at line 246 of file dictionary.C.
References UILList< DLListBase, entry >::first(), DLListBase::size(), and entry::startLineNumber().
Referenced by codedBase::updateLibrary().
endLineNumber()
Foam::label endLineNumber () const
Return line number of last token in dictionary.
Definition at line 259 of file dictionary.C.
References entry::endLineNumber(), UILList< DLListBase, entry >::last(), and DLListBase::size().
digest()
Foam::SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
Definition at line 272 of file dictionary.C.
References OSHA1stream::digest(), and forAllConstIter().
Referenced by writeDictionary::execute(), functionObjectList::read(), and writeDictionary::tryDirectory().
tokens()
Foam::tokenList tokens () const
Return the dictionary as a list of tokens.
Definition at line 286 of file dictionary.C.
References dictionary::found(), OStringStream::str(), and dictionary::write().
found()
bool found (const word & keyword, bool recursive = false, bool patternMatch = true) const
Search dictionary for given keyword.
If recursive, search parent dictionaries If patternMatch, use regular expressions
Definition at line 306 of file dictionary.C.
References dictionary::found(), and dictionary::lookupEntryPtr().
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), advectiveFvPatchField< Type >::advectiveFvPatchField(), alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), chemkinReader::chemkinReader(), forces::createFileNames(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), cyclicAMIFvPatchField< Type >::cyclicAMIFvPatchField(), fvSchemes::d2dt2Scheme(), fvSchemes::ddtScheme(), Foam::dimensionedConstant(), fvSchemes::divScheme(), energyJumpAMIFvPatchScalarField::energyJumpAMIFvPatchScalarField(), energyJumpFvPatchScalarField::energyJumpFvPatchScalarField(), ensightSurfaceWriter::ensightSurfaceWriter(), externalCoupledMixedFvPatchField< scalar >::externalCoupledMixedFvPatchField(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), fanFvPatchField< Type >::fanFvPatchField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), fixedJumpAMIFvPatchField< scalar >::fixedJumpAMIFvPatchField(), fixedJumpFvPatchField< scalar >::fixedJumpFvPatchField(), flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), fvSchemes::fluxRequired(), dictionary::found(), fvPatchField< Type >::fvPatchField(), fvsPatchField< Type >::fvsPatchField(), subModelBase::getModelProperty(), fvSchemes::gradScheme(), greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), faceSource::initialise(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), fvSchemes::interpolationScheme(), fvSchemes::laplacianScheme(), layerParameters::layerParameters(), localAxesRotation::localAxesRotation(), mappedPatchBase::mappedPatchBase(), MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), nastranSurfaceWriter::nastranSurfaceWriter(), sootModel::New(), pointPatchField< vector >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), oldCyclicPolyPatch::oldCyclicPolyPatch(), dlLibraryTable::open(), axesRotation::operator=(), dictionary::operator|=(), optionList::optionsDict(), oscillatingDisplacementPointPatchVectorField::oscillatingDisplacementPointPatchVectorField(), oscillatingFixedValueFvPatchField< Type >::oscillatingFixedValueFvPatchField(), oscillatingVelocityPointPatchVectorField::oscillatingVelocityPointPatchVectorField(), outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), Foam::preservePatchTypes(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), prghPressureFvPatchScalarField::prghPressureFvPatchScalarField(), radiationCoupledBase::radiationCoupledBase(), tolerances::read(), outputFilterOutputControl::read(), abortCalculation::read(), sampledSurfaces::read(), sampledSets::read(), streamLine::read(), regionSizeDistribution::read(), wallBoundedStreamLine::read(), forces::read(), fieldAverage::readAveragingProperties(), LduMatrix< Type, DType, LUType >::solver::readControl(), Time::readDict(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), refinementSurfaces::refinementSurfaces(), tolerances::relax(), rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField(), sampledPatchInternalField::sampledPatchInternalField(), sampledPlane::sampledPlane(), sampledThresholdCellFaces::sampledThresholdCellFaces(), fvSchemes::schemesDict(), searchableSurfaces::searchableSurfaces(), subModelBase::setModelProperty(), Foam::setRefCell(), shellSurfaces::shellSurfaces(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), sixDoFRigidBodyMotion::sixDoFRigidBodyMotion(), SLGThermo::SLGThermo(), fvSchemes::snGradScheme(), solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), thirdBodyEfficiencies::thirdBodyEfficiencies(), timeVaryingMappedFixedValueFvPatchField< Type >::timeVaryingMappedFixedValueFvPatchField(), timeVaryingMappedFixedValuePointPatchField< Type >::timeVaryingMappedFixedValuePointPatchField(), dictionary::tokens(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::totalFlowRateAdvectiveDiffusiveFvPatchScalarField(), totalPressureFvPatchScalarField::totalPressureFvPatchScalarField(), totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField(), turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField(), turbulentInletFvPatchField< Type >::turbulentInletFvPatchField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField(), uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField(), uniformFixedGradientFvPatchField< Type >::uniformFixedGradientFvPatchField(), uniformFixedValueFvPatchField< Type >::uniformFixedValueFvPatchField(), uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField(), uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField(), uniformJumpAMIFvPatchField< Type >::uniformJumpAMIFvPatchField(), uniformJumpFvPatchField< Type >::uniformJumpFvPatchField(), uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField(), Foam::unitSet(), valuePointPatchField< vector >::valuePointPatchField(), variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField(), wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField(), waveDisplacementPointPatchVectorField::waveDisplacementPointPatchVectorField(), wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField(), JobInfo::write(), and residuals::writeResidual().
lookupEntryPtr() [1/2]
const Foam::entry * lookupEntryPtr (const word & keyword, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
otherwise return NULL. If recursive, search parent dictionaries. If patternMatch, use regular expressions
Definition at line 345 of file dictionary.C.
References dictionary::lookupEntryPtr().
Referenced by coordinateSystem::coordinateSystem(), dynamicCodeContext::dynamicCodeContext(), dictionary::found(), dictionary::isDict(), dictionary::lookupEntry(), dictionary::lookupEntryPtr(), dictionary::lookupScopedEntryPtr(), entry::New(), functionObjectList::read(), codedFunctionObject::read(), refinementSurfaces::refinementSurfaces(), dictionary::set(), shellSurfaces::shellSurfaces(), dictionary::subDict(), dictionary::subDictPtr(), dictionary::subOrEmptyDict(), dictionary::substituteKeyword(), Foam::debug::switchSet(), and solution::upgradeSolverDict().
lookupEntryPtr() [2/2]
Foam::entry * lookupEntryPtr (const word & keyword, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
if present otherwise return NULL. If recursive, search parent dictionaries. If patternMatch, use regular expressions.
Definition at line 384 of file dictionary.C.
References dictionary::lookupEntry(), and dictionary::lookupEntryPtr().
lookupEntry()
const Foam::entry & lookupEntry (const word & keyword, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
If recursive, search parent dictionaries. If patternMatch, use regular expressions.
Definition at line 428 of file dictionary.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), dictionary::lookupEntryPtr(), and dictionaryName::name().
Referenced by dynamicCodeContext::dynamicCodeContext(), lduMatrix::smoother::getName(), lduMatrix::preconditioner::getName(), dictionary::lookup(), dictionary::lookupEntryPtr(), lduMatrix::smoother::New(), and lduMatrix::preconditioner::New().
lookup()
Foam::ITstream & lookup (const word & keyword, bool recursive = false, bool patternMatch = true) const
Find and return an entry data stream.
If recursive, search parent dictionaries. If patternMatch, use regular expressions.
Definition at line 452 of file dictionary.C.
References dictionary::lookupEntry(), dictionary::lookupScopedEntryPtr(), and entry::stream().
Referenced by activePressureForceBaffleVelocityFvPatchVectorField::activePressureForceBaffleVelocityFvPatchVectorField(), advectiveFvPatchField< Type >::advectiveFvPatchField(), bladeModel::bladeModel(), cellModel::cellModel(), motionSmootherAlgo::checkMesh(), chemkinReader::chemkinReader(), coalCloudList::coalCloudList(), CompatibilityConstant< Type >::CompatibilityConstant(), Constant< Type >::Constant(), molecule::constantProperties::constantProperties(), Foam::MULES::correct(), correlationFunction< Type >::correlationFunction(), constantFilmThermo::Cp(), forces::createFileNames(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), cyclicPolyPatch::cyclicPolyPatch(), constantFilmThermo::D(), fvSchemes::d2dt2Scheme(), fvSchemes::ddtScheme(), forces::devRhoReff(), Foam::dimensionedConstant(), directions::directions(), argList::displayDoc(), fvSchemes::divScheme(), ensightSurfaceWriter::ensightSurfaceWriter(), EulerCoordinateRotation::EulerCoordinateRotation(), Peclet::execute(), exponentialSolidTransport< Thermo >::exponentialSolidTransport(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), extrudePatchMesh::extrudePatchMesh(), fanFvPatchField< Type >::fanFvPatchField(), Field< Foam::Vector2D >::Field(), fieldAverageItem::fieldAverageItem(), forceList::forceList(), FreeStream< CloudType >::FreeStream(), lduMatrix::smoother::getName(), lduMatrix::preconditioner::getName(), fvSchemes::gradScheme(), greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission(), constantFilmThermo::hl(), Foam::MULES::implicitSolve(), coordinateSystem::init(), absorptionCoeffs::initialise(), faceSource::initialise(), liquidFilmThermo::initLiquid(), InjectionModel< CloudType >::InjectionModel(), InjectionModelList< Foam::KinematicCloud< CloudType > >::InjectionModelList(), injectionModelList::injectionModelList(), fvSchemes::interpolationScheme(), constantFilmThermo::kappa(), laminarFlameSpeed::laminarFlameSpeed(), LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate(), fvSchemes::laplacianScheme(), layerParameters::layerParameters(), liquidFilmThermo::liquidFilmThermo(), localAxesRotation::localAxesRotation(), dictionary::lookupEntry(), lookupProfile::lookupProfile(), basicThermo::lookupThermo(), mappedPatchBase::mappedPatchBase(), mappedPatchFieldBase< Type >::mappedPatchFieldBase(), MGridGenGAMGAgglomeration::MGridGenGAMGAgglomeration(), medialAxisMeshMover::move(), constantFilmThermo::mu(), forces::mu(), multiDirRefinement::multiDirRefinement(), NamedEnum< directionType, 3 >::names(), nastranSurfaceWriter::nastranSurfaceWriter(), basicChemistryModel::New(), scatterModel::New(), CorrectionLimitingMethod::New(), renumberMethod::New(), thermophysicalFunction::New(), decompositionMethod::New(), tetherPotential::New(), profileModel::New(), absorptionEmissionModel::New(), psiCombustionModel::New(), ParticleStressModel::New(), rhoCombustionModel::New(), motionSolver::New(), sootModel::New(), interpolation< Foam::Vector >::New(), energyScalingFunction::New(), PairModel< Foam::DsmcCloud >::New(), LESfilter::New(), WallModel< Foam::DsmcCloud >::New(), TimeScaleModel::New(), trimModel::New(), extrudeModel::New(), WallInteractionModel< Foam::DsmcCloud< DsmcParcel< ParcelType > > >::New(), DispersionModel< Foam::KinematicCloud< CloudType > >::New(), BinaryCollisionModel< Foam::DsmcCloud< DsmcParcel< ParcelType > > >::New(), InflowBoundaryModel< Foam::DsmcCloud< DsmcParcel< ParcelType > > >::New(), engineMesh::New(), LESdelta::New(), filmThermoModel::New(), filmRadiationModel::New(), heatTransferModel::New(), AtomizationModel< Foam::SprayCloud< Foam::DsmcCloud > >::New(), barotropicCompressibilityModel::New(), filmTurbulenceModel::New(), IsotropyModel< Foam::MPPICCloud< CloudType > >::New(), sixDoFRigidBodyMotionRestraint::New(), CollisionModel< Foam::CollidingCloud< CloudType > >::New(), StochasticCollisionModel< Foam::KinematicCloud< CloudType > >::New(), DampingModel< Foam::MPPICCloud< CloudType > >::New(), HeatTransferModel< Foam::ThermoCloud< CloudType > >::New(), dynamicFvMesh::New(), filmViscosityModel::New(), DevolatilisationModel< Foam::ReactingMultiphaseCloud< Foam::DsmcCloud > >::New(), solidBodyMotionFunction::New(), laminarFlameSpeed::New(), pairPotential::New(), coordinateRotation::New(), SurfaceReactionModel< Foam::ReactingMultiphaseCloud< Foam::DsmcCloud > >::New(), PackingModel< Foam::MPPICCloud< CloudType > >::New(), phaseChangeModel::New(), AveragingMethod< Foam::Vector >::New(), DataEntry< Foam::Vector >::New(), sixDoFRigidBodyMotionConstraint::New(), BreakupModel< Foam::SprayCloud< Foam::DsmcCloud > >::New(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::New(), regionModelFunctionObject::New(), polyMeshModifier::New(), surfaceFilmModel::New(), PatchInteractionModel< Foam::DsmcCloud >::New(), distributionModel::New(), functionObject::New(), fieldValue::New(), reactionRateFlameArea::New(), SRFModel::New(), turbulenceModel::New(), PhaseChangeModel< Foam::ReactingCloud< Foam::DsmcCloud > >::New(), ODESolver::New(), LESModel::New(), LESModel< BasicTurbulenceModel >::New(), solidProperties::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), RASModel::New(), pyrolysisModel::New(), liquidProperties::New(), IntegrationScheme< Type >::New(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::New(), radiationModel::New(), pointZone::New(), cellZone::New(), lduMatrix::solver::New(), porosityModel::New(), LduMatrix< Type, DType, LUType >::solver::New(), coordinateSystem::New(), sampledSurface::New(), faceZone::New(), sampledSet::New(), pointPatchField< vector >::New(), InjectionModel< CloudType >::New(), fvsPatchField< Type >::New(), option::New(), fvPatchField< Type >::New(), polyPatch::New(), Reaction< ReactionThermo >::New(), LduMatrix< Type, DType, LUType >::smoother::New(), lduMatrix::smoother::New(), LduMatrix< Type, DType, LUType >::preconditioner::New(), lduMatrix::preconditioner::New(), oldCyclicPolyPatch::oldCyclicPolyPatch(), dlLibraryTable::open(), multivariateIndependentScheme< Type >::operator()(), axesRotation::operator=(), Foam::operator>>(), dictionary::operator[](), argList::parse(), phaseProperties::phaseProperties(), plane::plane(), polynomial::polynomial(), porosityModel::porosityModel(), pressureGradientExplicitSource::pressureGradientExplicitSource(), UPstream::procNo(), constantFilmThermo::pv(), Reaction< ReactionThermo >::Reaction(), exponentialRepulsion::read(), lennardJones::read(), harmonicSpring::read(), tolerances::read(), pitchForkRing::read(), restrainedHarmonicSpring::read(), cubeRootVolDelta::read(), dampedCoulomb::read(), anisotropicFilter::read(), maxDeltaxyz::read(), laplaceFilter::read(), IDDESDelta::read(), solutionControl::read(), sigmoid::read(), doubleSigmoid::read(), relaxation::read(), thermalBaffle::read(), azizChen::read(), CrossPowerLaw::read(), HerschelBulkley::read(), powerLaw::read(), maitlandSmith::read(), outputFilterOutputControl::read(), BirdCarreau::read(), consumptionSpeed::read(), writeDictionary::read(), cloudSolution::read(), blendingFactor::read(), calcMag::read(), abortCalculation::read(), calcFvcDiv::read(), calcFvcGrad::read(), timeActivatedFileUpdate::read(), patchProbes::read(), residuals::read(), removeRegisteredObject::read(), inhomogeneousMixture< ThermoType >::read(), reactionRateFlameArea::read(), scalarTransport::read(), dimensioned< vector >::read(), egrMixture< ThermoType >::read(), cloudInfo::read(), writeRegisteredObject::read(), surfaceInterpolateFields::read(), fieldValue::read(), readFields::read(), fieldCoordinateSystemTransform::read(), codedFunctionObject::read(), partialWrite::read(), radiationModel::read(), fieldValueDelta::read(), fieldMinMax::read(), kinematicSingleLayer::read(), sampledSurfaces::read(), nearWallFields::read(), forceCoeffs::read(), turbulenceFields::read(), RASModel::read(), smoothDelta::read(), probes::read(), porosityModel::read(), sampledSets::read(), rotorDiskSource::read(), streamLine::read(), fieldAverage::read(), regionSizeDistribution::read(), wallBoundedStreamLine::read(), solidificationMeltingSource::read(), pressureTools::read(), sixDoFRigidBodyMotion::read(), forces::read(), option::read(), LduMatrix< Type, DType, LUType >::solver::readControl(), dynamicRefineFvMesh::readDict(), Time::readDict(), DimensionedField< Type, Foam::pointMesh >::readField(), IOobject::readHeader(), mappedPatchBase::readListOrField(), ensightPart::reconstruct(), refinementParameters::refinementParameters(), refinementSurfaces::refinementSurfaces(), tolerances::relaxationFactor(), boundaryRegion::rename(), constantFilmThermo::rho(), thermalBaffleFvPatchScalarField::rmap(), sampledCuttingPlane::sampledCuttingPlane(), sampledIsoSurface::sampledIsoSurface(), sampledPatchInternalField::sampledPatchInternalField(), motionSmootherAlgo::scaleMesh(), fvSchemes::schemesDict(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), seriesProfile::seriesProfile(), ExplicitSetValue< Type >::setFieldData(), SemiImplicitSource< Type >::setFieldData(), Foam::setRefCell(), reducedUnits::setRefValues(), option::setSelection(), shellSurfaces::shellSurfaces(), constantFilmThermo::sigma(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), slidingInterface::slidingInterface(), fvSchemes::snGradScheme(), solidReaction< ReactionThermo >::solidReaction(), tolerances::solverRelativeTolerance(), tolerances::solverTolerance(), STARCDCoordinateRotation::STARCDCoordinateRotation(), dictionaryEntry::stream(), surfaceFeatures::surfaceFeatures(), surfacePatchIOList::surfacePatchIOList(), surfaceZonesInfo::surfaceZonesInfo(), surfZoneIOList::surfZoneIOList(), Table< Type >::Table(), TableFile< Type >::TableFile(), constantFilmThermo::Tb(), thermoSingleLayer::thermoSingleLayer(), thirdBodyEfficiencies::thirdBodyEfficiencies(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), UniformDimensionedField< scalar >::UniformDimensionedField(), uniformInterpolationTable< scalar >::uniformInterpolationTable(), Foam::unitSet(), dynamicRefineFvMesh::update(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), constantFilmThermo::W(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), thermalBaffleFvPatchScalarField::write(), residuals::writeResidual(), and medialAxisMeshMover::~medialAxisMeshMover().
lookupOrDefault()
T lookupOrDefault (const word & keyword, const T & deflt, bool recursive = false, bool patternMatch = true) const
Find and return a T,.
if not found return the given default value If recursive, search parent dictionaries. If patternMatch, use regular expressions.
Definition at line 33 of file dictionaryTemplates.C.
References Foam::endl(), IOInfoIn, dictionary::lookupOrAddDefault(), entry::stream(), and T.
Referenced by subModelBase::defaultCoeffs(), EulerCoordinateRotation::EulerCoordinateRotation(), fieldAverageItem::fieldAverageItem(), flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), freestreamFvPatchField< Type >::freestreamFvPatchField(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), Foam::MULES::limiterCorr(), dimensioned< vector >::lookupOrDefault(), tableReader< scalar >::New(), thermalBaffleModel::New(), GAMGAgglomeration::New(), Foam::operator>>(), argList::parse(), pimpleControl::read(), solutionControl::read(), vorticity::read(), Lambda2::read(), outputFilterOutputControl::read(), Peclet::read(), Q::read(), CourantNo::read(), DESModelRegions::read(), yPlusRAS::read(), blendingFactor::read(), setTimeStepFunctionObject::read(), yPlusLES::read(), scalarTransport::read(), targetCoeffTrim::read(), fieldValue::read(), wallShearStress::read(), fieldValueDelta::read(), fieldMinMax::read(), MRFZone::read(), streamLine::read(), wallBoundedStreamLine::read(), sixDoFRigidBodyMotion::read(), forces::read(), refinementSurfaces::refinementSurfaces(), slidingInterface::setTolerances(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), fvMatrix< Type >::solve(), SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField(), STARCDCoordinateRotation::STARCDCoordinateRotation(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField(), turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField(), Foam::unitSet(), dynamicRefineFvMesh::update(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), and medialAxisMeshMover::~medialAxisMeshMover().
lookupOrAddDefault()
T lookupOrAddDefault (const word & keyword, const T & deflt, bool recursive = false, bool patternMatch = true)
Find and return a T, if not found return the given.
default value, and add to dictionary. If recursive, search parent dictionaries. If patternMatch, use regular expressions.
Definition at line 63 of file dictionaryTemplates.C.
References Foam::add(), Foam::endl(), IOInfoIn, dictionary::readIfPresent(), and entry::stream().
Referenced by Foam::debug::debugSwitch(), Foam::debug::infoSwitch(), dimensioned< vector >::lookupOrAddToDict(), Switch::lookupOrAddToDict(), dictionary::lookupOrDefault(), and Foam::debug::optimisationSwitch().
readIfPresent()
bool readIfPresent (const word & keyword, T & val, bool recursive = false, bool patternMatch = true) const
Find an entry if present, and assign to T.
Returns true if the entry was found. If recursive, search parent dictionaries. If patternMatch, use regular expressions.
Definition at line 94 of file dictionaryTemplates.C.
References Foam::endl(), IOInfoIn, and entry::stream().
Referenced by advectiveFvPatchField< Type >::advectiveFvPatchField(), motionSmootherAlgo::checkMesh(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), engineTime::engineTime(), fvMotionSolverEngineMesh::fvMotionSolverEngineMesh(), subModelBase::getBaseProperty(), subModelBase::getModelProperty(), IDDESDelta::IDDESDelta(), kinematicSingleLayer::info(), coordinateSystem::init(), cellSource::initialise(), faceSource::initialise(), layeredEngineMesh::layeredEngineMesh(), layerParameters::layerParameters(), linearNormal::linearNormal(), dictionary::lookupOrAddDefault(), chemistryReader< gasHThermoPhysics >::New(), polyPatch::New(), oldCyclicPolyPatch::oldCyclicPolyPatch(), axesRotation::operator=(), patchIdentifier::patchIdentifier(), Foam::preservePatchTypes(), profileModel::profileModel(), PrandtlDelta::read(), vanDriestDelta::read(), cloudSolution::read(), abortCalculation::read(), setTimeStepFunctionObject::read(), scalarTransport::read(), writeRegisteredObject::read(), fvDOM::read(), systemCall::read(), kinematicSingleLayer::read(), probes::read(), streamLine::read(), fieldAverage::read(), regionSizeDistribution::read(), solidificationMeltingSource::read(), pressureTools::read(), forces::read(), option::read(), Time::readDict(), IOobject::readHeader(), dimensioned< vector >::readIfPresent(), Switch::readIfPresent(), ensightPart::reconstruct(), refinementSurfaces::refinementSurfaces(), sampledPlane::sampledPlane(), sampledSurface::sampledSurface(), searchableSurfaces::searchableSurfaces(), Time::setControls(), data::setSolverPerformance(), Time::setTime(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), fvMatrix< Type >::solve(), surfaceZonesInfo::surfaceZonesInfo(), surfZoneIdentifier::surfZoneIdentifier(), surfZoneIOList::surfZoneIOList(), thermoSingleLayer::thermoSingleLayer(), timeVaryingMappedFixedValueFvPatchField< Type >::timeVaryingMappedFixedValueFvPatchField(), timeVaryingMappedFixedValuePointPatchField< Type >::timeVaryingMappedFixedValuePointPatchField(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), triSurfaceMesh::triSurfaceMesh(), triSurfaceSearch::triSurfaceSearch(), and uniformInterpolationTable< scalar >::uniformInterpolationTable().
lookupScopedEntryPtr()
const Foam::entry * lookupScopedEntryPtr (const word & keyword, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
otherwise return NULL. Allows scoping using '.'
Definition at line 463 of file dictionary.C.
References entry::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, entry::isDict(), dictionary::keys(), dictionary::lookupEntryPtr(), dictionary::lookupScopedEntryPtr(), and dictionaryName::name().
Referenced by Foam::stringOps::getVariable(), Foam::stringOps::inplaceExpand(), dictionary::lookup(), dictionary::lookupScopedEntryPtr(), entry::New(), and dictionary::substituteScopedKeyword().
isDict()
bool isDict (const word & keyword) const
Check if entry is a sub-dictionary.
Definition at line 607 of file dictionary.C.
References entry::isDict(), and dictionary::lookupEntryPtr().
Referenced by basicThermo::lookupThermo(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), basicChemistryModel::New(), searchableSurfaceCollection::searchableSurfaceCollection(), and searchableSurfaces::searchableSurfaces().
subDictPtr()
const Foam::dictionary * subDictPtr (const word & keyword) const
Find and return a sub-dictionary pointer if present.
otherwise return NULL.
Definition at line 623 of file dictionary.C.
References entry::dict(), and dictionary::lookupEntryPtr().
Referenced by regionModel::read(), LESModel< BasicTurbulenceModel >::read(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::read(), RASModel::read(), and LESModel::read().
subDict() [1/2]
const Foam::dictionary & subDict (const word & keyword) const
Find and return a sub-dictionary.
Definition at line 638 of file dictionary.C.
References entry::dict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookupEntryPtr(), and dictionaryName::name().
Referenced by sixDoFRigidBodyMotion::addConstraints(), autoLayerDriver::addLayers(), sixDoFRigidBodyMotion::addRestraints(), CloudFunctionObjectList< KinematicCloud< CloudType > >::CloudFunctionObjectList(), forces::createFileNames(), solutionControl::dict(), Foam::dimensionedConstant(), directions::directions(), argList::displayDoc(), fvMeshDistribute::distribute(), exponentialSolidTransport< Thermo >::exponentialSolidTransport(), subModelBase::getBaseProperty(), subModelBase::getModelProperty(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission(), IDDESDelta::IDDESDelta(), coordinateSystem::init(), liquidFilmThermo::initLiquid(), cloudSolution::integrationSchemes(), cloudSolution::interpolationSchemes(), layerParameters::layerParameters(), liquidMixtureProperties::liquidMixtureProperties(), basicThermo::lookupThermo(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< directionType, 3 >::names(), basicChemistryModel::New(), basicSolidChemistryModel::New(), regionModelFunctionObject::New(), solidProperties::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), liquidProperties::New(), coordinateSystem::New(), optionList::optionsDict(), plane::plane(), Foam::preservePatchTypes(), fvMeshDistribute::printFieldInfo(), profileModelList::profileModelList(), pyrolysisModelCollection::pyrolysisModelCollection(), exponentialRepulsion::read(), lennardJones::read(), harmonicSpring::read(), tolerances::read(), pitchForkRing::read(), restrainedHarmonicSpring::read(), cubeRootVolDelta::read(), dampedCoulomb::read(), PrandtlDelta::read(), vanDriestDelta::read(), anisotropicFilter::read(), maxDeltaxyz::read(), laplaceFilter::read(), IDDESDelta::read(), sigmoid::read(), doubleSigmoid::read(), relaxation::read(), pureMixture< ThermoType >::read(), azizChen::read(), trimModel::read(), CrossPowerLaw::read(), maitlandSmith::read(), HerschelBulkley::read(), porosityModelList::read(), powerLaw::read(), BirdCarreau::read(), homogeneousMixture< ThermoType >::read(), cloudSolution::read(), solidBodyMotionFunction::read(), multiComponentMixture< ThermoType >::read(), MRFZoneList::read(), inhomogeneousMixture< ThermoType >::read(), veryInhomogeneousMixture< ThermoType >::read(), motionSolver::read(), scalarTransport::read(), egrMixture< ThermoType >::read(), fieldValueDelta::read(), kinematicSingleLayer::read(), smoothDelta::read(), porosityModel::read(), streamLine::read(), wallBoundedStreamLine::read(), forces::read(), option::read(), fieldAverage::readAveragingProperties(), Time::readDict(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), optionList::readOptions(), refinementSurfaces::refinementSurfaces(), fvSchemes::schemesDict(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), subModelBase::setBaseProperty(), subModelBase::setModelProperty(), SLGThermo::SLGThermo(), solidMixtureProperties::solidMixtureProperties(), displacementLayeredMotionMotionSolver::solve(), data::solverPerformanceDict(), cloudSolution::sourceTermDict(), TableFile< Type >::TableFile(), Foam::unitSet(), dynamicRefineFvMesh::update(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), thermalBaffleFvPatchScalarField::write(), and fieldAverage::writeAveragingProperties().
subDict() [2/2]
Foam::dictionary & subDict (const word & keyword)
Find and return a sub-dictionary for manipulation.
Definition at line 656 of file dictionary.C.
References entry::dict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookupEntryPtr(), dictionaryName::name(), and dictionary::subOrEmptyDict().
subOrEmptyDict()
Foam::dictionary subOrEmptyDict (const word & keyword, const bool mustRead = false) const
Find and return a sub-dictionary as a copy, or.
return an empty dictionary if the sub-dictionary does not exist
Definition at line 675 of file dictionary.C.
References entry::dict(), dictionary::dictionary(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookupEntryPtr(), and dictionaryName::name().
Referenced by faceSource::initialise(), solutionControl::read(), radiationModel::read(), sampledSurfaces::read(), and dictionary::subDict().
toc()
Foam::wordList toc () const
Return the table of contents.
Definition at line 707 of file dictionary.C.
References forAllConstIter(), dictionary::keys(), and DLListBase::size().
Referenced by CloudFunctionObjectList< KinematicCloud< CloudType > >::CloudFunctionObjectList(), removeEntry::execute(), FreeStream< CloudType >::FreeStream(), InjectionModelList< Foam::KinematicCloud< CloudType > >::InjectionModelList(), liquidMixtureProperties::liquidMixtureProperties(), ParticleForceList< KinematicCloud< CloudType > >::ParticleForceList(), profileModelList::profileModelList(), pyrolysisModelCollection::pyrolysisModelCollection(), refinementSurfaces::refinementSurfaces(), regionModelFunctionObjectList::regionModelFunctionObjectList(), ExplicitSetValue< Type >::setFieldData(), SemiImplicitSource< Type >::setFieldData(), shellSurfaces::shellSurfaces(), and solidMixtureProperties::solidMixtureProperties().
keys()
Foam::List< Foam::keyType > keys (bool patterns = false) const
Return the list of available keys or patterns.
Definition at line 721 of file dictionary.C.
References forAllConstIter(), List< T >::setSize(), and DLListBase::size().
Referenced by dictionary::lookupScopedEntryPtr(), and dictionary::toc().
substituteKeyword()
bool substituteKeyword (const word & keyword)
Substitute the given keyword prepended by '$' with the.
corresponding sub-dictionary entries
Definition at line 132 of file dictionaryIO.C.
References dictionary::add(), forAllConstIter(), and dictionary::lookupEntryPtr().
substituteScopedKeyword()
bool substituteScopedKeyword (const word & keyword)
Substitute the given scoped keyword prepended by '$' with the.
corresponding sub-dictionary entries
Definition at line 583 of file dictionary.C.
References dictionary::add(), forAllConstIter(), and dictionary::lookupScopedEntryPtr().
Referenced by entry::New().
add() [1/8]
bool add (entry * entryPtr, bool mergeEntry = false)
Add a new entry.
With the merge option, dictionaries are interwoven and primitive entries are overwritten
Definition at line 739 of file dictionary.C.
References DLListBase::append(), entry::dict(), Foam::endl(), IOWarningIn, entry::isDict(), keyType::isPattern(), entry::keyword(), dictionaryName::name(), entry::name(), UILList< DLListBase, T >::remove(), and DLListBase::replace().
Referenced by error::abort(), IOerror::abort(), dictionary::add(), constAnIsoSolidTransport< Thermo >::constAnIsoSolidTransport(), constIsoSolidTransport< Thermo >::constIsoSolidTransport(), constTransport< Thermo >::constTransport(), coordinateSystem::dict(), Foam::dimensionedConstant(), calcEntry::execute(), error::exit(), IOerror::exit(), exponentialSolidTransport< Thermo >::exponentialSolidTransport(), dictionary::merge(), entry::New(), error::operator()(), dictionary::operator+=(), cellTable::operator=(), dictionary::operator=(), dictionary::operator|=(), argList::parse(), Foam::preservePatchTypes(), IOerror::SafeFatalIOError(), dictionary::set(), subModelBase::setBaseProperty(), subModelBase::setModelProperty(), sixDoFRigidBodyMotionSolver::solve(), BICCG::solverDict(), ICCG::solverDict(), dictionary::substituteKeyword(), dictionary::substituteScopedKeyword(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), solution::upgradeSolverDict(), JobInfo::write(), specie::write(), sixDoFRigidBodyMotionState::write(), rhoConst< Specie >::write(), polynomialTransport< Thermo, PolySize >::write(), hConstThermo< EquationOfState >::write(), polynomialSolidTransport< Thermo, PolySize >::write(), perfectFluid< Specie >::write(), icoPolynomial< Specie, PolySize >::write(), linear< Type >::write(), incompressiblePerfectGas< Specie >::write(), eConstThermo< EquationOfState >::write(), sutherlandTransport< Thermo >::write(), adiabaticPerfectFluid< Specie >::write(), hPolynomialThermo< EquationOfState, PolySize >::write(), uniformInterpolationTable< scalar >::write(), janafThermo< EquationOfState >::write(), fieldAverage::writeAveragingProperties(), surfaceFeatures::writeDict(), Time::writeObject(), cellSource::writeValues(), and faceSource::writeValues().
add() [2/8]
void add (const entry & e, bool mergeEntry = false)
Add an entry.
With the merge option, dictionaries are interwoven and primitive entries are overwritten
Definition at line 820 of file dictionary.C.
References dictionary::add(), and entry::clone().
add() [3/8]
void add (const keyType & k, const word & w, bool overwrite = false)
Add a word entry.
optionally overwrite an existing entry
Definition at line 826 of file dictionary.C.
References dictionary::add().
add() [4/8]
void add (const keyType & k, const string & s, bool overwrite = false)
Add a string entry.
optionally overwrite an existing entry
Definition at line 833 of file dictionary.C.
References dictionary::add().
add() [5/8]
void add (const keyType & k, const label l, bool overwrite = false)
Add a label entry.
optionally overwrite an existing entry
Definition at line 843 of file dictionary.C.
References dictionary::add().
add() [6/8]
void add (const keyType & k, const scalar s, bool overwrite = false)
Add a scalar entry.
optionally overwrite an existing entry
Definition at line 849 of file dictionary.C.
References dictionary::add().
add() [7/8]
void add (const keyType & k, const dictionary & d, bool mergeEntry = false)
Add a dictionary entry.
optionally merge with an existing sub-dictionary
Definition at line 856 of file dictionary.C.
References dictionary::add().
add() [8/8]
void add (const keyType & k, const T & t, bool overwrite = false)
Add a T entry.
optionally overwrite an existing entry
Definition at line 124 of file dictionaryTemplates.C.
References dictionary::add().
set() [1/4]
void set (entry * entryPtr)
Assign a new entry, overwrite any existing entry.
Definition at line 866 of file dictionary.C.
References dictionary::add(), dictionary::clear(), entry::dict(), entry::isDict(), entry::keyword(), and dictionary::lookupEntryPtr().
Referenced by meshRefinement::addPatch(), distributedTriSurfaceMesh::distribute(), extrudePatchMesh::extrudePatchMesh(), polyMesh::polyMesh(), codedFunctionObject::redirectFunctionObject(), CodedSource< Type >::redirectFvOption(), boundaryRegion::rename(), thermalBaffleFvPatchScalarField::rmap(), data::setSolverPerformance(), structuredDecomp::structuredDecomp(), and solution::upgradeSolverDict().
set() [2/4]
void set (const entry & e)
Assign a new entry, overwrite any existing entry.
Definition at line 879 of file dictionary.C.
References entry::clone().
set() [3/4]
void set (const keyType & k, const dictionary & d)
Assign a dictionary entry, overwrite any existing entry.
Definition at line 885 of file dictionary.C.
set() [4/4]
void set (const keyType & k, const T & t)
Assign a T entry, overwrite any existing entry.
Definition at line 131 of file dictionaryTemplates.C.
remove()
bool remove (const word & Keyword)
Remove an entry specified by keyword.
Definition at line 891 of file dictionary.C.
References dictionary::changeKeyword(), and UILList< DLListBase, T >::remove().
Referenced by removeEntry::execute(), and IOerror::SafeFatalIOError().
changeKeyword()
bool changeKeyword (const keyType & oldKeyword, const keyType & newKeyword, bool forceOverwrite = false)
Change the keyword for an entry,.
optionally forcing overwrite of an existing entry
Definition at line 924 of file dictionary.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, IOWarningIn, keyType::isPattern(), dictionaryName::name(), and DLListBase::replace().
Referenced by dictionary::remove().
merge()
bool merge (const dictionary & dict)
Merge entries from the given dictionary.
Also merge sub-dictionaries as required.
Definition at line 1017 of file dictionary.C.
References Foam::abort(), dictionary::add(), dictionary::clone(), dict, Foam::FatalIOError, FatalIOErrorIn, forAllConstIter(), and dictionaryName::name().
Referenced by autoLayerDriver::addLayers(), and Time::readDict().
clear()
void clear ()
Clear the dictionary.
Definition at line 1062 of file dictionary.C.
References ILList< DLListBase, T >::clear().
Referenced by entry::New(), dictionary::operator=(), Foam::operator>>(), dictionary::set(), and data::setSolverPerformance().
transfer()
void transfer (dictionary & dict)
Transfer the contents of the argument and annul the argument.
Definition at line 1071 of file dictionary.C.
References dictionaryName::name(), and ILList< DLListBase, T >::transfer().
Referenced by dictionary::dictionary(), and csvTableReader< Type >::operator()().
xfer()
Foam::Xfer< Foam::dictionary > xfer ()
Transfer contents to the Xfer container.
Definition at line 1084 of file dictionary.C.
References Foam::xferMove().
read() [1/2]
bool read (Istream & is)
Read dictionary from Istream.
Definition at line 126 of file dictionaryIO.C.
Referenced by dictionary::dictionary(), includeIfPresentEntry::execute(), calcEntry::execute(), includeEntry::execute(), includeEtcEntry::execute(), codeStream::execute(), and Foam::operator>>().
read() [2/2]
bool read (Istream & is, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
Definition at line 81 of file dictionaryIO.C.
References IOstream::bad(), token::BEGIN_BLOCK, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, IOstream::good(), Foam::Info, dictionaryName::name(), entry::New(), and Istream::putBack().
write()
void write (Ostream & os, const bool subDict = true) const
Write dictionary, normally with sub-dictionary formatting.
Definition at line 173 of file dictionaryIO.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), Foam::e, token::END_BLOCK, Foam::endl(), forAllConstIter(), IOstream::good(), Foam::incrIndent(), Foam::indent(), UILList< DLListBase, entry >::last(), dictionaryName::name(), Foam::nl, dictionary::null, dictionary::parent(), and WarningIn.
Referenced by Foam::operator<<(), dictionary::tokens(), dictionaryEntry::write(), fieldDictionary::writeData(), IOdictionary::writeData(), solidificationMeltingSource::writeData(), surfaceFeatures::writeDict(), and JobInfo::~JobInfo().
operator[]()
Foam::ITstream & operator[] (const word & keyword) const
Find and return entry.
Definition at line 1092 of file dictionary.C.
References dictionary::lookup().
operator=()
void operator= (const dictionary & rhs)
Definition at line 1098 of file dictionary.C.
References Foam::abort(), dictionary::add(), dictionary::clear(), dictionary::clone(), Foam::FatalIOError, FatalIOErrorIn, forAllConstIter(), and dictionaryName::name().
Referenced by dictionary::dictionary(), IOdictionary::IOdictionary(), and IOdictionary::operator=().
operator+=()
void operator+= (const dictionary & rhs)
Include entries from the given dictionary.
Warn, but do not overwrite existing entries.
Definition at line 1121 of file dictionary.C.
References Foam::abort(), dictionary::add(), dictionary::clone(), Foam::FatalIOError, FatalIOErrorIn, forAllConstIter(), and dictionaryName::name().
operator|=()
void operator|= (const dictionary & rhs)
Conditionally include entries from the given dictionary.
Do not overwrite existing entries.
Definition at line 1138 of file dictionary.C.
References Foam::abort(), dictionary::add(), dictionary::clone(), Foam::FatalIOError, FatalIOErrorIn, forAllConstIter(), dictionary::found(), and dictionaryName::name().
operator<<=()
void operator<<= (const dictionary & rhs)
Unconditionally include entries from the given dictionary.
Overwrite existing entries.
Definition at line 1158 of file dictionary.C.
References Foam::abort(), Foam::FatalIOError, FatalIOErrorIn, forAllConstIter(), and dictionaryName::name().
Friends And Related Function Documentation
entry
friend class entry friend
Declare friendship with the entry class for IO.
Definition at line 185 of file dictionary.H.
operator>>
Istream& operator>> (Istream & , dictionary &) friend
Read dictionary from Istream.
operator<<
Ostream& operator<< (Ostream & , const dictionary &) friend
Write dictionary to Ostream.
Member Data Documentation
null
const dictionary null static
Null dictionary.
Definition at line 193 of file dictionary.H.
Referenced by cellModel::cellModel(), entry::clone(), laminar::coeffDict(), primitiveEntry::dict(), Foam::dimensionedConstant(), fieldAverageItem::fieldAverageItem(), entry::New(), lduMatrix::preconditioner::New(), phase::iNew::operator()(), phaseModel::iNew::operator()(), Foam::operator>>(), phaseProperties::phaseProperties(), pressureGradientExplicitSource::pressureGradientExplicitSource(), primitiveEntry::primitiveEntry(), and dictionary::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/dictionary.H
src/OpenFOAM/db/dictionary/dictionary.C
src/OpenFOAM/db/dictionary/dictionaryIO.C
src/OpenFOAM/db/dictionary/dictionaryTemplates.C