OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
calcEntry Class Reference
Uses dynamic compilation to provide calculating functionality for entering dictionary entries.
Public Member Functions
ClassName ("calc")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Detailed Description
Uses dynamic compilation to provide calculating functionality for entering dictionary entries.
E.g.
a 1.0;
b 3;
c #calc "$a/$b";
Note the explicit trailing 0 ('1.0') to force a to be read (and written) as a floating point number.
Note
Internally this is just a wrapper around codeStream functionality - the calc string gets used to construct a dictionary for codeStream.
Source files
calcEntry.H
calcEntry.C
Definition at line 68 of file calcEntry.H.
Member Function Documentation
ClassName()
ClassName ("calc")
Runtime type information.
execute() [1/2]
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 108 of file calcEntry.C.
References dictionary::add(), dynamicCode::checkSecurity(), Foam::endl(), IOstream::format(), Foam::Info, IOstream::lineNumber(), dictionaryName::name(), dictionary::read(), and s().
Referenced by calcEntry::execute().
execute() [2/2]
bool execute (const dictionary & parentDict, primitiveEntry & thisEntry, Istream & is) static
Execute the functionEntry in a primitiveEntry context.
Definition at line 63 of file calcEntry.C.
References dictionary::add(), dynamicCode::checkSecurity(), Foam::endl(), calcEntry::execute(), IOstream::format(), Foam::Info, IOstream::lineNumber(), dictionaryName::name(), primitiveEntry::read(), and s().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/calcEntry/calcEntry.H
src/OpenFOAM/db/dictionary/functionEntries/calcEntry/calcEntry.C