OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
codedBase Class Reference abstract
Base class for function objects and boundary conditions using dynamic code.
Public Member Functions
ClassName ("codedBase")
Runtime type information.
codedBase ()
Construct null.
virtual ~codedBase ()
Destructor.
Protected Member Functions
void updateLibrary (const word &redirectType) const
Update library as required.
virtual dlLibraryTable & libs () const =0
get the loaded dynamic libraries
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const =0
adapt the context for the current object
virtual string description () const =0
virtual void clearRedirect () const =0
virtual const dictionary & codeDict () const =0
Detailed Description
Base class for function objects and boundary conditions using dynamic code.
Source files
codedBase.H
codedBase.C
Definition at line 53 of file codedBase.H.
Constructor & Destructor Documentation
codedBase()
codedBase ()
Construct null.
Definition at line 351 of file codedBase.C.
~codedBase()
~codedBase () virtual
Destructor.
Definition at line 357 of file codedBase.C.
Member Function Documentation
updateLibrary()
void updateLibrary (const word & redirectType) const protected
Update library as required.
Definition at line 290 of file codedBase.C.
References dynamicCode::checkSecurity(), dict, dynamicCodeContext::dict(), Foam::endl(), Foam::Info, dynamicCode::libraryBaseName(), dictionaryName::name(), dynamicCodeContext::sha1(), dictionary::startLineNumber(), and SHA1Digest::str().
libs()
virtual dlLibraryTable& libs () const protected pure virtual
get the loaded dynamic libraries
Implemented in CodedSource< Type >, and codedFunctionObject.
prepare()
virtual void prepare (dynamicCode & , const dynamicCodeContext &) const protected pure virtual
adapt the context for the current object
Implemented in CodedSource< Type >, and codedFunctionObject.
description()
virtual string description () const protected pure virtual
Implemented in CodedSource< Type >, and codedFunctionObject.
clearRedirect()
virtual void clearRedirect () const protected pure virtual
Implemented in CodedSource< Type >, and codedFunctionObject.
codeDict()
virtual const dictionary& codeDict () const protected pure virtual
Implemented in CodedSource< Type >, and codedFunctionObject.
ClassName()
ClassName ("codedBase")
Runtime type information.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/codedBase/codedBase.H
src/OpenFOAM/db/dynamicLibrary/codedBase/codedBase.C