OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
includeEtcEntry Class Reference
Specify an etc file to include when reading dictionaries, expects a single string to follow.
Public Member Functions
ClassName ("includeEtc")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Attributes
static bool report
Report which file is included to stdout.
Detailed Description
Specify an etc file to include when reading dictionaries, expects a single string to follow.
Searches for files from user/group/shipped directories. The search scheme allows for version-specific and version-independent files using the following hierarchy:
user settings:
~/.OpenFOAM/<VERSION>
~/.OpenFOAM/
group (site) settings (when $WM_PROJECT_SITE is set):
$WM_PROJECT_SITE/<VERSION>
$WM_PROJECT_SITE
group (site) settings (when $WM_PROJECT_SITE is not set):
$WM_PROJECT_INST_DIR/site/<VERSION>
$WM_PROJECT_INST_DIR/site/
other (shipped) settings:
$WM_PROJECT_DIR/etc/
An example of the #includeEtc directive:
    #includeEtc "etcFile"
The usual expansion of environment variables and other constructs is retained.
See also
findEtcFile, fileName, string::expand()
Source files
includeEtcEntry.H
includeEtcEntry.C
Definition at line 77 of file includeEtcEntry.H.
Member Function Documentation
ClassName()
ClassName ("includeEtc")
Runtime type information.
execute() [1/2]
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 98 of file includeEtcEntry.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, dictionaryName::name(), IFstream::name(), dictionary::read(), and includeEtcEntry::report.
execute() [2/2]
bool execute (const dictionary & parentDict, primitiveEntry & entry, Istream & is) static
Execute the functionEntry in a primitiveEntry context.
Definition at line 137 of file includeEtcEntry.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, dictionaryName::name(), IFstream::name(), primitiveEntry::read(), and includeEtcEntry::report.
Member Data Documentation
report
bool report static
Report which file is included to stdout.
Definition at line 102 of file includeEtcEntry.H.
Referenced by includeEtcEntry::execute().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/includeEtcEntry/includeEtcEntry.H
src/OpenFOAM/db/dictionary/functionEntries/includeEtcEntry/includeEtcEntry.C