OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dynamicCodeContext Class Reference
Encapsulation of dynamic code dictionaries.
Public Member Functions
dynamicCodeContext (const dictionary &)
Construct from a dictionary.
const dictionary & dict () const
Return the parent dictionary context.
const string & include () const
Return the code-includes.
const string & options () const
Return the code-options.
const string & libs () const
Return the code-libs.
const string & code () const
Return the code.
const string & localCode () const
Return the local (file-scope) code.
const SHA1Digest & sha1 () const
Return SHA1 digest calculated from include, options, code.
Static Public Member Functions
static void addLineDirective (string &, const label lineNum, const fileName &name)
Helper: add #line directive.
Detailed Description
Encapsulation of dynamic code dictionaries.
Source files
dynamicCodeContext.H
dynamicCodeContext.C
Definition at line 49 of file dynamicCodeContext.H.
Constructor & Destructor Documentation
dynamicCodeContext()
dynamicCodeContext (const dictionary & dict)
Construct from a dictionary.
Definition at line 33 of file dynamicCodeContext.C.
References dynamicCodeContext::addLineDirective(), OSHA1stream::digest(), Foam::stringOps::inplaceExpand(), dictionary::lookupEntry(), dictionary::lookupEntryPtr(), dictionaryName::name(), entry::startLineNumber(), entry::stream(), and Foam::stringOps::trim().
Member Function Documentation
dict()
const dictionary& dict () const inline
Return the parent dictionary context.
Definition at line 84 of file dynamicCodeContext.H.
Referenced by codedBase::updateLibrary().
include()
const string& include () const inline
Return the code-includes.
Definition at line 90 of file dynamicCodeContext.H.
Referenced by dynamicCode::setFilterContext().
options()
const string& options () const inline
Return the code-options.
Definition at line 96 of file dynamicCodeContext.H.
Referenced by codedFunctionObject::prepare(), and CodedSource< Type >::prepare().
libs()
const string& libs () const inline
Return the code-libs.
Definition at line 102 of file dynamicCodeContext.H.
Referenced by codedFunctionObject::prepare(), and CodedSource< Type >::prepare().
code()
const string& code () const inline
Return the code.
Definition at line 108 of file dynamicCodeContext.H.
Referenced by dynamicCodeContext::addLineDirective(), and dynamicCode::setFilterContext().
localCode()
const string& localCode () const inline
Return the local (file-scope) code.
Definition at line 114 of file dynamicCodeContext.H.
Referenced by dynamicCode::setFilterContext().
sha1()
const SHA1Digest& sha1 () const inline
Return SHA1 digest calculated from include, options, code.
Definition at line 120 of file dynamicCodeContext.H.
References dynamicCodeContext::addLineDirective(), and Foam::name().
Referenced by dynamicCode::setFilterContext(), codedBase::updateLibrary(), and dynamicCode::upToDate().
addLineDirective()
void addLineDirective (string & code, const label lineNum, const fileName & name) static
Helper: add #line directive.
Definition at line 128 of file dynamicCodeContext.C.
References dynamicCodeContext::code(), and Foam::name().
Referenced by dynamicCodeContext::dynamicCodeContext(), codedFunctionObject::read(), and dynamicCodeContext::sha1().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCodeContext.H
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCodeContext.C