OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
codeStream Class Reference
Dictionary entry that contains C++ OpenFOAM code that is compiled to generate the entry itself. So.
Public Member Functions
ClassName ("codeStream")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Attributes
static const word codeTemplateC = "codeStreamTemplate.C"
Name of the C code template to be used.
Friends
class calcEntry
Declare friendship with the calcEntry class.
Detailed Description
Dictionary entry that contains C++ OpenFOAM code that is compiled to generate the entry itself. So.
- codeStream reads three entries: 'code', 'codeInclude' (optional), 'codeOptions' (optional) and uses those to generate library sources inside codeStream/
these get compiled using 'wmake libso'
the resulting library is loaded in executed with as arguments
(const dictionary& dict, Ostream& os)
where the dictionary is the current dictionary.
the code has to write into Ostream which is then used to construct the actual dictionary entry.
E.g. to set the internal field of a field:
internalField  #codeStream
{
    code
    #{
        const IOdictionary& d = static_cast<const IOdictionary&>(dict);
        const fvMesh& mesh = refCast<const fvMesh>(d.db());
        scalarField fld(mesh.nCells(), 12.34);
        fld.writeEntry("", os);
    #};
    //! Optional:
    codeInclude
    #{
        #include "fvCFD.H"
    #};
    //! Optional:
    codeOptions
    #{
        -I$(LIB_SRC)/finiteVolume/lnInclude
    #};
};
Note the #{ ... #} syntax is a 'verbatim' input mode that allows inputting strings with embedded newlines.
Limitations:
'~' symbol not allowed inside the code sections.
probably some other limitations (uses string::expand which expands $ and ~ sequences)
Note
The code to be compiled is stored under the local codeStream directory with a subdirectory name corresponding to the SHA1 of the contents.
The corresponding library code is located under the local codeStream/platforms/$WM_OPTIONS/lib directory in a library libcodeStream_SHA1.so
Source files
codeStream.H
codeStream.C
Definition at line 112 of file codeStream.H.
Member Function Documentation
ClassName()
ClassName ("codeStream")
Runtime type information.
execute() [1/2]
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 365 of file codeStream.C.
References dynamicCode::checkSecurity(), Foam::endl(), IOstream::format(), Foam::Info, IOstream::lineNumber(), dictionaryName::name(), and dictionary::read().
Referenced by codeStream::execute().
execute() [2/2]
bool execute (const dictionary & parentDict, primitiveEntry & entry, Istream & is) static
Execute the functionEntry in a primitiveEntry context.
Definition at line 331 of file codeStream.C.
References dynamicCode::checkSecurity(), Foam::endl(), codeStream::execute(), IOstream::format(), Foam::Info, IOstream::lineNumber(), dictionaryName::name(), and primitiveEntry::read().
Friends And Related Function Documentation
calcEntry
friend class calcEntry friend
Declare friendship with the calcEntry class.
Definition at line 153 of file codeStream.H.
Member Data Documentation
codeTemplateC
const Foam::word codeTemplateC = "codeStreamTemplate.C" static
Name of the C code template to be used.
Definition at line 148 of file codeStream.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/codeStream/codeStream.H
src/OpenFOAM/db/dictionary/functionEntries/codeStream/codeStream.C