OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
includeIfPresentEntry Class Reference
Specify a file to include if it exists. Expects a single string to follow.
Public Member Functions
ClassName ("includeIfPresent")
Runtime type information.
Public Member Functions inherited from includeEntry
ClassName ("include")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Member Functions inherited from includeEntry
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Additional Inherited Members
Static Public Attributes inherited from includeEntry
static bool report
Report which file is included to stdout.
Static Protected Member Functions inherited from includeEntry
static fileName includeFileName (Istream &, const dictionary &)
Read the include fileName from Istream, expand and return.
static fileName includeFileName (const fileName &dir, const fileName &, const dictionary &)
Expand include fileName and return.
Detailed Description
Specify a file to include if it exists. Expects a single string to follow.
The #includeIfPresent directive is similar to the #include directive, but does not generate an error if the file does not exist.
See also
Foam::functionEntries::includeEntry
Source files
includeIfPresentEntry.H
includeIfPresentEntry.C
Definition at line 56 of file includeIfPresentEntry.H.
Member Function Documentation
ClassName()
ClassName ("includeIfPresent")
Runtime type information.
execute() [1/2]
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 67 of file includeIfPresentEntry.C.
References Foam::endl(), Foam::Info, dictionary::read(), and includeEntry::report.
execute() [2/2]
bool execute (const dictionary & parentDict, primitiveEntry & entry, Istream & is) static
Execute the functionEntry in a primitiveEntry context.
Definition at line 89 of file includeIfPresentEntry.C.
References Foam::endl(), Foam::Info, primitiveEntry::read(), and includeEntry::report.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/includeIfPresentEntry/includeIfPresentEntry.H
src/OpenFOAM/db/dictionary/functionEntries/includeIfPresentEntry/includeIfPresentEntry.C