OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
includeEntry Class Reference
Specify an include file when reading dictionaries, expects a single string to follow.
Public Member Functions
ClassName ("include")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Static Public Attributes
static bool report
Report which file is included to stdout.
Static Protected Member Functions
static fileName includeFileName (Istream &, const dictionary &)
Read the include fileName from Istream, expand and return.
static fileName includeFileName (const fileName &dir, const fileName &, const dictionary &)
Expand include fileName and return.
Detailed Description
Specify an include file when reading dictionaries, expects a single string to follow.
An example of the #include directive:
    #include "includeFile"
The usual expansion of environment variables and other constructs (eg, the ~OpenFOAM/ expansion) is retained.
See also
fileName, string::expand()
Source files
includeEntry.H
includeEntry.C
Definition at line 62 of file includeEntry.H.
Member Function Documentation
includeFileName() [1/2]
Foam::fileName includeFileName (Istream & is, const dictionary & dict) static protected
Read the include fileName from Istream, expand and return.
Definition at line 71 of file includeEntry.C.
References Foam::stringOps::inplaceExpand(), fileName::isAbsolute(), IOstream::name(), and path().
includeFileName() [2/2]
Foam::fileName includeFileName (const fileName & dir, const fileName & f, const dictionary & dict) static protected
Expand include fileName and return.
Definition at line 94 of file includeEntry.C.
References includeEntry::execute(), Foam::stringOps::inplaceExpand(), and fileName::isAbsolute().
ClassName()
ClassName ("include")
Runtime type information.
execute() [1/2]
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 120 of file includeEntry.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, dictionaryName::name(), IFstream::name(), IOstream::name(), fileName::path(), dictionary::read(), and includeEntry::report.
Referenced by includeEntry::includeFileName(), and entry::New().
execute() [2/2]
bool execute (const dictionary & parentDict, primitiveEntry & entry, Istream & is) static
Execute the functionEntry in a primitiveEntry context.
Definition at line 159 of file includeEntry.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, dictionaryName::name(), IFstream::name(), IOstream::name(), fileName::path(), primitiveEntry::read(), and includeEntry::report.
Member Data Documentation
report
bool report static
Report which file is included to stdout.
Definition at line 94 of file includeEntry.H.
Referenced by includeIfPresentEntry::execute(), and includeEntry::execute().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/includeEntry/includeEntry.H
src/OpenFOAM/db/dictionary/functionEntries/includeEntry/includeEntry.C