OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Callback< CallbackType > Class Template Reference
Abstract class to handle automatic call-back registration with the CallbackRegistry. Derive from this class and extend by adding the appropriate callback functions.
Public Member Functions
Callback (CallbackRegistry< CallbackType > &)
Construct and register with CallbackRegistry.
Callback (const Callback< CallbackType > &)
Construct as copy.
virtual ~Callback ()
Destructor.
bool checkIn ()
Register Callback with CallbackRegistry.
bool checkOut ()
Check-out Callback from CallbackRegistry.
Detailed Description
template<class CallbackType>
class Foam::Callback< CallbackType >
Abstract class to handle automatic call-back registration with the CallbackRegistry. Derive from this class and extend by adding the appropriate callback functions.
Source files
Callback.H
Callback.C
Definition at line 51 of file Callback.H.
Constructor & Destructor Documentation
Callback() [1/2]
Callback (CallbackRegistry< CallbackType > & cbr)
Construct and register with CallbackRegistry.
Definition at line 31 of file Callback.C.
References Callback< CallbackType >::checkIn().
Callback() [2/2]
Callback (const Callback< CallbackType > & cb)
Construct as copy.
Definition at line 40 of file Callback.C.
References Callback< CallbackType >::checkIn().
~Callback()
~Callback () virtual
Destructor.
Definition at line 51 of file Callback.C.
References Callback< CallbackType >::checkOut().
Member Function Documentation
checkIn()
bool checkIn ()
Register Callback with CallbackRegistry.
Definition at line 60 of file Callback.C.
Referenced by Callback< CallbackType >::Callback().
checkOut()
bool checkOut ()
Check-out Callback from CallbackRegistry.
Definition at line 75 of file Callback.C.
Referenced by Callback< CallbackType >::~Callback().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Callback/Callback.H
src/OpenFOAM/db/Callback/Callback.C