OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dictionaryName Class Reference
Public Member Functions
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Detailed Description
Definition at line 78 of file dictionary.H.
Constructor & Destructor Documentation
dictionaryName() [1/2]
dictionaryName () inline
Construct dictionaryName null.
Definition at line 90 of file dictionary.H.
dictionaryName() [2/2]
dictionaryName (const fileName & name) inline
Construct dictionaryName as copy of the given fileName.
Definition at line 94 of file dictionary.H.
Member Function Documentation
name() [1/2]
const fileName& name () const inline
Return the dictionary name.
Definition at line 103 of file dictionary.H.
Referenced by dictionary::add(), dictionary::changeKeyword(), chemkinReader::chemkinReader(), molecule::constantProperties::constantProperties(), dictionary::dictionary(), Foam::dimensionedConstant(), dynamicCodeContext::dynamicCodeContext(), calcEntry::execute(), includeEntry::execute(), includeEtcEntry::execute(), codeStream::execute(), IOdictionary::IOdictionary(), JobInfo::JobInfo(), dictionary::lookupEntry(), dictionary::lookupScopedEntryPtr(), dictionary::merge(), dictionaryEntry::name(), dictionary::operator+=(), dictionary::operator<<=(), dictionary::operator=(), Foam::operator>>(), dictionary::operator|=(), codedFunctionObject::read(), dictionary::read(), dictionary::subDict(), dictionary::subOrEmptyDict(), Foam::debug::switchSet(), dictionary::topDict(), dictionary::transfer(), Foam::unitSet(), codedBase::updateLibrary(), and dictionary::write().
name() [2/2]
fileName& name () inline
Return the dictionary name.
Definition at line 109 of file dictionary.H.
dictName()
const word dictName () const inline
Return the local dictionary name (final part of scoped name)
Definition at line 115 of file dictionary.H.
References fileName::name().
Referenced by constAnIsoSolidTransport< Thermo >::constAnIsoSolidTransport(), constIsoSolidTransport< Thermo >::constIsoSolidTransport(), constTransport< Thermo >::constTransport(), dictionaryEntry::dictName(), writeDictionary::execute(), exponentialSolidTransport< Thermo >::exponentialSolidTransport(), profileModel::New(), solidProperties::New(), liquidProperties::New(), writeDictionary::tryDirectory(), specie::write(), rhoConst< Specie >::write(), polynomialTransport< Thermo, PolySize >::write(), hConstThermo< EquationOfState >::write(), polynomialSolidTransport< Thermo, PolySize >::write(), icoPolynomial< Specie, PolySize >::write(), perfectFluid< Specie >::write(), linear< Type >::write(), eConstThermo< EquationOfState >::write(), incompressiblePerfectGas< Specie >::write(), sutherlandTransport< Thermo >::write(), adiabaticPerfectFluid< Specie >::write(), hPolynomialThermo< EquationOfState, PolySize >::write(), and janafThermo< EquationOfState >::write().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/dictionary/dictionary.H