OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
removeEntry Class Reference
Remove a dictionary entry.
Public Member Functions
ClassName ("remove")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Detailed Description
Remove a dictionary entry.
The #remove directive takes a list or a single wordRe. For example,
    #remove entry0
    #remove ( entry1 entry2 entry3 otherEntry )
    #remove "entry[1-3]"
    #remove ( "entry[1-3]" otherEntry )
The removal only occurs in the current context. Removing sub-entries or parent entries is not supported.
Source files
removeEntry.H
removeEntry.C
Definition at line 62 of file removeEntry.H.
Member Function Documentation
ClassName()
ClassName ("remove")
Runtime type information.
execute()
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 62 of file removeEntry.C.
References Foam::findStrings(), forAll, dictionary::remove(), and dictionary::toc().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/removeEntry/removeEntry.H
src/OpenFOAM/db/dictionary/functionEntries/removeEntry/removeEntry.C