OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
inputModeEntry Class Reference
Specify the input mode when reading dictionaries, expects a single word to follow.
Public Member Functions
ClassName ("inputMode")
Runtime type information.
Public Member Functions inherited from functionEntry
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static void clear ()
Reset the inputMode to default (ie, merge)
static bool merge ()
Return true if the inputMode is merge.
static bool overwrite ()
Return true if the inputMode is overwrite.
static bool protect ()
Return true if the inputMode is protect.
static bool error ()
Return true if the inputMode is error.
Static Public Member Functions inherited from functionEntry
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Detailed Description
Specify the input mode when reading dictionaries, expects a single word to follow.
An example of #inputMode directive:
    #inputMode merge
The possible input modes:
Parameters
merge merge sub-dictionaries when possible
overwrite keep last entry and silently remove previous ones
protect keep initial entry and silently ignore subsequent ones
warn keep initial entry and warn about subsequent ones
error issue a FatalError for duplicate entries
default currently identical to merge
Source files
inputModeEntry.H
inputModeEntry.C
Definition at line 64 of file inputModeEntry.H.
Member Function Documentation
ClassName()
ClassName ("inputMode")
Runtime type information.
execute()
bool execute (dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 99 of file inputModeEntry.C.
clear()
void clear () static
Reset the inputMode to default (ie, merge)
Definition at line 109 of file inputModeEntry.C.
Referenced by dictionary::dictionary(), and Foam::operator>>().
merge()
bool merge () static
Return true if the inputMode is merge.
Definition at line 115 of file inputModeEntry.C.
Referenced by entry::New().
overwrite()
bool overwrite () static
Return true if the inputMode is overwrite.
Definition at line 121 of file inputModeEntry.C.
Referenced by entry::New().
protect()
bool protect () static
Return true if the inputMode is protect.
Definition at line 127 of file inputModeEntry.C.
Referenced by entry::New().
error()
bool error () static
Return true if the inputMode is error.
Definition at line 132 of file inputModeEntry.C.
Referenced by entry::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/inputModeEntry/inputModeEntry.H
src/OpenFOAM/db/dictionary/functionEntries/inputModeEntry/inputModeEntry.C