OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CocoParserErrors< BaseClass, StringClass > Class Template Reference
Templated class to shadow the error handling for Coco/R parsers.
Public Member Functions
CocoParserErrors (const word &name)
Construct with given name.
virtual ~CocoParserErrors ()
Destructor.
virtual const word & name () const
Return the name issued for warnings.
virtual word & name ()
Return the name issued for warnings.
virtual void Warning (const StringClass &msg)
Handle a general warning 'msg'.
virtual void Warning (int line, int col, const StringClass &msg)
Handle a general warning 'msg'.
virtual void Error (int line, int col, const StringClass &msg)
Handle general error 'msg' (eg, a semantic error)
virtual void Error (const StringClass &msg)
Handle general error 'msg' (eg, a semantic error)
virtual void Exception (const StringClass &msg)
Handle a general exception 'msg'.
Detailed Description
template<class BaseClass, class StringClass = std::wstring>
class Foam::CocoParserErrors< BaseClass, StringClass >
Templated class to shadow the error handling for Coco/R parsers.
Definition at line 47 of file CocoParserErrors.H.
Constructor & Destructor Documentation
CocoParserErrors()
CocoParserErrors (const word & name) inline
Construct with given name.
Definition at line 61 of file CocoParserErrors.H.
~CocoParserErrors()
virtual ~CocoParserErrors () inline virtual
Destructor.
Definition at line 69 of file CocoParserErrors.H.
Member Function Documentation
name() [1/2]
virtual const word& name () const inline virtual
Return the name issued for warnings.
Definition at line 76 of file CocoParserErrors.H.
name() [2/2]
virtual word& name () inline virtual
Return the name issued for warnings.
Definition at line 82 of file CocoParserErrors.H.
Warning() [1/2]
virtual void Warning (const StringClass & msg) inline virtual
Handle a general warning 'msg'.
Definition at line 91 of file CocoParserErrors.H.
References Foam::endl(), and WarningIn.
Warning() [2/2]
virtual void Warning (int line, int col, const StringClass & msg) inline virtual
Handle a general warning 'msg'.
Definition at line 98 of file CocoParserErrors.H.
References Foam::endl(), and WarningIn.
Error() [1/2]
virtual void Error (int line, int col, const StringClass & msg) inline virtual
Handle general error 'msg' (eg, a semantic error)
Definition at line 106 of file CocoParserErrors.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorIn.
Referenced by CocoParserErrors< BaseClass, StringClass >::Exception().
Error() [2/2]
virtual void Error (const StringClass & msg) inline virtual
Handle general error 'msg' (eg, a semantic error)
Definition at line 114 of file CocoParserErrors.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorIn.
Exception()
virtual void Exception (const StringClass & msg) inline virtual
Handle a general exception 'msg'.
Definition at line 122 of file CocoParserErrors.H.
References CocoParserErrors< BaseClass, StringClass >::Error().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/error/CocoParserErrors.H