OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
error Class Reference
Class to handle errors and exceptions in a simple, consistent stream-based manner.
Public Member Functions
error (const string &title)
Construct from title string.
error (const dictionary &)
Construct from dictionary.
error (const error &)
Construct as copy.
virtual ~error () throw ()
Destructor.
string message () const
const string & functionName () const
const string & sourceFileName () const
label sourceFileLineNumber () const
void throwExceptions ()
void dontThrowExceptions ()
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
operator dictionary () const
Create and return a dictionary.
void exit (const int errNo=1)
Exit : can be called for any error to exit program.
void abort ()
Abort : used to stop code for fatal errors.
Public Member Functions inherited from messageStream
messageStream (const string &title, errorSeverity, const int maxErrors=0)
Construct from components.
messageStream (const dictionary &)
Construct from dictionary.
const string & title () const
Return the title of this error type.
int maxErrors () const
Return the maximum number of errors before program termination.
int & maxErrors ()
Return non-const access to the maximum number of errors before.
OSstream & masterStream (const label communicator)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Convert to OSstream.
OSstream & operator() (const bool output)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream for << operations.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
Static Public Member Functions
static void safePrintStack (std::ostream &)
Helper function to print a stack (if OpenFOAM IO not yet.
static void printStack (Ostream &)
Helper function to print a stack.
Protected Attributes
string functionName_
string sourceFileName_
label sourceFileLineNumber_
bool abort_
bool throwExceptions_
OStringStream * messageStreamPtr_
Protected Attributes inherited from messageStream
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Friends
Ostream & operator<< (Ostream &, const error &)
Additional Inherited Members
Public Types inherited from messageStream
enum errorSeverity { INFO, WARNING, SERIOUS, FATAL }
Severity flags.
Static Public Attributes inherited from messageStream
static int level
Detailed Description
Class to handle errors and exceptions in a simple, consistent stream-based manner.
The error class is globally instantiated with a title string. Errors, messages and other data are piped to the messageStream class in the standard manner. Manipulators are supplied for exit and abort which may terminate the program or throw an exception depending on whether the exception handling has been switched on (off by default).
Usage
error << "message1" << "message2" << FoamDataType << exit(errNo);
error << "message1" << "message2" << FoamDataType << abort();
Source files
error.H
error.C
Definition at line 66 of file error.H.
Constructor & Destructor Documentation
error() [1/3]
error (const string & title)
Construct from title string.
Definition at line 36 of file error.C.
References Foam::endl(), error::exit(), IOstream::good(), error::messageStreamPtr_, and Foam::Perr.
error() [2/3]
error (const dictionary & errDict)
Construct from dictionary.
Definition at line 57 of file error.C.
References Foam::endl(), error::exit(), IOstream::good(), error::messageStreamPtr_, and Foam::Perr.
error() [3/3]
error (const error & err)
Construct as copy.
Definition at line 79 of file error.C.
~error()
~error () throw () virtual
Destructor.
Definition at line 94 of file error.C.
References error::messageStreamPtr_.
Member Function Documentation
message()
Foam::string message () const
Definition at line 162 of file error.C.
References error::messageStreamPtr_, and OStringStream::str().
Referenced by error::operator()(), and Foam::operator<<().
functionName()
const string& functionName () const inline
Definition at line 107 of file error.H.
References error::functionName_.
Referenced by error::dontThrowExceptions(), IOerror::ioEndLineNumber(), error::operator()(), IOerror::operator()(), and Foam::operator<<().
sourceFileName()
const string& sourceFileName () const inline
Definition at line 112 of file error.H.
References error::sourceFileName_.
Referenced by error::dontThrowExceptions(), IOerror::ioEndLineNumber(), error::operator()(), IOerror::operator()(), and Foam::operator<<().
sourceFileLineNumber()
label sourceFileLineNumber () const inline
Definition at line 117 of file error.H.
References error::sourceFileLineNumber_.
Referenced by error::dontThrowExceptions(), IOerror::ioEndLineNumber(), error::operator()(), IOerror::operator()(), and Foam::operator<<().
throwExceptions()
void throwExceptions () inline
Definition at line 122 of file error.H.
Referenced by Foam::tryCalc(), calcType::tryCalc(), calcType::tryInit(), calcType::tryPostCalc(), and calcType::tryPreCalc().
dontThrowExceptions()
void dontThrowExceptions () inline
Definition at line 127 of file error.H.
References error::functionName(), error::sourceFileLineNumber(), and error::sourceFileName().
operator()() [1/3]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 101 of file error.C.
References error::functionName(), error::functionName_, error::sourceFileLineNumber(), error::sourceFileLineNumber_, error::sourceFileName(), and error::sourceFileName_.
operator()() [2/3]
Foam::OSstream & operator() (const string & functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 116 of file error.C.
References error::abort(), dictionary::add(), Foam::endl(), error::functionName(), IOstream::good(), error::message(), error::messageStreamPtr_, Foam::Perr, string::replaceAll(), error::sourceFileLineNumber(), and error::sourceFileName().
operator OSstream &()
operator OSstream & ()
Convert to OSstream.
Prints basic message and returns OSstream for further info.
operator()() [3/3]
OSstream& operator() () inline
Explicitly convert to OSstream for << operations.
Definition at line 155 of file error.H.
References error::abort(), error::exit(), error::operator<<, error::printStack(), and error::safePrintStack().
Referenced by IOerror::operator()().
operator dictionary()
operator dictionary () const
Create and return a dictionary.
safePrintStack()
void safePrintStack (std::ostream & os) static
Helper function to print a stack (if OpenFOAM IO not yet.
initialised)
Definition at line 193 of file printStack.C.
References Foam::absolutePath(), Foam::demangleSymbol(), Foam::endl(), Foam::nl, Foam::printSourceFileAndLine(), and error::printStack().
Referenced by error::operator()().
printStack()
void printStack (Ostream & os) static
Helper function to print a stack.
Definition at line 30 of file dummyPrintStack.C.
Referenced by error::abort(), IOerror::abort(), messageStream::masterStream(), error::operator()(), Foam::reduce(), and error::safePrintStack().
exit()
void exit (const int errNo = 1)
Exit : can be called for any error to exit program.
Prints stack before exiting.
Definition at line 168 of file error.C.
References error::abort(), error::abort_, dictionary::add(), JobInfo::constructed, Foam::endl(), JobInfo::exit(), UPstream::exit(), Foam::jobInfo, error::messageStreamPtr_, UPstream::parRun(), Foam::Perr, OStringStream::rewind(), and error::throwExceptions_.
Referenced by argList::argList(), error::error(), Foam::exit(), if(), IOerror::ioEndLineNumber(), error::operator()(), argList::parse(), argList::setOption(), and argList::unsetOption().
abort()
void abort ()
Abort : used to stop code for fatal errors.
Prints stack before exiting.
Definition at line 209 of file error.C.
References JobInfo::abort(), UPstream::abort(), error::abort_, dictionary::add(), JobInfo::constructed, Foam::endl(), Foam::jobInfo, error::messageStreamPtr_, UPstream::parRun(), Foam::Perr, error::printStack(), OStringStream::rewind(), and error::throwExceptions_.
Referenced by Foam::abort(), error::exit(), IOerror::ioEndLineNumber(), and error::operator()().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const error &) friend
Referenced by IOerror::ioEndLineNumber(), and error::operator()().
Member Data Documentation
functionName_
string functionName_ protected
Definition at line 76 of file error.H.
Referenced by error::functionName(), and error::operator()().
sourceFileName_
string sourceFileName_ protected
Definition at line 77 of file error.H.
Referenced by error::operator()(), and error::sourceFileName().
sourceFileLineNumber_
label sourceFileLineNumber_ protected
Definition at line 78 of file error.H.
Referenced by error::operator()(), and error::sourceFileLineNumber().
abort_
bool abort_ protected
Definition at line 80 of file error.H.
Referenced by error::abort(), IOerror::abort(), error::exit(), and IOerror::exit().
throwExceptions_
bool throwExceptions_ protected
Definition at line 82 of file error.H.
Referenced by error::abort(), IOerror::abort(), error::exit(), and IOerror::exit().
messageStreamPtr_
OStringStream* messageStreamPtr_ protected
Definition at line 83 of file error.H.
Referenced by error::abort(), IOerror::abort(), error::error(), error::exit(), IOerror::exit(), error::message(), error::operator()(), and error::~error().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/error.H
src/OpenFOAM/db/error/error.C
src/OSspecific/POSIX/dummyPrintStack.C
src/OSspecific/POSIX/printStack.C