OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
outputFilterOutputControl Class Reference
An output control for function objects. The default is time-step execution at every interval.
Public Types
enum outputControls {
ocTimeStep, ocOutputTime, ocAdjustableTime, ocRunTime,
ocClockTime, ocCpuTime, ocNone
}
The output control options.
Public Member Functions
outputFilterOutputControl (const Time &, const dictionary &, const word &prefix)
Construct from Time object and dictionary.
~outputFilterOutputControl ()
Destructor.
void read (const dictionary &)
Read from dictionary.
const Time & time () const
Return const access to the Time object.
bool output ()
Flag to indicate whether to output.
outputControls outputControl () const
Return outputControl.
scalar writeInterval () const
Return writeInterval.
label outputTimeLastDump () const
Return outputTimeLastDump.
Detailed Description
An output control for function objects. The default is time-step execution at every interval.
Source files
outputFilterOutputControl.H
outputFilterOutputControl.C
Definition at line 51 of file outputFilterOutputControl.H.
Member Enumeration Documentation
outputControls
enum outputControls
The output control options.
Enumerator
ocTimeStep
execution is coupled to the time-step
ocOutputTime
execution is coupled to the output-time
ocAdjustableTime
Adjust time step for dumping
ocRunTime
run time for dumping
ocClockTime
clock time for dumping
ocCpuTime
cpu time for dumping
ocNone
no output
Definition at line 56 of file outputFilterOutputControl.H.
Constructor & Destructor Documentation
outputFilterOutputControl()
outputFilterOutputControl (const Time & t, const dictionary & dict, const word & prefix)
Construct from Time object and dictionary.
Definition at line 54 of file outputFilterOutputControl.C.
~outputFilterOutputControl()
~outputFilterOutputControl ()
Destructor.
Definition at line 73 of file outputFilterOutputControl.C.
Member Function Documentation
read()
void read (const dictionary & dict)
Read from dictionary.
Definition at line 79 of file outputFilterOutputControl.C.
References dictionary::found(), dictionary::lookup(), dictionary::lookupOrDefault(), and Foam::readScalar().
time()
const Time& time () const inline
Return const access to the Time object.
Definition at line 125 of file outputFilterOutputControl.H.
References outputFilterOutputControl::output().
output()
bool output ()
Flag to indicate whether to output.
Definition at line 125 of file outputFilterOutputControl.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::nl, and Foam::returnReduce().
Referenced by outputFilterOutputControl::time().
outputControl()
outputControls outputControl () const inline
Return outputControl.
Definition at line 134 of file outputFilterOutputControl.H.
writeInterval()
scalar writeInterval () const inline
Return writeInterval.
Definition at line 140 of file outputFilterOutputControl.H.
outputTimeLastDump()
label outputTimeLastDump () const inline
Return outputTimeLastDump.
Definition at line 146 of file outputFilterOutputControl.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/outputFilterOutputControl/outputFilterOutputControl.H
src/OpenFOAM/db/functionObjects/outputFilterOutputControl/outputFilterOutputControl.C