OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IOobject Class Reference
IOobject defines the attributes of an object for which implicit objectRegistry management is supported, and provides the infrastructure for performing stream I/O.
Public Types
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Member Functions
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
virtual void rename (const word &newName)
Rename.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Member Functions
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Detailed Description
IOobject defines the attributes of an object for which implicit objectRegistry management is supported, and provides the infrastructure for performing stream I/O.
An IOobject is constructed with an object name, a class name, an instance path, a reference to a objectRegistry, and parameters determining its storage status.
Read options
Define what is done on object construction and explicit reads:
Parameters
MUST_READ Object must be read from Istream on construction.
Error if Istream does not exist or can't be read. Does not check timestamp or re-read.
MUST_READ_IF_MODIFIED Object must be read from Istream on construction.
Error if Istream does not exist or can't be read. If object is registered its timestamp will be checked every timestep and possibly re-read.
READ_IF_PRESENT Read object from Istream if Istream exists, otherwise don't.
Error only if Istream exists but can't be read. Does not check timestamp or re-read.
NO_READ Don't read
Write options
Define what is done on object destruction and explicit writes:
Parameters
AUTO_WRITE Object is written automatically when requested to by the objectRegistry.
NO_WRITE No automatic write on destruction but can be written explicitly
Source files
IOobject.H
IOobject.C
IOobjectReadHeader.C
IOobjectWriteHeader.C
IOobjectPrint.C
Definition at line 91 of file IOobject.H.
Member Enumeration Documentation
objectState
enum objectState
Enumeration defining the valid states of an IOobject.
Enumerator
GOOD
BAD
Definition at line 99 of file IOobject.H.
readOption
enum readOption
Enumeration defining the read options.
Enumerator
MUST_READ
MUST_READ_IF_MODIFIED
READ_IF_PRESENT
NO_READ
Definition at line 106 of file IOobject.H.
writeOption
enum writeOption
Enumeration defining the write options.
Enumerator
AUTO_WRITE
NO_WRITE
Definition at line 115 of file IOobject.H.
Constructor & Destructor Documentation
IOobject() [1/3]
IOobject (const word & name, const fileName & instance, const objectRegistry & registry, readOption r = NO_READ, writeOption w = NO_WRITE, bool registerObject = true)
Construct from name, instance, registry, io options.
Definition at line 143 of file IOobject.C.
References Foam::endl(), and Foam::Info.
Referenced by IOobject::clone(), IOobject::fileNameComponents(), fvMesh::fvMesh(), IOobject::IOobject(), noRadiation::Ru(), opaqueSolid::Ru(), viewFactor::Ru(), noFilm::Sh(), kinematicSingleLayer::Sh(), noFilm::Srho(), kinematicSingleLayer::Srho(), and fvMesh::V00().
IOobject() [2/3]
IOobject (const word & name, const fileName & instance, const fileName & local, const objectRegistry & registry, readOption r = NO_READ, writeOption w = NO_WRITE, bool registerObject = true)
Construct from name, instance, local, registry, io options.
Definition at line 173 of file IOobject.C.
References Foam::endl(), Foam::Info, and IOobject::IOobject().
IOobject() [3/3]
IOobject (const fileName & path, const objectRegistry & registry, readOption r = NO_READ, writeOption w = NO_WRITE, bool registerObject = true)
Construct from path, registry, io options.
Uses fileNameComponents() to split path into components.
Definition at line 204 of file IOobject.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, and Foam::Info.
~IOobject()
~IOobject () virtual
Destructor.
Definition at line 251 of file IOobject.C.
Referenced by IOobject::clone().
Member Function Documentation
objectStream() [1/2]
Foam::Istream * objectStream () protected
Construct and return an IFstream for the object.
The results is NULL if the stream construction failed
Definition at line 392 of file IOobject.C.
objectStream() [2/2]
Foam::Istream * objectStream (const fileName & fName) protected
Construct and return an IFstream for the object given the.
exact file. The results is NULL if the stream construction failed
Definition at line 398 of file IOobject.C.
References IOstream::good().
setBad()
void setBad (const string & s) protected
Set the object state to bad.
Definition at line 462 of file IOobject.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and messageStream::level.
Referenced by IFstream::IFstream().
TypeName()
TypeName ("IOobject")
Runtime type information.
fileNameComponents()
bool fileNameComponents (const fileName & path, fileName & instance, fileName & local, word & name) static
Split path into instance, local, name components.
Definition at line 52 of file IOobject.C.
References Foam::endl(), IOobject::IOobject(), fileName::isAbsolute(), Foam::isDir(), Foam::name(), path(), and WarningIn.
groupName() [1/2]
static word groupName (Name name, const word & group) inline static
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), DarcyForchheimer::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), LESeddyViscosity< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), kEqn< BasicTurbulenceModel >::epsilon(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), polyBoundaryMesh::mesh(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::nuEff(), basicThermo::phasePropertyName(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), and nutURoughWallFunctionFvPatchScalarField::yPlus().
clone()
Foam::autoPtr<IOobject> clone () const inline
Clone.
Definition at line 231 of file IOobject.H.
References IOobject::db(), IOobject::IOobject(), IOobject::time(), and IOobject::~IOobject().
Referenced by attachPolyTopoChanger::attach(), polyTopoChange::makeMesh(), searchableSurface::iNew::operator()(), polyMesh::readUpdate(), searchableSurfaces::searchableSurfaces(), fvMeshSubset::setCellSubset(), and fvMeshSubset::setLargeCellSubset().
time()
const Foam::Time & time () const
Return time.
Definition at line 263 of file IOobject.C.
References objectRegistry::time().
Referenced by motionSmootherAlgo::avg(), regIOobject::checkIn(), regIOobject::checkOut(), IOobject::clone(), fvMeshSubset::interpolate(), Foam::fvm::laplacian(), simpleControl::loop(), Foam::MapGeometricFields(), regIOobject::modified(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< directionType, 3 >::names(), engineMesh::New(), dynamicFvMesh::New(), laminarFlameSpeed::New(), SRFModel::New(), turbulenceModel::New(), LESModel::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), RASModel::New(), radiationModel::New(), consumptionSpeed::omega0Sigma(), isNotEqOp< T >::operator()(), RaviPetersen::operator()(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), regIOobject::readIfModified(), pointFieldReconstructor::reconstructField(), data::setSolverPerformance(), fixedTemperatureConstraint::setValue(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), regIOobject::write(), meshRefinement::write(), Foam::writeCellGraph(), Foam::writePatchGraph(), FSD< CombThermoType, ThermoType >::~FSD(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), and subCycleField< GeometricField >::~subCycleField().
db()
const Foam::objectRegistry & db () const
Return the local objectRegistry.
Definition at line 257 of file IOobject.C.
Referenced by isoSurface::adaptPatchFields(), Foam::atan2(), motionSmootherAlgo::avg(), regIOobject::checkIn(), regIOobject::checkOut(), IOobject::clone(), Foam::cmptAv(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), InjectionModel< CloudType >::inject(), surfaceInterpolationScheme< GType >::interpolate(), volPointInterpolation::interpolate(), PhiScheme< Type, PhiLimiter >::limiter(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), Foam::mag(), Foam::magSqr(), reuseTmpDimensionedField< TypeR, Type1, GeoMesh >::New(), reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::New(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), engineMesh::New(), dynamicFvMesh::New(), laminarFlameSpeed::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh >::New(), SRFModel::New(), turbulenceModel::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, Type2, PatchField, GeoMesh >::New(), LESModel::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), RASModel::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), consumptionSpeed::omega0Sigma(), RaviPetersen::operator()(), sampledSurface::pointAverage(), Foam::pow(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), surfMesh::removeFiles(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), motionSmootherAlgo::setDisplacementPatchFields(), regIOobject::setUpToDate(), Foam::sqr(), Foam::stabilise(), surfMesh::surfMesh(), Foam::transform(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), IOobject::writeHeader(), FSD< CombThermoType, ThermoType >::~FSD(), Gulders::~Gulders(), and GuldersEGR::~GuldersEGR().
name()
const word& name () const inline
Return name.
Definition at line 252 of file IOobject.H.
Referenced by isoSurface::adaptPatchFields(), multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), IOobjectList::add(), autoLayerDriver::addLayers(), polyTopoChange::addMesh(), faceZoneSet::addSet(), solidificationMeltingSource::addSup(), effectivenessHeatExchangerSource::addSup(), globalIndexAndTransform::addToTransformIndex(), setsToFaceZone::applyToSet(), Foam::atan2(), attachPolyTopoChanger::attach(), Foam::fvc::average(), motionSmootherAlgo::avg(), functionObjectFile::baseFileDir(), blended< Type >::blendingFactor(), localBlended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), Foam::bound(), cellLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), Foam::fvc::cellReduce(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkDefinition(), Cloud< streamLineParticle >::checkFieldFieldIOobject(), Cloud< streamLineParticle >::checkFieldIOobject(), regIOobject::checkIn(), objectRegistry::checkIn(), Foam::checkMethod(), objectRegistry::checkOut(), polyBoundaryMesh::checkParallelSync(), faceZone::checkParallelSync(), meshRefinement::checkZoneFaces(), KinematicCloud< Foam::DsmcCloud >::cloneBare(), Foam::cmptAv(), Foam::MULES::correct(), optionList::correct(), temperatureLimitsConstraint::correct(), cubic< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), correctedSnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), localBlended< Type >::correction(), Foam::fvc::curl(), Foam::fvc::d2dt2(), Foam::fvm::d2dt2(), objectRegistry::dbDir(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvc::ddtCorr(), fvFieldDecomposer::decomposeField(), faceZoneSet::deleteSet(), Foam::fvc::div(), Foam::fvm::div(), Foam::fvc::domainIntegrate(), dynamicRefineFvMesh::dynamicRefineFvMesh(), removeRegisteredObject::execute(), Foam::MULES::explicitSolve(), blendingFactor::factor(), faceSource::filterField(), localPointRegion::findDuplicateFacePairs(), coordinateSystems::findIndex(), coordinateSystems::findIndices(), refinementSurfaces::findInside(), polyTopoChanger::findModifierID(), coupleGroupIdentifier::findOtherPatchID(), Foam::fvc::flux(), objectRegistry::foundObject(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), gaussConvectionScheme< Type >::fvcDiv(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), GeometricField< vector, pointPatchField, pointMesh >::GeometricField(), globalIndexAndTransform::globalIndexAndTransform(), Foam::fvc::grad(), IOobject::groupName(), polyBoundaryMesh::groupPatchIDs(), thermoSingleLayer::hs(), Foam::MULES::implicitSolve(), injectionModelList::info(), Foam::interpolate(), localMin< Type >::interpolate(), localMax< Type >::interpolate(), surfaceInterpolationScheme< GType >::interpolate(), localBlended< Type >::interpolate(), Foam::fvc::interpolate(), volPointInterpolation::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), IOmapDistribute::IOmapDistribute(), isoSurface::isoSurface(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), objectRegistry::lookupClass(), objectRegistry::lookupObject(), Foam::MULES::LTScorrect(), Foam::mag(), Foam::magSqr(), Foam::makeGraph(), Foam::MapGeometricFields(), mappedFixedValueFvPatchField< Type >::mapper(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), Foam::fvc::meshPhi(), OutputFilterFunctionObject< OutputFilter >::movePoints(), IOdictionary::name(), NamedEnum< directionType, 3 >::names(), cyclicAMIPolyPatch::neighbPatchName(), interpolation< Foam::Vector >::New(), dynamicFvMesh::New(), IOobject::objectPath(), isNotEqOp< T >::operator()(), optionList::operator()(), Foam::operator<<(), patchInjection::patchInjection(), pointConstraints::pointConstraints(), pointMesh::pointMesh(), polyMesh::polyMesh(), Foam::pow(), fvMeshDistribute::printCoupleInfo(), singleStepCombustion< CombThermoType, ThermoType >::R(), laminar< Type >::R(), regIOobject::read(), IOobject::readHeader(), regIOobject::readIfModified(), regIOobject::readStream(), surfMesh::readUpdate(), polyMesh::readUpdate(), Foam::fvc::reconstruct(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), fvFieldReconstructor::reconstructFvVolumeInternalField(), Foam::fvc::reconstructMag(), IOobjectList::remove(), sampledPatchInternalField::sampledPatchInternalField(), mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), searchableSurfaces::searchableSurfaces(), Foam::setRefCell(), removeCells::setRefinement(), removeFaces::setRefinement(), fixedTemperatureConstraint::setValue(), skewCorrected< Type >::skewCorrection(), Foam::fvc::snGrad(), snGradScheme< Type >::snGrad(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), Foam::sqr(), Foam::stabilise(), faceZoneSet::subset(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), surfMesh::surfMesh(), thermoSingleLayer::T(), fvMesh::thisDb(), Foam::transform(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), triSurfaceMesh::triSurfaceMesh(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), OutputFilterFunctionObject< OutputFilter >::updateMesh(), motionSmootherAlgo::updateMesh(), basicThermo::validate(), meshReader::warnDuplicates(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), localBlended< Type >::weights(), PatchPostProcessing< CloudType >::write(), FacePostProcessing< CloudType >::write(), vorticity::write(), Lambda2::write(), Peclet::write(), Q::write(), CourantNo::write(), DESModelRegions::write(), yPlusRAS::write(), blendingFactor::write(), calcMag::write(), calcFvcDiv::write(), calcFvcGrad::write(), yPlusLES::write(), MeshedSurfaceProxy< Face >::write(), writeRegisteredObject::write(), fieldCoordinateSystemTransform::write(), wallShearStress::write(), regionSizeDistribution::write(), pressureTools::write(), addSubtract::writeAddSubtractField(), addSubtract::writeAddSubtractValue(), Foam::writeCellGraph(), components::writeComponentFields(), meshToMeshMethod::writeConnectivity(), boundaryRegion::writeDict(), cellTable::writeDict(), div::writeDivField(), molecule::writeFields(), IOobject::writeHeader(), interpolate::writeInterpolateField(), mag::writeMagField(), magGrad::writeMagGradField(), magSqr::writeMagSqrField(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), Foam::writePatchGraph(), randomise::writeRandomField(), gradScheme< Type >::~gradScheme(), and regIOobject::~regIOobject().
headerClassName()
const word& headerClassName () const inline
Return name of the class name read from header.
Definition at line 258 of file IOobject.H.
Referenced by fieldToCell::applyToSet(), regIOobject::read(), regIOobject::readStream(), addSubtract::writeAddSubtractField(), addSubtract::writeAddSubtractValue(), components::writeComponentFields(), div::writeDivField(), interpolate::writeInterpolateField(), mag::writeMagField(), magGrad::writeMagGradField(), magSqr::writeMagSqrField(), and randomise::writeRandomField().
note() [1/2]
string& note () inline
Return non-constant access to the optional note.
Definition at line 264 of file IOobject.H.
Referenced by regIOobject::read(), meshReader::warnDuplicates(), edgeMeshFormat::write(), boundaryRegion::writeDict(), cellTable::writeDict(), and IOobject::writeHeader().
note() [2/2]
const string& note () const inline
Return the optional note.
Definition at line 270 of file IOobject.H.
rename()
virtual void rename (const word & newName) inline virtual
Rename.
Reimplemented in regIOobject, and objectRegistry.
Definition at line 276 of file IOobject.H.
Referenced by nearWallFields::createFields(), and regIOobject::rename().
registerObject() [1/2]
bool& registerObject () inline
Register object created from this IOobject with registry if true.
Definition at line 282 of file IOobject.H.
Referenced by regIOobject::operator=(), regIOobject::regIOobject(), and regIOobject::rename().
registerObject() [2/2]
bool registerObject () const inline
Register object created from this IOobject with registry if true.
Definition at line 288 of file IOobject.H.
readOpt() [1/2]
readOption readOpt () const inline
Definition at line 296 of file IOobject.H.
Referenced by AverageIOField< Type >::AverageIOField(), regIOobject::checkIn(), CompactIOField< T, BaseType >::CompactIOField(), CompactIOList< face, label >::CompactIOList(), nearWallFields::createFields(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), fvSchemes::fvSchemes(), hexRef8::hexRef8(), IOdictionary::IOdictionary(), IOField< vector >::IOField(), IOList< labelList >::IOList(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), IOPtrList< coordinateSystem >::IOPtrList(), polyTopoChange::makeMesh(), radiationModel::radiationModel(), radiativeIntensityRay::radiativeIntensityRay(), refinementHistory::refinementHistory(), topoSet::topoSet(), and UniformDimensionedField< scalar >::UniformDimensionedField().
readOpt() [2/2]
readOption& readOpt () inline
Definition at line 301 of file IOobject.H.
writeOpt() [1/2]
writeOption writeOpt () const inline
Definition at line 306 of file IOobject.H.
Referenced by cellTable::addCellZones(), polyTopoChanger::addTopologyModifiers(), polyMesh::addZones(), nearWallFields::createFields(), polyMesh::movePoints(), surfMesh::setInstance(), polyMesh::setInstance(), polyTopoChanger::update(), and writeRegisteredObject::write().
writeOpt() [2/2]
writeOption& writeOpt () inline
Definition at line 311 of file IOobject.H.
References IOobject::caseName(), IOobject::group(), and IOobject::rootPath().
group()
Foam::word group () const
Return group (extension part of name)
Definition at line 275 of file IOobject.C.
References word::null.
Referenced by DarcyForchheimer::correct(), IOobject::groupName(), LESModel< BasicTurbulenceModel >::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), and IOobject::writeOpt().
rootPath()
const Foam::fileName & rootPath () const
Definition at line 290 of file IOobject.C.
Referenced by Foam::makeGraph(), and IOobject::writeOpt().
caseName()
const Foam::fileName & caseName () const
Definition at line 269 of file IOobject.C.
References fileName::caseName().
Referenced by Foam::makeGraph(), and IOobject::writeOpt().
instance() [1/2]
const fileName& instance () const inline
Definition at line 326 of file IOobject.H.
Referenced by isoSurface::adaptPatchFields(), autoLayerDriver::addLayers(), Foam::atan2(), autoRefineDriver::autoRefineDriver(), Foam::fvc::average(), Foam::fvc::cellReduce(), Foam::checkMethod(), Foam::cmptAv(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), surfMesh::facesInstance(), polyMesh::facesInstance(), faceCorrectedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), surfaceInterpolationScheme< GType >::interpolate(), volPointInterpolation::interpolate(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), IOobject::local(), Foam::mag(), Foam::magSqr(), Foam::makeGraph(), Foam::MapGeometricFields(), meshRefinement::mergePatchFacesUndo(), polyMesh::movePoints(), reuseTmpDimensionedField< TypeR, Type1, GeoMesh >::New(), reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::New(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), surfMesh::pointsInstance(), polyMesh::pointsInstance(), polyMesh::polyMesh(), Foam::pow(), surfMesh::readUpdate(), polyMesh::readUpdate(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), surfMesh::removeFiles(), polyMesh::removeFiles(), surfMesh::setInstance(), polyMesh::setInstance(), snGradScheme< Type >::snGrad(), Foam::sqr(), Foam::stabilise(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), surfMesh::surfMesh(), Foam::transform(), polyTopoChanger::update(), meshRefinement::write(), IOobject::writeHeader(), regIOobject::writeObject(), and distributedTriSurfaceMesh::writeObject().
instance() [2/2]
fileName& instance () inline
Definition at line 331 of file IOobject.H.
local()
const fileName& local () const inline
Definition at line 336 of file IOobject.H.
References IOobject::instance(), and IOobject::path().
Referenced by surfMesh::surfMesh(), and IOobject::writeHeader().
path() [1/2]
Foam::fileName path () const
Return complete path.
Definition at line 296 of file IOobject.C.
Referenced by searchableSurfaces::checkIntersection(), IOobjectList::IOobjectList(), IOobject::local(), IOobject::objectPath(), Foam::operator<<(), surfMesh::removeFiles(), motionSmootherAlgo::setDisplacementPatchFields(), surfMesh::surfMesh(), Time::writeObject(), and regIOobject::~regIOobject().
path() [2/2]
Foam::fileName path (const word & instance, const fileName & local = "") const
Return complete path with alternative instance and local.
Definition at line 310 of file IOobject.C.
objectPath()
fileName objectPath () const inline
Return complete path + object name.
Definition at line 352 of file IOobject.H.
References IOobject::filePath(), IOobject::headerOk(), IOobject::name(), IOobject::path(), IOobject::readHeader(), IOobject::writeBanner(), IOobject::writeDivider(), IOobject::writeEndDivider(), and IOobject::writeHeader().
Referenced by regIOobject::checkIn(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), hexRef8::consistentSlowRefinement2(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), hexRef8::hexRef8(), IOdictionary::IOdictionary(), mappedFixedValueFvPatchField< Type >::mapper(), meshRefinement::mergePatchFacesUndo(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), polyMesh::polyMesh(), IOdictionary::readData(), regIOobject::readStream(), polyMesh::readUpdate(), hexRef8::setUnrefinement(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), meshReader::warnDuplicates(), boundaryRegion::writeDict(), cellTable::writeDict(), triSurfaceMesh::writeObject(), and distributedTriSurfaceMesh::writeObject().
filePath()
Foam::fileName filePath () const
Return complete path + object name if the file exists.
either in the case/processor or case otherwise null
Definition at line 320 of file IOobject.C.
References Foam::isDir(), Foam::isFile(), Foam::name(), fileName::null, path(), and Foam::system().
Referenced by fieldToCell::applyToSet(), regIOobject::checkIn(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), regIOobject::close(), displacementMotionSolver::displacementMotionSolver(), IOobject::objectPath(), extendedEdgeMeshFormat::read(), and edgeMeshFormat::read().
readHeader()
bool readHeader (Istream & is)
Read header.
Definition at line 31 of file IOobjectReadHeader.C.
References IOobject::BAD, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, IOstream::format(), IOobject::GOOD, IOstream::good(), Foam::Info, IOWarningIn, token::isWord(), IOstream::lineNumber(), dictionary::lookup(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::name(), IOstream::name(), Foam::nl, dictionary::readIfPresent(), SeriousIOErrorIn, IOstream::version(), token::wordToken(), and IOobject::writeHeader().
Referenced by IOobject::objectPath(), extendedEdgeMeshFormat::read(), and edgeMeshFormat::read().
headerOk()
bool headerOk ()
Read and check header info.
Definition at line 421 of file IOobject.C.
References Foam::endl(), Foam::Info, and IOWarningIn.
Referenced by fieldToCell::applyToSet(), addSubtract::calc(), CompactIOField< T, BaseType >::CompactIOField(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), Time::findInstance(), fvSchemes::fvSchemes(), hexRef8::hexRef8(), IOdictionary::IOdictionary(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), IOobjectList::IOobjectList(), IOobject::objectPath(), displacementMotionSolver::points0IO(), Foam::preservePatchTypes(), extendedEdgeMeshFormat::read(), edgeMeshFormat::read(), fieldAverage::readAveragingProperties(), boundaryRegion::readDict(), cellTable::readDict(), refinementHistory::refinementHistory(), topoSet::topoSet(), writeDictionary::tryDirectory(), and uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField().
writeBanner()
Stream & writeBanner (Stream & os, bool noHint = false) inline static
Write the standard OpenFOAM file/dictionary banner.
Optionally without -*- C++ -*- editor hint (eg, for logs)
Definition at line 45 of file IOobjectI.H.
References Foam::FOAMversion.
Referenced by IOobject::objectPath(), argList::parse(), and IOobject::writeHeader().
writeDivider()
Stream & writeDivider (Stream & os) inline static
Write the standard file section divider.
Definition at line 98 of file IOobjectI.H.
Referenced by writeDictionary::execute(), IOobject::objectPath(), argList::parse(), writeDictionary::tryDirectory(), and IOobject::writeHeader().
writeEndDivider()
Stream & writeEndDivider (Stream & os) inline static
Write the standard end file divider.
Definition at line 108 of file IOobjectI.H.
Referenced by IOobject::objectPath(), meshReader::warnDuplicates(), and MeshedSurfaceProxy< Face >::write().
writeHeader() [1/2]
bool writeHeader (Ostream & os) const
Write header.
Definition at line 67 of file IOobjectWriteHeader.C.
References Foam::type().
Referenced by IOobject::objectPath(), IOdictionary::readData(), IOobject::readHeader(), meshReader::warnDuplicates(), edgeMeshFormat::write(), interpolationLookUpTable< scalar >::write(), MeshedSurfaceProxy< Face >::write(), boundaryRegion::writeDict(), and cellTable::writeDict().
writeHeader() [2/2]
bool writeHeader (Ostream & os, const word & objectType) const
Write header. Allow override of type.
Definition at line 35 of file IOobjectWriteHeader.C.
References IOobject::db(), objectRegistry::dbDir(), Foam::endl(), IOstream::format(), IOstream::good(), Foam::Info, IOstream::info(), IOobject::instance(), IOobject::local(), IOobject::name(), Foam::nl, IOobject::note(), IOstream::version(), IOobject::writeBanner(), and IOobject::writeDivider().
good()
bool good () const inline
Definition at line 395 of file IOobject.H.
References IOobject::GOOD.
Referenced by IFstream::IFstream(), IFstream::operator()(), topoSet::topoSet(), and CompactIOField< T, BaseType >::writeObject().
bad()
bool bad () const inline
Definition at line 400 of file IOobject.H.
References IOobject::BAD, IOobject::info(), and IOobject::operator=().
info()
InfoProxy<IOobject> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 410 of file IOobject.H.
Referenced by IOobject::bad(), polyMesh::findCellFacePt(), and IFstream::IFstream().
operator=()
void operator= (const IOobject & io)
Definition at line 481 of file IOobject.C.
Referenced by IOobject::bad(), and regIOobject::operator=().
groupName() [2/2]
Foam::word groupName (Name name, const word & group) inline
Definition at line 31 of file IOobjectI.H.
References IOobject::group(), IOobject::name(), and word::null.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobject/IOobject.H
src/OpenFOAM/db/IOobject/IOobject.C
src/OpenFOAM/db/IOobject/IOobjectI.H
src/OpenFOAM/db/IOobject/IOobjectReadHeader.C
src/OpenFOAM/db/IOobject/IOobjectWriteHeader.C