OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
OutputFilterFunctionObject< OutputFilter > Class Template Reference
A functionObject wrapper around OutputFilter to allow them to be created via the functions entry within controlDict.
Public Member Functions
TypeName (OutputFilter::typeName_())
Runtime type information.
OutputFilterFunctionObject (const word &name, const Time &, const dictionary &)
Construct from components.
virtual const Time & time () const
Return time database.
virtual const dictionary & dict () const
Return the input dictionary.
virtual const word & regionName () const
Return the region name.
virtual const word & dictName () const
Return the optional dictionary name.
virtual bool enabled () const
Return the enabled flag.
virtual const outputFilterOutputControl & outputControl () const
Return the output control object.
virtual const OutputFilter & outputFilter () const
Return the output filter.
virtual void on ()
Switch the function object on.
virtual void off ()
Switch the function object off.
virtual bool start ()
Called at the start of the time-loop.
virtual bool execute (const bool forceWrite)
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
virtual const word & name () const
Name.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
template<class OutputFilter>
class Foam::OutputFilterFunctionObject< OutputFilter >
A functionObject wrapper around OutputFilter to allow them to be created via the functions entry within controlDict.
Note
Since the timeIndex is used directly from Foam::Time, it is unaffected by user-time conversions. For example, Foam::engineTime might cause writeInterval to be degrees crank angle, but the functionObject execution interval would still be in timestep.
Source files
OutputFilterFunctionObject.H
OutputFilterFunctionObject.C
Definition at line 58 of file OutputFilterFunctionObject.H.
Constructor & Destructor Documentation
OutputFilterFunctionObject()
OutputFilterFunctionObject (const word & name, const Time & t, const dictionary & dict)
Construct from components.
Definition at line 98 of file OutputFilterFunctionObject.C.
Member Function Documentation
TypeName()
TypeName (OutputFilter::typeName_())
Runtime type information.
time()
virtual const Time& time () const inline virtual
Return time database.
Definition at line 150 of file OutputFilterFunctionObject.H.
dict()
virtual const dictionary& dict () const inline virtual
Return the input dictionary.
Definition at line 156 of file OutputFilterFunctionObject.H.
regionName()
virtual const word& regionName () const inline virtual
Return the region name.
Definition at line 162 of file OutputFilterFunctionObject.H.
dictName()
virtual const word& dictName () const inline virtual
Return the optional dictionary name.
Definition at line 168 of file OutputFilterFunctionObject.H.
enabled()
virtual bool enabled () const inline virtual
Return the enabled flag.
Definition at line 174 of file OutputFilterFunctionObject.H.
outputControl()
virtual const outputFilterOutputControl& outputControl () const inline virtual
Return the output control object.
Definition at line 180 of file OutputFilterFunctionObject.H.
outputFilter()
virtual const OutputFilter& outputFilter () const inline virtual
Return the output filter.
Definition at line 186 of file OutputFilterFunctionObject.H.
References OutputFilterFunctionObject< OutputFilter >::adjustTimeStep(), OutputFilterFunctionObject< OutputFilter >::end(), OutputFilterFunctionObject< OutputFilter >::execute(), mesh, OutputFilterFunctionObject< OutputFilter >::movePoints(), OutputFilterFunctionObject< OutputFilter >::off(), OutputFilterFunctionObject< OutputFilter >::on(), OutputFilterFunctionObject< OutputFilter >::read(), OutputFilterFunctionObject< OutputFilter >::start(), OutputFilterFunctionObject< OutputFilter >::timeSet(), and OutputFilterFunctionObject< OutputFilter >::updateMesh().
on()
void on () virtual
Switch the function object on.
Definition at line 127 of file OutputFilterFunctionObject.C.
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter().
off()
void off () virtual
Switch the function object off.
Definition at line 134 of file OutputFilterFunctionObject.C.
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter().
start()
bool start () virtual
Called at the start of the time-loop.
Implements functionObject.
Definition at line 141 of file OutputFilterFunctionObject.C.
References OutputFilterFunctionObject< OutputFilter >::execute().
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter().
execute()
bool execute (const bool forceWrite) virtual
Called at each ++ or += of the time-loop.
Implements functionObject.
Definition at line 156 of file OutputFilterFunctionObject.C.
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter(), and OutputFilterFunctionObject< OutputFilter >::start().
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
Reimplemented from functionObject.
Definition at line 188 of file OutputFilterFunctionObject.C.
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter().
timeSet()
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented from functionObject.
Definition at line 215 of file OutputFilterFunctionObject.C.
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter().
adjustTimeStep()
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented from functionObject.
Definition at line 227 of file OutputFilterFunctionObject.C.
References Foam::max(), and OutputFilterFunctionObject< OutputFilter >::read().
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter().
read()
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Implements functionObject.
Definition at line 274 of file OutputFilterFunctionObject.C.
References dict, and OutputFilterFunctionObject< OutputFilter >::updateMesh().
Referenced by OutputFilterFunctionObject< OutputFilter >::adjustTimeStep(), and OutputFilterFunctionObject< OutputFilter >::outputFilter().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Implements functionObject.
Definition at line 294 of file OutputFilterFunctionObject.C.
References mapPolyMesh::mesh(), OutputFilterFunctionObject< OutputFilter >::movePoints(), and IOobject::name().
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter(), and OutputFilterFunctionObject< OutputFilter >::read().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
Implements functionObject.
Definition at line 307 of file OutputFilterFunctionObject.C.
References IOobject::name().
Referenced by OutputFilterFunctionObject< OutputFilter >::outputFilter(), and OutputFilterFunctionObject< OutputFilter >::updateMesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/OutputFilterFunctionObject/OutputFilterFunctionObject.H
src/OpenFOAM/db/functionObjects/OutputFilterFunctionObject/OutputFilterFunctionObject.C