OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObjectList Class Reference
List of function objects with start(), execute() and end() functions that is called for each object.
Public Member Functions
functionObjectList (const Time &, const bool execution=true)
Construct from Time and the execution setting.
functionObjectList (const Time &, const dictionary &parentDict, const bool execution=true)
Construct from Time, a dictionary with "functions" entry.
virtual ~functionObjectList ()
Destructor.
virtual void clear ()
Clear the list of function objects.
virtual label findObjectID (const word &name) const
Find the ID of a given function object by name.
virtual void on ()
Switch the function objects on.
virtual void off ()
Switch the function objects off.
virtual bool status () const
Return the execution status (on/off) of the function objects.
virtual bool start ()
Called at the start of the time-loop.
virtual bool execute (const bool forceWrite=false)
Called at each ++ or += of the time-loop. forceWrite overrides.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read ()
Read and set the function objects if their data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Detailed Description
List of function objects with start(), execute() and end() functions that is called for each object.
See also
Foam::functionObject and Foam::OutputFilterFunctionObject
Source files
functionObjectList.H
functionObjectList.C
Definition at line 57 of file functionObjectList.H.
Constructor & Destructor Documentation
functionObjectList() [1/2]
functionObjectList (const Time & t, const bool execution = true)
Construct from Time and the execution setting.
The functionObject specifications are read from the controlDict
Definition at line 63 of file functionObjectList.C.
functionObjectList() [2/2]
functionObjectList (const Time & t, const dictionary & parentDict, const bool execution = true)
Construct from Time, a dictionary with "functions" entry.
and the execution setting.
Parameters
[in] parentDict - the parent dictionary containing a "functions" entry, which can either be a list or a dictionary of functionObject specifications.
Definition at line 79 of file functionObjectList.C.
~functionObjectList()
~functionObjectList () virtual
Destructor.
Definition at line 97 of file functionObjectList.C.
Member Function Documentation
clear()
void clear () virtual
Clear the list of function objects.
Definition at line 103 of file functionObjectList.C.
References PtrList< T >::clear(), and HashTable< T, Key, Hash >::clear().
findObjectID()
Foam::label findObjectID (const word & name) const virtual
Find the ID of a given function object by name.
Definition at line 112 of file functionObjectList.C.
References forAll, and Foam::name().
on()
void on () virtual
Switch the function objects on.
Definition at line 126 of file functionObjectList.C.
off()
void off () virtual
Switch the function objects off.
Definition at line 132 of file functionObjectList.C.
status()
bool status () const virtual
Return the execution status (on/off) of the function objects.
Definition at line 139 of file functionObjectList.C.
start()
bool start () virtual
Called at the start of the time-loop.
Definition at line 145 of file functionObjectList.C.
References functionObjectList::read().
execute()
bool execute (const bool forceWrite = false) virtual
Called at each ++ or += of the time-loop. forceWrite overrides.
the usual outputControl behaviour and forces writing always (used in postprocessing mode)
Definition at line 151 of file functionObjectList.C.
References functionObject::execute(), forAll, PtrList< functionObject >::operator[](), and functionObjectList::read().
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
Definition at line 172 of file functionObjectList.C.
References functionObject::end(), forAll, PtrList< functionObject >::operator[](), and functionObjectList::read().
timeSet()
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 193 of file functionObjectList.C.
References forAll, PtrList< functionObject >::operator[](), functionObjectList::read(), and functionObject::timeSet().
adjustTimeStep()
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Definition at line 214 of file functionObjectList.C.
References functionObject::adjustTimeStep(), forAll, PtrList< functionObject >::operator[](), and functionObjectList::read().
read()
bool read () virtual
Read and set the function objects if their data have changed.
Definition at line 235 of file functionObjectList.C.
References PtrList< T >::clear(), HashTable< T, Key, Hash >::clear(), dict, entry::dict(), dictionary::digest(), forAllConstIter(), forAllIter, HashTable< T, Key, Hash >::insert(), entry::isDict(), dictionary::lookupEntryPtr(), functionObject::New(), functionObject::read(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), DLListBase::size(), functionObject::start(), entry::stream(), PtrList< T >::transfer(), and HashTable< T, Key, Hash >::transfer().
Referenced by functionObjectList::adjustTimeStep(), functionObjectList::end(), functionObjectList::execute(), Time::readModifiedObjects(), functionObjectList::start(), and functionObjectList::timeSet().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Definition at line 368 of file functionObjectList.C.
References forAll, PtrList< functionObject >::operator[](), and functionObject::updateMesh().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
Definition at line 380 of file functionObjectList.C.
References forAll, functionObject::movePoints(), and PtrList< functionObject >::operator[]().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObjectList/functionObjectList.H
src/OpenFOAM/db/functionObjects/functionObjectList/functionObjectList.C