OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObjectFile Class Reference
Base class for output file data handling.
Public Member Functions
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void writeFileHeader (const label i=0)
File header information.
virtual void write ()
Write function.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Detailed Description
Base class for output file data handling.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
functionObjectFile.H
functionObjectFile.C
Definition at line 57 of file functionObjectFile.H.
Constructor & Destructor Documentation
functionObjectFile() [1/4]
functionObjectFile (const functionObjectFile &) protected
Disallow default bitwise copy construct.
Referenced by functionObjectFile::functionObjectFile(), and functionObjectFile::valueWidth().
functionObjectFile() [2/4]
functionObjectFile (const objectRegistry & obr, const word & prefix)
Construct null.
Definition at line 170 of file functionObjectFile.C.
References functionObjectFile::functionObjectFile().
functionObjectFile() [3/4]
functionObjectFile (const objectRegistry & obr, const word & prefix, const word & name)
Construct from components.
Definition at line 183 of file functionObjectFile.C.
References HashTable< T, Key, Hash >::clear(), functionObjectFile::functionObjectFile(), HashSet< Key, Hash >::insert(), and UPstream::master().
functionObjectFile() [4/4]
functionObjectFile (const objectRegistry & obr, const word & prefix, const wordList & names)
Construct from components.
Definition at line 208 of file functionObjectFile.C.
References HashTable< T, Key, Hash >::clear(), HashSet< Key, Hash >::insert(), UPstream::master(), and HashTable< T, Key, Hash >::size().
~functionObjectFile()
~functionObjectFile () virtual
Destructor.
Definition at line 234 of file functionObjectFile.C.
Member Function Documentation
initStream()
void initStream (Ostream & os) const protected virtual
Initialise the output stream for writing.
Definition at line 38 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::scientific(), IOstream::setf(), and Ostream::width().
Referenced by functionObjectFile::createFiles().
baseFileDir()
Foam::fileName baseFileDir () const protected virtual
Return the base directory for output.
Definition at line 46 of file functionObjectFile.C.
References polyMesh::defaultRegion, mesh, IOobject::name(), functionObjectFile::outputPrefix, UPstream::parRun(), Time::path(), and objectRegistry::time().
Referenced by functionObjectFile::baseTimeDir(), functionObjectFile::createFiles(), and faceSource::writeValues().
baseTimeDir()
Foam::fileName baseTimeDir () const protected virtual
Return the base directory for the current time value.
Definition at line 75 of file functionObjectFile.C.
References functionObjectFile::baseFileDir(), objectRegistry::time(), and Time::timeName().
createFiles()
void createFiles () protected virtual
Create the output file.
Definition at line 81 of file functionObjectFile.C.
References functionObjectFile::baseFileDir(), forAllConstIter(), functionObjectFile::initStream(), UPstream::master(), Foam::mkDir(), Time::startTime(), objectRegistry::time(), Time::timeName(), dimensioned< Type >::value(), and functionObjectFile::writeFileHeader().
Referenced by functionObjectFile::resetName(), functionObjectFile::resetNames(), and functionObjectFile::write().
writeFileHeader()
void writeFileHeader (const label i = 0) protected virtual
File header information.
Reimplemented in faceSource, cellSource, forces, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, cloudInfo, residuals, and DESModelRegions.
Definition at line 119 of file functionObjectFile.C.
Referenced by functionObjectFile::createFiles().
write()
void write () protected virtual
Write function.
Reimplemented in faceSource, forces, cellSource, regionSizeDistribution, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, fieldValue, cloudInfo, residuals, yPlusLES, yPlusRAS, and DESModelRegions.
Definition at line 125 of file functionObjectFile.C.
References functionObjectFile::createFiles().
Referenced by DESModelRegions::execute(), yPlusRAS::execute(), yPlusLES::execute(), wallShearStress::execute(), yPlusRAS::write(), yPlusLES::write(), residuals::write(), cloudInfo::write(), fieldValue::write(), wallShearStress::write(), fieldValueDelta::write(), fieldMinMax::write(), forceCoeffs::write(), and forces::write().
resetNames()
void resetNames (const wordList & names) protected virtual
Reset the list of names from a wordList.
Definition at line 131 of file functionObjectFile.C.
References HashTable< T, Key, Hash >::clear(), functionObjectFile::createFiles(), HashSet< Key, Hash >::insert(), UPstream::master(), and HashTable< T, Key, Hash >::toc().
Referenced by cloudInfo::read().
resetName()
void resetName (const word & name) protected virtual
Reset the list of names to a single name entry.
Definition at line 146 of file functionObjectFile.C.
References HashTable< T, Key, Hash >::clear(), functionObjectFile::createFiles(), HashSet< Key, Hash >::insert(), and UPstream::master().
valueWidth()
Foam::Omanip< int > valueWidth (const label offset = 0) const protected virtual
Return the value width when writing to stream with optional offset.
Definition at line 161 of file functionObjectFile.C.
References functionObjectFile::addChars, IOstream::defaultPrecision(), functionObjectFile::functionObjectFile(), and Foam::setw().
operator=()
void operator= (const functionObjectFile &) protected
Disallow default bitwise assignment.
names()
const Foam::wordHashSet & names () const
Return const access to the names.
Definition at line 240 of file functionObjectFile.C.
file() [1/2]
Foam::OFstream & file ()
Return access to the file (if only 1)
Definition at line 246 of file functionObjectFile.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, UPstream::master(), and WarningIn.
Referenced by cellSource::writeValues(), and faceSource::writeValues().
files()
Foam::PtrList< Foam::OFstream > & files ()
Return access to the files.
Definition at line 273 of file functionObjectFile.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and UPstream::master().
file() [2/2]
Foam::OFstream & file (const label i)
Return file 'i'.
Definition at line 286 of file functionObjectFile.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and UPstream::master().
writeCommented()
void writeCommented (Ostream & os, const string & str) const
Write a commented string to stream.
Definition at line 316 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::setw(), and functionObjectFile::writeTabbed().
Referenced by functionObjectFile::charWidth().
writeTabbed()
void writeTabbed (Ostream & os, const string & str) const
Write a tabbed string to stream.
Definition at line 327 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::setw(), Foam::tab, and functionObjectFile::writeHeader().
Referenced by functionObjectFile::writeCommented().
writeHeader()
void writeHeader (Ostream & os, const string & str) const
Write a commented header to stream.
Definition at line 337 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::nl, Foam::setf(), and Foam::setw().
Referenced by functionObjectFile::writeTabbed().
writeHeaderValue()
void writeHeaderValue (Ostream & os, const string & property, const Type & value) const
Write a (commented) header property and value pair.
Definition at line 32 of file functionObjectFileTemplates.C.
References Foam::nl, Foam::setf(), and Foam::setw().
charWidth()
Foam::label charWidth () const
Return width of character stream output.
Definition at line 309 of file functionObjectFile.C.
References functionObjectFile::addChars, IOstream::defaultPrecision(), and functionObjectFile::writeCommented().
Referenced by functionObjectFile::initStream(), functionObjectFile::writeCommented(), functionObjectFile::writeHeader(), and functionObjectFile::writeTabbed().
Member Data Documentation
outputPrefix
const Foam::word outputPrefix = "postProcessing" static
Directory prefix.
Definition at line 117 of file functionObjectFile.H.
Referenced by functionObjectFile::baseFileDir().
addChars
Foam::label addChars = 7 static
Additional characters for writing.
Definition at line 120 of file functionObjectFile.H.
Referenced by functionObjectFile::charWidth(), and functionObjectFile::valueWidth().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObjectFile/functionObjectFile.H
src/OpenFOAM/db/functionObjects/functionObjectFile/functionObjectFile.C
src/OpenFOAM/db/functionObjects/functionObjectFile/functionObjectFileTemplates.C