OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObject Class Reference abstract
Abstract base-class for Time/database function objects.
Classes
class iNew
Return a pointer to a new functionObject created on freestore.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
virtual const word & name () const
Name.
virtual bool start ()=0
Called at the start of the time-loop.
virtual bool execute (const bool forceWrite)=0
Called at each ++ or += of the time-loop. forceWrite overrides the.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)=0
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)=0
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)=0
Update for changes of mesh.
Static Public Member Functions
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes
static int debug
Detailed Description
Abstract base-class for Time/database function objects.
See also
Foam::OutputFilterFunctionObject
Source files
functionObject.H
functionObject.C
Definition at line 58 of file functionObject.H.
Constructor & Destructor Documentation
functionObject()
functionObject (const word & name)
Construct from components.
Definition at line 42 of file functionObject.C.
References functionObject::New().
~functionObject()
~functionObject () virtual
Destructor.
Definition at line 105 of file functionObject.C.
Referenced by functionObject::iNew::iNew().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , functionObject , dictionary , (const word &name, const Time &t, const dictionary &dict) , (name, t, dict))
clone()
autoPtr<functionObject> clone () const inline
Return clone.
Definition at line 101 of file functionObject.H.
References notImplemented.
New()
Foam::autoPtr< Foam::functionObject > New (const word & name, const Time & t, const dictionary & functionDict) static
Select from dictionary, based on its "type" entry.
Definition at line 51 of file functionObject.C.
References functionObject::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), functionObject::name(), and Foam::nl.
Referenced by functionObject::functionObject(), functionObject::iNew::iNew(), functionObject::iNew::operator()(), functionObjectList::read(), and codedFunctionObject::redirectFunctionObject().
name()
const Foam::word & name () const virtual
Name.
Definition at line 111 of file functionObject.C.
Referenced by functionObject::iNew::iNew(), and functionObject::New().
start()
virtual bool start () pure virtual
Called at the start of the time-loop.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::iNew::iNew(), and functionObjectList::read().
execute()
virtual bool execute (const bool forceWrite) pure virtual
Called at each ++ or += of the time-loop. forceWrite overrides the.
outputControl behaviour.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::end(), functionObjectList::execute(), and functionObject::iNew::iNew().
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
By default it simply calls execute().
Reimplemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Definition at line 117 of file functionObject.C.
References functionObject::execute().
Referenced by functionObjectList::end(), and functionObject::iNew::iNew().
timeSet()
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Definition at line 123 of file functionObject.C.
Referenced by functionObject::iNew::iNew(), and functionObjectList::timeSet().
adjustTimeStep()
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented in OutputFilterFunctionObject< OutputFilter >, and setTimeStepFunctionObject.
Definition at line 129 of file functionObject.C.
Referenced by functionObjectList::adjustTimeStep(), and functionObject::iNew::iNew().
read()
virtual bool read (const dictionary &) pure virtual
Read and set the function object if its data have changed.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::iNew::iNew(), and functionObjectList::read().
updateMesh()
virtual void updateMesh (const mapPolyMesh & mpm) pure virtual
Update for changes of mesh.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::iNew::iNew(), and functionObjectList::updateMesh().
movePoints()
virtual void movePoints (const polyMesh & mesh) pure virtual
Update for changes of mesh.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::iNew::iNew(), and functionObjectList::movePoints().
Member Data Documentation
debug
int debug static
Definition at line 80 of file functionObject.H.
Referenced by functionObject::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObject/functionObject.H
src/OpenFOAM/db/functionObjects/functionObject/functionObject.C