OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObject::iNew Class Reference
Return a pointer to a new functionObject created on freestore.
Public Member Functions
iNew (const Time &t)
autoPtr< functionObject > operator() (const word &name, Istream &is) const
Detailed Description
Return a pointer to a new functionObject created on freestore.
from Istream
Definition at line 109 of file functionObject.H.
Constructor & Destructor Documentation
iNew()
iNew (const Time & t) inline
Definition at line 115 of file functionObject.H.
References functionObject::adjustTimeStep(), functionObject::end(), functionObject::execute(), mesh, functionObject::movePoints(), functionObject::name(), functionObject::New(), functionObject::read(), functionObject::start(), functionObject::timeSet(), functionObject::updateMesh(), and functionObject::~functionObject().
Member Function Documentation
operator()()
Foam::autoPtr< Foam::functionObject > operator() (const word & name, Istream & is) const
Definition at line 136 of file functionObject.C.
References dict, and functionObject::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObject/functionObject.H
src/OpenFOAM/db/functionObjects/functionObject/functionObject.C