OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UPstream::commsStruct Class Reference
Structure for communicating between processors.
Public Member Functions
commsStruct ()
Construct null.
commsStruct (const label, const labelList &, const labelList &, const labelList &)
Construct from components.
commsStruct (const label nProcs, const label myProcID, const label, const labelList &, const labelList &)
Construct from components; construct allNotBelow_.
label above () const
const labelList & below () const
const labelList & allBelow () const
const labelList & allNotBelow () const
bool operator== (const commsStruct &) const
bool operator!= (const commsStruct &) const
Friends
Ostream & operator<< (Ostream &, const commsStruct &)
Detailed Description
Structure for communicating between processors.
Definition at line 76 of file UPstream.H.
Constructor & Destructor Documentation
commsStruct() [1/3]
commsStruct ()
Construct null.
Definition at line 31 of file UPstreamCommsStruct.C.
Referenced by UPstream::commsStruct::commsStruct().
commsStruct() [2/3]
commsStruct (const label above, const labelList & below, const labelList & allBelow, const labelList & allNotBelow)
Construct from components.
Definition at line 41 of file UPstreamCommsStruct.C.
References UPstream::commsStruct::commsStruct().
commsStruct() [3/3]
commsStruct (const label nProcs, const label myProcID, const label above, const labelList & below, const labelList & allBelow)
Construct from components; construct allNotBelow_.
Definition at line 56 of file UPstreamCommsStruct.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, and List< T >::size().
Member Function Documentation
above()
label above () const inline
Definition at line 125 of file UPstream.H.
Referenced by Pstream::combineGather(), Pstream::combineScatter(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), UPstream::commsStruct::operator==(), regIOobject::read(), Pstream::scatter(), and Pstream::scatterList().
below()
const labelList& below () const inline
Definition at line 130 of file UPstream.H.
Referenced by Pstream::combineGather(), Pstream::combineScatter(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), UPstream::commsStruct::operator==(), regIOobject::read(), Pstream::scatter(), and Pstream::scatterList().
allBelow()
const labelList& allBelow () const inline
Definition at line 135 of file UPstream.H.
Referenced by Pstream::gatherList(), and UPstream::commsStruct::operator==().
allNotBelow()
const labelList& allNotBelow () const inline
Definition at line 140 of file UPstream.H.
References UPstream::commsStruct::operator!=(), UPstream::commsStruct::operator<<, and UPstream::commsStruct::operator==().
Referenced by UPstream::commsStruct::operator==(), and Pstream::scatterList().
operator==()
bool operator== (const commsStruct & comm) const
Definition at line 93 of file UPstreamCommsStruct.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::allBelow(), UPstream::commsStruct::allNotBelow(), and UPstream::commsStruct::below().
Referenced by UPstream::commsStruct::allNotBelow(), and UPstream::commsStruct::operator!=().
operator!=()
bool operator!= (const commsStruct & comm) const
Definition at line 105 of file UPstreamCommsStruct.C.
References UPstream::commsStruct::operator==().
Referenced by UPstream::commsStruct::allNotBelow().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const commsStruct &) friend
Referenced by UPstream::commsStruct::allNotBelow(), and UPstream::commsType().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstreamCommsStruct.C