OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Istream Class Reference abstract
An Istream is an abstract base class for all input systems (streams, files, token lists etc). The basic operations are construct, close, read token, read primitive and read binary block.
Public Member Functions
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Istream ()
Destructor.
void putBack (const token &)
Put back token.
bool getBack (token &)
Get the put back token if there is one and return true.
bool peekBack (token &)
Peek at the put back token without removing it.
virtual Istream & read (token &)=0
Return next token from stream.
virtual Istream & read (char &)=0
Read a character.
virtual Istream & read (word &)=0
Read a word.
virtual Istream & read (string &)=0
virtual Istream & read (label &)=0
Read a label.
virtual Istream & read (floatScalar &)=0
Read a floatScalar.
virtual Istream & read (doubleScalar &)=0
Read a doubleScalar.
virtual Istream & read (char *, std::streamsize)=0
Read binary block.
virtual Istream & rewind ()=0
Rewind and return the stream so that it may be read again.
Istream & readBegin (const char *funcName)
Istream & readEnd (const char *funcName)
Istream & readEndBegin (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
virtual ios ::fmtflags flags () const =0
Return flags of stream.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios ::fmtflags flags (const ios ::fmtflags f)=0
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f)
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f, const ios ::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios ::fmtflags uf)
Unset flags of stream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios ::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from IOstream
label lineNumber_
Detailed Description
An Istream is an abstract base class for all input systems (streams, files, token lists etc). The basic operations are construct, close, read token, read primitive and read binary block.
In addition, version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
Istream.H
Istream.C
Definition at line 57 of file Istream.H.
Constructor & Destructor Documentation
Istream()
Istream (streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Set stream status.
Definition at line 76 of file Istream.H.
~Istream()
virtual ~Istream () inline virtual
Destructor.
Definition at line 88 of file Istream.H.
References Istream::getBack(), Istream::operator()(), Istream::peekBack(), Istream::putBack(), Istream::read(), Istream::readBegin(), Istream::readBeginList(), Istream::readEnd(), Istream::readEndBegin(), Istream::readEndList(), and Istream::rewind().
Member Function Documentation
putBack()
void putBack (const token & t)
Put back token.
Only a single put back is permitted
Definition at line 30 of file Istream.C.
References IOstream::bad(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorIn.
Referenced by blockDescriptor::blockDescriptor(), BSplineEdge::BSplineEdge(), dimensioned< vector >::dimensioned(), Field< Foam::Vector2D >::Field(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), genericFvPatchField< Type >::genericFvPatchField(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), entry::New(), dimensioned< vector >::operator/=(), Foam::operator>>(), StaticHashTable< T, Key, Hash >::printInfo(), PtrList< MRFZone >::read(), dimensionSet::read(), PackedList< 2 >::read(), dictionary::read(), IOPosition< CloudType >::readData(), mappedPatchBase::readListOrField(), Reaction< ReactionThermo >::setLRhs(), splineEdge::splineEdge(), UList< Foam::wordRe >::writeEntry(), and Istream::~Istream().
getBack()
bool getBack (token & t)
Get the put back token if there is one and return true.
Return false if no put back token is available.
Definition at line 52 of file Istream.C.
References IOstream::bad(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorIn.
Referenced by ISstream::read(), UIPstream::read(), ITstream::read(), and Istream::~Istream().
peekBack()
bool peekBack (token & t)
Peek at the put back token without removing it.
Returns false if no put back token is available and set the token to undefined.
Definition at line 71 of file Istream.C.
References token::undefinedToken.
Referenced by Istream::~Istream().
read() [1/8]
virtual Istream& read (token &) pure virtual
Return next token from stream.
Implemented in ITstream, UIPstream, and ISstream.
Referenced by CollidingParcel< ParcelType >::CollidingParcel(), DsmcParcel< ParcelType >::DsmcParcel(), directionInfo::edgeToFaceIndex(), findCellParticle::findCellParticle(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), KinematicParcel< ParcelType >::KinematicParcel(), List< functionObject *>::List(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), molecule::molecule(), MPPICParcel< ParcelType >::MPPICParcel(), Foam::operator>>(), particle< Type >::particle(), ReactingParcel< ParcelType >::ReactingParcel(), primitiveEntry::read(), dimensioned< vector >::read(), PackedList< 2 >::read(), Foam::readChar(), Foam::readLongLong(), labelledTri::region(), solidParticle::solidParticle(), SprayParcel< ParcelType >::SprayParcel(), ThermoParcel< ParcelType >::ThermoParcel(), token::token(), trackedParticle::trackedParticle(), wallBoundedParticle::wallBoundedParticle(), UList< Foam::wordRe >::writeEntry(), and Istream::~Istream().
read() [2/8]
virtual Istream& read (char &) pure virtual
Read a character.
Implemented in ITstream, UIPstream, and ISstream.
read() [3/8]
virtual Istream& read (word &) pure virtual
Read a word.
Implemented in ITstream, UIPstream, and ISstream.
read() [4/8]
virtual Istream& read (string &) pure virtual
Implemented in ITstream, ISstream, and UIPstream.
read() [5/8]
virtual Istream& read (label &) pure virtual
Read a label.
Implemented in ITstream, ISstream, and UIPstream.
read() [6/8]
virtual Istream& read (floatScalar &) pure virtual
Read a floatScalar.
Implemented in ITstream, ISstream, and UIPstream.
read() [7/8]
virtual Istream& read (doubleScalar &) pure virtual
Read a doubleScalar.
Implemented in ITstream, ISstream, and UIPstream.
read() [8/8]
virtual Istream& read (char * , std::streamsize) pure virtual
Read binary block.
Implemented in ITstream, ISstream, and UIPstream.
rewind()
virtual Istream& rewind () pure virtual
Rewind and return the stream so that it may be read again.
Implemented in ITstream, ISstream, and UIPstream.
Referenced by gaussConvectionScheme< Type >::gaussConvectionScheme(), and Istream::~Istream().
readBegin()
Foam::Istream & readBegin (const char * funcName)
Definition at line 88 of file Istream.C.
References token::BEGIN_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, token::info(), and IOstream::setBad().
Referenced by Keyed< T >::createList(), LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate(), line< Point, PointRef >::nearestDist(), triangle< Point, PointRef >::nearestPoint(), objectMap::objectMap(), Foam::operator>>(), ISstream::read(), Istream::readEndBegin(), labelledTri::region(), PackedList< 2 >::setPair(), tetrahedron< Point, PointRef >::sliceWithPlane(), memInfo::valid(), VectorSpace< Vector< vector >, vector, 3 >::VectorSpace(), and Istream::~Istream().
readEnd()
Foam::Istream & readEnd (const char * funcName)
Definition at line 105 of file Istream.C.
References token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, token::info(), and IOstream::setBad().
Referenced by ArrheniusReactionRate::ArrheniusReactionRate(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::ChemicallyActivatedReactionRate(), Keyed< T >::createList(), FallOffReactionRate< ReactionRate, FallOffFunction >::FallOffReactionRate(), JanevReactionRate::JanevReactionRate(), LandauTellerReactionRate::LandauTellerReactionRate(), LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate(), line< Point, PointRef >::nearestDist(), objectMap::objectMap(), Foam::operator>>(), powerSeriesReactionRate::powerSeriesReactionRate(), ISstream::read(), Istream::readEndBegin(), labelledTri::region(), PackedList< 2 >::setPair(), SRIFallOffFunction::SRIFallOffFunction(), thirdBodyArrheniusReactionRate::thirdBodyArrheniusReactionRate(), TroeFallOffFunction::TroeFallOffFunction(), memInfo::valid(), VectorSpace< Vector< vector >, vector, 3 >::VectorSpace(), and Istream::~Istream().
readEndBegin()
Foam::Istream & readEndBegin (const char * funcName)
Definition at line 122 of file Istream.C.
References Istream::readBegin(), and Istream::readEnd().
Referenced by Istream::~Istream().
readBeginList()
char readBeginList (const char * funcName)
Definition at line 131 of file Istream.C.
References token::BEGIN_BLOCK, token::BEGIN_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, token::info(), token::pToken(), and IOstream::setBad().
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), StaticHashTable< T, Key, Hash >::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), IOPosition< CloudType >::readData(), thirdBodyEfficiencies::thirdBodyEfficiencies(), UList< Foam::wordRe >::writeEntry(), and Istream::~Istream().
readEndList()
char readEndList (const char * funcName)
Definition at line 152 of file Istream.C.
References token::END_BLOCK, token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, token::info(), token::pToken(), and IOstream::setBad().
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), StaticHashTable< T, Key, Hash >::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), IOPosition< CloudType >::readData(), UList< Foam::wordRe >::writeEntry(), and Istream::~Istream().
operator()()
Foam::Istream & operator() () const
Return a non-const reference to const Istream.
Needed for read-constructors where the stream argument is temporary: e.g. thing thisThing(IFstream("thingFileName")());
Definition at line 173 of file Istream.C.
References IOstream::check(), IOerror::exit(), Foam::FatalIOError, and IOstream::good().
Referenced by Istream::~Istream().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/Istream.H
src/OpenFOAM/db/IOstreams/IOstreams/Istream.C