OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UPstream Class Reference
Inter-processor communications stream.
Classes
class commsStruct
Structure for communicating between processors.
class communicator
Helper class for allocating/freeing communicators.
class listEq
combineReduce operator for lists. Used for counting.
Public Types
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Public Member Functions
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Static Public Member Functions
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor.
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number.
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library.
static bool init (int &argc, char **&argv)
Initialisation function called from main.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static int masterNo ()
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (int communicator)
Process ID of given process index.
static int firstSlave ()
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
Static Public Attributes
static const NamedEnum< commsTypes, 3 > commsTypeNames
static bool floatTransfer
Should compact transfer be used in which floats replace doubles.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Protected Attributes
commsTypes commsType_
Communications type of this stream.
Detailed Description
Inter-processor communications stream.
Source files
UPstream.H
UPstream.C
UPstreamCommsStruct.C
gatherScatter.C
combineGatherScatter.C
gatherScatterList.C
Definition at line 58 of file UPstream.H.
Member Enumeration Documentation
commsTypes
enum commsTypes
Types of communications.
Enumerator
blocking
scheduled
nonBlocking
Definition at line 64 of file UPstream.H.
Constructor & Destructor Documentation
UPstream()
UPstream (const commsTypes commsType) inline
Construct given optional buffer size.
Definition at line 270 of file UPstream.H.
References UPstream::allocateCommunicator(), UPstream::freeCommunicator(), UPstream::freeCommunicators(), and UPstream::parent().
Member Function Documentation
ClassName()
ClassName ("UPstream")
allocateCommunicator()
Foam::label allocateCommunicator (const label parent, const labelList & subRanks, const bool doPstream = true) static
Allocate a new communicator.
Definition at line 228 of file UPstream.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, UPstream::freeCommunicator(), Foam::Pout, and List< T >::size().
Referenced by masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), NamedEnum< directionType, 3 >::names(), and UPstream::UPstream().
freeCommunicator()
void freeCommunicator (const label communicator, const bool doPstream = true) static
Free a previously allocated communicator.
Definition at line 297 of file UPstream.C.
References Foam::endl(), and Foam::Pout.
Referenced by UPstream::allocateCommunicator(), UPstream::UPstream(), UPstream::communicator::~communicator(), eagerGAMGProcAgglomeration::~eagerGAMGProcAgglomeration(), manualGAMGProcAgglomeration::~manualGAMGProcAgglomeration(), masterCoarsestGAMGProcAgglomeration::~masterCoarsestGAMGProcAgglomeration(), and procFacesGAMGProcAgglomeration::~procFacesGAMGProcAgglomeration().
freeCommunicators()
void freeCommunicators (const bool doPstream) static
Free all communicators.
Definition at line 324 of file UPstream.C.
References forAll.
Referenced by UPstream::UPstream().
baseProcNo()
int baseProcNo (const label myComm, const int procID) static
Return physical processor number (i.e. processor number in.
worldComm) given communicator and procssor
Definition at line 336 of file UPstream.C.
References UPstream::parent(), and UPstream::procID().
Referenced by UPstream::communicator::operator label(), and UPstream::procNo().
procNo() [1/2]
Foam::label procNo (const label comm, const int baseProcID) static
Return processor number in communicator (given physical processor.
number) (= reverse of baseProcNo)
Definition at line 352 of file UPstream.C.
References Foam::findIndex().
Referenced by UPstream::communicator::operator label().
procNo() [2/2]
Foam::label procNo (const label myComm, const label currentComm, const int currentProcID) static
Return processor number in communicator (given processor number.
and communicator)
Definition at line 370 of file UPstream.C.
References UPstream::baseProcNo(), UPstream::defaultCommsType, UPstream::floatTransfer, dictionary::lookup(), UPstream::nProcsSimpleSum, Foam::debug::optimisationSwitch(), Foam::debug::optimisationSwitches(), Foam::registerOptSwitchWithName(), and serialComm.
addValidParOptions()
void addValidParOptions (HashTable< string > & validParOptions) static
Add the valid option this type of communications library.
adds/requires on the command line
Definition at line 31 of file UPstream.C.
Referenced by UPstream::communicator::operator label().
init()
bool init (int & argc, char **& argv) static
Initialisation function called from main.
Spawns slave processes and initialises inter-communication
Definition at line 35 of file UPstream.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, and Foam::nl.
Referenced by UPstream::communicator::operator label(), and ParRunControl::runPar().
nRequests()
Foam::label nRequests () static
Get number of outstanding requests.
Definition at line 96 of file UPstream.C.
Referenced by mapDistribute::compact(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::evaluate(), Pstream::exchange(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), UPstream::communicator::operator label(), processorFvPatchField< Type >::updateInterfaceMatrix(), and processorGAMGInterfaceField::updateInterfaceMatrix().
resetRequests()
void resetRequests (const label sz) static
Truncate number of outstanding requests.
Definition at line 102 of file UPstream.C.
Referenced by UPstream::communicator::operator label().
waitRequests()
void waitRequests (const label start = 0) static
Wait until all requests (from start onwards) have finished.
Definition at line 106 of file UPstream.C.
Referenced by mapDistribute::compact(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::evaluate(), Pstream::exchange(), GAMGProcAgglomeration::globalCellCells(), and UPstream::communicator::operator label().
waitRequest()
void waitRequest (const label i) static
Wait until request i has finished.
Definition at line 110 of file UPstream.C.
Referenced by UPstream::communicator::operator label(), processorFvPatchField< Type >::updateInterfaceMatrix(), and processorGAMGInterfaceField::updateInterfaceMatrix().
finishedRequest()
bool finishedRequest (const label i) static
Non-blocking comms: has request i finished?
Definition at line 114 of file UPstream.C.
References notImplemented.
Referenced by UPstream::communicator::operator label().
allocateTag() [1/2]
int allocateTag (const char * s) static
Definition at line 567 of file UPstream.C.
References Foam::endl(), Foam::PstreamGlobals::freedTags_, Foam::PstreamGlobals::nTags_, Foam::Pout, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove().
Referenced by UPstream::communicator::operator label().
allocateTag() [2/2]
int allocateTag (const word & s) static
Definition at line 596 of file UPstream.C.
References Foam::endl(), Foam::PstreamGlobals::freedTags_, Foam::PstreamGlobals::nTags_, Foam::Pout, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove().
freeTag() [1/2]
void freeTag (const char * s, const int tag) static
Definition at line 625 of file UPstream.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::PstreamGlobals::freedTags_, and Foam::Pout.
Referenced by UPstream::communicator::operator label().
freeTag() [2/2]
void freeTag (const word & s, const int tag) static
Definition at line 641 of file UPstream.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::PstreamGlobals::freedTags_, and Foam::Pout.
parRun()
static bool& parRun () inline static
Is this a parallel run?
Definition at line 380 of file UPstream.H.
Referenced by error::abort(), IOerror::abort(), autoLayerDriver::addLayers(), meshRefinement::balance(), functionObjectFile::baseFileDir(), boundBox::boundBox(), processorCyclicPolyPatch::calcGeometry(), processorPolyPatch::calcGeometry(), FaceCellWave< Type, TrackingData >::cellToFace(), polyBoundaryMesh::checkParallelSync(), CloudFunctionObject< CloudType >::CloudFunctionObject(), mapDistribute::compact(), processorFvPatch::coupled(), processorPointPatchField< Type >::coupled(), processorCyclicPointPatchField< Type >::coupled(), processorFvsPatchField< Type >::coupled(), processorCyclicFvsPatchField< Type >::coupled(), cyclicAMIFvPatch::coupled(), cyclicACMIFvPatch::coupled(), processorFvPatchField< Type >::coupled(), processorPolyPatch::coupled(), simpleGeomDecomp::decompose(), decompositionMethod::decompose(), conformalVoronoiMesh::decomposition(), processorFvPatch::delta(), fvMeshDistribute::distribute(), refinementHistory::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), autoLayerDriver::doLayers(), autoRefineDriver::doRefine(), PointEdgeWave< Type, TrackingData >::edgeToPoint(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::evaluate(), error::exit(), IOerror::exit(), sampledSurfaces::expire(), polyMesh::findCell(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), GAMGProcAgglomeration::globalCellCells(), InflationInjection< CloudType >::InflationInjection(), processorPolyPatch::initGeometry(), processorPolyPatch::initOrder(), processorPolyPatch::initUpdateMesh(), PointEdgeWave< Type, TrackingData >::iterate(), FaceCellWave< Type, TrackingData >::iterate(), LUscalarMatrix::LUscalarMatrix(), processorFvPatch::makeWeights(), NamedEnum< directionType, 3 >::names(), polyBoundaryMesh::neighbourEdges(), decompositionMethod::New(), minEqOp< labelPair >::operator()(), messageStream::operator()(), processorPolyPatch::order(), InflationInjection< CloudType >::parcelsToInject(), probes::prepare(), sampledSurfaces::read(), regIOobject::read(), Time::readModifiedObjects(), structuredRenumber::renumber(), sampledSets::sampledSets(), sampledSurfaces::sampledSurfaces(), Time::setControls(), fvMeshSubset::setLargeCellSubset(), LUscalarMatrix::solve(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), sampledSurfaces::update(), processorPolyPatch::updateMesh(), streamLine::write(), wallBoundedStreamLine::write(), meshToMeshMethod::writeConnectivity(), and fieldMinMax::writeFileHeader().
nProcs()
static label nProcs (const label communicator = 0) inline static
Number of processes in parallel run.
Definition at line 386 of file UPstream.H.
References List< T >::size().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), meshRefinement::balanceAndRefine(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), Pstream::combineGather(), Foam::combineReduce(), Pstream::combineScatter(), mapDistribute::compact(), fvMeshDistribute::countCells(), simpleGeomDecomp::decompose(), fvMeshDistribute::distribute(), refinementHistory::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), Pstream::exchange(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), distributedTriSurfaceMesh::findNearest(), Pstream::gather(), Pstream::gatherList(), globalIndex::globalIndex(), UPstream::lastSlave(), Pstream::listCombineGather(), Pstream::listCombineScatter(), LUscalarMatrix::LUscalarMatrix(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), mapDistribute::mapDistribute(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), UPstream::listEq::operator()(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), fvMeshDistribute::printCoupleInfo(), mapDistribute::printLayout(), regIOobject::read(), mapDistribute::receive(), Foam::reduce(), meshRefinement::refineAndBalance(), meshRefinement::refineCandidates(), Foam::returnReduce(), Pstream::scatter(), Pstream::scatterList(), mapDistribute::schedule(), mapDistribute::send(), Time::setControls(), fvMeshSubset::setLargeCellSubset(), ParSortableList< Type >::sort(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), streamLine::write(), and wallBoundedStreamLine::write().
masterNo()
static int masterNo () inline static
Process index of the master.
Definition at line 392 of file UPstream.H.
Referenced by simpleGeomDecomp::decompose(), LUscalarMatrix::LUscalarMatrix(), UPstream::master(), minEqOp< labelPair >::operator()(), argList::parse(), mapDistribute::schedule(), globalMeshData::sharedPoints(), LUscalarMatrix::solve(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
master()
static bool master (const label communicator = 0) inline static
Am I the master process.
Definition at line 398 of file UPstream.H.
References UPstream::masterNo().
Referenced by effectivenessHeatExchangerSource::addSup(), mappedPatchBase::calcMapping(), wallShearStress::calcShearStress(), viewFactor::calculate(), argList::check(), polyBoundaryMesh::checkParallelSync(), argList::checkRootCase(), fieldValue::combineFields(), commSchedule::commSchedule(), functionObjectFile::createFiles(), simpleGeomDecomp::decompose(), DESModelRegions::execute(), functionObjectFile::file(), functionObjectFile::files(), probes::findElements(), functionObjectFile::functionObjectFile(), cachedRandom::globalPosition(), cachedRandom::globalRandomise01(), cachedRandom::globalSample01(), IOdictionary::IOdictionary(), JobInfo::JobInfo(), LUscalarMatrix::LUscalarMatrix(), messageStream::masterStream(), NamedEnum< directionType, 3 >::names(), isNotEqOp< T >::operator()(), ListPlusEqOp< T, Size >::operator()(), minEqOp< labelPair >::operator()(), messageStream::operator()(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), porosityModel::porosityModel(), probes::prepare(), sampledSurfaces::read(), regIOobject::read(), sampledSets::read(), IOdictionary::readData(), functionObjectFile::resetName(), functionObjectFile::resetNames(), mapDistribute::schedule(), patchInjectionBase::setPositionAndCell(), globalMeshData::sharedPoints(), JobInfo::signalEnd(), LUscalarMatrix::solve(), ParSortableList< Type >::sort(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), sampledSurfaces::update(), sixDoFRigidBodyMotion::updateAcceleration(), sixDoFRigidBodyMotion::updatePosition(), fileMonitor::updateStates(), solution::upgradeSolverDict(), JobInfo::write(), residuals::write(), cloudInfo::write(), fieldValueDelta::write(), sampledSurfaces::write(), forceCoeffs::write(), sampledSets::write(), streamLine::write(), regionSizeDistribution::write(), wallBoundedStreamLine::write(), cellSource::write(), forces::write(), faceSource::write(), residuals::writeFileHeader(), cellSource::writeValues(), faceSource::writeValues(), and JobInfo::~JobInfo().
myProcNo()
static int myProcNo (const label communicator = 0) inline static
Number of this process (starting from masterNo() = 0)
Definition at line 404 of file UPstream.H.
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), GAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), viewFactor::calculate(), GAMGAgglomeration::calculateRegionMaster(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), Pstream::combineGather(), Pstream::combineScatter(), mapDistribute::compact(), noDecomp::decompose(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), globalIndexAndTransform::encode(), Pstream::exchange(), processorField::execute(), InjectionModel< CloudType >::findCellAtPosition(), patchProbes::findElements(), probes::findElements(), distributedTriSurfaceMesh::findNearest(), mappedPatchBase::findSamples(), Pstream::gather(), lduPrimitiveMesh::gather(), Pstream::gatherList(), GAMGProcAgglomeration::globalCellCells(), globalIndex::globalIndex(), globalIndex::isLocal(), lduPrimitiveMesh::lduPrimitiveMesh(), Pstream::listCombineGather(), Pstream::listCombineScatter(), globalIndex::localSize(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), mapDistribute::mapDistribute(), conformalVoronoiMesh::maxSurfaceProtrusion(), meshRefinement::mergeBaffles(), NamedEnum< directionType, 3 >::names(), regionSplit::nLocalRegions(), ListPlusEqOp< T, Size >::operator()(), minEqOp< labelPair >::operator()(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), UOPstream::print(), fvMeshDistribute::printCoupleInfo(), mapDistribute::printLayout(), backgroundMeshDecomposition::procBounds(), regIOobject::read(), indexedVertex< Gt, Vb >::referred(), Pstream::scatter(), Pstream::scatterList(), mapDistribute::schedule(), Time::setControls(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::setPositionAndCell(), ParSortableList< Type >::sort(), ThermoSurfaceFilm< CloudType >::splashInteraction(), refinementHistory::subset(), globalIndex::toGlobal(), globalIndex::toLocal(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), patchInjectionBase::updateMesh(), meshToMeshMethod::writeConnectivity(), and extendedCellToFaceStencil::writeStencilStats().
parent()
static label parent (const label communicator) inline static
Definition at line 409 of file UPstream.H.
Referenced by UPstream::baseProcNo(), and UPstream::UPstream().
procID()
static List<int>& procID (int communicator) inline static
Process ID of given process index.
Definition at line 415 of file UPstream.H.
Referenced by UPstream::baseProcNo(), and UPstream::listEq::operator()().
firstSlave()
static int firstSlave () inline static
Process index of first slave.
Definition at line 421 of file UPstream.H.
Referenced by LUscalarMatrix::LUscalarMatrix(), minEqOp< labelPair >::operator()(), argList::parse(), mapDistribute::schedule(), globalMeshData::sharedPoints(), LUscalarMatrix::solve(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
lastSlave()
static int lastSlave (const label communicator = 0) inline static
Process index of last slave.
Definition at line 427 of file UPstream.H.
References UPstream::linearCommunication(), and UPstream::nProcs().
Referenced by LUscalarMatrix::LUscalarMatrix(), minEqOp< labelPair >::operator()(), argList::parse(), mapDistribute::schedule(), globalMeshData::sharedPoints(), LUscalarMatrix::solve(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
linearCommunication()
static const List<commsStruct>& linearCommunication (const label communicator = 0) inline static
Communication schedule for linear all-to-master (proc 0)
Definition at line 434 of file UPstream.H.
References UPstream::treeCommunication().
Referenced by Pstream::combineGather(), Foam::combineReduce(), Pstream::combineScatter(), Pstream::gather(), Pstream::gatherList(), UPstream::lastSlave(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), regIOobject::read(), Foam::reduce(), Foam::returnReduce(), Pstream::scatter(), and Pstream::scatterList().
treeCommunication()
static const List<commsStruct>& treeCommunication (const label communicator = 0) inline static
Communication schedule for tree all-to-master (proc 0)
Definition at line 443 of file UPstream.H.
Referenced by Pstream::combineGather(), Foam::combineReduce(), Pstream::combineScatter(), Pstream::gather(), Pstream::gatherList(), UPstream::linearCommunication(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), regIOobject::read(), Foam::reduce(), Foam::returnReduce(), Pstream::scatter(), and Pstream::scatterList().
msgType()
static int& msgType () inline static
Message tag of standard messages.
Definition at line 451 of file UPstream.H.
Referenced by decompositionMethod::calcCellCells(), extendedCentredCellToFaceStencil::compact(), extendedCentredFaceToCellStencil::compact(), extendedCentredCellToCellStencil::compact(), UOPstream::flags(), UIPstream::flags(), globalIndex::gather(), lduPrimitiveMesh::gather(), Foam::gAverage(), GAMGProcAgglomeration::globalCellCells(), globalIndex::globalIndex(), Foam::gSumCmptProd(), Foam::gSumProd(), regionModel::interRegionAMI(), lduPrimitiveMesh::lduPrimitiveMesh(), LUscalarMatrix::LUscalarMatrix(), mappedPatchFieldBase< Type >::mappedField(), mapDistribute::transformPosition::operator()(), Pstream::Pstream(), regIOobject::read(), Foam::reduce(), fvMatrix< Type >::relax(), mapDistribute::schedule(), LUscalarMatrix::solve(), processorFvPatch::tag(), processorPolyPatch::tag(), processorCyclicPolyPatch::tag(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), mapDistribute::transformStart(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), filmPyrolysisTemperatureCoupledFvPatchScalarField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), MarshakRadiationFvPatchScalarField::updateCoeffs(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), and thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs().
commsType() [1/2]
commsTypes commsType () const inline
Get the communications type of the stream.
Definition at line 458 of file UPstream.H.
References UPstream::commsType_.
commsType() [2/2]
commsTypes commsType (const commsTypes ct) inline
Set the communications type of the stream.
Definition at line 464 of file UPstream.H.
References UPstream::abort(), UPstream::commsType_, UPstream::exit(), and UPstream::commsStruct::operator<<.
exit()
void exit (int errnum = 1) static
Exit program.
Definition at line 46 of file UPstream.C.
References notImplemented.
Referenced by UPstream::commsType(), error::exit(), IOerror::exit(), ParRunControl::runPar(), and ParRunControl::~ParRunControl().
abort()
void abort () static
Abort program.
Definition at line 52 of file UPstream.C.
References notImplemented.
Referenced by error::abort(), IOerror::abort(), and UPstream::commsType().
Member Data Documentation
commsTypeNames
const Foam::NamedEnum< Foam::UPstream::commsTypes, 3 > commsTypeNames static
Definition at line 71 of file UPstream.H.
Referenced by GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::evaluate(), PstreamBuffers::finishedSends(), NamedEnum< directionType, 3 >::names(), and argList::parse().
commsType_
commsTypes commsType_ protected
Communications type of this stream.
Definition at line 235 of file UPstream.H.
Referenced by UPstream::commsType(), and UOPstream::~UOPstream().
floatTransfer
bool floatTransfer static
Should compact transfer be used in which floats replace doubles.
reducing the bandwidth requirement at the expense of some loss in accuracy
Definition at line 248 of file UPstream.H.
Referenced by processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), argList::parse(), UPstream::procNo(), processorFvPatchField< Type >::updateInterfaceMatrix(), and processorGAMGInterfaceField::updateInterfaceMatrix().
nProcsSimpleSum
int nProcsSimpleSum static
Number of processors at which the sum algorithm changes from linear.
to tree
Definition at line 252 of file UPstream.H.
Referenced by Pstream::combineGather(), Foam::combineReduce(), Pstream::combineScatter(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), argList::parse(), UPstream::procNo(), regIOobject::read(), Foam::reduce(), Foam::returnReduce(), Pstream::scatter(), and Pstream::scatterList().
defaultCommsType
Foam::UPstream::commsTypes defaultCommsType static
Default commsType.
Definition at line 255 of file UPstream.H.
Referenced by polyBoundaryMesh::clearAddressing(), mappedPatchBase::distribute(), mapDistribute::distribute(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::evaluate(), pointBoundaryMesh::findIndices(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), argList::parse(), UPstream::procNo(), mappedPatchBase::reverseDistribute(), mapDistribute::reverseDistribute(), pointBoundaryMesh::updateMesh(), polyBoundaryMesh::updateMesh(), and addcommsTypeToOpt::writeData().
nPollProcInterfaces
int nPollProcInterfaces static
Number of polling cycles in processor updates.
Definition at line 258 of file UPstream.H.
Referenced by argList::parse(), and addcommsTypeToOpt::writeData().
worldComm
Foam::label worldComm static
Default communicator (all processors)
Definition at line 261 of file UPstream.H.
Referenced by decompositionMethod::calcCellCells(), messageStream::masterStream(), NamedEnum< directionType, 3 >::names(), mapDistribute::printLayout(), Pstream::Pstream(), regIOobject::read(), Foam::reduce(), and addcommsTypeToOpt::writeData().
warnComm
Foam::label warnComm static
Debugging: warn for use of any communicator differing from warnComm.
Definition at line 264 of file UPstream.H.
Referenced by GAMGSolver::GAMGSolver(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), processorGAMGInterface::initInternalFieldTransfer(), processorGAMGInterface::internalFieldTransfer(), messageStream::masterStream(), Foam::reduce(), GAMGSolver::solve(), processorGAMGInterfaceField::updateInterfaceMatrix(), and addcommsTypeToOpt::writeData().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.C