OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Ostream Class Reference abstract
An Ostream is an abstract base class for all output systems (streams, files, token lists, etc).
Public Member Functions
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const token &)=0
Write next token to stream.
virtual Ostream & write (const char)=0
Write character.
virtual Ostream & write (const char *)=0
Write character string.
virtual Ostream & write (const word &)=0
Write word.
virtual Ostream & write (const keyType &)
Write keyType.
virtual Ostream & write (const string &)=0
Write string.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)=0
Write std::string surrounded by quotes.
virtual Ostream & write (const label)=0
Write label.
virtual Ostream & write (const floatScalar)=0
Write floatScalar.
virtual Ostream & write (const doubleScalar)=0
Write doubleScalar.
virtual Ostream & write (const char *, std::streamsize)=0
Write binary block.
virtual void indent ()=0
Add indentation characters.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
virtual void flush ()=0
Flush stream.
virtual void endl ()=0
Add newline and flush stream.
virtual int width () const =0
Get width of output field.
virtual int width (const int w)=0
Set width of output field (and return old width)
virtual int precision () const =0
Get precision of output field.
virtual int precision (const int p)=0
Set precision of output field (and return old precision)
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
virtual ios ::fmtflags flags () const =0
Return flags of stream.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios ::fmtflags flags (const ios ::fmtflags f)=0
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f)
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f, const ios ::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios ::fmtflags uf)
Unset flags of stream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Protected Attributes
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios ::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Detailed Description
An Ostream is an abstract base class for all output systems (streams, files, token lists, etc).
Source files
Ostream.H
Ostream.C
Definition at line 53 of file Ostream.H.
Constructor & Destructor Documentation
Ostream()
Ostream (streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Set stream status.
Definition at line 78 of file Ostream.H.
~Ostream()
virtual ~Ostream () inline virtual
Destructor.
Definition at line 90 of file Ostream.H.
References Ostream::indent(), Ostream::write(), and Ostream::writeQuoted().
Member Function Documentation
write() [1/10]
virtual Ostream& write (const token &) pure virtual
Write next token to stream.
Implemented in UOPstream, OSstream, and prefixOSstream.
Referenced by autoLayerDriver::addLayers(), interRegionHeatTransferModel::addSup(), autoRefineDriver::autoRefineDriver(), hexRef8::consistentSlowRefinement2(), trackedParticle::correctAfterParallelTransfer(), autoSnapDriver::doSnap(), directionInfo::edgeToFaceIndex(), findCellParticle::hitPatch(), if(), keyType::match(), meshRefinement::mergeBaffles(), meshRefinement::mergeEdgesUndo(), meshRefinement::mergePatchFacesUndo(), NamedEnum< directionType, 3 >::names(), ListPlusEqOp< T, Size >::operator()(), Foam::operator<<(), Foam::readLongLong(), Foam::readUlong(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), labelledTri::region(), rotorDiskSource::setFaceArea(), refinementIterator::setRefinement(), hexRef8::setRefinement(), autoSnapDriver::smoothDisplacement(), fieldCoordinateSystemTransform::transformField(), SHA1Digest::write(), FallOffReactionRate< ReactionRate, FallOffFunction >::write(), dsmcFields::write(), dictionaryEntry::write(), primitiveEntry::write(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), wallBoundedParticle::write(), streamLine::write(), wallBoundedStreamLine::write(), PackedList< 2 >::write(), particle< Type >::write(), UniformDimensionedField< scalar >::writeData(), ExplicitSetValue< Type >::writeData(), temperatureLimitsConstraint::writeData(), fixedTemperatureConstraint::writeData(), fixedCoeff::writeData(), explicitPorositySource::writeData(), interRegionExplicitPorositySource::writeData(), powerLaw::writeData(), MRFSource::writeData(), DarcyForchheimer::writeData(), SemiImplicitSource< Type >::writeData(), actuationDiskSource::writeData(), CodedSource< Type >::writeData(), MRFZone::writeData(), rotorDiskSource::writeData(), effectivenessHeatExchangerSource::writeData(), FixedList< bool, Foam::pTraits< Type >::nComponents >::writeEntry(), solidParticle::writeFields(), molecule::writeFields(), interpolate::writeInterpolateField(), Ostream::writeKeyword(), randomise::writeRandomField(), and Ostream::~Ostream().
write() [2/10]
virtual Ostream& write (const char) pure virtual
Write character.
Implemented in UOPstream, OSstream, prefixOSstream, and OBJstream.
write() [3/10]
virtual Ostream& write (const char *) pure virtual
Write character string.
Implemented in UOPstream, OSstream, prefixOSstream, and OBJstream.
write() [4/10]
virtual Ostream& write (const word &) pure virtual
Write word.
Implemented in UOPstream, OSstream, prefixOSstream, and OBJstream.
write() [5/10]
Foam::Ostream & write (const keyType & kw) virtual
Write keyType.
Definition at line 52 of file Ostream.C.
References keyType::isPattern(), and Ostream::writeQuoted().
write() [6/10]
virtual Ostream& write (const string &) pure virtual
Write string.
Implemented in UOPstream, ensightFile, OSstream, prefixOSstream, and OBJstream.
writeQuoted()
virtual Ostream& writeQuoted (const std::string & , const bool quoted = true) pure virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implemented in UOPstream, OSstream, prefixOSstream, and OBJstream.
Referenced by Foam::operator<<(), Ostream::write(), codedFixedValueFvPatchField< Type >::write(), codedFixedValuePointPatchField< Type >::write(), codedMixedFvPatchField< Type >::write(), dynamicCode::writeCommentSHA1(), and Ostream::~Ostream().
write() [7/10]
virtual Ostream& write (const label) pure virtual
Write label.
Implemented in UOPstream, ensightFile, OSstream, and prefixOSstream.
write() [8/10]
virtual Ostream& write (const floatScalar) pure virtual
Write floatScalar.
Implemented in UOPstream, OSstream, and prefixOSstream.
write() [9/10]
virtual Ostream& write (const doubleScalar) pure virtual
Write doubleScalar.
Implemented in UOPstream, OSstream, and prefixOSstream.
write() [10/10]
virtual Ostream& write (const char * , std::streamsize) pure virtual
Write binary block.
Implemented in UOPstream, OSstream, prefixOSstream, and ensightFile.
indent()
virtual void indent () pure virtual
Add indentation characters.
Implemented in UOPstream, OSstream, and prefixOSstream.
Referenced by Foam::indent(), dictionaryEntry::write(), Ostream::writeKeyword(), and Ostream::~Ostream().
indentLevel() [1/2]
unsigned short indentLevel () const inline
Return indent level.
Definition at line 140 of file Ostream.H.
References Ostream::indentLevel_.
indentLevel() [2/2]
unsigned short& indentLevel () inline
Access to indent level.
Definition at line 146 of file Ostream.H.
References Ostream::indentLevel_.
incrIndent()
void incrIndent () inline
Incrememt the indent level.
Definition at line 152 of file Ostream.H.
References Ostream::decrIndent(), Ostream::endl(), Ostream::flush(), Ostream::operator()(), p, Ostream::precision(), Ostream::width(), and Ostream::writeKeyword().
Referenced by Foam::incrIndent().
decrIndent()
void decrIndent ()
Decrememt the indent level.
Definition at line 35 of file Ostream.C.
References Foam::endl(), and Ostream::indentLevel_.
Referenced by Foam::decrIndent(), and Ostream::incrIndent().
writeKeyword()
Foam::Ostream & writeKeyword (const keyType & kw)
Write the keyword followed by an appropriate indentation.
Definition at line 59 of file Ostream.C.
References Ostream::entryIndentation_, Ostream::indent(), keyType::isPattern(), token::SPACE, and Ostream::write().
Referenced by Ostream::incrIndent(), Foam::operator<<(), phaseProperties::phaseProperties(), codedFixedValueFvPatchField< Type >::redirectPatchField(), codedFixedValuePointPatchField< Type >::redirectPatchField(), thirdBodyEfficiencies::write(), SRIFallOffFunction::write(), TroeFallOffFunction::write(), ArrheniusReactionRate::write(), axis::write(), LandauTellerReactionRate::write(), coupleGroupIdentifier::write(), sphericalAngularDamper::write(), JanevReactionRate::write(), powerSeriesReactionRate::write(), linearDamper::write(), solidArrheniusReactionRate::write(), LangmuirHinshelwoodReactionRate::write(), point::write(), csvTableReader< Type >::write(), tableReader< scalar >::write(), line::write(), plane::write(), sphericalAngularSpring::write(), DispersionRASModel< CloudType >::write(), ReactionList< Foam::sutherlandTransport >::write(), linearAxialAngularSpring::write(), boundaryPatch::write(), CloudSubModelBase< Foam::DsmcCloud >::write(), linearSpring::write(), tabulatedAxialAngularSpring::write(), timeVaryingAlphaContactAngleFvPatchScalarField::write(), oscillatingDisplacementPointPatchVectorField::write(), waveDisplacementPointPatchVectorField::write(), constantAlphaContactAngleFvPatchScalarField::write(), temperatureCoupledBase::write(), surfZoneIdentifier::write(), dynamicAlphaContactAngleFvPatchScalarField::write(), interpolation2DTable< scalar >::write(), mappedPatchFieldBase< Type >::write(), fixedNormalSlipPointPatchField< Type >::write(), oscillatingVelocityPointPatchVectorField::write(), genericPointPatchField< Type >::write(), solidBodyMotionDisplacementPointPatchVectorField::write(), angularOscillatingDisplacementPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), interpolationTable< scalar >::write(), sixDoFRigidBodyMotionState::write(), radiationCoupledBase::write(), alphaContactAngleFvPatchScalarField::write(), patchIdentifier::write(), genericPolyPatch::write(), interpolationLookUpTable< scalar >::write(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::write(), uniformInterpolatedDisplacementPointPatchVectorField::write(), fixedMeanFvPatchField< Type >::write(), primitiveEntry::write(), translatingWallVelocityFvPatchVectorField::write(), mutkFilmWallFunctionFvPatchScalarField::write(), freestreamFvPatchField< Type >::write(), solidReaction< ReactionThermo >::write(), genericFvPatchField< Type >::write(), sixDoFRigidBodyDisplacementPointPatchVectorField::write(), inletOutletFvPatchField< Type >::write(), outletInletFvPatchField< Type >::write(), outletMappedUniformInletFvPatchField< Type >::write(), nutUTabulatedWallFunctionFvPatchScalarField::write(), variableHeightFlowRateFvPatchScalarField::write(), fixedJumpAMIFvPatchField< scalar >::write(), turbulentHeatFluxTemperatureFvPatchScalarField::write(), outletPhaseMeanVelocityFvPatchVectorField::write(), regionCoupledBase::write(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), rotatingPressureInletOutletVelocityFvPatchVectorField::write(), fixedJumpFvPatchField< scalar >::write(), surfaceSlipDisplacementPointPatchVectorField::write(), uniformInletOutletFvPatchField< Type >::write(), variableHeightFlowRateInletVelocityFvPatchVectorField::write(), STARCDCoordinateRotation::write(), surfaceDisplacementPointPatchVectorField::write(), fWallFunctionFvPatchScalarField::write(), v2WallFunctionFvPatchScalarField::write(), EulerCoordinateRotation::write(), cylindricalInletVelocityFvPatchVectorField::write(), convectiveHeatTransferFvPatchScalarField::write(), turbulentIntensityKineticEnergyInletFvPatchScalarField::write(), rotatingWallVelocityFvPatchVectorField::write(), kLowReWallFunctionFvPatchScalarField::write(), axesRotation::write(), alphatFilmWallFunctionFvPatchScalarField::write(), pressureNormalInletOutletVelocityFvPatchVectorField::write(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::write(), turbulentMixingLengthFrequencyInletFvPatchScalarField::write(), fanPressureFvPatchScalarField::write(), mappedVariableThicknessWallPolyPatch::write(), SRFFreestreamVelocityFvPatchVectorField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), localAxesRotation::write(), codedFixedValueFvPatchField< Type >::write(), codedFixedValuePointPatchField< Type >::write(), porousBafflePressureFvPatchField< Type >::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), SRFVelocityFvPatchVectorField::write(), mutURoughWallFunctionFvPatchScalarField::write(), codedMixedFvPatchField< Type >::write(), nutURoughWallFunctionFvPatchScalarField::write(), thermalBaffle1DFvPatchScalarField< solidType >::write(), prghPressureFvPatchScalarField::write(), uniformDensityHydrostaticPressureFvPatchScalarField::write(), syringePressureFvPatchScalarField::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), turbulentInletFvPatchField< Type >::write(), phaseHydrostaticPressureFvPatchScalarField::write(), thermalBaffleFvPatchScalarField::write(), atmBoundaryLayerInletEpsilonFvPatchScalarField::write(), oldCyclicPolyPatch::write(), oscillatingFixedValueFvPatchField< Type >::write(), atmBoundaryLayer::write(), externalWallHeatFluxTemperatureFvPatchScalarField::write(), atmBoundaryLayerInletVelocityFvPatchVectorField::write(), fvsPatchField< Type >::write(), sixDoFRigidBodyMotion::write(), cyclicACMIPolyPatch::write(), polyPatch::write(), processorPolyPatch::write(), coupledPolyPatch::write(), Reaction< ReactionThermo >::write(), externalCoupledMixedFvPatchField< scalar >::write(), processorCyclicPolyPatch::write(), cyclicPolyPatch::write(), cyclicAMIPolyPatch::write(), pointPatchField< vector >::write(), mappedPatchBase::write(), fvPatchField< Type >::write(), UniformDimensionedField< scalar >::writeData(), CompatibilityConstant< Type >::writeData(), TableFile< Type >::writeData(), interRegionHeatTransferModel::writeData(), DataEntry< Foam::Vector >::writeData(), CSV< Type >::writeData(), MRFZone::writeData(), DimensionedField< Type, Foam::pointMesh >::writeData(), ensightPart::writeData(), option::writeData(), surfZone::writeDict(), plane::writeDict(), coordinateSystem::writeDict(), TableBase< Type >::writeEntries(), FixedList< bool, Foam::pTraits< Type >::nComponents >::writeEntry(), UList< Foam::wordRe >::writeEntry(), Field< Foam::Vector2D >::writeEntry(), PackedList< 2 >::writeEntry(), fvPatchField< Type >::writeEntryIfDifferent(), mutWallFunctionFvPatchScalarField::writeLocalEntries(), nutWallFunctionFvPatchScalarField::writeLocalEntries(), fWallFunctionFvPatchScalarField::writeLocalEntries(), v2WallFunctionFvPatchScalarField::writeLocalEntries(), epsilonWallFunctionFvPatchScalarField::writeLocalEntries(), omegaWallFunctionFvPatchScalarField::writeLocalEntries(), and ensightPart::writeSummary().
flush()
virtual void flush () pure virtual
Flush stream.
Implemented in UOPstream, and OSstream.
Referenced by Foam::flush(), Ostream::incrIndent(), wordRe::info(), STARCDsurfaceFormatCore::writeCase(), STARCDedgeFormat::writeCase(), and STARCDCore::writePoints().
endl()
virtual void endl () pure virtual
Add newline and flush stream.
Implemented in UOPstream, and OSstream.
Referenced by Foam::endl(), and Ostream::incrIndent().
width() [1/2]
virtual int width () const pure virtual
Get width of output field.
Implemented in UOPstream, and OSstream.
Referenced by Ostream::incrIndent(), functionObjectFile::initStream(), and Foam::setw().
width() [2/2]
virtual int width (const int w) pure virtual
Set width of output field (and return old width)
Implemented in UOPstream, and OSstream.
precision() [1/2]
virtual int precision () const pure virtual
Get precision of output field.
Implemented in UOPstream, and OSstream.
Referenced by Ostream::incrIndent(), Foam::setprecision(), dimensionSet::write(), and STARCDCore::writePoints().
precision() [2/2]
virtual int precision (const int p) pure virtual
Set precision of output field (and return old precision)
Implemented in UOPstream, and OSstream.
operator()()
Ostream& operator() () const inline
Return a non-const reference to const Ostream.
Needed for write functions where the stream argument is temporary: e.g. thing thisThing(OFstream("thingFileName")());
Definition at line 190 of file Ostream.H.
Referenced by Ostream::incrIndent().
Member Data Documentation
indentSize_
const unsigned short indentSize_ = 4 static protected
Number of spaces per indent level.
Definition at line 63 of file Ostream.H.
Referenced by OSstream::indent().
entryIndentation_
const unsigned short entryIndentation_ = 16 static protected
Indentation of the entry from the start of the keyword.
Definition at line 66 of file Ostream.H.
Referenced by Ostream::writeKeyword().
indentLevel_
unsigned short indentLevel_ protected
Current indent level.
Definition at line 69 of file Ostream.H.
Referenced by Ostream::decrIndent(), OSstream::indent(), and Ostream::indentLevel().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/Ostream.H
src/OpenFOAM/db/IOstreams/IOstreams/Ostream.C