OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IOstream Class Reference abstract
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
Classes
class versionNumber
Version number type.
Public Types
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Public Member Functions
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
virtual ios ::fmtflags flags () const =0
Return flags of stream.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios ::fmtflags flags (const ios ::fmtflags f)=0
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f)
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f, const ios ::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios ::fmtflags uf)
Unset flags of stream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Static Public Member Functions
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios ::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes
label lineNumber_
Friends
Ostream & operator<< (Ostream &os, const streamFormat &sf)
Ostream operator.
Detailed Description
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
The basic operations are construct, close, read token, read primitive and read binary block. In addition version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
IOstream.H
IOstream.C
Definition at line 75 of file IOstream.H.
Member Enumeration Documentation
streamAccess
enum streamAccess
Enumeration for whether the stream open or closed.
Enumerator
OPENED
CLOSED
Definition at line 83 of file IOstream.H.
streamFormat
enum streamFormat
Enumeration for the format of data in the stream.
Enumerator
ASCII
BINARY
Definition at line 90 of file IOstream.H.
compressionType
enum compressionType
Enumeration for the format of data in the stream.
Enumerator
UNCOMPRESSED
COMPRESSED
Definition at line 197 of file IOstream.H.
Constructor & Destructor Documentation
IOstream()
IOstream (streamFormat format, versionNumber version, compressionType compression = UNCOMPRESSED) inline
Construct setting format and version.
Definition at line 273 of file IOstream.H.
References IOstream::setBad().
Referenced by IOstream::setGood().
~IOstream()
virtual ~IOstream () inline virtual
Destructor.
Definition at line 291 of file IOstream.H.
References IOstream::check(), IOstream::fatalCheck(), and IOstream::name().
Member Function Documentation
setOpened()
void setOpened () inline protected
Set stream opened.
Definition at line 243 of file IOstream.H.
References IOstream::OPENED.
Referenced by ITstream::ITstream(), OFstream::OFstream(), and UOPstream::UOPstream().
setClosed()
void setClosed () inline protected
Set stream closed.
Definition at line 249 of file IOstream.H.
References IOstream::CLOSED.
Referenced by OFstream::OFstream().
setState()
void setState (ios ::iostate state) inline protected
Set stream state.
Definition at line 255 of file IOstream.H.
Referenced by ISstream::get(), ISstream::getLine(), OFstream::OFstream(), ISstream::putback(), ISstream::read(), OSstream::write(), and OSstream::writeQuoted().
setGood()
void setGood () inline protected
Set stream to be good.
Definition at line 261 of file IOstream.H.
References IOstream::IOstream().
Referenced by ITstream::ITstream(), ITstream::rewind(), and UOPstream::UOPstream().
name() [1/2]
virtual const fileName& name () const inline virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented in primitiveEntry, ITstream, OFstream, IFstream, ISstream, and OSstream.
Definition at line 301 of file IOstream.H.
Referenced by mappedPatchBase::calcMapping(), IOstream::check(), hexRef8::checkMesh(), functionEntry::execute(), includeEntry::execute(), IOstream::fatalCheck(), includeEntry::includeFileName(), Foam::operator>>(), IOobject::readHeader(), IOerror::SafeFatalIOError(), triSurface::triSurfInstance(), ensightSetWriter< Type >::write(), gnuplotGraph::write(), xmgrGraph::write(), edgeMeshFormat::write(), CloudSubModelBase< Foam::DsmcCloud >::write(), STARCDsurfaceFormatCore::writeCase(), STARCDedgeFormat::writeCase(), fieldValueDelta::writeFileHeader(), and IOstream::~IOstream().
name() [2/2]
virtual fileName& name () inline virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented in primitiveEntry, ITstream, OFstream, IFstream, ISstream, and OSstream.
Definition at line 308 of file IOstream.H.
check()
bool check (const char * operation) const virtual
Check IOstream status for given operation.
print IOstream state if error has occured
Definition at line 92 of file IOstream.C.
References IOstream::bad(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, and IOstream::name().
Referenced by adiabaticPerfectFluid< Specie >::adiabaticPerfectFluid(), Foam::checkMethod(), CollidingParcel< ParcelType >::CollidingParcel(), CollisionRecordList< vector, vector >::CollisionRecordList(), constTransport< Thermo >::constTransport(), trackedParticle::correctAfterParallelTransfer(), Keyed< T >::createList(), DsmcParcel< ParcelType >::DsmcParcel(), eConstThermo< EquationOfState >::eConstThermo(), directionInfo::edgeToFaceIndex(), fieldAverageItem::fieldAverageItem(), findCellParticle::findCellParticle(), hConstThermo< EquationOfState >::hConstThermo(), hExponentialThermo< EquationOfState >::hExponentialThermo(), findCellParticle::hitPatch(), ignitionSite::ignitionSite(), incompressiblePerfectGas< Specie >::incompressiblePerfectGas(), coordinateSystem::init(), janafThermo< EquationOfState >::janafThermo(), KinematicParcel< ParcelType >::KinematicParcel(), kinematicParcelInjectionData::kinematicParcelInjectionData(), linear< Type >::linear(), keyType::match(), molecule::molecule(), MPPICParcel< ParcelType >::MPPICParcel(), line< Point, PointRef >::nearestDist(), objectMap::objectMap(), Foam::operator!=(), WallSiteData< Type >::operator!=(), Istream::operator()(), dimensioned< vector >::operator/=(), Foam::operator<<(), distribution::operator=(), surfacePatch::operator==(), fvPatchField< Type >::operator==(), Foam::operator>>(), PairCollisionRecord< Type >::PairCollisionRecord(), particle< Type >::particle(), PengRobinsonGas< Specie >::PengRobinsonGas(), perfectFluid< Specie >::perfectFluid(), perfectGas< Specie >::perfectGas(), phaseProperties::phaseProperties(), polyBoundaryMesh::polyBoundaryMesh(), sampledSurface::print(), pyramid< Point, PointRef, polygonRef >::pyramid(), ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel(), reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData(), ReactingParcel< ParcelType >::ReactingParcel(), reactingParcelInjectionData::reactingParcelInjectionData(), dimensioned< vector >::read(), dimensionSet::read(), IOPosition< CloudType >::readData(), Foam::readLongLong(), Foam::readUlong(), ensightPart::reconstruct(), labelledTri::region(), rhoConst< Specie >::rhoConst(), PackedList< 2 >::setPair(), solidParticle::solidParticle(), LduMatrix< Type, DType, LUType >::source(), specie::specie(), SprayParcel< ParcelType >::SprayParcel(), streamLineParticle::streamLineParticle(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), sutherlandTransport< Thermo >::sutherlandTransport(), thermo< Thermo, Type >::thermo(), ThermoParcel< ParcelType >::ThermoParcel(), thermoParcelInjectionData::thermoParcelInjectionData(), lduMesh::thisDb(), polyMeshModifier::topoChanger(), trackedParticle::trackedParticle(), memInfo::valid(), VectorSpace< Vector< vector >, vector, 3 >::VectorSpace(), wallBoundedParticle::wallBoundedParticle(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), WallCollisionRecord< Type >::WallCollisionRecord(), SHA1Digest::write(), edgeMeshFormat::write(), boundaryPatch::write(), OFSsurfaceFormat< Face >::write(), specie::write(), perfectGas< Specie >::write(), janafThermo< EquationOfState >::write(), dimensionSet::write(), wallBoundedParticle::write(), thermo< Thermo, Type >::write(), triSurface::write(), particle< Type >::write(), ensightParts::writeData(), polyBoundaryMesh::writeData(), DimensionedField< Type, Foam::pointMesh >::writeData(), FixedList< bool, Foam::pTraits< Type >::nComponents >::writeEntry(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::writeEntry(), solidParticle::writeFields(), streamLineParticle::writeFields(), molecule::writeFields(), Cloud< streamLineParticle >::writeObject(), IOstream::~IOstream(), and tetIndices::~tetIndices().
fatalCheck()
void fatalCheck (const char * operation) const
Check IOstream status for given operation.
print IOstream state if error has occured and exit
Definition at line 107 of file IOstream.C.
References IOstream::bad(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, and IOstream::name().
Referenced by dictionaryEntry::dictionaryEntry(), functionEntry::execute(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), entry::New(), mapDistribute::operator=(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), PtrList< MRFZone >::read(), primitiveEntry::read(), PackedList< 2 >::read(), UList< Foam::wordRe >::writeEntry(), and IOstream::~IOstream().
opened()
bool opened () const inline
Return true if stream has been opened.
Definition at line 325 of file IOstream.H.
References IOstream::OPENED.
Referenced by IOstream::print().
closed()
bool closed () const inline
Return true if stream is closed.
Definition at line 331 of file IOstream.H.
References IOstream::CLOSED.
Referenced by IOstream::print().
good()
bool good () const inline
Return true if next operation might succeed.
Definition at line 337 of file IOstream.H.
Referenced by topoSetSource::checkIs(), Foam::debug::controlDict(), dynamicCode::copyAndFilter(), dynamicCode::copyOrCreateFiles(), AC3DsurfaceFormatCore::cueTo(), error::error(), edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), noiseFFT::noiseFFT(), IOobject::objectStream(), OFstream::OFstream(), csvTableReader< Type >::operator()(), error::operator()(), Istream::operator()(), Foam::operator>>(), argList::parse(), Foam::parseNASCoord(), pressureGradientExplicitSource::pressureGradientExplicitSource(), IOstream::print(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), OFFsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), edgeMeshFormat::read(), VTKedgeFormat::read(), STARCDsurfaceFormat< Face >::read(), FTRsurfaceFormat< Face >::read(), tabulated6DoFMotion::read(), OFSsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), dictionary::read(), STARCD::readBoundary(), Foam::readCmd(), AC3DsurfaceFormatCore::readCmd(), externalCoupledMixedFvPatchField< scalar >::readData(), STARCDCore::readHeader(), STARCD::readHeader(), IOobject::readHeader(), STARCDsurfaceFormatCore::readInpCellTable(), STARCDCore::readPoints(), Foam::readUpto(), scalarRanges::scalarRanges(), Reaction< ReactionThermo >::setLRhs(), topoSet::topoSet(), triSurface::triSurfInstance(), memInfo::update(), vtkUnstructuredReader::vtkUnstructuredReader(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OBJedgeFormat::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), VTKedgeFormat::write(), edgeMeshFormat::write(), OFSsurfaceFormat< Face >::write(), graph::write(), dictionary::write(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::write(), indexedOctree< Foam::treeDataFace >::write(), STLsurfaceFormat< Face >::writeAscii(), correlationFunction< Type >::writeAveraged(), fieldDictionary::writeData(), IOPosition< CloudType >::writeData(), featureEdgeMesh::writeData(), UniformDimensionedField< scalar >::writeData(), surfZoneIOList::writeData(), surfacePatchIOList::writeData(), IOdictionary::writeData(), AverageIOField< Type >::writeData(), porosityModelList::writeData(), coordinateSystems::writeData(), extendedFeatureEdgeMesh::writeData(), polyTopoChanger::writeData(), cellModel::writeData(), AveragingMethod< Foam::Vector >::writeData(), MRFZoneList::writeData(), ZoneMesh< cellZone, polyMesh >::writeData(), optionList::writeData(), polyBoundaryMesh::writeData(), DimensionedField< Type, Foam::pointMesh >::writeData(), refinementHistory::writeData(), GeometricField< vector, pointPatchField, pointMesh >::writeData(), pairPotential::writeEnergyAndForceTables(), IOobject::writeHeader(), regIOobject::writeObject(), JobInfo::~JobInfo(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
eof()
bool eof () const inline
Return true if end of input seen.
Definition at line 343 of file IOstream.H.
Referenced by topoSetSource::checkIs(), Time::findTimes(), gaussGrad< Type >::gaussGrad(), snGradScheme< Type >::New(), gradScheme< Type >::New(), surfaceInterpolationScheme< GType >::New(), d2dt2Scheme< Type >::New(), ddtScheme< Type >::New(), divScheme< Type >::New(), convectionScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), laplacianScheme< Type, GType >::New(), Reaction< ReactionThermo >::New(), noiseFFT::noiseFFT(), IOstream::print(), PtrList< MRFZone >::read(), ITstream::read(), dictionary::read(), solution::upgradeSolverDict(), and UIPstream::~UIPstream().
fail()
bool fail () const inline
Return true if next operation will fail.
Definition at line 349 of file IOstream.H.
Referenced by IOstream::operator void *(), IOstream::operator!(), and IOstream::print().
bad()
bool bad () const inline
Return true if stream is corrupted.
Definition at line 355 of file IOstream.H.
Referenced by IOstream::check(), IOstream::fatalCheck(), Istream::getBack(), Foam::operator<<(), IOstream::print(), Istream::putBack(), GTSsurfaceFormat< Face >::read(), ISstream::read(), primitiveEntry::read(), dictionary::read(), featureEdgeMesh::readData(), IOdictionary::readData(), extendedFeatureEdgeMesh::readData(), and refinementHistory::readData().
operator void *()
operator void * () const inline
Return non-zero if the stream has not failed.
Definition at line 361 of file IOstream.H.
References IOstream::fail().
operator!()
bool operator! () const inline
Return true if the stream has failed.
Definition at line 369 of file IOstream.H.
References IOstream::fail(), and IOstream::formatEnum().
formatEnum()
Foam::IOstream::streamFormat formatEnum (const word & format) static
Return stream format of given format name.
Definition at line 39 of file IOstream.C.
References IOstream::ASCII, IOstream::BINARY, Foam::endl(), and WarningIn.
Referenced by ensightSurfaceWriter::ensightSurfaceWriter(), IOstream::format(), IOstream::operator!(), and Time::readDict().
format() [1/3]
streamFormat format () const inline
Return current stream format.
Definition at line 381 of file IOstream.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel(), trackedParticle::correctAfterParallelTransfer(), DsmcParcel< ParcelType >::DsmcParcel(), directionInfo::edgeToFaceIndex(), calcEntry::execute(), codeStream::execute(), fanFvPatchField< Type >::fanFvPatchField(), findCellParticle::findCellParticle(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), findCellParticle::hitPatch(), KinematicParcel< ParcelType >::KinematicParcel(), List< functionObject *>::List(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), molecule::molecule(), MPPICParcel< ParcelType >::MPPICParcel(), ensightFile::newline(), Foam::operator<<(), Foam::operator>>(), particle< Type >::particle(), ReactingParcel< ParcelType >::ReactingParcel(), UIPstream::read(), ISstream::read(), PackedList< 2 >::read(), IOobject::readHeader(), refineCell::refineCell(), labelledTri::region(), Foam::setformat(), solidParticle::solidParticle(), SprayParcel< ParcelType >::SprayParcel(), ThermoParcel< ParcelType >::ThermoParcel(), trackedParticle::trackedParticle(), wallBoundedParticle::wallBoundedParticle(), csvTableReader< Type >::write(), ensightFile::write(), OSstream::write(), UOPstream::write(), dimensionSet::write(), wallBoundedParticle::write(), PackedList< 2 >::write(), particle< Type >::write(), ensightFile::writeBinaryHeader(), CSV< Type >::writeData(), FixedList< bool, Foam::pTraits< Type >::nComponents >::writeEntry(), UList< Foam::wordRe >::writeEntry(), solidParticle::writeFields(), molecule::writeFields(), and IOobject::writeHeader().
format() [2/3]
streamFormat format (const streamFormat fmt) inline
Set the stream format.
Definition at line 387 of file IOstream.H.
format() [3/3]
streamFormat format (const word & fmt) inline
Set the stream format from word.
Definition at line 395 of file IOstream.H.
References IOstream::formatEnum().
version() [1/2]
versionNumber version () const inline
Return the stream version.
Definition at line 403 of file IOstream.H.
Referenced by Field< Foam::Vector2D >::Field(), Foam::operator>>(), IOobject::readHeader(), mappedPatchBase::readListOrField(), Foam::setversion(), and IOobject::writeHeader().
version() [2/2]
versionNumber version (const versionNumber ver) inline
Set the stream version.
Definition at line 409 of file IOstream.H.
References IOstream::compressionEnum().
compressionEnum()
Foam::IOstream::compressionType compressionEnum (const word & compression) static
Return compression of given compression name.
Definition at line 61 of file IOstream.C.
References IOstream::COMPRESSED, Foam::endl(), IOstream::UNCOMPRESSED, Switch::valid(), and WarningIn.
Referenced by IOstream::compression(), Time::readDict(), and IOstream::version().
compression() [1/3]
compressionType compression () const inline
Return the stream compression.
Definition at line 420 of file IOstream.H.
Referenced by Foam::setcompression().
compression() [2/3]
compressionType compression (const compressionType cmp) inline
Set the stream compression.
Definition at line 426 of file IOstream.H.
compression() [3/3]
compressionType compression (const word & cmp) inline
Set the stream compression from word.
Definition at line 434 of file IOstream.H.
References IOstream::compressionEnum().
lineNumber() [1/3]
label lineNumber () const inline
Return current stream line number.
Definition at line 442 of file IOstream.H.
References IOstream::lineNumber_.
Referenced by functionEntry::execute(), calcEntry::execute(), codeStream::execute(), Foam::parseNASCoord(), ITstream::print(), IOstream::print(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), ISstream::read(), UIPstream::read(), primitiveEntry::read(), ITstream::read(), IOobject::readHeader(), IOerror::SafeFatalIOError(), and vtkUnstructuredReader::vtkUnstructuredReader().
lineNumber() [2/3]
label& lineNumber () inline
Return current stream line number.
Definition at line 448 of file IOstream.H.
References IOstream::lineNumber_.
lineNumber() [3/3]
label lineNumber (const label ln) inline
Set the stream line number.
Definition at line 454 of file IOstream.H.
References IOstream::flags(), IOstream::lineNumber_, and Foam::ln().
flags() [1/2]
virtual ios ::fmtflags flags () const pure virtual
Return flags of stream.
Implemented in ITstream, UIPstream, ISstream, UOPstream, and OSstream.
Referenced by IOstream::lineNumber(), IOstream::setBad(), IOstream::setf(), and IOstream::unsetf().
defaultPrecision() [1/2]
static unsigned int defaultPrecision () inline static
Return the default precision.
Definition at line 465 of file IOstream.H.
References IOstream::precision_.
Referenced by functionObjectFile::charWidth(), isNotEqOp< T >::operator()(), probes::prepare(), Time::readDict(), and functionObjectFile::valueWidth().
defaultPrecision() [2/2]
static unsigned int defaultPrecision (unsigned int p) inline static
Reset the default precision (and return old precision)
Definition at line 471 of file IOstream.H.
References p, and IOstream::precision_.
setEof()
void setEof () inline
Set stream to have reached eof.
Definition at line 479 of file IOstream.H.
Referenced by ITstream::read().
setFail()
void setFail () inline
Set stream to have failed.
Definition at line 485 of file IOstream.H.
setBad()
void setBad () inline
Set stream to be bad.
Definition at line 491 of file IOstream.H.
References f(), and IOstream::flags().
Referenced by IOstream::IOstream(), keyType::match(), OFstream::OFstream(), Foam::operator>>(), ISstream::putback(), UIPstream::read(), ITstream::read(), Istream::readBegin(), Istream::readBeginList(), Istream::readEnd(), Istream::readEndList(), and UOPstream::write().
flags() [2/2]
virtual ios ::fmtflags flags (const ios ::fmtflags f) pure virtual
Set flags of stream.
setf() [1/2]
ios ::fmtflags setf (const ios ::fmtflags f) inline
Set flags of stream.
Definition at line 500 of file IOstream.H.
References IOstream::flags().
Referenced by Foam::dec(), ensightAsciiStream::ensightAsciiStream(), ensightFile::ensightFile(), Foam::fixed(), Foam::hex(), functionObjectFile::initStream(), NamedEnum< directionType, 3 >::names(), Foam::oct(), Foam::scientific(), Foam::setf(), ensightSetWriter< Type >::write(), and STARCDCore::writePoints().
setf() [2/2]
ios ::fmtflags setf (const ios ::fmtflags f, const ios ::fmtflags mask) inline
Set flags of given field of stream.
Definition at line 507 of file IOstream.H.
References IOstream::flags().
unsetf()
void unsetf (const ios ::fmtflags uf) inline
Unset flags of stream.
Definition at line 516 of file IOstream.H.
References IOstream::flags(), IOstream::info(), IOstream::versionNumber::operator<<, IOstream::print(), and sf().
Referenced by NamedEnum< directionType, 3 >::names().
print() [1/2]
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented in UOPstream, ITstream, ISstream, OSstream, UIPstream, OFstream, prefixOSstream, IFstream, OStringStream, and IStringStream.
Definition at line 130 of file IOstream.C.
References IOstream::ASCII, IOstream::bad(), IOstream::BINARY, IOstream::closed(), Foam::endl(), IOstream::eof(), IOstream::fail(), IOstream::good(), IOstream::lineNumber(), and IOstream::opened().
Referenced by Foam::operator<<(), OSstream::print(), ISstream::print(), ITstream::print(), and IOstream::unsetf().
print() [2/2]
void print (Ostream & os, const int streamState) const
Check given stream state bits.
Definition at line 181 of file IOstream.C.
References Foam::endl().
info()
InfoProxy<IOstream> info () const inline
Return info proxy.
Used to print IOstream information to a stream
Definition at line 535 of file IOstream.H.
Referenced by OFstream::OFstream(), dimensionSet::read(), IOstream::unsetf(), and IOobject::writeHeader().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const streamFormat & sf) friend
Ostream operator.
Member Data Documentation
originalVersion
const IOstream::versionNumber originalVersion static
Original version number.
Definition at line 207 of file IOstream.H.
Referenced by Foam::operator>>().
currentVersion
const IOstream::versionNumber currentVersion static
Current version number.
Definition at line 210 of file IOstream.H.
Referenced by regionModel::evolve(), meshReader::warnDuplicates(), regIOobject::write(), and meshReader::writeMesh().
precision_
unsigned int precision_ static
Default precision.
Definition at line 213 of file IOstream.H.
Referenced by IOstream::defaultPrecision().
lineNumber_
label lineNumber_ protected
Definition at line 235 of file IOstream.H.
Referenced by ISstream::get(), ISstream::getLine(), IOstream::lineNumber(), OFstream::OFstream(), ISstream::putback(), ITstream::read(), ITstream::rewind(), OSstream::write(), and OSstream::writeQuoted().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.H
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.C
src/OpenFOAM/db/IOstreams/IOstreams.C