OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Pstream Class Reference
Inter-processor communications stream.
Public Member Functions
ClassName ("Pstream")
Pstream (const commsTypes commsType, const label bufSize=0)
Construct given optional buffer size.
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Static Public Member Functions
template<class T , class BinaryOp >
static void gather (const List< commsStruct > &comms, T &Value, const BinaryOp &bop, const int tag, const label comm)
Gather data. Apply bop to combine Value.
template<class T , class BinaryOp >
static void gather (T &Value, const BinaryOp &bop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void scatter (const List< commsStruct > &comms, T &Value, const int tag, const label comm)
Scatter data. Distribute without modification. Reverse of gather.
template<class T >
static void scatter (T &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T , class CombineOp >
static void combineGather (const List< commsStruct > &comms, T &Value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void combineGather (T &Value, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void combineScatter (const List< commsStruct > &comms, T &Value, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class T >
static void combineScatter (T &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T , class CombineOp >
static void listCombineGather (const List< commsStruct > &comms, List< T > &Value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void listCombineGather (List< T > &Value, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void listCombineScatter (const List< commsStruct > &comms, List< T > &Value, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class T >
static void listCombineScatter (List< T > &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container , class CombineOp >
static void mapCombineGather (const List< commsStruct > &comms, Container &Values, const CombineOp &cop, const int tag, const label comm)
template<class Container , class CombineOp >
static void mapCombineGather (Container &Values, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container >
static void mapCombineScatter (const List< commsStruct > &comms, Container &Values, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class Container >
static void mapCombineScatter (Container &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void gatherList (const List< commsStruct > &comms, List< T > &Values, const int tag, const label comm)
Gather data but keep individual values separate.
template<class T >
static void gatherList (List< T > &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void scatterList (const List< commsStruct > &comms, List< T > &Values, const int tag, const label comm)
Scatter data. Reverse of gatherList.
template<class T >
static void scatterList (List< T > &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container , class T >
static void exchange (const List< Container > &, List< Container > &, labelListList &sizes, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool block=true)
Exchange data. Sends sendData, receives into recvData, sets.
Static Public Member Functions inherited from UPstream
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor.
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number.
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library.
static bool init (int &argc, char **&argv)
Initialisation function called from main.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static int masterNo ()
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (int communicator)
Process ID of given process index.
static int firstSlave ()
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
Protected Attributes
DynamicList< char > buf_
Transfer buffer.
Protected Attributes inherited from UPstream
commsTypes commsType_
Communications type of this stream.
Additional Inherited Members
Public Types inherited from UPstream
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Static Public Attributes inherited from UPstream
static const NamedEnum< commsTypes, 3 > commsTypeNames
static bool floatTransfer
Should compact transfer be used in which floats replace doubles.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Detailed Description
Inter-processor communications stream.
Source files
Pstream.H
Pstream.C
gatherScatter.C
combineGatherScatter.C
gatherScatterList.C
exchange.C
Definition at line 53 of file Pstream.H.
Constructor & Destructor Documentation
Pstream()
Pstream (const commsTypes commsType, const label bufSize = 0) inline
Construct given optional buffer size.
Definition at line 75 of file Pstream.H.
References Pstream::combineGather(), Pstream::combineScatter(), Pstream::exchange(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), UPstream::msgType(), Pstream::scatter(), Pstream::scatterList(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), Foam::T(), and UPstream::worldComm.
Member Function Documentation
ClassName()
ClassName ("Pstream")
gather() [1/2]
void gather (const List< commsStruct > & comms, T & Value, const BinaryOp & bop, const int tag, const label comm) static
Gather data. Apply bop to combine Value.
from different processors
Definition at line 47 of file gatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), forAll, UPstream::myProcNo(), UPstream::nProcs(), UIPstream::read(), UPstream::scheduled, Foam::T(), and UOPstream::write().
Referenced by Pstream::Pstream(), and Foam::reduce().
gather() [2/2]
void gather (T & Value, const BinaryOp & bop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 127 of file gatherScatter.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatter(), and UPstream::treeCommunication().
scatter() [1/2]
void scatter (const List< commsStruct > & comms, T & Value, const int tag, const label comm) static
Scatter data. Distribute without modification. Reverse of gather.
Definition at line 147 of file gatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), forAll, UPstream::myProcNo(), UPstream::nProcs(), UIPstream::read(), UPstream::scheduled, Foam::T(), and UOPstream::write().
Referenced by Pstream::gather(), IOdictionary::IOdictionary(), InflationInjection< CloudType >::parcelsToInject(), Pstream::Pstream(), regIOobject::read(), Foam::reduce(), Pstream::scatter(), patchInjectionBase::setPositionAndCell(), ParSortableList< Type >::sort(), sixDoFRigidBodyMotion::updateAcceleration(), sixDoFRigidBodyMotion::updatePosition(), and fileMonitor::updateStates().
scatter() [2/2]
void scatter (T & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 221 of file gatherScatter.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatter(), and UPstream::treeCommunication().
combineGather() [1/2]
void combineGather (const List< commsStruct > & comms, T & Value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 50 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, Foam::T(), and UOPstream::write().
Referenced by Foam::combineReduce(), and Pstream::Pstream().
combineGather() [2/2]
void combineGather (T & Value, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 144 of file combineGatherScatter.C.
References Pstream::combineScatter(), UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
combineScatter() [1/2]
void combineScatter (const List< commsStruct > & comms, T & Value, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 178 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, Foam::T(), and UOPstream::write().
Referenced by Pstream::combineGather(), Foam::combineReduce(), and Pstream::Pstream().
combineScatter() [2/2]
void combineScatter (T & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 259 of file combineGatherScatter.C.
References UPstream::linearCommunication(), Pstream::listCombineGather(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
listCombineGather() [1/2]
void listCombineGather (const List< commsStruct > & comms, List< T > & Value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 282 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, List< T >::size(), and UOPstream::write().
Referenced by meshRefinement::balance(), forces::calcForcesMoment(), viewFactor::calculate(), Pstream::combineScatter(), patchInjection::correct(), patchProbes::findElements(), mappedPatchBase::findSamples(), injectionModelList::info(), meshRefinement::mergeBaffles(), ifEqEqOp< value >::operator()(), nearestEqOp::operator()(), patchInjection::patchInjectedMassTotals(), meshRefinement::printMeshInfo(), Pstream::Pstream(), patchProbes::sample(), probes::sample(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::updateMesh(), and fileMonitor::updateStates().
listCombineGather() [2/2]
void listCombineGather (List< T > & Value, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 383 of file combineGatherScatter.C.
References UPstream::linearCommunication(), Pstream::listCombineScatter(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
listCombineScatter() [1/2]
void listCombineScatter (const List< commsStruct > & comms, List< T > & Value, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 417 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, and UOPstream::write().
Referenced by meshRefinement::balance(), forces::calcForcesMoment(), viewFactor::calculate(), patchProbes::findElements(), mappedPatchBase::findSamples(), Pstream::listCombineGather(), meshRefinement::mergeBaffles(), ifEqEqOp< value >::operator()(), nearestEqOp::operator()(), meshRefinement::printMeshInfo(), Pstream::Pstream(), patchProbes::sample(), probes::sample(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::updateMesh(), and fileMonitor::updateStates().
listCombineScatter() [2/2]
void listCombineScatter (List< T > & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 498 of file combineGatherScatter.C.
References UPstream::linearCommunication(), Pstream::mapCombineGather(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
mapCombineGather() [1/2]
void mapCombineGather (const List< commsStruct > & comms, Container & Values, const CombineOp & cop, const int tag, const label comm) static
Definition at line 535 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, and UPstream::scheduled.
Referenced by extrudePatchMesh::extrudePatchMesh(), Pstream::listCombineScatter(), ListPlusEqOp< T, Size >::operator()(), Pstream::Pstream(), and meshRefinement::zonify().
mapCombineGather() [2/2]
void mapCombineGather (Container & Values, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 602 of file combineGatherScatter.C.
References UPstream::linearCommunication(), Pstream::mapCombineScatter(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
mapCombineScatter() [1/2]
void mapCombineScatter (const List< commsStruct > & comms, Container & Values, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 636 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, and UPstream::scheduled.
Referenced by extrudePatchMesh::extrudePatchMesh(), Pstream::mapCombineGather(), ListPlusEqOp< T, Size >::operator()(), Pstream::Pstream(), and meshRefinement::zonify().
mapCombineScatter() [2/2]
void mapCombineScatter (Container & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 687 of file combineGatherScatter.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, and UPstream::treeCommunication().
gatherList() [1/2]
void gatherList (const List< commsStruct > & comms, List< T > & Values, const int tag, const label comm) static
Gather data but keep individual values separate.
Definition at line 49 of file gatherScatterList.C.
References Foam::abort(), UPstream::commsStruct::above(), UPstream::commsStruct::allBelow(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, List< T >::size(), and UOPstream::write().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), Pstream::gatherList(), globalIndex::globalIndex(), NamedEnum< directionType, 3 >::names(), InflationInjection< CloudType >::parcelsToInject(), Pstream::Pstream(), fvMeshSubset::setLargeCellSubset(), ParSortableList< Type >::sort(), and externalCoupledTemperatureMixedFvPatchScalarField::transferData().
gatherList() [2/2]
void gatherList (List< T > & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 193 of file gatherScatterList.C.
References Pstream::gatherList(), UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatterList(), and UPstream::treeCommunication().
scatterList() [1/2]
void scatterList (const List< commsStruct > & comms, List< T > & Values, const int tag, const label comm) static
Scatter data. Reverse of gatherList.
Definition at line 208 of file gatherScatterList.C.
References Foam::abort(), UPstream::commsStruct::above(), UPstream::commsStruct::allNotBelow(), UPstream::commsStruct::below(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, UPstream::myProcNo(), UPstream::nProcs(), Foam::Pout, UIPstream::read(), UPstream::scheduled, List< T >::size(), and UOPstream::write().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), Pstream::gatherList(), globalIndex::globalIndex(), NamedEnum< directionType, 3 >::names(), Pstream::Pstream(), Pstream::scatterList(), and fvMeshSubset::setLargeCellSubset().
scatterList() [2/2]
void scatterList (List< T > & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 331 of file gatherScatterList.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatterList(), and UPstream::treeCommunication().
exchange()
void exchange (const List< Container > & sendBufs, List< Container > & recvBufs, labelListList & sizes, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool block = true) static
Exchange data. Sends sendData, receives into recvData, sets.
sizes (not bytes). sizes[p0][p1] is what processor p0 has sent to p1. Continuous data only. If block=true will wait for all transfers to finish.
Definition at line 44 of file exchange.C.
References Foam::abort(), Foam::combineReduce(), Foam::FatalError, FatalErrorIn, forAll, UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UIPstream::read(), List< T >::setSize(), List< T >::size(), Foam::T(), UPstream::waitRequests(), and UOPstream::write().
Referenced by Pstream::Pstream().
Member Data Documentation
buf_
DynamicList<char> buf_ protected
Transfer buffer.
Definition at line 63 of file Pstream.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/Pstream.H
src/OpenFOAM/db/IOstreams/Pstreams/combineGatherScatter.C
src/OpenFOAM/db/IOstreams/Pstreams/exchange.C
src/OpenFOAM/db/IOstreams/Pstreams/gatherScatter.C
src/OpenFOAM/db/IOstreams/Pstreams/gatherScatterList.C