OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UPstream::communicator Class Reference
Helper class for allocating/freeing communicators.
Public Member Functions
communicator (const label parent, const labelList &subRanks, const bool doPstream)
~communicator ()
operator label () const
Detailed Description
Helper class for allocating/freeing communicators.
Definition at line 297 of file UPstream.H.
Constructor & Destructor Documentation
communicator()
communicator (const label parent, const labelList & subRanks, const bool doPstream) inline
Definition at line 308 of file UPstream.H.
~communicator()
~communicator () inline
Definition at line 317 of file UPstream.H.
References UPstream::freeCommunicator().
Member Function Documentation
operator label()
operator label () const inline
Definition at line 322 of file UPstream.H.
References UPstream::addValidParOptions(), UPstream::allocateTag(), UPstream::baseProcNo(), UPstream::finishedRequest(), UPstream::freeTag(), UPstream::init(), UPstream::nRequests(), UPstream::procNo(), UPstream::resetRequests(), UPstream::waitRequest(), and UPstream::waitRequests().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H