OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ISstream Class Reference
Generic input stream.
Public Member Functions
ISstream (istream &is, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct as wrapper around istream.
virtual ~ISstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
ISstream & get (char &)
Raw, low-level get character function.
int peek ()
Raw, low-level peek function.
ISstream & getLine (string &)
Raw, low-level getline into a string function.
ISstream & putback (const char &)
Raw, low-level putback character function.
virtual Istream & read (token &)
Return next token from stream.
virtual Istream & read (char &)
Read a character.
virtual Istream & read (word &)
Read a word.
virtual Istream & read (string &)
Read a string (including enclosing double-quotes).
virtual Istream & read (label &)
Read a label.
virtual Istream & read (floatScalar &)
Read a floatScalar.
virtual Istream & read (doubleScalar &)
Read a doubleScalar.
virtual Istream & read (char *, std::streamsize)
Read binary block.
virtual Istream & rewind ()
Rewind and return the stream so that it may be read again.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual istream & stdStream ()
Access to underlying std::istream.
virtual const istream & stdStream () const
Const access to underlying std::istream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Istream
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Istream ()
Destructor.
void putBack (const token &)
Put back token.
bool getBack (token &)
Get the put back token if there is one and return true.
bool peekBack (token &)
Peek at the put back token without removing it.
Istream & readBegin (const char *funcName)
Istream & readEnd (const char *funcName)
Istream & readEndBegin (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios ::fmtflags flags (const ios ::fmtflags f)=0
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f)
Set flags of stream.
ios ::fmtflags setf (const ios ::fmtflags f, const ios ::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios ::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios ::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from IOstream
label lineNumber_
Detailed Description
Generic input stream.
Source files
ISstream.H
ISstreamI.H
ISstream.C
Definition at line 51 of file ISstream.H.
Constructor & Destructor Documentation
ISstream()
ISstream (istream & is, const string & name, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Construct as wrapper around istream.
Definition at line 31 of file ISstreamI.H.
~ISstream()
virtual ~ISstream () inline virtual
Destructor.
Definition at line 96 of file ISstream.H.
References ISstream::flags(), ISstream::getLine(), ISstream::name(), ISstream::peek(), ISstream::putback(), ISstream::read(), and ISstream::rewind().
Member Function Documentation
name() [1/2]
virtual const fileName& name () const inline virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented from IOstream.
Reimplemented in IFstream.
Definition at line 106 of file ISstream.H.
Referenced by dynamicCode::copyAndFilter(), IStringStream::print(), OStringStream::print(), OSstream::print(), ISstream::print(), and ISstream::~ISstream().
name() [2/2]
virtual fileName& name () inline virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented from IOstream.
Reimplemented in IFstream.
Definition at line 113 of file ISstream.H.
flags() [1/2]
std::ios_base::fmtflags flags () const virtual
Return flags of output stream.
Implements IOstream.
Definition at line 827 of file ISstream.C.
Referenced by ISstream::~ISstream().
get()
Foam::ISstream & get (char & c) inline
Raw, low-level get character function.
Definition at line 57 of file ISstreamI.H.
References IOstream::lineNumber_, and IOstream::setState().
Referenced by Foam::ReadHex().
peek()
int peek () inline
Raw, low-level peek function.
Does not remove the character from the stream. Returns the next character in the stream or EOF if the end of file is read.
Definition at line 71 of file ISstreamI.H.
Referenced by ISstream::~ISstream().
getLine()
Foam::ISstream & getLine (string & s) inline
Raw, low-level getline into a string function.
Definition at line 77 of file ISstreamI.H.
References IOstream::lineNumber_, and IOstream::setState().
Referenced by dynamicCode::copyAndFilter(), AC3DsurfaceFormatCore::cueTo(), edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), NamedEnum< directionType, 3 >::names(), csvTableReader< Type >::operator()(), Foam::parseNASCoord(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), Foam::readCmd(), AC3DsurfaceFormatCore::readCmd(), STARCDCore::readHeader(), STARCDsurfaceFormatCore::readInpCellTable(), Foam::readUpto(), triSurface::triSurfInstance(), memInfo::update(), vtkUnstructuredReader::vtkUnstructuredReader(), and ISstream::~ISstream().
putback()
Foam::ISstream & putback (const char & c) inline
Raw, low-level putback character function.
Definition at line 87 of file ISstreamI.H.
References IOstream::lineNumber_, IOstream::setBad(), and IOstream::setState().
Referenced by ISstream::read(), and ISstream::~ISstream().
read() [1/8]
Foam::Istream & read (token & t) virtual
Return next token from stream.
Implements Istream.
Definition at line 132 of file ISstream.C.
References token::ADD, token::ASSIGN, IOstream::bad(), token::BEGIN_BLOCK, token::BEGIN_LIST, token::BEGIN_SQR, token::BEGIN_STRING, Foam::constant::universal::c, token::COLON, token::COMMA, token::DIVIDE, token::END_BLOCK, token::END_LIST, token::END_SQR, token::END_STATEMENT, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Istream::getBack(), token::HASH, token::lineNumber(), IOstream::lineNumber(), token::MULTIPLY, ISstream::putback(), Foam::readScalar(), token::setBad(), IOstream::setState(), token::SUBTRACT, token::type(), token::VARIABLE, and token::VERBATIMSTRING.
Referenced by ISstream::~ISstream().
read() [2/8]
Foam::Istream & read (char & c) virtual
Read a character.
Implements Istream.
Definition at line 418 of file ISstream.C.
read() [3/8]
Foam::Istream & read (word & str) virtual
Read a word.
Implements Istream.
Definition at line 425 of file ISstream.C.
References IOstream::bad(), token::BEGIN_LIST, Foam::constant::universal::c, token::END_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, ISstream::putback(), and word::valid().
read() [4/8]
Foam::Istream & read (string & str) virtual
Read a string (including enclosing double-quotes).
Backslashes are retained, except when escaping double-quotes and an embedded newline character.
Implements Istream.
Definition at line 496 of file ISstream.C.
References IOstream::bad(), token::BEGIN_BLOCK, token::BEGIN_STRING, Foam::constant::universal::c, token::END_BLOCK, token::END_STRING, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, token::HASH, token::NL, ISstream::putback(), and word::valid().
read() [5/8]
Foam::Istream & read (label & val) virtual
Read a label.
Implements Istream.
Definition at line 772 of file ISstream.C.
References IOstream::setState().
read() [6/8]
Foam::Istream & read (floatScalar & val) virtual
Read a floatScalar.
Implements Istream.
Definition at line 780 of file ISstream.C.
References IOstream::setState().
read() [7/8]
Foam::Istream & read (doubleScalar & val) virtual
Read a doubleScalar.
Implements Istream.
Definition at line 788 of file ISstream.C.
References IOstream::setState().
read() [8/8]
Foam::Istream & read (char * buf, std::streamsize count) virtual
Read binary block.
Implements Istream.
Definition at line 797 of file ISstream.C.
References IOstream::BINARY, Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, IOstream::format(), Istream::readBegin(), Istream::readEnd(), and IOstream::setState().
rewind()
Foam::Istream & rewind () virtual
Rewind and return the stream so that it may be read again.
Implements Istream.
Definition at line 816 of file ISstream.C.
References ISstream::stdStream().
Referenced by ISstream::~ISstream().
flags() [2/2]
std::ios_base::fmtflags flags (const ios_base::fmtflags flags) virtual
Set flags of output stream.
Definition at line 833 of file ISstream.C.
stdStream() [1/2]
virtual istream& stdStream () inline virtual
Access to underlying std::istream.
Reimplemented in IFstream.
Definition at line 178 of file ISstream.H.
Referenced by ISstream::rewind(), IStringStream::str(), and IStringStream::~IStringStream().
stdStream() [2/2]
virtual const istream& stdStream () const inline virtual
Const access to underlying std::istream.
Reimplemented in IFstream.
Definition at line 184 of file ISstream.H.
References ISstream::print().
print()
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Reimplemented in IFstream, and IStringStream.
Definition at line 34 of file SstreamsPrint.C.
References ISstream::name(), and IOstream::print().
Referenced by IStringStream::print(), IFstream::print(), and ISstream::stdStream().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/ISstream.H
src/OpenFOAM/db/IOstreams/Sstreams/ISstream.C
src/OpenFOAM/db/IOstreams/Sstreams/ISstreamI.H
src/OpenFOAM/db/IOstreams/Sstreams/SstreamsPrint.C