OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IOstream::versionNumber Class Reference
Version number type.
Public Member Functions
versionNumber (const scalar num)
Construct from number.
versionNumber (Istream &is)
Construct from Istream.
int numberToIndex (const scalar num) const
Convert a version number into an index.
int majorVersion () const
Return major version.
int minorVersion () const
Return minor version.
string str () const
Return the versionNumber as a character string.
bool operator== (const versionNumber &vn)
Are these versionNumbers the same?
bool operator!= (const versionNumber &vn)
Are these versionNumbers different?
bool operator< (const versionNumber &vn)
Is this version older than the one given.
bool operator<= (const versionNumber &vn)
Is this version the same as or older than the one given.
bool operator> (const versionNumber &vn)
Is this version newer than the one given.
bool operator>= (const versionNumber &vn)
this version the same as or newer than the one given
Friends
Ostream & operator<< (Ostream &os, const versionNumber &vn)
Ostream operator.
Detailed Description
Version number type.
Definition at line 100 of file IOstream.H.
Constructor & Destructor Documentation
versionNumber() [1/2]
versionNumber (const scalar num) inline
Construct from number.
Definition at line 114 of file IOstream.H.
versionNumber() [2/2]
versionNumber (Istream & is) inline
Construct from Istream.
Definition at line 121 of file IOstream.H.
Member Function Documentation
numberToIndex()
int numberToIndex (const scalar num) const inline
Convert a version number into an index.
Definition at line 131 of file IOstream.H.
majorVersion()
int majorVersion () const inline
Return major version.
Definition at line 137 of file IOstream.H.
Referenced by IOstream::versionNumber::minorVersion().
minorVersion()
int minorVersion () const inline
Return minor version.
Definition at line 143 of file IOstream.H.
References IOstream::versionNumber::majorVersion(), and IOstream::versionNumber::str().
str()
Foam::string str () const
Return the versionNumber as a character string.
Definition at line 120 of file IOstream.C.
References Foam::fixed().
Referenced by IOstream::versionNumber::minorVersion(), and Foam::operator<<().
operator==()
bool operator== (const versionNumber & vn) inline
Are these versionNumbers the same?
Definition at line 155 of file IOstream.H.
operator!=()
bool operator!= (const versionNumber & vn) inline
Are these versionNumbers different?
Definition at line 161 of file IOstream.H.
operator<()
bool operator< (const versionNumber & vn) inline
Is this version older than the one given.
Definition at line 167 of file IOstream.H.
operator<=()
bool operator<= (const versionNumber & vn) inline
Is this version the same as or older than the one given.
Definition at line 173 of file IOstream.H.
operator>()
bool operator> (const versionNumber & vn) inline
Is this version newer than the one given.
Definition at line 179 of file IOstream.H.
operator>=()
bool operator>= (const versionNumber & vn) inline
this version the same as or newer than the one given
Definition at line 185 of file IOstream.H.
References IOstream::versionNumber::operator<<.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const versionNumber & vn) friend
Ostream operator.
Referenced by IOstream::versionNumber::operator>=(), and IOstream::unsetf().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.H
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.C