OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DimensionedField< Type, GeoMesh > Class Template Reference
Field with dimensions and associated with geometry type GeoMesh which is used to size the field and a reference to it is maintained.
Public Types
typedef GeoMesh::Mesh Mesh
typedef Field< Type >::cmptType cmptType
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const Field< Type > &)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensioned< Type > &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const DimensionedField< Type, GeoMesh > &)
Construct as copy.
DimensionedField (DimensionedField< Type, GeoMesh > &, bool reUse)
Construct as copy or re-use as specified.
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh > > &)
Construct by transferring the DimensionedField.
DimensionedField (const IOobject &, const DimensionedField< Type, GeoMesh > &)
Construct as copy of tmp<DimensionedField> deleting argument.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &, bool reUse)
Construct as copy resetting name and re-use as specified.
DimensionedField (const word &newName, const Xfer< DimensionedField< Type, GeoMesh > > &)
Construct by transferring the DimensionedField with a new name.
tmp< DimensionedField< Type, GeoMesh > > clone () const
Construct as copy resetting name.
virtual ~DimensionedField ()
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const Field< Type > & field () const
Field< Type > & field ()
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
void replace (const direction, const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
void replace (const direction, const tmp< DimensionedField< cmptType, GeoMesh > > &)
Replace a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh > > &) const
Calculate and return weighted average.
bool writeData (Ostream &, const word &fieldDictEntry) const
bool writeData (Ostream &) const
Pure virtual writaData function.
void operator= (const DimensionedField< Type, GeoMesh > &)
void operator= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator= (const dimensioned< Type > &)
void operator+= (const DimensionedField< Type, GeoMesh > &)
void operator+= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator-= (const DimensionedField< Type, GeoMesh > &)
void operator-= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator*= (const DimensionedField< scalar, GeoMesh > &)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh > > &)
void operator/= (const DimensionedField< scalar, GeoMesh > &)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type > > &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reUse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type > > &)
Construct by transferring the Field contents.
Field (Istream &)
Construct as copy of tmp<Field>
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType > > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const Type &)
template<class Form , class Cmpt , int nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type > > &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static const DimensionedField< Type, GeoMesh > & null ()
Return a null DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Friends
Ostream & operator (Ostream &, const DimensionedField< Type, GeoMesh > &)
Ostream & operator (Ostream &, const tmp< DimensionedField< Type, GeoMesh > > &)
Additional Inherited Members
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type, class GeoMesh>
class Foam::DimensionedField< Type, GeoMesh >
Field with dimensions and associated with geometry type GeoMesh which is used to size the field and a reference to it is maintained.
Source files
DimensionedField.H
DimensionedFieldI.H
DimensionedField.C
DimensionedFieldIO.C
Definition at line 51 of file DimensionedField.H.
Member Typedef Documentation
Mesh
typedef GeoMesh::Mesh Mesh
Definition at line 81 of file DimensionedField.H.
cmptType
typedef Field<Type>::cmptType cmptType
Definition at line 82 of file DimensionedField.H.
Constructor & Destructor Documentation
DimensionedField() [1/11]
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, const Field< Type > & field)
Construct from components.
Definition at line 52 of file DimensionedField.C.
Referenced by DimensionedField< Type, Foam::pointMesh >::DimensionedField(), and DimensionedField< Type, Foam::pointMesh >::readField().
DimensionedField() [2/11]
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, const bool checkIOFlags = true)
Construct from components.
Used for temporary fields which are initialised after construction
Definition at line 81 of file DimensionedField.C.
DimensionedField() [3/11]
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensioned< Type > & dt, const bool checkIOFlags = true)
Construct from components.
Definition at line 102 of file DimensionedField.C.
DimensionedField() [4/11]
DimensionedField (const IOobject & io, const Mesh & mesh, const word & fieldDictEntry = "value")
Construct from Istream.
Definition at line 68 of file DimensionedFieldIO.C.
DimensionedField() [5/11]
DimensionedField (const DimensionedField< Type, GeoMesh > & df)
Construct as copy.
Definition at line 123 of file DimensionedField.C.
DimensionedField() [6/11]
DimensionedField (DimensionedField< Type, GeoMesh > & df, bool reUse)
Construct as copy or re-use as specified.
Definition at line 136 of file DimensionedField.C.
DimensionedField() [7/11]
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh > > & df)
Construct by transferring the DimensionedField.
Definition at line 150 of file DimensionedField.C.
DimensionedField() [8/11]
DimensionedField (const IOobject & io, const DimensionedField< Type, GeoMesh > & df)
Construct as copy of tmp<DimensionedField> deleting argument.
Construct as copy resetting IO parameters
Definition at line 184 of file DimensionedField.C.
DimensionedField() [9/11]
DimensionedField (const word & newName, const DimensionedField< Type, GeoMesh > & df)
Construct as copy resetting name.
Definition at line 198 of file DimensionedField.C.
DimensionedField() [10/11]
DimensionedField (const word & newName, DimensionedField< Type, GeoMesh > & df, bool reUse)
Construct as copy resetting name and re-use as specified.
Definition at line 212 of file DimensionedField.C.
DimensionedField() [11/11]
DimensionedField (const word & newName, const Xfer< DimensionedField< Type, GeoMesh > > & df)
Construct by transferring the DimensionedField with a new name.
Definition at line 227 of file DimensionedField.C.
~DimensionedField()
~DimensionedField () virtual
Destructor.
Definition at line 275 of file DimensionedField.C.
Member Function Documentation
TypeName()
TypeName ("DimensionedField< Type, GeoMesh >")
Runtime type information.
null()
const DimensionedField< Type, GeoMesh > & null () inline static
Return a null DimensionedField.
Definition at line 35 of file DimensionedFieldI.H.
Referenced by basicSolidChemistryModel::calculateRR(), fvMeshSubset::interpolate(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvsPatchField< Type >::NewCalculatedType(), pointFieldReconstructor::reconstructField(), and basicSolidChemistryModel::RR().
clone()
tmp< DimensionedField< Type, GeoMesh > > clone () const
Construct as copy resetting name.
Clone
Definition at line 263 of file DimensionedField.C.
Referenced by GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::GeometricBoundaryField().
readField()
void readField (const dictionary & fieldDict, const word & fieldDictEntry = "value")
Definition at line 34 of file DimensionedFieldIO.C.
mesh()
const GeoMesh::Mesh & mesh () const inline
Return mesh.
Definition at line 43 of file DimensionedFieldI.H.
Referenced by isoSurface::adaptPatchFields(), Foam::atan2(), Foam::fvc::average(), motionSmootherAlgo::avg(), blackBodyEmission::blackBodyEmission(), forces::calcForcesMoment(), cellLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), P1::calculate(), Foam::fvc::cellReduce(), Foam::checkMethod(), KinematicCloud< Foam::DsmcCloud >::cloudReset(), Foam::cmptAv(), extendedCellToFaceStencil::collectData(), pointConstraints::constrainDisplacement(), Foam::MULES::correct(), reflectionVectors::correct(), pointPatchDist::correct(), patchDist::correct(), motionSmootherAlgo::correct(), gaussGrad< Type >::correctBoundaryConditions(), motionSmootherAlgo::correctBoundaryConditions(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), motionSmootherAlgo::curPoints(), Foam::fvc::d2dt2(), Foam::fvm::d2dt2(), Foam::fvc::DDt(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvc::ddtCorr(), fvFieldDecomposer::decomposeField(), Foam::fvm::div(), Foam::fvc::div(), blackBodyEmission::EbDeltaLambdaT(), Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), InjectionModel< CloudType >::findCellAtPosition(), Foam::fvc::flux(), fvMatrix< Type >::fvMatrix(), Foam::fvc::grad(), Foam::MULES::implicitSolve(), harmonic::interpolate(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), Foam::fvc::interpolate(), pointMVCWeight::interpolate(), surfaceInterpolationScheme< GType >::interpolate(), volPointInterpolation::interpolate(), fvMeshSubset::interpolate(), volPointInterpolation::interpolateBoundaryField(), volPointInterpolation::interpolateDisplacement(), sampledCuttingPlane::interpolateField(), sampledIsoSurface::interpolateField(), volPointInterpolation::interpolateInternalField(), Foam::interpolatePointToCell(), interpolationCellPoint< Foam::Vector >::interpolationCellPoint(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), Foam::linearInterpolate(), Foam::MULES::LTScorrect(), Foam::mag(), Foam::magSqr(), Foam::fvc::makeAbsolute(), Foam::fvc::makeRelative(), Foam::MapGeometricFields(), fvMeshAdder::MapVolFields(), Foam::fvc::meshPhi(), reuseTmpDimensionedField< TypeR, Type1, GeoMesh >::New(), reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::New(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), radiationModel::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), consumptionSpeed::omega0Sigma(), multivariateIndependentScheme< Type >::operator()(), MRFZoneList::operator()(), RaviPetersen::operator()(), externalDisplacementMeshMover::pMesh(), sampledSurface::pointAverage(), Foam::pow(), Foam::fvc::reconstruct(), fvFieldReconstructor::reconstructFvVolumeField(), Foam::fvc::reconstructMag(), Foam::fvc::scheme(), motionSmootherAlgo::setDisplacementPatchFields(), Foam::setRefCell(), Foam::fvc::smooth(), motionSmootherAlgo::smooth(), snGradScheme< Type >::sndGrad(), Foam::fvc::snGrad(), snGradScheme< Type >::snGrad(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), Foam::fvc::spread(), Foam::sqr(), Foam::stabilise(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), Foam::fvc::sweep(), Foam::transform(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), Foam::fvc::volumeIntegrate(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), Foam::writeCellGraph(), Foam::writePatchGraph(), FSD< CombThermoType, ThermoType >::~FSD(), Gulders::~Gulders(), and GuldersEGR::~GuldersEGR().
dimensions() [1/2]
const dimensionSet & dimensions () const inline
Return dimensions.
Definition at line 50 of file DimensionedFieldI.H.
Referenced by interRegionHeatTransferModel::addSup(), SemiImplicitSource< Type >::addSup(), advectiveFvPatchField< Type >::advectionSpeed(), laminar::alphat(), Foam::atan2(), Foam::fvc::average(), motionSmootherAlgo::avg(), CoBlended< Type >::blendingFactor(), P1::calculate(), Foam::fvc::cellReduce(), Foam::checkMethod(), Foam::cmptAv(), relaxation::correct(), dynOneEqEddy::correct(), SpalartAllmaras::correct(), LRR::correct(), thixotropicViscosity::correct(), LienCubicKELowRe::correct(), LaunderGibsonRSTM::correct(), faceCorrectedSnGrad< Type >::correction(), correctedSnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), limitedSnGrad< Type >::correction(), fvFieldDecomposer::decomposeField(), Foam::fvc::domainIntegrate(), greyMeanAbsorptionEmission::ECont(), wideBandAbsorptionEmission::ECont(), laminar::epsilon(), fluxCorrectedVelocityFvPatchVectorField::evaluate(), yPlusRAS::execute(), yPlusLES::execute(), scalarTransport::execute(), PatchFlowRateInjection< CloudType >::flowRate(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), steadyStateD2dt2Scheme< Type >::fvmD2dt2(), EulerD2dt2Scheme< Type >::fvmD2dt2(), steadyStateDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), SpalartAllmaras::fw(), fvMatrix< Type >::H(), Foam::MULES::implicitSolve(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< GType >::interpolate(), volPointInterpolation::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), laminar::k(), Foam::mag(), Foam::magSqr(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), laminar::mut(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), optionList::operator()(), MRFZoneList::operator()(), DimensionedField< Type, Foam::pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), Foam::pow(), laminar::R(), SpalartAllmaras::r(), Foam::fvc::reconstructMag(), thermoSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), forces::rho(), skewCorrected< Type >::skewCorrection(), snGradScheme< Type >::snGrad(), Foam::sqr(), Foam::stabilise(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), Foam::transform(), fixedShearStressFvPatchVectorField::updateCoeffs(), freestreamPressureFvPatchScalarField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), pressureInletVelocityFvPatchVectorField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), pressureInletOutletParSlipVelocityFvPatchVectorField::updateCoeffs(), pressureNormalInletOutletVelocityFvPatchVectorField::updateCoeffs(), fanPressureFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), pressureDirectedInletVelocityFvPatchVectorField::updateCoeffs(), pressureDirectedInletOutletVelocityFvPatchVectorField::updateCoeffs(), syringePressureFvPatchScalarField::updateCoeffs(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), and FSD< CombThermoType, ThermoType >::~FSD().
dimensions() [2/2]
dimensionSet & dimensions () inline
Return non-const access to dimensions.
Definition at line 56 of file DimensionedFieldI.H.
field() [1/2]
const Field< Type > & field () const inline
Definition at line 63 of file DimensionedFieldI.H.
Referenced by Foam::atan2(), Foam::checkMethod(), Foam::cmptAv(), Foam::mag(), Foam::magSqr(), Foam::pow(), fvFieldReconstructor::reconstructFvVolumeInternalField(), Foam::sqr(), Foam::stabilise(), and Foam::fvc::volumeIntegrate().
field() [2/2]
Field< Type > & field () inline
Definition at line 69 of file DimensionedFieldI.H.
component()
tmp<DimensionedField<cmptType, GeoMesh> > component (const direction) const
Return a component field of the field.
Referenced by DimensionedField< Type, Foam::pointMesh >::~DimensionedField().
replace() [1/2]
void replace (const direction , const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
Referenced by DimensionedField< Type, Foam::pointMesh >::~DimensionedField().
replace() [2/2]
void replace (const direction , const tmp< DimensionedField< cmptType, GeoMesh > > &)
Replace a component field of the field.
T()
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
Definition at line 343 of file DimensionedField.C.
average()
dimensioned< Type > average () const
Calculate and return arithmetic average.
Definition at line 367 of file DimensionedField.C.
weightedAverage() [1/2]
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > & weightField) const
Calculate and return weighted average.
Definition at line 382 of file DimensionedField.C.
Referenced by DimensionedField< Type, Foam::pointMesh >::average(), and DimensionedField< Type, Foam::pointMesh >::weightedAverage().
weightedAverage() [2/2]
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh > > & tweightField) const
Calculate and return weighted average.
Definition at line 400 of file DimensionedField.C.
writeData() [1/2]
bool writeData (Ostream & os, const word & fieldDictEntry) const
Definition at line 87 of file DimensionedFieldIO.C.
Referenced by DimensionedField< Type, Foam::pointMesh >::DimensionedField().
writeData() [2/2]
bool writeData (Ostream &) const virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Reimplemented in GeometricField< Type, PatchField, GeoMesh >, GeometricField< symmTensor, fvPatchField, volMesh >, GeometricField< tensor, fvPatchField, volMesh >, GeometricField< vector, fvsPatchField, surfaceMesh >, GeometricField< scalar, fvPatchField, volMesh >, GeometricField< scalar, fvsPatchField, surfaceMesh >, GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh >, GeometricField< scalar, pointPatchField, pointMesh >, GeometricField< vector, fvPatchField, volMesh >, GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh >, and GeometricField< vector, pointPatchField, pointMesh >.
Definition at line 109 of file DimensionedFieldIO.C.
operator=() [1/3]
void operator= (const DimensionedField< Type, GeoMesh > & df)
Definition at line 414 of file DimensionedField.C.
operator=() [2/3]
void operator= (const tmp< DimensionedField< Type, GeoMesh > > & tdf)
Definition at line 438 of file DimensionedField.C.
operator=() [3/3]
void operator= (const dimensioned< Type > & dt)
Definition at line 465 of file DimensionedField.C.
operator+=() [1/3]
void operator+= (const DimensionedField< Type, GeoMesh > & df)
Definition at line 508 of file DimensionedField.C.
operator+=() [2/3]
void operator+= (const tmp< DimensionedField< Type, GeoMesh > > & tdf)
Definition at line 508 of file DimensionedField.C.
operator-=() [1/3]
void operator-= (const DimensionedField< Type, GeoMesh > & df)
Definition at line 509 of file DimensionedField.C.
operator-=() [2/3]
void operator-= (const tmp< DimensionedField< Type, GeoMesh > > & tdf)
Definition at line 509 of file DimensionedField.C.
operator*=() [1/3]
void operator*= (const DimensionedField< scalar, GeoMesh > & df)
Definition at line 510 of file DimensionedField.C.
operator*=() [2/3]
void operator*= (const tmp< DimensionedField< scalar, GeoMesh > > & tdf)
Definition at line 510 of file DimensionedField.C.
operator/=() [1/3]
void operator/= (const DimensionedField< scalar, GeoMesh > & df)
Definition at line 511 of file DimensionedField.C.
operator/=() [2/3]
void operator/= (const tmp< DimensionedField< scalar, GeoMesh > > & tdf)
Definition at line 511 of file DimensionedField.C.
operator+=() [3/3]
void operator+= (const dimensioned< Type > & dt)
Definition at line 508 of file DimensionedField.C.
operator-=() [3/3]
void operator-= (const dimensioned< Type > & dt)
Definition at line 509 of file DimensionedField.C.
operator*=() [3/3]
void operator*= (const dimensioned< scalar > & dt)
Definition at line 510 of file DimensionedField.C.
operator/=() [3/3]
void operator/= (const dimensioned< scalar > & dt)
Definition at line 511 of file DimensionedField.C.
Friends And Related Function Documentation
operator [1/2]
Ostream& operator (Ostream & , const DimensionedField< Type, GeoMesh > &) friend
operator [2/2]
Ostream& operator (Ostream & , const tmp< DimensionedField< Type, GeoMesh > > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedField.H
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedField.C
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldI.H
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldIO.C