OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dimensioned< Type > Class Template Reference
Generic dimensioned Type class.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Member Functions
dimensioned (const word &, const dimensionSet &, const Type)
Construct given a name, a value and its dimensionSet.
dimensioned (const word &, const dimensioned< Type > &)
Construct from a dimensioned<Type> changing the name.
dimensioned (const Type &t)
Construct given a value (creates dimensionless value).
dimensioned (Istream &)
Construct from Istream.
dimensioned (const word &, Istream &)
Construct from an Istream with a given name.
dimensioned (const word &, const dimensionSet &, Istream &)
Construct from an Istream with a given name and dimensions.
dimensioned ()
Null constructor.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const Type & value () const
Return const reference to value.
Type & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction) const
Return a component as a dimensioned<cmptType>
void replace (const direction, const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
dimensioned< Type > T () const
Return transpose.
void read (const dictionary &)
Update the value of dimensioned<Type>
bool readIfPresent (const dictionary &)
Update the value of dimensioned<Type> if found in the dictionary.
Istream & read (Istream &is, const dictionary &)
Read value from stream and units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &)
Read value from stream and units from table.
Istream & read (Istream &is)
Read value from stream and units from system table.
dimensioned< cmptType > operator[] (const direction) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Member Functions
static dimensioned< Type > lookupOrDefault (const word &, const dictionary &, const Type &defaultValue=pTraits< Type >::zero, const dimensionSet &dims=dimless)
Construct from dictionary, with default value.
static dimensioned< Type > lookupOrAddToDict (const word &, dictionary &, const Type &defaultValue=pTraits< Type >::zero, const dimensionSet &dims=dimless)
Construct from dictionary, with default value.
Friends
Istream & operator>> (Istream &, dimensioned< Type > &)
Ostream & operator (Ostream &, const dimensioned< Type > &)
Detailed Description
template<class Type>
class Foam::dimensioned< Type >
Generic dimensioned Type class.
Source files
dimensionedType.H
dimensionedType.C
Definition at line 41 of file dimensionedScalarFwd.H.
Member Typedef Documentation
cmptType
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 81 of file dimensionedType.H.
Constructor & Destructor Documentation
dimensioned() [1/7]
dimensioned (const word & name, const dimensionSet & dimSet, const Type t)
Construct given a name, a value and its dimensionSet.
Definition at line 64 of file dimensionedType.C.
dimensioned() [2/7]
dimensioned (const word & name, const dimensioned< Type > & dt)
Construct from a dimensioned<Type> changing the name.
Definition at line 78 of file dimensionedType.C.
dimensioned() [3/7]
dimensioned (const Type & t) inline
Construct given a value (creates dimensionless value).
Definition at line 93 of file dimensionedType.H.
dimensioned() [4/7]
dimensioned (Istream & is)
Construct from Istream.
Definition at line 91 of file dimensionedType.C.
dimensioned() [5/7]
dimensioned (const word & name, Istream & is)
Construct from an Istream with a given name.
Definition at line 103 of file dimensionedType.C.
dimensioned() [6/7]
dimensioned (const word & name, const dimensionSet & dimSet, Istream & is)
Construct from an Istream with a given name and dimensions.
Definition at line 120 of file dimensionedType.C.
dimensioned() [7/7]
dimensioned ()
Null constructor.
Definition at line 171 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned(), and dimensioned< vector >::lookupOrAddToDict().
Member Function Documentation
lookupOrDefault()
Foam::dimensioned< Type > lookupOrDefault (const word & name, const dictionary & dict, const Type & defaultValue = pTraits<Type>::zero, const dimensionSet & dims = dimless) static
Construct from dictionary, with default value.
Definition at line 34 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned().
lookupOrAddToDict()
Foam::dimensioned< Type > lookupOrAddToDict (const word & name, dictionary & dict, const Type & defaultValue = pTraits<Type>::zero, const dimensionSet & dims = dimless) static
Construct from dictionary, with default value.
If the value is not found, it is added into the dictionary.
Definition at line 48 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned(), and dimensioned< vector >::lookupOrDefault().
name() [1/2]
const Foam::word & name () const
Return const reference to name.
Definition at line 182 of file dimensionedType.C.
Referenced by Foam::atan2(), Foam::cbrt(), Foam::checkMethod(), Foam::cof(), Foam::fvm::d2dt2(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::det(), Foam::dev(), Foam::dev2(), dimensioned< vector >::dimensioned(), Foam::eigenValues(), Foam::eigenVectors(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::hypot(), Foam::inv(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::meshPhi(), Foam::neg(), Foam::operator*(), dimensioned< vector >::operator/=(), Foam::operator<(), Foam::pos(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), Time::readDict(), Time::runTimeModifiable(), Foam::sign(), Foam::skew(), Foam::sqr(), Foam::sqrt(), Foam::stabilise(), Foam::symm(), dimensioned< vector >::T(), Foam::tr(), Foam::transform(), Foam::twoSymm(), and dimensionSet::write().
name() [2/2]
Foam::word & name ()
Return non-const reference to name.
Definition at line 188 of file dimensionedType.C.
dimensions() [1/2]
const Foam::dimensionSet & dimensions () const
Return const reference to dimensions.
Definition at line 195 of file dimensionedType.C.
Referenced by Foam::atan2(), Foam::cbrt(), Foam::checkMethod(), Foam::cof(), Foam::det(), Foam::dev(), Foam::dev2(), dimensioned< vector >::dimensioned(), dimensionSet::dimensionSet(), dimensionSets::dimensionSets(), Foam::eigenValues(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), steadyStateD2dt2Scheme< Type >::fvmD2dt2(), EulerD2dt2Scheme< Type >::fvmD2dt2(), steadyStateDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::hypot(), Foam::inv(), Foam::neg(), Foam::operator*(), dimensioned< vector >::operator/=(), Foam::operator<(), DimensionedField< Type, Foam::pointMesh >::operator=(), Foam::pos(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), dimensionSet::read(), Foam::sign(), Foam::skew(), Foam::sqr(), Foam::sqrt(), Foam::stabilise(), Foam::symm(), dimensioned< vector >::T(), Foam::tr(), and Foam::twoSymm().
dimensions() [2/2]
Foam::dimensionSet & dimensions ()
Return non-const reference to dimensions.
Definition at line 201 of file dimensionedType.C.
value() [1/2]
const Type & value () const
Return const reference to value.
Definition at line 208 of file dimensionedType.C.
Referenced by fieldAverage::addMeanFieldType(), fieldAverage::addPrime2MeanFieldType(), interRegionHeatTransferModel::addSup(), porosityModel::adjustNegativeResistance(), Foam::atan2(), Foam::bound(), NonInertialFrameForce< CloudType >::cacheFields(), BrownianMotionForce< CloudType >::calcCoupled(), ThermoParcel< ParcelType >::calcHeatTransfer(), SRFForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::calcNonCoupled(), wallShearStress::calcShearStress(), viewFactor::calculate(), Foam::cbrt(), Foam::cof(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), LRRDiffStress::correct(), DeardorffDiffStress::correct(), LienLeschzinerLowRe::correct(), dynLagrangian::correct(), LRR::correct(), LaunderGibsonRSTM::correct(), functionObjectFile::createFiles(), particle< Type >::currentTime(), curvatureSeparation::curvatureSeparation(), engineTime::degToTime(), Foam::det(), Foam::dev(), Foam::dev2(), dimensioned< vector >::dimensioned(), dimensionSet::dimensionSet(), GenSGSStress::divDevReff(), LRR::divDevReff(), LaunderGibsonRSTM::divDevReff(), GenSGSStress::divDevRhoReff(), LRR::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), blackBodyEmission::EbDeltaLambdaT(), Foam::eigenValues(), Foam::eigenVectors(), engineMesh::engineMesh(), engineTime::engineTime(), ThermoCloud< Foam::DsmcCloud >::Ep(), DsmcCloud< DsmcParcel< ParcelType > >::equipartitionInternalEnergy(), basicMultiComponentMixture::fres(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::hypot(), if(), ignitionSite::ignited(), ignitionSite::igniting(), reactingOneDim::info(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), option::inTimeLimits(), Foam::inv(), hexRef8::level0EdgeLength(), MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField(), GeometricField< vector, pointPatchField, pointMesh >::max(), GeometricField< vector, pointPatchField, pointMesh >::min(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), polyMesh::movePoints(), movingConeTopoFvMesh::movingConeTopoFvMesh(), NamedEnum< directionType, 3 >::names(), Foam::neg(), Foam::operator*(), Time::operator+=(), dimensioned< vector >::operator/=(), Foam::operator<(), Foam::operator<<(), DimensionedField< Type, Foam::pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator==(), Foam::operator>(), Foam::operator>>(), UniformDimensionedField< scalar >::operator[](), PatchFlowRateInjection< CloudType >::parcelsToInject(), engineTime::pistonDisplacement(), engineTime::pistonPosition(), engineTime::pistonSpeed(), Foam::pos(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), thermalBaffleModel::read(), GenSGSStress::read(), LRR::read(), LaunderGibsonRSTM::read(), dimensionSet::read(), Time::readDict(), GeometricField< vector, pointPatchField, pointMesh >::replace(), incompressibleTwoPhaseInteractingMixture::rho(), timeSelector::selectIfPresent(), Time::setDeltaT(), Time::setEndTime(), Time::setTime(), fixedTemperatureConstraint::setValue(), constantRadiation::Shs(), Foam::sign(), simpleControl::simpleControl(), Foam::skew(), sixDoFRigidBodyMotionSolver::solve(), thermalBaffle::solveEnergy(), Foam::sqr(), Foam::sqrt(), Foam::stabilise(), Foam::symm(), dimensioned< vector >::T(), engineTime::theta(), TimeState::timeOutputValue(), engineTime::timeToDeg(), Foam::tr(), Foam::transform(), Foam::twoSymm(), dynamicInkJetFvMesh::update(), movingConeTopoFvMesh::update(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), MarshakRadiationFvPatchScalarField::updateCoeffs(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), uniformDensityHydrostaticPressureFvPatchScalarField::updateCoeffs(), PatchFlowRateInjection< CloudType >::volumeToInject(), fvMesh::Vsc(), fvMesh::Vsc0(), wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField(), FacePostProcessing< CloudType >::write(), ParticleCollector< CloudType >::write(), dimensionSet::write(), Time::writeAndEnd(), Time::writeObject(), and FSD< CombThermoType, ThermoType >::~FSD().
value() [2/2]
Type & value ()
Return non-const reference to value.
Definition at line 214 of file dimensionedType.C.
component()
Foam::dimensioned< typename Foam::dimensioned< Type >::cmptType > component (const direction d) const
Return a component as a dimensioned<cmptType>
Definition at line 223 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned(), and dimensioned< vector >::value().
replace()
void replace (const direction , const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
Definition at line 238 of file dimensionedType.C.
Referenced by dimensioned< vector >::component(), and dimensioned< vector >::dimensioned().
T()
dimensionedTensor T () const
Return transpose.
Definition at line 36 of file dimensionedSphericalTensor.C.
Referenced by dimensioned< vector >::dimensioned(), and dimensioned< vector >::T().
read() [1/4]
void read (const dictionary & dict)
Update the value of dimensioned<Type>
Definition at line 249 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned(), dimensioned< vector >::read(), dimensionSet::read(), and Foam::unitSet().
readIfPresent()
bool readIfPresent (const dictionary & dict)
Update the value of dimensioned<Type> if found in the dictionary.
Definition at line 256 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned(), kOmegaSSTSAS::kOmegaSSTSAS(), LESModel::LESModel(), RASModel::RASModel(), spectEddyVisc::read(), LRRDiffStress::read(), SpalartAllmarasIDDES::read(), DeardorffDiffStress::read(), lowReOneEqEddy::read(), Smagorinsky::read(), oneEqEddy::read(), GenEddyVisc::read(), LamBremhorstKE::read(), LienLeschzinerLowRe::read(), LienCubicKE::read(), NonlinearKEShih::read(), dynLagrangian::read(), GenSGSStress::read(), SpalartAllmaras::read(), kEpsilon::read(), RNGkEpsilon::read(), LRR::read(), realizableKE::read(), LaunderSharmaKE::read(), LienCubicKELowRe::read(), LaunderGibsonRSTM::read(), kOmega::read(), qZeta::read(), RASModel::read(), v2f::read(), kOmegaSSTSAS::read(), LESModel::read(), kOmegaSST::read(), and kkLOmega::read().
read() [2/4]
Foam::Istream & read (Istream & is, const dictionary & readSet)
Read value from stream and units from dictionary.
Definition at line 264 of file dimensionedType.C.
read() [3/4]
Foam::Istream & read (Istream & is, const HashTable< dimensionedScalar > & readSet)
Read value from stream and units from table.
Definition at line 289 of file dimensionedType.C.
read() [4/4]
Foam::Istream & read (Istream & is)
Read value from stream and units from system table.
Definition at line 317 of file dimensionedType.C.
operator[]()
Foam::dimensioned< typename Foam::dimensioned< Type >::cmptType > operator[] (const direction d) const
Return a component as a dimensioned<cmptType>
Definition at line 345 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned().
operator+=()
void operator+= (const dimensioned< Type > & dt)
Definition at line 355 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned().
operator-=()
void operator-= (const dimensioned< Type > & dt)
Definition at line 366 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned().
operator*=()
void operator*= (const scalar s)
Definition at line 377 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned().
operator/=()
void operator/= (const scalar s)
Definition at line 387 of file dimensionedType.C.
Referenced by dimensioned< vector >::dimensioned().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , dimensioned< Type > &) friend
operator
Ostream& operator (Ostream & , const dimensioned< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionedTypes/dimensionedScalar/dimensionedScalarFwd.H
src/OpenFOAM/dimensionedTypes/dimensionedType/dimensionedType.H
src/OpenFOAM/dimensionedTypes/dimensionedSphericalTensor/dimensionedSphericalTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedSymmTensor/dimensionedSymmTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedTensor/dimensionedTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedType/dimensionedType.C