OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dimensionSets Class Reference
Public Member Functions
dimensionSets (const HashTable< dimensionedScalar > &, const wordList &unitNames)
Construct from all units and set of units to use for inversion.
const PtrList< dimensionedScalar > & units () const
Return the units.
bool valid () const
Is there a valid inverse of the selected unit.
void coefficients (scalarField &) const
(if valid) obtain set of coefficients of unitNames
Detailed Description
Definition at line 74 of file dimensionSets.H.
Constructor & Destructor Documentation
dimensionSets()
dimensionSets (const HashTable< dimensionedScalar > & units, const wordList & unitNames)
Construct from all units and set of units to use for inversion.
(writing)
Definition at line 208 of file dimensionSets.C.
References dimensioned< Type >::dimensions(), forAll, Foam::LUDecompose(), and List< T >::size().
Referenced by Foam::writeUnitSet().
Member Function Documentation
units()
const PtrList<dimensionedScalar>& units () const inline
Return the units.
Definition at line 105 of file dimensionSets.H.
Referenced by dimensionSet::write().
valid()
bool valid () const inline
Is there a valid inverse of the selected unit.
Definition at line 111 of file dimensionSets.H.
References dimensionSets::coefficients(), Foam::dimensionSystems(), Foam::unitSet(), and Foam::writeUnitSet().
Referenced by dimensionSet::write().
coefficients()
void coefficients (scalarField & exponents) const
(if valid) obtain set of coefficients of unitNames
Definition at line 251 of file dimensionSets.C.
References Foam::LUBacksubstitute().
Referenced by dimensionSets::valid(), and dimensionSet::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionSet/dimensionSets.H
src/OpenFOAM/dimensionSet/dimensionSets.C