OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Time Class Reference
Class to control time during OpenFOAM simulations that is also the top-level objectRegistry.
Public Types
enum writeControls {
wcTimeStep, wcRunTime, wcAdjustableRunTime, wcClockTime,
wcCpuTime
}
Write control options.
enum stopAtControls { saEndTime, saNoWriteNow, saWriteNow, saNextWrite }
Stop-run control options.
enum fmtflags { general = 0, fixed = ios_base::fixed, scientific = ios_base::scientific }
Supported time directory name formats.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from dimensioned< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Member Functions
TypeName ("time")
Time (const word &name, const argList &args, const word &systemName="system", const word &constantName="constant")
Construct given name of dictionary to read and argument list.
Time (const word &name, const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant", const bool enableFunctionObjects=true)
Construct given name of dictionary to read, rootPath and casePath.
Time (const dictionary &dict, const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant", const bool enableFunctionObjects=true)
Construct given dictionary, rootPath and casePath.
Time (const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant", const bool enableFunctionObjects=true)
Construct given endTime, rootPath and casePath.
virtual ~Time ()
Destructor.
const fileName & rootPath () const
Return root path.
const fileName & caseName () const
Return case name.
fileName path () const
Return path.
const dictionary & controlDict () const
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
fileName timePath () const
Return current time path.
IOstream::streamFormat writeFormat () const
Default write format.
IOstream::versionNumber writeVersion () const
Default write version number.
IOstream::compressionType writeCompression () const
Default write compression.
const word & graphFormat () const
Default graph format.
const Switch & runTimeModifiable () const
Supports re-reading.
virtual bool read ()
Read control dictionary, update controls and time.
void readModifiedObjects ()
Read the objects that have been modified.
label addWatch (const fileName &) const
Add watching of a file. Returns handle.
bool removeWatch (const label) const
Remove watch on a file (using handle)
const fileName & getFile (const label) const
Get name of file being watched (using handle)
fileMonitor::fileState getState (const label) const
Get current state of file (using handle)
void setUnmodified (const label) const
Set current state of file (using handle) to unmodified.
word findInstance (const fileName &dir, const word &name=word::null, const IOobject::readOption rOpt=IOobject::MUST_READ, const word &stopInstance=word::null) const
Return the location of "dir" containing the file "name".
instantList times () const
Search the case for valid time directories.
word findInstancePath (const instant &) const
Search the case for the time directory path.
instant findClosestTime (const scalar) const
Search the case for the time closest to the given time.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
bool writeNow ()
Write the objects now (not at end of iteration) and continue.
bool writeAndEnd ()
Write the objects now (not at end of iteration) and end the run.
void writeOnce ()
Write the objects once (one shot) and continue the run.
virtual word timeName () const
Return current time name.
virtual label startTimeIndex () const
Return start time index.
virtual dimensionedScalar startTime () const
Return start time.
virtual dimensionedScalar endTime () const
Return end time.
const functionObjectList & functionObjects () const
Return the list of function objects.
const dlLibraryTable & libs () const
External access to the loaded libraries.
dlLibraryTable & libs ()
External access to the loaded libraries.
bool subCycling () const
Return true if time currently being sub-cycled, otherwise false.
const TimeState & prevTimeState () const
Return previous TimeState if time is being sub-cycled.
virtual bool run () const
Return true if run should continue,.
virtual bool loop ()
Return true if run should continue and if so increment time.
virtual bool end () const
Return true if end of run,.
virtual bool stopAt (const stopAtControls) const
Adjust the current stopAtControl. Note that this value.
virtual void setTime (const Time &)
Reset the time and time-index to those of the given time.
virtual void setTime (const instant &, const label newIndex)
Reset the time and time-index.
virtual void setTime (const dimensionedScalar &, const label newIndex)
Reset the time and time-index.
virtual void setTime (const scalar, const label newIndex)
Reset the time and time-index.
virtual void setEndTime (const dimensionedScalar &)
Reset end time.
virtual void setEndTime (const scalar)
Reset end time.
virtual void setDeltaT (const dimensionedScalar &, const bool adjustDeltaT=true)
Reset time step.
virtual void setDeltaT (const scalar, const bool adjustDeltaT=true)
Reset time step.
virtual TimeState subCycle (const label nSubCycles)
Set time to sub-cycle for the given number of steps.
virtual void endSubCycle ()
Reset time after sub-cycling back to previous TimeState.
functionObjectList & functionObjects ()
Return non-const access to the list of function objects.
virtual Time & operator+= (const dimensionedScalar &)
Set deltaT to that specified and increment time via operator++()
virtual Time & operator+= (const scalar)
Set deltaT to that specified and increment time via operator++()
virtual Time & operator++ ()
Prefix increment,.
virtual Time & operator++ (int)
Postfix increment, this is identical to the prefix increment.
Public Member Functions inherited from clock
clock ()
Null constructor which stores the start time.
time_t elapsedClockTime () const
Returns wall-clock time from clock instantiation.
time_t clockTimeIncrement () const
Returns wall-clock time from last call of clockTimeIncrement()
Public Member Functions inherited from cpuTime
cpuTime ()
Construct with the current clock time.
double elapsedCpuTime () const
Return CPU time (in seconds) from the start.
double cpuTimeIncrement () const
Return CPU time (in seconds) since last call to cpuTimeIncrement()
Public Member Functions inherited from TimePaths
TimePaths (const fileName &rootPath, const fileName &caseName, const word &systemName, const word &constantName)
Construct given database name, rootPath and casePath.
TimePaths (const bool processorCase, const fileName &rootPath, const fileName &globalCaseName, const fileName &caseName, const word &systemName, const word &constantName)
Construct given database name, rootPath and casePath.
bool processorCase () const
Return true if this is a processor case.
const fileName & rootPath () const
Return root path.
const fileName & globalCaseName () const
Return global case name.
const fileName & caseName () const
Return case name.
const word & system () const
Return system name.
fileName caseSystem () const
Return system name for the case.
const word & constant () const
Return constant name.
fileName caseConstant () const
Return constant name for the case.
fileName path () const
Return path.
fileName systemPath () const
Return system path.
fileName constantPath () const
Return constant path.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash > > &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from TimeState
TimeState ()
virtual ~TimeState ()
Destructor.
virtual scalar userTimeToTime (const scalar theta) const
Convert the user-time (e.g. CA deg) to real-time (s).
virtual scalar timeToUserTime (const scalar t) const
Convert the real-time (s) into user-time (e.g. CA deg)
scalar timeOutputValue () const
Return current time value.
label timeIndex () const
Return current time index.
scalar deltaTValue () const
Return time step value.
scalar deltaT0Value () const
Return old time step value.
dimensionedScalar deltaT () const
Return time step.
dimensionedScalar deltaT0 () const
Return old time step.
bool outputTime () const
Return true if this is an output time (primary or secondary)
Public Member Functions inherited from dimensioned< Type >
dimensioned (const word &, const dimensionSet &, const Type)
Construct given a name, a value and its dimensionSet.
dimensioned (const word &, const dimensioned< Type > &)
Construct from a dimensioned<Type> changing the name.
dimensioned (const Type &t)
Construct given a value (creates dimensionless value).
dimensioned (Istream &)
Construct from Istream.
dimensioned (const word &, Istream &)
Construct from an Istream with a given name.
dimensioned (const word &, const dimensionSet &, Istream &)
Construct from an Istream with a given name and dimensions.
dimensioned ()
Null constructor.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const Type & value () const
Return const reference to value.
Type & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction) const
Return a component as a dimensioned<cmptType>
void replace (const direction, const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
dimensioned< Type > T () const
Return transpose.
void read (const dictionary &)
Update the value of dimensioned<Type>
bool readIfPresent (const dictionary &)
Update the value of dimensioned<Type> if found in the dictionary.
Istream & read (Istream &is, const dictionary &)
Read value from stream and units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &)
Read value from stream and units from table.
Istream & read (Istream &is)
Read value from stream and units from system table.
dimensioned< cmptType > operator[] (const direction) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Member Functions
static label findClosestTimeIndex (const instantList &, const scalar, const word &constantName="constant")
Search instantList for the time index closest to the given time.
static word timeName (const scalar)
Return time name of given scalar time.
static instantList findTimes (const fileName &, const word &constantName="constant")
Search a given directory for valid time directories.
Static Public Member Functions inherited from clock
static time_t getTime ()
Get the current clock time in seconds.
static const struct tm rawDate ()
Return the current wall-clock date as a raw struct.
static string dateTime ()
Return the current wall-clock date/time as a string.
static string date ()
Return the current wall-clock date as a string.
static string clockTime ()
Return the current wall-clock time as a string.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Member Functions inherited from dimensioned< Type >
static dimensioned< Type > lookupOrDefault (const word &, const dictionary &, const Type &defaultValue=pTraits< Type >::zero, const dimensionSet &dims=dimless)
Construct from dictionary, with default value.
static dimensioned< Type > lookupOrAddToDict (const word &, dictionary &, const Type &defaultValue=pTraits< Type >::zero, const dimensionSet &dims=dimless)
Construct from dictionary, with default value.
Static Public Attributes
static word controlDictName
The default control dictionary name (normally "controlDict")
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions
void adjustDeltaT ()
Adjust the time step so that writing occurs at the specified time.
void setControls ()
Set the controls from the current controlDict.
virtual void readDict ()
Read the control dictionary and set the write controls etc.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
label startTimeIndex_
scalar startTime_
scalar endTime_
stopAtControls stopAt_
writeControls writeControl_
scalar writeInterval_
writeControls secondaryWriteControl_
scalar secondaryWriteInterval_
label purgeWrite_
FIFOStack< word > previousOutputTimes_
label secondaryPurgeWrite_
FIFOStack< word > previousSecondaryOutputTimes_
bool writeOnce_
bool subCycling_
Is the time currently being sub-cycled?
autoPtr< TimeState > prevTimeState_
If time is being sub-cycled this is the previous TimeState.
sigWriteNow sigWriteNow_
Enable one-shot writing upon signal.
sigStopAtWriteNow sigStopAtWriteNow_
Enable write and clean exit upon signal.
Protected Attributes inherited from TimeState
label timeIndex_
scalar deltaT_
scalar deltaTSave_
scalar deltaT0_
bool deltaTchanged_
label outputTimeIndex_
bool primaryOutputTime_
Is outputTime because of primary?
label secondaryOutputTimeIndex_
bool secondaryOutputTime_
Is outputTime because of secondary?
bool outputTime_
Static Protected Attributes
static const NamedEnum< stopAtControls, 4 > stopAtControlNames_
static const NamedEnum< writeControls, 5 > writeControlNames_
static fmtflags format_
Time directory name format.
static int precision_
Time directory name precision.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Class to control time during OpenFOAM simulations that is also the top-level objectRegistry.
Source files
Time.H
Time.C
TimeIO.C
findInstance.C
Definition at line 68 of file Time.H.
Member Enumeration Documentation
writeControls
enum writeControls
Write control options.
Enumerator
wcTimeStep
wcRunTime
wcAdjustableRunTime
wcClockTime
wcCpuTime
Definition at line 91 of file Time.H.
stopAtControls
enum stopAtControls
Stop-run control options.
Enumerator
saEndTime
stop when Time reaches the prescribed endTime
saNoWriteNow
set endTime to stop immediately w/o writing
saWriteNow
set endTime to stop immediately w/ writing
saNextWrite
stop the next time data are written
Definition at line 101 of file Time.H.
fmtflags
enum fmtflags
Supported time directory name formats.
Enumerator
general
fixed
scientific
Definition at line 110 of file Time.H.
Constructor & Destructor Documentation
Time() [1/4]
Time (const word & name, const argList & args, const word & systemName = "system", const word & constantName = "constant")
Construct given name of dictionary to read and argument list.
Definition at line 380 of file Time.C.
References f(), regIOobject::fileModificationChecking, IOobject::MUST_READ_IF_MODIFIED, and List< T >::size().
Referenced by Time::setControls(), and Time::Time().
Time() [2/4]
Time (const word & name, const fileName & rootPath, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant", const bool enableFunctionObjects = true)
Construct given name of dictionary to read, rootPath and casePath.
Definition at line 285 of file Time.C.
References f(), regIOobject::fileModificationChecking, IOobject::MUST_READ_IF_MODIFIED, List< T >::size(), and Time::Time().
Time() [3/4]
Time (const dictionary & dict, const fileName & rootPath, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant", const bool enableFunctionObjects = true)
Construct given dictionary, rootPath and casePath.
Definition at line 481 of file Time.C.
References f(), regIOobject::fileModificationChecking, IOobject::MUST_READ_IF_MODIFIED, List< T >::size(), and Time::Time().
Time() [4/4]
Time (const fileName & rootPath, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant", const bool enableFunctionObjects = true)
Construct given endTime, rootPath and casePath.
Definition at line 581 of file Time.C.
~Time()
~Time () virtual
Destructor.
Definition at line 642 of file Time.C.
Member Function Documentation
adjustDeltaT()
void adjustDeltaT () protected
Adjust the time step so that writing occurs at the specified time.
Definition at line 80 of file Time.C.
References Foam::max(), and Foam::min().
Referenced by Time::prevTimeState().
setControls()
void setControls () protected
Set the controls from the current controlDict.
Definition at line 137 of file Time.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, IOWarningIn, UList< T >::last(), Foam::mag(), UPstream::myProcNo(), Foam::name(), Foam::nl, IOobject::NO_WRITE, UPstream::nProcs(), UPstream::parRun(), path(), IOobject::READ_IF_PRESENT, dictionary::readIfPresent(), Foam::reduce(), setTime(), List< T >::size(), Time::Time(), timeDirs, and timeName.
readDict()
void readDict () protected virtual
Read the control dictionary and set the write controls etc.
Reimplemented in engineTime.
Definition at line 33 of file TimeIO.C.
References IOstream::ASCII, IOstream::compressionEnum(), Foam::debug::debugObjects(), IOstream::defaultPrecision(), TimeState::deltaT_, TimeState::deltaTchanged_, dict, Foam::debug::dimensionedConstantObjects(), Foam::dimensionedConstants(), Foam::debug::dimensionSetObjects(), Foam::dimensionSystems(), Foam::endl(), Time::endTime_, Foam::exit(), Foam::FatalError, Foam::FatalIOError, FatalIOErrorIn, Time::fixed, forAll, forAllConstIter(), Time::format_, IOstream::formatEnum(), dictionary::found(), Time::general, Foam::Info, dictionary::lookup(), DictionaryBase< IDLListType, T >::lookupPtr(), dictionary::merge(), IOdictionary::name(), dimensioned< Type >::name(), dimensioned< scalar >::name(), Foam::debug::optimisationObjects(), TimeState::outputTimeIndex_, Foam::Perr, Foam::Pout, OSstream::precision(), Time::precision_, Time::purgeWrite_, NamedEnum< Enum, nEnum >::read(), dictionary::readIfPresent(), Foam::readScalar(), Foam::readUint(), Time::removeWatch(), Time::saEndTime, Time::scientific, TimeState::secondaryOutputTimeIndex_, Time::secondaryPurgeWrite_, Time::secondaryWriteControl_, Time::secondaryWriteInterval_, Foam::Serr, Foam::setEnv(), Foam::Sout, Time::stopAt_, Time::stopAtControlNames_, OStringStream::str(), dictionary::subDict(), Time::timeName(), dimensioned< Type >::value(), WarningIn, regIOobject::watchIndex(), Time::wcAdjustableRunTime, Time::wcRunTime, Time::wcTimeStep, Time::writeControl_, Time::writeControlNames_, and Time::writeInterval_.
Referenced by Time::read(), engineTime::readDict(), and Time::readModifiedObjects().
TypeName()
TypeName ("time")
rootPath()
const fileName& rootPath () const inline
Return root path.
Definition at line 266 of file Time.H.
References TimePaths::rootPath().
Referenced by Time::path().
caseName()
const fileName& caseName () const inline
Return case name.
Definition at line 272 of file Time.H.
References TimePaths::caseName().
Referenced by Time::path(), triSurface::triSurface(), triSurface::triSurfInstance(), and triSurface::write().
path()
fileName path () const inline
Return path.
Definition at line 278 of file Time.H.
References Time::caseName(), and Time::rootPath().
Referenced by autoLayerDriver::addLayers(), autoRefineDriver::autoRefineDriver(), meshRefinement::baffleAndSplitMesh(), functionObjectFile::baseFileDir(), nearWallFields::calcAddressing(), meshRefinement::createZoneBaffles(), autoSnapDriver::detectNearSurfaces(), autoSnapDriver::doSnap(), edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), meshRefinement::mergeBaffles(), listPlusEqOp< T >::operator()(), autoSnapDriver::preSmoothPatch(), polyMesh::removeFiles(), cyclicAMIPolyPatch::resetAMI(), duplicatePoints::setRefinement(), autoSnapDriver::smoothDisplacement(), Time::timePath(), triSurface::triSurface(), triSurface::triSurfInstance(), streamLine::write(), wallBoundedStreamLine::write(), triSurface::write(), and Foam::writeCellGraph().
controlDict()
const dictionary& controlDict () const inline
Definition at line 283 of file Time.H.
dbDir()
virtual const fileName& dbDir () const inline virtual
Local directory path of this objectRegistry relative to the time.
Reimplemented from objectRegistry.
Definition at line 288 of file Time.H.
References fileName::null.
timePath()
fileName timePath () const inline
Return current time path.
Definition at line 294 of file Time.H.
References Time::path(), and Time::timeName().
Referenced by MeshedSurfaceProxy< Face >::write(), molecule::writeFields(), and Foam::writePatchGraph().
writeFormat()
IOstream::streamFormat writeFormat () const inline
Default write format.
Definition at line 300 of file Time.H.
writeVersion()
IOstream::versionNumber writeVersion () const inline
Default write version number.
Definition at line 306 of file Time.H.
writeCompression()
IOstream::compressionType writeCompression () const inline
Default write compression.
Definition at line 312 of file Time.H.
Referenced by PatchPostProcessing< CloudType >::write().
graphFormat()
const word& graphFormat () const inline
Default graph format.
Definition at line 318 of file Time.H.
runTimeModifiable()
const Switch& runTimeModifiable () const inline
Supports re-reading.
Definition at line 324 of file Time.H.
References Time::addWatch(), Time::endTime(), Time::findClosestTime(), Time::findClosestTimeIndex(), Time::findInstance(), Time::findInstancePath(), Time::findTimes(), Time::getFile(), Time::getState(), IOobject::MUST_READ, dimensioned< Type >::name(), word::null, Time::read(), Time::readModifiedObjects(), Time::removeWatch(), Time::setUnmodified(), Time::startTime(), Time::startTimeIndex(), Time::timeName(), Time::times(), Time::writeAndEnd(), Time::writeNow(), Time::writeObject(), and Time::writeOnce().
read()
bool read () virtual
Read control dictionary, update controls and time.
Reimplemented from regIOobject.
Reimplemented in engineTime.
Definition at line 436 of file TimeIO.C.
References Time::readDict().
Referenced by engineTime::read(), and Time::runTimeModifiable().
readModifiedObjects()
void readModifiedObjects ()
Read the objects that have been modified.
Definition at line 450 of file TimeIO.C.
References regIOobject::fileModificationChecking, regIOobject::inotifyMaster, objectRegistry::modified(), UPstream::parRun(), functionObjectList::read(), Time::readDict(), regIOobject::readIfModified(), objectRegistry::readModifiedObjects(), regIOobject::timeStampMaster, and Time::writeObject().
Referenced by Time::run(), and Time::runTimeModifiable().
addWatch()
Foam::label addWatch (const fileName & fName) const
Add watching of a file. Returns handle.
Definition at line 656 of file Time.C.
Referenced by regIOobject::checkIn(), and Time::runTimeModifiable().
removeWatch()
bool removeWatch (const label watchIndex) const
Remove watch on a file (using handle)
Definition at line 662 of file Time.C.
Referenced by regIOobject::checkOut(), Time::readDict(), and Time::runTimeModifiable().
getFile()
const Foam::fileName & getFile (const label watchIndex) const
Get name of file being watched (using handle)
Definition at line 667 of file Time.C.
References Time::getState().
Referenced by regIOobject::readIfModified(), and Time::runTimeModifiable().
getState()
Foam::fileMonitor::fileState getState (const label watchFd) const
Get current state of file (using handle)
Definition at line 674 of file Time.C.
Referenced by Time::getFile(), regIOobject::modified(), and Time::runTimeModifiable().
setUnmodified()
void setUnmodified (const label watchFd) const
Set current state of file (using handle) to unmodified.
Definition at line 682 of file Time.C.
Referenced by Time::runTimeModifiable().
findInstance()
Foam::word findInstance (const fileName & dir, const word & name = word::null, const IOobject::readOption rOpt = IOobject::MUST_READ, const word & stopInstance = word::null) const
Return the location of "dir" containing the file "name".
(eg, used in reading mesh data) If name is null, search for the directory "dir" only. Does not search beyond stopInstance (if set) or constant.
Definition at line 38 of file findInstance.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, IOobject::headerOk(), Foam::Info, Foam::isDir(), Foam::isFile(), name(), path(), List< T >::size(), and timeName.
Referenced by Time::runTimeModifiable().
times()
Foam::instantList times () const
Search the case for valid time directories.
Definition at line 705 of file Time.C.
References path().
Referenced by edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), Time::runTimeModifiable(), timeSelector::select0(), and triSurface::triSurfInstance().
findInstancePath()
Foam::word findInstancePath (const instant & t) const
Search the case for the time directory path.
corresponding to the given instance
Definition at line 711 of file Time.C.
References fileName::DIRECTORY, instant::equal(), forAll, Foam::isDir(), word::null, path(), Foam::readDir(), and Foam::readScalar().
Referenced by IOobjectList::IOobjectList(), and Time::runTimeModifiable().
findClosestTime()
Foam::instant findClosestTime (const scalar t) const
Search the case for the time closest to the given time.
Definition at line 741 of file Time.C.
References Foam::diff(), Time::findClosestTimeIndex(), UList< T >::last(), Foam::mag(), path(), List< T >::size(), and timeDirs.
Referenced by Time::runTimeModifiable().
findClosestTimeIndex()
Foam::label findClosestTimeIndex (const instantList & timeDirs, const scalar t, const word & constantName = "constant") static
Search instantList for the time index closest to the given time.
Definition at line 788 of file Time.C.
References Foam::diff(), forAll, Foam::mag(), and Foam::name().
Referenced by Time::findClosestTime(), if(), and Time::runTimeModifiable().
writeObject()
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write using given format, version and compression.
Reimplemented from objectRegistry.
Definition at line 487 of file TimeIO.C.
References dictionary::add(), TimeState::deltaT0_, TimeState::deltaT_, IOobject::NO_READ, IOobject::NO_WRITE, TimeState::outputTime(), IOobject::path(), Time::previousOutputTimes_, Time::previousSecondaryOutputTimes_, TimeState::primaryOutputTime_, Time::purgeWrite_, Foam::rmDir(), TimeState::secondaryOutputTime_, Time::secondaryPurgeWrite_, TimeState::timeIndex_, Time::timeName(), TimeState::timeToUserTime(), dimensioned< Type >::value(), and objectRegistry::writeObject().
Referenced by Time::readModifiedObjects(), and Time::runTimeModifiable().
writeNow()
bool writeNow ()
Write the objects now (not at end of iteration) and continue.
the run
Definition at line 571 of file TimeIO.C.
References TimeState::outputTime_, TimeState::primaryOutputTime_, and regIOobject::write().
Referenced by Time::runTimeModifiable(), and Time::writeAndEnd().
writeAndEnd()
bool writeAndEnd ()
Write the objects now (not at end of iteration) and end the run.
Definition at line 579 of file TimeIO.C.
References Time::endTime_, Time::saWriteNow, Time::stopAt_, dimensioned< Type >::value(), and Time::writeNow().
Referenced by simpleControl::loop(), and Time::runTimeModifiable().
writeOnce()
void writeOnce ()
Write the objects once (one shot) and continue the run.
Definition at line 588 of file TimeIO.C.
References Time::writeOnce_.
Referenced by Time::runTimeModifiable().
timeName() [1/2]
Foam::word timeName (const scalar t) static
Return time name of given scalar time.
Definition at line 688 of file Time.C.
Referenced by fieldAverage::addMeanFieldType(), fieldAverage::addPrime2MeanFieldType(), interRegionExplicitPorositySource::addSup(), laminar::alphat(), fieldToCell::applyToSet(), Foam::compressible::autoCreateAlphat(), Foam::compressible::autoCreateLowReMut(), Foam::incompressible::autoCreateLowReNut(), Foam::compressible::autoCreateMut(), Foam::incompressible::autoCreateNut(), Foam::incompressible::autoCreateWallFunctionField(), Foam::compressible::autoCreateWallFunctionField(), laminar::B(), functionObjectFile::baseTimeDir(), basicMultiComponentMixture::basicMultiComponentMixture(), blended< Type >::blendingFactor(), interpolate::calc(), magSqr::calc(), mag::calc(), components::calc(), div::calc(), magGrad::calc(), randomise::calc(), addSubtract::calc(), nearWallFields::calcAddressing(), curvatureSeparation::calcCosAngle(), chemistryModel< CompType, ThermoType >::chemistryModel(), probes::classifyFields(), contactAngleForce::correct(), cubic< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), CourantNo::CourantNo(), heThermo< BasicSolidThermo, MixtureType >::Cp(), heThermo< BasicSolidThermo, MixtureType >::CpByCpv(), heThermo< BasicSolidThermo, MixtureType >::Cpv(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), functionObjectFile::createFiles(), heThermo< BasicSolidThermo, MixtureType >::Cv(), DESModelRegions::DESModelRegions(), laminar::devReff(), LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), GenSGSStress::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), LRR::devReff(), realizableKE::devReff(), LaunderGibsonRSTM::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), GenSGSStress::devRhoBeff(), laminar::devRhoReff(), kEpsilon::devRhoReff(), LRR::devRhoReff(), RNGkEpsilon::devRhoReff(), LaunderSharmaKE::devRhoReff(), realizableKE::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), SpalartAllmaras::devRhoReff(), v2f::devRhoReff(), kOmegaSST::devRhoReff(), fvMeshDistribute::distribute(), laminar::epsilon(), GenEddyVisc::epsilon(), GenSGSStress::epsilon(), kOmega::epsilon(), SpalartAllmaras::epsilon(), kOmegaSST::epsilon(), Peclet::execute(), blendingFactor::factor(), SpalartAllmaras::fv3(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), heThermo< BasicSolidThermo, MixtureType >::gamma(), calcFvcGrad::gradField(), constantHeatTransfer::h(), heThermo< BasicSolidThermo, MixtureType >::hc(), heThermo< BasicSolidThermo, MixtureType >::he(), thermoSingleLayer::hs(), coalCloudList::hsTrans(), Foam::MULES::implicitSolve(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), fvMeshSubset::interpolate(), laminar::k(), GenSGSStress::k(), SpalartAllmaras::k(), kkLOmega::k(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), Lambda2::Lambda2(), SpalartAllmaras::LESRegion(), Foam::MULES::limit(), Foam::MULES::limitCorr(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), readFields::loadField(), basicThermo::lookupOrConstruct(), simpleControl::loop(), meshRefinement::makeDisplacementField(), Foam::MapLagrangianFields(), Foam::MapMesh(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), Foam::MapVolFields(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), MeshedSurface< Foam::face >::MeshedSurface(), polyMesh::movePoints(), laminar::mut(), laminar::nuSgs(), laminar::nut(), consumptionSpeed::omega0Sigma(), RaviPetersen::operator()(), CloudFunctionObject< CloudType >::outputTimeDir(), Peclet::Peclet(), sampledSurface::pointAverage(), Foam::polyMeshZipUpCells(), kinematicSingleLayer::pp(), VoidFraction< CloudType >::preEvolve(), ParticleErosion< CloudType >::preEvolve(), pressureTools::pressureTools(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printFieldInfo(), processorField::processorField(), kinematicSingleLayer::pu(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), Q::Q(), laminar::R(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), kEpsilon::R(), RNGkEpsilon::R(), LienCubicKELowRe::R(), kOmega::R(), realizableKE::R(), LaunderSharmaKE::R(), qZeta::R(), SpalartAllmaras::R(), v2f::R(), kOmegaSST::R(), kkLOmega::R(), pointFieldReconstructor::reconstructField(), forces::rho(), coalCloudList::rhoTrans(), noRadiation::Rp(), opaqueSolid::Rp(), P1::Rp(), viewFactor::Rp(), fvDOM::Rp(), noRadiation::Ru(), opaqueSolid::Ru(), viewFactor::Ru(), timeSelector::selectIfPresent(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), skewCorrected< Type >::skewCorrection(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), coalCloudList::Srho(), thermoSingleLayer::Srho(), thermoSingleLayer::T(), thermoSingleLayer::thermoSingleLayer(), polyTopoChanger::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), laminar::Us(), coalCloudList::UTrans(), vorticity::vorticity(), wallShearStress::wallShearStress(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), reverseLinear< Type >::weights(), clippedLinear< Type >::weights(), FacePostProcessing< CloudType >::write(), STARCD::write(), MeshedSurfaceProxy< Face >::write(), ParticleCollector< CloudType >::write(), streamLine::write(), regionSizeDistribution::write(), wallBoundedStreamLine::write(), meshRefinement::write(), addSubtract::writeAddSubtractField(), addSubtract::writeAddSubtractValue(), Foam::writeCellGraph(), components::writeComponentFields(), div::writeDivField(), interpolate::writeInterpolateField(), mag::writeMagField(), magGrad::writeMagGradField(), magSqr::writeMagSqrField(), Foam::writeMeshObject(), dynamicRefineFvMesh::writeObject(), randomise::writeRandomField(), cellSource::writeValues(), faceSource::writeValues(), yPlusLES::yPlusLES(), yPlusRAS::yPlusRAS(), FSD< CombThermoType, ThermoType >::~FSD(), Gulders::~Gulders(), and GuldersEGR::~GuldersEGR().
timeName() [2/2]
Foam::word timeName () const virtual
Return current time name.
Definition at line 698 of file Time.C.
References dimensioned< scalar >::name().
Referenced by Time::readDict(), Time::runTimeModifiable(), Time::timePath(), and Time::writeObject().
findTimes()
Foam::instantList findTimes (const fileName & directory, const word & constantName = "constant") static
Search a given directory for valid time directories.
Definition at line 38 of file findTimes.C.
References Foam::endl(), IOstream::eof(), forAll, Foam::Info, token::isNumber(), Foam::less(), token::number(), Foam::readDir(), List< T >::setSize(), List< T >::size(), and Foam::sort().
Referenced by timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), Time::runTimeModifiable(), uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField(), and USERD_set_filenames().
startTimeIndex()
Foam::label startTimeIndex () const virtual
Return start time index.
Definition at line 813 of file Time.C.
Referenced by Time::runTimeModifiable().
startTime()
Foam::dimensionedScalar startTime () const virtual
Return start time.
Definition at line 819 of file Time.C.
References Foam::dimTime.
Referenced by fieldAverage::addMeanFieldType(), fieldAverage::addPrime2MeanFieldType(), functionObjectFile::createFiles(), and Time::runTimeModifiable().
endTime()
Foam::dimensionedScalar endTime () const virtual
Return end time.
Definition at line 825 of file Time.C.
References Foam::dimTime.
Referenced by Time::runTimeModifiable(), and simpleControl::simpleControl().
functionObjects() [1/2]
const functionObjectList& functionObjects () const inline
Return the list of function objects.
Definition at line 427 of file Time.H.
libs() [1/2]
const dlLibraryTable& libs () const inline
External access to the loaded libraries.
Definition at line 433 of file Time.H.
libs() [2/2]
dlLibraryTable& libs () inline
External access to the loaded libraries.
Definition at line 439 of file Time.H.
subCycling()
bool subCycling () const inline
Return true if time currently being sub-cycled, otherwise false.
Definition at line 445 of file Time.H.
References Time::subCycling_.
prevTimeState()
const TimeState& prevTimeState () const inline
Return previous TimeState if time is being sub-cycled.
Definition at line 451 of file Time.H.
References Time::adjustDeltaT(), Time::end(), Time::endSubCycle(), Time::loop(), Time::prevTimeState_, Time::run(), Time::setDeltaT(), Time::setEndTime(), Time::setTime(), Time::stopAt(), and Time::subCycle().
Referenced by fvMesh::Vsc(), and fvMesh::Vsc0().
run()
bool run () const virtual
Return true if run should continue,.
also invokes the functionObjectList::end() method when the time goes out of range
Note
For correct behaviour, the following style of time-loop is recommended:
while (runTime.run())
{
    runTime++;
    solve;
    runTime.write();
}
Definition at line 831 of file Time.C.
References Time::readModifiedObjects().
Referenced by Time::prevTimeState().
loop()
bool loop () virtual
Return true if run should continue and if so increment time.
also invokes the functionObjectList::end() method when the time goes out of range
Note
For correct behaviour, the following style of time-loop is recommended:
while (runTime.loop())
{
    solve;
    runTime.write();
}
Definition at line 871 of file Time.C.
Referenced by simpleControl::loop(), and Time::prevTimeState().
end()
bool end () const virtual
Return true if end of run,.
does not invoke any functionObject methods
Note
The rounding heuristics near endTime mean that
run()
and
!end()
may not yield the same result
Definition at line 884 of file Time.C.
Referenced by Time::prevTimeState().
stopAt()
bool stopAt (const stopAtControls sa) const virtual
Adjust the current stopAtControl. Note that this value.
only persists until the next time the dictionary is read. Return true if the stopAtControl changed.
Definition at line 890 of file Time.C.
Referenced by Time::prevTimeState().
setTime() [1/4]
void setTime (const Time & t) virtual
Reset the time and time-index to those of the given time.
Definition at line 908 of file Time.C.
References dimensioned< scalar >::name(), TimeState::timeIndex_, and dimensioned< Type >::value().
Referenced by Time::prevTimeState(), and timeSelector::select0().
setTime() [2/4]
void setTime (const instant & inst, const label newIndex) virtual
Reset the time and time-index.
Definition at line 916 of file Time.C.
References instant::name(), dimensioned< scalar >::name(), IOobject::NO_WRITE, IOobject::READ_IF_PRESENT, dictionary::readIfPresent(), timeName, and instant::value().
setTime() [3/4]
void setTime (const dimensionedScalar & newTime, const label newIndex) virtual
Reset the time and time-index.
Definition at line 942 of file Time.C.
References setTime(), and dimensioned< Type >::value().
setTime() [4/4]
void setTime (const scalar newTime, const label newIndex) virtual
Reset the time and time-index.
Definition at line 948 of file Time.C.
References dimensioned< scalar >::name(), and timeName.
setEndTime() [1/2]
void setEndTime (const dimensionedScalar & endTime) virtual
Reset end time.
Definition at line 956 of file Time.C.
References dimensioned< Type >::value().
Referenced by Time::prevTimeState().
setEndTime() [2/2]
void setEndTime (const scalar endTime) virtual
Reset end time.
Definition at line 962 of file Time.C.
References endTime, and Time::setDeltaT().
setDeltaT() [1/2]
void setDeltaT (const dimensionedScalar & deltaT, const bool adjustDeltaT = true) virtual
Reset time step.
Definition at line 969 of file Time.C.
References dimensioned< Type >::value().
Referenced by Time::prevTimeState(), and Time::setEndTime().
setDeltaT() [2/2]
void setDeltaT (const scalar deltaT, const bool adjustDeltaT = true) virtual
Reset time step.
Definition at line 978 of file Time.C.
subCycle()
Foam::TimeState subCycle (const label nSubCycles) virtual
Set time to sub-cycle for the given number of steps.
Definition at line 990 of file Time.C.
References setTime(), and timeIndex.
Referenced by Time::prevTimeState(), and subCycleTime::subCycleTime().
endSubCycle()
void endSubCycle () virtual
Reset time after sub-cycling back to previous TimeState.
Definition at line 1004 of file Time.C.
Referenced by subCycleTime::endSubCycle(), and Time::prevTimeState().
functionObjects() [2/2]
functionObjectList& functionObjects () inline
Return non-const access to the list of function objects.
Definition at line 549 of file Time.H.
References Time::operator++(), and Time::operator+=().
operator+=() [1/2]
Foam::Time & operator+= (const dimensionedScalar & deltaT) virtual
Set deltaT to that specified and increment time via operator++()
Definition at line 1017 of file Time.C.
References dimensioned< Type >::value().
Referenced by Time::functionObjects().
operator+=() [2/2]
Foam::Time & operator+= (const scalar deltaT) virtual
Set deltaT to that specified and increment time via operator++()
Definition at line 1023 of file Time.C.
operator++() [1/2]
Foam::Time & operator++ () virtual
Prefix increment,.
also invokes the functionObjectList::start() or functionObjectList::execute() method, depending on the time-index
Definition at line 1030 of file Time.C.
References Foam::endl(), Foam::mag(), dimensioned< scalar >::name(), Foam::reduce(), Foam::returnReduce(), setTime(), timeIndex, and WarningIn.
Referenced by Time::functionObjects().
operator++() [2/2]
Foam::Time & operator++ (int) virtual
Postfix increment, this is identical to the prefix increment.
Definition at line 1262 of file Time.C.
Member Data Documentation
startTimeIndex_
label startTimeIndex_ protected
Definition at line 122 of file Time.H.
startTime_
scalar startTime_ protected
Definition at line 123 of file Time.H.
Referenced by engineTime::engineTime().
endTime_
scalar endTime_ mutable protected
Definition at line 124 of file Time.H.
Referenced by Time::readDict(), and Time::writeAndEnd().
stopAtControlNames_
const Foam::NamedEnum< Foam::Time::stopAtControls, 4 > stopAtControlNames_ static protected
Definition at line 126 of file Time.H.
Referenced by NamedEnum< directionType, 3 >::names(), and Time::readDict().
stopAt_
stopAtControls stopAt_ mutable protected
Definition at line 127 of file Time.H.
Referenced by Time::readDict(), and Time::writeAndEnd().
writeControlNames_
const Foam::NamedEnum< Foam::Time::writeControls, 5 > writeControlNames_ static protected
Definition at line 129 of file Time.H.
Referenced by NamedEnum< directionType, 3 >::names(), and Time::readDict().
writeControl_
writeControls writeControl_ protected
Definition at line 130 of file Time.H.
Referenced by Time::readDict().
writeInterval_
scalar writeInterval_ protected
Definition at line 132 of file Time.H.
Referenced by Time::readDict().
secondaryWriteControl_
writeControls secondaryWriteControl_ protected
Definition at line 136 of file Time.H.
Referenced by Time::readDict().
secondaryWriteInterval_
scalar secondaryWriteInterval_ protected
Definition at line 138 of file Time.H.
Referenced by Time::readDict().
purgeWrite_
label purgeWrite_ protected
Definition at line 140 of file Time.H.
Referenced by Time::readDict(), and Time::writeObject().
previousOutputTimes_
FIFOStack<word> previousOutputTimes_ mutable protected
Definition at line 141 of file Time.H.
Referenced by Time::writeObject().
secondaryPurgeWrite_
label secondaryPurgeWrite_ protected
Definition at line 145 of file Time.H.
Referenced by Time::readDict(), and Time::writeObject().
previousSecondaryOutputTimes_
FIFOStack<word> previousSecondaryOutputTimes_ mutable protected
Definition at line 146 of file Time.H.
Referenced by Time::writeObject().
writeOnce_
bool writeOnce_ protected
Definition at line 150 of file Time.H.
Referenced by Time::writeOnce().
subCycling_
bool subCycling_ protected
Is the time currently being sub-cycled?
Definition at line 153 of file Time.H.
Referenced by Time::subCycling().
prevTimeState_
autoPtr<TimeState> prevTimeState_ protected
If time is being sub-cycled this is the previous TimeState.
Definition at line 156 of file Time.H.
Referenced by Time::prevTimeState().
sigWriteNow_
sigWriteNow sigWriteNow_ protected
Enable one-shot writing upon signal.
Definition at line 162 of file Time.H.
sigStopAtWriteNow_
sigStopAtWriteNow sigStopAtWriteNow_ protected
Enable write and clean exit upon signal.
Definition at line 165 of file Time.H.
format_
Foam::Time::fmtflags format_ static protected
Time directory name format.
Definition at line 169 of file Time.H.
Referenced by NamedEnum< directionType, 3 >::names(), and Time::readDict().
precision_
int precision_ static protected
Time directory name precision.
Definition at line 172 of file Time.H.
Referenced by NamedEnum< directionType, 3 >::names(), and Time::readDict().
controlDictName
Foam::word controlDictName static
The default control dictionary name (normally "controlDict")
Definition at line 210 of file Time.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/Time.H
src/OpenFOAM/db/Time/findInstance.C
src/OpenFOAM/db/Time/findTimes.C
src/OpenFOAM/db/Time/Time.C
src/OpenFOAM/db/Time/TimeIO.C