OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
addDimensionSetsToDebug Class Reference
Helper class to.
Public Member Functions
addDimensionSetsToDebug (const char *name)
virtual ~addDimensionSetsToDebug ()
virtual void readData (Foam::Istream &is)
Read.
virtual void writeData (Foam::Ostream &os) const
Write.
Public Member Functions inherited from simpleRegIOobject
simpleRegIOobject (void(*fn)(const char *name, simpleRegIOobject *), const char *name)
Construct from objectregistry inserter and name.
virtual ~simpleRegIOobject ()
Destructor.
Detailed Description
Helper class to.
register re-reader
deallocate demand-driven data
Definition at line 48 of file dimensionSets.C.
Constructor & Destructor Documentation
addDimensionSetsToDebug()
addDimensionSetsToDebug (const char * name) inline
Definition at line 53 of file dimensionSets.C.
~addDimensionSetsToDebug()
virtual ~addDimensionSetsToDebug () inline virtual
Definition at line 57 of file dimensionSets.C.
References Foam::deleteDemandDrivenData(), Foam::dimensionSystemsPtr_(), Foam::unitSetPtr_, and Foam::writeUnitSetPtr_().
Member Function Documentation
readData()
virtual void readData (Foam::Istream &) inline virtual
Read.
Implements simpleRegIOobject.
Definition at line 64 of file dimensionSets.C.
References Foam::deleteDemandDrivenData(), Foam::dimensionSystemsPtr_(), Foam::unitSetPtr_, and Foam::writeUnitSetPtr_().
writeData()
virtual void writeData (Foam::Ostream &) const inline virtual
Write.
Implements simpleRegIOobject.
Definition at line 71 of file dimensionSets.C.
References Foam::addDimensionSetsToDebug_, and Foam::dimensionSystems().
The documentation for this class was generated from the following file:
src/OpenFOAM/dimensionSet/dimensionSets.C