OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
token Class Reference
A token holds items read from Istream.
Classes
class compound
Abstract base class for complex tokens.
class Compound
A templated class for holding compound tokens.
Public Types
enum tokenType {
UNDEFINED, PUNCTUATION, WORD, VARIABLE,
STRING, VERBATIMSTRING, LABEL, FLOAT_SCALAR,
DOUBLE_SCALAR, COMPOUND, ERROR
}
Enumeration defining the types of token.
enum punctuationToken {
NULL_TOKEN = '\0', SPACE = ' ', TAB = '\t', NL = '\n',
END_STATEMENT = ';', BEGIN_LIST = '(', END_LIST = ')', BEGIN_SQR = '[',
END_SQR = ']', BEGIN_BLOCK = '{', END_BLOCK = '}', COLON = ':',
COMMA = ',', HASH = '#', BEGIN_STRING = '"', END_STRING = BEGIN_STRING,
ASSIGN = '=', ADD = '+', SUBTRACT = '-', MULTIPLY = '*',
DIVIDE = '/'
}
Standard punctuation tokens.
Public Member Functions
token ()
Construct null.
token (const token &)
Construct as copy.
token (punctuationToken, label lineNumber=0)
Construct punctuation character token.
token (const word &, label lineNumber=0)
Construct word token.
token (const string &, label lineNumber=0)
Construct string token.
token (const label, label lineNumber=0)
Construct label token.
token (const floatScalar, label lineNumber=0)
Construct floatScalar token.
token (const doubleScalar, label lineNumber=0)
Construct doubleScalar token.
token (Istream &)
Construct from Istream.
~token ()
Destructor.
tokenType type () const
tokenType & type ()
bool good () const
bool undefined () const
bool error () const
bool isPunctuation () const
punctuationToken pToken () const
bool isWord () const
const word & wordToken () const
bool isVariable () const
bool isString () const
const string & stringToken () const
bool isLabel () const
label labelToken () const
bool isFloatScalar () const
floatScalar floatScalarToken () const
bool isDoubleScalar () const
doubleScalar doubleScalarToken () const
bool isScalar () const
scalar scalarToken () const
bool isNumber () const
scalar number () const
bool isCompound () const
const compound & compoundToken () const
compound & transferCompoundToken (const Istream &is)
label lineNumber () const
label & lineNumber ()
void setBad ()
Set bad.
InfoProxy< token > info () const
Return info proxy.
void operator= (const token &)
void operator= (const punctuationToken)
void operator= (word *)
void operator= (const word &)
void operator= (string *)
void operator= (const string &)
void operator= (const label)
void operator= (const floatScalar)
void operator= (const doubleScalar)
void operator= (compound *)
bool operator== (const token &) const
bool operator== (const punctuationToken) const
bool operator== (const word &) const
bool operator== (const string &) const
bool operator== (const label) const
bool operator== (const floatScalar) const
bool operator== (const doubleScalar) const
bool operator!= (const token &) const
bool operator!= (const punctuationToken) const
bool operator!= (const word &) const
bool operator!= (const string &) const
bool operator!= (const label) const
bool operator!= (const floatScalar) const
bool operator!= (const doubleScalar) const
Static Public Attributes
static token undefinedToken
Static undefined token.
static const char *const typeName = "token"
Friends
Istream & operator>> (Istream &, token &)
Ostream & operator<< (Ostream &, const token &)
Ostream & operator<< (Ostream &, const punctuationToken &)
ostream & operator<< (ostream &, const punctuationToken &)
ostream & operator<< (ostream &, const InfoProxy< token > &)
Detailed Description
A token holds items read from Istream.
Source files
token.H
tokenI.H
token.C
tokenIO.C
Definition at line 67 of file token.H.
Member Enumeration Documentation
tokenType
enum tokenType
Enumeration defining the types of token.
Enumerator
UNDEFINED
PUNCTUATION
WORD
VARIABLE
STRING
VERBATIMSTRING
LABEL
FLOAT_SCALAR
DOUBLE_SCALAR
COMPOUND
ERROR
Definition at line 73 of file token.H.
punctuationToken
enum punctuationToken
Standard punctuation tokens.
Enumerator
NULL_TOKEN
SPACE
TAB
NL
END_STATEMENT
BEGIN_LIST
END_LIST
BEGIN_SQR
END_SQR
BEGIN_BLOCK
END_BLOCK
COLON
COMMA
HASH
BEGIN_STRING
END_STRING
ASSIGN
ADD
SUBTRACT
MULTIPLY
DIVIDE
Definition at line 92 of file token.H.
Constructor & Destructor Documentation
token() [1/9]
token () inline
Construct null.
Definition at line 65 of file tokenI.H.
token() [2/9]
token (const token & t) inline
Construct as copy.
Definition at line 72 of file tokenI.H.
References token::COMPOUND, token::compoundTokenPtr_, token::DOUBLE_SCALAR, token::doubleScalarToken_, token::ERROR, token::FLOAT_SCALAR, token::floatScalarToken_, token::LABEL, token::labelToken_, token::PUNCTUATION, token::punctuationToken_, token::STRING, token::stringTokenPtr_, token::UNDEFINED, token::VARIABLE, token::VERBATIMSTRING, token::WORD, and token::wordTokenPtr_.
token() [3/9]
token (punctuationToken p, label lineNumber = 0) inline
Construct punctuation character token.
Definition at line 119 of file tokenI.H.
token() [4/9]
token (const word & w, label lineNumber = 0) inline
Construct word token.
Definition at line 127 of file tokenI.H.
token() [5/9]
token (const string & s, label lineNumber = 0) inline
Construct string token.
Definition at line 135 of file tokenI.H.
token() [6/9]
token (const label l, label lineNumber = 0) inline
Construct label token.
Definition at line 143 of file tokenI.H.
token() [7/9]
token (const floatScalar s, label lineNumber = 0) inline
Construct floatScalar token.
Definition at line 151 of file tokenI.H.
token() [8/9]
token (const doubleScalar s, label lineNumber = 0) inline
Construct doubleScalar token.
Definition at line 159 of file tokenI.H.
token() [9/9]
token (Istream & is)
Construct from Istream.
Definition at line 37 of file tokenIO.C.
References Istream::read().
~token()
~token () inline
Destructor.
Definition at line 170 of file tokenI.H.
Member Function Documentation
type() [1/2]
token::tokenType type () const inline
Definition at line 178 of file tokenI.H.
Referenced by token::compound::compound(), Foam::operator<<(), ISstream::read(), UIPstream::read(), prefixOSstream::write(), OSstream::write(), UOPstream::write(), and primitiveEntry::write().
type() [2/2]
token::tokenType & type () inline
Definition at line 183 of file tokenI.H.
good()
bool good () const inline
Definition at line 188 of file tokenI.H.
References token::ERROR, and token::UNDEFINED.
Referenced by dimensionSet::dimensionSet(), keyType::match(), Foam::operator>>(), and primitiveEntry::read().
undefined()
bool undefined () const inline
Definition at line 193 of file tokenI.H.
References token::UNDEFINED.
error()
bool error () const inline
Definition at line 198 of file tokenI.H.
References token::ERROR.
isPunctuation()
bool isPunctuation () const inline
Definition at line 203 of file tokenI.H.
References token::PUNCTUATION.
Referenced by blockDescriptor::blockDescriptor(), dimensionSet::dimensionSet(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), genericFvPatchField< Type >::genericFvPatchField(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Foam::operator>>(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), IOPosition< CloudType >::readData(), Reaction< ReactionThermo >::setLRhs(), thirdBodyEfficiencies::thirdBodyEfficiencies(), and UList< Foam::wordRe >::writeEntry().
pToken()
token::punctuationToken pToken () const inline
Definition at line 208 of file tokenI.H.
References token::NULL_TOKEN, token::PUNCTUATION, and token::punctuationToken_.
Referenced by blockDescriptor::blockDescriptor(), dimensionSet::dimensionSet(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Foam::operator<<(), Foam::operator>>(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), Istream::readBeginList(), IOPosition< CloudType >::readData(), Istream::readEndList(), thirdBodyEfficiencies::thirdBodyEfficiencies(), and UList< Foam::wordRe >::writeEntry().
isWord()
bool isWord () const inline
Definition at line 221 of file tokenI.H.
References token::WORD.
Referenced by blockDescriptor::blockDescriptor(), Constant< Type >::Constant(), dimensioned< vector >::dimensioned(), dimensionSet::dimensionSet(), Field< Foam::Vector2D >::Field(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), keyType::match(), dimensioned< vector >::operator/=(), Foam::operator>>(), dimensionSet::read(), IOobject::readHeader(), mappedPatchBase::readListOrField(), Reaction< ReactionThermo >::specieCoeffs::specieCoeffs(), and thirdBodyEfficiencies::thirdBodyEfficiencies().
wordToken()
const word & wordToken () const inline
Definition at line 226 of file tokenI.H.
References word::null, token::WORD, and token::wordTokenPtr_.
Referenced by blockDescriptor::blockDescriptor(), dimensionSet::dimensionSet(), Field< Foam::Vector2D >::Field(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), keyType::match(), Foam::operator<<(), token::operator==(), Foam::operator>>(), dimensionSet::read(), IOobject::readHeader(), mappedPatchBase::readListOrField(), Reaction< ReactionThermo >::specieCoeffs::specieCoeffs(), and thirdBodyEfficiencies::thirdBodyEfficiencies().
isVariable()
bool isVariable () const inline
Definition at line 239 of file tokenI.H.
References token::VARIABLE.
isString()
bool isString () const inline
Definition at line 244 of file tokenI.H.
References token::STRING, token::VARIABLE, and token::VERBATIMSTRING.
Referenced by keyType::match(), and Foam::operator>>().
stringToken()
const string & stringToken () const inline
Definition at line 249 of file tokenI.H.
References string::null, token::STRING, token::stringTokenPtr_, token::VARIABLE, and token::VERBATIMSTRING.
Referenced by keyType::match(), Foam::operator<<(), token::operator==(), Foam::operator>>(), prefixOSstream::write(), OSstream::write(), and UOPstream::write().
isLabel()
bool isLabel () const inline
Definition at line 262 of file tokenI.H.
References token::LABEL.
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), Foam::operator>>(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), IOPosition< CloudType >::readData(), and UList< Foam::wordRe >::writeEntry().
labelToken()
label labelToken () const inline
Definition at line 267 of file tokenI.H.
References token::LABEL, and token::labelToken_.
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), Foam::operator<<(), Foam::operator>>(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), IOPosition< CloudType >::readData(), and UList< Foam::wordRe >::writeEntry().
isFloatScalar()
bool isFloatScalar () const inline
Definition at line 280 of file tokenI.H.
References token::FLOAT_SCALAR.
floatScalarToken()
floatScalar floatScalarToken () const inline
Definition at line 285 of file tokenI.H.
References token::FLOAT_SCALAR, and token::floatScalarToken_.
Referenced by Foam::operator<<().
isDoubleScalar()
bool isDoubleScalar () const inline
Definition at line 299 of file tokenI.H.
References token::DOUBLE_SCALAR.
doubleScalarToken()
doubleScalar doubleScalarToken () const inline
Definition at line 304 of file tokenI.H.
References token::DOUBLE_SCALAR, and token::doubleScalarToken_.
Referenced by Foam::operator<<().
isScalar()
bool isScalar () const inline
Definition at line 318 of file tokenI.H.
References token::DOUBLE_SCALAR, and token::FLOAT_SCALAR.
Referenced by token::isNumber(), and token::number().
scalarToken()
scalar scalarToken () const inline
Definition at line 323 of file tokenI.H.
References token::DOUBLE_SCALAR, token::doubleScalarToken_, token::FLOAT_SCALAR, and token::floatScalarToken_.
Referenced by token::number().
isNumber()
bool isNumber () const inline
Definition at line 340 of file tokenI.H.
References token::isScalar(), and token::LABEL.
Referenced by Time::findTimes(), Foam::operator>>(), dimensionSet::read(), and Reaction< ReactionThermo >::specieCoeffs::specieCoeffs().
number()
scalar number () const inline
Definition at line 345 of file tokenI.H.
References token::isScalar(), token::LABEL, token::labelToken_, and token::scalarToken().
Referenced by Time::findTimes(), genericFvPatchField< Type >::genericFvPatchField(), Foam::operator>>(), dimensionSet::read(), and Reaction< ReactionThermo >::specieCoeffs::specieCoeffs().
isCompound()
bool isCompound () const inline
Definition at line 362 of file tokenI.H.
References token::COMPOUND.
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), List< functionObject *>::List(), and UList< Foam::wordRe >::writeEntry().
compoundToken()
const token::compound & compoundToken () const inline
Definition at line 367 of file tokenI.H.
References token::COMPOUND, and token::compoundTokenPtr_.
Referenced by genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), and Foam::operator<<().
transferCompoundToken()
Foam::token::compound & transferCompoundToken (const Istream & is)
Definition at line 93 of file token.C.
References Foam::abort(), Foam::FatalIOError, and FatalIOErrorIn.
Referenced by FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), List< functionObject *>::List(), and UList< Foam::wordRe >::writeEntry().
lineNumber() [1/2]
label lineNumber () const inline
Definition at line 381 of file tokenI.H.
Referenced by Foam::operator<<(), ISstream::read(), UIPstream::read(), and ITstream::read().
lineNumber() [2/2]
label & lineNumber () inline
Definition at line 386 of file tokenI.H.
setBad()
void setBad () inline
Set bad.
Definition at line 392 of file tokenI.H.
References token::ERROR.
Referenced by ISstream::read(), and UIPstream::read().
info()
InfoProxy<token> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 372 of file token.H.
Referenced by blockDescriptor::blockDescriptor(), Field< Foam::Vector2D >::Field(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), keyType::match(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), Foam::operator>>(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), PtrList< MRFZone >::read(), PackedList< 2 >::read(), Istream::readBegin(), Istream::readBeginList(), IOPosition< CloudType >::readData(), Istream::readEnd(), Istream::readEndList(), Reaction< ReactionThermo >::specieCoeffs::specieCoeffs(), thirdBodyEfficiencies::thirdBodyEfficiencies(), and UList< Foam::wordRe >::writeEntry().
operator=() [1/10]
void operator= (const token & t) inline
Definition at line 401 of file tokenI.H.
References token::COMPOUND, token::compoundTokenPtr_, token::DOUBLE_SCALAR, token::doubleScalarToken_, token::ERROR, token::FLOAT_SCALAR, token::floatScalarToken_, token::LABEL, token::labelToken_, token::PUNCTUATION, token::punctuationToken_, token::STRING, token::stringTokenPtr_, token::UNDEFINED, token::VARIABLE, token::VERBATIMSTRING, token::WORD, and token::wordTokenPtr_.
Referenced by token::operator=().
operator=() [2/10]
void operator= (const punctuationToken p) inline
Definition at line 449 of file tokenI.H.
References p, token::PUNCTUATION, and token::punctuationToken_.
operator=() [3/10]
void operator= (word * wPtr) inline
Definition at line 456 of file tokenI.H.
References token::WORD, and token::wordTokenPtr_.
operator=() [4/10]
void operator= (const word & w) inline
Definition at line 463 of file tokenI.H.
References token::operator=().
operator=() [5/10]
void operator= (string * sPtr) inline
Definition at line 468 of file tokenI.H.
References token::STRING, and token::stringTokenPtr_.
operator=() [6/10]
void operator= (const string & s) inline
Definition at line 475 of file tokenI.H.
References token::operator=().
operator=() [7/10]
void operator= (const label l) inline
Definition at line 480 of file tokenI.H.
References token::LABEL, and token::labelToken_.
operator=() [8/10]
void operator= (const floatScalar s) inline
Definition at line 487 of file tokenI.H.
References token::FLOAT_SCALAR, token::floatScalarToken_, and s().
operator=() [9/10]
void operator= (const doubleScalar s) inline
Definition at line 494 of file tokenI.H.
References token::DOUBLE_SCALAR, token::doubleScalarToken_, and s().
operator=() [10/10]
void operator= (token::compound * cPtr) inline
Definition at line 501 of file tokenI.H.
References token::COMPOUND, and token::compoundTokenPtr_.
operator==() [1/7]
bool operator== (const token & t) const inline
Definition at line 509 of file tokenI.H.
References token::COMPOUND, token::compoundTokenPtr_, token::DOUBLE_SCALAR, token::doubleScalarToken_, Foam::equal(), token::ERROR, token::FLOAT_SCALAR, token::floatScalarToken_, token::LABEL, token::labelToken_, token::PUNCTUATION, token::punctuationToken_, token::STRING, token::stringTokenPtr_, token::UNDEFINED, token::VARIABLE, token::VERBATIMSTRING, token::WORD, and token::wordTokenPtr_.
Referenced by token::operator!=().
operator==() [2/7]
bool operator== (const punctuationToken p) const inline
Definition at line 551 of file tokenI.H.
References token::PUNCTUATION, and token::punctuationToken_.
operator==() [3/7]
bool operator== (const word & w) const inline
Definition at line 556 of file tokenI.H.
References token::WORD, and token::wordToken().
operator==() [4/7]
bool operator== (const string & s) const inline
Definition at line 561 of file tokenI.H.
References token::STRING, token::stringToken(), token::VARIABLE, and token::VERBATIMSTRING.
operator==() [5/7]
bool operator== (const label l) const inline
Definition at line 570 of file tokenI.H.
References token::LABEL, and token::labelToken_.
operator==() [6/7]
bool operator== (const floatScalar s) const inline
Definition at line 575 of file tokenI.H.
References Foam::equal(), token::FLOAT_SCALAR, and token::floatScalarToken_.
operator==() [7/7]
bool operator== (const doubleScalar s) const inline
Definition at line 580 of file tokenI.H.
References token::DOUBLE_SCALAR, token::doubleScalarToken_, and Foam::equal().
operator!=() [1/7]
bool operator!= (const token & t) const inline
Definition at line 585 of file tokenI.H.
References token::operator==().
operator!=() [2/7]
bool operator!= (const punctuationToken p) const inline
Definition at line 590 of file tokenI.H.
References token::operator==().
operator!=() [3/7]
bool operator!= (const word & w) const inline
Definition at line 595 of file tokenI.H.
References token::operator==().
operator!=() [4/7]
bool operator!= (const string & s) const inline
Definition at line 600 of file tokenI.H.
References token::operator==().
operator!=() [5/7]
bool operator!= (const label l) const inline
Definition at line 615 of file tokenI.H.
References token::operator==().
operator!=() [6/7]
bool operator!= (const floatScalar s) const inline
Definition at line 605 of file tokenI.H.
References token::operator==().
operator!=() [7/7]
bool operator!= (const doubleScalar s) const inline
Definition at line 610 of file tokenI.H.
References token::operator==().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , token &) friend
operator<< [1/4]
Ostream& operator<< (Ostream & , const token &) friend
operator<< [2/4]
Ostream& operator<< (Ostream & , const punctuationToken &) friend
operator<< [3/4]
ostream& operator<< (ostream & , const punctuationToken &) friend
operator<< [4/4]
ostream& operator<< (ostream & , const InfoProxy< token > &) friend
Member Data Documentation
undefinedToken
token undefinedToken static
Static undefined token.
Definition at line 241 of file token.H.
Referenced by Istream::peekBack(), and ITstream::read().
punctuationToken_
punctuationToken punctuationToken_
Definition at line 254 of file token.H.
Referenced by Foam::operator<<(), token::operator=(), token::operator==(), token::pToken(), and token::token().
wordTokenPtr_
word* wordTokenPtr_
Definition at line 255 of file token.H.
Referenced by Foam::operator<<(), token::operator=(), token::operator==(), token::token(), and token::wordToken().
stringTokenPtr_
string* stringTokenPtr_
Definition at line 256 of file token.H.
Referenced by Foam::operator<<(), token::operator=(), token::operator==(), token::stringToken(), and token::token().
labelToken_
label labelToken_
Definition at line 257 of file token.H.
Referenced by token::labelToken(), token::number(), Foam::operator<<(), token::operator=(), token::operator==(), and token::token().
floatScalarToken_
floatScalar floatScalarToken_
Definition at line 258 of file token.H.
Referenced by token::floatScalarToken(), Foam::operator<<(), token::operator=(), token::operator==(), token::scalarToken(), and token::token().
doubleScalarToken_
doubleScalar doubleScalarToken_
Definition at line 259 of file token.H.
Referenced by token::doubleScalarToken(), Foam::operator<<(), token::operator=(), token::operator==(), token::scalarToken(), and token::token().
compoundTokenPtr_
compound* compoundTokenPtr_ mutable
Definition at line 260 of file token.H.
Referenced by token::compoundToken(), Foam::operator<<(), token::operator=(), token::operator==(), and token::token().
typeName
const char *const typeName = "token" static
Definition at line 280 of file token.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/token/token.H
src/OpenFOAM/db/IOstreams/token/token.C
src/OpenFOAM/db/IOstreams/token/tokenI.H
src/OpenFOAM/db/IOstreams/token/tokenIO.C