OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
FieldMapper Class Reference abstract
Abstract base class to hold the Field mapping addressing and weights.
Public Member Functions
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual label size () const =0
virtual bool direct () const =0
virtual bool hasUnmapped () const =0
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Abstract base class to hold the Field mapping addressing and weights.
Definition at line 43 of file FieldMapper.H.
Constructor & Destructor Documentation
FieldMapper()
FieldMapper () inline
Null constructor.
Definition at line 51 of file FieldMapper.H.
~FieldMapper()
virtual ~FieldMapper () inline virtual
Destructor.
Definition at line 56 of file FieldMapper.H.
References FieldMapper::direct(), FieldMapper::hasUnmapped(), and FieldMapper::size().
Member Function Documentation
size()
virtual label size () const pure virtual
Implemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvPatchMapper, singleCellFvMesh::agglomPatchFieldMapper, faceMapper, cellMapper, pointMapper, fvSurfaceMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, weightedFvPatchFieldMapper, pointFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, fvFieldDecomposer::patchFieldDecomposer, and directFieldMapper.
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), and FieldMapper::~FieldMapper().
direct()
virtual bool direct () const pure virtual
Implemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvPatchMapper, faceMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, cellMapper, pointMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, weightedFvPatchFieldMapper, pointFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, fvFieldDecomposer::patchFieldDecomposer, and directFieldMapper.
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), pointPatchMapper::direct(), Field< Foam::Vector2D >::map(), and FieldMapper::~FieldMapper().
hasUnmapped()
virtual bool hasUnmapped () const pure virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, fvPatchMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvSurfaceMapper, faceMapper, pointPatchMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, cellMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, weightedFvPatchFieldMapper, pointFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, and directFieldMapper.
Referenced by directionMixedFvPatchField< Type >::directionMixedFvPatchField(), fixedGradientFvPatchField< Type >::fixedGradientFvPatchField(), fixedValueFvPatchField< scalar >::fixedValueFvPatchField(), mixedFvPatchField< scalar >::mixedFvPatchField(), and FieldMapper::~FieldMapper().
directAddressing()
virtual const labelUList& directAddressing () const inline virtual
Reimplemented in pointPatchMapper, fvPatchMapper, fvSurfaceMapper, faceMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, pointMapper, cellMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, pointFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, and directFieldMapper.
Definition at line 70 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and UList< T >::null().
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), and Field< Foam::Vector2D >::map().
addressing()
virtual const labelListList& addressing () const inline virtual
Reimplemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvPatchMapper, fvSurfaceMapper, faceMapper, pointMapper, cellMapper, singleCellFvMesh::agglomPatchFieldMapper, and weightedFvPatchFieldMapper.
Definition at line 79 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and List< labelList >::null().
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), and Field< Foam::Vector2D >::map().
weights()
virtual const scalarListList& weights () const inline virtual
Reimplemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvPatchMapper, fvSurfaceMapper, faceMapper, pointMapper, cellMapper, singleCellFvMesh::agglomPatchFieldMapper, and weightedFvPatchFieldMapper.
Definition at line 88 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and List< scalarList >::null().
Referenced by Field< Foam::Vector2D >::map().
operator()()
tmp<Field<Type> > operator() (const Field< Type > & f) const inline
Definition at line 101 of file FieldMapper.H.
References f().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/FieldMapper.H