OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reuseTmpFieldField< Field, TypeR, Type1 > Class Template Reference
Static Public Member Functions
static tmp< FieldField< Field, TypeR > > New (const tmp< FieldField< Field, Type1 > > &tf1)
static void clear (const tmp< FieldField< Field, Type1 > > &tf1)
Detailed Description
template<template< class > class Field, class TypeR, class Type1>
class Foam::reuseTmpFieldField< Field, TypeR, Type1 >
Definition at line 37 of file FieldFieldReuseFunctions.H.
Member Function Documentation
New()
static tmp<FieldField<Field, TypeR> > New (const tmp< FieldField< Field, Type1 > > & tf1) inline static
Definition at line 42 of file FieldFieldReuseFunctions.H.
References FieldField< Field, Type >::NewCalculatedType().
clear()
static void clear (const tmp< FieldField< Field, Type1 > > & tf1) inline static
Definition at line 52 of file FieldFieldReuseFunctions.H.
Referenced by Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::mag(), Foam::magSqr(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, Type2 >::New(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, TypeR >::New(), reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, Type2 >::New(), reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, TypeR >::New(), Foam::pow(), and Foam::sqr().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/FieldFields/FieldField/FieldFieldReuseFunctions.H