OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh > Class Template Reference
Static Public Member Functions
static tmp< GeometricField< TypeR, PatchField, GeoMesh > > New (const tmp< GeometricField< TypeR, PatchField, GeoMesh > > &tdf1, const tmp< GeometricField< Type2, PatchField, GeoMesh > > &tdf2, const word &name, const dimensionSet &dimensions)
static void clear (const tmp< GeometricField< TypeR, PatchField, GeoMesh > > &tdf1, const tmp< GeometricField< Type2, PatchField, GeoMesh > > &tdf2)
Detailed Description
template<class TypeR, class Type2, template< class > class PatchField, class GeoMesh>
class Foam::reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >
Definition at line 258 of file GeometricFieldReuseFunctions.H.
Member Function Documentation
New()
static tmp<GeometricField<TypeR, PatchField, GeoMesh> > New (const tmp< GeometricField< TypeR, PatchField, GeoMesh > > & tdf1, const tmp< GeometricField< Type2, PatchField, GeoMesh > > & tdf2, const word & name, const dimensionSet & dimensions) inline static
Definition at line 263 of file GeometricFieldReuseFunctions.H.
References reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::clear(), IOobject::db(), DimensionedField< Type, GeoMesh >::dimensions(), IOobject::instance(), DimensionedField< Type, GeoMesh >::mesh(), and regIOobject::rename().
clear()
static void clear (const tmp< GeometricField< TypeR, PatchField, GeoMesh > > & tdf1, const tmp< GeometricField< Type2, PatchField, GeoMesh > > & tdf2) inline static
Definition at line 299 of file GeometricFieldReuseFunctions.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricFieldReuseFunctions.H