OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
clock Class Reference
Read access to the system clock with formatting.
Public Member Functions
clock ()
Null constructor which stores the start time.
time_t elapsedClockTime () const
Returns wall-clock time from clock instantiation.
time_t clockTimeIncrement () const
Returns wall-clock time from last call of clockTimeIncrement()
Static Public Member Functions
static time_t getTime ()
Get the current clock time in seconds.
static const struct tm rawDate ()
Return the current wall-clock date as a raw struct.
static string dateTime ()
Return the current wall-clock date/time as a string.
static string date ()
Return the current wall-clock date as a string.
static string clockTime ()
Return the current wall-clock time as a string.
Detailed Description
Read access to the system clock with formatting.
Source files
clock.H
clock.C
Definition at line 50 of file clock.H.
Constructor & Destructor Documentation
clock()
clock ()
Null constructor which stores the start time.
Definition at line 114 of file clock.C.
Member Function Documentation
getTime()
time_t getTime () static
Get the current clock time in seconds.
Definition at line 45 of file clock.C.
Referenced by clock::clockTime(), clock::clockTimeIncrement(), clock::date(), clock::dateTime(), clock::elapsedClockTime(), and clock::rawDate().
rawDate()
const struct tm rawDate () static
Return the current wall-clock date as a raw struct.
Definition at line 51 of file clock.C.
References clock::getTime().
dateTime()
Foam::string dateTime () static
Return the current wall-clock date/time as a string.
format according to ISO-8601 (yyyy-mm-ddThh:mm:ss)
Definition at line 59 of file clock.C.
References clock::getTime(), and Foam::setw().
Referenced by OBJedgeFormat::write(), and STARCDedgeFormat::writeCase().
date()
Foam::string date () static
Return the current wall-clock date as a string.
Definition at line 79 of file clock.C.
References clock::getTime(), and Foam::setw().
Referenced by argList::parse(), and JobInfo::write().
clockTime()
Foam::string clockTime () static
Return the current wall-clock time as a string.
Definition at line 95 of file clock.C.
References clock::getTime(), and Foam::setw().
Referenced by argList::parse(), and JobInfo::write().
elapsedClockTime()
time_t elapsedClockTime () const
Returns wall-clock time from clock instantiation.
Definition at line 124 of file clock.C.
References clock::getTime().
clockTimeIncrement()
time_t clockTimeIncrement () const
Returns wall-clock time from last call of clockTimeIncrement()
Definition at line 131 of file clock.C.
References clock::getTime().
The documentation for this class was generated from the following files:
src/OpenFOAM/global/clock/clock.H
src/OpenFOAM/global/clock/clock.C