OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointConstraint Class Reference
Accumulates point constraints through successive applications of the applyConstraint function.
Public Member Functions
pointConstraint ()
Construct null.
pointConstraint (const Tuple2< label, vector > &)
Construct from components.
pointConstraint (Istream &)
Construct from Istream.
void applyConstraint (const vector &cd)
Apply and accumulate the effect of the given constraint direction.
void combine (const pointConstraint &)
Combine constraints.
tensor constraintTransformation () const
Return the accumulated constraint transformation tensor.
void unconstrainedDirections (label &n, tensor &vecs) const
Return the accumulated unconstrained directions. Directions.
Public Member Functions inherited from Tuple2< label, vector >
Tuple2 ()
Null constructor for lists.
Tuple2 (const label &f, const vector &s)
Construct from components.
Tuple2 (Istream &is)
Construct from Istream.
const label & first () const
Return first.
label & first ()
Return first.
const vector & second () const
Return second.
vector & second ()
Return second.
Detailed Description
Accumulates point constraints through successive applications of the applyConstraint function.
After all the constraints have been entered the resulting transformation tensor is returned by the constraintTransformation function.
Source files
pointConstraint.H
pointConstraintI.H
Definition at line 56 of file pointConstraint.H.
Constructor & Destructor Documentation
pointConstraint() [1/3]
pointConstraint () inline
Construct null.
Definition at line 28 of file pointConstraintI.H.
Referenced by Foam::transform().
pointConstraint() [2/3]
pointConstraint (const Tuple2< label, vector > & pc) inline
Construct from components.
Definition at line 34 of file pointConstraintI.H.
pointConstraint() [3/3]
pointConstraint (Istream & is) inline
Construct from Istream.
Definition at line 40 of file pointConstraintI.H.
Member Function Documentation
applyConstraint()
void applyConstraint (const vector & cd) inline
Apply and accumulate the effect of the given constraint direction.
Definition at line 48 of file pointConstraintI.H.
References Foam::e, Tuple2< label, vector >::first(), Foam::mag(), Tuple2< label, vector >::second(), and Vector< Cmpt >::zero.
Referenced by emptyPointPatch::applyConstraint(), wedgePointPatch::applyConstraint(), symmetryPlanePointPatch::applyConstraint(), cyclicSlipPointPatch::applyConstraint(), nonuniformTransformCyclicPointPatch::applyConstraint(), symmetryPointPatch::applyConstraint(), pointConstraint::combine(), plane::constrainTranslation(), and listPlusEqOp< T >::operator()().
combine()
void combine (const pointConstraint & pc) inline
Combine constraints.
Definition at line 77 of file pointConstraintI.H.
References pointConstraint::applyConstraint(), Foam::e, Tuple2< label, vector >::first(), Tuple2< Type1, Type2 >::first(), Foam::mag(), n, Tuple2< label, vector >::second(), Tuple2< Type1, Type2 >::second(), and Vector< Cmpt >::zero.
Referenced by orientation::constrainRotation(), axis::constrainRotation(), point::constrainTranslation(), line::constrainTranslation(), and combineConstraintsEqOp::operator()().
constraintTransformation()
Foam::tensor constraintTransformation () const inline
Return the accumulated constraint transformation tensor.
Definition at line 118 of file pointConstraintI.H.
References Tuple2< label, vector >::first(), Foam::I, Tuple2< label, vector >::second(), Foam::sqr(), and Tensor< scalar >::zero.
Referenced by sixDoFRigidBodyMotion::addConstraints().
unconstrainedDirections()
void unconstrainedDirections (label & n, tensor & vecs) const inline
Return the accumulated unconstrained directions. Directions.
coded as first n rows of tensor.
Definition at line 139 of file pointConstraintI.H.
References Foam::e, Tuple2< label, vector >::first(), Foam::mag(), Tuple2< label, vector >::second(), FixedList< T, Size >::size(), x, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointConstraint/pointConstraint.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointConstraint/pointConstraintI.H