OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
linearInterpolationWeights Class Reference
Public Member Functions
TypeName ("linear")
Runtime type information.
linearInterpolationWeights (const scalarField &samples)
Construct from components.
virtual ~linearInterpolationWeights ()
Destructor.
virtual bool valueWeights (const scalar t, labelList &indices, scalarField &weights) const
Calculate weights and indices to calculate t from samples.
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList &indices, scalarField &weights) const
Calculate weights and indices to calculate integrand of t1..t2.
Public Member Functions inherited from interpolationWeights
TypeName ("interpolationWeights")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolationWeights, word,(const scalarField &samples),(samples))
interpolationWeights (const scalarField &samples)
Construct from components.
virtual ~interpolationWeights ()
Destructor.
template<class ListType1 , class ListType2 >
Foam::outerProduct< typename ListType1::value_type, typename ListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Additional Inherited Members
Static Public Member Functions inherited from interpolationWeights
static autoPtr< interpolationWeights > New (const word &type, const scalarField &samples)
Return a reference to the selected interpolationWeights.
template<class ListType1 , class ListType2 >
static outerProduct< typename ListType1::value_type, typename ListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Helper: weighted sum.
Protected Attributes inherited from interpolationWeights
const scalarField & samples_
Detailed Description
Source files
linearInterpolationWeights.H
linearInterpolationWeights.C
Definition at line 47 of file linearInterpolationWeights.H.
Constructor & Destructor Documentation
linearInterpolationWeights()
linearInterpolationWeights (const scalarField & samples)
Construct from components.
Definition at line 76 of file linearInterpolationWeights.C.
References linearInterpolationWeights::valueWeights().
~linearInterpolationWeights()
virtual ~linearInterpolationWeights () inline virtual
Destructor.
Definition at line 84 of file linearInterpolationWeights.H.
References linearInterpolationWeights::valueWeights().
Member Function Documentation
TypeName()
TypeName ("linear")
Runtime type information.
valueWeights()
bool valueWeights (const scalar t, labelList & indices, scalarField & weights) const virtual
Calculate weights and indices to calculate t from samples.
Returns true if indices changed.
Implements interpolationWeights.
Definition at line 88 of file linearInterpolationWeights.C.
References Foam::findLower(), interpolationWeights::samples_, List< T >::setSize(), and List< T >::size().
Referenced by linearInterpolationWeights::linearInterpolationWeights(), splineInterpolationWeights::valueWeights(), and linearInterpolationWeights::~linearInterpolationWeights().
integrationWeights()
bool integrationWeights (const scalar t1, const scalar t2, labelList & indices, scalarField & weights) const virtual
Calculate weights and indices to calculate integrand of t1..t2.
from samples. Returns true if indices changed.
Find lower or equal index
Find lower index
Implements interpolationWeights.
Definition at line 155 of file linearInterpolationWeights.C.
References d(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::findLower(), Pair< Type >::first(), forAll, UList< T >::last(), interpolationWeights::samples_, Pair< Type >::second(), List< T >::setSize(), and List< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationWeights/linearInterpolationWeights/linearInterpolationWeights.H
src/OpenFOAM/interpolations/interpolationWeights/linearInterpolationWeights/linearInterpolationWeights.C