OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
rawGraph Class Reference
A raw xy graph output.
Public Member Functions
TypeName ("raw")
Runtime type information.
rawGraph ()
Construct null.
~rawGraph ()
Destructor.
const word & ext () const
Return the appropriate fileName extension.
void write (const graph &, Ostream &os) const
Write graph in appropriate format.
Public Member Functions inherited from graph::writer
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
Declare run-time constructor selection table.
writer ()
Construct null.
virtual ~writer ()
Destructor.
Static Public Attributes
static const word ext_
FileName extension for this graph format.
Additional Inherited Members
Static Public Member Functions inherited from graph::writer
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Protected Member Functions inherited from graph::writer
void writeXY (const scalarField &x, const scalarField &y, Ostream &) const
Detailed Description
A raw xy graph output.
Source files
rawGraph.H
rawGraph.C
Definition at line 48 of file rawGraph.H.
Constructor & Destructor Documentation
rawGraph()
rawGraph () inline
Construct null.
Definition at line 65 of file rawGraph.H.
~rawGraph()
~rawGraph () inline
Destructor.
Definition at line 70 of file rawGraph.H.
References rawGraph::ext(), rawGraph::ext_, and rawGraph::write().
Member Function Documentation
TypeName()
TypeName ("raw")
Runtime type information.
ext()
const word& ext () const inline virtual
Return the appropriate fileName extension.
for this graph format
Implements graph::writer.
Definition at line 80 of file rawGraph.H.
Referenced by rawGraph::~rawGraph().
write()
void write (const graph & , Ostream &) const virtual
Write graph in appropriate format.
Implements graph::writer.
Definition at line 43 of file rawGraph.C.
References graph::writeTable().
Referenced by rawGraph::~rawGraph().
Member Data Documentation
ext_
const word ext_ static
FileName extension for this graph format.
Definition at line 59 of file rawGraph.H.
Referenced by rawGraph::~rawGraph().
The documentation for this class was generated from the following files:
src/OpenFOAM/graph/writers/rawGraph/rawGraph.H
src/OpenFOAM/graph/writers/rawGraph/rawGraph.C