OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
splineInterpolationWeights Class Reference
Catmull-Rom spline interpolation.
Public Member Functions
TypeName ("spline")
Runtime type information.
splineInterpolationWeights (const scalarField &samples, const bool checkEqualDistance=true)
Construct from components. By default make sure samples are.
virtual ~splineInterpolationWeights ()
Destructor.
virtual bool valueWeights (const scalar t, labelList &indices, scalarField &weights) const
Calculate weights and indices to calculate t from samples.
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList &indices, scalarField &weights) const
Calculate weights and indices to calculate integrand of t1..t2.
Public Member Functions inherited from interpolationWeights
TypeName ("interpolationWeights")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolationWeights, word,(const scalarField &samples),(samples))
interpolationWeights (const scalarField &samples)
Construct from components.
virtual ~interpolationWeights ()
Destructor.
template<class ListType1 , class ListType2 >
Foam::outerProduct< typename ListType1::value_type, typename ListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Additional Inherited Members
Static Public Member Functions inherited from interpolationWeights
static autoPtr< interpolationWeights > New (const word &type, const scalarField &samples)
Return a reference to the selected interpolationWeights.
template<class ListType1 , class ListType2 >
static outerProduct< typename ListType1::value_type, typename ListType2::value_type >::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Helper: weighted sum.
Protected Attributes inherited from interpolationWeights
const scalarField & samples_
Detailed Description
Catmull-Rom spline interpolation.
Source files
splineInterpolationWeights.H
splineInterpolationWeights.C
Definition at line 48 of file splineInterpolationWeights.H.
Constructor & Destructor Documentation
splineInterpolationWeights()
splineInterpolationWeights (const scalarField & samples, const bool checkEqualDistance = true)
Construct from components. By default make sure samples are.
equidistant.
Definition at line 50 of file splineInterpolationWeights.C.
References d(), Foam::endl(), Foam::mag(), Foam::nl, splineInterpolationWeights::valueWeights(), and WarningIn.
~splineInterpolationWeights()
virtual ~splineInterpolationWeights () inline virtual
Destructor.
Definition at line 77 of file splineInterpolationWeights.H.
References splineInterpolationWeights::integrationWeights(), and splineInterpolationWeights::valueWeights().
Member Function Documentation
TypeName()
TypeName ("spline")
Runtime type information.
valueWeights()
bool valueWeights (const scalar t, labelList & indices, scalarField & weights) const virtual
Calculate weights and indices to calculate t from samples.
Returns true if indices changed.
Implements interpolationWeights.
Definition at line 85 of file splineInterpolationWeights.C.
References Foam::findLower(), Foam::constant::physicoChemical::mu, List< T >::setSize(), List< T >::size(), and linearInterpolationWeights::valueWeights().
Referenced by splineInterpolationWeights::splineInterpolationWeights(), and splineInterpolationWeights::~splineInterpolationWeights().
integrationWeights()
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList & indices, scalarField & weights) const inline virtual
Calculate weights and indices to calculate integrand of t1..t2.
from samples. Returns true if indices changed.
Implements interpolationWeights.
Definition at line 95 of file splineInterpolationWeights.H.
References notImplemented.
Referenced by splineInterpolationWeights::~splineInterpolationWeights().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationWeights/splineInterpolationWeights/splineInterpolationWeights.H
src/OpenFOAM/interpolations/interpolationWeights/splineInterpolationWeights/splineInterpolationWeights.C