OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LduMatrix< Type, DType, LUType >::solver Class Reference abstract
Abstract base-class for LduMatrix solvers.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
solver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~solver ()
const word & fieldName () const
const LduMatrix< Type, DType, LUType > & matrix () const
virtual void read (const dictionary &solverDict)
Read and reset the solver parameters from the given dictionary.
virtual SolverPerformance< Type > solve (Field< Type > &psi) const =0
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField) const
Return the matrix norm used to normalise the residual for the.
Static Public Member Functions
static autoPtr< solver > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Return a new solver.
Protected Member Functions
template<class T >
void readControl (const dictionary &controlDict, T &control, const word &controlName)
Read a control parameter from controlDict.
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
dictionary controlDict_
dictionary of controls
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
Type tolerance_
Final convergence tolerance.
Type relTol_
Convergence tolerance relative to the initial.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::solver
Abstract base-class for LduMatrix solvers.
Definition at line 112 of file LduMatrix.H.
Constructor & Destructor Documentation
solver()
solver (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict)
Definition at line 126 of file LduMatrixSolver.C.
Referenced by LduMatrix< Type, DType, LUType >::solver::New().
~solver()
virtual ~solver () inline virtual
Definition at line 219 of file LduMatrix.H.
Member Function Documentation
readControl()
void readControl (const dictionary & controlDict, T & control, const word & controlName) inline protected
Read a control parameter from controlDict.
Definition at line 31 of file LduMatrixI.H.
References dictionary::found(), and dictionary::lookup().
Referenced by LduMatrix< Type, DType, LUType >::solver::readControls().
readControls()
void readControls () protected virtual
Read the control parameters from the controlDict_.
Reimplemented in SmoothSolver< Type, DType, LUType >.
Definition at line 149 of file LduMatrixSolver.C.
References LduMatrix< Type, DType, LUType >::solver::controlDict_, LduMatrix< Type, DType, LUType >::solver::maxIter_, LduMatrix< Type, DType, LUType >::solver::minIter_, LduMatrix< Type, DType, LUType >::solver::read(), LduMatrix< Type, DType, LUType >::solver::readControl(), LduMatrix< Type, DType, LUType >::solver::relTol_, and LduMatrix< Type, DType, LUType >::solver::tolerance_.
Referenced by LduMatrix< Type, DType, LUType >::solver::read().
type()
virtual const word& type () const pure virtual
Runtime type information.
Referenced by LduMatrix< Type, DType, LUType >::preconditioner::preconditionT().
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , solver , symMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict) , (fieldName, matrix, solverDict))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , solver , asymMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict) , (fieldName, matrix, solverDict))
New()
Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::solver > New (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict) static
Return a new solver.
Definition at line 34 of file LduMatrixSolver.C.
References LduMatrix< Type, DType, LUType >::asymmetric(), LduMatrix< Type, DType, LUType >::diagonal(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), LduMatrix< Type, DType, LUType >::solver::solver(), and LduMatrix< Type, DType, LUType >::symmetric().
Referenced by LduMatrix< Type, DType, LUType >::preconditioner::preconditioner().
fieldName()
const word& fieldName () const inline
Definition at line 227 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::solver::fieldName_.
matrix()
const LduMatrix<Type, DType, LUType>& matrix () const inline
Definition at line 232 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::solver::matrix_, LduMatrix< Type, DType, LUType >::solver::normFactor(), psi, LduMatrix< Type, DType, LUType >::solver::read(), and LduMatrix< Type, DType, LUType >::solver::solve().
Referenced by LduMatrix< Type, DType, LUType >::preconditioner::New(), and TDILUPreconditioner< Type, DType, LUType >::TDILUPreconditioner().
read()
void read (const dictionary & solverDict) virtual
Read and reset the solver parameters from the given dictionary.
Reimplemented in DiagonalSolver< Type, DType, LUType >.
Definition at line 160 of file LduMatrixSolver.C.
References LduMatrix< Type, DType, LUType >::solver::controlDict_, LduMatrix< Type, DType, LUType >::solver::normFactor(), and LduMatrix< Type, DType, LUType >::solver::readControls().
Referenced by LduMatrix< Type, DType, LUType >::solver::matrix(), LduMatrix< Type, DType, LUType >::solver::readControls(), and LduMatrix< Type, DType, LUType >::preconditioner::~preconditioner().
solve()
virtual SolverPerformance<Type> solve (Field< Type > & psi) const pure virtual
Implemented in PBiCCCG< Type, DType, LUType >, PBiCICG< Type, DType, LUType >, PCICG< Type, DType, LUType >, SmoothSolver< Type, DType, LUType >, and DiagonalSolver< Type, DType, LUType >.
Referenced by LduMatrix< Type, DType, LUType >::solver::matrix().
normFactor()
Type normFactor (const Field< Type > & psi, const Field< Type > & Apsi, Field< Type > & tmpField) const
Return the matrix norm used to normalise the residual for the.
stopping criterion
Definition at line 171 of file LduMatrixSolver.C.
References Foam::cmptMag(), Foam::cmptMultiply(), Foam::gAverage(), Foam::gSum(), LduMatrix< Type, DType, LUType >::solver::matrix_, and Foam::stabilise().
Referenced by LduMatrix< Type, DType, LUType >::solver::matrix(), and LduMatrix< Type, DType, LUType >::solver::read().
Member Data Documentation
fieldName_
word fieldName_ protected
Definition at line 118 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::fieldName(), and LduMatrix< Type, DType, LUType >::smoother::fieldName().
matrix_
const LduMatrix<Type, DType, LUType>& matrix_ protected
Definition at line 119 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::matrix(), LduMatrix< Type, DType, LUType >::smoother::matrix(), and LduMatrix< Type, DType, LUType >::solver::normFactor().
controlDict_
dictionary controlDict_ protected
dictionary of controls
Definition at line 122 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::read(), and LduMatrix< Type, DType, LUType >::solver::readControls().
maxIter_
label maxIter_ protected
Maximum number of iterations in the solver.
Definition at line 125 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::readControls().
minIter_
label minIter_ protected
Minimum number of iterations in the solver.
Definition at line 128 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::readControls().
tolerance_
Type tolerance_ protected
Final convergence tolerance.
Definition at line 131 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::readControls().
relTol_
Type relTol_ protected
Convergence tolerance relative to the initial.
Definition at line 134 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::readControls().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixI.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixSolver.C