OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gnuplotGraph Class Reference
Output in gnuplot (http://www.gnuplot.info) format.
Public Member Functions
TypeName ("gnuplot")
Runtime type information.
gnuplotGraph ()
Construct null.
~gnuplotGraph ()
Destructor.
const word & ext () const
Return the appropriate fileName extension.
void write (const graph &, Ostream &os) const
Write graph in appropriate format.
Public Member Functions inherited from graph::writer
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
Declare run-time constructor selection table.
writer ()
Construct null.
virtual ~writer ()
Destructor.
Static Public Attributes
static const word ext_
FileName extension for this graph format.
Additional Inherited Members
Static Public Member Functions inherited from graph::writer
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Protected Member Functions inherited from graph::writer
void writeXY (const scalarField &x, const scalarField &y, Ostream &) const
Detailed Description
Output in gnuplot (http://www.gnuplot.info) format.
Source files
gnuplotGraph.H
gnuplotGraph.C
Definition at line 48 of file gnuplotGraph.H.
Constructor & Destructor Documentation
gnuplotGraph()
gnuplotGraph () inline
Construct null.
Definition at line 65 of file gnuplotGraph.H.
~gnuplotGraph()
~gnuplotGraph () inline
Destructor.
Definition at line 70 of file gnuplotGraph.H.
References gnuplotGraph::ext(), gnuplotGraph::ext_, and gnuplotGraph::write().
Member Function Documentation
TypeName()
TypeName ("gnuplot")
Runtime type information.
ext()
const word& ext () const inline virtual
Return the appropriate fileName extension.
for this graph format
Implements graph::writer.
Definition at line 80 of file gnuplotGraph.H.
Referenced by gnuplotGraph::~gnuplotGraph().
write()
void write (const graph & , Ostream &) const virtual
Write graph in appropriate format.
Implements graph::writer.
Definition at line 43 of file gnuplotGraph.C.
References Foam::endl(), forAllConstIter(), IOstream::name(), graph::title(), graph::x(), graph::xName(), and graph::yName().
Referenced by gnuplotGraph::~gnuplotGraph().
Member Data Documentation
ext_
const word ext_ static
FileName extension for this graph format.
Definition at line 59 of file gnuplotGraph.H.
Referenced by gnuplotGraph::~gnuplotGraph().
The documentation for this class was generated from the following files:
src/OpenFOAM/graph/writers/gnuplotGraph/gnuplotGraph.H
src/OpenFOAM/graph/writers/gnuplotGraph/gnuplotGraph.C