OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
graph::writer Class Reference abstract
Abstract base class for a graph writer.
Public Member Functions
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
Declare run-time constructor selection table.
writer ()
Construct null.
virtual ~writer ()
Destructor.
virtual const word & ext () const =0
Return the appropriate fileName extension.
virtual void write (const graph &, Ostream &) const =0
Write graph in appropriate format.
Static Public Member Functions
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Protected Member Functions
void writeXY (const scalarField &x, const scalarField &y, Ostream &) const
Detailed Description
Abstract base class for a graph writer.
Definition at line 184 of file graph.H.
Constructor & Destructor Documentation
writer()
writer () inline
Construct null.
Definition at line 224 of file graph.H.
~writer()
virtual ~writer () inline virtual
Destructor.
Definition at line 229 of file graph.H.
References format(), Foam::name(), graph::operator<<, path(), graph::wordify(), graph::write(), and graph::writeTable().
Member Function Documentation
writeXY()
void writeXY (const scalarField & x, const scalarField & y, Ostream & os) const protected
Definition at line 197 of file graph.C.
References Foam::endl(), forAll, Foam::setw(), and token::SPACE.
Referenced by graph::writer::New().
TypeName()
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , writer , word , () , ())
Declare run-time constructor selection table.
New()
Foam::autoPtr< Foam::graph::writer > New (const word & writeFormat) static
Return a reference to the selected writer.
Definition at line 164 of file graph.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, and graph::writer::writeXY().
Referenced by graph::write(), and graph::y().
ext()
virtual const word& ext () const pure virtual
Return the appropriate fileName extension.
for this graph format
Implemented in xmgrGraph, gnuplotGraph, jplotGraph, and rawGraph.
write()
virtual void write (const graph & , Ostream &) const pure virtual
Write graph in appropriate format.
Implemented in xmgrGraph, gnuplotGraph, jplotGraph, and rawGraph.
The documentation for this class was generated from the following files:
src/OpenFOAM/graph/graph.H
src/OpenFOAM/graph/graph.C