OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
xmgrGraph Class Reference
Output and agr file for xmgrace (http://plasma-gate.weizmann.ac.il/Grace/)
Public Member Functions
TypeName ("xmgr")
Runtime type information.
xmgrGraph ()
Construct null.
~xmgrGraph ()
Destructor.
const word & ext () const
Return the appropriate fileName extension.
void write (const graph &, Ostream &os) const
Write graph in appropriate format.
Public Member Functions inherited from graph::writer
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
Declare run-time constructor selection table.
writer ()
Construct null.
virtual ~writer ()
Destructor.
Static Public Attributes
static const word ext_
FileName extension for this graph format.
Additional Inherited Members
Static Public Member Functions inherited from graph::writer
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Protected Member Functions inherited from graph::writer
void writeXY (const scalarField &x, const scalarField &y, Ostream &) const
Detailed Description
Output and agr file for xmgrace (http://plasma-gate.weizmann.ac.il/Grace/)
Source files
xmgrGraph.H
xmgrGraph.C
Definition at line 49 of file xmgrGraph.H.
Constructor & Destructor Documentation
xmgrGraph()
xmgrGraph () inline
Construct null.
Definition at line 66 of file xmgrGraph.H.
~xmgrGraph()
~xmgrGraph () inline
Destructor.
Definition at line 71 of file xmgrGraph.H.
References xmgrGraph::ext(), xmgrGraph::ext_, and xmgrGraph::write().
Member Function Documentation
TypeName()
TypeName ("xmgr")
Runtime type information.
ext()
const word& ext () const inline virtual
Return the appropriate fileName extension.
for this graph format
Implements graph::writer.
Definition at line 81 of file xmgrGraph.H.
Referenced by xmgrGraph::~xmgrGraph().
write()
void write (const graph & , Ostream &) const virtual
Write graph in appropriate format.
Implements graph::writer.
Definition at line 43 of file xmgrGraph.C.
References Foam::endl(), forAllConstIter(), IOstream::name(), Foam::nl, graph::title(), graph::x(), graph::xName(), and graph::yName().
Referenced by xmgrGraph::~xmgrGraph().
Member Data Documentation
ext_
const word ext_ static
FileName extension for this graph format.
Definition at line 60 of file xmgrGraph.H.
Referenced by xmgrGraph::~xmgrGraph().
The documentation for this class was generated from the following files:
src/OpenFOAM/graph/writers/xmgrGraph/xmgrGraph.H
src/OpenFOAM/graph/writers/xmgrGraph/xmgrGraph.C