OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
openFoamTableReader< Type > Class Template Reference
Reads an interpolation table from a file - OpenFOAM-format.
Public Member Functions
TypeName ("openFoam")
Runtime type information.
openFoamTableReader (const dictionary &dict)
Construct from dictionary.
virtual autoPtr< tableReader< Type > > clone () const
Construct and return a copy.
virtual ~openFoamTableReader ()
Destructor.
virtual void operator() (const fileName &, List< Tuple2< scalar, Type > > &)
Read the table.
virtual void operator() (const fileName &, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Read 2D table.
Public Member Functions inherited from tableReader< Type >
TypeName ("tableReader")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, tableReader, dictionary,(const dictionary &dict),(dict))
tableReader (const dictionary &dict)
Construct from dictionary.
virtual ~tableReader ()
Destructor.
virtual void write (Ostream &os) const
Write additional information.
Additional Inherited Members
Static Public Member Functions inherited from tableReader< Type >
static autoPtr< tableReader > New (const dictionary &spec)
Return a reference to the selected tableReader.
Detailed Description
template<class Type>
class Foam::openFoamTableReader< Type >
Reads an interpolation table from a file - OpenFOAM-format.
Source files
openFoamTableReader.H
openFoamTableReader.C
Definition at line 49 of file openFoamTableReader.H.
Constructor & Destructor Documentation
openFoamTableReader()
openFoamTableReader (const dictionary & dict)
Construct from dictionary.
Definition at line 32 of file openFoamTableReader.C.
~openFoamTableReader()
~openFoamTableReader () virtual
Destructor.
Definition at line 41 of file openFoamTableReader.C.
Referenced by openFoamTableReader< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("openFoam")
Runtime type information.
clone()
virtual autoPtr<tableReader<Type> > clone () const inline virtual
Construct and return a copy.
Implements tableReader< Type >.
Definition at line 66 of file openFoamTableReader.H.
References openFoamTableReader< Type >::operator()(), and openFoamTableReader< Type >::~openFoamTableReader().
operator()() [1/2]
void operator() (const fileName & fName, List< Tuple2< scalar, Type > > & data) virtual
Read the table.
Implements tableReader< Type >.
Definition at line 49 of file openFoamTableReader.C.
Referenced by openFoamTableReader< Type >::clone().
operator()() [2/2]
void operator() (const fileName & fName, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > & data) virtual
Read 2D table.
Implements tableReader< Type >.
Definition at line 61 of file openFoamTableReader.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationTable/tableReaders/openFoam/openFoamTableReader.H
src/OpenFOAM/interpolations/interpolationTable/tableReaders/openFoam/openFoamTableReader.C