OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
lduMatrix::solver Class Reference abstract
Abstract base-class for lduMatrix solvers.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
virtual void read (const dictionary &)
Read and reset the solver parameters from the given stream.
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const =0
scalar normFactor (const scalarField &psi, const scalarField &source, const scalarField &Apsi, scalarField &tmpField) const
Return the matrix norm used to normalise the residual for the.
Static Public Member Functions
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new solver.
Protected Member Functions
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
dictionary of controls
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
scalar tolerance_
Final convergence tolerance.
scalar relTol_
Convergence tolerance relative to the initial.
Detailed Description
Abstract base-class for lduMatrix solvers.
Definition at line 91 of file lduMatrix.H.
Constructor & Destructor Documentation
solver()
solver (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Definition at line 142 of file lduMatrixSolver.C.
Referenced by lduMatrix::solver::New().
~solver()
virtual ~solver () inline virtual
Destructor.
Definition at line 208 of file lduMatrix.H.
Member Function Documentation
readControls()
void readControls () protected virtual
Read the control parameters from the controlDict_.
Reimplemented in smoothSolver, and GAMGPreconditioner.
Definition at line 164 of file lduMatrixSolver.C.
References Foam::e.
Referenced by smoothSolver::readControls(), and GAMGSolver::~GAMGSolver().
type()
virtual const word& type () const pure virtual
Runtime type information.
Referenced by lduMatrix::preconditioner::preconditionT().
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , solver , symMatrix , (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls) , (fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , solver , asymMatrix , (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls) , (fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
New()
Foam::autoPtr< Foam::lduMatrix::solver > New (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls) static
Return a new solver.
Definition at line 41 of file lduMatrixSolver.C.
References lduMatrix::asymmetric(), lduMatrix::diagonal(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), Foam::name(), Foam::nl, lduMatrix::solver::solver(), and lduMatrix::symmetric().
Referenced by lduMatrix::preconditioner::preconditioner().
fieldName()
const word& fieldName () const inline
Definition at line 216 of file lduMatrix.H.
References lduMatrix::solver::fieldName_.
matrix()
const lduMatrix& matrix () const inline
Definition at line 221 of file lduMatrix.H.
References lduMatrix::solver::matrix_.
Referenced by DICPreconditioner::DICPreconditioner(), DILUPreconditioner::DILUPreconditioner(), and lduMatrix::preconditioner::New().
interfaceBouCoeffs()
const FieldField<Field, scalar>& interfaceBouCoeffs () const inline
Definition at line 226 of file lduMatrix.H.
References lduMatrix::solver::interfaceBouCoeffs_.
interfaceIntCoeffs()
const FieldField<Field, scalar>& interfaceIntCoeffs () const inline
Definition at line 231 of file lduMatrix.H.
References lduMatrix::solver::interfaceIntCoeffs_.
interfaces()
const lduInterfaceFieldPtrsList& interfaces () const inline
Definition at line 236 of file lduMatrix.H.
References lduMatrix::solver::interfaces_, lduMatrix::solver::normFactor(), psi, lduMatrix::solver::read(), and lduMatrix::solver::solve().
read()
void read (const dictionary & solverControls) virtual
Read and reset the solver parameters from the given stream.
Reimplemented in diagonalSolver.
Definition at line 173 of file lduMatrixSolver.C.
References lduMatrix::solver::normFactor().
Referenced by lduMatrix::solver::interfaces(), and lduMatrix::preconditioner::~preconditioner().
solve()
virtual solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const pure virtual
Implemented in GAMGSolver, smoothSolver, PBiCG, PCG, and diagonalSolver.
Referenced by lduMatrix::solver::interfaces().
normFactor()
Foam::scalar normFactor (const scalarField & psi, const scalarField & source, const scalarField & Apsi, scalarField & tmpField) const
Return the matrix norm used to normalise the residual for the.
stopping criterion
Definition at line 181 of file lduMatrixSolver.C.
References Foam::gAverage(), Foam::gSum(), Foam::mag(), and SolverPerformance< Type >::small_.
Referenced by lduMatrix::solver::interfaces(), and lduMatrix::solver::read().
Member Data Documentation
fieldName_
word fieldName_ protected
Definition at line 97 of file lduMatrix.H.
Referenced by lduMatrix::solver::fieldName(), lduMatrix::smoother::fieldName(), and GAMGSolver::solve().
matrix_
const lduMatrix& matrix_ protected
Definition at line 98 of file lduMatrix.H.
Referenced by lduMatrix::solver::matrix(), lduMatrix::smoother::matrix(), and GAMGSolver::solve().
interfaceBouCoeffs_
const FieldField<Field, scalar>& interfaceBouCoeffs_ protected
Definition at line 99 of file lduMatrix.H.
Referenced by lduMatrix::solver::interfaceBouCoeffs(), lduMatrix::smoother::interfaceBouCoeffs(), and GAMGSolver::solve().
interfaceIntCoeffs_
const FieldField<Field, scalar>& interfaceIntCoeffs_ protected
Definition at line 100 of file lduMatrix.H.
Referenced by lduMatrix::solver::interfaceIntCoeffs(), lduMatrix::smoother::interfaceIntCoeffs(), and GAMGSolver::solve().
interfaces_
lduInterfaceFieldPtrsList interfaces_ protected
Definition at line 101 of file lduMatrix.H.
Referenced by lduMatrix::solver::interfaces(), lduMatrix::smoother::interfaces(), and GAMGSolver::solve().
controlDict_
dictionary controlDict_ protected
dictionary of controls
Definition at line 104 of file lduMatrix.H.
Referenced by GAMGSolver::solve().
maxIter_
label maxIter_ protected
Maximum number of iterations in the solver.
Definition at line 107 of file lduMatrix.H.
minIter_
label minIter_ protected
Minimum number of iterations in the solver.
Definition at line 110 of file lduMatrix.H.
tolerance_
scalar tolerance_ protected
Final convergence tolerance.
Definition at line 113 of file lduMatrix.H.
Referenced by GAMGSolver::solve().
relTol_
scalar relTol_ protected
Convergence tolerance relative to the initial.
Definition at line 116 of file lduMatrix.H.
Referenced by GAMGSolver::solve().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.H
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixSolver.C