OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DiagonalPreconditioner< Type, DType, LUType > Class Template Reference
Diagonal preconditioner for both symmetric and asymmetric matrices.
Public Member Functions
TypeName ("diagonal")
Runtime type information.
DiagonalPreconditioner (const typename LduMatrix< Type, DType, LUType >::solver &sol, const dictionary &preconditionerDict)
Construct from matrix components and preconditioner data dictionary.
virtual ~DiagonalPreconditioner ()
virtual void read (const dictionary &preconditionerDict)
Read and reset the preconditioner parameters from the given.
virtual void precondition (Field< Type > &wA, const Field< Type > &rA) const
Return wA the preconditioned form of residual rA.
virtual void preconditionT (Field< Type > &wT, const Field< Type > &rT) const
Return wT the transpose-matrix preconditioned form of.
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::preconditioner
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Additional Inherited Members
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::preconditioner
static autoPtr< preconditioner > New (const solver &sol, const dictionary &preconditionerDict)
Return a new preconditioner.
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::preconditioner
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::DiagonalPreconditioner< Type, DType, LUType >
Diagonal preconditioner for both symmetric and asymmetric matrices.
The inverse (reciprocal for scalar) of the diagonal is calculated and stored.
Source files
DiagonalPreconditioner.H
DiagonalPreconditioner.C
Definition at line 52 of file DiagonalPreconditioner.H.
Constructor & Destructor Documentation
DiagonalPreconditioner()
DiagonalPreconditioner (const typename LduMatrix< Type, DType, LUType >::solver & sol, const dictionary & preconditionerDict)
Construct from matrix components and preconditioner data dictionary.
Definition at line 32 of file DiagonalPreconditioner.C.
References inv().
~DiagonalPreconditioner()
virtual ~DiagonalPreconditioner () inline virtual
Definition at line 89 of file DiagonalPreconditioner.H.
References DiagonalPreconditioner< Type, DType, LUType >::precondition(), DiagonalPreconditioner< Type, DType, LUType >::preconditionT(), and DiagonalPreconditioner< Type, DType, LUType >::read().
Member Function Documentation
TypeName()
TypeName ("diagonal")
Runtime type information.
read()
void read (const dictionary & preconditionerDict) virtual
Read and reset the preconditioner parameters from the given.
dictionary
Reimplemented from LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 56 of file DiagonalPreconditioner.C.
References DiagonalPreconditioner< Type, DType, LUType >::precondition().
Referenced by DiagonalPreconditioner< Type, DType, LUType >::~DiagonalPreconditioner().
precondition()
void precondition (Field< Type > & wA, const Field< Type > & rA) const virtual
Return wA the preconditioned form of residual rA.
Implements LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 62 of file DiagonalPreconditioner.C.
References UList< Type >::begin(), dot(), and List< Type >::size().
Referenced by DiagonalPreconditioner< Type, DType, LUType >::preconditionT(), DiagonalPreconditioner< Type, DType, LUType >::read(), and DiagonalPreconditioner< Type, DType, LUType >::~DiagonalPreconditioner().
preconditionT()
virtual void preconditionT (Field< Type > & wT, const Field< Type > & rT) const inline virtual
Return wT the transpose-matrix preconditioned form of.
residual rT.
Reimplemented from LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 109 of file DiagonalPreconditioner.H.
References DiagonalPreconditioner< Type, DType, LUType >::precondition().
Referenced by DiagonalPreconditioner< Type, DType, LUType >::~DiagonalPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Preconditioners/DiagonalPreconditioner/DiagonalPreconditioner.H
src/OpenFOAM/matrices/LduMatrix/Preconditioners/DiagonalPreconditioner/DiagonalPreconditioner.C