OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
processorLduInterfaceField Class Reference abstract
Abstract base class for processor coupled interfaces.
Public Member Functions
TypeName ("processorLduInterfaceField")
Runtime type information.
processorLduInterfaceField ()
Construct given coupled patch.
virtual ~processorLduInterfaceField ()
Destructor.
virtual int comm () const =0
Return communicator used for comms.
virtual int myProcNo () const =0
Return processor number.
virtual int neighbProcNo () const =0
Return neigbour processor number.
virtual bool doTransform () const =0
Is the transform required.
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual int rank () const =0
Return rank of component for transform.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &f, const direction cmpt) const
Transform given patch component field.
Detailed Description
Abstract base class for processor coupled interfaces.
Source files
processorLduInterfaceField.H
processorLduInterfaceField.C
Definition at line 49 of file processorLduInterfaceField.H.
Constructor & Destructor Documentation
processorLduInterfaceField()
processorLduInterfaceField () inline
Construct given coupled patch.
Definition at line 61 of file processorLduInterfaceField.H.
References processorLduInterfaceField::comm(), processorLduInterfaceField::doTransform(), f(), processorLduInterfaceField::forwardT(), processorLduInterfaceField::myProcNo(), processorLduInterfaceField::neighbProcNo(), processorLduInterfaceField::rank(), processorLduInterfaceField::transformCoupleField(), and processorLduInterfaceField::~processorLduInterfaceField().
~processorLduInterfaceField()
~processorLduInterfaceField () virtual
Destructor.
Definition at line 39 of file processorLduInterfaceField.C.
References processorLduInterfaceField::transformCoupleField().
Referenced by processorLduInterfaceField::processorLduInterfaceField().
Member Function Documentation
TypeName()
TypeName ("processorLduInterfaceField")
Runtime type information.
comm()
virtual int comm () const pure virtual
Return communicator used for comms.
Implemented in processorFvPatchField< Type >, and processorGAMGInterfaceField.
Referenced by processorLduInterfaceField::processorLduInterfaceField().
myProcNo()
virtual int myProcNo () const pure virtual
Return processor number.
Implemented in processorFvPatchField< Type >, and processorGAMGInterfaceField.
Referenced by processorLduInterfaceField::processorLduInterfaceField().
neighbProcNo()
virtual int neighbProcNo () const pure virtual
Return neigbour processor number.
Implemented in processorFvPatchField< Type >, and processorGAMGInterfaceField.
Referenced by processorLduInterfaceField::processorLduInterfaceField().
doTransform()
virtual bool doTransform () const pure virtual
Is the transform required.
Implemented in processorFvPatchField< Type >, processorGAMGInterfaceField, and processorCyclicFvPatchField< Type >.
Referenced by processorGAMGInterfaceField::processorGAMGInterfaceField(), processorLduInterfaceField::processorLduInterfaceField(), and processorLduInterfaceField::transformCoupleField().
forwardT()
virtual const tensorField& forwardT () const pure virtual
Return face transformation tensor.
Implemented in processorFvPatchField< Type >, processorGAMGInterfaceField, and processorCyclicFvPatchField< Type >.
Referenced by processorLduInterfaceField::processorLduInterfaceField(), and processorLduInterfaceField::transformCoupleField().
rank()
virtual int rank () const pure virtual
Return rank of component for transform.
Implemented in processorFvPatchField< Type >, and processorGAMGInterfaceField.
Referenced by processorGAMGInterfaceField::processorGAMGInterfaceField(), and processorLduInterfaceField::processorLduInterfaceField().
transformCoupleField() [1/2]
void transformCoupleField (Field< Type > & f) const
Transform given patch field.
Definition at line 115 of file processorLduInterfaceField.H.
References processorLduInterfaceField::doTransform(), processorLduInterfaceField::forwardT(), and Foam::transform().
Referenced by processorLduInterfaceField::processorLduInterfaceField(), and processorLduInterfaceField::~processorLduInterfaceField().
transformCoupleField() [2/2]
void transformCoupleField (scalarField & f, const direction cmpt) const
Transform given patch component field.
Definition at line 46 of file processorLduInterfaceField.C.
References Foam::component(), Foam::diag(), and Foam::pow().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/processorLduInterfaceField/processorLduInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/processorLduInterfaceField/processorLduInterfaceField.C