OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LduMatrix< Type, DType, LUType >::preconditioner Class Reference abstract
Abstract base-class for LduMatrix preconditioners.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
preconditioner (const solver &sol)
virtual ~preconditioner ()
virtual void read (const dictionary &preconditionerDict)
Read and reset the preconditioner parameters.
virtual void precondition (Field< Type > &wA, const Field< Type > &rA) const =0
Return wA the preconditioned form of residual rA.
virtual void preconditionT (Field< Type > &wT, const Field< Type > &rT) const
Return wT the transpose-matrix preconditioned form of.
Static Public Member Functions
static autoPtr< preconditioner > New (const solver &sol, const dictionary &preconditionerDict)
Return a new preconditioner.
Protected Attributes
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::preconditioner
Abstract base-class for LduMatrix preconditioners.
Definition at line 358 of file LduMatrix.H.
Constructor & Destructor Documentation
preconditioner()
preconditioner (const solver & sol) inline
Definition at line 404 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::solver::New().
~preconditioner()
virtual ~preconditioner () inline virtual
Definition at line 424 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::solver::read().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , preconditioner , symMatrix , (const solver &sol, const dictionary &preconditionerDict) , (sol, preconditionerDict))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , preconditioner , asymMatrix , (const solver &sol, const dictionary &preconditionerDict) , (sol, preconditionerDict))
New()
Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::preconditioner > New (const solver & sol, const dictionary & preconditionerDict) static
Return a new preconditioner.
Definition at line 33 of file LduMatrixPreconditioner.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), and LduMatrix< Type, DType, LUType >::solver::matrix().
read()
virtual void read (const dictionary & preconditionerDict) inline virtual
Read and reset the preconditioner parameters.
from the given dictionary
Reimplemented in DiagonalPreconditioner< Type, DType, LUType >, and NoPreconditioner< Type, DType, LUType >.
Definition at line 432 of file LduMatrix.H.
precondition()
virtual void precondition (Field< Type > & wA, const Field< Type > & rA) const pure virtual
Return wA the preconditioned form of residual rA.
Implemented in DiagonalPreconditioner< Type, DType, LUType >, TDILUPreconditioner< Type, DType, LUType >, and NoPreconditioner< Type, DType, LUType >.
preconditionT()
virtual void preconditionT (Field< Type > & wT, const Field< Type > & rT) const inline virtual
Return wT the transpose-matrix preconditioned form of.
residual rT. This is only required for preconditioning asymmetric matrices.
Reimplemented in DiagonalPreconditioner< Type, DType, LUType >, TDILUPreconditioner< Type, DType, LUType >, and NoPreconditioner< Type, DType, LUType >.
Definition at line 446 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::ClassName(), LduMatrix< Type, DType, LUType >::LduMatrix(), notImplemented, LduMatrix< Type, DType, LUType >::solver::type(), and LduMatrix< Type, DType, LUType >::~LduMatrix().
Member Data Documentation
solver_
const solver& solver_ protected
Reference to the base-solver this preconditioner is used with.
Definition at line 365 of file LduMatrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixPreconditioner.C