OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
lduMatrix::smoother Class Reference abstract
Abstract base-class for lduMatrix smoothers.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
smoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
virtual ~smoother ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
virtual void smooth (scalarField &psi, const scalarField &source, const direction cmpt, const label nSweeps) const =0
Smooth the solution for a given number of sweeps.
Static Public Member Functions
static word getName (const dictionary &)
Find the smoother name (directly or from a sub-dictionary)
static autoPtr< smoother > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new smoother.
Protected Attributes
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
const lduInterfaceFieldPtrsList & interfaces_
Detailed Description
Abstract base-class for lduMatrix smoothers.
Definition at line 265 of file lduMatrix.H.
Constructor & Destructor Documentation
smoother()
smoother (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Definition at line 162 of file lduMatrixSmoother.C.
Referenced by lduMatrix::smoother::New().
~smoother()
virtual ~smoother () inline virtual
Destructor.
Definition at line 359 of file lduMatrix.H.
Member Function Documentation
getName()
Foam::word getName (const dictionary & solverControls) static
Find the smoother name (directly or from a sub-dictionary)
Definition at line 40 of file lduMatrixSmoother.C.
References entry::dict(), Foam::e, entry::isDict(), dictionary::lookup(), dictionary::lookupEntry(), Foam::name(), lduMatrix::smoother::New(), and entry::stream().
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , smoother , symMatrix , (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces) , (fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , smoother , asymMatrix , (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces) , (fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
New()
Foam::autoPtr< Foam::lduMatrix::smoother > New (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls) static
Return a new smoother.
Definition at line 62 of file lduMatrixSmoother.C.
References lduMatrix::asymmetric(), entry::dict(), Foam::e, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, entry::isDict(), dictionary::lookup(), dictionary::lookupEntry(), Foam::name(), Foam::nl, lduMatrix::smoother::smoother(), entry::stream(), and lduMatrix::symmetric().
Referenced by lduMatrix::smoother::getName(), smoothSolver::solve(), and GAMGSolver::solve().
fieldName()
const word& fieldName () const inline
Definition at line 367 of file lduMatrix.H.
References lduMatrix::solver::fieldName_.
matrix()
const lduMatrix& matrix () const inline
Definition at line 372 of file lduMatrix.H.
References lduMatrix::solver::matrix_.
interfaceBouCoeffs()
const FieldField<Field, scalar>& interfaceBouCoeffs () const inline
Definition at line 377 of file lduMatrix.H.
References lduMatrix::solver::interfaceBouCoeffs_.
interfaceIntCoeffs()
const FieldField<Field, scalar>& interfaceIntCoeffs () const inline
Definition at line 382 of file lduMatrix.H.
References lduMatrix::solver::interfaceIntCoeffs_.
interfaces()
const lduInterfaceFieldPtrsList& interfaces () const inline
Definition at line 387 of file lduMatrix.H.
References lduMatrix::solver::interfaces_, psi, and Foam::fvc::smooth().
smooth()
virtual void smooth (scalarField & psi, const scalarField & source, const direction cmpt, const label nSweeps) const pure virtual
Smooth the solution for a given number of sweeps.
Implemented in nonBlockingGaussSeidelSmoother, GaussSeidelSmoother, symGaussSeidelSmoother, FDICSmoother, DICSmoother, DICGaussSeidelSmoother, DILUGaussSeidelSmoother, and DILUSmoother.
Member Data Documentation
fieldName_
word fieldName_ protected
Definition at line 271 of file lduMatrix.H.
matrix_
const lduMatrix& matrix_ protected
Definition at line 272 of file lduMatrix.H.
interfaceBouCoeffs_
const FieldField<Field, scalar>& interfaceBouCoeffs_ protected
Definition at line 273 of file lduMatrix.H.
interfaceIntCoeffs_
const FieldField<Field, scalar>& interfaceIntCoeffs_ protected
Definition at line 274 of file lduMatrix.H.
interfaces_
const lduInterfaceFieldPtrsList& interfaces_ protected
Definition at line 275 of file lduMatrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.H
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixSmoother.C