OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SolverPerformance< Type > Class Template Reference
SolverPerformance is the class returned by the LduMatrix solver containing performance statistics.
Public Member Functions
ClassName ("SolverPerformance")
SolverPerformance ()
SolverPerformance (const word &solverName, const word &fieldName, const Type &iRes=pTraits< Type >::zero, const Type &fRes=pTraits< Type >::zero, const label nIter=0, const bool converged=false, const bool singular=false)
const word & solverName () const
Return solver name.
word & solverName ()
Return solver name.
const word & fieldName () const
Return field name.
const Type & initialResidual () const
Return initial residual.
Type & initialResidual ()
Return initial residual.
const Type & finalResidual () const
Return final residual.
Type & finalResidual ()
Return final residual.
label nIterations () const
Return number of iterations.
label & nIterations ()
Return number of iterations.
bool converged () const
Has the solver converged?
bool singular () const
Is the matrix singular?
bool checkConvergence (const Type &tolerance, const Type &relTolerance)
Check, store and return convergence.
bool checkSingularity (const Type &residual)
Singularity test.
void print (Ostream &os) const
Print summary of solver performance to the given stream.
bool operator!= (const SolverPerformance< Type > &) const
Static Public Attributes
static const scalar great_
Large Type for the use in solvers.
static const scalar small_
Small Type for the use in solvers.
static const scalar vsmall_
Very small Type for the use in solvers.
Friends
SolverPerformance< Type > max (const SolverPerformance< Type > &, const SolverPerformance< Type > &)
Return the element-wise maximum of two SolverPerformance<Type>s.
Istream & operator>> (Istream &, SolverPerformance< Type > &)
Ostream & operator (Ostream &, const SolverPerformance< Type > &)
Detailed Description
template<class Type>
class Foam::SolverPerformance< Type >
SolverPerformance is the class returned by the LduMatrix solver containing performance statistics.
Source files
SolverPerformance.H
SolverPerformance.C
Definition at line 49 of file SolverPerformance.H.
Constructor & Destructor Documentation
SolverPerformance() [1/2]
SolverPerformance () inline
Definition at line 108 of file SolverPerformance.H.
SolverPerformance() [2/2]
SolverPerformance (const word & solverName, const word & fieldName, const Type & iRes = pTraits<Type>::zero, const Type & fRes = pTraits<Type>::zero, const label nIter = 0, const bool converged = false, const bool singular = false) inline
Definition at line 119 of file SolverPerformance.H.
Member Function Documentation
ClassName()
ClassName ("SolverPerformance< Type >")
solverName() [1/2]
const word& solverName () const inline
Return solver name.
Definition at line 142 of file SolverPerformance.H.
Referenced by SolverPerformance< Type >::operator!=(), and fvMatrix< Type >::solveSegregated().
solverName() [2/2]
word& solverName () inline
Return solver name.
Definition at line 148 of file SolverPerformance.H.
fieldName()
const word& fieldName () const inline
Return field name.
Definition at line 155 of file SolverPerformance.H.
Referenced by data::setSolverPerformance().
initialResidual() [1/2]
const Type& initialResidual () const inline
Return initial residual.
Definition at line 162 of file SolverPerformance.H.
Referenced by radiativeIntensityRay::correct(), simpleControl::criteriaSatisfied(), pimpleControl::criteriaSatisfied(), SolverPerformance< Type >::operator!=(), SmoothSolver< Type, DType, LUType >::solve(), PBiCG::solve(), PCG::solve(), smoothSolver::solve(), and GAMGSolver::solve().
initialResidual() [2/2]
Type& initialResidual () inline
Return initial residual.
Definition at line 168 of file SolverPerformance.H.
finalResidual() [1/2]
const Type& finalResidual () const inline
Return final residual.
Definition at line 175 of file SolverPerformance.H.
Referenced by SolverPerformance< Type >::operator!=(), SmoothSolver< Type, DType, LUType >::solve(), PCG::solve(), PBiCG::solve(), smoothSolver::solve(), and GAMGSolver::solve().
finalResidual() [2/2]
Type& finalResidual () inline
Return final residual.
Definition at line 181 of file SolverPerformance.H.
nIterations() [1/2]
label nIterations () const inline
Return number of iterations.
Definition at line 188 of file SolverPerformance.H.
Referenced by SolverPerformance< Type >::operator!=(), SmoothSolver< Type, DType, LUType >::solve(), PCG::solve(), PBiCG::solve(), smoothSolver::solve(), and GAMGSolver::solve().
nIterations() [2/2]
label& nIterations () inline
Return number of iterations.
Definition at line 194 of file SolverPerformance.H.
converged()
bool converged () const inline
Has the solver converged?
Definition at line 201 of file SolverPerformance.H.
References SolverPerformance< Type >::checkConvergence(), SolverPerformance< Type >::checkSingularity(), SolverPerformance< Type >::operator!=(), SolverPerformance< Type >::print(), and SolverPerformance< Type >::singular().
Referenced by SolverPerformance< Type >::operator!=().
singular()
bool singular () const
Is the matrix singular?
Definition at line 48 of file SolverPerformance.C.
References SolverPerformance< Type >::checkConvergence().
Referenced by SolverPerformance< Type >::converged(), and SolverPerformance< Type >::operator!=().
checkConvergence()
bool checkConvergence (const Type & tolerance, const Type & relTolerance)
Check, store and return convergence.
Definition at line 61 of file SolverPerformance.C.
References cmptMultiply(), Foam::endl(), Foam::Info, and SolverPerformance< Type >::print().
Referenced by SolverPerformance< Type >::converged(), SolverPerformance< Type >::singular(), SmoothSolver< Type, DType, LUType >::solve(), PCG::solve(), PBiCG::solve(), smoothSolver::solve(), and GAMGSolver::solve().
checkSingularity()
bool checkSingularity (const Type & residual)
Singularity test.
Definition at line 33 of file SolverPerformance.C.
References component().
Referenced by SolverPerformance< Type >::converged(), PCG::solve(), and PBiCG::solve().
print()
void print (Ostream & os) const
Print summary of solver performance to the given stream.
Definition at line 97 of file SolverPerformance.C.
References component(), and Foam::endl().
Referenced by SolverPerformance< Type >::checkConvergence(), SolverPerformance< Type >::converged(), fvMatrix< Type >::fvSolver::solve(), GAMGSolver::solve(), fvMatrix< Type >::solveCoupled(), and fvMatrix< Type >::solveSegregated().
operator!=()
bool operator!= (const SolverPerformance< Type > & sp) const
Definition at line 131 of file SolverPerformance.C.
References SolverPerformance< Type >::converged(), SolverPerformance< Type >::finalResidual(), SolverPerformance< Type >::initialResidual(), Foam::max(), SolverPerformance< Type >::nIterations(), SolverPerformance< Type >::singular(), and SolverPerformance< Type >::solverName().
Referenced by SolverPerformance< Type >::converged().
Friends And Related Function Documentation
max
SolverPerformance<Type> max (const SolverPerformance< Type > & , const SolverPerformance< Type > &) friend
Return the element-wise maximum of two SolverPerformance<Type>s.
operator>>
Istream& operator>> (Istream & , SolverPerformance< Type > &) friend
operator
Ostream& operator (Ostream & , const SolverPerformance< Type > &) friend
Member Data Documentation
great_
const scalar great_ static
Large Type for the use in solvers.
Definition at line 97 of file SolverPerformance.H.
Referenced by PBiCG::solve(), and PCG::solve().
small_
const scalar small_ static
Small Type for the use in solvers.
Definition at line 100 of file SolverPerformance.H.
Referenced by lduMatrix::solver::normFactor().
vsmall_
const scalar vsmall_ static
Very small Type for the use in solvers.
Definition at line 103 of file SolverPerformance.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/SolverPerformance.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/solverPerformance.C