OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DiagonalSolver< Type, DType, LUType > Class Template Reference
Foam::DiagonalSolver.
Public Member Functions
TypeName ("diagonal")
Runtime type information.
DiagonalSolver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Construct from matrix.
void read (const dictionary &solverDict)
Read and reset the solver parameters from the given dictionary.
virtual SolverPerformance< Type > solve (Field< Type > &psi) const
Solve the matrix with this solver.
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
solver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~solver ()
const word & fieldName () const
const LduMatrix< Type, DType, LUType > & matrix () const
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField) const
Return the matrix norm used to normalise the residual for the.
Additional Inherited Members
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
static autoPtr< solver > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Return a new solver.
Protected Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
template<class T >
void readControl (const dictionary &controlDict, T &control, const word &controlName)
Read a control parameter from controlDict.
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::solver
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
dictionary controlDict_
dictionary of controls
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
Type tolerance_
Final convergence tolerance.
Type relTol_
Convergence tolerance relative to the initial.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::DiagonalSolver< Type, DType, LUType >
Foam::DiagonalSolver.
Source files
DiagonalSolver.H
DiagonalSolver.C
Definition at line 49 of file DiagonalSolver.H.
Constructor & Destructor Documentation
DiagonalSolver()
DiagonalSolver (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict)
Construct from matrix.
Definition at line 32 of file DiagonalSolver.C.
References DiagonalSolver< Type, DType, LUType >::read().
Member Function Documentation
TypeName()
TypeName ("diagonal")
Runtime type information.
read()
void read (const dictionary & solverDict) virtual
Read and reset the solver parameters from the given dictionary.
Reimplemented from LduMatrix< Type, DType, LUType >::solver.
Definition at line 51 of file DiagonalSolver.C.
References DiagonalSolver< Type, DType, LUType >::solve().
Referenced by DiagonalSolver< Type, DType, LUType >::DiagonalSolver().
solve()
Foam::SolverPerformance< Type > solve (Field< Type > & psi) const virtual
Solve the matrix with this solver.
Implements LduMatrix< Type, DType, LUType >::solver.
Definition at line 60 of file DiagonalSolver.C.
Referenced by DiagonalSolver< Type, DType, LUType >::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Solvers/DiagonalSolver/DiagonalSolver.H
src/OpenFOAM/matrices/LduMatrix/Solvers/DiagonalSolver/DiagonalSolver.C