OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DICPreconditioner Class Reference
Simplified diagonal-based incomplete Cholesky preconditioner for symmetric matrices (symmetric equivalent of DILU). The reciprocal of the preconditioned diagonal is calculated and stored.
Public Member Functions
TypeName ("DIC")
Runtime type information.
DICPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
virtual ~DICPreconditioner ()
Destructor.
virtual void precondition (scalarField &wA, const scalarField &rA, const direction cmpt=0) const
Return wA the preconditioned form of residual rA.
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Destructor.
virtual void read (const dictionary &)
Read and reset the preconditioner parameters.
virtual void preconditionT (scalarField &wT, const scalarField &rT, const direction cmpt=0) const
Return wT the transpose-matrix preconditioned form of.
Static Public Member Functions
static void calcReciprocalD (scalarField &rD, const lduMatrix &matrix)
Calculate the reciprocal of the preconditioned diagonal.
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
Find the preconditioner name (directly or from a sub-dictionary)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Return a new preconditioner.
Additional Inherited Members
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
Simplified diagonal-based incomplete Cholesky preconditioner for symmetric matrices (symmetric equivalent of DILU). The reciprocal of the preconditioned diagonal is calculated and stored.
Source files
DICPreconditioner.H
DICPreconditioner.C
Definition at line 50 of file DICPreconditioner.H.
Constructor & Destructor Documentation
DICPreconditioner()
DICPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
Definition at line 43 of file DICPreconditioner.C.
References DICPreconditioner::calcReciprocalD(), and lduMatrix::solver::matrix().
~DICPreconditioner()
virtual ~DICPreconditioner () inline virtual
Destructor.
Definition at line 77 of file DICPreconditioner.H.
References DICPreconditioner::calcReciprocalD(), and DICPreconditioner::precondition().
Member Function Documentation
TypeName()
TypeName ("DIC")
Runtime type information.
calcReciprocalD()
void calcReciprocalD (scalarField & rD, const lduMatrix & matrix) static
Calculate the reciprocal of the preconditioned diagonal.
Definition at line 58 of file DICPreconditioner.C.
References UList< T >::begin(), lduMatrix::lduAddr(), lduAddressing::lowerAddr(), DICPreconditioner::precondition(), List< T >::size(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by DICPreconditioner::DICPreconditioner(), DICSmoother::DICSmoother(), and DICPreconditioner::~DICPreconditioner().
precondition()
void precondition (scalarField & wA, const scalarField & rA, const direction cmpt = 0) const virtual
Return wA the preconditioned form of residual rA.
Implements lduMatrix::preconditioner.
Definition at line 88 of file DICPreconditioner.C.
References UList< T >::begin(), and List< T >::size().
Referenced by DICPreconditioner::calcReciprocalD(), and DICPreconditioner::~DICPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/preconditioners/DICPreconditioner/DICPreconditioner.H
src/OpenFOAM/matrices/lduMatrix/preconditioners/DICPreconditioner/DICPreconditioner.C