OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GAMGProcAgglomeration Class Reference abstract
Processor agglomeration of GAMGAgglomerations.
Public Member Functions
TypeName ("GAMGProcAgglomeration")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
Runtime selection table for pure geometric agglomerators.
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~GAMGProcAgglomeration ()
Destructor.
virtual bool agglomerate ()=0
Modify agglomeration. Return true if modified.
Static Public Member Functions
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Return the selected agglomerator.
Protected Member Functions
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
Debug: write agglomeration info.
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< int > &agglomProcIDs, const label procAgglomComm)
Agglomerate a level. Return true if anything has changed.
Static Protected Member Functions
static labelListList globalCellCells (const lduMesh &)
Debug: calculate global cell-cells.
Protected Attributes
GAMGAgglomeration & agglom_
Reference to agglomeration.
Detailed Description
Processor agglomeration of GAMGAgglomerations.
Source files
GAMGProcAgglomeration.H
GAMGProcAgglomeration.C
Definition at line 52 of file GAMGProcAgglomeration.H.
Constructor & Destructor Documentation
GAMGProcAgglomeration()
GAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Construct given agglomerator and controls.
Definition at line 343 of file GAMGProcAgglomeration.C.
References GAMGProcAgglomeration::New().
~GAMGProcAgglomeration()
~GAMGProcAgglomeration () virtual
Destructor.
Definition at line 389 of file GAMGProcAgglomeration.C.
Member Function Documentation
printStats()
void printStats (Ostream & os, GAMGAgglomeration & agglom) const protected
Debug: write agglomeration info.
Definition at line 42 of file GAMGProcAgglomeration.C.
References GAMGAgglomeration::agglomProcIDs_, Foam::endl(), GAMGAgglomeration::faceRestrictAddressing(), forAll, GAMGProcAgglomeration::globalCellCells(), GAMGAgglomeration::hasMeshLevel(), lduMesh::info(), Foam::max(), GAMGAgglomeration::meshLevel(), GAMGAgglomeration::nCells(), GAMGAgglomeration::nFaces(), Foam::nl, GAMGAgglomeration::patchFaceRestrictAddressing(), GAMGAgglomeration::procAgglomMap_, GAMGAgglomeration::procCellOffsets_, GAMGAgglomeration::procCommunicator_, GAMGAgglomeration::restrictAddressing(), GAMGAgglomeration::restrictAddressing_, List< T >::size(), and GAMGAgglomeration::size().
agglomerate() [1/2]
bool agglomerate (const label fineLevelIndex, const labelList & procAgglomMap, const labelList & masterProcs, const List< int > & agglomProcIDs, const label procAgglomComm) protected
Agglomerate a level. Return true if anything has changed.
Definition at line 265 of file GAMGProcAgglomeration.C.
References lduMesh::comm(), and UPstream::myProcNo().
globalCellCells()
Foam::labelListList globalCellCells (const lduMesh & mesh) static protected
Debug: calculate global cell-cells.
Definition at line 119 of file GAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), Foam::constant::physicoChemical::c1, lduMesh::comm(), forAll, lduMesh::interfaces(), lduMesh::lduAddr(), lduAddressing::lowerAddr(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::parRun(), UPtrList< T >::set(), UPtrList< T >::size(), lduAddressing::size(), Foam::stableSort(), lduAddressing::upperAddr(), and UPstream::waitRequests().
Referenced by GAMGProcAgglomeration::printStats().
TypeName()
TypeName ("GAMGProcAgglomeration")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , GAMGProcAgglomeration , GAMGAgglomeration , (GAMGAgglomeration &agglom, const dictionary &controlDict) , (agglom, controlDict))
Runtime selection table for pure geometric agglomerators.
New()
Foam::autoPtr< Foam::GAMGProcAgglomeration > New (const word & type, GAMGAgglomeration & agglom, const dictionary & controlDict) static
Return the selected agglomerator.
Definition at line 353 of file GAMGProcAgglomeration.C.
References Foam::debug::controlDict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
Referenced by GAMGProcAgglomeration::GAMGProcAgglomeration().
agglomerate() [2/2]
virtual bool agglomerate () pure virtual
Modify agglomeration. Return true if modified.
Implemented in manualGAMGProcAgglomeration, procFacesGAMGProcAgglomeration, eagerGAMGProcAgglomeration, masterCoarsestGAMGProcAgglomeration, and noneGAMGProcAgglomeration.
Referenced by masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), and GAMGProcAgglomeration::globalCellCells().
Member Data Documentation
agglom_
GAMGAgglomeration& agglom_ protected
Reference to agglomeration.
Definition at line 60 of file GAMGProcAgglomeration.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/GAMGProcAgglomeration/GAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/GAMGProcAgglomeration/GAMGProcAgglomeration.C