OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
eagerGAMGProcAgglomeration Class Reference
'Eager' processor agglomeration of GAMGAgglomerations: at every level agglomerates 'mergeLevels' number of processors onto the minimum processor number.
Public Member Functions
TypeName ("eager")
Runtime type information.
eagerGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~eagerGAMGProcAgglomeration ()
Destructor.
virtual bool agglomerate ()
Modify agglomeration. Return true if modified.
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
Runtime selection table for pure geometric agglomerators.
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~GAMGProcAgglomeration ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Return the selected agglomerator.
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
Debug: write agglomeration info.
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< int > &agglomProcIDs, const label procAgglomComm)
Agglomerate a level. Return true if anything has changed.
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Debug: calculate global cell-cells.
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
Reference to agglomeration.
Detailed Description
'Eager' processor agglomeration of GAMGAgglomerations: at every level agglomerates 'mergeLevels' number of processors onto the minimum processor number.
Source files
eagerGAMGProcAgglomeration.H
eagerGAMGProcAgglomeration.C
Definition at line 53 of file eagerGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
eagerGAMGProcAgglomeration()
eagerGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Construct given agglomerator and controls.
Definition at line 51 of file eagerGAMGProcAgglomeration.C.
References eagerGAMGProcAgglomeration::~eagerGAMGProcAgglomeration().
~eagerGAMGProcAgglomeration()
~eagerGAMGProcAgglomeration () virtual
Destructor.
Definition at line 64 of file eagerGAMGProcAgglomeration.C.
References forAllReverse, and UPstream::freeCommunicator().
Referenced by eagerGAMGProcAgglomeration::eagerGAMGProcAgglomeration().
Member Function Documentation
TypeName()
TypeName ("eager")
Runtime type information.
agglomerate()
bool agglomerate () virtual
Modify agglomeration. Return true if modified.
Implements GAMGProcAgglomeration.
Definition at line 78 of file eagerGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), GAMGAgglomeration::calculateRegionMaster(), lduMesh::comm(), Foam::endl(), forAll, UList< T >::last(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), and Foam::Pout.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/eagerGAMGProcAgglomeration/eagerGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/eagerGAMGProcAgglomeration/eagerGAMGProcAgglomeration.C