OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
BICCG Class Reference
Diagonal incomplete LU preconditioned BiCG solver derived from the general preconditioned BiCG solver PBiCG but with the choice of preconditioner pre-selected.
Public Member Functions
TypeName ("BICCG")
Runtime type information.
BICCG (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Construct from matrix components and solver data stream.
BICCG (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalar tolerance, const scalar relTol=0.0)
Construct from matrix components and tolerances.
virtual ~BICCG ()
Destructor.
Public Member Functions inherited from PBiCG
TypeName ("PBiCG")
Runtime type information.
PBiCG (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Construct from matrix components and solver data stream.
virtual ~PBiCG ()
Destructor.
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Solve the matrix with this solver.
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
virtual void read (const dictionary &)
Read and reset the solver parameters from the given stream.
scalar normFactor (const scalarField &psi, const scalarField &source, const scalarField &Apsi, scalarField &tmpField) const
Return the matrix norm used to normalise the residual for the.
Static Public Member Functions
static dictionary solverDict (const scalar tol, const scalar relTol)
Return the dictionary constructed from the components.
static dictionary solverDict (Istream &)
Return the dictionary constructed from the old-style data-stream.
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new solver.
Additional Inherited Members
Protected Member Functions inherited from lduMatrix::solver
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
dictionary of controls
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
scalar tolerance_
Final convergence tolerance.
scalar relTol_
Convergence tolerance relative to the initial.
Detailed Description
Diagonal incomplete LU preconditioned BiCG solver derived from the general preconditioned BiCG solver PBiCG but with the choice of preconditioner pre-selected.
Deprecated:
This solver is present for backward-compatibility and the PBiCG solver should be used instead. (deprecated Apr 2008)
Source files
BICCG.H
BICCG.C
Definition at line 54 of file BICCG.H.
Constructor & Destructor Documentation
BICCG() [1/2]
BICCG (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Construct from matrix components and solver data stream.
Definition at line 70 of file BICCG.C.
BICCG() [2/2]
BICCG (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const scalar tolerance, const scalar relTol = 0.0)
Construct from matrix components and tolerances.
Definition at line 92 of file BICCG.C.
~BICCG()
virtual ~BICCG () inline virtual
Destructor.
Definition at line 112 of file BICCG.H.
Member Function Documentation
solverDict() [1/2]
Foam::dictionary solverDict (const scalar tol, const scalar relTol) static
Return the dictionary constructed from the components.
Needed for backward compatibility
Definition at line 42 of file BICCG.C.
References dictionary::add(), and dict.
Referenced by solution::upgradeSolverDict().
solverDict() [2/2]
Foam::dictionary solverDict (Istream & is) static
Return the dictionary constructed from the old-style data-stream.
Needed for backward compatibility
Definition at line 56 of file BICCG.C.
References Foam::readScalar().
TypeName()
TypeName ("BICCG")
Runtime type information.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/BICCG/BICCG.H
src/OpenFOAM/matrices/lduMatrix/solvers/BICCG/BICCG.C