OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SymmetricSquareMatrix< Type > Class Template Reference
A templated 2D square symmetric matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Public Member Functions
SymmetricSquareMatrix ()
Null constructor.
SymmetricSquareMatrix (const label n)
Construct given number of rows/columns.
SymmetricSquareMatrix (const label m, const label n)
Construct with given number of rows/columns.
SymmetricSquareMatrix (const label m, const label n, const Type &)
Construct with given number of rows/columns.
SymmetricSquareMatrix (Istream &)
Construct from Istream.
autoPtr< SymmetricSquareMatrix< Type > > clone () const
Clone.
Type & operator() (const label r, const label c)
Return subscript-checked row of Matrix.
const Type & operator() (const label r, const label c) const
Return subscript-checked row of constant Matrix.
Public Member Functions inherited from Matrix< SymmetricSquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label n, const label m)
Construct given number of rows and columns.
Matrix (const label n, const label m, const Type &)
Construct with given number of rows and columns.
Matrix (const Matrix< SymmetricSquareMatrix< Type >, Type > &)
Copy constructor.
Matrix (Istream &)
Construct from Istream.
autoPtr< Matrix< SymmetricSquareMatrix< Type >, Type > > clone () const
Clone.
~Matrix ()
Destructor.
label n () const
Return the number of rows.
label m () const
Return the number of columns.
label size () const
Return the number of elements in matrix (n*m)
void checki (const label i) const
Check index i is within valid range (0 ... n-1).
void checkj (const label j) const
Check index j is within valid range (0 ... m-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (Matrix< SymmetricSquareMatrix< Type >, Type > &)
Transfer the contents of the argument Matrix into this Matrix.
SymmetricSquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
void operator= (const Matrix< SymmetricSquareMatrix< Type >, Type > &)
Assignment operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Additional Inherited Members
Static Public Member Functions inherited from Matrix< SymmetricSquareMatrix< Type >, Type >
static const Matrix< SymmetricSquareMatrix< Type >, Type > & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::SymmetricSquareMatrix< Type >
A templated 2D square symmetric matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Source files
SymmetricSquareMatrix.H
SymmetricSquareMatrixI.H
SymmetricSquareMatrix.C
Definition at line 51 of file SymmetricSquareMatrix.H.
Constructor & Destructor Documentation
SymmetricSquareMatrix() [1/5]
SymmetricSquareMatrix () inline
Null constructor.
Definition at line 29 of file SymmetricSquareMatrixI.H.
Referenced by SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [2/5]
SymmetricSquareMatrix (const label n) inline
Construct given number of rows/columns.
Definition at line 36 of file SymmetricSquareMatrixI.H.
References SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [3/5]
SymmetricSquareMatrix (const label m, const label n) inline
Construct with given number of rows/columns.
Definition at line 44 of file SymmetricSquareMatrixI.H.
References Foam::exit(), Foam::FatalError, FatalErrorIn, and SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [4/5]
SymmetricSquareMatrix (const label m, const label n, const Type & t) inline
Construct with given number of rows/columns.
and value for all elements.
Definition at line 65 of file SymmetricSquareMatrixI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorIn.
SymmetricSquareMatrix() [5/5]
SymmetricSquareMatrix (Istream & is) inline
Construct from Istream.
Definition at line 86 of file SymmetricSquareMatrixI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::SymmetricSquareMatrix< Type > > clone () const inline
Clone.
Definition at line 94 of file SymmetricSquareMatrixI.H.
References Matrix< SymmetricSquareMatrix< Type >, Type >::operator.
operator()() [1/2]
Type & operator() (const label r, const label c) inline
Return subscript-checked row of Matrix.
Definition at line 105 of file SymmetricSquareMatrixI.H.
References Foam::constant::universal::c, Matrix< SymmetricSquareMatrix< Type >, Type >::operator, and Matrix< SymmetricSquareMatrix< Type >, Type >::operator[]().
operator()() [2/2]
const Type & operator() (const label r, const label c) const inline
Return subscript-checked row of constant Matrix.
Definition at line 123 of file SymmetricSquareMatrixI.H.
References Foam::constant::universal::c, and Matrix< SymmetricSquareMatrix< Type >, Type >::operator[]().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/SymmetricSquareMatrix/SymmetricSquareMatrix.H
src/OpenFOAM/matrices/SymmetricSquareMatrix/SymmetricSquareMatrixI.H