OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
procLduMatrix Class Reference
I/O for lduMatrix and interface values.
Public Member Functions
procLduMatrix (const lduMatrix &ldum, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces)
procLduMatrix (Istream &is)
label size () const
Friends
class LUscalarMatrix
Ostream & operator<< (Ostream &, const procLduMatrix &)
Detailed Description
I/O for lduMatrix and interface values.
Source files
procLduMatrix.H
procLduMatrix.C
Definition at line 61 of file procLduMatrix.H.
Constructor & Destructor Documentation
procLduMatrix() [1/2]
procLduMatrix (const lduMatrix & ldum, const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Definition at line 33 of file procLduMatrix.C.
References forAll, and UPtrList< T >::set().
procLduMatrix() [2/2]
procLduMatrix (Istream & is)
Definition at line 78 of file procLduMatrix.C.
Member Function Documentation
size()
label size () const inline
Definition at line 98 of file procLduMatrix.H.
References procLduMatrix::operator<<, and List< T >::size().
Referenced by LUscalarMatrix::LUscalarMatrix().
Friends And Related Function Documentation
LUscalarMatrix
friend class LUscalarMatrix friend
Definition at line 81 of file procLduMatrix.H.
operator<<
Ostream& operator<< (Ostream & , const procLduMatrix &) friend
Referenced by procLduMatrix::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/procLduMatrix.H
src/OpenFOAM/matrices/LUscalarMatrix/procLduMatrix.C