OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SVD Class Reference
Singular value decomposition of a rectangular matrix.
Public Member Functions
SVD (const scalarRectangularMatrix &A, const scalar minCondition=0)
Construct from a rectangular Matrix.
const scalarRectangularMatrix & U () const
Return U.
const scalarRectangularMatrix & V () const
Return the square matrix V.
const scalarDiagonalMatrix & S () const
Return the singular values.
const scalarRectangularMatrix & VSinvUt () const
Return VSinvUt (the pseudo inverse)
label nZeros () const
Return the number of zero singular values.
scalar minNonZeroS () const
Return the minimum non-zero singular value.
Detailed Description
Singular value decomposition of a rectangular matrix.
Source files
SVD.H
SVDI.H
SVD.C
Definition at line 52 of file SVD.H.
Constructor & Destructor Documentation
SVD()
SVD (const scalarRectangularMatrix & A, const scalar minCondition = 0)
Construct from a rectangular Matrix.
Definition at line 33 of file SVD.C.
References Foam::constant::universal::c, Foam::endl(), f(), Foam::findMax(), forAll, Foam::constant::universal::h, Foam::inv(), k, Matrix< Form, Type >::m(), Foam::mag(), Foam::max(), Foam::min(), Foam::multiply(), Matrix< Form, Type >::n(), s(), Foam::sqrt(), sqrtSumSqr(), Matrix< Form, Type >::T(), WarningIn, x, and y.
Member Function Documentation
U()
const Foam::scalarRectangularMatrix & U () const inline
Return U.
Definition at line 37 of file SVDI.H.
V()
const Foam::scalarRectangularMatrix & V () const inline
Return the square matrix V.
Definition at line 42 of file SVDI.H.
S()
const Foam::scalarDiagonalMatrix & S () const inline
Return the singular values.
Definition at line 47 of file SVDI.H.
Referenced by CentredFitSnGradData< Polynomial >::calcFit().
VSinvUt()
const Foam::scalarRectangularMatrix & VSinvUt () const inline
Return VSinvUt (the pseudo inverse)
Definition at line 52 of file SVDI.H.
Referenced by CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), and Foam::SVDinv().
nZeros()
Foam::label nZeros () const inline
Return the number of zero singular values.
Definition at line 57 of file SVDI.H.
minNonZeroS()
Foam::scalar minNonZeroS () const inline
Return the minimum non-zero singular value.
Definition at line 62 of file SVDI.H.
References s(), and List< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.H
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.C
src/OpenFOAM/matrices/scalarMatrices/SVD/SVDI.H