OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GAMGInterfaceField Class Reference
Abstract base class for GAMG agglomerated interface fields.
Public Member Functions
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality.
Static Public Member Functions
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
Abstract base class for GAMG agglomerated interface fields.
Source files
GAMGInterfaceField.H
GAMGInterfaceField.C
GAMGInterfaceFieldNew.C
Definition at line 51 of file GAMGInterfaceField.H.
Constructor & Destructor Documentation
GAMGInterfaceField() [1/2]
GAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField &) inline
Construct from GAMG interface and fine level interface field.
Definition at line 128 of file GAMGInterfaceField.H.
GAMGInterfaceField() [2/2]
GAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank) inline
Construct from GAMG interface and fine level interface field.
Definition at line 139 of file GAMGInterfaceField.H.
Member Function Documentation
TypeName()
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , GAMGInterfaceField , lduInterfaceField , (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface) , (GAMGCp, fineInterface))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , GAMGInterfaceField , lduInterface , (const GAMGInterface &GAMGCp, const bool doTransform, const int rank) , (GAMGCp, doTransform, rank))
New() [1/2]
Foam::autoPtr< Foam::GAMGInterfaceField > New (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterface) static
Return a pointer to a new interface created on freestore given.
the fine interface
Definition at line 31 of file GAMGInterfaceFieldNew.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, lduInterfaceField::interfaceFieldType(), and Foam::nl.
New() [2/2]
Foam::autoPtr< Foam::GAMGInterfaceField > New (const GAMGInterface & GAMGCp, const bool doTransform, const int rank) static
Return a pointer to a new interface created on freestore given.
the fine interface
Definition at line 60 of file GAMGInterfaceFieldNew.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, and Foam::nl.
interface()
const GAMGInterface& interface () const inline
Return interface.
Definition at line 155 of file GAMGInterfaceField.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaceFields/GAMGInterfaceField/GAMGInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaceFields/GAMGInterfaceField/GAMGInterfaceFieldNew.C