OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LUscalarMatrix Class Reference
Foam::LUscalarMatrix.
Public Member Functions
ClassName ("LUscalarMatrix")
LUscalarMatrix (const scalarSquareMatrix &)
Construct from scalarSquareMatrix and perform LU decomposition.
LUscalarMatrix (const lduMatrix &, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces)
Construct from lduMatrix and perform LU decomposition.
template<class T >
void solve (Field< T > &source) const
Solve the matrix using the LU decomposition with pivoting.
template<class Type >
void solve (Field< Type > &sourceSol) const
Public Member Functions inherited from SquareMatrix< Type >
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n)
Construct given number of rows and columns,.
SquareMatrix (const label m, const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label n, const label m)
Construct given number of rows and columns.
Matrix (const label n, const label m, const Type &)
Construct with given number of rows and columns.
Matrix (const Matrix< SquareMatrix< Type >, Type > &)
Copy constructor.
Matrix (Istream &)
Construct from Istream.
autoPtr< Matrix< SquareMatrix< Type >, Type > > clone () const
Clone.
~Matrix ()
Destructor.
label n () const
Return the number of rows.
label m () const
Return the number of columns.
label size () const
Return the number of elements in matrix (n*m)
void checki (const label i) const
Check index i is within valid range (0 ... n-1).
void checkj (const label j) const
Check index j is within valid range (0 ... m-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (Matrix< SquareMatrix< Type >, Type > &)
Transfer the contents of the argument Matrix into this Matrix.
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
void operator= (const Matrix< SquareMatrix< Type >, Type > &)
Assignment operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Additional Inherited Members
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const Matrix< SquareMatrix< Type >, Type > & null ()
Return a null Matrix.
Detailed Description
Foam::LUscalarMatrix.
Source files
LUscalarMatrix.H
LUscalarMatrix.C
Definition at line 54 of file LUscalarMatrix.H.
Constructor & Destructor Documentation
LUscalarMatrix() [1/2]
LUscalarMatrix (const scalarSquareMatrix & matrix)
Construct from scalarSquareMatrix and perform LU decomposition.
Definition at line 42 of file LUscalarMatrix.C.
References Foam::LUDecompose().
LUscalarMatrix() [2/2]
LUscalarMatrix (const lduMatrix & ldum, const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Construct from lduMatrix and perform LU decomposition.
Definition at line 53 of file LUscalarMatrix.C.
References UList< T >::begin(), UPtrList< T >::begin(), PtrList< Field< Type > >::begin(), lduMatrix::diag(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, UPstream::firstSlave(), forAll, Foam::Info, interface(), UPstream::lastSlave(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), Foam::LUDecompose(), Matrix< SquareMatrix< Type >, Type >::m(), Foam::mag(), UPstream::master(), UPstream::masterNo(), UPstream::msgType(), Matrix< SquareMatrix< Type >, Type >::n(), cyclicLduInterface::neighbPatchID(), UPstream::nProcs(), Matrix< SquareMatrix< Type >, Type >::operator[](), UPstream::parRun(), Foam::Pout, UPstream::scheduled, UPtrList< T >::set(), PtrList< T >::set(), List< T >::setSize(), List< T >::size(), procLduMatrix::size(), PtrList< T >::size(), lduAddressing::size(), Foam::sum(), Matrix< SquareMatrix< Type >, Type >::transfer(), lduMatrix::upper(), and lduAddressing::upperAddr().
Member Function Documentation
ClassName()
ClassName ("LUscalarMatrix")
solve() [1/2]
void solve (Field< T > & source) const
Solve the matrix using the LU decomposition with pivoting.
returning the solution in the source
solve() [2/2]
void solve (Field< Type > & sourceSol) const
Definition at line 31 of file LUscalarMatrixTemplates.C.
References UList< Type >::begin(), UList< Type >::byteSize(), UPstream::firstSlave(), UPstream::lastSlave(), Foam::LUBacksubstitute(), UPstream::master(), UPstream::masterNo(), UPstream::msgType(), Matrix< SquareMatrix< Type >, Type >::n(), UPstream::parRun(), UIPstream::read(), UPstream::scheduled, List< Type >::size(), and UOPstream::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/LUscalarMatrix.H
src/OpenFOAM/matrices/LUscalarMatrix/LUscalarMatrix.C
src/OpenFOAM/matrices/LUscalarMatrix/LUscalarMatrixTemplates.C