OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellModel Class Reference
Maps a geometry to a set of cell primitives, which enables geometric cell data to be calculated without access to the primitive geometric level. This means mapping a 3D geometry to a set of pyramids which are each described by a cell face and the cell centre point.
Public Member Functions
cellModel (Istream &)
Construct from Istream.
autoPtr< cellModel > clone () const
Return clone.
const word & name () const
Return model name.
label index () const
Return index of model in the model list.
label nPoints () const
Return number of points.
label nEdges () const
Return number of edges.
label nFaces () const
Return number of faces.
edgeList edges (const labelList &pointLabels) const
Return list of edges.
const faceList & modelFaces () const
Return a raw list of model faces.
faceList faces (const labelList &pointLabels) const
Return list of faces.
vector centre (const labelList &pointLabels, const pointField &points) const
Vector centroid.
scalar mag (const labelList &pointLabels, const pointField &points) const
Cell volume.
InfoProxy< cellModel > info () const
Return info proxy.
bool writeData (Ostream &os) const
WriteData member function required by regIOobject.
Static Public Member Functions
static autoPtr< cellModel > New (Istream &is)
Return a new cellModel on free-store created from Istream.
Friends
bool operator== (const cellModel &, const cellModel &)
Equality operator: true => ptr to models are equal !
bool operator!= (const cellModel &, const cellModel &)
Inequality operator: true => ptr to models are not equal !
Ostream & operator<< (Ostream &, const cellModel &)
Detailed Description
Maps a geometry to a set of cell primitives, which enables geometric cell data to be calculated without access to the primitive geometric level. This means mapping a 3D geometry to a set of pyramids which are each described by a cell face and the cell centre point.
Source files
cellModel.H
cellModelI.H
Definition at line 64 of file cellModel.H.
Constructor & Destructor Documentation
cellModel()
cellModel (Istream & is)
Construct from Istream.
Definition at line 40 of file cellModelIO.C.
References entry::keyword(), dictionary::lookup(), and dictionary::null.
Referenced by cellModel::clone(), and cellModel::New().
Member Function Documentation
New()
static autoPtr<cellModel> New (Istream & is) inline static
Return a new cellModel on free-store created from Istream.
Definition at line 92 of file cellModel.H.
References cellModel::cellModel().
clone()
autoPtr<cellModel> clone () const inline
Return clone.
Definition at line 98 of file cellModel.H.
References cellModel::cellModel(), cellModel::centre(), cellModel::edges(), cellModel::faces(), cellModel::index(), cellModel::info(), cellModel::mag(), cellModel::modelFaces(), cellModel::name(), cellModel::nEdges(), cellModel::nFaces(), cellModel::nPoints(), pointLabels(), and points.
name()
const word & name () const inline
Return model name.
Definition at line 38 of file cellModelI.H.
Referenced by cellModel::clone(), and Foam::operator<<().
index()
label index () const inline
Return index of model in the model list.
Definition at line 44 of file cellModelI.H.
Referenced by cellModel::clone(), Foam::operator<<(), and STARCD::readBoundary().
nPoints()
label nPoints () const inline
Return number of points.
Definition at line 50 of file cellModelI.H.
Referenced by cellModel::clone(), and Foam::operator<<().
nEdges()
label nEdges () const inline
Return number of edges.
Definition at line 56 of file cellModelI.H.
References List< T >::size().
Referenced by cellModel::clone(), cellShape::nEdges(), and Foam::operator<<().
nFaces()
label nFaces () const inline
Return number of faces.
Definition at line 62 of file cellModelI.H.
References List< T >::size().
Referenced by cellModel::clone(), cellShape::nFaces(), and Foam::operator<<().
edges()
edgeList edges (const labelList & pointLabels) const inline
Return list of edges.
Definition at line 70 of file cellModelI.H.
References Foam::e, forAll, and List< T >::size().
Referenced by cellModel::clone(), and cellShape::edges().
modelFaces()
const faceList & modelFaces () const inline
Return a raw list of model faces.
Definition at line 90 of file cellModelI.H.
Referenced by cellModel::clone().
faces()
faceList faces (const labelList & pointLabels) const inline
Return list of faces.
Definition at line 97 of file cellModelI.H.
References f(), forAll, Foam::labelI, List< T >::setSize(), and List< T >::size().
Referenced by cellModel::clone(), and cellShape::faces().
centre()
Foam::vector centre (const labelList & pointLabels, const pointField & points) const
Vector centroid.
Definition at line 32 of file cellModel.C.
References Foam::endl(), forAll, cellModel::mag(), Foam::mag(), List< T >::size(), and WarningIn.
Referenced by cellShape::centre(), and cellModel::clone().
mag()
Foam::scalar mag (const labelList & pointLabels, const pointField & points) const
Cell volume.
Definition at line 89 of file cellModel.C.
References Foam::endl(), forAll, Foam::mag(), List< T >::size(), and WarningIn.
Referenced by cellModel::centre(), cellModel::clone(), and cellShape::mag().
info()
InfoProxy<cellModel> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 149 of file cellModel.H.
Referenced by cellModel::clone(), and Foam::operator<<().
writeData()
bool writeData (Ostream & os) const inline
WriteData member function required by regIOobject.
Definition at line 155 of file cellModel.H.
References IOstream::good(), cellModel::operator!=, cellModel::operator<<, and cellModel::operator==.
Friends And Related Function Documentation
operator==
bool operator== (const cellModel & m1, const cellModel & m2) friend
Equality operator: true => ptr to models are equal !
Definition at line 123 of file cellModelI.H.
Referenced by cellModel::writeData().
operator!=
bool operator!= (const cellModel & m1, const cellModel & m2) friend
Inequality operator: true => ptr to models are not equal !
Definition at line 129 of file cellModelI.H.
Referenced by cellModel::writeData().
operator<<
Ostream& operator<< (Ostream & os, const cellModel & c) friend
Definition at line 51 of file cellModelIO.C.
Referenced by cellModel::writeData().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellModel/cellModel.H
src/OpenFOAM/meshes/meshShapes/cellModel/cellModel.C
src/OpenFOAM/meshes/meshShapes/cellModel/cellModelI.H
src/OpenFOAM/meshes/meshShapes/cellModel/cellModelIO.C