OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
coupleGroupIdentifier Class Reference
Encapsulates using patchGroups to specify coupled patch.
Public Member Functions
coupleGroupIdentifier ()
Construct null.
coupleGroupIdentifier (const word &patchGroupName)
Construct from components.
coupleGroupIdentifier (const dictionary &)
Construct from dictionary.
const word & name () const
Name of patchGroup.
bool valid () const
Is a valid patchGroup.
label findOtherPatchID (const polyPatch &) const
Find other patch in same region. Returns index of patch or -1.
label findOtherPatchID (const polyPatch &, word &) const
Find other patch and region. Returns index of patch and sets.
void write (Ostream &) const
Write the data as a dictionary.
Friends
Ostream & operator<< (Ostream &, const coupleGroupIdentifier &)
Detailed Description
Encapsulates using patchGroups to specify coupled patch.
Source files
coupleGroupIdentifier.H
coupleGroupIdentifierI.H
coupleGroupIdentifier.C
coupleGroupIdentifierIO.C
Definition at line 62 of file coupleGroupIdentifier.H.
Constructor & Destructor Documentation
coupleGroupIdentifier() [1/3]
coupleGroupIdentifier ()
Construct null.
Definition at line 145 of file coupleGroupIdentifier.C.
coupleGroupIdentifier() [2/3]
coupleGroupIdentifier (const word & patchGroupName)
Construct from components.
Definition at line 151 of file coupleGroupIdentifier.C.
coupleGroupIdentifier() [3/3]
coupleGroupIdentifier (const dictionary & dict)
Construct from dictionary.
Definition at line 157 of file coupleGroupIdentifier.C.
Member Function Documentation
name()
const Foam::word & name () const inline
Name of patchGroup.
Definition at line 30 of file coupleGroupIdentifierI.H.
Referenced by mappedPatchBase::coupleGroup(), coupleGroupIdentifier::findOtherPatchID(), and coupleGroupIdentifier::write().
valid()
bool valid () const inline
Is a valid patchGroup.
Definition at line 36 of file coupleGroupIdentifierI.H.
Referenced by mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), and coupleGroupIdentifier::write().
findOtherPatchID() [1/2]
Foam::label findOtherPatchID (const polyPatch & thisPatch) const
Find other patch in same region. Returns index of patch or -1.
Definition at line 166 of file coupleGroupIdentifier.C.
References polyPatch::boundaryMesh(), and polyBoundaryMesh::mesh().
findOtherPatchID() [2/2]
Foam::label findOtherPatchID (const polyPatch & thisPatch, word & otherRegion) const
Find other patch and region. Returns index of patch and sets.
otherRegion to name of region. Fatal error if patch not found
Definition at line 177 of file coupleGroupIdentifier.C.
References polyPatch::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAllConstIter(), objectRegistry::lookupClass(), polyBoundaryMesh::mesh(), coupleGroupIdentifier::name(), patchIdentifier::name(), IOobject::name(), HashTable< T, Key, Hash >::sortedToc(), and objectRegistry::time().
write()
void write (Ostream & os) const
Write the data as a dictionary.
Definition at line 241 of file coupleGroupIdentifier.C.
References token::END_STATEMENT, coupleGroupIdentifier::name(), Foam::nl, coupleGroupIdentifier::valid(), and Ostream::writeKeyword().
Referenced by Foam::operator<<().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const coupleGroupIdentifier &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/patch/coupleGroupIdentifier.H
src/OpenFOAM/meshes/Identifiers/patch/coupleGroupIdentifier.C
src/OpenFOAM/meshes/Identifiers/patch/coupleGroupIdentifierI.H