OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
degenerateMatcher Class Reference
Collection of all hex degenerate matchers (hex, wedge, prism etc.) Has static member function to match a shape.
Static Public Member Functions
static cellShape match (const faceList &faces)
Recognize shape given faces of a cell.
static cellShape match (const cellShape &shape)
Recognize given uncollapsed shape (usually hex) with duplicate.
static cellShape match (const primitiveMesh &mesh, const label cellI)
Recognize shape given mesh and cellI.
Detailed Description
Collection of all hex degenerate matchers (hex, wedge, prism etc.) Has static member function to match a shape.
See also
cellMatcher
Source files
degenerateMatcher.H
degenerateMatcher.C
Definition at line 57 of file degenerateMatcher.H.
Member Function Documentation
match() [1/3]
Foam::cellShape match (const faceList & faces) static
Recognize shape given faces of a cell.
Definition at line 80 of file degenerateMatcher.C.
References Foam::identity(), and List< T >::size().
match() [2/3]
Foam::cellShape match (const cellShape & shape) static
Recognize given uncollapsed shape (usually hex) with duplicate.
vertices. cellShape just used to extract faces.
Definition at line 94 of file degenerateMatcher.C.
References cellShape::collapsedFaces().
match() [3/3]
Foam::cellShape match (const primitiveMesh & mesh, const label cellI) static
Recognize shape given mesh and cellI.
Definition at line 101 of file degenerateMatcher.C.
References primitiveMesh::cells(), primitiveMesh::faceOwner(), and primitiveMesh::faces().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellMatcher/degenerateMatcher.H
src/OpenFOAM/meshes/meshShapes/cellMatcher/degenerateMatcher.C