OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tetWedgeMatcher Class Reference
A cellMatcher for tetWedge cells.
Public Member Functions
tetWedgeMatcher ()
Construct null.
~tetWedgeMatcher ()
Destructor.
virtual label nVertPerCell () const
virtual label nFacePerCell () const
virtual label nMaxVertPerFace () const
virtual label faceHashValue () const
Hash value of all face sizes of this shape. Can be used for.
virtual bool faceSizeMatch (const faceList &, const labelList &) const
Check whether number of face sizes match the shape.
virtual bool matchShape (const bool checkOnly, const faceList &faces, const labelList &faceOwner, const label cellI, const labelList &myFaces)
Low level shape recognition. Return true if matches.
virtual bool isA (const primitiveMesh &mesh, const label cellI)
Exact match. Uses faceSizeMatch.
virtual bool isA (const faceList &)
Exact match given all the faces forming a cell. No checks.
virtual bool matches (const primitiveMesh &mesh, const label cellI, cellShape &shape)
Like isA but also constructs a cellShape (if shape matches)
Public Member Functions inherited from cellMatcher
cellMatcher (const label vertPerCell, const label facePerCell, const label maxVertPerFace, const word &cellModelName)
Construct given mesh and shape factors.
virtual ~cellMatcher ()
Destructor.
const Map< label > & localPoint () const
const faceList & localFaces () const
const labelList & faceSize () const
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & edgeFaces () const
const labelListList & pointFaceIndex () const
const labelList & vertLabels () const
const labelList & faceLabels () const
const cellModel & model () const
void write (Ostream &os) const
Additional Inherited Members
Protected Member Functions inherited from cellMatcher
label calcLocalFaces (const faceList &faces, const labelList &myFaces)
Calculates localFaces. Returns number of local vertices (or -1.
void calcEdgeAddressing (const label numVert)
Fill edge (start, end) to face number.
void calcPointFaceIndex ()
Fill vertex/face to index in face data structure.
label otherFace (const label numVert, const label v0, const label v1, const label localFaceI) const
Given start,end of edge lookup both faces sharing it and return.
Static Protected Member Functions inherited from cellMatcher
static label edgeKey (const label numVert, const label v0, const label v1)
Given start and end of edge generate unique key.
static label nextVert (const label, const label, const bool)
Step along face either in righthand or lefthand direction.
Protected Attributes inherited from cellMatcher
Map< label > localPoint_
faceList localFaces_
Faces using local vertex numbering.
labelList faceSize_
Number of vertices per face in localFaces_.
labelList pointMap_
Map from local to mesh vertex numbering.
labelList faceMap_
Map from local to mesh face numbering.
labelList edgeFaces_
Map from 'edge' to neighbouring faces.
labelListList pointFaceIndex_
pointFaceIndex[localVertI][localFaceI] is index in localFace
labelList vertLabels_
After matching: holds mesh vertices in cellmodel order.
labelList faceLabels_
After matching: holds mesh faces in cellmodel order.
const word cellModelName_
CellModel name.
const cellModel * cellModelPtr_
Detailed Description
A cellMatcher for tetWedge cells.
See also
cellMatcher
Source files
tetWedgeMatcher.H
tetWedgeMatcher.C
Definition at line 51 of file tetWedgeMatcher.H.
Constructor & Destructor Documentation
tetWedgeMatcher()
tetWedgeMatcher ()
Construct null.
Definition at line 42 of file tetWedgeMatcher.C.
~tetWedgeMatcher()
~tetWedgeMatcher ()
Destructor.
Definition at line 56 of file tetWedgeMatcher.C.
References tetWedgeMatcher::matchShape().
Member Function Documentation
nVertPerCell()
virtual label nVertPerCell () const inline virtual
Implements cellMatcher.
Definition at line 85 of file tetWedgeMatcher.H.
nFacePerCell()
virtual label nFacePerCell () const inline virtual
Implements cellMatcher.
Definition at line 90 of file tetWedgeMatcher.H.
nMaxVertPerFace()
virtual label nMaxVertPerFace () const inline virtual
Implements cellMatcher.
Definition at line 95 of file tetWedgeMatcher.H.
References tetWedgeMatcher::faceHashValue(), tetWedgeMatcher::faceSizeMatch(), tetWedgeMatcher::isA(), tetWedgeMatcher::matches(), tetWedgeMatcher::matchShape(), and mesh.
faceHashValue()
Foam::label faceHashValue () const virtual
Hash value of all face sizes of this shape. Can be used for.
quick initial recognition.
Implements cellMatcher.
Definition at line 223 of file tetWedgeMatcher.C.
References tetWedgeMatcher::faceSizeMatch().
Referenced by tetWedgeMatcher::nMaxVertPerFace().
faceSizeMatch()
bool faceSizeMatch (const faceList & , const labelList &) const virtual
Check whether number of face sizes match the shape.
Implements cellMatcher.
Definition at line 230 of file tetWedgeMatcher.C.
References forAll, and List< T >::size().
Referenced by tetWedgeMatcher::faceHashValue(), tetWedgeMatcher::matchShape(), and tetWedgeMatcher::nMaxVertPerFace().
matchShape()
bool matchShape (const bool checkOnly, const faceList & faces, const labelList & faceOwner, const label cellI, const labelList & myFaces) virtual
Low level shape recognition. Return true if matches.
Works in detection mode only (checkOnly=true) or in exact matching. Returns true and sets vertLabels_. Needs faces, faceOwner of all faces in 'mesh' and cell number and labels of faces for this cell. cellI only used in combination with faceOwner to detect owner status.
Implements cellMatcher.
Definition at line 63 of file tetWedgeMatcher.C.
References cellMatcher::calcEdgeAddressing(), cellMatcher::calcLocalFaces(), cellMatcher::calcPointFaceIndex(), cellMatcher::faceLabels_, cellMatcher::faceMap_, cellMatcher::faceSize_, tetWedgeMatcher::faceSizeMatch(), forAll, cellMatcher::localFaces_, cellMatcher::nextVert(), cellMatcher::otherFace(), cellMatcher::pointFaceIndex_, cellMatcher::pointMap_, List< T >::setSize(), and cellMatcher::vertLabels_.
Referenced by tetWedgeMatcher::isA(), tetWedgeMatcher::matches(), tetWedgeMatcher::nMaxVertPerFace(), and tetWedgeMatcher::~tetWedgeMatcher().
isA() [1/2]
bool isA (const primitiveMesh & mesh, const label cellI) virtual
Exact match. Uses faceSizeMatch.
Returns true if cell matches shape exactly.
Implements cellMatcher.
Definition at line 271 of file tetWedgeMatcher.C.
References primitiveMesh::cells(), primitiveMesh::faceOwner(), primitiveMesh::faces(), and tetWedgeMatcher::matchShape().
Referenced by tetWedgeMatcher::nMaxVertPerFace().
isA() [2/2]
bool isA (const faceList &) virtual
Exact match given all the faces forming a cell. No checks.
on whether faces match up and form a closed shape.
Implements cellMatcher.
Definition at line 284 of file tetWedgeMatcher.C.
References Foam::identity(), tetWedgeMatcher::matches(), tetWedgeMatcher::matchShape(), and List< T >::size().
matches()
bool matches (const primitiveMesh & mesh, const label cellI, cellShape & shape) virtual
Like isA but also constructs a cellShape (if shape matches)
Implements cellMatcher.
Definition at line 299 of file tetWedgeMatcher.C.
References primitiveMesh::cells(), primitiveMesh::faceOwner(), primitiveMesh::faces(), tetWedgeMatcher::matchShape(), cellMatcher::model(), and cellMatcher::vertLabels().
Referenced by tetWedgeMatcher::isA(), and tetWedgeMatcher::nMaxVertPerFace().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellMatcher/tetWedgeMatcher.H
src/OpenFOAM/meshes/meshShapes/cellMatcher/tetWedgeMatcher.C