OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellMatcher Class Reference abstract
Base class for cellshape matchers (hexMatch, prismMatch, etc.). These are classes which given a mesh and cell number find out the orientation of the cellShape and construct cell-vertex to mesh-vertex mapping and cell-face to mesh-face mapping.
Public Member Functions
cellMatcher (const label vertPerCell, const label facePerCell, const label maxVertPerFace, const word &cellModelName)
Construct given mesh and shape factors.
virtual ~cellMatcher ()
Destructor.
const Map< label > & localPoint () const
const faceList & localFaces () const
const labelList & faceSize () const
const labelList & pointMap () const
const labelList & faceMap () const
const labelList & edgeFaces () const
const labelListList & pointFaceIndex () const
const labelList & vertLabels () const
const labelList & faceLabels () const
const cellModel & model () const
void write (Ostream &os) const
virtual label nVertPerCell () const =0
virtual label nFacePerCell () const =0
virtual label nMaxVertPerFace () const =0
virtual label faceHashValue () const =0
Hash value of all face sizes of this shape. Can be used for.
virtual bool faceSizeMatch (const faceList &, const labelList &) const =0
Check whether number of face sizes match the shape.
virtual bool matchShape (const bool checkOnly, const faceList &faces, const labelList &faceOwner, const label cellI, const labelList &myFaces)=0
Low level shape recognition. Return true if matches.
virtual bool isA (const primitiveMesh &mesh, const label cellI)=0
Exact match. Uses faceSizeMatch.
virtual bool isA (const faceList &)=0
Exact match given all the faces forming a cell. No checks.
virtual bool matches (const primitiveMesh &mesh, const label cellI, cellShape &shape)=0
Like isA but also constructs a cellShape (if shape matches)
Protected Member Functions
label calcLocalFaces (const faceList &faces, const labelList &myFaces)
Calculates localFaces. Returns number of local vertices (or -1.
void calcEdgeAddressing (const label numVert)
Fill edge (start, end) to face number.
void calcPointFaceIndex ()
Fill vertex/face to index in face data structure.
label otherFace (const label numVert, const label v0, const label v1, const label localFaceI) const
Given start,end of edge lookup both faces sharing it and return.
Static Protected Member Functions
static label edgeKey (const label numVert, const label v0, const label v1)
Given start and end of edge generate unique key.
static label nextVert (const label, const label, const bool)
Step along face either in righthand or lefthand direction.
Protected Attributes
Map< label > localPoint_
faceList localFaces_
Faces using local vertex numbering.
labelList faceSize_
Number of vertices per face in localFaces_.
labelList pointMap_
Map from local to mesh vertex numbering.
labelList faceMap_
Map from local to mesh face numbering.
labelList edgeFaces_
Map from 'edge' to neighbouring faces.
labelListList pointFaceIndex_
pointFaceIndex[localVertI][localFaceI] is index in localFace
labelList vertLabels_
After matching: holds mesh vertices in cellmodel order.
labelList faceLabels_
After matching: holds mesh faces in cellmodel order.
const word cellModelName_
CellModel name.
const cellModel * cellModelPtr_
Detailed Description
Base class for cellshape matchers (hexMatch, prismMatch, etc.). These are classes which given a mesh and cell number find out the orientation of the cellShape and construct cell-vertex to mesh-vertex mapping and cell-face to mesh-face mapping.
For example,
    hexMatcher hex(mesh);
    cellShape shape;
    ..
    bool isHex = hex.match(cellI, shape);
Now shape is set to the correct Hex cellShape (if isHex is true)
Alternatively there is direct access to the vertex and face mapping:
    const labelList& hexVertLabels = hex.vertLabels();
    const labelList& hexFaceLabels = hex.faceLabels();
Now
hexVertLabels[n] is vertex label of hex vertex n
hexFaceLabels[n] is face label of hex vertex n
Process of cellShape recognition consists of following steps:
renumber vertices of cell to local vertex numbers
construct (local to cell) addressing edge-to-faces
construct (local to cell) addressing vertex and face to index in face
find most unique face shape (e.g. triangle for prism)
walk (following either vertices in face or jumping from face to other face) to other faces and checking face sizes.
if necessary try other rotations of this face (only necessary for wedge, tet-wedge)
if necessary try other faces which most unique face shape (never necessary for hex degenerates)
The whole calculation is done such that no lists are allocated during cell checking. E.g. localFaces_ are always sized to hold max. number of possible face vertices and a separate list is filled which holds the actusl face sizes.
For now all hex-degenerates implemented. Numbering taken from picture in demoGuide.
Source files
cellMatcher.H
cellMatcherI.H
cellMatcher.C
Definition at line 99 of file cellMatcher.H.
Constructor & Destructor Documentation
cellMatcher()
cellMatcher (const label vertPerCell, const label facePerCell, const label maxVertPerFace, const word & cellModelName)
Construct given mesh and shape factors.
Definition at line 38 of file cellMatcher.C.
References cellMatcher::calcLocalFaces(), f(), forAll, and List< T >::setSize().
~cellMatcher()
virtual ~cellMatcher () inline virtual
Destructor.
Definition at line 199 of file cellMatcher.H.
References cellMatcher::edgeFaces(), cellMatcher::faceHashValue(), cellMatcher::faceLabels(), cellMatcher::faceMap(), cellMatcher::faceSize(), cellMatcher::faceSizeMatch(), cellMatcher::isA(), cellMatcher::localFaces(), cellMatcher::localPoint(), cellMatcher::matches(), cellMatcher::matchShape(), mesh, cellMatcher::model(), cellMatcher::nFacePerCell(), cellMatcher::nMaxVertPerFace(), cellMatcher::nVertPerCell(), cellMatcher::pointFaceIndex(), cellMatcher::pointMap(), cellMatcher::vertLabels(), and cellMatcher::write().
Member Function Documentation
edgeKey()
Foam::label edgeKey (const label numVert, const label v0, const label v1) inline static protected
Given start and end of edge generate unique key.
Definition at line 100 of file cellMatcherI.H.
References cellMatcher::nextVert().
Referenced by cellMatcher::calcEdgeAddressing(), cellMatcher::model(), and cellMatcher::otherFace().
nextVert()
Foam::label nextVert (const label localVertI, const label size, const bool rightHand) inline static protected
Step along face either in righthand or lefthand direction.
Definition at line 112 of file cellMatcherI.H.
Referenced by cellMatcher::edgeKey(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), prismMatcher::matchShape(), and hexMatcher::matchShape().
calcLocalFaces()
Foam::label calcLocalFaces (const faceList & faces, const labelList & myFaces) protected
Calculates localFaces. Returns number of local vertices (or -1.
if more than vertPerCell).
Definition at line 75 of file cellMatcher.C.
References HashTableCore::end(), f(), HashTable< T, Key, Hash >::find(), forAll, forAllConstIter(), and List< T >::size().
Referenced by cellMatcher::cellMatcher(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), prismMatcher::matchShape(), and hexMatcher::matchShape().
calcEdgeAddressing()
void calcEdgeAddressing (const label numVert) protected
Fill edge (start, end) to face number.
Definition at line 140 of file cellMatcher.C.
References Foam::abort(), cellMatcher::edgeFaces_, cellMatcher::edgeKey(), f(), cellMatcher::faceSize_, Foam::FatalError, FatalErrorIn, forAll, and cellMatcher::localFaces_.
Referenced by hexMatcher::matchShape(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), and prismMatcher::matchShape().
calcPointFaceIndex()
void calcPointFaceIndex () protected
Fill vertex/face to index in face data structure.
Definition at line 193 of file cellMatcher.C.
References f(), cellMatcher::faceSize_, forAll, cellMatcher::localFaces_, cellMatcher::otherFace(), and cellMatcher::pointFaceIndex_.
Referenced by hexMatcher::matchShape(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), and prismMatcher::matchShape().
otherFace()
Foam::label otherFace (const label numVert, const label v0, const label v1, const label localFaceI) const protected
Given start,end of edge lookup both faces sharing it and return.
face != localFaceI
Definition at line 223 of file cellMatcher.C.
References Foam::abort(), cellMatcher::edgeFaces_, cellMatcher::edgeKey(), Foam::FatalError, and FatalErrorIn.
Referenced by cellMatcher::calcPointFaceIndex(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), prismMatcher::matchShape(), and hexMatcher::matchShape().
localPoint()
const Foam::Map< Foam::label > & localPoint () const inline
Definition at line 32 of file cellMatcherI.H.
References cellMatcher::localPoint_.
Referenced by cellMatcher::~cellMatcher().
localFaces()
const Foam::faceList & localFaces () const inline
Definition at line 38 of file cellMatcherI.H.
References cellMatcher::localFaces_.
Referenced by cellMatcher::~cellMatcher().
faceSize()
const Foam::labelList & faceSize () const inline
Definition at line 44 of file cellMatcherI.H.
References cellMatcher::faceSize_.
Referenced by cellMatcher::~cellMatcher().
pointMap()
const Foam::labelList & pointMap () const inline
Definition at line 50 of file cellMatcherI.H.
References cellMatcher::pointMap_.
Referenced by cellMatcher::~cellMatcher().
faceMap()
const Foam::labelList & faceMap () const inline
Definition at line 56 of file cellMatcherI.H.
References cellMatcher::faceMap_.
Referenced by cellMatcher::~cellMatcher().
edgeFaces()
const Foam::labelList & edgeFaces () const inline
Definition at line 62 of file cellMatcherI.H.
References cellMatcher::edgeFaces_.
Referenced by cellMatcher::~cellMatcher().
pointFaceIndex()
const Foam::labelListList & pointFaceIndex () const inline
Definition at line 68 of file cellMatcherI.H.
References cellMatcher::pointFaceIndex_.
Referenced by cellMatcher::~cellMatcher().
vertLabels()
const Foam::labelList & vertLabels () const inline
Definition at line 74 of file cellMatcherI.H.
References cellMatcher::vertLabels_.
Referenced by hexMatcher::matches(), wedgeMatcher::matches(), tetWedgeMatcher::matches(), tetMatcher::matches(), pyrMatcher::matches(), prismMatcher::matches(), and cellMatcher::~cellMatcher().
faceLabels()
const Foam::labelList & faceLabels () const inline
Definition at line 80 of file cellMatcherI.H.
References cellMatcher::faceLabels_.
Referenced by cellMatcher::~cellMatcher().
model()
const Foam::cellModel & model () const inline
Definition at line 86 of file cellMatcherI.H.
References cellMatcher::cellModelName_, cellMatcher::cellModelPtr_, cellMatcher::edgeKey(), and cellModeller::lookup().
Referenced by hexMatcher::matches(), wedgeMatcher::matches(), tetWedgeMatcher::matches(), tetMatcher::matches(), pyrMatcher::matches(), prismMatcher::matches(), and cellMatcher::~cellMatcher().
write()
void write (Foam::Ostream & os) const
Definition at line 258 of file cellMatcher.C.
References Foam::endl(), cellMatcher::faceMap_, cellMatcher::faceSize_, forAll, cellMatcher::localFaces_, and cellMatcher::pointMap_.
Referenced by cellMatcher::~cellMatcher().
nVertPerCell()
virtual label nVertPerCell () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
nFacePerCell()
virtual label nFacePerCell () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
nMaxVertPerFace()
virtual label nMaxVertPerFace () const pure virtual
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
faceHashValue()
virtual label faceHashValue () const pure virtual
Hash value of all face sizes of this shape. Can be used for.
quick initial recognition.
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
faceSizeMatch()
virtual bool faceSizeMatch (const faceList & , const labelList &) const pure virtual
Check whether number of face sizes match the shape.
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
matchShape()
virtual bool matchShape (const bool checkOnly, const faceList & faces, const labelList & faceOwner, const label cellI, const labelList & myFaces) pure virtual
Low level shape recognition. Return true if matches.
Works in detection mode only (checkOnly=true) or in exact matching. Returns true and sets vertLabels_. Needs faces, faceOwner of all faces in 'mesh' and cell number and labels of faces for this cell. cellI only used in combination with faceOwner to detect owner status.
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
isA() [1/2]
virtual bool isA (const primitiveMesh & mesh, const label cellI) pure virtual
Exact match. Uses faceSizeMatch.
Returns true if cell matches shape exactly.
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
isA() [2/2]
virtual bool isA (const faceList &) pure virtual
Exact match given all the faces forming a cell. No checks.
on whether faces match up and form a closed shape.
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
matches()
virtual bool matches (const primitiveMesh & mesh, const label cellI, cellShape & shape) pure virtual
Like isA but also constructs a cellShape (if shape matches)
Implemented in hexMatcher, prismMatcher, pyrMatcher, tetMatcher, tetWedgeMatcher, and wedgeMatcher.
Referenced by cellMatcher::~cellMatcher().
Member Data Documentation
localPoint_
Map<label> localPoint_ protected
Definition at line 119 of file cellMatcher.H.
Referenced by cellMatcher::localPoint().
localFaces_
faceList localFaces_ protected
Faces using local vertex numbering.
Definition at line 122 of file cellMatcher.H.
Referenced by cellMatcher::calcEdgeAddressing(), cellMatcher::calcPointFaceIndex(), cellMatcher::localFaces(), tetMatcher::matchShape(), pyrMatcher::matchShape(), tetWedgeMatcher::matchShape(), hexMatcher::matchShape(), wedgeMatcher::matchShape(), prismMatcher::matchShape(), and cellMatcher::write().
faceSize_
labelList faceSize_ protected
Number of vertices per face in localFaces_.
Definition at line 125 of file cellMatcher.H.
Referenced by cellMatcher::calcEdgeAddressing(), cellMatcher::calcPointFaceIndex(), cellMatcher::faceSize(), tetMatcher::matchShape(), pyrMatcher::matchShape(), tetWedgeMatcher::matchShape(), hexMatcher::matchShape(), wedgeMatcher::matchShape(), prismMatcher::matchShape(), and cellMatcher::write().
pointMap_
labelList pointMap_ protected
Map from local to mesh vertex numbering.
Definition at line 128 of file cellMatcher.H.
Referenced by hexMatcher::matchShape(), prismMatcher::matchShape(), tetWedgeMatcher::matchShape(), wedgeMatcher::matchShape(), pyrMatcher::matchShape(), tetMatcher::matchShape(), cellMatcher::pointMap(), and cellMatcher::write().
faceMap_
labelList faceMap_ protected
Map from local to mesh face numbering.
Definition at line 131 of file cellMatcher.H.
Referenced by cellMatcher::faceMap(), prismMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), wedgeMatcher::matchShape(), hexMatcher::matchShape(), and cellMatcher::write().
edgeFaces_
labelList edgeFaces_ protected
Map from 'edge' to neighbouring faces.
Definition at line 134 of file cellMatcher.H.
Referenced by cellMatcher::calcEdgeAddressing(), cellMatcher::edgeFaces(), and cellMatcher::otherFace().
pointFaceIndex_
labelListList pointFaceIndex_ protected
pointFaceIndex[localVertI][localFaceI] is index in localFace
where localVertI is.
Definition at line 138 of file cellMatcher.H.
Referenced by cellMatcher::calcPointFaceIndex(), prismMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), wedgeMatcher::matchShape(), hexMatcher::matchShape(), and cellMatcher::pointFaceIndex().
vertLabels_
labelList vertLabels_ protected
After matching: holds mesh vertices in cellmodel order.
Definition at line 141 of file cellMatcher.H.
Referenced by hexMatcher::matchShape(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), prismMatcher::matchShape(), and cellMatcher::vertLabels().
faceLabels_
labelList faceLabels_ protected
After matching: holds mesh faces in cellmodel order.
Definition at line 144 of file cellMatcher.H.
Referenced by cellMatcher::faceLabels(), wedgeMatcher::matchShape(), tetWedgeMatcher::matchShape(), tetMatcher::matchShape(), pyrMatcher::matchShape(), prismMatcher::matchShape(), and hexMatcher::matchShape().
cellModelName_
const word cellModelName_ protected
CellModel name.
Definition at line 147 of file cellMatcher.H.
Referenced by cellMatcher::model().
cellModelPtr_
const cellModel* cellModelPtr_ mutable protected
Definition at line 149 of file cellMatcher.H.
Referenced by cellMatcher::model().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellMatcher/cellMatcher.H
src/OpenFOAM/meshes/meshShapes/cellMatcher/cellMatcher.C
src/OpenFOAM/meshes/meshShapes/cellMatcher/cellMatcherI.H