OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
lduPrimitiveMesh Class Reference
Simplest contrete lduMesh which stores the addressing needed by lduMatrix.
Public Member Functions
ClassName ("lduPrimitiveMesh")
lduPrimitiveMesh (const label nCells, labelList &l, labelList &u, const label comm, bool reUse)
Construct from components but without interfaces. Add interfaces.
void addInterfaces (lduInterfacePtrsList &interfaces, const lduSchedule &ps)
Add interfaces to a mesh constructed without.
lduPrimitiveMesh (const label nCells, labelList &l, labelList &u, PtrList< const lduInterface > &primitiveInterfaces, const lduSchedule &ps, const label comm)
Construct from components and re-use storage.
lduPrimitiveMesh (const label comm, const labelList &procAgglomMap, const labelList &procIDs, const lduMesh &myMesh, const PtrList< lduPrimitiveMesh > &otherMeshes, labelList &cellOffsets, labelList &faceOffsets, labelListList &faceMap, labelListList &boundaryMap, labelListListList &boundaryFaceMap)
Construct by combining multiple meshes. The meshes come from.
virtual ~lduPrimitiveMesh ()
Destructor.
virtual const lduAddressing & lduAddr () const
Return ldu addressing.
virtual lduInterfacePtrsList interfaces () const
Return a list of pointers for each patch.
const lduInterfacePtrsList & rawInterfaces () const
Return a list of pointers for each patch.
virtual label comm () const
Return communicator used for parallel communication.
virtual const labelUList & lowerAddr () const
Return Lower addressing.
virtual const labelUList & upperAddr () const
Return Upper addressing.
virtual const labelUList & patchAddr (const label i) const
Return patch addressing.
virtual const lduSchedule & patchSchedule () const
Return patch evaluation schedule.
template<class ProcPatch >
Foam::lduSchedule nonBlockingSchedule (const lduInterfacePtrsList &interfaces)
Public Member Functions inherited from lduMesh
TypeName ("lduMesh")
Runtime type information.
virtual ~lduMesh ()
Destructor.
virtual const objectRegistry & thisDb () const
Return the object registry.
template<class T , class BinaryOp >
void reduce (T &Value, const BinaryOp &bop) const
Helper: reduce with current communicator.
InfoProxy< lduMesh > info () const
Return info proxy.
Public Member Functions inherited from lduAddressing
lduAddressing (const label nEqns)
virtual ~lduAddressing ()
Destructor.
label size () const
Return number of equations.
const labelUList & losortAddr () const
Return losort addressing.
const labelUList & ownerStartAddr () const
Return owner start addressing.
const labelUList & losortStartAddr () const
Return losort start addressing.
label triIndex (const label a, const label b) const
Return off-diagonal index given owner and neighbour label.
Tuple2< label, scalar > band () const
Calculate bandwidth and profile of addressing.
Static Public Member Functions
static const lduMesh & mesh (const lduMesh &mesh0, const PtrList< lduPrimitiveMesh > &otherMeshes, const label meshI)
Select either mesh0 (meshI is 0) or otherMeshes[meshI-1].
static void gather (const label comm, const lduMesh &mesh, const labelList &procIDs, PtrList< lduPrimitiveMesh > &otherMeshes)
Gather meshes from other processors onto procIDs[0].
template<class ProcPatch >
static lduSchedule nonBlockingSchedule (const lduInterfacePtrsList &)
Get non-scheduled send/receive schedule.
Detailed Description
Simplest contrete lduMesh which stores the addressing needed by lduMatrix.
Source files
lduPrimitiveMesh.H
lduPrimitiveMesh.C
Definition at line 49 of file lduPrimitiveMesh.H.
Constructor & Destructor Documentation
lduPrimitiveMesh() [1/3]
lduPrimitiveMesh (const label nCells, labelList & l, labelList & u, const label comm, bool reUse)
Construct from components but without interfaces. Add interfaces.
separately using addInterfaces
Definition at line 216 of file lduPrimitiveMesh.C.
References lduPrimitiveMesh::addInterfaces().
lduPrimitiveMesh() [2/3]
lduPrimitiveMesh (const label nCells, labelList & l, labelList & u, PtrList< const lduInterface > & primitiveInterfaces, const lduSchedule & ps, const label comm)
Construct from components and re-use storage.
Definition at line 253 of file lduPrimitiveMesh.C.
References forAll.
lduPrimitiveMesh() [3/3]
lduPrimitiveMesh (const label comm, const labelList & procAgglomMap, const labelList & procIDs, const lduMesh & myMesh, const PtrList< lduPrimitiveMesh > & otherMeshes, labelList & cellOffsets, labelList & faceOffsets, labelListList & faceMap, labelListList & boundaryMap, labelListListList & boundaryFaceMap)
Construct by combining multiple meshes. The meshes come from.
processors procIDs: procIDs[0] : local processor (myMesh) procIDs[i] : processor where otherMeshes[i-1] comes from procAgglomMap : for every processor which processor it agglomerates onto. The new processor numbers are in compact numbering (so ranks in communicator comm), i.e. similar to cell-restrict-addressing. We need this information to be able to map inter-processor interfaces cellOffsets : for every processor the offset it gets in the mesh faceMap : for every processor, for every face, the destination face. Negative for flipped faces. boundaryMap : for every processor, for every patch, -1 or the new patch index in the mesh. boundaryFaceMap : for every processor, for every patch, for every patch face:
the new internal face (if boundaryMap=-1)
the new patch face (if boundaryMap>=0) Faces becoming internal are negative for flipped faces.
Definition at line 284 of file lduPrimitiveMesh.C.
References Foam::abort(), lduMesh::comm(), HashTableCore::end(), Foam::endl(), Foam::exit(), lduInterface::faceCells(), Foam::FatalError, FatalErrorIn, HashTable< T, Key, Hash >::find(), Foam::findIndex(), Foam::findIndices(), forAll, forAllConstIter(), Foam::inplaceReorder(), HashTable< T, edge, Hash< edge > >::insert(), lduMesh::interfaces(), UList< T >::last(), lduMesh::lduAddr(), lduAddressing::lowerAddr(), Foam::max(), mesh, lduPrimitiveMesh::mesh(), Foam::min(), UPstream::msgType(), processorLduInterface::myProcNo(), UPstream::myProcNo(), n, processorLduInterface::neighbProcNo(), Foam::Pout, UPtrList< T >::set(), List< T >::setSize(), List< T >::size(), UPtrList< T >::size(), PtrList< T >::size(), lduAddressing::size(), UList< T >::size(), Foam::sortedOrder(), lduAddressing::upperAddr(), and WarningIn.
~lduPrimitiveMesh()
virtual ~lduPrimitiveMesh () inline virtual
Destructor.
Definition at line 179 of file lduPrimitiveMesh.H.
Member Function Documentation
ClassName()
ClassName ("lduPrimitiveMesh")
addInterfaces()
void addInterfaces (lduInterfacePtrsList & interfaces, const lduSchedule & ps)
Add interfaces to a mesh constructed without.
Definition at line 232 of file lduPrimitiveMesh.C.
References forAll, and List< T >::setSize().
Referenced by lduPrimitiveMesh::lduPrimitiveMesh().
lduAddr()
virtual const lduAddressing& lduAddr () const inline virtual
Return ldu addressing.
Implements lduMesh.
Definition at line 188 of file lduPrimitiveMesh.H.
References lduPrimitiveMesh::interfaces(), and lduPrimitiveMesh::rawInterfaces().
interfaces()
virtual lduInterfacePtrsList interfaces () const inline virtual
Return a list of pointers for each patch.
with only those pointing to interfaces being set
Implements lduMesh.
Definition at line 195 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMesh::lduAddr().
rawInterfaces()
const lduInterfacePtrsList& rawInterfaces () const inline
Return a list of pointers for each patch.
with only those pointing to interfaces being set (reference to cached interfaces)
Definition at line 203 of file lduPrimitiveMesh.H.
Referenced by lduPrimitiveMesh::lduAddr().
comm()
virtual label comm () const inline virtual
Return communicator used for parallel communication.
Implements lduMesh.
Definition at line 209 of file lduPrimitiveMesh.H.
lowerAddr()
virtual const labelUList& lowerAddr () const inline virtual
Return Lower addressing.
Implements lduAddressing.
Definition at line 215 of file lduPrimitiveMesh.H.
upperAddr()
virtual const labelUList& upperAddr () const inline virtual
Return Upper addressing.
Implements lduAddressing.
Definition at line 221 of file lduPrimitiveMesh.H.
patchAddr()
virtual const labelUList& patchAddr (const label i) const inline virtual
Return patch addressing.
Implements lduAddressing.
Definition at line 227 of file lduPrimitiveMesh.H.
patchSchedule()
virtual const lduSchedule& patchSchedule () const inline virtual
Return patch evaluation schedule.
Implements lduAddressing.
Definition at line 233 of file lduPrimitiveMesh.H.
References lduPrimitiveMesh::gather(), lduPrimitiveMesh::mesh(), and lduPrimitiveMesh::nonBlockingSchedule().
mesh()
const Foam::lduMesh & mesh (const lduMesh & mesh0, const PtrList< lduPrimitiveMesh > & otherMeshes, const label meshI) static
Select either mesh0 (meshI is 0) or otherMeshes[meshI-1].
Definition at line 987 of file lduPrimitiveMesh.C.
References lduPrimitiveMesh::gather().
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), and lduPrimitiveMesh::patchSchedule().
gather()
void gather (const label comm, const lduMesh & mesh, const labelList & procIDs, PtrList< lduPrimitiveMesh > & otherMeshes) static
Gather meshes from other processors onto procIDs[0].
Received meshes get GAMGInterface and communicator comm
Definition at line 998 of file lduPrimitiveMesh.C.
References Foam::findIndex(), forAll, interface(), lduMesh::interfaces(), lduMesh::lduAddr(), lduAddressing::lowerAddr(), UPstream::msgType(), UPstream::myProcNo(), GAMGInterface::New(), lduAddressing::patchSchedule(), Foam::refCast(), UPstream::scheduled, UPtrList< T >::set(), PtrList< T >::set(), PtrList< T >::setSize(), List< T >::size(), UPtrList< T >::size(), lduAddressing::size(), and lduAddressing::upperAddr().
Referenced by lduPrimitiveMesh::mesh(), and lduPrimitiveMesh::patchSchedule().
nonBlockingSchedule() [1/2]
static lduSchedule nonBlockingSchedule (const lduInterfacePtrsList &) static
Get non-scheduled send/receive schedule.
Referenced by lduPrimitiveMesh::patchSchedule().
nonBlockingSchedule() [2/2]
Foam::lduSchedule nonBlockingSchedule (const lduInterfacePtrsList & interfaces)
Definition at line 32 of file lduPrimitiveMeshTemplates.C.
References forAll, UPtrList< T >::set(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMesh.H
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMesh.C
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMeshTemplates.C