OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
patchIdentifier Class Reference
Identifies patch by name, patch index and physical type.
Public Member Functions
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Friends
Ostream & operator<< (Ostream &, const patchIdentifier &)
Detailed Description
Identifies patch by name, patch index and physical type.
Source files
patchIdentifier.H
patchIdentifier.C
Definition at line 57 of file patchIdentifier.H.
Constructor & Destructor Documentation
patchIdentifier() [1/3]
patchIdentifier (const word & name, const label index, const word & physicalType = word::null, const wordList & inGroups = wordList())
Construct from components.
Definition at line 33 of file patchIdentifier.C.
Referenced by patchIdentifier::patchIdentifier().
patchIdentifier() [2/3]
patchIdentifier (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 48 of file patchIdentifier.C.
References patchIdentifier::patchIdentifier(), and dictionary::readIfPresent().
patchIdentifier() [3/3]
patchIdentifier (const patchIdentifier & p, const label index)
Construct from geometric patch, resetting the index.
Definition at line 63 of file patchIdentifier.C.
~patchIdentifier()
~patchIdentifier () virtual
Destructor.
Definition at line 77 of file patchIdentifier.C.
Member Function Documentation
name() [1/2]
const word& name () const inline
Return name.
Definition at line 109 of file patchIdentifier.H.
Referenced by polyTopoChange::addMesh(), fvMeshTools::addPatch(), boundaryMesh::addPatch(), processorCyclicPolyPatch::calcGeometry(), processorPolyPatch::calcGeometry(), wallShearStress::calcShearStress(), boundaryMesh::changeFaces(), boundaryMesh::changePatchType(), hexRef8::checkMesh(), meshRefinement::checkZoneFaces(), decompositionMethod::decompose(), boundaryMesh::deletePatch(), autoLayerDriver::doLayers(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), coupleGroupIdentifier::findOtherPatchID(), particle< Type >::hitCyclicAMIPatch(), meshToMesh::interpolationMethodAMI(), mappedFixedValueFvPatchField< Type >::mapper(), MeshedSurface< Foam::face >::MeshedSurface(), fvPatch::name(), facePointPatch::name(), NamedEnum< directionType, 3 >::names(), regionModel::nbrCoupledPatchID(), polyBoundaryMesh::neighbourEdges(), cyclicACMIPolyPatch::nonOverlapPatchID(), combineEqOp< Type, TrackingData >::operator()(), boundaryMesh::patchify(), patchInteractionDataList::patchInteractionDataList(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), thermalBaffleModel::read(), boundaryMesh::read(), mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), motionSmootherAlgo::scaleMesh(), FaceCellWave< Type, TrackingData >::setFaceInfo(), processorCyclicPolyPatch::tag(), meshRefinement::testSyncBoundaryFaceList(), cyclicPolyPatch::transformGlobalFace(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), sampledPatch::update(), and boundaryMesh::writeTriSurface().
name() [2/2]
word& name () inline
Return name for modification.
Definition at line 115 of file patchIdentifier.H.
physicalType() [1/2]
const word& physicalType () const inline
Return the optional physical type of the patch.
Definition at line 121 of file patchIdentifier.H.
Referenced by boundaryMesh::addPatch(), boundaryMesh::changeFaces(), boundaryMesh::deletePatch(), boundaryMesh::patchify(), boundaryMesh::read(), and boundaryMesh::writeTriSurface().
physicalType() [2/2]
word& physicalType () inline
Return the optional physical type of the patch for modification.
Definition at line 127 of file patchIdentifier.H.
index() [1/2]
label index () const inline
Return the index of this patch in the boundaryMesh.
Definition at line 133 of file patchIdentifier.H.
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction(), ThermoSurfaceFilm< CloudType >::bounceInteraction(), processorCyclicPolyPatch::calcGeometry(), processorPolyPatch::calcGeometry(), boundaryMesh::changePatchType(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), LocalInteraction< CloudType >::correct(), MultiInteraction< CloudType >::correct(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), radiationCoupledBase::emissivity(), DsmcParcel< ParcelType >::hitWallPatch(), facePointPatch::index(), fvPatch::index(), meshToMesh::interpolationMethodAMI(), cyclicPolyPatch::owner(), KinematicCloud< Foam::DsmcCloud >::patchData(), patchInteractionDataList::patchInteractionDataList(), ParticleErosion< CloudType >::postPatch(), PatchPostProcessing< CloudType >::postPatch(), ThermoSurfaceFilm< CloudType >::splashInteraction(), ThermoSurfaceFilm< CloudType >::transferParcel(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
index() [2/2]
label& index () inline
Return the index of this patch in the boundaryMesh for modification.
Definition at line 139 of file patchIdentifier.H.
inGroups() [1/2]
const wordList& inGroups () const inline
Return the optional groups patch belongs to.
Definition at line 145 of file patchIdentifier.H.
Referenced by polyBoundaryMesh::setGroup().
inGroups() [2/2]
wordList& inGroups () inline
Return the optional groups patch belongs to for modification.
Definition at line 151 of file patchIdentifier.H.
References patchIdentifier::inGroup(), patchIdentifier::operator<<, and patchIdentifier::write().
inGroup()
bool inGroup (const word & name) const
Test if in group.
Definition at line 83 of file patchIdentifier.C.
References Foam::findIndex().
Referenced by patchIdentifier::inGroups(), and polyBoundaryMesh::setGroup().
write()
void write (Ostream & os) const
Write patchIdentifier as a dictionary.
Definition at line 89 of file patchIdentifier.C.
References token::END_STATEMENT, Foam::nl, List< T >::size(), and Ostream::writeKeyword().
Referenced by patchIdentifier::inGroups(), Foam::operator<<(), boundaryPatch::write(), genericPolyPatch::write(), oldCyclicPolyPatch::write(), and polyPatch::write().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const patchIdentifier &) friend
Referenced by patchIdentifier::inGroups().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/patch/patchIdentifier.H
src/OpenFOAM/meshes/Identifiers/patch/patchIdentifier.C