OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DynamicID< ObjectType > Class Template Reference
A class that holds the data needed to identify things (zones, patches) in a dynamic mesh.
Public Member Functions
DynamicID (const keyType &key, const ObjectType &obj)
Construct from name.
DynamicID (Istream &is, const ObjectType &obj)
Construct from Istream.
const keyType & name () const
Return name.
const labelList & indices () const
Return indices of matching zones.
label index () const
Return index of first matching zone.
bool active () const
Has the zone been found.
void update (const ObjectType &obj)
Update.
Friends
Ostream & operator (Ostream &, const DynamicID< ObjectType > &)
Detailed Description
template<class ObjectType>
class Foam::DynamicID< ObjectType >
A class that holds the data needed to identify things (zones, patches) in a dynamic mesh.
The thing is identified by name. Its indices are updated if the mesh has changed.
Definition at line 47 of file DynamicID.H.
Constructor & Destructor Documentation
DynamicID() [1/2]
DynamicID (const keyType & key, const ObjectType & obj) inline
Construct from name.
Definition at line 73 of file DynamicID.H.
DynamicID() [2/2]
DynamicID (Istream & is, const ObjectType & obj) inline
Construct from Istream.
Definition at line 80 of file DynamicID.H.
Member Function Documentation
name()
const keyType& name () const inline
Return name.
Definition at line 95 of file DynamicID.H.
Referenced by enginePiston::writeDict(), and engineValve::writeDict().
indices()
const labelList& indices () const inline
Return indices of matching zones.
Definition at line 101 of file DynamicID.H.
index()
label index () const inline
Return index of first matching zone.
Definition at line 107 of file DynamicID.H.
Referenced by engineValve::movingPatchIDs().
active()
bool active () const inline
Has the zone been found.
Definition at line 113 of file DynamicID.H.
Referenced by engineValve::movingPatchIDs().
update()
void update (const ObjectType & obj) inline
Update.
Definition at line 122 of file DynamicID.H.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const DynamicID< ObjectType > &) friend
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/Identifiers/DynamicID/DynamicID.H