OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
offsetOp< face > Class Template Reference
Hash specialization to offset faces in ListListOps::combineOffset.
Public Member Functions
face operator() (const face &x, const label offset) const
Detailed Description
template<>
class Foam::offsetOp< face >
Hash specialization to offset faces in ListListOps::combineOffset.
Definition at line 388 of file face.H.
Member Function Documentation
operator()()
face operator() (const face & x, const label offset) const inline
Definition at line 394 of file face.H.
References f(), forAll, Foam::longestEdge(), and List< T >::size().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/meshShapes/face/face.H