OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellModeller Class Reference
A static collection of cell models, and a means of looking them up.
Public Member Functions
cellModeller ()
Construct from central "cellModels" file.
~cellModeller ()
Destructor.
Static Public Member Functions
static const cellModel * lookup (const word &)
Look up a model by name and return a pointer to the model or NULL.
static const cellModel * lookup (const label i)
Look up a model by index and return a pointer to the model or NULL.
Detailed Description
A static collection of cell models, and a means of looking them up.
Source files
cellModeller.H
cellModeller.C
cellModellerIO.C
globalCellModeller.C
Definition at line 52 of file cellModeller.H.
Constructor & Destructor Documentation
cellModeller()
cellModeller ()
Construct from central "cellModels" file.
Definition at line 33 of file cellModeller.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, and Foam::name().
~cellModeller()
~cellModeller ()
Destructor.
Definition at line 82 of file cellModeller.C.
Member Function Documentation
lookup() [1/2]
const Foam::cellModel * lookup (const word & name) static
Look up a model by name and return a pointer to the model or NULL.
Definition at line 91 of file cellModeller.C.
Referenced by cellMatcher::model(), NamedEnum< directionType, 3 >::names(), Foam::operator>>(), shapeToCell::shapeToCell(), and tetCell::tetCellShape().
lookup() [2/2]
static const cellModel* lookup (const label i) inline static
Look up a model by index and return a pointer to the model or NULL.
Definition at line 83 of file cellModeller.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellModeller/cellModeller.H
src/OpenFOAM/meshes/meshShapes/cellModeller/cellModeller.C
src/OpenFOAM/meshes/meshShapes/cellModeller/globalCellModeller.C