OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapDistribute::transform Class Reference
Default transformation behaviour.
Public Member Functions
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< Type > &fld) const
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< Type > > &flds) const
template<class Type >
void operator() (const coupledPolyPatch &cpp, UList< Type > &fld) const
Transform patch-based field.
template<class Type , template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< Type > &map) const
Transform sparse field.
template<>
void operator() (const vectorTensorTransform &, const bool, List< label > &) const
template<>
void operator() (const coupledPolyPatch &, UList< label > &) const
template<>
void operator() (const coupledPolyPatch &, Map< label > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< label > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, UList< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, Map< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< scalar > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< bool > &) const
template<>
void operator() (const coupledPolyPatch &, UList< bool > &) const
template<>
void operator() (const coupledPolyPatch &, Map< bool > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< bool > &) const
Detailed Description
Default transformation behaviour.
Definition at line 249 of file mapDistribute.H.
Member Function Documentation
operator()() [1/16]
void operator() (const vectorTensorTransform & vt, const bool forward, List< Type > & fld) const inline
Definition at line 255 of file mapDistribute.H.
References fld(), vectorTensorTransform::R(), Foam::T(), Tensor< Cmpt >::T(), and Foam::transformList().
Referenced by mapDistribute::transform::operator()(), and mapDistribute::transformPosition::operator()().
operator()() [2/16]
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< Type > > & flds) const inline
Definition at line 267 of file mapDistribute.H.
References forAll, and mapDistribute::transform::operator()().
operator()() [3/16]
void operator() (const coupledPolyPatch & cpp, UList< Type > & fld) const inline
Transform patch-based field.
Definition at line 281 of file mapDistribute.H.
References fld(), coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), and Foam::transformList().
operator()() [4/16]
void operator() (const coupledPolyPatch & cpp, Container< Type > & map) const inline
Transform sparse field.
Definition at line 291 of file mapDistribute.H.
References coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), and Foam::transformList().
operator()() [5/16]
void operator() (const vectorTensorTransform & , const bool , List< label > &) const
Definition at line 46 of file mapDistribute.C.
operator()() [6/16]
void operator() (const coupledPolyPatch & , UList< label > &) const
Definition at line 54 of file mapDistribute.C.
operator()() [7/16]
void operator() (const coupledPolyPatch & , Map< label > &) const
Definition at line 61 of file mapDistribute.C.
operator()() [8/16]
void operator() (const coupledPolyPatch & , EdgeMap< label > &) const
Definition at line 68 of file mapDistribute.C.
operator()() [9/16]
void operator() (const vectorTensorTransform & , const bool , List< scalar > &) const
Definition at line 77 of file mapDistribute.C.
operator()() [10/16]
void operator() (const coupledPolyPatch & , UList< scalar > &) const
Definition at line 85 of file mapDistribute.C.
operator()() [11/16]
void operator() (const coupledPolyPatch & , Map< scalar > &) const
Definition at line 92 of file mapDistribute.C.
operator()() [12/16]
void operator() (const coupledPolyPatch & , EdgeMap< scalar > &) const
Definition at line 99 of file mapDistribute.C.
operator()() [13/16]
void operator() (const vectorTensorTransform & , const bool , List< bool > &) const
Definition at line 108 of file mapDistribute.C.
operator()() [14/16]
void operator() (const coupledPolyPatch & , UList< bool > &) const
Definition at line 116 of file mapDistribute.C.
operator()() [15/16]
void operator() (const coupledPolyPatch & , Map< bool > &) const
Definition at line 123 of file mapDistribute.C.
operator()() [16/16]
void operator() (const coupledPolyPatch & , EdgeMap< bool > &) const
Definition at line 130 of file mapDistribute.C.
References mapDistribute::schedule().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C