OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointPatch Class Reference abstract
Basic pointPatch represents a set of points from the mesh.
Public Member Functions
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
virtual const word & name () const =0
Return name.
virtual label size () const =0
Return size.
virtual label index () const =0
Return the index of this patch in the pointBoundaryMesh.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const =0
Return mesh points.
virtual const vectorField & localPoints () const =0
Return mesh points.
virtual const vectorField & pointNormals () const =0
Return point normals.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Friends
class pointBoundaryMesh
Detailed Description
Basic pointPatch represents a set of points from the mesh.
Source files
pointPatch.H
pointPatch.C
Definition at line 56 of file pointPatch.H.
Constructor & Destructor Documentation
pointPatch()
pointPatch (const pointBoundaryMesh & bm) inline
Definition at line 114 of file pointPatch.H.
~pointPatch()
virtual ~pointPatch () inline virtual
Destructor.
Definition at line 123 of file pointPatch.H.
References pointPatch::index(), pointPatch::name(), and pointPatch::size().
Member Function Documentation
initGeometry()
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Initialise the calculation of the patch geometry.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 81 of file pointPatch.H.
calcGeometry()
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Calculate the patch geometry.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, coupledFacePointPatch, and facePointPatch.
Definition at line 85 of file pointPatch.H.
initMovePoints()
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Initialise the patches for moving points.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 89 of file pointPatch.H.
movePoints()
virtual void movePoints (PstreamBuffers & , const pointField &) inline protected virtual
Correct patches after moving points.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 93 of file pointPatch.H.
initUpdateMesh()
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Initialise the update of the patch topology.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 97 of file pointPatch.H.
updateMesh()
virtual void updateMesh (PstreamBuffers &) inline protected virtual
Update of the patch topology.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 101 of file pointPatch.H.
References pointPatch::TypeName().
TypeName()
TypeName ("basePatch")
Runtime type information.
Referenced by pointPatch::updateMesh().
name()
virtual const word& name () const pure virtual
Return name.
Implemented in facePointPatch.
Referenced by NamedEnum< directionType, 3 >::names(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and pointPatch::~pointPatch().
size()
virtual label size () const pure virtual
Return size.
Implemented in facePointPatch.
Referenced by fvMeshSubset::interpolate(), pointPatchMapper::size(), pointPatchField< vector >::size(), and pointPatch::~pointPatch().
index()
virtual label index () const pure virtual
Return the index of this patch in the pointBoundaryMesh.
Implemented in facePointPatch.
Referenced by pointPatch::~pointPatch().
boundaryMesh()
const pointBoundaryMesh& boundaryMesh () const inline
Return boundaryMesh reference.
Definition at line 139 of file pointPatch.H.
Referenced by NamedEnum< directionType, 3 >::names(), cyclicPointPatch::neighbPatch(), cyclicAMIPointPatch::neighbPatch(), and cyclicACMIPointPatch::neighbPatch().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in facePointPatch, and cyclicACMIPointPatch.
Definition at line 145 of file pointPatch.H.
References pointPatch::localPoints(), pointPatch::meshPoints(), and pointPatch::pointNormals().
meshPoints()
virtual const labelList& meshPoints () const pure virtual
Return mesh points.
Implemented in facePointPatch.
Referenced by pointPatch::coupled(), fvMeshSubset::interpolate(), and NamedEnum< directionType, 3 >::names().
localPoints()
virtual const vectorField& localPoints () const pure virtual
Return mesh points.
Implemented in facePointPatch.
Referenced by pointPatch::coupled(), NamedEnum< directionType, 3 >::names(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), and angularOscillatingVelocityPointPatchVectorField::updateCoeffs().
pointNormals()
virtual const vectorField& pointNormals () const pure virtual
Return point normals.
Implemented in facePointPatch, cyclicSlipPointPatch, and nonuniformTransformCyclicPointPatch.
Referenced by pointPatch::coupled(), and NamedEnum< directionType, 3 >::names().
constraintType()
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented in processorPointPatch, cyclicACMIPointPatch, cyclicAMIPointPatch, cyclicPointPatch, symmetryPointPatch, symmetryPlanePointPatch, wedgePointPatch, and emptyPointPatch.
Definition at line 160 of file pointPatch.H.
References pointPatch::applyConstraint(), and word::null.
Referenced by pointPatchField< vector >::New().
applyConstraint()
virtual void applyConstraint (const label pointi, pointConstraint &) const inline virtual
Accumulate the effect of constraint direction of this patch.
Reimplemented in cyclicSlipPointPatch, nonuniformTransformCyclicPointPatch, symmetryPointPatch, symmetryPlanePointPatch, wedgePointPatch, and emptyPointPatch.
Definition at line 167 of file pointPatch.H.
Referenced by pointPatch::constraintType().
Friends And Related Function Documentation
pointBoundaryMesh
friend class pointBoundaryMesh friend
Definition at line 78 of file pointPatch.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/pointMesh/pointPatches/pointPatch/pointPatch.H