OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapSubsetMesh Class Reference
Class containing mesh-to-mesh mapping information after a subset operation.
Public Member Functions
mapSubsetMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, const labelList &pointMap, const labelList &faceMap, const labelList &cellMap, const label exposedPatchID, const labelList &oldPatchStarts, const labelList &oldPatchNMeshPoints)
Construct from components.
mapSubsetMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &pointMap, labelList &faceMap, labelList &cellMap, const label exposedPatchID, labelList &oldPatchStarts, labelList &oldPatchNMeshPoints, const bool reUse)
Construct from components and optionally reuse storage.
label nOldPoints () const
Number of old points.
label nOldInternalFaces () const
Number of old internal faces.
label nOldFaces () const
Number of old faces.
label nOldCells () const
Number of old cells.
label exposedPatchID () const
Patch that exposed faces were put into.
const labelList & pointMap () const
Old point map.
const labelList & faceMap () const
Old face map.
const labelList & cellMap () const
Old cell map.
const labelList & oldPatchSizes () const
Return list of the old patch sizes.
const labelList & oldPatchStarts () const
Return list of the old patch start labels.
const labelList & oldPatchNMeshPoints () const
Return numbers of mesh points per old patch.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Detailed Description
Class containing mesh-to-mesh mapping information after a subset operation.
Source files
mapSubsetMesh.H
Definition at line 48 of file mapSubsetMesh.H.
Constructor & Destructor Documentation
mapSubsetMesh() [1/2]
mapSubsetMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, const labelList & pointMap, const labelList & faceMap, const labelList & cellMap, const label exposedPatchID, const labelList & oldPatchStarts, const labelList & oldPatchNMeshPoints)
Construct from components.
mapSubsetMesh() [2/2]
mapSubsetMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, labelList & pointMap, labelList & faceMap, labelList & cellMap, const label exposedPatchID, labelList & oldPatchStarts, labelList & oldPatchNMeshPoints, const bool reUse)
Construct from components and optionally reuse storage.
Member Function Documentation
nOldPoints()
label nOldPoints () const inline
Number of old points.
Definition at line 123 of file mapSubsetMesh.H.
nOldInternalFaces()
label nOldInternalFaces () const inline
Number of old internal faces.
Definition at line 129 of file mapSubsetMesh.H.
nOldFaces()
label nOldFaces () const inline
Number of old faces.
Definition at line 135 of file mapSubsetMesh.H.
nOldCells()
label nOldCells () const inline
Number of old cells.
Definition at line 141 of file mapSubsetMesh.H.
exposedPatchID()
label exposedPatchID () const inline
Patch that exposed faces were put into.
Definition at line 147 of file mapSubsetMesh.H.
References mapSubsetMesh::cellMap(), mapSubsetMesh::faceMap(), and mapSubsetMesh::pointMap().
pointMap()
const labelList& pointMap () const inline
Old point map.
Contains the old point label for all points of the subsetted mesh
Definition at line 155 of file mapSubsetMesh.H.
Referenced by mapSubsetMesh::exposedPatchID().
faceMap()
const labelList& faceMap () const inline
Old face map.
Contains the old point label for all faces of the subsetted mesh
Definition at line 163 of file mapSubsetMesh.H.
Referenced by mapSubsetMesh::exposedPatchID().
cellMap()
const labelList& cellMap () const inline
Old cell map.
Contains the old point label for all cells of the subsetted mesh
Definition at line 171 of file mapSubsetMesh.H.
Referenced by mapSubsetMesh::exposedPatchID().
oldPatchSizes()
const labelList& oldPatchSizes () const inline
Return list of the old patch sizes.
Definition at line 177 of file mapSubsetMesh.H.
oldPatchStarts()
const labelList& oldPatchStarts () const inline
Return list of the old patch start labels.
Definition at line 183 of file mapSubsetMesh.H.
oldPatchNMeshPoints()
const labelList& oldPatchNMeshPoints () const inline
Return numbers of mesh points per old patch.
Definition at line 189 of file mapSubsetMesh.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapSubsetMesh/mapSubsetMesh.H