OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapDistributePolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
Public Member Functions
mapDistributePolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const Xfer< labelList > &oldPatchStarts, const Xfer< labelList > &oldPatchNMeshPoints, const Xfer< labelListList > &subPointMap, const Xfer< labelListList > &subFaceMap, const Xfer< labelListList > &subCellMap, const Xfer< labelListList > &subPatchMap, const Xfer< labelListList > &constructPointMap, const Xfer< labelListList > &constructFaceMap, const Xfer< labelListList > &constructCellMap, const Xfer< labelListList > &constructPatchMap)
Construct from components. Note that mesh has to be changed already.
const polyMesh & mesh () const
label nOldPoints () const
Number of points in mesh before distribution.
label nOldFaces () const
Number of faces in mesh before distribution.
label nOldCells () const
Number of cells in mesh before distribution.
const labelList & oldPatchSizes () const
List of the old patch sizes.
const labelList & oldPatchStarts () const
List of the old patch start labels.
const labelList & oldPatchNMeshPoints () const
List of numbers of mesh points per old patch.
const mapDistribute & pointMap () const
Point distribute map.
const mapDistribute & faceMap () const
Face distribute map.
const mapDistribute & cellMap () const
Cell distribute map.
const mapDistribute & patchMap () const
Patch distribute map.
template<class T >
void distributePointData (List< T > &lst) const
distribute list of point data
template<class T >
void distributeFaceData (List< T > &lst) const
distribute list of face data
template<class T >
void distributeCellData (List< T > &lst) const
distribute list of cell data
template<class T >
void distributePatchData (List< T > &lst) const
distribute list of patch data
void distributePointIndices (labelList &pointIDs) const
distribute list of point/face/cell/patch indices.
void distributeFaceIndices (labelList &faceIDs) const
void distributeCellIndices (labelList &cellIDs) const
void distributePatchIndices (labelList &patchIDs) const
void updateMesh (const mapPolyMesh &)
Correct for topo change.
Detailed Description
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
We store mapping from the bits-to-send to the complete starting mesh (subXXXMap) and from the received bits to their location in the new mesh (constructXXXMap).
Source files
mapDistributePolyMesh.H
mapDistributePolyMesh.C
Definition at line 57 of file mapDistributePolyMesh.H.
Constructor & Destructor Documentation
mapDistributePolyMesh()
mapDistributePolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const Xfer< labelList > & oldPatchStarts, const Xfer< labelList > & oldPatchNMeshPoints, const Xfer< labelListList > & subPointMap, const Xfer< labelListList > & subFaceMap, const Xfer< labelListList > & subCellMap, const Xfer< labelListList > & subPatchMap, const Xfer< labelListList > & constructPointMap, const Xfer< labelListList > & constructFaceMap, const Xfer< labelListList > & constructCellMap, const Xfer< labelListList > & constructPatchMap)
Construct from components. Note that mesh has to be changed already.
Construct from components.
since uses mesh.nPoints etc as the new size.
Definition at line 61 of file mapDistributePolyMesh.C.
Member Function Documentation
mesh()
const polyMesh& mesh () const inline
Definition at line 142 of file mapDistributePolyMesh.H.
Referenced by refinementHistory::distribute().
nOldPoints()
label nOldPoints () const inline
Number of points in mesh before distribution.
Definition at line 148 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributePointIndices().
nOldFaces()
label nOldFaces () const inline
Number of faces in mesh before distribution.
Definition at line 154 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributeFaceIndices().
nOldCells()
label nOldCells () const inline
Number of cells in mesh before distribution.
Definition at line 160 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributeCellIndices().
oldPatchSizes()
const labelList& oldPatchSizes () const inline
List of the old patch sizes.
Definition at line 166 of file mapDistributePolyMesh.H.
oldPatchStarts()
const labelList& oldPatchStarts () const inline
List of the old patch start labels.
Definition at line 172 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributePatchIndices().
oldPatchNMeshPoints()
const labelList& oldPatchNMeshPoints () const inline
List of numbers of mesh points per old patch.
Definition at line 178 of file mapDistributePolyMesh.H.
pointMap()
const mapDistribute& pointMap () const inline
Point distribute map.
Definition at line 184 of file mapDistributePolyMesh.H.
faceMap()
const mapDistribute& faceMap () const inline
Face distribute map.
Definition at line 190 of file mapDistributePolyMesh.H.
cellMap()
const mapDistribute& cellMap () const inline
Cell distribute map.
Definition at line 196 of file mapDistributePolyMesh.H.
Referenced by refinementHistory::distribute().
patchMap()
const mapDistribute& patchMap () const inline
Patch distribute map.
Definition at line 202 of file mapDistributePolyMesh.H.
distributePointData()
void distributePointData (List< T > & lst) const inline
distribute list of point data
Definition at line 212 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by hexRef8::distribute(), and mapDistributePolyMesh::distributePointIndices().
distributeFaceData()
void distributeFaceData (List< T > & lst) const inline
distribute list of face data
Definition at line 219 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by meshRefinement::distribute(), and mapDistributePolyMesh::distributeFaceIndices().
distributeCellData()
void distributeCellData (List< T > & lst) const inline
distribute list of cell data
Definition at line 226 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by hexRef8::distribute(), and mapDistributePolyMesh::distributeCellIndices().
distributePatchData()
void distributePatchData (List< T > & lst) const inline
distribute list of patch data
Definition at line 233 of file mapDistributePolyMesh.H.
References mapDistribute::distribute(), mapDistributePolyMesh::distributeCellIndices(), mapDistributePolyMesh::distributeFaceIndices(), mapDistributePolyMesh::distributePatchIndices(), and mapDistributePolyMesh::distributePointIndices().
Referenced by mapDistributePolyMesh::distributePatchIndices().
distributePointIndices()
void distributePointIndices (labelList & pointIDs) const
distribute list of point/face/cell/patch indices.
(Converts to boolList, distributes boolList and reconstructs)
Definition at line 102 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributePointData(), Foam::findIndices(), and mapDistributePolyMesh::nOldPoints().
Referenced by mapDistributePolyMesh::distributePatchData().
distributeFaceIndices()
void distributeFaceIndices (labelList & faceIDs) const
Definition at line 124 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributeFaceData(), Foam::findIndices(), and mapDistributePolyMesh::nOldFaces().
Referenced by mapDistributePolyMesh::distributePatchData().
distributeCellIndices()
void distributeCellIndices (labelList & cellIDs) const
Definition at line 146 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributeCellData(), Foam::findIndices(), and mapDistributePolyMesh::nOldCells().
Referenced by mapDistributePolyMesh::distributePatchData().
distributePatchIndices()
void distributePatchIndices (labelList & patchIDs) const
Definition at line 168 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributePatchData(), Foam::findIndices(), and mapDistributePolyMesh::oldPatchStarts().
Referenced by mapDistributePolyMesh::distributePatchData().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 249 of file mapDistributePolyMesh.H.
References notImplemented.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.C