OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
objectMap Class Reference
An objectMap is a pair of labels defining the mapping of an object from another object, e.g. a cell mapped from a point.
Public Member Functions
objectMap ()
Null constructor for lists.
objectMap (const label index, const labelList &master)
Construct from components.
objectMap (Istream &)
Construct from Istream.
label & index ()
Return object index.
label index () const
labelList & masterObjects ()
Return master object index.
const labelList & masterObjects () const
Friends
bool operator== (const objectMap &a, const objectMap &b)
bool operator!= (const objectMap &a, const objectMap &b)
Ostream & operator<< (Ostream &, const objectMap &)
Istream & operator>> (Istream &, objectMap &)
Detailed Description
An objectMap is a pair of labels defining the mapping of an object from another object, e.g. a cell mapped from a point.
Source files
objectMap.H
objectMapI.H
Definition at line 58 of file objectMap.H.
Constructor & Destructor Documentation
objectMap() [1/3]
objectMap () inline
Null constructor for lists.
Definition at line 37 of file objectMapI.H.
objectMap() [2/3]
objectMap (const label index, const labelList & master) inline
Construct from components.
Definition at line 44 of file objectMapI.H.
objectMap() [3/3]
objectMap (Istream & is) inline
Construct from Istream.
Definition at line 51 of file objectMapI.H.
References IOstream::check(), Istream::readBegin(), and Istream::readEnd().
Member Function Documentation
index() [1/2]
label & index () inline
Return object index.
Definition at line 68 of file objectMapI.H.
index() [2/2]
label index () const inline
Definition at line 74 of file objectMapI.H.
masterObjects() [1/2]
labelList & masterObjects () inline
Return master object index.
Definition at line 80 of file objectMapI.H.
masterObjects() [2/2]
const labelList & masterObjects () const inline
Definition at line 86 of file objectMapI.H.
Friends And Related Function Documentation
operator==
bool operator== (const objectMap & a, const objectMap & b) friend
Definition at line 94 of file objectMapI.H.
operator!=
bool operator!= (const objectMap & a, const objectMap & b) friend
Definition at line 103 of file objectMapI.H.
operator<<
Ostream& operator<< (Ostream & os, const objectMap & a) friend
Definition at line 111 of file objectMapI.H.
operator>>
Istream& operator>> (Istream & is, objectMap & a) friend
Definition at line 125 of file objectMapI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/objectMap/objectMap.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/objectMap/objectMapI.H