OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapPatchChange Class Reference
Class containing mesh-to-mesh mapping information after a patch change operation.
Public Member Functions
mapPatchChange (const label nOldPatches, const labelList &patchMap)
Construct from components.
label nOldPatches () const
Number of old patches.
const labelList & patchMap () const
Patch map. Size of current patches.
labelList addedPatches () const
labels of added patches
labelList deletedPatches () const
labels (on old mesh) of deleted patches
Detailed Description
Class containing mesh-to-mesh mapping information after a patch change operation.
Source files
mapPatchChange.H
Definition at line 48 of file mapPatchChange.H.
Constructor & Destructor Documentation
mapPatchChange()
mapPatchChange (const label nOldPatches, const labelList & patchMap) inline
Construct from components.
Definition at line 63 of file mapPatchChange.H.
Member Function Documentation
nOldPatches()
label nOldPatches () const inline
Number of old patches.
Definition at line 75 of file mapPatchChange.H.
References mapPatchChange::patchMap().
patchMap()
const labelList& patchMap () const inline
Patch map. Size of current patches.
-1 : patch was added >=0 : old position of patch any original patch which is not in the list has been deleted
Definition at line 84 of file mapPatchChange.H.
Referenced by mapPatchChange::nOldPatches().
addedPatches()
labelList addedPatches () const inline
labels of added patches
Definition at line 93 of file mapPatchChange.H.
References forAll, and List< T >::size().
deletedPatches()
labelList deletedPatches () const inline
labels (on old mesh) of deleted patches
Definition at line 111 of file mapPatchChange.H.
References forAll, and List< T >::setSize().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapPatchChange/mapPatchChange.H