OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
facePointPatch Class Reference
A pointPatch based on a polyPatch.
Public Member Functions
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &, const pointBoundaryMesh &)
Construct from polyPatch.
virtual ~facePointPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
virtual const vectorField & pointNormals () const
Return point unit normals.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Static Public Member Functions
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Attributes
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Friends
class processorPointPatch
class cyclicPointPatch
Detailed Description
A pointPatch based on a polyPatch.
Source files
facePointPatch.H
facePointPatch.C
newPointPatch.C
Definition at line 54 of file facePointPatch.H.
Constructor & Destructor Documentation
facePointPatch()
facePointPatch (const polyPatch & p, const pointBoundaryMesh & bm)
Construct from polyPatch.
Definition at line 82 of file facePointPatch.C.
~facePointPatch()
virtual ~facePointPatch () inline virtual
Destructor.
Definition at line 143 of file facePointPatch.H.
Member Function Documentation
initGeometry()
void initGeometry (PstreamBuffers &) protected virtual
Initialise the calculation of the patch geometry.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 53 of file facePointPatch.C.
Referenced by facePointPatch::initUpdateMesh().
calcGeometry()
void calcGeometry (PstreamBuffers &) protected virtual
Calculate the patch geometry.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and coupledFacePointPatch.
Definition at line 57 of file facePointPatch.C.
initMovePoints()
void initMovePoints (PstreamBuffers & , const pointField &) protected virtual
Initialise the patches for moving points.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 61 of file facePointPatch.C.
movePoints()
void movePoints (PstreamBuffers & , const pointField &) protected virtual
Correct patches after moving points.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 65 of file facePointPatch.C.
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 69 of file facePointPatch.C.
References facePointPatch::initGeometry().
Referenced by cyclicACMIPointPatch::initUpdateMesh(), and cyclicAMIPointPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers &) protected virtual
Update of the patch topology.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 75 of file facePointPatch.C.
Referenced by cyclicACMIPointPatch::updateMesh(), and cyclicAMIPointPatch::updateMesh().
TypeName()
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , facePointPatch , polyPatch , (const polyPatch &patch, const pointBoundaryMesh &bm) , (patch, bm))
New()
Foam::autoPtr< Foam::facePointPatch > New (const polyPatch & patch, const pointBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from polyPatch.
Definition at line 31 of file facePointPatchNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
patch()
const polyPatch& patch () const inline
Return the polyPatch.
Definition at line 150 of file facePointPatch.H.
References facePointPatch::polyPatch_.
name()
virtual const word& name () const inline virtual
Return name.
Implements pointPatch.
Definition at line 156 of file facePointPatch.H.
References patchIdentifier::name().
size()
virtual label size () const inline virtual
Return size.
Implements pointPatch.
Definition at line 162 of file facePointPatch.H.
References facePointPatch::meshPoints(), and List< T >::size().
index()
virtual label index () const inline virtual
Return the index of this patch in the pointBoundaryMesh.
Implements pointPatch.
Definition at line 168 of file facePointPatch.H.
References patchIdentifier::index().
Referenced by cyclicPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), and cyclicAMIPointPatchField< Type >::swapAddSeparated().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch.
Definition at line 174 of file facePointPatch.H.
References polyPatch::coupled().
meshPoints()
virtual const labelList& meshPoints () const inline virtual
Return mesh points.
Implements pointPatch.
Definition at line 180 of file facePointPatch.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints().
Referenced by facePointPatch::size().
localPoints()
virtual const pointField& localPoints () const inline virtual
Return pointField of points in patch.
Implements pointPatch.
Definition at line 187 of file facePointPatch.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints().
pointNormals()
virtual const vectorField& pointNormals () const inline virtual
Return point unit normals.
Implements pointPatch.
Reimplemented in cyclicSlipPointPatch, and nonuniformTransformCyclicPointPatch.
Definition at line 194 of file facePointPatch.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::pointNormals().
Referenced by cyclicSlipPointPatch::pointNormals(), and nonuniformTransformCyclicPointPatch::pointNormals().
Friends And Related Function Documentation
processorPointPatch
friend class processorPointPatch friend
Definition at line 102 of file facePointPatch.H.
cyclicPointPatch
friend class cyclicPointPatch friend
Definition at line 103 of file facePointPatch.H.
Member Data Documentation
polyPatch_
const polyPatch& polyPatch_ protected
Reference to the underlying polyPatch.
Definition at line 63 of file facePointPatch.H.
Referenced by facePointPatch::patch().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/facePointPatch/facePointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/facePointPatch/facePointPatch.C
src/OpenFOAM/meshes/pointMesh/pointPatches/facePointPatch/facePointPatchNew.C