OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapDistribute::transformPosition Class Reference
Default transformation behaviour for position.
Public Member Functions
void operator() (const vectorTensorTransform &vt, const bool forward, List< point > &fld) const
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< point > > &flds) const
void operator() (const coupledPolyPatch &cpp, pointField &fld) const
Transform patch-based field.
template<template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< point > &map) const
Detailed Description
Default transformation behaviour for position.
Definition at line 302 of file mapDistribute.H.
Member Function Documentation
operator()() [1/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< point > & fld) const inline
Definition at line 307 of file mapDistribute.H.
References fld(), vectorTensorTransform::invTransformPosition(), and vectorTensorTransform::transformPosition().
operator()() [2/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< point > > & flds) const inline
Definition at line 324 of file mapDistribute.H.
References forAll, and mapDistribute::transform::operator()().
operator()() [3/4]
void operator() (const coupledPolyPatch & cpp, pointField & fld) const inline
Transform patch-based field.
Definition at line 336 of file mapDistribute.H.
References coupledPolyPatch::transformPosition().
operator()() [4/4]
void operator() (const coupledPolyPatch & cpp, Container< point > & map) const inline
Definition at line 341 of file mapDistribute.H.
References mapDistribute::ClassName(), mapDistribute::constructMap(), mapDistribute::constructSize(), fld(), forAllConstIter(), forAllIter, mapDistribute::mapDistribute(), UPstream::msgType(), mapDistribute::subMap(), mapDistribute::transformElements(), coupledPolyPatch::transformPosition(), and mapDistribute::transformStart().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H