OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tetIndices Class Reference
Storage and named access for the indices of a tet which is part of the decomposition of a cell.
Public Member Functions
tetIndices ()
Construct null.
tetIndices (label cellI, label faceI, label faceBasePtI, label facePtAI, label facePtBI, label tetPtI)
Construct from components.
tetIndices (label cellI, label faceI, label tetPtI, const polyMesh &mesh)
Construct from cell, face, pt description of tet.
~tetIndices ()
Destructor.
label cell () const
Return the cell.
label face () const
Return the face.
label faceBasePt () const
Return the face base point.
label facePtA () const
Return face point A.
label facePtB () const
Return face point B.
label tetPt () const
Return the characterising tetPtI.
tetPointRef tet (const polyMesh &mesh) const
Return the geometry corresponding to this tet from the.
tetPointRef oldTet (const polyMesh &mesh) const
Return the geometry corresponding to this tet from the.
triPointRef faceTri (const polyMesh &mesh) const
Return the geometry corresponding to the tri on the.
triFace faceTriIs (const polyMesh &mesh) const
Return the point indices corresponding to the tri on the mesh.
triPointRef oldFaceTri (const polyMesh &mesh) const
Return the geometry corresponding to the tri on the.
label & cell ()
Return non-const access to the cell.
label & face ()
Return non-const access to the face.
label & faceBasePt ()
Return non-const access to the face base point.
label & facePtA ()
Return non-const access to face point A.
label & facePtB ()
Return non-const access to face point B.
label & tetPt ()
Return non-const access to the characterising tetPtI.
bool operator== (const tetIndices &) const
bool operator!= (const tetIndices &) const
Friends
Istream & operator>> (Istream &, tetIndices &)
Ostream & operator<< (Ostream &, const tetIndices &)
Detailed Description
Storage and named access for the indices of a tet which is part of the decomposition of a cell.
Tets are designated by
cell (of course)
face on cell
three points on face (faceBasePt, facePtA, facePtB) When constructing from a mesh and index in the face (tetPtI):
faceBasePt is the mesh.tetBasePtIs() base point
facePtA is tetPtI away from faceBasePt
facePtB is next one after/before facePtA e.g.:
+—+ |2 /| | / | |/ 1| <- tetPt (so 1 for first triangle, 2 for second) +—+ ^ faceBasePt
Source files
tetIndices.H
tetIndicesI.H
tetIndices.C
Definition at line 73 of file tetIndices.H.
Constructor & Destructor Documentation
tetIndices() [1/3]
tetIndices ()
Construct null.
Definition at line 30 of file tetIndices.C.
Referenced by tetIndices::tetIndices().
tetIndices() [2/3]
tetIndices (label cellI, label faceI, label faceBasePtI, label facePtAI, label facePtBI, label tetPtI)
Construct from components.
Definition at line 42 of file tetIndices.C.
References tetIndices::tetIndices().
tetIndices() [3/3]
tetIndices (label cellI, label faceI, label tetPtI, const polyMesh & mesh)
Construct from cell, face, pt description of tet.
Definition at line 61 of file tetIndices.C.
References f(), polyMesh::faceOwner(), polyMesh::faces(), UList< T >::fcIndex(), pFaces, List< T >::size(), and polyMesh::tetBasePtIs().
~tetIndices()
~tetIndices ()
Destructor.
Definition at line 102 of file tetIndices.C.
References tetIndices::cell(), IOstream::check(), Foam::endl(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), Foam::operator<<(), Foam::operator>>(), token::SPACE, and tetIndices::tetPt().
Member Function Documentation
cell() [1/2]
Foam::label cell () const inline
Return the cell.
Definition at line 30 of file tetIndicesI.H.
Referenced by Basic< Type >::add(), Moment< Type >::add(), Dual< Type >::add(), polyMeshTetDecomposition::faceTetIndices(), polyMeshTetDecomposition::findTet(), interpolationCellPointWallModified< Type >::interpolate(), interpolationCellPoint< Foam::Vector >::interpolate(), Basic< Type >::interpolate(), interpolation< Foam::Vector >::interpolate(), Moment< Type >::interpolate(), Dual< Type >::interpolate(), Basic< Type >::interpolateGrad(), Moment< Type >::interpolateGrad(), Dual< Type >::interpolateGrad(), tetIndices::operator==(), particle< Type >::trackToFace(), polyMeshTetDecomposition::triangleTetIndices(), and tetIndices::~tetIndices().
face() [1/2]
Foam::label face () const inline
Return the face.
Definition at line 36 of file tetIndicesI.H.
Referenced by Dual< Type >::Dual(), polyMeshTetDecomposition::faceTetIndices(), polyMesh::findTetFacePt(), cellPointWeight::findTetrahedron(), interpolationCellPointWallModified< Type >::interpolate(), interpolationCellPoint< Foam::Vector >::interpolate(), Moment< Type >::Moment(), tetIndices::operator==(), wallBoundedParticle::trackToEdge(), particle< Type >::trackToFace(), polyMeshTetDecomposition::triangleTetIndices(), AveragingMethod< Foam::Vector >::write(), Dual< Type >::~Dual(), and tetIndices::~tetIndices().
faceBasePt() [1/2]
Foam::label faceBasePt () const inline
Return the face base point.
Definition at line 42 of file tetIndicesI.H.
Referenced by Dual< Type >::Dual(), polyMeshTetDecomposition::faceTetIndices(), cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), particle< Type >::hitWallFaces(), interpolationCellPoint< Foam::Vector >::interpolate(), Moment< Type >::Moment(), tetIndices::operator==(), wallBoundedParticle::trackToEdge(), polyMeshTetDecomposition::triangleTetIndices(), AveragingMethod< Foam::Vector >::write(), Dual< Type >::~Dual(), and tetIndices::~tetIndices().
facePtA() [1/2]
Foam::label facePtA () const inline
Return face point A.
Definition at line 48 of file tetIndicesI.H.
Referenced by Dual< Type >::Dual(), polyMeshTetDecomposition::faceTetIndices(), cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), interpolationCellPoint< Foam::Vector >::interpolate(), Moment< Type >::Moment(), tetIndices::operator==(), wallBoundedParticle::trackToEdge(), polyMeshTetDecomposition::triangleTetIndices(), AveragingMethod< Foam::Vector >::write(), Dual< Type >::~Dual(), and tetIndices::~tetIndices().
facePtB() [1/2]
Foam::label facePtB () const inline
Return face point B.
Definition at line 54 of file tetIndicesI.H.
Referenced by Dual< Type >::Dual(), polyMeshTetDecomposition::faceTetIndices(), cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), interpolationCellPoint< Foam::Vector >::interpolate(), Moment< Type >::Moment(), tetIndices::operator==(), wallBoundedParticle::trackToEdge(), polyMeshTetDecomposition::triangleTetIndices(), AveragingMethod< Foam::Vector >::write(), Dual< Type >::~Dual(), and tetIndices::~tetIndices().
tetPt() [1/2]
Foam::label tetPt () const inline
Return the characterising tetPtI.
Definition at line 60 of file tetIndicesI.H.
Referenced by polyMeshTetDecomposition::faceTetIndices(), polyMesh::findTetFacePt(), particle< Type >::hitWallFaces(), FreeStream< CloudType >::inflow(), tetIndices::operator==(), polyMeshTetDecomposition::triangleTetIndices(), and tetIndices::~tetIndices().
tet()
Foam::tetPointRef tet (const polyMesh & mesh) const inline
Return the geometry corresponding to this tet from the.
supplied mesh
Definition at line 66 of file tetIndicesI.H.
References primitiveMesh::cellCentres(), f(), polyMesh::faces(), pFaces, and polyMesh::points().
Referenced by particle< Type >::currentTet(), Dual< Type >::Dual(), polyMeshTetDecomposition::findTet(), cellPointWeight::findTetrahedron(), particle< Type >::hitWallFaces(), interpolationCellPoint< Foam::Vector >::interpolate(), Moment< Type >::Moment(), particle< Type >::movingTetLambda(), particle< Type >::trackToFace(), AveragingMethod< Foam::Vector >::write(), and Dual< Type >::~Dual().
oldTet()
Foam::tetPointRef oldTet (const polyMesh & mesh) const inline
Return the geometry corresponding to this tet from the.
supplied mesh using the old positions
Definition at line 84 of file tetIndicesI.H.
References primitiveMesh::cells(), f(), polyMesh::faces(), polyMesh::oldPoints(), and pFaces.
Referenced by particle< Type >::movingTetLambda().
faceTri()
Foam::triPointRef faceTri (const polyMesh & mesh) const inline
Return the geometry corresponding to the tri on the.
mesh face for this tet from the supplied mesh. Normal of the tri points out of the cell.
Definition at line 109 of file tetIndicesI.H.
References f(), polyMesh::faces(), pFaces, and polyMesh::points().
Referenced by cellPointWeight::findTriangle(), particle< Type >::hitWallFaces(), solidParticle::hitWallPatch(), FreeStream< CloudType >::inflow(), particle< Type >::normal(), KinematicCloud< Foam::DsmcCloud >::patchData(), polyMesh::pointInCell(), wallBoundedParticle::trackToEdge(), and particle< Type >::trackToFace().
faceTriIs()
Foam::triFace faceTriIs (const polyMesh & mesh) const inline
Return the point indices corresponding to the tri on the mesh.
face for this tet from the supplied mesh. Normal of the tri points out of the cell.
Definition at line 125 of file tetIndicesI.H.
References f(), polyMesh::faces(), pFaces, and triFace().
oldFaceTri()
Foam::triPointRef oldFaceTri (const polyMesh & mesh) const inline
Return the geometry corresponding to the tri on the.
mesh face for this tet from the supplied mesh using the old position
Definition at line 140 of file tetIndicesI.H.
References f(), polyMesh::faces(), polyMesh::oldPoints(), and pFaces.
Referenced by particle< Type >::hitWallFaces(), particle< Type >::oldNormal(), and KinematicCloud< Foam::DsmcCloud >::patchData().
cell() [2/2]
Foam::label & cell () inline
Return non-const access to the cell.
Definition at line 156 of file tetIndicesI.H.
face() [2/2]
Foam::label & face () inline
Return non-const access to the face.
Definition at line 162 of file tetIndicesI.H.
faceBasePt() [2/2]
Foam::label & faceBasePt () inline
Return non-const access to the face base point.
Definition at line 168 of file tetIndicesI.H.
facePtA() [2/2]
Foam::label & facePtA () inline
Return non-const access to face point A.
Definition at line 174 of file tetIndicesI.H.
facePtB() [2/2]
Foam::label & facePtB () inline
Return non-const access to face point B.
Definition at line 180 of file tetIndicesI.H.
tetPt() [2/2]
Foam::label & tetPt () inline
Return non-const access to the characterising tetPtI.
Definition at line 186 of file tetIndicesI.H.
operator==()
bool operator== (const tetIndices & rhs) const inline
Definition at line 194 of file tetIndicesI.H.
References tetIndices::cell(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), and tetIndices::tetPt().
operator!=()
bool operator!= (const tetIndices & rhs) const inline
Definition at line 208 of file tetIndicesI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , tetIndices &) friend
operator<<
Ostream& operator<< (Ostream & , const tetIndices &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndices.H
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndices.C
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndicesI.H