OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointHitSort Class Reference
Container for sorting intersections.
Public Member Functions
pointHitSort ()
Construct null.
pointHitSort (const pointHit &inter, const label index)
Construct from intersection, index.
const pointHit & inter () const
label index () const
bool operator== (const pointHitSort &rhs) const
bool operator< (const pointHitSort &rhs) const
Detailed Description
Container for sorting intersections.
Source files
pointHitSort.H
Definition at line 50 of file pointHitSort.H.
Constructor & Destructor Documentation
pointHitSort() [1/2]
pointHitSort () inline
Construct null.
Definition at line 65 of file pointHitSort.H.
pointHitSort() [2/2]
pointHitSort (const pointHit & inter, const label index) inline
Construct from intersection, index.
Definition at line 72 of file pointHitSort.H.
Member Function Documentation
inter()
const pointHit& inter () const inline
Definition at line 81 of file pointHitSort.H.
Referenced by pointHitSort::operator<(), and pointHitSort::operator==().
index()
label index () const inline
Definition at line 86 of file pointHitSort.H.
operator==()
bool operator== (const pointHitSort & rhs) const inline
Definition at line 93 of file pointHitSort.H.
References PointHit< Point >::distance(), and pointHitSort::inter().
operator<()
bool operator< (const pointHitSort & rhs) const inline
Definition at line 98 of file pointHitSort.H.
References PointHit< Point >::distance(), and pointHitSort::inter().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/pointHitSort.H