OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PointIndexHit< Point > Class Template Reference
This class describes the interaction of (usually) a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Public Member Functions
PointIndexHit (const bool success, const Point &p, const label index)
Construct from components.
PointIndexHit (const Point &p)
Construct from point. Hit and distance set later.
PointIndexHit ()
Construct null.
PointIndexHit (Istream &is)
Construct from Istream.
bool hit () const
Is there a hit.
label index () const
Return index.
const Point & hitPoint () const
Return hit point.
const Point & missPoint () const
Return miss point.
const Point & rawPoint () const
Return point with no checking.
Point & rawPoint ()
void setHit ()
void setMiss ()
void setPoint (const Point &p)
void setIndex (const label index)
bool operator== (const PointIndexHit &rhs) const
bool operator!= (const PointIndexHit &rhs) const
void write (Ostream &os)
Friends
Ostream & operator<< (Ostream &os, const PointIndexHit &pHit)
Istream & operator>> (Istream &is, PointIndexHit &pHit)
Detailed Description
template<class Point>
class Foam::PointIndexHit< Point >
This class describes the interaction of (usually) a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
like pointHit but carries face (or cell, edge etc.) index
Source files
PointIndexHit.H
Definition at line 53 of file PointIndexHit.H.
Constructor & Destructor Documentation
PointIndexHit() [1/4]
PointIndexHit (const bool success, const Point & p, const label index) inline
Construct from components.
Definition at line 72 of file PointIndexHit.H.
PointIndexHit() [2/4]
PointIndexHit (const Point & p) inline
Construct from point. Hit and distance set later.
Definition at line 80 of file PointIndexHit.H.
PointIndexHit() [3/4]
PointIndexHit () inline
Construct null.
Definition at line 88 of file PointIndexHit.H.
PointIndexHit() [4/4]
PointIndexHit (Istream & is) inline
Construct from Istream.
Definition at line 96 of file PointIndexHit.H.
Member Function Documentation
hit()
bool hit () const inline
Is there a hit.
Definition at line 105 of file PointIndexHit.H.
Referenced by nearWallFields::calcAddressing(), searchableSurfacesQueries::facesIntersection(), polyMesh::findCellFacePt(), patchProbes::findElements(), mapNearestMethod::findInitialSeeds(), searchableSphere::findLine(), searchableCylinder::findLine(), indexedOctree< Foam::treeDataFace >::findLine(), triSurfaceSearch::findLineAll(), searchableSphere::findLineAll(), searchableDisk::findLineAll(), searchableCylinder::findLineAll(), searchableBox::findLineAll(), searchableSphere::findLineAny(), searchableCylinder::findLineAny(), triSurfaceRegionSearch::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), mappedPatchBase::findSamples(), AMIMethod< SourcePatch, TargetPatch >::findTargetFace(), boundaryMesh::getNearest(), meshSearch::intersection(), meshSearch::intersections(), edgeIntersections::merge(), NamedEnum< directionType, 3 >::names(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), PointIndexHit< Point >::operator==(), triSurfaceTools::track(), triSurfaceTools::trackToEdge(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), surfaceLocation::write(), and PointIndexHit< Point >::write().
index()
label index () const inline
Return index.
Definition at line 111 of file PointIndexHit.H.
Referenced by polyMesh::findCellFacePt(), patchProbes::findElements(), mapNearestMethod::findInitialSeeds(), searchableBox::findLine(), triSurfaceSearch::findLineAll(), searchableBox::findLineAll(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), mappedPatchBase::findSamples(), AMIMethod< SourcePatch, TargetPatch >::findTargetFace(), boundaryMesh::getNearest(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), meshSearch::intersection(), meshSearch::intersections(), edgeIntersections::merge(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), surfaceLocation::normal(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), PointIndexHit< Point >::operator==(), PointIndexHit< Point >::setIndex(), surfaceIntersection::surfaceIntersection(), triSurfaceTools::trackToEdge(), surfaceLocation::write(), and PointIndexHit< Point >::write().
hitPoint()
const Point& hitPoint () const inline
Return hit point.
Definition at line 117 of file PointIndexHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by nearWallFields::calcAddressing(), searchableSurfacesQueries::facesIntersection(), searchableBox::findLineAll(), triSurfaceRegionSearch::findNearest(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), mappedPatchBase::findSamples(), AMIMethod< SourcePatch, TargetPatch >::findTargetFace(), boundaryMesh::getNearest(), meshSearch::intersections(), NamedEnum< directionType, 3 >::names(), surfaceFeatures::nearestSurfEdge(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), surfaceIntersection::surfaceIntersection(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and PointIndexHit< Point >::write().
missPoint()
const Point& missPoint () const inline
Return miss point.
Definition at line 130 of file PointIndexHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by listPlusEqOp< T >::operator()(), and PointIndexHit< Point >::write().
rawPoint() [1/2]
const Point& rawPoint () const inline
Return point with no checking.
Definition at line 143 of file PointIndexHit.H.
Referenced by searchableBox::findLine(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), searchableBox::findNearestOnEdge(), edgeIntersections::merge(), NamedEnum< directionType, 3 >::names(), surfaceFeatures::nearestSurfEdge(), PointIndexHit< Point >::operator==(), searchableCylinder::points(), triSurfaceTools::trackToEdge(), and surfaceLocation::write().
rawPoint() [2/2]
Point& rawPoint () inline
Definition at line 148 of file PointIndexHit.H.
setHit()
void setHit () inline
Definition at line 153 of file PointIndexHit.H.
Referenced by triSurfaceTools::classify(), searchableBox::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), and searchableCylinder::points().
setMiss()
void setMiss () inline
Definition at line 158 of file PointIndexHit.H.
Referenced by triSurfaceTools::classify(), searchableBox::findNearestOnEdge(), searchableCylinder::points(), and triSurfaceTools::trackToEdge().
setPoint()
void setPoint (const Point & p) inline
Definition at line 163 of file PointIndexHit.H.
References p.
Referenced by triSurfaceTools::classify(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), mappedPatchBase::findSamples(), and searchableCylinder::points().
setIndex()
void setIndex (const label index) inline
Definition at line 168 of file PointIndexHit.H.
References PointIndexHit< Point >::index().
Referenced by triSurfaceTools::classify(), searchableBox::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), searchableBox::findNearestOnEdge(), meshSearch::intersection(), NamedEnum< directionType, 3 >::names(), and searchableCylinder::points().
operator==()
bool operator== (const PointIndexHit< Point > & rhs) const inline
Definition at line 173 of file PointIndexHit.H.
References PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), and PointIndexHit< Point >::rawPoint().
Referenced by PointIndexHit< Point >::operator!=().
operator!=()
bool operator!= (const PointIndexHit< Point > & rhs) const inline
Definition at line 181 of file PointIndexHit.H.
References PointIndexHit< Point >::operator==().
write()
void write (Ostream & os) inline
Definition at line 186 of file PointIndexHit.H.
References PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), and PointIndexHit< Point >::missPoint().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const PointIndexHit< Point > & pHit) friend
Definition at line 198 of file PointIndexHit.H.
operator>>
Istream& operator>> (Istream & is, PointIndexHit< Point > & pHit) friend
Definition at line 220 of file PointIndexHit.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/PointIndexHit.H