OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
line< Point, PointRef > Class Template Reference
A line primitive.
Public Member Functions
line (const Point &start, const Point &end)
Construct from two points.
line (const UList< Point > &, const FixedList< label, 2 > &indices)
Construct from two points in the list of points.
line (Istream &)
Construct from Istream.
PointRef start () const
Return first vertex.
PointRef end () const
Return second vertex.
Point centre () const
Return centre (centroid)
scalar mag () const
Return scalar magnitude.
Point vec () const
Return start-end vector.
PointHit< Point > nearestDist (const Point &p) const
Return nearest distance to line from a given point.
scalar nearestDist (const line< Point, const Point &> &edge, Point &thisPoint, Point &edgePoint) const
Return nearest distance from line to line. Returns distance.
template<>
scalar nearestDist (const line< point2D, const point2D & > &e, point2D &thisPt, point2D &edgePt) const
template<>
scalar nearestDist (const line< point2D, const point2D & > &edge, point2D &thisPoint, point2D &edgePoint) const
2D specialisation
Friends
Istream & operator>> (Istream &, line &)
Ostream & operator (Ostream &, const line &)
Detailed Description
template<class Point, class PointRef>
class Foam::line< Point, PointRef >
A line primitive.
Source files
line.H
lineI.H
Definition at line 56 of file line.H.
Constructor & Destructor Documentation
line() [1/3]
line (const Point & start, const Point & end) inline
Construct from two points.
Definition at line 31 of file lineI.H.
line() [2/3]
line (const UList< Point > & points, const FixedList< label, 2 > & indices) inline
Construct from two points in the list of points.
The indices could be from edge etc.
Definition at line 40 of file lineI.H.
line() [3/3]
line (Istream & is) inline
Construct from Istream.
Definition at line 51 of file lineI.H.
Member Function Documentation
start()
PointRef start () const inline
Return first vertex.
Definition at line 60 of file lineI.H.
Referenced by dynamicTreeDataPoint::findNearest(), plane::lineIntersect(), slidingInterface::modifyMotionPoints(), line< Point, PointRef >::nearestDist(), triangle< Point, PointRef >::nearestPoint(), and OBJstream::write().
end()
PointRef end () const inline
Return second vertex.
Definition at line 66 of file lineI.H.
Referenced by dynamicTreeDataPoint::findNearest(), line< Point, PointRef >::nearestDist(), triangle< Point, PointRef >::nearestPoint(), and OBJstream::write().
centre()
Point centre () const inline
Return centre (centroid)
Definition at line 73 of file lineI.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), and surfaceFeatures::nearestSurfEdge().
mag()
Foam::scalar mag () const inline
Return scalar magnitude.
Definition at line 80 of file lineI.H.
References Foam::mag(), and line< Point, PointRef >::vec().
Referenced by slidingInterface::modifyMotionPoints().
vec()
Point vec () const inline
Return start-end vector.
Definition at line 87 of file lineI.H.
References line< Point, PointRef >::nearestDist().
Referenced by plane::lineIntersect(), line< Point, PointRef >::mag(), slidingInterface::modifyMotionPoints(), line< Point, PointRef >::nearestDist(), and triangle< Point, PointRef >::nearestPoint().
nearestDist() [1/4]
Foam::PointHit< Point > nearestDist (const Point & p) const
Return nearest distance to line from a given point.
If the nearest point is on the line, return a hit
Definition at line 95 of file lineI.H.
References Foam::constant::physicoChemical::b, Foam::constant::physicoChemical::c1, Foam::constant::physicoChemical::c2, Foam::mag(), and line< Point, PointRef >::vec().
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), dynamicTreeDataPoint::findNearest(), treeDataPrimitivePatch< PatchType >::getVolumeType(), slidingInterface::modifyMotionPoints(), line< Point, PointRef >::nearestDist(), triangle< Point, PointRef >::nearestPoint(), surfaceFeatures::nearestSamples(), treeDataEdge::overlaps(), faceCollapser::setRefinement(), and line< Point, PointRef >::vec().
nearestDist() [2/4]
Foam::scalar nearestDist (const line< Point, const Point &> & edge, Point & thisPoint, Point & edgePoint) const
Return nearest distance from line to line. Returns distance.
and sets both points (one on *this, one on the provided linePointRef.
Definition at line 127 of file lineI.H.
References Foam::constant::physicoChemical::b, token::BEGIN_LIST, Foam::constant::universal::c, IOstream::check(), PointHit< Point >::distance(), line< Point, PointRef >::end(), token::END_LIST, Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), line< Point, PointRef >::nearestDist(), PointHit< Point >::rawPoint(), Istream::readBegin(), Istream::readEnd(), s(), token::SPACE, and line< Point, PointRef >::start().
nearestDist() [3/4]
scalar nearestDist (const line< point2D, const point2D &> & e, point2D & thisPt, point2D & edgePt) const
Definition at line 37 of file line.C.
References d(), line< Point, PointRef >::end(), Foam::mag(), Foam::max(), Foam::min(), line< Point, PointRef >::nearestDist(), Vector2D< Cmpt >::perp(), s(), and line< Point, PointRef >::start().
nearestDist() [4/4]
scalar nearestDist (const line< point2D, const point2D & > & edge, point2D & thisPoint, point2D & edgePoint) const
2D specialisation
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , line< Point, PointRef > &) friend
operator
Ostream& operator (Ostream & , const line< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/line/line.H
src/OpenFOAM/meshes/primitiveShapes/line/lineI.H