OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Table< Type > Class Template Reference
Templated table container data entry. Items are stored in a list of Tuple2's. First column is always stored as scalar entries. Data is read in Tuple2 form, e.g. for an entry <entryName> that is (scalar, vector):
Public Member Functions
TypeName ("table")
Runtime type information.
Table (const word &entryName, const dictionary &dict)
Construct from entry name and Istream.
Table (const Table< Type > &tbl)
Copy constructor.
virtual tmp< DataEntry< Type > > clone () const
Construct and return a clone.
virtual ~Table ()
Destructor.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual dimensioned< Type > dimValue (const scalar x) const
Return dimensioned constant value.
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2)
Integrate between two values and return dimensioned type.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from DataEntry< Type >
TypeName ("DataEntry") declareRunTimeSelectionTable(autoPtr
Runtime type information.
DataEntry (const word &entryName)
Construct from entry name.
DataEntry (const DataEntry< Type > &de)
Copy constructor.
virtual ~DataEntry ()
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual tmp< Field< dimensioned< Type > > > dimValue (const scalarField &x) const
Return dimensioned type as a function of (scalar)
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two scalars and return a dimensioned type.
virtual tmp< Field< dimensioned< Type > > > dimIntegrate (const scalarField &x1, const scalarField &x2) const
Integrate between two scalar fields and return a field of.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from TableBase< Type >
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two values and return dimensioned type.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format. Used for non-inline.
Friends
Ostream & operator (Ostream &os, const Table< Type > &tbl)
Ostream Operator.
Additional Inherited Members
Public Types inherited from TableBase< Type >
enum boundsHandling { ERROR, WARN, CLAMP, REPEAT }
Enumeration for handling out-of-bound values.
Static Public Member Functions inherited from DataEntry< Type >
static autoPtr< DataEntry< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from DataEntry< Type >
DataEntry
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Member Functions inherited from TableBase< Type >
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)
Disallow default bitwise assignment.
Protected Attributes inherited from DataEntry< Type >
const word name_
Name of entry.
Protected Attributes inherited from TableBase< Type >
const word name_
Table name.
const boundsHandling boundsHandling_
Enumeration for handling out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
dimensionSet dimensions_
The dimension set.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Detailed Description
template<class Type>
class Foam::Table< Type >
Templated table container data entry. Items are stored in a list of Tuple2's. First column is always stored as scalar entries. Data is read in Tuple2 form, e.g. for an entry <entryName> that is (scalar, vector):
    <entryName>   table
    (
        (0.0 (1 2 3))
        (1.0 (4 5 6))
    );
Source files
Table.H
Table.C
Definition at line 56 of file Table.H.
Constructor & Destructor Documentation
Table() [1/2]
Table (const word & entryName, const dictionary & dict)
Construct from entry name and Istream.
Definition at line 31 of file Table.C.
References token::BEGIN_SQR, TableBase< Type >::check(), TableBase< Type >::dimensions_, dictionary::lookup(), and TableBase< Type >::table_.
Table() [2/2]
Table (const Table< Type > & tbl)
Copy constructor.
Definition at line 52 of file Table.C.
~Table()
~Table () virtual
Destructor.
Definition at line 62 of file Table.C.
Referenced by Table< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("table")
Runtime type information.
clone()
virtual tmp<DataEntry<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from DataEntry< Type >.
Definition at line 96 of file Table.H.
References Table< Type >::~Table().
convertTimeBase()
virtual void convertTimeBase (const Time & t) inline virtual
Convert time.
Reimplemented from DataEntry< Type >.
Definition at line 111 of file Table.H.
References TableBase< Type >::convertTimeBase().
value()
virtual Type value (const scalar x) const inline virtual
Return Table value.
Reimplemented from DataEntry< Type >.
Definition at line 120 of file Table.H.
References TableBase< Type >::value().
integrate()
virtual Type integrate (const scalar x1, const scalar x2) const inline virtual
Integrate between two (scalar) values.
Reimplemented from DataEntry< Type >.
Definition at line 126 of file Table.H.
References TableBase< Type >::integrate().
dimValue()
virtual dimensioned<Type> dimValue (const scalar x) const inline virtual
Return dimensioned constant value.
Reimplemented from DataEntry< Type >.
Definition at line 132 of file Table.H.
References Table< Type >::dimIntegrate(), and TableBase< Type >::dimValue().
dimIntegrate()
virtual dimensioned<Type> dimIntegrate (const scalar x1, const scalar x2) inline virtual
Integrate between two values and return dimensioned type.
Definition at line 139 of file Table.H.
References TableBase< Type >::dimIntegrate(), and Table< Type >::writeData().
Referenced by Table< Type >::dimValue().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from DataEntry< Type >.
Definition at line 51 of file TableIO.C.
References writeData().
Referenced by Table< Type >::dimIntegrate().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const Table< Type > & tbl) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/Table/Table.H
src/OpenFOAM/primitives/functions/DataEntry/Table/Table.C
src/OpenFOAM/primitives/functions/DataEntry/Table/TableIO.C