OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Tensor< Cmpt > Class Template Reference
Templated 3D tensor derived from VectorSpace adding construction from 9 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum { rank = 2 }
enum components {
XX, XY, XZ, YX,
YY, YZ, ZX, ZY,
ZZ
}
Component labeling enumeration.
typedef Tensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Tensor< Cmpt >, Cmpt, 9 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
Tensor ()
Construct null.
template<class Cmpt2 >
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &)
Construct given VectorSpace of the same rank.
Tensor (const SphericalTensor< Cmpt > &)
Construct given SphericalTensor.
Tensor (const SymmTensor< Cmpt > &)
Construct given SymmTensor.
Tensor (const Vector< Vector< Cmpt > > &)
Construct given triad.
Tensor (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Construct given the three vector components.
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz)
Construct given the nine components.
Tensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yx () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zx () const
const Cmpt & zy () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yx ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zx ()
Cmpt & zy ()
Cmpt & zz ()
Vector< Cmpt > x () const
Vector< Cmpt > y () const
Vector< Cmpt > z () const
Vector< Cmpt > vectorComponent (const direction) const
Tensor< Cmpt > T () const
Transpose.
void operator= (const SphericalTensor< Cmpt > &)
Assign to a SphericalTensor.
void operator= (const SymmTensor< Cmpt > &)
Assign to a SymmTensor.
void operator= (const Vector< Vector< Cmpt > > &)
Assign to a triad.
Public Member Functions inherited from VectorSpace< Tensor< Cmpt >, Cmpt, 9 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Tensor< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Tensor< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< Tensor< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< Tensor< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "labelTensor"
static const char * componentNames []
static const Tensor zero
static const Tensor one
static const Tensor max
static const Tensor min
static const Tensor I
Additional Inherited Members
Public Attributes inherited from VectorSpace< Tensor< Cmpt >, Cmpt, 9 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Tensor< Cmpt >
Templated 3D tensor derived from VectorSpace adding construction from 9 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
Tensor.H
TensorI.H
Definition at line 224 of file complexI.H.
Member Typedef Documentation
labelType
typedef Tensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 64 of file Tensor.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
rank
Definition at line 69 of file Tensor.H.
components
enum components
Component labeling enumeration.
Enumerator
XX
XY
XZ
YX
YY
YZ
ZX
ZY
ZZ
Definition at line 88 of file Tensor.H.
Constructor & Destructor Documentation
Tensor() [1/8]
Tensor () inline
Construct null.
Definition at line 36 of file TensorI.H.
Tensor() [2/8]
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 42 of file TensorI.H.
Tensor() [3/8]
Tensor (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 49 of file TensorI.H.
Tensor() [4/8]
Tensor (const SymmTensor< Cmpt > & st) inline
Construct given SymmTensor.
Definition at line 58 of file TensorI.H.
Tensor() [5/8]
Tensor (const Vector< Vector< Cmpt > > & tr) inline
Construct given triad.
Definition at line 67 of file TensorI.H.
Tensor() [6/8]
Tensor (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Construct given the three vector components.
Definition at line 85 of file TensorI.H.
Tensor() [7/8]
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz) inline
Construct given the nine components.
Definition at line 99 of file TensorI.H.
Tensor() [8/8]
Tensor (Istream & is) inline
Construct from Istream.
Definition at line 112 of file TensorI.H.
Member Function Documentation
xx() [1/2]
const Cmpt & xx () const inline
Definition at line 160 of file TensorI.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), fixedCoeff::calcTranformModelData(), DarcyForchheimer::calcTranformModelData(), Foam::cof(), molecule::constantProperties::constantProperties(), Foam::det(), Foam::diag(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), triad::sortxyz(), Foam::symm(), Foam::tr(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
xy() [1/2]
const Cmpt & xy () const inline
Definition at line 167 of file TensorI.H.
Referenced by Foam::cof(), LRR::correct(), LaunderGibsonRSTM::correct(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), Foam::symm(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
xz() [1/2]
const Cmpt & xz () const inline
Definition at line 174 of file TensorI.H.
Referenced by Foam::cof(), LRR::correct(), LaunderGibsonRSTM::correct(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), Foam::symm(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
yx() [1/2]
const Cmpt & yx () const inline
Definition at line 181 of file TensorI.H.
Referenced by Foam::cof(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), Foam::symm(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
yy() [1/2]
const Cmpt & yy () const inline
Definition at line 188 of file TensorI.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), Foam::cof(), molecule::constantProperties::constantProperties(), Foam::det(), Foam::diag(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), triad::sortxyz(), Foam::symm(), Foam::tr(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
yz() [1/2]
const Cmpt & yz () const inline
Definition at line 195 of file TensorI.H.
Referenced by Foam::cof(), LRR::correct(), LaunderGibsonRSTM::correct(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), Foam::symm(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
zx() [1/2]
const Cmpt & zx () const inline
Definition at line 202 of file TensorI.H.
Referenced by Foam::cof(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), Foam::symm(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
zy() [1/2]
const Cmpt & zy () const inline
Definition at line 209 of file TensorI.H.
Referenced by Foam::cof(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), Foam::symm(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
zz() [1/2]
const Cmpt & zz () const inline
Definition at line 216 of file TensorI.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), Foam::cof(), molecule::constantProperties::constantProperties(), Foam::det(), Foam::diag(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), triad::sortxyz(), Foam::symm(), Foam::tr(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
xx() [2/2]
Cmpt & xx () inline
Definition at line 223 of file TensorI.H.
xy() [2/2]
Cmpt & xy () inline
Definition at line 230 of file TensorI.H.
xz() [2/2]
Cmpt & xz () inline
Definition at line 237 of file TensorI.H.
yx() [2/2]
Cmpt & yx () inline
Definition at line 244 of file TensorI.H.
yy() [2/2]
Cmpt & yy () inline
Definition at line 251 of file TensorI.H.
yz() [2/2]
Cmpt & yz () inline
Definition at line 258 of file TensorI.H.
zx() [2/2]
Cmpt & zx () inline
Definition at line 265 of file TensorI.H.
zy() [2/2]
Cmpt & zy () inline
Definition at line 272 of file TensorI.H.
zz() [2/2]
Cmpt & zz () inline
Definition at line 279 of file TensorI.H.
x()
Vector< Cmpt > x () const inline
Definition at line 121 of file TensorI.H.
Referenced by molecule::constantProperties::constantProperties(), STARCDCoordinateRotation::e1(), EulerCoordinateRotation::e1(), axesRotation::e1(), triad::operator=(), and triad::triad().
y()
Vector< Cmpt > y () const inline
Definition at line 128 of file TensorI.H.
Referenced by molecule::constantProperties::constantProperties(), STARCDCoordinateRotation::e2(), EulerCoordinateRotation::e2(), axesRotation::e2(), triad::operator=(), and triad::triad().
z()
Vector< Cmpt > z () const inline
Definition at line 135 of file TensorI.H.
Referenced by molecule::constantProperties::constantProperties(), STARCDCoordinateRotation::e3(), EulerCoordinateRotation::e3(), axesRotation::e3(), triad::operator=(), and triad::triad().
vectorComponent()
Vector< Cmpt > vectorComponent (const direction cmpt) const inline
Definition at line 142 of file TensorI.H.
T()
Tensor< Cmpt > T () const inline
Transpose.
Definition at line 286 of file TensorI.H.
Referenced by cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), Foam::inv(), vectorTensorTransform::invTransformPosition(), molecule::move(), mapDistribute::transform::operator()(), transformOp< PrimitivePatchType, Type, TrackingData >::operator()(), sixDoFRigidBodyMotion::transform(), and triad::triad().
operator=() [1/3]
void operator= (const SphericalTensor< Cmpt > & st) inline
Assign to a SphericalTensor.
Definition at line 300 of file TensorI.H.
operator=() [2/3]
void operator= (const SymmTensor< Cmpt > & st) inline
Assign to a SymmTensor.
Definition at line 309 of file TensorI.H.
operator=() [3/3]
void operator= (const Vector< Vector< Cmpt > > & tr) inline
Assign to a triad.
Definition at line 318 of file TensorI.H.
Member Data Documentation
typeName
const char *const typeName = "labelTensor" static
Definition at line 77 of file Tensor.H.
componentNames
const char * componentNames static
Initial value:
=
    {
        "xx", "xy", "xz",
        "yx", "yy", "yz",
        "zx", "zy", "zz"
    }
Definition at line 78 of file Tensor.H.
zero
const Foam::labelTensor zero static
Definition at line 80 of file Tensor.H.
one
const Foam::labelTensor one static
Definition at line 81 of file Tensor.H.
max
const Tensor max static
Definition at line 82 of file Tensor.H.
min
const Tensor min static
Definition at line 83 of file Tensor.H.
I
const Tensor I static
Definition at line 84 of file Tensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/complex/complexI.H
src/OpenFOAM/primitives/Tensor/Tensor.H
src/OpenFOAM/primitives/Tensor/labelTensor/labelTensor.C
src/OpenFOAM/primitives/Tensor/TensorI.H