OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CompatibilityConstant< Type > Class Template Reference
Templated basic entry that holds a constant value for backwards compatibility (when DataEntry type is not present)
Public Member Functions
TypeName ("CompatibilityConstant")
CompatibilityConstant (const word &entryName, const dictionary &dict)
Construct from entry name and Istream.
CompatibilityConstant (const CompatibilityConstant< Type > &cnst)
Copy constructor.
virtual tmp< DataEntry< Type > > clone () const
Construct and return a clone.
virtual ~CompatibilityConstant ()
Destructor.
Type value (const scalar) const
Return constant value.
Type integrate (const scalar x1, const scalar x2) const
Integrate between two values.
dimensioned< Type > dimValue (const scalar) const
Return dimensioned constant value.
dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two values and return dimensioned type.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from DataEntry< Type >
TypeName ("DataEntry") declareRunTimeSelectionTable(autoPtr
Runtime type information.
DataEntry (const word &entryName)
Construct from entry name.
DataEntry (const DataEntry< Type > &de)
Copy constructor.
virtual ~DataEntry ()
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual tmp< Field< dimensioned< Type > > > dimValue (const scalarField &x) const
Return dimensioned type as a function of (scalar)
virtual tmp< Field< dimensioned< Type > > > dimIntegrate (const scalarField &x1, const scalarField &x2) const
Integrate between two scalar fields and return a field of.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Friends
Ostream & operator (Ostream &os, const CompatibilityConstant< Type > &cnst)
Ostream Operator.
Additional Inherited Members
Static Public Member Functions inherited from DataEntry< Type >
static autoPtr< DataEntry< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from DataEntry< Type >
DataEntry
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Attributes inherited from DataEntry< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::CompatibilityConstant< Type >
Templated basic entry that holds a constant value for backwards compatibility (when DataEntry type is not present)
Usage - for entry <entryName> having the value
:
    <entryName>    <value>
Source files
CompatibilityConstant.H
CompatibilityConstant.C
Definition at line 52 of file CompatibilityConstant.H.
Constructor & Destructor Documentation
CompatibilityConstant() [1/2]
CompatibilityConstant (const word & entryName, const dictionary & dict)
Construct from entry name and Istream.
Definition at line 32 of file CompatibilityConstant.C.
References dictionary::lookup().
CompatibilityConstant() [2/2]
CompatibilityConstant (const CompatibilityConstant< Type > & cnst)
Copy constructor.
Definition at line 64 of file CompatibilityConstant.C.
~CompatibilityConstant()
~CompatibilityConstant () virtual
Destructor.
Definition at line 77 of file CompatibilityConstant.C.
Referenced by CompatibilityConstant< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("CompatibilityConstant< Type >")
clone()
virtual tmp<DataEntry<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from DataEntry< Type >.
Definition at line 96 of file CompatibilityConstant.H.
References CompatibilityConstant< Type >::dimIntegrate(), CompatibilityConstant< Type >::dimValue(), CompatibilityConstant< Type >::integrate(), CompatibilityConstant< Type >::value(), CompatibilityConstant< Type >::writeData(), and CompatibilityConstant< Type >::~CompatibilityConstant().
value()
Type value (const scalar x) const virtual
Return constant value.
Reimplemented from DataEntry< Type >.
Definition at line 84 of file CompatibilityConstant.C.
References CompatibilityConstant< Type >::integrate().
Referenced by CompatibilityConstant< Type >::clone().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two values.
Reimplemented from DataEntry< Type >.
Definition at line 92 of file CompatibilityConstant.C.
References CompatibilityConstant< Type >::dimValue().
Referenced by CompatibilityConstant< Type >::clone(), and CompatibilityConstant< Type >::value().
dimValue()
Foam::dimensioned< Type > dimValue (const scalar x) const virtual
Return dimensioned constant value.
Reimplemented from DataEntry< Type >.
Definition at line 103 of file CompatibilityConstant.C.
References CompatibilityConstant< Type >::dimIntegrate().
Referenced by CompatibilityConstant< Type >::clone(), and CompatibilityConstant< Type >::integrate().
dimIntegrate()
Foam::dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const virtual
Integrate between two values and return dimensioned type.
Reimplemented from DataEntry< Type >.
Definition at line 111 of file CompatibilityConstant.C.
Referenced by CompatibilityConstant< Type >::clone(), and CompatibilityConstant< Type >::dimValue().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from DataEntry< Type >.
Definition at line 63 of file CompatibilityConstantIO.C.
References Foam::nl, and Ostream::writeKeyword().
Referenced by CompatibilityConstant< Type >::clone().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const CompatibilityConstant< Type > & cnst) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/CompatibilityConstant/CompatibilityConstant.H
src/OpenFOAM/primitives/functions/DataEntry/CompatibilityConstant/CompatibilityConstant.C
src/OpenFOAM/primitives/functions/DataEntry/CompatibilityConstant/CompatibilityConstantIO.C