OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DataEntry< Type > Class Template Reference
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
Public Member Functions
TypeName ("DataEntry") declareRunTimeSelectionTable(autoPtr
Runtime type information.
DataEntry (const word &entryName)
Construct from entry name.
DataEntry (const DataEntry< Type > &de)
Copy constructor.
virtual tmp< DataEntry< Type > > clone () const
Construct and return a clone.
virtual ~DataEntry ()
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual dimensioned< Type > dimValue (const scalar x) const
Return dimensioned type.
virtual tmp< Field< dimensioned< Type > > > dimValue (const scalarField &x) const
Return dimensioned type as a function of (scalar)
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two scalars and return a dimensioned type.
virtual tmp< Field< dimensioned< Type > > > dimIntegrate (const scalarField &x1, const scalarField &x2) const
Integrate between two scalar fields and return a field of.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static autoPtr< DataEntry< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes
DataEntry
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Attributes
const word name_
Name of entry.
Friends
Ostream & operator (Ostream &os, const DataEntry< Type > &de)
Ostream Operator.
Detailed Description
template<class Type>
class Foam::DataEntry< Type >
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
Source files
DataEntry.H
DataEntry.C
DataEntryNew.C
Definition at line 52 of file DataEntry.H.
Constructor & Destructor Documentation
DataEntry() [1/2]
DataEntry (const word & entryName)
Construct from entry name.
DataEntry() [2/2]
DataEntry (const DataEntry< Type > & de)
Copy constructor.
~DataEntry()
~DataEntry () virtual
Destructor.
Definition at line 50 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone().
Member Function Documentation
TypeName()
TypeName ("DataEntry< Type >")
Runtime type information.
Declare runtime constructor selection table
clone()
virtual tmp<DataEntry<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented in CSV< Type >, TableFile< Type >, polynomial, CompatibilityConstant< Type >, Table< Type >, and Constant< Type >.
Definition at line 112 of file DataEntry.H.
New()
Foam::autoPtr< Foam::DataEntry< Type > > New (const word & entryName, const dictionary & dict) static
Selector.
Definition at line 32 of file DataEntryNew.C.
Referenced by DataEntry< Foam::Vector >::clone(), fanFvPatchField< Type >::fanFvPatchField(), and setTimeStepFunctionObject::read().
name()
const Foam::word & name () const
Return the name of the entry.
Definition at line 57 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone().
convertTimeBase()
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented in CSV< Type >, TableFile< Type >, polynomial, and Table< Type >.
Definition at line 64 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone().
value() [1/2]
Type value (const scalar x) const virtual
Return value as a function of (scalar) independent variable.
Reimplemented in CSV< Type >, TableFile< Type >, polynomial, Table< Type >, CompatibilityConstant< Type >, and Constant< Type >.
Definition at line 71 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone(), and DataEntry< Foam::Vector >::integrate().
value() [2/2]
Foam::tmp< Foam::Field< Type > > value (const scalarField & x) const virtual
Return value as a function of (scalar) independent variable.
Definition at line 97 of file DataEntry.C.
integrate() [1/2]
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented in CSV< Type >, TableFile< Type >, polynomial, Table< Type >, CompatibilityConstant< Type >, and Constant< Type >.
Definition at line 80 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone(), and DataEntry< Foam::Vector >::value().
integrate() [2/2]
Foam::tmp< Foam::Field< Type > > integrate (const scalarField & x1, const scalarField & x2) const virtual
Integrate between two (scalar) values.
Definition at line 114 of file DataEntry.C.
dimValue() [1/2]
Foam::dimensioned< Type > dimValue (const scalar x) const virtual
Return dimensioned type.
Reimplemented in CSV< Type >, TableFile< Type >, polynomial, Table< Type >, CompatibilityConstant< Type >, and Constant< Type >.
Definition at line 132 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone(), and DataEntry< Foam::Vector >::dimIntegrate().
dimValue() [2/2]
Foam::tmp< Foam::Field< Foam::dimensioned< Type > > > dimValue (const scalarField & x) const virtual
Return dimensioned type as a function of (scalar)
Definition at line 167 of file DataEntry.C.
dimIntegrate() [1/2]
Foam::dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const virtual
Integrate between two scalars and return a dimensioned type.
Reimplemented in CSV< Type >, polynomial, CompatibilityConstant< Type >, and Constant< Type >.
Definition at line 146 of file DataEntry.C.
Referenced by DataEntry< Foam::Vector >::clone(), and DataEntry< Foam::Vector >::dimValue().
dimIntegrate() [2/2]
Foam::tmp< Foam::Field< Foam::dimensioned< Type > > > dimIntegrate (const scalarField & x1, const scalarField & x2) const virtual
Integrate between two scalar fields and return a field of.
dimensioned type
Definition at line 194 of file DataEntry.C.
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented in CSV< Type >, TableFile< Type >, Table< Type >, polynomial, CompatibilityConstant< Type >, and Constant< Type >.
Definition at line 50 of file DataEntryIO.C.
Referenced by DataEntry< Foam::Vector >::clone(), and polynomial::writeData().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const DataEntry< Type > & de) friend
Ostream Operator.
Member Data Documentation
name_
const word name_ protected
Name of entry.
Definition at line 81 of file DataEntry.H.
Referenced by DataEntry< Foam::Vector >::name().
DataEntry
DataEntry
Definition at line 93 of file DataEntry.H.
dictionary
dictionary
Definition at line 93 of file DataEntry.H.
entryName [1/2]
const word& entryName
Definition at line 93 of file DataEntry.H.
Referenced by DataEntry< Foam::Vector >::clone().
dict [1/2]
const word const dictionary& dict
Definition at line 93 of file DataEntry.H.
Referenced by DataEntry< Foam::Vector >::clone().
entryName [2/2]
const word const dictionary entryName
Definition at line 93 of file DataEntry.H.
dict [2/2]
const word const dictionary dict
Definition at line 93 of file DataEntry.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/DataEntry/DataEntry.H
src/OpenFOAM/primitives/functions/DataEntry/DataEntry/DataEntry.C
src/OpenFOAM/primitives/functions/DataEntry/DataEntry/DataEntryIO.C
src/OpenFOAM/primitives/functions/DataEntry/DataEntry/DataEntryNew.C