OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vectorTensorTransform Class Reference
Vector-tensor class used to perform translations and rotations in 3D space.
Public Member Functions
vectorTensorTransform ()
Construct null.
vectorTensorTransform (const vector &t, const tensor &R, bool hasR=true)
Construct given a translation vector, rotation tensor and.
vectorTensorTransform (const vector &t)
Construct a pure translation vectorTensorTransform given a.
vectorTensorTransform (const tensor &R)
Construct a pure rotation vectorTensorTransform given a.
vectorTensorTransform (Istream &)
Construct from Istream.
const vector & t () const
const tensor & R () const
bool hasR () const
vector & t ()
tensor & R ()
vector transformPosition (const vector &v) const
Transform the given position.
pointField transformPosition (const pointField &pts) const
Transform the given pointField.
vector invTransformPosition (const vector &v) const
Inverse transform the given position.
pointField invTransformPosition (const pointField &pts) const
Inverse transform the given pointField.
template<class Type >
tmp< Field< Type > > transform (const Field< Type > &) const
Transform the given field.
void operator= (const vectorTensorTransform &)
void operator &= (const vectorTensorTransform &)
void operator= (const vector &)
void operator+= (const vector &)
void operator-= (const vector &)
void operator= (const tensor &)
void operator &= (const tensor &)
template<>
Foam::tmp< Foam::Field< bool > > transform (const Field< bool > &fld) const
template<>
Foam::tmp< Foam::Field< Foam::label > > transform (const Field< label > &fld) const
template<>
Foam::tmp< Foam::Field< Foam::scalar > > transform (const Field< scalar > &fld) const
template<>
tmp< Field< bool > > transform (const Field< bool > &) const
Template specialisations.
template<>
tmp< Field< label > > transform (const Field< label > &) const
template<>
tmp< Field< scalar > > transform (const Field< scalar > &) const
template<class Type >
Foam::tmp< Foam::Field< Type > > transform (const Field< Type > &fld) const
Static Public Attributes
static const char *const typeName
static const vectorTensorTransform zero
static const vectorTensorTransform I
Friends
Istream & operator>> (Istream &is, vectorTensorTransform &)
Ostream & operator<< (Ostream &os, const vectorTensorTransform &)
Detailed Description
Vector-tensor class used to perform translations and rotations in 3D space.
Source files
vectorTensorTransform.H
vectorTensorTransformI.H
vectorTensorTransform.C
vectorTensorTransformTemplates.C
Definition at line 61 of file vectorTensorTransform.H.
Constructor & Destructor Documentation
vectorTensorTransform() [1/5]
vectorTensorTransform () inline
Construct null.
Definition at line 28 of file vectorTensorTransformI.H.
Referenced by Foam::inv(), Foam::operator+(), and Foam::operator-().
vectorTensorTransform() [2/5]
vectorTensorTransform (const vector & t, const tensor & R, bool hasR = true) inline
Construct given a translation vector, rotation tensor and.
hasR bool
Definition at line 37 of file vectorTensorTransformI.H.
vectorTensorTransform() [3/5]
vectorTensorTransform (const vector & t) inline explicit
Construct a pure translation vectorTensorTransform given a.
translation vector
Definition at line 49 of file vectorTensorTransformI.H.
vectorTensorTransform() [4/5]
vectorTensorTransform (const tensor & R) inline explicit
Construct a pure rotation vectorTensorTransform given a.
rotation tensor
Definition at line 57 of file vectorTensorTransformI.H.
vectorTensorTransform() [5/5]
vectorTensorTransform (Istream & is)
Construct from Istream.
Definition at line 53 of file vectorTensorTransform.C.
Member Function Documentation
t() [1/2]
const Foam::vector & t () const inline
Definition at line 67 of file vectorTensorTransformI.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), Foam::contiguous< vectorTensorTransform >(), globalIndexAndTransform::globalIndexAndTransform(), Foam::inv(), vectorTensorTransform::invTransformPosition(), Foam::name(), Foam::operator+(), vectorTensorTransform::operator+=(), Foam::operator-(), vectorTensorTransform::operator-=(), Foam::operator<<(), vectorTensorTransform::operator=(), Foam::operator==(), and vectorTensorTransform::transformPosition().
R() [1/2]
const Foam::tensor & R () const inline
Definition at line 73 of file vectorTensorTransformI.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), globalIndexAndTransform::globalIndexAndTransform(), Foam::inv(), vectorTensorTransform::invTransformPosition(), Foam::name(), mapDistribute::transform::operator()(), transformOp< PrimitivePatchType, Type, TrackingData >::operator()(), Foam::operator+(), Foam::operator-(), Foam::operator<<(), vectorTensorTransform::operator=(), Foam::operator==(), and vectorTensorTransform::transformPosition().
hasR()
bool hasR () const inline
Definition at line 79 of file vectorTensorTransformI.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), globalIndexAndTransform::globalIndexAndTransform(), Foam::inv(), Foam::operator+(), Foam::operator-(), and Foam::operator<<().
t() [2/2]
Foam::vector & t () inline
Definition at line 85 of file vectorTensorTransformI.H.
R() [2/2]
Foam::tensor & R () inline
Definition at line 91 of file vectorTensorTransformI.H.
References vectorTensorTransform::transformPosition().
transformPosition() [1/2]
Foam::vector transformPosition (const vector & v) const inline
Transform the given position.
Definition at line 103 of file vectorTensorTransformI.H.
References vectorTensorTransform::R(), and vectorTensorTransform::t().
Referenced by mapDistribute::transformPosition::operator()(), and vectorTensorTransform::R().
transformPosition() [2/2]
Foam::pointField transformPosition (const pointField & pts) const inline
Transform the given pointField.
Definition at line 119 of file vectorTensorTransformI.H.
References vectorTensorTransform::invTransformPosition(), vectorTensorTransform::R(), and vectorTensorTransform::t().
invTransformPosition() [1/2]
Foam::vector invTransformPosition (const vector & v) const inline
Inverse transform the given position.
Definition at line 138 of file vectorTensorTransformI.H.
References vectorTensorTransform::R(), Foam::T(), and vectorTensorTransform::t().
Referenced by mapDistribute::transformPosition::operator()(), and vectorTensorTransform::transformPosition().
invTransformPosition() [2/2]
Foam::pointField invTransformPosition (const pointField & pts) const inline
Inverse transform the given pointField.
Definition at line 154 of file vectorTensorTransformI.H.
References vectorTensorTransform::R(), vectorTensorTransform::t(), and Tensor< Cmpt >::T().
transform() [1/8]
tmp<Field<Type> > transform (const Field< Type > &) const
Transform the given field.
Referenced by Foam::contiguous< vectorTensorTransform >(), Foam::name(), and vectorTensorTransform::transform().
operator=() [1/3]
void operator= (const vectorTensorTransform & tr) inline
Definition at line 175 of file vectorTensorTransformI.H.
References Foam::tr().
operator &=() [1/2]
void operator&= (const vectorTensorTransform &) inline
Referenced by vectorTensorTransform::operator=().
operator=() [2/3]
void operator= (const vector & t) inline
Definition at line 199 of file vectorTensorTransformI.H.
References vectorTensorTransform::t().
operator+=()
void operator+= (const vector & t) inline
Definition at line 205 of file vectorTensorTransformI.H.
References vectorTensorTransform::t().
operator-=()
void operator-= (const vector & t) inline
Definition at line 211 of file vectorTensorTransformI.H.
References vectorTensorTransform::t().
operator=() [3/3]
void operator= (const tensor & R) inline
Definition at line 217 of file vectorTensorTransformI.H.
References vectorTensorTransform::operator &=(), and vectorTensorTransform::R().
operator &=() [2/2]
void operator&= (const tensor &) inline
transform() [2/8]
Foam::tmp<Foam::Field<bool> > transform (const Field< bool > & fld) const
Definition at line 73 of file vectorTensorTransform.C.
References fld(), and vectorTensorTransform::transform().
transform() [3/8]
Foam::tmp<Foam::Field<Foam::label> > transform (const Field< label > & fld) const
Definition at line 81 of file vectorTensorTransform.C.
References fld(), and vectorTensorTransform::transform().
transform() [4/8]
Foam::tmp<Foam::Field<Foam::scalar> > transform (const Field< scalar > & fld) const
Definition at line 89 of file vectorTensorTransform.C.
References fld().
transform() [5/8]
tmp<Field<bool> > transform (const Field< bool > &) const
Template specialisations.
transform() [6/8]
tmp<Field<label> > transform (const Field< label > &) const
transform() [7/8]
tmp<Field<scalar> > transform (const Field< scalar > &) const
transform() [8/8]
Foam::tmp<Foam::Field<Type> > transform (const Field< Type > & fld) const
Definition at line 30 of file vectorTensorTransformTemplates.C.
References fld(), and R.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & is, vectorTensorTransform &) friend
operator<<
Ostream& operator<< (Ostream & os, const vectorTensorTransform &) friend
Member Data Documentation
typeName
const char *const typeName static
Initial value:
=
    "vectorTensorTransform"
Definition at line 81 of file vectorTensorTransform.H.
zero
const Foam::vectorTensorTransform zero static
Definition at line 83 of file vectorTensorTransform.H.
I
const Foam::vectorTensorTransform I static
Definition at line 85 of file vectorTensorTransform.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransform.H
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransform.C
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransformI.H
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransformTemplates.C