OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ProcessorTopology< Container, ProcPatch > Class Template Reference
Determines processor-processor connection. After instantiation contains on all processors the processor-processor connection table.
Public Member Functions
ProcessorTopology (const Container &patches, const label comm)
Construct from boundaryMesh.
const labelList & procPatchMap () const
from neighbour processor to index in boundaryMesh. Local information
const lduSchedule & patchSchedule () const
Order in which the patches should be initialised/evaluated.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const List< T > &)
Copy constructor.
List (const Xfer< List< T > > &)
Construct by transferring the parameter contents.
List (List< T > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< T > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const T &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< T > &)
Assign elements to those from UList.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static lduSchedule nonBlockingSchedule (const Container &patches)
Calculate non-blocking (i.e. unscheduled) schedule.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Container, class ProcPatch>
class Foam::ProcessorTopology< Container, ProcPatch >
Determines processor-processor connection. After instantiation contains on all processors the processor-processor connection table.
this[procI] gives the list of neighbouring processors.
TODO: This does not currently correctly support multiple processor patches connecting two processors.
Source files
ProcessorTopology.H
ProcessorTopology.C
Definition at line 56 of file ProcessorTopology.H.
Constructor & Destructor Documentation
ProcessorTopology()
ProcessorTopology (const Container & patches, const label comm)
Construct from boundaryMesh.
Definition at line 109 of file ProcessorTopology.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), forAll, ProcessorTopology< Container, ProcPatch >::nonBlockingSchedule(), patchi, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink().
Member Function Documentation
procPatchMap()
const labelList& procPatchMap () const inline
from neighbour processor to index in boundaryMesh. Local information
(so not same over all processors)
Definition at line 92 of file ProcessorTopology.H.
patchSchedule()
const lduSchedule& patchSchedule () const inline
Order in which the patches should be initialised/evaluated.
corresponding to the schedule
Definition at line 99 of file ProcessorTopology.H.
Referenced by polyBoundaryMesh::clearAddressing(), pointBoundaryMesh::findIndices(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), pointBoundaryMesh::updateMesh(), and polyBoundaryMesh::updateMesh().
nonBlockingSchedule()
Foam::lduSchedule nonBlockingSchedule (const Container & patches) static
Calculate non-blocking (i.e. unscheduled) schedule.
Definition at line 223 of file ProcessorTopology.C.
References forAll, and patchi.
Referenced by ProcessorTopology< Container, ProcPatch >::ProcessorTopology().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/ProcessorTopology/ProcessorTopology.H
src/OpenFOAM/meshes/ProcessorTopology/ProcessorTopology.C