OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
TableBase< Type > Class Template Reference
Base class for table with bounds handling, interpolation and integration.
Public Types
enum boundsHandling { ERROR, WARN, CLAMP, REPEAT }
Enumeration for handling out-of-bound values.
Public Member Functions
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual dimensioned< Type > dimValue (const scalar x) const
Return dimensioned constant value.
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two values and return dimensioned type.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeData (Ostream &os) const
Write all table data in dictionary format.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format. Used for non-inline.
Protected Member Functions
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)
Disallow default bitwise assignment.
Protected Attributes
const word name_
Table name.
const boundsHandling boundsHandling_
Enumeration for handling out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
dimensionSet dimensions_
The dimension set.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Friends
Ostream & operator (Ostream &os, const TableBase< Type > &tbl)
Ostream Operator.
Detailed Description
template<class Type>
class Foam::TableBase< Type >
Base class for table with bounds handling, interpolation and integration.
Source files
TableBase.H
TableBase.C
Definition at line 47 of file TableBase.H.
Member Enumeration Documentation
boundsHandling
enum boundsHandling
Enumeration for handling out-of-bound values.
Enumerator
ERROR
Exit with a FatalError
WARN
Issue warning and clamp value (default)
CLAMP
Clamp value to the start/end value
REPEAT
Treat as a repeating list
Definition at line 70 of file TableBase.H.
Constructor & Destructor Documentation
TableBase() [1/2]
TableBase (const word & name, const dictionary & dict)
Construct from dictionary - note table is not populated.
Definition at line 58 of file TableBase.C.
TableBase() [2/2]
TableBase (const TableBase< Type > & tbl)
Copy constructor. Note: steals interpolator, tableSamples.
Definition at line 78 of file TableBase.C.
~TableBase()
~TableBase () virtual
Destructor.
Definition at line 93 of file TableBase.C.
References TableBase< Type >::boundsHandlingToWord().
Member Function Documentation
interpolator()
const Foam::interpolationWeights & interpolator () const protected
Return (demand driven) interpolator.
Definition at line 33 of file TableBase.C.
References UList< T >::first(), forAll, and scalarField().
Referenced by TableBase< Type >::integrate(), and TableBase< Type >::value().
operator=()
void operator= (const TableBase< Type > &) protected
Disallow default bitwise assignment.
boundsHandlingToWord()
Foam::word boundsHandlingToWord (const boundsHandling & bound) const
Return the out-of-bounds handling as a word.
Definition at line 101 of file TableBase.C.
References TableBase< Type >::CLAMP, TableBase< Type >::ERROR, TableBase< Type >::REPEAT, TableBase< Type >::WARN, and TableBase< Type >::wordToBoundsHandling().
Referenced by TableBase< Type >::~TableBase().
wordToBoundsHandling()
Foam::TableBase< Type >::boundsHandling wordToBoundsHandling (const word & bound) const
Return the out-of-bounds handling as an enumeration.
Definition at line 138 of file TableBase.C.
References TableBase< Type >::CLAMP, Foam::endl(), TableBase< Type >::ERROR, TableBase< Type >::outOfBounds(), TableBase< Type >::REPEAT, TableBase< Type >::WARN, and WarningIn.
Referenced by TableBase< Type >::boundsHandlingToWord().
outOfBounds()
Foam::TableBase< Type >::boundsHandling outOfBounds (const boundsHandling & bound)
Set the out-of-bounds handling from enum, return previous setting.
Definition at line 172 of file TableBase.C.
References Foam::bound(), and TableBase< Type >::boundsHandling_.
Referenced by TableBase< Type >::wordToBoundsHandling().
check()
void check () const
Check the table for size and consistency.
Definition at line 184 of file TableBase.C.
References TableBase< Type >::checkMinBounds(), Foam::exit(), Foam::FatalError, FatalErrorIn, UList< T >::first(), n, TableBase< Type >::name_, Foam::nl, List< T >::size(), and TableBase< Type >::table_.
Referenced by CSV< Type >::CSV(), Table< Type >::Table(), and TableFile< Type >::TableFile().
checkMinBounds()
bool checkMinBounds (const scalar x, scalar & xDash) const
Check minimum table bounds.
Definition at line 214 of file TableBase.C.
References TableBase< Type >::boundsHandling_, TableBase< Type >::checkMaxBounds(), TableBase< Type >::CLAMP, Foam::endl(), TableBase< Type >::ERROR, Foam::exit(), Foam::FatalError, FatalErrorIn, UList< T >::first(), UList< T >::last(), Foam::nl, TableBase< Type >::REPEAT, TableBase< Type >::table_, TableBase< Type >::WARN, WarningIn, and TableBase< Type >::x().
Referenced by TableBase< Type >::check(), and TableBase< Type >::value().
checkMaxBounds()
bool checkMaxBounds (const scalar x, scalar & xDash) const
Check maximum table bounds.
Definition at line 276 of file TableBase.C.
References TableBase< Type >::boundsHandling_, TableBase< Type >::CLAMP, Foam::endl(), TableBase< Type >::ERROR, Foam::exit(), Foam::FatalError, FatalErrorIn, UList< T >::first(), UList< T >::last(), Foam::nl, TableBase< Type >::REPEAT, TableBase< Type >::table_, TableBase< Type >::WARN, WarningIn, and TableBase< Type >::x().
Referenced by TableBase< Type >::checkMinBounds(), and TableBase< Type >::value().
convertTimeBase()
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented in CSV< Type >, TableFile< Type >, and Table< Type >.
Definition at line 337 of file TableBase.C.
References UList< T >::first(), forAll, TableBase< Type >::interpolatorPtr_, TableBase< Type >::table_, TableBase< Type >::tableSamplesPtr_, TimeState::userTimeToTime(), and TableBase< Type >::value().
Referenced by Table< Type >::convertTimeBase(), TableFile< Type >::convertTimeBase(), and CSV< Type >::convertTimeBase().
value()
Type value (const scalar x) const virtual
Return Table value.
Reimplemented in CSV< Type >, TableFile< Type >, and Table< Type >.
Definition at line 351 of file TableBase.C.
References TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), TableBase< Type >::currentIndices_, TableBase< Type >::currentWeights_, TableBase< Type >::interpolator(), UList< T >::last(), List< T >::size(), TableBase< Type >::table_, interpolationWeights::valueWeights(), and TableBase< Type >::x().
Referenced by TableBase< Type >::convertTimeBase(), TableBase< Type >::dimValue(), Table< Type >::value(), TableFile< Type >::value(), and CSV< Type >::value().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented in CSV< Type >, TableFile< Type >, and Table< Type >.
Definition at line 379 of file TableBase.C.
References TableBase< Type >::currentIndices_, TableBase< Type >::currentWeights_, TableBase< Type >::dimValue(), interpolationWeights::integrationWeights(), TableBase< Type >::interpolator(), List< T >::size(), Foam::sum(), and TableBase< Type >::table_.
Referenced by TableBase< Type >::dimIntegrate(), Table< Type >::integrate(), TableFile< Type >::integrate(), and CSV< Type >::integrate().
dimValue()
Foam::dimensioned< Type > dimValue (const scalar x) const virtual
Return dimensioned constant value.
Reimplemented in CSV< Type >, TableFile< Type >, and Table< Type >.
Definition at line 396 of file TableBase.C.
References TableBase< Type >::dimensions_, TableBase< Type >::dimIntegrate(), and TableBase< Type >::value().
Referenced by Table< Type >::dimValue(), TableFile< Type >::dimValue(), CSV< Type >::dimValue(), and TableBase< Type >::integrate().
dimIntegrate()
Foam::dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const virtual
Integrate between two values and return dimensioned type.
Reimplemented in CSV< Type >.
Definition at line 404 of file TableBase.C.
References TableBase< Type >::dimensions_, and TableBase< Type >::integrate().
Referenced by Table< Type >::dimIntegrate(), TableFile< Type >::dimIntegrate(), CSV< Type >::dimIntegrate(), and TableBase< Type >::dimValue().
x()
Foam::tmp< Foam::scalarField > x () const virtual
Return the reference values.
Definition at line 418 of file TableBase.C.
References UList< T >::first(), fld(), forAll, List< T >::size(), and TableBase< Type >::table_.
Referenced by TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), and TableBase< Type >::value().
y()
Foam::tmp< Foam::Field< Type > > y () const virtual
Return the dependent values.
Definition at line 433 of file TableBase.C.
References fld(), forAll, List< T >::size(), and TableBase< Type >::table_.
writeData()
void writeData (Ostream & os) const virtual
Write all table data in dictionary format.
Reimplemented in CSV< Type >, TableFile< Type >, and Table< Type >.
Definition at line 61 of file TableBaseIO.C.
References Foam::indent(), and Foam::nl.
writeEntries()
void writeEntries (Ostream & os) const virtual
Write keywords only in dictionary format. Used for non-inline.
table types
Definition at line 69 of file TableBaseIO.C.
References Foam::nl, and Ostream::writeKeyword().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const TableBase< Type > & tbl) friend
Ostream Operator.
Member Data Documentation
name_
const word name_ protected
Table name.
Definition at line 84 of file TableBase.H.
Referenced by TableBase< Type >::check().
boundsHandling_
const boundsHandling boundsHandling_ protected
Enumeration for handling out-of-bound values.
Definition at line 87 of file TableBase.H.
Referenced by TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), and TableBase< Type >::outOfBounds().
interpolationScheme_
const word interpolationScheme_ protected
Interpolation type.
Definition at line 90 of file TableBase.H.
table_
List<Tuple2<scalar, Type> > table_ protected
Table data.
Definition at line 93 of file TableBase.H.
Referenced by TableBase< Type >::check(), TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), TableBase< Type >::convertTimeBase(), TableBase< Type >::integrate(), Table< Type >::Table(), TableFile< Type >::TableFile(), TableBase< Type >::value(), TableBase< Type >::x(), and TableBase< Type >::y().
dimensions_
dimensionSet dimensions_ protected
The dimension set.
Definition at line 96 of file TableBase.H.
Referenced by TableBase< Type >::dimIntegrate(), TableBase< Type >::dimValue(), Table< Type >::Table(), and TableFile< Type >::TableFile().
tableSamplesPtr_
autoPtr<scalarField> tableSamplesPtr_ mutable protected
Extracted values.
Definition at line 99 of file TableBase.H.
Referenced by TableBase< Type >::convertTimeBase().
interpolatorPtr_
autoPtr<interpolationWeights> interpolatorPtr_ mutable protected
Interpolator method.
Definition at line 102 of file TableBase.H.
Referenced by TableBase< Type >::convertTimeBase().
currentIndices_
labelList currentIndices_ mutable protected
Cached indices and weights.
Definition at line 105 of file TableBase.H.
Referenced by TableBase< Type >::integrate(), and TableBase< Type >::value().
currentWeights_
scalarField currentWeights_ mutable protected
Definition at line 107 of file TableBase.H.
Referenced by TableBase< Type >::integrate(), and TableBase< Type >::value().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/Table/TableBase.H
src/OpenFOAM/primitives/functions/DataEntry/Table/TableBase.C
src/OpenFOAM/primitives/functions/DataEntry/Table/TableBaseIO.C