OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Constant< Type > Class Template Reference
Templated basic entry that holds a constant value.
Public Member Functions
TypeName ("constant")
Constant (const word &entryName, const dictionary &dict)
Construct from entry name and Istream.
Constant (const Constant< Type > &cnst)
Copy constructor.
virtual tmp< DataEntry< Type > > clone () const
Construct and return a clone.
virtual ~Constant ()
Destructor.
Type value (const scalar) const
Return constant value.
Type integrate (const scalar x1, const scalar x2) const
Integrate between two values.
dimensioned< Type > dimValue (const scalar) const
Return dimensioned constant value.
dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two values and return dimensioned type.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from DataEntry< Type >
TypeName ("DataEntry") declareRunTimeSelectionTable(autoPtr
Runtime type information.
DataEntry (const word &entryName)
Construct from entry name.
DataEntry (const DataEntry< Type > &de)
Copy constructor.
virtual ~DataEntry ()
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual tmp< Field< dimensioned< Type > > > dimValue (const scalarField &x) const
Return dimensioned type as a function of (scalar)
virtual tmp< Field< dimensioned< Type > > > dimIntegrate (const scalarField &x1, const scalarField &x2) const
Integrate between two scalar fields and return a field of.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Friends
Ostream & operator (Ostream &os, const Constant< Type > &cnst)
Ostream Operator.
Additional Inherited Members
Static Public Member Functions inherited from DataEntry< Type >
static autoPtr< DataEntry< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from DataEntry< Type >
DataEntry
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Attributes inherited from DataEntry< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::Constant< Type >
Templated basic entry that holds a constant value.
Usage - for entry <entryName> having the value
:
    <entryName>    constant  <value>
Source files
Constant.H
Constant.C
Definition at line 51 of file Constant.H.
Constructor & Destructor Documentation
Constant() [1/2]
Constant (const word & entryName, const dictionary & dict)
Construct from entry name and Istream.
Definition at line 31 of file Constant.C.
References token::BEGIN_SQR, token::isWord(), and dictionary::lookup().
Constant() [2/2]
Constant (const Constant< Type > & cnst)
Copy constructor.
Definition at line 59 of file Constant.C.
~Constant()
~Constant () virtual
Destructor.
Definition at line 70 of file Constant.C.
Referenced by Constant< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("constant")
clone()
virtual tmp<DataEntry<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from DataEntry< Type >.
Definition at line 95 of file Constant.H.
References Constant< Type >::dimIntegrate(), Constant< Type >::dimValue(), Constant< Type >::integrate(), Constant< Type >::value(), Constant< Type >::writeData(), and Constant< Type >::~Constant().
value()
Type value (const scalar x) const virtual
Return constant value.
Reimplemented from DataEntry< Type >.
Definition at line 77 of file Constant.C.
Referenced by Constant< Type >::clone().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two values.
Reimplemented from DataEntry< Type >.
Definition at line 84 of file Constant.C.
Referenced by Constant< Type >::clone().
dimValue()
Foam::dimensioned< Type > dimValue (const scalar x) const virtual
Return dimensioned constant value.
Reimplemented from DataEntry< Type >.
Definition at line 91 of file Constant.C.
References Constant< Type >::dimIntegrate().
Referenced by Constant< Type >::clone().
dimIntegrate()
Foam::dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const virtual
Integrate between two values and return dimensioned type.
Reimplemented from DataEntry< Type >.
Definition at line 99 of file Constant.C.
Referenced by Constant< Type >::clone(), and Constant< Type >::dimValue().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from DataEntry< Type >.
Definition at line 63 of file ConstantIO.C.
References Foam::nl, and writeData().
Referenced by Constant< Type >::clone().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const Constant< Type > & cnst) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/Constant/Constant.H
src/OpenFOAM/primitives/functions/DataEntry/Constant/Constant.C
src/OpenFOAM/primitives/functions/DataEntry/Constant/ConstantIO.C