OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
demandDrivenEntry< Type > Class Template Reference
Class for demand-driven dictionary entries.
Public Member Functions
demandDrivenEntry (const dictionary &dict, const Type &value)
Constructors.
demandDrivenEntry (const dictionary &dict, const word &keyword)
Construct from dictionary and keyword.
demandDrivenEntry (const dictionary &dict, const word &keyword, const Type &defaultValue, const bool readIfPresent=true)
Construct from dictionary, keyword and default value.
demandDrivenEntry (const demandDrivenEntry &dde)
Copy constructor.
void initialise () const
Initialise.
const Type & value () const
Return the value.
void setValue (const Type &value)
Set the value.
void reset ()
Reset the demand-driven entry.
Detailed Description
template<class Type>
class Foam::demandDrivenEntry< Type >
Class for demand-driven dictionary entries.
Holds a reference to a dictionary, which is then queried if the value is requested and has not already been cached
Source files
demandDrivenEntry.H
demandDrivenEntry.C
demandDrivenEntryI.H
Definition at line 53 of file demandDrivenEntry.H.
Constructor & Destructor Documentation
demandDrivenEntry() [1/4]
demandDrivenEntry (const dictionary & dict, const Type & value)
Constructors.
Construct from dictionary and value - cannot be re-read
Definition at line 32 of file demandDrivenEntry.C.
Referenced by demandDrivenEntry< bool >::demandDrivenEntry().
demandDrivenEntry() [2/4]
demandDrivenEntry (const dictionary & dict, const word & keyword)
Construct from dictionary and keyword.
Definition at line 46 of file demandDrivenEntry.C.
demandDrivenEntry() [3/4]
demandDrivenEntry (const dictionary & dict, const word & keyword, const Type & defaultValue, const bool readIfPresent = true)
Construct from dictionary, keyword and default value.
Definition at line 60 of file demandDrivenEntry.C.
demandDrivenEntry() [4/4]
demandDrivenEntry (const demandDrivenEntry< Type > & dde)
Copy constructor.
Definition at line 80 of file demandDrivenEntry.C.
Member Function Documentation
initialise()
void initialise () const inline
Initialise.
Definition at line 31 of file demandDrivenEntryI.H.
value()
const Type & value () const inline
Return the value.
Definition at line 42 of file demandDrivenEntryI.H.
Referenced by ReactingParcel< ParcelType >::constantProperties::constantVolume(), ThermoParcel< ParcelType >::constantProperties::Cp0(), ThermoParcel< ParcelType >::constantProperties::epsilon0(), ThermoParcel< ParcelType >::constantProperties::f0(), ReactingMultiphaseParcel< ParcelType >::constantProperties::hRetentionCoeff(), ReactingMultiphaseParcel< ParcelType >::constantProperties::LDevol(), KinematicParcel< ParcelType >::constantProperties::minParcelMass(), SprayParcel< ParcelType >::constantProperties::mu0(), KinematicParcel< ParcelType >::constantProperties::parcelTypeId(), ReactingParcel< ParcelType >::constantProperties::pMin(), CollidingParcel< ParcelType >::constantProperties::poissonsRatio(), KinematicParcel< ParcelType >::constantProperties::rho0(), KinematicParcel< ParcelType >::constantProperties::rhoMin(), SprayParcel< ParcelType >::constantProperties::sigma0(), ThermoParcel< ParcelType >::constantProperties::T0(), ReactingMultiphaseParcel< ParcelType >::constantProperties::TDevol(), ThermoParcel< ParcelType >::constantProperties::TMax(), ThermoParcel< ParcelType >::constantProperties::TMin(), and CollidingParcel< ParcelType >::constantProperties::youngsModulus().
setValue()
void setValue (const Type & value) inline
Set the value.
Definition at line 51 of file demandDrivenEntryI.H.
Referenced by ThermoParcel< ParcelType >::constantProperties::setTMax().
reset()
void reset () inline
Reset the demand-driven entry.
Definition at line 60 of file demandDrivenEntryI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/demandDrivenEntry/demandDrivenEntry.H
src/OpenFOAM/primitives/demandDrivenEntry/demandDrivenEntry.C
src/OpenFOAM/primitives/demandDrivenEntry/demandDrivenEntryI.H