OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Polynomial< PolySize > Class Template Reference
Polynomial templated on size (order):
Public Types
typedef Polynomial< PolySize > polyType
typedef Polynomial< PolySize+1 > intPolyType
Public Types inherited from VectorSpace< Polynomial< PolySize >, scalar, PolySize >
enum
typedef scalar cmptType
Component type.
Public Member Functions
Polynomial ()
Construct null, with all coefficients = 0.0.
Polynomial (const Polynomial &)
Copy constructor.
Polynomial (const scalar coeffs[PolySize])
Construct from C-array of coefficients.
Polynomial (const UList< scalar > &coeffs)
Construct from a list of coefficients.
Polynomial (Istream &)
Construct from Istream.
Polynomial (const word &name, Istream &)
Construct from name and Istream.
bool logActive () const
Return true if the log term is active.
scalar logCoeff () const
Return the log coefficient.
scalar value (const scalar x) const
Return polynomial value.
scalar derivative (const scalar x) const
Return derivative of the polynomial at the given x.
scalar integral (const scalar x1, const scalar x2) const
Return integral between two values.
intPolyType integral (const scalar intConstant=0.0) const
Return integral coefficients.
polyType integralMinus1 (const scalar intConstant=0.0) const
Return integral coefficients when lowest order is -1.
Public Member Functions inherited from VectorSpace< Polynomial< PolySize >, scalar, PolySize >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Polynomial< PolySize >, scalar, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const scalar & component (const direction) const
scalar & component (const direction)
void component (scalar &, const direction) const
void replace (const direction, const scalar &)
const scalar & operator[] (const direction) const
scalar & operator[] (const direction)
void operator= (const VectorSpace< Polynomial< PolySize >, scalar, nCmpt > &)
void operator+= (const VectorSpace< Polynomial< PolySize >, scalar, nCmpt > &)
void operator-= (const VectorSpace< Polynomial< PolySize >, scalar, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Friends
Ostream & operator (Ostream &, const Polynomial &)
Ostream Operator.
Additional Inherited Members
Public Attributes inherited from VectorSpace< Polynomial< PolySize >, scalar, PolySize >
scalar v_ [nCmpt]
The components of this vector space.
Detailed Description
template<int PolySize>
class Foam::Polynomial< PolySize >
Polynomial templated on size (order):
poly = sum(coeff_[i]*x^i) logCoeff*log(x)
where 0 <= i <= N
integer powers, starting at zero
value(x) to evaluate the poly for a given value
derivative(x) returns derivative at value
integral(x1, x2) returns integral between two scalar values
integral() to return a new, integral coeff polynomial
increases the size (order)
integralMinus1() to return a new, integral coeff polynomial where the base poly starts at order -1
Source files
Polynomial.H
Polynomial.C
Definition at line 63 of file Polynomial.H.
Member Typedef Documentation
polyType
typedef Polynomial<PolySize> polyType
Definition at line 97 of file Polynomial.H.
intPolyType
typedef Polynomial<PolySize+1> intPolyType
Definition at line 99 of file Polynomial.H.
Constructor & Destructor Documentation
Polynomial() [1/6]
Polynomial ()
Construct null, with all coefficients = 0.0.
Definition at line 31 of file Polynomial.C.
References VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_.
Polynomial() [2/6]
Polynomial (const Polynomial< PolySize > &)
Copy constructor.
Polynomial() [3/6]
Polynomial (const scalar coeffs[PolySize]) explicit
Construct from C-array of coefficients.
Definition at line 57 of file Polynomial.C.
References VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_.
Polynomial() [4/6]
Polynomial (const UList< scalar > & coeffs) explicit
Construct from a list of coefficients.
Definition at line 71 of file Polynomial.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, UList< T >::size(), and VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_.
Polynomial() [5/6]
Polynomial (Istream & is)
Construct from Istream.
Definition at line 95 of file Polynomial.C.
Polynomial() [6/6]
Polynomial (const word & name, Istream & is)
Construct from name and Istream.
Definition at line 104 of file Polynomial.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, and VectorSpace< Polynomial< PolySize >, scalar, PolySize >::size().
Member Function Documentation
logActive()
bool logActive () const
Return true if the log term is active.
Definition at line 138 of file Polynomial.C.
logCoeff()
Foam::scalar logCoeff () const
Return the log coefficient.
Definition at line 145 of file Polynomial.C.
value()
Foam::scalar value (const scalar x) const
Return polynomial value.
Definition at line 152 of file Polynomial.C.
References Foam::log(), VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_, and x.
derivative()
Foam::scalar derivative (const scalar x) const
Return derivative of the polynomial at the given x.
Definition at line 174 of file Polynomial.C.
References Polynomial< PolySize >::integral(), VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_, and x.
integral() [1/2]
Foam::scalar integral (const scalar x1, const scalar x2) const
Return integral between two values.
Definition at line 202 of file Polynomial.C.
References Foam::log(), and VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_.
Referenced by Polynomial< PolySize >::derivative().
integral() [2/2]
Foam::Polynomial< PolySize >::intPolyType integral (const scalar intConstant = 0.0) const
Return integral coefficients.
Argument becomes zero'th element (constant of integration)
Definition at line 230 of file Polynomial.C.
References forAll, and VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_.
integralMinus1()
Foam::Polynomial< PolySize >::polyType integralMinus1 (const scalar intConstant = 0.0) const
Return integral coefficients when lowest order is -1.
Argument becomes zero'th element (constant of integration)
Definition at line 246 of file Polynomial.C.
References VectorSpace< Polynomial< PolySize >, scalar, PolySize >::v_.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const Polynomial< PolySize > &) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Polynomial/Polynomial.H
src/OpenFOAM/primitives/functions/Polynomial/Polynomial.C