OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
intersection Class Reference
Foam::intersection.
Public Types
enum direction { VECTOR, CONTACT_SPHERE }
enum algorithm { FULL_RAY, HALF_RAY, VISIBLE }
Static Public Member Functions
static scalar planarTol ()
Return planar tolerance.
static scalar setPlanarTol (const scalar t)
Set the planar tolerance, returning the previous value.
Static Public Attributes
static const NamedEnum< direction, 2 > directionNames_
Direction names.
static const NamedEnum< algorithm, 3 > algorithmNames_
Projection algorithm names.
Detailed Description
Foam::intersection.
Source files
intersection.H
intersection.C
Definition at line 49 of file intersection.H.
Member Enumeration Documentation
direction
enum direction
Enumerator
VECTOR
CONTACT_SPHERE
Definition at line 63 of file intersection.H.
algorithm
enum algorithm
Enumerator
FULL_RAY
HALF_RAY
VISIBLE
Definition at line 69 of file intersection.H.
Member Function Documentation
planarTol()
static scalar planarTol () inline static
Return planar tolerance.
Definition at line 85 of file intersection.H.
Referenced by surfaceIntersection::surfaceIntersection().
setPlanarTol()
static scalar setPlanarTol (const scalar t) inline static
Set the planar tolerance, returning the previous value.
Definition at line 91 of file intersection.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by treeDataCell::findIntersectOp::operator()().
Member Data Documentation
directionNames_
const Foam::NamedEnum< Foam::intersection::direction, 2 > directionNames_ static
Direction names.
Definition at line 79 of file intersection.H.
Referenced by NamedEnum< directionType, 3 >::names().
algorithmNames_
const Foam::NamedEnum< Foam::intersection::algorithm, 3 > algorithmNames_ static
Projection algorithm names.
Definition at line 82 of file intersection.H.
Referenced by NamedEnum< directionType, 3 >::names(), and slidingInterface::writeDict().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/triangle/intersection.H
src/OpenFOAM/meshes/primitiveShapes/triangle/intersection.C