OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Random Class Reference
Simple random number generator.
Public Member Functions
Random (const label)
Construct given seed.
int bit ()
scalar scalar01 ()
scalar [0..1] (so including 0,1)
vector vector01 ()
vector with every component scalar01
sphericalTensor sphericalTensor01 ()
sphericalTensor with every component scalar01
symmTensor symmTensor01 ()
symmTensor with every component scalar01
tensor tensor01 ()
tensor with every component scalar01
label integer (const label lower, const label upper)
label [lower..upper]
vector position (const vector &, const vector &)
void randomise (scalar &)
void randomise (vector &)
void randomise (sphericalTensor &)
void randomise (symmTensor &)
void randomise (tensor &)
scalar GaussNormal ()
Return a normal Gaussian randon number.
Detailed Description
Simple random number generator.
Source files
Random.H
Random.C
Definition at line 49 of file Random.H.
Constructor & Destructor Documentation
Random()
Random (const label seed)
Construct given seed.
Definition at line 45 of file Random.C.
References Foam::osRandomSeed().
Member Function Documentation
bit()
int bit ()
Definition at line 60 of file Random.C.
References Foam::osRandomInteger().
scalar01()
scalar scalar01 ()
scalar [0..1] (so including 0,1)
Definition at line 73 of file Random.C.
References Foam::osRandomDouble().
Referenced by Random::GaussNormal(), conformalVoronoiMesh::maxSurfaceProtrusion(), Random::position(), Random::randomise(), triangle< Point, PointRef >::randomPoint(), tetrahedron< Point, PointRef >::randomPoint(), Random::sphericalTensor01(), Random::symmTensor01(), Random::tensor01(), turbGen::U(), and Random::vector01().
vector01()
vector vector01 ()
vector with every component scalar01
Definition at line 79 of file Random.C.
References VectorSpace< Form, Cmpt, nCmpt >::component(), VectorSpace< Vector< Cmpt >, Cmpt, 3 >::nComponents, and Random::scalar01().
Referenced by treeBoundBox::extend(), Random::randomise(), and turbGen::U().
sphericalTensor01()
sphericalTensor sphericalTensor01 ()
sphericalTensor with every component scalar01
Definition at line 91 of file Random.C.
References SphericalTensor< Cmpt >::ii(), and Random::scalar01().
Referenced by Random::randomise().
symmTensor01()
symmTensor symmTensor01 ()
symmTensor with every component scalar01
Definition at line 100 of file Random.C.
References VectorSpace< Form, Cmpt, nCmpt >::component(), VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::nComponents, and Random::scalar01().
Referenced by Random::randomise().
tensor01()
tensor tensor01 ()
tensor with every component scalar01
Definition at line 112 of file Random.C.
References VectorSpace< Form, Cmpt, nCmpt >::component(), VectorSpace< Tensor< scalar >, scalar, 9 >::nComponents, and Random::scalar01().
Referenced by Random::randomise().
integer()
label integer (const label lower, const label upper)
label [lower..upper]
Definition at line 124 of file Random.C.
References Foam::osRandomInteger().
Referenced by randomRenumber::renumber().
position()
vector position (const vector & start, const vector & end)
Definition at line 130 of file Random.C.
References VectorSpace< Form, Cmpt, nCmpt >::component(), VectorSpace< Vector< Cmpt >, Cmpt, 3 >::nComponents, and Random::scalar01().
randomise() [1/5]
void randomise (scalar & s)
Definition at line 144 of file Random.C.
References Random::scalar01().
Referenced by randomise::writeRandomField().
randomise() [2/5]
void randomise (vector & v)
Definition at line 150 of file Random.C.
References Random::vector01().
randomise() [3/5]
void randomise (sphericalTensor & st)
Definition at line 156 of file Random.C.
References Random::sphericalTensor01().
randomise() [4/5]
void randomise (symmTensor & st)
Definition at line 162 of file Random.C.
References Random::symmTensor01().
randomise() [5/5]
void randomise (tensor & t)
Definition at line 168 of file Random.C.
References Random::tensor01().
GaussNormal()
scalar GaussNormal ()
Return a normal Gaussian randon number.
with zero mean and unity variance N(0, 1)
Definition at line 177 of file Random.C.
References Foam::log(), Random::scalar01(), and Foam::sqrt().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/random/Random/Random.H
src/OpenFOAM/primitives/random/Random/Random.C