OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelRanges Class Reference
A list of labelRange.
Classes
class const_iterator
An STL const_iterator.
Public Member Functions
labelRanges ()
Construct null.
labelRanges (const label)
Construct given size.
labelRanges (Istream &)
Construct from Istream.
bool contains (const label) const
Return true if the value is within any of the ranges.
bool add (const labelRange &)
Add the range to the list.
bool remove (const labelRange &)
Remove the range from the list.
const_iterator cbegin () const
const_iterator set to the beginning of the list
const const_iterator & cend () const
const_iterator set to beyond the end of the list
const_iterator begin () const
const_iterator set to the beginning of the list
const const_iterator & end () const
const_iterator set to beyond the end of the list
Friends
Istream & operator>> (Istream &, labelRanges &)
Ostream & operator<< (Ostream &, const labelRanges &)
Detailed Description
A list of labelRange.
Source files
labelRanges.H
labelRanges.C
Definition at line 58 of file labelRanges.H.
Constructor & Destructor Documentation
labelRanges() [1/3]
labelRanges () inline
Construct null.
Definition at line 29 of file labelRangesI.H.
labelRanges() [2/3]
labelRanges (const label nElem) inline explicit
Construct given size.
Definition at line 35 of file labelRangesI.H.
labelRanges() [3/3]
labelRanges (Istream & is)
Construct from Istream.
Definition at line 119 of file labelRanges.C.
Member Function Documentation
contains()
bool contains (const label value) const inline
Return true if the value is within any of the ranges.
Definition at line 152 of file labelRangesI.H.
References forAll, and DynamicList< labelRange >::operator.
add()
bool add (const labelRange & range)
Add the range to the list.
Definition at line 127 of file labelRanges.C.
References DynamicList< labelRange >::append(), labelRange::clear(), labelRange::empty(), UList< T >::empty(), forAll, labelRange::intersects(), UList< T >::operator[](), range, and List< T >::size().
remove()
bool remove (const labelRange & range)
Remove the range from the list.
Definition at line 185 of file labelRanges.C.
References labelRange::debug, labelRange::empty(), UList< T >::empty(), Foam::endl(), labelRange::first(), forAll, Foam::Info, labelRange::last(), and UList< T >::operator[]().
cbegin()
Foam::labelRanges::const_iterator cbegin () const inline
const_iterator set to the beginning of the list
Definition at line 126 of file labelRangesI.H.
References labelRanges::const_iterator::const_iterator().
cend()
const Foam::labelRanges::const_iterator & cend () const inline
const_iterator set to beyond the end of the list
Definition at line 132 of file labelRangesI.H.
begin()
Foam::labelRanges::const_iterator begin () const inline
const_iterator set to the beginning of the list
Definition at line 138 of file labelRangesI.H.
References labelRanges::const_iterator::const_iterator().
end()
const Foam::labelRanges::const_iterator & end () const inline
const_iterator set to beyond the end of the list
Definition at line 144 of file labelRangesI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , labelRanges &) friend
operator<<
Ostream& operator<< (Ostream & , const labelRanges &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRanges.H
src/OpenFOAM/primitives/ranges/labelRange/labelRanges.C
src/OpenFOAM/primitives/ranges/labelRange/labelRangesI.H