OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cachedRandom Class Reference
Random number generator.
Public Member Functions
cachedRandom (const label seed, const label count)
Construct given seed and sample count.
cachedRandom (const cachedRandom &cr, const bool reset=false)
Copy constructor with optional reset of sampleI.
~cachedRandom ()
label seed () const
Return const access to the initial random number seed.
const scalarList & samples () const
Return const access to the list of samples.
label sampleI () const
Return the current sample marker.
label & sampleI ()
Return non-const access to the sample marker.
template<class Type >
Type sample01 ()
Return a sample whose components lie in the range 0-1.
template<class Type >
Type position (const Type &start, const Type &end)
Return a sample between start and end.
template<class Type >
void randomise01 (Type &value)
Randomise value in the range 0-1.
template<class Type >
Type globalSample01 ()
Return a sample whose components lie in the range 0-1.
template<class Type >
Type globalPosition (const Type &start, const Type &end)
Return a sample between start and end.
template<class Type >
void globalRandomise01 (Type &value)
Randomise value in the range 0-1.
void operator= (const cachedRandom &cr)
Assignment operator.
template<>
Foam::label sample01 ()
template<>
Foam::scalar sample01 ()
template<>
Foam::label position (const label &start, const label &end)
template<>
Foam::scalar position (const scalar &start, const scalar &end)
template<>
Foam::label globalSample01 ()
template<>
Foam::scalar globalSample01 ()
template<>
Foam::label globalPosition (const label &start, const label &end)
template<>
Foam::scalar globalPosition (const scalar &start, const scalar &end)
template<>
label sample01 ()
template<>
scalar sample01 ()
template<>
label position (const label &start, const label &end)
template<>
scalar position (const scalar &start, const scalar &end)
template<>
label globalSample01 ()
template<>
scalar globalSample01 ()
template<>
label globalPosition (const label &start, const label &end)
template<>
scalar globalPosition (const scalar &start, const scalar &end)
Detailed Description
Random number generator.
Pre-computes and caches samples on construction, so that when sample01() is called, the function simply returns the next (pre-computed) sample. On reaching the last sample, the sample sequence is repeated.
Constructed using a seed and sample count. If the supplied count is negative, no caching is performed, and a new sample is generated on each call to sample01().
Note: the copy constructor cannot be used if count = -1.
Source files
cachedRandom.H
cachedRandomI.H
cachedRandom.C
cachedRandomTemplates.C
Definition at line 63 of file cachedRandom.H.
Constructor & Destructor Documentation
cachedRandom() [1/2]
cachedRandom (const label seed, const label count)
Construct given seed and sample count.
Definition at line 56 of file cachedRandom.C.
References forAll, Foam::osRandomDouble(), Foam::osRandomSeed(), cachedRandom::seed(), and List< T >::setSize().
cachedRandom() [2/2]
cachedRandom (const cachedRandom & cr, const bool reset = false)
Copy constructor with optional reset of sampleI.
Definition at line 83 of file cachedRandom.C.
References Foam::endl(), Foam::osRandomSeed(), List< T >::size(), and WarningIn.
~cachedRandom()
~cachedRandom ()
Definition at line 109 of file cachedRandom.C.
Member Function Documentation
seed()
Foam::label seed () const inline
Return const access to the initial random number seed.
Definition at line 30 of file cachedRandomI.H.
Referenced by cachedRandom::cachedRandom().
samples()
const Foam::scalarList & samples () const inline
Return const access to the list of samples.
Definition at line 36 of file cachedRandomI.H.
sampleI() [1/2]
Foam::label sampleI () const inline
Return the current sample marker.
Definition at line 42 of file cachedRandomI.H.
sampleI() [2/2]
Foam::label & sampleI () inline
Return non-const access to the sample marker.
Definition at line 48 of file cachedRandomI.H.
sample01() [1/5]
Type sample01 ()
Return a sample whose components lie in the range 0-1.
Definition at line 32 of file cachedRandomTemplates.C.
Referenced by Stochastic< CloudType >::calculate(), ConeInjection< CloudType >::ConeInjection(), ConeNozzleInjection< CloudType >::ConeNozzleInjection(), InflationInjection< CloudType >::parcelsToInject(), triangle< Point, PointRef >::randomPoint(), tetrahedron< Point, PointRef >::randomPoint(), exponential::sample(), general::sample(), RosinRammler::sample(), normal::sample(), multiNormal::sample(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), ConeNozzleInjection< CloudType >::setProperties(), StochasticDispersionRAS< CloudType >::update(), GradientDispersionRAS< CloudType >::update(), SHF< CloudType >::update(), and Stochastic< CloudType >::~Stochastic().
position() [1/5]
Type position (const Type & start, const Type & end)
Return a sample between start and end.
Definition at line 45 of file cachedRandomTemplates.C.
Referenced by InflationInjection< CloudType >::parcelsToInject(), cachedRandom::position(), uniform::sample(), patchInjectionBase::setPositionAndCell(), KinematicLookupTableInjection< CloudType >::setPositionAndCell(), ThermoLookupTableInjection< CloudType >::setPositionAndCell(), ReactingLookupTableInjection< CloudType >::setPositionAndCell(), ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell(), and ConeInjection< CloudType >::setProperties().
randomise01()
void randomise01 (Type & value)
Randomise value in the range 0-1.
Definition at line 59 of file cachedRandomTemplates.C.
globalSample01() [1/5]
Type globalSample01 ()
Return a sample whose components lie in the range 0-1.
Definition at line 66 of file cachedRandomTemplates.C.
References UPstream::master(), and Foam::reduce().
globalPosition() [1/5]
Type globalPosition (const Type & start, const Type & end)
Return a sample between start and end.
Definition at line 82 of file cachedRandomTemplates.C.
References UPstream::master(), and Foam::reduce().
Referenced by cachedRandom::globalPosition(), cachedRandom::globalSample01(), and PatchInjection< CloudType >::parcelsToInject().
globalRandomise01()
void globalRandomise01 (Type & value)
Randomise value in the range 0-1.
Definition at line 98 of file cachedRandomTemplates.C.
References UPstream::master(), and Foam::reduce().
operator=()
void operator= (const cachedRandom & cr)
Assignment operator.
Definition at line 219 of file cachedRandom.C.
sample01() [2/5]
Foam::label sample01 ()
Definition at line 116 of file cachedRandom.C.
sample01() [3/5]
Foam::scalar sample01 ()
Definition at line 123 of file cachedRandom.C.
position() [2/5]
Foam::label position (const label & start, const label & end)
Definition at line 130 of file cachedRandom.C.
References cachedRandom::position().
position() [3/5]
Foam::scalar position (const scalar & start, const scalar & end)
Definition at line 138 of file cachedRandom.C.
globalSample01() [2/5]
Foam::label globalSample01 ()
Definition at line 148 of file cachedRandom.C.
References UPstream::master(), and Foam::reduce().
globalSample01() [3/5]
Foam::scalar globalSample01 ()
Definition at line 164 of file cachedRandom.C.
References cachedRandom::globalPosition(), UPstream::master(), and Foam::reduce().
globalPosition() [2/5]
Foam::label globalPosition (const label & start, const label & end)
Definition at line 181 of file cachedRandom.C.
References cachedRandom::globalPosition(), UPstream::master(), and Foam::reduce().
globalPosition() [3/5]
Foam::scalar globalPosition (const scalar & start, const scalar & end)
Definition at line 201 of file cachedRandom.C.
References UPstream::master(), and Foam::reduce().
sample01() [4/5]
label sample01 ()
sample01() [5/5]
scalar sample01 ()
position() [4/5]
label position (const label & start, const label & end)
position() [5/5]
scalar position (const scalar & start, const scalar & end)
globalSample01() [4/5]
label globalSample01 ()
globalSample01() [5/5]
scalar globalSample01 ()
globalPosition() [4/5]
label globalPosition (const label & start, const label & end)
globalPosition() [5/5]
scalar globalPosition (const scalar & start, const scalar & end)
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/random/cachedRandom/cachedRandom.H
src/OpenFOAM/primitives/random/cachedRandom/cachedRandom.C
src/OpenFOAM/primitives/random/cachedRandom/cachedRandomI.H
src/OpenFOAM/primitives/random/cachedRandom/cachedRandomTemplates.C