OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelRange Class Reference
A label range specifier.
Classes
class const_iterator
An STL const_iterator.
class less
Less function class for sorting labelRange.
Public Member Functions
labelRange ()
Construct an empty range.
labelRange (const label start, const label size)
Construct a range.
labelRange (Istream &)
Construct from Istream.
void clear ()
Reset to zero size.
bool empty () const
Is the range empty?
label size () const
Return the effective size of the range.
label first () const
The (inclusive) lower value of the range.
label last () const
The (inclusive) upper value of the range.
bool contains (const label) const
Return true if the value is within the range.
bool intersects (const labelRange &, const bool touches=false) const
Return true if the ranges intersect.
labelRange join (const labelRange &) const
Return a joined range, squashing any gaps in between.
label operator[] (const label) const
Return element in range, no bounds checking.
bool operator< (const labelRange &rhs) const
Comparison function for sorting, compares the start.
labelRange & operator+= (const labelRange &)
Join ranges, squashing any gaps in between.
bool operator== (const labelRange &) const
bool operator!= (const labelRange &) const
const_iterator cbegin () const
const_iterator set to the beginning of the range
const const_iterator & cend () const
const_iterator set to beyond the end of the range
const_iterator begin () const
const_iterator set to the beginning of the range
const const_iterator & end () const
const_iterator set to beyond the end of the range
Static Public Attributes
static int debug
Friends
Istream & operator>> (Istream &, labelRange &)
Ostream & operator<< (Ostream &, const labelRange &)
Detailed Description
A label range specifier.
Source files
labelRange.H
labelRange.C
Definition at line 56 of file labelRange.H.
Constructor & Destructor Documentation
labelRange() [1/3]
labelRange () inline
Construct an empty range.
Definition at line 29 of file labelRangeI.H.
Referenced by labelRange::join(), and labelRange::less::operator()().
labelRange() [2/3]
labelRange (const label start, const label size) inline
Construct a range.
A negative size is autmatically changed to zero.
Definition at line 36 of file labelRangeI.H.
References labelRange::clear().
labelRange() [3/3]
labelRange (Istream & is)
Construct from Istream.
Definition at line 39 of file labelRange.C.
References labelRange::intersects().
Member Function Documentation
clear()
void clear () inline
Reset to zero size.
Definition at line 143 of file labelRangeI.H.
Referenced by labelRanges::add(), labelRange::labelRange(), labelRange::less::operator()(), and Foam::operator>>().
empty()
bool empty () const inline
Is the range empty?
Definition at line 149 of file labelRangeI.H.
Referenced by labelRanges::add(), labelRange::less::operator()(), and labelRanges::remove().
size()
Foam::label size () const inline
Return the effective size of the range.
Definition at line 155 of file labelRangeI.H.
Referenced by labelRange::intersects(), labelRange::less::operator()(), and labelRange::const_iterator::operator++().
first()
Foam::label first () const inline
The (inclusive) lower value of the range.
Definition at line 161 of file labelRangeI.H.
Referenced by labelRange::contains(), labelRange::intersects(), labelRange::join(), labelRange::less::operator()(), labelRange::operator+=(), labelRange::operator<(), and labelRanges::remove().
last()
Foam::label last () const inline
The (inclusive) upper value of the range.
Definition at line 167 of file labelRangeI.H.
Referenced by labelRange::contains(), labelRange::intersects(), labelRange::join(), labelRange::less::operator()(), labelRange::operator+=(), and labelRanges::remove().
contains()
bool contains (const label value) const inline
Return true if the value is within the range.
Definition at line 173 of file labelRangeI.H.
References labelRange::first(), and labelRange::last().
Referenced by labelRange::less::operator()().
intersects()
bool intersects (const labelRange & range, const bool touches = false) const
Return true if the ranges intersect.
Optional test for ranges that also just touch each other
Definition at line 51 of file labelRange.C.
References labelRange::first(), labelRange::last(), and labelRange::size().
Referenced by labelRanges::add(), labelRange::labelRange(), and labelRange::less::operator()().
join()
Foam::labelRange join (const labelRange & range) const
Return a joined range, squashing any gaps in between.
A prior intersects() check can be used to avoid squashing gaps.
Definition at line 78 of file labelRange.C.
References labelRange::first(), labelRange::labelRange(), labelRange::last(), Foam::max(), Foam::min(), and range.
Referenced by labelRange::less::operator()().
operator[]()
Foam::label operator[] (const label i) const inline
Return element in range, no bounds checking.
Definition at line 181 of file labelRangeI.H.
Referenced by labelRange::less::operator()().
operator<()
bool operator< (const labelRange & rhs) const inline
Comparison function for sorting, compares the start.
Definition at line 187 of file labelRangeI.H.
References labelRange::first().
Referenced by labelRange::less::operator()().
operator+=()
Foam::labelRange & operator+= (const labelRange & rhs)
Join ranges, squashing any gaps in between.
A prior intersects() check can be used to avoid squashing gaps.
Definition at line 100 of file labelRange.C.
References labelRange::first(), labelRange::last(), Foam::max(), and Foam::min().
Referenced by labelRange::less::operator()().
operator==()
bool operator== (const labelRange & rhs) const inline
Definition at line 193 of file labelRangeI.H.
Referenced by labelRange::less::operator()().
operator!=()
bool operator!= (const labelRange & rhs) const inline
Definition at line 199 of file labelRangeI.H.
References labelRange::const_iterator::operator==().
Referenced by labelRange::less::operator()().
cbegin()
Foam::labelRange::const_iterator cbegin () const inline
const_iterator set to the beginning of the range
Definition at line 117 of file labelRangeI.H.
References labelRange::const_iterator::const_iterator().
cend()
const Foam::labelRange::const_iterator & cend () const inline
const_iterator set to beyond the end of the range
Definition at line 123 of file labelRangeI.H.
begin()
Foam::labelRange::const_iterator begin () const inline
const_iterator set to the beginning of the range
Definition at line 129 of file labelRangeI.H.
References labelRange::const_iterator::const_iterator().
end()
const Foam::labelRange::const_iterator & end () const inline
const_iterator set to beyond the end of the range
Definition at line 135 of file labelRangeI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , labelRange &) friend
operator<<
Ostream& operator<< (Ostream & , const labelRange &) friend
Member Data Documentation
debug
int debug static
Definition at line 65 of file labelRange.H.
Referenced by labelRanges::remove().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRange.H
src/OpenFOAM/primitives/ranges/labelRange/labelRange.C
src/OpenFOAM/primitives/ranges/labelRange/labelRangeI.H