OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelRanges::const_iterator Class Reference
An STL const_iterator.
Public Member Functions
const_iterator ()
Construct null - equivalent to an 'end' position.
const_iterator (const labelRanges &)
Construct from list, moving to its 'begin' position.
bool operator== (const const_iterator &) const
bool operator!= (const const_iterator &) const
label operator* ()
label operator() ()
const_iterator & operator++ ()
const_iterator operator++ (int)
Detailed Description
An STL const_iterator.
Definition at line 113 of file labelRanges.H.
Constructor & Destructor Documentation
const_iterator() [1/2]
const_iterator () inline
Construct null - equivalent to an 'end' position.
Definition at line 43 of file labelRangesI.H.
Referenced by labelRanges::begin(), and labelRanges::cbegin().
const_iterator() [2/2]
const_iterator (const labelRanges & lst) inline explicit
Construct from list, moving to its 'begin' position.
Definition at line 51 of file labelRangesI.H.
References UList< T >::empty().
Member Function Documentation
operator==()
bool operator== (const const_iterator & iter) const inline
Definition at line 66 of file labelRangesI.H.
Referenced by labelRanges::const_iterator::operator!=().
operator!=()
bool operator!= (const const_iterator & iter) const inline
Definition at line 79 of file labelRangesI.H.
References labelRanges::const_iterator::operator==().
operator*()
Foam::label operator* () inline
Definition at line 87 of file labelRangesI.H.
operator()()
Foam::label operator() () inline
Definition at line 93 of file labelRangesI.H.
operator++() [1/2]
Foam::labelRanges::const_iterator & operator++ () inline
Definition at line 100 of file labelRangesI.H.
References List< T >::size().
Referenced by labelRanges::const_iterator::operator++().
operator++() [2/2]
Foam::labelRanges::const_iterator operator++ (int) inline
Definition at line 118 of file labelRangesI.H.
References labelRanges::const_iterator::operator++().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRanges.H
src/OpenFOAM/primitives/ranges/labelRange/labelRangesI.H