OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelRange::less Class Reference
Less function class for sorting labelRange.
Public Member Functions
bool operator() (const labelRange &a, const labelRange &b)
Detailed Description
Less function class for sorting labelRange.
Definition at line 71 of file labelRange.H.
Member Function Documentation
operator()()
bool operator() (const labelRange & a, const labelRange & b) inline
Definition at line 75 of file labelRange.H.
References labelRange::clear(), labelRange::contains(), labelRange::empty(), labelRange::first(), labelRange::intersects(), labelRange::join(), labelRange::labelRange(), labelRange::last(), labelRange::operator!=(), labelRange::operator+=(), labelRange::operator<(), labelRange::operator==(), labelRange::operator[](), and labelRange::size().
The documentation for this class was generated from the following file:
src/OpenFOAM/primitives/ranges/labelRange/labelRange.H