OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelRange::const_iterator Class Reference
An STL const_iterator.
Public Member Functions
const_iterator ()
Construct null - equivalent to an 'end' position.
const_iterator (const labelRange &)
Construct from range, moving to its 'begin' position.
bool operator== (const const_iterator &) const
bool operator!= (const const_iterator &) const
label operator* ()
label operator() ()
const_iterator & operator++ ()
const_iterator operator++ (int)
Detailed Description
An STL const_iterator.
Definition at line 142 of file labelRange.H.
Constructor & Destructor Documentation
const_iterator() [1/2]
const_iterator () inline
Construct null - equivalent to an 'end' position.
Definition at line 51 of file labelRangeI.H.
Referenced by labelRange::begin(), and labelRange::cbegin().
const_iterator() [2/2]
const_iterator (const labelRange & range) inline explicit
Construct from range, moving to its 'begin' position.
Definition at line 58 of file labelRangeI.H.
Member Function Documentation
operator==()
bool operator== (const const_iterator & iter) const inline
Definition at line 66 of file labelRangeI.H.
Referenced by labelRange::operator!=(), and labelRange::const_iterator::operator!=().
operator!=()
bool operator!= (const const_iterator & iter) const inline
Definition at line 75 of file labelRangeI.H.
References labelRange::const_iterator::operator==().
operator*()
Foam::label operator* () inline
Definition at line 83 of file labelRangeI.H.
operator()()
Foam::label operator() () inline
Definition at line 89 of file labelRangeI.H.
operator++() [1/2]
Foam::labelRange::const_iterator & operator++ () inline
Definition at line 96 of file labelRangeI.H.
References labelRange::size().
Referenced by labelRange::const_iterator::operator++().
operator++() [2/2]
Foam::labelRange::const_iterator operator++ (int) inline
Definition at line 109 of file labelRangeI.H.
References labelRange::const_iterator::operator++().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRange.H
src/OpenFOAM/primitives/ranges/labelRange/labelRangeI.H