OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SphericalTensor< Cmpt > Class Template Reference
Templated 3D SphericalTensor derived from VectorSpace adding construction from 1 component, element access using th ii() member function and the inner-product (dot-product) and outer-product operators.
Public Types
enum { rank = 2 }
enum components { II }
Component labeling enumeration.
typedef SphericalTensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
SphericalTensor ()
Construct null.
template<class Cmpt2 >
SphericalTensor (const VectorSpace< SphericalTensor< Cmpt2 >, Cmpt2, 1 > &)
Construct given VectorSpace.
SphericalTensor (const Cmpt &tii)
Construct given the component.
SphericalTensor (Istream &)
Construct from Istream.
const Cmpt & ii () const
Cmpt & ii ()
const SphericalTensor< Cmpt > & T () const
Transpose.
Public Member Functions inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "labelSphericalTensor"
static const char * componentNames [] = {"ii"}
static const SphericalTensor zero
static const SphericalTensor one
static const SphericalTensor max
static const SphericalTensor min
static const SphericalTensor I
static const SphericalTensor oneThirdI
static const SphericalTensor twoThirdsI
Additional Inherited Members
Public Attributes inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SphericalTensor< Cmpt >
Templated 3D SphericalTensor derived from VectorSpace adding construction from 1 component, element access using th ii() member function and the inner-product (dot-product) and outer-product operators.
Source files
SphericalTensor.H
SphericalTensorI.H
Definition at line 51 of file SphericalTensor.H.
Member Typedef Documentation
labelType
typedef SphericalTensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 59 of file SphericalTensor.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
rank
Definition at line 64 of file SphericalTensor.H.
components
enum components
Component labeling enumeration.
Enumerator
II
Definition at line 84 of file SphericalTensor.H.
Constructor & Destructor Documentation
SphericalTensor() [1/4]
SphericalTensor () inline
Construct null.
Definition at line 36 of file SphericalTensorI.H.
SphericalTensor() [2/4]
SphericalTensor (const VectorSpace< SphericalTensor< Cmpt2 >, Cmpt2, 1 > & vs) inline
Construct given VectorSpace.
Definition at line 43 of file SphericalTensorI.H.
SphericalTensor() [3/4]
SphericalTensor (const Cmpt & tii) inline
Construct given the component.
Definition at line 52 of file SphericalTensorI.H.
SphericalTensor() [4/4]
SphericalTensor (Istream & is) inline
Construct from Istream.
Definition at line 59 of file SphericalTensorI.H.
Member Function Documentation
ii() [1/2]
const Cmpt & ii () const inline
Definition at line 68 of file SphericalTensorI.H.
References SphericalTensor< Cmpt >::II, and VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >::v_.
Referenced by Foam::det(), Foam::inv(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Foam::operator/(), SymmTensor< Cmpt >::operator=(), Tensor< scalar >::operator=(), Random::sphericalTensor01(), SymmTensor< Cmpt >::SymmTensor(), Tensor< scalar >::Tensor(), and Foam::tr().
ii() [2/2]
Cmpt & ii () inline
Definition at line 75 of file SphericalTensorI.H.
References SphericalTensor< Cmpt >::II, and VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >::v_.
T()
const SphericalTensor< Cmpt > & T () const inline
Transpose.
Definition at line 82 of file SphericalTensorI.H.
Member Data Documentation
typeName
const char *const typeName = "labelSphericalTensor" static
Definition at line 72 of file SphericalTensor.H.
componentNames
const char * componentNames = {"ii"} static
Definition at line 73 of file SphericalTensor.H.
zero
const sphericalTensor zero static
Definition at line 74 of file SphericalTensor.H.
one
const sphericalTensor one static
Definition at line 75 of file SphericalTensor.H.
max
const sphericalTensor max static
Definition at line 76 of file SphericalTensor.H.
min
const sphericalTensor min static
Definition at line 77 of file SphericalTensor.H.
I
const sphericalTensor I static
Definition at line 78 of file SphericalTensor.H.
Referenced by STARCDCoordinateRotation::clear(), EulerCoordinateRotation::clear(), and axesRotation::clear().
oneThirdI
const sphericalTensor oneThirdI static
Definition at line 79 of file SphericalTensor.H.
twoThirdsI
const sphericalTensor twoThirdsI static
Definition at line 80 of file SphericalTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SphericalTensor/SphericalTensor.H
src/OpenFOAM/primitives/SphericalTensor/labelSphericalTensor/labelSphericalTensor.C
src/OpenFOAM/primitives/SphericalTensor/sphericalTensor/sphericalTensor.C
src/OpenFOAM/primitives/SphericalTensor/SphericalTensorI.H