OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SymmTensor< Cmpt > Class Template Reference
Templated 3D symmetric tensor derived from VectorSpace adding construction from 6 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum { rank = 2 }
enum components {
XX, XY, XZ, YY,
YZ, ZZ
}
Component labeling enumeration.
typedef SymmTensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
SymmTensor ()
Construct null.
template<class Cmpt2 >
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > &)
Construct given VectorSpace of the same rank.
SymmTensor (const SphericalTensor< Cmpt > &)
Construct given SphericalTensor.
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz)
Construct given the six components.
SymmTensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zz ()
const SymmTensor< Cmpt > & T () const
Transpose.
void operator= (const SphericalTensor< Cmpt > &)
Construct given SphericalTensor.
Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SymmTensor< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "labelSymmTensor"
static const char * componentNames []
static const SymmTensor zero
static const SymmTensor one
static const SymmTensor max
static const SymmTensor min
static const SymmTensor I
Additional Inherited Members
Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SymmTensor< Cmpt >
Templated 3D symmetric tensor derived from VectorSpace adding construction from 6 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
SymmTensor.H
SymmTensorI.H
Definition at line 53 of file SymmTensor.H.
Member Typedef Documentation
labelType
typedef SymmTensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file SymmTensor.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
rank
Definition at line 66 of file SymmTensor.H.
components
enum components
Component labeling enumeration.
Enumerator
XX
XY
XZ
YY
YZ
ZZ
Definition at line 85 of file SymmTensor.H.
Constructor & Destructor Documentation
SymmTensor() [1/5]
SymmTensor () inline
Construct null.
Definition at line 37 of file SymmTensorI.H.
Referenced by SymmTensor< Cmpt >::SymmTensor().
SymmTensor() [2/5]
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 44 of file SymmTensorI.H.
SymmTensor() [3/5]
SymmTensor (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 53 of file SymmTensorI.H.
References SphericalTensor< Cmpt >::ii(), and SymmTensor< Cmpt >::SymmTensor().
SymmTensor() [4/5]
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz) inline
Construct given the six components.
Definition at line 63 of file SymmTensorI.H.
SymmTensor() [5/5]
SymmTensor (Istream & is) inline
Construct from Istream.
Definition at line 76 of file SymmTensorI.H.
Member Function Documentation
xx() [1/2]
const Cmpt & xx () const inline
Definition at line 85 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XX.
Referenced by primitiveMeshTools::cellDeterminant(), Foam::cof(), Foam::det(), Foam::diag(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor< scalar >::operator=(), Tensor< scalar >::Tensor(), Foam::tr(), Foam::transform(), and dxSurfaceWriter::writeData().
xy() [1/2]
const Cmpt & xy () const inline
Definition at line 91 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
Referenced by Foam::cof(), Foam::det(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Tensor< scalar >::operator=(), Tensor< scalar >::Tensor(), Foam::transform(), and dxSurfaceWriter::writeData().
xz() [1/2]
const Cmpt & xz () const inline
Definition at line 97 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
Referenced by Foam::cof(), Foam::det(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Tensor< scalar >::operator=(), Tensor< scalar >::Tensor(), Foam::transform(), and dxSurfaceWriter::writeData().
yy() [1/2]
const Cmpt & yy () const inline
Definition at line 103 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YY.
Referenced by primitiveMeshTools::cellDeterminant(), Foam::cof(), Foam::det(), Foam::diag(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor< scalar >::operator=(), Tensor< scalar >::Tensor(), Foam::tr(), Foam::transform(), and dxSurfaceWriter::writeData().
yz() [1/2]
const Cmpt & yz () const inline
Definition at line 109 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
Referenced by Foam::cof(), Foam::det(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Tensor< scalar >::operator=(), Tensor< scalar >::Tensor(), Foam::transform(), and dxSurfaceWriter::writeData().
zz() [1/2]
const Cmpt & zz () const inline
Definition at line 115 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::ZZ.
Referenced by primitiveMeshTools::cellDeterminant(), Foam::cof(), Foam::det(), Foam::diag(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor< scalar >::operator=(), Tensor< scalar >::Tensor(), Foam::tr(), Foam::transform(), and dxSurfaceWriter::writeData().
xx() [2/2]
Cmpt & xx () inline
Definition at line 122 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XX.
xy() [2/2]
Cmpt & xy () inline
Definition at line 128 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
xz() [2/2]
Cmpt & xz () inline
Definition at line 134 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
yy() [2/2]
Cmpt & yy () inline
Definition at line 140 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YY.
yz() [2/2]
Cmpt & yz () inline
Definition at line 146 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
zz() [2/2]
Cmpt & zz () inline
Definition at line 152 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::ZZ.
T()
const SymmTensor< Cmpt > & T () const inline
Transpose.
Definition at line 159 of file SymmTensorI.H.
operator=()
void operator= (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 168 of file SymmTensorI.H.
References SphericalTensor< Cmpt >::ii(), VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, SymmTensor< Cmpt >::XX, SymmTensor< Cmpt >::XY, SymmTensor< Cmpt >::XZ, SymmTensor< Cmpt >::YY, SymmTensor< Cmpt >::YZ, and SymmTensor< Cmpt >::ZZ.
Member Data Documentation
typeName
const char *const typeName = "labelSymmTensor" static
Definition at line 74 of file SymmTensor.H.
componentNames
const char * componentNames static
Initial value:
=
{
    "xx", "xy", "xz",
          "yy", "yz",
                "zz"
}
Definition at line 75 of file SymmTensor.H.
zero
const symmTensor zero static
Definition at line 77 of file SymmTensor.H.
Referenced by laminar::B(), laminar::R(), localAxesRotation::transformVector(), and leastSquaresVectors::~leastSquaresVectors().
one
const symmTensor one static
Definition at line 78 of file SymmTensor.H.
max
const symmTensor max static
Definition at line 79 of file SymmTensor.H.
min
const symmTensor min static
Definition at line 80 of file SymmTensor.H.
I
const symmTensor I static
Definition at line 81 of file SymmTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor/SymmTensor.H
src/OpenFOAM/primitives/SymmTensor/labelSymmTensor/labelSymmTensor.C
src/OpenFOAM/primitives/SymmTensor/symmTensor/symmTensor.C
src/OpenFOAM/primitives/SymmTensor/SymmTensorI.H