OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
string::hash Class Reference
Hashing function class, shared by all the derived classes.
Public Member Functions
hash ()
unsigned operator() (const string &, unsigned seed=0) const
Detailed Description
Hashing function class, shared by all the derived classes.
Definition at line 90 of file string.H.
Constructor & Destructor Documentation
hash()
hash () inline
Definition at line 93 of file string.H.
References string::count(), string::expand(), string::match(), string::meta(), n, string::hash::operator()(), string::operator<<, string::operator>>, string::quotemeta(), string::removeRepeated(), string::removeTrailing(), string::replace(), string::replaceAll(), string::string(), string::stripInvalid(), string::valid(), and string::validate().
Member Function Documentation
operator()()
unsigned operator() (const string & key, unsigned seed = 0) const inline
Definition at line 205 of file stringI.H.
References Foam::Hasher().
Referenced by string::hash::hash().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/string/string.H
src/OpenFOAM/primitives/strings/string/stringI.H