OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SymmTensor2D< Cmpt > Class Template Reference
Templated 2D symmetric tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum { rank = 2 }
enum components { XX, XY, YY }
Component labeling enumeration.
typedef SymmTensor2D< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
SymmTensor2D ()
Construct null.
SymmTensor2D (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 > &)
Construct given VectorSpace.
SymmTensor2D (const SphericalTensor2D< Cmpt > &)
Construct given SphericalTensor.
SymmTensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyy)
Construct given the three components.
SymmTensor2D (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & yy () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & yy ()
const SymmTensor2D< Cmpt > & T () const
Transpose.
void operator= (const SphericalTensor2D< Cmpt > &)
Construct given SphericalTensor2D.
Public Member Functions inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "symmTensor2D"
static const char * componentNames []
static const SymmTensor2D zero
static const SymmTensor2D one
static const SymmTensor2D max
static const SymmTensor2D min
static const SymmTensor2D I
Additional Inherited Members
Public Attributes inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SymmTensor2D< Cmpt >
Templated 2D symmetric tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
SymmTensor2D.H
SymmTensor2DI.H
Definition at line 53 of file SymmTensor2D.H.
Member Typedef Documentation
labelType
typedef SymmTensor2D<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file SymmTensor2D.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
rank
Definition at line 66 of file SymmTensor2D.H.
components
enum components
Component labeling enumeration.
Enumerator
XX
XY
YY
Definition at line 85 of file SymmTensor2D.H.
Constructor & Destructor Documentation
SymmTensor2D() [1/5]
SymmTensor2D () inline
Construct null.
Definition at line 37 of file SymmTensor2DI.H.
Referenced by SymmTensor2D< Cmpt >::SymmTensor2D().
SymmTensor2D() [2/5]
SymmTensor2D (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 > & vs) inline
Construct given VectorSpace.
Definition at line 43 of file SymmTensor2DI.H.
SymmTensor2D() [3/5]
SymmTensor2D (const SphericalTensor2D< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 52 of file SymmTensor2DI.H.
References SphericalTensor2D< Cmpt >::ii(), and SymmTensor2D< Cmpt >::SymmTensor2D().
SymmTensor2D() [4/5]
SymmTensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyy) inline
Construct given the three components.
Definition at line 61 of file SymmTensor2DI.H.
SymmTensor2D() [5/5]
SymmTensor2D (Istream & is) inline
Construct from Istream.
Definition at line 72 of file SymmTensor2DI.H.
Member Function Documentation
xx() [1/2]
const Cmpt & xx () const inline
Definition at line 81 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XX.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor2D< Cmpt >::operator=(), Tensor2D< Cmpt >::Tensor2D(), and Foam::tr().
xy() [1/2]
const Cmpt & xy () const inline
Definition at line 87 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor2D< Cmpt >::operator=(), and Tensor2D< Cmpt >::Tensor2D().
yy() [1/2]
const Cmpt & yy () const inline
Definition at line 93 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::YY.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor2D< Cmpt >::operator=(), Tensor2D< Cmpt >::Tensor2D(), and Foam::tr().
xx() [2/2]
Cmpt & xx () inline
Definition at line 100 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XX.
xy() [2/2]
Cmpt & xy () inline
Definition at line 106 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
yy() [2/2]
Cmpt & yy () inline
Definition at line 112 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::YY.
T()
const SymmTensor2D< Cmpt > & T () const inline
Transpose.
Definition at line 119 of file SymmTensor2DI.H.
operator=()
void operator= (const SphericalTensor2D< Cmpt > & st) inline
Construct given SphericalTensor2D.
Definition at line 128 of file SymmTensor2DI.H.
References SphericalTensor2D< Cmpt >::ii(), VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, SymmTensor2D< Cmpt >::XX, SymmTensor2D< Cmpt >::XY, and SymmTensor2D< Cmpt >::YY.
Member Data Documentation
typeName
const char *const typeName = "symmTensor2D" static
Definition at line 74 of file SymmTensor2D.H.
componentNames
const char * componentNames static
Initial value:
=
{
    "xx", "xy",
          "yy"
}
Definition at line 75 of file SymmTensor2D.H.
zero
const symmTensor2D zero static
Definition at line 77 of file SymmTensor2D.H.
one
const symmTensor2D one static
Definition at line 78 of file SymmTensor2D.H.
max
const symmTensor2D max static
Definition at line 79 of file SymmTensor2D.H.
min
const symmTensor2D min static
Definition at line 80 of file SymmTensor2D.H.
I
const symmTensor2D I static
Definition at line 81 of file SymmTensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor2D/SymmTensor2D.H
src/OpenFOAM/primitives/SymmTensor2D/symmTensor2D/symmTensor2D.C
src/OpenFOAM/primitives/SymmTensor2D/SymmTensor2DI.H