OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Vector2D< Cmpt > Class Template Reference
Templated 2D Vector derived from VectorSpace adding construction from 2 components, element access using x() and y() member functions and the inner-product (dot-product).
Public Types
enum { rank = 1 }
enum components { X, Y }
Component labeling enumeration.
Public Types inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
Vector2D ()
Construct null.
Vector2D (const VectorSpace< Vector2D< Cmpt >, Cmpt, 2 > &)
Construct given VectorSpace.
Vector2D (const Cmpt &vx, const Cmpt &vy)
Construct given two components.
Vector2D (Istream &)
Construct from Istream.
const Cmpt & x () const
const Cmpt & y () const
Cmpt & x ()
Cmpt & y ()
scalar perp (const Vector2D< Cmpt > &b) const
perp dot product (dot product with perpendicular vector)
Public Member Functions inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Vector2D< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Vector2D< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< Vector2D< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< Vector2D< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName
static const char * componentNames []
static const Vector2D zero
static const Vector2D one
static const Vector2D max
static const Vector2D min
Additional Inherited Members
Public Attributes inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Vector2D< Cmpt >
Templated 2D Vector derived from VectorSpace adding construction from 2 components, element access using x() and y() member functions and the inner-product (dot-product).
Source files
Vector2D.H
Vector2DI.H
Definition at line 51 of file Vector2D.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
rank
Definition at line 60 of file Vector2D.H.
components
enum components
Component labeling enumeration.
Enumerator
X
Y
Definition at line 77 of file Vector2D.H.
Constructor & Destructor Documentation
Vector2D() [1/4]
Vector2D () inline
Construct null.
Definition at line 35 of file Vector2DI.H.
Vector2D() [2/4]
Vector2D (const VectorSpace< Vector2D< Cmpt >, Cmpt, 2 > & vs) inline
Construct given VectorSpace.
Definition at line 41 of file Vector2DI.H.
Vector2D() [3/4]
Vector2D (const Cmpt & vx, const Cmpt & vy) inline
Construct given two components.
Definition at line 49 of file Vector2DI.H.
Vector2D() [4/4]
Vector2D (Istream & is) inline
Construct from Istream.
Definition at line 58 of file Vector2DI.H.
Member Function Documentation
x() [1/2]
const Cmpt & x () const inline
Definition at line 67 of file Vector2DI.H.
Referenced by Foam::eigenVectors(), Foam::operator &(), Foam::operator*(), Vector2D< scalar >::perp(), Foam::sqr(), Tensor2D< Cmpt >::Tensor2D(), CV2D::toPoint(), and CV2D::toPoint3D().
y() [1/2]
const Cmpt & y () const inline
Definition at line 73 of file Vector2DI.H.
Referenced by Foam::eigenVectors(), Foam::operator &(), Foam::operator*(), Vector2D< scalar >::perp(), Foam::sqr(), Tensor2D< Cmpt >::Tensor2D(), CV2D::toPoint(), and CV2D::toPoint3D().
x() [2/2]
Cmpt & x () inline
Definition at line 80 of file Vector2DI.H.
y() [2/2]
Cmpt & y () inline
Definition at line 86 of file Vector2DI.H.
perp()
scalar perp (const Vector2D< Cmpt > & b) const inline
perp dot product (dot product with perpendicular vector)
Definition at line 103 of file Vector2DI.H.
Referenced by line< Point, PointRef >::nearestDist().
Member Data Documentation
typeName
const char* const typeName static
Definition at line 68 of file Vector2D.H.
componentNames
const char* componentNames[] static
Definition at line 69 of file Vector2D.H.
zero
const Vector2D zero static
Definition at line 70 of file Vector2D.H.
one
const Vector2D one static
Definition at line 71 of file Vector2D.H.
max
const Vector2D max static
Definition at line 72 of file Vector2D.H.
min
const Vector2D min static
Definition at line 73 of file Vector2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Vector2D/Vector2D.H
src/OpenFOAM/primitives/Vector2D/Vector2DI.H