OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Tuple2< Type1, Type2 > Class Template Reference
A 2-tuple for storing two objects of different types.
Public Member Functions
Tuple2 ()
Null constructor for lists.
Tuple2 (const Type1 &f, const Type2 &s)
Construct from components.
Tuple2 (Istream &is)
Construct from Istream.
const Type1 & first () const
Return first.
Type1 & first ()
Return first.
const Type2 & second () const
Return second.
Type2 & second ()
Return second.
Friends
Istream & operator>> (Istream &is, Tuple2< Type1, Type2 > &t2)
Read Tuple2 from Istream, discarding contents of existing Tuple2.
Ostream & operator (Ostream &os, const Tuple2< Type1, Type2 > &t2)
Detailed Description
template<class Type1, class Type2>
class Foam::Tuple2< Type1, Type2 >
A 2-tuple for storing two objects of different types.
See also
Foam::Pair for storing two objects of identical types.
Definition at line 47 of file Tuple2.H.
Constructor & Destructor Documentation
Tuple2() [1/3]
Tuple2 () inline
Null constructor for lists.
Definition at line 74 of file Tuple2.H.
Tuple2() [2/3]
Tuple2 (const Type1 & f, const Type2 & s) inline
Construct from components.
Definition at line 78 of file Tuple2.H.
Tuple2() [3/3]
Tuple2 (Istream & is) inline
Construct from Istream.
Definition at line 85 of file Tuple2.H.
Member Function Documentation
first() [1/2]
const Type1& first () const inline
Return first.
Definition at line 94 of file Tuple2.H.
Referenced by pointConstraint::combine(), patchProbes::findElements(), mappedPatchBase::findSamples(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), mappedPatchBase::nearestEqOp::operator()(), mappedPatchBase::maxProcEqOp::operator()(), Foam::operator+(), forceSuSp::operator+=(), forceSuSp::operator-=(), forceSuSp::operator=(), Foam::operator==(), Foam::reverse(), Foam::transform(), and sixDoFRigidBodyMotion::updatePosition().
first() [2/2]
Type1& first () inline
Return first.
Definition at line 100 of file Tuple2.H.
second() [1/2]
const Type2& second () const inline
Return second.
Definition at line 106 of file Tuple2.H.
Referenced by pointConstraint::combine(), patchProbes::findElements(), listPlusEqOp< T >::operator()(), mappedPatchBase::nearestEqOp::operator()(), mappedPatchBase::maxProcEqOp::operator()(), Foam::operator+(), forceSuSp::operator+=(), forceSuSp::operator-=(), forceSuSp::operator=(), Foam::operator==(), Foam::reverse(), Foam::transform(), and sixDoFRigidBodyMotion::updatePosition().
second() [2/2]
Type2& second () inline
Return second.
Definition at line 112 of file Tuple2.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & is, Tuple2< Type1, Type2 > & t2) friend
Read Tuple2 from Istream, discarding contents of existing Tuple2.
Definition at line 167 of file Tuple2.H.
operator
Ostream& operator (Ostream & os, const Tuple2< Type1, Type2 > & t2) friend
The documentation for this class was generated from the following file:
src/OpenFOAM/primitives/Tuple2/Tuple2.H