OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Vector< Cmpt > Class Template Reference
Templated 3D Vector derived from VectorSpace adding construction from 3 components, element access using x(), y() and z() member functions and the inner-product (dot-product) and cross product operators.
Public Types
enum { rank = 1 }
enum components { X, Y, Z }
Component labeling enumeration.
typedef Vector< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
Vector ()
Construct null.
template<class Cmpt2 >
Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > &)
Construct given VectorSpace of the same rank.
Vector (const Cmpt &vx, const Cmpt &vy, const Cmpt &vz)
Construct given three components.
Vector (Istream &)
Construct from Istream.
const Cmpt & x () const
const Cmpt & y () const
const Cmpt & z () const
Cmpt & x ()
Cmpt & y ()
Cmpt & z ()
const Vector< Cmpt > & centre (const Foam::List< Vector< Cmpt > > &) const
Return *this (used for point which is a typedef to Vector<scalar>.
Public Member Functions inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Vector< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Vector< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< Vector< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< Vector< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "complexVector"
static const char * componentNames [] = {"x", "y", "z"}
static const Vector zero
static const Vector one
static const Vector max
static const Vector min
static const Vector rootMax
static const Vector rootMin
Additional Inherited Members
Public Attributes inherited from VectorSpace< Vector< Cmpt >, Cmpt, 3 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Vector< Cmpt >
Templated 3D Vector derived from VectorSpace adding construction from 3 components, element access using x(), y() and z() member functions and the inner-product (dot-product) and cross product operators.
A centre() member function which returns the Vector for which it is called is defined so that point which is a typedef to Vector<scalar> behaves as other shapes in the shape hierachy.
Source files
Vector.H
VectorI.H
Definition at line 57 of file Vector.H.
Member Typedef Documentation
labelType
typedef Vector<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 65 of file Vector.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
rank
Definition at line 70 of file Vector.H.
components
enum components
Component labeling enumeration.
Enumerator
X
Y
Z
Definition at line 89 of file Vector.H.
Constructor & Destructor Documentation
Vector() [1/4]
Vector () inline
Construct null.
Definition at line 34 of file VectorI.H.
Vector() [2/4]
Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 40 of file VectorI.H.
Vector() [3/4]
Vector (const Cmpt & vx, const Cmpt & vy, const Cmpt & vz) inline
Construct given three components.
Definition at line 47 of file VectorI.H.
Vector() [4/4]
Vector (Istream & is) inline
Construct from Istream.
Definition at line 56 of file VectorI.H.
Member Function Documentation
x() [1/2]
const Cmpt & x () const inline
Definition at line 65 of file VectorI.H.
Referenced by biLinearFitPolynomial::addCoeffs(), cubicUpwindFitPolynomial::addCoeffs(), linearFitPolynomial::addCoeffs(), quadraticFitPolynomial::addCoeffs(), quadraticLinearUpwindFitPolynomial::addCoeffs(), quadraticUpwindFitPolynomial::addCoeffs(), quadraticLinearFitPolynomial::addCoeffs(), triad::align(), tetrahedron< Point, PointRef >::barycentric(), Foam::meshTools::calcBoxPointNormals(), treeBoundBox::calcExtremities(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), cyclicPolyPatch::calcTransforms(), rotorDiskSource::calculate(), edgeCollapser::checkMeshQuality(), molecule::constantProperties::constantProperties(), boundBox::contains(), boundBox::containsInside(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), treeBoundBox::distanceCmp(), Foam::eigenVector(), Foam::eigenVectors(), pitchForkRing::energy(), quaternion::eulerAngles(), treeBoundBox::faceBits(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicTreeDataPoint::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), pitchForkRing::force(), polyMesh::geometricD(), boundaryMesh::getNearest(), cylindricalCS::globalToLocal(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), triangleFuncs::intersectBb(), treeBoundBox::intersects(), Foam::inv(), cellMDLimitedGrad< Type >::limitFace(), cylindricalCS::localToGlobal(), momentOfInertia::massPropertiesSolid(), conformalVoronoiMesh::maxSurfaceProtrusion(), molecule::move(), NamedEnum< directionType, 3 >::names(), blockDescriptor::nCells(), boundBox::nearest(), twoDPointCorrector::normalDir(), blockDescriptor::nPoints(), Foam::operator &(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), Foam::operator*(), Foam::operator/(), Foam::operator^(), searchablePlate::overlaps(), boundBox::overlaps(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps(), indexedOctree< Foam::treeDataFace >::overlaps(), plane::planeCoeffs(), plane::planeIntersect(), polyTopoChange::pointRemoved(), boundBox::points(), treeBoundBox::posBits(), triad::primaryDirection(), quaternion::R(), AC3DsurfaceFormat< Face >::read(), Foam::readUpto(), coordSet::scalarCoord(), treeBoundBox::searchOrder(), KinematicLookupTableInjection< CloudType >::setPositionAndCell(), ReactingLookupTableInjection< CloudType >::setPositionAndCell(), ThermoLookupTableInjection< CloudType >::setPositionAndCell(), ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell(), polyMesh::solutionD(), Foam::sqr(), treeBoundBox::subBbox(), treeBoundBox::subOctant(), surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField(), Tensor< scalar >::Tensor(), Foam::toPoint(), oscillatingRotatingMotion::transformation(), coordinateRotation::transformPrincipal(), pointConstraint::unconstrainedDirections(), vtkInsertNextOpenFOAMPoint(), block::vtxLabel(), wallLayerCells::wallLayerCells(), vtkSetWriter< Type >::write(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), OBJedgeFormat::write(), AC3DsurfaceFormat< Face >::write(), OBJstream::write(), meshToMeshMethod::writeConnectivity(), VTKsurfaceFormatCore::writeHeader(), VTKedgeFormat::writeHeader(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), triSurfaceTools::writeOBJ(), cellCuts::writeOBJ(), blockMesh::writeTopology(), moleculeCloud::writeXYZ(), Foam::Xinterpolate(), and Foam::XstepForwardsToNextPoint().
y() [1/2]
const Cmpt & y () const inline
Definition at line 71 of file VectorI.H.
Referenced by biLinearFitPolynomial::addCoeffs(), cubicUpwindFitPolynomial::addCoeffs(), linearFitPolynomial::addCoeffs(), quadraticFitPolynomial::addCoeffs(), quadraticLinearUpwindFitPolynomial::addCoeffs(), quadraticUpwindFitPolynomial::addCoeffs(), quadraticLinearFitPolynomial::addCoeffs(), triad::align(), tetrahedron< Point, PointRef >::barycentric(), Foam::meshTools::calcBoxPointNormals(), treeBoundBox::calcExtremities(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), cyclicPolyPatch::calcTransforms(), rotorDiskSource::calculate(), edgeCollapser::checkMeshQuality(), molecule::constantProperties::constantProperties(), boundBox::contains(), boundBox::containsInside(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), treeBoundBox::distanceCmp(), Foam::eigenVector(), Foam::eigenVectors(), pitchForkRing::energy(), quaternion::eulerAngles(), treeBoundBox::faceBits(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicTreeDataPoint::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), pitchForkRing::force(), boundaryMesh::getNearest(), cylindricalCS::globalToLocal(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), triangleFuncs::intersectBb(), treeBoundBox::intersects(), Foam::inv(), cellMDLimitedGrad< Type >::limitFace(), cylindricalCS::localToGlobal(), momentOfInertia::massPropertiesSolid(), conformalVoronoiMesh::maxSurfaceProtrusion(), molecule::move(), NamedEnum< directionType, 3 >::names(), blockDescriptor::nCells(), boundBox::nearest(), twoDPointCorrector::normalDir(), blockDescriptor::nPoints(), Foam::operator &(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), Foam::operator*(), Foam::operator/(), Foam::operator^(), searchablePlate::overlaps(), boundBox::overlaps(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps(), indexedOctree< Foam::treeDataFace >::overlaps(), plane::planeCoeffs(), plane::planeIntersect(), polyTopoChange::pointRemoved(), boundBox::points(), treeBoundBox::posBits(), triad::primaryDirection(), quaternion::R(), AC3DsurfaceFormat< Face >::read(), Foam::readUpto(), coordSet::scalarCoord(), treeBoundBox::searchOrder(), Foam::sqr(), treeBoundBox::subBbox(), treeBoundBox::subOctant(), surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField(), Tensor< scalar >::Tensor(), Foam::toPoint(), oscillatingRotatingMotion::transformation(), coordinateRotation::transformPrincipal(), pointConstraint::unconstrainedDirections(), vtkInsertNextOpenFOAMPoint(), block::vtxLabel(), wallLayerCells::wallLayerCells(), vtkSetWriter< Type >::write(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OBJedgeFormat::write(), OBJstream::write(), meshToMeshMethod::writeConnectivity(), VTKsurfaceFormatCore::writeHeader(), VTKedgeFormat::writeHeader(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), triSurfaceTools::writeOBJ(), cellCuts::writeOBJ(), blockMesh::writeTopology(), moleculeCloud::writeXYZ(), and Foam::Xinterpolate().
z() [1/2]
const Cmpt & z () const inline
Definition at line 77 of file VectorI.H.
Referenced by biLinearFitPolynomial::addCoeffs(), cubicUpwindFitPolynomial::addCoeffs(), linearFitPolynomial::addCoeffs(), quadraticFitPolynomial::addCoeffs(), quadraticLinearUpwindFitPolynomial::addCoeffs(), quadraticUpwindFitPolynomial::addCoeffs(), quadraticLinearFitPolynomial::addCoeffs(), triad::align(), tetrahedron< Point, PointRef >::barycentric(), Foam::meshTools::calcBoxPointNormals(), treeBoundBox::calcExtremities(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), cyclicPolyPatch::calcTransforms(), rotorDiskSource::calculate(), molecule::constantProperties::constantProperties(), boundBox::contains(), boundBox::containsInside(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), treeBoundBox::distanceCmp(), Foam::eigenVector(), Foam::eigenVectors(), pitchForkRing::energy(), quaternion::eulerAngles(), treeBoundBox::faceBits(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicTreeDataPoint::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), pitchForkRing::force(), boundaryMesh::getNearest(), cylindricalCS::globalToLocal(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), triangleFuncs::intersectBb(), treeBoundBox::intersects(), Foam::inv(), cellMDLimitedGrad< Type >::limitFace(), cylindricalCS::localToGlobal(), momentOfInertia::massPropertiesSolid(), conformalVoronoiMesh::maxSurfaceProtrusion(), layeredEngineMesh::move(), NamedEnum< directionType, 3 >::names(), blockDescriptor::nCells(), boundBox::nearest(), twoDPointCorrector::normalDir(), blockDescriptor::nPoints(), Foam::operator &(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), Foam::operator*(), Foam::operator/(), Foam::operator^(), searchablePlate::overlaps(), boundBox::overlaps(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps(), indexedOctree< Foam::treeDataFace >::overlaps(), plane::planeCoeffs(), plane::planeIntersect(), polyTopoChange::pointRemoved(), boundBox::points(), treeBoundBox::posBits(), triad::primaryDirection(), quaternion::R(), AC3DsurfaceFormat< Face >::read(), Foam::readUpto(), coordSet::scalarCoord(), treeBoundBox::searchOrder(), Foam::sqr(), treeBoundBox::subBbox(), treeBoundBox::subOctant(), surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField(), Tensor< scalar >::Tensor(), Foam::toPoint(), oscillatingRotatingMotion::transformation(), coordinateRotation::transformPrincipal(), vtkInsertNextOpenFOAMPoint(), block::vtxLabel(), wallLayerCells::wallLayerCells(), vtkSetWriter< Type >::write(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OBJedgeFormat::write(), OBJstream::write(), meshToMeshMethod::writeConnectivity(), VTKsurfaceFormatCore::writeHeader(), VTKedgeFormat::writeHeader(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), triSurfaceTools::writeOBJ(), cellCuts::writeOBJ(), blockMesh::writeTopology(), and moleculeCloud::writeXYZ().
x() [2/2]
Cmpt & x () inline
Definition at line 84 of file VectorI.H.
y() [2/2]
Cmpt & y () inline
Definition at line 90 of file VectorI.H.
z() [2/2]
Cmpt & z () inline
Definition at line 96 of file VectorI.H.
centre()
const Vector< Cmpt > & centre (const Foam::List< Vector< Cmpt > > &) const inline
Return *this (used for point which is a typedef to Vector<scalar>.
Definition at line 106 of file VectorI.H.
Referenced by cyclicPolyPatch::coupledEdges(), treeDataPrimitivePatch< PatchType >::overlaps(), KinematicCloud< Foam::DsmcCloud >::patchData(), surfaceFeatures::setFromStatus(), and extendedEdgeMesh::sortPointsAndEdges().
Member Data Documentation
typeName
const char *const typeName = "complexVector" static
Definition at line 78 of file Vector.H.
componentNames
const char * componentNames = {"x", "y", "z"} static
Definition at line 79 of file Vector.H.
Referenced by searchablePlate::searchablePlate(), and regionSizeDistribution::write().
zero
const complexVector zero static
Definition at line 80 of file Vector.H.
Referenced by autoLayerDriver::addLayers(), pressureGradientExplicitSource::addSup(), interRegionExplicitPorositySource::addSup(), rotorDiskSource::addSup(), pointConstraint::applyConstraint(), autoSnapDriver::avgCellCentres(), booleanSurface::booleanSurface(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), targetCoeffTrim::calcCoeffs(), LiftForce< CloudType >::calcCoupled(), BrownianMotionForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcCoupled(), fixedCoeff::calcForce(), DarcyForchheimer::calcForce(), forces::calcForcesMoment(), autoSnapDriver::calcNearestSurface(), GravityForce< CloudType >::calcNonCoupled(), ParticleForce< CloudType >::calcNonCoupled(), cyclicAMIPolyPatch::calcTransforms(), moleculeCloud::calculateForce(), cell::centre(), face::centre(), polyTopoChange::changeMesh(), polyMeshGeometry::checkFaceTwist(), edgeCollapser::checkMeshQuality(), pointConstraint::combine(), ConeInjection< CloudType >::ConeInjection(), ConeNozzleInjection< CloudType >::ConeNozzleInjection(), molecule::constantProperties::constantProperties(), orientation::constrainRotation(), point::constrainTranslation(), contactAngleForce::correct(), motionSmootherAlgo::correctBoundaryConditions(), targetCoeffTrim::correctTrim(), rotorDiskSource::createCoordinateSystem(), displacementInterpolationMotionSolver::curPoints(), motionSmootherAlgo::curPoints(), geomCellLooper::cut(), cyclicAMIFvPatch::delta(), cyclicACMIFvPatch::delta(), autoSnapDriver::doSnap(), localAxesRotation::e1(), localAxesRotation::e2(), extendedEdgeMesh::edgeDirection(), triSurfaceMesh::edgeTree(), quaternion::eulerAngles(), Foam::exp(), extrudePatchMesh::extrudePatchMesh(), searchableSurfacesQueries::facesIntersection(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestRegionEdge(), searchableSphere::getNormal(), searchablePlate::getNormal(), searchableCylinder::getNormal(), searchableBox::getNormal(), triSurfaceMesh::getNormal(), triSurfaceMeshPointSet::getRefPoint(), treeDataFace::getVolumeType(), particle< Type >::hitWallFaces(), rotorDiskSource::inflowVelocity(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), localAxesRotation::invTransform(), meshRefinement::isGap(), meshRefinement::isNormalGap(), DsmcCloud< DsmcParcel< ParcelType > >::linearMomentumOfSystem(), cell::mag(), primitiveMesh::makeCellCentresAndVols(), meshRefinement::makeDisplacementField(), primitiveMesh::makeFaceCentresAndAreas(), MRFZone::makeRelative(), edgeMesh::mergePoints(), molecule::move(), regionModel1D::moveMesh(), surfaceInterpolation::movePoints(), NamedEnum< directionType, 3 >::names(), cellCuts::nonAnchorPoints(), surfaceLocation::normal(), face::normal(), listPlusEqOp< T >::operator()(), MRFZoneList::operator()(), InflationInjection< CloudType >::parcelsToInject(), searchableCylinder::points(), indexedCell< Gt, Cb >::potentialCoplanarCell(), boundaryMesh::read(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), sphericalAngularDamper::restrain(), linearDamper::restrain(), sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), linearSpring::restrain(), tabulatedAxialAngularSpring::restrain(), motionSmootherAlgo::scaleMesh(), motionSmootherAlgo::setDisplacementPatchFields(), rotorDiskSource::setFaceArea(), NoInjection< CloudType >::setProperties(), globalMeshData::sharedPoints(), sixDoFRigidBodyMotionSolver::solve(), triSurfaceTools::surfaceNormal(), ThermoSurfaceFilm< CloudType >::tangentVector(), meshRefinement::testSyncPointList(), localAxesRotation::transform(), porosityModel::transformModelData(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), pointConstraint::unconstrainedDirections(), StochasticDispersionRAS< CloudType >::update(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), outletPhaseMeanVelocityFvPatchVectorField::updateCoeffs(), laminar::Us(), coalCloudList::UTrans(), vorticity::vorticity(), wallShearStress::wallShearStress(), mappedPatchBase::write(), medialAxisMeshMover::~medialAxisMeshMover(), and skewCorrectionVectors::~skewCorrectionVectors().
one
const complexVector one static
Definition at line 81 of file Vector.H.
Referenced by autoLayerDriver::addLayers(), cellLimitedGrad< Type >::calcGrad(), motionDirectionalDiffusivity::correct(), boundBox::inflate(), and searchableSphere::searchableSphere().
max
const Vector max static
Definition at line 82 of file Vector.H.
Referenced by autoSnapDriver::doSnap(), mappedPatchBase::findSamples(), removePoints::getUnrefimentSet(), pointEdgeStructuredWalk::inZone(), NamedEnum< directionType, 3 >::names(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), orientedSurface::orientedSurface(), distributedTriSurfaceMesh::overlappingSurface(), primitiveMesh::pointInCellBB(), polyTopoChange::pointRemoved(), searchableDisk::searchableDisk(), addPatchCellLayer::setRefinement(), removePoints::setUnrefinement(), and pointEdgeStructuredWalk::valid().
min
const Vector min static
Definition at line 83 of file Vector.H.
Referenced by NamedEnum< directionType, 3 >::names(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), distributedTriSurfaceMesh::overlappingSurface(), searchableDisk::searchableDisk(), and searchableSurfaceCollection::searchableSurfaceCollection().
rootMax
const Vector rootMax static
Definition at line 84 of file Vector.H.
Referenced by symmetryPlanePolyPatch::calcGeometry(), and wedgePolyPatch::calcGeometry().
rootMin
const Vector rootMin static
Definition at line 85 of file Vector.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Vector/Vector.H
src/OpenFOAM/primitives/Vector/complexVector/complexVector.C
src/OpenFOAM/primitives/Vector/VectorI.H