OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvFieldDecomposer::processorSurfacePatchFieldDecomposer Class Reference
Processor patch field decomposer class. Surface field is assumed.
Public Member Functions
processorSurfacePatchFieldDecomposer (const labelUList &addressingSlice)
Construct given addressing.
label size () const
bool direct () const
bool hasUnmapped () const
Are there unmapped values.
const labelListList & addressing () const
const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual const labelUList & directAddressing () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Processor patch field decomposer class. Surface field is assumed.
to have direction (so manipulates sign when mapping)
Definition at line 151 of file fvFieldDecomposer.H.
Constructor & Destructor Documentation
processorSurfacePatchFieldDecomposer()
processorSurfacePatchFieldDecomposer (const labelUList & addressingSlice)
Construct given addressing.
Definition at line 97 of file fvFieldDecomposer.C.
References forAll, Foam::mag(), and sign().
Referenced by fvFieldDecomposer::processorVolPatchFieldDecomposer::processorVolPatchFieldDecomposer().
Member Function Documentation
size()
label size () const inline virtual
Implements FieldMapper.
Definition at line 169 of file fvFieldDecomposer.H.
References List< T >::size().
direct()
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 174 of file fvFieldDecomposer.H.
hasUnmapped()
bool hasUnmapped () const inline virtual
Are there unmapped values.
Implements FieldMapper.
Definition at line 180 of file fvFieldDecomposer.H.
addressing()
const labelListList& addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 185 of file fvFieldDecomposer.H.
weights()
const scalarListList& weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 190 of file fvFieldDecomposer.H.
References fvFieldDecomposer::decomposeField(), fvFieldDecomposer::decomposeFields(), fields, and fvFieldDecomposer::~fvFieldDecomposer().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/fvFieldDecomposer.H
src/parallel/decompose/decompose/fvFieldDecomposer.C