OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sigWriteNow Class Reference
Signal handler for interupt defined by OptimisationSwitches::writeNowSignal.
Public Member Functions
sigWriteNow ()
Construct null.
sigWriteNow (const bool verbose, Time &runTime)
Construct from components.
~sigWriteNow ()
Destructor.
bool active () const
Is active?
Static Public Member Functions
static void set (const bool verbose)
(re)set signal catcher
Friends
class sigStopAtWriteNow
class addwriteNowSignalToOpt
wip. Have setter have access to signal_
Detailed Description
Signal handler for interupt defined by OptimisationSwitches::writeNowSignal.
Write once and continue.
Source files
sigWriteNow.H
sigWriteNow.C
Definition at line 52 of file sigWriteNow.H.
Constructor & Destructor Documentation
sigWriteNow() [1/2]
sigWriteNow ()
Construct null.
Definition at line 89 of file sigWriteNow.C.
sigWriteNow() [2/2]
sigWriteNow (const bool verbose, Time & runTime)
Construct from components.
Definition at line 93 of file sigWriteNow.C.
~sigWriteNow()
~sigWriteNow ()
Destructor.
Definition at line 104 of file sigWriteNow.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Member Function Documentation
set()
void set (const bool verbose) static
(re)set signal catcher
Definition at line 123 of file sigWriteNow.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, and Foam::Info.
Referenced by addwriteNowSignalToOpt::readData().
active()
bool active () const
Is active?
Definition at line 150 of file sigWriteNow.C.
Friends And Related Function Documentation
sigStopAtWriteNow
friend class sigStopAtWriteNow friend
Definition at line 69 of file sigWriteNow.H.
addwriteNowSignalToOpt
friend class addwriteNowSignalToOpt friend
wip. Have setter have access to signal_
Definition at line 72 of file sigWriteNow.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigWriteNow.H
src/OSspecific/POSIX/signals/sigWriteNow.C