OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sigStopAtWriteNow Class Reference
Signal handler for interupt defined by OptimisationSwitches::stopAtWriteNowSignal.
Public Member Functions
sigStopAtWriteNow ()
Construct null.
sigStopAtWriteNow (const bool verbose, const Time &runTime)
Construct from components.
~sigStopAtWriteNow ()
Destructor.
bool active () const
Is active?
Static Public Member Functions
static void set (const bool verbose)
(re)set signal catcher
Friends
class addstopAtWriteNowSignalToOpt
wip. Have setter have access to signal_
Detailed Description
Signal handler for interupt defined by OptimisationSwitches::stopAtWriteNowSignal.
Write and stop the job.
Source files
sigStopAtWriteNow.H
sigStopAtWriteNow.C
Definition at line 53 of file sigStopAtWriteNow.H.
Constructor & Destructor Documentation
sigStopAtWriteNow() [1/2]
sigStopAtWriteNow ()
Construct null.
Definition at line 105 of file sigStopAtWriteNow.C.
sigStopAtWriteNow() [2/2]
sigStopAtWriteNow (const bool verbose, const Time & runTime)
Construct from components.
Definition at line 109 of file sigStopAtWriteNow.C.
~sigStopAtWriteNow()
~sigStopAtWriteNow ()
Destructor.
Definition at line 123 of file sigStopAtWriteNow.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Member Function Documentation
set()
void set (const bool verbose) static
(re)set signal catcher
Definition at line 142 of file sigStopAtWriteNow.C.
References Foam::abort(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::findEtcFile(), and Foam::Info.
Referenced by addstopAtWriteNowSignalToOpt::readData().
active()
bool active () const
Is active?
Definition at line 185 of file sigStopAtWriteNow.C.
Friends And Related Function Documentation
addstopAtWriteNowSignalToOpt
friend class addstopAtWriteNowSignalToOpt friend
wip. Have setter have access to signal_
Definition at line 71 of file sigStopAtWriteNow.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigStopAtWriteNow.H
src/OSspecific/POSIX/signals/sigStopAtWriteNow.C