OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
minData Class Reference
For use with FaceCellWave. Transports minimum passive data.
Public Member Functions
minData ()
Construct null.
minData (const label data)
Construct from count.
label data () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const minData &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const minData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const minData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const minData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const minData &, TrackingData &td) const
Same (like operator==)
bool operator== (const minData &) const
bool operator!= (const minData &) const
Friends
Ostream & operator<< (Ostream &, const minData &)
Istream & operator>> (Istream &, minData &)
Detailed Description
For use with FaceCellWave. Transports minimum passive data.
Source files
minData.H
minDataI.H
Definition at line 52 of file minData.H.
Constructor & Destructor Documentation
minData() [1/2]
minData () inline
Construct null.
Definition at line 30 of file minDataI.H.
minData() [2/2]
minData (const label data) inline
Construct from count.
Definition at line 36 of file minDataI.H.
Member Function Documentation
data()
label data () const inline
Definition at line 75 of file minData.H.
References minData::enterDomain(), minData::equal(), minData::leaveDomain(), minData::operator!=(), minData::operator<<, minData::operator==(), minData::operator>>, minData::sameGeometry(), minData::transform(), minData::updateCell(), minData::updateFace(), and minData::valid().
Referenced by minData::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 45 of file minDataI.H.
References minData::sameGeometry().
Referenced by minData::data().
sameGeometry()
bool sameGeometry (const polyMesh & , const minData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 53 of file minDataI.H.
References minData::leaveDomain().
Referenced by minData::data(), and minData::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 66 of file minDataI.H.
References minData::transform().
Referenced by minData::data(), and minData::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 88 of file minDataI.H.
References minData::updateCell().
Referenced by minData::data(), and minData::transform().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 78 of file minDataI.H.
References minData::enterDomain().
Referenced by minData::data(), and minData::leaveDomain().
updateCell()
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const minData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 100 of file minDataI.H.
References minData::updateFace().
Referenced by minData::data(), and minData::enterDomain().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFaceI, const label neighbourCellI, const minData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 123 of file minDataI.H.
Referenced by minData::data(), and minData::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & , const label thisFaceI, const minData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 148 of file minDataI.H.
References minData::equal().
equal()
bool equal (const minData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 171 of file minDataI.H.
References minData::operator==().
Referenced by minData::data(), and minData::updateFace().
operator==()
bool operator== (const minData & rhs) const inline
Definition at line 183 of file minDataI.H.
References minData::data().
Referenced by minData::data(), and minData::equal().
operator!=()
bool operator!= (const minData & rhs) const inline
Definition at line 192 of file minDataI.H.
Referenced by minData::data().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const minData &) friend
Referenced by minData::data().
operator>>
Istream& operator>> (Istream & , minData &) friend
Referenced by minData::data().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionMethod/minData.H
src/parallel/decompose/decompositionMethods/decompositionMethod/minDataI.H