OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sigFpe Class Reference
Set up trapping for floating point exceptions (signal FPE).
Public Member Functions
sigFpe ()
Construct null.
~sigFpe ()
Destructor.
void set (const bool verbose)
Activate SIGFPE signal handler when FOAM_SIGFPE is set.
Static Public Member Functions
static void fillSignallingNan (UList< scalar > &)
Helper: fill block of data with NaN.
Detailed Description
Set up trapping for floating point exceptions (signal FPE).
Controlled by two env vars:
Parameters
FOAM_SIGFPE
exception trapping
FOAM_SETNAN
initialization of all malloced memory to NaN. If FOAM_SIGFPE also set, this will cause usage of uninitialized scalars to trigger an abort.
Source files
sigFpe.H
sigFpe.C
Definition at line 66 of file sigFpe.H.
Constructor & Destructor Documentation
sigFpe()
sigFpe ()
Construct null.
Definition at line 116 of file sigFpe.C.
~sigFpe()
~sigFpe ()
Destructor.
Definition at line 124 of file sigFpe.C.
References Foam::abort(), Foam::env(), Foam::FatalError, and FatalErrorIn.
Member Function Documentation
set()
void set (const bool verbose)
Activate SIGFPE signal handler when FOAM_SIGFPE is set.
Fill memory with NaN when FOAM_SETNAN is set
Definition at line 160 of file sigFpe.C.
References Foam::abort(), Foam::endl(), Foam::env(), Foam::FatalError, FatalErrorIn, and Foam::Info.
Referenced by argList::parse().
fillSignallingNan()
void fillSignallingNan (UList< scalar > & lst) static
Helper: fill block of data with NaN.
Definition at line 55 of file sigFpe.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::jobInfo, Foam::Perr, and JobInfo::signalEnd().
Referenced by dynamicRefineFvMesh::refine().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigFpe.H
src/OSspecific/POSIX/signals/sigFpe.C