OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fileStat Class Reference
Wrapper for stat() system call.
Public Member Functions
fileStat ()
Empty constructor.
fileStat (const fileName &fName, const unsigned int maxTime=0)
Construct from components.
fileStat (Istream &)
Construct from Istream.
const struct stat & status () const
Raw status.
bool isValid () const
Did constructor fail.
bool sameDevice (const fileStat &stat2) const
compare two fileStats for same device
bool sameINode (const fileStat &stat2) const
compare two fileStats for same Inode
bool sameINode (const label iNode) const
compare state against inode
Friends
Istream & operator>> (Istream &, fileStat &)
Ostream & operator<< (Ostream &, const fileStat &)
Detailed Description
Wrapper for stat() system call.
Warning
on Linux (an maybe on others) a stat() of an nfs mounted (remote) file does never timeout and cannot be interrupted! So e.g. Foam::ping first and hope nfs is running.
Source files
fileStat.H
fileStat.C
Definition at line 65 of file fileStat.H.
Constructor & Destructor Documentation
fileStat() [1/3]
fileStat ()
Empty constructor.
Definition at line 36 of file fileStat.C.
fileStat() [2/3]
fileStat (const fileName & fName, const unsigned int maxTime = 0)
Construct from components.
Definition at line 42 of file fileStat.C.
References timedOut.
fileStat() [3/3]
fileStat (Istream & is)
Construct from Istream.
Definition at line 66 of file fileStat.C.
Member Function Documentation
status()
const struct stat& status () const inline
Raw status.
Definition at line 93 of file fileStat.H.
Referenced by Foam::fileSize(), Foam::lastModified(), Foam::mode(), fileStat::sameDevice(), and fileStat::sameINode().
isValid()
bool isValid () const inline
Did constructor fail.
Definition at line 99 of file fileStat.H.
References fileStat::operator<<, fileStat::operator>>, fileStat::sameDevice(), and fileStat::sameINode().
Referenced by Foam::fileSize(), Foam::lastModified(), and Foam::mode().
sameDevice()
bool sameDevice (const fileStat & stat2) const
compare two fileStats for same device
Definition at line 74 of file fileStat.C.
References fileStat::status().
Referenced by fileStat::isValid().
sameINode() [1/2]
bool sameINode (const fileStat & stat2) const
compare two fileStats for same Inode
Definition at line 85 of file fileStat.C.
References fileStat::status().
Referenced by fileStat::isValid().
sameINode() [2/2]
bool sameINode (const label iNode) const
compare state against inode
Definition at line 91 of file fileStat.C.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , fileStat &) friend
Referenced by fileStat::isValid().
operator<<
Ostream& operator<< (Ostream & , const fileStat &) friend
Referenced by fileStat::isValid().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/fileStat.H
src/OSspecific/POSIX/fileStat.C