OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
decompositionMethod Class Reference abstract
Abstract base class for decomposition.
Public Member Functions
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual bool parallelAware () const =0
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)=0
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)=0
Return for every coordinate the wanted processor number.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Static Public Member Functions
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
Protected Attributes
const dictionary & decompositionDict_
label nProcessors_
Detailed Description
Abstract base class for decomposition.
Source files
decompositionMethod.H
decompositionMethod.C
Definition at line 48 of file decompositionMethod.H.
Constructor & Destructor Documentation
decompositionMethod()
decompositionMethod (const dictionary & decompositionDict) inline
Construct given the decomposition dictionary.
Definition at line 100 of file decompositionMethod.H.
~decompositionMethod()
virtual ~decompositionMethod () inline virtual
Destructor.
Definition at line 111 of file decompositionMethod.H.
Member Function Documentation
TypeName()
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , decompositionMethod , dictionary , (const dictionary &decompositionDict) , (decompositionDict))
New()
Foam::autoPtr< Foam::decompositionMethod > New (const dictionary & decompositionDict) static
Return a reference to the selected decomposition method.
Definition at line 50 of file decompositionMethod.C.
References decompositionMethod::decompose(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), Foam::nl, and UPstream::parRun().
Referenced by multiLevelDecomp::multiLevelDecomp(), NamedEnum< directionType, 3 >::names(), and structuredDecomp::structuredDecomp().
nDomains()
label nDomains () const inline
Definition at line 117 of file decompositionMethod.H.
References decompositionMethod::decompose(), decompositionMethod::nProcessors_, and decompositionMethod::parallelAware().
Referenced by multiLevelDecomp::multiLevelDecomp(), and structuredDecomp::structuredDecomp().
parallelAware()
virtual bool parallelAware () const pure virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implemented in hierarchGeomDecomp, multiLevelDecomp, ptscotchDecomp, scotchDecomp, simpleGeomDecomp, structuredDecomp, metisDecomp, manualDecomp, and noDecomp.
Referenced by decompositionMethod::nDomains().
decompose() [1/10]
virtual labelList decompose (const pointField & points, const scalarField & pointWeights) inline virtual
Return for every coordinate the wanted processor number.
Reimplemented in hierarchGeomDecomp, simpleGeomDecomp, and geomDecomp.
Definition at line 131 of file decompositionMethod.H.
References notImplemented.
Referenced by meshRefinement::balance(), decompositionMethod::calcCellCells(), decompositionMethod::decompose(), decompositionMethod::nDomains(), decompositionMethod::New(), and decompositionMethod::setConstraints().
decompose() [2/10]
virtual labelList decompose (const pointField &) inline virtual
Like decompose but with uniform weights on the points.
Reimplemented in hierarchGeomDecomp, simpleGeomDecomp, and geomDecomp.
Definition at line 145 of file decompositionMethod.H.
References decompositionMethod::calcCellCells(), decompositionMethod::decompose(), mesh, notImplemented, and decompositionMethod::setConstraints().
decompose() [3/10]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) pure virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed)
Implemented in hierarchGeomDecomp, ptscotchDecomp, multiLevelDecomp, scotchDecomp, simpleGeomDecomp, metisDecomp, structuredDecomp, manualDecomp, and noDecomp.
decompose() [4/10]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points) virtual
Like decompose but with uniform weights on the points.
Reimplemented in hierarchGeomDecomp, and simpleGeomDecomp.
Definition at line 85 of file decompositionMethod.C.
References decompositionMethod::decompose(), and List< T >::size().
decompose() [5/10]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints, const scalarField & regionWeights) virtual
Return for every coordinate the wanted processor number. Gets.
passed agglomeration map (from fine to coarse cells) and coarse cell location. Can be overridden by decomposers that provide this functionality natively. Coarse cells are local to the processor (if in parallel). If you want to have coarse cells spanning processors use the globalCellCells instead.
Reimplemented in ptscotchDecomp, scotchDecomp, and metisDecomp.
Definition at line 97 of file decompositionMethod.C.
References decompositionMethod::decompose(), forAll, and List< T >::size().
decompose() [6/10]
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) virtual
Like decompose but with uniform weights on the regions.
Definition at line 138 of file decompositionMethod.C.
References decompositionMethod::decompose(), and List< T >::size().
decompose() [7/10]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) pure virtual
Return for every coordinate the wanted processor number.
The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches
Implemented in hierarchGeomDecomp, ptscotchDecomp, scotchDecomp, multiLevelDecomp, metisDecomp, simpleGeomDecomp, manualDecomp, noDecomp, and structuredDecomp.
decompose() [8/10]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc) virtual
Like decompose but with uniform weights on the cells.
Reimplemented in hierarchGeomDecomp.
Definition at line 157 of file decompositionMethod.C.
References decompositionMethod::calcCellCells(), and List< T >::size().
calcCellCells()
void calcCellCells (const polyMesh & mesh, const labelList & agglom, const label nLocalCoarse, const bool global, CompactListList< label > & cellCells) static
Helper: determine (local or global) cellCells from mesh.
agglomeration. Agglomeration is local to the processor. local : connections are in local indices. Coupled across cyclics but not processor patches. global : connections are in global indices. Coupled across cyclics and processor patches.
Definition at line 169 of file decompositionMethod.C.
References polyMesh::boundaryMesh(), HashTable< T, Key, Hash >::clear(), polyPatch::coupled(), decompositionMethod::decompose(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, HashSet< Key, Hash >::insert(), globalIndex::isLocal(), CompactListList< T, Container >::m(), UPstream::msgType(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), CompactListList< T, Container >::offsets(), patches, CompactListList< T, Container >::setSize(), List< T >::setSize(), CompactListList< T, Container >::size(), polyPatch::start(), syncTools::swapBoundaryFaceList(), globalIndex::toGlobal(), globalIndex::toLocal(), and UPstream::worldComm.
Referenced by multiLevelDecomp::decompose(), decompositionMethod::decompose(), CuthillMcKeeRenumber::renumber(), springRenumber::renumber(), and renumberMethod::renumber().
setConstraints()
void setConstraints (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections)
Helper: extract constraints:
blockedface: existing faces where owner and neighbour on same proc explicitConnections: sets of boundary faces ,, ,, specifiedProcessorFaces: groups of faces with all cells on same processor.
Definition at line 1116 of file decompositionMethod.C.
References polyMesh::boundaryMesh(), List< T >::clear(), PtrList< T >::clear(), decompositionMethod::decompose(), Foam::endl(), Foam::exit(), f(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorIn, localPointRegion::findDuplicateFacePairs(), polyBoundaryMesh::findPatchID(), ZoneMesh< ZoneType, MeshType >::findZoneID(), UList< T >::first(), forAll, Foam::Info, ZoneMesh< ZoneType, MeshType >::names(), polyBoundaryMesh::names(), primitiveMesh::nFaces(), Foam::nl, primitiveMesh::nPoints(), patches, pFaces, primitiveMesh::pointFaces(), Foam::reduce(), PtrList< T >::set(), List< T >::setSize(), PtrList< T >::setSize(), HashTable< T, Key, Hash >::size(), HashTable< T, Key, Hash >::sortedToc(), polyPatch::start(), syncTools::syncFaceList(), and syncTools::syncPointList().
Referenced by meshRefinement::balance(), and decompositionMethod::decompose().
decompose() [9/10]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cellWeights, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections) virtual
Parameters
blockedFace Whether owner and neighbour should be on same processor (takes priority over explicitConnections)
specifiedProcessorFaces Whether whole sets of faces (and point neighbours) need to be kept on single processor
explicitConnections Additional connections between boundary faces
Definition at line 749 of file decompositionMethod.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), polyPatch::coupled(), UList< T >::data(), Foam::endl(), Foam::exit(), f(), f1, primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorIn, Pair< Type >::first(), forAll, polyMesh::globalData(), Foam::Info, primitiveMesh::isInternalFace(), Vector< scalar >::max, patchIdentifier::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), regionSplit::nLocalRegions(), globalMeshData::nTotalCells(), UPstream::parRun(), patches, pFaces, primitiveMesh::pointFaces(), Foam::reduce(), Foam::returnReduce(), Pair< Type >::second(), decompositionMethod::setConstraints(), List< T >::size(), PtrList< T >::size(), polyPatch::start(), and syncTools::swapBoundaryCellList().
decompose() [10/10]
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
('preserveFaceZones' etc). Calls either
no constraints, empty weights: decompose(mesh, cellCentres())
no constraints, set weights: decompose(mesh, cellCentres(), cellWeights)
valid constraints: decompose(mesh, cellToRegion, regionPoints, regionWeights)
Definition at line 1297 of file decompositionMethod.C.
Member Data Documentation
decompositionDict_
const dictionary& decompositionDict_ protected
Definition at line 55 of file decompositionMethod.H.
nProcessors_
label nProcessors_ protected
Definition at line 56 of file decompositionMethod.H.
Referenced by manualDecomp::decompose(), and decompositionMethod::nDomains().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionMethod/decompositionMethod.H
src/parallel/decompose/decompositionMethods/decompositionMethod/decompositionMethod.C