OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sigQuit Class Reference
Signal handler for QUIT interupt.
Public Member Functions
sigQuit ()
Construct null.
~sigQuit ()
Destructor.
void set (const bool verbose)
Activate SIGQUIT signal handler.
Detailed Description
Signal handler for QUIT interupt.
The standard interupt handler is overridden to ensure that the runningJob file is removed.
See also
Foam::JobInfo
Source files
sigQuit.H
sigQuit.C
Definition at line 54 of file sigQuit.H.
Constructor & Destructor Documentation
sigQuit()
sigQuit ()
Construct null.
Definition at line 62 of file sigQuit.C.
~sigQuit()
~sigQuit ()
Destructor.
Definition at line 70 of file sigQuit.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Member Function Documentation
set()
void set (const bool verbose)
Activate SIGQUIT signal handler.
Definition at line 86 of file sigQuit.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by argList::parse().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigQuit.H
src/OSspecific/POSIX/signals/sigQuit.C