OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
memInfo Class Reference
Memory usage information for the process running this object.
Public Member Functions
memInfo ()
Construct null.
~memInfo ()
Destructor.
const memInfo & update ()
Parse /proc/<pid>/status.
int peak () const
Access the stored peak memory (VmPeak in /proc/<pid>/status)
int size () const
Access the stored memory size (VmSize in /proc/<pid>/status)
int rss () const
Access the stored rss value (VmRSS in /proc/<pid>/status)
bool valid () const
True if the memory information appears valid.
Friends
Istream & operator>> (Istream &, memInfo &)
Read peak/size/rss from stream.
Ostream & operator<< (Ostream &, const memInfo &)
Write peak/size/rss to stream.
Detailed Description
Memory usage information for the process running this object.
Note
Uses the information from /proc/<pid>/status
Source files
memInfo.H
memInfo.C
Definition at line 53 of file memInfo.H.
Constructor & Destructor Documentation
memInfo()
memInfo ()
Construct null.
Definition at line 30 of file memInfo.C.
References memInfo::update().
~memInfo()
~memInfo ()
Destructor.
Definition at line 42 of file memInfo.C.
Member Function Documentation
update()
const Foam::memInfo & update ()
Parse /proc/<pid>/status.
Definition at line 48 of file memInfo.C.
References ISstream::getLine(), IOstream::good(), Foam::name(), and Foam::pid().
Referenced by memInfo::memInfo().
peak()
int peak () const inline
Access the stored peak memory (VmPeak in /proc/<pid>/status)
The value is stored from the previous update()
Definition at line 88 of file memInfo.H.
size()
int size () const inline
Access the stored memory size (VmSize in /proc/<pid>/status)
The value is stored from the previous update()
Definition at line 95 of file memInfo.H.
Referenced by indexedOctree< Foam::treeDataFace >::indexedOctree().
rss()
int rss () const inline
Access the stored rss value (VmRSS in /proc/<pid>/status)
The value is stored from the previous update()
Definition at line 102 of file memInfo.H.
valid()
bool valid () const
True if the memory information appears valid.
Definition at line 82 of file memInfo.C.
References token::BEGIN_LIST, IOstream::check(), token::END_LIST, Foam::operator<<(), Foam::operator>>(), Istream::readBegin(), Istream::readEnd(), and token::SPACE.
Referenced by vtkPV3Foam::printMemory(), and vtkPV4Foam::printMemory().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , memInfo &) friend
Read peak/size/rss from stream.
operator<<
Ostream& operator<< (Ostream & , const memInfo &) friend
Write peak/size/rss to stream.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/memInfo/memInfo.H
src/OSspecific/POSIX/memInfo/memInfo.C
src/OSspecific/POSIX/memInfo/memInfoIO.C