OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
calcType Class Reference
Base class for post-processing calculation functions.
Public Member Functions
TypeName ("calcType")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, calcType, dictionary,(),())
calcType ()
Construct null.
virtual ~calcType ()
Destructor.
void tryInit ()
Initialise - typically setting static variables,.
void tryPreCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Pre-time loop calculations.
void tryCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Time loop calculations.
void tryPostCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Post-time loop calculations.
Static Public Member Functions
static autoPtr< calcType > New (const word &calcTypeName)
Protected Member Functions
virtual void init ()
Initialise - typically setting static variables,.
virtual void preCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Pre-time loop calculations.
virtual void calc (const argList &args, const Time &runTime, const fvMesh &mesh)
Time loop calculations.
virtual void postCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Post-time loop calculations.
Detailed Description
Base class for post-processing calculation functions.
Source files
calcType.H
calcType.C
Definition at line 58 of file calcType.H.
Constructor & Destructor Documentation
calcType()
calcType ()
Construct null.
Definition at line 37 of file calcType.C.
~calcType()
~calcType () virtual
Destructor.
Definition at line 43 of file calcType.C.
Member Function Documentation
init()
void init () protected virtual
Initialise - typically setting static variables,.
e.g. command line arguments
Reimplemented in addSubtract, components, div, magGrad, randomise, interpolate, mag, and magSqr.
Definition at line 49 of file calcType.C.
References calcType::preCalc().
Referenced by calcType::tryInit().
preCalc()
void preCalc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Pre-time loop calculations.
Reimplemented in addSubtract, components, div, magGrad, randomise, interpolate, mag, and magSqr.
Definition at line 56 of file calcType.C.
References calcType::calc().
Referenced by calcType::init(), and calcType::tryPreCalc().
calc()
void calc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Time loop calculations.
Reimplemented in addSubtract, components, div, magGrad, randomise, interpolate, mag, and magSqr.
Definition at line 67 of file calcType.C.
References calcType::postCalc().
Referenced by calcType::preCalc(), and calcType::tryCalc().
postCalc()
void postCalc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Post-time loop calculations.
Definition at line 78 of file calcType.C.
Referenced by calcType::calc(), and calcType::tryPostCalc().
TypeName()
TypeName ("calcType")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , calcType , dictionary , () , ())
New()
Foam::autoPtr< Foam::calcType > New (const word & calcTypeName) static
Definition at line 31 of file calcTypeNew.C.
References Foam::abort(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
tryInit()
void tryInit ()
Initialise - typically setting static variables,.
e.g. command line arguments
Definition at line 90 of file calcType.C.
References Foam::endl(), Foam::FatalIOError, calcType::init(), error::throwExceptions(), calcType::tryPreCalc(), and Foam::Warning.
tryPreCalc()
void tryPreCalc (const argList & args, const Time & runTime, const fvMesh & mesh)
Pre-time loop calculations.
Definition at line 106 of file calcType.C.
References Foam::endl(), Foam::FatalIOError, calcType::preCalc(), error::throwExceptions(), calcType::tryCalc(), and Foam::Warning.
Referenced by calcType::tryInit().
tryCalc()
void tryCalc (const argList & args, const Time & runTime, const fvMesh & mesh)
Time loop calculations.
Definition at line 126 of file calcType.C.
References calcType::calc(), Foam::endl(), Foam::FatalIOError, error::throwExceptions(), calcType::tryPostCalc(), and Foam::Warning.
Referenced by calcType::tryPreCalc().
tryPostCalc()
void tryPostCalc (const argList & args, const Time & runTime, const fvMesh & mesh)
Post-time loop calculations.
Definition at line 146 of file calcType.C.
References Foam::endl(), Foam::FatalIOError, calcType::postCalc(), error::throwExceptions(), and Foam::Warning.
Referenced by calcType::tryCalc().
The documentation for this class was generated from the following files:
src/postProcessing/foamCalcFunctions/calcType/calcType.H
src/postProcessing/foamCalcFunctions/calcType/calcType.C
src/postProcessing/foamCalcFunctions/calcType/calcTypeNew.C