OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointFieldReconstructor Class Reference
Point field reconstructor.
Classes
class pointPatchFieldReconstructor
Public Member Functions
pointFieldReconstructor (const pointMesh &mesh, const PtrList< pointMesh > &procMeshes, const PtrList< labelIOList > &pointProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
Construct from components.
label nReconstructed () const
Return number of fields reconstructed.
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > reconstructField (const IOobject &fieldIoObject)
Reconstruct field.
template<class Type >
void reconstructFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Reconstruct and write all fields.
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::pointPatchField, Foam::pointMesh > > reconstructField (const IOobject &fieldIoObject)
Detailed Description
Point field reconstructor.
Source files
pointFieldReconstructor.H
pointFieldReconstructor.C
Definition at line 51 of file pointFieldReconstructor.H.
Constructor & Destructor Documentation
pointFieldReconstructor()
pointFieldReconstructor (const pointMesh & mesh, const PtrList< pointMesh > & procMeshes, const PtrList< labelIOList > & pointProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Construct from components.
Definition at line 31 of file pointFieldReconstructor.C.
References Foam::abort(), pointMesh::boundary(), Foam::FatalError, FatalErrorIn, forAll, Foam::min(), patchi, List< T >::setSize(), List< T >::size(), and PtrList< T >::size().
Member Function Documentation
nReconstructed()
label nReconstructed () const inline
Return number of fields reconstructed.
Definition at line 141 of file pointFieldReconstructor.H.
References pointFieldReconstructor::reconstructField(), and pointFieldReconstructor::reconstructFields().
reconstructField() [1/2]
tmp<GeometricField<Type, pointPatchField, pointMesh> > reconstructField (const IOobject & fieldIoObject)
Reconstruct field.
Referenced by pointFieldReconstructor::nReconstructed().
reconstructFields()
void reconstructFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Reconstruct and write all fields.
Definition at line 144 of file pointFieldReconstructorReconstructFields.C.
References Foam::endl(), fields, forAllConstIter(), HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), HashTable< nil, Key, Hash >::size(), HashTable< T, Key, Hash >::size(), and Ostream::write().
Referenced by pointFieldReconstructor::nReconstructed(), and pointFieldReconstructor::reconstructField().
reconstructField() [2/2]
Foam::tmp<Foam::GeometricField<Type, Foam::pointPatchField, Foam::pointMesh> > reconstructField (const IOobject & fieldIoObject)
Definition at line 32 of file pointFieldReconstructorReconstructFields.C.
References pointMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), IOobject::MUST_READ, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), patchi, pointFieldReconstructor::reconstructFields(), pointMesh::size(), PtrList< T >::size(), IOobject::time(), and Time::timeName().
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/pointFieldReconstructor.H
src/parallel/reconstruct/reconstruct/pointFieldReconstructor.C
src/parallel/reconstruct/reconstruct/pointFieldReconstructorReconstructFields.C