OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readFields Class Reference
Function objects » Field function objects
This function object reads fields from the time directories and adds them to the mesh database for further post-processing.
Public Member Functions
TypeName ("readFields")
Runtime type information.
readFields (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~readFields ()
Destructor.
virtual const word & name () const
Return name of the readFields object.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
readFields (const readFields &)
Disallow default bitwise copy construct.
void operator= (const readFields &)
Disallow default bitwise assignment.
template<class Type >
void loadField (const word &, PtrList< GeometricField< Type, fvPatchField, volMesh > > &, PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
Protected Attributes
word name_
Name of this set of readFields object.
const objectRegistry & obr_
bool active_
on/off switch
wordList fieldSet_
Fields to load.
PtrList< volScalarField > vsf_
Loaded fields.
PtrList< volVectorField > vvf_
PtrList< volSphericalTensorField > vSpheretf_
PtrList< volSymmTensorField > vSymmtf_
PtrList< volTensorField > vtf_
PtrList< surfaceScalarField > ssf_
PtrList< surfaceVectorField > svf_
PtrList< surfaceSphericalTensorField > sSpheretf_
PtrList< surfaceSymmTensorField > sSymmtf_
PtrList< surfaceTensorField > stf_
Detailed Description
This function object reads fields from the time directories and adds them to the mesh database for further post-processing.
Example of function object specification:
readFields1
{
    type        readFields;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    fields
    (
        U
        p
    );
}
Function object usage
Property Description Required Default value
type type name: readFields yes
fields list of fields to read no
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
readFields.H
readFields.C
IOreadFields.H
Definition at line 102 of file readFields.H.
Constructor & Destructor Documentation
readFields() [1/2]
readFields (const readFields &) protected
Disallow default bitwise copy construct.
readFields() [2/2]
readFields (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 40 of file readFields.C.
References Foam::endl(), and WarningIn.
~readFields()
~readFields () virtual
Destructor.
Definition at line 77 of file readFields.C.
Member Function Documentation
operator=()
void operator= (const readFields &) protected
Disallow default bitwise assignment.
loadField()
void loadField (const word & fieldName, PtrList< GeometricField< Type, fvPatchField, volMesh > > & vflds, PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > & sflds) const protected
Definition at line 35 of file readFieldsTemplates.C.
References Foam::endl(), Foam::Info, mesh, fvMesh::time(), and Time::timeName().
TypeName()
TypeName ("readFields")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the readFields object.
Definition at line 176 of file readFields.H.
References readFields::end(), readFields::execute(), readFields::name_, readFields::read(), readFields::timeSet(), and readFields::write().
read()
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 83 of file readFields.C.
References dictionary::lookup().
Referenced by readFields::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 92 of file readFields.C.
References forAll.
Referenced by readFields::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 124 of file readFields.C.
Referenced by readFields::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 133 of file readFields.C.
Referenced by readFields::name().
write()
void write () virtual
Write.
Definition at line 139 of file readFields.C.
Referenced by readFields::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 197 of file readFields.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 201 of file readFields.H.
Member Data Documentation
name_
word name_ protected
Name of this set of readFields object.
Definition at line 109 of file readFields.H.
Referenced by readFields::name().
obr_
const objectRegistry& obr_ protected
Definition at line 111 of file readFields.H.
active_
bool active_ protected
on/off switch
Definition at line 114 of file readFields.H.
fieldSet_
wordList fieldSet_ protected
Fields to load.
Definition at line 117 of file readFields.H.
vsf_
PtrList<volScalarField> vsf_ protected
Loaded fields.
Definition at line 120 of file readFields.H.
vvf_
PtrList<volVectorField> vvf_ protected
Definition at line 121 of file readFields.H.
vSpheretf_
PtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 122 of file readFields.H.
vSymmtf_
PtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 123 of file readFields.H.
vtf_
PtrList<volTensorField> vtf_ protected
Definition at line 124 of file readFields.H.
ssf_
PtrList<surfaceScalarField> ssf_ protected
Definition at line 126 of file readFields.H.
svf_
PtrList<surfaceVectorField> svf_ protected
Definition at line 127 of file readFields.H.
sSpheretf_
PtrList<surfaceSphericalTensorField> sSpheretf_ protected
Definition at line 128 of file readFields.H.
sSymmtf_
PtrList<surfaceSymmTensorField> sSymmtf_ protected
Definition at line 129 of file readFields.H.
stf_
PtrList<surfaceTensorField> stf_ protected
Definition at line 130 of file readFields.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/readFields/readFields.H
src/postProcessing/functionObjects/field/readFields/readFields.C
src/postProcessing/functionObjects/field/readFields/readFieldsTemplates.C