OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
faceSource Class Reference
Function objects » Field function objects
This function object provides a 'face source' variant of the fieldValues function object. Given a list of user-specified fields and a selection of mesh (or general surface) faces, a number of operations can be performed, such as sums, averages and integrations.
Public Types
enum sourceType { stFaceZone, stPatch, stSampledSurface }
Source type enumeration.
enum operationType {
opNone, opSum, opSumMag, opSumDirection,
opSumDirectionBalance, opAverage, opWeightedAverage, opAreaAverage,
opAreaIntegrate, opMin, opMax, opCoV,
opAreaNormalAverage, opAreaNormalIntegrate
}
Operation type enumeration.
Public Member Functions
TypeName ("faceSource")
Run-time type information.
faceSource (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false)
Construct from components.
virtual ~faceSource ()
Destructor.
const sourceType & source () const
Return the source type.
const labelList & faceId () const
Return the local list of face IDs.
const labelList & facePatch () const
Return the local list of patch ID per face.
const labelList & faceSign () const
Return the list of +1/-1 representing face flip map.
virtual void read (const dictionary &)
Read from dictionary.
virtual void write ()
Calculate and write.
template<class Type >
bool writeValues (const word &fieldName, const scalarField &weightField, const bool orient)
Templated helper function to output field values.
template<class Type >
tmp< Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field, const bool applyOrientation) const
Filter a surface field according to faceIds.
template<class Type >
tmp< Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool applyOrientation) const
Filter a volume field according to faceIds.
template<>
Foam::scalar processValues (const Field< scalar > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
Foam::vector processValues (const Field< vector > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
scalar processValues (const Field< scalar > &values, const vectorField &Sf, const scalarField &weightField) const
Specialisation of processing scalars.
template<>
vector processValues (const Field< vector > &values, const vectorField &Sf, const scalarField &weightField) const
Specialisation of processing vectors.
template<class Type >
Foam::tmp< Foam::Field< Type > > getFieldValues (const word &fieldName, const bool mustGet, const bool applyOrientation) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool applyOrientation) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field, const bool applyOrientation) const
Public Member Functions inherited from fieldValue
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, fieldValue, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles),(name, obr, dict, loadFromFiles))
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType, const bool loadFromFiles=false)
Construct from components.
virtual ~fieldValue ()
Destructor.
const word & name () const
Return the name of the geometric source.
const objectRegistry & obr () const
Return the reference to the object registry.
const dictionary & dict () const
Return the reference to the construction dictionary.
bool active () const
Return the active flag.
const Switch & log () const
Return the switch to send output to Info as well as to file.
const word & sourceName () const
Return the source name.
const wordList & fields () const
Return the list of field names.
const Switch & valueOutput () const
Return the output field values flag.
const fvMesh & mesh () const
Helper function to return the reference to the mesh.
const dictionary & resultDict () const
Return access to the latest set of results.
virtual void execute ()
Execute.
virtual void end ()
Execute the at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void updateMesh (const mapPolyMesh &)
Update mesh.
virtual void movePoints (const polyMesh &)
Move points.
template<class Type >
void combineFields (Field< Type > &field)
Combine fields from all processor domains into single field.
template<class Type >
void combineFields (tmp< Field< Type > > &)
Combine fields from all processor domains into single field.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const NamedEnum< sourceType, 3 > sourceTypeNames_
Source type names.
static const NamedEnum< operationType, 14 > operationTypeNames_
Operation type names.
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions
void initialise (const dictionary &dict)
Initialise, e.g. face addressing.
template<class Type >
bool validField (const word &fieldName) const
Return true if the field name is valid.
template<class Type >
tmp< Field< Type > > getFieldValues (const word &fieldName, const bool mustGet=false, const bool applyOrientation=false) const
Return field values by looking up field name.
template<class Type >
Type processSameTypeValues (const Field< Type > &values, const vectorField &Sf, const scalarField &weightField) const
Apply the 'operation' to the values. Operation has to.
template<class Type >
Type processValues (const Field< Type > &values, const vectorField &Sf, const scalarField &weightField) const
Apply the 'operation' to the values. Wrapper around.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
autoPtr< surfaceWriter > surfaceWriterPtr_
Surface writer.
sourceType source_
Source type.
operationType operation_
Operation to apply to values.
word weightFieldName_
Weight field name - optional.
bool orientWeightField_
Flag to indicate if flipMap should be applied to the weight field.
label orientedFieldsStart_
Start index of fields that require application of flipMap.
scalar scaleFactor_
Scale factor - optional.
scalar totalArea_
Total area of the faceSource.
bool writeArea_
Optionally write the area of the faceSource.
label nFaces_
Global number of faces.
labelList faceId_
Local list of face IDs.
labelList facePatchId_
Local list of patch ID per face.
labelList faceSign_
List of +1/-1 representing face flip map.
autoPtr< sampledSurface > surfacePtr_
Underlying sampledSurface.
Protected Attributes inherited from fieldValue
word name_
Name of this fieldValue object.
const objectRegistry & obr_
Database this class is registered to.
dictionary dict_
Construction dictionary.
bool active_
Active flag.
Switch log_
Switch to send output to Info as well as to file.
word sourceName_
Name of source object.
wordList fields_
List of field names to operate on.
Switch valueOutput_
Output field values flag.
dictionary resultDict_
Results dictionary for external access of results.
Additional Inherited Members
Static Public Member Functions inherited from fieldValue
static autoPtr< fieldValue > New (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false, const bool output=true)
Return a reference to the selected fieldValue.
Detailed Description
This function object provides a 'face source' variant of the fieldValues function object. Given a list of user-specified fields and a selection of mesh (or general surface) faces, a number of operations can be performed, such as sums, averages and integrations.
For example, to calculate the volumetric or mass flux across a patch, apply the 'sum' operator to the flux field (typically phi)
Example of function object specification:
faceSource1
{
    type            faceSource;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    log             yes;
    valueOutput     true;
    surfaceFormat   none;
    source          faceZone;
    sourceName      f0;
    operation       sum;
    weightField     alpha1;
    fields
    (
        p
        phi
        U
    );
}
Function object usage
Property Description Required Default value
type type name: faceSource yes
log write data to standard output no no
valueOutput write the output values yes
writeArea Write the area of the faceSource no
surfaceFormat output value format no
source face source: see below yes
sourceName name of face source if required no
operation operation to perform yes
weightField name of field to apply weighting no
orientedWeightField name of oriented field to apply weighting no
scaleFactor scale factor no 1
fields list of fields to operate on yes
orientedFields list of oriented fields to operate on no
Where source is defined by
faceZone : requires a 'sourceName' entry to specify the faceZone
patch : requires a 'sourceName' entry to specify the patch
sampledSurface : requires a 'sampledSurfaceDict' sub-dictionary
The operation is one of:
none : no operation
sum : sum
sumMag : sum of component magnitudes
sumDirection : sum values which are positive in given direction
sumDirectionBalance : sum of balance of values in given direction
average : ensemble average
weightedAverage : weighted average
areaAverage : area weighted average
areaIntegrate : area integral
min : minimum
max : maximum
CoV : coefficient of variation: standard deviation/mean
areaNormalAverage : area weighted average in face normal direction
areaNormalIntegrate : area weighted integral in face normal directon
Note
The values reported by the areaNormalAverage and areaNormalIntegrate operations are written as the first component of a field with the same rank as the input field.
faces on empty patches get ignored
if the field is a volField the faceZone can only consist of boundary faces
the `oriented' entries relate to mesh-oriented fields, such as the flux, phi. These fields will be oriented according to the face normals.
using sampledSurfaces:
not available for surface fields
if interpolate=true they use interpolationCellPoint otherwise they use cell values
each triangle in sampledSurface is logically only in one cell so interpolation will be wrong when triangles are larger than cells. This can only happen for sampling on a triSurfaceMesh
take care when using isoSurfaces - these might have duplicate triangles and so integration might be wrong
See also
Foam::fieldValues Foam::functionObject Foam::OutputFilterFunctionObject
Source files
faceSource.H
faceSource.C
faceSourceTemplates.C
Definition at line 298 of file faceSource.H.
Member Enumeration Documentation
sourceType
enum sourceType
Source type enumeration.
Enumerator
stFaceZone
stPatch
stSampledSurface
Definition at line 308 of file faceSource.H.
operationType
enum operationType
Operation type enumeration.
Enumerator
opNone
opSum
opSumMag
opSumDirection
opSumDirectionBalance
opAverage
opWeightedAverage
opAreaAverage
opAreaIntegrate
opMin
opMax
opCoV
opAreaNormalAverage
opAreaNormalIntegrate
Definition at line 320 of file faceSource.H.
Constructor & Destructor Documentation
faceSource()
faceSource (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct from components.
Definition at line 637 of file faceSource.C.
Referenced by faceSource::processValues().
~faceSource()
~faceSource () virtual
Destructor.
Definition at line 664 of file faceSource.C.
Member Function Documentation
initialise()
void initialise (const dictionary & dict) protected
Initialise, e.g. face addressing.
Definition at line 400 of file faceSource.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::FatalIOError, FatalIOErrorIn, dictionary::found(), Foam::Info, dictionary::lookup(), surfaceWriter::New(), Foam::nl, dictionary::readIfPresent(), List< T >::size(), dictionary::subOrEmptyDict(), Foam::type(), and WarningIn.
validField()
bool validField (const word & fieldName) const protected
Return true if the field name is valid.
Definition at line 35 of file faceSourceTemplates.C.
References objectRegistry::foundObject(), faceSource::getFieldValues(), fieldValue::obr_, sf(), faceSource::source_, and faceSource::stSampledSurface.
getFieldValues() [1/2]
tmp<Field<Type> > getFieldValues (const word & fieldName, const bool mustGet = false, const bool applyOrientation = false) const protected
Return field values by looking up field name.
Referenced by faceSource::validField().
processSameTypeValues()
Type processSameTypeValues (const Field< Type > & values, const vectorField & Sf, const scalarField & weightField) const protected
Apply the 'operation' to the values. Operation has to.
preserve Type.
Definition at line 132 of file faceSourceTemplates.C.
References Foam::cmptMag(), Foam::component(), Field< Type >::component(), d(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::mag(), Foam::max(), Foam::min(), faceSource::opAreaAverage, faceSource::opAreaIntegrate, faceSource::opAverage, faceSource::opCoV, faceSource::operation_, faceSource::operationTypeNames_, faceSource::opMax, faceSource::opMin, faceSource::opSum, faceSource::opSumDirection, faceSource::opSumDirectionBalance, faceSource::opSumMag, faceSource::opWeightedAverage, faceSource::processValues(), Foam::setComponent(), List< Type >::size(), List< T >::size(), Foam::sqr(), Foam::sqrt(), and Foam::sum().
Referenced by faceSource::getFieldValues(), and faceSource::processValues().
processValues() [1/5]
Type processValues (const Field< Type > & values, const vectorField & Sf, const scalarField & weightField) const protected
Apply the 'operation' to the values. Wrapper around.
processSameTypeValues. See also template specialisation below.
Definition at line 263 of file faceSourceTemplates.C.
References faceSource::processSameTypeValues(), and faceSource::writeValues().
Referenced by faceSource::processSameTypeValues(), faceSource::processValues(), faceSource::writeFileHeader(), and faceSource::writeValues().
writeFileHeader()
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from functionObjectFile.
Definition at line 532 of file faceSource.C.
References Foam::endl(), forAll, faceSource::processValues(), and Foam::tab.
TypeName()
TypeName ("faceSource")
Run-time type information.
source()
const Foam::fieldValues::faceSource::sourceType & source () const inline
Return the source type.
Definition at line 31 of file faceSourceI.H.
References faceSource::source_.
faceId()
const Foam::labelList & faceId () const inline
Return the local list of face IDs.
Definition at line 38 of file faceSourceI.H.
References faceSource::faceId_.
facePatch()
const Foam::labelList & facePatch () const inline
Return the local list of patch ID per face.
Definition at line 45 of file faceSourceI.H.
References faceSource::facePatchId_.
faceSign()
const Foam::labelList & faceSign () const inline
Return the list of +1/-1 representing face flip map.
Definition at line 52 of file faceSourceI.H.
References faceSource::faceSign_.
read()
void read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented from fieldValue.
Definition at line 670 of file faceSource.C.
References fieldValue::read().
write()
void write () virtual
Calculate and write.
Reimplemented from fieldValue.
Definition at line 681 of file faceSource.C.
References Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::tab, WarningIn, and fieldValue::write().
writeValues()
bool writeValues (const word & fieldName, const scalarField & weightField, const bool orient)
Templated helper function to output field values.
Definition at line 278 of file faceSourceTemplates.C.
References dictionary::add(), functionObjectFile::baseFileDir(), fieldValue::combineFields(), Foam::endl(), functionObjectFile::file(), faceSource::filterField(), Foam::Info, fieldValue::log_, UPstream::master(), fieldValue::mesh(), fieldValue::name_, fieldValue::obr_, faceSource::operation_, faceSource::operationTypeNames_, points, faceSource::processValues(), fieldValue::resultDict_, faceSource::scaleFactor_, List< T >::size(), faceSource::source_, fieldValue::sourceName_, faceSource::sourceTypeNames_, faceSource::surfacePtr_, faceSource::surfaceWriterPtr_, Foam::tab, objectRegistry::time(), and Time::timeName().
Referenced by faceSource::processValues().
filterField() [1/4]
tmp<Field<Type> > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field, const bool applyOrientation) const
Filter a surface field according to faceIds.
Referenced by faceSource::filterField(), faceSource::getFieldValues(), and faceSource::writeValues().
filterField() [2/4]
tmp<Field<Type> > filterField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool applyOrientation) const
Filter a volume field according to faceIds.
processValues() [2/5]
Foam::scalar processValues (const Field< scalar > & values, const vectorField & Sf, const scalarField & weightField) const
Definition at line 560 of file faceSource.C.
References Foam::mag(), n, Foam::neg(), Foam::pos(), faceSource::processValues(), and Foam::sum().
processValues() [3/5]
Foam::vector processValues (const Field< vector > & values, const vectorField & Sf, const scalarField & weightField) const
Definition at line 591 of file faceSource.C.
References faceSource::faceSource(), Foam::mag(), n, Foam::pos(), and Foam::sum().
processValues() [4/5]
scalar processValues (const Field< scalar > & values, const vectorField & Sf, const scalarField & weightField) const
Specialisation of processing scalars.
processValues() [5/5]
vector processValues (const Field< vector > & values, const vectorField & Sf, const scalarField & weightField) const
Specialisation of processing vectors.
getFieldValues() [2/2]
Foam::tmp<Foam::Field<Type> > getFieldValues (const word & fieldName, const bool mustGet, const bool applyOrientation) const
Definition at line 55 of file faceSourceTemplates.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorIn, faceSource::filterField(), fld(), forAll, objectRegistry::foundObject(), Foam::interpolate(), objectRegistry::lookupObject(), fieldValue::obr_, faceSource::processSameTypeValues(), sf(), List< T >::size(), faceSource::source_, faceSource::stSampledSurface, and faceSource::surfacePtr_.
filterField() [3/4]
Foam::tmp<Foam::Field<Type> > filterField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool applyOrientation) const
Definition at line 368 of file faceSourceTemplates.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), faceSource::faceId_, faceSource::facePatchId_, faceSource::faceSign_, Foam::FatalError, FatalErrorIn, faceSource::filterField(), forAll, IOobject::name(), fieldValue::name_, Foam::nl, List< T >::size(), faceSource::source_, fieldValue::sourceName_, faceSource::sourceTypeNames_, and Foam::type().
filterField() [4/4]
Foam::tmp<Foam::Field<Type> > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field, const bool applyOrientation) const
Definition at line 415 of file faceSourceTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), faceSource::faceId_, faceSource::facePatchId_, faceSource::faceSign_, forAll, and List< T >::size().
Member Data Documentation
sourceTypeNames_
const Foam::NamedEnum< Foam::fieldValues::faceSource::sourceType, 3 > sourceTypeNames_ static
Source type names.
Definition at line 316 of file faceSource.H.
Referenced by faceSource::filterField(), NamedEnum< directionType, 3 >::names(), and faceSource::writeValues().
operationTypeNames_
const Foam::NamedEnum< Foam::fieldValues::faceSource::operationType, 14 > operationTypeNames_ static
Operation type names.
Definition at line 339 of file faceSource.H.
Referenced by NamedEnum< directionType, 3 >::names(), faceSource::processSameTypeValues(), and faceSource::writeValues().
surfaceWriterPtr_
autoPtr<surfaceWriter> surfaceWriterPtr_ protected
Surface writer.
Definition at line 378 of file faceSource.H.
Referenced by faceSource::writeValues().
source_
sourceType source_ protected
Source type.
Definition at line 381 of file faceSource.H.
Referenced by faceSource::filterField(), faceSource::getFieldValues(), faceSource::source(), faceSource::validField(), and faceSource::writeValues().
operation_
operationType operation_ protected
Operation to apply to values.
Definition at line 384 of file faceSource.H.
Referenced by faceSource::processSameTypeValues(), and faceSource::writeValues().
weightFieldName_
word weightFieldName_ protected
Weight field name - optional.
Definition at line 387 of file faceSource.H.
orientWeightField_
bool orientWeightField_ protected
Flag to indicate if flipMap should be applied to the weight field.
Definition at line 390 of file faceSource.H.
orientedFieldsStart_
label orientedFieldsStart_ protected
Start index of fields that require application of flipMap.
Definition at line 393 of file faceSource.H.
scaleFactor_
scalar scaleFactor_ protected
Scale factor - optional.
Definition at line 396 of file faceSource.H.
Referenced by faceSource::writeValues().
totalArea_
scalar totalArea_ protected
Total area of the faceSource.
Definition at line 399 of file faceSource.H.
writeArea_
bool writeArea_ protected
Optionally write the area of the faceSource.
Definition at line 402 of file faceSource.H.
nFaces_
label nFaces_ protected
Global number of faces.
Definition at line 405 of file faceSource.H.
faceId_
labelList faceId_ protected
Local list of face IDs.
Definition at line 411 of file faceSource.H.
Referenced by faceSource::faceId(), and faceSource::filterField().
facePatchId_
labelList facePatchId_ protected
Local list of patch ID per face.
Definition at line 414 of file faceSource.H.
Referenced by faceSource::facePatch(), and faceSource::filterField().
faceSign_
labelList faceSign_ protected
List of +1/-1 representing face flip map.
(1 use as is, -1 negate)
Definition at line 418 of file faceSource.H.
Referenced by faceSource::faceSign(), and faceSource::filterField().
surfacePtr_
autoPtr<sampledSurface> surfacePtr_ protected
Underlying sampledSurface.
Definition at line 424 of file faceSource.H.
Referenced by faceSource::getFieldValues(), and faceSource::writeValues().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldValues/faceSource/faceSource.H
src/postProcessing/functionObjects/field/fieldValues/faceSource/faceSource.C
src/postProcessing/functionObjects/field/fieldValues/faceSource/faceSourceI.H
src/postProcessing/functionObjects/field/fieldValues/faceSource/faceSourceTemplates.C