OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldValueDelta Class Reference
Function objects » Field function objects
This function object provides a differencing option between two 'field value' function objects.
Public Types
enum operationType {
opAdd, opSubtract, opMin, opMax,
opAverage
}
Operation type enumeration.
Public Member Functions
TypeName ("fieldValueDelta")
Run-time type information.
fieldValueDelta (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false)
Construct from components.
virtual ~fieldValueDelta ()
Destructor.
virtual void read (const dictionary &)
Read from dictionary.
virtual void write ()
Calculate and write.
virtual void execute ()
Execute.
virtual void end ()
Execute the at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void updateMesh (const mapPolyMesh &)
Update mesh.
virtual void movePoints (const polyMesh &)
Move points.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const NamedEnum< operationType, 5 > operationTypeNames_
Operation type names.
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Detailed Description
This function object provides a differencing option between two 'field value' function objects.
Example of function object specification:
fieldValueDelta1
{
    type            fieldValueDelta;
    functionObjectLibs ("libfieldFunctionObjects.so");
    operation       subtract;
    fieldValue1
    {
        ...
    }
    fieldValue2
    {
        ...
    }
}
Function object usage
Property Description Required Default value
type type name: fieldValueDelta yes
The operation is one of:
add : add
subtract : subtract
min : minimum
max : maximum
average : average
See also
Foam::fieldValue
Source files
fieldValueDelta.H
fieldValueDelta.C
Definition at line 124 of file fieldValueDelta.H.
Member Enumeration Documentation
operationType
enum operationType
Operation type enumeration.
Enumerator
opAdd
opSubtract
opMin
opMax
opAverage
Definition at line 130 of file fieldValueDelta.H.
Constructor & Destructor Documentation
fieldValueDelta()
fieldValueDelta (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct from components.
Definition at line 60 of file fieldValueDelta.C.
Referenced by NamedEnum< directionType, 3 >::names().
~fieldValueDelta()
~fieldValueDelta () virtual
Destructor.
Definition at line 113 of file fieldValueDelta.C.
Member Function Documentation
writeFileHeader()
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from functionObjectFile.
Definition at line 80 of file fieldValueDelta.C.
References Foam::endl(), Foam::findIndex(), forAll, IOstream::name(), List< T >::size(), and Foam::tab.
TypeName()
TypeName ("fieldValueDelta")
Run-time type information.
read()
void read (const dictionary & dict) virtual
Read from dictionary.
Definition at line 119 of file fieldValueDelta.C.
References dictionary::lookup(), dictionary::lookupOrDefault(), fieldValue::New(), and dictionary::subDict().
write()
void write () virtual
Calculate and write.
Reimplemented from functionObjectFile.
Definition at line 149 of file fieldValueDelta.C.
References Foam::endl(), found, Foam::Info, UPstream::master(), Foam::type(), and functionObjectFile::write().
execute()
void execute () virtual
Execute.
Definition at line 189 of file fieldValueDelta.C.
end()
void end () virtual
Execute the at the final time-loop, currently does nothing.
Definition at line 195 of file fieldValueDelta.C.
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 201 of file fieldValueDelta.C.
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Update mesh.
Definition at line 207 of file fieldValueDelta.C.
movePoints()
void movePoints (const polyMesh &) virtual
Move points.
Definition at line 213 of file fieldValueDelta.C.
Member Data Documentation
operationTypeNames_
const NamedEnum< fieldValues::fieldValueDelta::operationType, 5 > operationTypeNames_ static
Operation type names.
Definition at line 140 of file fieldValueDelta.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldValues/fieldValueDelta/fieldValueDelta.H
src/postProcessing/functionObjects/field/fieldValues/fieldValueDelta/fieldValueDelta.C
src/postProcessing/functionObjects/field/fieldValues/fieldValueDelta/fieldValueDeltaTemplates.C