OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldAverageItem Class Reference
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
Public Types
enum baseType { ITER, TIME }
Enumeration defining the averaging base type.
Public Member Functions
fieldAverageItem ()
Construct null.
fieldAverageItem (Istream &)
Construct from Istream.
fieldAverageItem (const fieldAverageItem &)
Construct as copy.
~fieldAverageItem ()
Destructor.
const Switch & active () const
Return const access to the active flag.
Switch & active ()
Return non-const access to the active flag.
const word & fieldName () const
Return const access to the field name.
const Switch & mean () const
Return const access to the mean flag.
Switch & mean ()
Return non-const access to the mean flag.
const word & meanFieldName () const
Return const access to the mean field name.
const Switch & prime2Mean () const
Return const access to the prime-squared mean flag.
Switch & prime2Mean ()
Return non-const access to the prime-squared mean flag.
const word & prime2MeanFieldName () const
Return const access to the prime-squared mean field name.
const word base () const
Return averaging base type name.
Switch iterBase () const
Return true if base is ITER.
Switch timeBase () const
Return true if base is time.
scalar window () const
const word & windowName () const
void operator= (const fieldAverageItem &)
Static Public Attributes
static const word EXT_MEAN = "Mean"
Mean average.
static const word EXT_PRIME2MEAN = "Prime2Mean"
Prime-squared average.
Friends
bool operator== (const fieldAverageItem &a, const fieldAverageItem &b)
bool operator!= (const fieldAverageItem &a, const fieldAverageItem &b)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
Detailed Description
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
{
    mean            on;
    prime2Mean      on;
    base            time; // iteration
    window          200;  // optional averaging window
    windowName      w1;   // optional window name (default = "")
}
The averaging window corresponds to the averaging interval (iters or time) If not specified, the averaging is over 'all iters/time'
Source files
fieldAverageItem.H
fieldAverageItem.C
fieldAverageItemIO.C
Definition at line 74 of file fieldAverageItem.H.
Member Enumeration Documentation
baseType
enum baseType
Enumeration defining the averaging base type.
Enumerator
ITER
TIME
Definition at line 89 of file fieldAverageItem.H.
Constructor & Destructor Documentation
fieldAverageItem() [1/3]
fieldAverageItem ()
Construct null.
Definition at line 54 of file fieldAverageItem.C.
fieldAverageItem() [2/3]
fieldAverageItem (Istream & is)
Construct from Istream.
Definition at line 32 of file fieldAverageItemIO.C.
References IOstream::check(), fieldAverageItem::EXT_MEAN, fieldAverageItem::EXT_PRIME2MEAN, entry::keyword(), dictionary::lookup(), dictionary::lookupOrDefault(), and dictionary::null.
fieldAverageItem() [3/3]
fieldAverageItem (const fieldAverageItem & faItem)
Construct as copy.
Definition at line 68 of file fieldAverageItem.C.
~fieldAverageItem()
~fieldAverageItem ()
Destructor.
Definition at line 84 of file fieldAverageItem.C.
Member Function Documentation
active() [1/2]
const Switch& active () const inline
Return const access to the active flag.
Definition at line 154 of file fieldAverageItem.H.
active() [2/2]
Switch& active () inline
Return non-const access to the active flag.
Definition at line 160 of file fieldAverageItem.H.
fieldName()
const word& fieldName () const inline
Return const access to the field name.
Definition at line 166 of file fieldAverageItem.H.
mean() [1/2]
const Switch& mean () const inline
Return const access to the mean flag.
Definition at line 172 of file fieldAverageItem.H.
mean() [2/2]
Switch& mean () inline
Return non-const access to the mean flag.
Definition at line 178 of file fieldAverageItem.H.
meanFieldName()
const word& meanFieldName () const inline
Return const access to the mean field name.
Definition at line 184 of file fieldAverageItem.H.
prime2Mean() [1/2]
const Switch& prime2Mean () const inline
Return const access to the prime-squared mean flag.
Definition at line 190 of file fieldAverageItem.H.
prime2Mean() [2/2]
Switch& prime2Mean () inline
Return non-const access to the prime-squared mean flag.
Definition at line 196 of file fieldAverageItem.H.
prime2MeanFieldName()
const word& prime2MeanFieldName () const inline
Return const access to the prime-squared mean field name.
Definition at line 202 of file fieldAverageItem.H.
base()
const word base () const inline
Return averaging base type name.
Definition at line 208 of file fieldAverageItem.H.
iterBase()
Switch iterBase () const inline
Return true if base is ITER.
Definition at line 214 of file fieldAverageItem.H.
References fieldAverageItem::ITER.
timeBase()
Switch timeBase () const inline
Return true if base is time.
Definition at line 220 of file fieldAverageItem.H.
References fieldAverageItem::TIME.
window()
scalar window () const inline
Definition at line 225 of file fieldAverageItem.H.
windowName()
const word& windowName () const inline
Definition at line 230 of file fieldAverageItem.H.
References fieldAverageItem::operator=().
operator=()
void operator= (const fieldAverageItem & rhs)
Definition at line 90 of file fieldAverageItem.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and Foam::nl.
Referenced by fieldAverageItem::windowName().
Friends And Related Function Documentation
operator==
bool operator== (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 244 of file fieldAverageItem.H.
operator!=
bool operator!= (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 261 of file fieldAverageItem.H.
operator>>
Istream& operator>> (Istream & , fieldAverageItem &) friend
operator<<
Ostream& operator<< (Ostream & , const fieldAverageItem &) friend
Member Data Documentation
EXT_MEAN
const word EXT_MEAN = "Mean" static
Mean average.
Definition at line 83 of file fieldAverageItem.H.
Referenced by fieldAverageItem::fieldAverageItem(), and Foam::operator>>().
EXT_PRIME2MEAN
const word EXT_PRIME2MEAN = "Prime2Mean" static
Prime-squared average.
Definition at line 86 of file fieldAverageItem.H.
Referenced by fieldAverageItem::fieldAverageItem(), and Foam::operator>>().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.H
src/postProcessing/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.C
src/postProcessing/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemIO.C