OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nearWallFields Class Reference
Function objects » Field function objects
This function object samples near-patch volume fields.
Public Member Functions
TypeName ("nearWallFields")
Runtime type information.
nearWallFields (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~nearWallFields ()
Destructor.
virtual const word & name () const
Return name of the nearWallFields object.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
void calcAddressing ()
Calculate addressing from cells back to patch faces.
template<class Type >
void createFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
template<class Type >
void sampleBoundaryField (const interpolationCellPoint< Type > &interpolator, GeometricField< Type, fvPatchField, volMesh > &fld) const
Override boundary fields with sampled values.
template<class Type >
void sampleFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
Protected Attributes
word name_
Name of this set of nearWallFields object.
const objectRegistry & obr_
bool active_
on/off switch
List< Tuple2< word, word > > fieldSet_
Fields to process.
labelHashSet patchSet_
Patches to sample.
scalar distance_
Distance away from wall.
HashTable< word > fieldMap_
From original field to sampled result.
HashTable< word > reverseFieldMap_
From resulting back to original field.
labelListList cellToWalls_
From cell to seed patch faces.
List< List< point > > cellToSamples_
From cell to tracked end point.
autoPtr< mapDistribute > getPatchDataMapPtr_
Map from cell based data back to patch based data.
PtrList< volScalarField > vsf_
PtrList< volVectorField > vvf_
PtrList< volSphericalTensorField > vSpheretf_
PtrList< volSymmTensorField > vSymmtf_
PtrList< volTensorField > vtf_
Detailed Description
This function object samples near-patch volume fields.
Fields are stored
every time step the field is updated with new values
at output it writes the fields
This functionObject can either be used
to calculate a new field as a post-processing step or
since the fields are registered, used in another functionObject
Example of function object specification:
nearWallFields1
{
    type        nearWallFields;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    fields      ((p pNear)(U UNear));
    patches     (movingWall);
    distance    0.13;
}
Function object usage
Property Description Required Default value
type type name: nearWallFields yes
fields list of fields with correspoding output field names yes
patches list of patches to sample yes
distance distance from patch to sample yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
nearWallFields.H
nearWallFields.C
IOnearWallFields.H
Definition at line 119 of file nearWallFields.H.
Constructor & Destructor Documentation
nearWallFields()
nearWallFields (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 225 of file nearWallFields.C.
References Foam::endl(), and WarningIn.
~nearWallFields()
~nearWallFields () virtual
Destructor.
Definition at line 263 of file nearWallFields.C.
References Foam::endl(), and Foam::Info.
Member Function Documentation
calcAddressing()
void calcAddressing () protected
Calculate addressing from cells back to patch faces.
Definition at line 42 of file nearWallFields.C.
References Cloud< ParticleType >::addParticle(), fvMesh::boundary(), polyMesh::bounds(), findCellParticle::end(), Foam::endl(), polyPatch::faceCellCentres(), polyMesh::FACEDIAGTETS, mappedPatchBase::facePoint(), polyMesh::findCellFacePt(), forAll, forAllConstIter(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), Foam::Info, boundBox::mag(), mesh, Cloud< ParticleType >::move(), primitiveMesh::nCells(), fvPatch::nf(), fvPatch::patch(), Time::path(), particle< Type >::position(), List< T >::setSize(), globalIndex::size(), PtrList< T >::size(), fvPatch::start(), fvMesh::time(), Time::timeName(), and globalIndex::toGlobal().
createFields()
void createFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > & sflds) const protected
Definition at line 32 of file nearWallFieldsTemplates.C.
References Foam::endl(), fld(), forAllConstIter(), Foam::Info, IOobject::readOpt(), IOobject::rename(), nearWallFields::sampleBoundaryField(), and IOobject::writeOpt().
sampleBoundaryField()
void sampleBoundaryField (const interpolationCellPoint< Type > & interpolator, GeometricField< Type, fvPatchField, volMesh > & fld) const protected
Override boundary fields with sampled values.
Definition at line 76 of file nearWallFieldsTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, forAllConstIter(), interpolationCellPoint< Type >::interpolate(), nearWallFields::sampleFields(), and List< Type >::size().
Referenced by nearWallFields::createFields().
sampleFields()
void sampleFields (PtrList< GeometricField< Type, fvPatchField, volMesh > > & sflds) const protected
Definition at line 123 of file nearWallFieldsTemplates.C.
References fld(), and forAll.
Referenced by nearWallFields::sampleBoundaryField().
TypeName()
TypeName ("nearWallFields")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the nearWallFields object.
Definition at line 232 of file nearWallFields.H.
References nearWallFields::end(), nearWallFields::execute(), nearWallFields::name_, nearWallFields::read(), nearWallFields::timeSet(), and nearWallFields::write().
read()
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 274 of file nearWallFields.C.
References polyMesh::boundaryMesh(), Foam::endl(), forAll, Foam::Info, dictionary::lookup(), mesh, polyBoundaryMesh::patchSet(), Foam::readScalar(), and Foam::type().
Referenced by nearWallFields::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 324 of file nearWallFields.C.
References Foam::endl(), Foam::Info, Foam::nl, and Foam::type().
Referenced by nearWallFields::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 370 of file nearWallFields.C.
References Foam::endl(), and Foam::Info.
Referenced by nearWallFields::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 384 of file nearWallFields.C.
Referenced by nearWallFields::name().
write()
void write () virtual
Write.
Definition at line 390 of file nearWallFields.C.
References Foam::endl(), forAll, and Foam::Info.
Referenced by nearWallFields::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 253 of file nearWallFields.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 257 of file nearWallFields.H.
Member Data Documentation
name_
word name_ protected
Name of this set of nearWallFields object.
Definition at line 126 of file nearWallFields.H.
Referenced by nearWallFields::name().
obr_
const objectRegistry& obr_ protected
Definition at line 128 of file nearWallFields.H.
active_
bool active_ protected
on/off switch
Definition at line 131 of file nearWallFields.H.
fieldSet_
List<Tuple2<word, word> > fieldSet_ protected
Fields to process.
Definition at line 136 of file nearWallFields.H.
patchSet_
labelHashSet patchSet_ protected
Patches to sample.
Definition at line 139 of file nearWallFields.H.
distance_
scalar distance_ protected
Distance away from wall.
Definition at line 142 of file nearWallFields.H.
fieldMap_
HashTable<word> fieldMap_ protected
From original field to sampled result.
Definition at line 145 of file nearWallFields.H.
reverseFieldMap_
HashTable<word> reverseFieldMap_ protected
From resulting back to original field.
Definition at line 148 of file nearWallFields.H.
cellToWalls_
labelListList cellToWalls_ protected
From cell to seed patch faces.
Definition at line 154 of file nearWallFields.H.
cellToSamples_
List<List<point> > cellToSamples_ protected
From cell to tracked end point.
Definition at line 157 of file nearWallFields.H.
getPatchDataMapPtr_
autoPtr<mapDistribute> getPatchDataMapPtr_ protected
Map from cell based data back to patch based data.
Definition at line 160 of file nearWallFields.H.
vsf_
PtrList<volScalarField> vsf_ protected
Definition at line 165 of file nearWallFields.H.
vvf_
PtrList<volVectorField> vvf_ protected
Definition at line 166 of file nearWallFields.H.
vSpheretf_
PtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 167 of file nearWallFields.H.
vSymmtf_
PtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 168 of file nearWallFields.H.
vtf_
PtrList<volTensorField> vtf_ protected
Definition at line 169 of file nearWallFields.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/nearWallFields/nearWallFields.H
src/postProcessing/functionObjects/field/nearWallFields/nearWallFields.C
src/postProcessing/functionObjects/field/nearWallFields/nearWallFieldsTemplates.C