OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
streamLineParticle Class Reference
Particle class that samples fields as it passes through. Used in streamline calculation.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToFace function.
Public Member Functions
streamLineParticle (const polyMesh &c, const vector &position, const label cellI, const label lifeTime)
Construct from components.
streamLineParticle (const polyMesh &c, Istream &is, bool readFields=true)
Construct from Istream.
streamLineParticle (const streamLineParticle &p)
Construct copy.
autoPtr< particle > clone () const
Construct and return a clone.
bool move (trackingData &, const scalar trackTime)
Track all particles to their end point.
bool hitPatch (const polyPatch &, trackingData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
void hitWedgePatch (const wedgePolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a wedge.
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a.
void hitSymmetryPatch (const symmetryPolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a.
void hitCyclicPatch (const cyclicPolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a cyclic.
void hitProcessorPatch (const processorPolyPatch &, trackingData &td)
void hitWallPatch (const wallPolyPatch &, trackingData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
void hitPatch (const polyPatch &, trackingData &td)
Overridable function to handle the particle hitting a polyPatch.
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label cellI, bool doCellFacePt=true)
Construct from components, tetFaceI_ and tetPtI_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFaceI_ for the.
vector oldNormal () const
Return the normal of the tri on tetFaceI_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label faceI) const
Is this global face an internal face?
bool boundaryFace (const label faceI) const
Is this global face a boundary face?
label patch (const label faceI) const
Which patch is particle on.
label patchFace (const label patchI, const label faceI) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchI, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchI, TrackData &td)
Convert processor patch addressing to the global equivalents.
void write (Ostream &os, bool writeFields) const
Write the particle data.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Public Member Functions inherited from DLListBase::link
link ()
Null construct.
bool registered () const
Check if the link is registered with the DLListBase.
void deregister ()
Deregister the link after removal.
Static Public Member Functions
static void readFields (Cloud< streamLineParticle > &)
Read.
static void writeFields (const Cloud< streamLineParticle > &)
Write.
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Friends
Ostream & operator<< (Ostream &, const streamLineParticle &)
Additional Inherited Members
Public Attributes inherited from DLListBase::link
link * prev_
Pointer to next entry in list.
link * next_
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions inherited from particle< Type >
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &cellI, label &tetFaceI, label &tetPtI, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes inherited from particle< Type >
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label cellI_
Index of the cell it is in.
label faceI_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFaceI_
Index of the face that owns the decomposed tet that the.
label tetPtI_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Detailed Description
Particle class that samples fields as it passes through. Used in streamline calculation.
Source files
streamLineParticle.H
streamLineParticle.C
Definition at line 54 of file streamLineParticle.H.
Constructor & Destructor Documentation
streamLineParticle() [1/3]
streamLineParticle (const polyMesh & c, const vector & position, const label cellI, const label lifeTime)
Construct from components.
Definition at line 109 of file streamLineParticle.C.
Referenced by streamLineParticle::clone(), streamLineParticle::iNew::operator()(), streamLineParticle::streamLineParticle(), and streamLineParticle::trackingData::trackingData().
streamLineParticle() [2/3]
streamLineParticle (const polyMesh & c, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 122 of file streamLineParticle.C.
References IOstream::check(), forAll, List< T >::setSize(), List< T >::size(), and streamLineParticle::streamLineParticle().
streamLineParticle() [3/3]
streamLineParticle (const streamLineParticle & p)
Construct copy.
Definition at line 161 of file streamLineParticle.C.
References streamLineParticle::move().
Member Function Documentation
clone()
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from particle< Type >.
Definition at line 184 of file streamLineParticle.H.
References particle< Type >::mesh_, and streamLineParticle::streamLineParticle().
move()
bool move (trackingData & td, const scalar trackTime)
Track all particles to their end point.
Definition at line 175 of file streamLineParticle.C.
References streamLineParticle::trackingData::allPositions_, streamLineParticle::trackingData::allScalars_, streamLineParticle::trackingData::allVectors_, Foam::endl(), forAll, streamLineParticle::hitPatch(), particle< Type >::TrackingData< CloudType >::keepParticle, Foam::mag(), streamLineParticle::trackingData::nSubCycle_, particle< Type >::position(), Foam::Pout, VectorSpace< Form, Cmpt, nCmpt >::size(), particle< Type >::TrackingData< CloudType >::switchProcessor, streamLineParticle::trackingData::trackForward_, streamLineParticle::trackingData::trackLength_, List< T >::transfer(), and U.
Referenced by streamLineParticle::iNew::operator()(), and streamLineParticle::streamLineParticle().
hitPatch() [1/2]
bool hitPatch (const polyPatch & , trackingData & td, const label patchI, const scalar trackFraction, const tetIndices & tetIs)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 324 of file streamLineParticle.C.
References streamLineParticle::hitWedgePatch().
Referenced by streamLineParticle::hitWallPatch(), streamLineParticle::move(), and streamLineParticle::iNew::operator()().
hitWedgePatch()
void hitWedgePatch (const wedgePolyPatch & pp, trackingData & td)
Overridable function to handle the particle hitting a wedge.
Definition at line 338 of file streamLineParticle.C.
References streamLineParticle::hitSymmetryPlanePatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by streamLineParticle::hitPatch(), and streamLineParticle::iNew::operator()().
hitSymmetryPlanePatch()
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch & pp, trackingData & td)
Overridable function to handle the particle hitting a.
symmetry plane
Definition at line 349 of file streamLineParticle.C.
References streamLineParticle::hitSymmetryPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by streamLineParticle::hitWedgePatch(), and streamLineParticle::iNew::operator()().
hitSymmetryPatch()
void hitSymmetryPatch (const symmetryPolyPatch & pp, trackingData & td)
Overridable function to handle the particle hitting a.
symmetry patch
Definition at line 360 of file streamLineParticle.C.
References streamLineParticle::hitCyclicPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by streamLineParticle::hitSymmetryPlanePatch(), and streamLineParticle::iNew::operator()().
hitCyclicPatch()
void hitCyclicPatch (const cyclicPolyPatch & pp, trackingData & td)
Overridable function to handle the particle hitting a cyclic.
Definition at line 371 of file streamLineParticle.C.
References streamLineParticle::hitProcessorPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by streamLineParticle::hitSymmetryPatch(), and streamLineParticle::iNew::operator()().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a processorPatch
Definition at line 382 of file streamLineParticle.C.
References streamLineParticle::hitWallPatch(), and particle< Type >::TrackingData< CloudType >::switchProcessor.
Referenced by streamLineParticle::hitCyclicPatch(), and streamLineParticle::iNew::operator()().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & wpp, trackingData & td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 393 of file streamLineParticle.C.
References streamLineParticle::hitPatch(), and particle< Type >::TrackingData< CloudType >::keepParticle.
Referenced by streamLineParticle::hitProcessorPatch(), and streamLineParticle::iNew::operator()().
hitPatch() [2/2]
void hitPatch (const polyPatch & wpp, trackingData & td)
Overridable function to handle the particle hitting a polyPatch.
Definition at line 405 of file streamLineParticle.C.
References particle< Type >::TrackingData< CloudType >::keepParticle.
readFields()
void readFields (Cloud< streamLineParticle > & c) static
Read.
Definition at line 415 of file streamLineParticle.C.
References Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAllIter, IOobject::MUST_READ, particle< Type >::readFields(), and Cloud< ParticleType >::size().
Referenced by streamLineParticle::iNew::operator()(), and streamLineParticleCloud::streamLineParticleCloud().
writeFields()
void writeFields (const Cloud< streamLineParticle > & c) static
Write.
Definition at line 453 of file streamLineParticle.C.
References IOstream::check(), Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), IOobject::NO_READ, Foam::operator<<(), p, Cloud< ParticleType >::size(), token::SPACE, regIOobject::write(), and particle< Type >::writeFields().
Referenced by streamLineParticle::iNew::operator()().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const streamLineParticle &) friend
Referenced by streamLineParticle::iNew::operator()().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/streamLine/streamLineParticle.H
src/postProcessing/functionObjects/field/streamLine/streamLineParticle.C