OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ListPlusEqOp< T, Size > Class Template Reference
plus op for FixedList<scalar>
Public Member Functions
void operator() (FixedList< T, Size > &x, const FixedList< T, Size > &y) const
void operator() (List< Type > &x, const List< Type > y) const
Detailed Description
template<class T, unsigned Size>
class Foam::ListPlusEqOp< T, Size >
plus op for FixedList<scalar>
Helper class for list.
Definition at line 41 of file regionSizeDistribution.C.
Member Function Documentation
operator()() [1/2]
void operator() (FixedList< T, Size > & x, const FixedList< T, Size > & y) const inline
Definition at line 45 of file regionSizeDistribution.C.
References Foam::constant::atomic::alpha, polyMesh::boundaryMesh(), Foam::divide(), Foam::fvc::domainIntegrate(), Foam::endl(), polyPatch::faceCells(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), Foam::Info, HashTable< T, Key, Hash >::insert(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), UPstream::master(), mesh, Foam::mkDir(), UPstream::myProcNo(), OFstream::name(), IOobject::NO_READ, polyBoundaryMesh::patchSet(), Foam::pow(), List< T >::size(), PtrList< T >::size(), Foam::sqr(), Foam::sqrt(), Ostream::write(), and y.
operator()() [2/2]
void operator() (List< Type > & x, const List< Type > y) const inline
Definition at line 41 of file meshToMeshTemplates.C.
References fld(), forAll, meshToMesh::mapSrcToTgt(), List< T >::setSize(), List< T >::size(), and y.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/regionSizeDistribution/regionSizeDistribution.C
src/sampling/meshToMeshInterpolation/meshToMesh/meshToMeshTemplates.C