OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
processorField Class Reference
Function objects » Field function objects
This function object writes a scalar field whose value is the local processor ID. The output field name is 'processorID'.
Public Member Functions
TypeName ("processorField")
Runtime type information.
processorField (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~processorField ()
Destructor.
virtual const word & name () const
Return name of the processorField object.
virtual void read (const dictionary &)
Read the input data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
processorField (const processorField &)
Disallow default bitwise copy construct.
void operator= (const processorField &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of nearWallFields object.
const objectRegistry & obr_
Reference to the database.
bool active_
on/off switch
Detailed Description
This function object writes a scalar field whose value is the local processor ID. The output field name is 'processorID'.
Example of function object specification:
processorField1
{
    type        processorField;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
}
Function object usage
Property Description Required Default value
type type name: processorField yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
processorField.H
processorField.C
IOprocessorField.H
Definition at line 92 of file processorField.H.
Constructor & Destructor Documentation
processorField() [1/2]
processorField (const processorField &) protected
Disallow default bitwise copy construct.
processorField() [2/2]
processorField (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 41 of file processorField.C.
References Foam::dimless, Foam::endl(), mesh, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), Time::timeName(), and WarningIn.
~processorField()
~processorField () virtual
Destructor.
Definition at line 98 of file processorField.C.
Member Function Documentation
operator=()
void operator= (const processorField &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("processorField")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the processorField object.
Definition at line 143 of file processorField.H.
References processorField::end(), processorField::execute(), processorField::name_, processorField::read(), processorField::timeSet(), and processorField::write().
read()
void read (const dictionary & dict) virtual
Read the input data.
Definition at line 104 of file processorField.C.
Referenced by processorField::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 110 of file processorField.C.
References Foam::dimless, and UPstream::myProcNo().
Referenced by processorField::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 123 of file processorField.C.
Referenced by processorField::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 132 of file processorField.C.
Referenced by processorField::name().
write()
void write () virtual
Write.
Definition at line 138 of file processorField.C.
References regIOobject::write().
Referenced by processorField::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 164 of file processorField.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 168 of file processorField.H.
Member Data Documentation
name_
word name_ protected
Name of this set of nearWallFields object.
Definition at line 99 of file processorField.H.
Referenced by processorField::name().
obr_
const objectRegistry& obr_ protected
Reference to the database.
Definition at line 102 of file processorField.H.
active_
bool active_ protected
on/off switch
Definition at line 105 of file processorField.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/processorField/processorField.H
src/postProcessing/functionObjects/field/processorField/processorField.C