OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cloudInfo Class Reference
Function objects » Cloud function objects
This function object outputs Lagrangian cloud information to a file. The current outputs include:
Public Member Functions
TypeName ("cloudInfo")
Runtime type information.
cloudInfo (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~cloudInfo ()
Destructor.
virtual const word & name () const
Return name of the cloudInfo object.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
virtual void writeFileHeader (const label i)
File header information.
cloudInfo (const cloudInfo &)
Disallow default bitwise copy construct.
void operator= (const cloudInfo &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of cloudInfo object.
const objectRegistry & obr_
Reference to the database.
bool active_
on/off switch
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
This function object outputs Lagrangian cloud information to a file. The current outputs include:
- total current number of parcels
total current mass of parcels
Example of function object specification:
cloudInfo1
{
    type        cloudInfo;
    functionObjectLibs ("libcloudFunctionObjects.so");
    ...
    clouds
    (
        kinematicCloud1
        thermoCloud1
    );
}
Function object usage
Property Description Required Default value
type type name: cloudInfo yes
clouds list of clouds names to process yes
The output data of each cloud is written to a file named <cloudName>.dat
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
cloudInfo.H
cloudInfo.C
IOcloudInfo.H
Definition at line 109 of file cloudInfo.H.
Constructor & Destructor Documentation
cloudInfo() [1/2]
cloudInfo (const cloudInfo &) protected
Disallow default bitwise copy construct.
Referenced by cloudInfo::writeFileHeader().
cloudInfo() [2/2]
cloudInfo (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 53 of file cloudInfo.C.
~cloudInfo()
~cloudInfo () virtual
Destructor.
Definition at line 71 of file cloudInfo.C.
Member Function Documentation
writeFileHeader()
void writeFileHeader (const label i) protected virtual
File header information.
Reimplemented from functionObjectFile.
Definition at line 40 of file cloudInfo.C.
References cloudInfo::cloudInfo(), and Foam::endl().
operator=()
void operator= (const cloudInfo &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("cloudInfo")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the cloudInfo object.
Definition at line 165 of file cloudInfo.H.
References cloudInfo::end(), cloudInfo::execute(), cloudInfo::name_, cloudInfo::read(), cloudInfo::timeSet(), and cloudInfo::write().
read()
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 77 of file cloudInfo.C.
References Foam::endl(), forAllConstIter(), Foam::Info, dictionary::lookup(), Foam::nl, functionObjectFile::resetNames(), and Foam::type().
Referenced by cloudInfo::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 101 of file cloudInfo.C.
Referenced by cloudInfo::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 107 of file cloudInfo.C.
Referenced by cloudInfo::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 113 of file cloudInfo.C.
Referenced by cloudInfo::name().
write()
void write () virtual
Write.
Reimplemented from functionObjectFile.
Definition at line 119 of file cloudInfo.C.
References cloudName(), Foam::endl(), forAllConstIter(), objectRegistry::lookupObject(), kinematicCloud::massInSystem(), UPstream::master(), kinematicCloud::nParcels(), Foam::returnReduce(), token::TAB, and functionObjectFile::write().
Referenced by cloudInfo::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 186 of file cloudInfo.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 190 of file cloudInfo.H.
Member Data Documentation
name_
word name_ protected
Name of this set of cloudInfo object.
Definition at line 118 of file cloudInfo.H.
Referenced by cloudInfo::name().
obr_
const objectRegistry& obr_ protected
Reference to the database.
Definition at line 121 of file cloudInfo.H.
active_
bool active_ protected
on/off switch
Definition at line 124 of file cloudInfo.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/cloud/cloudInfo/cloudInfo.H
src/postProcessing/functionObjects/cloud/cloudInfo/cloudInfo.C