OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldAverage Class Reference
Function objects » Field function objects
This function object calculates average quantities for a user-specified selection of volumetric and surface fields. Fields are entered as a list of sub-dictionaries, which indicate the type of averages to perform, and can be updated during the calculation. The current options include:
Public Member Functions
TypeName ("fieldAverage")
Runtime type information.
fieldAverage (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~fieldAverage ()
Destructor.
virtual const word & name () const
Return name of the set of field averages.
virtual void read (const dictionary &)
Read the field average data.
virtual void execute ()
Execute the averaging.
virtual void end ()
Execute the averaging at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the field average data and write.
virtual void updateMesh (const mapPolyMesh &)
Update mesh.
virtual void movePoints (const polyMesh &)
Move points.
Protected Member Functions
void resetFields ()
Checkout fields (causes deletion) from the database.
void initialize ()
Reset lists (clear existing values) and initialize averaging.
template<class Type >
void addMeanFieldType (const label fieldI)
Add mean average field to database.
template<class Type >
void addMeanField (const label fieldI)
Add mean average field to database.
template<class Type1 , class Type2 >
void addPrime2MeanFieldType (const label fieldI)
Add prime-squared average field to database.
template<class Type1 , class Type2 >
void addPrime2MeanField (const label fieldI)
Add prime-squared average field to database.
virtual void calcAverages ()
Main calculation routine.
template<class Type >
void calculateMeanFieldType (const label fieldI) const
Calculate mean average fields.
template<class Type >
void calculateMeanFields () const
Calculate mean average fields.
template<class Type1 , class Type2 >
void calculatePrime2MeanFieldType (const label fieldI) const
Calculate prime-squared average fields.
template<class Type1 , class Type2 >
void calculatePrime2MeanFields () const
Calculate prime-squared average fields.
template<class Type1 , class Type2 >
void addMeanSqrToPrime2MeanType (const label fieldI) const
Add mean-squared field value to prime-squared mean field.
template<class Type1 , class Type2 >
void addMeanSqrToPrime2Mean () const
Add mean-squared field value to prime-squared mean field.
virtual void writeAverages () const
Write averages.
template<class Type >
void writeFieldType (const word &fieldName) const
Write fields.
template<class Type >
void writeFields () const
Write fields.
void writeAveragingProperties () const
Write averaging properties - steps and time.
void readAveragingProperties ()
Read averaging properties - steps and time.
fieldAverage (const fieldAverage &)
Disallow default bitwise copy construct.
void operator= (const fieldAverage &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of field averages.
const objectRegistry & obr_
Database this class is registered to.
bool active_
On/off switch.
label prevTimeIndex_
Time at last call, prevents repeated averaging.
Switch resetOnRestart_
Reset the averaging process on restart flag.
Switch resetOnOutput_
Reset the averaging process on output flag.
bool initialised_
Initialised flag.
List< fieldAverageItem > faItems_
List of field average items, describing what averages to be.
List< label > totalIter_
Iteration steps counter.
List< scalar > totalTime_
Total time counter.
Detailed Description
This function object calculates average quantities for a user-specified selection of volumetric and surface fields. Fields are entered as a list of sub-dictionaries, which indicate the type of averages to perform, and can be updated during the calculation. The current options include:
- mean: arithmetic mean:
prime2Mean: prime-squared mean
base: average over 'time', or 'iteration' (in the above)
window: optional averaging window, specified in 'base' units
Average field names are constructed by concatenating the base field with the averaging type, e.g. when averaging field 'U', the resultant fields are:
arithmetic mean field, UMean
prime-squared field, UPrime2Mean
Information regarding the number of averaging steps, and total averaging time are written on a per-field basis to the fieldAveragingProperties dictionary, located in <time>/uniform
When restarting form a previous calculation, the averaging is continuous. However, the averaging process can be restarted using the resetOnRestart option.
To restart the averaging process after each calculation output time, use the resetOnOutput option.
Example of function object specification:
fieldAverage1
{
    type fieldAverage;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    resetOnRestart true;
    resetOnOutput false;
    fields
    (
        U
        {
            mean            on;
            prime2Mean      on;
            base            time;
            window          10.0;
            windowName      w1;
        }
        p
        {
            mean            on;
            prime2Mean      on;
            base            time;
        }
    );
}
Function object usage
Property Description Required Default value
type type name: fieldAverage yes
resetOnRestart flag to reset the averaging on restart yes
resetOnOutput flag to reset the averaging on output yes
fields list of fields and averaging options yes
Note
To employ the prime2Mean option, the mean option must be selecetd.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
fieldAverage.H
fieldAverage.C
fieldAverageTemplates.C
fieldAverageItem.C
Definition at line 165 of file fieldAverage.H.
Constructor & Destructor Documentation
fieldAverage() [1/2]
fieldAverage (const fieldAverage &) protected
Disallow default bitwise copy construct.
Referenced by fieldAverage::readAveragingProperties().
fieldAverage() [2/2]
fieldAverage (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 247 of file fieldAverage.C.
References Foam::endl(), Foam::nl, and WarningIn.
~fieldAverage()
~fieldAverage () virtual
Destructor.
Definition at line 290 of file fieldAverage.C.
Member Function Documentation
resetFields()
void resetFields () protected
Checkout fields (causes deletion) from the database.
and reset lists
Definition at line 42 of file fieldAverage.C.
References forAll.
initialize()
void initialize () protected
Reset lists (clear existing values) and initialize averaging.
Check requested field averages are valid, populate field lists
Definition at line 65 of file fieldAverage.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, Foam::type(), and WarningIn.
addMeanFieldType()
void addMeanFieldType (const label fieldI) protected
Add mean average field to database.
Definition at line 34 of file fieldAverageTemplates.C.
References Foam::endl(), fieldAverage::faItems_, HashTable< T, Key, Hash >::found(), objectRegistry::foundObject(), Foam::Info, objectRegistry::lookupObject(), IOobject::NO_READ, IOobject::NO_WRITE, fieldAverage::obr_, IOobject::READ_IF_PRESENT, fieldAverage::resetOnOutput_, Time::startTime(), regIOobject::store(), objectRegistry::time(), Time::timeName(), and dimensioned< Type >::value().
addMeanField()
void addMeanField (const label fieldI) protected
Add mean average field to database.
Definition at line 82 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, objectRegistry::foundObject(), and fieldAverage::obr_.
addPrime2MeanFieldType()
void addPrime2MeanFieldType (const label fieldI) protected
Add prime-squared average field to database.
Definition at line 104 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, HashTable< T, Key, Hash >::found(), objectRegistry::foundObject(), Foam::Info, objectRegistry::lookupObject(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, fieldAverage::obr_, IOobject::READ_IF_PRESENT, fieldAverage::resetOnOutput_, Foam::sqr(), Time::startTime(), regIOobject::store(), objectRegistry::time(), Time::timeName(), and dimensioned< Type >::value().
addPrime2MeanField()
void addPrime2MeanField (const label fieldI) protected
Add prime-squared average field to database.
Definition at line 152 of file fieldAverageTemplates.C.
References Foam::exit(), fieldAverage::faItems_, Foam::FatalError, FatalErrorIn, objectRegistry::foundObject(), Foam::nl, and fieldAverage::obr_.
calcAverages()
void calcAverages () protected virtual
Main calculation routine.
Definition at line 107 of file fieldAverage.C.
References forAll, Foam::Info, Foam::nl, and Foam::type().
calculateMeanFieldType()
void calculateMeanFieldType (const label fieldI) const protected
Calculate mean average fields.
Definition at line 188 of file fieldAverageTemplates.C.
References Foam::constant::atomic::alpha, beta(), TimeState::deltaTValue(), fieldAverage::faItems_, objectRegistry::foundObject(), objectRegistry::lookupObject(), fieldAverage::obr_, objectRegistry::time(), fieldAverage::totalIter_, and fieldAverage::totalTime_.
calculateMeanFields()
void calculateMeanFields () const protected
Calculate mean average fields.
Definition at line 230 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, and forAll.
calculatePrime2MeanFieldType()
void calculatePrime2MeanFieldType (const label fieldI) const protected
Calculate prime-squared average fields.
Definition at line 247 of file fieldAverageTemplates.C.
References Foam::constant::atomic::alpha, beta(), TimeState::deltaTValue(), fieldAverage::faItems_, objectRegistry::foundObject(), objectRegistry::lookupObject(), fieldAverage::obr_, Foam::sqr(), objectRegistry::time(), fieldAverage::totalIter_, and fieldAverage::totalTime_.
calculatePrime2MeanFields()
void calculatePrime2MeanFields () const protected
Calculate prime-squared average fields.
Definition at line 294 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, and forAll.
addMeanSqrToPrime2MeanType()
void addMeanSqrToPrime2MeanType (const label fieldI) const protected
Add mean-squared field value to prime-squared mean field.
Definition at line 314 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, objectRegistry::foundObject(), objectRegistry::lookupObject(), fieldAverage::obr_, and Foam::sqr().
addMeanSqrToPrime2Mean()
void addMeanSqrToPrime2Mean () const protected
Add mean-squared field value to prime-squared mean field.
Definition at line 334 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, and forAll.
writeAverages()
void writeAverages () const protected virtual
Write averages.
Definition at line 150 of file fieldAverage.C.
References Foam::endl(), and Foam::Info.
writeFieldType()
void writeFieldType (const word & fieldName) const protected
Write fields.
Definition at line 354 of file fieldAverageTemplates.C.
References f(), objectRegistry::foundObject(), objectRegistry::lookupObject(), and fieldAverage::obr_.
writeFields()
void writeFields () const protected
Write fields.
Definition at line 365 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, and forAll.
writeAveragingProperties()
void writeAveragingProperties () const protected
Write averaging properties - steps and time.
Definition at line 162 of file fieldAverage.C.
References dictionary::add(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, propsDict(), and dictionary::subDict().
readAveragingProperties()
void readAveragingProperties () protected
Read averaging properties - steps and time.
Definition at line 190 of file fieldAverage.C.
References fieldAverage::fieldAverage(), forAll, dictionary::found(), IOobject::headerOk(), Foam::Info, IOobject::MUST_READ_IF_MODIFIED, Foam::nl, IOobject::NO_WRITE, propsDict(), Foam::readScalar(), and dictionary::subDict().
operator=()
void operator= (const fieldAverage &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("fieldAverage")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of field averages.
Definition at line 317 of file fieldAverage.H.
References fieldAverage::end(), fieldAverage::execute(), fieldAverage::movePoints(), fieldAverage::name_, fieldAverage::read(), fieldAverage::timeSet(), fieldAverage::updateMesh(), and fieldAverage::write().
read()
void read (const dictionary & dict) virtual
Read the field average data.
Definition at line 296 of file fieldAverage.C.
References Foam::endl(), Foam::Info, dictionary::lookup(), Foam::nl, dictionary::readIfPresent(), and Foam::type().
Referenced by fieldAverage::name().
execute()
void execute () virtual
Execute the averaging.
Definition at line 315 of file fieldAverage.C.
References Foam::endl(), and Foam::Info.
Referenced by fieldAverage::name().
end()
void end () virtual
Execute the averaging at the final time-loop, currently does nothing.
Definition at line 325 of file fieldAverage.C.
References Foam::endl(), and Foam::Info.
Referenced by fieldAverage::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 335 of file fieldAverage.C.
Referenced by fieldAverage::name().
write()
void write () virtual
Calculate the field average data and write.
Definition at line 339 of file fieldAverage.C.
References Foam::endl(), Foam::Info, and Foam::nl.
Referenced by fieldAverage::name().
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Update mesh.
Definition at line 365 of file fieldAverage.C.
Referenced by fieldAverage::name().
movePoints()
void movePoints (const polyMesh &) virtual
Move points.
Definition at line 371 of file fieldAverage.C.
Referenced by fieldAverage::name().
Member Data Documentation
name_
word name_ protected
Name of this set of field averages.
Definition at line 172 of file fieldAverage.H.
Referenced by fieldAverage::name().
obr_
const objectRegistry& obr_ protected
Database this class is registered to.
Definition at line 175 of file fieldAverage.H.
Referenced by fieldAverage::addMeanField(), fieldAverage::addMeanFieldType(), fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::addPrime2MeanField(), fieldAverage::addPrime2MeanFieldType(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), and fieldAverage::writeFieldType().
active_
bool active_ protected
On/off switch.
Definition at line 178 of file fieldAverage.H.
prevTimeIndex_
label prevTimeIndex_ protected
Time at last call, prevents repeated averaging.
Definition at line 181 of file fieldAverage.H.
resetOnRestart_
Switch resetOnRestart_ protected
Reset the averaging process on restart flag.
Definition at line 184 of file fieldAverage.H.
resetOnOutput_
Switch resetOnOutput_ protected
Reset the averaging process on output flag.
Definition at line 187 of file fieldAverage.H.
Referenced by fieldAverage::addMeanFieldType(), and fieldAverage::addPrime2MeanFieldType().
initialised_
bool initialised_ protected
Initialised flag.
Definition at line 190 of file fieldAverage.H.
faItems_
List<fieldAverageItem> faItems_ protected
List of field average items, describing what averages to be.
calculated and output
Definition at line 194 of file fieldAverage.H.
Referenced by fieldAverage::addMeanField(), fieldAverage::addMeanFieldType(), fieldAverage::addMeanSqrToPrime2Mean(), fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::addPrime2MeanField(), fieldAverage::addPrime2MeanFieldType(), fieldAverage::calculateMeanFields(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFields(), fieldAverage::calculatePrime2MeanFieldType(), and fieldAverage::writeFields().
totalIter_
List<label> totalIter_ protected
Iteration steps counter.
Definition at line 199 of file fieldAverage.H.
Referenced by fieldAverage::calculateMeanFieldType(), and fieldAverage::calculatePrime2MeanFieldType().
totalTime_
List<scalar> totalTime_ protected
Total time counter.
Definition at line 202 of file fieldAverage.H.
Referenced by fieldAverage::calculateMeanFieldType(), and fieldAverage::calculatePrime2MeanFieldType().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldAverage/fieldAverage/fieldAverage.H
src/postProcessing/functionObjects/field/fieldAverage/fieldAverage/fieldAverage.C
src/postProcessing/functionObjects/field/fieldAverage/fieldAverage/fieldAverageTemplates.C