OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldCoordinateSystemTransform Class Reference
Function objects » Field function objects
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Public Member Functions
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
fieldCoordinateSystemTransform (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~fieldCoordinateSystemTransform ()
Destructor.
virtual const word & name () const
Return name of the fieldCoordinateSystemTransform object.
virtual void read (const dictionary &)
Read the input data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
fieldCoordinateSystemTransform (const fieldCoordinateSystemTransform &)
Disallow default bitwise copy construct.
void operator= (const fieldCoordinateSystemTransform &)
Disallow default bitwise assignment.
template<class Type >
void transform (const word &fieldName) const
template<class Type >
void transformField (const Type &field) const
Protected Attributes
word name_
Name.
const objectRegistry & obr_
bool active_
on/off switch
wordList fieldSet_
Fields to transform.
coordinateSystem coordSys_
Co-ordinate system to transform to.
Detailed Description
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Example of function object specification:
fieldCoordinateSystemTransform1
{
    type        fieldCoordinateSystemTransform;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    fields
    (
        U
        UMean
        UPrime2Mean
    );
    coordinateSystem
    {
        origin  (0.001  0       0);
        e1      (1      0.15    0);
        e3      (0      0      -1);
    }
}
Function object usage
Property Description Required Default value
type type name: fieldCoordinateSystemTransform yes
fields list of fields to be transformed yes
coordinateSystem local co-ordinate system yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::coordinateSystem
Source files
fieldCoordinateSystemTransform.H
fieldCoordinateSystemTransform.C
fieldCoordinateSystemTransformTemplates.C
IOfieldCoordinateSystemTransform.H
Definition at line 119 of file fieldCoordinateSystemTransform.H.
Constructor & Destructor Documentation
fieldCoordinateSystemTransform() [1/2]
fieldCoordinateSystemTransform (const fieldCoordinateSystemTransform &) protected
Disallow default bitwise copy construct.
fieldCoordinateSystemTransform() [2/2]
fieldCoordinateSystemTransform (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 40 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), Foam::Info, Foam::nl, Foam::type(), and WarningIn.
~fieldCoordinateSystemTransform()
~fieldCoordinateSystemTransform () virtual
Destructor.
Definition at line 82 of file fieldCoordinateSystemTransform.C.
Member Function Documentation
operator=()
void operator= (const fieldCoordinateSystemTransform &) protected
Disallow default bitwise assignment.
transform()
void transform (const word & fieldName) const protected
Definition at line 78 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::endl(), Foam::Info, and Foam::type().
Referenced by fieldCoordinateSystemTransform::transformField().
transformField()
void transformField (const Type & field) const protected
Definition at line 36 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::endl(), Foam::Info, Foam::nl, R, Foam::transform(), fieldCoordinateSystemTransform::transform(), and Ostream::write().
TypeName()
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the fieldCoordinateSystemTransform object.
Definition at line 181 of file fieldCoordinateSystemTransform.H.
References fieldCoordinateSystemTransform::end(), fieldCoordinateSystemTransform::execute(), fieldCoordinateSystemTransform::name_, fieldCoordinateSystemTransform::read(), fieldCoordinateSystemTransform::timeSet(), and fieldCoordinateSystemTransform::write().
read()
void read (const dictionary & dict) virtual
Read the input data.
Definition at line 88 of file fieldCoordinateSystemTransform.C.
References dictionary::lookup().
Referenced by fieldCoordinateSystemTransform::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 97 of file fieldCoordinateSystemTransform.C.
References forAll, Foam::Info, Foam::nl, and Foam::type().
Referenced by fieldCoordinateSystemTransform::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 116 of file fieldCoordinateSystemTransform.C.
Referenced by fieldCoordinateSystemTransform::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 125 of file fieldCoordinateSystemTransform.C.
Referenced by fieldCoordinateSystemTransform::name().
write()
void write () virtual
Write.
Definition at line 131 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), forAll, Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by fieldCoordinateSystemTransform::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 202 of file fieldCoordinateSystemTransform.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 206 of file fieldCoordinateSystemTransform.H.
Member Data Documentation
name_
word name_ protected
Name.
Definition at line 126 of file fieldCoordinateSystemTransform.H.
Referenced by fieldCoordinateSystemTransform::name().
obr_
const objectRegistry& obr_ protected
Definition at line 128 of file fieldCoordinateSystemTransform.H.
active_
bool active_ protected
on/off switch
Definition at line 131 of file fieldCoordinateSystemTransform.H.
fieldSet_
wordList fieldSet_ protected
Fields to transform.
Definition at line 134 of file fieldCoordinateSystemTransform.H.
coordSys_
coordinateSystem coordSys_ protected
Co-ordinate system to transform to.
Definition at line 137 of file fieldCoordinateSystemTransform.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.H
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.C
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransformTemplates.C