OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldValue Class Reference
Function objects » Field function objects
Base class for field value -based function objects.
Public Member Functions
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, fieldValue, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles),(name, obr, dict, loadFromFiles))
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType, const bool loadFromFiles=false)
Construct from components.
virtual ~fieldValue ()
Destructor.
const word & name () const
Return the name of the geometric source.
const objectRegistry & obr () const
Return the reference to the object registry.
const dictionary & dict () const
Return the reference to the construction dictionary.
bool active () const
Return the active flag.
const Switch & log () const
Return the switch to send output to Info as well as to file.
const word & sourceName () const
Return the source name.
const wordList & fields () const
Return the list of field names.
const Switch & valueOutput () const
Return the output field values flag.
const fvMesh & mesh () const
Helper function to return the reference to the mesh.
const dictionary & resultDict () const
Return access to the latest set of results.
virtual void read (const dictionary &dict)
Read from dictionary.
virtual void write ()
Write to screen/file.
virtual void execute ()
Execute.
virtual void end ()
Execute the at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void updateMesh (const mapPolyMesh &)
Update mesh.
virtual void movePoints (const polyMesh &)
Move points.
template<class Type >
void combineFields (Field< Type > &field)
Combine fields from all processor domains into single field.
template<class Type >
void combineFields (tmp< Field< Type > > &)
Combine fields from all processor domains into single field.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Member Functions
static autoPtr< fieldValue > New (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false, const bool output=true)
Return a reference to the selected fieldValue.
Protected Attributes
word name_
Name of this fieldValue object.
const objectRegistry & obr_
Database this class is registered to.
dictionary dict_
Construction dictionary.
bool active_
Active flag.
Switch log_
Switch to send output to Info as well as to file.
word sourceName_
Name of source object.
wordList fields_
List of field names to operate on.
Switch valueOutput_
Output field values flag.
dictionary resultDict_
Results dictionary for external access of results.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void writeFileHeader (const label i=0)
File header information.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Detailed Description
Base class for field value -based function objects.
Source files
fieldValue.H
fieldValue.C
Definition at line 62 of file fieldValue.H.
Constructor & Destructor Documentation
fieldValue()
fieldValue (const word & name, const objectRegistry & obr, const dictionary & dict, const word & valueType, const bool loadFromFiles = false)
Construct from components.
Definition at line 69 of file fieldValue.C.
References Foam::endl(), Foam::nl, and WarningIn.
Referenced by fieldValue::write().
~fieldValue()
~fieldValue () virtual
Destructor.
Definition at line 113 of file fieldValue.C.
Member Function Documentation
TypeName()
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , fieldValue , dictionary , (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles) , (name, obr, dict, loadFromFiles))
New()
Foam::autoPtr< Foam::fieldValue > New (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false, const bool output = true) static
Return a reference to the selected fieldValue.
Definition at line 31 of file fieldValueNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), name(), and Foam::nl.
Referenced by fieldValueDelta::read().
name()
const Foam::word & name () const inline
Return the name of the geometric source.
Definition at line 31 of file fieldValueI.H.
References fieldValue::name_.
obr()
const Foam::objectRegistry & obr () const inline
Return the reference to the object registry.
Definition at line 37 of file fieldValueI.H.
References fieldValue::obr_.
dict()
const Foam::dictionary & dict () const inline
Return the reference to the construction dictionary.
Definition at line 43 of file fieldValueI.H.
References fieldValue::dict_.
active()
bool active () const inline
Return the active flag.
Definition at line 49 of file fieldValueI.H.
References fieldValue::active_.
log()
const Foam::Switch & log () const inline
Return the switch to send output to Info as well as to file.
Definition at line 55 of file fieldValueI.H.
References fieldValue::log_.
sourceName()
const Foam::word & sourceName () const inline
Return the source name.
Definition at line 61 of file fieldValueI.H.
References fieldValue::sourceName_.
fields()
const Foam::wordList & fields () const inline
Return the list of field names.
Definition at line 67 of file fieldValueI.H.
References fieldValue::fields_.
valueOutput()
const Foam::Switch & valueOutput () const inline
Return the output field values flag.
Definition at line 73 of file fieldValueI.H.
References fieldValue::valueOutput_.
mesh()
const Foam::fvMesh & mesh () const inline
Helper function to return the reference to the mesh.
Definition at line 79 of file fieldValueI.H.
References fieldValue::obr_.
Referenced by cellSource::writeValues(), and faceSource::writeValues().
resultDict()
const Foam::dictionary & resultDict () const inline
Return access to the latest set of results.
Definition at line 85 of file fieldValueI.H.
References fieldValue::resultDict_.
read()
void read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented in faceSource, and cellSource.
Definition at line 42 of file fieldValue.C.
References dict, dictionary::lookup(), and dictionary::lookupOrDefault().
Referenced by cellSource::read(), and faceSource::read().
write()
void write () virtual
Write to screen/file.
Reimplemented from functionObjectFile.
Reimplemented in faceSource, and cellSource.
Definition at line 55 of file fieldValue.C.
References fieldValue::fieldValue(), Foam::Info, Foam::nl, Foam::type(), and functionObjectFile::write().
Referenced by cellSource::write(), and faceSource::write().
execute()
void execute () virtual
Execute.
Definition at line 119 of file fieldValue.C.
end()
void end () virtual
Execute the at the final time-loop, currently does nothing.
Definition at line 125 of file fieldValue.C.
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 131 of file fieldValue.C.
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Update mesh.
Definition at line 137 of file fieldValue.C.
movePoints()
void movePoints (const polyMesh &) virtual
Move points.
Definition at line 143 of file fieldValue.C.
combineFields() [1/2]
void combineFields (Field< Type > & field)
Combine fields from all processor domains into single field.
Definition at line 33 of file fieldValueTemplates.C.
References Pstream::gatherList(), UPstream::master(), UPstream::myProcNo(), and UPstream::nProcs().
Referenced by fieldValue::combineFields(), cellSource::writeValues(), and faceSource::writeValues().
combineFields() [2/2]
void combineFields (tmp< Field< Type > > & field)
Combine fields from all processor domains into single field.
Definition at line 54 of file fieldValueTemplates.C.
References fieldValue::combineFields().
Member Data Documentation
name_
word name_ protected
Name of this fieldValue object.
Definition at line 72 of file fieldValue.H.
Referenced by faceSource::filterField(), fieldValue::name(), and faceSource::writeValues().
obr_
const objectRegistry& obr_ protected
Database this class is registered to.
Definition at line 75 of file fieldValue.H.
Referenced by faceSource::getFieldValues(), fieldValue::mesh(), fieldValue::obr(), cellSource::setFieldValues(), cellSource::validField(), faceSource::validField(), cellSource::writeValues(), and faceSource::writeValues().
dict_
dictionary dict_ protected
Construction dictionary.
Definition at line 78 of file fieldValue.H.
Referenced by fieldValue::dict().
active_
bool active_ protected
Active flag.
Definition at line 81 of file fieldValue.H.
Referenced by fieldValue::active().
log_
Switch log_ protected
Switch to send output to Info as well as to file.
Definition at line 84 of file fieldValue.H.
Referenced by fieldValue::log(), cellSource::writeValues(), and faceSource::writeValues().
sourceName_
word sourceName_ protected
Name of source object.
Definition at line 87 of file fieldValue.H.
Referenced by faceSource::filterField(), fieldValue::sourceName(), cellSource::writeValues(), and faceSource::writeValues().
fields_
wordList fields_ protected
List of field names to operate on.
Definition at line 90 of file fieldValue.H.
Referenced by fieldValue::fields().
valueOutput_
Switch valueOutput_ protected
Output field values flag.
Definition at line 93 of file fieldValue.H.
Referenced by fieldValue::valueOutput(), and cellSource::writeValues().
resultDict_
dictionary resultDict_ protected
Results dictionary for external access of results.
Definition at line 96 of file fieldValue.H.
Referenced by fieldValue::resultDict(), cellSource::writeValues(), and faceSource::writeValues().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldValues/fieldValue/fieldValue.H
src/postProcessing/functionObjects/field/fieldValues/fieldValue/fieldValue.C
src/postProcessing/functionObjects/field/fieldValues/fieldValue/fieldValueI.H
src/postProcessing/functionObjects/field/fieldValues/fieldValue/fieldValueNew.C
src/postProcessing/functionObjects/field/fieldValues/fieldValue/fieldValueTemplates.C