OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
systemCall Class Reference
Function objects
This function object executes system calls, entered in the form of a string lists. Calls can be made at the following points in the calculation:
Public Member Functions
TypeName ("systemCall")
Runtime type information.
systemCall (const word &name, const objectRegistry &unused, const dictionary &, const bool loadFromFilesUnused=false)
Construct for given objectRegistry and dictionary.
virtual ~systemCall ()
Destructor.
virtual const word & name () const
Return name of the system call set.
virtual void read (const dictionary &)
Read the system calls.
virtual void execute ()
Execute the "executeCalls" at each time-step.
virtual void end ()
Execute the "endCalls" at the final time-loop.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write, execute the "writeCalls".
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
systemCall (const systemCall &)
Disallow default bitwise copy construct.
void operator= (const systemCall &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of system calls.
stringList executeCalls_
List of calls to execute - every step.
stringList endCalls_
List of calls to execute when exiting the time-loop.
stringList writeCalls_
List of calls to execute - write steps.
Detailed Description
This function object executes system calls, entered in the form of a string lists. Calls can be made at the following points in the calculation:
- every time step
every output time
end of the calculation
Example of function object specification:
systemCall1
{
    type        systemCall;
    functionObjectLibs ("libsystemCall.so");
    ...
    executeCalls
    (
        "echo execute"
    );
    writeCalls
    (
        "echo \*\*\* writing data \*\*\*"
    );
    endCalls
    (
        "echo \*\*\* writing .bashrc \*\*\*"
        "cat ~/.bashrc"
        "echo \*\*\* done \*\*\*"
    );
}
Function object usage
Property Description Required Default value
type type name: systemCall yes
executeCalls list of calls on execute yes
writeCalls list of calls on write yes
endCalls list of calls on end yes
Note
Since this function object executes system calls, there is a potential security risk. In order to use the systemCall function object, the allowSystemOperations must be set to '1'; otherwise, system calls will not be allowed.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
systemCall.H
systemCall.C
IOsystemCall.H
Definition at line 131 of file systemCall.H.
Constructor & Destructor Documentation
systemCall() [1/2]
systemCall (const systemCall &) protected
Disallow default bitwise copy construct.
systemCall() [2/2]
systemCall (const word & name, const objectRegistry & unused, const dictionary & dict, const bool loadFromFilesUnused = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 41 of file systemCall.C.
~systemCall()
~systemCall () virtual
Destructor.
Definition at line 59 of file systemCall.C.
Member Function Documentation
operator=()
void operator= (const systemCall &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("systemCall")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the system call set.
Definition at line 185 of file systemCall.H.
References systemCall::end(), systemCall::execute(), systemCall::name_, systemCall::read(), systemCall::timeSet(), and systemCall::write().
read()
void read (const dictionary & dict) virtual
Read the system calls.
Definition at line 65 of file systemCall.C.
References dynamicCode::allowSystemOperations, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, dictionary::readIfPresent(), and WarningIn.
Referenced by systemCall::name().
execute()
void execute () virtual
Execute the "executeCalls" at each time-step.
Definition at line 96 of file systemCall.C.
References forAll, and Foam::system().
Referenced by systemCall::name().
end()
void end () virtual
Execute the "endCalls" at the final time-loop.
Definition at line 105 of file systemCall.C.
References forAll, and Foam::system().
Referenced by systemCall::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 114 of file systemCall.C.
Referenced by systemCall::name().
write()
void write () virtual
Write, execute the "writeCalls".
Definition at line 120 of file systemCall.C.
References forAll, and Foam::system().
Referenced by systemCall::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 206 of file systemCall.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 210 of file systemCall.H.
Member Data Documentation
name_
word name_ protected
Name of this set of system calls.
Definition at line 138 of file systemCall.H.
Referenced by systemCall::name().
executeCalls_
stringList executeCalls_ protected
List of calls to execute - every step.
Definition at line 141 of file systemCall.H.
endCalls_
stringList endCalls_ protected
List of calls to execute when exiting the time-loop.
Definition at line 144 of file systemCall.H.
writeCalls_
stringList writeCalls_ protected
List of calls to execute - write steps.
Definition at line 147 of file systemCall.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/systemCall/systemCall.H
src/postProcessing/functionObjects/systemCall/systemCall.C