OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallBoundedStreamLine Class Reference
Function objects » Field function objects
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Public Member Functions
TypeName ("wallBoundedStreamLine")
Runtime type information.
wallBoundedStreamLine (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~wallBoundedStreamLine ()
Destructor.
virtual const word & name () const
Return name of the set of field averages.
virtual void read (const dictionary &)
Read the field average data.
virtual void execute ()
Execute the averaging.
virtual void end ()
Execute the averaging at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the field average data and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion.
Detailed Description
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Example of function object specification:
wallBoundedStreamLine1
{
    type            wallBoundedStreamLine;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    setFormat       vtk;
    UName           UNear;
    trackForward    yes;
    fields
    (
        UNear
        p
    );
    lifeTime        10000;
    trackLength     1e-3;
    nSubCycle       5;
    cloudName       particleTracks;
    seedSampleSet   patchSeed;
    patchSeedCoeffs
    {
        type        patchSeed;
        patches     (wall);
        axis        x;
        maxPoints   20000;
    }
}
Function object usage
Property Description Required Default value
type type name: wallBoundedStreamLine yes
setFormat output data type yes
UName tracking velocity field name yes
fields fields to sample yes
lifetime maximum number of particle tracking steps yes
trackLength tracking segment length no
nSubCycle number of tracking steps per cell no
cloudName cloud name to use yes
seedSampleSet seeding method (see below) yes
Where seedSampleSet is typically one of
uniform : uniform particle seeding
cloud : cloud of points
patchSeed : seeding via patch faces
triSurfaceMeshPointSet : points according to a tri-surface mesh
Note
When specifying the track resolution, the trackLength OR nSubCycle option should be used
See also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::sampledSet Foam::streamLine
Source files
wallBoundedStreamLine.H
wallBoundedStreamLine.C
Definition at line 199 of file wallBoundedStreamLine.H.
Constructor & Destructor Documentation
wallBoundedStreamLine()
wallBoundedStreamLine (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 436 of file wallBoundedStreamLine.C.
References Foam::endl(), Foam::nl, and WarningIn.
~wallBoundedStreamLine()
~wallBoundedStreamLine () virtual
Destructor.
Definition at line 474 of file wallBoundedStreamLine.C.
Member Function Documentation
TypeName()
TypeName ("wallBoundedStreamLine")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of field averages.
Definition at line 326 of file wallBoundedStreamLine.H.
References wallBoundedStreamLine::end(), wallBoundedStreamLine::execute(), wallBoundedStreamLine::movePoints(), wallBoundedStreamLine::read(), wallBoundedStreamLine::timeSet(), wallBoundedStreamLine::updateMesh(), and wallBoundedStreamLine::write().
read()
void read (const dictionary & dict) virtual
Read the field average data.
Definition at line 480 of file wallBoundedStreamLine.C.
References Foam::abort(), primitiveMesh::cells(), polyMeshTetDecomposition::checkFaceTets(), HashTable< T, Key, Hash >::clear(), Foam::e, HashTableCore::end(), Foam::endl(), Foam::exit(), polyMesh::faces(), Foam::FatalError, FatalErrorIn, Foam::FatalIOError, FatalIOErrorIn, HashTable< T, Key, Hash >::find(), Foam::findIndex(), forAll, forAllConstIter(), dictionary::found(), Foam::Info, HashTable< T, Key, Hash >::insert(), IOWarningIn, dictionary::lookup(), dictionary::lookupOrDefault(), polyMeshTetDecomposition::minTetQuality, MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >::New(), writer< Type >::New(), sampledSet::New(), face::nextLabel(), primitiveMesh::nFaces(), Foam::nl, Foam::returnReduce(), dictionary::subDict(), Foam::type(), and WarningIn.
Referenced by wallBoundedStreamLine::name().
execute()
void execute () virtual
Execute the averaging.
Definition at line 639 of file wallBoundedStreamLine.C.
Referenced by wallBoundedStreamLine::name().
end()
void end () virtual
Execute the averaging at the final time-loop, currently does nothing.
Definition at line 643 of file wallBoundedStreamLine.C.
Referenced by wallBoundedStreamLine::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 647 of file wallBoundedStreamLine.C.
Referenced by wallBoundedStreamLine::name().
write()
void write () virtual
Calculate the field average data and write.
Definition at line 651 of file wallBoundedStreamLine.C.
References polyMesh::defaultRegion, mapDistribute::distribute(), Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::mkDir(), n, Foam::name(), fvMesh::name(), Foam::nl, UPstream::nProcs(), UPstream::parRun(), fileName::path(), Time::path(), UPstream::scheduled, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::setSize(), List< T >::size(), objectRegistry::time(), fvMesh::time(), Time::timeName(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer(), Ostream::write(), and List< T >::xfer().
Referenced by wallBoundedStreamLine::name().
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Update for changes of mesh.
Definition at line 881 of file wallBoundedStreamLine.C.
Referenced by wallBoundedStreamLine::name().
movePoints()
void movePoints (const polyMesh &) virtual
Update for mesh point-motion.
Definition at line 887 of file wallBoundedStreamLine.C.
Referenced by wallBoundedStreamLine::name().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.H
src/postProcessing/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.C