OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
codedFunctionObject Class Reference
Function objects » Utility function objects
This function object provides a general interface to enable dynamic code compilation.
Public Member Functions
TypeName ("coded")
Runtime type information.
codedFunctionObject (const word &name, const Time &time, const dictionary &dict, bool readNow=true)
Construct for given objectRegistry and dictionary.
virtual ~codedFunctionObject ()
Destructor.
functionObject & redirectFunctionObject () const
Dynamically compiled functionObject.
virtual bool start ()
Called at the start of the time-loop.
virtual bool execute (const bool forceWrite)
Called at each ++ or += of the time-loop. forceWrite overrides the.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &)
Update mesh.
virtual void movePoints (const polyMesh &)
Move points.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
virtual const word & name () const
Name.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Public Member Functions inherited from codedBase
ClassName ("codedBase")
Runtime type information.
codedBase ()
Construct null.
virtual ~codedBase ()
Destructor.
Protected Member Functions
virtual dlLibraryTable & libs () const
get the loaded dynamic libraries
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
adapt the context for the current object
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeDict () const
Protected Member Functions inherited from codedBase
void updateLibrary (const word &redirectType) const
Update library as required.
Protected Attributes
const Time & time_
Reference to the time database.
dictionary dict_
Input dictionary.
word redirectType_
string codeData_
string codeRead_
string codeExecute_
string codeEnd_
string codeTimeSet_
autoPtr< functionObject > redirectFunctionObjectPtr_
Underlying functionObject.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
This function object provides a general interface to enable dynamic code compilation.
The entries are code : c++; upon functionObject::write() codeInclude : include files codeOptions : include paths; inserted into EXE_INC in Make/options codeLibs : link line; inserted into LIB_LIBS in Make/options
codeExecute : c++;upon functionObject::execute(); codeRead : c++; upon functionObject::read(); codeEnd : c++; upon functionObject::end(); codeData : c++; local member data (null constructed); codeTimeSet : c++; upon functionObject::timeSet(); localCode : c++; local static functions
Example of function object specification:
difference
{
    functionObjectLibs ("libutilityFunctionObjects.so");
    type coded;
    // Name of on-the-fly generated functionObject
    redirectType writeMagU;
    code
    #{
        // Lookup U
        const volVectorField& U = mesh().lookupObject<volVectorField>("U");
        // Write
        mag(U).write();
    }
}
See also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::codedBase
Source files
codedFunctionObject.H
codedFunctionObject.C
Definition at line 91 of file codedFunctionObject.H.
Constructor & Destructor Documentation
codedFunctionObject()
codedFunctionObject (const word & name, const Time & time, const dictionary & dict, bool readNow = true)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 124 of file codedFunctionObject.C.
~codedFunctionObject()
~codedFunctionObject () virtual
Destructor.
Definition at line 145 of file codedFunctionObject.C.
Member Function Documentation
libs()
Foam::dlLibraryTable & libs () const protected virtual
get the loaded dynamic libraries
Implements codedBase.
Definition at line 97 of file codedFunctionObject.C.
prepare()
void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
adapt the context for the current object
Implements codedBase.
Definition at line 53 of file codedFunctionObject.C.
References dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), dynamicCodeContext::libs(), dynamicCodeContext::options(), dynamicCode::setFilterVariable(), and dynamicCode::setMakeOptions().
description()
Foam::string description () const protected virtual
Implements codedBase.
Definition at line 103 of file codedFunctionObject.C.
References Foam::name().
clearRedirect()
void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 109 of file codedFunctionObject.C.
codeDict()
const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 115 of file codedFunctionObject.C.
TypeName()
TypeName ("coded")
Runtime type information.
redirectFunctionObject()
Foam::functionObject & redirectFunctionObject () const
Dynamically compiled functionObject.
Definition at line 152 of file codedFunctionObject.C.
References functionObject::New(), and dictionary::set().
start()
bool start () virtual
Called at the start of the time-loop.
Implements functionObject.
Definition at line 170 of file codedFunctionObject.C.
execute()
bool execute (const bool forceWrite) virtual
Called at each ++ or += of the time-loop. forceWrite overrides the.
outputControl behaviour.
Implements functionObject.
Definition at line 177 of file codedFunctionObject.C.
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
By default it simply calls execute().
Reimplemented from functionObject.
Definition at line 184 of file codedFunctionObject.C.
timeSet()
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented from functionObject.
Definition at line 191 of file codedFunctionObject.C.
read()
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Implements functionObject.
Definition at line 198 of file codedFunctionObject.C.
References dynamicCodeContext::addLineDirective(), Foam::stringOps::inplaceExpand(), dictionary::lookup(), dictionary::lookupEntryPtr(), dictionaryName::name(), entry::startLineNumber(), entry::stream(), and Foam::stringOps::trim().
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Update mesh.
Implements functionObject.
Definition at line 297 of file codedFunctionObject.C.
movePoints()
void movePoints (const polyMesh &) virtual
Move points.
Implements functionObject.
Definition at line 301 of file codedFunctionObject.C.
Member Data Documentation
time_
const Time& time_ protected
Reference to the time database.
Definition at line 101 of file codedFunctionObject.H.
dict_
dictionary dict_ protected
Input dictionary.
Definition at line 104 of file codedFunctionObject.H.
redirectType_
word redirectType_ protected
Definition at line 106 of file codedFunctionObject.H.
codeData_
string codeData_ protected
Definition at line 108 of file codedFunctionObject.H.
codeRead_
string codeRead_ protected
Definition at line 109 of file codedFunctionObject.H.
codeExecute_
string codeExecute_ protected
Definition at line 110 of file codedFunctionObject.H.
codeEnd_
string codeEnd_ protected
Definition at line 111 of file codedFunctionObject.H.
codeTimeSet_
string codeTimeSet_ protected
Definition at line 112 of file codedFunctionObject.H.
redirectFunctionObjectPtr_
autoPtr<functionObject> redirectFunctionObjectPtr_ mutable protected
Underlying functionObject.
Definition at line 115 of file codedFunctionObject.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/codedFunctionObject/codedFunctionObject.H
src/postProcessing/functionObjects/utilities/codedFunctionObject/codedFunctionObject.C