OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
partialWrite Class Reference
Function objects » Input/output function objects
This function object allows user-selected fields/registered objects to be written at a custom write interval. The interval is given in terms of number of overall dumps.
Public Member Functions
TypeName ("partialWrite")
Runtime type information.
partialWrite (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~partialWrite ()
Destructor.
virtual const word & name () const
Return name of the partialWrite.
virtual void read (const dictionary &)
Read the partialWrite data.
virtual void execute ()
Execute.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the partialWrite.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
partialWrite (const partialWrite &)
Disallow default bitwise copy construct.
void operator= (const partialWrite &)
Disallow default bitwise assignment.
template<class Type >
void loadField (const word &, UPtrList< GeometricField< Type, fvPatchField, volMesh > > &, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
Load objects in the objectNames.
template<class Type >
void changeWriteOptions (UPtrList< GeometricField< Type, fvPatchField, volMesh > > &, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &, const IOobject::writeOption) const
Protected Attributes
word name_
Name of this set of partialWrite.
const objectRegistry & obr_
UPtrList< volScalarField > vsf_
Loaded fields.
UPtrList< volVectorField > vvf_
UPtrList< volSphericalTensorField > vSpheretf_
UPtrList< volSymmTensorField > vSymmtf_
UPtrList< volTensorField > vtf_
UPtrList< surfaceScalarField > ssf_
UPtrList< surfaceVectorField > svf_
UPtrList< surfaceSphericalTensorField > sSpheretf_
UPtrList< surfaceSymmTensorField > sSymmtf_
UPtrList< surfaceTensorField > stf_
HashSet< word > objectNames_
Names of objects to dump always.
label writeInterval_
Write interval for restart dump.
label writeInstance_
Current dump instance. If reaches writeInterval do a full write.
Detailed Description
This function object allows user-selected fields/registered objects to be written at a custom write interval. The interval is given in terms of number of overall dumps.
Example of function object specification:
partialWrite1
{
    type        partialWrite;
    functionObjectLibs ("libIOFunctionObjects.so");
    ...
    objectNames (p U T);
    writeInterval 100;
}
Function object usage
Property Description Required Default value
type type name: partialWrite yes
objectNames objects to write yes
writeInterval write interval yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
partialWrite.H
partialWrite.C
IOpartialWrite.H
Definition at line 107 of file partialWrite.H.
Constructor & Destructor Documentation
partialWrite() [1/2]
partialWrite (const partialWrite &) protected
Disallow default bitwise copy construct.
partialWrite() [2/2]
partialWrite (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 44 of file partialWrite.C.
~partialWrite()
~partialWrite () virtual
Destructor.
Definition at line 60 of file partialWrite.C.
Member Function Documentation
operator=()
void operator= (const partialWrite &) protected
Disallow default bitwise assignment.
loadField()
void loadField (const word & fieldName, UPtrList< GeometricField< Type, fvPatchField, volMesh > > & vflds, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > & sflds) const protected
Load objects in the objectNames.
Definition at line 35 of file partialWriteTemplates.C.
References partialWrite::changeWriteOptions(), Foam::endl(), and Foam::Info.
changeWriteOptions()
void changeWriteOptions (UPtrList< GeometricField< Type, fvPatchField, volMesh > > & vflds, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > & sflds, const IOobject::writeOption wOption) const protected
Definition at line 87 of file partialWriteTemplates.C.
References forAll.
Referenced by partialWrite::loadField().
TypeName()
TypeName ("partialWrite")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the partialWrite.
Definition at line 198 of file partialWrite.H.
References partialWrite::end(), partialWrite::execute(), partialWrite::name_, partialWrite::read(), partialWrite::timeSet(), and partialWrite::write().
read()
void read (const dictionary & dict) virtual
Read the partialWrite data.
Definition at line 66 of file partialWrite.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, forAllConstIter(), Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, and Foam::type().
Referenced by partialWrite::name().
execute()
void execute () virtual
Execute.
Definition at line 112 of file partialWrite.C.
Referenced by partialWrite::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 117 of file partialWrite.C.
Referenced by partialWrite::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 124 of file partialWrite.C.
References IOobject::AUTO_WRITE, and IOobject::NO_WRITE.
Referenced by partialWrite::name().
write()
void write () virtual
Write the partialWrite.
Definition at line 174 of file partialWrite.C.
Referenced by partialWrite::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 219 of file partialWrite.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 223 of file partialWrite.H.
Member Data Documentation
name_
word name_ protected
Name of this set of partialWrite.
Definition at line 114 of file partialWrite.H.
Referenced by partialWrite::name().
obr_
const objectRegistry& obr_ protected
Definition at line 116 of file partialWrite.H.
vsf_
UPtrList<volScalarField> vsf_ protected
Loaded fields.
Definition at line 119 of file partialWrite.H.
vvf_
UPtrList<volVectorField> vvf_ protected
Definition at line 120 of file partialWrite.H.
vSpheretf_
UPtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 121 of file partialWrite.H.
vSymmtf_
UPtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 122 of file partialWrite.H.
vtf_
UPtrList<volTensorField> vtf_ protected
Definition at line 123 of file partialWrite.H.
ssf_
UPtrList<surfaceScalarField> ssf_ protected
Definition at line 125 of file partialWrite.H.
svf_
UPtrList<surfaceVectorField> svf_ protected
Definition at line 126 of file partialWrite.H.
sSpheretf_
UPtrList<surfaceSphericalTensorField> sSpheretf_ protected
Definition at line 127 of file partialWrite.H.
sSymmtf_
UPtrList<surfaceSymmTensorField> sSymmtf_ protected
Definition at line 128 of file partialWrite.H.
stf_
UPtrList<surfaceTensorField> stf_ protected
Definition at line 129 of file partialWrite.H.
objectNames_
HashSet<word> objectNames_ protected
Names of objects to dump always.
Definition at line 134 of file partialWrite.H.
writeInterval_
label writeInterval_ protected
Write interval for restart dump.
Definition at line 137 of file partialWrite.H.
writeInstance_
label writeInstance_ protected
Current dump instance. If reaches writeInterval do a full write.
Definition at line 142 of file partialWrite.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/IO/partialWrite/partialWrite.H
src/postProcessing/functionObjects/IO/partialWrite/partialWrite.C
src/postProcessing/functionObjects/IO/partialWrite/partialWriteTemplates.C