OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Lambda2 Class Reference
Function objects » Utility function objects
This function object calculates and outputs the second largest eigenvalue of the sum of the square of the symmetrical and anti-symmetrical parts of the velocity gradient tensor.
Public Member Functions
TypeName ("Lambda2")
Runtime type information.
Lambda2 (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~Lambda2 ()
Destructor.
virtual const word & name () const
Return name of the set of Lambda2.
virtual void read (const dictionary &)
Read the Lambda2 data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the Lambda2 and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object calculates and outputs the second largest eigenvalue of the sum of the square of the symmetrical and anti-symmetrical parts of the velocity gradient tensor.
Source files
Lambda2.H
Lambda2.C
IOLambda2.H
Definition at line 63 of file Lambda2.H.
Constructor & Destructor Documentation
Lambda2()
Lambda2 (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 43 of file Lambda2.C.
References Foam::dimless, Foam::dimTime, Foam::endl(), mesh, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, Foam::sqr(), fvMesh::time(), Time::timeName(), Foam::type(), and WarningIn.
~Lambda2()
~Lambda2 () virtual
Destructor.
Definition at line 102 of file Lambda2.C.
Member Function Documentation
TypeName()
TypeName ("Lambda2")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of Lambda2.
Definition at line 115 of file Lambda2.H.
References Lambda2::end(), Lambda2::execute(), Lambda2::read(), Lambda2::timeSet(), and Lambda2::write().
read()
void read (const dictionary & dict) virtual
Read the Lambda2 data.
Definition at line 108 of file Lambda2.C.
References dictionary::lookupOrDefault().
Referenced by Lambda2::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 117 of file Lambda2.C.
References Foam::component(), Foam::eigenValues(), Foam::fvc::grad(), objectRegistry::lookupObject(), mesh, Foam::skew(), Foam::symm(), Foam::type(), U, and Vector< Cmpt >::Y.
Referenced by Lambda2::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 145 of file Lambda2.C.
Referenced by Lambda2::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 154 of file Lambda2.C.
Referenced by Lambda2::name().
write()
void write () virtual
Calculate the Lambda2 and write.
Definition at line 160 of file Lambda2.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by Lambda2::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 136 of file Lambda2.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 140 of file Lambda2.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/Lambda2/Lambda2.H
src/postProcessing/functionObjects/utilities/Lambda2/Lambda2.C