OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pressureTools Class Reference
Function objects » Utility function objects
This function object includes tools to manipulate the pressure into different forms. These currently include:
Public Member Functions
TypeName ("pressureTools")
Runtime type information.
pressureTools (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~pressureTools ()
Destructor.
virtual const word & name () const
Return name of the set of pressureTools.
virtual void read (const dictionary &)
Read the pressureTools data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the pressureTools and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object includes tools to manipulate the pressure into different forms. These currently include:
- static pressure
total pressure
static pressure coefficient
total pressure coefficient
where
= density [kg/m3]
= velocity [m/s]
= freestream density [kg/m3]
= freestream pressure [Pa]
= freestream velocity [m/s]
= kinematic pressure (p/rho)[m2/s2]
= pressure [Pa]
= total pressure [Pa]
= reference pressure level [Pa]
= pressure coefficient
= total pressure coefficient
The function object will operate on both kinematic () and static pressure () fields, and the result is written as a volScalarField.
The modes of operation are:
Mode calcTotal calcCoeff
static pressure no no
total pressure yes no
pressure coefficient no yes
total pressure coefficient yes yes
Example of function object specification to calculate pressure coefficient:
    pressureTools1
    {
        type        pressureTools;
        functionObjectLibs ("libutilityFunctionObjects.so");
        ...
        calcTotal   no;
        calcCoeff   yes;
    }
Function object usage
Property Description Required Default value
type type name: pressureTools yes
calcTotal Calculate total coefficient yes
pRef Reference pressure for total pressure no 0.0
calcCoeff Calculate pressure coefficient yes
pInf Freestream pressure for coefficient calculation no
UInf Freestream velocity for coefficient calculation no
rhoInf Freestream density for coefficient calculation no
Source files
pressureTools.H
pressureTools.C
IOpressureTools.H
Definition at line 233 of file pressureTools.H.
Constructor & Destructor Documentation
pressureTools()
pressureTools (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 183 of file pressureTools.C.
References Foam::dimPressure, Foam::endl(), mesh, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), Time::timeName(), and WarningIn.
~pressureTools()
~pressureTools () virtual
Destructor.
Definition at line 257 of file pressureTools.C.
Member Function Documentation
TypeName()
TypeName ("pressureTools")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of pressureTools.
Definition at line 333 of file pressureTools.H.
References pressureTools::end(), pressureTools::execute(), pressureTools::read(), pressureTools::timeSet(), and pressureTools::write().
read()
void read (const dictionary & dict) virtual
Read the pressureTools data.
Definition at line 263 of file pressureTools.C.
References Foam::endl(), dictionary::lookup(), Foam::mag(), Foam::magSqr(), dictionary::readIfPresent(), Foam::type(), and WarningIn.
Referenced by pressureTools::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 304 of file pressureTools.C.
References pDyn(), and pRef.
Referenced by pressureTools::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 321 of file pressureTools.C.
Referenced by pressureTools::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 330 of file pressureTools.C.
Referenced by pressureTools::name().
write()
void write () virtual
Calculate the pressureTools and write.
Definition at line 336 of file pressureTools.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by pressureTools::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 354 of file pressureTools.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 358 of file pressureTools.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/pressureTools/pressureTools.H
src/postProcessing/functionObjects/utilities/pressureTools/pressureTools.C