OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
writeDictionary Class Reference
Function objects » Utility function objects
This function object writes dictionaries on start-up, and on change.
Public Member Functions
TypeName ("writeDictionary")
Runtime type information.
writeDictionary (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~writeDictionary ()
Destructor.
virtual const word & name () const
Return name of the writeDictionary.
virtual void read (const dictionary &)
Read the writeDictionary data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the writeDictionary.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
bool tryDirectory (const label dictI, const word &location, bool &firstDict)
Helper function to write the dictionary if found at location.
writeDictionary (const writeDictionary &)
Disallow default bitwise copy construct.
void operator= (const writeDictionary &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of writeDictionary.
const objectRegistry & obr_
Reference to the database.
wordList dictNames_
Names of dictionaries to monitor.
List< SHA1Digest > digests_
List of changed dictionaries (only those registered to database)
Detailed Description
This function object writes dictionaries on start-up, and on change.
Source files
writeDictionary.H
writeDictionary.C
IOwriteDictionary.H
Definition at line 60 of file writeDictionary.H.
Constructor & Destructor Documentation
writeDictionary() [1/2]
writeDictionary (const writeDictionary &) protected
Disallow default bitwise copy construct.
Referenced by writeDictionary::tryDirectory().
writeDictionary() [2/2]
writeDictionary (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 90 of file writeDictionary.C.
~writeDictionary()
~writeDictionary () virtual
Destructor.
Definition at line 110 of file writeDictionary.C.
Member Function Documentation
tryDirectory()
bool tryDirectory (const label dictI, const word & location, bool & firstDict) protected
Helper function to write the dictionary if found at location.
Definition at line 42 of file writeDictionary.C.
References dict, dictIO(), dictionaryName::dictName(), dictionary::digest(), Foam::endl(), IOobject::headerOk(), Foam::Info, IOobject::MUST_READ, Foam::nl, IOobject::NO_WRITE, Foam::type(), writeDictionary::writeDictionary(), and IOobject::writeDivider().
operator=()
void operator= (const writeDictionary &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("writeDictionary")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the writeDictionary.
Definition at line 122 of file writeDictionary.H.
References writeDictionary::end(), writeDictionary::execute(), writeDictionary::name_, writeDictionary::read(), writeDictionary::timeSet(), and writeDictionary::write().
read()
void read (const dictionary & dict) virtual
Read the writeDictionary data.
Definition at line 116 of file writeDictionary.C.
References Foam::endl(), forAll, Foam::Info, dictionary::lookup(), Foam::nl, and Foam::type().
Referenced by writeDictionary::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 140 of file writeDictionary.C.
References dictionaryName::dictName(), dictionary::digest(), Foam::endl(), forAll, Foam::Info, Foam::nl, Foam::type(), and IOobject::writeDivider().
Referenced by writeDictionary::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 196 of file writeDictionary.C.
Referenced by writeDictionary::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 202 of file writeDictionary.C.
Referenced by writeDictionary::name().
write()
void write () virtual
Write the writeDictionary.
Definition at line 208 of file writeDictionary.C.
Referenced by writeDictionary::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 143 of file writeDictionary.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 147 of file writeDictionary.H.
Member Data Documentation
name_
word name_ protected
Name of this set of writeDictionary.
Definition at line 67 of file writeDictionary.H.
Referenced by writeDictionary::name().
obr_
const objectRegistry& obr_ protected
Reference to the database.
Definition at line 70 of file writeDictionary.H.
dictNames_
wordList dictNames_ protected
Names of dictionaries to monitor.
Definition at line 73 of file writeDictionary.H.
digests_
List<SHA1Digest> digests_ protected
List of changed dictionaries (only those registered to database)
Definition at line 76 of file writeDictionary.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/IO/writeDictionary/writeDictionary.H
src/postProcessing/functionObjects/IO/writeDictionary/writeDictionary.C