OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
abortCalculation Class Reference
Function objects » Job control function objects
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
Public Types
enum actionType { noWriteNow, writeNow, nextWrite }
Enumeration defining the type of action.
Public Member Functions
TypeName ("abort")
Runtime type information.
abortCalculation (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFilesUnused=false)
Construct for given objectRegistry and dictionary.
virtual ~abortCalculation ()
Destructor.
virtual const word & name () const
Return name of the abort file.
virtual void read (const dictionary &)
Read the dictionary settings.
virtual void execute ()
Execute, check existence of abort file and take action.
virtual void end ()
Execute at the final time-loop, used for cleanup.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Execute, check existence of abort file and take action.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh - does nothing.
virtual void movePoints (const polyMesh &)
Update for changes of mesh - does nothing.
Detailed Description
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
Currently the following action types are supported:
noWriteNow
writeNow
nextWrite
Source files
abortCalculation.H
abortCalculation.C
IOabortCalculation.H
Definition at line 64 of file abortCalculation.H.
Member Enumeration Documentation
actionType
enum actionType
Enumeration defining the type of action.
Enumerator
noWriteNow
stop immediately without writing data
writeNow
write data and stop immediately
nextWrite
stop the next time data are written
Definition at line 71 of file abortCalculation.H.
Constructor & Destructor Documentation
abortCalculation()
abortCalculation (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFilesUnused = false)
Construct for given objectRegistry and dictionary.
Definition at line 81 of file abortCalculation.C.
~abortCalculation()
~abortCalculation () virtual
Destructor.
Definition at line 103 of file abortCalculation.C.
Member Function Documentation
TypeName()
TypeName ("abort")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the abort file.
Definition at line 134 of file abortCalculation.H.
References abortCalculation::end(), abortCalculation::execute(), abortCalculation::read(), abortCalculation::timeSet(), and abortCalculation::write().
read()
void read (const dictionary & dict) virtual
Read the dictionary settings.
Definition at line 109 of file abortCalculation.C.
References dictionary::found(), dictionary::lookup(), and dictionary::readIfPresent().
Referenced by abortCalculation::name().
execute()
void execute () virtual
Execute, check existence of abort file and take action.
Definition at line 127 of file abortCalculation.C.
References Foam::endl(), Foam::Info, Foam::isFile(), Foam::reduce(), Time::saNextWrite, Time::saNoWriteNow, and Time::saWriteNow.
Referenced by abortCalculation::name().
end()
void end () virtual
Execute at the final time-loop, used for cleanup.
Definition at line 176 of file abortCalculation.C.
Referenced by abortCalculation::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 182 of file abortCalculation.C.
Referenced by abortCalculation::name().
write()
void write () virtual
Execute, check existence of abort file and take action.
Definition at line 188 of file abortCalculation.C.
Referenced by abortCalculation::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh - does nothing.
Definition at line 155 of file abortCalculation.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh - does nothing.
Definition at line 159 of file abortCalculation.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/jobControl/abortCalculation/abortCalculation.H
src/postProcessing/functionObjects/jobControl/abortCalculation/abortCalculation.C