OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
writeRegisteredObject Class Reference
Function objects » Input/output function objects
This function object allows specification of different writing frequency of objects registered to the database. It has similar functionality as the main time database through the outputControl setting: timeStep outputTime adjustableTime runTime clockTime cpuTime.
Public Member Functions
TypeName ("writeRegisteredObject")
Runtime type information.
writeRegisteredObject (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~writeRegisteredObject ()
Destructor.
virtual const word & name () const
Return name of the writeRegisteredObject.
virtual void read (const dictionary &)
Read the writeRegisteredObject data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the writeRegisteredObject.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
writeRegisteredObject (const writeRegisteredObject &)
Disallow default bitwise copy construct.
void operator= (const writeRegisteredObject &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of writeRegisteredObject.
bool exclusiveWriting_
Takes over the writing from Db.
const objectRegistry & obr_
Refererence to Db.
wordReList objectNames_
Names of objects to control.
Detailed Description
This function object allows specification of different writing frequency of objects registered to the database. It has similar functionality as the main time database through the outputControl setting: timeStep outputTime adjustableTime runTime clockTime cpuTime.
Example of function object specification:
writeRegisteredObject1
{
    type        writeRegisteredObject;
    functionObjectLibs ("libIOFunctionObjects.so");
    exclusiveWriting     true;
    ...
    objectNames (obj1 obj2);
}
Function object usage
Property Description Required Default value
type type name: writeRegisteredObject yes
objectNames objects to write yes
exclusiveWriting Takes over object writing no yes
exclusiveWriting disables automatic writing (i.e through database) of the objects to avoid duplicate writing.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
writeRegisteredObject.H
writeRegisteredObject.C
IOwriteRegisteredObject.H
Definition at line 114 of file writeRegisteredObject.H.
Constructor & Destructor Documentation
writeRegisteredObject() [1/2]
writeRegisteredObject (const writeRegisteredObject &) protected
Disallow default bitwise copy construct.
writeRegisteredObject() [2/2]
writeRegisteredObject (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 41 of file writeRegisteredObject.C.
~writeRegisteredObject()
~writeRegisteredObject () virtual
Destructor.
Definition at line 59 of file writeRegisteredObject.C.
Member Function Documentation
operator=()
void operator= (const writeRegisteredObject &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("writeRegisteredObject")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the writeRegisteredObject.
Definition at line 171 of file writeRegisteredObject.H.
References writeRegisteredObject::end(), writeRegisteredObject::execute(), writeRegisteredObject::name_, writeRegisteredObject::read(), writeRegisteredObject::timeSet(), and writeRegisteredObject::write().
read()
void read (const dictionary & dict) virtual
Read the writeRegisteredObject data.
Definition at line 65 of file writeRegisteredObject.C.
References dictionary::lookup(), and dictionary::readIfPresent().
Referenced by writeRegisteredObject::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 72 of file writeRegisteredObject.C.
Referenced by writeRegisteredObject::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 78 of file writeRegisteredObject.C.
Referenced by writeRegisteredObject::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 84 of file writeRegisteredObject.C.
Referenced by writeRegisteredObject::name().
write()
void write () virtual
Write the writeRegisteredObject.
Definition at line 90 of file writeRegisteredObject.C.
References Foam::endl(), forAll, Foam::Info, IOobject::name(), Foam::nl, IOobject::NO_WRITE, List< T >::size(), Foam::type(), WarningIn, regIOobject::write(), and IOobject::writeOpt().
Referenced by writeRegisteredObject::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 192 of file writeRegisteredObject.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 196 of file writeRegisteredObject.H.
Member Data Documentation
name_
word name_ protected
Name of this set of writeRegisteredObject.
Definition at line 121 of file writeRegisteredObject.H.
Referenced by writeRegisteredObject::name().
exclusiveWriting_
bool exclusiveWriting_ protected
Takes over the writing from Db.
Definition at line 124 of file writeRegisteredObject.H.
obr_
const objectRegistry& obr_ protected
Refererence to Db.
Definition at line 127 of file writeRegisteredObject.H.
objectNames_
wordReList objectNames_ protected
Names of objects to control.
Definition at line 132 of file writeRegisteredObject.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/IO/writeRegisteredObject/writeRegisteredObject.H
src/postProcessing/functionObjects/IO/writeRegisteredObject/writeRegisteredObject.C