OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DESModelRegions Class Reference
Function objects » Utility function objects
This function object writes out an indicator field for DES turbulence calculations, that is:
Public Member Functions
TypeName ("DESModelRegions")
Runtime type information.
DESModelRegions (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~DESModelRegions ()
Destructor.
virtual const word & name () const
Return name of the set of DESModelRegions.
virtual void read (const dictionary &)
Read the DESModelRegions data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the DESModelRegions and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
virtual void writeFileHeader (const label i)
File header information.
DESModelRegions (const DESModelRegions &)
Disallow default bitwise copy construct.
void operator= (const DESModelRegions &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of DESModelRegions object.
const objectRegistry & obr_
bool active_
on/off switch
Switch log_
Switch to send output to Info as well as to file.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
This function object writes out an indicator field for DES turbulence calculations, that is:
- 0 for RAS regions
1 for LES regions
Source files
DESModelRegions.H
DESModelRegions.C
IODESModelRegions.H
Definition at line 66 of file DESModelRegions.H.
Constructor & Destructor Documentation
DESModelRegions() [1/2]
DESModelRegions (const DESModelRegions &) protected
Disallow default bitwise copy construct.
Referenced by DESModelRegions::writeFileHeader().
DESModelRegions() [2/2]
DESModelRegions (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 57 of file DESModelRegions.C.
References Foam::dimless, Foam::endl(), mesh, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), Time::timeName(), Foam::type(), and WarningIn.
~DESModelRegions()
~DESModelRegions () virtual
Destructor.
Definition at line 117 of file DESModelRegions.C.
Member Function Documentation
writeFileHeader()
void writeFileHeader (const label i) protected virtual
File header information.
Reimplemented from functionObjectFile.
Definition at line 43 of file DESModelRegions.C.
References DESModelRegions::DESModelRegions(), and Foam::endl().
operator=()
void operator= (const DESModelRegions &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("DESModelRegions")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of DESModelRegions.
Definition at line 124 of file DESModelRegions.H.
References DESModelRegions::end(), DESModelRegions::execute(), DESModelRegions::name_, DESModelRegions::read(), DESModelRegions::timeSet(), and DESModelRegions::write().
read()
void read (const dictionary & dict) virtual
Read the DESModelRegions data.
Definition at line 123 of file DESModelRegions.C.
References dictionary::lookupOrDefault().
Referenced by DESModelRegions::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 132 of file DESModelRegions.C.
References Foam::endl(), objectRegistry::foundObject(), Foam::gSum(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), objectRegistry::lookupObject(), UPstream::master(), mesh, Foam::nl, token::TAB, Foam::type(), fvMesh::V(), and functionObjectFile::write().
Referenced by DESModelRegions::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 210 of file DESModelRegions.C.
Referenced by DESModelRegions::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 219 of file DESModelRegions.C.
Referenced by DESModelRegions::name().
write()
void write () virtual
Calculate the DESModelRegions and write.
Reimplemented from functionObjectFile.
Definition at line 225 of file DESModelRegions.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by DESModelRegions::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 145 of file DESModelRegions.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 149 of file DESModelRegions.H.
Member Data Documentation
name_
word name_ protected
Name of this set of DESModelRegions object.
Definition at line 75 of file DESModelRegions.H.
Referenced by DESModelRegions::name().
obr_
const objectRegistry& obr_ protected
Definition at line 77 of file DESModelRegions.H.
active_
bool active_ protected
on/off switch
Definition at line 80 of file DESModelRegions.H.
log_
Switch log_ protected
Switch to send output to Info as well as to file.
Definition at line 83 of file DESModelRegions.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/DESModelRegions/DESModelRegions.H
src/postProcessing/functionObjects/utilities/DESModelRegions/DESModelRegions.C