OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
removeRegisteredObject Class Reference
Function objects » Input/output function objects
This function object removes registered objects if present in the database.
Public Member Functions
TypeName ("removeRegisteredObject")
Runtime type information.
removeRegisteredObject (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~removeRegisteredObject ()
Destructor.
virtual const word & name () const
Return name of the removeRegisteredObject.
virtual void read (const dictionary &)
Read the removeRegisteredObject data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the removeRegisteredObject.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
removeRegisteredObject (const removeRegisteredObject &)
Disallow default bitwise copy construct.
void operator= (const removeRegisteredObject &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of removeRegisteredObject.
const objectRegistry & obr_
wordList objectNames_
Names of objects to control.
Detailed Description
This function object removes registered objects if present in the database.
Example of function object specification:
removeRegisteredObject1
{
    type        removeRegisteredObject;
    functionObjectLibs ("libIOFunctionObjects.so");
    ...
    objectNames (obj1 obj2);
}
Function object usage
Property Description Required Default value
type type name: removeRegisteredObject yes
objectNames objects to remove yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
removeRegisteredObject.H
removeRegisteredObject.C
IOremoveRegisteredObject.H
Definition at line 96 of file removeRegisteredObject.H.
Constructor & Destructor Documentation
removeRegisteredObject() [1/2]
removeRegisteredObject (const removeRegisteredObject &) protected
Disallow default bitwise copy construct.
removeRegisteredObject() [2/2]
removeRegisteredObject (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 41 of file removeRegisteredObject.C.
~removeRegisteredObject()
~removeRegisteredObject () virtual
Destructor.
Definition at line 58 of file removeRegisteredObject.C.
Member Function Documentation
operator=()
void operator= (const removeRegisteredObject &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("removeRegisteredObject")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the removeRegisteredObject.
Definition at line 149 of file removeRegisteredObject.H.
References removeRegisteredObject::end(), removeRegisteredObject::execute(), removeRegisteredObject::name_, removeRegisteredObject::read(), removeRegisteredObject::timeSet(), and removeRegisteredObject::write().
read()
void read (const dictionary & dict) virtual
Read the removeRegisteredObject data.
Definition at line 64 of file removeRegisteredObject.C.
References dictionary::lookup().
Referenced by removeRegisteredObject::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 70 of file removeRegisteredObject.C.
References Foam::endl(), forAll, Foam::Info, IOobject::name(), Foam::nl, regIOobject::ownedByRegistry(), and Foam::type().
Referenced by removeRegisteredObject::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 93 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 99 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::name().
write()
void write () virtual
Write the removeRegisteredObject.
Definition at line 105 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 170 of file removeRegisteredObject.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 174 of file removeRegisteredObject.H.
Member Data Documentation
name_
word name_ protected
Name of this set of removeRegisteredObject.
Definition at line 103 of file removeRegisteredObject.H.
Referenced by removeRegisteredObject::name().
obr_
const objectRegistry& obr_ protected
Definition at line 105 of file removeRegisteredObject.H.
objectNames_
wordList objectNames_ protected
Names of objects to control.
Definition at line 110 of file removeRegisteredObject.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/IO/removeRegisteredObject/removeRegisteredObject.H
src/postProcessing/functionObjects/IO/removeRegisteredObject/removeRegisteredObject.C