OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dsmcFields Class Reference
Function objects » Utility function objects
Calculate intensive fields:
Public Member Functions
TypeName ("dsmcFields")
Runtime type information.
dsmcFields (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~dsmcFields ()
Destructor.
virtual const word & name () const
Return name of the set of dsmcFields.
virtual void read (const dictionary &)
Read the dsmcFields data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the dsmcFields and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
Calculate intensive fields:
- UMean
translationalT
internalT
overallT from averaged extensive fields from a DSMC calculation.
Source files
dsmcFields.H
dsmcFields.C
IOdsmcFields.H
Definition at line 63 of file dsmcFields.H.
Constructor & Destructor Documentation
dsmcFields()
dsmcFields (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 46 of file dsmcFields.C.
References Foam::endl(), Foam::nl, and WarningIn.
~dsmcFields()
~dsmcFields () virtual
Destructor.
Definition at line 80 of file dsmcFields.C.
Member Function Documentation
TypeName()
TypeName ("dsmcFields")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of dsmcFields.
Definition at line 111 of file dsmcFields.H.
References dsmcFields::end(), dsmcFields::execute(), dsmcFields::read(), dsmcFields::timeSet(), and dsmcFields::write().
read()
void read (const dictionary & dict) virtual
Read the dsmcFields data.
Definition at line 86 of file dsmcFields.C.
Referenced by dsmcFields::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 95 of file dsmcFields.C.
Referenced by dsmcFields::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 101 of file dsmcFields.C.
Referenced by dsmcFields::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 107 of file dsmcFields.C.
Referenced by dsmcFields::name().
write()
void write () virtual
Calculate the dsmcFields and write.
Definition at line 113 of file dsmcFields.C.
References polyPatch::boundaryMesh(), Foam::endl(), polyPatch::faceAreas(), forAll, Foam::Info, Foam::constant::physicoChemical::k, Foam::mag(), Foam::max(), mesh, Foam::min(), Foam::nl, IOobject::NO_READ, p, UMean(), Ostream::write(), and regIOobject::write().
Referenced by dsmcFields::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 132 of file dsmcFields.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 136 of file dsmcFields.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/dsmcFields/dsmcFields.H
src/postProcessing/functionObjects/utilities/dsmcFields/dsmcFields.C