OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
calcFvcGrad Class Reference
Function objects » Finite volume tools function objects
This function object calculates the gradient of a field. The operation is limited to scalar and vector volume or surface fields, and the output is a volume vector or tensor field.
Public Member Functions
TypeName ("calcFvcGrad")
Runtime type information.
calcFvcGrad (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~calcFvcGrad ()
Destructor.
virtual const word & name () const
Return name of the set of calcFvcGrad.
virtual void read (const dictionary &)
Read the calcFvcGrad data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the calcFvcGrad and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
template<class Type >
Foam::GeometricField< typename Foam::outerProduct< Foam::vector, Type >::type, Foam::fvPatchField, Foam::volMesh > & gradField (const word &gradName, const dimensionSet &dims)
Detailed Description
This function object calculates the gradient of a field. The operation is limited to scalar and vector volume or surface fields, and the output is a volume vector or tensor field.
Source files
calcFvcGrad.H
calcFvcGrad.C
IOcalcFvcGrad.H
Definition at line 65 of file calcFvcGrad.H.
Constructor & Destructor Documentation
calcFvcGrad()
calcFvcGrad (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 42 of file calcFvcGrad.C.
References Foam::endl(), Foam::nl, and WarningIn.
~calcFvcGrad()
~calcFvcGrad () virtual
Destructor.
Definition at line 78 of file calcFvcGrad.C.
Member Function Documentation
TypeName()
TypeName ("calcFvcGrad")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of calcFvcGrad.
Definition at line 139 of file calcFvcGrad.H.
References calcFvcGrad::end(), calcFvcGrad::execute(), calcFvcGrad::read(), calcFvcGrad::timeSet(), and calcFvcGrad::write().
read()
void read (const dictionary & dict) virtual
Read the calcFvcGrad data.
Definition at line 84 of file calcFvcGrad.C.
References dictionary::lookup().
Referenced by calcFvcGrad::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 99 of file calcFvcGrad.C.
References Foam::endl(), and WarningIn.
Referenced by calcFvcGrad::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 117 of file calcFvcGrad.C.
Referenced by calcFvcGrad::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 126 of file calcFvcGrad.C.
Referenced by calcFvcGrad::name().
write()
void write () virtual
Calculate the calcFvcGrad and write.
Definition at line 132 of file calcFvcGrad.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by calcFvcGrad::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 160 of file calcFvcGrad.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 164 of file calcFvcGrad.H.
gradField()
Foam::GeometricField< typename Foam::outerProduct<Foam::vector, Type>::type, Foam::fvPatchField, Foam::volMesh>& gradField (const word & gradName, const dimensionSet & dims)
Definition at line 36 of file calcFvcGradTemplates.C.
References Foam::dimLength, objectRegistry::foundObject(), Foam::fvc::grad(), objectRegistry::lookupObject(), mesh, IOobject::NO_READ, IOobject::NO_WRITE, sf(), fvMesh::time(), and Time::timeName().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/fvTools/calcFvcGrad/calcFvcGrad.H
src/postProcessing/functionObjects/fvTools/calcFvcGrad/calcFvcGrad.C
src/postProcessing/functionObjects/fvTools/calcFvcGrad/calcFvcGradTemplates.C