OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
calcMag Class Reference
Function objects » Finite volume tools function objects
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
Public Member Functions
TypeName ("calcMag")
Runtime type information.
calcMag (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~calcMag ()
Destructor.
virtual const word & name () const
Return name of the set of calcMag.
virtual void read (const dictionary &)
Read the calcMag data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the calcMag and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
Source files
calcMag.H
calcMag.C
IOcalcMag.H
Definition at line 65 of file calcMag.H.
Constructor & Destructor Documentation
calcMag()
calcMag (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 42 of file calcMag.C.
References Foam::endl(), Foam::nl, and WarningIn.
~calcMag()
~calcMag () virtual
Destructor.
Definition at line 78 of file calcMag.C.
Member Function Documentation
TypeName()
TypeName ("calcMag")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of calcMag.
Definition at line 133 of file calcMag.H.
References calcMag::end(), calcMag::execute(), calcMag::read(), calcMag::timeSet(), and calcMag::write().
read()
void read (const dictionary & dict) virtual
Read the calcMag data.
Definition at line 84 of file calcMag.C.
References dictionary::lookup().
Referenced by calcMag::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 99 of file calcMag.C.
References Foam::endl(), and WarningIn.
Referenced by calcMag::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 120 of file calcMag.C.
Referenced by calcMag::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 129 of file calcMag.C.
Referenced by calcMag::name().
write()
void write () virtual
Calculate the calcMag and write.
Definition at line 135 of file calcMag.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by calcMag::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 154 of file calcMag.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 158 of file calcMag.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/fvTools/calcMag/calcMag.H
src/postProcessing/functionObjects/fvTools/calcMag/calcMag.C
src/postProcessing/functionObjects/fvTools/calcMag/calcMagTemplates.C