OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
blendingFactor Class Reference
Function objects » Utility function objects
This function object calculates and outputs the blendingFactor as used by the bended convection schemes. The output is a volume field (cells) whose value is calculated via the maximum blending factor for any cell face.
Public Member Functions
TypeName ("blendingFactor")
Runtime type information.
blendingFactor (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~blendingFactor ()
Destructor.
virtual const word & name () const
Return name of the set of blendingFactor.
virtual void read (const dictionary &)
Read the blendingFactor data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the blendingFactor and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
template<class Type >
Foam::volScalarField & factor (const GeometricField< Type, fvPatchField, volMesh > &field)
Detailed Description
This function object calculates and outputs the blendingFactor as used by the bended convection schemes. The output is a volume field (cells) whose value is calculated via the maximum blending factor for any cell face.
Source files
blendingFactor.H
blendingFactor.C
IOblendingFactor.H
Definition at line 64 of file blendingFactor.H.
Constructor & Destructor Documentation
blendingFactor()
blendingFactor (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 40 of file blendingFactor.C.
References Foam::endl(), Foam::nl, and WarningIn.
~blendingFactor()
~blendingFactor () virtual
Destructor.
Definition at line 76 of file blendingFactor.C.
Member Function Documentation
TypeName()
TypeName ("blendingFactor")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of blendingFactor.
Definition at line 130 of file blendingFactor.H.
References blendingFactor::end(), blendingFactor::execute(), blendingFactor::read(), blendingFactor::timeSet(), and blendingFactor::write().
read()
void read (const dictionary & dict) virtual
Read the blendingFactor data.
Definition at line 82 of file blendingFactor.C.
References dictionary::lookup(), and dictionary::lookupOrDefault().
Referenced by blendingFactor::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 92 of file blendingFactor.C.
Referenced by blendingFactor::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 102 of file blendingFactor.C.
Referenced by blendingFactor::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 110 of file blendingFactor.C.
Referenced by blendingFactor::name().
write()
void write () virtual
Calculate the blendingFactor and write.
Definition at line 116 of file blendingFactor.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by blendingFactor::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 151 of file blendingFactor.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 155 of file blendingFactor.H.
factor()
Foam::volScalarField& factor (const GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 34 of file blendingFactorTemplates.C.
References blendedSchemeBase< Type >::blendingFactor(), Foam::fvc::cellReduce(), Foam::dimless, fvSchemes::divScheme(), Foam::exit(), Foam::FatalError, FatalErrorIn, objectRegistry::foundObject(), gaussConvectionScheme< Type >::interpScheme(), Foam::isA(), objectRegistry::lookupObject(), mesh, IOobject::name(), convectionScheme< Type >::New(), phi, regIOobject::store(), fvMesh::time(), and Time::timeName().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/blendingFactor/blendingFactor.H
src/postProcessing/functionObjects/utilities/blendingFactor/blendingFactor.C
src/postProcessing/functionObjects/utilities/blendingFactor/blendingFactorTemplates.C