OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
timeActivatedFileUpdate Class Reference
Function objects » Utility function objects
Performs a file copy/replacement once a specified time has been reached.
Public Member Functions
TypeName ("timeActivatedFileUpdate")
Runtime type information.
timeActivatedFileUpdate (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~timeActivatedFileUpdate ()
Destructor.
virtual const word & name () const
Return name of the set of timeActivatedFileUpdate.
virtual void read (const dictionary &)
Read the timeActivatedFileUpdate data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the timeActivatedFileUpdate and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
Performs a file copy/replacement once a specified time has been reached.
Example usage to update the fvSolution dictionary at various times throughout the calculation:
fileUpdate1
{
    type              timeActivatedFileUpdate;
    functionObjectLibs ("libutilityFunctionObjects.so");
    outputControl     timeStep;
    outputInterval    1;
    fileToUpdate      "$FOAM_CASE/system/fvSolution";
    timeVsFile
    (
        (-1 "$FOAM_CASE/system/fvSolution.0")
        (0.10 "$FOAM_CASE/system/fvSolution.10")
        (0.20 "$FOAM_CASE/system/fvSolution.20")
        (0.35 "$FOAM_CASE/system/fvSolution.35")
    );
}
Source files
timeActivatedFileUpdate.H
timeActivatedFileUpdate.C
IOtimeActivatedFileUpdate.H
Definition at line 79 of file timeActivatedFileUpdate.H.
Constructor & Destructor Documentation
timeActivatedFileUpdate()
timeActivatedFileUpdate (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 67 of file timeActivatedFileUpdate.C.
~timeActivatedFileUpdate()
~timeActivatedFileUpdate () virtual
Destructor.
Definition at line 87 of file timeActivatedFileUpdate.C.
Member Function Documentation
TypeName()
TypeName ("timeActivatedFileUpdate")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of timeActivatedFileUpdate.
Definition at line 140 of file timeActivatedFileUpdate.H.
References timeActivatedFileUpdate::end(), timeActivatedFileUpdate::execute(), timeActivatedFileUpdate::read(), timeActivatedFileUpdate::timeSet(), and timeActivatedFileUpdate::write().
read()
void read (const dictionary & dict) virtual
Read the timeActivatedFileUpdate data.
Definition at line 93 of file timeActivatedFileUpdate.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, Foam::Info, Foam::isFile(), dictionary::lookup(), Foam::nl, Foam::tab, and Foam::type().
Referenced by timeActivatedFileUpdate::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 124 of file timeActivatedFileUpdate.C.
Referenced by timeActivatedFileUpdate::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 133 of file timeActivatedFileUpdate.C.
Referenced by timeActivatedFileUpdate::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 142 of file timeActivatedFileUpdate.C.
Referenced by timeActivatedFileUpdate::name().
write()
void write () virtual
Calculate the timeActivatedFileUpdate and write.
Definition at line 148 of file timeActivatedFileUpdate.C.
Referenced by timeActivatedFileUpdate::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 161 of file timeActivatedFileUpdate.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 165 of file timeActivatedFileUpdate.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/timeActivatedFileUpdate/timeActivatedFileUpdate.H
src/postProcessing/functionObjects/utilities/timeActivatedFileUpdate/timeActivatedFileUpdate.C