OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulenceFields Class Reference
Function objects » Field function objects
This function object stores turbulence fields on the mesh database for further manipulation.
Public Types
enum compressibleField {
cfR, cfDevRhoReff, cfMut, cfMuEff,
cfAlphat, cfAlphaEff
}
enum incompressibleField { ifR, ifDevReff, ifNut, ifNuEff }
Public Member Functions
TypeName ("turbulenceFields")
Runtime type information.
turbulenceFields (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~turbulenceFields ()
Destructor.
virtual const word & name () const
Return name of the turbulenceFields object.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Static Public Attributes
static const NamedEnum< compressibleField, 6 > compressibleFieldNames_
static const NamedEnum< incompressibleField, 4 > incompressibleFieldNames_
static const word modelName = "turbulenceModel"
Protected Member Functions
turbulenceFields (const turbulenceFields &)
Disallow default bitwise copy construct.
void operator= (const turbulenceFields &)
Disallow default bitwise assignment.
bool compressible ()
Return true if compressible turbulence model is identified.
template<class Type >
void processField (const word &fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvalue)
Process the turbulence field.
Protected Attributes
word name_
Name of this set of turbulenceFields object.
const objectRegistry & obr_
bool active_
on/off switch
wordHashSet fieldSet_
Fields to load.
Detailed Description
This function object stores turbulence fields on the mesh database for further manipulation.
Fields are stored as copies of the original, with the prefix "tubulenceModel:", e.g.
turbulenceModel:R
Example of function object specification:
turbulenceFields1
{
    type        turbulenceFields;
    functionObjectLibs ("libutilityFunctionObjects.so");
    ...
    fields
    (
        R
        devRhoReff
    );
}
Function object usage
Property Description Required Default value
type type name: processorField yes
fields fields to store (see below) yes
Where fields can include:
R : Stress tensor
devRhoReff :
mut : turbulence viscosity (compressible)
muEff : effective turbulence viscosity (compressible)
alphat : turbulence thermal diffusivity (compressible)
alphaEff : effective turbulence thermal diffusivity (compressible)
devReff :
nut : turbulence viscosity (incompressible)
nuEff : effective turbulence viscosity (incompressible)
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
turbulenceFields.H
turbulenceFields.C
Definition at line 156 of file turbulenceFields.H.
Member Enumeration Documentation
compressibleField
enum compressibleField
Enumerator
cfR
cfDevRhoReff
cfMut
cfMuEff
cfAlphat
cfAlphaEff
Definition at line 160 of file turbulenceFields.H.
incompressibleField
enum incompressibleField
Enumerator
ifR
ifDevReff
ifNut
ifNuEff
Definition at line 171 of file turbulenceFields.H.
Constructor & Destructor Documentation
turbulenceFields() [1/2]
turbulenceFields (const turbulenceFields &) protected
Disallow default bitwise copy construct.
Referenced by turbulenceFields::compressible().
turbulenceFields() [2/2]
turbulenceFields (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 91 of file turbulenceFields.C.
References Foam::endl(), and WarningIn.
~turbulenceFields()
~turbulenceFields () virtual
Destructor.
Definition at line 128 of file turbulenceFields.C.
Member Function Documentation
operator=()
void operator= (const turbulenceFields &) protected
Disallow default bitwise assignment.
compressible()
bool compressible () protected
Return true if compressible turbulence model is identified.
Definition at line 67 of file turbulenceFields.C.
References turbulenceFields::turbulenceFields(), and WarningIn.
processField()
void processField (const word & fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvalue) protected
Process the turbulence field.
Definition at line 32 of file turbulenceFieldsTemplates.C.
References Foam::endl(), fld(), Foam::nl, and WarningIn.
TypeName()
TypeName ("turbulenceFields")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the turbulenceFields object.
Definition at line 245 of file turbulenceFields.H.
References turbulenceFields::end(), turbulenceFields::execute(), turbulenceFields::name_, turbulenceFields::read(), turbulenceFields::timeSet(), and turbulenceFields::write().
read()
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 134 of file turbulenceFields.C.
References Foam::endl(), forAllConstIter(), Foam::Info, dictionary::lookup(), Foam::nl, and Foam::type().
Referenced by turbulenceFields::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 158 of file turbulenceFields.C.
References Foam::abort(), compressible, f(), Foam::FatalError, FatalErrorIn, and forAllConstIter().
Referenced by turbulenceFields::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 256 of file turbulenceFields.C.
Referenced by turbulenceFields::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 265 of file turbulenceFields.C.
Referenced by turbulenceFields::name().
write()
void write () virtual
Write.
Definition at line 271 of file turbulenceFields.C.
Referenced by turbulenceFields::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 266 of file turbulenceFields.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 270 of file turbulenceFields.H.
Member Data Documentation
compressibleFieldNames_
const NamedEnum< turbulenceFields::compressibleField, 6 > compressibleFieldNames_ static
Definition at line 169 of file turbulenceFields.H.
Referenced by NamedEnum< directionType, 3 >::names().
incompressibleFieldNames_
const NamedEnum< turbulenceFields::incompressibleField, 4 > incompressibleFieldNames_ static
Definition at line 178 of file turbulenceFields.H.
Referenced by NamedEnum< directionType, 3 >::names().
modelName
const word modelName = "turbulenceModel" static
Definition at line 180 of file turbulenceFields.H.
Referenced by NamedEnum< directionType, 3 >::names().
name_
word name_ protected
Name of this set of turbulenceFields object.
Definition at line 188 of file turbulenceFields.H.
Referenced by turbulenceFields::name().
obr_
const objectRegistry& obr_ protected
Definition at line 190 of file turbulenceFields.H.
active_
bool active_ protected
on/off switch
Definition at line 193 of file turbulenceFields.H.
fieldSet_
wordHashSet fieldSet_ protected
Fields to load.
Definition at line 196 of file turbulenceFields.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/turbulenceFields/turbulenceFields.H
src/postProcessing/functionObjects/utilities/turbulenceFields/turbulenceFields.C
src/postProcessing/functionObjects/utilities/turbulenceFields/turbulenceFieldsTemplates.C