OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
residuals Class Reference
Function objects » Utility function objects
This function object writes out the initial residual for specified fields.
Public Member Functions
TypeName ("residuals")
Runtime type information.
residuals (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~residuals ()
Destructor.
virtual const word & name () const
Return name of the set of field min/max.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
template<class Type >
void writeResidual (const word &fieldName)
Calculate the field min/max.
virtual void write ()
Write the residuals.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
residuals (const residuals &)
Disallow default bitwise copy construct.
void operator= (const residuals &)
Disallow default bitwise assignment.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of residuals.
const objectRegistry & obr_
bool active_
on/off switch
wordList fieldSet_
Fields to write residuals.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
This function object writes out the initial residual for specified fields.
Example of function object specification:
residuals
{
    type            residuals;
    outputControl   timeStep;
    outputInterval  1;
    fields
    (
        U
        p
    );
}
Output data is written to the dir postProcessing/residuals/<timeDir>/ For vector/tensor fields, e.g. U, where an equation is solved for each component, the largest residual of each component is written out.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
residuals.H
residuals.C
IOresiduals.H
Definition at line 88 of file residuals.H.
Constructor & Destructor Documentation
residuals() [1/2]
residuals (const residuals &) protected
Disallow default bitwise copy construct.
residuals() [2/2]
residuals (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 41 of file residuals.C.
References Foam::endl(), and WarningIn.
~residuals()
~residuals () virtual
Destructor.
Definition at line 77 of file residuals.C.
Member Function Documentation
operator=()
void operator= (const residuals &) protected
Disallow default bitwise assignment.
writeFileHeader()
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from functionObjectFile.
Definition at line 92 of file residuals.C.
References Foam::endl(), forAll, and UPstream::master().
TypeName()
TypeName ("residuals")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of field min/max.
Definition at line 147 of file residuals.H.
References residuals::end(), residuals::execute(), residuals::name_, residuals::read(), residuals::timeSet(), residuals::write(), and residuals::writeResidual().
read()
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 83 of file residuals.C.
References dictionary::lookup().
Referenced by residuals::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 109 of file residuals.C.
Referenced by residuals::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 115 of file residuals.C.
Referenced by residuals::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 121 of file residuals.C.
Referenced by residuals::name().
writeResidual()
void writeResidual (const word & fieldName)
Calculate the field min/max.
Definition at line 36 of file residualsTemplates.C.
References UList< T >::first(), dictionary::found(), dictionary::lookup(), and mesh.
Referenced by residuals::name().
write()
void write () virtual
Write the residuals.
Reimplemented from functionObjectFile.
Definition at line 127 of file residuals.C.
References Foam::endl(), forAll, UPstream::master(), and functionObjectFile::write().
Referenced by residuals::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 172 of file residuals.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 176 of file residuals.H.
Member Data Documentation
name_
word name_ protected
Name of this set of residuals.
Also used as the name of the output directory
Definition at line 98 of file residuals.H.
Referenced by residuals::name().
obr_
const objectRegistry& obr_ protected
Definition at line 100 of file residuals.H.
active_
bool active_ protected
on/off switch
Definition at line 103 of file residuals.H.
fieldSet_
wordList fieldSet_ protected
Fields to write residuals.
Definition at line 106 of file residuals.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/residuals/residuals.H
src/postProcessing/functionObjects/utilities/residuals/residuals.C
src/postProcessing/functionObjects/utilities/residuals/residualsTemplates.C