OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Q Class Reference
Function objects » Utility function objects
This function object calculates and outputs the second invariant of the velocity gradient tensor [1/s^2].
Public Member Functions
TypeName ("Q")
Runtime type information.
Q (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~Q ()
Destructor.
virtual const word & name () const
Return name of the set of Q.
virtual void read (const dictionary &)
Read the Q data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the Q and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object calculates and outputs the second invariant of the velocity gradient tensor [1/s^2].
Source files
Q.H
Q.C
IOQ.H
Definition at line 66 of file Q.H.
Constructor & Destructor Documentation
Q()
Q (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 42 of file Q.C.
References Foam::dimless, Foam::dimTime, Foam::endl(), mesh, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, Foam::sqr(), fvMesh::time(), Time::timeName(), Foam::type(), and WarningIn.
~Q()
~Q () virtual
Destructor.
Definition at line 101 of file Q.C.
Member Function Documentation
TypeName()
TypeName ("Q")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of Q.
Definition at line 118 of file Q.H.
References Q::end(), Q::execute(), Q::read(), Q::timeSet(), and Q::write().
read()
void read (const dictionary & dict) virtual
Read the Q data.
Definition at line 107 of file Q.C.
References dictionary::lookupOrDefault().
Referenced by Q::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 116 of file Q.C.
References Foam::fvc::grad(), objectRegistry::lookupObject(), mesh, Foam::sqr(), Foam::tr(), Foam::type(), and U.
Referenced by Q::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 138 of file Q.C.
Referenced by Q::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 147 of file Q.C.
Referenced by Q::name().
write()
void write () virtual
Calculate the Q and write.
Definition at line 153 of file Q.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by Q::name(), and molecule::writeFields().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 139 of file Q.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 143 of file Q.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/Q/Q.H
src/postProcessing/functionObjects/utilities/Q/Q.C