OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UOprocess Class Reference
Random UO process.
Public Member Functions
UOprocess (const Kmesh &kmesh, const scalar deltaT, const dictionary &)
Construct from wavenumber mesh and timestep.
const complexVectorField & newField ()
Detailed Description
Random UO process.
Source files
UOprocess.H
UOprocess.C
Definition at line 53 of file UOprocess.H.
Constructor & Destructor Documentation
UOprocess()
UOprocess (const Kmesh & kmesh, const scalar deltaT, const dictionary & UOdict)
Construct from wavenumber mesh and timestep.
Definition at line 54 of file UOprocess.C.
References forAll, Foam::magSqr(), and Foam::sqr().
Member Function Documentation
newField()
const complexVectorField & newField ()
Definition at line 99 of file UOprocess.C.
References forAll, Foam::Info, Foam::magSqr(), Foam::nl, and Foam::sqr().
The documentation for this class was generated from the following files:
src/randomProcesses/processes/UOprocess/UOprocess.H
src/randomProcesses/processes/UOprocess/UOprocess.C