OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
filmPyrolysisVelocityCoupledFvPatchVectorField Class Reference
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling. It provides a velocity boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
Public Member Functions
TypeName ("filmPyrolysisVelocityCoupled")
Runtime type information.
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling. It provides a velocity boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
if the patch is wet, the velocity is set using the film velocity
otherwise, it is set using pyrolysis out-gassing velocity
Example of the boundary condition specification:
    myPatch
    {
        type            filmPyrolysisVelocityCoupled;
        phi             phi;      // name of flux field (default = phi)
        rho             rho;      // name of density field (default = rho)
        deltaWet        1e-4;     // threshold height for 'wet' film
        value           uniform   (0 0 0); // initial velocity / [m/s]
    }
Source files
filmPyrolysisVelocityCoupledFvPatchVectorField.H
filmPyrolysisVelocityCoupledFvPatchVectorField.C
Definition at line 66 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
Constructor & Destructor Documentation
filmPyrolysisVelocityCoupledFvPatchVectorField() [1/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
Referenced by filmPyrolysisVelocityCoupledFvPatchVectorField::clone(), and filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField().
filmPyrolysisVelocityCoupledFvPatchVectorField() [2/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 68 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField(), fvPatch::size(), and vectorField().
filmPyrolysisVelocityCoupledFvPatchVectorField() [3/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
filmPyrolysisVelocityCoupledFvPatchVectorField onto a new patch
Definition at line 51 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField().
filmPyrolysisVelocityCoupledFvPatchVectorField() [4/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField & fpvpvf)
Construct as copy.
Definition at line 92 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField().
filmPyrolysisVelocityCoupledFvPatchVectorField() [5/5]
filmPyrolysisVelocityCoupledFvPatchVectorField (const filmPyrolysisVelocityCoupledFvPatchVectorField & fpvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 106 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("filmPyrolysisVelocityCoupled")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 125 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
References filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 142 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
References filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField().
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 158 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 164 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 170 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 176 of file filmPyrolysisVelocityCoupledFvPatchVectorField.H.
References filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), and filmPyrolysisVelocityCoupledFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 121 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, dimensionedInternalField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorIn, UPstream::msgType(), Foam::nl, phi, and filmPyrolysisVelocityCoupledFvPatchVectorField::write().
Referenced by filmPyrolysisVelocityCoupledFvPatchVectorField::rhoName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 214 of file filmPyrolysisVelocityCoupledFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by filmPyrolysisVelocityCoupledFvPatchVectorField::rhoName(), and filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.H
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.C