OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
yPlusRAS Class Reference
Function objects » Utility function objects
Evaluates and outputs turbulence y+ for RAS models. Values written to time directories as field 'yPlusRAS'.
Public Member Functions
TypeName ("yPlusRAS")
Runtime type information.
yPlusRAS (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~yPlusRAS ()
Destructor.
virtual const word & name () const
Return name of the set of yPlusRAS.
virtual void read (const dictionary &)
Read the yPlusRAS data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the yPlusRAS and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordHashSet & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Detailed Description
Evaluates and outputs turbulence y+ for RAS models. Values written to time directories as field 'yPlusRAS'.
Source files
yPlusRAS.H
yPlusRAS.C
IOyPlusRAS.H
Definition at line 63 of file yPlusRAS.H.
Constructor & Destructor Documentation
yPlusRAS()
yPlusRAS (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 175 of file yPlusRAS.C.
References Foam::dimless, Foam::endl(), mesh, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), Time::timeName(), Foam::type(), and WarningIn.
~yPlusRAS()
~yPlusRAS () virtual
Destructor.
Definition at line 234 of file yPlusRAS.C.
Member Function Documentation
TypeName()
TypeName ("yPlusRAS")
Runtime type information.
name()
virtual const word& name () const inline virtual
Return name of the set of yPlusRAS.
Definition at line 128 of file yPlusRAS.H.
References yPlusRAS::end(), yPlusRAS::execute(), yPlusRAS::read(), yPlusRAS::timeSet(), and yPlusRAS::write().
read()
void read (const dictionary & dict) virtual
Read the yPlusRAS data.
Definition at line 240 of file yPlusRAS.C.
References dictionary::lookupOrDefault().
Referenced by yPlusRAS::name().
execute()
void execute () virtual
Execute, currently does nothing.
Definition at line 250 of file yPlusRAS.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimMass, Foam::dimTime, Foam::Info, Foam::nl, phi, Foam::type(), and functionObjectFile::write().
Referenced by yPlusRAS::name().
end()
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 281 of file yPlusRAS.C.
Referenced by yPlusRAS::name().
timeSet()
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 290 of file yPlusRAS.C.
Referenced by yPlusRAS::name().
write()
void write () virtual
Calculate the yPlusRAS and write.
Reimplemented from functionObjectFile.
Definition at line 296 of file yPlusRAS.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::type(), functionObjectFile::write(), and regIOobject::write().
Referenced by yPlusRAS::name().
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 149 of file yPlusRAS.H.
movePoints()
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 153 of file yPlusRAS.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/yPlusRAS/yPlusRAS.H
src/postProcessing/functionObjects/utilities/yPlusRAS/yPlusRAS.C