OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbGen Class Reference
Generate a turbulent velocity field conforming to a given energy spectrum and being divergence free.
Public Member Functions
turbGen (const Kmesh &k, const scalar EA, const scalar K0)
Construct from components.
vectorField U ()
Generate and return a velocity field.
Detailed Description
Generate a turbulent velocity field conforming to a given energy spectrum and being divergence free.
Source files
turbGen.H
turbGen.C
turbGenIO.C
Definition at line 53 of file turbGen.H.
Constructor & Destructor Documentation
turbGen()
turbGen (const Kmesh & k, const scalar EA, const scalar K0)
Construct from components.
Definition at line 36 of file turbGen.C.
Member Function Documentation
U()
Foam::vectorField U ()
Generate and return a velocity field.
Definition at line 47 of file turbGen.C.
References Foam::ComplexField(), Foam::cos(), Foam::Ek(), forAll, Foam::mag(), Foam::ReImSum(), fft::reverseTransform(), s(), Random::scalar01(), Foam::sin(), Foam::constant::mathematical::twoPi(), and Random::vector01().
The documentation for this class was generated from the following files:
src/randomProcesses/turbulence/turbGen.H
src/randomProcesses/turbulence/turbGen.C