OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
filmPyrolysisTemperatureCoupledFvPatchScalarField Class Reference
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling. It provides a temperature boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
Public Member Functions
TypeName ("filmPyrolysisTemperatureCoupled")
Runtime type information.
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition is designed to be used in conjunction with surface film and pyrolysis modelling. It provides a temperature boundary condition for patches on the primary region based on whether the patch is seen to be 'wet', retrieved from the film alpha field.
if the patch is wet, the temperature is set using the film temperature
otherwise, it is set using pyrolysis temperature
Example of the boundary condition specification:
    myPatch
    {
        type            filmPyrolysisTemperatureCoupled;
        phi             phi;      // name of flux field (default = phi)
        rho             rho;      // name of density field (default = rho)
        deltaWet        1e-4;     // threshold height for 'wet' film
        value           uniform   300; // initial temperature / [K]
    }
Source files
filmPyrolysisTemperatureCoupledFvPatchScalarField.H
filmPyrolysisTemperatureCoupledFvPatchScalarField.C
Definition at line 66 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
Constructor & Destructor Documentation
filmPyrolysisTemperatureCoupledFvPatchScalarField() [1/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
Referenced by filmPyrolysisTemperatureCoupledFvPatchScalarField::clone(), and filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField().
filmPyrolysisTemperatureCoupledFvPatchScalarField() [2/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 68 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField(), scalarField(), and fvPatch::size().
filmPyrolysisTemperatureCoupledFvPatchScalarField() [3/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
filmPyrolysisTemperatureCoupledFvPatchScalarField onto a new patch
Definition at line 51 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField().
filmPyrolysisTemperatureCoupledFvPatchScalarField() [4/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField & fptpsf)
Construct as copy.
Definition at line 92 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField().
filmPyrolysisTemperatureCoupledFvPatchScalarField() [5/5]
filmPyrolysisTemperatureCoupledFvPatchScalarField (const filmPyrolysisTemperatureCoupledFvPatchScalarField & fptpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 106 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("filmPyrolysisTemperatureCoupled")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 125 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
References filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 142 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
References filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField().
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 158 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 164 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 170 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 176 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.H.
References filmPyrolysisTemperatureCoupledFvPatchScalarField::updateCoeffs(), and filmPyrolysisTemperatureCoupledFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 121 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References UPstream::msgType(), Field< Type >::T(), and filmPyrolysisTemperatureCoupledFvPatchScalarField::write().
Referenced by filmPyrolysisTemperatureCoupledFvPatchScalarField::rhoName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 184 of file filmPyrolysisTemperatureCoupledFvPatchScalarField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by filmPyrolysisTemperatureCoupledFvPatchScalarField::rhoName(), and filmPyrolysisTemperatureCoupledFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.H
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.C