OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
filmThermoModel Class Reference abstract
Public Member Functions
TypeName ("filmThermoModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmThermoModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
filmThermoModel (surfaceFilmModel &owner)
Construct null.
filmThermoModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~filmThermoModel ()
Destructor.
virtual const word & name () const =0
Return the specie name.
virtual scalar rho (const scalar p, const scalar T) const =0
Return density [kg/m3].
virtual scalar mu (const scalar p, const scalar T) const =0
Return dynamic viscosity [Pa.s].
virtual scalar sigma (const scalar p, const scalar T) const =0
Return surface tension [kg/s2].
virtual scalar Cp (const scalar p, const scalar T) const =0
Return specific heat capacity [J/kg/K].
virtual scalar kappa (const scalar p, const scalar T) const =0
Return thermal conductivity [W/m/K].
virtual scalar D (const scalar p, const scalar T) const =0
Return diffusivity [m2/s].
virtual scalar hl (const scalar p, const scalar T) const =0
Return latent heat [J/kg].
virtual scalar pv (const scalar p, const scalar T) const =0
Return vapour pressure [Pa].
virtual scalar W () const =0
Return molecular weight [kg/kmol].
virtual scalar Tb (const scalar p) const =0
Return boiling temperature [K].
virtual tmp< volScalarField > rho () const =0
Return density [kg/m3].
virtual tmp< volScalarField > mu () const =0
Return dynamic viscosity [Pa.s].
virtual tmp< volScalarField > sigma () const =0
Return surface tension [kg/s2].
virtual tmp< volScalarField > Cp () const =0
Return specific heat capacity [J/kg/K].
virtual tmp< volScalarField > kappa () const =0
Return thermal conductivity [W/m/K].
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool outputTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Static Public Member Functions
static autoPtr< filmThermoModel > New (surfaceFilmModel &owner, const dictionary &dict)
Return a reference to the selected phase change model.
Additional Inherited Members
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Definition at line 54 of file filmThermoModel.H.
Constructor & Destructor Documentation
filmThermoModel() [1/2]
filmThermoModel (surfaceFilmModel & owner)
Construct null.
Definition at line 45 of file filmThermoModel.C.
filmThermoModel() [2/2]
filmThermoModel (const word & modelType, surfaceFilmModel & owner, const dictionary & dict)
Construct from type name, dictionary and surface film model.
Definition at line 54 of file filmThermoModel.C.
~filmThermoModel()
~filmThermoModel () virtual
Destructor.
Definition at line 66 of file filmThermoModel.C.
Member Function Documentation
TypeName()
TypeName ("filmThermoModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , filmThermoModel , dictionary , (surfaceFilmModel &owner, const dictionary &dict) , (owner, dict))
New()
autoPtr< filmThermoModel > New (surfaceFilmModel & owner, const dictionary & dict) static
Return a reference to the selected phase change model.
Definition at line 40 of file filmThermoModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
name()
virtual const word& name () const pure virtual
Return the specie name.
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
rho() [1/2]
virtual scalar rho (const scalar p, const scalar T) const pure virtual
Return density [kg/m3].
Implemented in constantFilmThermo, and liquidFilmThermo.
mu() [1/2]
virtual scalar mu (const scalar p, const scalar T) const pure virtual
Return dynamic viscosity [Pa.s].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by liquidViscosity::correct().
sigma() [1/2]
virtual scalar sigma (const scalar p, const scalar T) const pure virtual
Return surface tension [kg/s2].
Implemented in constantFilmThermo, and liquidFilmThermo.
Cp() [1/2]
virtual scalar Cp (const scalar p, const scalar T) const pure virtual
Return specific heat capacity [J/kg/K].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
kappa() [1/2]
virtual scalar kappa (const scalar p, const scalar T) const pure virtual
Return thermal conductivity [W/m/K].
Implemented in constantFilmThermo, and liquidFilmThermo.
D()
virtual scalar D (const scalar p, const scalar T) const pure virtual
Return diffusivity [m2/s].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
hl()
virtual scalar hl (const scalar p, const scalar T) const pure virtual
Return latent heat [J/kg].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
pv()
virtual scalar pv (const scalar p, const scalar T) const pure virtual
Return vapour pressure [Pa].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
W()
virtual scalar W () const pure virtual
Return molecular weight [kg/kmol].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
Tb()
virtual scalar Tb (const scalar p) const pure virtual
Return boiling temperature [K].
Implemented in constantFilmThermo, and liquidFilmThermo.
Referenced by standardPhaseChange::correctModel().
rho() [2/2]
virtual tmp<volScalarField> rho () const pure virtual
Return density [kg/m3].
Implemented in constantFilmThermo, and liquidFilmThermo.
mu() [2/2]
virtual tmp<volScalarField> mu () const pure virtual
Return dynamic viscosity [Pa.s].
Implemented in constantFilmThermo, and liquidFilmThermo.
sigma() [2/2]
virtual tmp<volScalarField> sigma () const pure virtual
Return surface tension [kg/s2].
Implemented in constantFilmThermo, and liquidFilmThermo.
Cp() [2/2]
virtual tmp<volScalarField> Cp () const pure virtual
Return specific heat capacity [J/kg/K].
Implemented in constantFilmThermo, and liquidFilmThermo.
kappa() [2/2]
virtual tmp<volScalarField> kappa () const pure virtual
Return thermal conductivity [W/m/K].
Implemented in constantFilmThermo, and liquidFilmThermo.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/filmThermoModel/filmThermoModel.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/filmThermoModel/filmThermoModel.C
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/filmThermoModel/filmThermoModelNew.C