OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphatFilmWallFunctionFvPatchScalarField Class Reference
Region boundary conditions » Surface film boundary conditionsCompressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » | RAS compressible wall functions
This boundary condition provides a turbulent thermal diffusivity condition when using wall functions, for use with surface film models. This condition varies from the standard wall function by taking into account any mass released from the film model.
Public Member Functions
TypeName ("alphatFilmWallFunction")
Runtime type information.
alphatFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
scalar B_
B Coefficient (default = 5.5)
scalar yPlusCrit_
y+ value for laminar -> turbulent transition (default = 11.05)
scalar Cmu_
Turbulent Cmu coefficient (default = 0.09)
scalar kappa_
Von-Karman constant (default = 0.41)
scalar Prt_
Turbulent Prandtl number (default = 0.85)
Detailed Description
This boundary condition provides a turbulent thermal diffusivity condition when using wall functions, for use with surface film models. This condition varies from the standard wall function by taking into account any mass released from the film model.
Patch usage
Property Description Required Default value
B model coefficient no 5.5
yPlusCrit critical y+ for transition to turbulent flow no 11.05
Cmu model coefficient no 0.09
kappa Von-Karman constant no 0.41
Prt turbulent Prandtl number no 0.85
Example of the boundary condition specification:
    myPatch
    {
        type            alphatFilmWallFunction;
        B               5.5;
        yPlusCrit       11.05;
        Cmu             0.09;
        kappa           0.41;
        Prt             0.85;
        value           uniform 0;
    }
See also
Foam::fixedValueFvPatchField
Source files
alphatFilmWallFunctionFvPatchScalarField.H
alphatFilmWallFunctionFvPatchScalarField.C
Definition at line 116 of file alphatFilmWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatFilmWallFunctionFvPatchScalarField() [1/5]
alphatFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 48 of file alphatFilmWallFunctionFvPatchScalarField.C.
Referenced by alphatFilmWallFunctionFvPatchScalarField::alphatFilmWallFunctionFvPatchScalarField(), and alphatFilmWallFunctionFvPatchScalarField::clone().
alphatFilmWallFunctionFvPatchScalarField() [2/5]
alphatFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 82 of file alphatFilmWallFunctionFvPatchScalarField.C.
References alphatFilmWallFunctionFvPatchScalarField::alphatFilmWallFunctionFvPatchScalarField().
alphatFilmWallFunctionFvPatchScalarField() [3/5]
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
alphatFilmWallFunctionFvPatchScalarField onto a new patch
Definition at line 64 of file alphatFilmWallFunctionFvPatchScalarField.C.
References alphatFilmWallFunctionFvPatchScalarField::alphatFilmWallFunctionFvPatchScalarField().
alphatFilmWallFunctionFvPatchScalarField() [4/5]
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField & fwfpsf)
Construct as copy.
Definition at line 99 of file alphatFilmWallFunctionFvPatchScalarField.C.
References alphatFilmWallFunctionFvPatchScalarField::alphatFilmWallFunctionFvPatchScalarField().
alphatFilmWallFunctionFvPatchScalarField() [5/5]
alphatFilmWallFunctionFvPatchScalarField (const alphatFilmWallFunctionFvPatchScalarField & fwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 114 of file alphatFilmWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("alphatFilmWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 181 of file alphatFilmWallFunctionFvPatchScalarField.H.
References alphatFilmWallFunctionFvPatchScalarField::alphatFilmWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 198 of file alphatFilmWallFunctionFvPatchScalarField.H.
References alphatFilmWallFunctionFvPatchScalarField::alphatFilmWallFunctionFvPatchScalarField(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 130 of file alphatFilmWallFunctionFvPatchScalarField.C.
References turbulenceModel::alpha(), alphaEff, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), alphatFilmWallFunctionFvPatchScalarField::Cmu_, Foam::exp(), forAll, k, turbulenceModel::k(), alphatFilmWallFunctionFvPatchScalarField::kappa_, Foam::max(), Foam::min(), UPstream::msgType(), turbulenceModel::mu(), Foam::pow(), Pr(), alphatFilmWallFunctionFvPatchScalarField::Prt_, turbulenceModel::rho(), Foam::sqrt(), uTau, y, turbulenceModel::y(), yPlus, and alphatFilmWallFunctionFvPatchScalarField::yPlusCrit_.
Referenced by alphatFilmWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 221 of file alphatFilmWallFunctionFvPatchScalarField.C.
References alphatFilmWallFunctionFvPatchScalarField::B_, alphatFilmWallFunctionFvPatchScalarField::Cmu_, token::END_STATEMENT, alphatFilmWallFunctionFvPatchScalarField::kappa_, Foam::compressible::RASModels::makePatchTypeField(), Foam::nl, alphatFilmWallFunctionFvPatchScalarField::Prt_, fvPatchField< Type >::write(), Ostream::writeKeyword(), and alphatFilmWallFunctionFvPatchScalarField::yPlusCrit_.
Referenced by alphatFilmWallFunctionFvPatchScalarField::clone().
Member Data Documentation
B_
scalar B_ protected
B Coefficient (default = 5.5)
Definition at line 125 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::write().
yPlusCrit_
scalar yPlusCrit_ protected
y+ value for laminar -> turbulent transition (default = 11.05)
Definition at line 128 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
Cmu_
scalar Cmu_ protected
Turbulent Cmu coefficient (default = 0.09)
Definition at line 131 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
kappa_
scalar kappa_ protected
Von-Karman constant (default = 0.41)
Definition at line 134 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
Prt_
scalar Prt_ protected
Turbulent Prandtl number (default = 0.85)
Definition at line 137 of file alphatFilmWallFunctionFvPatchScalarField.H.
Referenced by alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatFilmWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/alphatFilmWallFunction/alphatFilmWallFunctionFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/alphatFilmWallFunction/alphatFilmWallFunctionFvPatchScalarField.C