OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutkFilmWallFunctionFvPatchScalarField Class Reference
Region boundary conditions » Surface film boundary conditionsCompressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » | RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
Public Member Functions
TypeName ("mutkFilmWallFunction")
Runtime type information.
mutkFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutkFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutkFilmWallFunctionFvPatchScalarField (const mutkFilmWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutkFilmWallFunctionFvPatchScalarField (const mutkFilmWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutkFilmWallFunctionFvPatchScalarField (const mutkFilmWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from mutkWallFunctionFvPatchScalarField
TypeName ("mutkWallFunction")
Runtime type information.
mutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &)
Construct as copy.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
virtual tmp< scalarField > calcUTau (const scalarField &magGradU) const
Calculate the friction velocity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalar B_
B Coefficient (default = 5.5)
scalar yPlusCrit_
y+ value for laminar -> turbulent transition (default = 11.05)
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            mutkFilmWallFunction;
    value           uniform 0;
}
See also
Foam::mutkWallFunctionFvPatchScalarField
Source files
mutkFilmWallFunctionFvPatchScalarField.H
mutkFilmWallFunctionFvPatchScalarField.C
Definition at line 71 of file mutkFilmWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutkFilmWallFunctionFvPatchScalarField() [1/5]
mutkFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 139 of file mutkFilmWallFunctionFvPatchScalarField.C.
Referenced by mutkFilmWallFunctionFvPatchScalarField::calcMut(), mutkFilmWallFunctionFvPatchScalarField::clone(), and mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField().
mutkFilmWallFunctionFvPatchScalarField() [2/5]
mutkFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 165 of file mutkFilmWallFunctionFvPatchScalarField.C.
References mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField().
mutkFilmWallFunctionFvPatchScalarField() [3/5]
mutkFilmWallFunctionFvPatchScalarField (const mutkFilmWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutkFilmWallFunctionFvPatchScalarField onto a new patch
Definition at line 151 of file mutkFilmWallFunctionFvPatchScalarField.C.
References mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField().
mutkFilmWallFunctionFvPatchScalarField() [4/5]
mutkFilmWallFunctionFvPatchScalarField (const mutkFilmWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 178 of file mutkFilmWallFunctionFvPatchScalarField.C.
References mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField().
mutkFilmWallFunctionFvPatchScalarField() [5/5]
mutkFilmWallFunctionFvPatchScalarField (const mutkFilmWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 189 of file mutkFilmWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 118 of file mutkFilmWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), Foam::mag(), Foam::max(), turbulenceModel::mu(), mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField(), turbulenceModel::rho(), Foam::sqr(), and turbulenceModel::U().
calcUTau()
tmp< scalarField > calcUTau (const scalarField & magGradU) const protected virtual
Calculate the friction velocity.
Definition at line 47 of file mutkFilmWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::exp(), forAll, objectRegistry::foundObject(), k, turbulenceModel::k(), Foam::max(), Foam::min(), turbulenceModel::mu(), Foam::pow(), turbulenceModel::rho(), Foam::sqrt(), regionModel::time(), uTau, y, turbulenceModel::y(), and yPlus.
Referenced by mutkFilmWallFunctionFvPatchScalarField::calcMut(), and mutkFilmWallFunctionFvPatchScalarField::yPlus().
TypeName()
TypeName ("mutkFilmWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 136 of file mutkFilmWallFunctionFvPatchScalarField.H.
References mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 153 of file mutkFilmWallFunctionFvPatchScalarField.H.
References mutkFilmWallFunctionFvPatchScalarField::mutkFilmWallFunctionFvPatchScalarField(), mutkFilmWallFunctionFvPatchScalarField::write(), and mutkFilmWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 202 of file mutkFilmWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), Foam::mag(), turbulenceModel::mu(), turbulenceModel::rho(), fvPatchField< Type >::snGrad(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by mutkFilmWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from mutWallFunctionFvPatchScalarField.
Definition at line 216 of file mutkFilmWallFunctionFvPatchScalarField.C.
References mutkFilmWallFunctionFvPatchScalarField::B_, token::END_STATEMENT, Foam::compressible::RASModels::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), Ostream::writeKeyword(), mutWallFunctionFvPatchScalarField::writeLocalEntries(), and mutkFilmWallFunctionFvPatchScalarField::yPlusCrit_.
Referenced by mutkFilmWallFunctionFvPatchScalarField::clone().
Member Data Documentation
B_
scalar B_ protected
B Coefficient (default = 5.5)
Definition at line 80 of file mutkFilmWallFunctionFvPatchScalarField.H.
Referenced by mutkFilmWallFunctionFvPatchScalarField::write().
yPlusCrit_
scalar yPlusCrit_ protected
y+ value for laminar -> turbulent transition (default = 11.05)
Definition at line 83 of file mutkFilmWallFunctionFvPatchScalarField.H.
Referenced by mutkFilmWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/mutkFilmWallFunction/mutkFilmWallFunctionFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/mutkFilmWallFunction/mutkFilmWallFunctionFvPatchScalarField.C