OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
inclinedFilmNusseltInletVelocityFvPatchVectorField Class Reference
Film velocity boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the velocity is calculated using the Nusselt solution.
Public Member Functions
TypeName ("inclinedFilmNusseltInletVelocity")
Runtime type information.
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Film velocity boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the velocity is calculated using the Nusselt solution.
Source files
inclinedFilmNusseltInletVelocityFvPatchVectorField.H
inclinedFilmNusseltInletVelocityFvPatchVectorField.C
Definition at line 52 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
inclinedFilmNusseltInletVelocityFvPatchVectorField() [1/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
Referenced by inclinedFilmNusseltInletVelocityFvPatchVectorField::clone(), and inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField().
inclinedFilmNusseltInletVelocityFvPatchVectorField() [2/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 65 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField(), fvPatch::size(), and vectorField().
inclinedFilmNusseltInletVelocityFvPatchVectorField() [3/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
inclinedFilmNusseltInletVelocityFvPatchVectorField onto a new patch
Definition at line 49 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField().
inclinedFilmNusseltInletVelocityFvPatchVectorField() [4/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField & fmfrpvf)
Construct as copy.
Definition at line 82 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField().
inclinedFilmNusseltInletVelocityFvPatchVectorField() [5/5]
inclinedFilmNusseltInletVelocityFvPatchVectorField (const inclinedFilmNusseltInletVelocityFvPatchVectorField & fmfrpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 95 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("inclinedFilmNusseltInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 108 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.H.
References inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 125 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.H.
References inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), and inclinedFilmNusseltInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 109 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), d(), Foam::endl(), Foam::constant::universal::G, objectRegistry::lookupObject(), Foam::mag(), Foam::max(), Foam::constant::physicoChemical::mu, n, Foam::operator==(), Foam::pow(), Foam::Re(), rho, Foam::sin(), regionModel::time(), Foam::constant::mathematical::twoPi(), WarningIn, and inclinedFilmNusseltInletVelocityFvPatchVectorField::write().
Referenced by inclinedFilmNusseltInletVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 189 of file inclinedFilmNusseltInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by inclinedFilmNusseltInletVelocityFvPatchVectorField::clone(), and inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltInletVelocity/inclinedFilmNusseltInletVelocityFvPatchVectorField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltInletVelocity/inclinedFilmNusseltInletVelocityFvPatchVectorField.C