OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
constantFilmThermo::thermoData Struct Reference
Public Member Functions
thermoData ()
thermoData (const word &n)
Public Attributes
word name_
scalar value_
bool set_
Detailed Description
Definition at line 59 of file constantFilmThermo.H.
Constructor & Destructor Documentation
thermoData() [1/2]
thermoData () inline
Definition at line 67 of file constantFilmThermo.H.
thermoData() [2/2]
thermoData (const word & n) inline
Definition at line 73 of file constantFilmThermo.H.
References constantFilmThermo::Cp(), constantFilmThermo::D(), subModelBase::dict(), constantFilmThermo::hl(), constantFilmThermo::kappa(), constantFilmThermo::mu(), constantFilmThermo::name(), constantFilmThermo::thermoData::name_, filmSubModelBase::owner(), p, constantFilmThermo::pv(), constantFilmThermo::rho(), constantFilmThermo::sigma(), Foam::T(), constantFilmThermo::Tb(), constantFilmThermo::TypeName(), constantFilmThermo::W(), and constantFilmThermo::~constantFilmThermo().
Member Data Documentation
name_
word name_
Definition at line 62 of file constantFilmThermo.H.
Referenced by constantFilmThermo::Cp(), constantFilmThermo::D(), constantFilmThermo::hl(), constantFilmThermo::kappa(), constantFilmThermo::mu(), constantFilmThermo::pv(), constantFilmThermo::rho(), constantFilmThermo::sigma(), constantFilmThermo::Tb(), constantFilmThermo::thermoData::thermoData(), and constantFilmThermo::W().
value_
scalar value_
Definition at line 63 of file constantFilmThermo.H.
Referenced by constantFilmThermo::Cp(), constantFilmThermo::D(), constantFilmThermo::hl(), constantFilmThermo::kappa(), constantFilmThermo::mu(), constantFilmThermo::pv(), constantFilmThermo::rho(), constantFilmThermo::sigma(), constantFilmThermo::Tb(), and constantFilmThermo::W().
set_
bool set_
Definition at line 64 of file constantFilmThermo.H.
Referenced by constantFilmThermo::Cp(), constantFilmThermo::D(), constantFilmThermo::hl(), constantFilmThermo::kappa(), constantFilmThermo::mu(), constantFilmThermo::pv(), constantFilmThermo::rho(), constantFilmThermo::sigma(), constantFilmThermo::Tb(), and constantFilmThermo::W().
The documentation for this struct was generated from the following file:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/constantFilmThermo/constantFilmThermo.H