OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
inclinedFilmNusseltHeightFvPatchScalarField Class Reference
Film height boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the height is calculated using the Nusselt solution.
Public Member Functions
TypeName ("inclinedFilmNusseltHeight")
Runtime type information.
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Film height boundary condition for inclined films that imposes a sinusoidal perturbation on top of a mean flow rate, where the height is calculated using the Nusselt solution.
Source files
inclinedFilmNusseltHeightFvPatchScalarField.H
inclinedFilmNusseltHeightFvPatchScalarField.C
Definition at line 52 of file inclinedFilmNusseltHeightFvPatchScalarField.H.
Constructor & Destructor Documentation
inclinedFilmNusseltHeightFvPatchScalarField() [1/5]
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
Referenced by inclinedFilmNusseltHeightFvPatchScalarField::clone(), and inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField().
inclinedFilmNusseltHeightFvPatchScalarField() [2/5]
inclinedFilmNusseltHeightFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 65 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField(), scalarField(), and fvPatch::size().
inclinedFilmNusseltHeightFvPatchScalarField() [3/5]
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
inclinedFilmNusseltHeightFvPatchScalarField onto a new patch
Definition at line 49 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField().
inclinedFilmNusseltHeightFvPatchScalarField() [4/5]
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField & wmfrhpsf)
Construct as copy.
Definition at line 82 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField().
inclinedFilmNusseltHeightFvPatchScalarField() [5/5]
inclinedFilmNusseltHeightFvPatchScalarField (const inclinedFilmNusseltHeightFvPatchScalarField & wmfrhpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 95 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("inclinedFilmNusseltHeight")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 108 of file inclinedFilmNusseltHeightFvPatchScalarField.H.
References inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 125 of file inclinedFilmNusseltHeightFvPatchScalarField.H.
References inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), and inclinedFilmNusseltHeightFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 109 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), d(), Foam::endl(), Foam::constant::universal::G, objectRegistry::lookupObject(), Foam::mag(), Foam::max(), Foam::constant::physicoChemical::mu, n, Foam::pow(), Foam::Re(), rho, Foam::sin(), Foam::sqr(), regionModel::time(), Foam::constant::mathematical::twoPi(), WarningIn, and inclinedFilmNusseltHeightFvPatchScalarField::write().
Referenced by inclinedFilmNusseltHeightFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 193 of file inclinedFilmNusseltHeightFvPatchScalarField.C.
References Foam::makePatchTypeField(), and write().
Referenced by inclinedFilmNusseltHeightFvPatchScalarField::clone(), and inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltHeight/inclinedFilmNusseltHeightFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/inclinedFilmNusseltHeight/inclinedFilmNusseltHeightFvPatchScalarField.C