OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionModelFunctionObject Class Reference
Public Member Functions
TypeName ("regionModelFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, regionModelFunctionObject, dictionary,(const dictionary &dict, regionModel &owner),(dict, owner))
Declare runtime constructor selection table.
regionModelFunctionObject (regionModel &owner)
Construct null from owner.
regionModelFunctionObject (const dictionary &dict, regionModel &owner, const word &modelType)
Construct from dictionary.
regionModelFunctionObject (const regionModelFunctionObject &ppm)
Construct copy.
virtual autoPtr< regionModelFunctionObject > clone () const
Construct and return a clone.
virtual ~regionModelFunctionObject ()
Destructor.
virtual void preEvolveRegion ()
Pre-evolve region hook.
virtual void postEvolveRegion ()
Post-evolve region hook.
virtual void write () const
write
Static Public Member Functions
static autoPtr< regionModelFunctionObject > New (const dictionary &dict, regionModel &owner, const word &modelType)
Selector.
Protected Attributes
dictionary dict_
Dictionary.
regionModel & owner_
Reference to the region model.
word modelType_
Model type name.
Detailed Description
Definition at line 56 of file regionModelFunctionObject.H.
Constructor & Destructor Documentation
regionModelFunctionObject() [1/3]
regionModelFunctionObject (regionModel & owner)
Construct null from owner.
Definition at line 43 of file regionModelFunctionObject.C.
Referenced by regionModelFunctionObject::clone(), and regionModelFunctionObject::regionModelFunctionObject().
regionModelFunctionObject() [2/3]
regionModelFunctionObject (const dictionary & dict, regionModel & owner, const word & modelType)
Construct from dictionary.
Definition at line 54 of file regionModelFunctionObject.C.
References regionModelFunctionObject::regionModelFunctionObject().
regionModelFunctionObject() [3/3]
regionModelFunctionObject (const regionModelFunctionObject & ppm)
Construct copy.
Definition at line 67 of file regionModelFunctionObject.C.
~regionModelFunctionObject()
~regionModelFunctionObject () virtual
Destructor.
Definition at line 79 of file regionModelFunctionObject.C.
Referenced by regionModelFunctionObject::clone().
Member Function Documentation
TypeName()
TypeName ("regionModelFunctionObject")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , regionModelFunctionObject , dictionary , (const dictionary &dict, regionModel &owner) , (dict, owner))
Declare runtime constructor selection table.
clone()
virtual autoPtr<regionModelFunctionObject> clone () const inline virtual
Construct and return a clone.
Definition at line 108 of file regionModelFunctionObject.H.
References regionModelFunctionObject::New(), regionModelFunctionObject::postEvolveRegion(), regionModelFunctionObject::preEvolveRegion(), regionModelFunctionObject::regionModelFunctionObject(), regionModelFunctionObject::write(), and regionModelFunctionObject::~regionModelFunctionObject().
New()
Foam::autoPtr< Foam::regionModels::regionModelFunctionObject > New (const dictionary & dict, regionModel & owner, const word & modelType) static
Selector.
Definition at line 32 of file regionModelFunctionObjectNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), Foam::nl, and dictionary::subDict().
Referenced by regionModelFunctionObject::clone().
preEvolveRegion()
void preEvolveRegion () virtual
Pre-evolve region hook.
Definition at line 85 of file regionModelFunctionObject.C.
Referenced by regionModelFunctionObject::clone().
postEvolveRegion()
void postEvolveRegion () virtual
Post-evolve region hook.
Definition at line 91 of file regionModelFunctionObject.C.
References write().
Referenced by regionModelFunctionObject::clone().
write()
void write () const virtual
write
Definition at line 100 of file regionModelFunctionObject.C.
Referenced by regionModelFunctionObject::clone().
Member Data Documentation
dict_
dictionary dict_ protected
Dictionary.
Definition at line 63 of file regionModelFunctionObject.H.
owner_
regionModel& owner_ protected
Reference to the region model.
Definition at line 66 of file regionModelFunctionObject.H.
modelType_
word modelType_ protected
Model type name.
Definition at line 69 of file regionModelFunctionObject.H.
The documentation for this class was generated from the following files:
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObject.H
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObject.C
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObjectNew.C