OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
kinematicSingleLayer Class Reference
Public Member Functions
TypeName ("kinematicSingleLayer")
Runtime type information.
kinematicSingleLayer (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType, const bool readFields=true)
Construct from components.
virtual ~kinematicSingleLayer ()
Destructor.
virtual scalar CourantNumber () const
Courant number evaluation.
const Switch & momentumPredictor () const
Return the momentum predictor.
label nOuterCorr () const
Return the number of outer correctors.
label nCorr () const
Return the number of PISO correctors.
label nNonOrthCorr () const
Return the number of non-orthogonal correctors.
const dimensionedScalar & deltaSmall () const
Return small delta.
const volScalarField & mu () const
Return const access to the dynamic viscosity / [Pa.s].
const volScalarField & sigma () const
Return const access to the surface tension / [m/s2].
const volScalarField & delta () const
Return const access to the film thickness / [m].
const volScalarField & alpha () const
Return the film coverage, 1 = covered, 0 = uncovered / [].
virtual const volVectorField & U () const
Return the film velocity [m/s].
virtual const volVectorField & Us () const
Return the film surface velocity [m/s].
virtual const volVectorField & Uw () const
Return the film wall velocity [m/s].
virtual const volScalarField & deltaRho () const
Return the film thickness*density (helper field) [kg/m3].
virtual const surfaceScalarField & phi () const
Return the film flux [kg.m/s].
virtual const volScalarField & rho () const
Return the film density [kg/m3].
virtual const volScalarField & T () const
Return the film mean temperature [K].
virtual const volScalarField & Ts () const
Return the film surface temperature [K].
virtual const volScalarField & Tw () const
Return the film wall temperature [K].
virtual const volScalarField & Cp () const
Return the film specific heat capacity [J/kg/K].
virtual const volScalarField & kappa () const
Return the film thermal conductivity [W/m/K].
virtual tmp< volScalarField > primaryMassTrans () const
Return mass transfer source - Eulerian phase only.
virtual const volScalarField & cloudMassTrans () const
Return the film mass available for transfer to cloud.
virtual const volScalarField & cloudDiameterTrans () const
Return the parcel diameters originating from film to cloud.
virtual void addSources (const label patchI, const label faceI, const scalar massSource, const vector &momentumSource, const scalar pressureSource, const scalar energySource=0)
External hook to add sources to the film.
volVectorField & USpPrimary ()
Momementum / [kg/m/s2].
volScalarField & pSpPrimary ()
Pressure / [Pa].
volScalarField & rhoSpPrimary ()
Mass / [kg/m2/s].
volVectorField & USp ()
Momentum / [kg/m/s2].
volScalarField & pSp ()
Pressure / [Pa].
volScalarField & rhoSp ()
Mass / [kg/m2/s].
const volVectorField & USp () const
Momentum / [kg/m/s2].
const volScalarField & pSp () const
Pressure / [Pa].
const volScalarField & rhoSp () const
Mass / [kg/m2/s].
const volVectorField & UPrimary () const
Velocity / [m/s].
const volScalarField & pPrimary () const
Pressure / [Pa].
const volScalarField & rhoPrimary () const
Density / [kg/m3].
const volScalarField & muPrimary () const
Viscosity / [Pa.s].
const filmThermoModel & filmThermo () const
Film thermo.
injectionModelList & injection ()
Injection.
const filmTurbulenceModel & turbulence () const
Turbulence.
tmp< volScalarField > mass () const
Return the current film mass.
tmp< volScalarField > netMass () const
Return the net film mass available over the next integration.
tmp< volScalarField > deltaMass () const
Return the change in film mass due to sources/sinks.
tmp< volScalarField > gNorm () const
Return the gravity normal-to-patch component contribution.
tmp< volScalarField > gNormClipped () const
Return the gravity normal-to-patch component contribution.
tmp< volVectorField > gTan () const
Return the gravity tangential component contributions.
virtual void preEvolveRegion ()
Pre-evolve film hook.
virtual void evolveRegion ()
Evolve the film equations.
virtual tmp< DimensionedField< scalar, volMesh > > Srho () const
Return total mass source - Eulerian phase only.
virtual tmp< DimensionedField< scalar, volMesh > > Srho (const label i) const
Return mass source for specie i - Eulerian phase only.
virtual tmp< DimensionedField< scalar, volMesh > > Sh () const
Return enthalpy source - Eulerian phase only.
virtual void info ()
Provide some feedback.
Public Member Functions inherited from surfaceFilmModel
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType)
Construct from type name, mesh and gravity vector.
virtual ~surfaceFilmModel ()
Destructor.
const dimensionedVector & g () const
Return the accleration due to gravity.
Public Member Functions inherited from singleLayerRegion
TypeName ("regionModel")
Runtime type information.
singleLayerRegion (const fvMesh &mesh, const word &regionType)
Construct null.
singleLayerRegion (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
virtual ~singleLayerRegion ()
Destructor.
virtual const volVectorField & nHat () const
Return the patch normal vectors.
virtual const volScalarField & magSf () const
Return the face area magnitudes / [m2].
virtual const labelList & passivePatchIDs () const
Return the list of patch IDs opposite to internally.
template<class Type >
wordList mappedFieldAndInternalPatchTypes () const
Return boundary types for mapped field patches.
template<class Type >
wordList mappedPushedFieldPatchTypes () const
Return boundary types for pushed mapped field patches.
template<class Type >
Foam::wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
Foam::wordList mappedPushedFieldPatchTypes () const
Public Member Functions inherited from regionModel
TypeName ("regionModel")
Runtime type information.
regionModel (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh and name and dict.
virtual ~regionModel ()
Destructor.
const fvMesh & primaryMesh () const
Return the reference to the primary mesh database.
const Time & time () const
Return the reference to the time database.
const Switch & active () const
Return the active flag.
const Switch & infoOutput () const
Return the information flag.
const word & modelName () const
Return the model name.
const fvMesh & regionMesh () const
Return the region mesh database.
fvMesh & regionMesh ()
Return the region mesh database for manipulation.
const dictionary & coeffs () const
Return the model coefficients dictionary.
const dictionary & solution () const
Return the solution dictionary.
const IOdictionary & outputProperties () const
Return const access to the output properties dictionary.
IOdictionary & outputProperties ()
Return output properties dictionary.
bool isCoupledPatch (const label regionPatchI) const
Return true if patchI on the local region is a coupled.
bool isRegionPatch (const label primaryPatchI) const
Return true if patchI on the primary region is a coupled.
const labelList & primaryPatchIDs () const
Return the list of patch IDs on the primary region coupled.
const labelList & intCoupledPatchIDs () const
Return the list of patch IDs internally coupled with the.
label regionPatchID (const label primaryPatchID) const
Return region ID corresponding to primaryPatchID.
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchI) const
Return the coupled patch ID paired with coupled patch.
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch internal field from another region model to local.
template<class Type >
void toPrimary (const label regionPatchI, List< Type > &regionField) const
Convert a local region field to the primary region.
template<class Type >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField) const
Convert a primary region field to the local region.
template<class Type , class CombineOp >
void toPrimary (const label regionPatchI, List< Type > &regionField, const CombineOp &cop) const
Convert a local region field to the primary region with op.
template<class Type , class CombineOp >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField, const CombineOp &cop) const
Convert a primary region field to the local region with op.
virtual void evolve ()
Main driver routing to evolve the region - calls other evolves.
virtual void postEvolveRegion ()
Post-evolve region.
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Protected Member Functions
virtual bool read ()
Read control parameters from dictionary.
virtual void correctThermoFields ()
Correct the thermo fields.
virtual void resetPrimaryRegionSourceTerms ()
Reset source term fields.
virtual void transferPrimaryRegionThermoFields ()
Transfer thermo fields from the primary region to the film region.
virtual void transferPrimaryRegionSourceFields ()
Transfer source fields from the primary region to the film region.
virtual tmp< volScalarField > pu ()
Explicit pressure source contribution.
virtual tmp< volScalarField > pp ()
Implicit pressure source coefficient.
virtual void correctAlpha ()
Correct film coverage field.
virtual void updateSubmodels ()
Update the film sub-models.
virtual void continuityCheck ()
Continuity check.
virtual void updateSurfaceVelocities ()
Update film surface velocities.
template<class Type >
void constrainFilmField (Type &field, const typename Type::cmptType &value)
Constrain a film region master/slave boundaries of a field to a.
virtual void solveContinuity ()
Solve continuity equation.
virtual tmp< fvVectorMatrix > solveMomentum (const volScalarField &pu, const volScalarField &pp)
Solve for film velocity.
virtual void solveThickness (const volScalarField &pu, const volScalarField &pp, const fvVectorMatrix &UEqn)
Solve coupled velocity-thickness equations.
Protected Member Functions inherited from regionModel
virtual bool read (const dictionary &dict)
Read control parameters from dictionary.
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const bool flip) const
Create or return a new inter-region AMI object.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
Switch momentumPredictor_
Momentum predictor.
label nOuterCorr_
Number of outer correctors.
label nCorr_
Number of PISO-like correctors.
label nNonOrthCorr_
Number of non-orthogonal correctors.
scalar cumulativeContErr_
Cumulative continuity error.
const dimensionedScalar deltaSmall_
Small delta.
scalar deltaCoLimit_
Film thickness above which Courant number calculation in valid.
volScalarField rho_
Density / [kg/m3].
volScalarField mu_
Dynamic viscosity / [Pa.s].
volScalarField sigma_
Surface tension / [m/s2].
volScalarField delta_
Film thickness / [m].
volScalarField alpha_
Film coverage indicator, 1 = covered, 0 = uncovered / [].
volVectorField U_
Velocity - mean / [m/s].
volVectorField Us_
Velocity - surface / [m/s].
volVectorField Uw_
Velocity - wall / [m/s].
volScalarField deltaRho_
Film thickness*density (helper field) / [kg/m2].
surfaceScalarField phi_
Mass flux (includes film thickness) / [kg.m/s].
volScalarField primaryMassTrans_
Film mass available for transfer to the primary region.
volScalarField cloudMassTrans_
Film mass available for transfer to cloud.
volScalarField cloudDiameterTrans_
Parcel diameters originating from film to cloud.
volVectorField USp_
Momementum / [kg/m/s2].
volScalarField pSp_
Pressure / [Pa].
volScalarField rhoSp_
Mass / [kg/m2/s].
volVectorField USpPrimary_
Momementum / [kg/m/s2].
volScalarField pSpPrimary_
Pressure / [Pa].
volScalarField rhoSpPrimary_
Mass / [kg/m2/s].
volVectorField UPrimary_
Velocity / [m/s].
volScalarField pPrimary_
Pressure / [Pa].
volScalarField rhoPrimary_
Density / [kg/m3].
volScalarField muPrimary_
Viscosity / [Pa.s].
autoPtr< filmThermoModel > filmThermo_
Film thermo model.
scalarField availableMass_
Available mass for transfer via sub-models.
injectionModelList injection_
Cloud injection.
autoPtr< filmTurbulenceModel > turbulence_
Turbulence model.
forceList forces_
List of film forces.
scalar addedMassTotal_
Cumulative mass added via sources [kg].
Protected Attributes inherited from surfaceFilmModel
const dimensionedVector & g_
Acceleration due to gravity [m/s2].
Protected Attributes inherited from singleLayerRegion
autoPtr< volVectorField > nHatPtr_
Patch normal vectors.
autoPtr< volScalarField > magSfPtr_
Face area magnitudes / [m2].
labelList passivePatchIDs_
List of patch IDs opposite to internally coupled patches.
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
Reference to the primary mesh database.
const Time & time_
Reference to the time database.
Switch active_
Active flag.
Switch infoOutput_
Active information output.
const word modelName_
Model name.
autoPtr< fvMesh > regionMeshPtr_
Pointer to the region mesh database.
dictionary coeffs_
Model coefficients dictionary.
autoPtr< IOdictionary > outputPropertiesPtr_
Dictionary of output properties.
labelList primaryPatchIDs_
List of patch IDs on the primary region coupled to this region.
labelList intCoupledPatchIDs_
List of patch IDs internally coupled with the primary region.
word regionName_
Region name.
regionModelFunctionObjectList functions_
Region model function objects.
wordList interRegionAMINames_
List of region names this region is coupled to.
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
List of AMI objects per coupled region.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase ::iterator LListBase_iterator
typedef DLListBase ::const_iterator LListBase_const_iterator
typedef DLListBase ::const_reverse_iterator LListBase_const_reverse_iterator
Static Public Member Functions inherited from surfaceFilmModel
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Return a reference to the selected surface film model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Definition at line 63 of file kinematicSingleLayer.H.
Constructor & Destructor Documentation
kinematicSingleLayer()
kinematicSingleLayer (const word & modelType, const fvMesh & mesh, const dimensionedVector & g, const word & regionType, const bool readFields = true)
Construct from components.
Definition at line 432 of file kinematicSingleLayer.C.
References IOobject::AUTO_WRITE, kinematicSingleLayer::correctAlpha(), kinematicSingleLayer::correctThermoFields(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::fvc::interpolate(), Foam::constant::electromagnetic::phi0, kinematicSingleLayer::phi_, IOobject::READ_IF_PRESENT, regionModel::regionMesh(), kinematicSingleLayer::rho_, regionModel::time(), timeName, kinematicSingleLayer::transferPrimaryRegionThermoFields(), and kinematicSingleLayer::U_.
~kinematicSingleLayer()
~kinematicSingleLayer () virtual
Destructor.
Definition at line 820 of file kinematicSingleLayer.C.
References kinematicSingleLayer::addSources().
Member Function Documentation
read()
bool read () protected virtual
Read control parameters from dictionary.
Reimplemented from surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 55 of file kinematicSingleLayer.C.
References dictionary::lookup(), kinematicSingleLayer::momentumPredictor_, kinematicSingleLayer::nCorr_, kinematicSingleLayer::nNonOrthCorr_, kinematicSingleLayer::nOuterCorr_, surfaceFilmModel::read(), dictionary::readIfPresent(), regionModel::solution(), and dictionary::subDict().
Referenced by thermoSingleLayer::read().
correctThermoFields()
void correctThermoFields () protected virtual
Correct the thermo fields.
Reimplemented in thermoSingleLayer.
Definition at line 74 of file kinematicSingleLayer.C.
References kinematicSingleLayer::filmThermo_, kinematicSingleLayer::mu_, kinematicSingleLayer::rho_, and kinematicSingleLayer::sigma_.
Referenced by kinematicSingleLayer::kinematicSingleLayer(), and kinematicSingleLayer::preEvolveRegion().
resetPrimaryRegionSourceTerms()
void resetPrimaryRegionSourceTerms () protected virtual
Reset source term fields.
Reimplemented in thermoSingleLayer.
Definition at line 82 of file kinematicSingleLayer.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::endl(), Foam::Info, kinematicSingleLayer::pSp_, kinematicSingleLayer::pSpPrimary_, kinematicSingleLayer::rhoSp_, kinematicSingleLayer::rhoSpPrimary_, kinematicSingleLayer::USp_, kinematicSingleLayer::USpPrimary_, and Vector< Cmpt >::zero.
Referenced by kinematicSingleLayer::evolveRegion(), and thermoSingleLayer::resetPrimaryRegionSourceTerms().
transferPrimaryRegionThermoFields()
void transferPrimaryRegionThermoFields () protected virtual
Transfer thermo fields from the primary region to the film region.
Reimplemented in thermoSingleLayer.
Definition at line 95 of file kinematicSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::Info, kinematicSingleLayer::muPrimary_, kinematicSingleLayer::pPrimary_, kinematicSingleLayer::rhoPrimary_, and kinematicSingleLayer::UPrimary_.
Referenced by kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::preEvolveRegion(), and thermoSingleLayer::transferPrimaryRegionThermoFields().
transferPrimaryRegionSourceFields()
void transferPrimaryRegionSourceFields () protected virtual
Transfer source fields from the primary region to the film region.
Reimplemented in thermoSingleLayer.
Definition at line 112 of file kinematicSingleLayer.C.
References dictionary::add(), kinematicSingleLayer::addedMassTotal_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), TimeState::deltaTValue(), Foam::endl(), forAll, Foam::Info, fvMesh::magSf(), regionModel::outputProperties(), regionModel::primaryMesh(), kinematicSingleLayer::pSp_, kinematicSingleLayer::pSpPrimary_, dictionary::readIfPresent(), Foam::returnReduce(), kinematicSingleLayer::rhoSp_, kinematicSingleLayer::rhoSpPrimary_, regionModel::time(), regionModel::time_, kinematicSingleLayer::USp_, and kinematicSingleLayer::USpPrimary_.
Referenced by kinematicSingleLayer::preEvolveRegion(), and thermoSingleLayer::transferPrimaryRegionSourceFields().
pu()
tmp< volScalarField > pu () protected virtual
Explicit pressure source contribution.
Definition at line 152 of file kinematicSingleLayer.C.
References kinematicSingleLayer::delta_, Foam::fvc::laplacian(), IOobject::NO_READ, IOobject::NO_WRITE, kinematicSingleLayer::pPrimary_, kinematicSingleLayer::pSp_, regionModel::regionMesh(), kinematicSingleLayer::sigma_, regionModel::time_, and Time::timeName().
Referenced by thermoSingleLayer::evolveRegion(), and kinematicSingleLayer::evolveRegion().
pp()
tmp< volScalarField > pp () protected virtual
Implicit pressure source coefficient.
Definition at line 174 of file kinematicSingleLayer.C.
References kinematicSingleLayer::gNormClipped(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::regionMesh(), kinematicSingleLayer::rho_, regionModel::time_, and Time::timeName().
Referenced by thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), thermoSingleLayer::updateSurfaceTemperatures(), and kinematicSingleLayer::updateSurfaceVelocities().
correctAlpha()
void correctAlpha () protected virtual
Correct film coverage field.
Reimplemented in thermoSingleLayer.
Definition at line 194 of file kinematicSingleLayer.C.
References kinematicSingleLayer::alpha_, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaSmall_, and Foam::pos().
Referenced by kinematicSingleLayer::evolveRegion(), and kinematicSingleLayer::kinematicSingleLayer().
updateSubmodels()
void updateSubmodels () protected virtual
Update the film sub-models.
Reimplemented in thermoSingleLayer.
Definition at line 200 of file kinematicSingleLayer.C.
References kinematicSingleLayer::availableMass_, kinematicSingleLayer::cloudDiameterTrans_, kinematicSingleLayer::cloudMassTrans_, injectionModelList::correct(), TimeState::deltaT(), Foam::endl(), Foam::Info, kinematicSingleLayer::injection_, singleLayerRegion::magSf(), kinematicSingleLayer::rhoSp_, regionModel::time(), and kinematicSingleLayer::turbulence_.
Referenced by kinematicSingleLayer::evolveRegion(), and thermoSingleLayer::updateSubmodels().
continuityCheck()
void continuityCheck () protected virtual
Continuity check.
Definition at line 218 of file kinematicSingleLayer.C.
References kinematicSingleLayer::cumulativeContErr_, kinematicSingleLayer::deltaRho_, Foam::dimMass, Foam::dimVolume, Foam::fvc::domainIntegrate(), Foam::endl(), globalContErr, Foam::Info, Foam::mag(), singleLayerRegion::magSf(), kinematicSingleLayer::mass(), Foam::nl, kinematicSingleLayer::solveContinuity(), sumLocalContErr, totalMass, and Foam::type().
Referenced by kinematicSingleLayer::solveThickness().
updateSurfaceVelocities()
void updateSurfaceVelocities () protected virtual
Update film surface velocities.
Definition at line 268 of file kinematicSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::faceCells(), regionModel::intCoupledPatchIDs_, singleLayerRegion::nHat(), kinematicSingleLayer::pp(), regionModel::regionMesh(), List< T >::size(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::turbulence_, kinematicSingleLayer::U_, kinematicSingleLayer::Us_, and kinematicSingleLayer::Uw_.
Referenced by thermoSingleLayer::evolveRegion(), and kinematicSingleLayer::evolveRegion().
constrainFilmField()
void constrainFilmField (Type & field, const typename Type::cmptType & value) protected
Constrain a film region master/slave boundaries of a field to a.
given value
Definition at line 41 of file kinematicSingleLayerTemplates.C.
References Foam::endl(), forAll, and Foam::Info.
Referenced by kinematicSingleLayer::solveThickness().
solveContinuity()
void solveContinuity () protected virtual
Solve continuity equation.
Definition at line 251 of file kinematicSingleLayer.C.
References Foam::fvm::ddt(), kinematicSingleLayer::deltaRho_, Foam::fvc::div(), Foam::endl(), Foam::Info, kinematicSingleLayer::phi_, kinematicSingleLayer::rhoSp_, and Foam::solve().
Referenced by kinematicSingleLayer::continuityCheck(), thermoSingleLayer::evolveRegion(), and kinematicSingleLayer::evolveRegion().
solveMomentum()
tmp< Foam::fvVectorMatrix > solveMomentum (const volScalarField & pu, const volScalarField & pp) protected virtual
Solve for film velocity.
Definition at line 286 of file kinematicSingleLayer.C.
References forceList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::fvm::div(), Foam::endl(), kinematicSingleLayer::forces_, kinematicSingleLayer::gTan(), Foam::Info, Foam::fvc::interpolate(), singleLayerRegion::magSf(), kinematicSingleLayer::momentumPredictor_, singleLayerRegion::nHat(), kinematicSingleLayer::phi_, Foam::fvc::reconstruct(), regionModel::regionMesh(), kinematicSingleLayer::rho_, kinematicSingleLayer::rhoSp_, Foam::fvc::snGrad(), Foam::solve(), kinematicSingleLayer::solveThickness(), kinematicSingleLayer::turbulence_, kinematicSingleLayer::U_, UEqn(), and kinematicSingleLayer::USp_.
Referenced by thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), and kinematicSingleLayer::updateSurfaceVelocities().
solveThickness()
void solveThickness (const volScalarField & pu, const volScalarField & pp, const fvVectorMatrix & UEqn) protected virtual
Solve coupled velocity-thickness equations.
Definition at line 344 of file kinematicSingleLayer.C.
References fvMatrix< Type >::A(), kinematicSingleLayer::constrainFilmField(), kinematicSingleLayer::continuityCheck(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), kinematicSingleLayer::delta_, Foam::fvm::div(), Foam::endl(), fvMatrix< Type >::flux(), kinematicSingleLayer::gTan(), fvMatrix< Type >::H(), Foam::Info, Foam::fvc::interpolate(), Foam::fvm::laplacian(), singleLayerRegion::magSf(), fvMesh::magSf(), GeometricField< Type, PatchField, GeoMesh >::max(), singleLayerRegion::nHat(), kinematicSingleLayer::nNonOrthCorr_, kinematicSingleLayer::phi_, phid(), Foam::fvc::reconstruct(), regionModel::regionMesh(), kinematicSingleLayer::rho_, rhof(), kinematicSingleLayer::rhoSp_, Foam::fvc::snGrad(), fvMatrix< Type >::solve(), and kinematicSingleLayer::U_.
Referenced by thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), and kinematicSingleLayer::solveMomentum().
TypeName()
TypeName ("kinematicSingleLayer")
Runtime type information.
CourantNumber()
scalar CourantNumber () const virtual
Courant number evaluation.
Reimplemented from surfaceFilmModel.
Definition at line 921 of file kinematicSingleLayer.C.
References CoNum, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaCoLimit_, kinematicSingleLayer::deltaRho_, TimeState::deltaTValue(), Foam::endl(), forAll, Foam::Info, internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::mag(), singleLayerRegion::magSf(), Foam::max(), kinematicSingleLayer::phi_, Foam::reduce(), regionModel::regionMesh(), Foam::fvc::surfaceSum(), and regionModel::time_.
momentumPredictor()
const Switch & momentumPredictor () const inline
Return the momentum predictor.
Definition at line 41 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::momentumPredictor_.
nOuterCorr()
label nOuterCorr () const inline
Return the number of outer correctors.
Definition at line 47 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::nOuterCorr_.
nCorr()
label nCorr () const inline
Return the number of PISO correctors.
Definition at line 53 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::nCorr_.
nNonOrthCorr()
label nNonOrthCorr () const inline
Return the number of non-orthogonal correctors.
Definition at line 59 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::nNonOrthCorr_.
deltaSmall()
const dimensionedScalar & deltaSmall () const inline
Return small delta.
Definition at line 65 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::deltaSmall_.
Referenced by thixotropicViscosity::correct(), laminar::Su(), and thixotropicViscosity::updateMu().
mu()
const volScalarField & mu () const inline
Return const access to the dynamic viscosity / [Pa.s].
Definition at line 71 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::mu_.
Referenced by laminar::Su().
sigma()
const volScalarField & sigma () const inline virtual
Return const access to the surface tension / [m/s2].
Implements surfaceFilmModel.
Definition at line 77 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::sigma_.
Referenced by curvatureSeparation::correct().
delta()
const volScalarField & delta () const inline virtual
Return const access to the film thickness / [m].
Implements surfaceFilmModel.
Definition at line 83 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::delta_.
Referenced by drippingInjection::correct(), curvatureSeparation::correct(), thixotropicViscosity::correct(), standardPhaseChange::correctModel(), laminar::Su(), and thixotropicViscosity::updateMu().
alpha()
const volScalarField & alpha () const inline virtual
Return the film coverage, 1 = covered, 0 = uncovered / [].
Implements surfaceFilmModel.
Definition at line 89 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::alpha_.
Referenced by thixotropicViscosity::correct(), and solidification::correctModel().
U()
const volVectorField & U () const virtual
Return the film velocity [m/s].
Implements surfaceFilmModel.
Definition at line 952 of file kinematicSingleLayer.C.
References kinematicSingleLayer::U_.
Referenced by curvatureSeparation::correct(), and thixotropicViscosity::correct().
Us()
const volVectorField & Us () const virtual
Return the film surface velocity [m/s].
Implements surfaceFilmModel.
Definition at line 958 of file kinematicSingleLayer.C.
References kinematicSingleLayer::Us_.
Referenced by standardPhaseChange::correctModel().
Uw()
const volVectorField & Uw () const virtual
Return the film wall velocity [m/s].
Implements surfaceFilmModel.
Definition at line 964 of file kinematicSingleLayer.C.
References kinematicSingleLayer::Uw_.
Referenced by thixotropicViscosity::correct(), and laminar::Su().
deltaRho()
const volScalarField & deltaRho () const virtual
Return the film thickness*density (helper field) [kg/m3].
Definition at line 970 of file kinematicSingleLayer.C.
References kinematicSingleLayer::deltaRho_.
Referenced by thixotropicViscosity::correct().
phi()
const surfaceScalarField & phi () const virtual
Return the film flux [kg.m/s].
Definition at line 976 of file kinematicSingleLayer.C.
References kinematicSingleLayer::phi_.
Referenced by curvatureSeparation::correct(), and thixotropicViscosity::correct().
rho()
const volScalarField & rho () const virtual
Return the film density [kg/m3].
Implements surfaceFilmModel.
Definition at line 982 of file kinematicSingleLayer.C.
References kinematicSingleLayer::rho_.
Referenced by drippingInjection::correct(), curvatureSeparation::correct(), solidification::correctModel(), and standardPhaseChange::correctModel().
T()
const volScalarField & T () const virtual
Return the film mean temperature [K].
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 988 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
Ts()
const volScalarField & Ts () const virtual
Return the film surface temperature [K].
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 999 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
Tw()
const volScalarField & Tw () const virtual
Return the film wall temperature [K].
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1010 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
Cp()
const volScalarField & Cp () const virtual
Return the film specific heat capacity [J/kg/K].
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1021 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
kappa()
const volScalarField & kappa () const virtual
Return the film thermal conductivity [W/m/K].
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1032 of file kinematicSingleLayer.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, GeometricField< scalar, fvPatchField, volMesh >::null(), and Foam::type().
primaryMassTrans()
tmp< volScalarField > primaryMassTrans () const virtual
Return mass transfer source - Eulerian phase only.
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1043 of file kinematicSingleLayer.C.
References Foam::dimMass, Foam::dimVolume, IOobject::NO_READ, IOobject::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), and timeName.
cloudMassTrans()
const volScalarField & cloudMassTrans () const virtual
Return the film mass available for transfer to cloud.
Implements surfaceFilmModel.
Definition at line 1065 of file kinematicSingleLayer.C.
References kinematicSingleLayer::cloudMassTrans_.
cloudDiameterTrans()
const volScalarField & cloudDiameterTrans () const virtual
Return the parcel diameters originating from film to cloud.
Implements surfaceFilmModel.
Definition at line 1071 of file kinematicSingleLayer.C.
References kinematicSingleLayer::cloudDiameterTrans_.
addSources()
void addSources (const label patchI, const label faceI, const scalar massSource, const vector & momentumSource, const scalar pressureSource, const scalar energySource = 0) virtual
External hook to add sources to the film.
Implements surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 827 of file kinematicSingleLayer.C.
References kinematicSingleLayer::addedMassTotal_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), Foam::Info, Foam::nl, kinematicSingleLayer::pSpPrimary_, kinematicSingleLayer::rhoSpPrimary_, Foam::type(), and kinematicSingleLayer::USpPrimary_.
Referenced by thermoSingleLayer::addSources(), and kinematicSingleLayer::~kinematicSingleLayer().
USpPrimary()
volVectorField & USpPrimary () inline
Momementum / [kg/m/s2].
Definition at line 95 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::USpPrimary_.
pSpPrimary()
volScalarField & pSpPrimary () inline
Pressure / [Pa].
Definition at line 101 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pSpPrimary_.
rhoSpPrimary()
volScalarField & rhoSpPrimary () inline
Mass / [kg/m2/s].
Definition at line 107 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoSpPrimary_.
USp() [1/2]
volVectorField & USp () inline
Momentum / [kg/m/s2].
Definition at line 113 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::USp_.
pSp() [1/2]
volScalarField & pSp () inline
Pressure / [Pa].
Definition at line 119 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pSp_.
rhoSp() [1/2]
volScalarField & rhoSp () inline
Mass / [kg/m2/s].
Definition at line 125 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoSp_.
USp() [2/2]
const volVectorField & USp () const inline
Momentum / [kg/m/s2].
Definition at line 131 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::USp_.
pSp() [2/2]
const volScalarField & pSp () const inline
Pressure / [Pa].
Definition at line 137 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pSp_.
rhoSp() [2/2]
const volScalarField & rhoSp () const inline
Mass / [kg/m2/s].
Definition at line 143 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoSp_.
UPrimary()
const volVectorField & UPrimary () const inline
Velocity / [m/s].
Definition at line 149 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::UPrimary_.
Referenced by standardPhaseChange::correctModel(), and laminar::Su().
pPrimary()
const volScalarField & pPrimary () const inline
Pressure / [Pa].
Definition at line 155 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::pPrimary_.
Referenced by standardPhaseChange::correctModel(), liquidFilmThermo::Cp(), liquidFilmThermo::kappa(), liquidFilmThermo::mu(), liquidFilmThermo::rho(), and liquidFilmThermo::sigma().
rhoPrimary()
const volScalarField & rhoPrimary () const inline
Density / [kg/m3].
Definition at line 161 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::rhoPrimary_.
Referenced by standardPhaseChange::correctModel(), and laminar::Su().
muPrimary()
const volScalarField & muPrimary () const inline
Viscosity / [Pa.s].
Definition at line 167 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::muPrimary_.
Referenced by standardPhaseChange::correctModel().
filmThermo()
const filmThermoModel & filmThermo () const inline
Film thermo.
Definition at line 173 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::filmThermo_.
Referenced by liquidViscosity::correct(), and standardPhaseChange::correctModel().
injection()
injectionModelList & injection () inline
Injection.
Definition at line 179 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::injection_.
turbulence()
const filmTurbulenceModel & turbulence () const inline
Turbulence.
Definition at line 185 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::turbulence_.
mass()
tmp< volScalarField > mass () const inline
Return the current film mass.
Definition at line 191 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::delta_, singleLayerRegion::magSf(), and kinematicSingleLayer::rho_.
Referenced by kinematicSingleLayer::continuityCheck().
netMass()
tmp< volScalarField > netMass () const inline
Return the net film mass available over the next integration.
Definition at line 197 of file kinematicSingleLayerI.H.
References kinematicSingleLayer::delta_, kinematicSingleLayer::deltaSmall_, TimeState::deltaT(), Foam::fvc::interpolate(), singleLayerRegion::magSf(), kinematicSingleLayer::phi_, Foam::pos(), kinematicSingleLayer::rho_, Foam::fvc::surfaceSum(), and regionModel::time().
Referenced by kinematicSingleLayer::preEvolveRegion(), and thixotropicViscosity::updateMu().
deltaMass()
tmp< volScalarField > deltaMass () const inline
Return the change in film mass due to sources/sinks.
Definition at line 206 of file kinematicSingleLayerI.H.
References TimeState::deltaT(), singleLayerRegion::magSf(), kinematicSingleLayer::rhoSp_, and regionModel::time().
Referenced by thixotropicViscosity::updateMu().
gNorm()
tmp< volScalarField > gNorm () const inline
Return the gravity normal-to-patch component contribution.
Definition at line 212 of file kinematicSingleLayerI.H.
References surfaceFilmModel::g_, singleLayerRegion::nHat(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::regionMesh(), regionModel::time(), and timeName.
Referenced by drippingInjection::correct(), and kinematicSingleLayer::gTan().
gNormClipped()
tmp< volScalarField > gNormClipped () const inline
Return the gravity normal-to-patch component contribution.
Clipped so that only non-zero if g & nHat_ < 0
Definition at line 235 of file kinematicSingleLayerI.H.
References surfaceFilmModel::g_, GeometricField< Type, PatchField, GeoMesh >::min(), singleLayerRegion::nHat(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::regionMesh(), regionModel::time(), and timeName.
Referenced by kinematicSingleLayer::pp().
gTan()
tmp< volVectorField > gTan () const inline
Return the gravity tangential component contributions.
Definition at line 261 of file kinematicSingleLayerI.H.
References surfaceFilmModel::g_, kinematicSingleLayer::gNorm(), singleLayerRegion::nHat(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::regionMesh(), regionModel::time(), and timeName.
Referenced by kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().
preEvolveRegion()
void preEvolveRegion () virtual
Pre-evolve film hook.
Reimplemented from regionModel.
Reimplemented in thermoSingleLayer.
Definition at line 852 of file kinematicSingleLayer.C.
References kinematicSingleLayer::availableMass_, kinematicSingleLayer::cloudDiameterTrans_, kinematicSingleLayer::cloudMassTrans_, kinematicSingleLayer::correctThermoFields(), Foam::dimLength, Foam::dimMass, Foam::endl(), Foam::Info, kinematicSingleLayer::netMass(), regionModel::preEvolveRegion(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and kinematicSingleLayer::transferPrimaryRegionThermoFields().
Referenced by thermoSingleLayer::preEvolveRegion().
evolveRegion()
void evolveRegion () virtual
Evolve the film equations.
Reimplemented from regionModel.
Reimplemented in thermoSingleLayer.
Definition at line 875 of file kinematicSingleLayer.C.
References kinematicSingleLayer::correctAlpha(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::endl(), Foam::Info, kinematicSingleLayer::nCorr_, kinematicSingleLayer::nOuterCorr_, kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::rho_, kinematicSingleLayer::solveContinuity(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), UEqn(), kinematicSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSurfaceVelocities().
Srho() [1/2]
tmp< DimensionedField< scalar, volMesh > > Srho () const virtual
Return total mass source - Eulerian phase only.
Reimplemented from surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1101 of file kinematicSingleLayer.C.
References Foam::dimMass, Foam::dimVolume, IOobject::IOobject(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), and timeName.
Srho() [2/2]
tmp< DimensionedField< scalar, volMesh > > Srho (const label i) const virtual
Return mass source for specie i - Eulerian phase only.
Reimplemented from surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1124 of file kinematicSingleLayer.C.
References Foam::dimMass, Foam::dimVolume, IOobject::IOobject(), Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), and timeName.
Sh()
tmp< DimensionedField< scalar, volMesh > > Sh () const virtual
Return enthalpy source - Eulerian phase only.
Reimplemented from surfaceFilmModel.
Reimplemented in thermoSingleLayer.
Definition at line 1148 of file kinematicSingleLayer.C.
References Foam::dimEnergy, Foam::dimVolume, IOobject::IOobject(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), and timeName.
info()
void info () virtual
Provide some feedback.
Reimplemented from regionModel.
Reimplemented in thermoSingleLayer.
Definition at line 1077 of file kinematicSingleLayer.C.
References kinematicSingleLayer::addedMassTotal_, kinematicSingleLayer::alpha_, kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::endl(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::indent(), injectionModelList::info(), Foam::Info, kinematicSingleLayer::injection_, GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::mag(), singleLayerRegion::magSf(), Foam::nl, regionModel::outputProperties(), dictionary::readIfPresent(), Foam::returnReduce(), Foam::type(), and kinematicSingleLayer::U_.
Referenced by thermoSingleLayer::info().
Member Data Documentation
momentumPredictor_
Switch momentumPredictor_ protected
Momentum predictor.
Definition at line 85 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::momentumPredictor(), kinematicSingleLayer::read(), and kinematicSingleLayer::solveMomentum().
nOuterCorr_
label nOuterCorr_ protected
Number of outer correctors.
Definition at line 88 of file kinematicSingleLayer.H.
Referenced by thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), kinematicSingleLayer::nOuterCorr(), and kinematicSingleLayer::read().
nCorr_
label nCorr_ protected
Number of PISO-like correctors.
Definition at line 91 of file kinematicSingleLayer.H.
Referenced by thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), kinematicSingleLayer::nCorr(), and kinematicSingleLayer::read().
nNonOrthCorr_
label nNonOrthCorr_ protected
Number of non-orthogonal correctors.
Definition at line 94 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::nNonOrthCorr(), kinematicSingleLayer::read(), and kinematicSingleLayer::solveThickness().
cumulativeContErr_
scalar cumulativeContErr_ protected
Cumulative continuity error.
Definition at line 97 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::continuityCheck().
deltaSmall_
const dimensionedScalar deltaSmall_ protected
Small delta.
Definition at line 100 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctAlpha(), kinematicSingleLayer::deltaSmall(), and kinematicSingleLayer::netMass().
deltaCoLimit_
scalar deltaCoLimit_ protected
Film thickness above which Courant number calculation in valid.
Definition at line 103 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::CourantNumber().
rho_
volScalarField rho_ protected
Density / [kg/m3].
Definition at line 111 of file kinematicSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::correctThermoFields(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::mass(), kinematicSingleLayer::netMass(), kinematicSingleLayer::pp(), kinematicSingleLayer::rho(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::thermoSingleLayer().
mu_
volScalarField mu_ protected
Dynamic viscosity / [Pa.s].
Definition at line 114 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::correctThermoFields(), and kinematicSingleLayer::mu().
sigma_
volScalarField sigma_ protected
Surface tension / [m/s2].
Definition at line 117 of file kinematicSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::correctThermoFields(), kinematicSingleLayer::pu(), and kinematicSingleLayer::sigma().
delta_
volScalarField delta_ protected
Film thickness / [m].
Definition at line 123 of file kinematicSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), kinematicSingleLayer::correctAlpha(), kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::delta(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), kinematicSingleLayer::info(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::mass(), kinematicSingleLayer::netMass(), kinematicSingleLayer::pu(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::thermoSingleLayer().
alpha_
volScalarField alpha_ protected
Film coverage indicator, 1 = covered, 0 = uncovered / [].
Definition at line 126 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::alpha(), thermoSingleLayer::correctAlpha(), kinematicSingleLayer::correctAlpha(), and kinematicSingleLayer::info().
U_
volVectorField U_ protected
Velocity - mean / [m/s].
Definition at line 129 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::info(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::thermoSingleLayer(), kinematicSingleLayer::U(), and kinematicSingleLayer::updateSurfaceVelocities().
Us_
volVectorField Us_ protected
Velocity - surface / [m/s].
Definition at line 132 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::updateSurfaceVelocities(), and kinematicSingleLayer::Us().
Uw_
volVectorField Uw_ protected
Velocity - wall / [m/s].
Definition at line 135 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::updateSurfaceVelocities(), and kinematicSingleLayer::Uw().
deltaRho_
volScalarField deltaRho_ protected
Film thickness*density (helper field) / [kg/m2].
Definition at line 138 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::continuityCheck(), kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::deltaRho(), thermoSingleLayer::evolveRegion(), kinematicSingleLayer::evolveRegion(), kinematicSingleLayer::info(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), and thermoSingleLayer::thermoSingleLayer().
phi_
surfaceScalarField phi_ protected
Mass flux (includes film thickness) / [kg.m/s].
Definition at line 141 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::netMass(), kinematicSingleLayer::phi(), kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::thermoSingleLayer().
primaryMassTrans_
volScalarField primaryMassTrans_ protected
Film mass available for transfer to the primary region.
Definition at line 147 of file kinematicSingleLayer.H.
cloudMassTrans_
volScalarField cloudMassTrans_ protected
Film mass available for transfer to cloud.
Definition at line 150 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::cloudMassTrans(), kinematicSingleLayer::preEvolveRegion(), and kinematicSingleLayer::updateSubmodels().
cloudDiameterTrans_
volScalarField cloudDiameterTrans_ protected
Parcel diameters originating from film to cloud.
Definition at line 153 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::cloudDiameterTrans(), kinematicSingleLayer::preEvolveRegion(), and kinematicSingleLayer::updateSubmodels().
USp_
volVectorField USp_ protected
Momementum / [kg/m/s2].
Definition at line 163 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and kinematicSingleLayer::USp().
pSp_
volScalarField pSp_ protected
Pressure / [Pa].
Definition at line 166 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::pSp(), kinematicSingleLayer::pu(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), thermoSingleLayer::thermoSingleLayer(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and thermoSingleLayer::updateSubmodels().
rhoSp_
volScalarField rhoSp_ protected
Mass / [kg/m2/s].
Definition at line 169 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::deltaMass(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::rhoSp(), kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), thermoSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSubmodels().
USpPrimary_
volVectorField USpPrimary_ protected
Momementum / [kg/m/s2].
Definition at line 176 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and kinematicSingleLayer::USpPrimary().
pSpPrimary_
volScalarField pSpPrimary_ protected
Pressure / [Pa].
Definition at line 179 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::pSpPrimary(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
rhoSpPrimary_
volScalarField rhoSpPrimary_ protected
Mass / [kg/m2/s].
Definition at line 182 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::rhoSpPrimary(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
UPrimary_
volVectorField UPrimary_ protected
Velocity / [m/s].
Definition at line 189 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::transferPrimaryRegionThermoFields(), and kinematicSingleLayer::UPrimary().
pPrimary_
volScalarField pPrimary_ protected
Pressure / [Pa].
Definition at line 192 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::pPrimary(), kinematicSingleLayer::pu(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::thermoSingleLayer(), and kinematicSingleLayer::transferPrimaryRegionThermoFields().
rhoPrimary_
volScalarField rhoPrimary_ protected
Density / [kg/m3].
Definition at line 195 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::rhoPrimary(), kinematicSingleLayer::transferPrimaryRegionThermoFields(), and thermoSingleLayer::updateSubmodels().
muPrimary_
volScalarField muPrimary_ protected
Viscosity / [Pa.s].
Definition at line 198 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::muPrimary(), and kinematicSingleLayer::transferPrimaryRegionThermoFields().
filmThermo_
autoPtr<filmThermoModel> filmThermo_ protected
Film thermo model.
Definition at line 204 of file kinematicSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::correctThermoFields(), kinematicSingleLayer::filmThermo(), and thermoSingleLayer::Srho().
availableMass_
scalarField availableMass_ protected
Available mass for transfer via sub-models.
Definition at line 207 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::preEvolveRegion(), thermoSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSubmodels().
injection_
injectionModelList injection_ protected
Cloud injection.
Definition at line 210 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::info(), kinematicSingleLayer::injection(), and kinematicSingleLayer::updateSubmodels().
turbulence_
autoPtr<filmTurbulenceModel> turbulence_ protected
Turbulence model.
Definition at line 213 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::turbulence(), kinematicSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSurfaceVelocities().
forces_
forceList forces_ protected
List of film forces.
Definition at line 216 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::solveMomentum().
addedMassTotal_
scalar addedMassTotal_ protected
Cumulative mass added via sources [kg].
Definition at line 222 of file kinematicSingleLayer.H.
Referenced by kinematicSingleLayer::addSources(), kinematicSingleLayer::info(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayer.H
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayer.C
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayerI.H
src/regionModels/surfaceFilmModels/kinematicSingleLayer/kinematicSingleLayerTemplates.C