OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
contactAngleForce Class Reference
Public Member Functions
TypeName ("contactAngle")
Runtime type information.
contactAngleForce (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model.
virtual ~contactAngleForce ()
Destructor.
virtual tmp< fvVectorMatrix > correct (volVectorField &U)
Correct.
Public Member Functions inherited from force
TypeName ("force")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, force, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
force (surfaceFilmModel &owner)
Construct null.
force (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~force ()
Destructor.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool outputTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Additional Inherited Members
Static Public Member Functions inherited from force
static autoPtr< force > New (surfaceFilmModel &owner, const dictionary &dict, const word &modelType)
Return a reference to the selected force model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Definition at line 57 of file contactAngleForce.H.
Constructor & Destructor Documentation
contactAngleForce()
contactAngleForce (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model.
Definition at line 79 of file contactAngleForce.C.
~contactAngleForce()
~contactAngleForce () virtual
Destructor.
Definition at line 115 of file contactAngleForce.C.
Member Function Documentation
TypeName()
TypeName ("contactAngle")
Runtime type information.
correct()
tmp< fvVectorMatrix > correct (volVectorField & U) virtual
Correct.
Implements force.
Definition at line 121 of file contactAngleForce.C.
References Foam::constant::atomic::alpha, surfaceFilmModel::alpha(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cos(), Foam::degToRad(), surfaceInterpolation::deltaCoeffs(), Foam::dimArea, Foam::dimForce, Foam::dimVolume, forAll, Foam::fvc::grad(), regionModel::isCoupledPatch(), Foam::mag(), singleLayerRegion::magSf(), n, fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, TimeState::outputTime(), filmSubModelBase::owner(), fvMesh::owner(), filmSubModelBase::owner_, fvPatchField< Type >::patch(), regionModel::regionMesh(), Foam::constant::physicoChemical::sigma, surfaceFilmModel::sigma(), regionModel::time(), fvMesh::time(), Time::timeName(), and Vector< Cmpt >::zero.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/force/contactAngleForce/contactAngleForce.H
src/regionModels/surfaceFilmModels/submodels/kinematic/force/contactAngleForce/contactAngleForce.C