OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
thixotropicViscosity Class Reference
Public Member Functions
TypeName ("thixotropic")
Runtime type information.
thixotropicViscosity (surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu)
Construct from surface film model.
virtual ~thixotropicViscosity ()
Destructor.
virtual void correct (const volScalarField &p, const volScalarField &T)
Correct.
Public Member Functions inherited from filmViscosityModel
TypeName ("filmViscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmViscosityModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu),(owner, dict, mu))
filmViscosityModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu)
Construct from type name, dictionary and surface film model.
virtual ~filmViscosityModel ()
Destructor.
virtual void info (Ostream &os) const
Provide some feedback.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool outputTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
void updateMu ()
Update the viscosity.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
dimensionedScalar a_
Model `a' coefficient.
dimensionedScalar b_
Model `b' coefficient.
dimensionedScalar d_
Model `d' coefficient.
dimensionedScalar c_
Model `c' coefficient (read after d since dims depend on d value)
dimensionedScalar mu0_
Limiting viscosity when lambda = 1.
dimensionedScalar muInf_
Limiting viscosity when lambda = 0.
dimensionedScalar K_
Model coeffiicient.
volScalarField lambda_
Structural parameter.
Protected Attributes inherited from filmViscosityModel
volScalarField & mu_
Reference to the viscosity field.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from filmViscosityModel
static autoPtr< filmViscosityModel > New (surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu)
Return a reference to the selected phase change model.
Detailed Description
Definition at line 120 of file thixotropicViscosity.H.
Constructor & Destructor Documentation
thixotropicViscosity()
thixotropicViscosity (surfaceFilmModel & owner, const dictionary & dict, volScalarField & mu)
Construct from surface film model.
Definition at line 87 of file thixotropicViscosity.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), thixotropicViscosity::lambda_, GeometricField< Type, PatchField, GeoMesh >::max(), GeometricField< Type, PatchField, GeoMesh >::min(), filmViscosityModel::mu_, and thixotropicViscosity::muInf_.
~thixotropicViscosity()
~thixotropicViscosity () virtual
Destructor.
Definition at line 127 of file thixotropicViscosity.C.
References thixotropicViscosity::correct().
Member Function Documentation
updateMu()
void updateMu () protected
Update the viscosity.
Definition at line 58 of file thixotropicViscosity.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), kinematicSingleLayer::delta(), kinematicSingleLayer::deltaMass(), kinematicSingleLayer::deltaSmall(), Foam::dimMass, thixotropicViscosity::K_, thixotropicViscosity::lambda_, Foam::max(), Foam::min(), filmViscosityModel::mu_, thixotropicViscosity::muInf_, kinematicSingleLayer::netMass(), Foam::pos(), and Foam::sqr().
Referenced by thixotropicViscosity::correct().
TypeName()
TypeName ("thixotropic")
Runtime type information.
correct()
void correct (const volScalarField & p, const volScalarField & T) virtual
Correct.
Implements filmViscosityModel.
Definition at line 134 of file thixotropicViscosity.C.
References thixotropicViscosity::a_, Foam::constant::atomic::alpha, kinematicSingleLayer::alpha(), thixotropicViscosity::b_, thixotropicViscosity::c_, thixotropicViscosity::d_, Foam::fvm::ddt(), delta, kinematicSingleLayer::delta(), kinematicSingleLayer::deltaRho(), kinematicSingleLayer::deltaSmall(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::fvm::div(), Foam::fvc::div(), Foam::fvc::interpolate(), thixotropicViscosity::lambda_, Foam::mag(), GeometricField< Type, PatchField, GeoMesh >::max(), GeometricField< Type, PatchField, GeoMesh >::min(), filmSubModelBase::outputTime(), filmSubModelBase::owner(), phi, kinematicSingleLayer::phi(), Foam::pow(), fvMatrix< Type >::relax(), fvMatrix< Type >::solve(), Foam::fvm::Sp(), Foam::fvm::SuSp(), U, kinematicSingleLayer::U(), thixotropicViscosity::updateMu(), kinematicSingleLayer::Uw(), and regIOobject::write().
Referenced by thixotropicViscosity::~thixotropicViscosity().
Member Data Documentation
a_
dimensionedScalar a_ protected
Model `a' coefficient.
Definition at line 140 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
b_
dimensionedScalar b_ protected
Model `b' coefficient.
Definition at line 143 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
d_
dimensionedScalar d_ protected
Model `d' coefficient.
Definition at line 146 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
c_
dimensionedScalar c_ protected
Model `c' coefficient (read after d since dims depend on d value)
Definition at line 149 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct().
mu0_
dimensionedScalar mu0_ protected
Limiting viscosity when lambda = 1.
Definition at line 152 of file thixotropicViscosity.H.
muInf_
dimensionedScalar muInf_ protected
Limiting viscosity when lambda = 0.
Definition at line 155 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::thixotropicViscosity(), and thixotropicViscosity::updateMu().
K_
dimensionedScalar K_ protected
Model coeffiicient.
Definition at line 158 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::updateMu().
lambda_
volScalarField lambda_ protected
Structural parameter.
0 = freestream value (most liquid) 1 = fully built (most solid)
Definition at line 163 of file thixotropicViscosity.H.
Referenced by thixotropicViscosity::correct(), thixotropicViscosity::thixotropicViscosity(), and thixotropicViscosity::updateMu().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/filmViscosityModel/thixotropicViscosity/thixotropicViscosity.H
src/regionModels/surfaceFilmModels/submodels/thermo/filmViscosityModel/thixotropicViscosity/thixotropicViscosity.C