OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
thermoSingleLayer Class Reference
Public Member Functions
TypeName ("thermoSingleLayer")
Runtime type information.
thermoSingleLayer (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType, const bool readFields=true)
Construct from components.
virtual ~thermoSingleLayer ()
Destructor.
const SLGThermo & thermo () const
Return const reference to the SLGThermo object.
virtual const volScalarField & Cp () const
Return the film specific heat capacity [J/kg/K].
virtual const volScalarField & kappa () const
Return the film thermal conductivity [W/m/K].
virtual const volScalarField & T () const
Return the film mean temperature [K].
virtual const volScalarField & Ts () const
Return the film surface temperature [K].
virtual const volScalarField & Tw () const
Return the film wall temperature [K].
virtual const volScalarField & hs () const
Return the film sensible enthalpy [J/kg].
virtual tmp< volScalarField > primaryMassTrans () const
Return mass transfer source - Eulerian phase only.
tmp< scalarField > hs (const scalarField &T, const label patchI) const
Return sensible enthalpy as a function of temperature.
tmp< volScalarField > hs (const volScalarField &T) const
Return sensible enthalpy as a function of temperature.
tmp< volScalarField > T (const volScalarField &hs) const
Return temperature as a function of sensible enthalpy.
virtual void addSources (const label patchI, const label faceI, const scalar massSource, const vector &momentumSource, const scalar pressureSource, const scalar energySource)
External hook to add sources to the film.
const volScalarField & hsSp () const
Energy / [J/m2/s].
const volScalarField & hsSpPrimary () const
Energy / [J/m2/s].
const volScalarField & TPrimary () const
Temperature / [K].
const PtrList< volScalarField > & YPrimary () const
Specie mass fractions / [0-1].
const heatTransferModel & htcs () const
Return const access to the (surface) heat transfer model.
const heatTransferModel & htcw () const
Return const access to the (wall) heat transfer model.
const phaseChangeModel & phaseChange () const
Return const access to the phase change model.
const filmRadiationModel & radiation () const
Return const access to the radiation model.
tmp< scalarField > Qconvw (const label patchI) const
Return the convective heat energy from film to wall.
tmp< scalarField > Qconvp (const label patchI) const
Return the convective heat energy from primary region to film.
virtual void preEvolveRegion ()
Pre-evolve film hook.
virtual void evolveRegion ()
Evolve the film equations.
virtual tmp< DimensionedField< scalar, volMesh > > Srho () const
Return total mass source - Eulerian phase only.
virtual tmp< DimensionedField< scalar, volMesh > > Srho (const label i) const
Return mass source for specie i - Eulerian phase only.
virtual tmp< DimensionedField< scalar, volMesh > > Sh () const
Return enthalpy source - Eulerian phase only.
virtual void info ()
Provide some feedback.
Public Member Functions inherited from kinematicSingleLayer
TypeName ("kinematicSingleLayer")
Runtime type information.
kinematicSingleLayer (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType, const bool readFields=true)
Construct from components.
virtual ~kinematicSingleLayer ()
Destructor.
virtual scalar CourantNumber () const
Courant number evaluation.
const Switch & momentumPredictor () const
Return the momentum predictor.
label nOuterCorr () const
Return the number of outer correctors.
label nCorr () const
Return the number of PISO correctors.
label nNonOrthCorr () const
Return the number of non-orthogonal correctors.
const dimensionedScalar & deltaSmall () const
Return small delta.
const volScalarField & mu () const
Return const access to the dynamic viscosity / [Pa.s].
const volScalarField & sigma () const
Return const access to the surface tension / [m/s2].
const volScalarField & delta () const
Return const access to the film thickness / [m].
const volScalarField & alpha () const
Return the film coverage, 1 = covered, 0 = uncovered / [].
virtual const volVectorField & U () const
Return the film velocity [m/s].
virtual const volVectorField & Us () const
Return the film surface velocity [m/s].
virtual const volVectorField & Uw () const
Return the film wall velocity [m/s].
virtual const volScalarField & deltaRho () const
Return the film thickness*density (helper field) [kg/m3].
virtual const surfaceScalarField & phi () const
Return the film flux [kg.m/s].
virtual const volScalarField & rho () const
Return the film density [kg/m3].
virtual const volScalarField & cloudMassTrans () const
Return the film mass available for transfer to cloud.
virtual const volScalarField & cloudDiameterTrans () const
Return the parcel diameters originating from film to cloud.
volVectorField & USpPrimary ()
Momementum / [kg/m/s2].
volScalarField & pSpPrimary ()
Pressure / [Pa].
volScalarField & rhoSpPrimary ()
Mass / [kg/m2/s].
volVectorField & USp ()
Momentum / [kg/m/s2].
volScalarField & pSp ()
Pressure / [Pa].
volScalarField & rhoSp ()
Mass / [kg/m2/s].
const volVectorField & USp () const
Momentum / [kg/m/s2].
const volScalarField & pSp () const
Pressure / [Pa].
const volScalarField & rhoSp () const
Mass / [kg/m2/s].
const volVectorField & UPrimary () const
Velocity / [m/s].
const volScalarField & pPrimary () const
Pressure / [Pa].
const volScalarField & rhoPrimary () const
Density / [kg/m3].
const volScalarField & muPrimary () const
Viscosity / [Pa.s].
const filmThermoModel & filmThermo () const
Film thermo.
injectionModelList & injection ()
Injection.
const filmTurbulenceModel & turbulence () const
Turbulence.
tmp< volScalarField > mass () const
Return the current film mass.
tmp< volScalarField > netMass () const
Return the net film mass available over the next integration.
tmp< volScalarField > deltaMass () const
Return the change in film mass due to sources/sinks.
tmp< volScalarField > gNorm () const
Return the gravity normal-to-patch component contribution.
tmp< volScalarField > gNormClipped () const
Return the gravity normal-to-patch component contribution.
tmp< volVectorField > gTan () const
Return the gravity tangential component contributions.
Public Member Functions inherited from surfaceFilmModel
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType)
Construct from type name, mesh and gravity vector.
virtual ~surfaceFilmModel ()
Destructor.
const dimensionedVector & g () const
Return the accleration due to gravity.
Public Member Functions inherited from singleLayerRegion
TypeName ("regionModel")
Runtime type information.
singleLayerRegion (const fvMesh &mesh, const word &regionType)
Construct null.
singleLayerRegion (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
virtual ~singleLayerRegion ()
Destructor.
virtual const volVectorField & nHat () const
Return the patch normal vectors.
virtual const volScalarField & magSf () const
Return the face area magnitudes / [m2].
virtual const labelList & passivePatchIDs () const
Return the list of patch IDs opposite to internally.
template<class Type >
wordList mappedFieldAndInternalPatchTypes () const
Return boundary types for mapped field patches.
template<class Type >
wordList mappedPushedFieldPatchTypes () const
Return boundary types for pushed mapped field patches.
template<class Type >
Foam::wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
Foam::wordList mappedPushedFieldPatchTypes () const
Public Member Functions inherited from regionModel
TypeName ("regionModel")
Runtime type information.
regionModel (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh and name and dict.
virtual ~regionModel ()
Destructor.
const fvMesh & primaryMesh () const
Return the reference to the primary mesh database.
const Time & time () const
Return the reference to the time database.
const Switch & active () const
Return the active flag.
const Switch & infoOutput () const
Return the information flag.
const word & modelName () const
Return the model name.
const fvMesh & regionMesh () const
Return the region mesh database.
fvMesh & regionMesh ()
Return the region mesh database for manipulation.
const dictionary & coeffs () const
Return the model coefficients dictionary.
const dictionary & solution () const
Return the solution dictionary.
const IOdictionary & outputProperties () const
Return const access to the output properties dictionary.
IOdictionary & outputProperties ()
Return output properties dictionary.
bool isCoupledPatch (const label regionPatchI) const
Return true if patchI on the local region is a coupled.
bool isRegionPatch (const label primaryPatchI) const
Return true if patchI on the primary region is a coupled.
const labelList & primaryPatchIDs () const
Return the list of patch IDs on the primary region coupled.
const labelList & intCoupledPatchIDs () const
Return the list of patch IDs internally coupled with the.
label regionPatchID (const label primaryPatchID) const
Return region ID corresponding to primaryPatchID.
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchI) const
Return the coupled patch ID paired with coupled patch.
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch internal field from another region model to local.
template<class Type >
void toPrimary (const label regionPatchI, List< Type > &regionField) const
Convert a local region field to the primary region.
template<class Type >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField) const
Convert a primary region field to the local region.
template<class Type , class CombineOp >
void toPrimary (const label regionPatchI, List< Type > &regionField, const CombineOp &cop) const
Convert a local region field to the primary region with op.
template<class Type , class CombineOp >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField, const CombineOp &cop) const
Convert a primary region field to the local region with op.
virtual void evolve ()
Main driver routing to evolve the region - calls other evolves.
virtual void postEvolveRegion ()
Post-evolve region.
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Protected Member Functions
virtual bool read ()
Read control parameters from dictionary.
virtual void correctThermoFields ()
Correct the thermo fields.
virtual void correctHsForMappedT ()
Correct sensible enthalpy for mapped temperature fields.
virtual void updateSurfaceTemperatures ()
Correct the film surface and wall temperatures.
virtual void resetPrimaryRegionSourceTerms ()
Reset source term fields.
virtual void transferPrimaryRegionThermoFields ()
Transfer thermo fields from the primary region to the film region.
virtual void transferPrimaryRegionSourceFields ()
Transfer source fields from the primary region to the film region.
virtual void correctAlpha ()
Correct film coverage field.
virtual void updateSubmodels ()
Update the film sub-models.
virtual tmp< fvScalarMatrix > q (volScalarField &hs) const
Return the wall/surface heat transfer term for the enthalpy equation.
virtual void solveEnergy ()
Solve energy equation.
Protected Member Functions inherited from kinematicSingleLayer
virtual tmp< volScalarField > pu ()
Explicit pressure source contribution.
virtual tmp< volScalarField > pp ()
Implicit pressure source coefficient.
virtual void continuityCheck ()
Continuity check.
virtual void updateSurfaceVelocities ()
Update film surface velocities.
template<class Type >
void constrainFilmField (Type &field, const typename Type::cmptType &value)
Constrain a film region master/slave boundaries of a field to a.
virtual void solveContinuity ()
Solve continuity equation.
virtual tmp< fvVectorMatrix > solveMomentum (const volScalarField &pu, const volScalarField &pp)
Solve for film velocity.
virtual void solveThickness (const volScalarField &pu, const volScalarField &pp, const fvVectorMatrix &UEqn)
Solve coupled velocity-thickness equations.
Protected Member Functions inherited from regionModel
virtual bool read (const dictionary &dict)
Read control parameters from dictionary.
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const bool flip) const
Create or return a new inter-region AMI object.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
const SLGThermo & thermo_
Reference to the SLGThermo.
volScalarField Cp_
Specific heat capacity / [J/kg/K].
volScalarField kappa_
Thermal conductivity / [W/m/K].
volScalarField T_
Temperature - mean / [K].
volScalarField Ts_
Temperature - surface / [K].
volScalarField Tw_
Temperature - wall / [K].
volScalarField hs_
Sensible enthalpy / [J/kg].
volScalarField primaryMassPCTrans_
Film mass evolved via phase change.
volScalarField primaryEnergyPCTrans_
Film energy evolved via phase change.
scalar deltaWet_
Threshold film thickness beyond which the film is considered 'wet'.
bool hydrophilic_
Activation flag.
scalar hydrophilicDryScale_
Length scale applied to deltaWet_ to determine when a wet.
scalar hydrophilicWetScale_
Length scale applied to deltaWet_ to determine when a dry.
volScalarField hsSp_
Energy / [J/m2/s].
volScalarField hsSpPrimary_
Energy / [J/m2/s].
volScalarField TPrimary_
Temperature / [K].
PtrList< volScalarField > YPrimary_
List of specie mass fractions / [0-1].
autoPtr< filmViscosityModel > viscosity_
Viscosity model.
autoPtr< heatTransferModel > htcs_
Heat transfer coefficient bewteen film surface and primary.
autoPtr< heatTransferModel > htcw_
Heat transfer coefficient bewteen wall and film [W/m2/K].
autoPtr< phaseChangeModel > phaseChange_
Phase change.
autoPtr< filmRadiationModel > radiation_
Radiation.
scalar Tmin_
Minimum temperature limit (optional)
scalar Tmax_
Maximum temperature limit (optional)
Protected Attributes inherited from kinematicSingleLayer
Switch momentumPredictor_
Momentum predictor.
label nOuterCorr_
Number of outer correctors.
label nCorr_
Number of PISO-like correctors.
label nNonOrthCorr_
Number of non-orthogonal correctors.
scalar cumulativeContErr_
Cumulative continuity error.
const dimensionedScalar deltaSmall_
Small delta.
scalar deltaCoLimit_
Film thickness above which Courant number calculation in valid.
volScalarField rho_
Density / [kg/m3].
volScalarField mu_
Dynamic viscosity / [Pa.s].
volScalarField sigma_
Surface tension / [m/s2].
volScalarField delta_
Film thickness / [m].
volScalarField alpha_
Film coverage indicator, 1 = covered, 0 = uncovered / [].
volVectorField U_
Velocity - mean / [m/s].
volVectorField Us_
Velocity - surface / [m/s].
volVectorField Uw_
Velocity - wall / [m/s].
volScalarField deltaRho_
Film thickness*density (helper field) / [kg/m2].
surfaceScalarField phi_
Mass flux (includes film thickness) / [kg.m/s].
volScalarField primaryMassTrans_
Film mass available for transfer to the primary region.
volScalarField cloudMassTrans_
Film mass available for transfer to cloud.
volScalarField cloudDiameterTrans_
Parcel diameters originating from film to cloud.
volVectorField USp_
Momementum / [kg/m/s2].
volScalarField pSp_
Pressure / [Pa].
volScalarField rhoSp_
Mass / [kg/m2/s].
volVectorField USpPrimary_
Momementum / [kg/m/s2].
volScalarField pSpPrimary_
Pressure / [Pa].
volScalarField rhoSpPrimary_
Mass / [kg/m2/s].
volVectorField UPrimary_
Velocity / [m/s].
volScalarField pPrimary_
Pressure / [Pa].
volScalarField rhoPrimary_
Density / [kg/m3].
volScalarField muPrimary_
Viscosity / [Pa.s].
autoPtr< filmThermoModel > filmThermo_
Film thermo model.
scalarField availableMass_
Available mass for transfer via sub-models.
injectionModelList injection_
Cloud injection.
autoPtr< filmTurbulenceModel > turbulence_
Turbulence model.
forceList forces_
List of film forces.
scalar addedMassTotal_
Cumulative mass added via sources [kg].
Protected Attributes inherited from surfaceFilmModel
const dimensionedVector & g_
Acceleration due to gravity [m/s2].
Protected Attributes inherited from singleLayerRegion
autoPtr< volVectorField > nHatPtr_
Patch normal vectors.
autoPtr< volScalarField > magSfPtr_
Face area magnitudes / [m2].
labelList passivePatchIDs_
List of patch IDs opposite to internally coupled patches.
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
Reference to the primary mesh database.
const Time & time_
Reference to the time database.
Switch active_
Active flag.
Switch infoOutput_
Active information output.
const word modelName_
Model name.
autoPtr< fvMesh > regionMeshPtr_
Pointer to the region mesh database.
dictionary coeffs_
Model coefficients dictionary.
autoPtr< IOdictionary > outputPropertiesPtr_
Dictionary of output properties.
labelList primaryPatchIDs_
List of patch IDs on the primary region coupled to this region.
labelList intCoupledPatchIDs_
List of patch IDs internally coupled with the primary region.
word regionName_
Region name.
regionModelFunctionObjectList functions_
Region model function objects.
wordList interRegionAMINames_
List of region names this region is coupled to.
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
List of AMI objects per coupled region.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase ::iterator LListBase_iterator
typedef DLListBase ::const_iterator LListBase_const_iterator
typedef DLListBase ::const_reverse_iterator LListBase_const_reverse_iterator
Static Public Member Functions inherited from surfaceFilmModel
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Return a reference to the selected surface film model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Definition at line 63 of file thermoSingleLayer.H.
Constructor & Destructor Documentation
thermoSingleLayer()
thermoSingleLayer (const word & modelType, const fvMesh & mesh, const dimensionedVector & g, const word & regionType, const bool readFields = true)
Construct from components.
Definition at line 301 of file thermoSingleLayer.C.
References IOobject::AUTO_WRITE, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), SLGThermo::carrier(), regionModel::coeffs(), regionModel::coeffs_, thermoSingleLayer::correctAlpha(), thermoSingleLayer::correctThermoFields(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::dimless, Foam::endl(), forAll, SLGThermo::hasMultiComponentCarrier(), thermoSingleLayer::hs(), thermoSingleLayer::hs_, thermoSingleLayer::hydrophilic_, thermoSingleLayer::hydrophilicDryScale_, thermoSingleLayer::hydrophilicWetScale_, Foam::Info, Foam::fvc::interpolate(), dictionary::lookup(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::constant::electromagnetic::phi0, kinematicSingleLayer::phi_, kinematicSingleLayer::pPrimary_, kinematicSingleLayer::pSp_, IOobject::READ_IF_PRESENT, dictionary::readIfPresent(), regionModel::regionMesh(), kinematicSingleLayer::rho_, List< T >::size(), basicMultiComponentMixture::species(), thermoSingleLayer::T_, thermoSingleLayer::thermo_, regionModel::time(), timeName, Time::timeName(), thermoSingleLayer::Tmax_, thermoSingleLayer::Tmin_, thermoSingleLayer::transferPrimaryRegionThermoFields(), kinematicSingleLayer::U_, thermoSingleLayer::viscosity_, and thermoSingleLayer::YPrimary_.
~thermoSingleLayer()
~thermoSingleLayer () virtual
Destructor.
Definition at line 572 of file thermoSingleLayer.C.
References thermoSingleLayer::addSources().
Member Function Documentation
read()
bool read () protected virtual
Read control parameters from dictionary.
Reimplemented from kinematicSingleLayer.
Definition at line 81 of file thermoSingleLayer.C.
References kinematicSingleLayer::read().
correctThermoFields()
void correctThermoFields () protected virtual
Correct the thermo fields.
Reimplemented from kinematicSingleLayer.
Definition at line 101 of file thermoSingleLayer.C.
References thermoSingleLayer::Cp_, kinematicSingleLayer::filmThermo_, thermoSingleLayer::kappa_, kinematicSingleLayer::rho_, and kinematicSingleLayer::sigma_.
Referenced by thermoSingleLayer::solveEnergy(), and thermoSingleLayer::thermoSingleLayer().
correctHsForMappedT()
void correctHsForMappedT () protected virtual
Correct sensible enthalpy for mapped temperature fields.
Definition at line 110 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), forAll, thermoSingleLayer::hs(), thermoSingleLayer::hs_, Foam::isA(), and thermoSingleLayer::T_.
Referenced by thermoSingleLayer::updateSurfaceTemperatures().
updateSurfaceTemperatures()
void updateSurfaceTemperatures () protected virtual
Correct the film surface and wall temperatures.
Definition at line 125 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), thermoSingleLayer::correctHsForMappedT(), polyPatch::faceCells(), regionModel::intCoupledPatchIDs_, kinematicSingleLayer::pp(), regionModel::regionMesh(), List< T >::size(), thermoSingleLayer::T_, thermoSingleLayer::Ts_, and thermoSingleLayer::Tw_.
Referenced by thermoSingleLayer::evolveRegion(), and thermoSingleLayer::solveEnergy().
resetPrimaryRegionSourceTerms()
void resetPrimaryRegionSourceTerms () protected virtual
Reset source term fields.
Reimplemented from kinematicSingleLayer.
Definition at line 88 of file thermoSingleLayer.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::endl(), thermoSingleLayer::hsSp_, thermoSingleLayer::hsSpPrimary_, Foam::Info, and kinematicSingleLayer::resetPrimaryRegionSourceTerms().
Referenced by thermoSingleLayer::evolveRegion().
transferPrimaryRegionThermoFields()
void transferPrimaryRegionThermoFields () protected virtual
Transfer thermo fields from the primary region to the film region.
Reimplemented from kinematicSingleLayer.
Definition at line 145 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), forAll, Foam::Info, thermoSingleLayer::TPrimary_, kinematicSingleLayer::transferPrimaryRegionThermoFields(), and thermoSingleLayer::YPrimary_.
Referenced by thermoSingleLayer::thermoSingleLayer().
transferPrimaryRegionSourceFields()
void transferPrimaryRegionSourceFields () protected virtual
Transfer source fields from the primary region to the film region.
Reimplemented from kinematicSingleLayer.
Definition at line 164 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), TimeState::deltaTValue(), Foam::endl(), forAll, thermoSingleLayer::hs_, thermoSingleLayer::hsSp_, thermoSingleLayer::hsSpPrimary_, Foam::Info, fvMesh::magSf(), regionModel::primaryMesh(), kinematicSingleLayer::rhoSp_, regionModel::time_, and kinematicSingleLayer::transferPrimaryRegionSourceFields().
correctAlpha()
void correctAlpha () protected virtual
Correct film coverage field.
Reimplemented from kinematicSingleLayer.
Definition at line 194 of file thermoSingleLayer.C.
References kinematicSingleLayer::alpha_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), kinematicSingleLayer::delta_, thermoSingleLayer::deltaWet_, Foam::dimLength, forAll, thermoSingleLayer::hydrophilic_, thermoSingleLayer::hydrophilicDryScale_, thermoSingleLayer::hydrophilicWetScale_, and Foam::pos().
Referenced by thermoSingleLayer::evolveRegion(), and thermoSingleLayer::thermoSingleLayer().
updateSubmodels()
void updateSubmodels () protected virtual
Update the film sub-models.
Reimplemented from kinematicSingleLayer.
Definition at line 223 of file thermoSingleLayer.C.
References kinematicSingleLayer::availableMass_, TimeState::deltaT(), TimeState::deltaTValue(), Foam::endl(), thermoSingleLayer::hsSp_, thermoSingleLayer::htcs_, thermoSingleLayer::htcw_, Foam::Info, singleLayerRegion::magSf(), thermoSingleLayer::phaseChange_, thermoSingleLayer::primaryEnergyPCTrans_, thermoSingleLayer::primaryMassPCTrans_, kinematicSingleLayer::pSp_, thermoSingleLayer::radiation_, kinematicSingleLayer::rhoPrimary_, kinematicSingleLayer::rhoSp_, Foam::sqr(), regionModel::time(), regionModel::time_, and kinematicSingleLayer::updateSubmodels().
Referenced by thermoSingleLayer::evolveRegion().
q()
tmp< fvScalarMatrix > q (volScalarField & hs) const protected virtual
Return the wall/surface heat transfer term for the enthalpy equation.
Definition at line 257 of file thermoSingleLayer.C.
References thermoSingleLayer::Cp_, thermoSingleLayer::hs(), thermoSingleLayer::htcs_, thermoSingleLayer::htcw_, Foam::fvm::Sp(), thermoSingleLayer::TPrimary_, Foam::constant::standard::Tstd, and thermoSingleLayer::Tw_.
Referenced by thermoSingleLayer::solveEnergy().
solveEnergy()
void solveEnergy () protected virtual
Solve energy equation.
Definition at line 270 of file thermoSingleLayer.C.
References thermoSingleLayer::correctThermoFields(), Foam::fvm::ddt(), kinematicSingleLayer::deltaRho_, Foam::fvm::div(), Foam::endl(), thermoSingleLayer::hs_, thermoSingleLayer::hsSp_, Foam::Info, kinematicSingleLayer::phi_, kinematicSingleLayer::pPrimary_, thermoSingleLayer::q(), thermoSingleLayer::radiation_, kinematicSingleLayer::rhoSp_, Foam::solve(), thermoSingleLayer::T_, thermoSingleLayer::updateSurfaceTemperatures(), and thermoSingleLayer::viscosity_.
Referenced by thermoSingleLayer::evolveRegion().
TypeName()
TypeName ("thermoSingleLayer")
Runtime type information.
thermo()
const SLGThermo & thermo () const inline
Return const reference to the SLGThermo object.
Definition at line 42 of file thermoSingleLayerI.H.
References thermoSingleLayer::hs(), and thermoSingleLayer::thermo_.
Referenced by standardPhaseChange::correctModel().
Cp()
const volScalarField & Cp () const virtual
Return the film specific heat capacity [J/kg/K].
Reimplemented from kinematicSingleLayer.
Definition at line 679 of file thermoSingleLayer.C.
References thermoSingleLayer::Cp_.
Referenced by thermoSingleLayer::hs().
kappa()
const volScalarField & kappa () const virtual
Return the film thermal conductivity [W/m/K].
Reimplemented from kinematicSingleLayer.
Definition at line 685 of file thermoSingleLayer.C.
References thermoSingleLayer::kappa_.
T() [1/2]
const volScalarField & T () const virtual
Return the film mean temperature [K].
Reimplemented from kinematicSingleLayer.
Definition at line 691 of file thermoSingleLayer.C.
References thermoSingleLayer::T_.
Referenced by solidification::correctModel(), standardPhaseChange::correctModel(), liquidFilmThermo::Cp(), thermoSingleLayer::evolveRegion(), thermoSingleLayer::hs(), liquidFilmThermo::kappa(), liquidFilmThermo::mu(), liquidFilmThermo::rho(), and liquidFilmThermo::sigma().
Ts()
const volScalarField & Ts () const virtual
Return the film surface temperature [K].
Reimplemented from kinematicSingleLayer.
Definition at line 697 of file thermoSingleLayer.C.
References thermoSingleLayer::Ts_.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
Tw()
const volScalarField & Tw () const virtual
Return the film wall temperature [K].
Reimplemented from kinematicSingleLayer.
Definition at line 703 of file thermoSingleLayer.C.
References thermoSingleLayer::Tw_.
hs() [1/3]
const volScalarField & hs () const virtual
Return the film sensible enthalpy [J/kg].
Definition at line 709 of file thermoSingleLayer.C.
References thermoSingleLayer::hs_.
Referenced by thermoSingleLayer::correctHsForMappedT(), thermoSingleLayer::hs(), thermoSingleLayer::q(), thermoSingleLayer::thermo(), and thermoSingleLayer::thermoSingleLayer().
primaryMassTrans()
tmp< volScalarField > primaryMassTrans () const virtual
Return mass transfer source - Eulerian phase only.
Reimplemented from kinematicSingleLayer.
Definition at line 715 of file thermoSingleLayer.C.
References thermoSingleLayer::primaryMassPCTrans_.
hs() [2/3]
tmp< scalarField > hs (const scalarField & T, const label patchI) const inline
Return sensible enthalpy as a function of temperature.
for a patch
Definition at line 49 of file thermoSingleLayerI.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::Cp(), thermoSingleLayer::Cp_, and thermoSingleLayer::hs().
hs() [3/3]
tmp< volScalarField > hs (const volScalarField & T) const inline
Return sensible enthalpy as a function of temperature.
Definition at line 60 of file thermoSingleLayerI.H.
References thermoSingleLayer::Cp_, Foam::dimTemperature, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::regionMesh(), thermoSingleLayer::T(), regionModel::time(), and Time::timeName().
T() [2/2]
tmp< volScalarField > T (const volScalarField & hs) const inline
Return temperature as a function of sensible enthalpy.
Definition at line 84 of file thermoSingleLayerI.H.
References thermoSingleLayer::Cp_, Foam::dimTemperature, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, regionModel::regionMesh(), regionModel::time(), Time::timeName(), thermoSingleLayer::Tmax_, and thermoSingleLayer::Tmin_.
addSources()
void addSources (const label patchI, const label faceI, const scalar massSource, const vector & momentumSource, const scalar pressureSource, const scalar energySource) virtual
External hook to add sources to the film.
Reimplemented from kinematicSingleLayer.
Definition at line 579 of file thermoSingleLayer.C.
References kinematicSingleLayer::addSources(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), thermoSingleLayer::hsSpPrimary_, Foam::Info, and Foam::nl.
Referenced by thermoSingleLayer::~thermoSingleLayer().
hsSp()
const volScalarField & hsSp () const inline
Energy / [J/m2/s].
Definition at line 112 of file thermoSingleLayerI.H.
References thermoSingleLayer::hsSp_.
hsSpPrimary()
const volScalarField & hsSpPrimary () const inline
Energy / [J/m2/s].
Definition at line 118 of file thermoSingleLayerI.H.
References thermoSingleLayer::hsSpPrimary_.
TPrimary()
const volScalarField & TPrimary () const inline
Temperature / [K].
Definition at line 124 of file thermoSingleLayerI.H.
References thermoSingleLayer::TPrimary_.
YPrimary()
const PtrList< volScalarField > & YPrimary () const inline
Specie mass fractions / [0-1].
Definition at line 130 of file thermoSingleLayerI.H.
References thermoSingleLayer::YPrimary_.
Referenced by standardPhaseChange::correctModel().
htcs()
const heatTransferModel & htcs () const inline
Return const access to the (surface) heat transfer model.
Definition at line 136 of file thermoSingleLayerI.H.
References thermoSingleLayer::htcs_.
htcw()
const heatTransferModel & htcw () const inline
Return const access to the (wall) heat transfer model.
Definition at line 142 of file thermoSingleLayerI.H.
References thermoSingleLayer::htcw_.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
phaseChange()
const phaseChangeModel & phaseChange () const inline
Return const access to the phase change model.
Definition at line 148 of file thermoSingleLayerI.H.
References thermoSingleLayer::phaseChange_.
radiation()
const filmRadiationModel & radiation () const inline
Return const access to the radiation model.
Definition at line 154 of file thermoSingleLayerI.H.
References thermoSingleLayer::radiation_.
Qconvw()
tmp< scalarField > Qconvw (const label patchI) const inline
Return the convective heat energy from film to wall.
Definition at line 160 of file thermoSingleLayerI.H.
References boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::htcw_, thermoSingleLayer::T_, and thermoSingleLayer::Tw_.
Qconvp()
tmp< scalarField > Qconvp (const label patchI) const inline
Return the convective heat energy from primary region to film.
Definition at line 170 of file thermoSingleLayerI.H.
References boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), thermoSingleLayer::htcs_, thermoSingleLayer::T_, and thermoSingleLayer::TPrimary_.
preEvolveRegion()
void preEvolveRegion () virtual
Pre-evolve film hook.
Reimplemented from kinematicSingleLayer.
Definition at line 607 of file thermoSingleLayer.C.
References Foam::dimEnergy, Foam::dimMass, Foam::endl(), Foam::Info, kinematicSingleLayer::preEvolveRegion(), thermoSingleLayer::primaryEnergyPCTrans_, and thermoSingleLayer::primaryMassPCTrans_.
evolveRegion()
void evolveRegion () virtual
Evolve the film equations.
Reimplemented from kinematicSingleLayer.
Definition at line 624 of file thermoSingleLayer.C.
References thermoSingleLayer::correctAlpha(), kinematicSingleLayer::delta_, kinematicSingleLayer::deltaRho_, Foam::endl(), thermoSingleLayer::hs_, Foam::Info, kinematicSingleLayer::nCorr_, kinematicSingleLayer::nOuterCorr_, kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), thermoSingleLayer::resetPrimaryRegionSourceTerms(), kinematicSingleLayer::rho_, kinematicSingleLayer::solveContinuity(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::T(), thermoSingleLayer::T_, UEqn(), thermoSingleLayer::updateSubmodels(), thermoSingleLayer::updateSurfaceTemperatures(), and kinematicSingleLayer::updateSurfaceVelocities().
Srho() [1/2]
tmp< DimensionedField< scalar, volMesh > > Srho () const virtual
Return total mass source - Eulerian phase only.
Reimplemented from kinematicSingleLayer.
Definition at line 734 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), cells, TimeState::deltaTValue(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, regionModel::intCoupledPatchIDs(), IOobject::NO_READ, IOobject::NO_WRITE, thermoSingleLayer::primaryMassPCTrans_, regionModel::primaryMesh(), regionModel::primaryPatchIDs(), regionModel::time(), regionModel::time_, timeName, regionModel::toPrimary(), and fvMesh::V().
Referenced by thermoSingleLayer::Srho().
Srho() [2/2]
tmp< DimensionedField< scalar, volMesh > > Srho (const label i) const virtual
Return mass source for specie i - Eulerian phase only.
Reimplemented from kinematicSingleLayer.
Definition at line 782 of file thermoSingleLayer.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), SLGThermo::carrierId(), cells, TimeState::deltaTValue(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, kinematicSingleLayer::filmThermo_, forAll, regionModel::intCoupledPatchIDs_, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, thermoSingleLayer::primaryMassPCTrans_, regionModel::primaryMesh(), regionModel::primaryPatchIDs(), thermoSingleLayer::Srho(), thermoSingleLayer::thermo_, regionModel::time(), regionModel::time_, Time::timeName(), regionModel::toPrimary(), and fvMesh::V().
Sh()
tmp< DimensionedField< scalar, volMesh > > Sh () const virtual
Return enthalpy source - Eulerian phase only.
Reimplemented from kinematicSingleLayer.
Definition at line 836 of file thermoSingleLayer.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, IOobject::NO_READ, IOobject::NO_WRITE, regionModel::primaryMesh(), regionModel::time(), and timeName.
info()
void info () virtual
Provide some feedback.
Reimplemented from kinematicSingleLayer.
Definition at line 721 of file thermoSingleLayer.C.
References Foam::gMax(), Foam::gMin(), Foam::indent(), Foam::Info, kinematicSingleLayer::info(), GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::nl, thermoSingleLayer::phaseChange_, and thermoSingleLayer::T_.
Member Data Documentation
thermo_
const SLGThermo& thermo_ protected
Reference to the SLGThermo.
Definition at line 88 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::Srho(), thermoSingleLayer::thermo(), and thermoSingleLayer::thermoSingleLayer().
Cp_
volScalarField Cp_ protected
Specific heat capacity / [J/kg/K].
Definition at line 94 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), thermoSingleLayer::Cp(), thermoSingleLayer::hs(), thermoSingleLayer::q(), and thermoSingleLayer::T().
kappa_
volScalarField kappa_ protected
Thermal conductivity / [W/m/K].
Definition at line 97 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctThermoFields(), and thermoSingleLayer::kappa().
T_
volScalarField T_ protected
Temperature - mean / [K].
Definition at line 100 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctHsForMappedT(), thermoSingleLayer::evolveRegion(), thermoSingleLayer::info(), thermoSingleLayer::Qconvp(), thermoSingleLayer::Qconvw(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::T(), thermoSingleLayer::thermoSingleLayer(), and thermoSingleLayer::updateSurfaceTemperatures().
Ts_
volScalarField Ts_ protected
Temperature - surface / [K].
Definition at line 103 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::Ts(), and thermoSingleLayer::updateSurfaceTemperatures().
Tw_
volScalarField Tw_ protected
Temperature - wall / [K].
Definition at line 106 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::q(), thermoSingleLayer::Qconvw(), thermoSingleLayer::Tw(), and thermoSingleLayer::updateSurfaceTemperatures().
hs_
volScalarField hs_ protected
Sensible enthalpy / [J/kg].
Definition at line 109 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctHsForMappedT(), thermoSingleLayer::evolveRegion(), thermoSingleLayer::hs(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::thermoSingleLayer(), and thermoSingleLayer::transferPrimaryRegionSourceFields().
primaryMassPCTrans_
volScalarField primaryMassPCTrans_ protected
Film mass evolved via phase change.
Definition at line 115 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::preEvolveRegion(), thermoSingleLayer::primaryMassTrans(), thermoSingleLayer::Srho(), and thermoSingleLayer::updateSubmodels().
primaryEnergyPCTrans_
volScalarField primaryEnergyPCTrans_ protected
Film energy evolved via phase change.
Definition at line 118 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::preEvolveRegion(), and thermoSingleLayer::updateSubmodels().
deltaWet_
scalar deltaWet_ protected
Threshold film thickness beyond which the film is considered 'wet'.
Definition at line 122 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha().
hydrophilic_
bool hydrophilic_ protected
Activation flag.
Definition at line 128 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), and thermoSingleLayer::thermoSingleLayer().
hydrophilicDryScale_
scalar hydrophilicDryScale_ protected
Length scale applied to deltaWet_ to determine when a wet.
surface becomes dry, typically 0.5
Definition at line 132 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), and thermoSingleLayer::thermoSingleLayer().
hydrophilicWetScale_
scalar hydrophilicWetScale_ protected
Length scale applied to deltaWet_ to determine when a dry.
surface becomes wet, typically 0.001
Definition at line 136 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::correctAlpha(), and thermoSingleLayer::thermoSingleLayer().
hsSp_
volScalarField hsSp_ protected
Energy / [J/m2/s].
Definition at line 146 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::hsSp(), thermoSingleLayer::resetPrimaryRegionSourceTerms(), thermoSingleLayer::solveEnergy(), thermoSingleLayer::transferPrimaryRegionSourceFields(), and thermoSingleLayer::updateSubmodels().
hsSpPrimary_
volScalarField hsSpPrimary_ protected
Energy / [J/m2/s].
Definition at line 153 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::addSources(), thermoSingleLayer::hsSpPrimary(), thermoSingleLayer::resetPrimaryRegionSourceTerms(), and thermoSingleLayer::transferPrimaryRegionSourceFields().
TPrimary_
volScalarField TPrimary_ protected
Temperature / [K].
Definition at line 160 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::q(), thermoSingleLayer::Qconvp(), thermoSingleLayer::TPrimary(), and thermoSingleLayer::transferPrimaryRegionThermoFields().
YPrimary_
PtrList<volScalarField> YPrimary_ protected
List of specie mass fractions / [0-1].
Definition at line 163 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::thermoSingleLayer(), thermoSingleLayer::transferPrimaryRegionThermoFields(), and thermoSingleLayer::YPrimary().
viscosity_
autoPtr<filmViscosityModel> viscosity_ protected
Viscosity model.
Definition at line 169 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::solveEnergy(), and thermoSingleLayer::thermoSingleLayer().
htcs_
autoPtr<heatTransferModel> htcs_ protected
Heat transfer coefficient bewteen film surface and primary.
region [W/m2/K]
Definition at line 173 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::htcs(), thermoSingleLayer::q(), thermoSingleLayer::Qconvp(), and thermoSingleLayer::updateSubmodels().
htcw_
autoPtr<heatTransferModel> htcw_ protected
Heat transfer coefficient bewteen wall and film [W/m2/K].
Definition at line 176 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::htcw(), thermoSingleLayer::q(), thermoSingleLayer::Qconvw(), and thermoSingleLayer::updateSubmodels().
phaseChange_
autoPtr<phaseChangeModel> phaseChange_ protected
Phase change.
Definition at line 179 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::info(), thermoSingleLayer::phaseChange(), and thermoSingleLayer::updateSubmodels().
radiation_
autoPtr<filmRadiationModel> radiation_ protected
Radiation.
Definition at line 182 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::radiation(), thermoSingleLayer::solveEnergy(), and thermoSingleLayer::updateSubmodels().
Tmin_
scalar Tmin_ protected
Minimum temperature limit (optional)
Definition at line 188 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::T(), and thermoSingleLayer::thermoSingleLayer().
Tmax_
scalar Tmax_ protected
Maximum temperature limit (optional)
Definition at line 191 of file thermoSingleLayer.H.
Referenced by thermoSingleLayer::T(), and thermoSingleLayer::thermoSingleLayer().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/thermoSingleLayer/thermoSingleLayer.H
src/regionModels/surfaceFilmModels/thermoSingleLayer/thermoSingleLayer.C
src/regionModels/surfaceFilmModels/thermoSingleLayer/thermoSingleLayerI.H