OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
standardPhaseChange Class Reference
Public Member Functions
TypeName ("standardPhaseChange")
Runtime type information.
standardPhaseChange (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model.
virtual ~standardPhaseChange ()
Destructor.
virtual void correctModel (const scalar dt, scalarField &availableMass, scalarField &dMass, scalarField &dEnergy)
Correct.
Public Member Functions inherited from phaseChangeModel
TypeName ("phaseChangeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, phaseChangeModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
phaseChangeModel (surfaceFilmModel &owner)
Construct null.
phaseChangeModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~phaseChangeModel ()
Destructor.
virtual void correct (const scalar dt, scalarField &availableMass, volScalarField &dMass, volScalarField &dEnergy)
Correct.
virtual void info (Ostream &os) const
Provide some feedback.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool outputTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
scalar Sh (const scalar Re, const scalar Sc) const
Return Sherwood number as a function of Reynolds and Schmidt numbers.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const scalar deltaMin_
Minimum film height for model to be active.
const scalar L_
Length scale / [m].
const scalar TbFactor_
Boiling temperature factor / [].
Protected Attributes inherited from phaseChangeModel
scalar latestMassPC_
Latest mass transfer due to phase change.
scalar totalMassPC_
Total mass transfer due to phase change.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from phaseChangeModel
static autoPtr< phaseChangeModel > New (surfaceFilmModel &owner, const dictionary &dict)
Return a reference to the selected phase change model.
Detailed Description
Definition at line 52 of file standardPhaseChange.H.
Constructor & Destructor Documentation
standardPhaseChange()
standardPhaseChange (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model.
Definition at line 72 of file standardPhaseChange.C.
~standardPhaseChange()
~standardPhaseChange () virtual
Destructor.
Definition at line 86 of file standardPhaseChange.C.
References standardPhaseChange::correctModel().
Member Function Documentation
Sh()
scalar Sh (const scalar Re, const scalar Sc) const protected
Return Sherwood number as a function of Reynolds and Schmidt numbers.
Definition at line 53 of file standardPhaseChange.C.
References Foam::cbrt(), Foam::pow(), and Foam::sqrt().
Referenced by standardPhaseChange::correctModel().
TypeName()
TypeName ("standardPhaseChange")
Runtime type information.
correctModel()
void correctModel (const scalar dt, scalarField & availableMass, scalarField & dMass, scalarField & dEnergy) virtual
Correct.
Implements phaseChangeModel.
Definition at line 93 of file standardPhaseChange.C.
References filmThermoModel::Cp(), filmThermoModel::D(), delta, kinematicSingleLayer::delta(), standardPhaseChange::deltaMin_, kinematicSingleLayer::filmThermo(), forAll, filmThermoModel::hl(), standardPhaseChange::L_, Foam::mag(), singleLayerRegion::magSf(), Foam::max(), Foam::min(), kinematicSingleLayer::muPrimary(), filmThermoModel::name(), kinematicSingleLayer::pPrimary(), pSat, filmThermoModel::pv(), rho, kinematicSingleLayer::rho(), kinematicSingleLayer::rhoPrimary(), standardPhaseChange::Sh(), Foam::T(), thermoSingleLayer::T(), filmThermoModel::Tb(), standardPhaseChange::TbFactor_, thermoSingleLayer::thermo(), kinematicSingleLayer::UPrimary(), kinematicSingleLayer::Us(), filmThermoModel::W(), and thermoSingleLayer::YPrimary().
Referenced by standardPhaseChange::~standardPhaseChange().
Member Data Documentation
deltaMin_
const scalar deltaMin_ protected
Minimum film height for model to be active.
Definition at line 72 of file standardPhaseChange.H.
Referenced by standardPhaseChange::correctModel().
L_
const scalar L_ protected
Length scale / [m].
Definition at line 75 of file standardPhaseChange.H.
Referenced by standardPhaseChange::correctModel().
TbFactor_
const scalar TbFactor_ protected
Boiling temperature factor / [].
Used to set max limit on temperature to Tb*TbFactor
Definition at line 79 of file standardPhaseChange.H.
Referenced by standardPhaseChange::correctModel().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/phaseChangeModel/standardPhaseChange/standardPhaseChange.H
src/regionModels/surfaceFilmModels/submodels/thermo/phaseChangeModel/standardPhaseChange/standardPhaseChange.C