OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
thermalBaffleModel Class Reference abstract
Public Member Functions
TypeName ("thermalBaffleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermalBaffleModel, mesh,(const word &modelType, const fvMesh &mesh),(modelType, mesh))
declareRunTimeSelectionTable (autoPtr, thermalBaffleModel, dictionary,(const word &modelType, const fvMesh &mesh, const dictionary &dict),(modelType, mesh, dict))
thermalBaffleModel (const fvMesh &mesh)
Construct null from mesh.
thermalBaffleModel (const word &modelType, const fvMesh &mesh)
Construct from type name and mesh.
thermalBaffleModel (const word &modelType, const fvMesh &mesh, const dictionary &dict)
Construct from type name and mesh and dict.
virtual ~thermalBaffleModel ()
Destructor.
virtual const solidThermo & thermo () const =0
Return solid thermo.
const scalarField & thickness () const
Return thickness.
const dimensionedScalar & delta () const
Return geometrical thickness.
bool oneD () const
Return if region is one dimensional.
bool constantThickness () const
Return if region has constant thickness.
virtual const volScalarField & rho () const =0
Return density [kg/m3].
virtual const volScalarField & T () const =0
Return const temperature [K].
virtual const tmp< volScalarField > Cp () const =0
Return specific heat capacity [J/kg/K].
virtual const volScalarField & kappaRad () const =0
Return the region absorptivity [1/m].
virtual const volScalarField & kappa () const =0
Return the region thermal conductivity [W/m/k].
virtual void preEvolveRegion ()
Pre-evolve region.
Public Member Functions inherited from regionModel1D
TypeName ("regionModel1D")
Runtime type information.
regionModel1D (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel1D (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel1D (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh, region type and name and dict.
virtual ~regionModel1D ()
Destructor.
const labelListList & boundaryFaceFaces () const
Return the global face IDs.
const labelListList & boundaryFaceCells () const
Return the global cell IDs.
const labelList & boundaryFaceOppositeFace () const
Return the global boundary face IDs oppossite coupled patch.
const surfaceScalarField & nMagSf () const
Return the face area magnitudes / [m2].
label nLayers () const
Return the number of layers in the region.
Public Member Functions inherited from regionModel
TypeName ("regionModel")
Runtime type information.
regionModel (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh and name and dict.
virtual ~regionModel ()
Destructor.
const fvMesh & primaryMesh () const
Return the reference to the primary mesh database.
const Time & time () const
Return the reference to the time database.
const Switch & active () const
Return the active flag.
const Switch & infoOutput () const
Return the information flag.
const word & modelName () const
Return the model name.
const fvMesh & regionMesh () const
Return the region mesh database.
fvMesh & regionMesh ()
Return the region mesh database for manipulation.
const dictionary & coeffs () const
Return the model coefficients dictionary.
const dictionary & solution () const
Return the solution dictionary.
const IOdictionary & outputProperties () const
Return const access to the output properties dictionary.
IOdictionary & outputProperties ()
Return output properties dictionary.
bool isCoupledPatch (const label regionPatchI) const
Return true if patchI on the local region is a coupled.
bool isRegionPatch (const label primaryPatchI) const
Return true if patchI on the primary region is a coupled.
const labelList & primaryPatchIDs () const
Return the list of patch IDs on the primary region coupled.
const labelList & intCoupledPatchIDs () const
Return the list of patch IDs internally coupled with the.
label regionPatchID (const label primaryPatchID) const
Return region ID corresponding to primaryPatchID.
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchI) const
Return the coupled patch ID paired with coupled patch.
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch internal field from another region model to local.
template<class Type >
void toPrimary (const label regionPatchI, List< Type > &regionField) const
Convert a local region field to the primary region.
template<class Type >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField) const
Convert a primary region field to the local region.
template<class Type , class CombineOp >
void toPrimary (const label regionPatchI, List< Type > &regionField, const CombineOp &cop) const
Convert a local region field to the primary region with op.
template<class Type , class CombineOp >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField, const CombineOp &cop) const
Convert a primary region field to the local region with op.
virtual void evolve ()
Main driver routing to evolve the region - calls other evolves.
virtual void evolveRegion ()
Evolve the region.
virtual void postEvolveRegion ()
Post-evolve region.
virtual void info ()
Provide some feedback.
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Static Public Member Functions
static autoPtr< thermalBaffleModel > New (const fvMesh &mesh)
Return a reference to the selected model.
static autoPtr< thermalBaffleModel > New (const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected model using dictionary.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Protected Member Functions
virtual bool read ()
Read control parameters from IO dictionary.
virtual bool read (const dictionary &)
Read control parameters from dictionary.
Protected Member Functions inherited from regionModel1D
tmp< labelField > moveMesh (const scalarList &deltaV, const scalar minDelta=0.0)
Move mesh points according to change in cell volumes.
Protected Member Functions inherited from regionModel
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const bool flip) const
Create or return a new inter-region AMI object.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
scalarField thickness_
Baffle physical thickness.
dimensionedScalar delta_
Baffle mesh thickness.
bool oneD_
Is it one dimension.
bool constantThickness_
Is thickness constant.
Protected Attributes inherited from regionModel1D
labelListList boundaryFaceFaces_
Global face IDs.
labelListList boundaryFaceCells_
Global cell IDs.
labelList boundaryFaceOppositeFace_
Global boundary face IDs oppossite coupled patch.
label nLayers_
Number of layers in the region.
autoPtr< surfaceScalarField > nMagSfPtr_
Face area magnitude normal to patch.
Switch moveMesh_
Flag to allow mesh movement.
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
Reference to the primary mesh database.
const Time & time_
Reference to the time database.
Switch active_
Active flag.
Switch infoOutput_
Active information output.
const word modelName_
Model name.
autoPtr< fvMesh > regionMeshPtr_
Pointer to the region mesh database.
dictionary coeffs_
Model coefficients dictionary.
autoPtr< IOdictionary > outputPropertiesPtr_
Dictionary of output properties.
labelList primaryPatchIDs_
List of patch IDs on the primary region coupled to this region.
labelList intCoupledPatchIDs_
List of patch IDs internally coupled with the primary region.
word regionName_
Region name.
regionModelFunctionObjectList functions_
Region model function objects.
wordList interRegionAMINames_
List of region names this region is coupled to.
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
List of AMI objects per coupled region.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase ::iterator LListBase_iterator
typedef DLListBase ::const_iterator LListBase_const_iterator
typedef DLListBase ::const_reverse_iterator LListBase_const_reverse_iterator
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Definition at line 58 of file thermalBaffleModel.H.
Constructor & Destructor Documentation
thermalBaffleModel() [1/3]
thermalBaffleModel (const fvMesh & mesh)
Construct null from mesh.
Definition at line 202 of file thermalBaffleModel.C.
thermalBaffleModel() [2/3]
thermalBaffleModel (const word & modelType, const fvMesh & mesh)
Construct from type name and mesh.
Definition at line 231 of file thermalBaffleModel.C.
thermalBaffleModel() [3/3]
thermalBaffleModel (const word & modelType, const fvMesh & mesh, const dictionary & dict)
Construct from type name and mesh and dict.
Definition at line 213 of file thermalBaffleModel.C.
~thermalBaffleModel()
~thermalBaffleModel () virtual
Destructor.
Definition at line 248 of file thermalBaffleModel.C.
Member Function Documentation
read() [1/2]
bool read () protected virtual
Read control parameters from IO dictionary.
Reimplemented from regionModel1D.
Reimplemented in thermalBaffle, and noThermo.
Definition at line 49 of file thermalBaffleModel.C.
References regionModel1D::read().
read() [2/2]
bool read (const dictionary & dict) protected virtual
Read control parameters from dictionary.
Reimplemented from regionModel1D.
Reimplemented in thermalBaffle.
Definition at line 56 of file thermalBaffleModel.C.
References regionModel::active_, regionModel1D::boundaryFaceOppositeFace_, polyMesh::boundaryMesh(), thermalBaffleModel::constantThickness_, thermalBaffleModel::delta_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, Foam::Info, regionModel::intCoupledPatchIDs_, Foam::mag(), patchIdentifier::name(), Foam::nl, regionModel1D::nLayers_, thermalBaffleModel::oneD_, patchi, regionModel1D::read(), Foam::reduce(), Foam::refCast(), regionModel::regionMesh(), DLListBase::size(), PtrList< T >::size(), polyPatch::start(), mappedVariableThicknessWallPolyPatch::thickness(), thermalBaffleModel::thickness_, and dimensioned< Type >::value().
TypeName()
TypeName ("thermalBaffleModel")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , thermalBaffleModel , mesh , (const word &modelType, const fvMesh &mesh) , (modelType, mesh))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , thermalBaffleModel , dictionary , (const word &modelType, const fvMesh &mesh, const dictionary &dict) , (modelType, mesh, dict))
New() [1/2]
autoPtr< thermalBaffleModel > New (const fvMesh & mesh) static
Return a reference to the selected model.
Definition at line 39 of file thermalBaffleModelNew.C.
References TimePaths::constant(), Foam::exit(), Foam::FatalError, FatalErrorIn, dictionary::lookupOrDefault(), mesh, IOobject::MUST_READ_IF_MODIFIED, Foam::nl, IOobject::NO_WRITE, and fvMesh::time().
New() [2/2]
autoPtr< thermalBaffleModel > New (const fvMesh & mesh, const dictionary & dict) static
Return a reference to the selected model using dictionary.
Definition at line 83 of file thermalBaffleModelNew.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorIn, dictionary::lookupOrDefault(), mesh, and Foam::nl.
thermo()
virtual const solidThermo& thermo () const pure virtual
Return solid thermo.
Implemented in thermalBaffle, and noThermo.
thickness()
const scalarField& thickness () const inline
Return thickness.
Definition at line 178 of file thermalBaffleModel.H.
References thermalBaffleModel::thickness_.
delta()
const dimensionedScalar& delta () const inline
Return geometrical thickness.
Definition at line 184 of file thermalBaffleModel.H.
References thermalBaffleModel::delta_.
oneD()
bool oneD () const inline
Return if region is one dimensional.
Definition at line 190 of file thermalBaffleModel.H.
References thermalBaffleModel::oneD_.
constantThickness()
bool constantThickness () const inline
Return if region has constant thickness.
Definition at line 196 of file thermalBaffleModel.H.
References thermalBaffleModel::constantThickness_, thermalBaffleModel::Cp(), thermalBaffleModel::kappa(), thermalBaffleModel::kappaRad(), thermalBaffleModel::preEvolveRegion(), thermalBaffleModel::rho(), and thermalBaffleModel::T().
rho()
virtual const volScalarField& rho () const pure virtual
Return density [kg/m3].
Implemented in thermalBaffle, and noThermo.
Referenced by thermalBaffleModel::constantThickness().
T()
virtual const volScalarField& T () const pure virtual
Return const temperature [K].
Implemented in thermalBaffle, and noThermo.
Referenced by thermalBaffleModel::constantThickness().
Cp()
virtual const tmp<volScalarField> Cp () const pure virtual
Return specific heat capacity [J/kg/K].
Implemented in thermalBaffle, and noThermo.
Referenced by thermalBaffleModel::constantThickness().
kappaRad()
virtual const volScalarField& kappaRad () const pure virtual
Return the region absorptivity [1/m].
Implemented in thermalBaffle, and noThermo.
Referenced by thermalBaffleModel::constantThickness().
kappa()
virtual const volScalarField& kappa () const pure virtual
Return the region thermal conductivity [W/m/k].
Implemented in thermalBaffle, and noThermo.
Referenced by thermalBaffleModel::constantThickness().
preEvolveRegion()
void preEvolveRegion () virtual
Pre-evolve region.
Reimplemented from regionModel.
Reimplemented in thermalBaffle, and noThermo.
Definition at line 254 of file thermalBaffleModel.C.
Referenced by thermalBaffleModel::constantThickness().
Member Data Documentation
thickness_
scalarField thickness_ protected
Baffle physical thickness.
Definition at line 81 of file thermalBaffleModel.H.
Referenced by thermalBaffleModel::read(), thermalBaffle::solveEnergy(), thermalBaffleModel::thickness(), and thermalBaffle::~thermalBaffle().
delta_
dimensionedScalar delta_ protected
Baffle mesh thickness.
Definition at line 84 of file thermalBaffleModel.H.
Referenced by thermalBaffleModel::delta(), thermalBaffleModel::read(), and thermalBaffle::solveEnergy().
oneD_
bool oneD_ protected
Is it one dimension.
Definition at line 87 of file thermalBaffleModel.H.
Referenced by thermalBaffleModel::oneD(), thermalBaffleModel::read(), thermalBaffle::solveEnergy(), and thermalBaffle::~thermalBaffle().
constantThickness_
bool constantThickness_ protected
Is thickness constant.
Definition at line 90 of file thermalBaffleModel.H.
Referenced by thermalBaffleModel::constantThickness(), thermalBaffleModel::read(), thermalBaffle::solveEnergy(), and thermalBaffle::~thermalBaffle().
The documentation for this class was generated from the following files:
src/regionModels/thermalBaffleModels/thermalBaffleModel/thermalBaffleModel.H
src/regionModels/thermalBaffleModels/thermalBaffleModel/thermalBaffleModel.C
src/regionModels/thermalBaffleModels/thermalBaffleModel/thermalBaffleModelNew.C