OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meshToMeshMethod Class Reference abstract
Base class for mesh-to-mesh calculation methods.
Public Member Functions
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
Declare runtime constructor selection table.
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~meshToMeshMethod ()
Destructor.
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght)=0
Calculate addressing and weights.
const polyMesh & src () const
Return const access to the source mesh.
const polyMesh & tgt () const
Return const access to the target mesh.
scalar V () const
Return const access to the overlap volume.
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Static Public Member Functions
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Selector.
Protected Member Functions
labelList maskCells () const
Return src cell IDs for the overlap region.
virtual bool intersect (const label srcCellI, const label tgtCellI) const
Return the true if cells intersect.
virtual scalar interVol (const label srcCellI, const label tgtCellI) const
Return the intersection volume between two cells.
virtual void appendNbrCells (const label tgtCellI, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
Append target cell neihgbour cells to cellIDs list.
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
meshToMeshMethod (const meshToMeshMethod &)
Disallow default bitwise copy construct.
void operator= (const meshToMeshMethod &)
Disallow default bitwise assignment.
Protected Attributes
const polyMesh & src_
Reference to the source mesh.
const polyMesh & tgt_
Reference to the target mesh.
scalar V_
Cell total volume in overlap region [m3].
Static Protected Attributes
static scalar tolerance_ = 1e-6
Tolerance used in volume overlap calculations.
Detailed Description
Base class for mesh-to-mesh calculation methods.
Source files
meshToMeshMethod.H
meshToMeshMethod.C
Definition at line 48 of file meshToMeshMethod.H.
Constructor & Destructor Documentation
meshToMeshMethod() [1/2]
meshToMeshMethod (const meshToMeshMethod &) protected
Disallow default bitwise copy construct.
Referenced by meshToMeshMethod::initialise().
meshToMeshMethod() [2/2]
meshToMeshMethod (const polyMesh & src, const polyMesh & tgt)
Construct from source and target meshes.
Definition at line 186 of file meshToMeshMethod.C.
References Foam::endl(), and Foam::Pout.
~meshToMeshMethod()
~meshToMeshMethod () virtual
Destructor.
Definition at line 209 of file meshToMeshMethod.C.
References meshToMeshMethod::writeConnectivity().
Member Function Documentation
maskCells()
Foam::labelList maskCells () const protected
Return src cell IDs for the overlap region.
Definition at line 44 of file meshToMeshMethod.C.
References List< T >::append(), cells, Foam::endl(), forAll, boundBox::inflate(), meshToMeshMethod::intersect(), Foam::max(), Foam::min(), boundBox::overlaps(), points, Foam::Pout, and List< T >::size().
intersect()
bool intersect (const label srcCellI, const label tgtCellI) const protected virtual
Return the true if cells intersect.
Reimplemented in directMethod.
Definition at line 78 of file meshToMeshMethod.C.
References tetOverlapVolume::cellCellOverlapMinDecomp(), and meshToMeshMethod::interVol().
Referenced by meshToMeshMethod::maskCells().
interVol()
Foam::scalar interVol (const label srcCellI, const label tgtCellI) const protected virtual
Return the intersection volume between two cells.
Definition at line 102 of file meshToMeshMethod.C.
References meshToMeshMethod::appendNbrCells(), and tetOverlapVolume::cellCellOverlapVolumeMinDecomp().
Referenced by meshToMeshMethod::intersect().
appendNbrCells()
void appendNbrCells (const label tgtCellI, const polyMesh & mesh, const DynamicList< label > & visitedTgtCells, DynamicList< label > & nbrTgtCellIDs) const protected virtual
Append target cell neihgbour cells to cellIDs list.
Definition at line 125 of file meshToMeshMethod.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), primitiveMesh::cellCells(), Foam::findIndex(), forAll, and meshToMeshMethod::initialise().
Referenced by meshToMeshMethod::interVol().
initialise()
bool initialise (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) const protected virtual
Definition at line 152 of file meshToMeshMethod.C.
References Foam::endl(), meshToMeshMethod::meshToMeshMethod(), Foam::Pout, and List< T >::setSize().
Referenced by meshToMeshMethod::appendNbrCells().
operator=()
void operator= (const meshToMeshMethod &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , meshToMeshMethod , components , (const polyMesh &src, const polyMesh &tgt) , (src, tgt))
Declare runtime constructor selection table.
New()
Foam::autoPtr< Foam::meshToMeshMethod > New (const word & methodName, const polyMesh & src, const polyMesh & tgt) static
Selector.
Definition at line 31 of file meshToMeshMethodNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, and Foam::nl.
Referenced by NamedEnum< directionType, 3 >::names().
calculate()
virtual void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) pure virtual
Calculate addressing and weights.
Implemented in mapNearestMethod, directMethod, and cellVolumeWeightMethod.
Referenced by NamedEnum< directionType, 3 >::names().
src()
const Foam::polyMesh & src () const inline
Return const access to the source mesh.
Definition at line 26 of file meshToMeshMethodI.H.
References meshToMeshMethod::src_.
tgt()
const Foam::polyMesh & tgt () const inline
Return const access to the target mesh.
Definition at line 32 of file meshToMeshMethodI.H.
References meshToMeshMethod::tgt_.
V()
Foam::scalar V () const inline
Return const access to the overlap volume.
Definition at line 38 of file meshToMeshMethodI.H.
References meshToMeshMethod::V_.
Referenced by NamedEnum< directionType, 3 >::names().
writeConnectivity()
void writeConnectivity (const polyMesh & mesh1, const polyMesh & mesh2, const labelListList & mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Definition at line 216 of file meshToMeshMethod.C.
References Foam::constant::universal::c, primitiveMesh::cellCentres(), primitiveMesh::cells(), Foam::endl(), polyMesh::faces(), forAll, UPstream::myProcNo(), Foam::name(), IOobject::name(), primitiveMesh::nCells(), Foam::nl, p, UPstream::parRun(), cell::points(), polyMesh::points(), Foam::Pout, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by NamedEnum< directionType, 3 >::names(), and meshToMeshMethod::~meshToMeshMethod().
Member Data Documentation
src_
const polyMesh& src_ protected
Reference to the source mesh.
Definition at line 56 of file meshToMeshMethod.H.
Referenced by meshToMeshMethod::src().
tgt_
const polyMesh& tgt_ protected
Reference to the target mesh.
Definition at line 59 of file meshToMeshMethod.H.
Referenced by meshToMeshMethod::tgt().
V_
scalar V_ protected
Cell total volume in overlap region [m3].
Definition at line 62 of file meshToMeshMethod.H.
Referenced by meshToMeshMethod::V().
tolerance_
Foam::scalar tolerance_ = 1e-6 static protected
Tolerance used in volume overlap calculations.
Definition at line 65 of file meshToMeshMethod.H.
The documentation for this class was generated from the following files:
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethod.H
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethod.C
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethodI.H
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethodNew.C