OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
weightedFvPatchFieldMapper Class Reference
FieldMapper with weighted mapping.
Public Member Functions
weightedFvPatchFieldMapper (const labelListList &addressing, const scalarListList &weights)
Construct given addressing.
virtual ~weightedFvPatchFieldMapper ()
Destructor.
virtual label size () const
virtual bool direct () const
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual const labelUList & directAddressing () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
FieldMapper with weighted mapping.
Definition at line 45 of file weightedFvPatchFieldMapper.H.
Constructor & Destructor Documentation
weightedFvPatchFieldMapper()
weightedFvPatchFieldMapper (const labelListList & addressing, const scalarListList & weights) inline
Construct given addressing.
Definition at line 61 of file weightedFvPatchFieldMapper.H.
References forAll, and weightedFvPatchFieldMapper::size().
~weightedFvPatchFieldMapper()
virtual ~weightedFvPatchFieldMapper () inline virtual
Destructor.
Definition at line 80 of file weightedFvPatchFieldMapper.H.
Member Function Documentation
size()
virtual label size () const inline virtual
Implements FieldMapper.
Definition at line 86 of file weightedFvPatchFieldMapper.H.
References weightedFvPatchFieldMapper::addressing(), and List< T >::size().
Referenced by weightedFvPatchFieldMapper::weightedFvPatchFieldMapper().
direct()
virtual bool direct () const inline virtual
Implements FieldMapper.
Definition at line 91 of file weightedFvPatchFieldMapper.H.
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 96 of file weightedFvPatchFieldMapper.H.
addressing()
virtual const labelListList& addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 101 of file weightedFvPatchFieldMapper.H.
Referenced by weightedFvPatchFieldMapper::size().
weights()
virtual const scalarListList& weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 106 of file weightedFvPatchFieldMapper.H.
The documentation for this class was generated from the following file:
src/sampling/meshToMeshInterpolation/meshToMesh/weightedFvPatchFieldMapper.H