OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cuttingPlane Class Reference
Constructs plane through mesh.
Public Member Functions
cuttingPlane (const plane &, const primitiveMesh &, const bool triangulate, const labelUList &cellIdLabels=labelUList::null())
Construct from plane and mesh reference,.
const plane & planeDesc () const
Return plane used.
const labelList & cutCells () const
Return List of cells cut by the plane.
bool cut () const
Return true or false to question: have any cells been cut?
template<class Type >
tmp< Field< Type > > sample (const Field< Type > &) const
Sample the cell field.
template<class Type >
tmp< Field< Type > > sample (const tmp< Field< Type > > &) const
void operator= (const cuttingPlane &)
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const Field< Type > &fld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const tmp< Field< Type > > &tfld) const
Public Member Functions inherited from plane
plane (const vector &normalVector)
Construct from normal vector through the origin.
plane (const point &basePoint, const vector &normalVector)
Construct from normal vector and point in plane.
plane (const point &point1, const point &point2, const point &point3)
Construct from three points in plane.
plane (const scalarList &C)
Construct from coefficients for the.
plane (const dictionary &planeDict)
Construct from dictionary.
plane (Istream &is)
Construct from Istream. Assumes the base + normal notation.
const vector & normal () const
Return plane normal.
const point & refPoint () const
Return or return plane base point.
FixedList< scalar, 4 > planeCoeffs () const
Return coefficients for the.
point nearestPoint (const point &p) const
Return nearest point in the plane for the given point.
scalar distance (const point &p) const
Return distance from the given point to the plane.
scalar normalIntersect (const point &pnt0, const vector &dir) const
Return cut coefficient for plane and line defined by.
scalar normalIntersect (const ray &r) const
Return cut coefficient for plane and ray.
template<class Point , class PointRef >
scalar lineIntersect (const line< Point, PointRef > &l) const
Return the cutting point between the plane and.
ray planeIntersect (const plane &) const
Return the cutting line between this plane and another.
point planePlaneIntersect (const plane &, const plane &) const
Return the cutting point between this plane and two other planes.
side sideOfPlane (const point &p) const
Return the side of the plane that the point is on.
point mirror (const point &p) const
Mirror the supplied point in the plane. Return the mirrored point.
void writeDict (Ostream &) const
Write to dictionary.
Public Member Functions inherited from MeshedSurface< face >
MeshedSurface ()
Construct null.
MeshedSurface (const Xfer< pointField > &, const Xfer< List< face > > &, const Xfer< surfZoneList > &)
Construct by transferring components (points, faces, zones).
MeshedSurface (const Xfer< pointField > &, const Xfer< List< face > > &, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Construct by transferring components (points, faces).
MeshedSurface (const MeshedSurface &)
Construct as copy.
MeshedSurface (const UnsortedMeshedSurface< face > &)
Construct from a UnsortedMeshedSurface.
MeshedSurface (const polyBoundaryMesh &, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &)
Construct from a surfMesh.
MeshedSurface (const Xfer< UnsortedMeshedSurface< face > > &)
Construct by transferring the contents from a UnsortedMeshedSurface.
MeshedSurface (const Xfer< MeshedSurface< face > > &)
Construct by transferring the contents from a MeshedSurface.
MeshedSurface (const fileName &)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (const Time &, const word &surfName="")
Construct from database.
MeshedSurface (const MeshedSurface< face > &surf)
ClassName ("MeshedSurface")
Runtime type information.
bool isTri ()
Specialization for holding triangulated information.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< face > &surf),(name, surf))
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void write (const Time &, const word &surfName="") const
Write to database.
label size () const
The surface size is the number of faces.
const List< face > & faces () const
Return const access to the faces.
const List< surfZone > & surfZones () const
Const access to the surface zones.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
virtual void removeZones ()
Remove surface zones.
virtual void clear ()
Clear all storage.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
virtual void reset (const Xfer< pointField > &points, const Xfer< List< face > > &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void reset (const Xfer< List< point > > &points, const Xfer< List< face > > &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
label triangulate ()
Specialization for holding triangulated information.
label triangulate (List< label > &faceMap)
Specialization for holding triangulated information.
MeshedSurface subsetMesh (const labelHashSet &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void transfer (MeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
Xfer< MeshedSurface< face > > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
void writeStats (Ostream &os) const
void operator= (const MeshedSurface< face > &)
operator MeshedSurfaceProxy< face > () const
Conversion operator to MeshedSurfaceProxy.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face > > &faces, const Xfer< List< PointType > > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reUse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Protected Member Functions
cuttingPlane (const plane &)
Construct plane description without cutting.
void reCut (const primitiveMesh &, const bool triangulate, const labelUList &cellIdLabels=labelUList::null())
recut mesh with existing planeDesc, restricted to a list of cells
virtual void remapFaces (const labelUList &faceMap)
remap action on triangulation or cleanup
Protected Member Functions inherited from MeshedSurface< face >
void transcribe (MeshedSurface< face > &)
Transfer points/zones and transcribe face -> triFace.
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void checkZones ()
basic sanity check on zones
pointField & storedPoints ()
Non-const access to global points.
List< face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (const Xfer< List< face > > &unsortedFaces, const Xfer< List< label > > &zoneIds, const bool sorted)
sort faces by zones and store sorted faces
Additional Inherited Members
Public Types inherited from plane
enum side { NORMAL, FLIP }
Side of the plane.
Public Types inherited from MeshedSurface< face >
typedef face FaceType
Face type used.
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from MeshedSurface< face >
static bool isTri ()
Face storage only handles triangulated faces.
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< MeshedSurface > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const MeshedSurface< face > &)
Write to file.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Constructs plane through mesh.
No attempt at resolving degenerate cases. Since the cut faces are usually quite ugly, they will always be triangulated.
Note
When the cutting plane coincides with a mesh face, the cell edge on the positive side of the plane is taken.
Source files
cuttingPlane.H
cuttingPlane.C
Definition at line 60 of file cuttingPlane.H.
Constructor & Destructor Documentation
cuttingPlane() [1/2]
cuttingPlane (const plane & pln) protected
Construct plane description without cutting.
Definition at line 346 of file cuttingPlane.C.
cuttingPlane() [2/2]
cuttingPlane (const plane & pln, const primitiveMesh & mesh, const bool triangulate, const labelUList & cellIdLabels = labelUList::null())
Construct from plane and mesh reference,.
possibly restricted to a list of cells
Definition at line 354 of file cuttingPlane.C.
References cuttingPlane::reCut().
Member Function Documentation
reCut()
void reCut (const primitiveMesh & mesh, const bool triangulate, const labelUList & cellIdLabels = labelUList::null()) protected
recut mesh with existing planeDesc, restricted to a list of cells
Definition at line 372 of file cuttingPlane.C.
References List< T >::clear(), MeshedSurface< face >::clear(), plane::normal(), primitiveMesh::points(), plane::refPoint(), and cuttingPlane::remapFaces().
Referenced by cuttingPlane::cuttingPlane().
remapFaces()
void remapFaces (const labelUList & faceMap) protected virtual
remap action on triangulation or cleanup
Reimplemented from MeshedSurface< face >.
Definition at line 398 of file cuttingPlane.C.
References forAll, MeshedSurface< face >::remapFaces(), UList< T >::size(), and List< T >::transfer().
Referenced by cuttingPlane::reCut().
planeDesc()
const plane& planeDesc () const inline
Return plane used.
Definition at line 152 of file cuttingPlane.H.
cutCells()
const labelList& cutCells () const inline
Return List of cells cut by the plane.
Definition at line 158 of file cuttingPlane.H.
Referenced by sampledPlane::meshCells(), and cuttingPlane::operator=().
cut()
bool cut () const inline
Return true or false to question: have any cells been cut?
Definition at line 164 of file cuttingPlane.H.
References cuttingPlane::operator=(), cuttingPlane::sample(), and List< T >::size().
sample() [1/4]
tmp<Field<Type> > sample (const Field< Type > &) const
Sample the cell field.
Referenced by cuttingPlane::cut(), and cuttingPlane::sample().
sample() [2/4]
tmp<Field<Type> > sample (const tmp< Field< Type > > &) const
operator=()
void operator= (const cuttingPlane & rhs)
Definition at line 418 of file cuttingPlane.C.
References Foam::abort(), cuttingPlane::cutCells(), Foam::FatalError, and FatalErrorIn.
Referenced by cuttingPlane::cut().
sample() [3/4]
Foam::tmp<Foam::Field<Type> > sample (const Field< Type > & fld) const
Definition at line 37 of file cuttingPlaneTemplates.C.
References fld(), and cuttingPlane::sample().
sample() [4/4]
Foam::tmp<Foam::Field<Type> > sample (const tmp< Field< Type > > & tfld) const
Definition at line 47 of file cuttingPlaneTemplates.C.
The documentation for this class was generated from the following files:
src/sampling/cuttingPlane/cuttingPlane.H
src/sampling/cuttingPlane/cuttingPlane.C
src/sampling/cuttingPlane/cuttingPlaneTemplates.C