OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellVolumeWeightMethod Class Reference
Cell-volume-weighted mesh-to-mesh interpolation class.
Public Member Functions
TypeName ("cellVolumeWeight")
Run-time type information.
cellVolumeWeightMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~cellVolumeWeightMethod ()
Destructor.
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght)
Calculate addressing and weights.
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
Declare runtime constructor selection table.
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~meshToMeshMethod ()
Destructor.
const polyMesh & src () const
Return const access to the source mesh.
const polyMesh & tgt () const
Return const access to the target mesh.
scalar V () const
Return const access to the overlap volume.
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Protected Member Functions
bool findInitialSeeds (const labelList &srcCellIDs, const boolList &mapFlag, const label startSeedI, label &srcSeedI, label &tgtSeedI) const
Find indices of overlapping cells in src and tgt meshes - returns.
void calculateAddressing (labelListList &srcToTgtCellAddr, scalarListList &srcToTgtCellWght, labelListList &tgtToSrcCellAddr, scalarListList &tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList &srcCellIDs, boolList &mapFlag, label &startSeedI)
Calculate the mesh-to-mesh addressing and weights.
void setNextCells (label &startSeedI, label &srcCellI, label &tgtCellI, const labelList &srcCellIDs, const boolList &mapFlag, const DynamicList< label > &visitedCells, labelList &seedCells) const
Set the next cells in the advancing front algorithm.
cellVolumeWeightMethod (const cellVolumeWeightMethod &)
Disallow default bitwise copy construct.
void operator= (const cellVolumeWeightMethod &)
Disallow default bitwise assignment.
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
Return src cell IDs for the overlap region.
virtual bool intersect (const label srcCellI, const label tgtCellI) const
Return the true if cells intersect.
virtual scalar interVol (const label srcCellI, const label tgtCellI) const
Return the intersection volume between two cells.
virtual void appendNbrCells (const label tgtCellI, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
Append target cell neihgbour cells to cellIDs list.
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
meshToMeshMethod (const meshToMeshMethod &)
Disallow default bitwise copy construct.
void operator= (const meshToMeshMethod &)
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Selector.
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
Reference to the source mesh.
const polyMesh & tgt_
Reference to the target mesh.
scalar V_
Cell total volume in overlap region [m3].
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Tolerance used in volume overlap calculations.
Detailed Description
Cell-volume-weighted mesh-to-mesh interpolation class.
Volume conservative.
Source files
cellVolumeWeightMethod.H
cellVolumeWeightMethod.C
Definition at line 50 of file cellVolumeWeightMethod.H.
Constructor & Destructor Documentation
cellVolumeWeightMethod() [1/2]
cellVolumeWeightMethod (const cellVolumeWeightMethod &) protected
Disallow default bitwise copy construct.
Referenced by cellVolumeWeightMethod::setNextCells().
cellVolumeWeightMethod() [2/2]
cellVolumeWeightMethod (const polyMesh & src, const polyMesh & tgt)
Construct from source and target meshes.
Definition at line 297 of file cellVolumeWeightMethod.C.
~cellVolumeWeightMethod()
~cellVolumeWeightMethod () virtual
Destructor.
Definition at line 308 of file cellVolumeWeightMethod.C.
References cellVolumeWeightMethod::calculate().
Member Function Documentation
findInitialSeeds()
bool findInitialSeeds (const labelList & srcCellIDs, const boolList & mapFlag, const label startSeedI, label & srcSeedI, label & tgtSeedI) const protected
Find indices of overlapping cells in src and tgt meshes - returns.
true if found a matching pair
Definition at line 47 of file cellVolumeWeightMethod.C.
References cellVolumeWeightMethod::calculateAddressing(), Foam::endl(), forAll, points, Foam::Pout, and List< T >::size().
calculateAddressing()
void calculateAddressing (labelListList & srcToTgtCellAddr, scalarListList & srcToTgtCellWght, labelListList & tgtToSrcCellAddr, scalarListList & tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList & srcCellIDs, boolList & mapFlag, label & startSeedI) protected
Calculate the mesh-to-mesh addressing and weights.
Definition at line 94 of file cellVolumeWeightMethod.C.
References List< T >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), List< T >::clear(), UList< T >::empty(), forAll, cellVolumeWeightMethod::setNextCells(), and List< T >::transfer().
Referenced by cellVolumeWeightMethod::findInitialSeeds().
setNextCells()
void setNextCells (label & startSeedI, label & srcCellI, label & tgtCellI, const labelList & srcCellIDs, const boolList & mapFlag, const DynamicList< label > & visitedCells, labelList & seedCells) const protected
Set the next cells in the advancing front algorithm.
Definition at line 193 of file cellVolumeWeightMethod.C.
References cellVolumeWeightMethod::cellVolumeWeightMethod(), Foam::endl(), forAll, Foam::Pout, and List< T >::size().
Referenced by cellVolumeWeightMethod::calculateAddressing().
operator=()
void operator= (const cellVolumeWeightMethod &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("cellVolumeWeight")
Run-time type information.
calculate()
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) virtual
Calculate addressing and weights.
Implements meshToMeshMethod.
Definition at line 315 of file cellVolumeWeightMethod.C.
Referenced by cellVolumeWeightMethod::~cellVolumeWeightMethod().
The documentation for this class was generated from the following files:
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/cellVolumeWeight/cellVolumeWeightMethod.H
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/cellVolumeWeight/cellVolumeWeightMethod.C