OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapNearestMethod Class Reference
Map nearest mesh-to-mesh interpolation class.
Public Member Functions
TypeName ("mapNearest")
Run-time type information.
mapNearestMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~mapNearestMethod ()
Destructor.
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght)
Calculate addressing and weights.
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
Declare runtime constructor selection table.
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~meshToMeshMethod ()
Destructor.
const polyMesh & src () const
Return const access to the source mesh.
const polyMesh & tgt () const
Return const access to the target mesh.
scalar V () const
Return const access to the overlap volume.
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Protected Member Functions
virtual bool findInitialSeeds (const labelList &srcCellIDs, const boolList &mapFlag, const label startSeedI, label &srcSeedI, label &tgtSeedI) const
Find indices of overlapping cells in src and tgt meshes - returns.
virtual void calculateAddressing (labelListList &srcToTgtCellAddr, scalarListList &srcToTgtCellWght, labelListList &tgtToSrcCellAddr, scalarListList &tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList &srcCellIDs, boolList &mapFlag, label &startSeedI)
Calculate the mesh-to-mesh addressing and weights.
virtual void findNearestCell (const polyMesh &mesh1, const polyMesh &mesh2, const label cell1, label &cell2) const
Find the nearest cell on mesh2 for cell1 on mesh1.
virtual void setNextNearestCells (label &startSeedI, label &srcCellI, label &tgtCellI, boolList &mapFlag, const labelList &srcCellIDs) const
Set the next cells for the marching front algorithm.
virtual label findMappedSrcCell (const label tgtCellI, const List< DynamicList< label > > &tgtToSrc) const
Find a source cell mapped to target cell tgtCellI.
mapNearestMethod (const mapNearestMethod &)
Disallow default bitwise copy construct.
void operator= (const mapNearestMethod &)
Disallow default bitwise assignment.
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
Return src cell IDs for the overlap region.
virtual bool intersect (const label srcCellI, const label tgtCellI) const
Return the true if cells intersect.
virtual scalar interVol (const label srcCellI, const label tgtCellI) const
Return the intersection volume between two cells.
virtual void appendNbrCells (const label tgtCellI, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
Append target cell neihgbour cells to cellIDs list.
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
meshToMeshMethod (const meshToMeshMethod &)
Disallow default bitwise copy construct.
void operator= (const meshToMeshMethod &)
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Selector.
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
Reference to the source mesh.
const polyMesh & tgt_
Reference to the target mesh.
scalar V_
Cell total volume in overlap region [m3].
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Tolerance used in volume overlap calculations.
Detailed Description
Map nearest mesh-to-mesh interpolation class.
Not volume conservative.
cells outside other meshes bounding box do not get mapped (initial filtering)
all remaining cells will be mapped (with weight 1!)
so take care when mapping meshes with different bounding boxes!
Source files
mapNearestMethod.H
mapNearestMethod.C
Definition at line 54 of file mapNearestMethod.H.
Constructor & Destructor Documentation
mapNearestMethod() [1/2]
mapNearestMethod (const mapNearestMethod &) protected
Disallow default bitwise copy construct.
Referenced by mapNearestMethod::findMappedSrcCell().
mapNearestMethod() [2/2]
mapNearestMethod (const polyMesh & src, const polyMesh & tgt)
Construct from source and target meshes.
Definition at line 341 of file mapNearestMethod.C.
~mapNearestMethod()
~mapNearestMethod () virtual
Destructor.
Definition at line 352 of file mapNearestMethod.C.
References mapNearestMethod::calculate().
Member Function Documentation
findInitialSeeds()
bool findInitialSeeds (const labelList & srcCellIDs, const boolList & mapFlag, const label startSeedI, label & srcSeedI, label & tgtSeedI) const protected virtual
Find indices of overlapping cells in src and tgt meshes - returns.
true if found a matching pair
Definition at line 43 of file mapNearestMethod.C.
References Foam::abort(), mapNearestMethod::calculateAddressing(), Foam::endl(), Foam::FatalError, FatalErrorIn, PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), Foam::Pout, and List< T >::size().
calculateAddressing()
void calculateAddressing (labelListList & srcToTgtCellAddr, scalarListList & srcToTgtCellWght, labelListList & tgtToSrcCellAddr, scalarListList & tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList & srcCellIDs, boolList & mapFlag, label & startSeedI) protected virtual
Calculate the mesh-to-mesh addressing and weights.
Definition at line 103 of file mapNearestMethod.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), d(), mapNearestMethod::findNearestCell(), forAll, Foam::magSqr(), List< T >::size(), and List< T >::transfer().
Referenced by mapNearestMethod::findInitialSeeds().
findNearestCell()
void findNearestCell (const polyMesh & mesh1, const polyMesh & mesh2, const label cell1, label & cell2) const protected virtual
Find the nearest cell on mesh2 for cell1 on mesh1.
Definition at line 215 of file mapNearestMethod.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::constant::physicoChemical::c2, primitiveMesh::cellCentres(), d(), Foam::magSqr(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), mapNearestMethod::setNextNearestCells(), and List< T >::size().
Referenced by mapNearestMethod::calculateAddressing().
setNextNearestCells()
void setNextNearestCells (label & startSeedI, label & srcCellI, label & tgtCellI, boolList & mapFlag, const labelList & srcCellIDs) const protected virtual
Set the next cells for the marching front algorithm.
Definition at line 252 of file mapNearestMethod.C.
References mapNearestMethod::findMappedSrcCell(), forAll, and List< T >::size().
Referenced by mapNearestMethod::findNearestCell().
findMappedSrcCell()
Foam::label findMappedSrcCell (const label tgtCellI, const List< DynamicList< label > > & tgtToSrc) const protected virtual
Find a source cell mapped to target cell tgtCellI.
Definition at line 295 of file mapNearestMethod.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::findIndex(), forAll, mapNearestMethod::mapNearestMethod(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), and List< T >::size().
Referenced by mapNearestMethod::setNextNearestCells().
operator=()
void operator= (const mapNearestMethod &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("mapNearest")
Run-time type information.
calculate()
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) virtual
Calculate addressing and weights.
Implements meshToMeshMethod.
Definition at line 359 of file mapNearestMethod.C.
Referenced by mapNearestMethod::~mapNearestMethod().
The documentation for this class was generated from the following files:
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/mapNearest/mapNearestMethod.H
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/mapNearest/mapNearestMethod.C