OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
directMethod Class Reference
Direct (one-to-one cell correspondence) mesh-to-mesh interpolation class.
Public Member Functions
TypeName ("direct")
Run-time type information.
directMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~directMethod ()
Destructor.
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght)
Calculate addressing and weights.
Public Member Functions inherited from meshToMeshMethod
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
Declare runtime constructor selection table.
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~meshToMeshMethod ()
Destructor.
const polyMesh & src () const
Return const access to the source mesh.
const polyMesh & tgt () const
Return const access to the target mesh.
scalar V () const
Return const access to the overlap volume.
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Protected Member Functions
virtual bool intersect (const label srcCellI, const label tgtCellI) const
Return the true if cells intersect.
virtual bool findInitialSeeds (const labelList &srcCellIDs, const boolList &mapFlag, const label startSeedI, label &srcSeedI, label &tgtSeedI) const
Find indices of overlapping cells in src and tgt meshes - returns.
virtual void calculateAddressing (labelListList &srcToTgtCellAddr, scalarListList &srcToTgtCellWght, labelListList &tgtToSrcCellAddr, scalarListList &tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList &srcCellIDs, boolList &mapFlag, label &startSeedI)
Calculate the mesh-to-mesh addressing and weights.
virtual void appendToDirectSeeds (boolList &mapFlag, labelList &srcTgtSeed, DynamicList< label > &srcSeeds, label &srcSeedI, label &tgtSeedI) const
Append to list of src mesh seed indices.
directMethod (const directMethod &)
Disallow default bitwise copy construct.
void operator= (const directMethod &)
Disallow default bitwise assignment.
Protected Member Functions inherited from meshToMeshMethod
labelList maskCells () const
Return src cell IDs for the overlap region.
virtual scalar interVol (const label srcCellI, const label tgtCellI) const
Return the intersection volume between two cells.
virtual void appendNbrCells (const label tgtCellI, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
Append target cell neihgbour cells to cellIDs list.
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
meshToMeshMethod (const meshToMeshMethod &)
Disallow default bitwise copy construct.
void operator= (const meshToMeshMethod &)
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from meshToMeshMethod
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Selector.
Protected Attributes inherited from meshToMeshMethod
const polyMesh & src_
Reference to the source mesh.
const polyMesh & tgt_
Reference to the target mesh.
scalar V_
Cell total volume in overlap region [m3].
Static Protected Attributes inherited from meshToMeshMethod
static scalar tolerance_ = 1e-6
Tolerance used in volume overlap calculations.
Detailed Description
Direct (one-to-one cell correspondence) mesh-to-mesh interpolation class.
Volume conservative.
Source files
directMethod.H
directMethod.C
Definition at line 50 of file directMethod.H.
Constructor & Destructor Documentation
directMethod() [1/2]
directMethod (const directMethod &) protected
Disallow default bitwise copy construct.
Referenced by directMethod::appendToDirectSeeds().
directMethod() [2/2]
directMethod (const polyMesh & src, const polyMesh & tgt)
Construct from source and target meshes.
Definition at line 240 of file directMethod.C.
~directMethod()
~directMethod () virtual
Destructor.
Definition at line 251 of file directMethod.C.
References directMethod::calculate().
Member Function Documentation
intersect()
bool intersect (const label srcCellI, const label tgtCellI) const protected virtual
Return the true if cells intersect.
Reimplemented from meshToMeshMethod.
Definition at line 42 of file directMethod.C.
References polyMesh::FACEPLANES, and directMethod::findInitialSeeds().
findInitialSeeds()
bool findInitialSeeds (const labelList & srcCellIDs, const boolList & mapFlag, const label startSeedI, label & srcSeedI, label & tgtSeedI) const protected virtual
Find indices of overlapping cells in src and tgt meshes - returns.
true if found a matching pair
Definition at line 57 of file directMethod.C.
References directMethod::calculateAddressing(), Foam::endl(), forAll, points, Foam::Pout, and List< T >::size().
Referenced by directMethod::intersect().
calculateAddressing()
void calculateAddressing (labelListList & srcToTgtCellAddr, scalarListList & srcToTgtCellWght, labelListList & tgtToSrcCellAddr, scalarListList & tgtToSrcCellWght, const label srcSeedI, const label tgtSeedI, const labelList & srcCellIDs, boolList & mapFlag, label & startSeedI) protected virtual
Calculate the mesh-to-mesh addressing and weights.
Definition at line 104 of file directMethod.C.
References List< T >::append(), directMethod::appendToDirectSeeds(), forAll, and List< T >::transfer().
Referenced by directMethod::findInitialSeeds().
appendToDirectSeeds()
void appendToDirectSeeds (boolList & mapFlag, labelList & srcTgtSeed, DynamicList< label > & srcSeeds, label & srcSeedI, label & tgtSeedI) const protected virtual
Append to list of src mesh seed indices.
Definition at line 170 of file directMethod.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), directMethod::directMethod(), polyMesh::FACEPLANES, forAll, found, DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), and List< T >::size().
Referenced by directMethod::calculateAddressing().
operator=()
void operator= (const directMethod &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("direct")
Run-time type information.
calculate()
void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) virtual
Calculate addressing and weights.
Implements meshToMeshMethod.
Definition at line 257 of file directMethod.C.
Referenced by directMethod::~directMethod().
The documentation for this class was generated from the following files:
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/direct/directMethod.H
src/sampling/meshToMeshInterpolation/meshToMesh/calcMethod/direct/directMethod.C