OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meshToMesh Class Reference
Class to calculate the cell-addressing between two overlapping meshes.
Public Types
enum interpolationMethod { imDirect, imMapNearest, imCellVolumeWeight }
Enumeration specifying interpolation method.
Public Member Functions
TypeName ("meshToMesh")
Run-time type information.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const interpolationMethod &method, const bool interpAllPatches=true)
Construct from source and target meshes.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const word &methodName, const word &AMIMethodName, const bool interpAllPatches=true)
Construct from source and target meshes, generic mapping methods.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const interpolationMethod &method, const HashTable< word > &patchMap, const wordList &cuttingPatches)
Construct from source and target meshes.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const word &methodName, const word &AMIMethodName, const HashTable< word > &patchMap, const wordList &cuttingPatches)
Construct from source and target meshes, generic mapping methods.
virtual ~meshToMesh ()
Destructor.
const polyMesh & srcRegion () const
Return const access to the source mesh.
const polyMesh & tgtRegion () const
Return const access to the target mesh.
const labelListList & srcToTgtCellAddr () const
Return const access to the source to target cell addressing.
const labelListList & tgtToSrcCellAddr () const
Return const access to the target to source cell addressing.
const scalarListList & srcToTgtCellWght () const
Return const access to the source to target cell weights.
const scalarListList & tgtToSrcCellWght () const
Return const access to the target to source cell weights.
scalar V () const
Return const access to the overlap volume.
template<class Type , class CombineOp >
void mapSrcToTgt (const UList< Type > &srcFld, const CombineOp &cop, List< Type > &result) const
Map field from src to tgt mesh with defined operation.
template<class Type , class CombineOp >
tmp< Field< Type > > mapSrcToTgt (const Field< Type > &srcFld, const CombineOp &cop) const
Return the src field mapped to the tgt mesh with a defined.
template<class Type , class CombineOp >
tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcFld, const CombineOp &cop) const
Convenience function to map a tmp field to the tgt mesh.
template<class Type >
tmp< Field< Type > > mapSrcToTgt (const Field< Type > &srcFld) const
Convenience function to map a field to the tgt mesh with a.
template<class Type >
tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcFld) const
Convenience function to map a tmp field to the tgt mesh.
template<class Type , class CombineOp >
void mapTgtToSrc (const UList< Type > &tgtFld, const CombineOp &cop, List< Type > &result) const
Map field from tgt to src mesh with defined operation.
template<class Type , class CombineOp >
tmp< Field< Type > > mapTgtToSrc (const Field< Type > &tgtFld, const CombineOp &cop) const
Return the tgt field mapped to the src mesh with a defined.
template<class Type , class CombineOp >
tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtFld, const CombineOp &cop) const
Convenience function to map a tmp field to the src mesh.
template<class Type >
tmp< Field< Type > > mapTgtToSrc (const Field< Type > &tgtFld) const
Convenience function to map a field to the src mesh with a.
template<class Type >
tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtFld) const
Convenience function to map a tmp field to the src mesh.
template<class Type , class CombineOp >
void mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop, GeometricField< Type, fvPatchField, volMesh > &result) const
Interpolate a field with a defined operation. Values.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
Interpolate a field with a defined operation. The initial.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield, const CombineOp &cop) const
Interpolate a tmp field with a defined operation. The.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field) const
Convenience function to map a field with a default.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield) const
Convenience function to map a tmp field with a default.
template<class Type , class CombineOp >
void mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop, GeometricField< Type, fvPatchField, volMesh > &result) const
Interpolate a field with a defined operation. Values.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
Interpolate a field with a defined operation. The initial.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield, const CombineOp &cop) const
Interpolate a tmp field with a defined operation. The.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field) const
Convenience function to map a field with a default.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield) const
Convenience function to map a tmp field with a default.
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > &srcField, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > &srcField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type > > &tsrcField) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > &tgtField, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > &tgtField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type > > &ttgtField) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tfield) const
Static Public Member Functions
static AMIPatchToPatchInterpolation::interpolationMethod interpolationMethodAMI (const interpolationMethod method)
Conversion between mesh and patch interpolation methods.
Static Public Attributes
static const NamedEnum< interpolationMethod, 3 > interpolationMethodNames_
Detailed Description
Class to calculate the cell-addressing between two overlapping meshes.
Mapping is performed using a run-time selectable interpolation mothod
See also
meshToMeshMethod
Source files
meshToMesh.H
meshToMesh.C
meshToMeshParallelOps.C
meshToMeshTemplates.C
Definition at line 60 of file meshToMesh.H.
Member Enumeration Documentation
interpolationMethod
enum interpolationMethod
Enumeration specifying interpolation method.
Enumerator
imDirect
imMapNearest
imCellVolumeWeight
Definition at line 67 of file meshToMesh.H.
Constructor & Destructor Documentation
meshToMesh() [1/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const interpolationMethod & method, const bool interpAllPatches = true)
Construct from source and target meshes.
Definition at line 532 of file meshToMesh.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethodToWord().
meshToMesh() [2/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const word & methodName, const word & AMIMethodName, const bool interpAllPatches = true)
Construct from source and target meshes, generic mapping methods.
Definition at line 567 of file meshToMesh.C.
meshToMesh() [3/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const interpolationMethod & method, const HashTable< word > & patchMap, const wordList & cuttingPatches)
Construct from source and target meshes.
Definition at line 595 of file meshToMesh.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethodToWord().
meshToMesh() [4/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const word & methodName, const word & AMIMethodName, const HashTable< word > & patchMap, const wordList & cuttingPatches)
Construct from source and target meshes, generic mapping methods.
Definition at line 632 of file meshToMesh.C.
~meshToMesh()
~meshToMesh () virtual
Destructor.
Definition at line 668 of file meshToMesh.C.
Member Function Documentation
TypeName()
TypeName ("meshToMesh")
Run-time type information.
srcRegion()
const Foam::polyMesh & srcRegion () const inline
Return const access to the source mesh.
Definition at line 30 of file meshToMeshI.H.
Referenced by Foam::MapMesh(), and Foam::MapVolFields().
tgtRegion()
const Foam::polyMesh & tgtRegion () const inline
Return const access to the target mesh.
Definition at line 36 of file meshToMeshI.H.
Referenced by Foam::MapMesh(), and Foam::MapVolFields().
srcToTgtCellAddr()
const Foam::labelListList & srcToTgtCellAddr () const inline
Return const access to the source to target cell addressing.
Definition at line 43 of file meshToMeshI.H.
tgtToSrcCellAddr()
const Foam::labelListList & tgtToSrcCellAddr () const inline
Return const access to the target to source cell addressing.
Definition at line 50 of file meshToMeshI.H.
srcToTgtCellWght()
const Foam::scalarListList & srcToTgtCellWght () const inline
Return const access to the source to target cell weights.
Definition at line 57 of file meshToMeshI.H.
tgtToSrcCellWght()
const Foam::scalarListList & tgtToSrcCellWght () const inline
Return const access to the target to source cell weights.
Definition at line 64 of file meshToMeshI.H.
V()
Foam::scalar V () const inline
Return const access to the overlap volume.
Definition at line 70 of file meshToMeshI.H.
interpolationMethodAMI()
Foam::AMIPatchToPatchInterpolation::interpolationMethod interpolationMethodAMI (const interpolationMethod method) static
Conversion between mesh and patch interpolation methods.
Definition at line 346 of file meshToMesh.C.
References Foam::abort(), PtrList< T >::append(), polyPatch::boundaryMesh(), polyPatch::constraintType(), Foam::decrIndent(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, polyBoundaryMesh::findPatchID(), forAll, forAllConstIter(), AMIInterpolation< SourcePatch, TargetPatch >::imDirect, AMIInterpolation< SourcePatch, TargetPatch >::imFaceAreaWeight, AMIInterpolation< SourcePatch, TargetPatch >::imMapNearest, Foam::incrIndent(), patchIdentifier::index(), Foam::Info, patchIdentifier::name(), polyBoundaryMesh::names(), List< T >::size(), PtrList< T >::size(), HashTable< T, Key, Hash >::size(), and faceAreaIntersect::tmMesh.
mapSrcToTgt() [1/18]
void mapSrcToTgt (const UList< Type > & srcFld, const CombineOp & cop, List< Type > & result) const
Map field from src to tgt mesh with defined operation.
Values passed in via 'result' are used to initialise the return value
Definition at line 82 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorIn, forAll, Foam::nl, List< T >::size(), and Foam::sum().
Referenced by interRegionHeatTransferModel::interpolate(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), Foam::MapVolFields(), and ListPlusEqOp< T, Size >::operator()().
mapSrcToTgt() [2/18]
tmp<Field<Type> > mapSrcToTgt (const Field< Type > & srcFld, const CombineOp & cop) const
Return the src field mapped to the tgt mesh with a defined.
operation. Initial values of the result are set to zero
mapSrcToTgt() [3/18]
tmp<Field<Type> > mapSrcToTgt (const tmp< Field< Type > > & tsrcFld, const CombineOp & cop) const
Convenience function to map a tmp field to the tgt mesh.
with a defined operation
mapSrcToTgt() [4/18]
tmp<Field<Type> > mapSrcToTgt (const Field< Type > & srcFld) const
Convenience function to map a field to the tgt mesh with a.
default operation (plusEqOp)
mapSrcToTgt() [5/18]
tmp<Field<Type> > mapSrcToTgt (const tmp< Field< Type > > & tsrcFld) const
Convenience function to map a tmp field to the tgt mesh.
with a default operation (plusEqOp)
mapTgtToSrc() [1/18]
void mapTgtToSrc (const UList< Type > & tgtFld, const CombineOp & cop, List< Type > & result) const
Map field from tgt to src mesh with defined operation.
Values passed in via 'result' are used to initialise the return value
Definition at line 210 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorIn, forAll, Foam::nl, List< T >::size(), and Foam::sum().
Referenced by meshToMesh::mapSrcToTgt(), and meshToMesh::mapTgtToSrc().
mapTgtToSrc() [2/18]
tmp<Field<Type> > mapTgtToSrc (const Field< Type > & tgtFld, const CombineOp & cop) const
Return the tgt field mapped to the src mesh with a defined.
operation. Initial values of the result are set to zero
mapTgtToSrc() [3/18]
tmp<Field<Type> > mapTgtToSrc (const tmp< Field< Type > > & ttgtFld, const CombineOp & cop) const
Convenience function to map a tmp field to the src mesh.
with a defined operation
mapTgtToSrc() [4/18]
tmp<Field<Type> > mapTgtToSrc (const Field< Type > & tgtFld) const
Convenience function to map a field to the src mesh with a.
default operation (plusEqOp)
mapTgtToSrc() [5/18]
tmp<Field<Type> > mapTgtToSrc (const tmp< Field< Type > > & ttgtFld) const
Convenience function to map a tmp field to the src mesh.
with a default operation (plusEqOp)
mapSrcToTgt() [6/18]
void mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop, GeometricField< Type, fvPatchField, volMesh > & result) const
Interpolate a field with a defined operation. Values.
passed in via 'result' are used to initialise the return value
Definition at line 336 of file meshToMeshTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::dimensionedInternalField(), forAll, Foam::identity(), GeometricField< Type, PatchField, GeoMesh >::internalField(), meshToMesh::mapSrcToTgt(), fvPatchField< Type >::patch(), fvPatchField< Type >::patchInternalField(), fvPatchField< Type >::rmap(), and List< Type >::size().
mapSrcToTgt() [7/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Interpolate a field with a defined operation. The initial.
values of the result are set to zero
mapSrcToTgt() [8/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield, const CombineOp & cop) const
Interpolate a tmp field with a defined operation. The.
initial values of the result are set to zero
mapSrcToTgt() [9/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field) const
Convenience function to map a field with a default.
operation (plusEqOp)
mapSrcToTgt() [10/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield) const
Convenience function to map a tmp field with a default.
operation (plusEqOp)
mapTgtToSrc() [6/18]
void mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop, GeometricField< Type, fvPatchField, volMesh > & result) const
Interpolate a field with a defined operation. Values.
passed in via 'result' are used to initialise the return value
Definition at line 525 of file meshToMeshTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::dimensionedInternalField(), forAll, Foam::identity(), GeometricField< Type, PatchField, GeoMesh >::internalField(), meshToMesh::mapTgtToSrc(), fvPatchField< Type >::patch(), fvPatchField< Type >::patchInternalField(), fvPatchField< Type >::rmap(), and List< Type >::size().
mapTgtToSrc() [7/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Interpolate a field with a defined operation. The initial.
values of the result are set to zero
mapTgtToSrc() [8/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield, const CombineOp & cop) const
Interpolate a tmp field with a defined operation. The.
initial values of the result are set to zero
mapTgtToSrc() [9/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field) const
Convenience function to map a field with a default.
operation (plusEqOp)
mapTgtToSrc() [10/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield) const
Convenience function to map a tmp field with a default.
operation (plusEqOp)
mapSrcToTgt() [11/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const Field< Type > & srcField, const CombineOp & cop) const
Definition at line 157 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [12/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const tmp< Field< Type > > & tsrcField, const CombineOp & cop) const
Definition at line 179 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [13/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const Field< Type > & srcField) const
Definition at line 190 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [14/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const tmp< Field< Type > > & tsrcField) const
Definition at line 200 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [11/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const Field< Type > & tgtField, const CombineOp & cop) const
Definition at line 283 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [12/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const tmp< Field< Type > > & ttgtField, const CombineOp & cop) const
Definition at line 305 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [13/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const Field< Type > & tgtField) const
Definition at line 316 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [14/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const tmp< Field< Type > > & ttgtField) const
Definition at line 326 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [15/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Definition at line 402 of file meshToMeshTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, meshToMesh::mapSrcToTgt(), IOobject::name(), primitiveMesh::nCells(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), PtrList< T >::size(), fvMesh::time(), Time::timeName(), and Foam::type().
mapSrcToTgt() [16/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield, const CombineOp & cop) const
Definition at line 492 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [17/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 504 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [18/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield) const
Definition at line 515 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [15/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Definition at line 590 of file meshToMeshTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, meshToMesh::mapTgtToSrc(), IOobject::name(), primitiveMesh::nCells(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), PtrList< T >::size(), fvMesh::time(), Time::timeName(), and Foam::type().
mapTgtToSrc() [16/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield, const CombineOp & cop) const
Definition at line 680 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [17/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 692 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [18/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tfield) const
Definition at line 703 of file meshToMeshTemplates.C.
Member Data Documentation
interpolationMethodNames_
const NamedEnum< meshToMesh::interpolationMethod, 3 > interpolationMethodNames_ static
Definition at line 75 of file meshToMesh.H.
Referenced by NamedEnum< directionType, 3 >::names(), and option::setCellSet().
The documentation for this class was generated from the following files:
src/sampling/meshToMeshInterpolation/meshToMesh/meshToMesh.H
src/sampling/meshToMeshInterpolation/meshToMesh/meshToMesh.C
src/sampling/meshToMeshInterpolation/meshToMesh/meshToMeshI.H
src/sampling/meshToMeshInterpolation/meshToMesh/meshToMeshParallelOps.C
src/sampling/meshToMeshInterpolation/meshToMesh/meshToMeshTemplates.C