OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SloanRenumber Class Reference
Sloan renumbering algorithm.
Public Member Functions
TypeName ("Sloan")
Runtime type information.
SloanRenumber (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~SloanRenumber ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Sloan renumbering algorithm.
E.g. http://www.apav.it/sito_ratio/file_pdf/ratio_4/capitolo_1.pdf
Source files
SloanRenumber.H
SloanRenumber.C
Definition at line 49 of file SloanRenumber.H.
Constructor & Destructor Documentation
SloanRenumber()
SloanRenumber (const dictionary & renumberDict)
Construct given the renumber dictionary.
Definition at line 90 of file SloanRenumber.C.
References SloanRenumber::renumber().
~SloanRenumber()
virtual ~SloanRenumber () inline virtual
Destructor.
Definition at line 78 of file SloanRenumber.H.
References mesh, notImplemented, and SloanRenumber::renumber().
Member Function Documentation
TypeName()
TypeName ("Sloan")
Runtime type information.
renumber() [1/3]
virtual labelList renumber (const pointField &) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented from renumberMethod.
Definition at line 87 of file SloanRenumber.H.
Referenced by SloanRenumber::renumber(), SloanRenumber::SloanRenumber(), and SloanRenumber::~SloanRenumber().
renumber() [2/3]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented from renumberMethod.
Definition at line 105 of file SloanRenumber.C.
References polyMesh::boundaryMesh(), Foam::constant::universal::c, polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::constant::universal::G, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), SloanRenumber::renumber(), Foam::reverse(), PtrList< T >::size(), syncTools::swapBoundaryFaceList(), and Foam::type().
renumber() [3/3]
Foam::labelList renumber (const labelListList & cellCells, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implements renumberMethod.
Definition at line 206 of file SloanRenumber.C.
References Foam::constant::universal::c, forAll, Foam::constant::universal::G, Foam::reverse(), List< T >::size(), and Foam::type().
The documentation for this class was generated from the following files:
src/renumber/SloanRenumber/SloanRenumber.H
src/renumber/SloanRenumber/SloanRenumber.C