OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CuthillMcKeeRenumber Class Reference
Cuthill-McKee renumbering.
Public Member Functions
TypeName ("CuthillMcKee")
Runtime type information.
CuthillMcKeeRenumber (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~CuthillMcKeeRenumber ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Cuthill-McKee renumbering.
Source files
CuthillMcKeeRenumber.H
CuthillMcKeeRenumber.C
Definition at line 47 of file CuthillMcKeeRenumber.H.
Constructor & Destructor Documentation
CuthillMcKeeRenumber()
CuthillMcKeeRenumber (const dictionary & renumberDict)
Construct given the renumber dictionary.
Definition at line 48 of file CuthillMcKeeRenumber.C.
References CuthillMcKeeRenumber::renumber().
~CuthillMcKeeRenumber()
virtual ~CuthillMcKeeRenumber () inline virtual
Destructor.
Definition at line 76 of file CuthillMcKeeRenumber.H.
References mesh, notImplemented, and CuthillMcKeeRenumber::renumber().
Member Function Documentation
TypeName()
TypeName ("CuthillMcKee")
Runtime type information.
renumber() [1/4]
virtual labelList renumber (const pointField &) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented from renumberMethod.
Definition at line 85 of file CuthillMcKeeRenumber.H.
Referenced by CuthillMcKeeRenumber::CuthillMcKeeRenumber(), CuthillMcKeeRenumber::renumber(), and CuthillMcKeeRenumber::~CuthillMcKeeRenumber().
renumber() [2/4]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented from renumberMethod.
Definition at line 63 of file CuthillMcKeeRenumber.C.
References Foam::bandCompression(), decompositionMethod::calcCellCells(), Foam::identity(), primitiveMesh::nCells(), CuthillMcKeeRenumber::renumber(), and Foam::reverse().
renumber() [3/4]
Foam::labelList renumber (const labelList & cellCells, const labelList & offsets, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Connectivity in losort addressing (= neighbour + offsets into neighbour)
Reimplemented from renumberMethod.
Definition at line 90 of file CuthillMcKeeRenumber.C.
References Foam::bandCompression(), CuthillMcKeeRenumber::renumber(), and Foam::reverse().
renumber() [4/4]
Foam::labelList renumber (const labelListList & cellCells, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implements renumberMethod.
Definition at line 108 of file CuthillMcKeeRenumber.C.
References Foam::bandCompression(), and Foam::reverse().
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/CuthillMcKeeRenumber/CuthillMcKeeRenumber.H
src/renumber/renumberMethods/CuthillMcKeeRenumber/CuthillMcKeeRenumber.C