OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
randomRenumber Class Reference
Random renumber. Just to see effect of renumbering.
Public Member Functions
TypeName ("random")
Runtime type information.
randomRenumber (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~randomRenumber ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Random renumber. Just to see effect of renumbering.
Source files
randomRenumber.H
randomRenumber.C
Definition at line 46 of file randomRenumber.H.
Constructor & Destructor Documentation
randomRenumber()
randomRenumber (const dictionary & renumberDict)
Construct given the renumber dictionary.
Definition at line 47 of file randomRenumber.C.
References randomRenumber::renumber().
~randomRenumber()
virtual ~randomRenumber () inline virtual
Destructor.
Definition at line 70 of file randomRenumber.H.
References mesh, and randomRenumber::renumber().
Member Function Documentation
TypeName()
TypeName ("random")
Runtime type information.
renumber() [1/3]
Foam::labelList renumber (const pointField & points) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented from renumberMethod.
Definition at line 56 of file randomRenumber.C.
References forAll, Foam::identity(), Random::integer(), rndGen(), List< T >::size(), and Foam::Swap().
Referenced by randomRenumber::randomRenumber(), randomRenumber::renumber(), and randomRenumber::~randomRenumber().
renumber() [2/3]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented from renumberMethod.
Definition at line 77 of file randomRenumber.C.
References randomRenumber::renumber().
renumber() [3/3]
Foam::labelList renumber (const labelListList & cellCells, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implements renumberMethod.
Definition at line 87 of file randomRenumber.C.
References randomRenumber::renumber().
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/randomRenumber/randomRenumber.H
src/renumber/renumberMethods/randomRenumber/randomRenumber.C