OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledCuttingPlane Class Reference
A sampledSurface defined by a plane.
Public Member Functions
TypeName ("sampledCuttingPlane")
Runtime type information.
sampledCuttingPlane (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~sampledCuttingPlane ()
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
const isoSurface & surface () const
virtual tmp< scalarField > sample (const volScalarField &) const
sample field on surface
virtual tmp< vectorField > sample (const volVectorField &) const
sample field on surface
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const
sample field on surface
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const
sample field on surface
virtual tmp< tensorField > sample (const volTensorField &) const
sample field on surface
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const
interpolate field on surface
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const
interpolate field on surface
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const
interpolate field on surface
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const
interpolate field on surface
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const
interpolate field on surface
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateField (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
interpolation requested for surface
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type > > &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type > > &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual void rename (const word &newName)
Rename.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type > > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Detailed Description
A sampledSurface defined by a plane.
Source files
sampledCuttingPlane.H
sampledCuttingPlane.C
Definition at line 53 of file sampledCuttingPlane.H.
Constructor & Destructor Documentation
sampledCuttingPlane()
sampledCuttingPlane (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 257 of file sampledCuttingPlane.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, polyBoundaryMesh::findPatchID(), Foam::Info, dictionary::lookup(), and polyBoundaryMesh::names().
~sampledCuttingPlane()
~sampledCuttingPlane () virtual
Destructor.
Definition at line 304 of file sampledCuttingPlane.C.
Member Function Documentation
TypeName()
TypeName ("sampledCuttingPlane")
Runtime type information.
needsUpdate()
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 310 of file sampledCuttingPlane.C.
expire()
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 316 of file sampledCuttingPlane.C.
References Foam::endl(), and Foam::Pout.
update()
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 342 of file sampledCuttingPlane.C.
References Foam::endl(), Foam::Pout, and sampledCuttingPlane::sample().
points()
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 152 of file sampledCuttingPlane.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and sampledCuttingPlane::surface().
faces()
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 158 of file sampledCuttingPlane.H.
References autoPtr< T >::empty(), forAll, autoPtr< T >::reset(), s(), List< T >::size(), and sampledCuttingPlane::surface().
surface()
const isoSurface& surface () const inline
Definition at line 176 of file sampledCuttingPlane.H.
References sampledSurface::interpolate(), sampledCuttingPlane::print(), and sampledCuttingPlane::sample().
Referenced by sampledCuttingPlane::faces(), and sampledCuttingPlane::points().
sample() [1/5]
Foam::tmp< Foam::scalarField > sample (const volScalarField & vField) const virtual
sample field on surface
Implements sampledSurface.
Definition at line 365 of file sampledCuttingPlane.C.
Referenced by sampledCuttingPlane::sample(), sampledCuttingPlane::surface(), and sampledCuttingPlane::update().
sample() [2/5]
Foam::tmp< Foam::vectorField > sample (const volVectorField & vField) const virtual
sample field on surface
Implements sampledSurface.
Definition at line 375 of file sampledCuttingPlane.C.
References sampledCuttingPlane::sample().
sample() [3/5]
Foam::tmp< Foam::sphericalTensorField > sample (const volSphericalTensorField & vField) const virtual
sample field on surface
Implements sampledSurface.
Definition at line 385 of file sampledCuttingPlane.C.
References sampledCuttingPlane::sample().
sample() [4/5]
Foam::tmp< Foam::symmTensorField > sample (const volSymmTensorField & vField) const virtual
sample field on surface
Implements sampledSurface.
Definition at line 395 of file sampledCuttingPlane.C.
References sampledCuttingPlane::sample().
sample() [5/5]
Foam::tmp< Foam::tensorField > sample (const volTensorField & vField) const virtual
sample field on surface
Implements sampledSurface.
Definition at line 405 of file sampledCuttingPlane.C.
References sampledSurface::interpolate().
interpolate() [1/5]
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
interpolate field on surface
Implements sampledSurface.
Definition at line 415 of file sampledCuttingPlane.C.
References sampledSurface::interpolate().
interpolate() [2/5]
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
interpolate field on surface
Implements sampledSurface.
Definition at line 425 of file sampledCuttingPlane.C.
References sampledSurface::interpolate().
interpolate() [3/5]
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
interpolate field on surface
Implements sampledSurface.
Definition at line 434 of file sampledCuttingPlane.C.
References sampledSurface::interpolate().
interpolate() [4/5]
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
interpolate field on surface
Implements sampledSurface.
Definition at line 444 of file sampledCuttingPlane.C.
References sampledSurface::interpolate().
interpolate() [5/5]
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
interpolate field on surface
Implements sampledSurface.
Definition at line 454 of file sampledCuttingPlane.C.
print()
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Definition at line 462 of file sampledCuttingPlane.C.
References Foam::name(), points, and List< T >::size().
Referenced by sampledCuttingPlane::surface().
sampleField()
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 36 of file sampledCuttingPlaneTemplates.C.
interpolateField()
Foam::tmp<Foam::Field<Type> > interpolateField (const interpolation< Type > & interpolator) const
Definition at line 47 of file sampledCuttingPlaneTemplates.C.
References Foam::MULES::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), and interpolation< Type >::psi().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledCuttingPlane/sampledCuttingPlane.H
src/sampling/sampledSurface/sampledCuttingPlane/sampledCuttingPlane.C
src/sampling/sampledSurface/sampledCuttingPlane/sampledCuttingPlaneTemplates.C