OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nearestEqOp Class Reference
Public Member Functions
void operator() (nearInfo &x, const nearInfo &y) const
Detailed Description
Definition at line 66 of file sampledTriSurfaceMesh.C.
Member Function Documentation
operator()()
void operator() (nearInfo & x, const nearInfo & y) const inline
Definition at line 71 of file sampledTriSurfaceMesh.C.
References indexedOctree< Type >::bb(), cells, meshSearch::cellTree(), polyPatch::coupled(), meshSearch::decompMode(), PointHit< Point >::distance(), Foam::e, Foam::endl(), treeBoundBox::extend(), f(), indexedOctree< Type >::findInside(), Tuple2< Type1, Type2 >::first(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), Foam::Info, sampledSurface::interpolate(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Foam::magSqr(), boundBox::max(), mesh, boundBox::min(), OFstream::name(), face::nearestPoint(), Foam::nl, patches, path(), points, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, PointHit< Point >::rawPoint(), rndGen(), s(), sampledTriSurfaceMesh::sampledTriSurfaceMesh(), List< T >::setSize(), FixedList< T, Size >::setSize(), indexedOctree< Type >::shapes(), List< T >::size(), Foam::sqr(), polyPatch::start(), triFace::triFaceFace(), sampledTriSurfaceMesh::update(), Foam::meshTools::writeOBJ(), and y.
The documentation for this class was generated from the following file:
src/sampling/sampledSurface/sampledTriSurfaceMesh/sampledTriSurfaceMesh.C