OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledSet::iNew Class Reference
Class used for the read-construction of.
Public Member Functions
iNew (const polyMesh &mesh, const meshSearch &searchEngine)
autoPtr< sampledSet > operator() (Istream &is) const
Detailed Description
Class used for the read-construction of.
PtrLists of sampledSet
Definition at line 173 of file sampledSet.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh, const meshSearch & searchEngine) inline
Definition at line 180 of file sampledSet.H.
Member Function Documentation
operator()()
autoPtr<sampledSet> operator() (Istream & is) const inline
Definition at line 186 of file sampledSet.H.
References coordSet::axis(), dict, coordSet::name(), sampledSet::New(), sampledSet::sampledSet(), and sampledSet::tol.
The documentation for this class was generated from the following file:
src/sampling/sampledSet/sampledSet/sampledSet.H