OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
proxySurfaceWriter Class Reference
A surfaceWriter that writes the geometry via the MeshedSurfaceProxy, but which does not support any fields.
Public Member Functions
TypeName ("proxy")
Runtime type information.
proxySurfaceWriter (const word &ext)
Construct for a given extension.
virtual ~proxySurfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surfaceWriter that writes the geometry via the MeshedSurfaceProxy, but which does not support any fields.
Source files
proxySurfaceWriter.H
proxySurfaceWriter.C
Definition at line 49 of file proxySurfaceWriter.H.
Constructor & Destructor Documentation
proxySurfaceWriter()
proxySurfaceWriter (const word & ext)
Construct for a given extension.
Definition at line 44 of file proxySurfaceWriter.C.
~proxySurfaceWriter()
~proxySurfaceWriter () virtual
Destructor.
Definition at line 53 of file proxySurfaceWriter.C.
References proxySurfaceWriter::write().
Member Function Documentation
TypeName()
TypeName ("proxy")
Runtime type information.
separateGeometry()
virtual bool separateGeometry () inline virtual
True if the surface format supports geometry in a separate file.
False if geometry and field must be in a single file
Reimplemented from surfaceWriter.
Definition at line 80 of file proxySurfaceWriter.H.
write()
void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const virtual
Write single surface geometry to file.
Reimplemented from surfaceWriter.
Definition at line 60 of file proxySurfaceWriter.C.
References Foam::endl(), Foam::Info, Foam::isDir(), Foam::mkDir(), and points.
Referenced by proxySurfaceWriter::~proxySurfaceWriter().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/proxy/proxySurfaceWriter.H
src/sampling/sampledSurface/writers/proxy/proxySurfaceWriter.C