OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
axis Class Reference
Orientation constraint: may only rotate around a fixed axis.
Public Member Functions
TypeName ("axis")
Runtime type information.
axis (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
Construct and return a clone.
virtual ~axis ()
Destructor.
virtual void constrainTranslation (pointConstraint &) const
Apply and accumulate translational constraints.
virtual void constrainRotation (pointConstraint &) const
Apply and accumulate rotational constraints.
virtual bool read (const dictionary &sDoFRBMCCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from the sDoFRBMCDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionConstraint ()
Destructor.
const word & name () const
Return the name.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation if not the centre of mass.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Select constructed from the sDoFRBMCDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
Name of the constraint.
dictionary sDoFRBMCCoeffs_
Constraint model specific coefficient dictionary.
const sixDoFRigidBodyMotion & motion_
Reference to the body motion.
Detailed Description
Orientation constraint: may only rotate around a fixed axis.
Source files
sixDoFRigidBodyMotionAxisConstraint.H
sixDoFRigidBodyMotionAxisConstraint.C
Definition at line 52 of file sixDoFRigidBodyMotionAxisConstraint.H.
Constructor & Destructor Documentation
axis()
axis (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Construct from components.
Definition at line 51 of file sixDoFRigidBodyMotionAxisConstraint.C.
Referenced by axis::clone().
~axis()
~axis () virtual
Destructor.
Definition at line 66 of file sixDoFRigidBodyMotionAxisConstraint.C.
References axis::constrainTranslation().
Referenced by axis::clone().
Member Function Documentation
TypeName()
TypeName ("axis")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionConstraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 80 of file sixDoFRigidBodyMotionAxisConstraint.H.
References axis::axis(), axis::constrainRotation(), axis::constrainTranslation(), axis::read(), axis::write(), and axis::~axis().
constrainTranslation()
void constrainTranslation (pointConstraint & pc) const virtual
Apply and accumulate translational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 73 of file sixDoFRigidBodyMotionAxisConstraint.C.
References axis::constrainRotation().
Referenced by axis::clone(), and axis::~axis().
constrainRotation()
void constrainRotation (pointConstraint & pc) const virtual
Apply and accumulate rotational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 80 of file sixDoFRigidBodyMotionAxisConstraint.C.
References pointConstraint::combine(), and axis::read().
Referenced by axis::clone(), and axis::constrainTranslation().
read()
bool read (const dictionary & sDoFRBMCCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 89 of file sixDoFRigidBodyMotionAxisConstraint.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::mag(), sixDoFRigidBodyMotionConstraint::read(), and axis::write().
Referenced by axis::clone(), and axis::constrainRotation().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 121 of file sixDoFRigidBodyMotionAxisConstraint.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by axis::clone(), and axis::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/axis/sixDoFRigidBodyMotionAxisConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/axis/sixDoFRigidBodyMotionAxisConstraint.C