OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightSurfaceWriter Class Reference
A surfaceWriter for Ensight format.
Public Member Functions
TypeName ("ensight")
Runtime type information.
ensightSurfaceWriter ()
Construct null.
ensightSurfaceWriter (const dictionary &options)
Construct with some output options.
virtual ~ensightSurfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surfaceWriter for Ensight format.
Source files
ensightSurfaceWriter.H
ensightSurfaceWriter.C
Definition at line 48 of file ensightSurfaceWriter.H.
Constructor & Destructor Documentation
ensightSurfaceWriter() [1/2]
ensightSurfaceWriter ()
Construct null.
Definition at line 118 of file ensightSurfaceWriter.C.
ensightSurfaceWriter() [2/2]
ensightSurfaceWriter (const dictionary & options)
Construct with some output options.
Definition at line 125 of file ensightSurfaceWriter.C.
References IOstream::formatEnum(), dictionary::found(), and dictionary::lookup().
~ensightSurfaceWriter()
~ensightSurfaceWriter () virtual
Destructor.
Definition at line 140 of file ensightSurfaceWriter.C.
References ensightSurfaceWriter::write().
Member Function Documentation
TypeName()
TypeName ("ensight")
Runtime type information.
separateGeometry()
virtual bool separateGeometry () inline virtual
True if the surface format supports geometry in a separate file.
False if geometry and field must be in a single file
Reimplemented from surfaceWriter.
Definition at line 98 of file ensightSurfaceWriter.H.
write() [1/6]
void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const virtual
Write single surface geometry to file.
Reimplemented from surfaceWriter.
Definition at line 147 of file ensightSurfaceWriter.C.
References Foam::defineSurfaceWriterWriteFields(), Foam::endl(), Foam::Info, Foam::isDir(), Foam::mkDir(), OFstream::name(), fileName::name(), Foam::nl, and points.
Referenced by ensightSurfaceWriter::~ensightSurfaceWriter().
write() [2/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [3/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [4/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [5/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< symmTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write symmTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [6/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< tensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write tensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/ensight/ensightSurfaceWriter.H
src/sampling/sampledSurface/writers/ensight/ensightSurfaceWriter.C