OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
point Class Reference
Translation constraint on the centre of rotation: fixed in space.
Public Member Functions
TypeName ("point")
Runtime type information.
point (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
Construct and return a clone.
virtual ~point ()
Destructor.
virtual void setCentreOfRotation (Foam::point &) const
Set the centre of rotation to the point.
virtual void constrainTranslation (pointConstraint &) const
Apply and accumulate translational constraints.
virtual void constrainRotation (pointConstraint &) const
Apply and accumulate rotational constraints.
virtual bool read (const dictionary &sDoFRBMCCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from the sDoFRBMCDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionConstraint ()
Destructor.
const word & name () const
Return the name.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Select constructed from the sDoFRBMCDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
Name of the constraint.
dictionary sDoFRBMCCoeffs_
Constraint model specific coefficient dictionary.
const sixDoFRigidBodyMotion & motion_
Reference to the body motion.
Detailed Description
Translation constraint on the centre of rotation: fixed in space.
If 'centreOfRotation' is not provided in the dictionary the centre of mass is used.
Source files
sixDoFRigidBodyMotionPointConstraint.H
sixDoFRigidBodyMotionPointConstraint.C
Definition at line 56 of file sixDoFRigidBodyMotionPointConstraint.H.
Constructor & Destructor Documentation
point()
point (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Construct from components.
Definition at line 51 of file sixDoFRigidBodyMotionPointConstraint.C.
Referenced by point::clone().
~point()
~point () virtual
Destructor.
Definition at line 66 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::setCentreOfRotation().
Referenced by point::clone().
Member Function Documentation
TypeName()
TypeName ("point")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionConstraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 83 of file sixDoFRigidBodyMotionPointConstraint.H.
References point::constrainRotation(), point::constrainTranslation(), point::point(), point::read(), point::setCentreOfRotation(), point::write(), and point::~point().
setCentreOfRotation()
void setCentreOfRotation (Foam::point & CofR) const virtual
Set the centre of rotation to the point.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 73 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::constrainTranslation().
Referenced by point::clone(), and point::~point().
constrainTranslation()
void constrainTranslation (pointConstraint & pc) const virtual
Apply and accumulate translational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 82 of file sixDoFRigidBodyMotionPointConstraint.C.
References pointConstraint::combine(), point::constrainRotation(), and Vector< Cmpt >::zero.
Referenced by point::clone(), and point::setCentreOfRotation().
constrainRotation()
void constrainRotation (pointConstraint & pc) const virtual
Apply and accumulate rotational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 91 of file sixDoFRigidBodyMotionPointConstraint.C.
References point::read().
Referenced by point::clone(), and point::constrainTranslation().
read()
bool read (const dictionary & sDoFRBMCCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 98 of file sixDoFRigidBodyMotionPointConstraint.C.
References sixDoFRigidBodyMotionConstraint::read(), and point::write().
Referenced by point::clone(), and point::constrainRotation().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 115 of file sixDoFRigidBodyMotionPointConstraint.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by point::clone(), and point::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/point/sixDoFRigidBodyMotionPointConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/point/sixDoFRigidBodyMotionPointConstraint.C