OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vtkSurfaceWriter Class Reference
A surfaceWriter for VTK legacy format.
Public Member Functions
TypeName ("vtk")
Runtime type information.
vtkSurfaceWriter ()
Construct null.
virtual ~vtkSurfaceWriter ()
Destructor.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
template<>
void writeData (Ostream &os, const Field< scalar > &values)
template<>
void writeData (Ostream &os, const Field< vector > &values)
template<>
void writeData (Ostream &os, const Field< sphericalTensor > &values)
template<>
void writeData (Ostream &os, const Field< symmTensor > &values)
template<>
void writeData (Ostream &os, const Field< tensor > &values)
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surfaceWriter for VTK legacy format.
Source files
vtkSurfaceWriter.H
vtkSurfaceWriter.C
Definition at line 48 of file vtkSurfaceWriter.H.
Constructor & Destructor Documentation
vtkSurfaceWriter()
vtkSurfaceWriter ()
Construct null.
Definition at line 270 of file vtkSurfaceWriter.C.
~vtkSurfaceWriter()
~vtkSurfaceWriter () virtual
Destructor.
Definition at line 278 of file vtkSurfaceWriter.C.
References vtkSurfaceWriter::write().
Member Function Documentation
TypeName()
TypeName ("vtk")
Runtime type information.
write() [1/6]
void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const virtual
Write single surface geometry to file.
Reimplemented from surfaceWriter.
Definition at line 285 of file vtkSurfaceWriter.C.
References Foam::defineSurfaceWriterWriteFields(), Foam::endl(), Foam::Info, Foam::isDir(), Foam::mkDir(), and OFstream::name().
Referenced by vtkSurfaceWriter::~vtkSurfaceWriter().
write() [2/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [3/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [4/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [5/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< symmTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write symmTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [6/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< tensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write tensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
writeData() [1/5]
void writeData (Ostream & os, const Field< scalar > & values)
Definition at line 98 of file vtkSurfaceWriter.C.
References forAll, Foam::nl, and List< T >::size().
writeData() [2/5]
void writeData (Ostream & os, const Field< vector > & values)
Definition at line 127 of file vtkSurfaceWriter.C.
References forAll, Foam::nl, and List< T >::size().
writeData() [3/5]
void writeData (Ostream & os, const Field< sphericalTensor > & values)
Definition at line 145 of file vtkSurfaceWriter.C.
References forAll, Foam::nl, and List< Type >::size().
writeData() [4/5]
void writeData (Ostream & os, const Field< symmTensor > & values)
Definition at line 162 of file vtkSurfaceWriter.C.
References forAll, Foam::nl, and List< T >::size().
writeData() [5/5]
void writeData (Ostream & os, const Field< tensor > & values)
Definition at line 183 of file vtkSurfaceWriter.C.
References Foam::endl(), forAll, Foam::Info, Foam::isDir(), Foam::mkDir(), OFstream::name(), Foam::nl, List< Type >::size(), List< T >::size(), and writeData().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/vtk/vtkSurfaceWriter.H
src/sampling/sampledSurface/writers/vtk/vtkSurfaceWriter.C