OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sixDoFRigidBodyMotion Class Reference
Six degree of freedom motion for a rigid body. Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form.
Public Member Functions
sixDoFRigidBodyMotion ()
Construct null.
sixDoFRigidBodyMotion (const dictionary &dict, const dictionary &stateDict)
Construct from constant and state dictionaries.
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion &)
Construct as copy.
scalar mass () const
Return the mass.
const diagTensor & momentOfInertia () const
Return the inertia tensor.
const sixDoFRigidBodyMotionState & state () const
Return the motion state.
const point & centreOfRotation () const
Return the current centre of rotation.
const point & centreOfRotation0 () const
Return the centre of rotation at previous time-step.
const point & initialCentreOfMass () const
Return the initial centre of mass.
point centreOfMass () const
Return the current centre of mass.
const tensor & orientation () const
Return the orientation tensor, Q.
vector omega () const
Return the angular velocity in the global frame.
const vector & v () const
Return the current velocity.
vector momentArm () const
bool report () const
Return the report Switch.
void newTime ()
Store the motion state at the beginning of the time-step.
point & centreOfRotation ()
Return non-const access to the centre of rotation.
void addRestraints (const dictionary &dict)
Add restraints to the motion, public to allow external.
void addConstraints (const dictionary &dict)
Add restraints to the motion, public to allow external.
void updatePosition (scalar deltaT, scalar deltaT0)
First leapfrog velocity adjust and motion part, required.
void updateAcceleration (const vector &fGlobal, const vector &tauGlobal, scalar deltaT)
Second leapfrog velocity adjust part.
void status () const
Report the status of the motion.
point velocity (const point &pt) const
Return the velocity of a position.
point transform (const point &initialPoints) const
Transform the given initial state point by the current motion.
tmp< pointField > transform (const pointField &initialPoints) const
Transform the given initial state pointField by the current.
tmp< pointField > transform (const pointField &initialPoints, const scalarField &scale) const
Transform the given initial state pointField by the current.
void write (Ostream &) const
Write.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Detailed Description
Six degree of freedom motion for a rigid body. Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form.
Symplectic motion as per:
title = {Symplectic splitting methods for rigid body molecular dynamics}, publisher = {AIP}, year = {1997}, journal = {The Journal of Chemical Physics}, volume = {107}, number = {15}, pages = {5840-5851}, url = {http://link.aip.org/link/?JCP/107/5840/1}, doi = {10.1063/1.474310}
Can add restraints (e.g. a spring) and constraints (e.g. motion may only be on a plane).
Source files
sixDoFRigidBodyMotion.H
sixDoFRigidBodyMotionI.H
sixDoFRigidBodyMotion.C
sixDoFRigidBodyMotionIO.C
Definition at line 72 of file sixDoFRigidBodyMotion.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotion() [1/3]
sixDoFRigidBodyMotion ()
Construct null.
Definition at line 72 of file sixDoFRigidBodyMotion.C.
Referenced by sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
sixDoFRigidBodyMotion() [2/3]
sixDoFRigidBodyMotion (const dictionary & dict, const dictionary & stateDict)
Construct from constant and state dictionaries.
Definition at line 92 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), sixDoFRigidBodyMotionState::centreOfRotation(), Foam::diag(), dictionary::found(), Foam::I, Foam::magSqr(), R, sixDoFRigidBodyMotion::sixDoFRigidBodyMotion(), and Foam::sqr().
sixDoFRigidBodyMotion() [3/3]
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion & sDoFRBM)
Construct as copy.
Definition at line 153 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addRestraints().
Member Function Documentation
mass()
Foam::scalar mass () const inline
Return the mass.
Definition at line 238 of file sixDoFRigidBodyMotionI.H.
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
momentOfInertia()
const Foam::diagTensor & momentOfInertia () const inline
Return the inertia tensor.
Definition at line 245 of file sixDoFRigidBodyMotionI.H.
state()
const Foam::sixDoFRigidBodyMotionState & state () const inline
Return the motion state.
Definition at line 252 of file sixDoFRigidBodyMotionI.H.
centreOfRotation() [1/2]
const Foam::point & centreOfRotation () const inline
Return the current centre of rotation.
Definition at line 258 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::centreOfRotation().
Referenced by sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), sixDoFRigidBodyMotion::status(), sixDoFRigidBodyMotion::transform(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyMotion::updatePosition(), and sixDoFRigidBodyMotion::velocity().
centreOfRotation0()
const Foam::point & centreOfRotation0 () const inline
Return the centre of rotation at previous time-step.
Definition at line 264 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::centreOfRotation().
Referenced by sixDoFRigidBodyMotion::updatePosition().
initialCentreOfMass()
const Foam::point & initialCentreOfMass () const inline
Return the initial centre of mass.
Definition at line 271 of file sixDoFRigidBodyMotionI.H.
centreOfMass()
Foam::point centreOfMass () const inline
Return the current centre of mass.
Definition at line 277 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::transform().
Referenced by sixDoFRigidBodyMotion::momentArm(), and sixDoFRigidBodyMotion::status().
orientation()
const Foam::tensor & orientation () const inline
Return the orientation tensor, Q.
globalVector = Q & bodyLocalVector bodyLocalVector = Q.T() & globalVector
Definition at line 290 of file sixDoFRigidBodyMotionI.H.
Referenced by sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), and sixDoFRigidBodyMotion::status().
omega()
Foam::vector omega () const inline
Return the angular velocity in the global frame.
Definition at line 296 of file sixDoFRigidBodyMotionI.H.
References Foam::inv().
Referenced by sphericalAngularDamper::restrain(), sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), sixDoFRigidBodyMotion::status(), and sixDoFRigidBodyMotion::velocity().
v()
const Foam::vector & v () const inline
Return the current velocity.
Definition at line 140 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::a(), sixDoFRigidBodyMotionState::pi(), sixDoFRigidBodyMotionState::Q(), sixDoFRigidBodyMotionState::tau(), and sixDoFRigidBodyMotionState::v().
momentArm()
Foam::vector momentArm () const inline
Definition at line 283 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::centreOfMass(), and sixDoFRigidBodyMotionState::centreOfRotation().
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
report()
bool report () const inline
Return the report Switch.
Definition at line 302 of file sixDoFRigidBodyMotionI.H.
Referenced by sphericalAngularDamper::restrain(), linearDamper::restrain(), sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), linearSpring::restrain(), and tabulatedAxialAngularSpring::restrain().
newTime()
void newTime () inline
Store the motion state at the beginning of the time-step.
Definition at line 308 of file sixDoFRigidBodyMotionI.H.
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
centreOfRotation() [2/2]
Foam::point & centreOfRotation () inline
Return non-const access to the centre of rotation.
Definition at line 314 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::centreOfRotation(), and sixDoFRigidBodyMotion::velocity().
addRestraints()
void addRestraints (const dictionary & dict)
Add restraints to the motion, public to allow external.
addition of restraints after construction
Definition at line 177 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addConstraints(), dict, forAllConstIter(), dictionary::found(), sixDoFRigidBodyMotionRestraint::New(), DLListBase::size(), and dictionary::subDict().
Referenced by sixDoFRigidBodyMotion::read(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
addConstraints()
void addConstraints (const dictionary & dict)
Add restraints to the motion, public to allow external.
addition of restraints after construction
Definition at line 211 of file sixDoFRigidBodyMotion.C.
References pointConstraint::constraintTransformation(), dict, Foam::endl(), forAllConstIter(), dictionary::found(), Foam::Info, sixDoFRigidBodyMotionConstraint::New(), Foam::nl, DLListBase::size(), dictionary::subDict(), and sixDoFRigidBodyMotion::updatePosition().
Referenced by sixDoFRigidBodyMotion::addRestraints(), sixDoFRigidBodyMotion::read(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
updatePosition()
void updatePosition (scalar deltaT, scalar deltaT0)
First leapfrog velocity adjust and motion part, required.
before force calculation. Takes old timestep for variable timestep cases.
Definition at line 261 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfRotation(), sixDoFRigidBodyMotion::centreOfRotation0(), Tuple2< Type1, Type2 >::first(), UPstream::master(), Pstream::scatter(), Tuple2< Type1, Type2 >::second(), and sixDoFRigidBodyMotion::updateAcceleration().
Referenced by sixDoFRigidBodyMotion::addConstraints(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
updateAcceleration()
void updateAcceleration (const vector & fGlobal, const vector & tauGlobal, scalar deltaT)
Second leapfrog velocity adjust part.
required after motion and force calculation
Definition at line 288 of file sixDoFRigidBodyMotion.C.
References UPstream::master(), Pstream::scatter(), and sixDoFRigidBodyMotion::status().
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyMotion::updatePosition().
status()
void status () const
Report the status of the motion.
Definition at line 332 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfMass(), sixDoFRigidBodyMotion::centreOfRotation(), Foam::endl(), Foam::Info, Foam::nl, sixDoFRigidBodyMotion::omega(), sixDoFRigidBodyMotion::orientation(), and sixDoFRigidBodyMotion::transform().
Referenced by sixDoFRigidBodyMotion::updateAcceleration().
velocity()
Foam::point velocity (const point & pt) const inline
Return the velocity of a position.
Definition at line 321 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::centreOfRotation(), sixDoFRigidBodyMotion::omega(), and sixDoFRigidBodyMotion::transform().
Referenced by sixDoFRigidBodyMotion::centreOfRotation(), and linearSpring::restrain().
transform() [1/3]
Foam::point transform (const point & initialPoints) const inline
Transform the given initial state point by the current motion.
state
Definition at line 330 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::centreOfRotation(), and Tensor< Cmpt >::T().
Referenced by sixDoFRigidBodyMotion::centreOfMass(), linearSpring::restrain(), sixDoFRigidBodyMotion::status(), sixDoFRigidBodyMotion::transform(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyMotion::velocity().
transform() [2/3]
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints) const
Transform the given initial state pointField by the current.
motion state
Definition at line 345 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfRotation(), Tensor< Cmpt >::T(), and sixDoFRigidBodyMotion::transform().
transform() [3/3]
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints, const scalarField & scale) const
Transform the given initial state pointField by the current.
motion state scaled by the given scale
Definition at line 358 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfRotation(), forAll, septernion::I, points, s(), Foam::slerp(), Foam::T(), septernion::transform(), and sixDoFRigidBodyMotion::transform().
write()
void write (Ostream & os) const
Write.
Definition at line 49 of file sixDoFRigidBodyMotionIO.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), forAll, Foam::incrIndent(), Foam::indent(), Foam::nl, sixDoFRigidBodyMotionState::write(), and Ostream::writeKeyword().
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), and sixDoFRigidBodyDisplacementPointPatchVectorField::write().
read()
bool read (const dictionary & dict)
Read coefficients dictionary and update system parameters,.
constraints and restraints but not the current state
Definition at line 31 of file sixDoFRigidBodyMotionIO.C.
References sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), dictionary::lookup(), and dictionary::lookupOrDefault().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionI.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionIO.C