OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
externalPointEdgePoint::trackingData Class Reference
Class used to pass data into container.
Public Member Functions
trackingData (const pointField &points)
Public Attributes
const pointField & points_
Detailed Description
Class used to pass data into container.
Definition at line 94 of file externalPointEdgePoint.H.
Constructor & Destructor Documentation
trackingData()
trackingData (const pointField & points) inline
Definition at line 99 of file externalPointEdgePoint.H.
References externalPointEdgePoint::distSqr(), externalPointEdgePoint::enterDomain(), externalPointEdgePoint::equal(), externalPointEdgePoint::externalPointEdgePoint(), externalPointEdgePoint::leaveDomain(), mesh, externalPointEdgePoint::operator!=(), externalPointEdgePoint::operator<<, externalPointEdgePoint::operator==(), externalPointEdgePoint::operator>>, externalPointEdgePoint::origin(), Foam::pos(), externalPointEdgePoint::sameGeometry(), externalPointEdgePoint::transform(), externalPointEdgePoint::updateEdge(), externalPointEdgePoint::updatePoint(), and externalPointEdgePoint::valid().
Member Data Documentation
points_
const pointField& points_
Definition at line 97 of file externalPointEdgePoint.H.
Referenced by pointPatchDist::correct().
The documentation for this class was generated from the following file:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionSolver/externalPointEdgePoint.H