OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sphericalAngularSpring Class Reference
sixDoFRigidBodyMotionRestraints model. Spherical angular spring.
Public Member Functions
TypeName ("sphericalAngularSpring")
Runtime type information.
sphericalAngularSpring (const word &name, const dictionary &sDoFRBMRDict)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
Construct and return a clone.
virtual ~sphericalAngularSpring ()
Destructor.
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
Calculate the restraint position, force and moment.
virtual bool read (const dictionary &sDoFRBMRCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionRestraint ()
Destructor.
const word & name () const
Return the name.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Select constructed from the sDoFRBMRDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
Name of the restraint.
dictionary sDoFRBMRCoeffs_
Restraint model specific coefficient dictionary.
Detailed Description
sixDoFRigidBodyMotionRestraints model. Spherical angular spring.
Source files
sphericalAngularSpring.H
sphericalAngularSpring.C
Definition at line 53 of file sphericalAngularSpring.H.
Constructor & Destructor Documentation
sphericalAngularSpring()
sphericalAngularSpring (const word & name, const dictionary & sDoFRBMRDict)
Construct from components.
Definition at line 52 of file sphericalAngularSpring.C.
References sphericalAngularSpring::~sphericalAngularSpring().
Referenced by sphericalAngularSpring::clone().
~sphericalAngularSpring()
~sphericalAngularSpring () virtual
Destructor.
Definition at line 69 of file sphericalAngularSpring.C.
References sphericalAngularSpring::restrain().
Referenced by sphericalAngularSpring::clone(), and sphericalAngularSpring::sphericalAngularSpring().
Member Function Documentation
TypeName()
TypeName ("sphericalAngularSpring")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionRestraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 85 of file sphericalAngularSpring.H.
References sphericalAngularSpring::read(), sphericalAngularSpring::restrain(), sphericalAngularSpring::sphericalAngularSpring(), sphericalAngularSpring::write(), and sphericalAngularSpring::~sphericalAngularSpring().
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Calculate the restraint position, force and moment.
Global reference frame vectors.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 76 of file sphericalAngularSpring.C.
References sixDoFRigidBodyMotion::centreOfRotation(), Foam::endl(), Foam::Info, VectorSpace< Vector< Cmpt >, Cmpt, 3 >::nComponents, sixDoFRigidBodyMotion::omega(), sixDoFRigidBodyMotion::orientation(), sphericalAngularSpring::read(), sixDoFRigidBodyMotion::report(), and Vector< Cmpt >::zero.
Referenced by sphericalAngularSpring::clone(), and sphericalAngularSpring::~sphericalAngularSpring().
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 119 of file sphericalAngularSpring.C.
References Foam::e, Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::I, Foam::mag(), Foam::nl, sixDoFRigidBodyMotionRestraint::read(), Foam::sqrt(), and sphericalAngularSpring::write().
Referenced by sphericalAngularSpring::clone(), and sphericalAngularSpring::restrain().
write()
void write (Ostream & os) const virtual
Write.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 151 of file sphericalAngularSpring.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by sphericalAngularSpring::clone(), and sphericalAngularSpring::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sphericalAngularSpring/sphericalAngularSpring.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sphericalAngularSpring/sphericalAngularSpring.C