OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STLASCIILexer Class Reference
A lexer for parsing STL ASCII files.
Public Member Functions
STLASCIILexer (istream *is, const label approxNpoints)
From input stream and the approximate number of vertices in the STL.
int lex ()
The lexer function itself.
bool sorted () const
Do all the solid groups appear in order.
DynamicList< point > & points ()
A list of points corresponding to a pointField.
DynamicList< label > & facets ()
A list of facet IDs (group IDs)
DynamicList< word > & names ()
Names.
DynamicList< label > & sizes ()
Sizes.
Detailed Description
A lexer for parsing STL ASCII files.
Returns DynamicList(s) of points and facets (zoneIds). The facets are within a solid/endsolid grouping
Definition at line 5259 of file STLsurfaceFormatASCII.C.
Constructor & Destructor Documentation
STLASCIILexer()
STLASCIILexer (istream * is, const label approxNpoints)
From input stream and the approximate number of vertices in the STL.
Definition at line 5324 of file STLsurfaceFormatASCII.C.
Member Function Documentation
lex()
int lex ()
The lexer function itself.
The main scanner function which does all the work.
Definition at line 5457 of file STLsurfaceFormatASCII.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::constant::physicoChemical::b, BEGIN, Foam::constant::universal::c, ECHO, HashTableCore::end(), EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, Foam::exit(), Foam::FatalError, FatalErrorIn, HashTable< T, Key, Hash >::find(), INITIAL, HashTable< T, Key, Hash >::insert(), name(), Foam::nl, readFacet, readNormal, readSolidName, readVertex, readVertices, List< T >::size(), stlError, yy_accept, yy_buffer_state::yy_at_bol, YY_BREAK, yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, yy_buffer_state::yy_buf_pos, YY_BUF_SIZE, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, YY_INPUT, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_buffer_state::yy_n_chars, YY_NEW_FILE, yy_NUL_trans, yy_nxt, YY_READ_BUF_SIZE, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, YY_START_STACK_INCR, YY_STATE_EOF, yyalloc(), yyFlexLexer, yyfree(), yyrealloc(), yyterminate, and yytext_ptr.
sorted()
bool sorted () const inline
Do all the solid groups appear in order.
Definition at line 5292 of file STLsurfaceFormatASCII.C.
points()
DynamicList<point>& points () inline
A list of points corresponding to a pointField.
Definition at line 5298 of file STLsurfaceFormatASCII.C.
facets()
DynamicList<label>& facets () inline
A list of facet IDs (group IDs)
corresponds to the number of triangles
Definition at line 5305 of file STLsurfaceFormatASCII.C.
names()
DynamicList<word>& names () inline
Names.
Definition at line 5311 of file STLsurfaceFormatASCII.C.
sizes()
DynamicList<label>& sizes () inline
Sizes.
Definition at line 5317 of file STLsurfaceFormatASCII.C.
The documentation for this class was generated from the following file:
src/surfMesh/Make/linux64GccDPOpt/STLsurfaceFormatASCII.C