OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sphericalAngularDamper Class Reference
sixDoFRigidBodyMotionRestraints model. Spherical angular damper.
Public Member Functions
TypeName ("sphericalAngularDamper")
Runtime type information.
sphericalAngularDamper (const word &name, const dictionary &sDoFRBMRDict)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
Construct and return a clone.
virtual ~sphericalAngularDamper ()
Destructor.
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
Calculate the restraint position, force and moment.
virtual bool read (const dictionary &sDoFRBMRCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionRestraint ()
Destructor.
const word & name () const
Return the name.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Select constructed from the sDoFRBMRDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
Name of the restraint.
dictionary sDoFRBMRCoeffs_
Restraint model specific coefficient dictionary.
Detailed Description
sixDoFRigidBodyMotionRestraints model. Spherical angular damper.
Source files
sphericalAngularDamper.H
sphericalAngularDamper.C
Definition at line 51 of file sphericalAngularDamper.H.
Constructor & Destructor Documentation
sphericalAngularDamper()
sphericalAngularDamper (const word & name, const dictionary & sDoFRBMRDict)
Construct from components.
Definition at line 52 of file sphericalAngularDamper.C.
References sphericalAngularDamper::~sphericalAngularDamper().
Referenced by sphericalAngularDamper::clone().
~sphericalAngularDamper()
~sphericalAngularDamper () virtual
Destructor.
Definition at line 67 of file sphericalAngularDamper.C.
References sphericalAngularDamper::restrain().
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::sphericalAngularDamper().
Member Function Documentation
TypeName()
TypeName ("sphericalAngularDamper")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionRestraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 77 of file sphericalAngularDamper.H.
References sphericalAngularDamper::read(), sphericalAngularDamper::restrain(), sphericalAngularDamper::sphericalAngularDamper(), sphericalAngularDamper::write(), and sphericalAngularDamper::~sphericalAngularDamper().
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Calculate the restraint position, force and moment.
Global reference frame vectors.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 74 of file sphericalAngularDamper.C.
References Foam::endl(), Foam::Info, sixDoFRigidBodyMotion::omega(), sphericalAngularDamper::read(), sixDoFRigidBodyMotion::report(), and Vector< Cmpt >::zero.
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::~sphericalAngularDamper().
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 93 of file sphericalAngularDamper.C.
References sixDoFRigidBodyMotionRestraint::read(), and sphericalAngularDamper::write().
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::restrain().
write()
void write (Ostream & os) const virtual
Write.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 106 of file sphericalAngularDamper.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sphericalAngularDamper/sphericalAngularDamper.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sphericalAngularDamper/sphericalAngularDamper.C