OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
externalPointEdgePoint Class Reference
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Classes
class trackingData
Class used to pass data into container.
Public Member Functions
externalPointEdgePoint ()
Construct null.
externalPointEdgePoint (const point &, const scalar)
Construct from origin, distance.
externalPointEdgePoint (const externalPointEdgePoint &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const externalPointEdgePoint &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointI, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const label edgeI, const externalPointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointI, const externalPointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const externalPointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointI, const externalPointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const externalPointEdgePoint &, TrackingData &td) const
Equivalent to operator== with TrackingData.
bool operator== (const externalPointEdgePoint &) const
bool operator!= (const externalPointEdgePoint &) const
Friends
Ostream & operator<< (Ostream &, const externalPointEdgePoint &)
Istream & operator>> (Istream &, externalPointEdgePoint &)
Detailed Description
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Source files
externalPointEdgePoint.H
externalPointEdgePointI.H
externalPointEdgePoint.C
Definition at line 55 of file externalPointEdgePoint.H.
Constructor & Destructor Documentation
externalPointEdgePoint() [1/3]
externalPointEdgePoint () inline
Construct null.
Definition at line 118 of file externalPointEdgePointI.H.
Referenced by externalPointEdgePoint::externalPointEdgePoint(), and externalPointEdgePoint::trackingData::trackingData().
externalPointEdgePoint() [2/3]
externalPointEdgePoint (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 126 of file externalPointEdgePointI.H.
References externalPointEdgePoint::externalPointEdgePoint().
externalPointEdgePoint() [3/3]
externalPointEdgePoint (const externalPointEdgePoint & wpt) inline
Construct as copy.
Definition at line 137 of file externalPointEdgePointI.H.
Member Function Documentation
origin()
const Foam::point & origin () const inline
Definition at line 148 of file externalPointEdgePointI.H.
Referenced by externalPointEdgePoint::operator==(), and externalPointEdgePoint::trackingData::trackingData().
distSqr()
Foam::scalar distSqr () const inline
Definition at line 154 of file externalPointEdgePointI.H.
Referenced by externalPointEdgePoint::operator==(), externalPointEdgePoint::sameGeometry(), and externalPointEdgePoint::trackingData::trackingData().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 161 of file externalPointEdgePointI.H.
References Vector< scalar >::max, and externalPointEdgePoint::sameGeometry().
Referenced by externalPointEdgePoint::trackingData::trackingData().
sameGeometry()
bool sameGeometry (const externalPointEdgePoint & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 170 of file externalPointEdgePointI.H.
References externalPointEdgePoint::distSqr(), externalPointEdgePoint::leaveDomain(), and Foam::mag().
Referenced by externalPointEdgePoint::trackingData::trackingData(), and externalPointEdgePoint::valid().
leaveDomain()
void leaveDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 198 of file externalPointEdgePointI.H.
References externalPointEdgePoint::transform().
Referenced by externalPointEdgePoint::sameGeometry(), and externalPointEdgePoint::trackingData::trackingData().
enterDomain()
void enterDomain (const polyPatch & patch, const label patchPointI, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 222 of file externalPointEdgePointI.H.
References externalPointEdgePoint::updatePoint().
Referenced by externalPointEdgePoint::trackingData::trackingData(), and externalPointEdgePoint::transform().
transform()
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 211 of file externalPointEdgePointI.H.
References externalPointEdgePoint::enterDomain(), and Foam::transform().
Referenced by externalPointEdgePoint::leaveDomain(), and externalPointEdgePoint::trackingData::trackingData().
updatePoint() [1/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const label edgeI, const externalPointEdgePoint & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 236 of file externalPointEdgePointI.H.
Referenced by externalPointEdgePoint::enterDomain(), externalPointEdgePoint::trackingData::trackingData(), and externalPointEdgePoint::updatePoint().
updatePoint() [2/3]
bool updatePoint (const polyMesh & mesh, const label pointI, const externalPointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 251 of file externalPointEdgePointI.H.
References externalPointEdgePoint::updatePoint().
updatePoint() [3/3]
bool updatePoint (const externalPointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 265 of file externalPointEdgePointI.H.
References externalPointEdgePoint::updateEdge().
updateEdge()
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointI, const externalPointEdgePoint & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 277 of file externalPointEdgePointI.H.
References edge::centre(), Foam::e, primitiveMesh::edges(), and externalPointEdgePoint::equal().
Referenced by externalPointEdgePoint::trackingData::trackingData(), and externalPointEdgePoint::updatePoint().
equal()
bool equal (const externalPointEdgePoint & rhs, TrackingData & td) const inline
Equivalent to operator== with TrackingData.
Definition at line 293 of file externalPointEdgePointI.H.
References externalPointEdgePoint::operator==().
Referenced by externalPointEdgePoint::trackingData::trackingData(), and externalPointEdgePoint::updateEdge().
operator==()
bool operator== (const externalPointEdgePoint & rhs) const inline
Definition at line 305 of file externalPointEdgePointI.H.
References externalPointEdgePoint::distSqr(), and externalPointEdgePoint::origin().
Referenced by externalPointEdgePoint::equal(), and externalPointEdgePoint::trackingData::trackingData().
operator!=()
bool operator!= (const externalPointEdgePoint & rhs) const inline
Definition at line 315 of file externalPointEdgePointI.H.
Referenced by externalPointEdgePoint::trackingData::trackingData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const externalPointEdgePoint &) friend
Referenced by externalPointEdgePoint::trackingData::trackingData().
operator>>
Istream& operator>> (Istream & , externalPointEdgePoint &) friend
Referenced by externalPointEdgePoint::trackingData::trackingData().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionSolver/externalPointEdgePoint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionSolver/externalPointEdgePointI.H