OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STARCDsurfaceFormatCore Class Reference
Internal class used by the STARCDsurfaceFormat.
Static Protected Member Functions
static Map< word > readInpCellTable (IFstream &)
static void writeCase (Ostream &, const pointField &, const label nFaces, const UList< surfZone > &)
Static Protected Member Functions inherited from STARCDCore
static bool readHeader (IFstream &, const word &fileSignature)
Read header.
static void writeHeader (Ostream &, const word &fileType)
Write header for fileType (CELL|VERTEX|BOUNDARY)
Additional Inherited Members
Public Member Functions inherited from STARCDCore
STARCDCore ()
Construct null.
Static Public Member Functions inherited from STARCDCore
static bool readPoints (IFstream &, pointField &, labelList &ids)
Read points from a (.vrt) file.
static void writePoints (Ostream &, const pointField &)
Write header and points to (.vrt) file.
Protected Types inherited from STARCDCore
enum cellType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Detailed Description
Internal class used by the STARCDsurfaceFormat.
Source files
STARCDsurfaceFormatCore.H
STARCDsurfaceFormatCore.C
Definition at line 54 of file STARCDsurfaceFormatCore.H.
Member Function Documentation
readInpCellTable()
Foam::Map< Foam::word > readInpCellTable (IFstream & is) static protected
Definition at line 39 of file STARCDsurfaceFormatCore.C.
References ISstream::getLine(), IOstream::good(), HashTable< T, label, Hash< label > >::insert(), regExp::match(), and STARCDsurfaceFormatCore::writeCase().
writeCase()
void writeCase (Ostream & os, const pointField & pointLst, const label nFaces, const UList< surfZone > & zoneLst) static protected
Definition at line 78 of file STARCDsurfaceFormatCore.C.
References Ostream::flush(), forAll, fileName::lessExt(), fileName::name(), IOstream::name(), Foam::nl, and List< T >::size().
Referenced by STARCDsurfaceFormatCore::readInpCellTable().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/starcd/STARCDsurfaceFormatCore.H
src/surfMesh/surfaceFormats/starcd/STARCDsurfaceFormatCore.C