OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STLtriangle Class Reference
A triangle representation for STL files.
Public Member Functions
STLtriangle ()
Construct null.
STLtriangle (const STLpoint &normal, const STLpoint &a, const STLpoint &b, const STLpoint &c, unsigned short attrib)
Construct from components.
STLtriangle (istream &)
Construct from istream (read binary)
const STLpoint & normal () const
const STLpoint & a () const
const STLpoint & b () const
const STLpoint & c () const
unsigned short attrib () const
void read (istream &)
Read from istream (binary)
void write (ostream &)
Write to ostream (binary)
STLtriangle ()
Construct null.
STLtriangle (const STLpoint &normal, const STLpoint &a, const STLpoint &b, const STLpoint &c, unsigned short region)
Construct from components.
STLtriangle (istream &)
Construct from istream (read binary)
const STLpoint & a () const
const STLpoint & b () const
const STLpoint & c () const
unsigned short region () const
void read (istream &)
Read from istream (binary)
void write (ostream &)
Write to istream (binary)
Friends
Ostream & operator<< (Ostream &, const STLtriangle &)
Ostream & operator<< (Ostream &, const STLtriangle &)
Detailed Description
A triangle representation for STL files.
Source files
STLtriangle.H
STLtriangleI.H
Source files
STLtriangle.H
STLtriangleI.H
Definition at line 50 of file STLtriangle.H.
Constructor & Destructor Documentation
STLtriangle() [1/6]
STLtriangle () inline
Construct null.
Definition at line 28 of file STLtriangleI.H.
STLtriangle() [2/6]
STLtriangle (const STLpoint & normal, const STLpoint & a, const STLpoint & b, const STLpoint & c, unsigned short attrib) inline
Construct from components.
Definition at line 33 of file STLtriangleI.H.
STLtriangle() [3/6]
STLtriangle (istream & is) inline
Construct from istream (read binary)
Construct from istream (binary)
Definition at line 49 of file STLtriangleI.H.
References STLtriangle::read().
STLtriangle() [4/6]
STLtriangle () inline
Construct null.
STLtriangle() [5/6]
STLtriangle (const STLpoint & normal, const STLpoint & a, const STLpoint & b, const STLpoint & c, unsigned short region) inline
Construct from components.
STLtriangle() [6/6]
STLtriangle (istream &) inline
Construct from istream (read binary)
Member Function Documentation
normal()
const Foam::STLpoint & normal () const inline
Definition at line 57 of file STLtriangleI.H.
a() [1/2]
const STLpoint & a () const inline
Definition at line 63 of file STLtriangleI.H.
b() [1/2]
const STLpoint & b () const inline
Definition at line 69 of file STLtriangleI.H.
c() [1/2]
const STLpoint & c () const inline
Definition at line 75 of file STLtriangleI.H.
attrib()
unsigned short attrib () const inline
Definition at line 81 of file STLtriangleI.H.
read() [1/2]
void read (istream & is) inline
Read from istream (binary)
Definition at line 87 of file STLtriangleI.H.
Referenced by STLtriangle::region(), and STLtriangle::STLtriangle().
write() [1/2]
void write (ostream & os) inline
Write to ostream (binary)
Definition at line 94 of file STLtriangleI.H.
References Foam::operator<<(), and token::SPACE.
Referenced by STLtriangle::region().
a() [2/2]
const STLpoint& a () const inline
b() [2/2]
const STLpoint& b () const inline
c() [2/2]
const STLpoint& c () const inline
region()
unsigned short region () const inline
Definition at line 82 of file STLtriangleI.H.
References STLtriangle::read(), and STLtriangle::write().
read() [2/2]
void read (istream &) inline
Read from istream (binary)
write() [2/2]
void write (ostream &) inline
Write to istream (binary)
Friends And Related Function Documentation
operator<< [1/2]
Ostream& operator<< (Ostream & os, const STLtriangle & stlt) friend
Definition at line 103 of file STLtriangleI.H.
operator<< [2/2]
Ostream& operator<< (Ostream & os, const STLtriangle & stlt) friend
Definition at line 103 of file STLtriangleI.H.
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/stl/STLtriangle.H
src/surfMesh/surfaceFormats/stl/STLtriangleI.H