OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceFormatsCore Class Reference
A collection of helper functions for reading/writing surface formats.
Public Member Functions
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Static Public Member Functions
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Static Public Attributes
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
A collection of helper functions for reading/writing surface formats.
Source files
surfaceFormatsCore.H
surfaceFormatsCore.C
Definition at line 60 of file surfaceFormatsCore.H.
Constructor & Destructor Documentation
surfaceFormatsCore()
surfaceFormatsCore ()
Construct null.
Definition at line 190 of file surfaceFormatsCore.C.
Referenced by surfaceFormatsCore::oneZone().
~surfaceFormatsCore()
~surfaceFormatsCore () virtual
Destructor.
Definition at line 196 of file surfaceFormatsCore.C.
Referenced by surfaceFormatsCore::oneZone().
Member Function Documentation
oneZone()
static List<surfZone> oneZone (const Container & container, const word & name = "zone0") inline static protected
Return a list with a single entry,.
the size corresponds to that of the container
Definition at line 68 of file surfaceFormatsCore.H.
References surfaceFormatsCore::checkSupport(), surfaceFormatsCore::findMeshFile(), surfaceFormatsCore::findMeshInstance(), surfaceFormatsCore::getLineNoComment(), surfaceFormatsCore::localMeshFileName(), Foam::name(), surfaceFormatsCore::nativeExt, surfaceFormatsCore::surfaceFormatsCore(), and surfaceFormatsCore::~surfaceFormatsCore().
getLineNoComment()
Foam::string getLineNoComment (IFstream & is) static protected
Read non-comment line.
Definition at line 41 of file surfaceFormatsCore.C.
References surfaceFormatsCore::checkSupport(), TimePaths::constant(), surfaceRegistry::defaultName, surfaceFormatsCore::findMeshFile(), surfaceFormatsCore::findMeshInstance(), ISstream::getLine(), IOstream::good(), Foam::isFile(), surfaceFormatsCore::localMeshFileName(), surfMesh::meshSubDir, Foam::name(), surfaceFormatsCore::nativeExt, Time::path(), surfaceRegistry::prefix, List< T >::size(), TimeState::timeOutputValue(), and Time::times().
Referenced by surfaceFormatsCore::oneZone(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
checkSupport()
bool checkSupport (const wordHashSet & available, const word & ext, const bool verbose, const word & functionName) static
Definition at line 157 of file surfaceFormatsCore.C.
References Foam::endl(), forAll, HashTable< T, Key, Hash >::found(), Foam::Info, Foam::nl, HashTable< T, Key, Hash >::toc(), and List< T >::xfer().
Referenced by surfaceFormatsCore::getLineNoComment(), and surfaceFormatsCore::oneZone().
localMeshFileName()
static fileName localMeshFileName (const word & surfName = "") static
Return the local file name (within time directory)
NEEDS FIXING
Referenced by surfaceFormatsCore::getLineNoComment(), and surfaceFormatsCore::oneZone().
findMeshInstance()
static fileName findMeshInstance (const Time & , const word & surfName = "") static
Find instance with surfName.
NEEDS FIXING
Referenced by surfaceFormatsCore::getLineNoComment(), and surfaceFormatsCore::oneZone().
findMeshFile()
static fileName findMeshFile (const Time & , const word & surfName = "") static
Find mesh file with surfName.
NEEDS FIXING
Referenced by surfaceFormatsCore::getLineNoComment(), and surfaceFormatsCore::oneZone().
Member Data Documentation
nativeExt
Foam::word nativeExt static
The file extension corresponding to 'native' surface format.
Normally "ofs" (mnemonic: OF = OpenFOAM, S = Surface)
Definition at line 86 of file surfaceFormatsCore.H.
Referenced by surfaceFormatsCore::getLineNoComment(), and surfaceFormatsCore::oneZone().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/surfaceFormatsCore.H
src/surfMesh/surfaceFormats/surfaceFormatsCore.C