OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
OFSsurfaceFormatCore Class Reference
Internal class used by the OFSsurfaceFormat.
Static Protected Member Functions
static void writeHeader (Ostream &, const pointField &, const UList< surfZone > &)
Write header information and surfZoneList.
Detailed Description
Internal class used by the OFSsurfaceFormat.
Source files
OFSsurfaceFormatCore.H
OFSsurfaceFormatCore.C
Definition at line 53 of file OFSsurfaceFormatCore.H.
Member Function Documentation
writeHeader()
void writeHeader (Ostream & os, const pointField & pointLst, const UList< surfZone > & zoneLst) static protected
Write header information and surfZoneList.
Definition at line 32 of file OFSsurfaceFormatCore.C.
References Foam::decrIndent(), forAll, Foam::incrIndent(), Foam::nl, and UList< T >::size().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/ofs/OFSsurfaceFormatCore.H
src/surfMesh/surfaceFormats/ofs/OFSsurfaceFormatCore.C