OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
WRLsurfaceFormatCore Class Reference
Internal class used by the WRLsurfaceFormat.
Static Protected Member Functions
static void writeHeader (Ostream &, const pointField &, const label nFaces, const UList< surfZone > &)
Write file header.
static void writeAppearance (Ostream &)
Write appearance node.
Detailed Description
Internal class used by the WRLsurfaceFormat.
Source files
WRLsurfaceFormatCore.H
WRLsurfaceFormatCore.C
Definition at line 52 of file WRLsurfaceFormatCore.H.
Member Function Documentation
writeHeader()
void writeHeader (Ostream & os, const pointField & pointLst, const label nFaces, const UList< surfZone > & zoneLst) static protected
Write file header.
Definition at line 32 of file WRLsurfaceFormatCore.C.
References forAll, Foam::nl, List< T >::size(), UList< T >::size(), and WRLsurfaceFormatCore::writeAppearance().
writeAppearance()
void writeAppearance (Ostream & os) static protected
Write appearance node.
Definition at line 56 of file WRLsurfaceFormatCore.C.
Referenced by WRLsurfaceFormatCore::writeHeader().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/wrl/WRLsurfaceFormatCore.H
src/surfMesh/surfaceFormats/wrl/WRLsurfaceFormatCore.C