OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gradientEnergyFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a gradient condition for internal energy, where the gradient is calculated using:
Public Member Functions
TypeName ("gradientEnergy")
Runtime type information.
gradientEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
gradientEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given gradientEnergyFvPatchScalarField.
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Detailed Description
This boundary condition provides a gradient condition for internal energy, where the gradient is calculated using:
where
= energy at patch faces [J]
= energy at patch internal cells [J]
= pressure [bar]
= temperature [K]
= specific heat [J/kg/K]
= distance between patch face and internal cell centres [m]
Patch usage
Example of the boundary condition specification:
    myPatch
    {
        type            gradientEnergy;
        gradient        uniform 10;
    }
See also
Foam::fixedGradientFvPatchField
Source files
gradientEnergyFvPatchScalarField.H
gradientEnergyFvPatchScalarField.C
Definition at line 104 of file gradientEnergyFvPatchScalarField.H.
Constructor & Destructor Documentation
gradientEnergyFvPatchScalarField() [1/5]
gradientEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file gradientEnergyFvPatchScalarField.C.
Referenced by gradientEnergyFvPatchScalarField::clone(), and gradientEnergyFvPatchScalarField::gradientEnergyFvPatchScalarField().
gradientEnergyFvPatchScalarField() [2/5]
gradientEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 60 of file gradientEnergyFvPatchScalarField.C.
References gradientEnergyFvPatchScalarField::gradientEnergyFvPatchScalarField().
gradientEnergyFvPatchScalarField() [3/5]
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given gradientEnergyFvPatchScalarField.
onto a new patch
Definition at line 47 of file gradientEnergyFvPatchScalarField.C.
References gradientEnergyFvPatchScalarField::gradientEnergyFvPatchScalarField().
gradientEnergyFvPatchScalarField() [4/5]
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 72 of file gradientEnergyFvPatchScalarField.C.
References gradientEnergyFvPatchScalarField::gradientEnergyFvPatchScalarField().
gradientEnergyFvPatchScalarField() [5/5]
gradientEnergyFvPatchScalarField (const gradientEnergyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 82 of file gradientEnergyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("gradientEnergy")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 149 of file gradientEnergyFvPatchScalarField.H.
References gradientEnergyFvPatchScalarField::gradientEnergyFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 166 of file gradientEnergyFvPatchScalarField.H.
References gradientEnergyFvPatchScalarField::gradientEnergyFvPatchScalarField(), and gradientEnergyFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 93 of file gradientEnergyFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicThermo::Cpv(), fvPatchField< Type >::evaluate(), basicThermo::he(), basicThermo::lookupThermo(), Foam::makePatchTypeField(), basicThermo::p(), patchi, fvPatchField< Type >::snGrad(), and basicThermo::T().
Referenced by gradientEnergyFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/derivedFvPatchFields/gradientEnergy/gradientEnergyFvPatchScalarField.H
src/thermophysicalModels/basic/derivedFvPatchFields/gradientEnergy/gradientEnergyFvPatchScalarField.C