OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fixedEnergyFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a fixed condition for internal energy.
Public Member Functions
TypeName ("fixedEnergy")
Runtime type information.
fixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given fixedEnergyFvPatchScalarField.
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Detailed Description
This boundary condition provides a fixed condition for internal energy.
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            fixedEnergy;
    value           uniform 100;
}
See also
Foam::fixedValueFvPatchField
Source files
fixedEnergyFvPatchScalarField.H
fixedEnergyFvPatchScalarField.C
Definition at line 65 of file fixedEnergyFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedEnergyFvPatchScalarField() [1/5]
fixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fixedEnergyFvPatchScalarField.C.
Referenced by fixedEnergyFvPatchScalarField::clone(), and fixedEnergyFvPatchScalarField::fixedEnergyFvPatchScalarField().
fixedEnergyFvPatchScalarField() [2/5]
fixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 60 of file fixedEnergyFvPatchScalarField.C.
References fixedEnergyFvPatchScalarField::fixedEnergyFvPatchScalarField().
fixedEnergyFvPatchScalarField() [3/5]
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given fixedEnergyFvPatchScalarField.
onto a new patch
Definition at line 47 of file fixedEnergyFvPatchScalarField.C.
References fixedEnergyFvPatchScalarField::fixedEnergyFvPatchScalarField().
fixedEnergyFvPatchScalarField() [4/5]
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 72 of file fixedEnergyFvPatchScalarField.C.
References fixedEnergyFvPatchScalarField::fixedEnergyFvPatchScalarField().
fixedEnergyFvPatchScalarField() [5/5]
fixedEnergyFvPatchScalarField (const fixedEnergyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 82 of file fixedEnergyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedEnergy")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 110 of file fixedEnergyFvPatchScalarField.H.
References fixedEnergyFvPatchScalarField::fixedEnergyFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 127 of file fixedEnergyFvPatchScalarField.H.
References fixedEnergyFvPatchScalarField::fixedEnergyFvPatchScalarField(), and fixedEnergyFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 93 of file fixedEnergyFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatchField< Type >::evaluate(), basicThermo::he(), basicThermo::lookupThermo(), Foam::makePatchTypeField(), Foam::operator==(), basicThermo::p(), patchi, and basicThermo::T().
Referenced by fixedEnergyFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/derivedFvPatchFields/fixedEnergy/fixedEnergyFvPatchScalarField.H
src/thermophysicalModels/basic/derivedFvPatchFields/fixedEnergy/fixedEnergyFvPatchScalarField.C