OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
chemistryModel< CompType, ThermoType > Class Template Reference
Extends base chemistry model by adding a thermo package, and ODE functions. Introduces chemistry equation system and evaluation of chemical source terms.
Public Member Functions
TypeName ("chemistryModel")
Runtime type information.
chemistryModel (const fvMesh &mesh)
Construct from mesh.
virtual ~chemistryModel ()
Destructor.
const PtrList< Reaction< ThermoType > > & reactions () const
The reactions.
const PtrList< ThermoType > & specieThermo () const
Thermodynamic data of the species.
label nSpecie () const
The number of species.
label nReaction () const
The number of reactions.
virtual tmp< scalarField > omega (const scalarField &c, const scalar T, const scalar p) const
dc/dt = omega, rate of change in concentration, for each species
virtual scalar omega (const Reaction< ThermoType > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for reaction r and the reference.
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for iReaction and the reference.
virtual void calculate ()
Calculates the reaction rates.
const DimensionedField< scalar, volMesh > & RR (const label i) const
Return const access to the chemical source terms for specie, i.
virtual DimensionedField< scalar, volMesh > & RR (const label i)
Return non const access to chemical source terms [kg/m3/s].
virtual tmp< DimensionedField< scalar, volMesh > > calculateRR (const label reactionI, const label specieI) const
Return reaction rate of the specieI in reactionI.
virtual scalar solve (const scalar deltaT)
Solve the reaction system for the given time step.
virtual scalar solve (const scalarField &deltaT)
Solve the reaction system for the given time step.
virtual tmp< volScalarField > tc () const
Return the chemical time scale.
virtual tmp< volScalarField > Sh () const
Return source for enthalpy equation [kg/m/s3].
virtual tmp< volScalarField > dQ () const
Return the heat release, i.e. enthalpy/sec [kg/m2/s3].
virtual label nEqns () const
Number of ODE's to solve.
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const
Calculate the derivatives in dydx.
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const
Calculate the Jacobian of the system.
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
template<class DeltaTType >
Foam::scalar solve (const DeltaTType &deltaT)
Public Member Functions inherited from ODESystem
ODESystem ()
Construct null.
virtual ~ODESystem ()
Destructor.
Protected Types
typedef ThermoType thermoType
Protected Member Functions
PtrList< DimensionedField< scalar, volMesh > > & RR ()
Write access to chemical source terms.
Protected Attributes
PtrList< volScalarField > & Y_
Reference to the field of specie mass fractions.
const PtrList< Reaction< ThermoType > > & reactions_
Reactions.
const PtrList< ThermoType > & specieThermo_
Thermodynamic data of the species.
label nSpecie_
Number of species.
label nReaction_
Number of reactions.
PtrList< DimensionedField< scalar, volMesh > > RR_
List of reaction rate per specie [kg/m3/s].
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryModel< CompType, ThermoType >
Extends base chemistry model by adding a thermo package, and ODE functions. Introduces chemistry equation system and evaluation of chemical source terms.
Source files
chemistryModel.H
chemistryModelI.H
chemistryModel.C
Definition at line 59 of file chemistryModel.H.
Member Typedef Documentation
thermoType
typedef ThermoType thermoType protected
Definition at line 80 of file chemistryModel.H.
Constructor & Destructor Documentation
chemistryModel()
chemistryModel (const fvMesh & mesh)
Construct from mesh.
Definition at line 34 of file chemistryModel.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, mesh, name(), fvMesh::time(), and Time::timeName().
~chemistryModel()
~chemistryModel () virtual
Destructor.
Definition at line 86 of file chemistryModel.C.
References chemistryModel< CompType, ThermoType >::omega().
Member Function Documentation
RR() [1/3]
Foam::PtrList< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > & RR () inline protected
Write access to chemical source terms.
(e.g. for multi-chemistry model)
Definition at line 33 of file chemistryModelI.H.
Referenced by chemistryModel< CompType, ThermoType >::nReaction(), and chemistryModel< CompType, ThermoType >::RR().
TypeName()
TypeName ("chemistryModel< CompType, ThermoType >")
Runtime type information.
reactions()
const Foam::PtrList< Foam::Reaction< ThermoType > > & reactions () const inline
The reactions.
Definition at line 41 of file chemistryModelI.H.
specieThermo()
const Foam::PtrList< ThermoType > & specieThermo () const inline
Thermodynamic data of the species.
Definition at line 49 of file chemistryModelI.H.
nSpecie()
Foam::label nSpecie () const inline
The number of species.
Definition at line 57 of file chemistryModelI.H.
nReaction()
Foam::label nReaction () const inline
The number of reactions.
Definition at line 65 of file chemistryModelI.H.
References chemistryModel< CompType, ThermoType >::RR().
omega() [1/2]
Foam::tmp< Foam::scalarField > omega (const scalarField & c, const scalar T, const scalar p) const virtual
dc/dt = omega, rate of change in concentration, for each species
Definition at line 95 of file chemistryModel.C.
References forAll, Reaction< ReactionThermo >::lhs(), chemistryModel< CompType, ThermoType >::omegaI(), R, Reaction< ReactionThermo >::rhs(), s(), and scalarField().
Referenced by chemistryModel< CompType, ThermoType >::omegaI(), and chemistryModel< CompType, ThermoType >::~chemistryModel().
omega() [2/2]
Foam::scalar omega (const Reaction< ThermoType > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for reaction r and the reference.
species and charateristic times
Definition at line 159 of file chemistryModel.C.
References Foam::constant::physicoChemical::c2, chemistryModel< CompType, ThermoType >::derivatives(), Foam::exp(), Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::kr(), Reaction< ReactionThermo >::lhs(), Foam::max(), Foam::pow(), Reaction< ReactionThermo >::rhs(), and s().
omegaI()
Foam::scalar omegaI (label iReaction, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for iReaction and the reference.
species and charateristic times
Definition at line 137 of file chemistryModel.C.
References chemistryModel< CompType, ThermoType >::omega(), and R.
Referenced by chemistryModel< CompType, ThermoType >::omega().
calculate()
void calculate () virtual
Calculates the reaction rates.
Definition at line 712 of file chemistryModel.C.
References Foam::constant::universal::c, forAll, mesh, Foam::constant::mathematical::pi(), rho, thermo, and timeName.
RR() [2/3]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RR (const label i) const inline
Return const access to the chemical source terms for specie, i.
Definition at line 74 of file chemistryModelI.H.
References chemistryModel< CompType, ThermoType >::RR().
RR() [3/3]
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RR (const label i) virtual
Return non const access to chemical source terms [kg/m3/s].
Definition at line 84 of file chemistryModelI.H.
calculateRR()
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > calculateRR (const label reactionI, const label specieI) const virtual
Return reaction rate of the specieI in reactionI.
Definition at line 632 of file chemistryModel.C.
References Foam::constant::universal::c, Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, mesh, Foam::constant::mathematical::pi(), rho, thermo, and timeName.
Referenced by chemistryModel< CompType, ThermoType >::nEqns().
solve() [1/4]
Foam::scalar solve (const scalar deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Definition at line 832 of file chemistryModel.C.
References Foam::min(), and solve().
solve() [2/4]
Foam::scalar solve (const scalarField & deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Definition at line 847 of file chemistryModel.C.
tc()
Foam::tmp< Foam::volScalarField > tc () const virtual
Return the chemical time scale.
Definition at line 463 of file chemistryModel.C.
References Foam::constant::universal::c, Foam::dimTime, forAll, mesh, Foam::constant::mathematical::pi(), rho, Reaction< ReactionThermo >::rhs(), s(), thermo, and timeName.
Sh()
Foam::tmp< Foam::volScalarField > Sh () const virtual
Return source for enthalpy equation [kg/m/s3].
Definition at line 548 of file chemistryModel.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAll, and Sh.
dQ()
Foam::tmp< Foam::volScalarField > dQ () const virtual
Return the heat release, i.e. enthalpy/sec [kg/m2/s3].
Definition at line 590 of file chemistryModel.C.
References Foam::dimEnergy, GeometricField< Type, PatchField, GeoMesh >::dimensionedInternalField(), Foam::dimTime, dQ, and Sh.
nEqns()
Foam::label nEqns () const virtual
Number of ODE's to solve.
Implements ODESystem.
Definition at line 622 of file chemistryModel.C.
References chemistryModel< CompType, ThermoType >::calculateRR().
derivatives()
void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const virtual
Calculate the derivatives in dydx.
Implements ODESystem.
Definition at line 277 of file chemistryModel.C.
References cp, chemistryModel< CompType, ThermoType >::jacobian(), and rho.
Referenced by chemistryModel< CompType, ThermoType >::omega().
jacobian()
void jacobian (const scalar x, const scalarField & y, scalarField & dfdx, scalarSquareMatrix & dfdy) const virtual
Calculate the Jacobian of the system.
Need by the stiff-system solvers
Implements ODESystem.
Definition at line 322 of file chemistryModel.C.
References Foam::constant::physicoChemical::c2, delta, forAll, Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::kr(), Reaction< ReactionThermo >::lhs(), Foam::max(), nSpecie, Foam::pow(), and Reaction< ReactionThermo >::rhs().
Referenced by chemistryModel< CompType, ThermoType >::derivatives().
solve() [3/4]
void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Definition at line 857 of file chemistryModel.C.
References notImplemented.
solve() [4/4]
Foam::scalar solve (const DeltaTType & deltaT)
Definition at line 762 of file chemistryModel.C.
References Foam::constant::universal::c, correct, forAll, mesh, Foam::min(), Foam::constant::mathematical::pi(), rho, solve(), thermo, and timeName.
Member Data Documentation
Y_
PtrList<volScalarField>& Y_ protected
Reference to the field of specie mass fractions.
Definition at line 85 of file chemistryModel.H.
reactions_
const PtrList<Reaction<ThermoType> >& reactions_ protected
Reactions.
Definition at line 88 of file chemistryModel.H.
specieThermo_
const PtrList<ThermoType>& specieThermo_ protected
Thermodynamic data of the species.
Definition at line 91 of file chemistryModel.H.
nSpecie_
label nSpecie_ protected
Number of species.
Definition at line 94 of file chemistryModel.H.
nReaction_
label nReaction_ protected
Number of reactions.
Definition at line 97 of file chemistryModel.H.
RR_
PtrList<DimensionedField<scalar, volMesh> > RR_ protected
List of reaction rate per specie [kg/m3/s].
Definition at line 100 of file chemistryModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/chemistryModel/chemistryModel.H
src/thermophysicalModels/chemistryModel/chemistryModel/chemistryModel/chemistryModel.C
src/thermophysicalModels/chemistryModel/chemistryModel/chemistryModel/chemistryModelI.H