OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mixedEnergyFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a mixed condition for internal energy.
Public Member Functions
TypeName ("mixedEnergy")
Runtime type information.
mixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mixedEnergyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given mixedEnergyFvPatchScalarField.
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Detailed Description
This boundary condition provides a mixed condition for internal energy.
See also
Foam::mixedFvPatchField
Source files
mixedEnergyFvPatchScalarField.H
mixedEnergyFvPatchScalarField.C
Definition at line 54 of file mixedEnergyFvPatchScalarField.H.
Constructor & Destructor Documentation
mixedEnergyFvPatchScalarField() [1/5]
mixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file mixedEnergyFvPatchScalarField.C.
Referenced by mixedEnergyFvPatchScalarField::clone(), and mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField().
mixedEnergyFvPatchScalarField() [2/5]
mixedEnergyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 65 of file mixedEnergyFvPatchScalarField.C.
References mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField().
mixedEnergyFvPatchScalarField() [3/5]
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given mixedEnergyFvPatchScalarField.
onto a new patch
Definition at line 52 of file mixedEnergyFvPatchScalarField.C.
References mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField().
mixedEnergyFvPatchScalarField() [4/5]
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 77 of file mixedEnergyFvPatchScalarField.C.
References mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField().
mixedEnergyFvPatchScalarField() [5/5]
mixedEnergyFvPatchScalarField (const mixedEnergyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 87 of file mixedEnergyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("mixedEnergy")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 99 of file mixedEnergyFvPatchScalarField.H.
References mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 116 of file mixedEnergyFvPatchScalarField.H.
References mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField(), and mixedEnergyFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 98 of file mixedEnergyFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicThermo::Cpv(), basicThermo::he(), basicThermo::lookupThermo(), Foam::makePatchTypeField(), basicThermo::p(), patchi, and basicThermo::T().
Referenced by mixedEnergyFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/derivedFvPatchFields/mixedEnergy/mixedEnergyFvPatchScalarField.H
src/thermophysicalModels/basic/derivedFvPatchFields/mixedEnergy/mixedEnergyFvPatchScalarField.C