OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfZone Class Reference
A surface zone on a MeshedSurface.
Public Member Functions
ClassName ("surfZone")
Runtime type information.
surfZone ()
Construct null.
surfZone (const word &name, const label size, const label start, const label index, const word &geometricType=word::null)
Construct from components.
surfZone (Istream &is, const label index)
Construct from Istream.
surfZone (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
surfZone (const surfZone &)
Construct as copy.
surfZone (const surfZone &, const label index)
Construct from another zone, resetting the index.
autoPtr< surfZone > clone () const
Return clone.
label start () const
Return start label of this zone in the face list.
label & start ()
Return start label of this zone in the face list.
label size () const
Return size of this zone in the face list.
label & size ()
Return size of this zone in the face list.
void write (Ostream &) const
Write.
void writeDict (Ostream &) const
Write dictionary.
bool operator!= (const surfZone &) const
bool operator== (const surfZone &) const
compare.
Public Member Functions inherited from surfZoneIdentifier
surfZoneIdentifier ()
Construct null.
surfZoneIdentifier (const word &name, const label index, const word &geometricType=word::null)
Construct from components.
surfZoneIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
surfZoneIdentifier (const surfZoneIdentifier &, const label index)
Construct from another zone identifier, resetting the index.
virtual ~surfZoneIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & geometricType () const
Return the geometric type of the zone.
word & geometricType ()
Return the geometric type of the zone for modification.
label index () const
Return the index of this zone in the surface mesh.
void write (Ostream &) const
Write surfZoneIdentifier as a dictionary.
Static Public Member Functions
static autoPtr< surfZone > New (Istream &is)
Friends
Istream & operator>> (Istream &, surfZone &)
Ostream & operator<< (Ostream &, const surfZone &)
Detailed Description
A surface zone on a MeshedSurface.
Similar in concept to a faceZone, but the face list is contiguous.
Source files
surfZone.H
surfZone.C
Definition at line 62 of file surfZone.H.
Constructor & Destructor Documentation
surfZone() [1/6]
surfZone ()
Construct null.
Definition at line 40 of file surfZone.C.
Referenced by surfZone::New(), Foam::operator>>(), and surfZone::surfZone().
surfZone() [2/6]
surfZone (const word & name, const label size, const label start, const label index, const word & geometricType = word::null)
Construct from components.
Definition at line 49 of file surfZone.C.
surfZone() [3/6]
surfZone (Istream & is, const label index)
Construct from Istream.
Definition at line 63 of file surfZone.C.
References dict, surfZoneIdentifier::name(), and surfZone::surfZone().
surfZone() [4/6]
surfZone (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 77 of file surfZone.C.
surfZone() [5/6]
surfZone (const surfZone & zone)
Construct as copy.
Definition at line 89 of file surfZone.C.
surfZone() [6/6]
surfZone (const surfZone & zone, const label index)
Construct from another zone, resetting the index.
Definition at line 97 of file surfZone.C.
Member Function Documentation
ClassName()
ClassName ("surfZone")
Runtime type information.
clone()
autoPtr<surfZone> clone () const inline
Return clone.
Definition at line 114 of file surfZone.H.
References notImplemented.
New()
static autoPtr<surfZone> New (Istream & is) inline static
Definition at line 120 of file surfZone.H.
References dict, surfZoneIdentifier::name(), and surfZone::surfZone().
start() [1/2]
label start () const inline
Return start label of this zone in the face list.
Definition at line 132 of file surfZone.H.
Referenced by surfZone::operator==(), MeshedSurface< Foam::face >::remapFaces(), UnsortedMeshedSurface< Face >::setZones(), MeshedSurface< Foam::face >::subsetMesh(), AC3DsurfaceFormat< Face >::write(), and surfZone::writeDict().
start() [2/2]
label& start () inline
Return start label of this zone in the face list.
Definition at line 138 of file surfZone.H.
size() [1/2]
label size () const inline
Return size of this zone in the face list.
Definition at line 144 of file surfZone.H.
Referenced by surfZone::operator==(), MeshedSurface< Foam::face >::remapFaces(), UnsortedMeshedSurface< Face >::setZones(), MeshedSurface< Foam::face >::subsetMesh(), AC3DsurfaceFormat< Face >::write(), and surfZone::writeDict().
size() [2/2]
label& size () inline
Return size of this zone in the face list.
Definition at line 150 of file surfZone.H.
References surfZone::operator!=(), surfZone::operator<<, surfZone::operator==(), surfZone::operator>>, surfZone::write(), and surfZone::writeDict().
write()
void write (Ostream & os) const
Write.
Definition at line 107 of file surfZone.C.
References surfZone::writeDict().
Referenced by Foam::operator<<(), and surfZone::size().
writeDict()
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 113 of file surfZone.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::incrIndent(), Foam::indent(), surfZoneIdentifier::name(), Foam::nl, surfZone::size(), surfZone::start(), surfZoneIdentifier::write(), and Ostream::writeKeyword().
Referenced by surfZone::size(), and surfZone::write().
operator!=()
bool operator!= (const surfZone & rhs) const
Definition at line 128 of file surfZone.C.
Referenced by surfZone::size().
operator==()
bool operator== (const surfZone & rhs) const
compare.
Definition at line 134 of file surfZone.C.
References surfZoneIdentifier::geometricType(), surfZone::size(), and surfZone::start().
Referenced by surfZone::size().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , surfZone &) friend
Referenced by surfZone::size().
operator<<
Ostream& operator<< (Ostream & , const surfZone &) friend
Referenced by surfZone::size().
The documentation for this class was generated from the following files:
src/surfMesh/surfZone/surfZone/surfZone.H
src/surfMesh/surfZone/surfZone/surfZone.C