OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Chung Class Reference
Chung compressibility model.
Public Member Functions
TypeName ("Chung")
Runtime type information.
Chung (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
construct from components
~Chung ()
Destructor.
void correct ()
Correct the Chung compressibility.
bool read (const dictionary &compressibilityProperties)
Read transportProperties dictionary.
Public Member Functions inherited from barotropicCompressibilityModel
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
virtual ~barotropicCompressibilityModel ()
Destructor.
const dictionary & compressibilityProperties () const
Return the phase transport properties dictionary.
const volScalarField & psi () const
Return the compressibility.
Additional Inherited Members
Static Public Member Functions inherited from barotropicCompressibilityModel
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Return a reference to the selected compressibility model.
Protected Member Functions inherited from barotropicCompressibilityModel
barotropicCompressibilityModel (const barotropicCompressibilityModel &)
Disallow copy construct.
void operator= (const barotropicCompressibilityModel &)
Disallow default bitwise assignment.
Protected Attributes inherited from barotropicCompressibilityModel
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
Chung compressibility model.
Source files
Chung.H
Chung.C
Definition at line 51 of file Chung.H.
Constructor & Destructor Documentation
Chung()
Chung (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
construct from components
Definition at line 48 of file Chung.C.
References correct.
~Chung()
~Chung () inline
Destructor.
Definition at line 82 of file Chung.H.
References Chung::correct(), and Chung::read().
Member Function Documentation
TypeName()
TypeName ("Chung")
Runtime type information.
correct()
void correct () virtual
Correct the Chung compressibility.
Implements barotropicCompressibilityModel.
Definition at line 66 of file Chung.C.
References Chung::read(), Foam::sqr(), and Foam::sqrt().
Referenced by Chung::~Chung().
read()
bool read (const dictionary & compressibilityProperties) virtual
Read transportProperties dictionary.
Implements barotropicCompressibilityModel.
Definition at line 86 of file Chung.C.
References barotropicCompressibilityModel::read().
Referenced by Chung::correct(), and Chung::~Chung().
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/Chung/Chung.H
src/thermophysicalModels/barotropicCompressibilityModel/Chung/Chung.C