OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
liquidMixtureProperties Class Reference
A mixture of liquids.
Public Member Functions
liquidMixtureProperties (const dictionary &dict)
Construct from dictionary.
liquidMixtureProperties (const liquidMixtureProperties &lm)
Construct copy.
virtual autoPtr< liquidMixtureProperties > clone () const
Construct and return a clone.
virtual ~liquidMixtureProperties ()
Destructor.
const List< word > & components () const
Return the liquid names.
const PtrList< liquidProperties > & properties () const
Return the liquid properties.
label size () const
Return the number of liquids in the mixture.
scalar Tc (const scalarField &x) const
Calculate the critical temperature of mixture.
scalar pvInvert (const scalar p, const scalarField &x) const
Invert the vapour pressure relationship to retrieve the boiling.
scalar Tpc (const scalarField &x) const
Return pseudocritical temperature according to Kay's rule.
scalar Ppc (const scalarField &x) const
Return pseudocritical pressure (modified Prausnitz and Gunn)
scalar Tpt (const scalarField &x) const
Return pseudo triple point temperature (mole averaged formulation)
scalar omega (const scalarField &x) const
Return mixture accentric factor.
scalarField Xs (const scalar p, const scalar Tg, const scalar Tl, const scalarField &xg, const scalarField &xl) const
Return the surface molar fractions.
scalar W (const scalarField &x) const
Calculate the mean molecular weight [kg/kmol].
scalarField Y (const scalarField &X) const
Returns the mass fractions, given mole fractions.
scalarField X (const scalarField &Y) const
Returns the mole fractions, given mass fractions.
scalar rho (const scalar p, const scalar T, const scalarField &x) const
Calculate the mixture density [kg/m^3].
scalar pv (const scalar p, const scalar T, const scalarField &x) const
Calculate the mixture vapour pressure [Pa].
scalar hl (const scalar p, const scalar T, const scalarField &x) const
Calculate the mixture latent heat [J/kg].
scalar Cp (const scalar p, const scalar T, const scalarField &x) const
Calculate the mixture heat capacity [J/(kg K)].
scalar sigma (const scalar p, const scalar T, const scalarField &x) const
Estimate mixture surface tension [N/m].
scalar mu (const scalar p, const scalar T, const scalarField &x) const
Calculate the mixture viscosity [Pa s].
scalar K (const scalar p, const scalar T, const scalarField &x) const
Estimate thermal conductivity [W/(m K)].
scalar D (const scalar p, const scalar T, const scalarField &x) const
Static Public Member Functions
static autoPtr< liquidMixtureProperties > New (const dictionary &)
Select construct from dictionary.
Detailed Description
A mixture of liquids.
An example of a two component liquid mixture:
    <parentDictionary>
    {
        H2O
        {
            defaultCoeffs   yes;     // employ default coefficients
        }
        C7H16
        {
            defaultCoeffs   no;
            C7H16Coeffs
            {
                ... user defined properties for C7H16
            }
        }
    }
Source files
liquidMixtureProperties.H
liquidMixtureProperties.C
See also
Foam::liquidProperties
Definition at line 74 of file liquidMixtureProperties.H.
Constructor & Destructor Documentation
liquidMixtureProperties() [1/2]
liquidMixtureProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 38 of file liquidMixtureProperties.C.
References forAll, List< T >::setSize(), dictionary::subDict(), and dictionary::toc().
Referenced by liquidMixtureProperties::clone().
liquidMixtureProperties() [2/2]
liquidMixtureProperties (const liquidMixtureProperties & lm)
Construct copy.
Definition at line 60 of file liquidMixtureProperties.C.
References forAll, and liquidMixtureProperties::New().
~liquidMixtureProperties()
virtual ~liquidMixtureProperties () inline virtual
Destructor.
Definition at line 110 of file liquidMixtureProperties.H.
References liquidMixtureProperties::New().
Member Function Documentation
clone()
virtual autoPtr<liquidMixtureProperties> clone () const inline virtual
Construct and return a clone.
Definition at line 100 of file liquidMixtureProperties.H.
References liquidMixtureProperties::liquidMixtureProperties().
New()
Foam::autoPtr< Foam::liquidMixtureProperties > New (const dictionary & thermophysicalProperties) static
Select construct from dictionary.
Definition at line 77 of file liquidMixtureProperties.C.
Referenced by liquidMixtureProperties::liquidMixtureProperties(), SLGThermo::SLGThermo(), and liquidMixtureProperties::~liquidMixtureProperties().
components()
const List<word>& components () const inline
Return the liquid names.
Definition at line 123 of file liquidMixtureProperties.H.
properties()
const PtrList<liquidProperties>& properties () const inline
Return the liquid properties.
Definition at line 129 of file liquidMixtureProperties.H.
Referenced by liquidFilmThermo::initLiquid().
size()
label size () const inline
Return the number of liquids in the mixture.
Definition at line 135 of file liquidMixtureProperties.H.
References liquidMixtureProperties::Cp(), liquidMixtureProperties::D(), liquidMixtureProperties::hl(), liquidMixtureProperties::K(), liquidMixtureProperties::mu(), liquidMixtureProperties::omega(), p, liquidMixtureProperties::Ppc(), liquidMixtureProperties::pv(), liquidMixtureProperties::pvInvert(), liquidMixtureProperties::rho(), liquidMixtureProperties::sigma(), List< T >::size(), Foam::T(), liquidMixtureProperties::Tc(), liquidMixtureProperties::Tpc(), liquidMixtureProperties::Tpt(), liquidMixtureProperties::W(), x, liquidMixtureProperties::X(), liquidMixtureProperties::Xs(), and liquidMixtureProperties::Y().
Tc()
Foam::scalar Tc (const scalarField & x) const
Calculate the critical temperature of mixture.
Definition at line 90 of file liquidMixtureProperties.C.
References forAll.
Referenced by liquidMixtureProperties::Cp(), liquidMixtureProperties::D(), liquidMixtureProperties::hl(), liquidMixtureProperties::K(), liquidMixtureProperties::mu(), liquidMixtureProperties::pv(), liquidMixtureProperties::pvInvert(), liquidMixtureProperties::rho(), liquidMixtureProperties::sigma(), liquidMixtureProperties::size(), and liquidMixtureProperties::Xs().
pvInvert()
Foam::scalar pvInvert (const scalar p, const scalarField & x) const
Invert the vapour pressure relationship to retrieve the boiling.
temperature of the mixture as a function of pressure
Definition at line 119 of file liquidMixtureProperties.C.
References Foam::endl(), Foam::nl, liquidMixtureProperties::pv(), Foam::T(), liquidMixtureProperties::Tc(), liquidMixtureProperties::Tpt(), and WarningIn.
Referenced by liquidMixtureProperties::size(), and liquidMixtureProperties::Tpt().
Tpc()
Foam::scalar Tpc (const scalarField & x) const
Return pseudocritical temperature according to Kay's rule.
Definition at line 168 of file liquidMixtureProperties.C.
References forAll.
Referenced by liquidMixtureProperties::Ppc(), and liquidMixtureProperties::size().
Ppc()
Foam::scalar Ppc (const scalarField & x) const
Return pseudocritical pressure (modified Prausnitz and Gunn)
Definition at line 180 of file liquidMixtureProperties.C.
References forAll, specie::RR, and liquidMixtureProperties::Tpc().
Referenced by liquidMixtureProperties::size().
Tpt()
Foam::scalar Tpt (const scalarField & x) const
Return pseudo triple point temperature (mole averaged formulation)
Definition at line 106 of file liquidMixtureProperties.C.
References forAll, and liquidMixtureProperties::pvInvert().
Referenced by liquidMixtureProperties::pvInvert(), and liquidMixtureProperties::size().
omega()
Foam::scalar omega (const scalarField & x) const
Return mixture accentric factor.
Definition at line 194 of file liquidMixtureProperties.C.
References forAll, and liquidMixtureProperties::Xs().
Referenced by liquidMixtureProperties::size().
Xs()
Foam::scalarField Xs (const scalar p, const scalar Tg, const scalar Tl, const scalarField & xg, const scalarField & xl) const
Return the surface molar fractions.
Definition at line 207 of file liquidMixtureProperties.C.
References forAll, Foam::min(), p, List< T >::size(), and liquidMixtureProperties::Tc().
Referenced by liquidMixtureProperties::omega(), liquidMixtureProperties::sigma(), and liquidMixtureProperties::size().
W()
Foam::scalar W (const scalarField & x) const
Calculate the mean molecular weight [kg/kmol].
from mole fractions
Definition at line 227 of file liquidMixtureProperties.C.
References forAll.
Referenced by liquidMixtureProperties::Cp(), liquidMixtureProperties::hl(), liquidMixtureProperties::pv(), liquidMixtureProperties::rho(), liquidMixtureProperties::size(), and liquidMixtureProperties::Y().
Y()
Foam::scalarField Y (const scalarField & X) const
Returns the mass fractions, given mole fractions.
Definition at line 239 of file liquidMixtureProperties.C.
References forAll, and liquidMixtureProperties::W().
Referenced by liquidMixtureProperties::size().
X()
Foam::scalarField X (const scalarField & Y) const
Returns the mole fractions, given mass fractions.
Definition at line 252 of file liquidMixtureProperties.C.
References forAll, liquidMixtureProperties::rho(), and List< T >::size().
Referenced by SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), and liquidMixtureProperties::size().
rho()
Foam::scalar rho (const scalar p, const scalar T, const scalarField & x) const
Calculate the mixture density [kg/m^3].
Definition at line 268 of file liquidMixtureProperties.C.
References forAll, Foam::min(), liquidMixtureProperties::pv(), liquidMixtureProperties::Tc(), and liquidMixtureProperties::W().
Referenced by SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), liquidMixtureProperties::size(), and liquidMixtureProperties::X().
pv()
Foam::scalar pv (const scalar p, const scalar T, const scalarField & x) const
Calculate the mixture vapour pressure [Pa].
Definition at line 291 of file liquidMixtureProperties.C.
References forAll, liquidMixtureProperties::hl(), Foam::min(), liquidMixtureProperties::Tc(), and liquidMixtureProperties::W().
Referenced by liquidMixtureProperties::pvInvert(), liquidMixtureProperties::rho(), and liquidMixtureProperties::size().
hl()
Foam::scalar hl (const scalar p, const scalar T, const scalarField & x) const
Calculate the mixture latent heat [J/kg].
Definition at line 313 of file liquidMixtureProperties.C.
References liquidMixtureProperties::Cp(), forAll, Foam::min(), liquidMixtureProperties::Tc(), and liquidMixtureProperties::W().
Referenced by liquidMixtureProperties::pv(), and liquidMixtureProperties::size().
Cp()
Foam::scalar Cp (const scalar p, const scalar T, const scalarField & x) const
Calculate the mixture heat capacity [J/(kg K)].
Definition at line 335 of file liquidMixtureProperties.C.
References forAll, Foam::min(), liquidMixtureProperties::sigma(), liquidMixtureProperties::Tc(), and liquidMixtureProperties::W().
Referenced by liquidMixtureProperties::hl(), SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), and liquidMixtureProperties::size().
sigma()
Foam::scalar sigma (const scalar p, const scalar T, const scalarField & x) const
Estimate mixture surface tension [N/m].
Definition at line 357 of file liquidMixtureProperties.C.
References forAll, Foam::min(), liquidMixtureProperties::mu(), p, List< T >::size(), liquidMixtureProperties::Tc(), and liquidMixtureProperties::Xs().
Referenced by liquidMixtureProperties::Cp(), SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), and liquidMixtureProperties::size().
mu()
Foam::scalar mu (const scalar p, const scalar T, const scalarField & x) const
Calculate the mixture viscosity [Pa s].
Definition at line 391 of file liquidMixtureProperties.C.
References Foam::exp(), forAll, liquidMixtureProperties::K(), Foam::log(), Foam::min(), and liquidMixtureProperties::Tc().
Referenced by SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), liquidMixtureProperties::sigma(), and liquidMixtureProperties::size().
K()
Foam::scalar K (const scalar p, const scalar T, const scalarField & x) const
Estimate thermal conductivity [W/(m K)].
Li's method, Eq. 10-12.27 - 10.12-19
Definition at line 413 of file liquidMixtureProperties.C.
References liquidMixtureProperties::D(), forAll, Foam::min(), List< T >::size(), and liquidMixtureProperties::Tc().
Referenced by liquidMixtureProperties::mu(), and liquidMixtureProperties::size().
D()
Foam::scalar D (const scalar p, const scalar T, const scalarField & x) const
Definition at line 462 of file liquidMixtureProperties.C.
References forAll, Foam::min(), and liquidMixtureProperties::Tc().
Referenced by liquidMixtureProperties::K(), and liquidMixtureProperties::size().
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/liquidMixtureProperties/liquidMixtureProperties/liquidMixtureProperties.H
src/thermophysicalModels/properties/liquidMixtureProperties/liquidMixtureProperties/liquidMixtureProperties.C