OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
greyDiffusiveViewFactorFixedValueFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a grey-diffuse condition for radiative heat flux, Qr, for use with the view factor model.
Public Member Functions
TypeName ("greyDiffusiveRadiationViewFactor")
Runtime type information.
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given a.
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarList & Qro ()
Return external radiative heat flux.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from radiationCoupledBase
TypeName ("radiationCoupledBase")
Runtime type information.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity)
Construct from patch, emissivity mode and emissivity.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity, const fvPatchFieldMapper &mapper)
Construct from patch, emissivity mode and emissivity and mapper.
radiationCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
virtual ~radiationCoupledBase ()
Destructor.
word emissivityMethod () const
Method to obtain emissivity.
scalarField emissivity () const
Calculate corresponding emissivity field.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from radiationCoupledBase
enum emissivityMethodType { SOLIDRADIATION, LOOKUP }
Type of supplied emissivity.
Protected Attributes inherited from radiationCoupledBase
const emissivityMethodType method_
How to get emissivity.
scalarField emissivity_
Emissivity.
Detailed Description
This boundary condition provides a grey-diffuse condition for radiative heat flux, Qr, for use with the view factor model.
Patch usage
Property Description Required Default value
Qro external radiative heat flux yes
emissivityMode emissivity mode: solidThermo or lookup yes
Example of the boundary condition specification:
    myPatch
    {
        type            greyDiffusiveRadiationViewFactor;
        Qro             uniform 0;
        emissivityMode  solidThermo;
        value           uniform 0;
    }
See also
Foam::radiation::radiationModel Foam::radiation::viewFactor Foam::radiationCoupledBase Foam::fixedValueFvPatchField
Source files
greyDiffusiveViewFactorFixedValueFvPatchScalarField.H
greyDiffusiveViewFactorFixedValueFvPatchScalarField.C
Definition at line 94 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
Constructor & Destructor Documentation
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [1/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
Referenced by greyDiffusiveViewFactorFixedValueFvPatchScalarField::clone(), and greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField().
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [2/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 69 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References dictionary::found(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), scalarField(), and fvPatch::size().
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [3/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given a.
greyDiffusiveViewFactorFixedValueFvPatchScalarField onto a new patch
Definition at line 49 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField().
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [4/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField & ptf)
Construct as copy.
Definition at line 96 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField().
greyDiffusiveViewFactorFixedValueFvPatchScalarField() [5/5]
greyDiffusiveViewFactorFixedValueFvPatchScalarField (const greyDiffusiveViewFactorFixedValueFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 113 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References greyDiffusiveViewFactorFixedValueFvPatchScalarField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("greyDiffusiveRadiationViewFactor")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 145 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
References greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 162 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
References greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField().
Qro()
const scalarList& Qro () inline
Return external radiative heat flux.
Definition at line 182 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.H.
References greyDiffusiveViewFactorFixedValueFvPatchScalarField::updateCoeffs(), and greyDiffusiveViewFactorFixedValueFvPatchScalarField::write().
Referenced by viewFactor::calculate().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 132 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References dimensionedInternalField(), Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::Info, and greyDiffusiveViewFactorFixedValueFvPatchScalarField::write().
Referenced by greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), and greyDiffusiveViewFactorFixedValueFvPatchScalarField::Qro().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 162 of file greyDiffusiveViewFactorFixedValueFvPatchScalarField.C.
References Foam::radiation::makePatchTypeField(), radiation, write(), radiationCoupledBase::write(), and Field< Type >::writeEntry().
Referenced by greyDiffusiveViewFactorFixedValueFvPatchScalarField::Qro(), and greyDiffusiveViewFactorFixedValueFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiationModels/derivedFvPatchFields/greyDiffusiveViewFactor/greyDiffusiveViewFactorFixedValueFvPatchScalarField.H
src/thermophysicalModels/radiationModels/derivedFvPatchFields/greyDiffusiveViewFactor/greyDiffusiveViewFactorFixedValueFvPatchScalarField.C