OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
solidMixtureProperties Class Reference
A mixture of solids.
Public Member Functions
solidMixtureProperties (const dictionary &)
Construct from dictionary.
solidMixtureProperties (const solidMixtureProperties &lm)
Construct copy.
virtual autoPtr< solidMixtureProperties > clone () const
Construct and return a clone.
virtual ~solidMixtureProperties ()
Destructor.
const List< word > & components () const
Return the solidProperties names.
const PtrList< solidProperties > & properties () const
Return the solidProperties properties.
label size () const
Return the number of solids in the mixture.
scalarField Y (const scalarField &X) const
Returns the mass fractions, given mole fractions.
scalarField X (const scalarField &Y) const
Returns the mole fractions, given mass fractions.
scalar rho (const scalarField &X) const
Calculate the mixture density [kg/m^3] as a function of.
scalar Cp (const scalarField &Y) const
Calculate the mixture heat capacity [J/(kg K)] as a function.
Static Public Member Functions
static autoPtr< solidMixtureProperties > New (const dictionary &)
Select construct from dictionary.
Detailed Description
A mixture of solids.
An example of a two component solid mixture:
    <parentDictionary>
    {
        C
        {
            defaultCoeffs   yes;     // employ default coefficients
        }
        ash
        {
            defaultCoeffs   no;
            ashCoeffs
            {
                ... user defined properties for ash
            }
        }
    }
Source files
solidMixtureProperties.H
solidMixtureProperties.C
See also
Foam::solidProperties
Definition at line 74 of file solidMixtureProperties.H.
Constructor & Destructor Documentation
solidMixtureProperties() [1/2]
solidMixtureProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 30 of file solidMixtureProperties.C.
References forAll, solidProperties::New(), List< T >::size(), dictionary::subDict(), and dictionary::toc().
Referenced by solidMixtureProperties::clone(), and solidMixtureProperties::New().
solidMixtureProperties() [2/2]
solidMixtureProperties (const solidMixtureProperties & lm)
Construct copy.
Definition at line 45 of file solidMixtureProperties.C.
References forAll, and solidMixtureProperties::New().
~solidMixtureProperties()
virtual ~solidMixtureProperties () inline virtual
Destructor.
Definition at line 106 of file solidMixtureProperties.H.
References solidMixtureProperties::New().
Member Function Documentation
clone()
virtual autoPtr<solidMixtureProperties> clone () const inline virtual
Construct and return a clone.
Definition at line 96 of file solidMixtureProperties.H.
References solidMixtureProperties::solidMixtureProperties().
New()
Foam::autoPtr< Foam::solidMixtureProperties > New (const dictionary & thermophysicalProperties) static
Select construct from dictionary.
Definition at line 62 of file solidMixtureProperties.C.
References solidMixtureProperties::solidMixtureProperties().
Referenced by SLGThermo::SLGThermo(), solidMixtureProperties::solidMixtureProperties(), and solidMixtureProperties::~solidMixtureProperties().
components()
const List<word>& components () const inline
Return the solidProperties names.
Definition at line 119 of file solidMixtureProperties.H.
properties()
const PtrList<solidProperties>& properties () const inline
Return the solidProperties properties.
Definition at line 125 of file solidMixtureProperties.H.
Referenced by COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), and COxidationMurphyShaddix< CloudType >::calculate().
size()
label size () const inline
Return the number of solids in the mixture.
Definition at line 131 of file solidMixtureProperties.H.
References solidMixtureProperties::Cp(), solidMixtureProperties::rho(), List< T >::size(), solidMixtureProperties::X(), and solidMixtureProperties::Y().
Y()
scalarField Y (const scalarField & X) const
Returns the mass fractions, given mole fractions.
Referenced by solidMixtureProperties::size().
X()
Foam::scalarField X (const scalarField & Y) const
Returns the mole fractions, given mass fractions.
Definition at line 75 of file solidMixtureProperties.C.
References forAll, and List< T >::size().
Referenced by solidMixtureProperties::size().
rho()
Foam::scalar rho (const scalarField & X) const
Calculate the mixture density [kg/m^3] as a function of.
volume fractions
Definition at line 90 of file solidMixtureProperties.C.
References forAll.
Referenced by solidMixtureProperties::size().
Cp()
Foam::scalar Cp (const scalarField & Y) const
Calculate the mixture heat capacity [J/(kg K)] as a function.
of mass fractions
Definition at line 101 of file solidMixtureProperties.C.
References forAll.
Referenced by solidMixtureProperties::size().
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/solidMixtureProperties/solidMixtureProperties/solidMixtureProperties.H
src/thermophysicalModels/properties/solidMixtureProperties/solidMixtureProperties/solidMixtureProperties.C