OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
blackBodyEmission Class Reference
Class black body emission.
Public Member Functions
blackBodyEmission (const label nLambda, const volScalarField &T)
Construct from components.
~blackBodyEmission ()
Destructor.
const volScalarField & bLambda (const label lambdaI) const
Black body spectrum.
dimensionedScalar EblambdaT (const dimensionedScalar &T, const scalar lambda) const
Spectral emission for the black body at T and lambda.
tmp< Foam::volScalarField > EbDeltaLambdaT (const volScalarField &T, const Vector2D< scalar > &band) const
Integral energy at T from lambda1 to lambda2.
void correct (const label lambdaI, const Vector2D< scalar > &band)
Static Public Attributes
static const List< Tuple2< scalar, scalar > > emissivePowerTable
Static table of black body emissive power.
Detailed Description
Class black body emission.
Table of black body emissive power taken from: Modest, "Radiative Heat Transfer", pp.775-777, 1993
Source files
blackBodyEmission.H
blackBodyEmission.C
Definition at line 56 of file blackBodyEmission.H.
Constructor & Destructor Documentation
blackBodyEmission()
blackBodyEmission (const label nLambda, const volScalarField & T)
Construct from components.
Definition at line 144 of file blackBodyEmission.C.
References forAll, DimensionedField< Type, GeoMesh >::mesh(), Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow4(), and Foam::constant::physicoChemical::sigma.
~blackBodyEmission()
~blackBodyEmission ()
Destructor.
Definition at line 185 of file blackBodyEmission.C.
References blackBodyEmission::EbDeltaLambdaT().
Member Function Documentation
bLambda()
const volScalarField& bLambda (const label lambdaI) const inline
Black body spectrum.
Definition at line 110 of file blackBodyEmission.H.
References blackBodyEmission::EblambdaT().
EblambdaT()
dimensionedScalar EblambdaT (const dimensionedScalar & T, const scalar lambda) const inline
Spectral emission for the black body at T and lambda.
Definition at line 117 of file blackBodyEmission.H.
References blackBodyEmission::correct(), blackBodyEmission::EbDeltaLambdaT(), Foam::exp(), and Foam::pow5().
Referenced by blackBodyEmission::bLambda().
EbDeltaLambdaT()
Foam::tmp< Foam::volScalarField > EbDeltaLambdaT (const volScalarField & T, const Vector2D< scalar > & band) const
Integral energy at T from lambda1 to lambda2.
Definition at line 202 of file blackBodyEmission.C.
References blackBodyEmission::correct(), Foam::dimless, forAll, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow4(), Foam::constant::physicoChemical::sigma, and dimensioned< Type >::value().
Referenced by blackBodyEmission::EblambdaT(), and blackBodyEmission::~blackBodyEmission().
correct()
void correct (const label lambdaI, const Vector2D< scalar > & band)
Definition at line 248 of file blackBodyEmission.C.
Referenced by blackBodyEmission::EbDeltaLambdaT(), blackBodyEmission::EblambdaT(), and fvDOM::Ru().
Member Data Documentation
emissivePowerTable
const Foam::List< Foam::Tuple2< Foam::scalar, Foam::scalar > > emissivePowerTable static
Static table of black body emissive power.
Definition at line 61 of file blackBodyEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiationModels/radiationModel/fvDOM/blackBodyEmission/blackBodyEmission.H
src/thermophysicalModels/radiationModels/radiationModel/fvDOM/blackBodyEmission/blackBodyEmission.C