OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wideBandDiffusiveRadiationMixedFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a wide-band, diffusive radiation condition, where the patch temperature is specified.
Public Member Functions
TypeName ("wideBandDiffusiveRadiation")
Runtime type information.
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given GreyDiffusiveRadiationMixedFvPatchField.
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & TName () const
Return the temperature field name.
word & TName ()
Return reference to the temperature field name to allow.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from radiationCoupledBase
TypeName ("radiationCoupledBase")
Runtime type information.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity)
Construct from patch, emissivity mode and emissivity.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity, const fvPatchFieldMapper &mapper)
Construct from patch, emissivity mode and emissivity and mapper.
radiationCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
virtual ~radiationCoupledBase ()
Destructor.
word emissivityMethod () const
Method to obtain emissivity.
scalarField emissivity () const
Calculate corresponding emissivity field.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from radiationCoupledBase
enum emissivityMethodType { SOLIDRADIATION, LOOKUP }
Type of supplied emissivity.
Protected Attributes inherited from radiationCoupledBase
const emissivityMethodType method_
How to get emissivity.
scalarField emissivity_
Emissivity.
Detailed Description
This boundary condition provides a wide-band, diffusive radiation condition, where the patch temperature is specified.
Patch usage
Property Description Required Default value
T temperature field name no T
Example of the boundary condition specification:
    myPatch
    {
        type            wideBandDiffusiveRadiation;
        value           uniform 0;
    }
See also
Foam::mixedFvPatchScalarField Foam::radiationCoupledBase
Source files
wideBandDiffusiveRadiationMixedFvPatchScalarField.H
wideBandDiffusiveRadiationMixedFvPatchScalarField.C
Definition at line 84 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
wideBandDiffusiveRadiationMixedFvPatchScalarField() [1/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 42 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
Referenced by wideBandDiffusiveRadiationMixedFvPatchScalarField::clone(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
wideBandDiffusiveRadiationMixedFvPatchScalarField() [2/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 79 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References dictionary::found(), fvPatchField< Type >::operator, fvPatchField< Type >::operator=(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::constant::physicoChemical::sigma, fvPatch::size(), dimensioned< Type >::value(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
wideBandDiffusiveRadiationMixedFvPatchScalarField() [3/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given GreyDiffusiveRadiationMixedFvPatchField.
onto a new patch
Definition at line 59 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
wideBandDiffusiveRadiationMixedFvPatchScalarField() [4/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField & ptf)
Construct as copy.
Definition at line 115 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
wideBandDiffusiveRadiationMixedFvPatchScalarField() [5/5]
wideBandDiffusiveRadiationMixedFvPatchScalarField (const wideBandDiffusiveRadiationMixedFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 132 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("wideBandDiffusiveRadiation")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 135 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
References wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 152 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
References wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
TName() [1/2]
const word& TName () const inline
Return the temperature field name.
Definition at line 168 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
References wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::write().
TName() [2/2]
word& TName () inline
Return reference to the temperature field name to allow.
adjustment
Definition at line 175 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 151 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), d(), radiativeIntensityRay::dAve(), dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, UPstream::msgType(), n, Foam::name(), Foam::nl, Foam::constant::mathematical::pi(), radiativeIntensityRay::Qem(), radiativeIntensityRay::Qin(), radiativeIntensityRay::Qr(), radiation, and wideBandDiffusiveRadiationMixedFvPatchScalarField::write().
Referenced by wideBandDiffusiveRadiationMixedFvPatchScalarField::TName(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 251 of file wideBandDiffusiveRadiationMixedFvPatchScalarField.C.
References Foam::makePatchTypeField(), radiation, write(), and radiationCoupledBase::write().
Referenced by wideBandDiffusiveRadiationMixedFvPatchScalarField::TName(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiationModels/derivedFvPatchFields/wideBandDiffusiveRadiation/wideBandDiffusiveRadiationMixedFvPatchScalarField.H
src/thermophysicalModels/radiationModels/derivedFvPatchFields/wideBandDiffusiveRadiation/wideBandDiffusiveRadiationMixedFvPatchScalarField.C