OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
radiativeIntensityRay Class Reference
Radiation intensity for a ray in a given direction.
Public Member Functions
radiativeIntensityRay (const fvDOM &dom, const fvMesh &mesh, const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const label lambda, const absorptionEmissionModel &absEmmModel_, const blackBodyEmission &blackBody, const label rayId)
Construct form components.
~radiativeIntensityRay ()
Destructor.
scalar correct ()
Update radiative intensity on i direction.
void init (const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const scalar lambda)
Initialise the ray in i direction.
void addIntensity ()
Add radiative intensities from all the bands.
const volScalarField & I () const
Return intensity.
const volScalarField & Qr () const
Return const access to the boundary heat flux.
volScalarField & Qr ()
Return non-const access to the boundary heat flux.
volScalarField & Qin ()
Return non-const access to the boundary incident heat flux.
volScalarField & Qem ()
Return non-const access to the boundary emmited heat flux.
const volScalarField & Qin () const
Return const access to the boundary incident heat flux.
const volScalarField & Qem () const
Return const access to the boundary emmited heat flux.
const vector & d () const
Return direction.
const vector & dAve () const
Return the average vector inside the solid angle.
scalar nLambda () const
Return the number of bands.
scalar phi () const
Return the phi angle.
scalar theta () const
Return the theta angle.
scalar omega () const
Return the solid angle.
const volScalarField & ILambda (const label lambdaI) const
Return the radiative intensity for a given wavelength.
Static Public Attributes
static const word intensityPrefix
Detailed Description
Radiation intensity for a ray in a given direction.
Source files
radiativeIntensityRay.H
radiativeIntensityRay.C
Definition at line 55 of file radiativeIntensityRay.H.
Constructor & Destructor Documentation
radiativeIntensityRay()
radiativeIntensityRay (const fvDOM & dom, const fvMesh & mesh, const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const label lambda, const absorptionEmissionModel & absEmmModel_, const blackBodyEmission & blackBody, const label rayId)
Construct form components.
Definition at line 41 of file radiativeIntensityRay.C.
References IOobject::AUTO_WRITE, Foam::cos(), Foam::vectorTools::cosPhi(), forAll, IOobject::MUST_READ, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, IOobject::readOpt(), autoPtr< T >::reset(), Foam::sin(), and autoPtr< T >::valid().
~radiativeIntensityRay()
~radiativeIntensityRay ()
Destructor.
Definition at line 199 of file radiativeIntensityRay.C.
Member Function Documentation
correct()
Foam::scalar correct ()
Update radiative intensity on i direction.
Definition at line 205 of file radiativeIntensityRay.C.
References Foam::fvm::div(), forAll, SolverPerformance< Type >::initialResidual(), k, Foam::max(), Foam::constant::mathematical::pi(), Foam::solve(), and Foam::fvm::Sp().
init()
void init (const scalar phi, const scalar theta, const scalar deltaPhi, const scalar deltaTheta, const scalar lambda)
Initialise the ray in i direction.
addIntensity()
void addIntensity ()
Add radiative intensities from all the bands.
Definition at line 267 of file radiativeIntensityRay.C.
References Foam::dimMass, Foam::dimTime, forAll, and Foam::pow3().
I()
const Foam::volScalarField & I () const inline
Return intensity.
Definition at line 27 of file radiativeIntensityRayI.H.
Qr() [1/2]
const Foam::volScalarField & Qr () const inline
Return const access to the boundary heat flux.
Definition at line 34 of file radiativeIntensityRayI.H.
Referenced by wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
Qr() [2/2]
Foam::volScalarField & Qr () inline
Return non-const access to the boundary heat flux.
Definition at line 40 of file radiativeIntensityRayI.H.
References radiativeIntensityRay::Qin().
Qin() [1/2]
Foam::volScalarField & Qin () inline
Return non-const access to the boundary incident heat flux.
Definition at line 52 of file radiativeIntensityRayI.H.
References radiativeIntensityRay::Qem().
Referenced by radiativeIntensityRay::Qr(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
Qem() [1/2]
Foam::volScalarField & Qem () inline
Return non-const access to the boundary emmited heat flux.
Definition at line 65 of file radiativeIntensityRayI.H.
Referenced by radiativeIntensityRay::Qin(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
Qin() [2/2]
const Foam::volScalarField & Qin () const inline
Return const access to the boundary incident heat flux.
Definition at line 46 of file radiativeIntensityRayI.H.
Qem() [2/2]
const Foam::volScalarField & Qem () const inline
Return const access to the boundary emmited heat flux.
Definition at line 59 of file radiativeIntensityRayI.H.
d()
const Foam::vector & d () const inline
Return direction.
Definition at line 71 of file radiativeIntensityRayI.H.
dAve()
const Foam::vector & dAve () const inline
Return the average vector inside the solid angle.
Definition at line 77 of file radiativeIntensityRayI.H.
Referenced by wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
nLambda()
Foam::scalar nLambda () const inline
Return the number of bands.
Definition at line 83 of file radiativeIntensityRayI.H.
phi()
Foam::scalar phi () const inline
Return the phi angle.
Definition at line 89 of file radiativeIntensityRayI.H.
theta()
Foam::scalar theta () const inline
Return the theta angle.
Definition at line 95 of file radiativeIntensityRayI.H.
omega()
Foam::scalar omega () const inline
Return the solid angle.
Definition at line 101 of file radiativeIntensityRayI.H.
References radiativeIntensityRay::ILambda().
ILambda()
const Foam::volScalarField & ILambda (const label lambdaI) const inline
Return the radiative intensity for a given wavelength.
Definition at line 109 of file radiativeIntensityRayI.H.
Referenced by radiativeIntensityRay::omega().
Member Data Documentation
intensityPrefix
const Foam::word intensityPrefix static
Definition at line 59 of file radiativeIntensityRay.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiationModels/radiationModel/fvDOM/radiativeIntensityRay/radiativeIntensityRay.H
src/thermophysicalModels/radiationModels/radiationModel/fvDOM/radiativeIntensityRay/radiativeIntensityRay.C
src/thermophysicalModels/radiationModels/radiationModel/fvDOM/radiativeIntensityRay/radiativeIntensityRayI.H