OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
greyMeanSolidAbsorptionEmission Class Reference
greyMeanSolidAbsorptionEmission radiation absorption and emission coefficients for continuous phase
Public Member Functions
TypeName ("greyMeanSolidAbsorptionEmission")
Runtime type information.
greyMeanSolidAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~greyMeanSolidAbsorptionEmission ()
Destructor.
tmp< volScalarField > aCont (const label bandI=0) const
Absorption coefficient for continuous phase.
tmp< volScalarField > eCont (const label bandI=0) const
Emission coefficient for continuous phase.
bool isGrey () const
Flag for whether the absorption/emission is for a grey gas.
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
Declare runtime constructor selection table.
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~absorptionEmissionModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual tmp< volScalarField > a (const label bandI=0) const
Absorption coefficient (net)
virtual tmp< volScalarField > aDisp (const label bandI=0) const
Absorption coefficient for dispersed phase.
virtual tmp< volScalarField > e (const label bandI=0) const
Emission coefficient (net)
virtual tmp< volScalarField > eDisp (const label bandI=0) const
Return emission coefficient for dispersed phase.
virtual tmp< volScalarField > E (const label bandI=0) const
Emission contribution (net)
virtual tmp< volScalarField > ECont (const label bandI=0) const
Emission contribution for continuous phase.
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Emission contribution for dispersed phase.
virtual label nBands () const
Const access to the number of bands - defaults to 1 for grey.
virtual const Vector2D< scalar > & bands (const label n) const
Const access to the bands - defaults to Vector2D::one for grey.
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Correct absorption coefficients.
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
greyMeanSolidAbsorptionEmission radiation absorption and emission coefficients for continuous phase
The coefficients for the species in the Look up table have to be specified for use in moles x P [atm], i.e. (k[i] = species[i]*p*9.869231e-6).
The coefficients for CO and soot or any other added are multiplied by the respective mass fraction being solved
All the species in the dictionary need either to be in the look-up table or being solved. Conversely, all the species solved do not need to be included in the calculation of the absorption coefficient
The names of the species in the absorption dictionary must match exactly the name in the look-up table or the name of the field being solved
Source files
greyMeanSolidAbsorptionEmission.H
greyMeanSolidAbsorptionEmission.C
Definition at line 66 of file greyMeanSolidAbsorptionEmission.H.
Constructor & Destructor Documentation
greyMeanSolidAbsorptionEmission()
greyMeanSolidAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 87 of file greyMeanSolidAbsorptionEmission.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAllConstIter(), dictionary::lookup(), Foam::nl, dictionary::subDict(), WarningIn, and greyMeanSolidAbsorptionEmission::~greyMeanSolidAbsorptionEmission().
~greyMeanSolidAbsorptionEmission()
~greyMeanSolidAbsorptionEmission () virtual
Destructor.
Definition at line 151 of file greyMeanSolidAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, greyMeanSolidAbsorptionEmission::eCont(), forAllConstIter(), mesh, IOobject::NO_READ, IOobject::NO_WRITE, and timeName.
Referenced by greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission().
Member Function Documentation
TypeName()
TypeName ("greyMeanSolidAbsorptionEmission")
Runtime type information.
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Absorption coefficient for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 206 of file greyMeanSolidAbsorptionEmission.C.
References Foam::calc().
Referenced by greyMeanSolidAbsorptionEmission::eCont().
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Emission coefficient for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 196 of file greyMeanSolidAbsorptionEmission.C.
References greyMeanSolidAbsorptionEmission::aCont(), and Foam::calc().
Referenced by greyMeanSolidAbsorptionEmission::~greyMeanSolidAbsorptionEmission().
isGrey()
bool isGrey () const inline virtual
Flag for whether the absorption/emission is for a grey gas.
Reimplemented from absorptionEmissionModel.
Definition at line 145 of file greyMeanSolidAbsorptionEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiationModels/submodels/absorptionEmissionModel/greyMeanSolidAbsorptionEmission/greyMeanSolidAbsorptionEmission.H
src/thermophysicalModels/radiationModels/submodels/absorptionEmissionModel/greyMeanSolidAbsorptionEmission/greyMeanSolidAbsorptionEmission.C