OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
homogeneousMixture< ThermoType > Class Template Reference
Foam::homogeneousMixture.
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
homogeneousMixture (const dictionary &, const fvMesh &)
Construct from dictionary and mesh.
virtual ~homogeneousMixture ()
Destructor.
const ThermoType & mixture (const scalar) const
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellReactants (const label) const
const ThermoType & patchFaceReactants (const label, const label) const
const ThermoType & cellProducts (const label) const
const ThermoType & patchFaceProducts (const label, const label) const
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label specieI) const
Return thermo based on index.
Public Member Functions inherited from basicMultiComponentMixture
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &)
Construct from dictionary and mesh.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
bool contains (const word &specieName) const
Does the mixture include this specie?
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
virtual scalar nMoles (const label specieI) const =0
Number of moles [].
virtual scalar W (const label specieI) const =0
Molecular weight [kg/kmol].
virtual scalar Cp (const label specieI, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label specieI, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label specieI, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label specieI, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label specieI) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label specieI, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label specieI, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label specieI, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label specieI, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label specieI, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label specieI, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label specieI, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label specieI, const scalar p, const scalar T) const =0
Density [kg/m3].
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
template<class ThermoType>
class Foam::homogeneousMixture< ThermoType >
Foam::homogeneousMixture.
Source files
homogeneousMixture.H
homogeneousMixture.C
Definition at line 49 of file homogeneousMixture.H.
Member Typedef Documentation
thermoType
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 73 of file homogeneousMixture.H.
Constructor & Destructor Documentation
homogeneousMixture()
homogeneousMixture (const dictionary & thermoDict, const fvMesh & mesh)
Construct from dictionary and mesh.
Definition at line 39 of file homogeneousMixture.C.
References homogeneousMixture< ThermoType >::mixture().
~homogeneousMixture()
virtual ~homogeneousMixture () inline virtual
Destructor.
Definition at line 83 of file homogeneousMixture.H.
References homogeneousMixture< ThermoType >::mixture().
Member Function Documentation
mixture()
const ThermoType & mixture (const scalar b) const
Definition at line 62 of file homogeneousMixture.C.
References Foam::constant::physicoChemical::b.
Referenced by homogeneousMixture< ThermoType >::cellMixture(), homogeneousMixture< ThermoType >::homogeneousMixture(), homogeneousMixture< ThermoType >::patchFaceMixture(), and homogeneousMixture< ThermoType >::~homogeneousMixture().
cellMixture()
const ThermoType& cellMixture (const label celli) const inline
Definition at line 91 of file homogeneousMixture.H.
References homogeneousMixture< ThermoType >::mixture(), and homogeneousMixture< ThermoType >::patchFaceMixture().
patchFaceMixture()
const ThermoType& patchFaceMixture (const label patchi, const label facei) const inline
Definition at line 97 of file homogeneousMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), homogeneousMixture< ThermoType >::mixture(), and patchi.
Referenced by homogeneousMixture< ThermoType >::cellMixture().
cellReactants()
const ThermoType& cellReactants (const label) const inline
Definition at line 105 of file homogeneousMixture.H.
patchFaceReactants()
const ThermoType& patchFaceReactants (const label , const label) const inline
Definition at line 110 of file homogeneousMixture.H.
cellProducts()
const ThermoType& cellProducts (const label) const inline
Definition at line 115 of file homogeneousMixture.H.
patchFaceProducts()
const ThermoType& patchFaceProducts (const label , const label) const inline
Definition at line 120 of file homogeneousMixture.H.
References homogeneousMixture< ThermoType >::getLocalThermo(), and homogeneousMixture< ThermoType >::read().
read()
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 85 of file homogeneousMixture.C.
References homogeneousMixture< ThermoType >::getLocalThermo(), and dictionary::subDict().
Referenced by homogeneousMixture< ThermoType >::patchFaceProducts().
getLocalThermo()
const ThermoType & getLocalThermo (const label specieI) const
Return thermo based on index.
Definition at line 94 of file homogeneousMixture.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by homogeneousMixture< ThermoType >::patchFaceProducts(), and homogeneousMixture< ThermoType >::read().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/homogeneousMixture/homogeneousMixture.H
src/thermophysicalModels/reactionThermo/mixtures/homogeneousMixture/homogeneousMixture.C