OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SpecieMixture< MixtureType > Class Template Reference
Foam::SpecieMixture.
Public Member Functions
SpecieMixture (const dictionary &, const fvMesh &)
Construct from dictionary and mesh.
virtual ~SpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const
Number of moles [].
virtual scalar W (const label speciei) const
Molecular weight [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label specieI, const scalar p, const scalar T) const
Density [kg/m3].
Detailed Description
template<class MixtureType>
class Foam::SpecieMixture< MixtureType >
Foam::SpecieMixture.
Source files
SpecieMixture.H
SpecieMixture.C
Definition at line 54 of file SpecieMixture.H.
Constructor & Destructor Documentation
SpecieMixture()
SpecieMixture (const dictionary & thermoDict, const fvMesh & mesh)
Construct from dictionary and mesh.
Definition at line 33 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::nMoles().
~SpecieMixture()
virtual ~SpecieMixture () inline virtual
Destructor.
Definition at line 68 of file SpecieMixture.H.
References SpecieMixture< MixtureType >::A(), SpecieMixture< MixtureType >::alphah(), SpecieMixture< MixtureType >::Cp(), SpecieMixture< MixtureType >::Cv(), SpecieMixture< MixtureType >::Es(), SpecieMixture< MixtureType >::G(), SpecieMixture< MixtureType >::Ha(), SpecieMixture< MixtureType >::Hc(), SpecieMixture< MixtureType >::Hs(), SpecieMixture< MixtureType >::kappa(), SpecieMixture< MixtureType >::mu(), SpecieMixture< MixtureType >::nMoles(), p, SpecieMixture< MixtureType >::rho(), SpecieMixture< MixtureType >::S(), Foam::T(), and SpecieMixture< MixtureType >::W().
Member Function Documentation
nMoles()
Foam::scalar nMoles (const label speciei) const virtual
Number of moles [].
Definition at line 50 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::W().
Referenced by SpecieMixture< MixtureType >::SpecieMixture(), and SpecieMixture< MixtureType >::~SpecieMixture().
W()
Foam::scalar W (const label speciei) const virtual
Molecular weight [kg/kmol].
Definition at line 60 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Cp().
Referenced by SpecieMixture< MixtureType >::nMoles(), and SpecieMixture< MixtureType >::~SpecieMixture().
Cp()
Foam::scalar Cp (const label speciei, const scalar p, const scalar T) const virtual
Heat capacity at constant pressure [J/(kg K)].
Definition at line 70 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Cv().
Referenced by SpecieMixture< MixtureType >::W(), and SpecieMixture< MixtureType >::~SpecieMixture().
Cv()
Foam::scalar Cv (const label speciei, const scalar p, const scalar T) const virtual
Heat capacity at constant volume [J/(kg K)].
Definition at line 82 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Ha().
Referenced by SpecieMixture< MixtureType >::Cp(), and SpecieMixture< MixtureType >::~SpecieMixture().
Ha()
Foam::scalar Ha (const label speciei, const scalar p, const scalar T) const virtual
Absolute enthalpy [J/kg].
Definition at line 94 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Hs().
Referenced by SpecieMixture< MixtureType >::Cv(), and SpecieMixture< MixtureType >::~SpecieMixture().
Hs()
Foam::scalar Hs (const label speciei, const scalar p, const scalar T) const virtual
Sensible enthalpy [J/kg].
Definition at line 106 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Hc().
Referenced by SpecieMixture< MixtureType >::Ha(), and SpecieMixture< MixtureType >::~SpecieMixture().
Hc()
Foam::scalar Hc (const label speciei) const virtual
Chemical enthalpy [J/kg].
Definition at line 118 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::S().
Referenced by SpecieMixture< MixtureType >::Hs(), and SpecieMixture< MixtureType >::~SpecieMixture().
S()
Foam::scalar S (const label speciei, const scalar p, const scalar T) const virtual
Entropy [J/(kg K)].
Definition at line 128 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Es().
Referenced by SpecieMixture< MixtureType >::Hc(), and SpecieMixture< MixtureType >::~SpecieMixture().
Es()
Foam::scalar Es (const label speciei, const scalar p, const scalar T) const virtual
Sensible internal energy [J/kg].
Definition at line 140 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::G().
Referenced by SpecieMixture< MixtureType >::S(), and SpecieMixture< MixtureType >::~SpecieMixture().
G()
Foam::scalar G (const label speciei, const scalar p, const scalar T) const virtual
Gibbs free energy [J/kg].
Definition at line 152 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::A().
Referenced by SpecieMixture< MixtureType >::Es(), and SpecieMixture< MixtureType >::~SpecieMixture().
A()
Foam::scalar A (const label speciei, const scalar p, const scalar T) const virtual
Helmholtz free energy [J/kg].
Definition at line 164 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::mu().
Referenced by SpecieMixture< MixtureType >::G(), and SpecieMixture< MixtureType >::~SpecieMixture().
mu()
Foam::scalar mu (const label speciei, const scalar p, const scalar T) const virtual
Dynamic viscosity [kg/m/s].
Definition at line 176 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::kappa().
Referenced by SpecieMixture< MixtureType >::A(), and SpecieMixture< MixtureType >::~SpecieMixture().
kappa()
Foam::scalar kappa (const label speciei, const scalar p, const scalar T) const virtual
Thermal conductivity [W/m/K].
Definition at line 188 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::alphah().
Referenced by SpecieMixture< MixtureType >::mu(), and SpecieMixture< MixtureType >::~SpecieMixture().
alphah()
Foam::scalar alphah (const label speciei, const scalar p, const scalar T) const virtual
Thermal diffusivity of enthalpy [kg/m/s].
Definition at line 200 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::rho().
Referenced by SpecieMixture< MixtureType >::kappa(), and SpecieMixture< MixtureType >::~SpecieMixture().
rho()
Foam::scalar rho (const label specieI, const scalar p, const scalar T) const virtual
Density [kg/m3].
Definition at line 212 of file SpecieMixture.C.
Referenced by SpecieMixture< MixtureType >::alphah(), and SpecieMixture< MixtureType >::~SpecieMixture().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/SpecieMixture/SpecieMixture.H
src/thermophysicalModels/reactionThermo/mixtures/SpecieMixture/SpecieMixture.C