OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
basicMultiComponentMixture Class Reference abstract
Multi-component mixture. Provides a list of mass fraction fields and helper functions to query mixture composition.
Public Types
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &)
Construct from dictionary and mesh.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
bool contains (const word &specieName) const
Does the mixture include this specie?
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
virtual scalar nMoles (const label specieI) const =0
Number of moles [].
virtual scalar W (const label specieI) const =0
Molecular weight [kg/kmol].
virtual scalar Cp (const label specieI, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label specieI, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label specieI, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label specieI, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label specieI) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label specieI, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label specieI, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label specieI, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label specieI, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label specieI, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label specieI, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label specieI, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label specieI, const scalar p, const scalar T) const =0
Density [kg/m3].
Protected Attributes
speciesTable species_
Table of specie names.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
Multi-component mixture. Provides a list of mass fraction fields and helper functions to query mixture composition.
Source files
basicMultiComponentMixture.H
basicMultiComponentMixture.C
Definition at line 51 of file basicMultiComponentMixture.H.
Member Typedef Documentation
basicMixtureType
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Definition at line 68 of file basicMultiComponentMixture.H.
Constructor & Destructor Documentation
basicMultiComponentMixture()
basicMultiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh)
Construct from dictionary and mesh.
Definition at line 31 of file basicMultiComponentMixture.C.
References forAll, mesh, fvMesh::time(), and Time::timeName().
~basicMultiComponentMixture()
virtual ~basicMultiComponentMixture () inline virtual
Destructor.
Definition at line 83 of file basicMultiComponentMixture.H.
Member Function Documentation
species()
const speciesTable& species () const inline
Return the table of species.
Definition at line 90 of file basicMultiComponentMixture.H.
References basicMultiComponentMixture::A(), basicMultiComponentMixture::alphah(), basicMultiComponentMixture::contains(), basicMultiComponentMixture::Cp(), basicMultiComponentMixture::Cv(), basicMultiComponentMixture::Es(), basicMultiComponentMixture::fres(), basicMultiComponentMixture::G(), basicMultiComponentMixture::Ha(), basicMultiComponentMixture::Hc(), basicMultiComponentMixture::Hs(), basicMultiComponentMixture::kappa(), basicMultiComponentMixture::mu(), basicMultiComponentMixture::nMoles(), p, basicMultiComponentMixture::rho(), basicMultiComponentMixture::S(), basicMultiComponentMixture::species_, Foam::T(), basicMultiComponentMixture::W(), and basicMultiComponentMixture::Y().
Referenced by greyMeanAbsorptionEmission::aCont(), SLGThermo::carrierId(), ReactingParcel< ParcelType >::correctSurfaceValues(), ReactingCloud< Foam::DsmcCloud >::ReactingCloud(), SLGThermo::SLGThermo(), and thermoSingleLayer::thermoSingleLayer().
Y() [1/6]
Foam::PtrList< Foam::volScalarField > & Y () inline
Return the mass-fraction fields.
Definition at line 27 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y_.
Referenced by greyMeanAbsorptionEmission::aCont(), COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), ReactingParcel< ParcelType >::correctSurfaceValues(), basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
Y() [2/6]
const Foam::PtrList< Foam::volScalarField > & Y () const inline
Return the const mass-fraction fields.
Definition at line 34 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y_.
Y() [3/6]
Foam::volScalarField & Y (const label i) inline
Return the mass-fraction field for a specie given by index.
Definition at line 40 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Y() [4/6]
const Foam::volScalarField & Y (const label i) const inline
Return the const mass-fraction field for a specie given by index.
Definition at line 47 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Y() [5/6]
Foam::volScalarField & Y (const word & specieName) inline
Return the mass-fraction field for a specie given by name.
Definition at line 56 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_, basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Y() [6/6]
const Foam::volScalarField & Y (const word & specieName) const inline
Return the const mass-fraction field for a specie given by name.
Definition at line 65 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::contains(), basicMultiComponentMixture::species_, and basicMultiComponentMixture::Y_.
contains()
bool contains (const word & specieName) const inline
Does the mixture include this specie?
Definition at line 74 of file basicMultiComponentMixtureI.H.
References hashedWordList::contains(), basicMultiComponentMixture::fres(), and basicMultiComponentMixture::species_.
Referenced by basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
fres() [1/2]
Foam::scalar fres (const scalar ft, const scalar stoicRatio) const inline
Definition at line 83 of file basicMultiComponentMixtureI.H.
References Foam::max().
Referenced by veryInhomogeneousMixture< ThermoType >::cellProducts(), basicMultiComponentMixture::contains(), veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), and basicMultiComponentMixture::species().
fres() [2/2]
Foam::tmp< Foam::volScalarField > fres (const volScalarField & ft, const dimensionedScalar & stoicRatio) const inline
Definition at line 93 of file basicMultiComponentMixtureI.H.
References Foam::max(), and dimensioned< Type >::value().
nMoles()
virtual scalar nMoles (const label specieI) const pure virtual
Number of moles [].
Referenced by basicMultiComponentMixture::species().
W()
virtual scalar W (const label specieI) const pure virtual
Molecular weight [kg/kmol].
Referenced by greyMeanAbsorptionEmission::aCont(), ReactingParcel< ParcelType >::correctSurfaceValues(), and basicMultiComponentMixture::species().
Cp()
virtual scalar Cp (const label specieI, const scalar p, const scalar T) const pure virtual
Heat capacity at constant pressure [J/(kg K)].
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), and basicMultiComponentMixture::species().
Cv()
virtual scalar Cv (const label specieI, const scalar p, const scalar T) const pure virtual
Heat capacity at constant volume [J/(kg K)].
Referenced by basicMultiComponentMixture::species().
Ha()
virtual scalar Ha (const label specieI, const scalar p, const scalar T) const pure virtual
Absolute enthalpy [J/kg].
Referenced by basicMultiComponentMixture::species().
Hs()
virtual scalar Hs (const label specieI, const scalar p, const scalar T) const pure virtual
Sensible enthalpy [J/kg].
Referenced by basicMultiComponentMixture::species().
Hc()
virtual scalar Hc (const label specieI) const pure virtual
Chemical enthalpy [J/kg].
Referenced by basicMultiComponentMixture::species().
S()
virtual scalar S (const label specieI, const scalar p, const scalar T) const pure virtual
Entropy [J/(kg K)].
Referenced by basicMultiComponentMixture::species().
Es()
virtual scalar Es (const label specieI, const scalar p, const scalar T) const pure virtual
Sensible internal energy [J/kg].
Referenced by basicMultiComponentMixture::species().
G()
virtual scalar G (const label specieI, const scalar p, const scalar T) const pure virtual
Gibbs free energy [J/kg].
Referenced by basicMultiComponentMixture::species().
A()
virtual scalar A (const label specieI, const scalar p, const scalar T) const pure virtual
Helmholtz free energy [J/kg].
Referenced by basicMultiComponentMixture::species().
mu()
virtual scalar mu (const label specieI, const scalar p, const scalar T) const pure virtual
Dynamic viscosity [kg/m/s].
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), and basicMultiComponentMixture::species().
kappa()
virtual scalar kappa (const label specieI, const scalar p, const scalar T) const pure virtual
Thermal conductivity [W/m/K].
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), and basicMultiComponentMixture::species().
alphah()
virtual scalar alphah (const label specieI, const scalar p, const scalar T) const pure virtual
Thermal diffusivity of enthalpy [kg/m/s].
Referenced by basicMultiComponentMixture::species().
rho()
virtual scalar rho (const label specieI, const scalar p, const scalar T) const pure virtual
Density [kg/m3].
Referenced by basicMultiComponentMixture::species().
Member Data Documentation
species_
speciesTable species_ protected
Table of specie names.
Definition at line 59 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::contains(), basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
Y_
PtrList<volScalarField> Y_ protected
Species mass fractions.
Definition at line 62 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::Y().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.C
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixtureI.H