OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polynomialSolidTransport< Thermo, PolySize > Class Template Reference
Transport package using polynomial functions for solid kappa.
Public Member Functions
polynomialSolidTransport (const polynomialSolidTransport &)
Construct copy.
polynomialSolidTransport (const word &, const polynomialSolidTransport &)
Construct as named copy.
polynomialSolidTransport (Istream &is)
Construct from Istream.
polynomialSolidTransport (const dictionary &dict)
Construct from dictionary.
autoPtr< polynomialSolidTransport > clone () const
Construct and return a clone.
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
vector Kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
polynomialSolidTransport & operator= (const polynomialSolidTransport &)
void operator+= (const polynomialSolidTransport &)
void operator-= (const polynomialSolidTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< polynomialSolidTransport > New (Istream &is)
static autoPtr< polynomialSolidTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool isotropic = true
Is the thermal conductivity isotropic.
Friends
polynomialSolidTransport operator+ (const polynomialSolidTransport &, const polynomialSolidTransport &)
polynomialSolidTransport operator- (const polynomialSolidTransport &, const polynomialSolidTransport &)
polynomialSolidTransport operator* (const scalar, const polynomialSolidTransport &)
polynomialSolidTransport operator== (const polynomialSolidTransport &, const polynomialSolidTransport &)
Ostream & operator (Ostream &, const polynomialSolidTransport &)
Detailed Description
template<class Thermo, int PolySize = 8>
class Foam::polynomialSolidTransport< Thermo, PolySize >
Transport package using polynomial functions for solid kappa.
Source files
polynomialSolidTransport.H
polynomialSolidTransportI.H
polynomialSolidTransport.C
Definition at line 47 of file polynomialSolidTransport.H.
Constructor & Destructor Documentation
polynomialSolidTransport() [1/4]
polynomialSolidTransport (const polynomialSolidTransport< Thermo, PolySize > & pt) inline
Construct copy.
Definition at line 33 of file polynomialSolidTransportI.H.
polynomialSolidTransport() [2/4]
polynomialSolidTransport (const word & name, const polynomialSolidTransport< Thermo, PolySize > & pt) inline
Construct as named copy.
Definition at line 58 of file polynomialSolidTransportI.H.
polynomialSolidTransport() [3/4]
polynomialSolidTransport (Istream & is)
Construct from Istream.
Definition at line 33 of file polynomialSolidTransport.C.
polynomialSolidTransport() [4/4]
polynomialSolidTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 45 of file polynomialSolidTransport.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::polynomialSolidTransport< Thermo, PolySize > > clone () const inline
Construct and return a clone.
Definition at line 70 of file polynomialSolidTransportI.H.
New() [1/2]
Foam::autoPtr< Foam::polynomialSolidTransport< Thermo, PolySize > > New (Istream & is) inline static
Definition at line 81 of file polynomialSolidTransportI.H.
New() [2/2]
Foam::autoPtr< Foam::polynomialSolidTransport< Thermo, PolySize > > New (const dictionary & dict) inline static
Definition at line 92 of file polynomialSolidTransportI.H.
References dict, and polynomialSolidTransport< Thermo, PolySize >::mu().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 147 of file polynomialSolidTransport.H.
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 105 of file polynomialSolidTransportI.H.
References polynomialSolidTransport< Thermo, PolySize >::kappa(), and notImplemented.
Referenced by polynomialSolidTransport< Thermo, PolySize >::New().
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 123 of file polynomialSolidTransportI.H.
References polynomialSolidTransport< Thermo, PolySize >::Kappa().
Referenced by polynomialSolidTransport< Thermo, PolySize >::mu().
Kappa()
Foam::vector Kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 134 of file polynomialSolidTransportI.H.
References polynomialSolidTransport< Thermo, PolySize >::alphah(), and Foam::constant::electromagnetic::kappa.
Referenced by polynomialSolidTransport< Thermo, PolySize >::kappa().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 146 of file polynomialSolidTransportI.H.
References Foam::constant::electromagnetic::kappa.
Referenced by polynomialSolidTransport< Thermo, PolySize >::Kappa().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 64 of file polynomialSolidTransport.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::name(), Foam::tab, and write().
operator=()
Foam::polynomialSolidTransport< Thermo, PolySize > & operator= (const polynomialSolidTransport< Thermo, PolySize > &) inline
Definition at line 159 of file polynomialSolidTransportI.H.
operator+=()
void operator+= (const polynomialSolidTransport< Thermo, PolySize > &) inline
Definition at line 173 of file polynomialSolidTransportI.H.
operator-=()
void operator-= (const polynomialSolidTransport< Thermo, PolySize > &) inline
Definition at line 190 of file polynomialSolidTransportI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 207 of file polynomialSolidTransportI.H.
References s().
Friends And Related Function Documentation
operator+
polynomialSolidTransport operator+ (const polynomialSolidTransport< Thermo, PolySize > & , const polynomialSolidTransport< Thermo, PolySize > &) friend
operator-
polynomialSolidTransport operator- (const polynomialSolidTransport< Thermo, PolySize > & , const polynomialSolidTransport< Thermo, PolySize > &) friend
operator*
polynomialSolidTransport operator* (const scalar , const polynomialSolidTransport< Thermo, PolySize > &) friend
operator==
polynomialSolidTransport operator== (const polynomialSolidTransport< Thermo, PolySize > & , const polynomialSolidTransport< Thermo, PolySize > &) friend
operator
Ostream& operator (Ostream & , const polynomialSolidTransport< Thermo, PolySize > &) friend
Member Data Documentation
isotropic
const bool isotropic = true static
Is the thermal conductivity isotropic.
Definition at line 153 of file polynomialSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/polynomial/polynomialSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/polynomial/polynomialSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/polynomial/polynomialSolidTransportI.H