OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
TroeFallOffFunction Class Reference
The Troe fall-off function.
Public Member Functions
TroeFallOffFunction (const scalar alpha, const scalar Tsss, const scalar Ts, const scalar Tss)
Construct from components.
TroeFallOffFunction (Istream &)
Construct from Istream.
TroeFallOffFunction (const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar T, const scalar Pr) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const TroeFallOffFunction &)
Detailed Description
The Troe fall-off function.
Source files
TroeFallOffFunction.H
TroeFallOffFunctionI.H
Definition at line 54 of file TroeFallOffFunction.H.
Constructor & Destructor Documentation
TroeFallOffFunction() [1/3]
TroeFallOffFunction (const scalar alpha, const scalar Tsss, const scalar Ts, const scalar Tss) inline
Construct from components.
Definition at line 29 of file TroeFallOffFunctionI.H.
TroeFallOffFunction() [2/3]
TroeFallOffFunction (Istream & is) inline
Construct from Istream.
Definition at line 43 of file TroeFallOffFunctionI.H.
References Istream::readEnd().
TroeFallOffFunction() [3/3]
TroeFallOffFunction (const dictionary & dict) inline
Construct from dictionary.
Definition at line 54 of file TroeFallOffFunctionI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 85 of file TroeFallOffFunction.H.
References TroeFallOffFunction::operator<<, Pr(), Foam::T(), and TroeFallOffFunction::write().
operator()()
Foam::scalar operator() (const scalar T, const scalar Pr) const inline
Definition at line 66 of file TroeFallOffFunctionI.H.
References Foam::constant::universal::c, d(), Foam::exp(), Foam::log10(), Foam::max(), n, Foam::pow(), Pr(), Foam::sqr(), and Foam::T().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 89 of file TroeFallOffFunctionI.H.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by TroeFallOffFunction::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const TroeFallOffFunction &) friend
Referenced by TroeFallOffFunction::type().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/TroeFallOffFunction/TroeFallOffFunction.H
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/TroeFallOffFunction/TroeFallOffFunctionI.H