OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
constIsoSolidTransport< Thermo > Class Template Reference
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
Public Member Functions
constIsoSolidTransport (const word &, const constIsoSolidTransport &)
Construct as named copy.
constIsoSolidTransport (const dictionary &dict)
Construct from Istream.
scalar kappa (const scalar p, const scalar T) const
Isotropic thermal conductivity [W/mK].
vector Kappa (const scalar p, const scalar T) const
Un-isotropic thermal conductivity [W/mK].
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
constIsoSolidTransport & operator= (const constIsoSolidTransport &)
void operator+= (const constIsoSolidTransport &)
void operator-= (const constIsoSolidTransport &)
Static Public Member Functions
static autoPtr< constIsoSolidTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool isotropic = true
Is the thermal conductivity isotropic.
Friends
constIsoSolidTransport operator* (const scalar, const constIsoSolidTransport &)
Ostream & operator (Ostream &, const constIsoSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::constIsoSolidTransport< Thermo >
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
Source files
constIsoSolidTransport.H
constIsoSolidTransportI.H
constIsoSolidTransport.C
Definition at line 47 of file constIsoSolidTransport.H.
Constructor & Destructor Documentation
constIsoSolidTransport() [1/2]
constIsoSolidTransport (const word & name, const constIsoSolidTransport< Thermo > & ct) inline
Construct as named copy.
Definition at line 42 of file constIsoSolidTransportI.H.
References constIsoSolidTransport< Thermo >::New().
constIsoSolidTransport() [2/2]
constIsoSolidTransport (const dictionary & dict)
Construct from Istream.
Definition at line 33 of file constIsoSolidTransport.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::tab, and write().
Member Function Documentation
New()
Foam::autoPtr< Foam::constIsoSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 55 of file constIsoSolidTransportI.H.
References dict, and constIsoSolidTransport< Thermo >::kappa().
Referenced by constIsoSolidTransport< Thermo >::constIsoSolidTransport().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 109 of file constIsoSolidTransport.H.
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Isotropic thermal conductivity [W/mK].
Definition at line 69 of file constIsoSolidTransportI.H.
References constIsoSolidTransport< Thermo >::Kappa().
Referenced by constIsoSolidTransport< Thermo >::New().
Kappa()
Foam::vector Kappa (const scalar p, const scalar T) const inline
Un-isotropic thermal conductivity [W/mK].
Definition at line 76 of file constIsoSolidTransportI.H.
References constIsoSolidTransport< Thermo >::mu().
Referenced by constIsoSolidTransport< Thermo >::kappa().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 84 of file constIsoSolidTransportI.H.
References constIsoSolidTransport< Thermo >::alphah(), and notImplemented.
Referenced by constIsoSolidTransport< Thermo >::Kappa().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 99 of file constIsoSolidTransportI.H.
Referenced by constIsoSolidTransport< Thermo >::mu().
write()
void write (Ostream & os) const
Write to Ostream.
operator=()
Foam::constIsoSolidTransport< thermo > & operator= (const constIsoSolidTransport< Thermo > &) inline
Definition at line 109 of file constIsoSolidTransportI.H.
operator+=()
void operator+= (const constIsoSolidTransport< Thermo > &) inline
Definition at line 121 of file constIsoSolidTransportI.H.
operator-=()
void operator-= (const constIsoSolidTransport< Thermo > &) inline
Definition at line 137 of file constIsoSolidTransportI.H.
References s().
Friends And Related Function Documentation
operator*
constIsoSolidTransport operator* (const scalar , const constIsoSolidTransport< Thermo > &) friend
operator
Ostream& operator (Ostream & , const constIsoSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
const bool isotropic = true static
Is the thermal conductivity isotropic.
Definition at line 115 of file constIsoSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/const/constIsoSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/const/constIsoSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/const/constIsoSolidTransportI.H