OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LindemannFallOffFunction Class Reference
Lindemann fall-off function.
Public Member Functions
LindemannFallOffFunction ()
Construct null.
LindemannFallOffFunction (Istream &)
Construct from Istream.
LindemannFallOffFunction (const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar T, const scalar Pr) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const LindemannFallOffFunction &)
Detailed Description
Lindemann fall-off function.
Source files
LindemannFallOffFunction.H
LindemannFallOffFunctionI.H
Definition at line 54 of file LindemannFallOffFunction.H.
Constructor & Destructor Documentation
LindemannFallOffFunction() [1/3]
LindemannFallOffFunction () inline
Construct null.
Definition at line 28 of file LindemannFallOffFunctionI.H.
Referenced by LindemannFallOffFunction::LindemannFallOffFunction().
LindemannFallOffFunction() [2/3]
LindemannFallOffFunction (Istream &) inline
Construct from Istream.
Definition at line 32 of file LindemannFallOffFunctionI.H.
References LindemannFallOffFunction::LindemannFallOffFunction().
LindemannFallOffFunction() [3/3]
LindemannFallOffFunction (const dictionary & dict) inline
Construct from dictionary.
Definition at line 37 of file LindemannFallOffFunctionI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 74 of file LindemannFallOffFunction.H.
References LindemannFallOffFunction::operator<<, Pr(), Foam::T(), and LindemannFallOffFunction::write().
operator()()
Foam::scalar operator() (const scalar T, const scalar Pr) const inline
Definition at line 46 of file LindemannFallOffFunctionI.H.
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 55 of file LindemannFallOffFunctionI.H.
Referenced by LindemannFallOffFunction::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const LindemannFallOffFunction &) friend
Referenced by LindemannFallOffFunction::type().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/LindemannFallOffFunction/LindemannFallOffFunction.H
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/LindemannFallOffFunction/LindemannFallOffFunctionI.H