OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SRIFallOffFunction Class Reference
The SRI fall-off function.
Public Member Functions
SRIFallOffFunction (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
SRIFallOffFunction (Istream &)
Construct from Istream.
SRIFallOffFunction (const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar T, const scalar Pr) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const SRIFallOffFunction &)
Detailed Description
The SRI fall-off function.
Source files
SRIFallOffFunction.H
SRIFallOffFunctionI.H
Definition at line 54 of file SRIFallOffFunction.H.
Constructor & Destructor Documentation
SRIFallOffFunction() [1/3]
SRIFallOffFunction (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e) inline
Construct from components.
Definition at line 29 of file SRIFallOffFunctionI.H.
SRIFallOffFunction() [2/3]
SRIFallOffFunction (Istream & is) inline
Construct from Istream.
Definition at line 45 of file SRIFallOffFunctionI.H.
References Istream::readEnd().
SRIFallOffFunction() [3/3]
SRIFallOffFunction (const dictionary & dict) inline
Construct from dictionary.
Definition at line 57 of file SRIFallOffFunctionI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 85 of file SRIFallOffFunction.H.
References SRIFallOffFunction::operator<<, Pr(), Foam::T(), and SRIFallOffFunction::write().
operator()()
Foam::scalar operator() (const scalar T, const scalar Pr) const inline
Definition at line 70 of file SRIFallOffFunctionI.H.
References Foam::exp(), Foam::log10(), Foam::max(), Foam::pow(), Pr(), Foam::sqr(), and Foam::T().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 80 of file SRIFallOffFunctionI.H.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by SRIFallOffFunction::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const SRIFallOffFunction &) friend
Referenced by SRIFallOffFunction::type().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/SRIFallOffFunction/SRIFallOffFunction.H
src/thermophysicalModels/specie/reaction/reactionRate/fallOffFunctions/SRIFallOffFunction/SRIFallOffFunctionI.H