OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
adiabaticPerfectFluid< Specie > Class Template Reference
AdiabaticPerfect gas equation of state.
Public Member Functions
adiabaticPerfectFluid (const Specie &sp, const scalar p0, const scalar rho0, const scalar gamma, const scalar B)
Construct from components.
adiabaticPerfectFluid (Istream &)
Construct from Istream.
adiabaticPerfectFluid (const dictionary &dict)
Construct from dictionary.
adiabaticPerfectFluid (const word &name, const adiabaticPerfectFluid &)
Construct as named copy.
autoPtr< adiabaticPerfectFluid > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const adiabaticPerfectFluid &)
void operator-= (const adiabaticPerfectFluid &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< adiabaticPerfectFluid > New (Istream &is)
static autoPtr< adiabaticPerfectFluid > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
adiabaticPerfectFluid operator+ (const adiabaticPerfectFluid &, const adiabaticPerfectFluid &)
adiabaticPerfectFluid operator- (const adiabaticPerfectFluid &, const adiabaticPerfectFluid &)
adiabaticPerfectFluid operator* (const scalar s, const adiabaticPerfectFluid &)
adiabaticPerfectFluid operator== (const adiabaticPerfectFluid &, const adiabaticPerfectFluid &)
Ostream & operator (Ostream &, const adiabaticPerfectFluid &)
Detailed Description
template<class Specie>
class Foam::adiabaticPerfectFluid< Specie >
AdiabaticPerfect gas equation of state.
Source files
adiabaticPerfectFluid.H
adiabaticPerfectFluidI.H
adiabaticPerfectFluid.C
Definition at line 47 of file adiabaticPerfectFluid.H.
Constructor & Destructor Documentation
adiabaticPerfectFluid() [1/4]
adiabaticPerfectFluid (const Specie & sp, const scalar p0, const scalar rho0, const scalar gamma, const scalar B) inline
Construct from components.
Definition at line 32 of file adiabaticPerfectFluidI.H.
References name().
Referenced by adiabaticPerfectFluid< Specie >::adiabaticPerfectFluid().
adiabaticPerfectFluid() [2/4]
adiabaticPerfectFluid (Istream & is)
Construct from Istream.
Definition at line 32 of file adiabaticPerfectFluid.C.
References adiabaticPerfectFluid< Specie >::adiabaticPerfectFluid(), and IOstream::check().
adiabaticPerfectFluid() [3/4]
adiabaticPerfectFluid (const dictionary & dict)
Construct from dictionary.
Definition at line 49 of file adiabaticPerfectFluid.C.
adiabaticPerfectFluid() [4/4]
adiabaticPerfectFluid (const word & name, const adiabaticPerfectFluid< Specie > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::adiabaticPerfectFluid< Specie > > clone () const inline
Construct and return a clone.
Definition at line 67 of file adiabaticPerfectFluidI.H.
New() [1/2]
Foam::autoPtr< Foam::adiabaticPerfectFluid< Specie > > New (Istream & is) inline static
Definition at line 78 of file adiabaticPerfectFluidI.H.
New() [2/2]
Foam::autoPtr< Foam::adiabaticPerfectFluid< Specie > > New (const dictionary & dict) inline static
Definition at line 90 of file adiabaticPerfectFluidI.H.
References dict, and adiabaticPerfectFluid< Specie >::rho().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 152 of file adiabaticPerfectFluid.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 105 of file adiabaticPerfectFluidI.H.
References Foam::pow(), and adiabaticPerfectFluid< Specie >::psi().
Referenced by adiabaticPerfectFluid< Specie >::New().
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 116 of file adiabaticPerfectFluidI.H.
References Foam::pow().
Referenced by adiabaticPerfectFluid< Specie >::rho().
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 128 of file adiabaticPerfectFluidI.H.
References adiabaticPerfectFluid< Specie >::cpMcv().
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 136 of file adiabaticPerfectFluidI.H.
Referenced by adiabaticPerfectFluid< Specie >::Z().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 64 of file adiabaticPerfectFluid.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), token::SPACE, and write().
operator+=()
void operator+= (const adiabaticPerfectFluid< Specie > &) inline
Definition at line 149 of file adiabaticPerfectFluidI.H.
operator-=()
void operator-= (const adiabaticPerfectFluid< Specie > &) inline
Definition at line 169 of file adiabaticPerfectFluidI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 188 of file adiabaticPerfectFluidI.H.
References s().
Friends And Related Function Documentation
operator+
adiabaticPerfectFluid operator+ (const adiabaticPerfectFluid< Specie > & , const adiabaticPerfectFluid< Specie > &) friend
operator-
adiabaticPerfectFluid operator- (const adiabaticPerfectFluid< Specie > & , const adiabaticPerfectFluid< Specie > &) friend
operator*
adiabaticPerfectFluid operator* (const scalar s, const adiabaticPerfectFluid< Specie > &) friend
operator==
adiabaticPerfectFluid operator== (const adiabaticPerfectFluid< Specie > & , const adiabaticPerfectFluid< Specie > &) friend
operator
Ostream& operator (Ostream & , const adiabaticPerfectFluid< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 161 of file adiabaticPerfectFluid.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 164 of file adiabaticPerfectFluid.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/adiabaticPerfectFluid/adiabaticPerfectFluid.H
src/thermophysicalModels/specie/equationOfState/adiabaticPerfectFluid/adiabaticPerfectFluid.C
src/thermophysicalModels/specie/equationOfState/adiabaticPerfectFluid/adiabaticPerfectFluidI.H