OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ArrheniusReactionRate Class Reference
Arrhenius reaction rate given by:
Public Member Functions
ArrheniusReactionRate (const scalar A, const scalar beta, const scalar Ta)
Construct from components.
ArrheniusReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
ArrheniusReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const ArrheniusReactionRate &)
Detailed Description
Arrhenius reaction rate given by:
k = A * T^beta * exp(-Ta/T)
Source files
ArrheniusReactionRate.H
ArrheniusReactionRateI.H
Definition at line 51 of file ArrheniusReactionRate.H.
Constructor & Destructor Documentation
ArrheniusReactionRate() [1/3]
ArrheniusReactionRate (const scalar A, const scalar beta, const scalar Ta) inline
Construct from components.
Definition at line 29 of file ArrheniusReactionRateI.H.
Referenced by ArrheniusReactionRate::ArrheniusReactionRate().
ArrheniusReactionRate() [2/3]
ArrheniusReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 42 of file ArrheniusReactionRateI.H.
References ArrheniusReactionRate::ArrheniusReactionRate(), and Istream::readEnd().
ArrheniusReactionRate() [3/3]
ArrheniusReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 56 of file ArrheniusReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 90 of file ArrheniusReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and ArrheniusReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 70 of file ArrheniusReactionRateI.H.
References Foam::exp(), Foam::mag(), and Foam::pow().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 92 of file ArrheniusReactionRateI.H.
References token::BEGIN_LIST, token::END_LIST, token::END_STATEMENT, Foam::nl, token::SPACE, and Ostream::writeKeyword().
Referenced by ArrheniusReactionRate::type(), and thirdBodyArrheniusReactionRate::write().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const ArrheniusReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/ArrheniusReactionRate/ArrheniusReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/ArrheniusReactionRate/ArrheniusReactionRateI.H