OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
infiniteReactionRate Class Reference
infinite reaction rate.
Public Member Functions
infiniteReactionRate ()
Null constructor.
infiniteReactionRate (const speciesTable &species, const dictionary &dict)
Construct from Istream.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const infiniteReactionRate &)
Detailed Description
infinite reaction rate.
Source files
infiniteReactionRate.H
infiniteReactionRateI.H
Definition at line 49 of file infiniteReactionRate.H.
Constructor & Destructor Documentation
infiniteReactionRate() [1/2]
infiniteReactionRate () inline
Null constructor.
Definition at line 28 of file infiniteReactionRateI.H.
infiniteReactionRate() [2/2]
infiniteReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from Istream.
Definition at line 33 of file infiniteReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 70 of file infiniteReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and infiniteReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 47 of file infiniteReactionRateI.H.
References token::BEGIN_LIST, and token::END_LIST.
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 40 of file infiniteReactionRateI.H.
Referenced by infiniteReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const infiniteReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/infiniteReactionRate/infiniteReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/infiniteReactionRate/infiniteReactionRateI.H