OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
hExponentialThermo< EquationOfState > Class Template Reference
Exponential properties thermodynamics package templated into the equationOfState.
Public Member Functions
hExponentialThermo (Istream &)
Construct from Istream.
hExponentialThermo (const dictionary &)
Construct from dictionary.
hExponentialThermo (const word &, const hExponentialThermo &)
Construct as a named copy.
autoPtr< hExponentialThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar ha (const scalar p, const scalar T) const
Absolute enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar hc () const
chemical enthalpy [J/kg]
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void operator+= (const hExponentialThermo &)
void operator-= (const hExponentialThermo &)
Static Public Member Functions
static autoPtr< hExponentialThermo > New (Istream &is)
Selector from Istream.
static autoPtr< hExponentialThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hExponentialThermo operator+ (const hExponentialThermo &, const hExponentialThermo &)
hExponentialThermo operator- (const hExponentialThermo &, const hExponentialThermo &)
hExponentialThermo operator* (const scalar, const hExponentialThermo &)
hExponentialThermo operator== (const hExponentialThermo &, const hExponentialThermo &)
Ostream & operator (Ostream &, const hExponentialThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hExponentialThermo< EquationOfState >
Exponential properties thermodynamics package templated into the equationOfState.
Source files
hExponentialThermo.H
hExponentialThermoI.H
hExponentialThermo.C
Definition at line 48 of file hExponentialThermo.H.
Constructor & Destructor Documentation
hExponentialThermo() [1/3]
hExponentialThermo (Istream & is)
Construct from Istream.
Definition at line 32 of file hExponentialThermo.C.
References IOstream::check().
hExponentialThermo() [2/3]
hExponentialThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 48 of file hExponentialThermo.C.
References IOstream::check(), Foam::endl(), Foam::nl, and Foam::tab.
hExponentialThermo() [3/3]
hExponentialThermo (const word & name, const hExponentialThermo< EquationOfState > & jt) inline
Construct as a named copy.
Definition at line 65 of file hExponentialThermoI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::hExponentialThermo< equationOfState > > clone () const inline
Construct and return a clone.
Definition at line 100 of file hExponentialThermoI.H.
New() [1/2]
Foam::autoPtr< Foam::hExponentialThermo< equationOfState > > New (Istream & is) inline static
Selector from Istream.
Definition at line 111 of file hExponentialThermoI.H.
New() [2/2]
Foam::autoPtr< Foam::hExponentialThermo< equationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 122 of file hExponentialThermoI.H.
References dict, and hExponentialThermo< EquationOfState >::limit().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 154 of file hExponentialThermo.H.
References hExponentialThermo< EquationOfState >::cp(), hExponentialThermo< EquationOfState >::ha(), hExponentialThermo< EquationOfState >::hc(), hExponentialThermo< EquationOfState >::hs(), hExponentialThermo< EquationOfState >::limit(), hExponentialThermo< EquationOfState >::operator+=(), hExponentialThermo< EquationOfState >::operator-=(), p, hExponentialThermo< EquationOfState >::s(), and Foam::T().
limit()
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 135 of file hExponentialThermoI.H.
References hExponentialThermo< EquationOfState >::cp(), and T.
Referenced by hExponentialThermo< EquationOfState >::New(), and hExponentialThermo< EquationOfState >::typeName().
cp()
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 145 of file hExponentialThermoI.H.
References hExponentialThermo< EquationOfState >::ha(), and Foam::pow().
Referenced by hExponentialThermo< EquationOfState >::limit(), and hExponentialThermo< EquationOfState >::typeName().
ha()
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute enthalpy [J/kmol].
Definition at line 155 of file hExponentialThermoI.H.
References hExponentialThermo< EquationOfState >::hs(), and Foam::constant::standard::Tstd.
Referenced by hExponentialThermo< EquationOfState >::cp(), and hExponentialThermo< EquationOfState >::typeName().
hs()
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 170 of file hExponentialThermoI.H.
References Foam::constant::standard::Tstd.
Referenced by hExponentialThermo< EquationOfState >::ha(), and hExponentialThermo< EquationOfState >::typeName().
hc()
Foam::scalar hc () const inline
chemical enthalpy [J/kg]
Definition at line 180 of file hExponentialThermoI.H.
References hExponentialThermo< EquationOfState >::s().
Referenced by hExponentialThermo< EquationOfState >::typeName().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 188 of file hExponentialThermoI.H.
References notImplemented, and T.
Referenced by hExponentialThermo< EquationOfState >::hc(), and hExponentialThermo< EquationOfState >::typeName().
operator+=()
void operator+= (const hExponentialThermo< EquationOfState > &) inline
Definition at line 204 of file hExponentialThermoI.H.
Referenced by hExponentialThermo< EquationOfState >::typeName().
operator-=()
void operator-= (const hExponentialThermo< EquationOfState > &) inline
Definition at line 223 of file hExponentialThermoI.H.
References s().
Referenced by hExponentialThermo< EquationOfState >::typeName().
Friends And Related Function Documentation
operator+
hExponentialThermo operator+ (const hExponentialThermo< EquationOfState > & , const hExponentialThermo< EquationOfState > &) friend
operator-
hExponentialThermo operator- (const hExponentialThermo< EquationOfState > & , const hExponentialThermo< EquationOfState > &) friend
operator*
hExponentialThermo operator* (const scalar , const hExponentialThermo< EquationOfState > &) friend
operator==
hExponentialThermo operator== (const hExponentialThermo< EquationOfState > & , const hExponentialThermo< EquationOfState > &) friend
operator
Ostream& operator (Ostream & , const hExponentialThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hExponential/hExponentialThermo.H
src/thermophysicalModels/specie/thermo/hExponential/hExponentialThermo.C
src/thermophysicalModels/specie/thermo/hExponential/hExponentialThermoI.H