OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
constTransport< Thermo > Class Template Reference
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
Public Member Functions
constTransport (const word &, const constTransport &)
Construct as named copy.
constTransport (Istream &)
Construct from Istream.
constTransport (const dictionary &dict)
Construct from dictionary.
autoPtr< constTransport > clone () const
Construct and return a clone.
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
constTransport & operator= (const constTransport &)
void operator+= (const constTransport &)
void operator-= (const constTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< constTransport > New (Istream &is)
static autoPtr< constTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Friends
constTransport operator+ (const constTransport &, const constTransport &)
constTransport operator- (const constTransport &, const constTransport &)
constTransport operator* (const scalar, const constTransport &)
constTransport operator== (const constTransport &, const constTransport &)
Ostream & operator (Ostream &, const constTransport &)
Detailed Description
template<class Thermo>
class Foam::constTransport< Thermo >
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
Source files
constTransport.H
constTransportI.H
constTransport.C
Definition at line 47 of file constTransport.H.
Constructor & Destructor Documentation
constTransport() [1/3]
constTransport (const word & name, const constTransport< Thermo > & ct) inline
Construct as named copy.
Definition at line 44 of file constTransportI.H.
constTransport() [2/3]
constTransport (Istream & is)
Construct from Istream.
Definition at line 32 of file constTransport.C.
References IOstream::check().
constTransport() [3/3]
constTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 43 of file constTransport.C.
References dictionary::add(), token::BEGIN_BLOCK, IOstream::check(), Foam::decrIndent(), dict, dictionaryName::dictName(), token::END_BLOCK, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::name(), Foam::nl, Foam::tab, and write().
Member Function Documentation
clone()
Foam::autoPtr< Foam::constTransport< Thermo > > clone () const inline
Construct and return a clone.
Definition at line 57 of file constTransportI.H.
References constTransport< Thermo >::New().
New() [1/2]
Foam::autoPtr< Foam::constTransport< Thermo > > New (Istream & is) inline static
Definition at line 69 of file constTransportI.H.
Referenced by constTransport< Thermo >::clone().
New() [2/2]
Foam::autoPtr< Foam::constTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 83 of file constTransportI.H.
References dict, and constTransport< Thermo >::mu().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 140 of file constTransport.H.
References constTransport< Thermo >::alphah(), constTransport< Thermo >::kappa(), constTransport< Thermo >::mu(), constTransport< Thermo >::operator*=(), constTransport< Thermo >::operator+=(), constTransport< Thermo >::operator-=(), constTransport< Thermo >::operator=(), p, Foam::T(), and constTransport< Thermo >::write().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 98 of file constTransportI.H.
References constTransport< Thermo >::kappa().
Referenced by constTransport< Thermo >::alphah(), constTransport< Thermo >::kappa(), constTransport< Thermo >::New(), and constTransport< Thermo >::typeName().
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 109 of file constTransportI.H.
References constTransport< Thermo >::alphah(), and constTransport< Thermo >::mu().
Referenced by constTransport< Thermo >::mu(), and constTransport< Thermo >::typeName().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 120 of file constTransportI.H.
References constTransport< Thermo >::mu().
Referenced by constTransport< Thermo >::kappa(), and constTransport< Thermo >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Referenced by constTransport< Thermo >::typeName().
operator=()
Foam::constTransport< Thermo > & operator= (const constTransport< Thermo > &) inline
Definition at line 133 of file constTransportI.H.
Referenced by constTransport< Thermo >::typeName().
operator+=()
void operator+= (const constTransport< Thermo > &) inline
Definition at line 148 of file constTransportI.H.
References Foam::mag().
Referenced by constTransport< Thermo >::typeName().
operator-=()
void operator-= (const constTransport< Thermo > &) inline
Definition at line 169 of file constTransportI.H.
References Foam::mag().
Referenced by constTransport< Thermo >::typeName().
operator*=()
void operator*= (const scalar s) inline
Definition at line 190 of file constTransportI.H.
References Foam::mag(), and s().
Referenced by constTransport< Thermo >::typeName().
Friends And Related Function Documentation
operator+
constTransport operator+ (const constTransport< Thermo > & , const constTransport< Thermo > &) friend
operator-
constTransport operator- (const constTransport< Thermo > & , const constTransport< Thermo > &) friend
operator*
constTransport operator* (const scalar , const constTransport< Thermo > &) friend
operator==
constTransport operator== (const constTransport< Thermo > & , const constTransport< Thermo > &) friend
operator
Ostream& operator (Ostream & , const constTransport< Thermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/const/constTransport.H
src/thermophysicalModels/specie/transport/const/constTransport.C
src/thermophysicalModels/specie/transport/const/constTransportI.H