OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
absoluteEnthalpy< Thermo > Class Template Reference
Thermodynamics mapping class to expose the absolute enthalpy function as the standard enthalpy function h(T).
Public Member Functions
absoluteEnthalpy ()
Construct.
scalar he (const Thermo &thermo, const scalar p, const scalar T) const
scalar cpv (const Thermo &thermo, const scalar p, const scalar T) const
scalar cpBycpv (const Thermo &thermo, const scalar p, const scalar T) const
cp/cp []
scalar HE (const Thermo &thermo, const scalar p, const scalar T) const
scalar THE (const Thermo &thermo, const scalar h, const scalar p, const scalar T0) const
Temperature from absolute enthalpy.
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
static word name ()
Detailed Description
template<class Thermo>
class Foam::absoluteEnthalpy< Thermo >
Thermodynamics mapping class to expose the absolute enthalpy function as the standard enthalpy function h(T).
Definition at line 45 of file absoluteEnthalpy.H.
Constructor & Destructor Documentation
absoluteEnthalpy()
absoluteEnthalpy () inline
Construct.
Definition at line 53 of file absoluteEnthalpy.H.
Member Function Documentation
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 60 of file absoluteEnthalpy.H.
name()
static word name () inline static
Definition at line 67 of file absoluteEnthalpy.H.
References absoluteEnthalpy< Thermo >::he().
he()
scalar he (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 74 of file absoluteEnthalpy.H.
References absoluteEnthalpy< Thermo >::cpv().
Referenced by absoluteEnthalpy< Thermo >::name().
cpv()
scalar cpv (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 85 of file absoluteEnthalpy.H.
References absoluteEnthalpy< Thermo >::cpBycpv().
Referenced by absoluteEnthalpy< Thermo >::he().
cpBycpv()
scalar cpBycpv (const Thermo & thermo, const scalar p, const scalar T) const inline
cp/cp []
Definition at line 96 of file absoluteEnthalpy.H.
References absoluteEnthalpy< Thermo >::HE().
Referenced by absoluteEnthalpy< Thermo >::cpv().
HE()
scalar HE (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 107 of file absoluteEnthalpy.H.
References absoluteEnthalpy< Thermo >::THE().
Referenced by absoluteEnthalpy< Thermo >::cpBycpv().
THE()
scalar THE (const Thermo & thermo, const scalar h, const scalar p, const scalar T0) const inline
Temperature from absolute enthalpy.
given an initial temperature T0
Definition at line 119 of file absoluteEnthalpy.H.
Referenced by absoluteEnthalpy< Thermo >::HE().
The documentation for this class was generated from the following file:
src/thermophysicalModels/specie/thermo/absoluteEnthalpy/absoluteEnthalpy.H