OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LangmuirHinshelwoodReactionRate Class Reference
Power series reaction rate.
Public Member Functions
LangmuirHinshelwoodReactionRate (const scalar A[], const scalar Ta[], const label co, const label c3h6, const label no)
Construct from components.
LangmuirHinshelwoodReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
LangmuirHinshelwoodReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const LangmuirHinshelwoodReactionRate &)
Detailed Description
Power series reaction rate.
Source files
LangmuirHinshelwoodReactionRate.H
LangmuirHinshelwoodReactionRateI.H
Definition at line 49 of file LangmuirHinshelwoodReactionRate.H.
Constructor & Destructor Documentation
LangmuirHinshelwoodReactionRate() [1/3]
LangmuirHinshelwoodReactionRate (const scalar A[], const scalar Ta[], const label co, const label c3h6, const label no) inline
Construct from components.
Definition at line 32 of file LangmuirHinshelwoodReactionRateI.H.
Referenced by LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate().
LangmuirHinshelwoodReactionRate() [2/3]
LangmuirHinshelwoodReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 53 of file LangmuirHinshelwoodReactionRateI.H.
References LangmuirHinshelwoodReactionRate::LangmuirHinshelwoodReactionRate(), Istream::readBegin(), and Istream::readEnd().
LangmuirHinshelwoodReactionRate() [3/3]
LangmuirHinshelwoodReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 74 of file LangmuirHinshelwoodReactionRateI.H.
References forAll, and dictionary::lookup().
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 94 of file LangmuirHinshelwoodReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and LangmuirHinshelwoodReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 97 of file LangmuirHinshelwoodReactionRateI.H.
References Foam::constant::universal::c, Foam::exp(), Foam::pow(), and sqr().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 113 of file LangmuirHinshelwoodReactionRateI.H.
References token::BEGIN_LIST, token::END_LIST, FixedList< T, Size >::first(), forAll, Foam::nl, token::SPACE, and Ostream::writeKeyword().
Referenced by LangmuirHinshelwoodReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const LangmuirHinshelwoodReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/LangmuirHinshelwood/LangmuirHinshelwoodReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/LangmuirHinshelwood/LangmuirHinshelwoodReactionRateI.H