OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Reaction< ReactionThermo >::iNew Class Reference
Class used for the read-construction of PtrLists of reaction.
Public Member Functions
iNew (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase)
autoPtr< Reaction > operator() (Istream &is) const
Detailed Description
template<class ReactionThermo>
class Foam::Reaction< ReactionThermo >::iNew
Class used for the read-construction of PtrLists of reaction.
Definition at line 196 of file Reaction.H.
Constructor & Destructor Documentation
iNew()
iNew (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase) inline
Definition at line 204 of file Reaction.H.
Member Function Documentation
operator()()
autoPtr<Reaction> operator() (Istream & is) const inline
Definition at line 213 of file Reaction.H.
References Reaction< ReactionThermo >::lhs(), Reaction< ReactionThermo >::New(), Reaction< ReactionThermo >::Reaction(), and Reaction< ReactionThermo >::rhs().
The documentation for this class was generated from the following file:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H