OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
powerSeriesReactionRate Class Reference
Power series reaction rate.
Public Member Functions
powerSeriesReactionRate (const scalar A, const scalar beta, const scalar Ta, const FixedList< scalar, nCoeff_ > coeffs)
Construct from components.
powerSeriesReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
powerSeriesReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const powerSeriesReactionRate &)
Detailed Description
Power series reaction rate.
Source files
powerSeriesReactionRate.H
powerSeriesReactionRateI.H
Definition at line 50 of file powerSeriesReactionRate.H.
Constructor & Destructor Documentation
powerSeriesReactionRate() [1/3]
powerSeriesReactionRate (const scalar A, const scalar beta, const scalar Ta, const FixedList< scalar, nCoeff_ > coeffs) inline
Construct from components.
Definition at line 29 of file powerSeriesReactionRateI.H.
Referenced by powerSeriesReactionRate::powerSeriesReactionRate().
powerSeriesReactionRate() [2/3]
powerSeriesReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 44 of file powerSeriesReactionRateI.H.
References powerSeriesReactionRate::powerSeriesReactionRate(), and Istream::readEnd().
powerSeriesReactionRate() [3/3]
powerSeriesReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 59 of file powerSeriesReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 93 of file powerSeriesReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and powerSeriesReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 74 of file powerSeriesReactionRateI.H.
References Foam::exp(), forAll, Foam::mag(), n, and Foam::pow().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 100 of file powerSeriesReactionRateI.H.
References token::BEGIN_LIST, token::END_LIST, token::END_STATEMENT, n, Foam::nl, token::SPACE, and Ostream::writeKeyword().
Referenced by powerSeriesReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const powerSeriesReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/powerSeries/powerSeriesReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/powerSeries/powerSeriesReactionRateI.H