OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LandauTellerReactionRate Class Reference
Landau-Teller reaction rate.
Public Member Functions
LandauTellerReactionRate (const scalar A, const scalar beta, const scalar Ta, const scalar B, const scalar C)
Construct from components.
LandauTellerReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
LandauTellerReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const LandauTellerReactionRate &)
Detailed Description
Landau-Teller reaction rate.
Source files
LandauTellerReactionRate.H
LandauTellerReactionRateI.H
Definition at line 49 of file LandauTellerReactionRate.H.
Constructor & Destructor Documentation
LandauTellerReactionRate() [1/3]
LandauTellerReactionRate (const scalar A, const scalar beta, const scalar Ta, const scalar B, const scalar C) inline
Construct from components.
Definition at line 29 of file LandauTellerReactionRateI.H.
Referenced by LandauTellerReactionRate::LandauTellerReactionRate().
LandauTellerReactionRate() [2/3]
LandauTellerReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 46 of file LandauTellerReactionRateI.H.
References LandauTellerReactionRate::LandauTellerReactionRate(), and Istream::readEnd().
LandauTellerReactionRate() [3/3]
LandauTellerReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 62 of file LandauTellerReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 92 of file LandauTellerReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and LandauTellerReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 78 of file LandauTellerReactionRateI.H.
References Foam::cbrt(), Foam::exp(), Foam::mag(), Foam::pow(), and T.
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 117 of file LandauTellerReactionRateI.H.
References token::BEGIN_LIST, token::END_LIST, token::END_STATEMENT, Foam::nl, token::SPACE, and Ostream::writeKeyword().
Referenced by LandauTellerReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const LandauTellerReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/LandauTellerReactionRate/LandauTellerReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/LandauTellerReactionRate/LandauTellerReactionRateI.H