OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
specie Class Reference
Base class of the thermophysical property types.
Public Member Functions
ClassName ("specie")
Runtime type information.
specie (const scalar nMoles, const scalar molWeight)
Construct from components without name.
specie (const word &name, const scalar nMoles, const scalar molWeight)
Construct from components with name.
specie (const specie &)
Construct as copy.
specie (const word &name, const specie &)
Construct as named copy.
specie (Istream &)
Construct from Istream.
specie (const dictionary &dict)
Construct from dictionary.
const word & name () const
Name.
scalar W () const
Molecular weight [kg/kmol].
scalar nMoles () const
No of moles of this species in mixture.
scalar R () const
Gas constant [J/(kg K)].
void write (Ostream &os) const
Write to Ostream.
void operator= (const specie &)
void operator+= (const specie &)
void operator-= (const specie &)
void operator*= (const scalar)
Static Public Attributes
static const scalar RR = constant::physicoChemical::R.value()*1000
Universal gas constant [J/(kmol K)].
static const scalar Pstd = constant::standard::Pstd.value()
Standard pressure [Pa].
static const scalar Tstd = constant::standard::Tstd.value()
Standard temperature [K].
Friends
specie operator+ (const specie &, const specie &)
specie operator- (const specie &, const specie &)
specie operator* (const scalar, const specie &)
specie operator== (const specie &, const specie &)
Ostream & operator<< (Ostream &, const specie &)
Detailed Description
Base class of the thermophysical property types.
Source files
specie.H
specieI.H
specie.C
Definition at line 54 of file specie.H.
Constructor & Destructor Documentation
specie() [1/6]
specie (const scalar nMoles, const scalar molWeight) inline
Construct from components without name.
Definition at line 49 of file specieI.H.
Referenced by Foam::operator*(), Foam::operator+(), Foam::operator-(), and specie::specie().
specie() [2/6]
specie (const word & name, const scalar nMoles, const scalar molWeight) inline
Construct from components with name.
Definition at line 36 of file specieI.H.
References specie::specie().
specie() [3/6]
specie (const specie & st) inline
Construct as copy.
Definition at line 61 of file specieI.H.
specie() [4/6]
specie (const word & name, const specie & st) inline
Construct as named copy.
Definition at line 69 of file specieI.H.
specie() [5/6]
specie (Istream & is)
Construct from Istream.
Definition at line 49 of file specie.C.
References IOstream::check().
specie() [6/6]
specie (const dictionary & dict)
Construct from dictionary.
Definition at line 59 of file specie.C.
Member Function Documentation
ClassName()
ClassName ("specie")
Runtime type information.
name()
const word & name () const inline
Name.
Definition at line 79 of file specieI.H.
Referenced by sutherlandTransport< Thermo >::write().
W()
scalar W () const inline
Molecular weight [kg/kmol].
Definition at line 85 of file specieI.H.
nMoles()
scalar nMoles () const inline
No of moles of this species in mixture.
Definition at line 91 of file specieI.H.
R()
scalar R () const inline
Gas constant [J/(kg K)].
Definition at line 97 of file specieI.H.
References specie::RR.
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 69 of file specie.C.
References dictionary::add(), IOstream::check(), dict, dictionaryName::dictName(), Foam::indent(), Foam::operator<<(), and Foam::tab.
operator=()
void operator= (const specie & st) inline
Definition at line 105 of file specieI.H.
operator+=()
void operator+= (const specie & st) inline
Definition at line 113 of file specieI.H.
References Foam::max().
operator-=()
void operator-= (const specie & st) inline
Definition at line 125 of file specieI.H.
References Foam::mag().
operator*=()
void operator*= (const scalar s) inline
Definition at line 141 of file specieI.H.
References s().
Friends And Related Function Documentation
operator+
specie operator+ (const specie & st1, const specie & st2) friend
Definition at line 149 of file specieI.H.
operator-
specie operator- (const specie & st1, const specie & st2) friend
Definition at line 162 of file specieI.H.
operator*
specie operator* (const scalar s, const specie & st) friend
Definition at line 179 of file specieI.H.
operator==
specie operator== (const specie & st1, const specie & st2) friend
Definition at line 189 of file specieI.H.
operator<<
Ostream& operator<< (Ostream & , const specie &) friend
Member Data Documentation
RR
const Foam::scalar RR = constant::physicoChemical::R.value()*1000 static
Universal gas constant [J/(kmol K)].
Universal gas constant (default in [J/(kmol K)])
Definition at line 79 of file specie.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), ReactingParcel< ParcelType >::correctSurfaceValues(), PengRobinsonGas< Specie >::PengRobinsonGas(), liquidMixtureProperties::Ppc(), and specie::R().
Pstd
const Foam::scalar Pstd = constant::standard::Pstd.value() static
Standard pressure [Pa].
Standard pressure (default in [Pa])
Definition at line 82 of file specie.H.
Tstd
const Foam::scalar Tstd = constant::standard::Tstd.value() static
Standard temperature [K].
Standard temperature (default in [K])
Definition at line 85 of file specie.H.
Referenced by janafThermo< EquationOfState >::hc(), and solidProperties::Hs().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/specie/specie.H
src/thermophysicalModels/specie/specie/specie.C
src/thermophysicalModels/specie/specie/specieI.H