OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
thermo< Thermo, Type > Class Template Reference
Public Types
typedef thermo< Thermo, Type > thermoType
The thermodynamics of the individual species'.
Public Member Functions
thermo (const Thermo &sp)
construct from components
thermo (Istream &)
Construct from Istream.
thermo (const dictionary &dict)
Construct from dictionary.
thermo (const word &name, const thermo &)
Construct as named copy.
scalar he (const scalar p, const scalar T) const
Enthalpy/Internal energy [J/kmol].
scalar cv (const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kmol K)].
scalar cpv (const scalar p, const scalar T) const
Heat capacity at constant pressure/volume [J/(kmol K)].
scalar gamma (const scalar p, const scalar T) const
gamma = cp/cv []
scalar cpBycpv (const scalar p, const scalar T) const
Ratio of heat capacity at constant pressure to that at.
scalar es (const scalar p, const scalar T) const
Sensible internal energy [J/kmol].
scalar ea (const scalar p, const scalar T) const
Absolute internal energy [J/kmol].
scalar g (const scalar p, const scalar T) const
Gibbs free energy [J/kmol].
scalar a (const scalar p, const scalar T) const
Helmholtz free energy [J/kmol].
scalar Cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar Cv (const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kg K)].
scalar Cpv (const scalar p, const scalar T) const
Heat capacity at constant pressure/volume [J/(kg K)].
scalar HE (const scalar p, const scalar T) const
Enthalpy/Internal energy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar E (const scalar p, const scalar T) const
Internal energy [J/kg].
scalar Es (const scalar p, const scalar T) const
Sensible internal energy [J/kg].
scalar Ea (const scalar p, const scalar T) const
Absolute internal energy [J/kg].
scalar G (const scalar p, const scalar T) const
Gibbs free energy [J/kg].
scalar A (const scalar p, const scalar T) const
Helmholtz free energy [J/kg].
scalar K (const scalar p, const scalar T) const
Equilibrium constant [] i.t.o fugacities.
scalar Kp (const scalar p, const scalar T) const
Equilibrium constant [] i.t.o. partial pressures.
scalar Kc (const scalar p, const scalar T) const
Equilibrium constant i.t.o. molar concentration.
scalar Kx (const scalar p, const scalar T) const
Equilibrium constant [] i.t.o. mole-fractions.
scalar Kn (const scalar p, const scalar T, const scalar n) const
Equilibrium constant [] i.t.o. number of moles.
scalar THE (const scalar H, const scalar p, const scalar T0) const
Temperature from enthalpy or internal energy.
scalar THs (const scalar Hs, const scalar p, const scalar T0) const
Temperature from sensible enthalpy given an initial T0.
scalar THa (const scalar H, const scalar p, const scalar T0) const
Temperature from absolute enthalpy.
scalar TEs (const scalar E, const scalar p, const scalar T0) const
Temperature from sensible internal energy.
scalar TEa (const scalar E, const scalar p, const scalar T0) const
Temperature from absolute internal energy.
void write (Ostream &os) const
Write to Ostream.
void operator+= (const thermo &)
void operator-= (const thermo &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
static word heName ()
Name of Enthalpy/Internal energy.
Friends
thermo operator+ (const thermo &, const thermo &)
thermo operator- (const thermo &, const thermo &)
thermo operator* (const scalar s, const thermo &)
thermo operator== (const thermo &, const thermo &)
Ostream & operator (Ostream &, const thermo &)
Detailed Description
template<class Thermo, template< class > class Type>
class Foam::species::thermo< Thermo, Type >
Definition at line 49 of file thermo.H.
Member Typedef Documentation
thermoType
typedef thermo<Thermo, Type> thermoType
The thermodynamics of the individual species'.
Definition at line 125 of file thermo.H.
Constructor & Destructor Documentation
thermo() [1/4]
thermo (const Thermo & sp) inline
construct from components
Definition at line 32 of file thermoI.H.
References Foam::abort(), f(), Foam::constant::physicoChemical::F, Foam::FatalError, FatalErrorIn, limit(), Foam::mag(), and p.
thermo() [2/4]
thermo (Istream & is)
Construct from Istream.
Definition at line 41 of file thermo.C.
References IOstream::check().
thermo() [3/4]
thermo (const dictionary & dict)
Construct from dictionary.
Definition at line 50 of file thermo.C.
thermo() [4/4]
thermo (const word & name, const thermo< Thermo, Type > & st) inline
Construct as named copy.
Definition at line 90 of file thermoI.H.
Member Function Documentation
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 146 of file thermo.H.
References thermo< Thermo, Type >::a(), thermo< Thermo, Type >::A(), thermo< Thermo, Type >::Cp(), thermo< Thermo, Type >::cpBycpv(), thermo< Thermo, Type >::cpv(), thermo< Thermo, Type >::Cpv(), thermo< Thermo, Type >::cv(), thermo< Thermo, Type >::Cv(), thermo< Thermo, Type >::E(), thermo< Thermo, Type >::ea(), thermo< Thermo, Type >::Ea(), thermo< Thermo, Type >::es(), thermo< Thermo, Type >::Es(), thermo< Thermo, Type >::g(), thermo< Thermo, Type >::G(), thermo< Thermo, Type >::gamma(), thermo< Thermo, Type >::Ha(), thermo< Thermo, Type >::Hc(), thermo< Thermo, Type >::he(), thermo< Thermo, Type >::HE(), thermo< Thermo, Type >::heName(), thermo< Thermo, Type >::Hs(), thermo< Thermo, Type >::K(), thermo< Thermo, Type >::Kc(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kp(), thermo< Thermo, Type >::Kx(), n, thermo< Thermo, Type >::operator*=(), thermo< Thermo, Type >::operator+=(), thermo< Thermo, Type >::operator-=(), s(), thermo< Thermo, Type >::S(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THE(), thermo< Thermo, Type >::THs(), and thermo< Thermo, Type >::write().
heName()
Foam::word heName () inline static
Name of Enthalpy/Internal energy.
Definition at line 103 of file thermoI.H.
References name().
Referenced by thermo< Thermo, Type >::typeName().
he()
Foam::scalar he (const scalar p, const scalar T) const inline
Enthalpy/Internal energy [J/kmol].
Definition at line 111 of file thermoI.H.
References he.
Referenced by thermo< Thermo, Type >::typeName().
cv()
Foam::scalar cv (const scalar p, const scalar T) const inline
Heat capacity at constant volume [J/(kmol K)].
Definition at line 119 of file thermoI.H.
References cp.
Referenced by thermo< Thermo, Type >::typeName().
cpv()
Foam::scalar cpv (const scalar p, const scalar T) const inline
Heat capacity at constant pressure/volume [J/(kmol K)].
Definition at line 127 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
gamma()
Foam::scalar gamma (const scalar p, const scalar T) const inline
gamma = cp/cv []
Definition at line 135 of file thermoI.H.
References cp, and thermo< Thermo, Type >::cpBycpv().
Referenced by thermo< Thermo, Type >::typeName().
cpBycpv()
Foam::scalar cpBycpv (const scalar p, const scalar T) const inline
Ratio of heat capacity at constant pressure to that at.
constant pressure/volume []
Definition at line 145 of file thermoI.H.
Referenced by thermo< Thermo, Type >::gamma(), and thermo< Thermo, Type >::typeName().
es()
Foam::scalar es (const scalar p, const scalar T) const inline
Sensible internal energy [J/kmol].
Definition at line 156 of file thermoI.H.
References rho.
Referenced by thermo< Thermo, Type >::typeName().
ea()
Foam::scalar ea (const scalar p, const scalar T) const inline
Absolute internal energy [J/kmol].
Definition at line 164 of file thermoI.H.
References rho.
Referenced by thermo< Thermo, Type >::typeName().
g()
Foam::scalar g (const scalar p, const scalar T) const inline
Gibbs free energy [J/kmol].
Definition at line 172 of file thermoI.H.
References s().
Referenced by thermo< Thermo, Type >::typeName().
a()
Foam::scalar a (const scalar p, const scalar T) const inline
Helmholtz free energy [J/kmol].
Definition at line 180 of file thermoI.H.
References s().
Referenced by thermo< Thermo, Type >::typeName().
Cp()
Foam::scalar Cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 196 of file thermoI.H.
References cp.
Referenced by thermo< Thermo, Type >::typeName().
Cv()
Foam::scalar Cv (const scalar p, const scalar T) const inline
Heat capacity at constant volume [J/(kg K)].
Definition at line 204 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
Cpv()
Foam::scalar Cpv (const scalar p, const scalar T) const inline
Heat capacity at constant pressure/volume [J/(kg K)].
Definition at line 188 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
HE()
Foam::scalar HE (const scalar p, const scalar T) const inline
Enthalpy/Internal energy [J/kg].
Definition at line 212 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
Hs()
Foam::scalar Hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 220 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
Hc()
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 228 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
Ha()
Foam::scalar Ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kg].
Definition at line 236 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
S()
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 244 of file thermoI.H.
References s().
Referenced by thermo< Thermo, Type >::typeName().
E()
Foam::scalar E (const scalar p, const scalar T) const inline
Internal energy [J/kg].
Definition at line 252 of file thermoI.H.
References Foam::constant::electromagnetic::e.
Referenced by thermo< Thermo, Type >::typeName().
Es()
Foam::scalar Es (const scalar p, const scalar T) const inline
Sensible internal energy [J/kg].
Definition at line 260 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
Ea()
Foam::scalar Ea (const scalar p, const scalar T) const inline
Absolute internal energy [J/kg].
Definition at line 267 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
G()
Foam::scalar G (const scalar p, const scalar T) const inline
Gibbs free energy [J/kg].
Definition at line 275 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
A()
Foam::scalar A (const scalar p, const scalar T) const inline
Helmholtz free energy [J/kg].
Definition at line 283 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
K()
Foam::scalar K (const scalar p, const scalar T) const inline
Equilibrium constant [] i.t.o fugacities.
= PIi(fi/Pstd)^nui
Definition at line 291 of file thermoI.H.
References Foam::exp(), and T.
Referenced by thermo< Thermo, Type >::typeName().
Kp()
Foam::scalar Kp (const scalar p, const scalar T) const inline
Equilibrium constant [] i.t.o. partial pressures.
= PIi(pi/Pstd)^nui For low pressures (where the gas mixture is near perfect) Kp = K
Definition at line 308 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
Kc()
Foam::scalar Kc (const scalar p, const scalar T) const inline
Equilibrium constant i.t.o. molar concentration.
= PIi(ci/cstd)^nui For low pressures (where the gas mixture is near perfect) Kc = Kp(pstd/(RR*T))^nu
Definition at line 316 of file thermoI.H.
References equal(), thermo< Thermo, Type >::Kx(), Foam::pow(), and Foam::constant::standard::Pstd.
Referenced by thermo< Thermo, Type >::typeName().
Kx()
Foam::scalar Kx (const scalar p, const scalar T) const inline
Equilibrium constant [] i.t.o. mole-fractions.
For low pressures (where the gas mixture is near perfect) Kx = Kp(pstd/p)^nui
Definition at line 331 of file thermoI.H.
References equal(), thermo< Thermo, Type >::Kn(), Foam::pow(), and Foam::constant::standard::Pstd.
Referenced by thermo< Thermo, Type >::Kc(), and thermo< Thermo, Type >::typeName().
Kn()
Foam::scalar Kn (const scalar p, const scalar T, const scalar n) const inline
Equilibrium constant [] i.t.o. number of moles.
For low pressures (where the gas mixture is near perfect) Kn = Kp(n*pstd/p)^nui where n = number of moles in mixture
Definition at line 349 of file thermoI.H.
References equal(), Foam::pow(), Foam::constant::standard::Pstd, and thermo< Thermo, Type >::THE().
Referenced by thermo< Thermo, Type >::Kx(), and thermo< Thermo, Type >::typeName().
THE()
Foam::scalar THE (const scalar H, const scalar p, const scalar T0) const inline
Temperature from enthalpy or internal energy.
given an initial temperature T0
Definition at line 368 of file thermoI.H.
References thermo< Thermo, Type >::THs().
Referenced by thermo< Thermo, Type >::Kn(), and thermo< Thermo, Type >::typeName().
THs()
Foam::scalar THs (const scalar Hs, const scalar p, const scalar T0) const inline
Temperature from sensible enthalpy given an initial T0.
Definition at line 380 of file thermoI.H.
References T, and thermo< Thermo, Type >::THa().
Referenced by thermo< Thermo, Type >::THE(), and thermo< Thermo, Type >::typeName().
THa()
Foam::scalar THa (const scalar H, const scalar p, const scalar T0) const inline
Temperature from absolute enthalpy.
given an initial temperature T0
Definition at line 400 of file thermoI.H.
References T, and thermo< Thermo, Type >::TEs().
Referenced by thermo< Thermo, Type >::THs(), and thermo< Thermo, Type >::typeName().
TEs()
Foam::scalar TEs (const scalar E, const scalar p, const scalar T0) const inline
Temperature from sensible internal energy.
given an initial temperature T0
Definition at line 420 of file thermoI.H.
References T, and thermo< Thermo, Type >::TEa().
Referenced by thermo< Thermo, Type >::THa(), and thermo< Thermo, Type >::typeName().
TEa()
Foam::scalar TEa (const scalar E, const scalar p, const scalar T0) const inline
Temperature from absolute internal energy.
given an initial temperature T0
Definition at line 440 of file thermoI.H.
References T.
Referenced by thermo< Thermo, Type >::TEs(), and thermo< Thermo, Type >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 59 of file thermo.C.
References IOstream::check(), and write().
Referenced by thermo< Thermo, Type >::typeName().
operator+=()
void operator+= (const thermo< Thermo, Type > &) inline
Definition at line 462 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
operator-=()
void operator-= (const thermo< Thermo, Type > &) inline
Definition at line 472 of file thermoI.H.
Referenced by thermo< Thermo, Type >::typeName().
operator*=()
void operator*= (const scalar s) inline
Definition at line 481 of file thermoI.H.
References s().
Referenced by thermo< Thermo, Type >::typeName().
Friends And Related Function Documentation
operator+
thermo operator+ (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator-
thermo operator- (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator*
thermo operator* (const scalar s, const thermo< Thermo, Type > &) friend
operator==
thermo operator== (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator
Ostream& operator (Ostream & , const thermo< Thermo, Type > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/thermo/thermo.H
src/thermophysicalModels/specie/thermo/thermo/thermo.C
src/thermophysicalModels/specie/thermo/thermo/thermoI.H