OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
hPolynomialThermo< EquationOfState, PolySize > Class Template Reference
Thermodynamics package templated on the equation of state, using polynomial functions for cp, h and s.
Public Member Functions
hPolynomialThermo (Istream &is)
Construct from Istream.
hPolynomialThermo (const dictionary &dict)
Construct from dictionary.
hPolynomialThermo (const hPolynomialThermo &)
Construct as copy.
hPolynomialThermo (const word &, const hPolynomialThermo &)
Construct as a named copy.
scalar limit (const scalar) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kmol K)].
scalar ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kmol].
scalar hc () const
Chemical enthalpy [J/kmol].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void write (Ostream &os) const
Write to Ostream.
hPolynomialThermo & operator= (const hPolynomialThermo &)
void operator+= (const hPolynomialThermo &)
void operator-= (const hPolynomialThermo &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
Friends
hPolynomialThermo operator+ (const hPolynomialThermo &, const hPolynomialThermo &)
hPolynomialThermo operator- (const hPolynomialThermo &, const hPolynomialThermo &)
hPolynomialThermo operator* (const scalar, const hPolynomialThermo &)
hPolynomialThermo operator== (const hPolynomialThermo &, const hPolynomialThermo &)
Ostream & operator (Ostream &, const hPolynomialThermo &)
Detailed Description
template<class EquationOfState, int PolySize = 8>
class Foam::hPolynomialThermo< EquationOfState, PolySize >
Thermodynamics package templated on the equation of state, using polynomial functions for cp, h and s.
Polynomials for h and s derived from cp
Source files
hPolynomialThermo.H
hPolynomialThermoI.H
hPolynomialThermo.C
Definition at line 52 of file hPolynomialThermo.H.
Constructor & Destructor Documentation
hPolynomialThermo() [1/4]
hPolynomialThermo (Istream & is)
Construct from Istream.
Definition at line 33 of file hPolynomialThermo.C.
References Foam::constant::standard::Tstd.
hPolynomialThermo() [2/4]
hPolynomialThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 61 of file hPolynomialThermo.C.
References Foam::constant::standard::Tstd, and hPolynomialThermo< EquationOfState, PolySize >::write().
hPolynomialThermo() [3/4]
hPolynomialThermo (const hPolynomialThermo< EquationOfState, PolySize > & pt) inline
Construct as copy.
Definition at line 54 of file hPolynomialThermoI.H.
hPolynomialThermo() [4/4]
hPolynomialThermo (const word & name, const hPolynomialThermo< EquationOfState, PolySize > & pt) inline
Construct as a named copy.
Definition at line 69 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::limit().
Member Function Documentation
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 154 of file hPolynomialThermo.H.
References hPolynomialThermo< EquationOfState, PolySize >::cp(), hPolynomialThermo< EquationOfState, PolySize >::ha(), hPolynomialThermo< EquationOfState, PolySize >::hc(), hPolynomialThermo< EquationOfState, PolySize >::hs(), hPolynomialThermo< EquationOfState, PolySize >::limit(), hPolynomialThermo< EquationOfState, PolySize >::operator*=(), hPolynomialThermo< EquationOfState, PolySize >::operator+=(), hPolynomialThermo< EquationOfState, PolySize >::operator-=(), hPolynomialThermo< EquationOfState, PolySize >::operator=(), p, hPolynomialThermo< EquationOfState, PolySize >::s(), Foam::T(), and hPolynomialThermo< EquationOfState, PolySize >::write().
limit()
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 87 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::cp(), and Foam::T().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::hPolynomialThermo(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
cp()
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kmol K)].
Definition at line 97 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::ha().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::limit(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
ha()
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kmol].
Definition at line 107 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::hs().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::cp(), hPolynomialThermo< EquationOfState, PolySize >::hs(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
hs()
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kmol].
Definition at line 117 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::ha(), and hPolynomialThermo< EquationOfState, PolySize >::hc().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::ha(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
hc()
Foam::scalar hc () const inline
Chemical enthalpy [J/kmol].
Definition at line 126 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::s().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::hs(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 135 of file hPolynomialThermoI.H.
Referenced by hPolynomialThermo< EquationOfState, PolySize >::hc(), hPolynomialThermo< EquationOfState, PolySize >::operator*=(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 97 of file hPolynomialThermo.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::name(), Foam::tab, and write().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::hPolynomialThermo(), and hPolynomialThermo< EquationOfState, PolySize >::typeName().
operator=()
Foam::hPolynomialThermo< EquationOfState, PolySize > & operator= (const hPolynomialThermo< EquationOfState, PolySize > &) inline
Definition at line 149 of file hPolynomialThermoI.H.
Referenced by hPolynomialThermo< EquationOfState, PolySize >::typeName().
operator+=()
void operator+= (const hPolynomialThermo< EquationOfState, PolySize > &) inline
Definition at line 167 of file hPolynomialThermoI.H.
Referenced by hPolynomialThermo< EquationOfState, PolySize >::typeName().
operator-=()
void operator-= (const hPolynomialThermo< EquationOfState, PolySize > &) inline
Definition at line 188 of file hPolynomialThermoI.H.
Referenced by hPolynomialThermo< EquationOfState, PolySize >::typeName().
operator*=()
void operator*= (const scalar s) inline
Definition at line 209 of file hPolynomialThermoI.H.
References hPolynomialThermo< EquationOfState, PolySize >::s().
Referenced by hPolynomialThermo< EquationOfState, PolySize >::typeName().
Friends And Related Function Documentation
operator+
hPolynomialThermo operator+ (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator-
hPolynomialThermo operator- (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator*
hPolynomialThermo operator* (const scalar , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator==
hPolynomialThermo operator== (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
operator
Ostream& operator (Ostream & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermo.H
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermo.C
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermoI.H