OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polynomialTransport< Thermo, PolySize > Class Template Reference
Transport package using polynomial functions for mu and kappa.
Public Member Functions
polynomialTransport (const polynomialTransport &)
Construct copy.
polynomialTransport (const word &, const polynomialTransport &)
Construct as named copy.
polynomialTransport (Istream &is)
Construct from Istream.
polynomialTransport (const dictionary &dict)
Construct from dictionary.
autoPtr< polynomialTransport > clone () const
Construct and return a clone.
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
polynomialTransport & operator= (const polynomialTransport &)
void operator+= (const polynomialTransport &)
void operator-= (const polynomialTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< polynomialTransport > New (Istream &is)
static autoPtr< polynomialTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Friends
polynomialTransport operator+ (const polynomialTransport &, const polynomialTransport &)
polynomialTransport operator- (const polynomialTransport &, const polynomialTransport &)
polynomialTransport operator* (const scalar, const polynomialTransport &)
polynomialTransport operator== (const polynomialTransport &, const polynomialTransport &)
Ostream & operator (Ostream &, const polynomialTransport &)
Detailed Description
template<class Thermo, int PolySize = 8>
class Foam::polynomialTransport< Thermo, PolySize >
Transport package using polynomial functions for mu and kappa.
Source files
polynomialTransport.H
polynomialTransportI.H
polynomialTransport.C
Definition at line 47 of file polynomialTransport.H.
Constructor & Destructor Documentation
polynomialTransport() [1/4]
polynomialTransport (const polynomialTransport< Thermo, PolySize > & pt) inline
Construct copy.
Definition at line 32 of file polynomialTransportI.H.
polynomialTransport() [2/4]
polynomialTransport (const word & name, const polynomialTransport< Thermo, PolySize > & pt) inline
Construct as named copy.
Definition at line 58 of file polynomialTransportI.H.
polynomialTransport() [3/4]
polynomialTransport (Istream & is)
Construct from Istream.
Definition at line 32 of file polynomialTransport.C.
polynomialTransport() [4/4]
polynomialTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 45 of file polynomialTransport.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::polynomialTransport< Thermo, PolySize > > clone () const inline
Construct and return a clone.
Definition at line 71 of file polynomialTransportI.H.
New() [1/2]
Foam::autoPtr< Foam::polynomialTransport< Thermo, PolySize > > New (Istream & is) inline static
Definition at line 82 of file polynomialTransportI.H.
New() [2/2]
Foam::autoPtr< Foam::polynomialTransport< Thermo, PolySize > > New (const dictionary & dict) inline static
Definition at line 93 of file polynomialTransportI.H.
References dict, and polynomialTransport< Thermo, PolySize >::mu().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 145 of file polynomialTransport.H.
References polynomialTransport< Thermo, PolySize >::alphah(), polynomialTransport< Thermo, PolySize >::kappa(), polynomialTransport< Thermo, PolySize >::mu(), polynomialTransport< Thermo, PolySize >::operator*=(), polynomialTransport< Thermo, PolySize >::operator+=(), polynomialTransport< Thermo, PolySize >::operator-=(), polynomialTransport< Thermo, PolySize >::operator=(), p, Foam::T(), and polynomialTransport< Thermo, PolySize >::write().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 106 of file polynomialTransportI.H.
References polynomialTransport< Thermo, PolySize >::kappa().
Referenced by polynomialTransport< Thermo, PolySize >::New(), and polynomialTransport< Thermo, PolySize >::typeName().
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 117 of file polynomialTransportI.H.
References polynomialTransport< Thermo, PolySize >::alphah().
Referenced by polynomialTransport< Thermo, PolySize >::mu(), and polynomialTransport< Thermo, PolySize >::typeName().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 128 of file polynomialTransportI.H.
References Foam::constant::electromagnetic::kappa.
Referenced by polynomialTransport< Thermo, PolySize >::kappa(), and polynomialTransport< Thermo, PolySize >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 73 of file polynomialTransport.C.
References dictionary::add(), token::BEGIN_BLOCK, Foam::decrIndent(), dict, dictionaryName::dictName(), token::END_BLOCK, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::name(), Foam::nl, Foam::tab, and write().
Referenced by polynomialTransport< Thermo, PolySize >::typeName().
operator=()
Foam::polynomialTransport< Thermo, PolySize > & operator= (const polynomialTransport< Thermo, PolySize > &) inline
Definition at line 141 of file polynomialTransportI.H.
Referenced by polynomialTransport< Thermo, PolySize >::typeName().
operator+=()
void operator+= (const polynomialTransport< Thermo, PolySize > &) inline
Definition at line 156 of file polynomialTransportI.H.
Referenced by polynomialTransport< Thermo, PolySize >::typeName().
operator-=()
void operator-= (const polynomialTransport< Thermo, PolySize > &) inline
Definition at line 174 of file polynomialTransportI.H.
Referenced by polynomialTransport< Thermo, PolySize >::typeName().
operator*=()
void operator*= (const scalar s) inline
Definition at line 192 of file polynomialTransportI.H.
References s().
Referenced by polynomialTransport< Thermo, PolySize >::typeName().
Friends And Related Function Documentation
operator+
polynomialTransport operator+ (const polynomialTransport< Thermo, PolySize > & , const polynomialTransport< Thermo, PolySize > &) friend
operator-
polynomialTransport operator- (const polynomialTransport< Thermo, PolySize > & , const polynomialTransport< Thermo, PolySize > &) friend
operator*
polynomialTransport operator* (const scalar , const polynomialTransport< Thermo, PolySize > &) friend
operator==
polynomialTransport operator== (const polynomialTransport< Thermo, PolySize > & , const polynomialTransport< Thermo, PolySize > &) friend
operator
Ostream& operator (Ostream & , const polynomialTransport< Thermo, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/polynomial/polynomialTransport.H
src/thermophysicalModels/specie/transport/polynomial/polynomialTransport.C
src/thermophysicalModels/specie/transport/polynomial/polynomialTransportI.H