OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NSRDSfunc14 Class Reference
NSRDS function number 114.
Public Member Functions
TypeName ("NSRDSfunc14")
Runtime type information.
NSRDSfunc14 (const scalar Tc, const scalar a, const scalar b, const scalar c, const scalar d)
Construct from components.
NSRDSfunc14 (Istream &is)
Construct from Istream.
NSRDSfunc14 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc14 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS function number 114.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 67 of file NSRDSfunc14.H.
Constructor & Destructor Documentation
NSRDSfunc14() [1/3]
NSRDSfunc14 (const scalar Tc, const scalar a, const scalar b, const scalar c, const scalar d)
Construct from components.
Definition at line 46 of file NSRDSfunc14.C.
NSRDSfunc14() [2/3]
NSRDSfunc14 (Istream & is)
Construct from Istream.
Definition at line 62 of file NSRDSfunc14.C.
NSRDSfunc14() [3/3]
NSRDSfunc14 (const dictionary & dict)
Construct from dictionary.
Definition at line 72 of file NSRDSfunc14.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc14")
Runtime type information.
f()
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 105 of file NSRDSfunc14.H.
References Foam::min().
Referenced by C2H6::Cp(), C7H16::Cp(), and C3H8::Cp().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 119 of file NSRDSfunc14.H.
References token::SPACE.
Referenced by C2H6::writeData(), C7H16::writeData(), and C3H8::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const NSRDSfunc14 & f) friend
Definition at line 131 of file NSRDSfunc14.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc14/NSRDSfunc14.H
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc14/NSRDSfunc14.C