OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
transportModel Class Reference abstract
Base-class for all transport models used by the incompressible turbulence models.
Public Member Functions
TypeName ("transportModel")
Runtime type information.
transportModel ()
Construct from components.
virtual ~transportModel ()
Destructor.
virtual tmp< volScalarField > nu () const =0
Return the laminar viscosity.
virtual tmp< scalarField > nu (const label patchi) const =0
Return the laminar viscosity for patch.
virtual void correct ()=0
Correct the laminar viscosity.
virtual bool read ()=0
Read transportProperties dictionary.
Detailed Description
Base-class for all transport models used by the incompressible turbulence models.
Source files
transportModel.H
transportModel.C
Definition at line 51 of file transportModel.H.
Constructor & Destructor Documentation
transportModel()
transportModel ()
Construct from components.
Definition at line 39 of file transportModel.C.
~transportModel()
~transportModel () virtual
Destructor.
Definition at line 45 of file transportModel.C.
Member Function Documentation
TypeName()
TypeName ("transportModel")
Runtime type information.
nu() [1/2]
virtual tmp<volScalarField> nu () const pure virtual
Return the laminar viscosity.
Implemented in multiphaseSystem, multiphaseMixture, incompressibleThreePhaseMixture, incompressibleTwoPhaseInteractingMixture, phaseModel, phaseModel, incompressibleTwoPhaseMixture, and singlePhaseTransportModel.
Referenced by forces::devRhoReff(), forces::mu(), and turbulenceModel::nu().
nu() [2/2]
virtual tmp<scalarField> nu (const label patchi) const pure virtual
Return the laminar viscosity for patch.
Implemented in multiphaseSystem, multiphaseMixture, incompressibleThreePhaseMixture, incompressibleTwoPhaseInteractingMixture, phaseModel, incompressibleTwoPhaseMixture, and singlePhaseTransportModel.
correct()
virtual void correct () pure virtual
Correct the laminar viscosity.
Implemented in multiphaseSystem, multiphaseMixture, phaseModel, incompressibleThreePhaseMixture, phaseModel, incompressibleTwoPhaseInteractingMixture, incompressibleTwoPhaseMixture, phaseChangeTwoPhaseMixture, phaseModel, SchnerrSauer, Kunz, Merkle, singlePhaseTransportModel, immiscibleIncompressibleTwoPhaseMixture, and immiscibleIncompressibleThreePhaseMixture.
read()
bool read () pure virtual
Read transportProperties dictionary.
Implemented in multiphaseSystem, multiphaseMixture, phaseModel, incompressibleThreePhaseMixture, incompressibleTwoPhaseInteractingMixture, incompressibleTwoPhaseMixture, phaseChangeTwoPhaseMixture, SchnerrSauer, Kunz, Merkle, and singlePhaseTransportModel.
Definition at line 51 of file transportModel.C.
The documentation for this class was generated from the following files:
src/transportModels/incompressible/transportModel/transportModel.H
src/transportModels/incompressible/transportModel/transportModel.C