OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NSRDSfunc4 Class Reference
NSRDS function number 104.
Public Member Functions
TypeName ("NSRDSfunc4")
Runtime type information.
NSRDSfunc4 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
NSRDSfunc4 (Istream &is)
Construct from Istream.
NSRDSfunc4 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc4 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS function number 104.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 67 of file NSRDSfunc4.H.
Constructor & Destructor Documentation
NSRDSfunc4() [1/3]
NSRDSfunc4 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
Definition at line 41 of file NSRDSfunc4.C.
NSRDSfunc4() [2/3]
NSRDSfunc4 (Istream & is)
Construct from Istream.
Definition at line 57 of file NSRDSfunc4.C.
NSRDSfunc4() [3/3]
NSRDSfunc4 (const dictionary & dict)
Construct from dictionary.
Definition at line 67 of file NSRDSfunc4.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc4")
Runtime type information.
f()
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 105 of file NSRDSfunc4.H.
References Foam::pow().
Referenced by iC3H8O::B(), nC3H8O::B(), H2O::B(), C8H10::B(), aC10H7CH3::B(), IC8H18::B(), C13H28::B(), C3H6O::B(), CH4N2O::B(), CH3OH::B(), C9H20::B(), C8H18::B(), C2H5OH::B(), C7H8::B(), C7H16::B(), Ar::B(), C14H30::B(), C4H10O::B(), C3H8::B(), bC10H7CH3::B(), C2H6O::B(), C2H6::B(), C10H22::B(), C16H34::B(), N2::B(), C6H14::B(), C12H26::B(), C6H6::B(), MB::B(), and IDEA::B().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 111 of file NSRDSfunc4.H.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), iC3H8O::writeData(), nC3H8O::writeData(), IC8H18::writeData(), C13H28::writeData(), C3H6O::writeData(), CH4N2O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H5OH::writeData(), C7H8::writeData(), C7H16::writeData(), C6H6::writeData(), C6H14::writeData(), C14H30::writeData(), C3H8::writeData(), bC10H7CH3::writeData(), C2H6O::writeData(), C2H6::writeData(), C10H22::writeData(), C16H34::writeData(), N2::writeData(), C4H10O::writeData(), C12H26::writeData(), Ar::writeData(), MB::writeData(), and aC10H7CH3::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const NSRDSfunc4 & f) friend
Definition at line 123 of file NSRDSfunc4.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc4/NSRDSfunc4.H
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc4/NSRDSfunc4.C