OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
BirdCarreau Class Reference
An incompressible Bird-Carreau non-Newtonian viscosity model.
Public Member Functions
TypeName ("BirdCarreau")
Runtime type information.
BirdCarreau (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
construct from components
~BirdCarreau ()
Destructor.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
void correct ()
Correct the laminar viscosity.
bool read (const dictionary &viscosityProperties)
Read transportProperties dictionary.
Public Member Functions inherited from viscosityModel
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~viscosityModel ()
Destructor.
const dictionary & viscosityProperties () const
Return the phase transport properties dictionary.
tmp< volScalarField > strainRate () const
Return the strain rate.
Additional Inherited Members
Static Public Member Functions inherited from viscosityModel
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from viscosityModel
viscosityModel (const viscosityModel &)
Disallow copy construct.
void operator= (const viscosityModel &)
Disallow default bitwise assignment.
Protected Attributes inherited from viscosityModel
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Detailed Description
An incompressible Bird-Carreau non-Newtonian viscosity model.
The Bird-Carreau-Yasuda form is also supported if the optional "a" coefficient is specified. "a" defaults to 2 for the Bird-Carreau model.
Source files
BirdCarreau.H
BirdCarreau.C
Definition at line 55 of file BirdCarreau.H.
Constructor & Destructor Documentation
BirdCarreau()
BirdCarreau (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
construct from components
Definition at line 62 of file BirdCarreau.C.
References BirdCarreau::read().
~BirdCarreau()
~BirdCarreau () inline
Destructor.
Definition at line 97 of file BirdCarreau.H.
Member Function Documentation
TypeName()
TypeName ("BirdCarreau")
Runtime type information.
nu() [1/2]
tmp<volScalarField> nu () const inline virtual
Return the laminar viscosity.
Implements viscosityModel.
Definition at line 104 of file BirdCarreau.H.
nu() [2/2]
tmp<scalarField> nu (const label patchi) const inline virtual
Return the laminar viscosity for patch.
Implements viscosityModel.
Definition at line 110 of file BirdCarreau.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and patchi.
correct()
void correct () inline virtual
Correct the laminar viscosity.
Implements viscosityModel.
Definition at line 116 of file BirdCarreau.H.
References BirdCarreau::read().
read()
bool read (const dictionary & viscosityProperties) virtual
Read transportProperties dictionary.
Implements viscosityModel.
Definition at line 101 of file BirdCarreau.C.
References Foam::dimless, dictionary::lookup(), viscosityModel::read(), and dictionary::subDict().
Referenced by BirdCarreau::BirdCarreau(), and BirdCarreau::correct().
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/BirdCarreau/BirdCarreau.H
src/transportModels/incompressible/viscosityModels/BirdCarreau/BirdCarreau.C