OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NSRDSfunc0 Class Reference
NSRDS function number 100.
Public Member Functions
TypeName ("NSRDSfunc0")
Runtime type information.
NSRDSfunc0 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e, const scalar f)
Construct from components.
NSRDSfunc0 (Istream &is)
Construct from Istream.
NSRDSfunc0 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc0 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS function number 100.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 67 of file NSRDSfunc0.H.
Constructor & Destructor Documentation
NSRDSfunc0() [1/3]
NSRDSfunc0 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e, const scalar f)
Construct from components.
Definition at line 41 of file NSRDSfunc0.C.
NSRDSfunc0() [2/3]
NSRDSfunc0 (Istream & is)
Construct from Istream.
Definition at line 59 of file NSRDSfunc0.C.
NSRDSfunc0() [3/3]
NSRDSfunc0 (const dictionary & dict)
Construct from dictionary.
Definition at line 70 of file NSRDSfunc0.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc0")
Runtime type information.
f()
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 106 of file NSRDSfunc0.H.
Referenced by iC3H8O::Cp(), nC3H8O::Cp(), H2O::Cp(), C8H10::Cp(), bC10H7CH3::Cp(), C2H6O::Cp(), CH4N2O::Cp(), C13H28::Cp(), C3H6O::Cp(), Ar::Cp(), IC8H18::Cp(), C14H30::Cp(), C4H10O::Cp(), MB::Cp(), C6H14::Cp(), N2::Cp(), C10H22::Cp(), C16H34::Cp(), C6H6::Cp(), aC10H7CH3::Cp(), C12H26::Cp(), C7H8::Cp(), C2H5OH::Cp(), C8H18::Cp(), C9H20::Cp(), CH3OH::Cp(), IDEA::Cp(), Ar::Cpg(), iC3H8O::h(), nC3H8O::h(), H2O::h(), C8H10::h(), C9H20::h(), CH3OH::h(), C2H6O::h(), N2::h(), CH4N2O::h(), aC10H7CH3::h(), C10H22::h(), C13H28::h(), C3H6O::h(), bC10H7CH3::h(), C14H30::h(), C3H8::h(), IC8H18::h(), C4H10O::h(), MB::h(), C6H14::h(), Ar::h(), C6H6::h(), C7H16::h(), C16H34::h(), C7H8::h(), C2H5OH::h(), C8H18::h(), C12H26::h(), C2H6::h(), IDEA::h(), nC3H8O::K(), iC3H8O::K(), H2O::K(), C8H10::K(), C14H30::K(), C2H6::K(), CH4N2O::K(), C2H6O::K(), C12H26::K(), C4H10O::K(), C7H16::K(), C6H14::K(), C6H6::K(), C8H18::K(), IC8H18::K(), aC10H7CH3::K(), C16H34::K(), C2H5OH::K(), C10H22::K(), N2::K(), C7H8::K(), MB::K(), CH3OH::K(), C3H6O::K(), C13H28::K(), C3H8::K(), bC10H7CH3::K(), C9H20::K(), Ar::K(), IDEA::K(), CH4N2O::rho(), iC3H8O::sigma(), nC3H8O::sigma(), and C2H5OH::sigma().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 112 of file NSRDSfunc0.H.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), iC3H8O::writeData(), nC3H8O::writeData(), aC10H7CH3::writeData(), IC8H18::writeData(), C13H28::writeData(), C3H6O::writeData(), CH4N2O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H5OH::writeData(), C7H8::writeData(), C7H16::writeData(), Ar::writeData(), C14H30::writeData(), C4H10O::writeData(), C3H8::writeData(), bC10H7CH3::writeData(), C2H6O::writeData(), C2H6::writeData(), C10H22::writeData(), C16H34::writeData(), N2::writeData(), C6H14::writeData(), C12H26::writeData(), C6H6::writeData(), MB::writeData(), and IDEA::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const NSRDSfunc0 & f) friend
Definition at line 125 of file NSRDSfunc0.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc0/NSRDSfunc0.H
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc0/NSRDSfunc0.C