OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NSRDSfunc7 Class Reference
NSRDS-AICHE function number 107.
Public Member Functions
TypeName ("NSRDSfunc7")
Runtime type information.
NSRDSfunc7 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
NSRDSfunc7 (Istream &is)
Construct from Istream.
NSRDSfunc7 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc7 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS-AICHE function number 107.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 67 of file NSRDSfunc7.H.
Constructor & Destructor Documentation
NSRDSfunc7() [1/3]
NSRDSfunc7 (const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
Definition at line 41 of file NSRDSfunc7.C.
NSRDSfunc7() [2/3]
NSRDSfunc7 (Istream & is)
Construct from Istream.
Definition at line 57 of file NSRDSfunc7.C.
NSRDSfunc7() [3/3]
NSRDSfunc7 (const dictionary & dict)
Construct from dictionary.
Definition at line 67 of file NSRDSfunc7.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc7")
Runtime type information.
f()
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 105 of file NSRDSfunc7.H.
References Foam::cosh(), Foam::sinh(), and Foam::sqr().
Referenced by iC3H8O::Cpg(), nC3H8O::Cpg(), H2O::Cpg(), C8H10::Cpg(), N2::Cpg(), IC8H18::Cpg(), C3H8::Cpg(), C3H6O::Cpg(), CH4N2O::Cpg(), CH3OH::Cpg(), C9H20::Cpg(), C8H18::Cpg(), C2H6::Cpg(), C7H8::Cpg(), bC10H7CH3::Cpg(), C6H6::Cpg(), C16H34::Cpg(), C4H10O::Cpg(), C14H30::Cpg(), C13H28::Cpg(), C2H6O::Cpg(), C12H26::Cpg(), C2H5OH::Cpg(), C6H14::Cpg(), C10H22::Cpg(), aC10H7CH3::Cpg(), C7H16::Cpg(), MB::Cpg(), and IDEA::Cpg().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 111 of file NSRDSfunc7.H.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), iC3H8O::writeData(), nC3H8O::writeData(), C6H14::writeData(), IC8H18::writeData(), C3H8::writeData(), C3H6O::writeData(), CH4N2O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H6::writeData(), C7H8::writeData(), bC10H7CH3::writeData(), C6H6::writeData(), C16H34::writeData(), C4H10O::writeData(), C14H30::writeData(), C13H28::writeData(), C2H6O::writeData(), C12H26::writeData(), C2H5OH::writeData(), N2::writeData(), C10H22::writeData(), aC10H7CH3::writeData(), C7H16::writeData(), MB::writeData(), and IDEA::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const NSRDSfunc7 & f) friend
Definition at line 123 of file NSRDSfunc7.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc7/NSRDSfunc7.H
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc7/NSRDSfunc7.C