OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
APIdiffCoefFunc Class Reference
API function for vapour mass diffusivity.
Public Member Functions
TypeName ("APIdiffCoefFunc")
Runtime type information.
APIdiffCoefFunc (const scalar a, const scalar b, const scalar wf, const scalar wa)
Construct from components.
APIdiffCoefFunc (Istream &is)
Construct from Istream.
APIdiffCoefFunc (const dictionary &dict)
Construct from dictionary.
scalar f (scalar p, scalar T) const
API vapour mass diffusivity function using properties from.
scalar f (scalar p, scalar T, scalar Wa) const
API vapour mass diffusivity function using properties from.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const APIdiffCoefFunc &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
API function for vapour mass diffusivity.
Source:
        API (American Petroleum Institute)
                Technical Data Book
Definition at line 51 of file APIdiffCoefFunc.H.
Constructor & Destructor Documentation
APIdiffCoefFunc() [1/3]
APIdiffCoefFunc (const scalar a, const scalar b, const scalar wf, const scalar wa)
Construct from components.
Definition at line 51 of file APIdiffCoefFunc.C.
APIdiffCoefFunc() [2/3]
APIdiffCoefFunc (Istream & is)
Construct from Istream.
Definition at line 67 of file APIdiffCoefFunc.C.
APIdiffCoefFunc() [3/3]
APIdiffCoefFunc (const dictionary & dict)
Construct from dictionary.
Definition at line 78 of file APIdiffCoefFunc.C.
Member Function Documentation
TypeName()
TypeName ("APIdiffCoefFunc")
Runtime type information.
f() [1/2]
scalar f (scalar p, scalar T) const inline virtual
API vapour mass diffusivity function using properties from.
construction
Implements thermophysicalFunction.
Definition at line 92 of file APIdiffCoefFunc.H.
Referenced by C8H10::D(), H2O::D(), MB::D(), aC10H7CH3::D(), IC8H18::D(), C3H6O::D(), CH4N2O::D(), CH3OH::D(), C9H20::D(), C8H18::D(), C2H5OH::D(), C7H8::D(), C7H16::D(), Ar::D(), C6H14::D(), C4H10O::D(), C3H8::D(), C13H28::D(), C2H6O::D(), C2H6::D(), C10H22::D(), C16H34::D(), C14H30::D(), bC10H7CH3::D(), C12H26::D(), C6H6::D(), N2::D(), and IDEA::D().
f() [2/2]
scalar f (scalar p, scalar T, scalar Wa) const inline
API vapour mass diffusivity function using properties from.
construction - with specified binary pair
Definition at line 99 of file APIdiffCoefFunc.H.
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 106 of file APIdiffCoefFunc.H.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), MB::writeData(), aC10H7CH3::writeData(), IC8H18::writeData(), C3H6O::writeData(), CH4N2O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H5OH::writeData(), C7H8::writeData(), C7H16::writeData(), Ar::writeData(), C6H14::writeData(), C4H10O::writeData(), C3H8::writeData(), C13H28::writeData(), C2H6O::writeData(), C2H6::writeData(), C10H22::writeData(), C16H34::writeData(), C14H30::writeData(), bC10H7CH3::writeData(), C12H26::writeData(), C6H6::writeData(), N2::writeData(), and IDEA::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const APIdiffCoefFunc & f) friend
Definition at line 117 of file APIdiffCoefFunc.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/APIfunctions/APIdiffCoefFunc/APIdiffCoefFunc.H
src/thermophysicalModels/thermophysicalFunctions/APIfunctions/APIdiffCoefFunc/APIdiffCoefFunc.C