OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelledTri Class Reference
Triangle with additional region number.
Public Member Functions
labelledTri ()
Construct null.
labelledTri (const triFace &, const label region)
Construct from triFace and a region label.
labelledTri (const label a, const label b, const label c, const label region)
Construct from three point labels and a region label.
labelledTri (Istream &)
Construct from Istream.
label region () const
Return region label.
label & region ()
Return region label.
Public Member Functions inherited from triFace
triFace ()
Construct null.
triFace (const label a, const label b, const label c)
Construct from three point labels.
triFace (const labelUList &)
Construct from a list of labels.
triFace (Istream &)
Construct from Istream.
label collapse ()
Collapse face by removing duplicate point labels.
void flip ()
Flip the face in-place.
pointField points (const pointField &) const
Return the points corresponding to this face.
face triFaceFace () const
Return triangle as a face.
triPointRef tri (const pointField &) const
Return the triangle.
point centre (const pointField &) const
Return centre (centroid)
template<class Type >
Type average (const pointField &, const Field< Type > &) const
Calculate average value at centroid of face.
scalar mag (const pointField &) const
Magnitude of face area.
vector normal (const pointField &) const
Vector normal; magnitude is equal to area of face.
label nTriangles () const
Number of triangles after splitting.
triFace reverseFace () const
Return face with reverse direction.
scalar sweptVol (const pointField &oldPoints, const pointField &newPoints) const
Return swept-volume.
tensor inertia (const pointField &, const point &refPt=vector::zero, scalar density=1.0) const
Return the inertia tensor, with optional reference.
pointHit ray (const point &p, const vector &q, const pointField &points, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
Return point intersection with a ray starting at p,.
pointHit intersection (const point &p, const vector &q, const pointField &points, const intersection::algorithm alg, const scalar tol=0.0) const
Fast intersection with a ray.
pointHit intersection (const point &p, const vector &q, const point &ctr, const pointField &points, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit nearestPoint (const point &p, const pointField &points) const
Return nearest point to face.
pointHit nearestPointClassify (const point &p, const pointField &points, label &nearType, label &nearLabel) const
Return nearest point to face and classify it:
label nEdges () const
Return number of edges.
edgeList edges () const
Return edges in face point ordering,.
edge faceEdge (const label n) const
Return n-th face edge.
int edgeDirection (const edge &) const
Return the edge direction on the face.
Public Member Functions inherited from FixedList< label, 3 >
FixedList ()
Null constructor.
FixedList (const label v[Size])
Construct from C-array.
FixedList (const label &)
Construct from value.
FixedList (const UList< label > &)
Construct from UList.
FixedList (const SLList< label > &)
Construct from SLList.
FixedList (const FixedList< label, Size > &)
Copy constructor.
FixedList (Istream &)
Construct from Istream.
autoPtr< FixedList< label, Size > > clone () const
Clone.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
const label * cdata () const
Return a const pointer to the first data element,.
label * data ()
Return a pointer to the first data element,.
label & first ()
Return the first element of the list.
const label & first () const
Return first element of the list.
label & last ()
Return the last element of the list.
const label & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void resize (const label)
Dummy resize function.
void setSize (const label)
Dummy setSize function.
void transfer (const FixedList< label, Size > &)
Copy (not transfer) the argument contents.
void writeEntry (Ostream &) const
Write the FixedList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the FixedList as a dictionary entry with keyword.
label & operator[] (const label)
Return element of FixedList.
const label & operator[] (const label) const
Return element of constant FixedList.
void operator= (const label v[Size])
Assignment from array operator. Takes linear time.
void operator= (const UList< label > &)
Assignment from UList operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment from SLList operator. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
label size () const
Return the number of elements in the FixedList.
label max_size () const
Return size of the largest possible FixedList.
bool empty () const
Return true if the FixedList is empty (ie, size() is zero).
void swap (FixedList< label, Size > &)
Swap two FixedLists of the same type in constant time.
bool operator== (const FixedList< label, Size > &) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< label, Size > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< label, Size > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< label, Size > &) const
Return true if !(a < b). Takes linear time.
Friends
Istream & operator>> (Istream &, labelledTri &)
Ostream & operator<< (Ostream &, const labelledTri &)
Additional Inherited Members
Public Types inherited from FixedList< label, 3 >
typedef label value_type
Type of values the FixedList contains.
typedef label & reference
Type that can be used for storing into.
typedef const label & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a FixedList.
typedef label * iterator
Random access iterator for traversing FixedList.
typedef const label * const_iterator
Random access iterator for traversing FixedList.
typedef label * reverse_iterator
Reverse iterator for reverse traversal of FixedList.
typedef const label * const_reverse_iterator
Reverse iterator for reverse traversal of constant FixedList.
Static Public Member Functions inherited from triFace
static int compare (const triFace &, const triFace &)
compare triFaces
Static Public Member Functions inherited from FixedList< label, 3 >
static const FixedList< label, Size > & null ()
Return a null FixedList.
Detailed Description
Triangle with additional region number.
Source files
labelledTri.H
labelledTriI.H
Definition at line 49 of file labelledTri.H.
Constructor & Destructor Documentation
labelledTri() [1/4]
labelledTri () inline
Construct null.
Definition at line 30 of file labelledTriI.H.
Referenced by labelledTri::labelledTri().
labelledTri() [2/4]
labelledTri (const triFace & tri, const label region) inline
Construct from triFace and a region label.
Definition at line 37 of file labelledTriI.H.
References labelledTri::labelledTri().
labelledTri() [3/4]
labelledTri (const label a, const label b, const label c, const label region) inline
Construct from three point labels and a region label.
Definition at line 48 of file labelledTriI.H.
labelledTri() [4/4]
labelledTri (Istream & is) inline
Construct from Istream.
Definition at line 60 of file labelledTriI.H.
References labelledTri::operator>>.
Member Function Documentation
region() [1/2]
Foam::label region () const inline
Return region label.
Definition at line 68 of file labelledTriI.H.
Referenced by booleanSurface::booleanSurface(), NamedEnum< directionType, 3 >::names(), boundaryMesh::readTriSurface(), and triSurface::triSurfInstance().
region() [2/2]
Foam::label & region () inline
Return region label.
Definition at line 73 of file labelledTriI.H.
References IOstream::ASCII, token::BEGIN_LIST, IOstream::check(), token::END_LIST, IOstream::format(), Foam::operator<<(), Foam::operator>>(), Istream::read(), Istream::readBegin(), Istream::readEnd(), token::SPACE, and Ostream::write().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , labelledTri &) friend
Referenced by labelledTri::labelledTri().
operator<<
Ostream& operator<< (Ostream & , const labelledTri &) friend
The documentation for this class was generated from the following files:
src/triSurface/tools/labelledTri/labelledTri.H
src/triSurface/tools/labelledTri/labelledTriI.H