OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STLLexer Class Reference
Public Member Functions
STLLexer (istream *is, const label approxNpoints)
From input stream and the approximate number of vertices in the STL.
int lex ()
The lexer function itself.
label nTriangles () const
DynamicList< floatVector > & STLpoints ()
DynamicList< label > & STLlabels ()
const HashTable< label, word > & STLsolidNames () const
Detailed Description
Definition at line 5261 of file readSTLASCII.C.
Constructor & Destructor Documentation
STLLexer()
STLLexer (istream * is, const label approxNpoints)
From input stream and the approximate number of vertices in the STL.
Definition at line 5322 of file readSTLASCII.C.
Member Function Documentation
lex()
int lex ()
The lexer function itself.
The main scanner function which does all the work.
Definition at line 5460 of file readSTLASCII.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::constant::physicoChemical::b, BEGIN, Foam::constant::universal::c, ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, Foam::exit(), Foam::FatalError, FatalErrorIn, HashTable< T, Key, Hash >::found(), INITIAL, HashTable< T, Key, Hash >::insert(), Foam::nl, readFacet, readNormal, readSolidName, readVertex, readVertices, stlerror, yy_accept, yy_buffer_state::yy_at_bol, YY_BREAK, yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, yy_buffer_state::yy_buf_pos, YY_BUF_SIZE, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, YY_INPUT, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_buffer_state::yy_n_chars, YY_NEW_FILE, yy_NUL_trans, yy_nxt, YY_READ_BUF_SIZE, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, YY_START_STACK_INCR, YY_STATE_EOF, yyalloc(), yyFlexLexer, yyfree(), yyrealloc(), yyterminate, and yytext_ptr.
nTriangles()
label nTriangles () const inline
Definition at line 5295 of file readSTLASCII.C.
STLpoints()
DynamicList<floatVector>& STLpoints () inline
Definition at line 5300 of file readSTLASCII.C.
STLlabels()
DynamicList<label>& STLlabels () inline
Definition at line 5310 of file readSTLASCII.C.
STLsolidNames()
const HashTable<label, word>& STLsolidNames () const inline
Definition at line 5315 of file readSTLASCII.C.
The documentation for this class was generated from the following file:
src/triSurface/Make/linux64GccDPOpt/readSTLASCII.C