OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfacePatch Class Reference
'Patch' on surface as subset of triSurface.
Public Member Functions
ClassName ("surfacePatch")
Runtime type information.
surfacePatch ()
Construct null.
surfacePatch (const word &geometricType, const word &name, const label size, const label start, const label index)
Construct from components.
surfacePatch (Istream &is, const label index)
Construct from Istream.
surfacePatch (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
surfacePatch (const surfacePatch &)
Construct as copy.
label start () const
Return start label of this patch in the polyMesh face list.
label & start ()
Return start label of this patch in the polyMesh face list.
label size () const
Return size of this patch in the polyMesh face list.
label & size ()
Return size of this patch in the polyMesh face list.
void write (Ostream &) const
Write.
void writeDict (Ostream &) const
Write dictionary.
bool operator!= (const surfacePatch &) const
bool operator== (const surfacePatch &) const
compare.
Public Member Functions inherited from geometricSurfacePatch
ClassName ("geometricSurfacePatch")
Runtime type information.
geometricSurfacePatch ()
Construct null.
geometricSurfacePatch (const word &geometricType, const word &name, const label index)
Construct from components.
geometricSurfacePatch (Istream &, const label index)
Construct from Istream.
geometricSurfacePatch (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
const word & name () const
Return name.
word & name ()
Return name.
const word & geometricType () const
Return the type of the patch.
word & geometricType ()
Return the type of the patch.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh.
void write (Ostream &) const
Write.
void writeDict (Ostream &) const
Write dictionary.
bool operator!= (const geometricSurfacePatch &) const
bool operator== (const geometricSurfacePatch &) const
compare.
Friends
Ostream & operator<< (Ostream &, const surfacePatch &)
Detailed Description
'Patch' on surface as subset of triSurface.
Source files
surfacePatch.H
surfacePatch.C
Definition at line 51 of file surfacePatch.H.
Constructor & Destructor Documentation
surfacePatch() [1/5]
surfacePatch ()
Construct null.
Definition at line 41 of file surfacePatch.C.
Referenced by surfacePatch::surfacePatch().
surfacePatch() [2/5]
surfacePatch (const word & geometricType, const word & name, const label size, const label start, const label index)
Construct from components.
Definition at line 52 of file surfacePatch.C.
surfacePatch() [3/5]
surfacePatch (Istream & is, const label index)
Construct from Istream.
Definition at line 67 of file surfacePatch.C.
References surfacePatch::surfacePatch().
surfacePatch() [4/5]
surfacePatch (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 79 of file surfacePatch.C.
surfacePatch() [5/5]
surfacePatch (const surfacePatch & sp)
Construct as copy.
Definition at line 92 of file surfacePatch.C.
Member Function Documentation
ClassName()
ClassName ("surfacePatch")
Runtime type information.
start() [1/2]
label start () const inline
Return start label of this patch in the polyMesh face list.
Definition at line 102 of file surfacePatch.H.
Referenced by triSurface::checkEdges(), surfacePatch::operator==(), surfacePatch::write(), and surfacePatch::writeDict().
start() [2/2]
label& start () inline
Return start label of this patch in the polyMesh face list.
Definition at line 108 of file surfacePatch.H.
size() [1/2]
label size () const inline
Return size of this patch in the polyMesh face list.
Definition at line 114 of file surfacePatch.H.
Referenced by triSurface::checkEdges(), surfacePatch::operator==(), surfacePatch::write(), and surfacePatch::writeDict().
size() [2/2]
label& size () inline
Return size of this patch in the polyMesh face list.
Definition at line 120 of file surfacePatch.H.
References surfacePatch::operator!=(), surfacePatch::operator<<, surfacePatch::operator==(), surfacePatch::write(), and surfacePatch::writeDict().
write()
void write (Ostream & os) const
Write.
Definition at line 102 of file surfacePatch.C.
References Foam::endl(), Foam::nl, surfacePatch::size(), surfacePatch::start(), and Foam::tab.
Referenced by surfacePatch::operator==(), and surfacePatch::size().
writeDict()
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 109 of file surfacePatch.C.
References token::BEGIN_BLOCK, token::END_BLOCK, Foam::endl(), geometricSurfacePatch::name(), Foam::nl, surfacePatch::size(), surfacePatch::start(), and geometricSurfacePatch::writeDict().
Referenced by surfacePatch::size().
operator!=()
bool operator!= (const surfacePatch & p) const
Definition at line 123 of file surfacePatch.C.
References p.
Referenced by surfacePatch::size().
operator==()
bool operator== (const surfacePatch & p) const
compare.
Definition at line 129 of file surfacePatch.C.
References IOstream::check(), geometricSurfacePatch::geometricType(), Foam::operator<<(), p, surfacePatch::size(), surfacePatch::start(), and surfacePatch::write().
Referenced by surfacePatch::size().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const surfacePatch &) friend
Referenced by surfacePatch::size().
The documentation for this class was generated from the following files:
src/triSurface/triSurface/surfacePatch/surfacePatch.H
src/triSurface/triSurface/surfacePatch/surfacePatch.C