OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphaFixedPressureFvPatchScalarField Class Reference
A fixed-pressure alphaContactAngle boundary.
Public Member Functions
TypeName ("alphaFixedPressure")
Runtime type information.
alphaFixedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaFixedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaFixedPressureFvPatchScalarField.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & p () const
Return the alphaFixed pressure.
scalarField & p ()
Return reference to the alphaFixed pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
A fixed-pressure alphaContactAngle boundary.
Source files
alphaFixedPressureFvPatchScalarField.H
alphaFixedPressureFvPatchScalarField.C
Definition at line 48 of file alphaFixedPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
alphaFixedPressureFvPatchScalarField() [1/5]
alphaFixedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file alphaFixedPressureFvPatchScalarField.C.
Referenced by alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), and alphaFixedPressureFvPatchScalarField::clone().
alphaFixedPressureFvPatchScalarField() [2/5]
alphaFixedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 63 of file alphaFixedPressureFvPatchScalarField.C.
References alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), dictionary::found(), scalarField(), and fvPatch::size().
alphaFixedPressureFvPatchScalarField() [3/5]
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given alphaFixedPressureFvPatchScalarField.
onto a new patch
Definition at line 49 of file alphaFixedPressureFvPatchScalarField.C.
References alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField().
alphaFixedPressureFvPatchScalarField() [4/5]
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 88 of file alphaFixedPressureFvPatchScalarField.C.
References alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField().
alphaFixedPressureFvPatchScalarField() [5/5]
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 99 of file alphaFixedPressureFvPatchScalarField.C.
References alphaFixedPressureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("alphaFixedPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 98 of file alphaFixedPressureFvPatchScalarField.H.
References alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 115 of file alphaFixedPressureFvPatchScalarField.H.
References alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField().
p() [1/2]
const scalarField& p () const inline
Return the alphaFixed pressure.
Definition at line 131 of file alphaFixedPressureFvPatchScalarField.H.
p() [2/2]
scalarField& p () inline
Return reference to the alphaFixed pressure to allow adjustment.
Definition at line 137 of file alphaFixedPressureFvPatchScalarField.H.
References alphaFixedPressureFvPatchScalarField::autoMap(), alphaFixedPressureFvPatchScalarField::rmap(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), and alphaFixedPressureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 112 of file alphaFixedPressureFvPatchScalarField.C.
References alphaFixedPressureFvPatchScalarField::rmap().
Referenced by alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), and alphaFixedPressureFvPatchScalarField::p().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 122 of file alphaFixedPressureFvPatchScalarField.C.
References alphaFixedPressureFvPatchScalarField::rmap().
Referenced by alphaFixedPressureFvPatchScalarField::autoMap(), alphaFixedPressureFvPatchScalarField::p(), and alphaFixedPressureFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 136 of file alphaFixedPressureFvPatchScalarField.C.
References Foam::operator==(), rho, dimensioned< Type >::value(), and alphaFixedPressureFvPatchScalarField::write().
Referenced by alphaFixedPressureFvPatchScalarField::p().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 156 of file alphaFixedPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by alphaFixedPressureFvPatchScalarField::p(), and alphaFixedPressureFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaFixedPressure/alphaFixedPressureFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaFixedPressure/alphaFixedPressureFvPatchScalarField.C