OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
triSurface Class Reference
Triangulated surface description with patch information.
Public Types
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Public Types inherited from PrimitivePatch< labelledTri, ::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef labelledTri FaceType
typedef ::Foam::List< labelledTri > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< labelledTri >
typedef SubList< labelledTri > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
ClassName ("triSurface")
Runtime type information.
triSurface ()
Construct null.
triSurface (const List< labelledTri > &, const geometricSurfacePatchList &, const pointField &)
Construct from triangles, patches, points.
triSurface (List< labelledTri > &, const geometricSurfacePatchList &, pointField &, const bool reUse)
Construct from triangles, patches, points. Reuse storage.
triSurface (const Xfer< List< labelledTri > > &, const geometricSurfacePatchList &, const Xfer< List< point > > &)
Construct from triangles, patches, points.
triSurface (const List< labelledTri > &, const pointField &)
Construct from triangles, points. Set patchnames to default.
triSurface (const triFaceList &, const pointField &)
Construct from triangles, points. Set region to 0 and default.
triSurface (const fileName &)
Construct from file name (uses extension to determine type)
triSurface (Istream &)
Construct from Istream.
triSurface (const Time &d)
Construct from objectRegistry.
triSurface (const triSurface &)
Construct as copy.
~triSurface ()
Destructor.
void clearOut ()
void clearTopology ()
void clearPatchMeshAddr ()
const geometricSurfacePatchList & patches () const
geometricSurfacePatchList & patches ()
const labelListList & sortedEdgeFaces () const
Return edge-face addressing sorted (for edges with more than.
const labelList & edgeOwner () const
If 2 face neighbours: label of face where ordering of edge.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void checkTriangles (const bool verbose)
Check/remove duplicate/degenerate triangles.
void checkEdges (const bool verbose)
Check triply (or more) connected edges.
void cleanup (const bool verbose)
Remove non-valid triangles.
void markZone (const boolList &borderEdge, const label faceI, const label currentZone, labelList &faceZone) const
Fill faceZone with currentZone for every face reachable.
label markZones (const boolList &borderEdge, labelList &faceZone) const
(size and) fills faceZone with zone of face. Zone is area
void subsetMeshMap (const boolList &include, labelList &pointMap, labelList &faceMap) const
'Create' sub mesh, including only faces for which
triSurface subsetMesh (const boolList &include, labelList &pointMap, labelList &faceMap) const
Return new surface. Returns pointMap, faceMap from.
void write (Ostream &) const
Write to Ostream in simple FOAM format.
void write (const fileName &, const bool sortByRegion=false) const
Generic write routine. Chooses writer based on extension.
void write (const Time &) const
Write to database.
void writeDX (const scalarField &, Ostream &) const
Write to Ostream in OpenDX format.
void writeDX (const vectorField &, Ostream &) const
void writeStats (Ostream &) const
Write some statistics.
void operator= (const triSurface &)
Public Member Functions inherited from PrimitivePatch< labelledTri, ::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< labelledTri > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::List< labelledTri > > &faces, const Xfer< List< point > > &points)
Construct from components.
PrimitivePatch (::Foam::List< labelledTri > &faces, Field< point > &points, const bool reUse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< labelledTri, ::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< labelledTri > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< labelledTri, ::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< labelledTri >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const labelledTri &)
Construct with given size and value for all elements.
List (const List< labelledTri > &)
Copy constructor.
List (const Xfer< List< labelledTri > > &)
Construct by transferring the parameter contents.
List (List< labelledTri > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< labelledTri > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< labelledTri, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< labelledTri > &)
Construct as copy of PtrList<T>
List (const SLList< labelledTri > &)
Construct as copy of SLList<T>
List (const UIndirectList< labelledTri > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< labelledTri > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< labelledTri > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const labelledTri &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const labelledTri &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const labelledTri &)
Append an element at the end of the list.
void append (const UList< labelledTri > &)
Append a List at the end of this list.
void append (const UIndirectList< labelledTri > &)
Append a UIndirectList at the end of this list.
void transfer (List< labelledTri > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< labelledTri, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< labelledTri > &)
Transfer the contents of the argument List into this list.
Xfer< List< labelledTri > > xfer ()
Transfer contents to the Xfer container.
labelledTri & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< labelledTri > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< labelledTri > &)
Assignment operator. Takes linear time.
void operator= (const SLList< labelledTri > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< labelledTri > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< labelledTri > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const labelledTri &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< T > &)
Assign elements to those from UList.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static fileName triSurfInstance (const Time &)
Name of triSurface directory to use.
Static Public Member Functions inherited from List< labelledTri >
static const List< labelledTri > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
Protected Member Functions inherited from List< labelledTri >
void size (const label)
Override size to be inconsistent with allocated storage.
Friends
Ostream & operator<< (Ostream &, const triSurface &)
Detailed Description
Triangulated surface description with patch information.
Source files
triSurface.H
triSurface.C
Definition at line 57 of file triSurface.H.
Member Typedef Documentation
BoundaryMesh
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Definition at line 229 of file triSurface.H.
Constructor & Destructor Documentation
triSurface() [1/10]
triSurface ()
Construct null.
Definition at line 611 of file triSurface.C.
Referenced by booleanSurface::booleanSurface(), distributedTriSurfaceMesh::distribute(), intersectedSurface::intersectedSurface(), meshTriangulation::meshTriangulation(), Foam::parseNASCoord(), Foam::readUpto(), triSurface::subsetMesh(), and triSurface::triSurface().
triSurface() [2/10]
triSurface (const List< labelledTri > & triangles, const geometricSurfacePatchList & patches, const pointField & points)
Construct from triangles, patches, points.
Definition at line 622 of file triSurface.C.
References triSurface::triSurface().
triSurface() [3/10]
triSurface (List< labelledTri > & triangles, const geometricSurfacePatchList & patches, pointField & points, const bool reUse)
Construct from triangles, patches, points. Reuse storage.
Definition at line 636 of file triSurface.C.
References triSurface::triSurface().
triSurface() [4/10]
triSurface (const Xfer< List< labelledTri > > & triangles, const geometricSurfacePatchList & patches, const Xfer< List< point > > & points)
Construct from triangles, patches, points.
Definition at line 651 of file triSurface.C.
References triSurface::triSurface().
triSurface() [5/10]
triSurface (const List< labelledTri > & triangles, const pointField & points)
Construct from triangles, points. Set patchnames to default.
Definition at line 665 of file triSurface.C.
References triSurface::triSurface().
triSurface() [6/10]
triSurface (const triFaceList & triangles, const pointField & points)
Construct from triangles, points. Set region to 0 and default.
patchName.
Definition at line 680 of file triSurface.C.
triSurface() [7/10]
triSurface (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 694 of file triSurface.C.
References fileName::ext().
triSurface() [8/10]
triSurface (Istream & is)
Construct from Istream.
Definition at line 709 of file triSurface.C.
triSurface() [9/10]
triSurface (const Time & d)
Construct from objectRegistry.
Definition at line 722 of file triSurface.C.
References Time::caseName(), Time::path(), and triSurface::triSurfInstance().
triSurface() [10/10]
triSurface (const triSurface & ts)
Construct as copy.
Definition at line 741 of file triSurface.C.
~triSurface()
~triSurface ()
Destructor.
Definition at line 752 of file triSurface.C.
References triSurface::clearOut().
Member Function Documentation
storedPoints()
pointField& storedPoints () inline protected
Non-const access to global points.
Definition at line 212 of file triSurface.H.
References PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::points().
Referenced by triSurface::movePoints(), triSurface::operator=(), and triSurface::scalePoints().
storedFaces()
List<Face>& storedFaces () inline protected
Non-const access to the faces.
Definition at line 218 of file triSurface.H.
ClassName()
ClassName ("triSurface")
Runtime type information.
triSurfInstance()
Foam::fileName triSurfInstance (const Time & d) static
Name of triSurface directory to use.
Definition at line 43 of file triSurface.C.
References Foam::abort(), Time::caseName(), TimePaths::constant(), Foam::endl(), f(), Foam::FatalError, FatalErrorIn, foamName(), forAll, ISstream::getLine(), IOstream::good(), Foam::isFile(), fileName::name(), IOstream::name(), Time::path(), points, Foam::Pout, labelledTri::region(), List< T >::size(), TimeState::timeOutputValue(), and Time::times().
Referenced by triSurface::triSurface(), and triSurface::write().
clearOut()
void clearOut ()
Definition at line 774 of file triSurface.C.
References PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::clearOut(), triSurface::clearPatchMeshAddr(), and triSurface::clearTopology().
Referenced by triSurface::cleanup(), triSurfaceMesh::clearOut(), triSurface::operator=(), and triSurface::~triSurface().
clearTopology()
void clearTopology ()
Definition at line 760 of file triSurface.C.
References PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::clearTopology(), and Foam::deleteDemandDrivenData().
Referenced by triSurface::clearOut(), and triSurface::scalePoints().
clearPatchMeshAddr()
void clearPatchMeshAddr ()
Definition at line 768 of file triSurface.C.
References PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::clearPatchMeshAddr().
Referenced by triSurface::clearOut().
patches() [1/2]
const geometricSurfacePatchList& patches () const inline
Definition at line 306 of file triSurface.H.
Referenced by triSurfaceTools::collapseEdges(), distributedTriSurfaceMesh::distribute(), isoSurface::generateFaceTriPoints(), triSurfaceTools::greenRefine(), intersectedSurface::intersectedSurface(), triSurfaceTools::mergePoints(), meshTriangulation::meshTriangulation(), NamedEnum< directionType, 3 >::names(), triSurface::operator=(), Foam::parseNASCoord(), boundaryMesh::readTriSurface(), Foam::readUpto(), triSurfaceMesh::regions(), triSurface::subsetMesh(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), and triSurface::write().
patches() [2/2]
geometricSurfacePatchList& patches () inline
Definition at line 311 of file triSurface.H.
References triSurface::checkEdges(), triSurface::checkTriangles(), triSurface::cleanup(), triSurface::edgeOwner(), triSurface::markZone(), triSurface::markZones(), triSurface::movePoints(), triSurface::operator<<, triSurface::operator=(), triSurface::scalePoints(), triSurface::sortedEdgeFaces(), triSurface::subsetMesh(), triSurface::subsetMeshMap(), and triSurface::writeStats().
sortedEdgeFaces()
const Foam::labelListList & sortedEdgeFaces () const
Return edge-face addressing sorted (for edges with more than.
2 faces) according to the angle around the edge. Orientation is anticlockwise looking from edge.vec(localPoints())
Definition at line 783 of file triSurface.C.
Referenced by triSurface::patches().
edgeOwner()
const Foam::labelList & edgeOwner () const
If 2 face neighbours: label of face where ordering of edge.
is consistent with righthand walk. If 1 neighbour: label of only face. If >2 neighbours: undetermined.
Definition at line 794 of file triSurface.C.
Referenced by triSurface::patches().
movePoints()
void movePoints (const pointField & newPoints) virtual
Move points.
Reimplemented in triSurfaceMesh.
Definition at line 805 of file triSurface.C.
References Foam::deleteDemandDrivenData(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::movePoints(), and triSurface::storedPoints().
Referenced by triSurfaceMesh::movePoints(), and triSurface::patches().
scalePoints()
void scalePoints (const scalar scaleFactor) virtual
Scale points. A non-positive factor is ignored.
Definition at line 818 of file triSurface.C.
References triSurface::clearTopology(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::movePoints(), and triSurface::storedPoints().
Referenced by triSurface::patches(), and triSurfaceMesh::triSurfaceMesh().
checkTriangles()
void checkTriangles (const bool verbose)
Check/remove duplicate/degenerate triangles.
Definition at line 186 of file triSurface.C.
References Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorIn, forAll, n, points, List< T >::size(), Foam::Warning, and WarningIn.
Referenced by triSurface::cleanup(), and triSurface::patches().
checkEdges()
void checkEdges (const bool verbose)
Check triply (or more) connected edges.
Definition at line 322 of file triSurface.C.
References UList< T >::empty(), Foam::endl(), Foam::exists(), Foam::exit(), fileName::ext(), Foam::FatalError, FatalErrorIn, forAll, geometricSurfacePatch::geometricType(), geometricSurfacePatch::index(), SortableList< T >::indices(), UList< T >::last(), fileName::lessExt(), Foam::max(), geometricSurfacePatch::name(), Foam::name(), List< T >::size(), surfacePatch::size(), SortableList< T >::sort(), Foam::sort(), surfacePatch::start(), WarningIn, write(), Foam::meshTools::writeOBJ(), and Foam::writeVTK().
Referenced by triSurface::cleanup(), and triSurface::patches().
cleanup()
void cleanup (const bool verbose)
Remove non-valid triangles.
Definition at line 835 of file triSurface.C.
References triSurface::checkEdges(), triSurface::checkTriangles(), triSurface::clearOut(), and triSurface::markZone().
Referenced by triSurface::patches().
markZone()
void markZone (const boolList & borderEdge, const label faceI, const label currentZone, labelList & faceZone) const
Fill faceZone with currentZone for every face reachable.
from faceI without crossing edge marked in borderEdge. Note: faceZone has to be sized nFaces before calling this fun.
Definition at line 852 of file triSurface.C.
References Foam::abort(), List< T >::append(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::edgeFaces(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::faceEdges(), Foam::FatalError, FatalErrorIn, forAll, triSurface::markZones(), List< T >::size(), and List< T >::transfer().
Referenced by triSurface::cleanup(), triSurface::markZones(), and triSurface::patches().
markZones()
Foam::label markZones (const boolList & borderEdge, labelList & faceZone) const
(size and) fills faceZone with zone of face. Zone is area
reachable by edge crossing without crossing borderEdge (bool for every edge in surface). Returns number of zones.
Definition at line 921 of file triSurface.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, triSurface::markZone(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::nEdges(), List< T >::setSize(), List< T >::size(), List< labelledTri >::size(), and triSurface::subsetMeshMap().
Referenced by booleanSurface::booleanSurface(), triSurface::markZone(), orientedSurface::orient(), and triSurface::patches().
subsetMeshMap()
void subsetMeshMap (const boolList & include, labelList & pointMap, labelList & faceMap) const
'Create' sub mesh, including only faces for which
boolList entry is true Sets: pointMap: from new to old localPoints faceMap: new to old faces
Definition at line 970 of file triSurface.C.
References forAll, PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::localFaces(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::nPoints(), List< T >::setSize(), List< T >::size(), and triSurface::subsetMesh().
Referenced by triSurface::markZones(), triSurface::patches(), and triSurface::subsetMesh().
subsetMesh()
Foam::triSurface subsetMesh (const boolList & include, labelList & pointMap, labelList & faceMap) const
Return new surface. Returns pointMap, faceMap from.
subsetMeshMap
Definition at line 1016 of file triSurface.C.
References forAll, PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::localFaces(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::localPoints(), triSurface::patches(), List< T >::size(), triSurface::subsetMeshMap(), and triSurface::triSurface().
Referenced by booleanSurface::booleanSurface(), triSurface::patches(), and triSurface::subsetMeshMap().
write() [1/3]
void write (Ostream & os) const
Write to Ostream in simple FOAM format.
Definition at line 1067 of file triSurface.C.
References IOstream::check(), Foam::endl(), Foam::nl, triSurface::patches(), and PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::points().
Referenced by booleanSurface::booleanSurface().
write() [2/3]
void write (const fileName & name, const bool sortByRegion = false) const
Generic write routine. Chooses writer based on extension.
Definition at line 1058 of file triSurface.C.
References fileName::ext().
write() [3/3]
void write (const Time & d) const
Write to database.
Definition at line 1080 of file triSurface.C.
References Time::caseName(), Time::path(), and triSurface::triSurfInstance().
writeDX() [1/2]
void writeDX (const scalarField & field, Ostream & os) const
Write to Ostream in OpenDX format.
Definition at line 164 of file writeDX.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::nPoints(), List< T >::size(), and List< labelledTri >::size().
writeDX() [2/2]
void writeDX (const vectorField & field, Ostream & os) const
Definition at line 209 of file writeDX.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::nPoints(), List< T >::size(), and List< labelledTri >::size().
writeStats()
void writeStats (Ostream & os) const
Write some statistics.
Definition at line 1092 of file triSurface.C.
References Foam::endl(), forAll, boundBox::invertedBox, boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::nPoints(), UList< T >::operator[](), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::points(), PackedBoolList::set(), and List< labelledTri >::size().
Referenced by booleanSurface::booleanSurface(), and triSurface::patches().
operator=()
void operator= (const triSurface & ts)
Definition at line 1125 of file triSurface.C.
References triSurface::clearOut(), Foam::operator<<(), List< T >::operator=(), triSurface::patches(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and triSurface::storedPoints().
Referenced by booleanSurface::booleanSurface(), distributedTriSurfaceMesh::distribute(), intersectedSurface::intersectedSurface(), and triSurface::patches().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const triSurface &) friend
Referenced by triSurface::patches().
The documentation for this class was generated from the following files:
src/triSurface/triSurface/triSurface.H
src/triSurface/Make/linux64GccDPOpt/readSTLASCII.C
src/triSurface/triSurface/interfaces/AC3D/readAC.C
src/triSurface/triSurface/interfaces/AC3D/writeAC.C
src/triSurface/triSurface/interfaces/DX/writeDX.C
src/triSurface/triSurface/interfaces/GTS/readGTS.C
src/triSurface/triSurface/interfaces/GTS/writeGTS.C
src/triSurface/triSurface/interfaces/NAS/readNAS.C
src/triSurface/triSurface/interfaces/OBJ/readOBJ.C
src/triSurface/triSurface/interfaces/OBJ/writeOBJ.C
src/triSurface/triSurface/interfaces/OFF/readOFF.C
src/triSurface/triSurface/interfaces/OFF/writeOFF.C
src/triSurface/triSurface/interfaces/SMESH/writeSMESH.C
src/triSurface/triSurface/interfaces/STL/readSTL.C
src/triSurface/triSurface/interfaces/STL/readSTLBINARY.C
src/triSurface/triSurface/interfaces/STL/writeSTL.C
src/triSurface/triSurface/interfaces/TRI/readTRI.C
src/triSurface/triSurface/interfaces/TRI/writeTRI.C
src/triSurface/triSurface/interfaces/VTK/readVTK.C
src/triSurface/triSurface/interfaces/VTK/writeVTK.C
src/triSurface/triSurface/stitchTriangles.C
src/triSurface/triSurface/triSurface.C
src/triSurface/triSurface/triSurfaceAddressing.C