OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vanDriestDelta Class Reference
Simple cube-root of cell volume delta used in compressible LES models.
Public Member Functions
TypeName ("vanDriest")
Runtime type information.
vanDriestDelta (const word &name, const fvMesh &mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
virtual ~vanDriestDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
Public Member Functions inherited from LESdelta
declareRunTimeSelectionTable (autoPtr, foamLESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &mesh)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< foamLESdelta > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected LES delta.
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes inherited from LESdelta
const fvMesh & mesh_
volScalarField delta_
Detailed Description
Simple cube-root of cell volume delta used in compressible LES models.
Source files
vanDriestDelta.H
vanDriestDelta.C
Definition at line 52 of file vanDriestDelta.H.
Constructor & Destructor Documentation
vanDriestDelta()
vanDriestDelta (const word & name, const fvMesh & mesh, const dictionary & dd)
Construct from name, mesh and IOdictionary.
Definition at line 101 of file vanDriestDelta.C.
References LESdelta::delta_.
~vanDriestDelta()
virtual ~vanDriestDelta () inline virtual
Destructor.
Definition at line 88 of file vanDriestDelta.H.
References vanDriestDelta::correct(), and vanDriestDelta::read().
Member Function Documentation
TypeName()
TypeName ("vanDriest")
Runtime type information.
read()
void read (const dictionary & d) virtual
Read the LESdelta dictionary.
Implements LESdelta.
Definition at line 132 of file vanDriestDelta.C.
References dictionary::readIfPresent(), dictionary::subDict(), and Foam::type().
Referenced by vanDriestDelta::~vanDriestDelta().
correct()
void correct () virtual
Implements LESdelta.
Definition at line 145 of file vanDriestDelta.C.
References LESdelta::mesh(), and timeIndex.
Referenced by vanDriestDelta::~vanDriestDelta().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/LES/vanDriestDelta/vanDriestDelta.H
src/turbulenceModels/compressible/LES/vanDriestDelta/vanDriestDelta.C