OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
Public Member Functions
TypeName ("compressible::alphatJayatillekeWallFunction")
Runtime type information.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given an.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
Patch usage
Property Description Required Default value
Prt turbulent Prandtl number no 0.85
Cmu model coefficient no 0.09
kappa Von Karman constant no 0.41
E model coefficient no 9.8
Example of the boundary condition specification:
    myPatch
    {
        type            alphatJayatillekeWallFunction;
        Prt             0.85;
        kappa           0.41;
        E               9.8;
        value           uniform 0; // optional value entry
    }
See also
Foam::fixedValueFvPatchField
Source files
alphatJayatillekeWallFunctionFvPatchScalarField.H
alphatJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 104 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatJayatillekeWallFunctionFvPatchScalarField() [1/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 108 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), and alphatJayatillekeWallFunctionFvPatchScalarField::clone().
alphatJayatillekeWallFunctionFvPatchScalarField() [2/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 142 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
alphatJayatillekeWallFunctionFvPatchScalarField() [3/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given an.
alphatJayatillekeWallFunctionFvPatchScalarField onto a new patch
Definition at line 125 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
alphatJayatillekeWallFunctionFvPatchScalarField() [4/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & awfpsf)
Construct as copy.
Definition at line 160 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
alphatJayatillekeWallFunctionFvPatchScalarField() [5/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & awfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 176 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::alphatJayatillekeWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 187 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 204 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 193 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References turbulenceModel::alpha(), alphaEff, basicThermo::alphaEff(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), forAll, basicThermo::he(), Foam::Info, k, turbulenceModel::k(), Foam::log(), Foam::mag(), magUp, Foam::max(), turbulenceModel::mu(), Foam::nl, patchi, fvPatchField< Type >::patchInternalField(), Foam::pow025(), Pr(), turbulenceModel::rho(), fvPatchField< Type >::snGrad(), Foam::sqr(), Foam::sqrt(), turbulenceModel::thermo(), turbulenceModel::U(), fvPatchField< Type >::updateCoeffs(), uTau, y, turbulenceModel::y(), and yPlus.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const
Write.
Definition at line 292 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References token::END_STATEMENT, Foam::compressible::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C