OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutkRoughWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on turbulence kinetic energy. The condition manipulates the E parameter to account for roughness effects.
Public Member Functions
TypeName ("mutkRoughWallFunction")
Runtime type information.
mutkRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutkRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutkRoughWallFunctionFvPatchScalarField (const mutkRoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutkRoughWallFunctionFvPatchScalarField (const mutkRoughWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutkRoughWallFunctionFvPatchScalarField (const mutkRoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from mutkWallFunctionFvPatchScalarField
TypeName ("mutkWallFunction")
Runtime type information.
mutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &)
Construct as copy.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual scalar fnRough (const scalar KsPlus, const scalar Cs) const
Compute the roughness function.
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalarField Ks_
Roughness height.
scalarField Cs_
Roughness constant.
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on turbulence kinetic energy. The condition manipulates the E parameter to account for roughness effects.
Parameter ranges
roughness height = sand-grain roughness (0 for smooth walls)
roughness constant = 0.5-1.0
Patch usage
Property Description Required Default value
Ks sand-grain roughness height yes
Cs roughness constant yes
Example of the boundary condition specification:
    myPatch
    {
        type            mutkRoughWallFunction;
        Ks              uniform 0;
        Cs              uniform 0.5;
    }
See also
Foam::compressible::mutkRoughWallFunctionFvPatchScalarField
Source files
mutkRoughWallFunctionFvPatchScalarField.H
mutkRoughWallFunctionFvPatchScalarField.C
Definition at line 96 of file mutkRoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutkRoughWallFunctionFvPatchScalarField() [1/5]
mutkRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 128 of file mutkRoughWallFunctionFvPatchScalarField.C.
Referenced by mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::clone(), and mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField().
mutkRoughWallFunctionFvPatchScalarField() [2/5]
mutkRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 154 of file mutkRoughWallFunctionFvPatchScalarField.C.
References mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField().
mutkRoughWallFunctionFvPatchScalarField() [3/5]
mutkRoughWallFunctionFvPatchScalarField (const mutkRoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutkRoughWallFunctionFvPatchScalarField onto a new patch
Definition at line 140 of file mutkRoughWallFunctionFvPatchScalarField.C.
References mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField().
mutkRoughWallFunctionFvPatchScalarField() [4/5]
mutkRoughWallFunctionFvPatchScalarField (const mutkRoughWallFunctionFvPatchScalarField & rwfpsf)
Construct as copy.
Definition at line 167 of file mutkRoughWallFunctionFvPatchScalarField.C.
References mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField().
mutkRoughWallFunctionFvPatchScalarField() [5/5]
mutkRoughWallFunctionFvPatchScalarField (const mutkRoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 178 of file mutkRoughWallFunctionFvPatchScalarField.C.
References mutkRoughWallFunctionFvPatchScalarField::autoMap().
Member Function Documentation
fnRough()
scalar fnRough (const scalar KsPlus, const scalar Cs) const protected virtual
Compute the roughness function.
Definition at line 42 of file mutkRoughWallFunctionFvPatchScalarField.C.
References Foam::log(), Foam::pow(), and Foam::sin().
Referenced by mutkRoughWallFunctionFvPatchScalarField::calcMut().
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 64 of file mutkRoughWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutWallFunctionFvPatchScalarField::Cmu_, mutkRoughWallFunctionFvPatchScalarField::Cs_, Foam::e, mutWallFunctionFvPatchScalarField::E_, Foam::endl(), mutkRoughWallFunctionFvPatchScalarField::fnRough(), forAll, Foam::Info, k, turbulenceModel::k(), mutWallFunctionFvPatchScalarField::kappa_, mutkRoughWallFunctionFvPatchScalarField::Ks_, Foam::log(), Foam::max(), Foam::min(), turbulenceModel::mu(), mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField(), patchi, Foam::pow025(), turbulenceModel::rho(), Foam::sqrt(), y, turbulenceModel::y(), and mutkWallFunctionFvPatchScalarField::yPlus().
TypeName()
TypeName ("mutkRoughWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 161 of file mutkRoughWallFunctionFvPatchScalarField.H.
References mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from mutkWallFunctionFvPatchScalarField.
Definition at line 178 of file mutkRoughWallFunctionFvPatchScalarField.H.
References mutkRoughWallFunctionFvPatchScalarField::autoMap(), mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField(), mutkRoughWallFunctionFvPatchScalarField::rmap(), and mutkRoughWallFunctionFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 192 of file mutkRoughWallFunctionFvPatchScalarField.C.
References Field< Type >::autoMap(), mutkRoughWallFunctionFvPatchScalarField::Cs_, mutkRoughWallFunctionFvPatchScalarField::Ks_, and mutkRoughWallFunctionFvPatchScalarField::rmap().
Referenced by mutkRoughWallFunctionFvPatchScalarField::clone(), and mutkRoughWallFunctionFvPatchScalarField::mutkRoughWallFunctionFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 203 of file mutkRoughWallFunctionFvPatchScalarField.C.
References mutkRoughWallFunctionFvPatchScalarField::Cs_, mutkRoughWallFunctionFvPatchScalarField::Ks_, and Field< Type >::rmap().
Referenced by mutkRoughWallFunctionFvPatchScalarField::autoMap(), and mutkRoughWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from mutWallFunctionFvPatchScalarField.
Definition at line 218 of file mutkRoughWallFunctionFvPatchScalarField.C.
References mutkRoughWallFunctionFvPatchScalarField::Cs_, mutkRoughWallFunctionFvPatchScalarField::Ks_, Foam::compressible::makePatchTypeField(), fvPatchField< Type >::write(), Field< Type >::writeEntry(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by mutkRoughWallFunctionFvPatchScalarField::clone().
Member Data Documentation
Ks_
scalarField Ks_ protected
Roughness height.
Definition at line 105 of file mutkRoughWallFunctionFvPatchScalarField.H.
Referenced by mutkRoughWallFunctionFvPatchScalarField::autoMap(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::rmap(), and mutkRoughWallFunctionFvPatchScalarField::write().
Cs_
scalarField Cs_ protected
Roughness constant.
Definition at line 108 of file mutkRoughWallFunctionFvPatchScalarField.H.
Referenced by mutkRoughWallFunctionFvPatchScalarField::autoMap(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::rmap(), and mutkRoughWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkRoughWallFunction/mutkRoughWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkRoughWallFunction/mutkRoughWallFunctionFvPatchScalarField.C