OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutWallFunctionFvPatchScalarField Class Reference abstract
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy.
Public Member Functions
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< scalarField > yPlus () const =0
Calculate and return the yPlus at the boundary.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Member Functions
virtual void checkType ()
Check the type of the patch.
virtual tmp< scalarField > calcMut () const =0
Calculate the turbulence viscosity.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy.
- replicates OpenFOAM v1.5 (and earlier) behaviour
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            mutWallFunction;
}
See also
Foam::fixedValueFvPatchField
Source files
mutWallFunctionFvPatchScalarField.H
mutWallFunctionFvPatchScalarField.C
Definition at line 68 of file mutWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutWallFunctionFvPatchScalarField() [1/5]
mutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 71 of file mutWallFunctionFvPatchScalarField.C.
Referenced by mutWallFunctionFvPatchScalarField::mutWallFunctionFvPatchScalarField(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
mutWallFunctionFvPatchScalarField() [2/5]
mutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 101 of file mutWallFunctionFvPatchScalarField.C.
References mutWallFunctionFvPatchScalarField::mutWallFunctionFvPatchScalarField().
mutWallFunctionFvPatchScalarField() [3/5]
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutWallFunctionFvPatchScalarField onto a new patch
Definition at line 85 of file mutWallFunctionFvPatchScalarField.C.
References mutWallFunctionFvPatchScalarField::mutWallFunctionFvPatchScalarField().
mutWallFunctionFvPatchScalarField() [4/5]
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 116 of file mutWallFunctionFvPatchScalarField.C.
References mutWallFunctionFvPatchScalarField::mutWallFunctionFvPatchScalarField().
mutWallFunctionFvPatchScalarField() [5/5]
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 129 of file mutWallFunctionFvPatchScalarField.C.
References mutWallFunctionFvPatchScalarField::yPlusLam().
Member Function Documentation
checkType()
void checkType () protected virtual
Check the type of the patch.
Definition at line 46 of file mutWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, and Foam::nl.
calcMut()
virtual tmp<scalarField> calcMut () const protected pure virtual
Calculate the turbulence viscosity.
Implemented in mutURoughWallFunctionFvPatchScalarField, mutkRoughWallFunctionFvPatchScalarField, mutUSpaldingWallFunctionFvPatchScalarField, mutkFilmWallFunctionFvPatchScalarField, mutUWallFunctionFvPatchScalarField, mutkWallFunctionFvPatchScalarField, and mutLowReWallFunctionFvPatchScalarField.
Referenced by mutWallFunctionFvPatchScalarField::updateCoeffs().
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected virtual
Write local wall function variables.
Definition at line 60 of file mutWallFunctionFvPatchScalarField.C.
References mutWallFunctionFvPatchScalarField::Cmu_, mutWallFunctionFvPatchScalarField::E_, token::END_STATEMENT, mutWallFunctionFvPatchScalarField::kappa_, mutWallFunctionFvPatchScalarField::mutWallFunctionFvPatchScalarField(), Foam::nl, and Ostream::writeKeyword().
Referenced by mutUWallFunctionFvPatchScalarField::write(), mutWallFunctionFvPatchScalarField::write(), mutkFilmWallFunctionFvPatchScalarField::write(), mutUSpaldingWallFunctionFvPatchScalarField::write(), mutkRoughWallFunctionFvPatchScalarField::write(), and mutURoughWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("mutWallFunction")
Runtime type information.
yPlusLam()
scalar yPlusLam (const scalar kappa, const scalar E) static
Calculate the Y+ at the edge of the laminar sublayer.
Definition at line 145 of file mutWallFunctionFvPatchScalarField.C.
References Foam::constant::electromagnetic::kappa, Foam::log(), and Foam::max().
Referenced by mutWallFunctionFvPatchScalarField::mutWallFunctionFvPatchScalarField().
yPlus()
virtual tmp<scalarField> yPlus () const pure virtual
Calculate and return the yPlus at the boundary.
Implemented in mutURoughWallFunctionFvPatchScalarField, mutUSpaldingWallFunctionFvPatchScalarField, mutkFilmWallFunctionFvPatchScalarField, mutUWallFunctionFvPatchScalarField, mutkWallFunctionFvPatchScalarField, and mutLowReWallFunctionFvPatchScalarField.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 161 of file mutWallFunctionFvPatchScalarField.C.
References mutWallFunctionFvPatchScalarField::calcMut(), and Foam::operator==().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in mutURoughWallFunctionFvPatchScalarField, mutkRoughWallFunctionFvPatchScalarField, mutUSpaldingWallFunctionFvPatchScalarField, mutkFilmWallFunctionFvPatchScalarField, and mutUWallFunctionFvPatchScalarField.
Definition at line 174 of file mutWallFunctionFvPatchScalarField.C.
References fvPatchField< Type >::write(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
Member Data Documentation
Cmu_
scalar Cmu_ protected
Cmu coefficient.
Definition at line 77 of file mutWallFunctionFvPatchScalarField.H.
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutWallFunctionFvPatchScalarField::writeLocalEntries(), and mutkWallFunctionFvPatchScalarField::yPlus().
kappa_
scalar kappa_ protected
Von Karman constant.
Definition at line 80 of file mutWallFunctionFvPatchScalarField.H.
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutUWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
E_
scalar E_ protected
E coefficient.
Definition at line 83 of file mutWallFunctionFvPatchScalarField.H.
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutUWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
yPlusLam_
scalar yPlusLam_ protected
Y+ at the edge of the laminar sublayer.
Definition at line 86 of file mutWallFunctionFvPatchScalarField.H.
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutUWallFunctionFvPatchScalarField::calcMut(), and mutURoughWallFunctionFvPatchScalarField::calcMut().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutWallFunction/mutWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutWallFunction/mutWallFunctionFvPatchScalarField.C