OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutkWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy.
Public Member Functions
TypeName ("mutkWallFunction")
Runtime type information.
mutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Member Functions
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy.
- replicates OpenFOAM v1.5 (and earlier) behaviour
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            mutkWallFunction;
}
See also
Foam::compressible::mutWallFunctionFvPatchScalarField
Source files
mutkWallFunctionFvPatchScalarField.H
mutkWallFunctionFvPatchScalarField.C
Definition at line 68 of file mutkWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutkWallFunctionFvPatchScalarField() [1/5]
mutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 78 of file mutkWallFunctionFvPatchScalarField.C.
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutkWallFunctionFvPatchScalarField::clone(), and mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField().
mutkWallFunctionFvPatchScalarField() [2/5]
mutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 100 of file mutkWallFunctionFvPatchScalarField.C.
References mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField().
mutkWallFunctionFvPatchScalarField() [3/5]
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutkWallFunctionFvPatchScalarField onto a new patch
Definition at line 88 of file mutkWallFunctionFvPatchScalarField.C.
References mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField().
mutkWallFunctionFvPatchScalarField() [4/5]
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 111 of file mutkWallFunctionFvPatchScalarField.C.
References mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField().
mutkWallFunctionFvPatchScalarField() [5/5]
mutkWallFunctionFvPatchScalarField (const mutkWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 120 of file mutkWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Implements mutWallFunctionFvPatchScalarField.
Reimplemented in mutkRoughWallFunctionFvPatchScalarField, and mutkFilmWallFunctionFvPatchScalarField.
Definition at line 42 of file mutkWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutWallFunctionFvPatchScalarField::Cmu_, mutWallFunctionFvPatchScalarField::E_, forAll, k, turbulenceModel::k(), mutWallFunctionFvPatchScalarField::kappa_, Foam::log(), turbulenceModel::mu(), mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField(), patchi, Foam::pow025(), turbulenceModel::rho(), Foam::sqrt(), y, turbulenceModel::y(), mutkWallFunctionFvPatchScalarField::yPlus(), and mutWallFunctionFvPatchScalarField::yPlusLam_.
TypeName()
TypeName ("mutkWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in mutkRoughWallFunctionFvPatchScalarField, and mutkFilmWallFunctionFvPatchScalarField.
Definition at line 121 of file mutkWallFunctionFvPatchScalarField.H.
References mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in mutkRoughWallFunctionFvPatchScalarField, and mutkFilmWallFunctionFvPatchScalarField.
Definition at line 138 of file mutkWallFunctionFvPatchScalarField.H.
References mutkWallFunctionFvPatchScalarField::mutkWallFunctionFvPatchScalarField(), and mutkWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements mutWallFunctionFvPatchScalarField.
Reimplemented in mutkFilmWallFunctionFvPatchScalarField.
Definition at line 131 of file mutkWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutWallFunctionFvPatchScalarField::Cmu_, k, turbulenceModel::k(), Foam::compressible::makePatchTypeField(), turbulenceModel::mu(), patchi, Foam::pow025(), turbulenceModel::rho(), Foam::sqrt(), y, and turbulenceModel::y().
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), and mutkWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkWallFunction/mutkWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkWallFunction/mutkWallFunctionFvPatchScalarField.C