OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutUWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions, based on velocity.
Public Member Functions
TypeName ("mutUWallFunction")
Runtime type information.
mutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutUWallFunctionFvPatchScalarField (const mutUWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutUWallFunctionFvPatchScalarField (const mutUWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutUWallFunctionFvPatchScalarField (const mutUWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcYPlus (const scalarField &magUp) const
Calculate yPLus.
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions, based on velocity.
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            mutUWallFunction;
}
See also
Foam::compressible::mutWallFunctionFvPatchScalarField
Source files
mutUWallFunctionFvPatchScalarField.H
mutUWallFunctionFvPatchScalarField.C
Definition at line 67 of file mutUWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutUWallFunctionFvPatchScalarField() [1/5]
mutUWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 115 of file mutUWallFunctionFvPatchScalarField.C.
Referenced by mutUWallFunctionFvPatchScalarField::calcMut(), mutUWallFunctionFvPatchScalarField::clone(), and mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField().
mutUWallFunctionFvPatchScalarField() [2/5]
mutUWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 137 of file mutUWallFunctionFvPatchScalarField.C.
References mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField().
mutUWallFunctionFvPatchScalarField() [3/5]
mutUWallFunctionFvPatchScalarField (const mutUWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutUWallFunctionFvPatchScalarField onto a new patch
Definition at line 125 of file mutUWallFunctionFvPatchScalarField.C.
References mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField().
mutUWallFunctionFvPatchScalarField() [4/5]
mutUWallFunctionFvPatchScalarField (const mutUWallFunctionFvPatchScalarField & sawfpsf)
Construct as copy.
Definition at line 148 of file mutUWallFunctionFvPatchScalarField.C.
References mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField().
mutUWallFunctionFvPatchScalarField() [5/5]
mutUWallFunctionFvPatchScalarField (const mutUWallFunctionFvPatchScalarField & sawfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 157 of file mutUWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcYPlus()
tmp< scalarField > calcYPlus (const scalarField & magUp) const protected virtual
Calculate yPLus.
Definition at line 42 of file mutUWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, Foam::log(), Foam::mag(), Foam::max(), turbulenceModel::mu(), patchi, turbulenceModel::rho(), y, turbulenceModel::y(), and yPlus.
Referenced by mutUWallFunctionFvPatchScalarField::calcMut(), and mutUWallFunctionFvPatchScalarField::yPlus().
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 82 of file mutUWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutUWallFunctionFvPatchScalarField::calcYPlus(), mutWallFunctionFvPatchScalarField::E_, forAll, mutWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), magUp, turbulenceModel::mu(), mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField(), patchi, turbulenceModel::U(), mutUWallFunctionFvPatchScalarField::yPlus(), and mutWallFunctionFvPatchScalarField::yPlusLam_.
TypeName()
TypeName ("mutUWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 123 of file mutUWallFunctionFvPatchScalarField.H.
References mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 140 of file mutUWallFunctionFvPatchScalarField.H.
References mutUWallFunctionFvPatchScalarField::mutUWallFunctionFvPatchScalarField(), mutUWallFunctionFvPatchScalarField::write(), and mutUWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 168 of file mutUWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutUWallFunctionFvPatchScalarField::calcYPlus(), Foam::mag(), magUp, patchi, and turbulenceModel::U().
Referenced by mutUWallFunctionFvPatchScalarField::calcMut(), and mutUWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from mutWallFunctionFvPatchScalarField.
Definition at line 180 of file mutUWallFunctionFvPatchScalarField.C.
References Foam::compressible::makePatchTypeField(), fvPatchField< Type >::write(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by mutUWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUWallFunction/mutUWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUWallFunction/mutUWallFunctionFvPatchScalarField.C