OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutLowReWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition for use with low Reynolds number models. It sets nut to zero, and provides an access function to calculate y+.
Public Member Functions
TypeName ("mutLowReWallFunction")
Runtime type information.
mutLowReWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutLowReWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutLowReWallFunctionFvPatchScalarField (const mutLowReWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutLowReWallFunctionFvPatchScalarField (const mutLowReWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutLowReWallFunctionFvPatchScalarField (const mutLowReWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Member Functions
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition for use with low Reynolds number models. It sets nut to zero, and provides an access function to calculate y+.
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            mutLowReWallFunction;
}
See also
Foam::compressible::mutWallFunctionFvPatchScalarField
Source files
mutLowReWallFunctionFvPatchScalarField.H
mutLowReWallFunctionFvPatchScalarField.C
Definition at line 68 of file mutLowReWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutLowReWallFunctionFvPatchScalarField() [1/5]
mutLowReWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 50 of file mutLowReWallFunctionFvPatchScalarField.C.
Referenced by mutLowReWallFunctionFvPatchScalarField::calcMut(), mutLowReWallFunctionFvPatchScalarField::clone(), and mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField().
mutLowReWallFunctionFvPatchScalarField() [2/5]
mutLowReWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 72 of file mutLowReWallFunctionFvPatchScalarField.C.
References mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField().
mutLowReWallFunctionFvPatchScalarField() [3/5]
mutLowReWallFunctionFvPatchScalarField (const mutLowReWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutLowReWallFunctionFvPatchScalarField onto a new patch
Definition at line 60 of file mutLowReWallFunctionFvPatchScalarField.C.
References mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField().
mutLowReWallFunctionFvPatchScalarField() [4/5]
mutLowReWallFunctionFvPatchScalarField (const mutLowReWallFunctionFvPatchScalarField & mlrwfpsf)
Construct as copy.
Definition at line 83 of file mutLowReWallFunctionFvPatchScalarField.C.
References mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField().
mutLowReWallFunctionFvPatchScalarField() [5/5]
mutLowReWallFunctionFvPatchScalarField (const mutLowReWallFunctionFvPatchScalarField & mlrwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 92 of file mutLowReWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 41 of file mutLowReWallFunctionFvPatchScalarField.C.
References mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField().
TypeName()
TypeName ("mutLowReWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 121 of file mutLowReWallFunctionFvPatchScalarField.H.
References mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 138 of file mutLowReWallFunctionFvPatchScalarField.H.
References mutLowReWallFunctionFvPatchScalarField::mutLowReWallFunctionFvPatchScalarField(), and mutLowReWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 103 of file mutLowReWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::mag(), Foam::compressible::makePatchTypeField(), turbulenceModel::mu(), patchi, turbulenceModel::rho(), Foam::sqrt(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by mutLowReWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutLowReWallFunction/mutLowReWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutLowReWallFunction/mutLowReWallFunctionFvPatchScalarField.C