OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutURoughWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on velocity.
Public Member Functions
TypeName ("mutURoughWallFunction")
Runtime type information.
mutURoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutURoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutURoughWallFunctionFvPatchScalarField (const mutURoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutURoughWallFunctionFvPatchScalarField (const mutURoughWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutURoughWallFunctionFvPatchScalarField (const mutURoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalar roughnessHeight () const
Return the roughness height scale.
scalar & roughnessHeight ()
Return reference to the roughness height to allow adjustment.
scalar roughnessConstant () const
Return the roughness constant scale.
scalar & roughnessConstant ()
Return reference to the roughness constant to allow adjustment.
scalar roughnessFactor () const
Return the roughness scale factor.
scalar & roughnessFactor ()
Return reference to the roughness scale factor to allow.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcYPlus (const scalarField &magUp) const
Calculate yPLus.
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalar roughnessHeight_
Height.
scalar roughnessConstant_
Constant.
scalar roughnessFactor_
Scale factor.
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on velocity.
Patch usage
Property Description Required Default value
roughnessHeight roughness height yes
roughnessConstant roughness constanr yes
roughnessFactor scaling factor yes
Example of the boundary condition specification:
    myPatch
    {
        type            mutURoughWallFunction;
        roughnessHeight 1e-5;
        roughnessConstant 0.5;
        roughnessFactor 1;
    }
See also
Foam::compressible::mutWallFunctionFvPatchScalarField
Source files
mutURoughWallFunctionFvPatchScalarField.H
mutURoughWallFunctionFvPatchScalarField.C
Definition at line 97 of file mutURoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutURoughWallFunctionFvPatchScalarField() [1/5]
mutURoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 208 of file mutURoughWallFunctionFvPatchScalarField.C.
Referenced by mutURoughWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::clone(), and mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField().
mutURoughWallFunctionFvPatchScalarField() [2/5]
mutURoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 236 of file mutURoughWallFunctionFvPatchScalarField.C.
References mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField().
mutURoughWallFunctionFvPatchScalarField() [3/5]
mutURoughWallFunctionFvPatchScalarField (const mutURoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutURoughWallFunctionFvPatchScalarField onto a new patch
Definition at line 221 of file mutURoughWallFunctionFvPatchScalarField.C.
References mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField().
mutURoughWallFunctionFvPatchScalarField() [4/5]
mutURoughWallFunctionFvPatchScalarField (const mutURoughWallFunctionFvPatchScalarField & rwfpsf)
Construct as copy.
Definition at line 250 of file mutURoughWallFunctionFvPatchScalarField.C.
References mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField().
mutURoughWallFunctionFvPatchScalarField() [5/5]
mutURoughWallFunctionFvPatchScalarField (const mutURoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 262 of file mutURoughWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcYPlus()
tmp< scalarField > calcYPlus (const scalarField & magUp) const protected virtual
Calculate yPLus.
Definition at line 42 of file mutURoughWallFunctionFvPatchScalarField.C.
References Foam::atan(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cos(), forAll, Foam::constant::universal::G, Foam::log(), Foam::mag(), Foam::max(), turbulenceModel::mu(), patchi, Foam::Re(), rho, turbulenceModel::rho(), Foam::sin(), y, turbulenceModel::y(), and yPlus.
Referenced by mutURoughWallFunctionFvPatchScalarField::calcMut(), and mutURoughWallFunctionFvPatchScalarField::yPlus().
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 171 of file mutURoughWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), forAll, Foam::mag(), magUp, turbulenceModel::mu(), mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField(), patchi, fvPatchField< Type >::patchInternalField(), Foam::Re(), rho, turbulenceModel::rho(), Foam::sqr(), turbulenceModel::U(), y, turbulenceModel::y(), mutURoughWallFunctionFvPatchScalarField::yPlus(), and mutWallFunctionFvPatchScalarField::yPlusLam_.
TypeName()
TypeName ("mutURoughWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 167 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 184 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::mutURoughWallFunctionFvPatchScalarField().
roughnessHeight() [1/2]
scalar roughnessHeight () const inline
Return the roughness height scale.
Definition at line 200 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::roughnessHeight_.
roughnessHeight() [2/2]
scalar& roughnessHeight () inline
Return reference to the roughness height to allow adjustment.
Definition at line 206 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::roughnessHeight_.
roughnessConstant() [1/2]
scalar roughnessConstant () const inline
Return the roughness constant scale.
Definition at line 212 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::roughnessConstant_.
roughnessConstant() [2/2]
scalar& roughnessConstant () inline
Return reference to the roughness constant to allow adjustment.
Definition at line 218 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::roughnessConstant_.
roughnessFactor() [1/2]
scalar roughnessFactor () const inline
Return the roughness scale factor.
Definition at line 224 of file mutURoughWallFunctionFvPatchScalarField.H.
References mutURoughWallFunctionFvPatchScalarField::roughnessFactor_, mutURoughWallFunctionFvPatchScalarField::write(), and mutURoughWallFunctionFvPatchScalarField::yPlus().
roughnessFactor() [2/2]
scalar& roughnessFactor () inline
Return reference to the roughness scale factor to allow.
adjustment
Definition at line 231 of file mutURoughWallFunctionFvPatchScalarField.H.
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 276 of file mutURoughWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), Foam::mag(), magUp, patchi, and turbulenceModel::U().
Referenced by mutURoughWallFunctionFvPatchScalarField::calcMut(), and mutURoughWallFunctionFvPatchScalarField::roughnessFactor().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from mutWallFunctionFvPatchScalarField.
Definition at line 289 of file mutURoughWallFunctionFvPatchScalarField.C.
References token::END_STATEMENT, Foam::compressible::makePatchTypeField(), Foam::nl, mutURoughWallFunctionFvPatchScalarField::roughnessConstant_, mutURoughWallFunctionFvPatchScalarField::roughnessFactor_, mutURoughWallFunctionFvPatchScalarField::roughnessHeight_, write(), Ostream::writeKeyword(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by mutURoughWallFunctionFvPatchScalarField::roughnessFactor().
Member Data Documentation
roughnessHeight_
scalar roughnessHeight_ protected
Height.
Definition at line 108 of file mutURoughWallFunctionFvPatchScalarField.H.
Referenced by mutURoughWallFunctionFvPatchScalarField::roughnessHeight(), and mutURoughWallFunctionFvPatchScalarField::write().
roughnessConstant_
scalar roughnessConstant_ protected
Constant.
Definition at line 111 of file mutURoughWallFunctionFvPatchScalarField.H.
Referenced by mutURoughWallFunctionFvPatchScalarField::roughnessConstant(), and mutURoughWallFunctionFvPatchScalarField::write().
roughnessFactor_
scalar roughnessFactor_ protected
Scale factor.
Definition at line 114 of file mutURoughWallFunctionFvPatchScalarField.H.
Referenced by mutURoughWallFunctionFvPatchScalarField::roughnessFactor(), and mutURoughWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutURoughWallFunction/mutURoughWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutURoughWallFunction/mutURoughWallFunctionFvPatchScalarField.C