OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
externalWallHeatFluxTemperatureFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditionsBoundary Conditions » | Wall boundary Conditions
This boundary condition supplies a heat flux condition for temperature on an external wall. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries for the fixed heat transfer coefficient mode.
Public Types
enum operationMode { fixedHeatFlux, fixedHeatTransferCoeff, unknown }
Operation mode enumeration.
Public Types inherited from temperatureCoupledBase
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Public Member Functions
TypeName ("externalWallHeatFluxTemperature")
Runtime type information.
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
void write (Ostream &) const
Write.
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Static Public Attributes
static const NamedEnum< operationMode, 3 > operationModeNames
Additional Inherited Members
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes inherited from temperatureCoupledBase
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
This boundary condition supplies a heat flux condition for temperature on an external wall. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries for the fixed heat transfer coefficient mode.
The condition can operate in two modes:
fixed heat transfer coefficient: supply h and Ta
fixed heat flux: supply q
where:
= heat transfer coefficient [W/m^2/K]
= ambient temperature [K]
= heat flux [W/m^2]
The thermal conductivity, kappa, can either be retrieved from the mesh database using the lookup option, or from a solidThermo thermophysical package.
Patch usage
Property Description Required Default value
kappa thermal conductivity option yes
q heat flux [W/m^2] yes*
Ta ambient temperature [K] yes*
h heat transfer coefficient [W/m^2/K] yes*
thicknessLayers list of thicknesses per layer [m] yes
kappaLayers list of thermal conductivites per layer [W/m/K] yes
kappaName name of thermal conductivity field yes
QrName name of the radiative field no no
Example of the boundary condition specification:
    myPatch
    {
        type            externalWallHeatFluxTemperature;
        kappa           fluidThermo;
        q               uniform 1000;
        Ta              uniform 300.0;
        h               uniform 10.0;
        thicknessLayers (0.1 0.2 0.3 0.4);
        kappaLayers     (1 2 3 4);
        value           uniform 300.0;
        kappaName       none;
        QrName          none;
    }
Note
Only supply h and Ta, or q in the dictionary (see above)
kappa entries can be: fluidThermo, solidThermo or lookup
Source files
externalWallHeatFluxTemperatureFvPatchScalarField.H
externalWallHeatFluxTemperatureFvPatchScalarField.C
Definition at line 163 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
Member Enumeration Documentation
operationMode
enum operationMode
Operation mode enumeration.
Enumerator
fixedHeatFlux
fixedHeatTransferCoeff
unknown
Definition at line 173 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
externalWallHeatFluxTemperatureFvPatchScalarField() [1/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 61 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
Referenced by externalWallHeatFluxTemperatureFvPatchScalarField::clone(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), and NamedEnum< directionType, 3 >::names().
externalWallHeatFluxTemperatureFvPatchScalarField() [2/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 109 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References dimensionedInternalField(), Foam::exit(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), Foam::FatalError, FatalErrorIn, dictionary::found(), dictionary::lookup(), fvPatch::name(), fvPatchField< Type >::operator=(), and fvPatch::size().
externalWallHeatFluxTemperatureFvPatchScalarField() [3/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
externalWallHeatFluxTemperatureFvPatchScalarField onto a new patch
Definition at line 86 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField().
externalWallHeatFluxTemperatureFvPatchScalarField() [4/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 188 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField().
externalWallHeatFluxTemperatureFvPatchScalarField() [5/5]
externalWallHeatFluxTemperatureFvPatchScalarField (const externalWallHeatFluxTemperatureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 208 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References externalWallHeatFluxTemperatureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("externalWallHeatFluxTemperature")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 255 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
References externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 272 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
References externalWallHeatFluxTemperatureFvPatchScalarField::autoMap(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), externalWallHeatFluxTemperatureFvPatchScalarField::rmap(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), and externalWallHeatFluxTemperatureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 230 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References externalWallHeatFluxTemperatureFvPatchScalarField::rmap().
Referenced by externalWallHeatFluxTemperatureFvPatchScalarField::clone(), and externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 242 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References externalWallHeatFluxTemperatureFvPatchScalarField::rmap().
Referenced by externalWallHeatFluxTemperatureFvPatchScalarField::autoMap(), externalWallHeatFluxTemperatureFvPatchScalarField::clone(), and externalWallHeatFluxTemperatureFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 258 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References dimensionedInternalField(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), Foam::Info, Foam::constant::electromagnetic::kappa, List< T >::size(), Foam::fvc::snGrad(), and externalWallHeatFluxTemperatureFvPatchScalarField::write().
Referenced by externalWallHeatFluxTemperatureFvPatchScalarField::clone().
write()
void write (Ostream & os) const
Write.
Definition at line 346 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References Foam::abort(), token::END_STATEMENT, Foam::FatalError, FatalErrorIn, Foam::makePatchTypeField(), Foam::nl, write(), temperatureCoupledBase::write(), and Ostream::writeKeyword().
Referenced by externalWallHeatFluxTemperatureFvPatchScalarField::clone(), and externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
Member Data Documentation
operationModeNames
const NamedEnum< externalWallHeatFluxTemperatureFvPatchScalarField::operationMode, 3 > operationModeNames static
Definition at line 179 of file externalWallHeatFluxTemperatureFvPatchScalarField.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/externalWallHeatFluxTemperature/externalWallHeatFluxTemperatureFvPatchScalarField.H
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/externalWallHeatFluxTemperature/externalWallHeatFluxTemperatureFvPatchScalarField.C