OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mutUSpaldingWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible RAS turbulence » RAS compressible boundary conditions » RAS compressible wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on velocity, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
Public Member Functions
TypeName ("mutUSpaldingWallFunction")
Runtime type information.
mutUSpaldingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutUSpaldingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutUSpaldingWallFunctionFvPatchScalarField (const mutUSpaldingWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutUSpaldingWallFunctionFvPatchScalarField (const mutUSpaldingWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mutUSpaldingWallFunctionFvPatchScalarField (const mutUSpaldingWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from mutWallFunctionFvPatchScalarField
TypeName ("mutWallFunction")
Runtime type information.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &)
Construct as copy.
mutWallFunctionFvPatchScalarField (const mutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcMut () const
Calculate the turbulence viscosity.
virtual tmp< scalarField > calcUTau (const scalarField &magGradU) const
Calculate the friction velocity.
Protected Member Functions inherited from mutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from mutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from mutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions for rough walls, based on velocity, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
where
= non-dimensional position
= non-dimensional velocity
= Von Karman constant
Patch usage
Example of the boundary condition specification:
    myPatch
    {
        type            mutUSpaldingWallFunction;
    }
See also
Foam::compressible::mutWallFunctionFvPatchScalarField
Source files
mutUSpaldingWallFunctionFvPatchScalarField.H
mutUSpaldingWallFunctionFvPatchScalarField.C
Definition at line 93 of file mutUSpaldingWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
mutUSpaldingWallFunctionFvPatchScalarField() [1/5]
mutUSpaldingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 129 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
Referenced by mutUSpaldingWallFunctionFvPatchScalarField::calcMut(), mutUSpaldingWallFunctionFvPatchScalarField::clone(), and mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField().
mutUSpaldingWallFunctionFvPatchScalarField() [2/5]
mutUSpaldingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 153 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField().
mutUSpaldingWallFunctionFvPatchScalarField() [3/5]
mutUSpaldingWallFunctionFvPatchScalarField (const mutUSpaldingWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mutUSpaldingWallFunctionFvPatchScalarField onto a new patch
Definition at line 140 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField().
mutUSpaldingWallFunctionFvPatchScalarField() [4/5]
mutUSpaldingWallFunctionFvPatchScalarField (const mutUSpaldingWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 165 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField().
mutUSpaldingWallFunctionFvPatchScalarField() [5/5]
mutUSpaldingWallFunctionFvPatchScalarField (const mutUSpaldingWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 175 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcMut()
tmp< scalarField > calcMut () const protected virtual
Calculate the turbulence viscosity.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 105 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), Foam::mag(), Foam::max(), turbulenceModel::mu(), mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField(), patchi, turbulenceModel::rho(), Foam::sqr(), and turbulenceModel::U().
calcUTau()
tmp< scalarField > calcUTau (const scalarField & magGradU) const protected virtual
Calculate the friction velocity.
Definition at line 42 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::exp(), f(), forAll, Foam::mag(), magUp, Foam::max(), Foam::min(), turbulenceModel::mu(), fvPatchField< Type >::patchInternalField(), turbulenceModel::rho(), Foam::sqr(), Foam::sqrt(), turbulenceModel::U(), uTau, y, and turbulenceModel::y().
Referenced by mutUSpaldingWallFunctionFvPatchScalarField::calcMut(), and mutUSpaldingWallFunctionFvPatchScalarField::yPlus().
TypeName()
TypeName ("mutUSpaldingWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 149 of file mutUSpaldingWallFunctionFvPatchScalarField.H.
References mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 166 of file mutUSpaldingWallFunctionFvPatchScalarField.H.
References mutUSpaldingWallFunctionFvPatchScalarField::mutUSpaldingWallFunctionFvPatchScalarField(), mutUSpaldingWallFunctionFvPatchScalarField::write(), and mutUSpaldingWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements mutWallFunctionFvPatchScalarField.
Definition at line 186 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), Foam::mag(), turbulenceModel::mu(), patchi, turbulenceModel::rho(), fvPatchField< Type >::snGrad(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by mutUSpaldingWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from mutWallFunctionFvPatchScalarField.
Definition at line 202 of file mutUSpaldingWallFunctionFvPatchScalarField.C.
References Foam::compressible::makePatchTypeField(), fvPatchField< Type >::write(), and mutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by mutUSpaldingWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUSpaldingWallFunction/mutUSpaldingWallFunctionFvPatchScalarField.H
src/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUSpaldingWallFunction/mutUSpaldingWallFunctionFvPatchScalarField.C