OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentHeatFluxTemperatureFvPatchScalarField Class Reference
Public Types
enum heatSourceType { hsPower, hsFlux }
Enumeration listing the possible hest source input modes.
Public Types inherited from temperatureCoupledBase
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Public Member Functions
TypeName ("compressible::turbulentHeatFluxTemperature")
Runtime type information.
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Additional Inherited Members
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes inherited from temperatureCoupledBase
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
Definition at line 66 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
Member Enumeration Documentation
heatSourceType
enum heatSourceType
Enumeration listing the possible hest source input modes.
Enumerator
hsPower
hsFlux
Definition at line 76 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentHeatFluxTemperatureFvPatchScalarField() [1/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 73 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone(), NamedEnum< directionType, 3 >::names(), and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [2/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 105 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References dict, dictionary::found(), fvPatchField< Type >::operator=(), fvPatch::size(), and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [3/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentHeatFluxTemperatureFvPatchScalarField onto a new patch
Definition at line 88 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [4/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField & thftpsf)
Construct as copy.
Definition at line 133 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [5/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField & thftpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 147 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("compressible::turbulentHeatFluxTemperature")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 141 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
References turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 158 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
References turbulentHeatFluxTemperatureFvPatchScalarField::autoMap(), turbulentHeatFluxTemperatureFvPatchScalarField::rmap(), turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField(), turbulentHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), and turbulentHeatFluxTemperatureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 163 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::rmap().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone(), and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 173 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::rmap().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::autoMap(), turbulentHeatFluxTemperatureFvPatchScalarField::clone(), and turbulentHeatFluxTemperatureFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
qr is negative going into the domain
Definition at line 190 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::gSum(), turbulentHeatFluxTemperatureFvPatchScalarField::hsFlux, turbulentHeatFluxTemperatureFvPatchScalarField::hsPower, temperatureCoupledBase::kappa(), Foam::nl, and turbulentHeatFluxTemperatureFvPatchScalarField::write().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 235 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::compressible::makePatchTypeField(), Foam::nl, write(), temperatureCoupledBase::write(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone(), and turbulentHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/turbulentHeatFluxTemperature/turbulentHeatFluxTemperatureFvPatchScalarField.H
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/turbulentHeatFluxTemperature/turbulentHeatFluxTemperatureFvPatchScalarField.C