OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LESdelta Class Reference
Abstract base class for incompressible LES deltas.
Public Member Functions
declareRunTimeSelectionTable (autoPtr, foamLESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &mesh)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESdelta dictionary.
virtual void correct ()=0
virtual operator const volScalarField & () const
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESdelta dictionary.
virtual void correct ()=0
virtual operator const volScalarField & () const
Static Public Member Functions
static autoPtr< foamLESdelta > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected LES delta.
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Additional Inherited Members
Protected Attributes inherited from LESdelta
const fvMesh & mesh_
volScalarField delta_
Detailed Description
Abstract base class for incompressible LES deltas.
Source files
incompressibleLESdelta.H
incompressibleLESdelta.C
Definition at line 54 of file incompressibleLESdelta.H.
Constructor & Destructor Documentation
LESdelta()
LESdelta (const word & name, const fvMesh & mesh)
Construct from name and mesh.
Definition at line 42 of file incompressibleLESdelta.C.
References LESdelta::New().
~LESdelta()
virtual ~LESdelta () inline virtual
Destructor.
Reimplemented from LESdelta.
Definition at line 94 of file incompressibleLESdelta.H.
Member Function Documentation
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , foamLESdelta , dictionary , (const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict) , (name, mesh, LESdeltaDict))
New()
Foam::autoPtr< foamLESdelta > New (const word & name, const fvMesh & mesh, const dictionary & dict) static
Return a reference to the selected LES delta.
Definition at line 51 of file incompressibleLESdelta.C.
References LESdelta::New().
Referenced by LESdelta::LESdelta().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/LES/incompressibleLESdelta/incompressibleLESdelta.H
src/turbulenceModels/incompressible/LES/incompressibleLESdelta/incompressibleLESdelta.C