OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fixedShearStressFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary Conditions
Set a constant shear stress as tau0 = -nuEff dU/dn.
Public Member Functions
TypeName ("fixedShearStress")
Runtime type information.
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
TypeName ("fixedShearStress")
Runtime type information.
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Set a constant shear stress as tau0 = -nuEff dU/dn.
Source files
fixedShearStressFvPatchVectorField.H
fixedShearStressFvPatchVectorField.C
Source files
fixedShearStressFvPatchVectorField.H
fixedShearStressFvPatchVectorField.C
Definition at line 52 of file fixedShearStressFvPatchVectorField.H.
Constructor & Destructor Documentation
fixedShearStressFvPatchVectorField() [1/10]
fixedShearStressFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file fixedShearStressFvPatchVectorField.C.
Referenced by fixedShearStressFvPatchVectorField::clone(), and fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [2/10]
fixedShearStressFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 50 of file fixedShearStressFvPatchVectorField.C.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [3/10]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
Definition at line 66 of file fixedShearStressFvPatchVectorField.C.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [4/10]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf)
Construct as copy.
Definition at line 81 of file fixedShearStressFvPatchVectorField.C.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [5/10]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 93 of file fixedShearStressFvPatchVectorField.C.
fixedShearStressFvPatchVectorField() [6/10]
fixedShearStressFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
fixedShearStressFvPatchVectorField() [7/10]
fixedShearStressFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
fixedShearStressFvPatchVectorField() [8/10]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
fixedShearStressFvPatchVectorField() [9/10]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &)
Construct as copy.
fixedShearStressFvPatchVectorField() [10/10]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName() [1/2]
TypeName ("fixedShearStress")
Runtime type information.
clone() [1/4]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 107 of file fixedShearStressFvPatchVectorField.H.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
Referenced by fixedShearStressFvPatchVectorField::clone().
clone() [2/4]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 124 of file fixedShearStressFvPatchVectorField.H.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField(), fixedShearStressFvPatchVectorField::updateCoeffs(), and fixedShearStressFvPatchVectorField::write().
updateCoeffs() [1/2]
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 107 of file fixedShearStressFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, dimensionedInternalField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::mag(), Foam::operator==(), and phi.
Referenced by fixedShearStressFvPatchVectorField::clone().
write() [1/2]
void write (Ostream & os) const virtual
Write.
Definition at line 165 of file fixedShearStressFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, and write().
Referenced by fixedShearStressFvPatchVectorField::clone().
TypeName() [2/2]
TypeName ("fixedShearStress")
Runtime type information.
clone() [3/4]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 101 of file fixedShearStressFvPatchVectorField.H.
References fixedShearStressFvPatchVectorField::clone(), and fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
clone() [4/4]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 118 of file fixedShearStressFvPatchVectorField.H.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField(), fixedShearStressFvPatchVectorField::updateCoeffs(), and fixedShearStressFvPatchVectorField::write().
updateCoeffs() [2/2]
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
write() [2/2]
virtual void write (Ostream &) const virtual
Write.
The documentation for this class was generated from the following files:
src/turbulenceModels/derivedFvPatchFields/fixedShearStress/fixedShearStressFvPatchVectorField.H
src/turbulenceModels/derivedFvPatchFields/fixedShearStress/fixedShearStressFvPatchVectorField.C