OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentTemperatureRadCoupledMixedFvPatchScalarField Class Reference
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
Public Member Functions
TypeName ("compressible::turbulentTemperatureRadCoupledMixed")
Runtime type information.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes inherited from temperatureCoupledBase
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
The thermal conductivity, kappa, can either be retrieved from the mesh database using the lookup option, or from a solidThermo or fluidThermo thermophysical package.
Patch usage
Property Description Required Default value
kappa thermal conductivity option yes
kappaName name of thermal conductivity field no
Tnbr name of the field no T
QrNbr name of the radiative flux in the nbr region no none
Qr name of the radiative flux in this region no none
thicknessLayers list of thicknesses per layer [m] no
kappaLayers list of thermal conductivites per layer [W/m/K] no
Example of the boundary condition specification:
    myPatch
    {
        type            compressible::turbulentTemperatureRadCoupledMixed;
        Tnbr            T;
        kappa           lookup;
        KappaName       kappa;
        QrNbr           Qr; // or none. Name of Qr field on neighbour region
        Qr              Qr; // or none. Name of Qr field on local region
        thicknessLayers (0.1 0.2 0.3 0.4);
        kappaLayers     (1 2 3 4)
        value           uniform 300;
    }
Needs to be on underlying mapped(Wall)FvPatch.
Note: kappa : heat conduction at patch. Gets supplied how to lookup/calculate kappa:
'lookup' : lookup volScalarField (or volSymmTensorField) with name
'fluidThermo' : use fluidThermo and compressible::RASmodel to calculate K
'solidThermo' : use solidThermo kappa()
'directionalSolidThermo' directionalKappa()
Source files
turbulentTemperatureRadCoupledMixedFvPatchScalarField.H
turbulentTemperatureRadCoupledMixedFvPatchScalarField.C
Definition at line 138 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [1/4]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 43 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::clone(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField().
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [2/4]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 85 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, dictionary::found(), dictionary::lookup(), fvPatch::name(), fvPatchField< Type >::operator=(), fvPatch::size(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField().
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [3/4]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField onto a new patch
Definition at line 65 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField().
turbulentTemperatureRadCoupledMixedFvPatchScalarField() [4/4]
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 156 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::turbulentTemperatureRadCoupledMixed")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 200 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.H.
References turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 220 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.H.
References turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 174 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References boundary(), fvPatch::deltaCoeffs(), dimensionedInternalField(), mappedPatchBase::distribute(), Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), patchIdentifier::index(), Foam::Info, temperatureCoupledBase::kappa(), fvPatch::lookupPatchField(), UPstream::msgType(), fvPatch::name(), Foam::refCast(), mappedPatchBase::sampleMesh(), mappedPatchBase::samplePolyPatch(), List< T >::setSize(), List< T >::size(), Foam::fvc::snGrad(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::write().
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::clone(), and thermalBaffleFvPatchScalarField::updateCoeffs().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in thermalBaffleFvPatchScalarField.
Definition at line 267 of file turbulentTemperatureRadCoupledMixedFvPatchScalarField.C.
References token::END_STATEMENT, Foam::compressible::makePatchTypeField(), Foam::nl, write(), temperatureCoupledBase::write(), UList< T >::writeEntry(), and Ostream::writeKeyword().
Referenced by turbulentTemperatureRadCoupledMixedFvPatchScalarField::clone(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), and thermalBaffleFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/turbulentTemperatureRadCoupledMixed/turbulentTemperatureRadCoupledMixedFvPatchScalarField.H
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/turbulentTemperatureRadCoupledMixed/turbulentTemperatureRadCoupledMixedFvPatchScalarField.C