OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField Class Reference
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles.Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
Public Member Functions
TypeName ("compressible::turbulentTemperatureCoupledBaffleMixed")
Runtime type information.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes inherited from temperatureCoupledBase
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles.Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
The thermal conductivity, kappa, can either be retrieved from the mesh database using the lookup option, or from a solidThermo or fluidThermo thermophysical package.
Specifies gradient and temperature such that the equations are the same on both sides:
refGradient = zero gradient
refValue = neighbour value
mixFraction = nbrKDelta / (nbrKDelta + myKDelta())
where KDelta is heat-transfer coefficient K * deltaCoeffs
Patch usage
Property Description Required Default value
kappa thermal conductivity option yes
kappaName name of thermal conductivity field no
Tnbr name of the field no T
thicknessLayers list of thicknesses per layer [m] no
kappaLayers list of thermal conductivites per layer [W/m/K] no
Example of the boundary condition specification:
    myPatch
    {
        type            compressible::turbulentTemperatureCoupledBaffleMixed;
        Tnbr            T;
        kappa           lookup;
        KappaName       kappa;
        thicknessLayers (0.1 0.2 0.3 0.4);
        kappaLayers     (1 2 3 4)
        value           uniform 300;
    }
Needs to be on underlying mapped(Wall)FvPatch.
Note: kappa : heat conduction at patch. Gets supplied how to lookup calculate kappa:
'lookup' : lookup volScalarField (or volSymmTensorField) with name
'fluidThermo' : use fluidThermo and compressible::RASmodel to calculate kappa
'solidThermo' : use solidThermo kappa()
'directionalSolidThermo' directionalKappa()
Source files
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C
Definition at line 134 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [1/4]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 43 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::clone(), and turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField().
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [2/4]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 81 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, dictionary::found(), dictionary::lookup(), fvPatch::name(), fvPatchField< Type >::operator=(), fvPatch::size(), and turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField().
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [3/4]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField onto a new patch
Definition at line 63 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField().
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField() [4/4]
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField (const turbulentTemperatureCoupledBaffleMixedFvPatchScalarField & wtcsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 150 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::turbulentTemperatureCoupledBaffleMixed")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 189 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H.
References turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 209 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H.
References turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 166 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References boundary(), fvPatch::deltaCoeffs(), dimensionedInternalField(), mappedPatchBase::distribute(), Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), patchIdentifier::index(), Foam::Info, temperatureCoupledBase::kappa(), fvPatch::lookupPatchField(), UPstream::msgType(), fvPatch::name(), Foam::refCast(), mappedPatchBase::sampleMesh(), mappedPatchBase::samplePolyPatch(), Foam::fvc::snGrad(), and turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write().
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 273 of file turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C.
References token::END_STATEMENT, Foam::compressible::makePatchTypeField(), Foam::nl, write(), temperatureCoupledBase::write(), UList< T >::writeEntry(), and Ostream::writeKeyword().
Referenced by turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::clone(), and turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/turbulentTemperatureCoupledBaffleMixed/turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.H
src/turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/turbulentTemperatureCoupledBaffleMixed/turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.C