OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulenceModel Class Reference abstract
Abstract base class for compressible turbulence models (RAS, LES and laminar).
Public Member Functions
TypeName ("turbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr, turbulenceModel, turbulenceModel,(const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const fluidThermo &thermoPhysicalModel, const word &turbulenceModelName),(rho, U, phi, thermoPhysicalModel, turbulenceModelName))
turbulenceModel (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const fluidThermo &thermoPhysicalModel, const word &turbulenceModelName=typeName)
Construct from components.
virtual ~turbulenceModel ()
Destructor.
virtual const dictionary & coeffDict () const =0
Const access to the coefficients dictionary.
word GName () const
Helper function to return the nam eof the turbulence G field.
const volScalarField & rho () const
Access function to density field.
const volVectorField & U () const
Access function to velocity field.
const surfaceScalarField & phi () const
Access function to flux field.
const fluidThermo & thermo () const
Access function to thermophysical model.
const nearWallDist & y () const
Return the near wall distances.
const volScalarField & mu () const
Return the laminar viscosity.
const volScalarField & alpha () const
Return the laminar thermal conductivity.
virtual tmp< volScalarField > mut () const =0
Return the turbulence viscosity.
virtual tmp< volScalarField > muEff () const =0
Return the effective viscosity.
virtual tmp< volScalarField > alphat () const =0
Return the turbulence thermal diffusivity.
virtual tmp< scalarField > alphat (const label patchI) const
Return the turbulence thermal diffusivity for a patch.
virtual tmp< volScalarField > kappaEff () const =0
Return the effective turbulence temperature diffusivity.
virtual tmp< scalarField > kappaEff (const label patchI) const =0
Return the effective turbulence temperature diffusivity for a patch.
virtual tmp< volScalarField > alphaEff () const =0
Return the effective turbulence thermal diffusivity.
virtual tmp< scalarField > alphaEff (const label patchI) const =0
Return the effective turbulence thermal diffusivity for a patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const =0
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > rhoEpsilonEff () const
Return the laminar+turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const =0
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const =0
Return the effective stress tensor including the laminar stress.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const =0
Return the source term for the momentum equation.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
virtual bool read ()=0
Read LESProperties or RASProperties dictionary.
virtual bool writeData (Ostream &) const
Default dummy write function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static autoPtr< turbulenceModel > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const fluidThermo &thermoPhysicalModel, const word &turbulenceModelName=typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Attributes
const Time & runTime_
const fvMesh & mesh_
const volScalarField & rho_
const volVectorField & U_
const surfaceScalarField & phi_
const fluidThermo & thermophysicalModel_
nearWallDist y_
Near wall distance boundary field.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Abstract base class for compressible turbulence models (RAS, LES and laminar).
Source files
turbulenceModel.H
turbulenceModel.C
Definition at line 70 of file turbulenceModel.H.
Constructor & Destructor Documentation
turbulenceModel()
turbulenceModel (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const fluidThermo & thermoPhysicalModel, const word & turbulenceModelName = typeName)
Construct from components.
~turbulenceModel()
virtual ~turbulenceModel () inline virtual
Destructor.
Definition at line 154 of file turbulenceModel.H.
References turbulenceModel::coeffDict().
Member Function Documentation
TypeName()
TypeName ("turbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable()
declareRunTimeNewSelectionTable (autoPtr , turbulenceModel , turbulenceModel , (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const fluidThermo &thermoPhysicalModel, const word &turbulenceModelName) , (rho, U, phi, thermoPhysicalModel, turbulenceModelName))
New()
autoPtr< turbulenceModel > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const fluidThermo & thermoPhysicalModel, const word & turbulenceModelName = typeName) static
Return a reference to the selected turbulence model.
Definition at line 80 of file turbulenceModel.C.
References TimePaths::constant(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), IOobject::MUST_READ_IF_MODIFIED, Foam::nl, IOobject::NO_WRITE, phi, rho, IOobject::time(), and U.
coeffDict()
virtual const dictionary& coeffDict () const pure virtual
Const access to the coefficients dictionary.
Implemented in RASModel, LESModel, and laminar.
Referenced by turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), and turbulenceModel::~turbulenceModel().
GName()
word GName () const inline
Helper function to return the nam eof the turbulence G field.
Definition at line 164 of file turbulenceModel.H.
References Foam::type().
Referenced by lowReOneEqEddy::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), v2f::correct(), kOmegaSST::correct(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
rho()
const volScalarField& rho () const inline
Access function to density field.
Definition at line 170 of file turbulenceModel.H.
References turbulenceModel::rho_.
Referenced by GenEddyVisc::B(), SpalartAllmaras::B(), mutkWallFunctionFvPatchScalarField::calcMut(), mutkFilmWallFunctionFvPatchScalarField::calcMut(), mutUSpaldingWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::calcMut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUWallFunctionFvPatchScalarField::calcYPlus(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), DeardorffDiffStress::correct(), lowReOneEqEddy::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), SpalartAllmaras::correct(), GenSGSStress::devRhoBeff(), GenSGSStress::divDevRhoBeff(), SpalartAllmaras::epsilon(), kOmegaSST::gamma(), SpalartAllmaras::k(), LESModel::New(), RASModel::New(), v2WallFunctionFvPatchScalarField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), mutkWallFunctionFvPatchScalarField::yPlus(), mutLowReWallFunctionFvPatchScalarField::yPlus(), mutkFilmWallFunctionFvPatchScalarField::yPlus(), and mutUSpaldingWallFunctionFvPatchScalarField::yPlus().
U()
const volVectorField& U () const inline
Access function to velocity field.
Definition at line 176 of file turbulenceModel.H.
References turbulenceModel::U_.
Referenced by GenEddyVisc::alphaSgs(), SpalartAllmaras::alphat(), GenEddyVisc::B(), GenSGSStress::B(), SpalartAllmaras::B(), mutUWallFunctionFvPatchScalarField::calcMut(), mutkFilmWallFunctionFvPatchScalarField::calcMut(), mutUSpaldingWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::calcMut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), GenEddyVisc::devRhoBeff(), SpalartAllmaras::devRhoBeff(), GenSGSStress::devRhoBeff(), SpalartAllmaras::epsilon(), kEpsilon::epsilon(), RNGkEpsilon::epsilon(), realizableKE::epsilon(), LaunderSharmaKE::epsilon(), v2f::f(), kOmegaSST::gamma(), Smagorinsky::k(), turbulenceModel::New(), LESModel::New(), RASModel::New(), LRR::R(), LaunderGibsonRSTM::R(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), mutLowReWallFunctionFvPatchScalarField::yPlus(), mutUWallFunctionFvPatchScalarField::yPlus(), mutkFilmWallFunctionFvPatchScalarField::yPlus(), mutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and mutURoughWallFunctionFvPatchScalarField::yPlus().
phi()
const surfaceScalarField& phi () const inline
Access function to flux field.
Definition at line 182 of file turbulenceModel.H.
References turbulenceModel::phi_.
Referenced by DeardorffDiffStress::correct(), lowReOneEqEddy::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), SpalartAllmaras::correct(), kOmegaSST::gamma(), turbulenceModel::New(), LESModel::New(), and RASModel::New().
thermo()
const fluidThermo& thermo () const inline
Access function to thermophysical model.
Definition at line 188 of file turbulenceModel.H.
References turbulenceModel::thermophysicalModel_.
Referenced by LESModel::alphaEff(), RASModel::alphaEff(), LESModel::kappaEff(), RASModel::kappaEff(), laminar::muEff(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
y()
const nearWallDist& y () const inline
Return the near wall distances.
Definition at line 194 of file turbulenceModel.H.
References turbulenceModel::y_.
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::calcMut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUWallFunctionFvPatchScalarField::calcYPlus(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), SpalartAllmaras::correct(), SpalartAllmaras::LESRegion(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), mutLowReWallFunctionFvPatchScalarField::yPlus(), mutkWallFunctionFvPatchScalarField::yPlus(), mutkFilmWallFunctionFvPatchScalarField::yPlus(), and mutUSpaldingWallFunctionFvPatchScalarField::yPlus().
mu()
const volScalarField& mu () const inline
Return the laminar viscosity.
Definition at line 200 of file turbulenceModel.H.
References fluidThermo::mu().
Referenced by mutkWallFunctionFvPatchScalarField::calcMut(), mutUWallFunctionFvPatchScalarField::calcMut(), mutkFilmWallFunctionFvPatchScalarField::calcMut(), mutUSpaldingWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), mutURoughWallFunctionFvPatchScalarField::calcMut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), mutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), mutUWallFunctionFvPatchScalarField::calcYPlus(), mutURoughWallFunctionFvPatchScalarField::calcYPlus(), SpalartAllmaras::chi(), SpalartAllmaras::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), DeardorffDiffStress::DBEff(), kEpsilon::DepsilonEff(), LRR::DepsilonEff(), RNGkEpsilon::DepsilonEff(), LaunderSharmaKE::DepsilonEff(), realizableKE::DepsilonEff(), LaunderGibsonRSTM::DepsilonEff(), v2f::DepsilonEff(), GenSGSStress::devRhoBeff(), laminar::devRhoReff(), LRR::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), GenSGSStress::divDevRhoBeff(), LRR::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), lowReOneEqEddy::DkEff(), oneEqEddy::DkEff(), kEpsilon::DkEff(), homogeneousDynOneEqEddy::DkEff(), RNGkEpsilon::DkEff(), realizableKE::DkEff(), LaunderSharmaKE::DkEff(), v2f::DkEff(), kOmegaSST::DkEff(), SpalartAllmaras::DnuTildaEff(), kOmegaSST::DomegaEff(), LRR::DREff(), LaunderGibsonRSTM::DREff(), kOmegaSST::F1(), LaunderSharmaKE::f2(), kOmegaSST::F2(), kOmegaSST::F3(), LaunderSharmaKE::fMu(), v2f::Ls(), laminar::muEff(), LESModel::muEff(), RASModel::muEff(), laminar::mut(), v2f::Ts(), v2WallFunctionFvPatchScalarField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), mutLowReWallFunctionFvPatchScalarField::yPlus(), mutkWallFunctionFvPatchScalarField::yPlus(), mutkFilmWallFunctionFvPatchScalarField::yPlus(), and mutUSpaldingWallFunctionFvPatchScalarField::yPlus().
alpha()
const volScalarField& alpha () const inline
Return the laminar thermal conductivity.
Definition at line 206 of file turbulenceModel.H.
References basicThermo::alpha(), turbulenceModel::alphat(), turbulenceModel::muEff(), and turbulenceModel::mut().
Referenced by laminar::alphat(), v2f::correct(), laminar::muEff(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
mut()
virtual tmp<volScalarField> mut () const pure virtual
Return the turbulence viscosity.
Implemented in LESModel, kOmegaSST, v2f, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, RNGkEpsilon, LRR, kEpsilon, laminar, and laminar.
Referenced by turbulenceModel::alpha(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), and RASModel::muEff().
muEff()
virtual tmp<volScalarField> muEff () const pure virtual
Return the effective viscosity.
Implemented in RASModel, LESModel, laminar, and laminar.
Referenced by turbulenceModel::alpha().
alphat() [1/2]
virtual tmp<volScalarField> alphat () const pure virtual
Return the turbulence thermal diffusivity.
Implemented in LESModel, kOmegaSST, v2f, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, RNGkEpsilon, LRR, kEpsilon, laminar, and laminar.
Referenced by turbulenceModel::alpha(), RASModel::alphaEff(), turbulenceModel::alphat(), and RASModel::kappaEff().
alphat() [2/2]
virtual tmp<scalarField> alphat (const label patchI) const inline virtual
Return the turbulence thermal diffusivity for a patch.
Definition at line 221 of file turbulenceModel.H.
References turbulenceModel::alphaEff(), turbulenceModel::alphat(), boundaryField(), turbulenceModel::correct(), turbulenceModel::devRhoReff(), turbulenceModel::divDevRhoReff(), turbulenceModel::epsilon(), turbulenceModel::k(), turbulenceModel::kappaEff(), turbulenceModel::R(), turbulenceModel::read(), and turbulenceModel::rhoEpsilonEff().
kappaEff() [1/2]
virtual tmp<volScalarField> kappaEff () const pure virtual
Return the effective turbulence temperature diffusivity.
Implemented in RASModel, LESModel, and laminar.
Referenced by turbulenceModel::alphat().
kappaEff() [2/2]
virtual tmp<scalarField> kappaEff (const label patchI) const pure virtual
Return the effective turbulence temperature diffusivity for a patch.
Implemented in RASModel, LESModel, and laminar.
alphaEff() [1/2]
virtual tmp<volScalarField> alphaEff () const pure virtual
Return the effective turbulence thermal diffusivity.
Implemented in RASModel, LESModel, laminar, and laminar.
Referenced by turbulenceModel::alphat(), and convectiveHeatTransferFvPatchScalarField::updateCoeffs().
alphaEff() [2/2]
virtual tmp<scalarField> alphaEff (const label patchI) const pure virtual
Return the effective turbulence thermal diffusivity for a patch.
Implemented in RASModel, LESModel, and laminar.
k()
virtual tmp<volScalarField> k () const pure virtual
Return the turbulence kinetic energy.
Implemented in kOmegaSST, v2f, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, RNGkEpsilon, LRR, kEpsilon, SpalartAllmaras, laminar, homogeneousDynOneEqEddy, Smagorinsky, oneEqEddy, lowReOneEqEddy, GenSGSStress, and laminar.
Referenced by turbulenceModel::alphat(), GenEddyVisc::B(), mutkWallFunctionFvPatchScalarField::calcMut(), mutkRoughWallFunctionFvPatchScalarField::calcMut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), mutkFilmWallFunctionFvPatchScalarField::calcUTau(), GenEddyVisc::epsilon(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and mutkWallFunctionFvPatchScalarField::yPlus().
epsilon()
virtual tmp<volScalarField> epsilon () const pure virtual
Return the turbulence kinetic energy dissipation rate.
Implemented in kOmegaSST, v2f, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, RNGkEpsilon, LRR, kEpsilon, SpalartAllmaras, laminar, GenSGSStress, GenEddyVisc, and laminar.
Referenced by turbulenceModel::alphat().
rhoEpsilonEff()
tmp< volScalarField > rhoEpsilonEff () const virtual
Return the laminar+turbulence kinetic energy dissipation rate.
Used as the viscous contribution to the energy equations
Definition at line 134 of file turbulenceModel.C.
References Foam::dev(), epsilon, Foam::fvc::grad(), Foam::constant::physicoChemical::mu, and Foam::twoSymm().
Referenced by turbulenceModel::alphat().
R()
virtual tmp<volSymmTensorField> R () const pure virtual
Return the Reynolds stress tensor.
Implemented in kOmegaSST, LESModel, v2f, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, RNGkEpsilon, LRR, kEpsilon, laminar, and laminar.
Referenced by turbulenceModel::alphat().
devRhoReff()
virtual tmp<volSymmTensorField> devRhoReff () const pure virtual
Return the effective stress tensor including the laminar stress.
Implemented in kOmegaSST, LESModel, v2f, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, LRR, RNGkEpsilon, kEpsilon, laminar, and laminar.
Referenced by turbulenceModel::alphat(), and forces::devRhoReff().
divDevRhoReff()
virtual tmp<fvVectorMatrix> divDevRhoReff (volVectorField & U) const pure virtual
Return the source term for the momentum equation.
Referenced by turbulenceModel::alphat().
correct()
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implemented in kOmegaSST, LESModel, v2f, RASModel, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, LRR, RNGkEpsilon, kEpsilon, laminar, laminar, and PDRkEpsilon.
Definition at line 141 of file turbulenceModel.C.
Referenced by turbulenceModel::alphat(), laminar::correct(), RASModel::correct(), and LESModel::correct().
read()
virtual bool read () pure virtual
Read LESProperties or RASProperties dictionary.
Reimplemented from regIOobject.
Implemented in kOmegaSST, LESModel, v2f, RASModel, SpalartAllmaras, LaunderGibsonRSTM, LaunderSharmaKE, realizableKE, LRR, RNGkEpsilon, kEpsilon, GenSGSStress, SpalartAllmaras, laminar, GenEddyVisc, homogeneousDynOneEqEddy, oneEqEddy, Smagorinsky, lowReOneEqEddy, DeardorffDiffStress, laminar, and PDRkEpsilon.
Referenced by turbulenceModel::alphat().
writeData()
virtual bool writeData (Ostream &) const inline virtual
Default dummy write function.
Implements regIOobject.
Definition at line 264 of file turbulenceModel.H.
Member Data Documentation
runTime_
const Time& runTime_ protected
Definition at line 79 of file turbulenceModel.H.
Referenced by laminar::alphat(), GenSGSStress::devRhoBeff(), laminar::devRhoReff(), kEpsilon::devRhoReff(), LRR::devRhoReff(), RNGkEpsilon::devRhoReff(), LaunderSharmaKE::devRhoReff(), realizableKE::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), SpalartAllmaras::devRhoReff(), v2f::devRhoReff(), kOmegaSST::devRhoReff(), laminar::epsilon(), GenEddyVisc::epsilon(), GenSGSStress::epsilon(), SpalartAllmaras::epsilon(), laminar::k(), GenSGSStress::k(), SpalartAllmaras::k(), laminar::mut(), laminar::R(), kEpsilon::R(), RNGkEpsilon::R(), LaunderSharmaKE::R(), realizableKE::R(), SpalartAllmaras::R(), v2f::R(), and kOmegaSST::R().
mesh_
const fvMesh& mesh_ protected
Definition at line 80 of file turbulenceModel.H.
Referenced by laminar::alphat(), SpalartAllmaras::correct(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), realizableKE::correct(), LaunderSharmaKE::correct(), LaunderGibsonRSTM::correct(), turbulenceModel::correct(), v2f::correct(), kOmegaSST::correct(), GenSGSStress::devRhoBeff(), laminar::devRhoReff(), kEpsilon::devRhoReff(), RNGkEpsilon::devRhoReff(), LRR::devRhoReff(), realizableKE::devRhoReff(), LaunderSharmaKE::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), SpalartAllmaras::devRhoReff(), v2f::devRhoReff(), kOmegaSST::devRhoReff(), laminar::epsilon(), GenEddyVisc::epsilon(), GenSGSStress::epsilon(), SpalartAllmaras::epsilon(), kOmegaSST::epsilon(), SpalartAllmaras::fv3(), laminar::k(), GenSGSStress::k(), SpalartAllmaras::k(), LESModel::LESModel(), SpalartAllmaras::LESRegion(), laminar::mut(), laminar::R(), kEpsilon::R(), RNGkEpsilon::R(), LaunderSharmaKE::R(), realizableKE::R(), SpalartAllmaras::R(), v2f::R(), kOmegaSST::R(), and RASModel::RASModel().
rho_
const volScalarField& rho_ protected
Definition at line 82 of file turbulenceModel.H.
Referenced by SpalartAllmaras::chi(), kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), SpalartAllmaras::correct(), v2f::correct(), kOmegaSST::correct(), LRR::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), LRR::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), SpalartAllmaras::DnuTildaEff(), kOmegaSST::F1(), LaunderSharmaKE::f2(), kOmegaSST::F2(), kOmegaSST::F3(), LaunderSharmaKE::fMu(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), v2f::Ls(), kEpsilon::R(), RNGkEpsilon::R(), realizableKE::R(), LaunderSharmaKE::R(), SpalartAllmaras::R(), v2f::R(), kOmegaSST::R(), turbulenceModel::rho(), v2f::Ts(), and v2f::v2f().
U_
const volVectorField& U_ protected
Definition at line 83 of file turbulenceModel.H.
Referenced by kEpsilon::correct(), LRR::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), SpalartAllmaras::correct(), v2f::correct(), LESModel::correct(), kOmegaSST::correct(), laminar::devRhoReff(), kEpsilon::devRhoReff(), LRR::devRhoReff(), RNGkEpsilon::devRhoReff(), LaunderSharmaKE::devRhoReff(), realizableKE::devRhoReff(), LaunderGibsonRSTM::devRhoReff(), SpalartAllmaras::devRhoReff(), v2f::devRhoReff(), kOmegaSST::devRhoReff(), laminar::epsilon(), laminar::k(), kOmegaSST::kOmegaSST(), laminar::R(), kEpsilon::R(), RNGkEpsilon::R(), realizableKE::R(), LaunderSharmaKE::R(), SpalartAllmaras::R(), v2f::R(), kOmegaSST::R(), and turbulenceModel::U().
phi_
const surfaceScalarField& phi_ protected
Definition at line 84 of file turbulenceModel.H.
Referenced by kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), SpalartAllmaras::correct(), v2f::correct(), kOmegaSST::correct(), and turbulenceModel::phi().
thermophysicalModel_
const fluidThermo& thermophysicalModel_ protected
Definition at line 86 of file turbulenceModel.H.
Referenced by turbulenceModel::thermo().
y_
nearWallDist y_ protected
Near wall distance boundary field.
Definition at line 89 of file turbulenceModel.H.
Referenced by turbulenceModel::correct(), and turbulenceModel::y().
The documentation for this class was generated from the following files:
src/turbulenceModels/compressible/turbulenceModel/turbulenceModel.H
src/turbulenceModels/compressible/turbulenceModel/turbulenceModel.C