OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
atmBoundaryLayerInletKFvPatchScalarField Class Reference
Incompressible turbulence » Incompressible RAS turbulence » RAS incompressible boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition specifies an inlet value for the turbulence kinetic energy, , appropriate for atmospheric boundary layers.
Public Member Functions
TypeName ("atmBoundaryLayerInletK")
Runtime type information.
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer ()
Construct null.
atmBoundaryLayer (const vectorField &p, const dictionary &)
Construct from the coordinates field and dictionary.
atmBoundaryLayer (const atmBoundaryLayer &, const fvPatchFieldMapper &)
Construct by mapping given.
atmBoundaryLayer (const atmBoundaryLayer &)
Construct as copy.
const vector & flowDir () const
Return flow direction.
const vector & zDir () const
Return z-direction.
const scalarField & Ustar () const
Return friction velocity.
void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
void rmap (const atmBoundaryLayer &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
tmp< vectorField > U (const vectorField &p) const
Return the velocity distribution for the ATM.
tmp< scalarField > k (const vectorField &p) const
Return the turbulent kinetic energy distribution for the ATM.
tmp< scalarField > epsilon (const vectorField &p) const
Return the turbulent dissipation rate distribution for the ATM.
void write (Ostream &) const
Write.
Detailed Description
This boundary condition specifies an inlet value for the turbulence kinetic energy, , appropriate for atmospheric boundary layers.
See Foam::incompressible::atmBoundaryLayer for details.
Example of the boundary condition specification:
ground
{
    type            atmBoundaryLayerInletK;
    z               (0 0 1);
    Uref            10.0;
    Zref            20.0;
    z0              uniform 0.1;
    zGround         uniform 0.0;
}
See also
Foam::incompressible::atmBoundaryLayer, Foam::incompressible::atmBoundaryLayerInletVelocityFvPatchVectorField, Foam::incompressible::atmBoundaryLayerInletEpsilonFvPatchScalarField
Source files
atmBoundaryLayerInletKFvPatchScalarField.H
atmBoundaryLayerInletKFvPatchScalarField.C
Definition at line 76 of file atmBoundaryLayerInletKFvPatchScalarField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletKFvPatchScalarField() [1/4]
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 43 of file atmBoundaryLayerInletKFvPatchScalarField.C.
Referenced by atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), and atmBoundaryLayerInletKFvPatchScalarField::clone().
atmBoundaryLayerInletKFvPatchScalarField() [2/4]
atmBoundaryLayerInletKFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 55 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), k, and Field< scalar >::operator=().
atmBoundaryLayerInletKFvPatchScalarField() [3/4]
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
atmBoundaryLayerInletKFvPatchScalarField onto a new patch
Definition at line 70 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField().
atmBoundaryLayerInletKFvPatchScalarField() [4/4]
atmBoundaryLayerInletKFvPatchScalarField (const atmBoundaryLayerInletKFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 84 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayerInletKFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletK")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 116 of file atmBoundaryLayerInletKFvPatchScalarField.H.
References atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 133 of file atmBoundaryLayerInletKFvPatchScalarField.H.
References atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), atmBoundaryLayerInletKFvPatchScalarField::autoMap(), atmBoundaryLayerInletKFvPatchScalarField::rmap(), and atmBoundaryLayerInletKFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 97 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayer::autoMap(), and atmBoundaryLayerInletKFvPatchScalarField::rmap().
Referenced by atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), and atmBoundaryLayerInletKFvPatchScalarField::clone().
rmap()
void rmap (const fvPatchScalarField & psf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 107 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References atmBoundaryLayer::rmap().
Referenced by atmBoundaryLayerInletKFvPatchScalarField::autoMap(), and atmBoundaryLayerInletKFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 121 of file atmBoundaryLayerInletKFvPatchScalarField.C.
References Foam::incompressible::makePatchTypeField(), atmBoundaryLayer::write(), and fvPatchField< Type >::write().
Referenced by atmBoundaryLayerInletKFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/RAS/derivedFvPatchFields/atmBoundaryLayerInletK/atmBoundaryLayerInletKFvPatchScalarField.H
src/turbulenceModels/incompressible/RAS/derivedFvPatchFields/atmBoundaryLayerInletK/atmBoundaryLayerInletKFvPatchScalarField.C