OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IDDESDelta Class Reference
IDDESDelta used by the IDDES (improved low Re Spalart-Allmaras DES model) The min and max delta are calculated using the double distance of the min or max from the face centre to the cell centre.
Public Member Functions
TypeName ("IDDESDelta")
Runtime type information.
IDDESDelta (const word &name, const fvMesh &mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
~IDDESDelta ()
void read (const dictionary &)
Read the LESdelta dictionary.
void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes inherited from LESdelta
const fvMesh & mesh_
volScalarField delta_
Detailed Description
IDDESDelta used by the IDDES (improved low Re Spalart-Allmaras DES model) The min and max delta are calculated using the double distance of the min or max from the face centre to the cell centre.
Source files
IDDESDelta.H
IDDESDelta.C
Definition at line 50 of file IDDESDelta.H.
Constructor & Destructor Documentation
IDDESDelta()
IDDESDelta (const word & name, const fvMesh & mesh, const dictionary & dd)
Construct from name, mesh and IOdictionary.
Definition at line 132 of file IDDESDelta.C.
References dictionary::readIfPresent(), dictionary::subDict(), and Foam::type().
~IDDESDelta()
~IDDESDelta () inline
Definition at line 90 of file IDDESDelta.H.
References IDDESDelta::correct(), and IDDESDelta::read().
Member Function Documentation
TypeName()
TypeName ("IDDESDelta")
Runtime type information.
read()
void read (const dictionary & dd) virtual
Read the LESdelta dictionary.
Implements LESdelta.
Definition at line 150 of file IDDESDelta.C.
References dictionary::lookup(), dictionary::subDict(), and Foam::type().
Referenced by IDDESDelta::~IDDESDelta().
correct()
void correct () virtual
Implements LESdelta.
Definition at line 157 of file IDDESDelta.C.
Referenced by IDDESDelta::~IDDESDelta().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/LES/SpalartAllmarasIDDES/IDDESDelta/IDDESDelta.H
src/turbulenceModels/incompressible/LES/SpalartAllmarasIDDES/IDDESDelta/IDDESDelta.C