OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentHeatFluxTemperatureFvPatchScalarField Class Reference
Incompressible turbulence » Incompressible RAS turbulence » RAS incompressible boundary conditionsBoundary Conditions » | Wall boundary Conditions
Fixed heat boundary condition to specify temperature gradient. Input heat source either specified in terms of an absolute power [W], or as a flux [W/m^2].
Public Types
enum heatSourceType { hsPower, hsFlux }
Enumeration listing the possible hest source input modes.
Public Member Functions
TypeName ("turbulentHeatFluxTemperature")
Runtime type information.
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Fixed heat boundary condition to specify temperature gradient. Input heat source either specified in terms of an absolute power [W], or as a flux [W/m^2].
Patch usage
Property Description Required Default value
heatSource heat source type: flux [W/m^2] or power [W] yes
q heat source value yes
alphaEff turbulent thermal diffusivity field name yes
Example of the boundary condition specification:
    myPatch
    {
        type            turbulentHeatFluxTemperature;
        heatSource      flux;
        q               uniform 10;
        alphaEff        alphaEff;
        value           uniform 300; // place holder
    }
Note
The units of alphaEff are [kg/m/s]
The density*specific heat capacity rhoCp0 (units [kg/m^3]*[J/kg/K]) is read from the transport dictionary entry
Source files
turbulentHeatFluxTemperatureFvPatchScalarField.H
turbulentHeatFluxTemperatureFvPatchScalarField.C
Definition at line 103 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
Member Enumeration Documentation
heatSourceType
enum heatSourceType
Enumeration listing the possible hest source input modes.
Enumerator
hsPower
hsFlux
Definition at line 112 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentHeatFluxTemperatureFvPatchScalarField() [1/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 73 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone(), NamedEnum< directionType, 3 >::names(), and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [2/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 103 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References dict, dictionary::found(), fvPatchField< Type >::operator=(), fvPatch::size(), and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [3/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentHeatFluxTemperatureFvPatchScalarField onto a new patch
Definition at line 87 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [4/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField & thftpsf)
Construct as copy.
Definition at line 129 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
turbulentHeatFluxTemperatureFvPatchScalarField() [5/5]
turbulentHeatFluxTemperatureFvPatchScalarField (const turbulentHeatFluxTemperatureFvPatchScalarField & thftpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 142 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("turbulentHeatFluxTemperature")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 177 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
References turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 194 of file turbulentHeatFluxTemperatureFvPatchScalarField.H.
References turbulentHeatFluxTemperatureFvPatchScalarField::autoMap(), turbulentHeatFluxTemperatureFvPatchScalarField::rmap(), turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField(), turbulentHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), and turbulentHeatFluxTemperatureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 157 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References Field< scalar >::autoMap(), and turbulentHeatFluxTemperatureFvPatchScalarField::rmap().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone(), and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 167 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References turbulentHeatFluxTemperatureFvPatchScalarField::rmap().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::autoMap(), turbulentHeatFluxTemperatureFvPatchScalarField::clone(), and turbulentHeatFluxTemperatureFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 184 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::gSum(), turbulentHeatFluxTemperatureFvPatchScalarField::hsFlux, turbulentHeatFluxTemperatureFvPatchScalarField::hsPower, Foam::nl, Foam::readScalar(), and transportProperties().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 231 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::incompressible::makePatchTypeField(), Foam::nl, write(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by turbulentHeatFluxTemperatureFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/turbulenceModel/derivedFvPatchFields/turbulentHeatFluxTemperature/turbulentHeatFluxTemperatureFvPatchScalarField.H
src/turbulenceModels/incompressible/turbulenceModel/derivedFvPatchFields/turbulentHeatFluxTemperature/turbulentHeatFluxTemperatureFvPatchScalarField.C