OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
laminar Class Reference
Turbulence model for laminar incompressible flow.
Public Member Functions
TypeName ("laminar")
Runtime type information.
laminar (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=turbulenceModel::typeName)
Construct from components.
virtual ~laminar ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity, i.e. 0 for laminar flow.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity, i.e. the laminar viscosity.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate,.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
virtual tmp< volSymmTensorField > devReff () const
Return the effective stress tensor, i.e. the laminar stress.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()
Correct the laminar viscosity.
virtual bool read ()
Read turbulenceProperties dictionary.
Public Member Functions inherited from turbulenceModel
TypeName ("turbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr, turbulenceModel, turbulenceModel,(const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName),(U, phi, transport, turbulenceModelName))
turbulenceModel (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=typeName)
Construct from components.
virtual ~turbulenceModel ()
Destructor.
word GName () const
Helper function to return the nam eof the turbulence G field.
const volVectorField & U () const
Access function to velocity field.
const surfaceScalarField & phi () const
Access function to flux field.
transportModel & transport () const
Access function to incompressible transport model.
const nearWallDist & y () const
Return the near wall distances.
tmp< volScalarField > nu () const
Return the laminar viscosity.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const =0
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const =0
Return the source term for the momentum equation.
virtual bool writeData (Ostream &) const
Default dummy write function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static autoPtr< laminar > New (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=turbulenceModel::typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from turbulenceModel
static autoPtr< turbulenceModel > New (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from turbulenceModel
const Time & runTime_
const fvMesh & mesh_
const volVectorField & U_
const surfaceScalarField & phi_
transportModel & transportModel_
nearWallDist y_
Near wall distance boundary field.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Turbulence model for laminar incompressible flow.
Source files
laminar.H
laminar.C
Definition at line 50 of file laminar.H.
Constructor & Destructor Documentation
laminar()
laminar (const volVectorField & U, const surfaceScalarField & phi, transportModel & transport, const word & turbulenceModelName = turbulenceModel::typeName)
Construct from components.
Definition at line 50 of file laminar.C.
References laminar::New().
~laminar()
virtual ~laminar () inline virtual
Destructor.
Definition at line 85 of file laminar.H.
References laminar::coeffDict(), laminar::correct(), laminar::devReff(), laminar::divDevReff(), laminar::divDevRhoReff(), laminar::epsilon(), laminar::k(), laminar::nuEff(), laminar::nut(), laminar::R(), laminar::read(), and rho.
Member Function Documentation
TypeName()
TypeName ("laminar")
Runtime type information.
New()
autoPtr< laminar > New (const volVectorField & U, const surfaceScalarField & phi, transportModel & transport, const word & turbulenceModelName = turbulenceModel::typeName) static
Return a reference to the selected turbulence model.
Definition at line 64 of file laminar.C.
Referenced by laminar::laminar().
coeffDict()
const dictionary & coeffDict () const virtual
Const access to the coefficients dictionary.
Implements turbulenceModel.
Definition at line 80 of file laminar.C.
References dictionary::null.
Referenced by laminar::~laminar().
nut()
tmp< volScalarField > nut () const virtual
Return the turbulence viscosity, i.e. 0 for laminar flow.
Implements turbulenceModel.
Definition at line 86 of file laminar.C.
References turbulenceModel::mesh_, IOobject::NO_READ, IOobject::NO_WRITE, turbulenceModel::nu(), turbulenceModel::runTime_, and Time::timeName().
Referenced by laminar::~laminar().
nuEff()
tmp< volScalarField > nuEff () const virtual
Return the effective viscosity, i.e. the laminar viscosity.
Implements turbulenceModel.
Definition at line 107 of file laminar.C.
References turbulenceModel::nu().
Referenced by laminar::divDevReff(), laminar::divDevRhoReff(), and laminar::~laminar().
k()
tmp< volScalarField > k () const virtual
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
Implements turbulenceModel.
Definition at line 113 of file laminar.C.
References DimensionedField< Type, GeoMesh >::dimensions(), turbulenceModel::mesh_, IOobject::NO_READ, IOobject::NO_WRITE, turbulenceModel::runTime_, Foam::sqr(), Time::timeName(), and turbulenceModel::U_.
Referenced by laminar::~laminar().
epsilon()
tmp< volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate,.
i.e. 0 for laminar flow
Implements turbulenceModel.
Definition at line 134 of file laminar.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, turbulenceModel::mesh_, IOobject::NO_READ, IOobject::NO_WRITE, turbulenceModel::runTime_, Foam::sqr(), Time::timeName(), and turbulenceModel::U_.
Referenced by laminar::~laminar().
R()
tmp< volSymmTensorField > R () const virtual
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
Implements turbulenceModel.
Definition at line 158 of file laminar.C.
References DimensionedField< Type, GeoMesh >::dimensions(), turbulenceModel::mesh_, IOobject::NO_READ, IOobject::NO_WRITE, turbulenceModel::runTime_, Foam::sqr(), Time::timeName(), turbulenceModel::U_, and SymmTensor< Cmpt >::zero.
Referenced by laminar::~laminar().
devReff()
tmp< volSymmTensorField > devReff () const virtual
Return the effective stress tensor, i.e. the laminar stress.
Implements turbulenceModel.
Definition at line 182 of file laminar.C.
References Foam::dev(), Foam::fvc::grad(), turbulenceModel::mesh_, IOobject::NO_READ, IOobject::NO_WRITE, turbulenceModel::nu(), turbulenceModel::runTime_, Time::timeName(), Foam::twoSymm(), and turbulenceModel::U_.
Referenced by laminar::~laminar().
divDevReff()
tmp< fvVectorMatrix > divDevReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 202 of file laminar.C.
References Foam::dev(), Foam::fvc::div(), laminar::divDevRhoReff(), Foam::fvc::grad(), Foam::fvm::laplacian(), laminar::nuEff(), and Foam::T().
Referenced by laminar::~laminar().
divDevRhoReff()
tmp< fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 213 of file laminar.C.
References Foam::dev(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvm::laplacian(), muEff(), laminar::nuEff(), and Foam::T().
Referenced by laminar::divDevReff(), and laminar::~laminar().
correct()
void correct () virtual
Correct the laminar viscosity.
Implements turbulenceModel.
Definition at line 228 of file laminar.C.
References turbulenceModel::correct().
Referenced by laminar::~laminar().
read()
bool read () virtual
Read turbulenceProperties dictionary.
Implements turbulenceModel.
Definition at line 234 of file laminar.C.
Referenced by laminar::~laminar().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/turbulenceModel/laminar/laminar.H
src/turbulenceModels/incompressible/turbulenceModel/laminar/laminar.C