OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
RASModel Class Reference
Abstract base class for incompressible turbulence models.
Public Member Functions
TypeName ("RASModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName),(U, phi, transport, turbulenceModelName))
RASModel (const word &type, const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=turbulenceModel::typeName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
virtual bool read ()
Read RASProperties dictionary.
Public Member Functions inherited from turbulenceModel
TypeName ("turbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr, turbulenceModel, turbulenceModel,(const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName),(U, phi, transport, turbulenceModelName))
turbulenceModel (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=typeName)
Construct from components.
virtual ~turbulenceModel ()
Destructor.
word GName () const
Helper function to return the nam eof the turbulence G field.
const volVectorField & U () const
Access function to velocity field.
const surfaceScalarField & phi () const
Access function to flux field.
transportModel & transport () const
Access function to incompressible transport model.
const nearWallDist & y () const
Return the near wall distances.
tmp< volScalarField > nu () const
Return the laminar viscosity.
virtual tmp< volScalarField > nut () const =0
Return the turbulence viscosity.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const =0
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const =0
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devReff () const =0
Return the effective stress tensor including the laminar stress.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const =0
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const =0
Return the source term for the momentum equation.
virtual bool writeData (Ostream &) const
Default dummy write function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Static Public Member Functions
static autoPtr< RASModel > New (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=turbulenceModel::typeName)
Return a reference to the selected RAS model.
Static Public Member Functions inherited from turbulenceModel
static autoPtr< turbulenceModel > New (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Protected Member Functions
virtual void printCoeffs ()
Print model coefficients.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Protected Attributes inherited from turbulenceModel
const Time & runTime_
const fvMesh & mesh_
const volVectorField & U_
const surfaceScalarField & phi_
transportModel & transportModel_
nearWallDist y_
Near wall distance boundary field.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase ::iterator LListBase_iterator
typedef DLListBase ::const_iterator LListBase_const_iterator
typedef DLListBase ::const_reverse_iterator LListBase_const_reverse_iterator
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Abstract base class for incompressible turbulence models.
Source files
RASModel.H
RASModel.C
Definition at line 70 of file RASModel.H.
Constructor & Destructor Documentation
RASModel()
RASModel (const word & type, const volVectorField & U, const surfaceScalarField & phi, transportModel & transport, const word & turbulenceModelName = turbulenceModel::typeName)
Construct from components.
Definition at line 56 of file RASModel.C.
References surfaceInterpolation::deltaCoeffs(), RASModel::epsilonMin_, RASModel::kMin_, turbulenceModel::mesh_, RASModel::New(), RASModel::omegaMin_, and dimensioned< Type >::readIfPresent().
~RASModel()
virtual ~RASModel () inline virtual
Destructor.
Definition at line 165 of file RASModel.H.
Member Function Documentation
printCoeffs()
void printCoeffs () protected virtual
Print model coefficients.
Definition at line 44 of file RASModel.C.
References RASModel::coeffDict_, Foam::endl(), Foam::Info, RASModel::printCoeffs_, and Foam::type().
Referenced by kkLOmega::kkLOmega(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), qZeta::qZeta(), SpalartAllmaras::SpalartAllmaras(), and v2f::v2f().
TypeName()
TypeName ("RASModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , RASModel , dictionary , (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName) , (U, phi, transport, turbulenceModelName))
New()
autoPtr< RASModel > New (const volVectorField & U, const surfaceScalarField & phi, transportModel & transport, const word & turbulenceModelName = turbulenceModel::typeName) static
Return a reference to the selected RAS model.
Definition at line 99 of file RASModel.C.
References TimePaths::constant(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), IOobject::MUST_READ_IF_MODIFIED, Foam::nl, IOobject::NO_WRITE, turbulenceModel::phi(), IOobject::time(), turbulenceModel::transport(), and turbulenceModel::U().
Referenced by RASModel::RASModel().
kMin() [1/2]
const dimensionedScalar& kMin () const inline
Return the lower allowable limit for k (default: SMALL)
Definition at line 174 of file RASModel.H.
References RASModel::kMin_.
epsilonMin() [1/2]
const dimensionedScalar& epsilonMin () const inline
Return the lower allowable limit for epsilon (default: SMALL)
Definition at line 180 of file RASModel.H.
References RASModel::epsilonMin_.
omegaMin() [1/2]
const dimensionedScalar& omegaMin () const inline
Return the lower allowable limit for omega (default: SMALL)
Definition at line 186 of file RASModel.H.
References RASModel::omegaMin_.
kMin() [2/2]
dimensionedScalar& kMin () inline
Allow kMin to be changed.
Definition at line 192 of file RASModel.H.
References RASModel::kMin_.
epsilonMin() [2/2]
dimensionedScalar& epsilonMin () inline
Allow epsilonMin to be changed.
Definition at line 198 of file RASModel.H.
References RASModel::epsilonMin_.
omegaMin() [2/2]
dimensionedScalar& omegaMin () inline
Allow omegaMin to be changed.
Definition at line 204 of file RASModel.H.
References RASModel::omegaMin_.
coeffDict()
virtual const dictionary& coeffDict () const inline virtual
Const access to the coefficients dictionary.
Implements turbulenceModel.
Definition at line 210 of file RASModel.H.
References RASModel::coeffDict_.
Referenced by LamBremhorstKE::read(), LienLeschzinerLowRe::read(), LienCubicKE::read(), NonlinearKEShih::read(), LaunderSharmaKE::read(), kEpsilon::read(), RNGkEpsilon::read(), LRR::read(), realizableKE::read(), LaunderGibsonRSTM::read(), LienCubicKELowRe::read(), kOmega::read(), SpalartAllmaras::read(), qZeta::read(), v2f::read(), kOmegaSST::read(), and kkLOmega::read().
nuEff()
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Implements turbulenceModel.
Reimplemented in laminar.
Definition at line 217 of file RASModel.H.
References RASModel::correct(), turbulenceModel::nu(), turbulenceModel::nut(), and RASModel::read().
Referenced by LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), realizableKE::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), LamBremhorstKE::divDevReff(), LienLeschzinerLowRe::divDevReff(), LienCubicKE::divDevReff(), NonlinearKEShih::divDevReff(), LaunderSharmaKE::divDevReff(), kEpsilon::divDevReff(), RNGkEpsilon::divDevReff(), LRR::divDevReff(), realizableKE::divDevReff(), LaunderGibsonRSTM::divDevReff(), LienCubicKELowRe::divDevReff(), kOmega::divDevReff(), SpalartAllmaras::divDevReff(), qZeta::divDevReff(), v2f::divDevReff(), kOmegaSST::divDevReff(), kkLOmega::divDevReff(), LamBremhorstKE::divDevRhoReff(), LienLeschzinerLowRe::divDevRhoReff(), LienCubicKE::divDevRhoReff(), NonlinearKEShih::divDevRhoReff(), LaunderSharmaKE::divDevRhoReff(), kEpsilon::divDevRhoReff(), RNGkEpsilon::divDevRhoReff(), LRR::divDevRhoReff(), realizableKE::divDevRhoReff(), LaunderGibsonRSTM::divDevRhoReff(), LienCubicKELowRe::divDevRhoReff(), kOmega::divDevRhoReff(), SpalartAllmaras::divDevRhoReff(), qZeta::divDevRhoReff(), v2f::divDevRhoReff(), kOmegaSST::divDevRhoReff(), and kkLOmega::divDevRhoReff().
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements turbulenceModel.
Reimplemented in kkLOmega, kOmegaSST, v2f, qZeta, SpalartAllmaras, kOmega, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, RNGkEpsilon, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, and laminar.
Definition at line 156 of file RASModel.C.
References turbulenceModel::correct().
Referenced by LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), kOmega::correct(), SpalartAllmaras::correct(), qZeta::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), and RASModel::nuEff().
read()
bool read () virtual
Read RASProperties dictionary.
Implements turbulenceModel.
Reimplemented in kkLOmega, kOmegaSST, v2f, qZeta, SpalartAllmaras, kOmega, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, RNGkEpsilon, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, and laminar.
Definition at line 162 of file RASModel.C.
References regIOobject::close(), RASModel::coeffDict_, RASModel::epsilonMin_, RASModel::kMin_, dictionary::lookup(), RASModel::omegaMin_, IOdictionary::readData(), dimensioned< Type >::readIfPresent(), dictionary::subDictPtr(), RASModel::turbulence_, and Foam::type().
Referenced by RASModel::nuEff(), laminar::read(), LamBremhorstKE::read(), LienLeschzinerLowRe::read(), LienCubicKE::read(), NonlinearKEShih::read(), LaunderSharmaKE::read(), kEpsilon::read(), RNGkEpsilon::read(), LRR::read(), realizableKE::read(), LaunderGibsonRSTM::read(), LienCubicKELowRe::read(), kOmega::read(), SpalartAllmaras::read(), qZeta::read(), v2f::read(), kOmegaSST::read(), and kkLOmega::read().
Member Data Documentation
turbulence_
Switch turbulence_ protected
Turbulence on/off flag.
Definition at line 81 of file RASModel.H.
Referenced by LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), kOmega::correct(), SpalartAllmaras::correct(), qZeta::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), and RASModel::read().
printCoeffs_
Switch printCoeffs_ protected
Flag to print the model coeffs at run-time.
Definition at line 84 of file RASModel.H.
Referenced by RASModel::printCoeffs().
coeffDict_
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 87 of file RASModel.H.
Referenced by RASModel::coeffDict(), RASModel::printCoeffs(), and RASModel::read().
kMin_
dimensionedScalar kMin_ protected
Lower limit of k.
Definition at line 90 of file RASModel.H.
Referenced by LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), kOmega::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), kkLOmega::kkLOmega(), RASModel::kMin(), kOmegaSST::kOmegaSST(), LaunderSharmaKE::LaunderSharmaKE(), qZeta::qZeta(), RASModel::RASModel(), RASModel::read(), and v2f::v2f().
epsilonMin_
dimensionedScalar epsilonMin_ protected
Lower limit of epsilon.
Definition at line 93 of file RASModel.H.
Referenced by LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), v2f::correct(), kkLOmega::correct(), RASModel::epsilonMin(), kkLOmega::kkLOmega(), LaunderSharmaKE::LaunderSharmaKE(), qZeta::qZeta(), RASModel::RASModel(), RASModel::read(), and v2f::v2f().
omegaMin_
dimensionedScalar omegaMin_ protected
Lower limit for omega.
Definition at line 96 of file RASModel.H.
Referenced by kOmega::correct(), kOmegaSST::correct(), kkLOmega::correct(), kkLOmega::kkLOmega(), kOmegaSST::kOmegaSST(), RASModel::omegaMin(), RASModel::RASModel(), and RASModel::read().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/RAS/RASModel/RASModel.H
src/turbulenceModels/incompressible/RAS/RASModel/RASModel.C