OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
simpleFilter Class Reference
Simple top-hat filter used in dynamic LES models.
Public Member Functions
TypeName ("simple")
Runtime type information.
simpleFilter (const fvMesh &mesh)
Construct from components.
simpleFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~simpleFilter ()
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
TypeName ("simple")
Runtime type information.
simpleFilter (const fvMesh &mesh)
Construct from components.
simpleFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~simpleFilter ()
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &)
Return a reference to the selected LES filter.
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &)
Return a reference to the selected LES filter.
Detailed Description
Simple top-hat filter used in dynamic LES models.
Implemented as a surface integral of the face interpolate of the field.
Source files
simpleFilter.H
simpleFilter.C
Implemented as a surface integral of the face interpolate of the field.
Source files
simpleFilter.H
simpleFilter.C
Definition at line 50 of file simpleFilter.H.
Constructor & Destructor Documentation
simpleFilter() [1/4]
simpleFilter (const fvMesh & mesh)
Construct from components.
Definition at line 42 of file simpleFilter.C.
simpleFilter() [2/4]
simpleFilter (const fvMesh & mesh, const dictionary &)
Construct from IOdictionary.
Definition at line 50 of file simpleFilter.C.
~simpleFilter() [1/2]
virtual ~simpleFilter () inline virtual
Destructor.
Definition at line 78 of file simpleFilter.H.
References simpleFilter::read().
simpleFilter() [3/4]
simpleFilter (const fvMesh & mesh)
Construct from components.
simpleFilter() [4/4]
simpleFilter (const fvMesh & mesh, const dictionary &)
Construct from IOdictionary.
~simpleFilter() [2/2]
virtual ~simpleFilter () inline virtual
Destructor.
Definition at line 78 of file simpleFilter.H.
References simpleFilter::read().
Member Function Documentation
TypeName() [1/2]
TypeName ("simple")
Runtime type information.
read() [1/2]
void read (const dictionary &) virtual
Read the LESfilter dictionary.
Implements LESfilter.
Definition at line 58 of file simpleFilter.C.
Referenced by simpleFilter::~simpleFilter().
operator()() [1/8]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 65 of file simpleFilter.C.
References Foam::fvc::interpolate(), LESfilter::mesh(), and Foam::fvc::surfaceSum().
operator()() [2/8]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 81 of file simpleFilter.C.
References Foam::fvc::interpolate(), LESfilter::mesh(), and Foam::fvc::surfaceSum().
operator()() [3/8]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 97 of file simpleFilter.C.
References Foam::fvc::interpolate(), LESfilter::mesh(), and Foam::fvc::surfaceSum().
operator()() [4/8]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 113 of file simpleFilter.C.
References Foam::fvc::interpolate(), LESfilter::mesh(), and Foam::fvc::surfaceSum().
TypeName() [2/2]
TypeName ("simple")
Runtime type information.
read() [2/2]
virtual void read (const dictionary &) virtual
Read the LESfilter dictionary.
Implements LESfilter.
operator()() [5/8]
virtual tmp<volScalarField> operator() (const tmp< volScalarField > &) const virtual
Implements LESfilter.
operator()() [6/8]
virtual tmp<volVectorField> operator() (const tmp< volVectorField > &) const virtual
Implements LESfilter.
operator()() [7/8]
virtual tmp<volSymmTensorField> operator() (const tmp< volSymmTensorField > &) const virtual
Implements LESfilter.
operator()() [8/8]
virtual tmp<volTensorField> operator() (const tmp< volTensorField > &) const virtual
Implements LESfilter.
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESfilters/simpleFilter/simpleFilter.H
src/turbulenceModels/LES/LESfilters/simpleFilter/simpleFilter.C