OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LESdelta Class Reference abstract
Abstract base class for LES deltas.
Public Member Functions
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESdelta dictionary.
virtual void correct ()=0
virtual operator const volScalarField & () const
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESdelta dictionary.
virtual void correct ()=0
virtual operator const volScalarField & () const
Static Public Member Functions
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes
const fvMesh & mesh_
volScalarField delta_
Detailed Description
Abstract base class for LES deltas.
Source files
LESdelta.H
LESdelta.C
Source files
LESdelta.H
LESdelta.C
Definition at line 53 of file LESdelta.H.
Constructor & Destructor Documentation
LESdelta() [1/2]
LESdelta (const word & name, const fvMesh & mesh)
Construct from name and mesh.
Definition at line 39 of file LESdelta.C.
References LESdelta::New().
~LESdelta() [1/2]
virtual ~LESdelta () inline virtual
Destructor.
Reimplemented in LESdelta, and LESdelta.
Definition at line 123 of file LESdelta.H.
LESdelta() [2/2]
LESdelta (const word & name, const fvMesh &)
Construct from name and mesh.
~LESdelta() [2/2]
virtual ~LESdelta () inline virtual
Destructor.
Reimplemented in LESdelta, and LESdelta.
Definition at line 123 of file LESdelta.H.
Member Function Documentation
TypeName() [1/2]
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , LESdelta , dictionary , (const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict) , (name, mesh, LESdeltaDict))
New() [1/4]
Foam::autoPtr< Foam::LESdelta > New (const word & name, const fvMesh & mesh, const dictionary & dict) static
Return a reference to the selected LES delta.
Definition at line 62 of file LESdelta.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), LESdelta::mesh(), Foam::name(), and Foam::nl.
Referenced by LESdelta::LESdelta(), and LESdelta::New().
New() [2/4]
Foam::autoPtr< Foam::LESdelta > New (const word & name, const fvMesh & mesh, const dictionary & dict, const dictionaryConstructorTable & additionalConstructors) static
Return a reference to the selected LES delta.
Definition at line 92 of file LESdelta.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), LESdelta::mesh(), Foam::name(), and Foam::nl.
mesh() [1/2]
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 130 of file LESdelta.H.
References LESdelta::correct(), LESdelta::mesh_, and LESdelta::read().
Referenced by vanDriestDelta::correct(), and LESdelta::New().
read() [1/2]
virtual void read (const dictionary &) pure virtual
Read the LESdelta dictionary.
Implemented in smoothDelta, smoothDelta, IDDESDelta, maxDeltaxyz, maxDeltaxyz, vanDriestDelta, vanDriestDelta, PrandtlDelta, PrandtlDelta, cubeRootVolDelta, and cubeRootVolDelta.
Referenced by LESdelta::mesh().
correct() [1/2]
virtual void correct () pure virtual
Implemented in smoothDelta, smoothDelta, IDDESDelta, maxDeltaxyz, maxDeltaxyz, vanDriestDelta, vanDriestDelta, PrandtlDelta, PrandtlDelta, cubeRootVolDelta, and cubeRootVolDelta.
Referenced by LESdelta::mesh().
operator const volScalarField &() [1/2]
virtual operator const volScalarField & () const inline virtual
Definition at line 144 of file LESdelta.H.
References LESdelta::delta_.
TypeName() [2/2]
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , LESdelta , dictionary , (const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict) , (name, mesh, LESdeltaDict))
New() [3/4]
static autoPtr<LESdelta> New (const word & name, const fvMesh & , const dictionary &) static
Return a reference to the selected LES delta.
New() [4/4]
static autoPtr<LESdelta> New (const word & name, const fvMesh & , const dictionary & , const dictionaryConstructorTable &) static
Return a reference to the selected LES delta.
mesh() [2/2]
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 130 of file LESdelta.H.
References LESdelta::correct(), LESdelta::mesh_, and LESdelta::read().
read() [2/2]
virtual void read (const dictionary &) pure virtual
Read the LESdelta dictionary.
Implemented in smoothDelta, smoothDelta, IDDESDelta, maxDeltaxyz, maxDeltaxyz, vanDriestDelta, vanDriestDelta, PrandtlDelta, PrandtlDelta, cubeRootVolDelta, and cubeRootVolDelta.
correct() [2/2]
virtual void correct () pure virtual
Implemented in smoothDelta, smoothDelta, IDDESDelta, maxDeltaxyz, maxDeltaxyz, vanDriestDelta, vanDriestDelta, PrandtlDelta, PrandtlDelta, cubeRootVolDelta, and cubeRootVolDelta.
operator const volScalarField &() [2/2]
virtual operator const volScalarField & () const inline virtual
Definition at line 144 of file LESdelta.H.
References LESdelta::delta_.
Member Data Documentation
mesh_
const fvMesh & mesh_ protected
Definition at line 60 of file LESdelta.H.
Referenced by cubeRootVolDelta::correct(), PrandtlDelta::correct(), maxDeltaxyz::correct(), smoothDelta::correct(), and LESdelta::mesh().
delta_
volScalarField delta_ protected
Definition at line 62 of file LESdelta.H.
Referenced by LESdelta::operator const volScalarField &(), and vanDriestDelta::vanDriestDelta().
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESdeltas/LESdelta/LESdelta.H
src/turbulenceModels/LES/LESdeltas/LESdelta/LESdelta.C