OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PrandtlDelta Class Reference
Simple cube-root of cell volume delta used in LES models.
Public Member Functions
TypeName ("Prandtl")
Runtime type information.
PrandtlDelta (const word &name, const fvMesh &mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
virtual ~PrandtlDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
TypeName ("Prandtl")
Runtime type information.
PrandtlDelta (const word &name, const fvMesh &mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
virtual ~PrandtlDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes inherited from LESdelta
const fvMesh & mesh_
volScalarField delta_
Detailed Description
Simple cube-root of cell volume delta used in LES models.
Source files
PrandtlDelta.H
PrandtlDelta.C
Source files
PrandtlDelta.H
PrandtlDelta.C
Definition at line 48 of file PrandtlDelta.H.
Constructor & Destructor Documentation
PrandtlDelta() [1/2]
PrandtlDelta (const word & name, const fvMesh & mesh, const dictionary & dd)
Construct from name, mesh and IOdictionary.
Definition at line 56 of file PrandtlDelta.C.
~PrandtlDelta() [1/2]
virtual ~PrandtlDelta () inline virtual
Destructor.
Definition at line 87 of file PrandtlDelta.H.
References PrandtlDelta::correct(), and PrandtlDelta::read().
PrandtlDelta() [2/2]
PrandtlDelta (const word & name, const fvMesh & mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
~PrandtlDelta() [2/2]
virtual ~PrandtlDelta () inline virtual
Destructor.
Definition at line 87 of file PrandtlDelta.H.
References PrandtlDelta::correct(), and PrandtlDelta::read().
Member Function Documentation
TypeName() [1/2]
TypeName ("Prandtl")
Runtime type information.
read() [1/2]
void read (const dictionary & d) virtual
Read the LESdelta dictionary.
Implements LESdelta.
Definition at line 76 of file PrandtlDelta.C.
References dictionary::readIfPresent(), dictionary::subDict(), and Foam::type().
Referenced by PrandtlDelta::~PrandtlDelta().
correct() [1/2]
void correct () virtual
Implements LESdelta.
Definition at line 87 of file PrandtlDelta.C.
References polyMesh::changing(), and LESdelta::mesh_.
Referenced by PrandtlDelta::~PrandtlDelta().
TypeName() [2/2]
TypeName ("Prandtl")
Runtime type information.
read() [2/2]
virtual void read (const dictionary &) virtual
Read the LESdelta dictionary.
Implements LESdelta.
correct() [2/2]
virtual void correct () virtual
Implements LESdelta.
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESdeltas/PrandtlDelta/PrandtlDelta.H
src/turbulenceModels/LES/LESdeltas/PrandtlDelta/PrandtlDelta.C