OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
eddyViscosity< BasicTurbulenceModel > Class Template Reference abstract
Eddy viscosity turbulence model base class.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
virtual bool read ()=0
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Protected Member Functions
virtual void correctNut ()=0
Protected Attributes
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::eddyViscosity< BasicTurbulenceModel >
Eddy viscosity turbulence model base class.
Source files
eddyViscosity.H
eddyViscosity.C
Definition at line 50 of file eddyViscosity.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 71 of file eddyViscosity.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 72 of file eddyViscosity.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 73 of file eddyViscosity.H.
Constructor & Destructor Documentation
eddyViscosity()
eddyViscosity (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 34 of file eddyViscosity.C.
~eddyViscosity()
virtual ~eddyViscosity () inline virtual
Destructor.
Definition at line 93 of file eddyViscosity.H.
Member Function Documentation
correctNut()
virtual void correctNut () protected pure virtual
Implemented in mixtureKEpsilon< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, NicenoKEqn< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, and Smagorinsky< BasicTurbulenceModel >.
read()
bool read () pure virtual
Re-read model coefficients if they have changed.
Implemented in mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, LaheyKEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, NicenoKEqn< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, continuousGasKEqn< BasicTurbulenceModel >, buoyantKEpsilon< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, phasePressureModel, and LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 138 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::~eddyViscosity().
nut() [1/2]
virtual tmp<volScalarField> nut () const inline virtual
Return the turbulence viscosity.
Definition at line 103 of file eddyViscosity.H.
nut() [2/2]
virtual tmp<scalarField> nut (const label patchi) const inline virtual
Return the turbulence viscosity on patch.
Definition at line 109 of file eddyViscosity.H.
k()
virtual tmp<volScalarField> k () const pure virtual
Return the turbulence kinetic energy.
Implemented in mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, kEpsilon< BasicTurbulenceModel >, phasePressureModel, kEqn< BasicTurbulenceModel >, and Smagorinsky< BasicTurbulenceModel >.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
R()
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor.
Reimplemented in kineticTheoryModel, continuousGasKEpsilon< BasicTurbulenceModel >, and phasePressureModel.
Definition at line 76 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
devRhoReff()
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Reimplemented in kineticTheoryModel, and phasePressureModel.
Definition at line 101 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
divDevRhoReff()
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Reimplemented in kineticTheoryModel, and phasePressureModel.
Definition at line 125 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::devRhoReff(), and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
correct()
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implemented in mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, kEpsilon< BasicTurbulenceModel >, phasePressureModel, kEqn< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, and Smagorinsky< BasicTurbulenceModel >.
Definition at line 145 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
Member Data Documentation
nut_
volScalarField nut_ protected
Definition at line 61 of file eddyViscosity.H.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/eddyViscosity/eddyViscosity.H
src/TurbulenceModels/turbulenceModels/eddyViscosity/eddyViscosity.C