OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
laplaceFilter Class Reference
Laplace filter for LES.
Public Member Functions
TypeName ("laplace")
Runtime type information.
laplaceFilter (const fvMesh &mesh, scalar widthCoeff)
Construct from components.
laplaceFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~laplaceFilter ()
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
TypeName ("laplace")
Runtime type information.
laplaceFilter (const fvMesh &mesh, scalar widthCoeff)
Construct from components.
laplaceFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~laplaceFilter ()
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &)
Return a reference to the selected LES filter.
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &)
Return a reference to the selected LES filter.
Detailed Description
Laplace filter for LES.
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
laplaceFilter.H
laplaceFilter.C
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
laplaceFilter.H
laplaceFilter.C
Definition at line 56 of file laplaceFilter.H.
Constructor & Destructor Documentation
laplaceFilter() [1/4]
laplaceFilter (const fvMesh & mesh, scalar widthCoeff)
Construct from components.
Definition at line 43 of file laplaceFilter.C.
References GeometricField< Type, PatchField, GeoMesh >::dimensionedInternalField(), Foam::pow(), and fvMesh::V().
laplaceFilter() [2/4]
laplaceFilter (const fvMesh & mesh, const dictionary & bd)
Construct from IOdictionary.
Definition at line 64 of file laplaceFilter.C.
References GeometricField< Type, PatchField, GeoMesh >::dimensionedInternalField(), Foam::pow(), and fvMesh::V().
~laplaceFilter() [1/2]
virtual ~laplaceFilter () inline virtual
Destructor.
Definition at line 89 of file laplaceFilter.H.
References laplaceFilter::read().
laplaceFilter() [3/4]
laplaceFilter (const fvMesh & mesh, scalar widthCoeff)
Construct from components.
laplaceFilter() [4/4]
laplaceFilter (const fvMesh & mesh, const dictionary &)
Construct from IOdictionary.
~laplaceFilter() [2/2]
virtual ~laplaceFilter () inline virtual
Destructor.
Definition at line 89 of file laplaceFilter.H.
References laplaceFilter::read().
Member Function Documentation
TypeName() [1/2]
TypeName ("laplace")
Runtime type information.
read() [1/2]
void read (const dictionary & bd) virtual
Read the LESfilter dictionary.
Implements LESfilter.
Definition at line 87 of file laplaceFilter.C.
References dictionary::lookup(), dictionary::subDict(), and Foam::type().
Referenced by laplaceFilter::~laplaceFilter().
operator()() [1/8]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 96 of file laplaceFilter.C.
References Foam::fvc::laplacian().
operator()() [2/8]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 110 of file laplaceFilter.C.
References Foam::fvc::laplacian().
operator()() [3/8]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 124 of file laplaceFilter.C.
References Foam::fvc::laplacian().
operator()() [4/8]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 138 of file laplaceFilter.C.
References Foam::fvc::laplacian().
TypeName() [2/2]
TypeName ("laplace")
Runtime type information.
read() [2/2]
virtual void read (const dictionary &) virtual
Read the LESfilter dictionary.
Implements LESfilter.
operator()() [5/8]
virtual tmp<volScalarField> operator() (const tmp< volScalarField > &) const virtual
Implements LESfilter.
operator()() [6/8]
virtual tmp<volVectorField> operator() (const tmp< volVectorField > &) const virtual
Implements LESfilter.
operator()() [7/8]
virtual tmp<volSymmTensorField> operator() (const tmp< volSymmTensorField > &) const virtual
Implements LESfilter.
operator()() [8/8]
virtual tmp<volTensorField> operator() (const tmp< volTensorField > &) const virtual
Implements LESfilter.
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.H
src/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.C