OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LESfilter Class Reference abstract
Abstract class for LES filters.
Public Member Functions
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const =0
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const =0
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const =0
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const =0
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const =0
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const =0
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const =0
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const =0
Static Public Member Functions
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &)
Return a reference to the selected LES filter.
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &)
Return a reference to the selected LES filter.
Detailed Description
Abstract class for LES filters.
Source files
LESfilter.H
LESfilter.C
newFilter.C
Source files
LESfilter.H
LESfilter.C
newFilter.C
Definition at line 54 of file LESfilter.H.
Constructor & Destructor Documentation
LESfilter() [1/2]
LESfilter (const fvMesh & mesh) inline
Construct from components.
Definition at line 92 of file LESfilter.H.
References LESfilter::New().
~LESfilter() [1/2]
virtual ~LESfilter () inline virtual
Destructor.
Definition at line 109 of file LESfilter.H.
LESfilter() [2/2]
LESfilter (const fvMesh & mesh) inline
Construct from components.
Definition at line 92 of file LESfilter.H.
References LESfilter::New().
~LESfilter() [2/2]
virtual ~LESfilter () inline virtual
Destructor.
Definition at line 109 of file LESfilter.H.
Member Function Documentation
TypeName() [1/2]
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , LESfilter , dictionary , (const fvMesh &mesh, const dictionary &LESfilterDict) , (mesh, LESfilterDict))
New() [1/2]
Foam::autoPtr< Foam::LESfilter > New (const fvMesh & mesh, const dictionary & dict) static
Return a reference to the selected LES filter.
Definition at line 41 of file LESfilter.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, dictionary::lookup(), mesh, and Foam::nl.
Referenced by LESfilter::LESfilter().
mesh() [1/2]
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 116 of file LESfilter.H.
References LESfilter::read().
Referenced by simpleFilter::operator()().
read() [1/2]
virtual void read (const dictionary &) pure virtual
Read the LESfilter dictionary.
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
Referenced by LESfilter::mesh(), scaleSimilarity::read(), homogeneousDynOneEqEddy::read(), homogeneousDynSmagorinsky::read(), dynOneEqEddy::read(), and dynLagrangian::read().
operator()() [1/8]
virtual tmp<volScalarField> operator() (const tmp< volScalarField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [2/8]
virtual tmp<volVectorField> operator() (const tmp< volVectorField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [3/8]
virtual tmp<volSymmTensorField> operator() (const tmp< volSymmTensorField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [4/8]
virtual tmp<volTensorField> operator() (const tmp< volTensorField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
TypeName() [2/2]
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , LESfilter , dictionary , (const fvMesh &mesh, const dictionary &LESfilterDict) , (mesh, LESfilterDict))
New() [2/2]
static autoPtr<LESfilter> New (const fvMesh & , const dictionary &) static
Return a reference to the selected LES filter.
mesh() [2/2]
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 116 of file LESfilter.H.
References LESfilter::read().
read() [2/2]
virtual void read (const dictionary &) pure virtual
Read the LESfilter dictionary.
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [5/8]
virtual tmp<volScalarField> operator() (const tmp< volScalarField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [6/8]
virtual tmp<volVectorField> operator() (const tmp< volVectorField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [7/8]
virtual tmp<volSymmTensorField> operator() (const tmp< volSymmTensorField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
operator()() [8/8]
virtual tmp<volTensorField> operator() (const tmp< volTensorField > &) const pure virtual
Implemented in laplaceFilter, laplaceFilter, anisotropicFilter, anisotropicFilter, simpleFilter, and simpleFilter.
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESfilters/LESfilter/LESfilter.H
src/turbulenceModels/LES/LESfilters/LESfilter/LESfilter.C