OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cubeRootVolDelta Class Reference
Simple cube-root of cell volume delta used in LES models.
Public Member Functions
TypeName ("cubeRootVol")
Runtime type information.
cubeRootVolDelta (const word &name, const fvMesh &mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
virtual ~cubeRootVolDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
TypeName ("cubeRootVol")
Runtime type information.
cubeRootVolDelta (const word &name, const fvMesh &mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
virtual ~cubeRootVolDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const fvMesh &mesh, const dictionary &LESdeltaDict),(name, mesh, LESdeltaDict))
LESdelta (const word &name, const fvMesh &)
Construct from name and mesh.
virtual ~LESdelta ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const fvMesh &, const dictionary &, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes inherited from LESdelta
const fvMesh & mesh_
volScalarField delta_
Detailed Description
Simple cube-root of cell volume delta used in LES models.
Source files
cubeRootVolDelta.H
cubeRootVolDelta.C
Source files
cubeRootVolDelta.H
cubeRootVolDelta.C
Definition at line 48 of file cubeRootVolDelta.H.
Constructor & Destructor Documentation
cubeRootVolDelta() [1/2]
cubeRootVolDelta (const word & name, const fvMesh & mesh, const dictionary & dd)
Construct from name, mesh and IOdictionary.
Definition at line 82 of file cubeRootVolDelta.C.
~cubeRootVolDelta() [1/2]
virtual ~cubeRootVolDelta () inline virtual
Destructor.
Definition at line 85 of file cubeRootVolDelta.H.
References cubeRootVolDelta::correct(), and cubeRootVolDelta::read().
cubeRootVolDelta() [2/2]
cubeRootVolDelta (const word & name, const fvMesh & mesh, const dictionary &)
Construct from name, mesh and IOdictionary.
~cubeRootVolDelta() [2/2]
virtual ~cubeRootVolDelta () inline virtual
Destructor.
Definition at line 85 of file cubeRootVolDelta.H.
References cubeRootVolDelta::correct(), and cubeRootVolDelta::read().
Member Function Documentation
TypeName() [1/2]
TypeName ("cubeRootVol")
Runtime type information.
read() [1/2]
void read (const dictionary & dd) virtual
Read the LESdelta dictionary.
Implements LESdelta.
Definition at line 97 of file cubeRootVolDelta.C.
References dictionary::lookup(), dictionary::subDict(), and Foam::type().
Referenced by cubeRootVolDelta::~cubeRootVolDelta().
correct() [1/2]
void correct () virtual
Implements LESdelta.
Definition at line 104 of file cubeRootVolDelta.C.
References polyMesh::changing(), and LESdelta::mesh_.
Referenced by cubeRootVolDelta::~cubeRootVolDelta().
TypeName() [2/2]
TypeName ("cubeRootVol")
Runtime type information.
read() [2/2]
virtual void read (const dictionary &) virtual
Read the LESdelta dictionary.
Implements LESdelta.
correct() [2/2]
virtual void correct () virtual
Implements LESdelta.
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESdeltas/cubeRootVolDelta/cubeRootVolDelta.H
src/turbulenceModels/LES/LESdeltas/cubeRootVolDelta/cubeRootVolDelta.C