OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
continuousGasKEqn< BasicTurbulenceModel > Class Template Reference
One-equation SGS model for the gas-phase in a two-phase system supporting phase-inversion.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEqn< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("continuousGasKEqn")
Runtime type information.
continuousGasKEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~continuousGasKEqn ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
Public Member Functions inherited from kEqn< BasicTurbulenceModel >
TypeName ("kEqn")
Runtime type information.
kEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Constructor from components.
virtual ~kEqn ()
Destructor.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
virtual void correct ()
Correct Eddy-Viscosity and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
const turbulenceModel & liquidTurbulence () const
Return the turbulence model for the liquid phase.
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
Protected Member Functions inherited from kEqn< BasicTurbulenceModel >
virtual void correctNut ()
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar alphaInversion_
Protected Attributes inherited from kEqn< BasicTurbulenceModel >
volScalarField k_
dimensionedScalar Ck_
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::continuousGasKEqn< BasicTurbulenceModel >
One-equation SGS model for the gas-phase in a two-phase system supporting phase-inversion.
In the limit that the gas-phase fraction approaches zero a contribution from the other phase is blended into the k-equation up to the phase-fraction of alphaInversion at which point phase-inversion is considered to have occurred and the model reverts to the pure single-phase form.
This model is unpublished and is provided as a stable numerical framework on which a more physical model may be built.
The default model coefficients correspond to the following:
    continuousKEqnCoeffs
    {
        Ck              0.094;
        Ce              1.048;
        alphaInversion  0.7;
    }
Source files
continuousGasKEqn.H
continuousGasKEqn.C
Definition at line 73 of file continuousGasKEqn.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 109 of file continuousGasKEqn.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 110 of file continuousGasKEqn.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 111 of file continuousGasKEqn.H.
Constructor & Destructor Documentation
continuousGasKEqn()
continuousGasKEqn (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 41 of file continuousGasKEqn.C.
References kEqn< BasicTurbulenceModel >::correctNut().
~continuousGasKEqn()
virtual ~continuousGasKEqn () inline virtual
Destructor.
Definition at line 135 of file continuousGasKEqn.H.
References continuousGasKEqn< BasicTurbulenceModel >::read().
Member Function Documentation
liquidTurbulence()
const turbulenceModel & liquidTurbulence () const protected
Return the turbulence model for the liquid phase.
Definition at line 104 of file continuousGasKEqn.C.
References IOobject::db(), IOobject::groupName(), objectRegistry::lookupObject(), twoPhaseSystem::otherPhase(), and turbulenceModel::propertiesName.
phaseTransferCoeff()
tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 131 of file continuousGasKEqn.C.
References delta, TimeState::deltaT(), turbulenceModel::k(), Foam::max(), Foam::min(), Foam::sqrt(), and IOobject::time().
kSource()
tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 154 of file continuousGasKEqn.C.
References turbulenceModel::k(), and Foam::fvm::Sp().
TypeName()
TypeName ("continuousGasKEqn< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 87 of file continuousGasKEqn.C.
Referenced by continuousGasKEqn< BasicTurbulenceModel >::~continuousGasKEqn().
Member Data Documentation
alphaInversion_
dimensionedScalar alphaInversion_ protected
Definition at line 95 of file continuousGasKEqn.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/LES/continuousGasKEqn/continuousGasKEqn.H
src/TurbulenceModels/phaseCompressible/LES/continuousGasKEqn/continuousGasKEqn.C