OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulenceModel Class Reference abstract
Abstract base class for incompressible turbulence models (RAS, LES and laminar).
Public Member Functions
TypeName ("turbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr, turbulenceModel, turbulenceModel,(const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName),(U, phi, transport, turbulenceModelName))
turbulenceModel (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=typeName)
Construct from components.
virtual ~turbulenceModel ()
Destructor.
virtual const dictionary & coeffDict () const =0
Const access to the coefficients dictionary.
word GName () const
Helper function to return the nam eof the turbulence G field.
const volVectorField & U () const
Access function to velocity field.
const surfaceScalarField & phi () const
Access function to flux field.
transportModel & transport () const
Access function to incompressible transport model.
const nearWallDist & y () const
Return the near wall distances.
tmp< volScalarField > nu () const
Return the laminar viscosity.
virtual tmp< volScalarField > nut () const =0
Return the turbulence viscosity.
virtual tmp< volScalarField > nuEff () const =0
Return the effective viscosity.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const =0
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const =0
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devReff () const =0
Return the effective stress tensor including the laminar stress.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const =0
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const =0
Return the source term for the momentum equation.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
virtual bool read ()=0
Read LESProperties or RASProperties dictionary.
virtual bool writeData (Ostream &) const
Default dummy write function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static autoPtr< turbulenceModel > New (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName=typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Attributes
const Time & runTime_
const fvMesh & mesh_
const volVectorField & U_
const surfaceScalarField & phi_
transportModel & transportModel_
nearWallDist y_
Near wall distance boundary field.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Abstract base class for incompressible turbulence models (RAS, LES and laminar).
Source files
turbulenceModel.H
turbulenceModel.C
newTurbulenceModel.C
Definition at line 69 of file turbulenceModel.H.
Constructor & Destructor Documentation
turbulenceModel()
turbulenceModel (const volVectorField & U, const surfaceScalarField & phi, transportModel & transport, const word & turbulenceModelName = typeName)
Construct from components.
~turbulenceModel()
virtual ~turbulenceModel () inline virtual
Destructor.
Definition at line 149 of file turbulenceModel.H.
References turbulenceModel::coeffDict().
Member Function Documentation
TypeName()
TypeName ("turbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable()
declareRunTimeNewSelectionTable (autoPtr , turbulenceModel , turbulenceModel , (const volVectorField &U, const surfaceScalarField &phi, transportModel &transport, const word &turbulenceModelName) , (U, phi, transport, turbulenceModelName))
New()
autoPtr< turbulenceModel > New (const volVectorField & U, const surfaceScalarField & phi, transportModel & transport, const word & turbulenceModelName = typeName) static
Return a reference to the selected turbulence model.
Definition at line 77 of file turbulenceModel.C.
References TimePaths::constant(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), IOobject::MUST_READ_IF_MODIFIED, Foam::nl, IOobject::NO_WRITE, turbulenceModel::phi(), IOobject::time(), and turbulenceModel::U().
coeffDict()
virtual const dictionary& coeffDict () const pure virtual
Const access to the coefficients dictionary.
Implemented in RASModel, LESModel, and laminar.
Referenced by turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), and turbulenceModel::~turbulenceModel().
GName()
word GName () const inline
Helper function to return the nam eof the turbulence G field.
Definition at line 159 of file turbulenceModel.H.
References Foam::type().
Referenced by oneEqEddy::correct(), LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), kOmega::correct(), qZeta::correct(), v2f::correct(), kOmegaSSTSAS::correct(), kOmegaSST::correct(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
U()
const volVectorField& U () const inline
Access function to velocity field.
Definition at line 165 of file turbulenceModel.H.
References turbulenceModel::U_.
Referenced by laminar::B(), scaleSimilarity::B(), Smagorinsky2::B(), GenEddyVisc::B(), GenSGSStress::B(), SpalartAllmaras::B(), kOmegaSSTSAS::B(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), dynOneEqEddy::correct(), dynLagrangian::correct(), laminar::devReff(), GenEddyVisc::devReff(), GenSGSStress::devReff(), SpalartAllmaras::devReff(), kOmegaSSTSAS::devReff(), laminar::epsilon(), scaleSimilarity::epsilon(), LamBremhorstKE::epsilon(), LienLeschzinerLowRe::epsilon(), LienCubicKE::epsilon(), NonlinearKEShih::epsilon(), kEpsilon::epsilon(), RNGkEpsilon::epsilon(), kOmega::epsilon(), realizableKE::epsilon(), SpalartAllmaras::epsilon(), LienCubicKELowRe::epsilon(), kOmegaSSTSAS::epsilon(), kkLOmega::epsilon(), v2f::f(), kOmegaSSTSAS::gamma(), kOmegaSST::gamma(), laminar::k(), scaleSimilarity::k(), Smagorinsky::k(), spectEddyVisc::k(), LaunderSharmaKE::k(), dynLagrangian::k(), SpalartAllmaras::k(), kOmegaSSTSAS::Lvk2(), LESModel::New(), RASModel::New(), GenEddyVisc::nuSgs(), SpalartAllmaras::nuSgs(), SpalartAllmaras::nut(), LRR::R(), LaunderGibsonRSTM::R(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), and qZeta::zeta().
phi()
const surfaceScalarField& phi () const inline
Access function to flux field.
Definition at line 171 of file turbulenceModel.H.
References turbulenceModel::phi_.
Referenced by LRRDiffStress::correct(), DeardorffDiffStress::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), dynOneEqEddy::correct(), dynLagrangian::correct(), SpalartAllmaras::correct(), kOmegaSSTSAS::correct(), kOmegaSSTSAS::gamma(), kOmegaSST::gamma(), LESModel::New(), and RASModel::New().
transport()
transportModel& transport () const inline
Access function to incompressible transport model.
Definition at line 177 of file turbulenceModel.H.
References turbulenceModel::transportModel_.
Referenced by kOmegaSSTSAS::gamma(), kOmegaSST::gamma(), LESModel::New(), and RASModel::New().
y()
const nearWallDist& y () const inline
Return the near wall distances.
Definition at line 183 of file turbulenceModel.H.
References turbulenceModel::y_.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutkWallFunctionFvPatchScalarField::yPlus(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
nu()
tmp<volScalarField> nu () const inline
Return the laminar viscosity.
Definition at line 189 of file turbulenceModel.H.
References turbulenceModel::correct(), turbulenceModel::devReff(), turbulenceModel::divDevReff(), turbulenceModel::divDevRhoReff(), turbulenceModel::epsilon(), turbulenceModel::k(), transportModel::nu(), turbulenceModel::nuEff(), turbulenceModel::nut(), turbulenceModel::R(), turbulenceModel::read(), and rho.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), SpalartAllmaras::chi(), LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), LienCubicKELowRe::correct(), SpalartAllmaras::correct(), qZeta::correct(), kkLOmega::correct(), LRRDiffStress::DBEff(), DeardorffDiffStress::DBEff(), LamBremhorstKE::DepsilonEff(), LienLeschzinerLowRe::DepsilonEff(), LienCubicKE::DepsilonEff(), NonlinearKEShih::DepsilonEff(), LaunderSharmaKE::DepsilonEff(), kEpsilon::DepsilonEff(), RNGkEpsilon::DepsilonEff(), LRR::DepsilonEff(), realizableKE::DepsilonEff(), LaunderGibsonRSTM::DepsilonEff(), LienCubicKELowRe::DepsilonEff(), v2f::DepsilonEff(), laminar::devReff(), GenSGSStress::devReff(), LRR::devReff(), LaunderGibsonRSTM::devReff(), laminar::divDevReff(), LamBremhorstKE::DkEff(), LienLeschzinerLowRe::DkEff(), LienCubicKE::DkEff(), oneEqEddy::DkEff(), NonlinearKEShih::DkEff(), LaunderSharmaKE::DkEff(), kEpsilon::DkEff(), homogeneousDynOneEqEddy::DkEff(), kOmega::DkEff(), RNGkEpsilon::DkEff(), realizableKE::DkEff(), LienCubicKELowRe::DkEff(), dynOneEqEddy::DkEff(), dynLagrangian::DkEff(), v2f::DkEff(), kOmegaSSTSAS::DkEff(), kOmegaSST::DkEff(), kkLOmega::DkEff(), SpalartAllmaras::DnuTildaEff(), kOmega::DomegaEff(), kOmegaSSTSAS::DomegaEff(), kOmegaSST::DomegaEff(), kkLOmega::DomegaEff(), qZeta::DqEff(), LRR::DREff(), LaunderGibsonRSTM::DREff(), qZeta::DzetaEff(), laminar::epsilon(), kOmegaSSTSAS::F1(), kOmegaSST::F1(), LaunderSharmaKE::f2(), qZeta::f2(), kOmegaSSTSAS::F2(), kOmegaSST::F2(), kOmegaSST::F3(), LaunderSharmaKE::fMu(), qZeta::fMu(), SpalartAllmaras::fv1(), SpalartAllmaras::fv2(), SpalartAllmaras::fv3(), spectEddyVisc::k(), v2f::Ls(), laminar::nuEff(), LESModel::nuEff(), RASModel::nuEff(), laminar::nuSgs(), laminar::nut(), v2f::Ts(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
nut()
virtual tmp<volScalarField> nut () const pure virtual
Return the turbulence viscosity.
Implemented in kkLOmega, kOmegaSST, LESModel, v2f, SpalartAllmaras, qZeta, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, kOmega, RNGkEpsilon, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, laminar, and laminar.
Referenced by epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), turbulenceModel::nu(), and RASModel::nuEff().
nuEff()
virtual tmp<volScalarField> nuEff () const pure virtual
Return the effective viscosity.
Implemented in RASModel, LESModel, laminar, laminar, and laminar.
Referenced by turbulenceModel::nu().
k()
virtual tmp<volScalarField> k () const pure virtual
Return the turbulence kinetic energy.
Implemented in kkLOmega, kOmegaSST, v2f, kOmegaSSTSAS, qZeta, SpalartAllmaras, LienCubicKELowRe, SpalartAllmaras, LaunderGibsonRSTM, realizableKE, dynLagrangian, LRR, kOmega, RNGkEpsilon, dynOneEqEddy, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, homogeneousDynSmagorinsky, LienLeschzinerLowRe, LamBremhorstKE, homogeneousDynOneEqEddy, spectEddyVisc, Smagorinsky, oneEqEddy, mixedSmagorinsky, GenSGSStress, scaleSimilarity, laminar, laminar, and laminar.
Referenced by GenEddyVisc::B(), nutkWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), GenEddyVisc::epsilon(), turbulenceModel::nu(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and nutkWallFunctionFvPatchScalarField::yPlus().
epsilon()
virtual tmp<volScalarField> epsilon () const pure virtual
Return the turbulence kinetic energy dissipation rate.
Implemented in kkLOmega, kOmegaSST, kOmegaSSTSAS, v2f, qZeta, SpalartAllmaras, LienCubicKELowRe, SpalartAllmaras, LaunderGibsonRSTM, realizableKE, kOmega, LRR, RNGkEpsilon, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, GenSGSStress, mixedSmagorinsky, GenEddyVisc, scaleSimilarity, laminar, laminar, and laminar.
Referenced by turbulenceModel::nu().
R()
virtual tmp<volSymmTensorField> R () const pure virtual
Return the Reynolds stress tensor.
Implemented in kkLOmega, kOmegaSST, v2f, LESModel, qZeta, SpalartAllmaras, kOmega, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, RNGkEpsilon, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, laminar, and laminar.
Referenced by turbulenceModel::nu().
devReff()
virtual tmp<volSymmTensorField> devReff () const pure virtual
Return the effective stress tensor including the laminar stress.
Implemented in kkLOmega, kOmegaSST, kOmegaSSTSAS, v2f, qZeta, SpalartAllmaras, SpalartAllmaras, kOmega, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, RNGkEpsilon, kEpsilon, LaunderSharmaKE, GenSGSStress, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, GenEddyVisc, mixedSmagorinsky, scaleSimilarity, laminar, laminar, and laminar.
Referenced by turbulenceModel::nu().
divDevReff()
virtual tmp<fvVectorMatrix> divDevReff (volVectorField & U) const pure virtual
Return the source term for the momentum equation.
Referenced by turbulenceModel::nu().
divDevRhoReff()
virtual tmp<fvVectorMatrix> divDevRhoReff (const volScalarField & rho, volVectorField & U) const pure virtual
Return the source term for the momentum equation.
Referenced by turbulenceModel::nu().
correct()
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implemented in kkLOmega, kOmegaSST, v2f, LESModel, RASModel, qZeta, SpalartAllmaras, kOmega, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, RNGkEpsilon, kEpsilon, LaunderSharmaKE, NonlinearKEShih, LienCubicKE, LienLeschzinerLowRe, LamBremhorstKE, laminar, and laminar.
Definition at line 129 of file turbulenceModel.C.
References polyMesh::changing(), nearWallDist::correct(), turbulenceModel::mesh_, and turbulenceModel::y_.
Referenced by laminar::correct(), RASModel::correct(), LESModel::correct(), and turbulenceModel::nu().
read()
virtual bool read () pure virtual
Read LESProperties or RASProperties dictionary.
Reimplemented from regIOobject.
Implemented in kkLOmega, kOmegaSST, kOmegaSSTSAS, v2f, LESModel, RASModel, qZeta, SpalartAllmaras, SpalartAllmaras, kOmega, LienCubicKELowRe, LaunderGibsonRSTM, realizableKE, LRR, RNGkEpsilon, kEpsilon, dynLagrangian, LaunderSharmaKE, NonlinearKEShih, GenSGSStress, LienCubicKE, LienLeschzinerLowRe, dynOneEqEddy, LamBremhorstKE, GenEddyVisc, mixedSmagorinsky, homogeneousDynSmagorinsky, homogeneousDynOneEqEddy, oneEqEddy, DeardorffDiffStress, Smagorinsky, scaleSimilarity, SpalartAllmarasIDDES, LRRDiffStress, spectEddyVisc, Smagorinsky2, laminar, laminar, and laminar.
Referenced by turbulenceModel::nu().
writeData()
virtual bool writeData (Ostream &) const inline virtual
Default dummy write function.
Implements regIOobject.
Definition at line 229 of file turbulenceModel.H.
Member Data Documentation
runTime_
const Time& runTime_ protected
Definition at line 78 of file turbulenceModel.H.
Referenced by laminar::B(), laminar::devReff(), LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), GenSGSStress::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), LRR::devReff(), realizableKE::devReff(), LaunderGibsonRSTM::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), laminar::epsilon(), GenEddyVisc::epsilon(), GenSGSStress::epsilon(), SpalartAllmaras::epsilon(), laminar::k(), GenSGSStress::k(), SpalartAllmaras::k(), laminar::nuSgs(), laminar::nut(), laminar::R(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), LaunderSharmaKE::R(), kEpsilon::R(), RNGkEpsilon::R(), realizableKE::R(), LienCubicKELowRe::R(), kOmega::R(), SpalartAllmaras::R(), qZeta::R(), v2f::R(), kOmegaSST::R(), and kkLOmega::R().
mesh_
const fvMesh& mesh_ protected
Definition at line 79 of file turbulenceModel.H.
Referenced by laminar::B(), LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LRR::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), turbulenceModel::correct(), SpalartAllmaras::correct(), kOmegaSSTSAS::correct(), kOmegaSST::correct(), kkLOmega::correct(), laminar::devReff(), LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), GenSGSStress::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), LRR::devReff(), realizableKE::devReff(), LaunderGibsonRSTM::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), laminar::epsilon(), GenEddyVisc::epsilon(), GenSGSStress::epsilon(), kOmega::epsilon(), SpalartAllmaras::epsilon(), kOmegaSST::epsilon(), SpalartAllmaras::fv3(), laminar::k(), GenSGSStress::k(), SpalartAllmaras::k(), kkLOmega::k(), LESModel::LESModel(), SpalartAllmaras::LESRegion(), laminar::nuSgs(), laminar::nut(), laminar::R(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), LaunderSharmaKE::R(), kEpsilon::R(), RNGkEpsilon::R(), realizableKE::R(), LienCubicKELowRe::R(), kOmega::R(), SpalartAllmaras::R(), qZeta::R(), v2f::R(), kOmegaSST::R(), kkLOmega::R(), and RASModel::RASModel().
U_
const volVectorField& U_ protected
Definition at line 81 of file turbulenceModel.H.
Referenced by LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), kOmega::correct(), SpalartAllmaras::correct(), qZeta::correct(), LESModel::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), laminar::devReff(), LamBremhorstKE::devReff(), LienLeschzinerLowRe::devReff(), LienCubicKE::devReff(), NonlinearKEShih::devReff(), LaunderSharmaKE::devReff(), kEpsilon::devReff(), RNGkEpsilon::devReff(), LRR::devReff(), realizableKE::devReff(), LaunderGibsonRSTM::devReff(), LienCubicKELowRe::devReff(), kOmega::devReff(), SpalartAllmaras::devReff(), qZeta::devReff(), v2f::devReff(), kOmegaSST::devReff(), kkLOmega::devReff(), laminar::epsilon(), laminar::k(), kOmegaSST::kOmegaSST(), SpalartAllmaras::LESRegion(), laminar::R(), LamBremhorstKE::R(), LienLeschzinerLowRe::R(), LienCubicKE::R(), NonlinearKEShih::R(), LaunderSharmaKE::R(), kEpsilon::R(), RNGkEpsilon::R(), realizableKE::R(), LienCubicKELowRe::R(), kOmega::R(), SpalartAllmaras::R(), qZeta::R(), v2f::R(), kOmegaSST::R(), kkLOmega::R(), and turbulenceModel::U().
phi_
const surfaceScalarField& phi_ protected
Definition at line 82 of file turbulenceModel.H.
Referenced by LamBremhorstKE::correct(), LienLeschzinerLowRe::correct(), LienCubicKE::correct(), NonlinearKEShih::correct(), LaunderSharmaKE::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LRR::correct(), realizableKE::correct(), LaunderGibsonRSTM::correct(), LienCubicKELowRe::correct(), kOmega::correct(), SpalartAllmaras::correct(), qZeta::correct(), v2f::correct(), kOmegaSST::correct(), kkLOmega::correct(), and turbulenceModel::phi().
transportModel_
transportModel& transportModel_ protected
Definition at line 84 of file turbulenceModel.H.
Referenced by turbulenceModel::transport().
y_
nearWallDist y_ protected
Near wall distance boundary field.
Definition at line 87 of file turbulenceModel.H.
Referenced by turbulenceModel::correct(), and turbulenceModel::y().
The documentation for this class was generated from the following files:
src/turbulenceModels/incompressible/turbulenceModel/turbulenceModel.H
src/turbulenceModels/incompressible/turbulenceModel/turbulenceModel.C