OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
smoothDelta::deltaData Class Reference
Public member class used by mesh-wave to propagate the delta-ratio.
Public Member Functions
deltaData ()
Construct null.
deltaData (const scalar delta)
Construct from delta value.
scalar delta () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const deltaData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const deltaData &, TrackingData &td) const
Same (like operator==)
bool operator== (const deltaData &) const
bool operator!= (const deltaData &) const
deltaData ()
Construct null.
deltaData (const scalar delta)
Construct from delta value.
scalar delta () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const deltaData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const deltaData &, TrackingData &td) const
Same (like operator==)
bool operator== (const deltaData &) const
bool operator!= (const deltaData &) const
Friends
Ostream & operator<< (Ostream &os, const deltaData &wDist)
Istream & operator>> (Istream &is, deltaData &wDist)
Ostream & operator<< (Ostream &os, const deltaData &wDist)
Istream & operator>> (Istream &is, deltaData &wDist)
Detailed Description
Public member class used by mesh-wave to propagate the delta-ratio.
Definition at line 57 of file smoothDelta.H.
Constructor & Destructor Documentation
deltaData() [1/4]
deltaData () inline
Construct null.
Definition at line 71 of file smoothDeltaDeltaDataI.H.
deltaData() [2/4]
deltaData (const scalar delta) inline
Construct from delta value.
Definition at line 78 of file smoothDeltaDeltaDataI.H.
deltaData() [3/4]
deltaData () inline
Construct null.
deltaData() [4/4]
deltaData (const scalar delta) inline
Construct from delta value.
Member Function Documentation
delta() [1/2]
scalar delta () const inline
Definition at line 90 of file smoothDelta.H.
References smoothDelta::deltaData::enterDomain(), smoothDelta::deltaData::equal(), smoothDelta::deltaData::leaveDomain(), smoothDelta::deltaData::operator!=(), smoothDelta::deltaData::operator==(), smoothDelta::deltaData::sameGeometry(), smoothDelta::deltaData::transform(), smoothDelta::deltaData::updateCell(), smoothDelta::deltaData::updateFace(), and smoothDelta::deltaData::valid().
Referenced by smoothDelta::deltaData::operator==().
valid() [1/2]
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 87 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::sameGeometry().
Referenced by smoothDelta::deltaData::delta().
sameGeometry() [1/2]
bool sameGeometry (const polyMesh & , const deltaData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking.
Definition at line 96 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::leaveDomain().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::valid().
leaveDomain() [1/2]
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
Definition at line 109 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::transform().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::sameGeometry().
enterDomain() [1/2]
void enterDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 132 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::updateCell().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::transform().
transform() [1/2]
void transform (const polyMesh & , const tensor & , TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 121 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::enterDomain().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::leaveDomain().
updateCell() [1/2]
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 145 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::updateFace().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::enterDomain().
updateFace() [1/4]
bool updateFace (const polyMesh & , const label thisFaceI, const label neighbourCellI, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 162 of file smoothDeltaDeltaDataI.H.
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::updateCell().
updateFace() [2/4]
bool updateFace (const polyMesh & , const label thisFaceI, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 179 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::equal().
equal() [1/2]
bool equal (const deltaData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 194 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::operator==().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::updateFace().
operator==() [1/2]
bool operator== (const deltaData & rhs) const inline
Definition at line 206 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::delta().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::equal().
operator!=() [1/2]
bool operator!= (const deltaData & rhs) const inline
Definition at line 215 of file smoothDeltaDeltaDataI.H.
Referenced by smoothDelta::deltaData::delta().
delta() [2/2]
scalar delta () const inline
Definition at line 90 of file smoothDelta.H.
References smoothDelta::deltaData::enterDomain(), smoothDelta::deltaData::equal(), smoothDelta::deltaData::leaveDomain(), smoothDelta::deltaData::operator!=(), smoothDelta::deltaData::operator==(), smoothDelta::deltaData::sameGeometry(), smoothDelta::deltaData::transform(), smoothDelta::deltaData::updateCell(), smoothDelta::deltaData::updateFace(), and smoothDelta::deltaData::valid().
valid() [2/2]
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
sameGeometry() [2/2]
bool sameGeometry (const polyMesh & , const deltaData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking.
leaveDomain() [2/2]
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
enterDomain() [2/2]
void enterDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
transform() [2/2]
void transform (const polyMesh & , const tensor & , TrackingData & td) inline
Apply rotation matrix to any coordinates.
updateCell() [2/2]
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
updateFace() [3/4]
bool updateFace (const polyMesh & , const label thisFaceI, const label neighbourCellI, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
updateFace() [4/4]
bool updateFace (const polyMesh & , const label thisFaceI, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
equal() [2/2]
bool equal (const deltaData & , TrackingData & td) const inline
Same (like operator==)
operator==() [2/2]
bool operator== (const deltaData &) const inline
operator!=() [2/2]
bool operator!= (const deltaData &) const inline
Friends And Related Function Documentation
operator<< [1/2]
Ostream& operator<< (Ostream & os, const deltaData & wDist) friend
Definition at line 195 of file smoothDelta.H.
operator>> [1/2]
Istream& operator>> (Istream & is, deltaData & wDist) friend
Definition at line 203 of file smoothDelta.H.
operator<< [2/2]
Ostream& operator<< (Ostream & os, const deltaData & wDist) friend
Definition at line 195 of file smoothDelta.H.
operator>> [2/2]
Istream& operator>> (Istream & is, deltaData & wDist) friend
Definition at line 203 of file smoothDelta.H.
The documentation for this class was generated from the following files:
src/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDelta.H
src/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDeltaDeltaDataI.H