OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nutUSpaldingWallFunctionFvPatchScalarField Class Reference
RAS boundary conditions » RAS wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on velocity, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
Public Member Functions
TypeName ("nutUSpaldingWallFunction")
Runtime type information.
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
virtual tmp< scalarField > calcUTau (const scalarField &magGradU) const
Calculate the friction velocity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on velocity, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
where
= non-dimensional position
= non-dimensional velocity
= Von Karman constant
Patch usage
Example of the boundary condition specification:
    myPatch
    {
        type            nutUSpaldingWallFunction;
    }
See also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutUSpaldingWallFunctionFvPatchScalarField.H
nutUSpaldingWallFunctionFvPatchScalarField.C
Definition at line 91 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUSpaldingWallFunctionFvPatchScalarField() [1/5]
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 134 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
Referenced by nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::clone(), and nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField().
nutUSpaldingWallFunctionFvPatchScalarField() [2/5]
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 158 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField().
nutUSpaldingWallFunctionFvPatchScalarField() [3/5]
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutUSpaldingWallFunctionFvPatchScalarField onto a new patch
Definition at line 145 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField().
nutUSpaldingWallFunctionFvPatchScalarField() [4/5]
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 170 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField().
nutUSpaldingWallFunctionFvPatchScalarField() [5/5]
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 180 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 39 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), dimensionedInternalField(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), Foam::max(), turbulenceModel::nu(), patchi, turbulenceModel::propertiesName, Foam::sqr(), and turbulenceModel::U().
calcUTau()
tmp< scalarField > calcUTau (const scalarField & magGradU) const protected virtual
Calculate the friction velocity.
Definition at line 65 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensionedInternalField(), nutWallFunctionFvPatchScalarField::E_, Foam::exp(), f(), forAll, Foam::constant::atomic::group, IOobject::groupName(), nutWallFunctionFvPatchScalarField::kappa_, Foam::mag(), magUp, Foam::max(), Foam::min(), turbulenceModel::nu(), nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField(), patchi, fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, Foam::sqr(), Foam::sqrt(), turbulenceModel::U(), uTau, y, and turbulenceModel::y().
Referenced by nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), and nutUSpaldingWallFunctionFvPatchScalarField::yPlus().
TypeName()
TypeName ("nutUSpaldingWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 147 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
References nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 164 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
References nutUSpaldingWallFunctionFvPatchScalarField::nutUSpaldingWallFunctionFvPatchScalarField(), nutUSpaldingWallFunctionFvPatchScalarField::write(), and nutUSpaldingWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 191 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), dimensionedInternalField(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), turbulenceModel::nu(), patchi, turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by nutUSpaldingWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 212 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), and nutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by nutUSpaldingWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUSpaldingWallFunction/nutUSpaldingWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUSpaldingWallFunction/nutUSpaldingWallFunctionFvPatchScalarField.C