OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
atmBoundaryLayerInletVelocityFvPatchVectorField Class Reference
RAS boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition specifies a velocity inlet profile appropriate for atmospheric boundary layers (ABL). The profile is derived from the friction velocity, flow direction and the direction of the parabolic co-ordinate z.
Public Member Functions
TypeName ("atmBoundaryLayerInletVelocity")
Runtime type information.
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & Ustar () const
Return Ustar.
const vector & n () const
Return flow direction.
const vector & z () const
Return z direction.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition specifies a velocity inlet profile appropriate for atmospheric boundary layers (ABL). The profile is derived from the friction velocity, flow direction and the direction of the parabolic co-ordinate z.
where
= frictional velocity
= Karman's constant
= vertical co-ordinate [m]
= surface roughness length [m]
= minimum vlaue in z direction [m]
and:
where:
= reference velocity at [m/s]
= reference height [m]
Reference: D.M. Hargreaves and N.G. Wright, "On the use of the k-epsilon model in commercial CFD software to model the neutral atmospheric boundary layer", Journal of Wind Engineering and Industrial Aerodynamics 95(2007), pp 355-369.
Patch usage
Property Description Required Default value
n flow direction yes
z vertical co-ordinate [m] yes
kappa Karman's constanat no 0.41
Uref reference velocity [m/s] yes
Href reference height [m] yes
z0 surface roughness length [m] yes
zGround minimum z co-ordinate [m] yes
Example of the boundary condition specification:
    myPatch
    {
        type            atmBoundaryLayerInletVelocity;
        n               (0 1 0);
        z               1.0;
        kappa           0.41;
        Uref            1.0;
        Href            0.0;
        z0              uniform 0.0;
        zGround         uniform 0.0;
    }
Note
D.M. Hargreaves and N.G. Wright recommend Gamma epsilon in the k-epsilon model should be changed from 1.3 to 1.11 for consistency. The roughness height (Er) is given by Er = 20 z0 following the same reference.
Source files
atmBoundaryLayerInletVelocityFvPatchVectorField.H
atmBoundaryLayerInletVelocityFvPatchVectorField.C
Definition at line 188 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletVelocityFvPatchVectorField() [1/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 41 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), and atmBoundaryLayerInletVelocityFvPatchVectorField::clone().
atmBoundaryLayerInletVelocityFvPatchVectorField() [2/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 81 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References Foam::abort(), atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), Foam::constant::universal::c, Foam::FatalError, FatalErrorIn, forAll, Foam::log(), Foam::mag(), Field< vector >::operator=(), and List< T >::size().
atmBoundaryLayerInletVelocityFvPatchVectorField() [3/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
atmBoundaryLayerInletVelocityFvPatchVectorField onto a new patch
Definition at line 60 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField().
atmBoundaryLayerInletVelocityFvPatchVectorField() [4/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField & blpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 146 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 253 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 270 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField().
Ustar()
const scalarField& Ustar () const inline
Return Ustar.
Definition at line 286 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
n()
const vector& n () const inline
Return flow direction.
Definition at line 292 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
z()
const vector& z () const inline
Return z direction.
Definition at line 298 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
References atmBoundaryLayerInletVelocityFvPatchVectorField::autoMap(), atmBoundaryLayerInletVelocityFvPatchVectorField::rmap(), and atmBoundaryLayerInletVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 166 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::rmap().
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), and atmBoundaryLayerInletVelocityFvPatchVectorField::z().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 178 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::rmap().
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::autoMap(), atmBoundaryLayerInletVelocityFvPatchVectorField::rmap(), and atmBoundaryLayerInletVelocityFvPatchVectorField::z().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 194 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::z().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.C