OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
atmBoundaryLayerInletEpsilonFvPatchScalarField Class Reference
RAS boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition specifies an inlet value for the turbulence dissipation, (epsilon), appropriate for atmospheric boundary layers (ABL), and designed to be used in conjunction with the ABLInletVelocity inlet velocity boundary condition.
Public Member Functions
TypeName ("atmBoundaryLayerInletEpsilon")
Runtime type information.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & Ustar () const
Return max value.
const vector & z () const
Return z direction.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition specifies an inlet value for the turbulence dissipation, (epsilon), appropriate for atmospheric boundary layers (ABL), and designed to be used in conjunction with the ABLInletVelocity inlet velocity boundary condition.
where
= frictional velocity
= Karman's constant
= vertical co-ordinate [m]
= surface roughness length [m]
= minimum vlaue in z direction [m]
and:
where:
= reference velocity at [m/s]
= reference height [m]
Patch usage
Property Description Required Default value
z vertical co-ordinate [m] yes
kappa Karman's constanat no 0.41
Uref reference velocity [m/s] yes
Href reference height [m] yes
z0 surface roughness length [m] yes
zGround minimum z co-ordinate [m] yes
Example of the boundary condition specification:
    myPatch
    {
        type            atmBoundaryLayerInletEpsilon;
        z               1.0;
        kappa           0.41;
        Uref            1.0;
        Href            0.0;
        z0              uniform 0.0;
        zGround         uniform 0.0;
    }
Reference: D.M. Hargreaves and N.G. Wright, "On the use of the k-epsilon model in commercial CFD software to model the neutral atmospheric boundary layer", Journal of Wind Engineering and Industrial Aerodynamics 95(2007), pp 355-369.
Source files
atmBoundaryLayerInletEpsilonFvPatchScalarField.H
atmBoundaryLayerInletEpsilonFvPatchScalarField.C
Definition at line 175 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletEpsilonFvPatchScalarField() [1/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 41 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::clone().
atmBoundaryLayerInletEpsilonFvPatchScalarField() [2/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 79 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References Foam::abort(), atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), Foam::constant::universal::c, Foam::FatalError, FatalErrorIn, forAll, Foam::log(), Foam::mag(), Field< scalar >::operator=(), and Foam::pow3().
atmBoundaryLayerInletEpsilonFvPatchScalarField() [3/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
atmBoundaryLayerInletEpsilonFvPatchScalarField onto a new patch
Definition at line 59 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField().
atmBoundaryLayerInletEpsilonFvPatchScalarField() [4/4]
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField & blpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 125 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletEpsilon")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 237 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 254 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField().
Ustar()
const scalarField& Ustar () const inline
Return max value.
Definition at line 270 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
z()
const vector& z () const inline
Return z direction.
Definition at line 276 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::autoMap(), atmBoundaryLayerInletEpsilonFvPatchScalarField::rmap(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 144 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::rmap().
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::z().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 156 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::rmap().
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::autoMap(), atmBoundaryLayerInletEpsilonFvPatchScalarField::rmap(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::z().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 172 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::z().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.C