OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentMixingLengthFrequencyInletFvPatchScalarField Class Reference
RAS boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition provides a turbulence specific dissipation, (omega) inlet condition based on a specified mixing length. The patch values are calculated using:
Public Member Functions
TypeName ("turbulentMixingLengthFrequencyInlet")
Runtime type information.
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a turbulence specific dissipation, (omega) inlet condition based on a specified mixing length. The patch values are calculated using:
where
= patch omega values
= Model coefficient, set to 0.09
= turbulence kinetic energy
= length scale
Patch usage
Property Description Required Default value
mixingLength Length scale [m] yes
phi flux field name no phi
k turbulence kinetic energy field name no k
Example of the boundary condition specification:
    myPatch
    {
        type            turbulentMixingLengthFrequencyInlet;
        mixingLength    0.005;
        value           uniform 200;   // placeholder
    }
Note
In the event of reverse flow, a zero-gradient condition is applied
See also
Foam::inletOutletFvPatchField
Source files
turbulentMixingLengthFrequencyInletFvPatchScalarField.H
turbulentMixingLengthFrequencyInletFvPatchScalarField.C
Definition at line 128 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentMixingLengthFrequencyInletFvPatchScalarField() [1/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 42 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
Referenced by turbulentMixingLengthFrequencyInletFvPatchScalarField::clone(), and turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField().
turbulentMixingLengthFrequencyInletFvPatchScalarField() [2/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 72 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References dictionary::lookupOrDefault(), fvPatchField< Type >::operator=(), fvPatch::size(), and turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField().
turbulentMixingLengthFrequencyInletFvPatchScalarField() [3/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentMixingLengthFrequencyInletFvPatchScalarField onto a new patch
Definition at line 58 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField().
turbulentMixingLengthFrequencyInletFvPatchScalarField() [4/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField & ptf)
Construct as copy.
Definition at line 93 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField().
turbulentMixingLengthFrequencyInletFvPatchScalarField() [5/5]
turbulentMixingLengthFrequencyInletFvPatchScalarField (const turbulentMixingLengthFrequencyInletFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 104 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("turbulentMixingLengthFrequencyInlet")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 182 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.H.
References turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 202 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.H.
References turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), and turbulentMixingLengthFrequencyInletFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 117 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References turbulenceModel::coeffDict(), dimensionedInternalField(), Foam::constant::atomic::group, IOobject::groupName(), dictionary::lookupOrDefault(), Foam::pos(), Foam::pow(), turbulenceModel::propertiesName, Foam::sqrt(), turbulence, and turbulentMixingLengthFrequencyInletFvPatchScalarField::write().
Referenced by turbulentMixingLengthFrequencyInletFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 153 of file turbulentMixingLengthFrequencyInletFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by turbulentMixingLengthFrequencyInletFvPatchScalarField::clone(), and turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthFrequencyInlet/turbulentMixingLengthFrequencyInletFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthFrequencyInlet/turbulentMixingLengthFrequencyInletFvPatchScalarField.C