OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
laminar< BasicTurbulenceModel > Class Template Reference
Turbulence model for laminar flow.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("laminar")
Runtime type information.
laminar (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~laminar ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity, i.e. 0 for laminar flow.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity, i.e. the laminar viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate,.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor, i.e. the laminar stress.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()
Correct the laminar viscosity.
virtual bool read ()
Read turbulenceProperties dictionary.
Static Public Member Functions
static autoPtr< laminar > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminar< BasicTurbulenceModel >
Turbulence model for laminar flow.
Source files
laminar.H
laminar.C
Definition at line 49 of file laminar.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 56 of file laminar.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 57 of file laminar.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 58 of file laminar.H.
Constructor & Destructor Documentation
laminar()
laminar (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Construct from components.
Definition at line 37 of file laminar.C.
References laminar< BasicTurbulenceModel >::New().
~laminar()
virtual ~laminar () inline virtual
Destructor.
Definition at line 96 of file laminar.H.
References laminar< BasicTurbulenceModel >::coeffDict(), laminar< BasicTurbulenceModel >::correct(), laminar< BasicTurbulenceModel >::devRhoReff(), laminar< BasicTurbulenceModel >::divDevRhoReff(), laminar< BasicTurbulenceModel >::epsilon(), laminar< BasicTurbulenceModel >::k(), laminar< BasicTurbulenceModel >::nuEff(), laminar< BasicTurbulenceModel >::nut(), patchi, laminar< BasicTurbulenceModel >::R(), laminar< BasicTurbulenceModel >::read(), and U.
Member Function Documentation
TypeName()
TypeName ("laminar< BasicTurbulenceModel >")
Runtime type information.
New()
Foam::autoPtr< Foam::laminar< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 65 of file laminar.C.
Referenced by laminar< BasicTurbulenceModel >::laminar().
coeffDict()
const Foam::dictionary & coeffDict () const virtual
Const access to the coefficients dictionary.
Definition at line 95 of file laminar.C.
Referenced by laminar< BasicTurbulenceModel >::~laminar().
nut() [1/2]
Foam::tmp< Foam::volScalarField > nut () const virtual
Return the turbulence viscosity, i.e. 0 for laminar flow.
Definition at line 103 of file laminar.C.
References Foam::dimViscosity.
Referenced by laminar< BasicTurbulenceModel >::~laminar().
nut() [2/2]
Foam::tmp< Foam::scalarField > nut (const label patchi) const virtual
Return the turbulence viscosity on patch.
Definition at line 127 of file laminar.C.
References patchi, and scalarField().
nuEff() [1/2]
Foam::tmp< Foam::volScalarField > nuEff () const virtual
Return the effective viscosity, i.e. the laminar viscosity.
Definition at line 140 of file laminar.C.
References nu.
Referenced by laminar< BasicTurbulenceModel >::~laminar().
nuEff() [2/2]
Foam::tmp< Foam::scalarField > nuEff (const label patchi) const virtual
Return the effective viscosity on patch.
Definition at line 155 of file laminar.C.
References nu.
k()
Foam::tmp< Foam::volScalarField > k () const virtual
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
Definition at line 165 of file laminar.C.
References sqr().
Referenced by laminar< BasicTurbulenceModel >::~laminar().
epsilon()
Foam::tmp< Foam::volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate,.
i.e. 0 for laminar flow
Definition at line 188 of file laminar.C.
References Foam::dimTime, and sqr().
Referenced by laminar< BasicTurbulenceModel >::~laminar().
R()
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
Definition at line 214 of file laminar.C.
References sqr().
Referenced by laminar< BasicTurbulenceModel >::~laminar().
devRhoReff()
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor, i.e. the laminar stress.
Definition at line 240 of file laminar.C.
References Foam::dev(), laminar< BasicTurbulenceModel >::divDevRhoReff(), Foam::fvc::grad(), and Foam::twoSymm().
Referenced by laminar< BasicTurbulenceModel >::~laminar().
divDevRhoReff()
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 263 of file laminar.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvc::laplacian(), and T.
Referenced by laminar< BasicTurbulenceModel >::devRhoReff(), and laminar< BasicTurbulenceModel >::~laminar().
correct()
void correct () virtual
Correct the laminar viscosity.
Definition at line 276 of file laminar.C.
References correct.
Referenced by laminar< BasicTurbulenceModel >::~laminar().
read()
bool read () virtual
Read turbulenceProperties dictionary.
Definition at line 283 of file laminar.C.
Referenced by laminar< BasicTurbulenceModel >::~laminar().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/laminar.H
src/TurbulenceModels/turbulenceModels/laminar/laminar.C