OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellShapeControlMesh Class Reference
Public Types
typedef CellSizeDelaunay::Cell_handle Cell_handle
typedef CellSizeDelaunay::Vertex_handle Vertex_handle
typedef CellSizeDelaunay::Point Point
Public Types inherited from DistributedDelaunayMesh< CellSizeDelaunay >
typedef CellSizeDelaunay ::Vertex_handle Vertex_handle
typedef CellSizeDelaunay ::Cell_handle Cell_handle
typedef CellSizeDelaunay ::Point Point
typedef CellSizeDelaunay ::Finite_vertices_iterator Finite_vertices_iterator
typedef CellSizeDelaunay ::Finite_cells_iterator Finite_cells_iterator
typedef CellSizeDelaunay ::All_cells_iterator All_cells_iterator
typedef DelaunayMesh< CellSizeDelaunay >::labelPairHashSet labelPairHashSet
Public Types inherited from DelaunayMesh< CellSizeDelaunay >
typedef CellSizeDelaunay ::Cell_handle Cell_handle
typedef CellSizeDelaunay ::Vertex_handle Vertex_handle
typedef CellSizeDelaunay ::Edge Edge
typedef CellSizeDelaunay ::Point Point
typedef CellSizeDelaunay ::Facet Facet
typedef CellSizeDelaunay ::Finite_vertices_iterator Finite_vertices_iterator
typedef CellSizeDelaunay ::Finite_cells_iterator Finite_cells_iterator
typedef CellSizeDelaunay ::Finite_facets_iterator Finite_facets_iterator
typedef HashSet< Pair< label >, FixedList< label, 2 >::Hash<> > labelPairHashSet
typedef HashTable< label, labelPair, FixedList< label, 2 >::Hash<> > labelTolabelPairHashTable
Public Member Functions
ClassName ("cellShapeControlMesh")
Runtime type information.
cellShapeControlMesh (const Time &runTime)
~cellShapeControlMesh ()
Destructor.
const Time & time () const
void barycentricCoords (const Foam::point &pt, scalarList &bary, Cell_handle &ch) const
Calculate and return the barycentric coordinates for.
boundBox bounds () const
label removePoints ()
tmp< pointField > cellCentres () const
Get the centres of all the tets.
Vertex_handle insert (const Foam::point &pt, const scalar &size, const triad &alignment, const Foam::indexedVertexEnum::vertexType type=Vb::vtInternal)
Vertex_handle insertFar (const Foam::point &pt)
void distribute (const backgroundMeshDecomposition &decomposition)
tensorField dumpAlignments () const
void writeTriangulation ()
void write () const
label estimateCellCount (const autoPtr< backgroundMeshDecomposition > &decomposition) const
Public Member Functions inherited from DistributedDelaunayMesh< CellSizeDelaunay >
DistributedDelaunayMesh (const Time &runTime)
Construct from components.
DistributedDelaunayMesh (const Time &runTime, const word &meshName)
~DistributedDelaunayMesh ()
Destructor.
scalar calculateLoadUnbalance () const
bool distribute (const boundBox &bb)
autoPtr< mapDistribute > distribute (const backgroundMeshDecomposition &decomposition, List< Foam::point > &points)
void sync (const boundBox &bb)
Refer vertices so that the processor interfaces are consistent.
void sync (const boundBox &bb, PtrList< labelPairHashSet > &referralVertices, labelPairHashSet &receivedVertices, bool iterateReferral=true)
Refer vertices so that the processor interfaces are consistent.
labelPairHashSet rangeInsertReferredWithInfo (PointIterator begin, PointIterator end, bool printErrors=true)
Inserts points into the triangulation if the point is within.
Public Member Functions inherited from DelaunayMesh< CellSizeDelaunay >
DelaunayMesh (const Time &runTime)
Construct from components.
DelaunayMesh (const Time &runTime, const word &meshName)
~DelaunayMesh ()
Destructor.
const Time & time () const
Return a reference to the Time object.
void timeCheck (const string &description, const bool check=true) const
Write the cpuTime to screen.
label getNewCellIndex () const
Create a new unique cell index and return.
label getNewVertexIndex () const
Create a new unique vertex index and return.
label cellCount () const
Return the cell count (the next unique cell index)
label vertexCount () const
Return the vertex count (the next unique vertex index)
void resetCellCount ()
Set the cell count to zero.
void resetVertexCount ()
Set the vertex count to zero.
void reset ()
Clear the entire triangulation.
Map< label > insertPoints (const List< Vb > &vertices, const bool reIndex)
Insert the list of vertices (calls rangeInsertWithInfo)
Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors=false, bool reIndex=true)
Function inserting points into a triangulation and setting the.
void printInfo (Ostream &os) const
Write mesh statistics to stream.
void printVertexInfo (Ostream &os) const
Write vertex statistics in the form of a table to stream.
autoPtr< polyMesh > createMesh (const fileName &name, labelTolabelPairHashTable &vertexMap, labelList &cellMap, const bool writeDelaunayData=true) const
Create an fvMesh from the triangulation.
Static Public Attributes
static word meshSubDir
Return the mesh sub-directory name (usually "cellShapeControlMesh")
Additional Inherited Members
Static Public Member Functions inherited from DistributedDelaunayMesh< CellSizeDelaunay >
static autoPtr< mapDistribute > buildMap (const List< label > &toProc)
Build a mapDistribute for the supplied destination processor data.
Detailed Description
Source files
cellShapeControlMesh.H
cellShapeControlMeshI.H
cellShapeControlMesh.C
Definition at line 61 of file cellShapeControlMesh.H.
Member Typedef Documentation
Cell_handle
typedef CellSizeDelaunay::Cell_handle Cell_handle
Definition at line 67 of file cellShapeControlMesh.H.
Vertex_handle
typedef CellSizeDelaunay::Vertex_handle Vertex_handle
Definition at line 68 of file cellShapeControlMesh.H.
Point
typedef CellSizeDelaunay::Point Point
Definition at line 69 of file cellShapeControlMesh.H.
Constructor & Destructor Documentation
cellShapeControlMesh()
cellShapeControlMesh (const Time & runTime) explicit
~cellShapeControlMesh()
~cellShapeControlMesh ()
Destructor.
Member Function Documentation
ClassName()
ClassName ("cellShapeControlMesh")
Runtime type information.
time()
const Time& time () const inline
Definition at line 114 of file cellShapeControlMesh.H.
References cellShapeControlMesh::barycentricCoords(), cellShapeControlMesh::bounds(), cellShapeControlMesh::cellCentres(), cellShapeControlMesh::distribute(), cellShapeControlMesh::dumpAlignments(), cellShapeControlMesh::estimateCellCount(), cellShapeControlMesh::insert(), cellShapeControlMesh::insertFar(), cellShapeControlMesh::removePoints(), Foam::type(), indexedVertexEnum::vtInternal, cellShapeControlMesh::write(), and cellShapeControlMesh::writeTriangulation().
barycentricCoords()
void barycentricCoords (const Foam::point & pt, scalarList & bary, Cell_handle & ch) const
Calculate and return the barycentric coordinates for.
interpolating quantities on the background mesh
Referenced by cellShapeControlMesh::time().
bounds()
boundBox bounds () const
Referenced by cellShapeControlMesh::time().
removePoints()
label removePoints ()
Referenced by cellShapeControlMesh::time().
cellCentres()
tmp<pointField> cellCentres () const
Get the centres of all the tets.
Referenced by cellShapeControlMesh::time().
insert()
Foam::cellShapeControlMesh::Vertex_handle insert (const Foam::point & pt, const scalar & size, const triad & alignment, const Foam::indexedVertexEnum::vertexType type = Vb::vtInternal) inline
Definition at line 29 of file cellShapeControlMeshI.H.
References insert(), cellShapeControlMesh::insertFar(), Foam::type(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cellShapeControlMesh::time().
insertFar()
Foam::cellShapeControlMesh::Vertex_handle insertFar (const Foam::point & pt) inline
Definition at line 51 of file cellShapeControlMeshI.H.
References insert(), indexedVertexEnum::vtFar, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cellShapeControlMesh::insert(), and cellShapeControlMesh::time().
distribute()
void distribute (const backgroundMeshDecomposition & decomposition)
Referenced by cellShapeControlMesh::time().
dumpAlignments()
tensorField dumpAlignments () const
Referenced by cellShapeControlMesh::time().
writeTriangulation()
void writeTriangulation ()
Referenced by cellShapeControlMesh::time().
write()
void write () const
Referenced by cellShapeControlMesh::time().
estimateCellCount()
label estimateCellCount (const autoPtr< backgroundMeshDecomposition > & decomposition) const
Referenced by cellShapeControlMesh::time().
Member Data Documentation
meshSubDir
word meshSubDir static
Return the mesh sub-directory name (usually "cellShapeControlMesh")
Definition at line 98 of file cellShapeControlMesh.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/cellShapeControl/cellShapeControlMesh/cellShapeControlMesh.H
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/cellShapeControl/cellShapeControlMesh/cellShapeControlMeshI.H