OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
RASModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for RAS turbulence models.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Static Public Member Functions
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Protected Member Functions
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModel< BasicTurbulenceModel >
Templated abstract base class for RAS turbulence models.
Source files
RASModel.H
RASModel.C
Definition at line 55 of file RASModel.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 105 of file RASModel.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 106 of file RASModel.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 107 of file RASModel.H.
Constructor & Destructor Documentation
RASModel()
RASModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 44 of file RASModel.C.
~RASModel()
virtual ~RASModel () inline virtual
Destructor.
Definition at line 166 of file RASModel.H.
Member Function Documentation
printCoeffs()
void printCoeffs (const word & type) protected virtual
Print model coefficients.
Definition at line 31 of file RASModel.C.
TypeName()
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , RASModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
New()
Foam::autoPtr< Foam::RASModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected RAS model.
Definition at line 115 of file RASModel.C.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::RASModel().
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented in mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, LaheyKEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, buoyantKEpsilon< BasicTurbulenceModel >, phasePressureModel, eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >, and eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 184 of file RASModel.C.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::~RASModel().
kMin() [1/2]
const dimensionedScalar& kMin () const inline
Return the lower allowable limit for k (default: SMALL)
Definition at line 179 of file RASModel.H.
epsilonMin() [1/2]
const dimensionedScalar& epsilonMin () const inline
Return the lower allowable limit for epsilon (default: SMALL)
Definition at line 185 of file RASModel.H.
omegaMin() [1/2]
const dimensionedScalar& omegaMin () const inline
Return the lower allowable limit for omega (default: SMALL)
Definition at line 191 of file RASModel.H.
kMin() [2/2]
dimensionedScalar& kMin () inline
Allow kMin to be changed.
Definition at line 197 of file RASModel.H.
epsilonMin() [2/2]
dimensionedScalar& epsilonMin () inline
Allow epsilonMin to be changed.
Definition at line 203 of file RASModel.H.
omegaMin() [2/2]
dimensionedScalar& omegaMin () inline
Allow omegaMin to be changed.
Definition at line 209 of file RASModel.H.
coeffDict()
virtual const dictionary& coeffDict () const inline virtual
Const access to the coefficients dictionary.
Definition at line 215 of file RASModel.H.
nuEff() [1/2]
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Reimplemented in kineticTheoryModel, continuousGasKEpsilon< BasicTurbulenceModel >, and phasePressureModel.
Definition at line 222 of file RASModel.H.
nuEff() [2/2]
virtual tmp<scalarField> nuEff (const label patchi) const inline virtual
Return the effective viscosity on patch.
Reimplemented in kineticTheoryModel, and phasePressureModel.
Definition at line 235 of file RASModel.H.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented in mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, kEpsilon< BasicTurbulenceModel >, phasePressureModel, LaheyKEpsilon< BasicTurbulenceModel >, eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >, and eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 177 of file RASModel.C.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::nuEff().
Member Data Documentation
RASDict_
dictionary RASDict_ protected
RAS coefficients dictionary.
Definition at line 65 of file RASModel.H.
turbulence_
Switch turbulence_ protected
Turbulence on/off flag.
Definition at line 68 of file RASModel.H.
printCoeffs_
Switch printCoeffs_ protected
Flag to print the model coeffs at run-time.
Definition at line 71 of file RASModel.H.
coeffDict_
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 74 of file RASModel.H.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::coeffDict().
kMin_
dimensionedScalar kMin_ protected
Lower limit of k.
Definition at line 77 of file RASModel.H.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::kMin().
epsilonMin_
dimensionedScalar epsilonMin_ protected
Lower limit of epsilon.
Definition at line 80 of file RASModel.H.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::epsilonMin().
omegaMin_
dimensionedScalar omegaMin_ protected
Lower limit for omega.
Definition at line 83 of file RASModel.H.
Referenced by RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::omegaMin().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/RASModel/RASModel.H
src/TurbulenceModels/turbulenceModels/RAS/RASModel/RASModel.C