OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
hexBlock Class Reference
Hex block definition used in the cfx converter.
Public Member Functions
hexBlock (const label nx, const label ny, const label nz)
Construct from components.
label xDim () const
Number of points.
label yDim () const
label zDim () const
label nBlockPoints () const
label nBlockCells () const
const pointField & points () const
Return block points.
labelListList blockCells () const
Return block cells.
faceList patchFaces (label direc, const labelList &range) const
Return block patch faces given direction and range limits.
void readPoints (Istream &)
Read block points.
hexBlock (const label nx, const label ny, const label nz)
Construct from components.
label xDim () const
Number of points.
label yDim () const
label zDim () const
label nBlockPoints () const
label nBlockCells () const
const pointField & points () const
Return block points.
labelListList blockCells () const
Return block cells.
faceList patchFaces (label direc, const labelList &range) const
Return block patch faces given direction and range limits.
void readPoints (const bool readBlank, const scalar twoDThicknes, Istream &)
Read block points either with or without blanking after every block.
Detailed Description
Hex block definition used in the cfx converter.
Source files
hexBlock.H
hexBlock.C
Definition at line 50 of file hexBlock.H.
Constructor & Destructor Documentation
hexBlock() [1/2]
hexBlock (const label nx, const label ny, const label nz)
Construct from components.
hexBlock() [2/2]
hexBlock (const label nx, const label ny, const label nz)
Construct from components.
Member Function Documentation
xDim() [1/2]
label xDim () const inline
Number of points.
Definition at line 96 of file hexBlock.H.
yDim() [1/2]
label yDim () const inline
Definition at line 101 of file hexBlock.H.
zDim() [1/2]
label zDim () const inline
Definition at line 106 of file hexBlock.H.
nBlockPoints() [1/2]
label nBlockPoints () const inline
Definition at line 111 of file hexBlock.H.
nBlockCells() [1/2]
label nBlockCells () const inline
Definition at line 116 of file hexBlock.H.
points() [1/2]
const pointField& points () const inline
Return block points.
Definition at line 122 of file hexBlock.H.
References Foam::abort(), hexBlock::blockCells(), Foam::FatalError, FatalErrorIn, hexBlock::patchFaces(), range, and hexBlock::readPoints().
blockCells() [1/2]
labelListList blockCells () const
Return block cells.
Referenced by hexBlock::points().
patchFaces() [1/2]
faceList patchFaces (label direc, const labelList & range) const
Return block patch faces given direction and range limits.
From the cfx manual: direction 0 = solid (3-D patch), 1 = high i, 2 = high j, 3 = high k 4 = low i, 5 = low j, 6 = low k
Referenced by hexBlock::points().
readPoints() [1/2]
void readPoints (Istream &)
Read block points.
Referenced by hexBlock::points().
xDim() [2/2]
label xDim () const inline
Number of points.
Definition at line 97 of file hexBlock.H.
yDim() [2/2]
label yDim () const inline
Definition at line 102 of file hexBlock.H.
zDim() [2/2]
label zDim () const inline
Definition at line 107 of file hexBlock.H.
nBlockPoints() [2/2]
label nBlockPoints () const inline
Definition at line 112 of file hexBlock.H.
nBlockCells() [2/2]
label nBlockCells () const inline
Definition at line 117 of file hexBlock.H.
points() [2/2]
const pointField& points () const inline
Return block points.
Definition at line 123 of file hexBlock.H.
References Foam::abort(), hexBlock::blockCells(), Foam::FatalError, FatalErrorIn, hexBlock::patchFaces(), range, and hexBlock::readPoints().
blockCells() [2/2]
labelListList blockCells () const
Return block cells.
patchFaces() [2/2]
faceList patchFaces (label direc, const labelList & range) const
Return block patch faces given direction and range limits.
From the cfx manual: direction 0 = solid (3-D patch), 1 = high i, 2 = high j, 3 = high k 4 = low i, 5 = low j, 6 = low k
readPoints() [2/2]
void readPoints (const bool readBlank, const scalar twoDThicknes, Istream &)
Read block points either with or without blanking after every block.
If twoDThickness > 0 reads (half) the points and extrudes the points in z direction.
The documentation for this class was generated from the following file:
applications/utilities/mesh/conversion/cfx4ToFoam/hexBlock.H