OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
conformalVoronoiMesh Class Reference
Public Types
enum dualMeshPointType {
internal = 0, surface = 1, featureEdge = 2, featurePoint = 3,
constrained = 4
}
typedef Delaunay::Vertex_handle Vertex_handle
typedef Delaunay::Cell_handle Cell_handle
typedef Delaunay::Edge Edge
typedef Delaunay::Facet Facet
typedef Delaunay::Point Point
typedef List< DynamicList< Pair< labelPair > > > labelPairPairDynListList
typedef Tuple2< pointIndexHit, label > pointIndexHitAndFeature
typedef List< pointIndexHitAndFeature > pointIndexHitAndFeatureList
typedef DynamicList< pointIndexHitAndFeature > pointIndexHitAndFeatureDynList
Public Types inherited from DistributedDelaunayMesh< Delaunay >
typedef Delaunay ::Vertex_handle Vertex_handle
typedef Delaunay ::Cell_handle Cell_handle
typedef Delaunay ::Point Point
typedef Delaunay ::Finite_vertices_iterator Finite_vertices_iterator
typedef Delaunay ::Finite_cells_iterator Finite_cells_iterator
typedef Delaunay ::All_cells_iterator All_cells_iterator
typedef DelaunayMesh< Delaunay >::labelPairHashSet labelPairHashSet
Public Types inherited from DelaunayMesh< Delaunay >
typedef Delaunay ::Cell_handle Cell_handle
typedef Delaunay ::Vertex_handle Vertex_handle
typedef Delaunay ::Edge Edge
typedef Delaunay ::Point Point
typedef Delaunay ::Facet Facet
typedef Delaunay ::Finite_vertices_iterator Finite_vertices_iterator
typedef Delaunay ::Finite_cells_iterator Finite_cells_iterator
typedef Delaunay ::Finite_facets_iterator Finite_facets_iterator
typedef HashSet< Pair< label >, FixedList< label, 2 >::Hash<> > labelPairHashSet
typedef HashTable< label, labelPair, FixedList< label, 2 >::Hash<> > labelTolabelPairHashTable
Public Member Functions
ClassName ("conformalVoronoiMesh")
Runtime type information.
conformalVoronoiMesh (const Time &runTime, const dictionary &foamyHexMeshDict)
Construct from Time and foamyHexMeshDict.
~conformalVoronoiMesh ()
Destructor.
void initialiseForMotion ()
void initialiseForConformation ()
void move ()
Move the vertices according to the controller, re-conforming to the.
const Time & time () const
Return the Time object.
Random & rndGen () const
Return the random number generator.
const searchableSurfaces & allGeometry () const
Return the allGeometry object.
const conformationSurfaces & geometryToConformTo () const
Return the conformationSurfaces object.
const backgroundMeshDecomposition & decomposition () const
Return the backgroundMeshDecomposition.
const cellShapeControl & cellShapeControls () const
Return the cellShapeControl object.
const cvControls & foamyHexMeshControls () const
Return the foamyHexMeshControls object.
scalar pointPairDistance (const Foam::point &pt) const
Return the local point pair separation at the given location.
scalar mixedFeaturePointDistance (const Foam::point &pt) const
Return the local mixed feature point placement distance.
scalar featurePointExclusionDistanceSqr (const Foam::point &pt) const
Return the square of the local feature point exclusion distance.
scalar featureEdgeExclusionDistanceSqr (const Foam::point &pt) const
Return the square of the local feature edge exclusion distance.
scalar surfacePtExclusionDistanceSqr (const Foam::point &pt) const
Return the square of the local surface point exclusion distance.
scalar surfaceSearchDistanceSqr (const Foam::point &pt) const
Return the square of the local surface search distance.
scalar maxSurfaceProtrusion (const Foam::point &pt) const
Return the local maximum surface protrusion distance.
void createEdgePointGroup (const extendedFeatureEdgeMesh &feMesh, const pointIndexHit &edHit, DynamicList< Vb > &pts) const
Call the appropriate function to conform to an edge.
void timeCheck (const string &description=string::null) const
void writeMesh (const fileName &instance)
Prepare data and call writeMesh for polyMesh and.
void writeMesh (const word &meshName, const fileName &instance, pointField &points, labelList &boundaryPts, faceList &faces, labelList &owner, labelList &neighbour, const wordList &patchNames, const PtrList< dictionary > &patchDicts, const pointField &cellCentres, PackedBoolList &boundaryFacesToRemove) const
Write mesh to disk.
void writeCellSizes (const fvMesh &mesh) const
Calculate and write a field of the target cell size,.
void writeCellAlignments (const fvMesh &mesh) const
void writeCellCentres (const fvMesh &mesh) const
Calculate and write the cell centres.
labelHashSet findRemainingProtrusionSet (const polyMesh &mesh) const
Find the cellSet of the boundary cells which have points that.
Public Member Functions inherited from DistributedDelaunayMesh< Delaunay >
DistributedDelaunayMesh (const Time &runTime)
Construct from components.
DistributedDelaunayMesh (const Time &runTime, const word &meshName)
~DistributedDelaunayMesh ()
Destructor.
scalar calculateLoadUnbalance () const
bool distribute (const boundBox &bb)
autoPtr< mapDistribute > distribute (const backgroundMeshDecomposition &decomposition, List< Foam::point > &points)
void sync (const boundBox &bb)
Refer vertices so that the processor interfaces are consistent.
void sync (const boundBox &bb, PtrList< labelPairHashSet > &referralVertices, labelPairHashSet &receivedVertices, bool iterateReferral=true)
Refer vertices so that the processor interfaces are consistent.
labelPairHashSet rangeInsertReferredWithInfo (PointIterator begin, PointIterator end, bool printErrors=true)
Inserts points into the triangulation if the point is within.
Public Member Functions inherited from DelaunayMesh< Delaunay >
DelaunayMesh (const Time &runTime)
Construct from components.
DelaunayMesh (const Time &runTime, const word &meshName)
~DelaunayMesh ()
Destructor.
const Time & time () const
Return a reference to the Time object.
void timeCheck (const string &description, const bool check=true) const
Write the cpuTime to screen.
label getNewCellIndex () const
Create a new unique cell index and return.
label getNewVertexIndex () const
Create a new unique vertex index and return.
label cellCount () const
Return the cell count (the next unique cell index)
label vertexCount () const
Return the vertex count (the next unique vertex index)
void resetCellCount ()
Set the cell count to zero.
void resetVertexCount ()
Set the vertex count to zero.
void reset ()
Clear the entire triangulation.
Map< label > insertPoints (const List< Vb > &vertices, const bool reIndex)
Insert the list of vertices (calls rangeInsertWithInfo)
Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors=false, bool reIndex=true)
Function inserting points into a triangulation and setting the.
void printInfo (Ostream &os) const
Write mesh statistics to stream.
void printVertexInfo (Ostream &os) const
Write vertex statistics in the form of a table to stream.
autoPtr< polyMesh > createMesh (const fileName &name, labelTolabelPairHashTable &vertexMap, labelList &cellMap, const bool writeDelaunayData=true) const
Create an fvMesh from the triangulation.
Static Public Member Functions
static void timeCheck (const Time &runTime, const string &description=string::null, const bool check=true)
Write the elapsedCpuTime and memory usage, with an optional.
Static Public Member Functions inherited from DistributedDelaunayMesh< Delaunay >
static autoPtr< mapDistribute > buildMap (const List< label > &toProc)
Build a mapDistribute for the supplied destination processor data.
Static Public Attributes
static const NamedEnum< dualMeshPointType, 5 > dualMeshPointTypeNames_
Detailed Description
Source files
conformalVoronoiMesh.H
conformalVoronoiMeshI.H
conformalVoronoiMesh.C
conformalVoronoiMeshZones.C
conformalVoronoiMeshIO.C
conformalVoronoiMeshConformToSurface.C
conformalVoronoiMeshFeaturePoints.C
conformalVoronoiMeshCalcDualMesh.C
conformalVoronoiMeshTemplates.C
Definition at line 97 of file conformalVoronoiMesh.H.
Member Typedef Documentation
Vertex_handle
typedef Delaunay::Vertex_handle Vertex_handle
Definition at line 103 of file conformalVoronoiMesh.H.
Cell_handle
typedef Delaunay::Cell_handle Cell_handle
Definition at line 104 of file conformalVoronoiMesh.H.
Edge
typedef Delaunay::Edge Edge
Definition at line 105 of file conformalVoronoiMesh.H.
Facet
typedef Delaunay::Facet Facet
Definition at line 106 of file conformalVoronoiMesh.H.
Point
typedef Delaunay::Point Point
Definition at line 107 of file conformalVoronoiMesh.H.
labelPairPairDynListList
typedef List<DynamicList<Pair<labelPair> > > labelPairPairDynListList
Definition at line 109 of file conformalVoronoiMesh.H.
pointIndexHitAndFeature
typedef Tuple2<pointIndexHit, label> pointIndexHitAndFeature
Definition at line 111 of file conformalVoronoiMesh.H.
pointIndexHitAndFeatureList
typedef List<pointIndexHitAndFeature> pointIndexHitAndFeatureList
Definition at line 112 of file conformalVoronoiMesh.H.
pointIndexHitAndFeatureDynList
typedef DynamicList<pointIndexHitAndFeature> pointIndexHitAndFeatureDynList
Definition at line 113 of file conformalVoronoiMesh.H.
Member Enumeration Documentation
dualMeshPointType
enum dualMeshPointType
Enumerator
internal
surface
featureEdge
featurePoint
constrained
Definition at line 117 of file conformalVoronoiMesh.H.
Constructor & Destructor Documentation
conformalVoronoiMesh()
conformalVoronoiMesh (const Time & runTime, const dictionary & foamyHexMeshDict)
Construct from Time and foamyHexMeshDict.
~conformalVoronoiMesh()
~conformalVoronoiMesh ()
Destructor.
Member Function Documentation
ClassName()
ClassName ("conformalVoronoiMesh")
Runtime type information.
initialiseForMotion()
void initialiseForMotion ()
initialiseForConformation()
void initialiseForConformation ()
move()
void move ()
Move the vertices according to the controller, re-conforming to the.
surface as required
time()
const Foam::Time & time () const inline
Return the Time object.
Definition at line 530 of file conformalVoronoiMeshI.H.
rndGen()
Foam::Random & rndGen () const inline
Return the random number generator.
Definition at line 536 of file conformalVoronoiMeshI.H.
allGeometry()
const Foam::searchableSurfaces & allGeometry () const inline
Return the allGeometry object.
Definition at line 543 of file conformalVoronoiMeshI.H.
geometryToConformTo()
const Foam::conformationSurfaces & geometryToConformTo () const inline
Return the conformationSurfaces object.
Definition at line 550 of file conformalVoronoiMeshI.H.
decomposition()
const Foam::backgroundMeshDecomposition & decomposition () const inline
Return the backgroundMeshDecomposition.
Definition at line 557 of file conformalVoronoiMeshI.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, and UPstream::parRun().
cellShapeControls()
const Foam::cellShapeControl & cellShapeControls () const inline
Return the cellShapeControl object.
Definition at line 575 of file conformalVoronoiMeshI.H.
foamyHexMeshControls()
const Foam::cvControls & foamyHexMeshControls () const inline
Return the foamyHexMeshControls object.
Definition at line 582 of file conformalVoronoiMeshI.H.
Referenced by conformalVoronoiMesh::featureEdgeExclusionDistanceSqr(), conformalVoronoiMesh::featurePointExclusionDistanceSqr(), conformalVoronoiMesh::maxSurfaceProtrusion(), conformalVoronoiMesh::mixedFeaturePointDistance(), conformalVoronoiMesh::pointPairDistance(), conformalVoronoiMesh::surfacePtExclusionDistanceSqr(), and conformalVoronoiMesh::surfaceSearchDistanceSqr().
pointPairDistance()
Foam::scalar pointPairDistance (const Foam::point & pt) const inline
Return the local point pair separation at the given location.
Definition at line 137 of file conformalVoronoiMeshI.H.
References conformalVoronoiMesh::foamyHexMeshControls(), conformalVoronoiMesh::mixedFeaturePointDistance(), and cvControls::pointPairDistanceCoeff().
Referenced by conformalVoronoiMesh::mixedFeaturePointDistance().
mixedFeaturePointDistance()
Foam::scalar mixedFeaturePointDistance (const Foam::point & pt) const inline
Return the local mixed feature point placement distance.
Definition at line 146 of file conformalVoronoiMeshI.H.
References conformalVoronoiMesh::featurePointExclusionDistanceSqr(), conformalVoronoiMesh::foamyHexMeshControls(), cvControls::mixedFeaturePointPPDistanceCoeff(), and conformalVoronoiMesh::pointPairDistance().
Referenced by conformalVoronoiMesh::pointPairDistance().
featurePointExclusionDistanceSqr()
Foam::scalar featurePointExclusionDistanceSqr (const Foam::point & pt) const inline
Return the square of the local feature point exclusion distance.
Definition at line 157 of file conformalVoronoiMeshI.H.
References conformalVoronoiMesh::featureEdgeExclusionDistanceSqr(), conformalVoronoiMesh::foamyHexMeshControls(), and Foam::sqr().
Referenced by conformalVoronoiMesh::mixedFeaturePointDistance().
featureEdgeExclusionDistanceSqr()
Foam::scalar featureEdgeExclusionDistanceSqr (const Foam::point & pt) const inline
Return the square of the local feature edge exclusion distance.
Definition at line 171 of file conformalVoronoiMeshI.H.
References conformalVoronoiMesh::foamyHexMeshControls(), Foam::sqr(), and conformalVoronoiMesh::surfacePtExclusionDistanceSqr().
Referenced by conformalVoronoiMesh::featurePointExclusionDistanceSqr().
surfacePtExclusionDistanceSqr()
Foam::scalar surfacePtExclusionDistanceSqr (const Foam::point & pt) const inline
Return the square of the local surface point exclusion distance.
Definition at line 185 of file conformalVoronoiMeshI.H.
References conformalVoronoiMesh::foamyHexMeshControls(), Foam::sqr(), and conformalVoronoiMesh::surfaceSearchDistanceSqr().
Referenced by conformalVoronoiMesh::featureEdgeExclusionDistanceSqr().
surfaceSearchDistanceSqr()
Foam::scalar surfaceSearchDistanceSqr (const Foam::point & pt) const inline
Return the square of the local surface search distance.
Definition at line 199 of file conformalVoronoiMeshI.H.
References conformalVoronoiMesh::foamyHexMeshControls(), conformalVoronoiMesh::maxSurfaceProtrusion(), and Foam::sqr().
Referenced by conformalVoronoiMesh::surfacePtExclusionDistanceSqr().
maxSurfaceProtrusion()
Foam::scalar maxSurfaceProtrusion (const Foam::point & pt) const inline
Return the local maximum surface protrusion distance.
Definition at line 213 of file conformalVoronoiMeshI.H.
References pointPairs< Triangulation >::addPointPair(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::constant::universal::c, Foam::constant::physicoChemical::c1, Foam::constant::physicoChemical::c2, treeBoundBox::contains(), Foam::e, Foam::findIndex(), conformalVoronoiMesh::foamyHexMeshControls(), forAll, conformationSurfaces::globalBounds(), conformationSurfaces::inside(), cvControls::maxSurfaceProtrusionCoeff(), UPstream::myProcNo(), n, CGAL::indexedCellOps::processorsAttached(), Random::scalar01(), List< T >::size(), DelaunayMesh< Delaunay >::vertexCount(), indexedVertexEnum::vtExternalSurface, indexedVertexEnum::vtExternalSurfaceBaffle, indexedVertexEnum::vtInternalSurface, indexedVertexEnum::vtInternalSurfaceBaffle, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by conformalVoronoiMesh::surfaceSearchDistanceSqr().
createEdgePointGroup()
void createEdgePointGroup (const extendedFeatureEdgeMesh & feMesh, const pointIndexHit & edHit, DynamicList< Vb > & pts) const
Call the appropriate function to conform to an edge.
timeCheck() [1/2]
static void timeCheck (const Time & runTime, const string & description = string::null, const bool check = true) static
Write the elapsedCpuTime and memory usage, with an optional.
description
timeCheck() [2/2]
void timeCheck (const string & description = string::null) const
writeMesh() [1/2]
void writeMesh (const fileName & instance)
Prepare data and call writeMesh for polyMesh and.
tetDualMesh
writeMesh() [2/2]
void writeMesh (const word & meshName, const fileName & instance, pointField & points, labelList & boundaryPts, faceList & faces, labelList & owner, labelList & neighbour, const wordList & patchNames, const PtrList< dictionary > & patchDicts, const pointField & cellCentres, PackedBoolList & boundaryFacesToRemove) const
Write mesh to disk.
writeCellSizes()
void writeCellSizes (const fvMesh & mesh) const
Calculate and write a field of the target cell size,.
target cell volume, actual cell volume and equivalent actual cell size (cbrt(actual cell volume)).
writeCellAlignments()
void writeCellAlignments (const fvMesh & mesh) const
writeCellCentres()
void writeCellCentres (const fvMesh & mesh) const
Calculate and write the cell centres.
findRemainingProtrusionSet()
labelHashSet findRemainingProtrusionSet (const polyMesh & mesh) const
Find the cellSet of the boundary cells which have points that.
protrude out of the surface beyond a tolerance.
Member Data Documentation
dualMeshPointTypeNames_
const NamedEnum<dualMeshPointType, 5> dualMeshPointTypeNames_ static
Definition at line 126 of file conformalVoronoiMesh.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/conformalVoronoiMesh/conformalVoronoiMesh.H
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/conformalVoronoiMesh/conformalVoronoiMeshI.H