OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
searchablePlateFeatures Class Reference
Public Member Functions
TypeName ("searchablePlateFeatures")
Runtime type information.
searchablePlateFeatures (const searchableSurface &surface, const dictionary &dict)
Construct from searchable surface and dictionary.
virtual ~searchablePlateFeatures ()
Destructor.
virtual bool hasFeatures () const
Return true for a searchable plate having features.
virtual autoPtr< extendedFeatureEdgeMesh > features () const
Return an extendedFeatureEdgeMesh containing the features.
Public Member Functions inherited from searchableSurfaceFeatures
TypeName ("searchableSurfaceFeatures")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurfaceFeatures, dict,(const searchableSurface &surface, const dictionary &dict),(surface, dict))
searchableSurfaceFeatures (const searchableSurface &surface, const dictionary &dict)
Construct from components.
virtual autoPtr< searchableSurfaceFeatures > clone () const
Clone.
virtual ~searchableSurfaceFeatures ()
Destructor.
const searchableSurface & surface () const
Return a reference to the searchable surface.
const dictionary & dict () const
Return a reference to the dictionary.
Static Public Attributes
static const edgeList edges
Edge to point addressing.
Additional Inherited Members
Static Public Member Functions inherited from searchableSurfaceFeatures
static autoPtr< searchableSurfaceFeatures > New (const searchableSurface &surface, const dictionary &dict)
Return a reference to the selected searchableSurfaceFeatures.
Detailed Description
Source files
searchablePlateFeatures.H
searchablePlateFeatures.C
Definition at line 47 of file searchablePlateFeatures.H.
Constructor & Destructor Documentation
searchablePlateFeatures()
searchablePlateFeatures (const searchableSurface & surface, const dictionary & dict)
Construct from searchable surface and dictionary.
Definition at line 79 of file searchablePlateFeatures.C.
References Foam::endl(), Foam::indent(), Foam::Info, and extendedEdgeMesh::sideVolumeTypeNames_.
~searchablePlateFeatures()
~searchablePlateFeatures () virtual
Destructor.
Definition at line 102 of file searchablePlateFeatures.C.
Member Function Documentation
TypeName()
TypeName ("searchablePlateFeatures")
Runtime type information.
hasFeatures()
virtual bool hasFeatures () const inline virtual
Return true for a searchable plate having features.
Implements searchableSurfaceFeatures.
Definition at line 101 of file searchablePlateFeatures.H.
References searchablePlateFeatures::features().
features()
Foam::autoPtr< Foam::extendedFeatureEdgeMesh > features () const virtual
Return an extendedFeatureEdgeMesh containing the features.
Reimplemented from searchableSurfaceFeatures.
Definition at line 109 of file searchablePlateFeatures.C.
References IOobject::AUTO_WRITE, Foam::cross(), Foam::e, edge::end(), forAll, searchableSurface::getNormal(), Foam::mag(), Foam::max(), Foam::min(), Foam::name(), IOobject::NO_READ, points, searchableSurface::points(), autoPtr< T >::set(), List< T >::setSize(), and edge::start().
Referenced by searchablePlateFeatures::hasFeatures().
Member Data Documentation
edges
const edgeList edges static
Edge to point addressing.
Definition at line 81 of file searchablePlateFeatures.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/searchableSurfaceFeatures/searchablePlateFeatures.H
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/searchableSurfaceFeatures/searchablePlateFeatures.C