OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
indexedFace< Gt, Fb > Class Template Reference
Classes
struct Rebind_TDS
Public Types
enum faceTypes { UNCHANGED = 0, CHANGED = -1, SAVE_CHANGED = -2 }
typedef Fb::Vertex_handle Vertex_handle
typedef Fb::Face_handle Face_handle
Public Member Functions
indexedFace ()
indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2)
indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Face_handle n0, Face_handle n1, Face_handle n2)
void set_vertex (int i, Vertex_handle v)
void set_vertices ()
void set_vertices (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2)
int & faceIndex ()
int faceIndex () const
Detailed Description
template<class Gt, class Fb = CGAL::Triangulation_face_base_2<Gt>>
class CGAL::indexedFace< Gt, Fb >
Definition at line 48 of file indexedFace.H.
Member Typedef Documentation
Vertex_handle
typedef Fb::Vertex_handle Vertex_handle
Definition at line 69 of file indexedFace.H.
Face_handle
typedef Fb::Face_handle Face_handle
Definition at line 70 of file indexedFace.H.
Member Enumeration Documentation
faceTypes
enum faceTypes
Enumerator
UNCHANGED
CHANGED
SAVE_CHANGED
Definition at line 62 of file indexedFace.H.
Constructor & Destructor Documentation
indexedFace() [1/3]
indexedFace () inline
Definition at line 29 of file indexedFaceI.H.
Referenced by indexedFace< Gt, Fb >::indexedFace().
indexedFace() [2/3]
indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2) inline
Definition at line 38 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::indexedFace().
indexedFace() [3/3]
indexedFace (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Face_handle n0, Face_handle n1, Face_handle n2) inline
Definition at line 51 of file indexedFaceI.H.
Member Function Documentation
set_vertex()
void set_vertex (int i, Vertex_handle v) inline
Definition at line 68 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::CHANGED.
set_vertices() [1/2]
void set_vertices () inline
Definition at line 76 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::CHANGED.
Referenced by indexedFace< Gt, Fb >::set_vertices().
set_vertices() [2/2]
void set_vertices (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2) inline
Definition at line 85 of file indexedFaceI.H.
References indexedFace< Gt, Fb >::CHANGED, and indexedFace< Gt, Fb >::set_vertices().
faceIndex() [1/2]
int & faceIndex () inline
Definition at line 97 of file indexedFaceI.H.
faceIndex() [2/2]
int faceIndex () const inline
Definition at line 104 of file indexedFaceI.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyQuadMesh/indexedFace.H
applications/utilities/mesh/generation/foamyQuadMesh/indexedFaceI.H