OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
searchableSurfaceFeatures Class Reference abstract
Decorator that returns the features of a searchable surface.
Public Member Functions
TypeName ("searchableSurfaceFeatures")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurfaceFeatures, dict,(const searchableSurface &surface, const dictionary &dict),(surface, dict))
searchableSurfaceFeatures (const searchableSurface &surface, const dictionary &dict)
Construct from components.
virtual autoPtr< searchableSurfaceFeatures > clone () const
Clone.
virtual ~searchableSurfaceFeatures ()
Destructor.
const searchableSurface & surface () const
Return a reference to the searchable surface.
const dictionary & dict () const
Return a reference to the dictionary.
virtual bool hasFeatures () const =0
Return whether this searchable surface has features.
virtual autoPtr< extendedFeatureEdgeMesh > features () const
Return an extendedFeatureEdgeMesh containing the features.
Static Public Member Functions
static autoPtr< searchableSurfaceFeatures > New (const searchableSurface &surface, const dictionary &dict)
Return a reference to the selected searchableSurfaceFeatures.
Detailed Description
Decorator that returns the features of a searchable surface.
Source files
searchableSurfaceFeatures.H
searchableSurfaceFeatures.C
Definition at line 51 of file searchableSurfaceFeatures.H.
Constructor & Destructor Documentation
searchableSurfaceFeatures()
searchableSurfaceFeatures (const searchableSurface & surface, const dictionary & dict)
Construct from components.
~searchableSurfaceFeatures()
virtual ~searchableSurfaceFeatures () virtual
Destructor.
Referenced by searchableSurfaceFeatures::clone().
Member Function Documentation
TypeName()
TypeName ("searchableSurfaceFeatures")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , searchableSurfaceFeatures , dict , (const searchableSurface &surface, const dictionary &dict) , (surface, dict))
clone()
virtual autoPtr<searchableSurfaceFeatures> clone () const inline virtual
Clone.
Definition at line 100 of file searchableSurfaceFeatures.H.
References searchableSurfaceFeatures::New(), notImplemented, and searchableSurfaceFeatures::~searchableSurfaceFeatures().
New()
static autoPtr<searchableSurfaceFeatures> New (const searchableSurface & surface, const dictionary & dict) static
Return a reference to the selected searchableSurfaceFeatures.
Referenced by searchableSurfaceFeatures::clone().
surface()
const searchableSurface& surface () const inline
Return a reference to the searchable surface.
Definition at line 124 of file searchableSurfaceFeatures.H.
dict()
const dictionary& dict () const inline
Return a reference to the dictionary.
Definition at line 130 of file searchableSurfaceFeatures.H.
References searchableSurfaceFeatures::hasFeatures().
hasFeatures()
virtual bool hasFeatures () const pure virtual
Return whether this searchable surface has features.
Implemented in searchablePlateFeatures, triSurfaceMeshFeatures, and searchableBoxFeatures.
Referenced by searchableSurfaceFeatures::dict().
features()
virtual autoPtr<extendedFeatureEdgeMesh> features () const inline virtual
Return an extendedFeatureEdgeMesh containing the features.
Reimplemented in searchablePlateFeatures, triSurfaceMeshFeatures, and searchableBoxFeatures.
Definition at line 139 of file searchableSurfaceFeatures.H.
The documentation for this class was generated from the following file:
applications/utilities/mesh/generation/foamyHexMesh/conformalVoronoiMesh/searchableSurfaceFeatures/searchableSurfaceFeatures.H