OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightAsciiStream Class Reference
Public Member Functions
ensightAsciiStream (const fileName &f, const Time &runTime)
Construct from components.
virtual ~ensightAsciiStream ()
Destructor.
virtual bool ascii () const
virtual void write (const char *c)
virtual void write (const int v)
virtual void write (const scalarField &sf)
virtual void write (const List< int > &sf)
virtual void writePartHeader (const label partI)
Public Member Functions inherited from ensightStream
ensightStream (const fileName &f)
Construct from components.
virtual ~ensightStream ()
Destructor.
const fileName & name () const
Detailed Description
Source files
ensightAsciiStream.H
ensightAsciiStream.C
Definition at line 48 of file ensightAsciiStream.H.
Constructor & Destructor Documentation
ensightAsciiStream()
ensightAsciiStream (const fileName & f, const Time & runTime) inline
Construct from components.
Definition at line 72 of file ensightAsciiStream.H.
References OSstream::precision(), Foam::scientific(), and IOstream::setf().
~ensightAsciiStream()
virtual ~ensightAsciiStream () inline virtual
Destructor.
Definition at line 90 of file ensightAsciiStream.H.
Member Function Documentation
ascii()
virtual bool ascii () const inline virtual
Implements ensightStream.
Definition at line 96 of file ensightAsciiStream.H.
write() [1/4]
virtual void write (const char * c) inline virtual
Implements ensightStream.
Definition at line 101 of file ensightAsciiStream.H.
References Foam::nl.
write() [2/4]
virtual void write (const int v) inline virtual
Implements ensightStream.
Definition at line 106 of file ensightAsciiStream.H.
References Foam::nl, and Foam::setw().
write() [3/4]
virtual void write (const scalarField & sf) inline virtual
Implements ensightStream.
Definition at line 111 of file ensightAsciiStream.H.
References Foam::floatScalarVSMALL, forAll, Foam::mag(), Foam::nl, and Foam::setw().
write() [4/4]
virtual void write (const List< int > & sf) inline virtual
Implements ensightStream.
Definition at line 126 of file ensightAsciiStream.H.
References forAll, Foam::nl, and Foam::setw().
writePartHeader()
virtual void writePartHeader (const label partI) inline virtual
Implements ensightStream.
Definition at line 135 of file ensightAsciiStream.H.
References Foam::nl, and Foam::setw().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToEnsight/ensightAsciiStream.H