OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightMesh Class Reference
Classes
class nFacePrimitives
Public Member Functions
ensightMesh (const fvMesh &mesh, const bool noPatches, const bool patches, const wordReList &patchPatterns, const bool faceZones, const wordReList &faceZonePatterns, const bool binary)
Construct from fvMesh.
~ensightMesh ()
Destructor.
const fvMesh & mesh () const
const cellSets & meshCellSets () const
const List< faceSets > & boundaryFaceSets () const
const wordList & allPatchNames () const
const wordHashSet & patchNames () const
const HashTable< nFacePrimitives > & nPatchPrims () const
const List< faceSets > & faceZoneFaceSets () const
const wordHashSet & faceZoneNames () const
const HashTable< nFacePrimitives > & nFaceZonePrims () const
label patchPartOffset () const
The ensight part id for the first patch.
const globalIndex & globalPoints () const
Global numbering for merged points.
const labelList & pointToGlobal () const
From mesh point to global merged point.
const labelList & uniquePointMap () const
Local points that are unique.
void correct ()
Update for new mesh.
bool faceToBeIncluded (const label faceI) const
When exporting faceZones, check if a given face has to be included.
void write (const fileName &postProcPath, const word &prepend, const label timeIndex, const bool meshMoving, Ostream &ensightCaseFile) const
Static Public Member Functions
static void barrier ()
Helper to cause barrier. Necessary on Quadrics.
Detailed Description
Source files
ensightMesh.H
ensightMesh.C
Definition at line 62 of file ensightMesh.H.
Constructor & Destructor Documentation
ensightMesh()
ensightMesh (const fvMesh & mesh, const bool noPatches, const bool patches, const wordReList & patchPatterns, const bool faceZones, const wordReList & faceZonePatterns, const bool binary)
Construct from fvMesh.
~ensightMesh()
~ensightMesh ()
Destructor.
Referenced by ensightMesh::nFacePrimitives::nFacePrimitives().
Member Function Documentation
mesh()
const fvMesh& mesh () const inline
Definition at line 281 of file ensightMesh.H.
Referenced by ensightMesh::nFacePrimitives::nFacePrimitives().
meshCellSets()
const cellSets& meshCellSets () const inline
Definition at line 286 of file ensightMesh.H.
boundaryFaceSets()
const List<faceSets>& boundaryFaceSets () const inline
Definition at line 291 of file ensightMesh.H.
allPatchNames()
const wordList& allPatchNames () const inline
Definition at line 296 of file ensightMesh.H.
patchNames()
const wordHashSet& patchNames () const inline
Definition at line 301 of file ensightMesh.H.
nPatchPrims()
const HashTable<nFacePrimitives>& nPatchPrims () const inline
Definition at line 306 of file ensightMesh.H.
faceZoneFaceSets()
const List<faceSets>& faceZoneFaceSets () const inline
Definition at line 311 of file ensightMesh.H.
faceZoneNames()
const wordHashSet& faceZoneNames () const inline
Definition at line 316 of file ensightMesh.H.
nFaceZonePrims()
const HashTable<nFacePrimitives>& nFaceZonePrims () const inline
Definition at line 321 of file ensightMesh.H.
patchPartOffset()
label patchPartOffset () const inline
The ensight part id for the first patch.
Definition at line 327 of file ensightMesh.H.
globalPoints()
const globalIndex& globalPoints () const inline
Global numbering for merged points.
Definition at line 336 of file ensightMesh.H.
pointToGlobal()
const labelList& pointToGlobal () const inline
From mesh point to global merged point.
Definition at line 342 of file ensightMesh.H.
Referenced by ensightMesh::nFacePrimitives::nFacePrimitives().
uniquePointMap()
const labelList& uniquePointMap () const inline
Local points that are unique.
Definition at line 348 of file ensightMesh.H.
References ensightMesh::barrier(), ensightMesh::correct(), ensightMesh::faceToBeIncluded(), meshMoving, timeIndex, and ensightMesh::write().
correct()
void correct ()
Update for new mesh.
Referenced by ensightMesh::uniquePointMap().
faceToBeIncluded()
bool faceToBeIncluded (const label faceI) const
When exporting faceZones, check if a given face has to be included.
or not (i.e. faces on processor boundaries)
Referenced by ensightMesh::uniquePointMap().
barrier()
static void barrier () static
Helper to cause barrier. Necessary on Quadrics.
Referenced by ensightMesh::uniquePointMap().
write()
void write (const fileName & postProcPath, const word & prepend, const label timeIndex, const bool meshMoving, Ostream & ensightCaseFile) const
Referenced by ensightMesh::uniquePointMap().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToEnsight/ensightMesh.H