OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
shortEdgeFilter2D Class Reference
This class filters short edges generated by the CV2D mesher.
Public Member Functions
ClassName ("shortEdgeFilter2D")
Runtime type information.
shortEdgeFilter2D (const CV2D &cv2Dmesh, const dictionary &dict)
~shortEdgeFilter2D ()
Destructor.
const wordList & patchNames () const
const labelList & patchSizes () const
const EdgeMap< label > & mapEdgesRegion () const
const MeshedSurface< face > & fMesh () const
void filter ()
void writeInfo (Ostream &os)
Detailed Description
This class filters short edges generated by the CV2D mesher.
Source files
shortEdgeFilter2D.H
shortEdgeFilter2D.C
Definition at line 49 of file shortEdgeFilter2D.H.
Constructor & Destructor Documentation
shortEdgeFilter2D()
shortEdgeFilter2D (const CV2D & cv2Dmesh, const dictionary & dict)
~shortEdgeFilter2D()
~shortEdgeFilter2D ()
Destructor.
Member Function Documentation
ClassName()
ClassName ("shortEdgeFilter2D")
Runtime type information.
patchNames()
const wordList& patchNames () const inline
Definition at line 115 of file shortEdgeFilter2D.H.
patchSizes()
const labelList& patchSizes () const inline
Definition at line 120 of file shortEdgeFilter2D.H.
mapEdgesRegion()
const EdgeMap<label>& mapEdgesRegion () const inline
Definition at line 125 of file shortEdgeFilter2D.H.
fMesh()
const MeshedSurface<face>& fMesh () const inline
Definition at line 130 of file shortEdgeFilter2D.H.
References shortEdgeFilter2D::filter(), and shortEdgeFilter2D::writeInfo().
filter()
void filter ()
Referenced by shortEdgeFilter2D::fMesh().
writeInfo()
void writeInfo (Ostream & os)
Referenced by shortEdgeFilter2D::fMesh().
The documentation for this class was generated from the following file:
applications/utilities/mesh/generation/foamyQuadMesh/shortEdgeFilter2D.H