OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightMesh::nFacePrimitives Class Reference
Public Member Functions
nFacePrimitives ()
Public Attributes
label nTris
label nQuads
label nPolys
Detailed Description
Definition at line 65 of file ensightMesh.H.
Constructor & Destructor Documentation
nFacePrimitives()
nFacePrimitives () inline
Definition at line 73 of file ensightMesh.H.
References cellShapes, ensightMesh::mesh(), nPoints, patches, ensightMesh::pointToGlobal(), and ensightMesh::~ensightMesh().
Member Data Documentation
nTris
label nTris
Definition at line 69 of file ensightMesh.H.
nQuads
label nQuads
Definition at line 70 of file ensightMesh.H.
nPolys
label nPolys
Definition at line 71 of file ensightMesh.H.
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToEnsight/ensightMesh.H