OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightStream Class Reference abstract
Abstract base class for writing Ensight data.
Public Member Functions
ensightStream (const fileName &f)
Construct from components.
virtual ~ensightStream ()
Destructor.
const fileName & name () const
virtual bool ascii () const =0
virtual void write (const char *)=0
virtual void write (const int)=0
virtual void write (const scalarField &)=0
virtual void write (const List< int > &)=0
virtual void writePartHeader (const label)=0
Detailed Description
Abstract base class for writing Ensight data.
Source files
ensightStream.H
ensightStream.C
Definition at line 50 of file ensightStream.H.
Constructor & Destructor Documentation
ensightStream()
ensightStream (const fileName & f) inline
Construct from components.
Definition at line 70 of file ensightStream.H.
~ensightStream()
virtual ~ensightStream () inline virtual
Destructor.
Definition at line 77 of file ensightStream.H.
Member Function Documentation
name()
const fileName& name () const inline
Definition at line 83 of file ensightStream.H.
References ensightStream::ascii(), ensightStream::write(), and ensightStream::writePartHeader().
ascii()
virtual bool ascii () const pure virtual
Implemented in ensightAsciiStream, and ensightBinaryStream.
Referenced by ensightStream::name().
write() [1/4]
virtual void write (const char *) pure virtual
Implemented in ensightAsciiStream, and ensightBinaryStream.
Referenced by ensightStream::name().
write() [2/4]
virtual void write (const int) pure virtual
Implemented in ensightAsciiStream, and ensightBinaryStream.
write() [3/4]
virtual void write (const scalarField &) pure virtual
Implemented in ensightAsciiStream, and ensightBinaryStream.
write() [4/4]
virtual void write (const List< int > &) pure virtual
Implemented in ensightBinaryStream, and ensightAsciiStream.
writePartHeader()
virtual void writePartHeader (const label) pure virtual
Implemented in ensightBinaryStream, and ensightAsciiStream.
Referenced by ensightStream::name().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToEnsight/ensightStream.H