OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightBinaryStream Class Reference
Public Member Functions
ensightBinaryStream (const fileName &f, const Time &)
Construct from components.
virtual ~ensightBinaryStream ()
Destructor.
virtual bool ascii () const
virtual void write (const char *val)
virtual void write (const int val)
virtual void write (const scalarField &sf)
virtual void write (const List< int > &sf)
virtual void writePartHeader (const label partI)
Public Member Functions inherited from ensightStream
ensightStream (const fileName &f)
Construct from components.
virtual ~ensightStream ()
Destructor.
const fileName & name () const
Detailed Description
Source files
ensightBinaryStream.H
ensightBinaryStream.C
Definition at line 47 of file ensightBinaryStream.H.
Constructor & Destructor Documentation
ensightBinaryStream()
ensightBinaryStream (const fileName & f, const Time &) inline
Construct from components.
Definition at line 71 of file ensightBinaryStream.H.
~ensightBinaryStream()
virtual ~ensightBinaryStream () inline virtual
Destructor.
Definition at line 86 of file ensightBinaryStream.H.
Member Function Documentation
ascii()
virtual bool ascii () const inline virtual
Implements ensightStream.
Definition at line 92 of file ensightBinaryStream.H.
write() [1/4]
virtual void write (const char * val) inline virtual
Implements ensightStream.
Definition at line 97 of file ensightBinaryStream.H.
Referenced by ensightBinaryStream::writePartHeader().
write() [2/4]
virtual void write (const int val) inline virtual
Implements ensightStream.
Definition at line 104 of file ensightBinaryStream.H.
write() [3/4]
virtual void write (const scalarField & sf) inline virtual
Implements ensightStream.
Definition at line 109 of file ensightBinaryStream.H.
References forAll, and List< T >::size().
write() [4/4]
virtual void write (const List< int > & sf) inline virtual
Implements ensightStream.
Definition at line 128 of file ensightBinaryStream.H.
References UList< T >::begin(), and List< T >::size().
writePartHeader()
virtual void writePartHeader (const label partI) inline virtual
Implements ensightStream.
Definition at line 137 of file ensightBinaryStream.H.
References ensightBinaryStream::write().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToEnsight/ensightBinaryStream.H