OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointFieldDecomposer Class Reference
Point field decomposer.
Classes
class patchFieldDecomposer
Point patch field decomposer class.
Public Member Functions
pointFieldDecomposer (const pointMesh &completeMesh, const pointMesh &procMesh, const labelList &pointAddressing, const labelList &boundaryAddressing)
Construct from components.
~pointFieldDecomposer ()
Destructor.
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > decomposeField (const GeometricField< Type, pointPatchField, pointMesh > &) const
Decompose point field.
template<class GeoField >
void decomposeFields (const PtrList< GeoField > &fields) const
Detailed Description
Point field decomposer.
Source files
pointFieldDecomposer.H
pointFieldDecomposer.C
pointFieldDecomposerDecomposeFields.C
Definition at line 51 of file pointFieldDecomposer.H.
Constructor & Destructor Documentation
pointFieldDecomposer()
pointFieldDecomposer (const pointMesh & completeMesh, const pointMesh & procMesh, const labelList & pointAddressing, const labelList & boundaryAddressing)
Construct from components.
~pointFieldDecomposer()
~pointFieldDecomposer ()
Destructor.
Referenced by pointFieldDecomposer::patchFieldDecomposer::directAddressing().
Member Function Documentation
decomposeField()
tmp<GeometricField<Type, pointPatchField, pointMesh> > decomposeField (const GeometricField< Type, pointPatchField, pointMesh > &) const
Decompose point field.
Referenced by pointFieldDecomposer::patchFieldDecomposer::directAddressing().
decomposeFields()
void decomposeFields (const PtrList< GeoField > & fields) const
Referenced by pointFieldDecomposer::patchFieldDecomposer::directAddressing().
The documentation for this class was generated from the following file:
applications/utilities/parallelProcessing/decomposePar/pointFieldDecomposer.H