OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vtkPV4Foam Class Reference
Provides a reader interface for OpenFOAM to VTK interaction.
Public Member Functions
ClassName ("vtkPV4Foam")
Static data members.
vtkPV4Foam (const char *const FileName, vtkPV4FoamReader *reader)
Construct from components.
~vtkPV4Foam ()
Destructor.
void updateInfo ()
Update.
void Update (vtkMultiBlockDataSet *output, vtkMultiBlockDataSet *lagrangianOutput)
void CleanUp ()
Clean any storage.
double * findTimes (int &nTimeSteps)
Allocate and return a list of selected times.
void renderPatchNames (vtkRenderer *, const bool show)
Add/remove patch names to/from the view.
int setTime (int count, const double requestTimes[])
set the runTime to the first plausible request time,
int timeIndex () const
The current time index.
void PrintSelf (ostream &, vtkIndent) const
Debug information.
template<class Type >
Foam::label addToSelection (vtkDataArraySelection *select, const IOobjectList &objectLst, const string &suffix)
Static Public Member Functions
static void printMemory ()
Simple memory used debugging information.
Detailed Description
Provides a reader interface for OpenFOAM to VTK interaction.
Source files
vtkPV4Foam.H
vtkPV4Foam.C
vtkPV4Foam.H
vtkPV4FoamFields.C
vtkPV4FoamMesh.C
vtkPV4FoamMeshLagrangian.C
vtkPV4FoamTemplates.C
vtkPV4FoamMeshSet.C
vtkPV4FoamMeshVolume.C
vtkPV4FoamMeshZone.C
vtkPV4FoamFaceField.H
vtkPV4FoamLagrangianFields.H
vtkPV4FoamPatchField.H
vtkPV4FoamPointFields.H
vtkPV4FoamPoints.H
vtkPV4FoamUpdateInfo.C
vtkPV4FoamUpdateInfoFields.H
vtkPV4FoamUtils.C
vtkPV4FoamVolFields.H
vtkPV4FoamAddToSelection.H
Needed by VTK: vtkDataArrayTemplateImplicit.txx
Definition at line 107 of file vtkPV4Foam.H.
Constructor & Destructor Documentation
vtkPV4Foam()
vtkPV4Foam (const char *const FileName, vtkPV4FoamReader * reader)
Construct from components.
~vtkPV4Foam()
~vtkPV4Foam ()
Destructor.
Member Function Documentation
ClassName()
ClassName ("vtkPV4Foam")
Static data members.
updateInfo()
void updateInfo ()
Update.
Update()
void Update (vtkMultiBlockDataSet * output, vtkMultiBlockDataSet * lagrangianOutput)
CleanUp()
void CleanUp ()
Clean any storage.
findTimes()
double* findTimes (int & nTimeSteps)
Allocate and return a list of selected times.
returns the count via the parameter
renderPatchNames()
void renderPatchNames (vtkRenderer * , const bool show)
Add/remove patch names to/from the view.
setTime()
int setTime (int count, const double requestTimes[])
set the runTime to the first plausible request time,
returns the timeIndex sets to "constant" on error
timeIndex()
int timeIndex () const inline
The current time index.
Definition at line 709 of file vtkPV4Foam.H.
References vtkPV4Foam::printMemory(), and vtkPV4Foam::PrintSelf().
PrintSelf()
void PrintSelf (ostream & , vtkIndent) const
Debug information.
Referenced by vtkPV4Foam::timeIndex().
printMemory()
void printMemory () static
Simple memory used debugging information.
Definition at line 330 of file vtkPV4FoamUtils.C.
References Foam::Info, and memInfo::valid().
Referenced by vtkPV4Foam::timeIndex().
addToSelection()
Foam::label addToSelection (vtkDataArraySelection * select, const IOobjectList & objectLst, const string & suffix)
Definition at line 40 of file vtkPV4FoamAddToSelection.H.
References forAll, and IOobjectList::names().
The documentation for this class was generated from the following files:
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4Foam.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamAddToSelection.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamFaceField.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamLagrangianFields.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamPatchField.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamPointFields.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamUpdateInfoFields.H
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamUtils.C
applications/utilities/postProcessing/graphics/PV4Readers/PV4FoamReader/vtkPV4Foam/vtkPV4FoamVolFields.H