OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
lagrangianWriter Class Reference
Write fields (internal).
Public Member Functions
lagrangianWriter (const vtkMesh &, const bool binary, const fileName &, const word &, const bool dummyCloud)
Construct from components.
std::ofstream & os ()
void writeParcelHeader (const label nFields)
template<class Type >
void writeIOField (const wordList &)
Write IOField.
Detailed Description
Write fields (internal).
Source files
lagrangianWriter.H
lagrangianWriter.C
lagrangianWriterTemplates.C
Definition at line 57 of file lagrangianWriter.H.
Constructor & Destructor Documentation
lagrangianWriter()
lagrangianWriter (const vtkMesh & , const bool binary, const fileName & , const word & , const bool dummyCloud)
Construct from components.
Member Function Documentation
os()
std::ofstream& os () inline
Definition at line 89 of file lagrangianWriter.H.
References lagrangianWriter::writeIOField(), and lagrangianWriter::writeParcelHeader().
writeParcelHeader()
void writeParcelHeader (const label nFields)
Referenced by lagrangianWriter::os().
writeIOField()
void writeIOField (const wordList &)
Write IOField.
Referenced by lagrangianWriter::os().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToVTK/lagrangianWriter.H