OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField Class Reference
Dummy version of turbulentIntensityKineticEnergyInlet patch type for symmetric tensors provided for compatibility with R utility.
Public Member Functions
TypeName ("turbulentIntensityKineticEnergyInlet")
Runtime type information.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const fvPatch &, const DimensionedField< symmTensor, volMesh > &)
Construct from patch and internal field.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const fvPatch &, const DimensionedField< symmTensor, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const turbulentIntensityKineticEnergyInletFvPatchSymmTensorField &, const fvPatch &, const DimensionedField< symmTensor, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const turbulentIntensityKineticEnergyInletFvPatchSymmTensorField &)
Construct as copy.
virtual tmp< fvPatchSymmTensorField > clone () const
Construct and return a clone.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const turbulentIntensityKineticEnergyInletFvPatchSymmTensorField &, const DimensionedField< symmTensor, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchSymmTensorField > clone (const DimensionedField< symmTensor, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void write (Ostream &) const
Write.
Detailed Description
Dummy version of turbulentIntensityKineticEnergyInlet patch type for symmetric tensors provided for compatibility with R utility.
Value is given by a fixed-value condition.
Source files
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.H
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.C
Definition at line 52 of file turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.H.
Constructor & Destructor Documentation
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField() [1/5]
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const fvPatch & , const DimensionedField< symmTensor, volMesh > &)
Construct from patch and internal field.
Referenced by turbulentIntensityKineticEnergyInletFvPatchSymmTensorField::clone().
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField() [2/5]
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const fvPatch & , const DimensionedField< symmTensor, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField() [3/5]
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const turbulentIntensityKineticEnergyInletFvPatchSymmTensorField & , const fvPatch & , const DimensionedField< symmTensor, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField onto a new patch
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField() [4/5]
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const turbulentIntensityKineticEnergyInletFvPatchSymmTensorField &)
Construct as copy.
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField() [5/5]
turbulentIntensityKineticEnergyInletFvPatchSymmTensorField (const turbulentIntensityKineticEnergyInletFvPatchSymmTensorField & , const DimensionedField< symmTensor, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("turbulentIntensityKineticEnergyInlet")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchSymmTensorField> clone () const inline virtual
Construct and return a clone.
Definition at line 97 of file turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.H.
References turbulentIntensityKineticEnergyInletFvPatchSymmTensorField::turbulentIntensityKineticEnergyInletFvPatchSymmTensorField().
clone() [2/2]
virtual tmp<fvPatchSymmTensorField> clone (const DimensionedField< symmTensor, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 117 of file turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.H.
References turbulentIntensityKineticEnergyInletFvPatchSymmTensorField::turbulentIntensityKineticEnergyInletFvPatchSymmTensorField(), and turbulentIntensityKineticEnergyInletFvPatchSymmTensorField::write().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by turbulentIntensityKineticEnergyInletFvPatchSymmTensorField::clone().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/turbulence/R/compatibilityFvPatchFields/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.H