OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vtkPV3Foam Class Reference
Provides a reader interface for OpenFOAM to VTK interaction.
Public Member Functions
ClassName ("vtkPV3Foam")
Static data members.
vtkPV3Foam (const char *const FileName, vtkPV3FoamReader *reader)
Construct from components.
~vtkPV3Foam ()
Destructor.
void updateInfo ()
Update.
void Update (vtkMultiBlockDataSet *output, vtkMultiBlockDataSet *lagrangianOutput)
void CleanUp ()
Clean any storage.
double * findTimes (int &nTimeSteps)
Allocate and return a list of selected times.
void renderPatchNames (vtkRenderer *, const bool show)
Add/remove patch names to/from the view.
int setTime (int count, const double requestTimes[])
set the runTime to the first plausible request time,
int timeIndex () const
The current time index.
void PrintSelf (ostream &, vtkIndent) const
Debug information.
template<class Type >
Foam::label addToSelection (vtkDataArraySelection *select, const IOobjectList &objectLst, const string &suffix)
Static Public Member Functions
static void printMemory ()
Simple memory used debugging information.
Detailed Description
Provides a reader interface for OpenFOAM to VTK interaction.
Source files
vtkPV3Foam.H
vtkPV3Foam.C
vtkPV3Foam.H
vtkPV3FoamFields.C
vtkPV3FoamMesh.C
vtkPV3FoamMeshLagrangian.C
vtkPV3FoamTemplates.C
vtkPV3FoamMeshSet.C
vtkPV3FoamMeshVolume.C
vtkPV3FoamMeshZone.C
vtkPV3FoamFaceField.H
vtkPV3FoamLagrangianFields.H
vtkPV3FoamPatchField.H
vtkPV3FoamPointFields.H
vtkPV3FoamPoints.H
vtkPV3FoamUpdateInfo.C
vtkPV3FoamUpdateInfoFields.H
vtkPV3FoamUtils.C
vtkPV3FoamVolFields.H
vtkPV3FoamAddToSelection.H
Needed by VTK: vtkDataArrayTemplateImplicit.txx
Definition at line 107 of file vtkPV3Foam.H.
Constructor & Destructor Documentation
vtkPV3Foam()
vtkPV3Foam (const char *const FileName, vtkPV3FoamReader * reader)
Construct from components.
~vtkPV3Foam()
~vtkPV3Foam ()
Destructor.
Member Function Documentation
ClassName()
ClassName ("vtkPV3Foam")
Static data members.
updateInfo()
void updateInfo ()
Update.
Update()
void Update (vtkMultiBlockDataSet * output, vtkMultiBlockDataSet * lagrangianOutput)
CleanUp()
void CleanUp ()
Clean any storage.
findTimes()
double* findTimes (int & nTimeSteps)
Allocate and return a list of selected times.
returns the count via the parameter
renderPatchNames()
void renderPatchNames (vtkRenderer * , const bool show)
Add/remove patch names to/from the view.
setTime()
int setTime (int count, const double requestTimes[])
set the runTime to the first plausible request time,
returns the timeIndex sets to "constant" on error
timeIndex()
int timeIndex () const inline
The current time index.
Definition at line 709 of file vtkPV3Foam.H.
References vtkPV3Foam::printMemory(), and vtkPV3Foam::PrintSelf().
PrintSelf()
void PrintSelf (ostream & , vtkIndent) const
Debug information.
Referenced by vtkPV3Foam::timeIndex().
printMemory()
void printMemory () static
Simple memory used debugging information.
Definition at line 330 of file vtkPV3FoamUtils.C.
References Foam::Info, and memInfo::valid().
Referenced by vtkPV3Foam::timeIndex().
addToSelection()
Foam::label addToSelection (vtkDataArraySelection * select, const IOobjectList & objectLst, const string & suffix)
Definition at line 40 of file vtkPV3FoamAddToSelection.H.
References forAll, and IOobjectList::names().
The documentation for this class was generated from the following files:
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3Foam.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamAddToSelection.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamFaceField.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamLagrangianFields.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamPatchField.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamPointFields.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamUpdateInfoFields.H
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamUtils.C
applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkPV3FoamVolFields.H