OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
partInfo Class Reference
Bookkeeping for GUI checklists and the multi-block organization.
Public Member Functions
partInfo (const char *name, const int blockNo=0)
int block () const
Return the block holding these datasets.
int block (int blockNo)
Assign block number, return previous value.
const char * name () const
int start () const
int end () const
int size () const
bool empty () const
void reset ()
void operator= (const int i)
Assign new start and reset the size.
void operator+= (const int n)
Increment the size.
Detailed Description
Bookkeeping for GUI checklists and the multi-block organization.
Definition at line 75 of file vtkPV3Readers.H.
Constructor & Destructor Documentation
partInfo()
partInfo (const char * name, const int blockNo = 0) inline
Definition at line 84 of file vtkPV3Readers.H.
Member Function Documentation
block() [1/2]
int block () const inline
Return the block holding these datasets.
Definition at line 93 of file vtkPV3Readers.H.
Referenced by Foam::vtkPV3Readers::AddToBlock(), Foam::vtkPV3Readers::GetDataSetFromBlock(), and Foam::vtkPV3Readers::GetNumberOfDataSets().
block() [2/2]
int block (int blockNo) inline
Assign block number, return previous value.
Definition at line 99 of file vtkPV3Readers.H.
name()
const char* name () const inline
Definition at line 106 of file vtkPV3Readers.H.
Referenced by Foam::vtkPV3Readers::AddToBlock().
start()
int start () const inline
Definition at line 111 of file vtkPV3Readers.H.
Referenced by Foam::vtkPV3Readers::getSelected(), and Foam::vtkPV3Readers::getSelectedArrayEntries().
end()
int end () const inline
Definition at line 116 of file vtkPV3Readers.H.
Referenced by Foam::vtkPV3Readers::getSelected(), and Foam::vtkPV3Readers::getSelectedArrayEntries().
size()
int size () const inline
Definition at line 121 of file vtkPV3Readers.H.
Referenced by Foam::vtkPV3Readers::getSelectedArrayEntries().
empty()
bool empty () const inline
Definition at line 126 of file vtkPV3Readers.H.
reset()
void reset () inline
Definition at line 131 of file vtkPV3Readers.H.
operator=()
void operator= (const int i) inline
Assign new start and reset the size.
Definition at line 138 of file vtkPV3Readers.H.
operator+=()
void operator+= (const int n) inline
Increment the size.
Definition at line 145 of file vtkPV3Readers.H.
References Foam::vtkPV3Readers::AddToBlock(), Foam::vtkPV3Readers::GetDataSetFromBlock(), Foam::vtkPV3Readers::GetNumberOfDataSets(), Foam::vtkPV3Readers::getSelected(), Foam::vtkPV3Readers::getSelectedArrayEntries(), n, and Foam::vtkPV3Readers::setSelectedArrayEntries().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/graphics/PV3Readers/vtkPV3Readers/vtkPV3Readers.H