OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vtkMesh Class Reference
Encapsulation of VTK mesh data. Holds mesh or meshsubset and polyhedral-cell decomposition on it.
Public Member Functions
vtkMesh (fvMesh &baseMesh, const word &setName="")
Construct from components.
const fvMesh & baseMesh () const
whole mesh
const fvMeshSubset & subsetter () const
bool useSubMesh () const
Check if running subMesh.
const fvMesh & mesh () const
Access either mesh or submesh.
polyMesh::readUpdateState readUpdate ()
Read mesh.
template<class GeoField >
tmp< GeoField > interpolate (const GeoField &fld) const
Map volume field (does in fact do very little interpolation;.
vtkMesh (fvMesh &baseMesh, const word &setName="")
Construct from components.
const fvMesh & baseMesh () const
whole mesh
const fvMeshSubset & subsetter () const
bool useSubMesh () const
Check if running subMesh.
const vtkTopo & topo () const
topology
const fvMesh & mesh () const
Access either mesh or submesh.
label nFieldCells () const
Number of field cells.
label nFieldPoints () const
Number of field points.
polyMesh::readUpdateState readUpdate ()
Read mesh.
template<class GeoField >
tmp< GeoField > interpolate (const GeoField &fld) const
Map volume field (does in fact do very little interpolation;.
Detailed Description
Encapsulation of VTK mesh data. Holds mesh or meshsubset and polyhedral-cell decomposition on it.
Source files
vtkMesh.H
vtkMesh.C
Source files
vtkMesh.H
vtkMesh.C
Definition at line 52 of file vtkMesh.H.
Constructor & Destructor Documentation
vtkMesh() [1/2]
vtkMesh (fvMesh & baseMesh, const word & setName = "")
Construct from components.
vtkMesh() [2/2]
vtkMesh (fvMesh & baseMesh, const word & setName = "")
Construct from components.
Member Function Documentation
baseMesh() [1/2]
const fvMesh& baseMesh () const inline
whole mesh
Definition at line 92 of file vtkMesh.H.
subsetter() [1/2]
const fvMeshSubset& subsetter () const inline
Definition at line 97 of file vtkMesh.H.
useSubMesh() [1/2]
bool useSubMesh () const inline
Check if running subMesh.
Definition at line 103 of file vtkMesh.H.
Referenced by vtkMesh::interpolate(), and vtkMesh::mesh().
mesh() [1/2]
const fvMesh& mesh () const inline
Access either mesh or submesh.
Definition at line 119 of file vtkMesh.H.
References vtkMesh::readUpdate(), fvMeshSubset::subMesh(), and vtkMesh::useSubMesh().
Referenced by vtkMesh::nFieldPoints(), and vtkMesh::topo().
readUpdate() [1/2]
polyMesh::readUpdateState readUpdate ()
Read mesh.
Referenced by vtkMesh::mesh(), and vtkMesh::nFieldPoints().
interpolate() [1/2]
tmp<GeoField> interpolate (const GeoField & fld) const inline
Map volume field (does in fact do very little interpolation;.
just copied from fvMeshSubset)
Definition at line 153 of file vtkMesh.H.
References fld(), fvMeshSubset::interpolate(), and vtkMesh::useSubMesh().
baseMesh() [2/2]
const fvMesh& baseMesh () const inline
whole mesh
Definition at line 93 of file vtkMesh.H.
subsetter() [2/2]
const fvMeshSubset& subsetter () const inline
Definition at line 98 of file vtkMesh.H.
useSubMesh() [2/2]
bool useSubMesh () const inline
Check if running subMesh.
Definition at line 104 of file vtkMesh.H.
topo()
const vtkTopo& topo () const inline
topology
Definition at line 110 of file vtkMesh.H.
References vtkMesh::mesh().
Referenced by vtkMesh::nFieldCells(), and vtkMesh::nFieldPoints().
mesh() [2/2]
const fvMesh& mesh () const inline
Access either mesh or submesh.
Definition at line 120 of file vtkMesh.H.
References vtkMesh::useSubMesh().
nFieldCells()
label nFieldCells () const inline
Number of field cells.
Definition at line 133 of file vtkMesh.H.
References vtkTopo::cellTypes(), List< T >::size(), and vtkMesh::topo().
nFieldPoints()
label nFieldPoints () const inline
Number of field points.
Definition at line 139 of file vtkMesh.H.
References vtkTopo::addPointCellLabels(), vtkMesh::mesh(), primitiveMesh::nPoints(), vtkMesh::readUpdate(), List< T >::size(), and vtkMesh::topo().
readUpdate() [2/2]
polyMesh::readUpdateState readUpdate ()
Read mesh.
interpolate() [2/2]
tmp<GeoField> interpolate (const GeoField & fld) const inline
Map volume field (does in fact do very little interpolation;.
just copied from fvMeshSubset)
Definition at line 154 of file vtkMesh.H.
References fld(), and vtkMesh::useSubMesh().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToTecplot360/vtkMesh.H