OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fixedRhoFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary Conditions
Foam::fixedRhoFvPatchScalarField.
Public Member Functions
TypeName ("fixedRho")
Runtime type information.
fixedRhoFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedRhoFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedRhoFvPatchScalarField (const fixedRhoFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given fixedRhoFvPatchScalarField.
fixedRhoFvPatchScalarField (const fixedRhoFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fixedRhoFvPatchScalarField (const fixedRhoFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Foam::fixedRhoFvPatchScalarField.
This boundary condition provides a fixed density inlet condition for compressible solvers, where the density of calculated using:
{ = p ]
where
= pressure [Pa]
= density [kg/m3]
Patch usage
Property Description Required Default value
pName Pressure field name no p
psiName Compressibility field name no thermo:psi
Example of the boundary condition specification:
    myPatch
    {
        type            fixedRho;
    }
Source files
fixedRhoFvPatchScalarField.H
fixedRhoFvPatchScalarField.C
Definition at line 104 of file fixedRhoFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedRhoFvPatchScalarField() [1/5]
fixedRhoFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by fixedRhoFvPatchScalarField::clone().
fixedRhoFvPatchScalarField() [2/5]
fixedRhoFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
fixedRhoFvPatchScalarField() [3/5]
fixedRhoFvPatchScalarField (const fixedRhoFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given fixedRhoFvPatchScalarField.
onto a new patch
fixedRhoFvPatchScalarField() [4/5]
fixedRhoFvPatchScalarField (const fixedRhoFvPatchScalarField &)
Construct as copy.
fixedRhoFvPatchScalarField() [5/5]
fixedRhoFvPatchScalarField (const fixedRhoFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("fixedRho")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 160 of file fixedRhoFvPatchScalarField.H.
References fixedRhoFvPatchScalarField::fixedRhoFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 177 of file fixedRhoFvPatchScalarField.H.
References fixedRhoFvPatchScalarField::fixedRhoFvPatchScalarField(), fixedRhoFvPatchScalarField::updateCoeffs(), and fixedRhoFvPatchScalarField::write().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by fixedRhoFvPatchScalarField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by fixedRhoFvPatchScalarField::clone().
The documentation for this class was generated from the following file:
applications/solvers/compressible/rhoCentralFoam/BCs/rho/fixedRhoFvPatchScalarField.H