OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
XiEqModel Class Reference abstract
Base-class for all XiEq models used by the b-XiEq combustion model. The available models are : basicXiSubXiEq.H Gulder.H instabilityXiEq.H SCOPEBlendXiEq.H SCOPEXiEq.H.
Public Member Functions
TypeName ("XiEqModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, XiEqModel, dictionary,(const dictionary &XiEqProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su),(XiEqProperties, thermo, turbulence, Su))
XiEqModel (const dictionary &XiEqProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su)
Construct from components.
virtual ~XiEqModel ()
Destructor.
virtual tmp< volScalarField > XiEq () const
Return the flame-wrinking XiEq.
tmp< volScalarField > calculateSchelkinEffect (const scalar) const
Return the sub-grid Schelkin effect.
virtual bool read (const dictionary &XiEqProperties)=0
Update properties from given dictionary.
void writeFields () const
Write fields.
Static Public Member Functions
static autoPtr< XiEqModel > New (const dictionary &XiEqProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su)
Return a reference to the selected XiEq model.
Protected Attributes
dictionary XiEqModelCoeffs_
Dictionary.
const psiuReactionThermo & thermo_
Thermo.
const compressible::RASModel & turbulence_
Turbulence.
const volScalarField & Su_
Laminar burning velocity.
volScalarField Nv_
Volumetric obstacles number.
volSymmTensorField nsv_
Detailed Description
Base-class for all XiEq models used by the b-XiEq combustion model. The available models are : basicXiSubXiEq.H Gulder.H instabilityXiEq.H SCOPEBlendXiEq.H SCOPEXiEq.H.
Source files
XiEqModel.H
XiEqModel.C
Definition at line 57 of file XiEqModel.H.
Constructor & Destructor Documentation
XiEqModel()
XiEqModel (const dictionary & XiEqProperties, const psiuReactionThermo & thermo, const compressible::RASModel & turbulence, const volScalarField & Su)
Construct from components.
~XiEqModel()
virtual ~XiEqModel () virtual
Destructor.
Member Function Documentation
TypeName()
TypeName ("XiEqModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , XiEqModel , dictionary , (const dictionary &XiEqProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su) , (XiEqProperties, thermo, turbulence, Su))
New()
static autoPtr<XiEqModel> New (const dictionary & XiEqProperties, const psiuReactionThermo & thermo, const compressible::RASModel & turbulence, const volScalarField & Su) static
Return a reference to the selected XiEq model.
XiEq()
virtual tmp<volScalarField> XiEq () const inline virtual
Return the flame-wrinking XiEq.
Reimplemented in basicSubGrid, SCOPEXiEq, Gulder, SCOPEBlend, and instability.
Definition at line 153 of file XiEqModel.H.
References XiEqModel::calculateSchelkinEffect(), XiEqModel::read(), and XiEqModel::writeFields().
calculateSchelkinEffect()
tmp<volScalarField> calculateSchelkinEffect (const scalar) const
Return the sub-grid Schelkin effect.
Referenced by XiEqModel::XiEq().
read()
virtual bool read (const dictionary & XiEqProperties) pure virtual
Update properties from given dictionary.
Implemented in basicSubGrid, SCOPEXiEq, Gulder, SCOPEBlend, and instability.
Referenced by XiEqModel::XiEq().
writeFields()
void writeFields () const
Write fields.
Referenced by XiEqModel::XiEq().
Member Data Documentation
XiEqModelCoeffs_
dictionary XiEqModelCoeffs_ protected
Dictionary.
Definition at line 65 of file XiEqModel.H.
thermo_
const psiuReactionThermo& thermo_ protected
Thermo.
Definition at line 68 of file XiEqModel.H.
turbulence_
const compressible::RASModel& turbulence_ protected
Turbulence.
Definition at line 71 of file XiEqModel.H.
Su_
const volScalarField& Su_ protected
Laminar burning velocity.
Definition at line 74 of file XiEqModel.H.
Nv_
volScalarField Nv_ protected
Volumetric obstacles number.
Definition at line 77 of file XiEqModel.H.
nsv_
volSymmTensorField nsv_ protected
Definition at line 80 of file XiEqModel.H.
The documentation for this class was generated from the following file:
applications/solvers/combustion/PDRFoam/XiModels/XiEqModels/XiEqModel/XiEqModel.H