OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
XiModel Class Reference abstract
Base-class for all Xi models used by the b-Xi combustion model. See Technical Report SH/RE/01R for details on the PDR modelling.
Public Member Functions
TypeName ("XiModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, XiModel, dictionary,(const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi),(XiProperties, thermo, turbulence, Su, rho, b, phi))
XiModel (const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi)
Construct from components.
virtual ~XiModel ()
Destructor.
virtual const volScalarField & Xi () const
Return the flame-wrinking Xi.
virtual tmp< volScalarField > Db () const
Return the flame diffusivity.
virtual void addXi (multivariateSurfaceInterpolationScheme< scalar >::fieldTable &)
Add Xi to the multivariateSurfaceInterpolationScheme table.
virtual void correct ()=0
Correct the flame-wrinking Xi.
virtual void correct (const fv::convectionScheme< scalar > &)
Correct the flame-wrinking Xi using the given convection scheme.
virtual bool read (const dictionary &XiProperties)=0
Update properties from given dictionary.
virtual void writeFields ()=0
Write fields related to Xi model.
Static Public Member Functions
static autoPtr< XiModel > New (const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi)
Return a reference to the selected Xi model.
Protected Attributes
dictionary XiModelCoeffs_
const psiuReactionThermo & thermo_
const compressible::RASModel & turbulence_
const volScalarField & Su_
const volScalarField & rho_
const volScalarField & b_
const surfaceScalarField & phi_
volScalarField Xi_
Flame wrinking field.
Detailed Description
Base-class for all Xi models used by the b-Xi combustion model. See Technical Report SH/RE/01R for details on the PDR modelling.
Xi is given through an algebraic expression (algebraic.H), by solving a transport equation (transport.H) or a fixed value (fixed.H).
See report TR/HGW/10 for details on the Weller two equations model.
In the algebraic and transport methods is calculated in similar way. In the algebraic approach, is the value used in the transport equation.
is calculated as follows:
where:
is the regress variable.
is a model constant.
is the total equilibrium wrinkling combining the effects of the flame inestability and turbulence interaction and is given by
where:
is the generation rate of wrinkling due to turbulence interaction.
is the generation rate due to the flame inestability.
By adding the removal rates of the two effects:
where:
is the total removal.
is a model constant.
is the flame wrinkling due to turbulence.
is the equilibrium level of the flame wrinkling generated by inestability. It is a constant (default 2.5).
Source files
XiModel.H
XiModel.C
Definition at line 107 of file XiModel.H.
Constructor & Destructor Documentation
XiModel()
XiModel (const dictionary & XiProperties, const psiuReactionThermo & thermo, const compressible::RASModel & turbulence, const volScalarField & Su, const volScalarField & rho, const volScalarField & b, const surfaceScalarField & phi)
Construct from components.
~XiModel()
virtual ~XiModel () virtual
Destructor.
Member Function Documentation
TypeName()
TypeName ("XiModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , XiModel , dictionary , (const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi) , (XiProperties, thermo, turbulence, Su, rho, b, phi))
New()
static autoPtr<XiModel> New (const dictionary & XiProperties, const psiuReactionThermo & thermo, const compressible::RASModel & turbulence, const volScalarField & Su, const volScalarField & rho, const volScalarField & b, const surfaceScalarField & phi) static
Return a reference to the selected Xi model.
Xi()
virtual const volScalarField& Xi () const inline virtual
Return the flame-wrinking Xi.
Definition at line 209 of file XiModel.H.
References XiModel::Xi_.
Db()
virtual tmp<volScalarField> Db () const inline virtual
Return the flame diffusivity.
Reimplemented in algebraic, and transport.
Definition at line 215 of file XiModel.H.
References XiModel::addXi().
addXi()
virtual void addXi (multivariateSurfaceInterpolationScheme< scalar >::fieldTable &) inline virtual
Add Xi to the multivariateSurfaceInterpolationScheme table.
if required
Reimplemented in transport.
Definition at line 223 of file XiModel.H.
References XiModel::correct().
Referenced by XiModel::Db().
correct() [1/2]
virtual void correct () pure virtual
Correct the flame-wrinking Xi.
Implemented in transport, algebraic, and fixed.
Referenced by XiModel::addXi(), and XiModel::correct().
correct() [2/2]
virtual void correct (const fv::convectionScheme< scalar > &) inline virtual
Correct the flame-wrinking Xi using the given convection scheme.
Reimplemented in transport.
Definition at line 232 of file XiModel.H.
References XiModel::correct(), XiModel::read(), and XiModel::writeFields().
read()
virtual bool read (const dictionary & XiProperties) pure virtual
Update properties from given dictionary.
Implemented in transport, algebraic, and fixed.
Referenced by XiModel::correct().
writeFields()
virtual void writeFields () pure virtual
Write fields related to Xi model.
Implemented in transport, algebraic, and fixed.
Referenced by XiModel::correct().
Member Data Documentation
XiModelCoeffs_
dictionary XiModelCoeffs_ protected
Definition at line 114 of file XiModel.H.
thermo_
const psiuReactionThermo& thermo_ protected
Definition at line 116 of file XiModel.H.
turbulence_
const compressible::RASModel& turbulence_ protected
Definition at line 117 of file XiModel.H.
Su_
const volScalarField& Su_ protected
Definition at line 118 of file XiModel.H.
rho_
const volScalarField& rho_ protected
Definition at line 119 of file XiModel.H.
b_
const volScalarField& b_ protected
Definition at line 120 of file XiModel.H.
phi_
const surfaceScalarField& phi_ protected
Definition at line 121 of file XiModel.H.
Xi_
volScalarField Xi_ protected
Flame wrinking field.
Definition at line 124 of file XiModel.H.
Referenced by transport::addXi(), and XiModel::Xi().
The documentation for this class was generated from the following file:
applications/solvers/combustion/PDRFoam/XiModels/XiModel/XiModel.H