OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
maxwellSlipUFvPatchVectorField Class Reference
Maxwell slip boundary condition including thermal creep and surface curvature terms that can be optionally switched off.
Public Member Functions
TypeName ("maxwellSlipU")
Runtime type information.
maxwellSlipUFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
maxwellSlipUFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
maxwellSlipUFvPatchVectorField (const maxwellSlipUFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
maxwellSlipUFvPatchVectorField (const maxwellSlipUFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Maxwell slip boundary condition including thermal creep and surface curvature terms that can be optionally switched off.
Source files
maxwellSlipUFvPatchVectorField.H
fixedRhoFvPatchScalarField.C
Definition at line 50 of file maxwellSlipUFvPatchVectorField.H.
Constructor & Destructor Documentation
maxwellSlipUFvPatchVectorField() [1/4]
maxwellSlipUFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
Referenced by maxwellSlipUFvPatchVectorField::clone().
maxwellSlipUFvPatchVectorField() [2/4]
maxwellSlipUFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
maxwellSlipUFvPatchVectorField() [3/4]
maxwellSlipUFvPatchVectorField (const maxwellSlipUFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
maxwellSlipUFvPatchVectorField onto a new patch
maxwellSlipUFvPatchVectorField() [4/4]
maxwellSlipUFvPatchVectorField (const maxwellSlipUFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("maxwellSlipU")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 118 of file maxwellSlipUFvPatchVectorField.H.
References maxwellSlipUFvPatchVectorField::maxwellSlipUFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 135 of file maxwellSlipUFvPatchVectorField.H.
References maxwellSlipUFvPatchVectorField::maxwellSlipUFvPatchVectorField(), maxwellSlipUFvPatchVectorField::updateCoeffs(), and maxwellSlipUFvPatchVectorField::write().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by maxwellSlipUFvPatchVectorField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by maxwellSlipUFvPatchVectorField::clone().
The documentation for this class was generated from the following file:
applications/solvers/compressible/rhoCentralFoam/BCs/U/maxwellSlipUFvPatchVectorField.H