OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
smoluchowskiJumpTFvPatchScalarField Class Reference
Smoluchowski temperature jump boundary condition.
Public Member Functions
TypeName ("smoluchowskiJumpT")
Runtime type information.
smoluchowskiJumpTFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
smoluchowskiJumpTFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
smoluchowskiJumpTFvPatchScalarField (const smoluchowskiJumpTFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given smoluchowskiJumpTFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
smoluchowskiJumpTFvPatchScalarField (const smoluchowskiJumpTFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< scalar > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Smoluchowski temperature jump boundary condition.
Source files
smoluchowskiJumpTFvPatchScalarField.H
smoluchowskiJumpTFvPatchScalarField.C
Definition at line 48 of file smoluchowskiJumpTFvPatchScalarField.H.
Constructor & Destructor Documentation
smoluchowskiJumpTFvPatchScalarField() [1/4]
smoluchowskiJumpTFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by smoluchowskiJumpTFvPatchScalarField::clone().
smoluchowskiJumpTFvPatchScalarField() [2/4]
smoluchowskiJumpTFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
smoluchowskiJumpTFvPatchScalarField() [3/4]
smoluchowskiJumpTFvPatchScalarField (const smoluchowskiJumpTFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given smoluchowskiJumpTFvPatchScalarField.
onto a new patch
smoluchowskiJumpTFvPatchScalarField() [4/4]
smoluchowskiJumpTFvPatchScalarField (const smoluchowskiJumpTFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("smoluchowskiJumpT")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 110 of file smoluchowskiJumpTFvPatchScalarField.H.
References smoluchowskiJumpTFvPatchScalarField::smoluchowskiJumpTFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 127 of file smoluchowskiJumpTFvPatchScalarField.H.
References smoluchowskiJumpTFvPatchScalarField::autoMap(), smoluchowskiJumpTFvPatchScalarField::rmap(), smoluchowskiJumpTFvPatchScalarField::smoluchowskiJumpTFvPatchScalarField(), smoluchowskiJumpTFvPatchScalarField::updateCoeffs(), and smoluchowskiJumpTFvPatchScalarField::write().
autoMap()
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by smoluchowskiJumpTFvPatchScalarField::clone().
rmap()
virtual void rmap (const fvPatchField< scalar > & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by smoluchowskiJumpTFvPatchScalarField::clone().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by smoluchowskiJumpTFvPatchScalarField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by smoluchowskiJumpTFvPatchScalarField::clone().
The documentation for this class was generated from the following file:
applications/solvers/compressible/rhoCentralFoam/BCs/T/smoluchowskiJumpTFvPatchScalarField.H