OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
phaseModel::iNew Class Reference
Return a pointer to a new phaseModel created on freestore.
Public Member Functions
iNew (const volScalarField &p, const volScalarField &T)
autoPtr< phaseModel > operator() (Istream &is) const
iNew (const fvMesh &mesh)
autoPtr< phaseModel > operator() (Istream &is) const
Detailed Description
Return a pointer to a new phaseModel created on freestore.
Return a pointer to a new phase created on freestore.
from Istream
Definition at line 83 of file phaseModel.H.
Constructor & Destructor Documentation
iNew() [1/2]
iNew (const volScalarField & p, const volScalarField & T) inline
Definition at line 91 of file phaseModel.H.
iNew() [2/2]
iNew (const fvMesh & mesh) inline
Definition at line 114 of file phaseModel.H.
Member Function Documentation
operator()() [1/2]
autoPtr<phaseModel> operator() (Istream & is) const inline
Definition at line 100 of file phaseModel.H.
References phaseModel::phaseModel().
operator()() [2/2]
autoPtr<phaseModel> operator() (Istream & is) const inline
Definition at line 121 of file phaseModel.H.
References entry::keyword(), dictionary::null, phaseModel::phaseModel(), and phaseModel::~phaseModel().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/phaseModel/phaseModel.H