OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
relativeVelocityModel Class Reference abstract
Public Member Functions
TypeName ("relativeVelocityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, relativeVelocityModel, dictionary,(const dictionary &dict, const incompressibleTwoPhaseInteractingMixture &mixture),(dict, mixture))
Declare runtime constructor selection table.
relativeVelocityModel (const dictionary &dict, const incompressibleTwoPhaseInteractingMixture &mixture)
Construct from components.
virtual ~relativeVelocityModel ()
Destructor.
const incompressibleTwoPhaseInteractingMixture & mixture () const
Mixture properties.
tmp< volScalarField > rho () const
Return the mixture mean density.
const volVectorField & Udm () const
Return the diffusion velocity of the dispersed phase.
tmp< volSymmTensorField > tauDm () const
Return the stress tensor due to the phase transport.
virtual void correct ()=0
Update the diffusion velocity.
Static Public Member Functions
static autoPtr< relativeVelocityModel > New (const dictionary &dict, const incompressibleTwoPhaseInteractingMixture &mixture)
Protected Attributes
const incompressibleTwoPhaseInteractingMixture & mixture_
Mixture properties.
const word continuousPhaseName_
Name of the continuous phase.
const volScalarField & alphac_
Continuous phase fraction.
const volScalarField & alphad_
Dispersed phase fraction.
const dimensionedScalar & rhoc_
Continuous density.
const dimensionedScalar & rhod_
Dispersed density.
volVectorField Udm_
Dispersed diffusion velocity.
Detailed Description
Source files
relativeVelocityModel.H
relativeVelocityModel.C
Definition at line 50 of file relativeVelocityModel.H.
Constructor & Destructor Documentation
relativeVelocityModel()
relativeVelocityModel (const dictionary & dict, const incompressibleTwoPhaseInteractingMixture & mixture)
Construct from components.
~relativeVelocityModel()
virtual ~relativeVelocityModel () virtual
Destructor.
Member Function Documentation
TypeName()
TypeName ("relativeVelocityModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , relativeVelocityModel , dictionary , (const dictionary &dict, const incompressibleTwoPhaseInteractingMixture &mixture) , (dict, mixture))
Declare runtime constructor selection table.
New()
static autoPtr<relativeVelocityModel> New (const dictionary & dict, const incompressibleTwoPhaseInteractingMixture & mixture) static
mixture()
const incompressibleTwoPhaseInteractingMixture& mixture () const inline
Mixture properties.
Definition at line 128 of file relativeVelocityModel.H.
References relativeVelocityModel::mixture_, and relativeVelocityModel::rho().
rho()
tmp<volScalarField> rho () const
Return the mixture mean density.
Referenced by relativeVelocityModel::mixture().
Udm()
const volVectorField& Udm () const inline
Return the diffusion velocity of the dispersed phase.
Definition at line 137 of file relativeVelocityModel.H.
References relativeVelocityModel::correct(), relativeVelocityModel::tauDm(), and relativeVelocityModel::Udm_.
tauDm()
tmp<volSymmTensorField> tauDm () const
Return the stress tensor due to the phase transport.
Referenced by relativeVelocityModel::Udm().
correct()
virtual void correct () pure virtual
Update the diffusion velocity.
Implemented in general, and simple.
Referenced by relativeVelocityModel::Udm().
Member Data Documentation
mixture_
const incompressibleTwoPhaseInteractingMixture& mixture_ protected
Mixture properties.
Definition at line 65 of file relativeVelocityModel.H.
Referenced by relativeVelocityModel::mixture().
continuousPhaseName_
const word continuousPhaseName_ protected
Name of the continuous phase.
Definition at line 68 of file relativeVelocityModel.H.
alphac_
const volScalarField& alphac_ protected
Continuous phase fraction.
Definition at line 71 of file relativeVelocityModel.H.
alphad_
const volScalarField& alphad_ protected
Dispersed phase fraction.
Definition at line 74 of file relativeVelocityModel.H.
rhoc_
const dimensionedScalar& rhoc_ protected
Continuous density.
Definition at line 77 of file relativeVelocityModel.H.
rhod_
const dimensionedScalar& rhod_ protected
Dispersed density.
Definition at line 80 of file relativeVelocityModel.H.
Udm_
volVectorField Udm_ mutable protected
Dispersed diffusion velocity.
Definition at line 83 of file relativeVelocityModel.H.
Referenced by relativeVelocityModel::Udm().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/driftFluxFoam/relativeVelocityModels/relativeVelocityModel/relativeVelocityModel.H