OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
phaseModel Class Reference
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Classes
class iNew
Return a pointer to a new phaseModel created on freestore.
Public Member Functions
phaseModel (const word &phaseName, const volScalarField &p, const volScalarField &T)
Construct from components.
autoPtr< phaseModel > clone () const
Return clone.
const word & name () const
const word & keyword () const
const rhoThermo & thermo () const
Return const-access to phase rhoThermo.
rhoThermo & thermo ()
Return access to phase rhoThermo.
const volScalarField & dgdt () const
Return const-access to phase divergence.
volScalarField & dgdt ()
Return access to phase divergence.
void correct ()
Correct the laminar viscosity.
phaseModel (const word &phaseName, const dictionary &phaseDict, const fvMesh &mesh)
autoPtr< phaseModel > clone () const
Return clone.
virtual ~phaseModel ()
Destructor.
const word & name () const
const word & keyword () const
tmp< volScalarField > d () const
const dimensionedScalar & nu () const
Return the laminar viscosity.
const dimensionedScalar & kappa () const
const dimensionedScalar & Cp () const
const dimensionedScalar & rho () const
const volVectorField & U () const
volVectorField & U ()
const volVectorField & DDtU () const
volVectorField & DDtU ()
const surfaceScalarField & phi () const
surfaceScalarField & phi ()
const surfaceScalarField & phiAlpha () const
surfaceScalarField & phiAlpha ()
void correct ()
Correct the phase properties.
bool read (const dictionary &phaseDict)
Read base transportProperties dictionary.
phaseModel (const twoPhaseSystem &fluid, const dictionary &phaseProperties, const word &phaseName)
virtual ~phaseModel ()
Destructor.
const word & name () const
Return the name of this phase.
const twoPhaseSystem & fluid () const
Return the twoPhaseSystem to which this phase belongs.
const phaseModel & otherPhase () const
Return the other phase in this two-phase system.
scalar alphaMax () const
Optional maximum phase-fraction (e.g. packing limit)
tmp< volScalarField > d () const
Return the Sauter-mean diameter.
const PhaseCompressibleTurbulenceModel< phaseModel > & turbulence () const
Return the turbulence model.
PhaseCompressibleTurbulenceModel< phaseModel > & turbulence ()
Return non-const access to the turbulence model.
const rhoThermo & thermo () const
Return the thermophysical model.
rhoThermo & thermo ()
Return non-const access to the thermophysical model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity for patch.
tmp< volScalarField > kappa () const
Return the thermal conductivity.
tmp< volScalarField > Cp () const
Return the specific heat capacity.
const volScalarField & rho () const
Return the density.
const volVectorField & U () const
Return the velocity.
volVectorField & U ()
Return non-const access to the velocity.
const surfaceScalarField & phi () const
Return the volumetric flux.
surfaceScalarField & phi ()
Return non-const access to the volumetric flux.
const surfaceScalarField & alphaPhi () const
Return the volumetric flux of the phase.
surfaceScalarField & alphaPhi ()
Return non-const access to the volumetric flux of the phase.
const surfaceScalarField & alphaRhoPhi () const
Return the mass flux of the phase.
surfaceScalarField & alphaRhoPhi ()
Return non-const access to the mass flux of the phase.
void correct ()
Correct the phase properties.
virtual bool read (const dictionary &phaseProperties)
Read phaseProperties dictionary.
virtual bool read ()
Dummy Read for transportModel.
Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
TypeName ("GeometricField")
Runtime type information.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensions and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensioned< scalar > &, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensioned< scalar > &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const Field< scalar > &, const PtrList< fvPatchField< scalar > > &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &)
Construct and read given IOobject.
GeometricField (const IOobject &, const Mesh &, const dictionary &)
Construct from dictionary.
GeometricField (const GeometricField< scalar, fvPatchField, volMesh > &)
Construct as copy.
GeometricField (const IOobject &, const GeometricField< scalar, fvPatchField, volMesh > &)
Construct as copy of tmp<GeometricField> deleting argument.
GeometricField (const word &newName, const GeometricField< scalar, fvPatchField, volMesh > &)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< scalar, fvPatchField, volMesh > &, const word &patchFieldType)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< scalar, fvPatchField, volMesh > &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
virtual ~GeometricField ()
Destructor.
DimensionedInternalField & dimensionedInternalField ()
Return dimensioned internal field.
const DimensionedInternalField & dimensionedInternalField () const
Return dimensioned internal field.
InternalField & internalField ()
Return internal field.
const InternalField & internalField () const
Return internal field.
GeometricBoundaryField & boundaryField ()
Return reference to GeometricBoundaryField.
const GeometricBoundaryField & boundaryField () const
Return reference to GeometricBoundaryField for const field.
label timeIndex () const
Return the time index of the field.
label & timeIndex ()
Return the time index of the field.
void storeOldTimes () const
Store the old-time fields.
void storeOldTime () const
Store the old-time field.
label nOldTimes () const
Return the number of old time fields stored.
const GeometricField< scalar, fvPatchField, volMesh > & oldTime () const
Return old time field.
GeometricField< scalar, fvPatchField, volMesh > & oldTime ()
Return non-const old time field.
void storePrevIter () const
Store the field as the previous iteration value.
const GeometricField< scalar, fvPatchField, volMesh > & prevIter () const
Return previous iteration field.
void correctBoundaryConditions ()
Correct boundary field.
bool needReference () const
Does the field need a reference level for solution.
tmp< GeometricField< cmptType, fvPatchField, volMesh > > component (const direction) const
Return a component of the field.
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
bool writeData (Ostream &) const
WriteData member function required by regIOobject.
tmp< GeometricField< scalar, fvPatchField, volMesh > > T () const
Return transpose (only if it is a tensor field)
void relax (const scalar alpha)
Relax field (for steady-state solution).
void relax ()
Relax field (for steady-state solution).
word select (bool final) const
Select the final iteration parameters if `final' is true.
void writeMinMax (Ostream &os) const
Helper function to write the min and max to an Ostream.
void negate ()
void replace (const direction, const GeometricField< cmptType, fvPatchField, volMesh > &)
void replace (const direction, const dimensioned< cmptType > &)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
void max (const dimensioned< scalar > &)
void max (const GeometricField< scalar, fvPatchField, volMesh > &, const dimensioned< scalar > &)
void min (const dimensioned< scalar > &)
void min (const GeometricField< scalar, fvPatchField, volMesh > &, const dimensioned< scalar > &)
void scale (const GeometricField< scalar, fvPatchField, volMesh > &, const GeometricField< scalar, fvPatchField, volMesh > &)
void scale (const GeometricField< scalar, fvPatchField, volMesh > &, const dimensioned< scalar > &)
void operator= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator= (const dimensioned< scalar > &)
void operator== (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator== (const dimensioned< scalar > &)
void operator+= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator+= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator+= (const dimensioned< scalar > &)
void operator-= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator-= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator-= (const dimensioned< scalar > &)
void operator*= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator*= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator/= (const tmp< GeometricField< scalar, fvPatchField, volMesh > > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const Field< Type > &)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensioned< Type > &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const DimensionedField< Type, GeoMesh > &)
Construct as copy.
DimensionedField (DimensionedField< Type, GeoMesh > &, bool reUse)
Construct as copy or re-use as specified.
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh > > &)
Construct by transferring the DimensionedField.
DimensionedField (const IOobject &, const DimensionedField< Type, GeoMesh > &)
Construct as copy of tmp<DimensionedField> deleting argument.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &, bool reUse)
Construct as copy resetting name and re-use as specified.
DimensionedField (const word &newName, const Xfer< DimensionedField< Type, GeoMesh > > &)
Construct by transferring the DimensionedField with a new name.
tmp< DimensionedField< Type, GeoMesh > > clone () const
Construct as copy resetting name.
virtual ~DimensionedField ()
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const Field< Type > & field () const
Field< Type > & field ()
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
void replace (const direction, const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
void replace (const direction, const tmp< DimensionedField< cmptType, GeoMesh > > &)
Replace a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh > > &) const
Calculate and return weighted average.
bool writeData (Ostream &, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &)
void operator= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator= (const dimensioned< Type > &)
void operator+= (const DimensionedField< Type, GeoMesh > &)
void operator+= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator-= (const DimensionedField< Type, GeoMesh > &)
void operator-= (const tmp< DimensionedField< Type, GeoMesh > > &)
void operator*= (const DimensionedField< scalar, GeoMesh > &)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh > > &)
void operator/= (const DimensionedField< scalar, GeoMesh > &)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, and transferring registry registration to copy.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type > > &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reUse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type > > &)
Construct by transferring the Field contents.
Field (Istream &)
Construct as copy of tmp<Field>
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType > > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const Type &)
template<class Form , class Cmpt , int nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type > > &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Public Member Functions inherited from transportModel
TypeName ("transportModel")
Runtime type information.
transportModel ()
Construct from components.
virtual ~transportModel ()
Destructor.
Additional Inherited Members
Public Types inherited from GeometricField< scalar, fvPatchField, volMesh >
typedef volMesh ::Mesh Mesh
typedef volMesh ::BoundaryMesh BoundaryMesh
typedef DimensionedField< scalar, volMesh > DimensionedInternalField
typedef Field< scalar > InternalField
typedef fvPatchField< scalar > PatchFieldType
typedef Field< scalar >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
typedef Field< Type >::cmptType cmptType
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
static const GeometricField< scalar, fvPatchField, volMesh > & null ()
Return a null geometric field.
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
Return a null DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Definition at line 53 of file phaseModel.H.
Constructor & Destructor Documentation
phaseModel() [1/3]
phaseModel (const word & phaseName, const volScalarField & p, const volScalarField & T)
Construct from components.
Referenced by phaseModel::iNew::operator()().
phaseModel() [2/3]
phaseModel (const word & phaseName, const dictionary & phaseDict, const fvMesh & mesh)
~phaseModel() [1/2]
virtual ~phaseModel () virtual
Destructor.
Referenced by phaseModel::iNew::operator()().
phaseModel() [3/3]
phaseModel (const twoPhaseSystem & fluid, const dictionary & phaseProperties, const word & phaseName)
~phaseModel() [2/2]
virtual ~phaseModel () virtual
Destructor.
Member Function Documentation
clone() [1/2]
autoPtr<phaseModel> clone () const
Return clone.
name() [1/3]
const word& name () const inline
Definition at line 109 of file phaseModel.H.
Referenced by phaseModel::keyword().
keyword() [1/2]
const word& keyword () const inline
Definition at line 114 of file phaseModel.H.
References phaseModel::name().
thermo() [1/4]
const rhoThermo& thermo () const inline
Return const-access to phase rhoThermo.
Definition at line 120 of file phaseModel.H.
Referenced by phaseModel::thermo().
thermo() [2/4]
rhoThermo& thermo () inline
Return access to phase rhoThermo.
Definition at line 126 of file phaseModel.H.
dgdt() [1/2]
const volScalarField& dgdt () const inline
Return const-access to phase divergence.
Definition at line 132 of file phaseModel.H.
dgdt() [2/2]
volScalarField& dgdt () inline
Return access to phase divergence.
Definition at line 138 of file phaseModel.H.
References phaseModel::correct().
correct() [1/3]
void correct () virtual
Correct the laminar viscosity.
Implements transportModel.
Referenced by phaseModel::alphaRhoPhi(), phaseModel::dgdt(), and phaseModel::phiAlpha().
clone() [2/2]
autoPtr<phaseModel> clone () const
Return clone.
name() [2/3]
const word& name () const inline
Definition at line 138 of file phaseModel.H.
keyword() [2/2]
const word& keyword () const inline
Definition at line 143 of file phaseModel.H.
References phaseModel::d(), and phaseModel::name().
d() [1/2]
tmp<volScalarField> d () const
Referenced by phaseModel::fluid(), and phaseModel::keyword().
nu() [1/3]
const dimensionedScalar& nu () const inline virtual
Return the laminar viscosity.
Implements transportModel.
Definition at line 150 of file phaseModel.H.
kappa() [1/2]
const dimensionedScalar& kappa () const inline
Definition at line 155 of file phaseModel.H.
Cp() [1/2]
const dimensionedScalar& Cp () const inline
Definition at line 160 of file phaseModel.H.
rho() [1/2]
const dimensionedScalar& rho () const inline
Definition at line 165 of file phaseModel.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::rhogEff(), and mixtureKEpsilon< BasicTurbulenceModel >::rholEff().
U() [1/4]
const volVectorField& U () const inline
Definition at line 170 of file phaseModel.H.
Referenced by phaseModel::U().
U() [2/4]
volVectorField& U () inline
Definition at line 175 of file phaseModel.H.
DDtU() [1/2]
const volVectorField& DDtU () const inline
Definition at line 180 of file phaseModel.H.
DDtU() [2/2]
volVectorField& DDtU () inline
Definition at line 185 of file phaseModel.H.
phi() [1/4]
const surfaceScalarField& phi () const inline
Definition at line 190 of file phaseModel.H.
phi() [2/4]
surfaceScalarField& phi () inline
Definition at line 195 of file phaseModel.H.
phiAlpha() [1/2]
const surfaceScalarField& phiAlpha () const inline
Definition at line 200 of file phaseModel.H.
phiAlpha() [2/2]
surfaceScalarField& phiAlpha () inline
Definition at line 205 of file phaseModel.H.
References phaseModel::correct(), and phaseModel::read().
correct() [2/3]
void correct () virtual
Correct the phase properties.
Implements transportModel.
read() [1/3]
bool read (const dictionary & phaseDict)
Read base transportProperties dictionary.
name() [3/3]
const word& name () const inline
Return the name of this phase.
Definition at line 117 of file phaseModel.H.
fluid()
const twoPhaseSystem& fluid () const inline
Return the twoPhaseSystem to which this phase belongs.
Definition at line 123 of file phaseModel.H.
References phaseModel::alphaMax(), phaseModel::d(), phaseModel::otherPhase(), and phaseModel::turbulence().
Referenced by IATEsource::fluid().
otherPhase()
const phaseModel& otherPhase () const
Return the other phase in this two-phase system.
Referenced by phaseModel::fluid(), and IATEsource::otherPhase().
alphaMax()
scalar alphaMax () const inline
Optional maximum phase-fraction (e.g. packing limit)
Defaults to 1
Definition at line 133 of file phaseModel.H.
Referenced by phaseModel::fluid().
d() [2/2]
tmp<volScalarField> d () const
Return the Sauter-mean diameter.
turbulence() [1/2]
const PhaseCompressibleTurbulenceModel<phaseModel>& turbulence () const
Return the turbulence model.
Referenced by phaseModel::fluid().
turbulence() [2/2]
PhaseCompressibleTurbulenceModel<phaseModel>& turbulence ()
Return non-const access to the turbulence model.
for correction
thermo() [3/4]
const rhoThermo& thermo () const inline
Return the thermophysical model.
Definition at line 151 of file phaseModel.H.
References phaseModel::thermo().
thermo() [4/4]
rhoThermo& thermo () inline
Return non-const access to the thermophysical model.
for correction
Definition at line 158 of file phaseModel.H.
nu() [2/3]
tmp<volScalarField> nu () const inline virtual
Return the laminar viscosity.
Implements transportModel.
Definition at line 164 of file phaseModel.H.
nu() [3/3]
tmp<scalarField> nu (const label patchi) const inline virtual
Return the laminar viscosity for patch.
Implements transportModel.
Definition at line 170 of file phaseModel.H.
mu() [1/2]
tmp<volScalarField> mu () const inline
Return the laminar dynamic viscosity.
Definition at line 176 of file phaseModel.H.
mu() [2/2]
tmp<scalarField> mu (const label patchi) const inline
Return the laminar dynamic viscosity for patch.
Definition at line 182 of file phaseModel.H.
kappa() [2/2]
tmp<volScalarField> kappa () const inline
Return the thermal conductivity.
Definition at line 188 of file phaseModel.H.
Cp() [2/2]
tmp<volScalarField> Cp () const inline
Return the specific heat capacity.
Definition at line 194 of file phaseModel.H.
rho() [2/2]
const volScalarField& rho () const inline
Return the density.
Definition at line 200 of file phaseModel.H.
U() [3/4]
const volVectorField& U () const inline
Return the velocity.
Definition at line 206 of file phaseModel.H.
References phaseModel::U().
U() [4/4]
volVectorField& U () inline
Return non-const access to the velocity.
Used in the momentum equation
Definition at line 213 of file phaseModel.H.
phi() [3/4]
const surfaceScalarField& phi () const inline
Return the volumetric flux.
Definition at line 219 of file phaseModel.H.
phi() [4/4]
surfaceScalarField& phi () inline
Return non-const access to the volumetric flux.
Definition at line 225 of file phaseModel.H.
alphaPhi() [1/2]
const surfaceScalarField& alphaPhi () const inline
Return the volumetric flux of the phase.
Definition at line 231 of file phaseModel.H.
alphaPhi() [2/2]
surfaceScalarField& alphaPhi () inline
Return non-const access to the volumetric flux of the phase.
Definition at line 237 of file phaseModel.H.
alphaRhoPhi() [1/2]
const surfaceScalarField& alphaRhoPhi () const inline
Return the mass flux of the phase.
Definition at line 243 of file phaseModel.H.
alphaRhoPhi() [2/2]
surfaceScalarField& alphaRhoPhi () inline
Return non-const access to the mass flux of the phase.
Definition at line 249 of file phaseModel.H.
References phaseModel::correct(), and phaseModel::read().
correct() [3/3]
void correct () virtual
Correct the phase properties.
other than the thermodynamics and turbulence which have special treatment
Implements transportModel.
read() [2/3]
virtual bool read (const dictionary & phaseProperties) virtual
Read phaseProperties dictionary.
read() [3/3]
virtual bool read () inline virtual
Dummy Read for transportModel.
Implements transportModel.
Definition at line 263 of file phaseModel.H.
Referenced by phaseModel::alphaRhoPhi(), and phaseModel::phiAlpha().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/phaseModel/phaseModel.H