OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
slurry Class Reference
Thomas' viscosity correction for slurry.
Public Member Functions
TypeName ("slurry")
Runtime type information.
slurry (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi, const word modelName=typeName)
Construct from components.
~slurry ()
Destructor.
tmp< volScalarField > mu (const volScalarField &muc) const
Return the mixture viscosity.
bool read (const dictionary &viscosityProperties)
Read transportProperties dictionary.
Public Member Functions inherited from mixtureViscosityModel
TypeName ("mixtureViscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, mixtureViscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
mixtureViscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~mixtureViscosityModel ()
Destructor.
const dictionary & viscosityProperties () const
Return the phase transport properties dictionary.
Protected Attributes
const volScalarField & alpha_
Slurry phase fraction.
Protected Attributes inherited from mixtureViscosityModel
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Additional Inherited Members
Static Public Member Functions inherited from mixtureViscosityModel
static autoPtr< mixtureViscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from mixtureViscosityModel
mixtureViscosityModel (const mixtureViscosityModel &)
Disallow copy construct.
void operator= (const mixtureViscosityModel &)
Disallow default bitwise assignment.
Detailed Description
Thomas' viscosity correction for slurry.
References:
     "Transport characteristics of suspension:
      VIII. A note on the viscosity of Newtonian suspensions
      of uniform spherical particles".
      D.G. Thomas,
      J. Colloid Sci. 20 (3), 1965, p267.
Source files
slurry.H
slurry.C
Definition at line 64 of file slurry.H.
Constructor & Destructor Documentation
slurry()
slurry (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi, const word modelName = typeName)
Construct from components.
~slurry()
~slurry () inline
Destructor.
Definition at line 96 of file slurry.H.
References slurry::mu(), slurry::read(), and mixtureViscosityModel::viscosityProperties().
Member Function Documentation
TypeName()
TypeName ("slurry")
Runtime type information.
mu()
tmp<volScalarField> mu (const volScalarField & muc) const virtual
Return the mixture viscosity.
given the viscosity of the continuous phase
Implements mixtureViscosityModel.
Referenced by slurry::~slurry().
read()
bool read (const dictionary & viscosityProperties) virtual
Read transportProperties dictionary.
Implements mixtureViscosityModel.
Referenced by slurry::~slurry().
Member Data Documentation
alpha_
const volScalarField& alpha_ protected
Slurry phase fraction.
Definition at line 73 of file slurry.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/driftFluxFoam/mixtureViscosityModels/slurry/slurry.H