OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mixtureViscosityModel Class Reference abstract
An abstract base class for incompressible mixtureViscosityModels.
Public Member Functions
TypeName ("mixtureViscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, mixtureViscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
mixtureViscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~mixtureViscosityModel ()
Destructor.
const dictionary & viscosityProperties () const
Return the phase transport properties dictionary.
virtual tmp< volScalarField > mu (const volScalarField &muc) const =0
Return the mixture viscosity.
virtual bool read (const dictionary &viscosityProperties)=0
Read transportProperties dictionary.
Static Public Member Functions
static autoPtr< mixtureViscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Return a reference to the selected viscosity model.
Protected Member Functions
mixtureViscosityModel (const mixtureViscosityModel &)
Disallow copy construct.
void operator= (const mixtureViscosityModel &)
Disallow default bitwise assignment.
Protected Attributes
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Detailed Description
An abstract base class for incompressible mixtureViscosityModels.
Source files
mixtureViscosityModel.H
mixtureViscosityModel.C
mixtureViscosityModelNew.C
Definition at line 59 of file mixtureViscosityModel.H.
Constructor & Destructor Documentation
mixtureViscosityModel() [1/2]
mixtureViscosityModel (const mixtureViscosityModel &) protected
Disallow copy construct.
mixtureViscosityModel() [2/2]
mixtureViscosityModel (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Construct from components.
~mixtureViscosityModel()
virtual ~mixtureViscosityModel () inline virtual
Destructor.
Definition at line 130 of file mixtureViscosityModel.H.
Member Function Documentation
operator=()
void operator= (const mixtureViscosityModel &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("mixtureViscosityModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , mixtureViscosityModel , dictionary , (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi) , (name, viscosityProperties, U, phi))
New()
static autoPtr<mixtureViscosityModel> New (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi) static
Return a reference to the selected viscosity model.
viscosityProperties()
const dictionary& viscosityProperties () const inline
Return the phase transport properties dictionary.
Definition at line 137 of file mixtureViscosityModel.H.
References mixtureViscosityModel::mu(), mixtureViscosityModel::read(), and mixtureViscosityModel::viscosityProperties_.
Referenced by BinghamPlastic::~BinghamPlastic(), plastic::~plastic(), and slurry::~slurry().
mu()
virtual tmp<volScalarField> mu (const volScalarField & muc) const pure virtual
Return the mixture viscosity.
given the viscosity of the continuous phase
Implemented in plastic, slurry, and BinghamPlastic.
Referenced by mixtureViscosityModel::viscosityProperties().
read()
virtual bool read (const dictionary & viscosityProperties) pure virtual
Read transportProperties dictionary.
Implemented in plastic, slurry, and BinghamPlastic.
Referenced by mixtureViscosityModel::viscosityProperties().
Member Data Documentation
name_
word name_ protected
Definition at line 66 of file mixtureViscosityModel.H.
viscosityProperties_
dictionary viscosityProperties_ protected
Definition at line 67 of file mixtureViscosityModel.H.
Referenced by mixtureViscosityModel::viscosityProperties().
U_
const volVectorField& U_ protected
Definition at line 69 of file mixtureViscosityModel.H.
phi_
const surfaceScalarField& phi_ protected
Definition at line 70 of file mixtureViscosityModel.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/driftFluxFoam/mixtureViscosityModels/mixtureViscosityModel/mixtureViscosityModel.H