OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
kineticTheoryModel Class Reference
Public Member Functions
TypeName ("kineticTheory")
Runtime type information.
kineticTheoryModel (const volScalarField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const phaseModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kineticTheoryModel ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volScalarField > pPrime () const
Return the phase-pressure'.
virtual tmp< surfaceScalarField > pPrimef () const
Return the face-phase-pressure'.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()
Solve the kinetic theory equations and correct the viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
Public Member Functions inherited from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
Public Member Functions inherited from PhaseCompressibleTurbulenceModel< phaseModel >
PhaseCompressibleTurbulenceModel (const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~PhaseCompressibleTurbulenceModel ()
Destructor.
virtual tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity on patch.
virtual tmp< volScalarField > mut () const
Return the turbulence dynamic viscosity.
virtual tmp< scalarField > mut (const label patchi) const
Return the turbulence dynamic viscosity on patch.
virtual tmp< volScalarField > muEff () const
Return the effective dynamic viscosity.
virtual tmp< scalarField > muEff (const label patchi) const
Return the effective dynamic viscosity on patch.
Public Member Functions inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
declareRunTimeNewSelectionTable (autoPtr, TurbulenceModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
TurbulenceModel (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct.
virtual ~TurbulenceModel ()
Destructor.
const alphaField & alpha () const
Access function to phase fraction.
const transportModel & transport () const
Access function to incompressible transport model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity on patchi.
Additional Inherited Members
Public Types inherited from eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >
typedef RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > ::alphaField alphaField
typedef RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > ::rhoField rhoField
typedef RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > ::transportModel transportModel
Public Types inherited from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >
typedef PhaseCompressibleTurbulenceModel< phaseModel > ::alphaField alphaField
typedef PhaseCompressibleTurbulenceModel< phaseModel > ::rhoField rhoField
typedef PhaseCompressibleTurbulenceModel< phaseModel > ::transportModel transportModel
Public Types inherited from PhaseCompressibleTurbulenceModel< phaseModel >
typedef volScalarField alphaField
typedef volScalarField rhoField
typedef phaseModel transportModel
Public Types inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
typedef Alpha alphaField
typedef Rho rhoField
typedef TransportModel transportModel
Static Public Member Functions inherited from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Static Public Member Functions inherited from PhaseCompressibleTurbulenceModel< phaseModel >
static autoPtr< PhaseCompressibleTurbulenceModel > New (const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
static autoPtr< TurbulenceModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Protected Member Functions inherited from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes inherited from eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >
volScalarField nut_
Protected Attributes inherited from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Protected Attributes inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
const alphaField & alpha_
const transportModel & transport_
Detailed Description
Definition at line 70 of file kineticTheoryModel.H.
Constructor & Destructor Documentation
kineticTheoryModel()
kineticTheoryModel (const volScalarField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const phaseModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
~kineticTheoryModel()
virtual ~kineticTheoryModel () virtual
Destructor.
Member Function Documentation
TypeName()
TypeName ("kineticTheory")
Runtime type information.
read()
virtual bool read () virtual
Re-read model coefficients if they have changed.
Implements eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >.
nuEff() [1/2]
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Reimplemented from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >.
Definition at line 181 of file kineticTheoryModel.H.
References eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >::nut().
nuEff() [2/2]
virtual tmp<scalarField> nuEff (const label patchi) const inline virtual
Return the effective viscosity on patch.
Reimplemented from RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >.
Definition at line 187 of file kineticTheoryModel.H.
References kineticTheoryModel::correct(), kineticTheoryModel::devRhoReff(), kineticTheoryModel::divDevRhoReff(), kineticTheoryModel::epsilon(), kineticTheoryModel::k(), eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >::nut(), kineticTheoryModel::pPrime(), kineticTheoryModel::pPrimef(), and kineticTheoryModel::R().
k()
virtual tmp<volScalarField> k () const virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Referenced by kineticTheoryModel::nuEff().
epsilon()
virtual tmp<volScalarField> epsilon () const virtual
Return the turbulence kinetic energy dissipation rate.
Referenced by kineticTheoryModel::nuEff().
R()
virtual tmp<volSymmTensorField> R () const virtual
Return the Reynolds stress tensor.
Reimplemented from eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Referenced by kineticTheoryModel::nuEff().
pPrime()
virtual tmp<volScalarField> pPrime () const virtual
Return the phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Reimplemented from PhaseCompressibleTurbulenceModel< phaseModel >.
Referenced by kineticTheoryModel::nuEff().
pPrimef()
virtual tmp<surfaceScalarField> pPrimef () const virtual
Return the face-phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Reimplemented from PhaseCompressibleTurbulenceModel< phaseModel >.
Referenced by kineticTheoryModel::nuEff().
devRhoReff()
virtual tmp<volSymmTensorField> devRhoReff () const virtual
Return the effective stress tensor.
Reimplemented from eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Referenced by kineticTheoryModel::nuEff().
divDevRhoReff()
virtual tmp<fvVectorMatrix> divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Reimplemented from eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Referenced by kineticTheoryModel::nuEff().
correct()
virtual void correct () virtual
Solve the kinetic theory equations and correct the viscosity.
Implements eddyViscosity< RASModel< PhaseCompressibleTurbulenceModel< phaseModel > > >.
Referenced by kineticTheoryModel::nuEff().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/kineticTheoryModel/kineticTheoryModel.H