OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
JohnsonJacksonParticleSlipFvPatchVectorField Class Reference
Partial slip boundary condition for the particulate velocity.
Public Member Functions
TypeName ("JohnsonJacksonParticleSlip")
Runtime type information.
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients.
virtual void write (Ostream &) const
Write.
Detailed Description
Partial slip boundary condition for the particulate velocity.
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
    hydrodynamics: Influence of the dissipation parameters"
    N Reuge
    Chemical Engineering Science
    Volume 63, Issue 22, Pages 5540-5551, November 2008
    "Frictional-collisional constitutive relations for granular materials,
    with application to plane shearing"
    P C Johnson and R Jackson
    Journal of Fluid Mechanics
    Volume 176, Pages 67-93, March 1987
Source files
JohnsonJacksonParticleSlipFvPatchVectorField.H
JohnsonJacksonParticleSlipFvPatchVectorField.C
Definition at line 65 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
Constructor & Destructor Documentation
JohnsonJacksonParticleSlipFvPatchVectorField() [1/5]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
JohnsonJacksonParticleSlipFvPatchVectorField() [2/5]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleSlipFvPatchVectorField() [3/5]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleSlipFvPatchVectorField() [4/5]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
Construct as copy.
JohnsonJacksonParticleSlipFvPatchVectorField() [5/5]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("JohnsonJacksonParticleSlip")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 114 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
References JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 131 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
References JohnsonJacksonParticleSlipFvPatchVectorField::autoMap(), JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(), JohnsonJacksonParticleSlipFvPatchVectorField::rmap(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), and JohnsonJacksonParticleSlipFvPatchVectorField::write().
autoMap()
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
rmap()
virtual void rmap (const fvPatchVectorField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleSlip/JohnsonJacksonParticleSlipFvPatchVectorField.H