OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
JohnsonJacksonParticleThetaFvPatchScalarField Class Reference
Robin condition for the particulate granular temperature.
Public Member Functions
TypeName ("JohnsonJacksonParticleTheta")
Runtime type information.
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients.
virtual void write (Ostream &) const
Write.
Detailed Description
Robin condition for the particulate granular temperature.
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
    hydrodynamics: Influence of the dissipation parameters"
    N Reuge
    Chemical Engineering Science
    Volume 63, Issue 22, Pages 5540-5551, November 2008
    "Frictional-collisional constitutive relations for granular materials,
    with application to plane shearing"
    P C Johnson and R Jackson
    Journal of Fluid Mechanics
    Volume 176, Pages 67-93, March 1987
Source files
JohnsonJacksonParticleThetaFvPatchScalarField.H
JohnsonJacksonParticleThetaFvPatchScalarField.C
Definition at line 65 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
Constructor & Destructor Documentation
JohnsonJacksonParticleThetaFvPatchScalarField() [1/5]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
JohnsonJacksonParticleThetaFvPatchScalarField() [2/5]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleThetaFvPatchScalarField() [3/5]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleThetaFvPatchScalarField() [4/5]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
Construct as copy.
JohnsonJacksonParticleThetaFvPatchScalarField() [5/5]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("JohnsonJacksonParticleTheta")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 117 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
References JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 134 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
References JohnsonJacksonParticleThetaFvPatchScalarField::autoMap(), JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(), JohnsonJacksonParticleThetaFvPatchScalarField::rmap(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), and JohnsonJacksonParticleThetaFvPatchScalarField::write().
autoMap()
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
rmap()
virtual void rmap (const fvPatchScalarField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleTheta/JohnsonJacksonParticleThetaFvPatchScalarField.H