OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IATEsource Class Reference abstract
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Classes
class iNew
Class used for the read-construction of.
Public Member Functions
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
virtual tmp< volScalarField > R () const =0
Static Public Member Functions
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes
const IATE & iate_
Reference to the IATE this source applies to.
Detailed Description
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Source files
IATEsource.H
IATEsource.C
Definition at line 52 of file IATEsource.H.
Constructor & Destructor Documentation
IATEsource()
IATEsource (const IATE & iate) inline
Definition at line 108 of file IATEsource.H.
~IATEsource()
virtual ~IATEsource () inline virtual
Destructor.
Definition at line 131 of file IATEsource.H.
Member Function Documentation
TypeName()
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
clone()
autoPtr<IATEsource> clone () const inline
Definition at line 113 of file IATEsource.H.
References IATEsource::New(), notImplemented, and Foam::type().
New()
static autoPtr<IATEsource> New (const word & type, const IATE & iate, const dictionary & dict) static
Referenced by IATEsource::clone(), and IATEsource::iNew::operator()().
phase()
const phaseModel& phase () const inline
Definition at line 137 of file IATEsource.H.
References diameterModel::phase().
Referenced by IATEsource::otherPhase().
fluid()
const twoPhaseSystem& fluid () const inline
Definition at line 142 of file IATEsource.H.
References phaseModel::fluid(), and diameterModel::phase().
otherPhase()
const phaseModel& otherPhase () const inline
Definition at line 147 of file IATEsource.H.
References phaseModel::otherPhase(), and IATEsource::phase().
phi()
scalar phi () const inline
Definition at line 152 of file IATEsource.H.
References IATEsource::CD(), IATEsource::Eo(), IATEsource::Mo(), Foam::constant::mathematical::pi(), IATEsource::R(), IATEsource::Re(), IATEsource::Ur(), IATEsource::Ut(), and IATEsource::We().
Ur()
tmp<volScalarField> Ur () const
Return the bubble relative velocity.
Referenced by IATEsource::phi().
Ut()
tmp<volScalarField> Ut () const
Return the bubble turbulent velocity.
Referenced by IATEsource::phi().
Re()
tmp<volScalarField> Re () const
Return the bubble Reynolds number.
Referenced by IATEsource::phi().
CD()
tmp<volScalarField> CD () const
Return the bubble drag coefficient.
Referenced by IATEsource::phi().
Mo()
tmp<volScalarField> Mo () const
Return the bubble Morton number.
Referenced by IATEsource::phi().
Eo()
tmp<volScalarField> Eo () const
Return the bubble Eotvos number.
Referenced by IATEsource::phi().
We()
tmp<volScalarField> We () const
Return the bubble Webber number.
Referenced by IATEsource::phi().
R()
virtual tmp<volScalarField> R () const pure virtual
Implemented in randomCoalescence, turbulentBreakUp, wakeEntrainmentCoalescence, and dummy.
Referenced by IATEsource::phi().
Member Data Documentation
iate_
const IATE& iate_ protected
Reference to the IATE this source applies to.
Definition at line 60 of file IATEsource.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/twoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H