OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn().A())
volScalarField rAtU (1.0/(1.0/rAU - UEqn().H1()))
volVectorField HbyA ("HbyA", U)
UEqn clear ()
if (simple.transonic())
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
HbyA = rAU*UEqn().H()
bool closedVolume = false
else
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
U = HbyA - rAtU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
rAU()
volScalarField rAU (1.0/ UEqn).A()
rAtU()
volScalarField rAtU (1.0/ 1.0/rAU - UEqn().H1())
HbyA()
volVectorField HbyA ("HbyA" , U)
clear()
UEqn clear ()
if() [1/3]
if (simple. transonic())
Definition at line 11 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, p, phi, phic, phid(), pRefCell, pRefValue, psi, rAtU(), rAU(), rho, rhorAtU(), simple, and Foam::fvc::snGrad().
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
rhorAtU()
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
while()
while (simple. correctNonOrthogonal())
Definition at line 75 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, psi, rho, rhorAtU(), and simple.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [2/3]
if (closedVolume)
Definition at line 111 of file pEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if() [3/3]
if (!simple. transonic())
Definition at line 122 of file pEqn.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and rho.
Variable Documentation
HbyA
HbyA = rAU*UEqn().H()
Definition at line 5 of file pEqn.H.
closedVolume
closedVolume = false
Definition at line 9 of file pEqn.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        fvc::interpolate(rho*HbyA) & mesh.Sf()
    )
Definition at line 59 of file pEqn.H.
phiHbyA
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 70 of file pEqn.H.
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 105 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 118 of file pEqn.H.