OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phid ("phid", fvc::interpolate(psi) *((mesh.Sf() &fvc::interpolate(HbyA))+rhorAUf *fvc::ddtCorr(rho, U, phi)/fvc::interpolate(rho)))
fvOptions makeRelative (fvc::interpolate(psi), phid)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
rho = thermo.rho()
HbyA = rAU*UEqn.H()
U = HbyA - rAU*fvc::grad(p)
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phid()
surfaceScalarField phid ("phid" , fvc::interpolate(psi) *((mesh.Sf() &fvc::interpolate(HbyA))+rhorAUf *fvc::ddtCorr(rho, U, phi)/fvc::interpolate(rho)))
Referenced by if(), kinematicSingleLayer::solveThickness(), and while().
makeRelative()
fvOptions makeRelative (fvc::interpolate(psi) , phid)
while()
while (pimple. correctNonOrthogonal())
Definition at line 22 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phid(), pimple, psi, rho, and rhorAUf().
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
HbyA
HbyA = rAU*UEqn.H()
Definition at line 7 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 44 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 47 of file pEqn.H.