OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volVectorField HbyA ("HbyA", U)
UEqn clear ()
if (simple.transonic())
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
HbyA = rAU*UEqn().H()
bool closedVolume = false
else
U = HbyA - rAU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
HbyA()
volVectorField HbyA ("HbyA" , U)
clear()
UEqn clear ()
Referenced by Foam::atan2(), cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), HashPtrTable< ThermoType >::clear(), ILList< DLListBase, Foam::molecule >::clear(), DictionaryBase< DLPtrList< T >, T >::clear(), LPtrList< DLListBase, Foam::phaseModel >::clear(), ZoneMesh< cellZone, polyMesh >::clear(), wordRe::clear(), LList< DLListBase, Foam::entry * >::clear(), DynamicList< Foam::List< int > >::clearStorage(), HashTable< Foam::phase *>::clearStorage(), DsmcCloud< DsmcParcel< ParcelType > >::DsmcCloud(), sampledPatch::expire(), sampledTriSurfaceMesh::expire(), moleculeCloud::moleculeCloud(), HashPtrTable< ThermoType >::operator=(), ILList< DLListBase, Foam::molecule >::operator=(), UILList< DLListBase, Foam::molecule >::operator=(), LPtrList< DLListBase, Foam::phaseModel >::operator=(), Matrix< RectangularMatrix< Type >, Type >::operator=(), LList< DLListBase, Foam::entry * >::operator=(), HashTable< Foam::phase *>::operator=(), MeshedSurface< Foam::face >::operator=(), dictionary::parent(), Foam::pow(), reactingMixture< ThermoType >::reactingMixture(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), FTRsurfaceFormat< Face >::read(), edgeMeshFormat::read(), OFSsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), MeshedSurface< Foam::face >::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), UPtrList< Foam::Field< Type > >::setSize(), List< functionObject *>::setSize(), PtrList< MRFZone >::setSize(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), Foam::stabilise(), ILList< DLListBase, Foam::molecule >::transfer(), Matrix< RectangularMatrix< Type >, Type >::transfer(), LPtrList< DLListBase, Foam::phaseModel >::transfer(), PtrList< MRFZone >::transfer(), LList< DLListBase, Foam::entry * >::transfer(), HashTable< Foam::phase *>::transfer(), MeshedSurface< Foam::face >::transfer(), Foam::transform(), autoPtr< Foam::lduMatrix::solver >::~autoPtr(), HashPtrTable< ThermoType >::~HashPtrTable(), HashTable< Foam::phase *>::~HashTable(), ILList< DLListBase, Foam::molecule >::~ILList(), LList< DLListBase, Foam::entry * >::~LList(), and LPtrList< DLListBase, Foam::phaseModel >::~LPtrList().
if() [1/3]
if (simple. transonic())
Definition at line 10 of file pEqn.H.
References Foam::fvc::div(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, p, phi, phid(), pRefCell, pRefValue, psi, rAU(), rho, and simple.
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
while()
while (simple. correctNonOrthogonal())
Definition at line 58 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, psi, rAU(), rho, and simple.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [2/3]
if (closedVolume)
Definition at line 93 of file pEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if() [3/3]
if (!simple. transonic())
Definition at line 103 of file pEqn.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and rho.
Variable Documentation
HbyA
HbyA = rAU*UEqn().H()
Definition at line 4 of file pEqn.H.
closedVolume
closedVolume = false
Definition at line 8 of file pEqn.H.
else
else
Initial value:
{
        surfaceScalarField phiHbyA
        (
            "phiHbyA",
            fvc::interpolate(rho*HbyA) & mesh.Sf()
        )
Definition at line 47 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 87 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 99 of file pEqn.H.