OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU ("rAU", 1.0/UEqn().A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",((fvc::interpolate(rho *HbyA) &mesh.Sf())+rhorAUf *fvc::ddtCorr(rho, U, phi))+phig)
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rhorAUf.boundaryField()))
thermo rho () -
for (int nonOrth=0;nonOrth<=nNonOrthCorr;nonOrth++)
if (thermo.dpdt())
Variables
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
rho = thermo.rho()
HbyA = rAU*UEqn().H()
p = p_rgh + rho*gh
Function Documentation
rAU()
volScalarField rAU ("rAU" , 1.0/ UEqn).A()
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , ((fvc::interpolate(rho *HbyA) &mesh.Sf())+rhorAUf *fvc::ddtCorr(rho, U, phi))+ phig)
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rhorAUf.boundaryField()))
rho()
thermo rho ()
for()
for (int nonOrth = 0; nonOrth<=nNonOrthCorr; nonOrth++)
Definition at line 50 of file pEqn.H.
References fvOptions, HbyA, Foam::fvc::laplacian(), magSqr(), mesh, nCorr, nNonOrthCorr, nOuterCorr, p_rgh, p_rghDDtEqn(), phi, phig(), phiHbyA, psi, rAU(), Foam::fvc::reconstruct(), rhorAUf(), thermo, and U.
if()
if (thermo. dpdt())
Definition at line 91 of file pEqn.H.
References compressibility, Foam::fvc::ddt(), Foam::fvc::domainIntegrate(), dpdt, gh, initialMass, p, rho, and thermo.
Variable Documentation
compressibility
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 3 of file pEqn.H.
compressible
bool compressible = (compressibility.value() > SMALL)
Definition at line 4 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 6 of file pEqn.H.
HbyA
HbyA = rAU*UEqn().H()
Definition at line 12 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 88 of file pEqn.H.