OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAUrel (1.0/UrelEqn().A())
volVectorField HbyA ("HbyA", Urel)
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rAUrel) *fvc::ddtCorr(Urel, phi))
adjustPhi (phiHbyA, Urel, p)
while (pimple.correctNonOrthogonal())
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variables
HbyA = rAUrel*UrelEqn().H()
Urel = HbyA - rAUrel*fvc::grad(p)
Function Documentation
rAUrel()
volScalarField rAUrel (1.0/ UrelEqn).A()
Referenced by if(), and while().
HbyA()
volVectorField HbyA ("HbyA" , Urel)
if()
if (pimple.nCorrPISO()<= 1)
Definition at line 5 of file pEqn.H.
References adjustPhi(), Foam::fvc::ddtCorr(), HbyA, Foam::MULES::interpolate(), mesh, p, phi, phiHbyA, rAUrel(), Urel, and UrelEqn().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rAUrel) *fvc::ddtCorr(Urel, phi))
adjustPhi()
adjustPhi (phiHbyA , Urel , p)
while()
while (pimple. correctNonOrthogonal())
Definition at line 20 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAUrel().
relax()
p relax ()
correctBoundaryConditions()
Urel correctBoundaryConditions ()
correct()
fvOptions correct (Urel)
Variable Documentation
HbyA
HbyA = rAUrel*UrelEqn().H()
Definition at line 3 of file pEqn.H.
Urel
Urel = HbyA - rAUrel*fvc::grad(p)
Definition at line 43 of file pEqn.H.
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction(), ThermoSurfaceFilm< CloudType >::bounceInteraction(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), NoBreakup< CloudType >::clone(), NoAtomization< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), AtomizationModel< Foam::SprayCloud< Foam::DsmcCloud > >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), TAB< CloudType >::clone(), LISAAtomization< CloudType >::clone(), SHF< CloudType >::clone(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), if(), SRFModel::New(), ThermoSurfaceFilm< CloudType >::splashInteraction(), BreakupModel< Foam::SprayCloud< Foam::DsmcCloud > >::TABWeCrit(), LISAAtomization< CloudType >::update(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().