OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
rho relax ()
volScalarField rAU (1.0/UEqn().A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
if (pimple.nCorrPISO()<=1)
if (pimple.transonic())
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
while (pimple.correctNonOrthogonal())
Variables
rho = thermo.rho()
HbyA = rAU*UEqn().H()
else
Function Documentation
relax()
rho relax ()
rAU()
volScalarField rAU (1.0/ UEqn).A()
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
if() [1/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 12 of file pEqn.H.
References UEqn().
if() [2/2]
if (pimple. transonic())
Definition at line 17 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, p, phi, phid(), pimple, psi, rho, rhorAUf(), and U.
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
while()
while (pimple. correctNonOrthogonal())
Definition at line 65 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), dpdt, Foam::endl(), fvOptions, Foam::fvc::grad(), Foam::Info, Foam::fvc::laplacian(), magSqr(), Foam::max(), mesh, Foam::min(), p, phi, pimple, psi, rAU(), rho, rhoMax(), rhoMin(), rhorAUf(), thermo, and U.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
HbyA
HbyA = rAU*UEqn().H()
Definition at line 10 of file pEqn.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            (fvc::interpolate(rho*HbyA) & mesh.Sf())
          + rhorAUf*fvc::ddtCorr(rho, U, phi)
        )
    )
Definition at line 53 of file pEqn.H.