OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readControls.H File Reference
Functions
if (runTime.controlDict().lookupOrDefault("suppressSolverInfo", false))
Switch adjustTimeStep (runTime.controlDict().lookup("adjustTimeStep"))
scalar maxDeltaT (readScalar(runTime.controlDict().lookup("maxDeltaT")))
Function Documentation
if()
if (runTime. controlDict).lookupOrDefault("suppressSolverInfo", false)
Definition at line 1 of file readControls.H.
References adjustTimeStep(), maxDeltaT(), and readScalar.
adjustTimeStep()
Switch adjustTimeStep (runTime. controlDict).lookup("adjustTimeStep")
Referenced by if().
maxDeltaT()
scalar maxDeltaT (readScalar(runTime.controlDict().lookup("maxDeltaT")))
Referenced by if().