OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
rho relax ()
volScalarField rAU ("rAU", 1.0/UEqn().A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
UEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(rho *HbyA) &mesh.Sf()))
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rhorAUf.boundaryField()))
while (simple.correctNonOrthogonal())
if (closedVolume)
Variables
HbyA = rAU*UEqn().H()
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
phiHbyA = phig
p = p_rgh + rho*gh
rho = thermo.rho()
Function Documentation
relax()
rho relax ()
rAU()
volScalarField rAU ("rAU" , 1.0/ UEqn).A()
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
clear()
UEqn clear ()
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(rho *HbyA) &mesh.Sf()))
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rhorAUf.boundaryField()))
while()
while (simple. correctNonOrthogonal())
Definition at line 37 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::getRefCellValue(), HbyA, Foam::fvc::laplacian(), p_rgh, phi, phig(), phiHbyA, pRefCell, rAU(), Foam::fvc::reconstruct(), rhorAUf(), simple, and U.
if()
if (closedVolume)
Definition at line 69 of file pEqn.H.
References Foam::fvc::domainIntegrate(), gh, initialMass, p, p_rgh, psi, and rho.
Variable Documentation
HbyA
HbyA = rAU*UEqn().H()
Definition at line 9 of file pEqn.H.
closedVolume
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
Definition at line 22 of file pEqn.H.
phiHbyA
phiHbyA = phig
Definition at line 24 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 65 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 76 of file pEqn.H.