OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
thermo rho () -
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phig (-rAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",((fvc::interpolate(rho *HbyA) &mesh.Sf())+rAUf *fvc::ddtCorr(rho, U, phi))+phig)
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==fvOptions(psi, p_rgh, rho.name()))
while (pimple.correctNonOrthogonal())
if (thermo.dpdt())
Variables
HbyA = rAU*UEqn.H()
p = p_rgh + rho*gh
Function Documentation
rho()
thermo rho ()
rAU()
volScalarField rAU (1.0/UEqn. A())
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phig()
surfaceScalarField phig (-rAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , ((fvc::interpolate(rho *HbyA) &mesh.Sf())+rAUf *fvc::ddtCorr(rho, U, phi))+ phig)
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
p_rghDDtEqn()
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA) = =fvOptions(psi, p_rgh, rho.name()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 47 of file pEqn.H.
References fvOptions, HbyA, Foam::fvc::laplacian(), magSqr(), mesh, p_rghDDtEqn(), phi, phig(), phiHbyA, pimple, rAU(), rAUf(), Foam::fvc::reconstruct(), and U.
if()
if (thermo. dpdt())
Definition at line 81 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 12 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 76 of file pEqn.H.