OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+rAUf *fvc::ddtCorr(U, Uf))
if (p.needReference())
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
HbyA = rAU*UEqn().H()
U = HbyA - rAU*fvc::grad(p)
Uf = n*(phi/mesh.magSf() - (n & Uf))
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
if() [1/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 6 of file pEqn.H.
References Foam::fvc::ddtCorr(), HbyA, Foam::MULES::interpolate(), mesh, phiHbyA, rAUf(), U, UEqn(), and Uf.
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+rAUf *fvc::ddtCorr(U, Uf))
if() [2/2]
if (p. needReference())
Definition at line 18 of file pEqn.H.
References adjustPhi(), makeAbsolute(), makeRelative(), p, phiHbyA, and U.
while()
while (pimple. correctNonOrthogonal())
Definition at line 25 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAUf().
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
HbyA
HbyA = rAU*UEqn().H()
Definition at line 4 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 47 of file pEqn.H.
Uf
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 54 of file pEqn.H.
Referenced by dynLagrangian::correct(), Foam::fvc::ddt(), if(), and while().