OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
if (pimple.transonic())
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh.Sf()/mesh.magSf())
if (thermo.dpdt())
Variables
rho = thermo.rho()
HbyA = rAU*UEqn.H()
else
U = HbyA - rAU*fvc::grad(p)
K = 0.5*magSqr(U)
rhoUf = n*(fvc::absolute(phi, rho, U)/mesh.magSf() - (n & rhoUf))
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by pressureGradientExplicitSource::correct(), for(), if(), and while().
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
Referenced by for(), if(), and while().
HbyA()
volVectorField HbyA ("HbyA" , U)
if() [1/2]
if (pimple. transonic())
Definition at line 9 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), makeRelative(), mesh, p, phi, phid(), pimple, psi, rAU(), rho, rhorAUf(), rhoUf, and U.
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
Referenced by if().
while()
while (pimple. correctNonOrthogonal())
Definition at line 61 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), mesh, p, phi, pimple, psi, rAU(), and rho.
correctBoundaryConditions()
U correctBoundaryConditions ()
Referenced by SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::correctBoundaryConditions(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), and solidBodyMotionFvMesh::update().
correct()
fvOptions correct (U)
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Referenced by while().
if() [2/2]
if (thermo. dpdt())
Definition at line 97 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), dpdt, Foam::fvc::meshPhi(), p, rho, and U.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
Referenced by forAllConstIter(), if(), and while().
HbyA
HbyA = rAU*UEqn.H()
Definition at line 7 of file pEqn.H.
Referenced by for(), if(), and while().
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            (fvc::interpolate(rho*HbyA) & mesh.Sf())
          + rhorAUf*fvc::ddtCorr(rho, U, rhoUf)
        )
    )
Definition at line 48 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 86 of file pEqn.H.
Referenced by interRegionExplicitPorositySource::addSup(), radialActuationDiskSource::addSup(), actuationDiskSource::addSup(), solidificationMeltingSource::addSup(), effectivenessHeatExchangerSource::addSup(), atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), mixtureKEpsilon< BasicTurbulenceModel >::bubbleG(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), powerLaw::calcForce(), forces::calcForcesMoment(), tabulatedHeatTransfer::calculateHtc(), NoBreakup< CloudType >::clone(), NoDispersion< CloudType >::clone(), StochasticDispersionRAS< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), GradientDispersionRAS< CloudType >::clone(), DispersionModel< Foam::KinematicCloud< CloudType > >::clone(), ReitzDiwakar< CloudType >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), TAB< CloudType >::clone(), SHF< CloudType >::clone(), KinematicCloud< Foam::DsmcCloud >::cloudReset(), SpecularReflection< CloudType >::correct(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), Rebound< CloudType >::correct(), LocalInteraction< CloudType >::correct(), StandardWallInteraction< CloudType >::correct(), thixotropicViscosity::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), Foam::fvc::ddt(), forces::devRhoReff(), DispersionRASModel< CloudType >::epsilonModel(), vorticity::execute(), Lambda2::execute(), Q::execute(), for(), forAllIter(), if(), FreeStream< CloudType >::inflow(), MRFSource::initialise(), DispersionRASModel< CloudType >::kModel(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), streamLineParticle::move(), turbulenceModel::New(), LESModel< BasicTurbulenceModel >::New(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), eddyViscosity< RASModel< BasicTurbulenceModel > >::nut(), MRFZoneList::operator()(), porosityModel::iNew::operator()(), KinematicCloud< Foam::DsmcCloud >::patchData(), ParticleErosion< CloudType >::postPatch(), DsmcParcel< ParcelType >::readFields(), KinematicParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::solveTABEq(), KinematicCloud< Foam::DsmcCloud >::SU(), BreakupModel< Foam::SprayCloud< Foam::DsmcCloud > >::TABWeCrit(), streamLineParticle::trackingData::trackingData(), porosityModel::transformModelData(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), SRFModel::Uabs(), dynamicMotionSolverFvMesh::update(), rawTopoChangerFvMesh::update(), dynamicInkJetFvMesh::update(), solidBodyMotionFvMesh::update(), movingWallVelocityFvPatchVectorField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), supersonicFreestreamFvPatchVectorField::updateCoeffs(), MRFZone::updateMesh(), Implicit< CloudType >::velocityCorrection(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), while(), DsmcParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), FSD< CombThermoType, ThermoType >::~FSD(), and laminar< BasicTurbulenceModel >::~laminar().
K
K = 0.5*magSqr(U)
Definition at line 89 of file pEqn.H.
rhoUf
rhoUf = n*(fvc::absolute(phi, rho, U)/mesh.magSf() - (n & rhoUf))
Definition at line 94 of file pEqn.H.
Referenced by if(), and while().