OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
YEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,Yi_h)")))
volScalarField Yt (0.0 *Y[0])
forAll (Y, i)
Y [inertIndex] max (0.0)
Variables
dQ = combustion->dQ()
label inertIndex = -1
Y [inertIndex] = scalar(1) - Yt
Function Documentation
mvConvection()
tmp<fv::convectionScheme<scalar> > mvConvection (fv::convectionScheme< scalar > ::Newmesh, fields, phi, mesh.divScheme("div(phi,Yi_h)"))
Yt()
volScalarField Yt (0.0 * Y[0])
forAll()
forAll (Y , i)
Definition at line 19 of file YEqn.H.
References combustion(), Foam::fvc::ddt(), fvOptions, inertSpecie(), Foam::fvc::laplacian(), mesh, mvConvection(), name(), phi, rho, turbulence, Y, and Yt().
max()
Y [inertIndex] max (0. 0)
Variable Documentation
dQ
dQ = combustion->dQ()
Definition at line 15 of file YEqn.H.
inertIndex
label inertIndex = -1
Definition at line 16 of file YEqn.H.
Y
Y[inertIndex] = scalar(1) - Yt
Definition at line 53 of file YEqn.H.