OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",((fvc::interpolate(rho *HbyA) &mesh.Sf())+rhorAUf *fvc::ddtCorr(rho, U, phi))+phig)
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rhorAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
if (thermo.dpdt())
Variables
rho = thermo.rho()
HbyA = rAU*UEqn.H()
p = p_rgh + rho*gh
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , ((fvc::interpolate(rho *HbyA) &mesh.Sf())+rhorAUf *fvc::ddtCorr(rho, U, phi))+ phig)
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() - fvOptions.relative(mesh.Sf().boundaryField() &U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField() *rhorAUf.boundaryField()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 34 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, gh, HbyA, Foam::fvc::laplacian(), mesh, p_rgh, phi, phig(), phiHbyA, pimple, psi, rAU(), Foam::fvc::reconstruct(), rho, rhorAUf(), surfaceFilm, and U.
if()
if (thermo. dpdt())
Definition at line 68 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
HbyA
HbyA = rAU*UEqn.H()
Definition at line 7 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 61 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 66 of file pEqn.H.