OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, Uf))
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
if (pimple.transonic())
volScalarField p_rgh_0 (p_rgh)
while (pimple.correctNonOrthogonal())
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
HbyA = rAU*UEqn.H()
phiHbyA = phig
tmp< fvScalarMatrix > p_rghEqnComp1
tmp< fvScalarMatrix > p_rghEqnComp2
else
Uf = n*(fvc::absolute(phi, U)/mesh.magSf() - (n & Uf))
rho1 = psi1*(p_rgh - p_rgh_0)
rho2 = psi2*(p_rgh - p_rgh_0)
rho = alpha1*rho1 + alpha2*rho2
K = 0.5*magSqr(U)
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, Uf))
phig()
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
if()
if (pimple. transonic())
Definition at line 41 of file pEqn.H.
References Foam::correction(), Foam::fvc::ddt(), Foam::deleteDemandDrivenData(), Foam::fvc::div(), Foam::MULES::interpolate(), p_rgh, p_rghEqnComp1, p_rghEqnComp2, phi, psi1, psi2, rho1, rho2, and Foam::fvc::Sp().
p_rgh_0()
volScalarField p_rgh_0 (p_rgh)
Referenced by forAllConstIter().
while()
while (pimple. correctNonOrthogonal())
Definition at line 80 of file pEqn.H.
References alpha1(), alpha2, Foam::fvc::div(), gh, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::max(), mesh, n(), p, p_rgh, p_rghEqnComp1, p_rghEqnComp2, phi, phig(), phiHbyA, pimple, pos(), rAU(), rAUf(), Foam::fvc::reconstruct(), rho1, rho2, solve(), U, and Uf.
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 6 of file pEqn.H.
phiHbyA
phiHbyA = phig
Definition at line 23 of file pEqn.H.
p_rghEqnComp1
tmp<fvScalarMatrix> p_rghEqnComp1
Definition at line 38 of file pEqn.H.
Referenced by if(), and while().
p_rghEqnComp2
p_rghEqnComp2
Initial value:
=
            fvc::ddt(rho2) + psi2*correction(fvm::ddt(p_rgh))
          + fvc::div(phi, rho2) - fvc::Sp(fvc::div(phi), rho2)
Definition at line 39 of file pEqn.H.
Referenced by if(), and while().
else
else
Initial value:
{
        p_rghEqnComp1 =
            fvc::ddt(rho1) + psi1*correction(fvm::ddt(p_rgh))
          + fvc::div(phi, rho1) - fvc::Sp(fvc::div(phi), rho1)
Definition at line 67 of file pEqn.H.
Uf
Uf = n*(fvc::absolute(phi, U)/mesh.magSf() - (n & Uf))
Definition at line 120 of file pEqn.H.
rho1
rho1 = psi1*(p_rgh - p_rgh_0)
Definition at line 124 of file pEqn.H.
Referenced by SprayParcel< ParcelType >::calc(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
rho2
rho2 = psi2*(p_rgh - p_rgh_0)
Definition at line 125 of file pEqn.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
rho
rho = alpha1*rho1 + alpha2*rho2
Definition at line 127 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 129 of file pEqn.H.