OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiGradp (rhorAUf *mesh.magSf() *fvc::snGrad(p))
volScalarField rho0 (rho - psi *p)
while (pimple.correctNonOrthogonal())
Variables
HbyA = rAU*UEqn.H()
phi
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phiGradp()
surfaceScalarField phiGradp (rhorAUf *mesh. magSf) *fvc::snGrad(p)
Referenced by while().
rho0()
volScalarField rho0 (rho - psi * p)
Referenced by if(), and while().
while()
while (pimple. correctNonOrthogonal())
Definition at line 30 of file pEqn.H.
References alphal, Foam::correction(), Foam::fvc::ddt(), Foam::fvc::div(), Foam::endl(), Foam::fvc::grad(), HbyA, Foam::Info, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, Foam::min(), n(), p, phiGradp(), pimple, pSat, psi, rAU(), rho, rho0(), rhof(), rhoMin(), rhorAUf(), U, and Uf.
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 18 of file pEqn.H.
phi
phi
Initial value:
= (fvc::interpolate(HbyA) & mesh.Sf())
         + rhorAUf*fvc::ddtCorr(U, Uf)
Definition at line 20 of file pEqn.H.
Referenced by for(), forAllConstIter(), forAllIter(), if(), and while().