OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn().A())
volVectorField HbyA ("HbyA", U)
UEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::interpolate(rho) *(fvc::interpolate(HbyA) &mesh.Sf()))
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
while (simple.correctNonOrthogonal())
p relax ()
thermo rho ()+
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
HbyA = rAU*UEqn().H()
U = HbyA - rAU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
rAU()
volScalarField rAU (1.0/ UEqn).A()
HbyA()
volVectorField HbyA ("HbyA" , U)
clear()
UEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::interpolate(rho) *(fvc::interpolate(HbyA) &mesh.Sf()))
makeRelative()
fvOptions makeRelative (fvc::interpolate(rho) , phiHbyA)
while()
while (simple. correctNonOrthogonal())
Definition at line 20 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phiHbyA, psi, rAU(), rho, simple, and thermo.
relax()
p relax ()
rho()
thermo rho ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
HbyA
HbyA = rAU*UEqn().H()
Definition at line 8 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 48 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 52 of file pEqn.H.