OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField alpha2f ("alpha2f", scalar(1) - alpha1f)
surfaceScalarField rAlphaAU1f (fvc::interpolate(alpha1 *rho1 *rAU1))
surfaceScalarField rAlphaAU2f (fvc::interpolate(alpha2 *rho2 *rAU2))
volVectorField HbyA1 (IOobject::groupName("HbyA", phase1.name()), U1)
volVectorField HbyA2 (IOobject::groupName("HbyA", phase2.name()), U2)
mrfZones makeAbsolute (phi1.oldTime())
mrfZones makeAbsolute (phi1)
mrfZones makeAbsolute (phi2.oldTime())
mrfZones makeAbsolute (phi2)
surfaceScalarField phiP1 ("phiP1", fvc::interpolate(rAU1 *phase1.turbulence().pPrime()) *fvc::snGrad(alpha1) *mesh.magSf())
phiP1 boundaryField () == 0
surfaceScalarField phiP2 ("phiP2", fvc::interpolate(rAU2 *phase2.turbulence().pPrime()) *fvc::snGrad(alpha2) *mesh.magSf())
surfaceScalarField phiHbyA1 (IOobject::groupName("phiHbyA", phase1.name()),(fvc::interpolate(HbyA1) &mesh.Sf())+rAlphaAU1f *fvc::ddtCorr(U1, phi1))
surfaceScalarField phiHbyA2 (IOobject::groupName("phiHbyA", phase2.name()),(fvc::interpolate(HbyA2) &mesh.Sf())+rAlphaAU2f *fvc::ddtCorr(U2, phi2))
mrfZones makeRelative (phiHbyA1)
mrfZones makeRelative (phiHbyA2)
mrfZones makeRelative (phi1.oldTime())
mrfZones makeRelative (phi1)
mrfZones makeRelative (phi2.oldTime())
mrfZones makeRelative (phi2)
surfaceScalarField phiHbyA ("phiHbyA", alpha1f *phiHbyA1+alpha2f *phiHbyA2)
surfaceScalarField rAUf ("rAUf", mag(alpha1f *rAlphaAU1f/fvc::interpolate(rho1)+alpha2f *rAlphaAU2f/fvc::interpolate(rho2)))
setSnGrad< fixedFluxPressureFvPatchScalarField > (p.boundaryField(),(phiHbyA.boundaryField() - mrfZones.relative(alpha1f.boundaryField() *(mesh.Sf().boundaryField() &U1.boundaryField())+alpha2f.boundaryField() *(mesh.Sf().boundaryField() &U2.boundaryField())))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
if (pimple.transonic())
volScalarField p_0 (p)
while (pimple.correctNonOrthogonal())
if (thermo1.dpdt()||thermo2.dpdt())
Variables
rAU1 = 1.0/U1Eqn.A()
rAU2 = 1.0/U2Eqn.A()
HbyA1 = rAU1*U1Eqn.H()
HbyA2 = rAU2*U2Eqn.H()
phiHbyA1
phiHbyA2
tmp< fvScalarMatrix > pEqnComp1
tmp< fvScalarMatrix > pEqnComp2
else
p = max(p, pMin)
rho1 = psi1*(p - p_0)
rho2 = psi2*(p - p_0)
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
alpha2f()
surfaceScalarField alpha2f ("alpha2f" , scalar(1) - alpha1f)
Referenced by while().
rAlphaAU1f()
surfaceScalarField rAlphaAU1f (fvc::interpolate(alpha1 *rho1 *rAU1))
Referenced by while().
rAlphaAU2f()
surfaceScalarField rAlphaAU2f (fvc::interpolate(alpha2 *rho2 *rAU2))
Referenced by while().
HbyA1()
volVectorField HbyA1 (IOobject::groupName("HbyA", phase1.name()) , U1)
HbyA2()
volVectorField HbyA2 (IOobject::groupName("HbyA", phase2.name()) , U2)
makeAbsolute() [1/4]
mrfZones makeAbsolute (phi1. oldTime())
Referenced by if().
makeAbsolute() [2/4]
mrfZones makeAbsolute (phi1)
makeAbsolute() [3/4]
mrfZones makeAbsolute (phi2. oldTime())
makeAbsolute() [4/4]
mrfZones makeAbsolute (phi2)
phiP1()
surfaceScalarField phiP1 ("phiP1" , fvc::interpolate(rAU1 *phase1.turbulence().pPrime()) *fvc::snGrad(alpha1) *mesh.magSf())
Referenced by while().
boundaryField()
phiP2 boundaryField () == 0
Referenced by LESModel::alphaEff(), turbulenceModel::alphat(), Foam::incompressible::autoCreateWallFunctionField(), Foam::compressible::autoCreateWallFunctionField(), wallDistData< wallPointData< vector > >::correct(), radiationCoupledBase::emissivity(), thermalBaffle::info(), LESModel::kappaEff(), Foam::MULES::limitSum(), GeometricField< vector, pointPatchField, pointMesh >::max(), GeometricField< vector, pointPatchField, pointMesh >::min(), GeometricField< vector, pointPatchField, pointMesh >::negate(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator==(), thermoSingleLayer::Qconvp(), thermoSingleLayer::Qconvw(), GeometricField< vector, pointPatchField, pointMesh >::replace(), snGradScheme< Type >::snGrad(), GeometricField< vector, pointPatchField, pointMesh >::T(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
phiP2()
surfaceScalarField phiP2 ("phiP2" , fvc::interpolate(rAU2 *phase2.turbulence().pPrime()) *fvc::snGrad(alpha2) *mesh.magSf())
Referenced by while().
phiHbyA1()
surfaceScalarField phiHbyA1 (IOobject::groupName("phiHbyA", phase1.name()) , (fvc::interpolate(HbyA1) &mesh.Sf())+rAlphaAU1f *fvc::ddtCorr(U1, phi1))
phiHbyA2()
surfaceScalarField phiHbyA2 (IOobject::groupName("phiHbyA", phase2.name()) , (fvc::interpolate(HbyA2) &mesh.Sf())+rAlphaAU2f *fvc::ddtCorr(U2, phi2))
makeRelative() [1/6]
mrfZones makeRelative (phiHbyA1)
makeRelative() [2/6]
mrfZones makeRelative (phiHbyA2)
makeRelative() [3/6]
mrfZones makeRelative (phi1. oldTime())
makeRelative() [4/6]
mrfZones makeRelative (phi1)
makeRelative() [5/6]
mrfZones makeRelative (phi2. oldTime())
makeRelative() [6/6]
mrfZones makeRelative (phi2)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , alpha1f *phiHbyA1+alpha2f * phiHbyA2)
rAUf()
surfaceScalarField rAUf ("rAUf" , mag(alpha1f *rAlphaAU1f/fvc::interpolate(rho1)+alpha2f *rAlphaAU2f/fvc::interpolate(rho2)))
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p. boundaryField(), (phiHbyA.boundaryField() - mrfZones.relative(alpha1f.boundaryField() *(mesh.Sf().boundaryField() &U1.boundaryField())+alpha2f.boundaryField() *(mesh.Sf().boundaryField() &U2.boundaryField())))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
if() [1/2]
if (pimple. transonic())
Definition at line 117 of file pEqn.H.
References alpha1(), alpha2, Foam::correction(), Foam::fvc::ddt(), Foam::deleteDemandDrivenData(), Foam::fvc::div(), fvOptions, Foam::MULES::interpolate(), p, pEqnComp1, pEqnComp2, psi1, psi2, rho1, rho2, and Foam::fvc::Sp().
p_0()
volScalarField p_0 (p)
while()
while (pimple. correctNonOrthogonal())
Definition at line 181 of file pEqn.H.
References alpha1(), alpha2, alpha2f(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::fvc::div(), fvOptions, HbyA1, HbyA2, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, mrfZones(), p, pEqnComp1, pEqnComp2, phi, phiHbyA, phiHbyA1, phiHbyA2, phiP1(), phiP2(), pimple, rAlphaAU1f(), rAlphaAU2f(), rAUf(), Foam::fvc::reconstruct(), rho1, rho2, solve(), and U.
if() [2/2]
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 263 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
rAU1
rAU1 = 1.0/U1Eqn.A()
Definition at line 5 of file pEqn.H.
rAU2
rAU2 = 1.0/U2Eqn.A()
Definition at line 6 of file pEqn.H.
HbyA1
HbyA1 = rAU1*U1Eqn.H()
Definition at line 16 of file pEqn.H.
Referenced by while().
HbyA2
HbyA2 = rAU2*U2Eqn.H()
Definition at line 23 of file pEqn.H.
Referenced by while().
phiHbyA1
phiHbyA1
Initial value:
=
    (
        fvc::interpolate(rAU1*dragCoeff)*phi2
      - phiP1
      + rAlphaAU1f*(g & mesh.Sf())
    )
Definition at line 62 of file pEqn.H.
Referenced by while().
phiHbyA2
phiHbyA2
Initial value:
=
    (
        fvc::interpolate(rAU2*dragCoeff)*phi1
      - phiP2
      + rAlphaAU2f*(g & mesh.Sf())
    )
Definition at line 69 of file pEqn.H.
Referenced by while().
pEqnComp1
tmp<fvScalarMatrix> pEqnComp1
Definition at line 114 of file pEqn.H.
Referenced by if(), and while().
pEqnComp2
pEqnComp2
Initial value:
=
            (
                fvc::ddt(alpha2, rho2) + fvc::div(alphaRhoPhi2)
              - (fvOptions(alpha2, rho2)&rho2)
              - fvc::Sp(fvc::ddt(alpha2) + fvc::div(alphaPhi2), rho2)
            )/rho2
          + (alpha2*psi2/rho2)*correction(fvm::ddt(p))
Definition at line 115 of file pEqn.H.
Referenced by if(), and while().
else
else
Initial value:
{
        pEqnComp1 =
            (
                fvc::ddt(alpha1, rho1) + fvc::div(alphaRhoPhi1)
              - (fvOptions(alpha1, rho1)&rho1)
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + (alpha1*psi1/rho1)*correction(fvm::ddt(p))
Definition at line 160 of file pEqn.H.
p
p = max(p, pMin)
Definition at line 254 of file pEqn.H.
rho1
rho1 = psi1*(p - p_0)
Definition at line 257 of file pEqn.H.
rho2
rho2 = psi2*(p - p_0)
Definition at line 258 of file pEqn.H.
K1
K1 = 0.5*magSqr(U1)
Definition at line 260 of file pEqn.H.
K2
K2 = 0.5*magSqr(U2)
Definition at line 261 of file pEqn.H.