OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
PtrList< volVectorField > HbyAs (fluid.phases().size())
PtrList< surfaceScalarField > phiHbyAs (fluid.phases().size())
PtrList< volScalarField > rAUs (fluid.phases().size())
PtrList< surfaceScalarField > rAlphaAUfs (fluid.phases().size())
forAllIter (PtrDictionary< phaseModel >, fluid.phases(), iter)
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("phiHbyA", dimArea *dimVelocity, 0))
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh), mesh, dimensionedScalar("rAUf", dimensionSet(-1, 3, 1, 0, 0), 0))
setSnGrad< fixedFluxPressureFvPatchScalarField > (p.boundaryField(),(phiHbyA.boundaryField() - mrfZones.relative(phib))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
Variables
phasei = 0
phib = 0
Function Documentation
HbyAs()
PtrList<volVectorField> HbyAs (fluid. phases).size()
Referenced by forAllIter(), and while().
phiHbyAs()
PtrList<surfaceScalarField> phiHbyAs (fluid. phases).size()
Referenced by forAllIter(), and while().
rAUs()
PtrList<volScalarField> rAUs (fluid. phases).size()
Referenced by forAllIter().
rAlphaAUfs()
PtrList<surfaceScalarField> rAlphaAUfs (fluid. phases).size()
Referenced by forAllIter(), and while().
forAllIter()
forAllIter (PtrDictionary< phaseModel > , fluid. phases(), iter)
Definition at line 34 of file pEqn.H.
References Foam::constant::atomic::alpha, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvc::ddtCorr(), Foam::dimArea, Foam::dimVelocity, dragCoeffs(), HbyAs(), Foam::MULES::interpolate(), Foam::mag(), mesh, mrfZones(), phasei, phi, phib, phiHbyA, phiHbyAs(), rAlphaAUfs(), rAUf(), rAUs(), and UEqns().
Referenced by while().
phiHbyA()
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("phiHbyA", dimArea *dimVelocity, 0))
rAUf()
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh) , mesh , dimensionedScalar("rAUf", dimensionSet(-1, 3, 1, 0, 0), 0))
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p. boundaryField(), (phiHbyA.boundaryField() - mrfZones.relative(phib))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 209 of file pEqn.H.
References Foam::constant::atomic::alpha, Foam::fvc::div(), forAllIter(), HbyAs(), Foam::fvc::laplacian(), Foam::mag(), mesh, p, phasei, phi, phiHbyA, phiHbyAs(), pimple, pRefCell, pRefValue, rAlphaAUfs(), rAUf(), Foam::fvc::reconstruct(), solve(), and U.
Variable Documentation
phasei
phasei = 0
Definition at line 33 of file pEqn.H.
phib
phib = 0
Definition at line 187 of file pEqn.H.
Referenced by forAllIter().