OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn().A())
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+rAUf *fvc::ddtCorr(U, phi))
fvOptions makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p_gh)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_gh.boundaryField(),(phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
p_gh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
HbyA = rAU*UEqn().H()
p = p_gh + (g & mesh.C())
U = HbyA - rAU*fvc::grad(p_gh)
Function Documentation
rAU()
volScalarField rAU (1.0/ UEqn).A()
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
if()
if (pimple.nCorrPISO()<= 1)
Definition at line 7 of file pEqn.H.
References adjustPhi(), Foam::fvc::ddtCorr(), fvOptions, HbyA, Foam::MULES::interpolate(), mesh, phi, phiHbyA, rAUf(), setSnGrad< fixedFluxPressureFvPatchScalarField >(), U, and UEqn().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+rAUf *fvc::ddtCorr(U, phi))
makeRelative()
fvOptions makeRelative (phiHbyA)
adjustPhi()
adjustPhi (phiHbyA , U , p_gh)
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_gh. boundaryField(), (phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 33 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, phi, phiHbyA, pimple, and rAUf().
relax()
p_gh relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
HbyA
HbyA = rAU*UEqn().H()
Definition at line 5 of file pEqn.H.
p
p = p_gh + (g & mesh.C())
Definition at line 55 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p_gh)
Definition at line 57 of file pEqn.H.