OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiGradp (rhorAUf *mesh.magSf() *fvc::snGrad(p))
while (pimple.correctNonOrthogonal())
p correctBoundaryConditions ()
Variables
HbyA = rAU*UEqn.H()
phi
Info<< "Predicted p max-min : "<< max(p).value()<< " "<< min(p).value()<< endl;rho==max(psi *p+alphal *rhol0+((alphav *psiv+alphal *psil) - psi) *pSat, rhoMin);# 1 "/home/zt/OpenFOAM/OpenFOAM-2.3.x/applications/solvers/multiphase/cavitatingFoam/alphavPsi.H" 1{ alphav=max(min((rho - rholSat)/(rhovSat - rholSat), scalar(1)), scalar(0));alphal=1.0 - alphav;Info<< "max-min alphav: "<< max(alphav).value()<< " "<< min(alphav).value()<< endl;psiModel-> correct ()
p
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phiGradp()
surfaceScalarField phiGradp (rhorAUf *mesh. magSf) *fvc::snGrad(p)
while()
while (pimple. correctNonOrthogonal())
Definition at line 27 of file pEqn.H.
References alphal, Foam::fvc::ddt(), Foam::fvc::div(), Foam::endl(), Foam::Info, Foam::fvc::laplacian(), Foam::max(), mesh, Foam::min(), p, phiGradp(), pimple, pSat, psi, rho, rhof(), rhoMin(), and rhorAUf().
correctBoundaryConditions()
p correctBoundaryConditions ()
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 18 of file pEqn.H.
phi
phi
Initial value:
= (fvc::interpolate(HbyA) & mesh.Sf())
         + rhorAUf*fvc::ddtCorr(U, phi)
Definition at line 20 of file pEqn.H.
correct
radiation correct ()
Definition at line 74 of file pEqn.H.
Referenced by porosityModel::addResistance(), interRegionHeatTransferModel::addSup(), Chung::Chung(), motionDirectionalDiffusivity::correct(), Foam::MULES::correct(), PaSR< Type >::correct(), eddyViscosity< RASModel< BasicTurbulenceModel > >::correct(), laminar< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), LESModel< BasicTurbulenceModel >::correct(), RASModel< PhaseCompressibleTurbulenceModel< phaseModel > >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), directionalDiffusivity::directionalDiffusivity(), for(), if(), inverseDistanceDiffusivity::inverseDistanceDiffusivity(), inverseFaceDistanceDiffusivity::inverseFaceDistanceDiffusivity(), inversePointDistanceDiffusivity::inversePointDistanceDiffusivity(), inverseVolumeDiffusivity::inverseVolumeDiffusivity(), linear::linear(), Foam::MULES::LTScorrect(), meshStructure::meshStructure(), sampledSets::movePoints(), patchDataWave< TransferType >::patchDataWave(), patchDist::patchDist(), patchPatchDist::patchPatchDist(), pointPatchDist::pointPatchDist(), primitiveMeshGeometry::primitiveMeshGeometry(), sampledSets::readUpdate(), chemistryModel< CompType, ThermoType >::solve(), sampledSets::updateMesh(), wallDistData< wallPointData< vector > >::wallDistData(), and Wallis::Wallis().
p
p
Initial value:
=
    (
        rho
      - alphal*rhol0
      - ((alphav*psiv + alphal*psil) - psi)*pSat
    )/psi
Definition at line 59 of file pEqn.H.