OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA, U, p_rgh)
surfaceScalarField phig (- ghf *fvc::snGrad(rho) *rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
if (p_rgh.needReference())
Variables
HbyA = rAU*UEqn.H()
phiHbyA = phig
p == p_rgh + rho*gh
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
adjustPhi()
adjustPhi (phiHbyA , U , p_rgh)
phig()
surfaceScalarField phig (- ghf * fvc::snGradrho) *rAUf *mesh.magSf()
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 33 of file pEqn.H.
References Foam::fvc::div(), Foam::getRefCellValue(), HbyA, Foam::fvc::laplacian(), mesh, p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, rAU(), rAUf(), Foam::fvc::reconstruct(), and U.
if()
if (p_rgh. needReference())
Definition at line 57 of file pEqn.H.
References Foam::getRefCellValue(), gh, p, p_rgh, pRefCell, pRefValue, and rho.
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 6 of file pEqn.H.
phiHbyA
phiHbyA = phig
Definition at line 21 of file pEqn.H.
p
p == p_rgh + rho*gh
Definition at line 55 of file pEqn.H.