OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volVectorField HbyA ("HbyA", Urel)
UrelEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::interpolate(HbyA) &mesh.Sf())
adjustPhi (phiHbyA, Urel, p)
while (simple.correctNonOrthogonal())
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variables
HbyA = rAUrel*UrelEqn().H()
Urel = HbyA - rAUrel*fvc::grad(p)
Function Documentation
HbyA()
volVectorField HbyA ("HbyA" , Urel)
clear()
UrelEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::interpolate(HbyA) &mesh.Sf())
adjustPhi()
adjustPhi (phiHbyA , Urel , p)
while()
while (simple. correctNonOrthogonal())
Definition at line 11 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, rAUrel(), and simple.
relax()
p relax ()
correctBoundaryConditions()
Urel correctBoundaryConditions ()
correct()
fvOptions correct (Urel)
Variable Documentation
HbyA
HbyA = rAUrel*UrelEqn().H()
Definition at line 4 of file pEqn.H.
Urel
Urel = HbyA - rAUrel*fvc::grad(p)
Definition at line 34 of file pEqn.H.