OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
PtrList< fvScalarMatrix > p_rghEqnComps (mixture.phases().size())
forAllConstIter (PtrDictionary< phaseModel >, mixture.phases(), phase)
volScalarField p_rgh_0 (p_rgh)
while (pimple.correctNonOrthogonal())
mixture correctRho (p_rgh - p_rgh_0)
Variables
HbyA = rAU*UEqn.H()
phiHbyA = phig
label phasei = 0
p = max(p_rgh + mixture.rho()*gh, pMin)
rho = mixture.rho()
K = 0.5*magSqr(U)
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA ("HbyA" , U)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA) &mesh.Sf())+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
phig()
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() -(mesh.Sf().boundaryField() &U.boundaryField()))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
p_rghEqnComps()
PtrList<fvScalarMatrix> p_rghEqnComps (mixture. phases).size()
Referenced by forAllConstIter(), and while().
forAllConstIter()
forAllConstIter (PtrDictionary< phaseModel > , mixture. phases(), phase)
Definition at line 39 of file pEqn.H.
References Foam::correction(), Foam::fvc::ddt(), Foam::fvc::div(), p_rgh, p_rgh_0(), p_rghEqnComps(), phi, rho, Foam::fvc::Sp(), and thermo.
Referenced by greyMeanAbsorptionEmission::aCont(), sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), topoSet::addSet(), KinematicCloud< Foam::DsmcCloud >::alpha(), boundaryRegion::append(), cellTable::append(), setToPointZone::applyToSet(), setToCellZone::applyToSet(), setToFaceZone::applyToSet(), normalToFace::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), distribution::approxTotalEntries(), boundaryRegion::boundaryTypes(), nearWallFields::calcAddressing(), cellToFaceStencil::calcFaceStencil(), forces::calcForcesMoment(), cellMatcher::calcLocalFaces(), wallShearStress::calcShearStress(), GAMGAgglomeration::calculateRegionMaster(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), topoSet::check(), argList::check(), primitiveMesh::checkCommonOrder(), primitiveMesh::checkDuplicateFaces(), edgeCollapser::checkMeshQuality(), coalCloudList::coalCloudList(), cellTable::combine(), hexRef8::consistentSlowRefinement(), inversePointDistanceDiffusivity::correct(), inverseFaceDistanceDiffusivity::correct(), patchPatchDist::correct(), pointPatchDist::correct(), nearWallFields::createFields(), functionObjectFile::createFiles(), meshRefinement::createZoneBaffles(), simpleControl::criteriaSatisfied(), pimpleControl::criteriaSatisfied(), structuredDecomp::decompose(), topoSet::deleteSet(), dictionary::digest(), KinematicCloud< Foam::DsmcCloud >::Dij(), KinematicCloud< Foam::DsmcCloud >::Dmax(), DsmcCloud< DsmcParcel< ParcelType > >::dumpParticlePositions(), edgeSurface::edgeSurface(), turbulenceFields::execute(), cellClassification::fillRegionPoints(), boundaryRegion::findIndex(), cellTable::findIndex(), coupleGroupIdentifier::findOtherPatchID(), polyMeshAdder::findSharedPoints(), forAll(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), undoableMeshCutter::getAddedCells(), surfaceSets::getHangingCells(), combineFaces::getMergeSets(), undoableMeshCutter::getSplitFaces(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission(), meshRefinement::growFaceCellFace(), if(), InjectionModelList< Foam::KinematicCloud< CloudType > >::InjectionModelList(), injectionModelList::injectionModelList(), DsmcCloud< DsmcParcel< ParcelType > >::internalEnergyOfSystem(), surfaceInterpolateFields::interpolateFields(), meshToMesh::interpolationMethodAMI(), dictionary::keys(), layerParameters::layerParameters(), lduPrimitiveMesh::lduPrimitiveMesh(), DsmcCloud< DsmcParcel< ParcelType > >::linearKineticEnergyOfSystem(), KinematicCloud< Foam::DsmcCloud >::linearKineticEnergyOfSystem(), DsmcCloud< DsmcParcel< ParcelType > >::linearMomentumOfSystem(), KinematicCloud< Foam::DsmcCloud >::linearMomentumOfSystem(), IOobjectList::lookup(), objectRegistry::lookupClass(), IOobjectList::lookupClass(), Foam::MapDimensionedFields(), DsmcCloud< DsmcParcel< ParcelType > >::massInSystem(), KinematicCloud< Foam::DsmcCloud >::massInSystem(), cellTable::materialTypes(), cellToCellStencil::merge(), cellToFaceStencil::merge(), dictionary::merge(), edgeMesh::mergeEdges(), meshRefinement::mergePatchFacesUndo(), edgeMesh::mergePoints(), MGridGenGAMGAgglomeration::MGridGenGAMGAgglomeration(), objectRegistry::modified(), MRFZone::MRFZone(), multiLevelDecomp::multiLevelDecomp(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), objectRegistry::names(), NamedEnum< directionType, 3 >::names(), boundaryRegion::names(), IOobjectList::names(), cellTable::names(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), cellCuts::nonAnchorPoints(), ListPlusEqOp< T, Size >::operator()(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), mapDistribute::transformPosition::operator()(), dictionary::operator+=(), dictionary::operator<<=(), dictionary::operator=(), dictionary::operator|=(), Foam::parseNASCoord(), ParticleForceList< KinematicCloud< CloudType > >::ParticleForceList(), patchInjection::patchInjection(), KinematicCloud< Foam::DsmcCloud >::penetration(), phaseProperties::phaseProperties(), probes::prepare(), fvMeshDistribute::printFieldInfo(), argList::printNotes(), argList::printUsage(), solutionControl::read(), NASsurfaceFormat< Face >::read(), multiMotion::read(), cloudInfo::read(), functionObjectList::read(), wallShearStress::read(), partialWrite::read(), turbulenceFields::read(), wallBoundedStreamLine::read(), forces::read(), Time::readDict(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), ReactionList< Foam::sutherlandTransport >::readReactionDict(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::reconstructLagrangianPositions(), dynamicRefineFvMesh::refine(), refinementSurfaces::refinementSurfaces(), boundaryRegion::rename(), zoltanRenumber::renumber(), structuredRenumber::renumber(), porosityModelList::reset(), MRFZoneList::reset(), optionList::reset(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), KinematicCloud< Foam::DsmcCloud >::rhoEff(), CollidingCloud< Foam::DsmcCloud >::rotationalKineticEnergyOfSystem(), nearWallFields::sampleBoundaryField(), motionSmootherAlgo::scaleMesh(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), cellTable::selectType(), ExplicitSetValue< Type >::setFieldData(), SemiImplicitSource< Type >::setFieldData(), hexRef8::setInstance(), fvMeshSubset::setLargeCellSubset(), duplicatePoints::setRefinement(), refinementIterator::setRefinement(), perfectInterface::setRefinement(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), removePoints::setRefinement(), undoableMeshCutter::setRefinement(), removeFaces::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), edgeCollapser::setRefinement(), displacementLayeredMotionMotionSolver::solve(), topoSet::subset(), dictionary::substituteKeyword(), dictionary::substituteScopedKeyword(), surfaceIntersection::surfaceIntersection(), faceSet::sync(), pointSet::sync(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), KinematicCloud< Foam::DsmcCloud >::theta(), ThermoCloud< Foam::DsmcCloud >::Tmax(), ThermoCloud< Foam::DsmcCloud >::Tmin(), dictionary::toc(), distribution::totalEntries(), globalIndexAndTransform::transformIndicesForPatches(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), Foam::unitSet(), Foam::UnMapped(), dynamicRefineFvMesh::unrefine(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), topoSet::updateLabels(), edgeVertex::updateLabels(), boundaryCutter::updateMesh(), localPointRegion::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), hexRef8::updateMesh(), USERD_get_part_coords(), USERD_get_part_node_ids(), KinematicCloud< Foam::DsmcCloud >::vDotSweep(), meshReader::warnDuplicates(), while(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), jplotGraph::write(), gnuplotGraph::write(), xmgrGraph::write(), ReactionList< Foam::sutherlandTransport >::write(), genericPointPatchField< Type >::write(), genericPolyPatch::write(), genericFvPatchField< Type >::write(), cloudInfo::write(), regionSizeDistribution::write(), dictionary::write(), IOPosition< CloudType >::writeData(), wallBoundedStreamLineParticle::writeFields(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), streamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), DsmcParcel< ParcelType >::writeFields(), wallBoundedParticle::writeFields(), molecule::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), particle< Type >::writeFields(), KinematicParcel< ParcelType >::writeFields(), objectRegistry::writeObject(), Cloud< streamLineParticle >::writePositions(), graph::writeTable(), moleculeCloud::writeXYZ(), and greyMeanSolidAbsorptionEmission::~greyMeanSolidAbsorptionEmission().
p_rgh_0()
volScalarField p_rgh_0 (p_rgh)
while()
while (pimple. correctNonOrthogonal())
Definition at line 63 of file pEqn.H.
References Foam::fvc::div(), forAllConstIter(), forAllIter(), HbyA, Foam::fvc::laplacian(), Foam::max(), mesh, mixture, p_rgh, p_rghEqnComps(), phasei, phi, phig(), phiHbyA, pimple, pos(), rAU(), rAUf(), Foam::fvc::reconstruct(), rho, solve(), thermo, and U.
correctRho()
mixture correctRho (p_rgh - p_rgh_0)
Variable Documentation
HbyA
HbyA = rAU*UEqn.H()
Definition at line 6 of file pEqn.H.
phiHbyA
phiHbyA = phig
Definition at line 23 of file pEqn.H.
phasei
label phasei = 0
Definition at line 37 of file pEqn.H.
Referenced by forAllIter(), Foam::MULES::limitSum(), and while().
p
p = max(p_rgh + mixture.rho()*gh, pMin)
Definition at line 132 of file pEqn.H.
rho
rho = mixture.rho()
Definition at line 136 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 138 of file pEqn.H.