OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
tmp< fvVectorMatrix > UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+turb.divDevRhoReff(U)==fvOptions(rho, U))
UEqn ().relax()
fvOptions constrain (UEqn())
if (momentumPredictor)
Function Documentation
UEqn() [1/2]
tmp<fvVectorMatrix> UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+turb.divDevRhoReff(U) = =fvOptions(rho, U))
UEqn() [2/2]
UEqn ()
constrain()
fvOptions constrain (UEqn())
if()
if (momentumPredictor)
Definition at line 15 of file UEqn.H.
References fvOptions, ghf, magSqr(), mesh, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn().