OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
tmp< fvVectorMatrix > UEqn (fvm::div(phi, U)+turbulence->divDevReff(U)==fvOptions(U))
UEqn ().relax()
fvOptions constrain (UEqn())
if (simple.momentumPredictor())
Function Documentation
UEqn() [1/2]
tmp<fvVectorMatrix> UEqn (fvm::div(phi, U)+turbulence->divDevReff(U) = =fvOptions(U))
UEqn() [2/2]
UEqn ()
constrain()
fvOptions constrain (UEqn())
if()
if (simple. momentumPredictor())
Definition at line 15 of file UEqn.H.
References fvOptions, ghf, mesh, p_rgh, Foam::fvc::reconstruct(), rhok, Foam::fvc::snGrad(), solve(), U, and UEqn().