OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
fvVectorMatrix UEqn (fvm::ddt(U)+fvm::div(phi, U)+turbulence->divDevReff(U)==fvOptions(U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
UEqn()
fvVectorMatrix UEqn (fvm::ddt(U)+fvm::div(phi, U)+turbulence->divDevReff(U) = =fvOptions(U))
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 16 of file UEqn.H.
References fvOptions, ghf, mesh, p_rgh, Foam::fvc::reconstruct(), rhok, Foam::fvc::snGrad(), solve(), U, and UEqn().