OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
tmp< fvVectorMatrix > UEqn (fvm::div(phi, U)+turbulence->divDevReff(U)==fvOptions(U))
mrfZones addCoriolis (UEqn())
UEqn ().relax()
if (pressureImplicitPorosity)
fvOptions constrain (UEqn())
solve (UEqn()==-fvc::grad(p))
fvOptions correct (U)
trAU ().rename("rAU")
Variables
tmp< volScalarField > trAU = 1.0/UEqn().A()
tmp< volTensorField > trTU
else
Function Documentation
UEqn() [1/2]
tmp<fvVectorMatrix> UEqn (fvm::div(phi, U)+turbulence->divDevReff(U) = =fvOptions(U))
addCoriolis()
mrfZones addCoriolis (UEqn())
UEqn() [2/2]
UEqn ()
if()
if (pressureImplicitPorosity)
Definition at line 22 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), Foam::I, inv(), nUCorr, p, pZones(), trTU, U, and UEqn().
constrain()
fvOptions constrain (UEqn())
solve()
solve (UEqn() = =-fvc::grad(p))
correct()
fvOptions correct (U)
trAU()
trAU ()
Variable Documentation
trAU
trAU = 1.0/UEqn().A()
Definition at line 19 of file UEqn.H.
trTU
tmp<volTensorField> trTU
Definition at line 20 of file UEqn.H.
else
else
Initial value:
{
        pZones.addResistance(UEqn())
Definition at line 42 of file UEqn.H.