OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createSurfaceFilmModel.H File Reference
Functions
Info<< "\Constructing surface film model"<< endl;typedef regionModels::surfaceFilmModels::surfaceFilmModel filmModelType;autoPtr< filmModelType > tsurfaceFilm (filmModelType::New(mesh, g))
Variables
filmModelType & surfaceFilm = tsurfaceFilm()
Function Documentation
tsurfaceFilm()
Info<< "\nConstructing surface film model" << endl;typedef regionModels::surfaceFilmModels::surfaceFilmModel filmModelType;autoPtr<filmModelType> tsurfaceFilm (filmModelType::New(mesh, g))
Variable Documentation
surfaceFilm
filmModelType& surfaceFilm = tsurfaceFilm()
Definition at line 6 of file createSurfaceFilmModel.H.
Referenced by KinematicCloud< Foam::DsmcCloud >::evolveCloud(), forAll(), if(), KinematicCloud< Foam::DsmcCloud >::info(), and while().