OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
correctPhi.H File Reference
Functions
if (mesh.changing())
surfaceScalarField rhof (fvc::interpolate(rho, "div(phi,rho)"))
dimensionedScalar rAUf ("rAUf", dimTime, 1.0)
while (pimple.correctNonOrthogonal())
Function Documentation
if()
if (mesh. changing())
Definition at line 1 of file correctPhi.H.
References Foam::dimTime, forAll, Foam::MULES::interpolate(), mesh, p, pcorrTypes(), phi, rAUf(), rho, rhof(), and U.
rhof()
surfaceScalarField rhof (fvc::interpolate(rho, "div(phi,rho)"))
Referenced by if(), kinematicSingleLayer::solveThickness(), and while().
rAUf()
dimensionedScalar rAUf ("rAUf" , dimTime , 1. 0)
while()
while (pimple. correctNonOrthogonal())
Definition at line 43 of file correctPhi.H.
References Foam::fvc::ddt(), Foam::fvc::div(), Foam::fvc::laplacian(), phi, pimple, rho, and rhof().