OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setrDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.lookupOrDefault< scalar >("maxCo", 0.8))
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTDampingCoeff", 1.0))
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar >("maxDeltaT", GREAT))
volScalarField rDeltaT0 ("rDeltaT0", rDeltaT)
rDeltaT dimensionedInternalField ()
if (pimple.transonic())
rDeltaT correctBoundaryConditions ()
Function Documentation
maxCo()
scalar maxCo (pimpleDict.lookupOrDefault< scalar > "maxCo", 0.8)
Referenced by if().
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.02)
Referenced by if().
rDeltaTDampingCoeff()
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTDampingCoeff", 1.0)
Referenced by if().
maxDeltaT()
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar > "maxDeltaT", GREAT)
rDeltaT0()
volScalarField rDeltaT0 ("rDeltaT0" , rDeltaT)
dimensionedInternalField()
rDeltaT dimensionedInternalField ()
Referenced by advectiveFvPatchField< Type >::advectiveFvPatchField(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), kkLOmega::correct(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), cyclicAMIFvPatchField< Type >::cyclicAMIFvPatchField(), cyclicFvPatchField< Type >::cyclicFvPatchField(), emptyFvPatchField< Type >::emptyFvPatchField(), energyRegionCoupledFvPatchScalarField::energyRegionCoupledFvPatchScalarField(), fluxCorrectedVelocityFvPatchVectorField::evaluate(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), calculatedFvPatchField< Type >::gradientBoundaryCoeffs(), genericFvPatchField< Type >::gradientBoundaryCoeffs(), calculatedFvPatchField< Type >::gradientInternalCoeffs(), genericFvPatchField< Type >::gradientInternalCoeffs(), if(), basicThermo::lookupThermo(), mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), GeometricField< vector, pointPatchField, pointMesh >::operator=(), GeometricField< vector, pointPatchField, pointMesh >::operator==(), processorCyclicFvPatchField< Type >::processorCyclicFvPatchField(), processorFvPatchField< Type >::processorFvPatchField(), codedFixedValueFvPatchField< Type >::redirectPatchField(), codedFixedValuePointPatchField< Type >::redirectPatchField(), codedMixedFvPatchField< Type >::redirectPatchField(), P1::Ru(), fvDOM::Ru(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), cyclicPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), symmetryFvPatchField< Type >::symmetryFvPatchField(), symmetryPlaneFvPatchField< Type >::symmetryPlaneFvPatchField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField(), cellMotionFvPatchField< Type >::updateCoeffs(), fixedShearStressFvPatchVectorField::updateCoeffs(), freestreamPressureFvPatchScalarField::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), pressureInletVelocityFvPatchVectorField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), mappedFixedValueFvPatchField< Type >::updateCoeffs(), pressureNormalInletOutletVelocityFvPatchVectorField::updateCoeffs(), pressureInletOutletParSlipVelocityFvPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), mappedFieldFvPatchField< Type >::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), fanPressureFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), pressureDirectedInletVelocityFvPatchVectorField::updateCoeffs(), pressureDirectedInletOutletVelocityFvPatchVectorField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), supersonicFreestreamFvPatchVectorField::updateCoeffs(), syringePressureFvPatchScalarField::updateCoeffs(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), calculatedFvPatchField< Type >::valueBoundaryCoeffs(), genericFvPatchField< Type >::valueBoundaryCoeffs(), calculatedFvPatchField< Type >::valueInternalCoeffs(), genericFvPatchField< Type >::valueInternalCoeffs(), wedgeFvPatchField< Type >::wedgeFvPatchField(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), externalCoupledMixedFvPatchField< scalar >::writeData(), externalCoupledMixedFvPatchField< scalar >::writeGeometry(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), and externalCoupledMixedFvPatchField< scalar >::~externalCoupledMixedFvPatchField().
if()
if (pimple. transonic())
Definition at line 34 of file setrDeltaT.H.
References dimensionedInternalField(), Foam::endl(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::MULES::interpolate(), Foam::mag(), max(), maxCo(), mesh, phid(), psi, rDeltaT(), rDeltaT0(), rDeltaTDampingCoeff(), rDeltaTSmoothingCoeff(), Foam::fvc::smooth(), Foam::fvc::surfaceSum(), and U.
correctBoundaryConditions()
rDeltaT correctBoundaryConditions ()