OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFluidFields.H File Reference
Functions
PtrList< rhoThermo > thermoFluid (fluidRegions.size())
PtrList< volScalarField > rhoFluid (fluidRegions.size())
PtrList< volVectorField > UFluid (fluidRegions.size())
PtrList< surfaceScalarField > phiFluid (fluidRegions.size())
PtrList< uniformDimensionedVectorField > gFluid (fluidRegions.size())
PtrList< compressible::turbulenceModel > turbulence (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList< radiation::radiationModel > radiation (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< label > pRefCellFluid (fluidRegions.size(), 0)
List< scalar > pRefValueFluid (fluidRegions.size(), 0.0)
List< bool > frozenFlowFluid (fluidRegions.size(), false)
PtrList< dimensionedScalar > rhoMax (fluidRegions.size())
PtrList< dimensionedScalar > rhoMin (fluidRegions.size())
PtrList< fv::IOoptionList > fluidFvOptions (fluidRegions.size())
forAll (fluidRegions, i)
Function Documentation
thermoFluid()
PtrList<rhoThermo> thermoFluid (fluidRegions. size())
Referenced by forAll().
rhoFluid()
PtrList<volScalarField> rhoFluid (fluidRegions. size())
Referenced by forAll().
UFluid()
PtrList<volVectorField> UFluid (fluidRegions. size())
Referenced by forAll().
phiFluid()
PtrList<surfaceScalarField> phiFluid (fluidRegions. size())
Referenced by forAll().
gFluid()
PtrList<uniformDimensionedVectorField> gFluid (fluidRegions. size())
Referenced by forAll().
turbulence()
PtrList<compressible::turbulenceModel> turbulence (fluidRegions. size())
Referenced by forAll().
p_rghFluid()
PtrList<volScalarField> p_rghFluid (fluidRegions. size())
Referenced by forAll().
ghFluid()
PtrList<volScalarField> ghFluid (fluidRegions. size())
Referenced by forAll().
ghfFluid()
PtrList<surfaceScalarField> ghfFluid (fluidRegions. size())
Referenced by forAll().
radiation()
PtrList<radiation::radiationModel> radiation (fluidRegions. size())
Referenced by forAll().
initialMassFluid()
List<scalar> initialMassFluid (fluidRegions. size())
Referenced by forAll().
pRefCellFluid()
List<label> pRefCellFluid (fluidRegions. size(), 0)
Referenced by forAll().
pRefValueFluid()
List<scalar> pRefValueFluid (fluidRegions. size(), 0. 0)
Referenced by forAll().
frozenFlowFluid()
List<bool> frozenFlowFluid (fluidRegions. size(), false)
Referenced by forAll().
rhoMax()
PtrList<dimensionedScalar> rhoMax (fluidRegions. size())
Referenced by forAll(), if(), WallSpringSliderDashpot< CloudType >::nSubCycles(), PairSpringSliderDashpot< CloudType >::nSubCycles(), WallLocalSpringSliderDashpot< CloudType >::nSubCycles(), and while().
rhoMin()
PtrList<dimensionedScalar> rhoMin (fluidRegions. size())
Referenced by forAll(), if(), and while().
fluidFvOptions()
PtrList<fv::IOoptionList> fluidFvOptions (fluidRegions. size())
Referenced by forAll().
forAll()
forAll (fluidRegions , i)
Definition at line 24 of file createFluidFields.H.
References C, Foam::fvc::domainIntegrate(), Foam::endl(), fluidFvOptions(), fluidRegions(), frozenFlowFluid(), gFluid(), ghfFluid(), ghFluid(), Foam::Info, initialMassFluid(), Foam::linearInterpolate(), Foam::nl, p, p_rghFluid(), phiFluid(), pRefCellFluid(), pRefValueFluid(), radiation(), rho, rhoFluid(), rhoMax(), rhoMin(), Foam::setRefCell(), T, thermoFluid(), turbulence(), and UFluid().