OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
correctPhi.H File Reference
Functions
dimensionedScalar rAUf ("rAUf", dimTime/rho.dimensions(), 1.0)
adjustPhi (phi, U, pcorr)
while (pimple.correctNonOrthogonal())
Function Documentation
rAUf()
dimensionedScalar rAUf ("rAUf" , dimTime/rho. dimensions(), 1. 0)
adjustPhi()
adjustPhi (phi , U , pcorr)
while()
while (pimple. correctNonOrthogonal())
Definition at line 23 of file correctPhi.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), phi, pimple, pRefCell, pRefValue, and rAUf().