OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createZones.H File Reference
Functions
IOMRFZoneList mrfZones (mesh)
mrfZones correctBoundaryVelocity (U)
IOporosityModelList pZones (mesh)
Switch pressureImplicitPorosity (false)
if (pZones.active())
Variables
int nUCorr = 0
Function Documentation
mrfZones()
IOMRFZoneList mrfZones (mesh)
Referenced by forAllIter(), and while().
correctBoundaryVelocity()
mrfZones correctBoundaryVelocity (U)
pZones()
IOporosityModelList pZones (mesh)
pressureImplicitPorosity()
Switch pressureImplicitPorosity (false)
if()
if (pZones. active())
Definition at line 9 of file createZones.H.
References Foam::endl(), Foam::Info, pressureImplicitPorosity(), and simple.
Variable Documentation
nUCorr
int nUCorr = 0
Definition at line 8 of file createZones.H.