OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphaEqnsSubCycle.H File Reference
Functions
volScalarField divU (fvc::div(fvc::absolute(phi, U)))
if (nAlphaSubCycles > 1)
Variables
phic = min(interface.cAlpha()*phic, max(phic))
Function Documentation
divU()
volScalarField divU (fvc::div(fvc::absolute(phi, U)))
Referenced by lowReOneEqEddy::correct(), oneEqEddy::correct(), homogeneousDynOneEqEddy::correct(), kEqn< BasicTurbulenceModel >::correct(), kEpsilon::correct(), RNGkEpsilon::correct(), LaunderSharmaKE::correct(), realizableKE::correct(), kEpsilon< BasicTurbulenceModel >::correct(), v2f::correct(), kOmegaSST::correct(), for(), if(), and while().
if()
if (nAlphaSubCycles , 1)
Definition at line 9 of file alphaEqnsSubCycle.H.
References alpha1(), mesh, nAlphaSubCycles(), and rhoPhi.
Variable Documentation
phic
phic = min(interface.cAlpha()*phic, max(phic))
Definition at line 5 of file alphaEqnsSubCycle.H.
Referenced by if(), ETAB< CloudType >::update(), TAB< CloudType >::update(), and while().