OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
if (MULESCorr)
for (int aCorr=0;aCorr< nAlphaCorr;aCorr++)
if (alphaApplyPrevCorr &&MULESCorr)
Variables
alpha2 = 1.0 - alpha1
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
Referenced by for().
if() [1/2]
if (MULESCorr)
Definition at line 5 of file alphaEqn.H.
References alpha1(), alphaApplyPrevCorr(), correct, Foam::endl(), Foam::Info, Foam::MULES::LTScorrect(), Foam::max(), mesh, Foam::min(), mixture, phi, phiAlpha(), rDeltaT(), solve(), and tphiAlphaCorr0.
for()
for ()
Definition at line 64 of file alphaEqn.H.
References alpha1(), alpha10(), alpharScheme(), correct, Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), Foam::fvc::flux(), Foam::MULES::LTScorrect(), mixture, MULESCorr(), phi, phiAlpha(), and phir().
if() [2/2]
if (alphaApplyPrevCorr && MULESCorr)
Definition at line 144 of file alphaEqn.H.
References phiAlpha(), and tphiAlphaCorr0.
Variable Documentation
alpha2
alpha2 = 1.0 - alpha1
Definition at line 149 of file alphaEqn.H.
Referenced by for(), if(), and while().