OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
tmp< fv::ddtScheme< scalar > > ddtAlpha (fv::ddtScheme< scalar >::New(mesh, mesh.ddtScheme("ddt(alpha)")))
if (isType< fv::EulerDdtScheme< scalar > >(ddtAlpha())||isType< fv::localEulerDdtScheme< scalar > >(ddtAlpha()))
else if (isType< fv::CrankNicolsonDdtScheme< scalar > >(ddtAlpha()))
surfaceScalarField phic (mixture.cAlpha() *mag(phi/mesh.magSf()))
if (icAlpha > 0)
forAll (phic.boundaryField(), patchi)
tmp< surfaceScalarField > phiCN (phi)
if (ocCoeff > 0)
if (MULESCorr)
for (int aCorr=0;aCorr< nAlphaCorr;aCorr++)
if (alphaApplyPrevCorr &&MULESCorr)
if (word(mesh.ddtScheme("ddt(rho,U)"))==fv::EulerDdtScheme< vector >::typeName)
Variables
scalar ocCoeff = 0
else
scalar cnCoeff = 1.0/(1.0 + ocCoeff)
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
ddtAlpha()
tmp<fv::ddtScheme<scalar> > ddtAlpha (fv::ddtScheme< scalar > ::Newmesh, mesh.ddtScheme("ddt(alpha)"))
Referenced by if().
if() [1/7]
if (isType< fv::EulerDdtScheme< scalar > > ddtAlpha())||isType< fv::localEulerDdtScheme< scalar > >(ddtAlpha())
Definition at line 17 of file alphaEqn.H.
if() [2/7]
else if (isType< fv::CrankNicolsonDdtScheme< scalar > > ddtAlpha())
Definition at line 24 of file alphaEqn.H.
References args, ddtAlpha(), argList::executable(), Foam::exit(), Foam::FatalError, FatalErrorIn, nAlphaSubCycles(), and ocCoeff.
phic()
surfaceScalarField phic (mixture. cAlpha) *mag(phi/mesh.magSf())
Referenced by for(), forAll(), and if().
if() [3/7]
if (icAlpha , 0)
Definition at line 50 of file alphaEqn.H.
References icAlpha(), Foam::MULES::interpolate(), Foam::mag(), mixture, phic(), and U.
forAll()
forAll (phic. boundaryField(), patchi)
Definition at line 58 of file alphaEqn.H.
References patchi, phi, phic(), and phiCN().
phiCN()
tmp<surfaceScalarField> phiCN (phi)
Referenced by forAll(), and if().
if() [4/7]
if (ocCoeff , 0)
Definition at line 71 of file alphaEqn.H.
References cnCoeff, and phi.
if() [5/7]
if (MULESCorr)
Definition at line 76 of file alphaEqn.H.
References alpha1(), alpha2, alphaApplyPrevCorr(), correct, Foam::endl(), Foam::Info, Foam::MULES::LTScorrect(), Foam::max(), mesh, Foam::min(), mixture, phiAlpha(), phiCN(), rDeltaT(), and tphiAlphaCorr0.
for()
for ()
Definition at line 125 of file alphaEqn.H.
References alpha1(), alpha10(), alpha2, alpharScheme(), cnCoeff, correct, Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), Foam::fvc::flux(), Foam::MULES::LTScorrect(), mixture, MULESCorr(), phi, phiAlpha(), phic(), and phir().
if() [6/7]
if (alphaApplyPrevCorr && MULESCorr)
Definition at line 190 of file alphaEqn.H.
References phiAlpha(), and tphiAlphaCorr0.
if() [7/7]
if (word(mesh.ddtScheme("ddt(rho,U)")) = = fv::EulerDdtScheme<vector>::typeName)
Definition at line 196 of file alphaEqn.H.
References alpha1(), cnCoeff, Foam::endl(), Foam::Info, Foam::max(), mesh, Foam::min(), phi, phiAlpha(), rho1, rho2, and rhoPhi.
Variable Documentation
ocCoeff
scalar ocCoeff = 0
Definition at line 15 of file alphaEqn.H.
Referenced by if().
else
else
Initial value:
{
        FatalErrorIn(args.executable())
            << "Only Euler and CrankNicolson ddt schemes are supported"
            << exit(FatalError)
Definition at line 38 of file alphaEqn.H.
cnCoeff
scalar cnCoeff = 1.0/(1.0 + ocCoeff)
Definition at line 44 of file alphaEqn.H.
Referenced by for(), and if().