OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqns.H File Reference
Functions
PtrList< fvVectorMatrix > UEqns (fluid.phases().size())
autoPtr< multiphaseSystem::dragCoeffFields > dragCoeffs (fluid.dragCoeffs())
forAllIter (PtrDictionary< phaseModel >, fluid.phases(), iter)
Variables
int phasei = 0
Function Documentation
UEqns()
PtrList<fvVectorMatrix> UEqns (fluid. phases).size()
Referenced by forAllIter().
dragCoeffs()
autoPtr<multiphaseSystem::dragCoeffFields> dragCoeffs (fluid. dragCoeffs())
Referenced by forAllIter().
forAllIter()
forAllIter (PtrDictionary< phaseModel > , fluid. phases(), iter)
fvm::Sp(fluid.dragCoeff(phase, dragCoeffs())/phase.rho(), U) (alpha*phase.rho())*fluid.lift(phase)
+
Definition at line 7 of file UEqns.H.
References Foam::constant::atomic::alpha, Foam::fvc::ddt(), Foam::dev(), Foam::dimVelocity, Foam::fvc::div(), Foam::fvc::grad(), Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, mrfZones(), Foam::pow(), sgsModel, Foam::fvc::Sp(), T, U, and UEqns().
Variable Documentation
phasei
int phasei = 0
Definition at line 6 of file UEqns.H.