OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createTimes.H File Reference
Functions
Info<< "\Create databases as time"<< endl;HashTable< string > srcOptions (args.options())
srcOptions erase ("case")
srcOptions insert ("case", fileName(rootDirSource/caseDirSource))
argList argsSrc (args, srcOptions, false, false, false)
Time runTimeSource (Time::controlDictName, argsSrc)
Time runTimeTarget (Time::controlDictName, args)
Function Documentation
srcOptions()
Info<< "\nCreate databases as time" << endl; HashTable<string> srcOptions (args. options())
erase()
srcOptions erase ("case")
Referenced by HashTable< Foam::phase *>::erase(), HashSet< Foam::word >::operator-=(), HashSet< Foam::word >::operator^=(), HashSet< Foam::word >::operator|=(), and HashPtrTable< ThermoType >::remove().
insert()
srcOptions insert ("case" , fileName(rootDirSource/caseDirSource))
argsSrc()
argList argsSrc (args , srcOptions , false , false , false)
runTimeSource()
Time runTimeSource (Time::controlDictName , argsSrc)
runTimeTarget()
Time runTimeTarget (Time::controlDictName , args)