OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
if (mesh.nCells() !=1)
Info<< "Reading initial conditions.\"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=readScalar(initialConditions.lookup("p"));scalar T0=readScalar(initialConditions.lookup("T"));# 24 "/home/zt/OpenFOAM/OpenFOAM-2.3.x/applications/solvers/combustion/chemFoam/createFields.H" 2 Info<< nl<< "Reading thermophysicalProperties"<< endl;autoPtr< psiChemistryModel > pChemistry (psiChemistryModel::New(mesh))
thermo validate (args.executable(), "h")
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimVelocity, vector::zero), p.boundaryField().types())
Info<< "Creating turbulence model.\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
OFstream post (args.path()/"chemFoam.out")
Variables
psiChemistryModel & chemistry = pChemistry()
scalar dtChem = refCast<const psiChemistryModel>(chemistry).deltaTChem()[0]
psiReactionThermo & thermo = chemistry.thermo()
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Function Documentation
if()
if (mesh.nCells() ! = 1)
Definition at line 1 of file createFields.H.
References args, Foam::endl(), argList::executable(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, mesh, Foam::nl, pChemistry(), and readScalar.
pChemistry()
Info<< "Reading initial conditions.\n" << endl; IOdictionary initialConditions (IOobject ("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); scalar p0 = readScalar(initialConditions.lookup("p")); scalar T0 = readScalar(initialConditions.lookup("T"));# 24 "/home/zt/OpenFOAM/OpenFOAM-2.3.x/applications/solvers/combustion/chemFoam/createFields.H" 2 Info<< nl << "Reading thermophysicalProperties" << endl; autoPtr<psiChemistryModel> pChemistry (psiChemistryModel::New(mesh))
Referenced by if().
validate()
thermo validate (args. executable(), "h")
Referenced by surfMesh::surfZones().
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Rspecific()
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
U()
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimVelocity, vector::zero) , p. boundaryField).types()
Referenced by forAll(), and if().
turbulence()
Info<< "Creating turbulence model.\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
post()
OFstream post (args.path()/"chemFoam.out")
Variable Documentation
chemistry
psiChemistryModel& chemistry = pChemistry()
Definition at line 29 of file createFields.H.
dtChem
scalar dtChem = refCast<const psiChemistryModel>(chemistry).deltaTChem()[0]
Definition at line 30 of file createFields.H.
Referenced by if().
thermo
psiReactionThermo& thermo = chemistry.thermo()
Definition at line 32 of file createFields.H.
Referenced by LiquidEvaporationBoil< CloudType >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), for(), forAll(), forAllConstIter(), if(), laminar< Type >::R(), ReactingCloud< Foam::DsmcCloud >::ReactingCloud(), ReactingCloud< Foam::DsmcCloud >::setParcelThermoProperties(), singleStepCombustion< CombThermoType, ThermoType >::singleStepCombustion(), chemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::tc(), and while().
composition
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 35 of file createFields.H.
Referenced by ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), ReactingMultiphaseCloud< Foam::DsmcCloud >::checkParcelProperties(), ReactingCloud< Foam::DsmcCloud >::checkParcelProperties(), SprayParcel< ParcelType >::chi(), if(), ReactingCloud< Foam::DsmcCloud >::ReactingCloud(), ReactingMultiphaseCloud< Foam::DsmcCloud >::ReactingMultiphaseCloud(), SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), ReactingMultiphaseCloud< Foam::DsmcCloud >::setParcelThermoProperties(), ReactingCloud< Foam::DsmcCloud >::setParcelThermoProperties(), SprayCloud< Foam::DsmcCloud >::SprayCloud(), ReactingMultiphaseCloud< Foam::DsmcCloud >::writeFields(), and ReactingCloud< Foam::DsmcCloud >::writeFields().
Y
PtrList<volScalarField>& Y = composition.Y()
Definition at line 36 of file createFields.H.
Referenced by SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), LiquidEvaporationBoil< CloudType >::calculate(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), LiquidEvaporation< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), PhaseChangeModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), laminar< Type >::correct(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), singleStepReactingMixture< ThermoType >::fresCorrect(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), if(), ReactingParcel< ParcelType >::readFields(), coordSet::scalarCoord(), SprayCloud< Foam::DsmcCloud >::setParcelThermoProperties(), basicSymmetryFvPatchField< Type >::snGradTransformDiag(), symmetryPlaneFvPatchField< Type >::snGradTransformDiag(), fixedNormalSlipFvPatchField< Type >::snGradTransformDiag(), partialSlipFvPatchField< Type >::snGradTransformDiag(), directionMixedFvPatchField< Type >::snGradTransformDiag(), Vector< vector >::Vector(), Vector2D< scalar >::Vector2D(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), ReactingParcel< ParcelType >::writeFields(), Vector2D< scalar >::y(), and Vector< vector >::y().
p
volScalarField& p = thermo.p()
Definition at line 51 of file createFields.H.
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), autoLayerDriver::addLayers(), advectiveFvPatchField< Type >::advectiveFvPatchField(), KinematicCloud< Foam::DsmcCloud >::alpha(), attachPolyTopoChanger::attach(), Cloud< streamLineParticle >::autoMap(), SprayParcel< ParcelType >::calcBreakup(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), ThermoParcel< ParcelType >::calcHeatTransfer(), Stochastic< CloudType >::calculate(), KinematicParcel< ParcelType >::calcVelocity(), polyMeshTetDecomposition::checkFaceTets(), NoInteraction< CloudType >::clone(), NoDamping< CloudType >::clone(), NoPacking< CloudType >::clone(), Rebound< CloudType >::clone(), SphereDragForce< CloudType >::clone(), NoSurfaceFilm< CloudType >::clone(), VirtualMassForce< CloudType >::clone(), GravityForce< CloudType >::clone(), SRFForce< CloudType >::clone(), ErgunWenYuDragForce< CloudType >::clone(), PlessisMasliyahDragForce< CloudType >::clone(), WenYuDragForce< CloudType >::clone(), PressureGradientForce< CloudType >::clone(), ParamagneticForce< CloudType >::clone(), Relaxation< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), VoidFraction< CloudType >::clone(), LiftForce< CloudType >::clone(), LocalInteraction< CloudType >::clone(), Implicit< CloudType >::clone(), Explicit< CloudType >::clone(), BrownianMotionForce< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), NonInertialFrameForce< CloudType >::clone(), PatchPostProcessing< CloudType >::clone(), ParticleTrap< CloudType >::clone(), StandardWallInteraction< CloudType >::clone(), ParticleForce< CloudType >::clone(), ParticleTracks< CloudType >::clone(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), ParticleErosion< CloudType >::clone(), CloudFunctionObject< CloudType >::clone(), iC3H8O::clone(), nC3H8O::clone(), C8H10::clone(), H2O::clone(), C9H20::clone(), MultiInteraction< CloudType >::clone(), aC10H7CH3::clone(), C3H8::clone(), Ar::clone(), bC10H7CH3::clone(), C10H22::clone(), C12H26::clone(), C13H28::clone(), C14H30::clone(), C16H34::clone(), C2H5OH::clone(), C2H6::clone(), C2H6O::clone(), C3H6O::clone(), C4H10O::clone(), C6H14::clone(), C6H6::clone(), C7H16::clone(), C7H8::clone(), C8H18::clone(), CH3OH::clone(), CH4N2O::clone(), IC8H18::clone(), MB::clone(), N2::clone(), NonSphereDragForce< CloudType >::clone(), PhaseChangeModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), FacePostProcessing< CloudType >::clone(), IDEA::clone(), SurfaceFilmModel< Foam::KinematicCloud< CloudType > >::clone(), cyclicAMIPolyPatch::clone(), ThermoSurfaceFilm< CloudType >::clone(), ParticleCollector< CloudType >::clone(), KinematicCloud< Foam::DsmcCloud >::cloneBare(), SuppressionCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collide(), molecule::constantProperties::constantProperties(), face::contactSphereDiameter(), trackedParticle::correctAfterParallelTransfer(), cyclicACMIGAMGInterfaceField::cyclicACMIGAMGInterfaceField(), cyclicAMIGAMGInterfaceField::cyclicAMIGAMGInterfaceField(), cyclicGAMGInterfaceField::cyclicGAMGInterfaceField(), fvFieldDecomposer::decomposeField(), IOstream::defaultPrecision(), Cloud< streamLineParticle >::deleteParticle(), LiquidEvaporationBoil< CloudType >::dh(), KinematicCloud< Foam::DsmcCloud >::Dij(), plane::ray::dir(), KinematicCloud< Foam::DsmcCloud >::Dmax(), Foam::domainName(), pitchForkRing::energy(), atmBoundaryLayer::epsilon(), externalCoupledMixedFvPatchField< scalar >::externalCoupledMixedFvPatchField(), mappedPatchBase::facePoint(), for(), forAll(), pitchForkRing::force(), FreeStream< CloudType >::FreeStream(), PatchTools::gatherAndMerge(), get_geom_list(), Hash< Foam::label >::Hash(), heThermo< BasicSolidThermo, MixtureType >::he(), findCellParticle::hitPatch(), particle< Type >::hitWallFaces(), if(), ILList< DLListBase, Foam::molecule >::ILList(), Ostream::incrIndent(), FreeStream< CloudType >::inflow(), polyPatch::initMovePoints(), DsmcCloud< DsmcParcel< ParcelType > >::internalEnergyOfSystem(), regionModel::interRegionAMI(), cell::labels(), DsmcCloud< DsmcParcel< ParcelType > >::linearKineticEnergyOfSystem(), KinematicCloud< Foam::DsmcCloud >::linearKineticEnergyOfSystem(), DsmcCloud< DsmcParcel< ParcelType > >::linearMomentumOfSystem(), KinematicCloud< Foam::DsmcCloud >::linearMomentumOfSystem(), pyramid< Point, PointRef, polygonRef >::mag(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), DsmcCloud< DsmcParcel< ParcelType > >::massInSystem(), KinematicCloud< Foam::DsmcCloud >::massInSystem(), cellDistFuncs::mesh(), MeshedSurface< Foam::face >::MeshedSurface(), layeredEngineMesh::move(), DsmcParcel< ParcelType >::move(), Cloud< streamLineParticle >::move(), MPPICParcel< ParcelType >::move(), CollidingParcel< ParcelType >::move(), surfaceInterpolation::movePoints(), NamedEnum< directionType, 3 >::names(), regionModel::nbrCoupledPatchID(), tetrahedron< Point, PointRef >::nearestPoint(), pointPatchField< vector >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), fvsPatchField< Type >::NewCalculatedType(), fvPatchField< Type >::NewCalculatedType(), surfacePatch::operator!=(), geometricSurfacePatch::operator!=(), listPlusEqOp< T >::operator()(), sigmaRadial::operator()(), Hash< Foam::string >::operator()(), tetrahedron< Point, PointRef >::storeOp::operator()(), Hash< Foam::word >::operator()(), Hash< Foam::fileName >::operator()(), Hash< Foam::wordRe >::operator()(), Hash< Foam::keyType >::operator()(), KinematicParcel< ParcelType >::iNew::operator()(), Foam::operator*(), Foam::operator/(), curvedEdge::operator=(), token::operator=(), surfacePatch::operator==(), dynamicTreeDataPoint::overlaps(), wallBoundedParticle::patchInteraction(), KinematicCloud< Foam::DsmcCloud >::penetration(), cell::points(), cellShape::points(), triFace::points(), face::points(), PatchPostProcessing< CloudType >::postPatch(), processorGAMGInterfaceField::processorGAMGInterfaceField(), triangle< Point, PointRef >::ray(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), CollidingParcel< ParcelType >::readFields(), DsmcParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), KinematicParcel< ParcelType >::readFields(), UILList< DLListBase, Foam::molecule >::remove(), SLListBase::remove(), autoPtr< Foam::lduMatrix::solver >::reset(), linear< Type >::rho(), KinematicCloud< Foam::DsmcCloud >::rhoEff(), CollidingCloud< Foam::DsmcCloud >::rotationalKineticEnergyOfSystem(), general::sample(), multiNormal::sample(), coordSet::scalarCoord(), autoPtr< Foam::lduMatrix::solver >::set(), PointIndexHit< Point >::setPoint(), PointHit< point >::setPoint(), liquidMixtureProperties::sigma(), liquidMixtureProperties::size(), ode< ChemistryModel >::solve(), SprayParcel< ParcelType >::solveTABEq(), basicMultiComponentMixture::species(), thermo< Thermo, Type >::thermo(), constantFilmThermo::thermoData::thermoData(), KinematicCloud< Foam::DsmcCloud >::theta(), ThermoCloud< Foam::DsmcCloud >::Tmax(), ThermoCloud< Foam::DsmcCloud >::Tmin(), dictionary::topDict(), CV2D::toPoint2D(), CV2D::toPoint3D(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), streamLineParticle::trackingData::trackingData(), wallBoundedStreamLineParticle::trackingData::trackingData(), particle< Type >::trackToFace(), heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu(), infiniteReactionRate::type(), thirdBodyArrheniusReactionRate::type(), ArrheniusReactionRate::type(), LandauTellerReactionRate::type(), powerSeriesReactionRate::type(), JanevReactionRate::type(), solidArrheniusReactionRate::type(), LangmuirHinshelwoodReactionRate::type(), FallOffReactionRate< ReactionRate, FallOffFunction >::type(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::type(), hConstThermo< EquationOfState >::typeName(), constTransport< Thermo >::typeName(), eConstThermo< EquationOfState >::typeName(), polynomialTransport< Thermo, PolySize >::typeName(), janafThermo< EquationOfState >::typeName(), hPolynomialThermo< EquationOfState, PolySize >::typeName(), hExponentialThermo< EquationOfState >::typeName(), sutherlandTransport< Thermo >::typeName(), SHF< CloudType >::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), ReactingParcel< ParcelType >::updateMassFraction(), meshRefinement::userFaceData(), KinematicCloud< Foam::DsmcCloud >::vDotSweep(), coordSet::vectorCoord(), block::vtxLabel(), waveTransmissiveFvPatchField< Type >::waveTransmissiveFvPatchField(), while(), OBJedgeFormat::write(), OBJstream::write(), boundaryPatch::write(), dsmcFields::write(), wallBoundedParticle::write(), meshToMeshMethod::writeConnectivity(), IOPosition< CloudType >::writeData(), wallBoundedStreamLineParticle::writeFields(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), streamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), DsmcParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), Cloud< streamLineParticle >::writePositions(), liquidMixtureProperties::Xs(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~IrreversibleReaction(), leastSquaresVectors::~leastSquaresVectors(), liquidProperties::~liquidProperties(), multiComponentMixture< ThermoType >::~multiComponentMixture(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~NonEquilibriumReversibleReaction(), RaviPetersen::~RaviPetersen(), Reaction< ReactionThermo >::~Reaction(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~ReversibleReaction(), skewCorrectionVectors::~skewCorrectionVectors(), SpecieMixture< MixtureType >::~SpecieMixture(), thermophysicalFunction::~thermophysicalFunction(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().