OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
IOdictionary pdfDictionary (IOobject("pdfDict", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
const label nIntervals (readLabel(pdfDictionary.lookup("nIntervals")))
const label nSamples (readLabel(pdfDictionary.lookup("nSamples")))
const bool writeData (readBool(pdfDictionary.lookup("writeData")))
mkDir (pdfPath)
cachedRandom rndGen (label(0), -1)
autoPtr< distributionModels::distributionModel > p (distributionModels::distributionModel::New(pdfDictionary, rndGen))
autoPtr< OFstream > filePtr (NULL)
if (writeData)
scalarField samples (nIntervals, 0)
Variables
const fileName pdfPath = runTime.path()/"pdf"
const scalar xMin = p->minValue()
const scalar xMax = p->maxValue()
Function Documentation
pdfDictionary()
IOdictionary pdfDictionary (IOobject("pdfDict", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
nIntervals()
const label nIntervals (readLabel(pdfDictionary.lookup("nIntervals")))
Referenced by if(), and uniformInterpolationTable< scalar >::uniformInterpolationTable().
nSamples()
const label nSamples (readLabel(pdfDictionary.lookup("nSamples")))
Referenced by ParticleTracks< CloudType >::postFace().
writeData()
const bool writeData (readBool(pdfDictionary.lookup("writeData")))
Referenced by externalCoupledMixedFvPatchField< scalar >::evaluate(), starcdSurfaceWriter::writeData(), Constant< Type >::writeData(), Table< Type >::writeData(), TableFile< Type >::writeData(), vtkSurfaceWriter::writeData(), dxSurfaceWriter::writeData(), rawSurfaceWriter::writeData(), CSV< Type >::writeData(), DimensionedField< Type, Foam::pointMesh >::writeData(), and regIOobject::writeObject().
mkDir()
mkDir (pdfPath)
rndGen()
cachedRandom rndGen (label(0) , - 1)
Referenced by procFacesGAMGProcAgglomeration::agglomerate(), meshSearch::boundaryTree(), Stochastic< CloudType >::calculate(), meshSearch::cellTree(), polyMesh::cellTree(), NoAtomization< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), AtomizationModel< Foam::SprayCloud< Foam::DsmcCloud > >::clone(), LISAAtomization< CloudType >::clone(), VariableHardSphere< CloudType >::collide(), LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), ConeNozzleInjection< CloudType >::ConeNozzleInjection(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), meshRefinement::distribute(), triSurfaceMesh::edgeTree(), extendedEdgeMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), patchProbes::findElements(), mappedPatchBase::findSamples(), FreeStream< CloudType >::inflow(), distributionModel::New(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), PatchFlowRateInjection< CloudType >::parcelsToInject(), extendedEdgeMesh::pointTree(), refinementFeatures::regionEdgeTrees(), edgeIntersections::removeDegenerates(), randomRenumber::renumber(), PatchInjection< CloudType >::setPositionAndCell(), PatchFlowRateInjection< CloudType >::setPositionAndCell(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeNozzleInjection< CloudType >::setProperties(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), TAB< CloudType >::update(), SHF< CloudType >::update(), while(), and Stochastic< CloudType >::~Stochastic().
p()
autoPtr<distributionModels::distributionModel> p (distributionModels::distributionModel::New(pdfDictionary, rndGen))
filePtr()
autoPtr<OFstream> filePtr (NULL)
Referenced by if().
if()
if (writeData)
Definition at line 38 of file createFields.H.
References Foam::endl(), filePtr(), Foam::Info, nIntervals(), Foam::nl, p, samples(), and scalarField().
samples()
scalarField samples (nIntervals , 0)
Referenced by mappedPatchBase::calcMapping(), refinementFeatures::distances(), if(), sampledPatchInternalField::interpolateField(), mappedPatchFieldBase< Type >::mappedField(), triSurfaceSearch::maxTreeDepth(), interpolationWeights::New(), surfaceFeatures::nInternalEdges(), refinementSurfaces::nRegions(), and searchableSurfaces::regionNames().
Variable Documentation
pdfPath
const fileName pdfPath = runTime.path()/"pdf"
Definition at line 20 of file createFields.H.
xMin
const scalar xMin = p->minValue()
Definition at line 34 of file createFields.H.
xMax
const scalar xMax = p->maxValue()
Definition at line 35 of file createFields.H.
Referenced by uniformInterpolationTable< scalar >::interpolate(), and uniformInterpolationTable< scalar >::uniformInterpolationTable().