OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);singlePhaseTransportModel laminarTransport(U, phi);autoPtr< incompressible::LESModel > sgsModel (incompressible::LESModel::New(U, phi, laminarTransport))
volScalarField::GeometricBoundaryField d (nearWallDist(mesh).y())
Function Documentation
sgsModel()
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);singlePhaseTransportModel laminarTransport(U, phi);autoPtr<incompressible::LESModel> sgsModel (incompressible::LESModel::New(U, phi, laminarTransport))
d()
volScalarField::GeometricBoundaryField d (nearWallDist(mesh).y())
Referenced by isoSurface::adaptPatchFields(), polyMeshGeometry::affectedCells(), anisotropicFilter::anisotropicFilter(), momentOfInertia::applyParallelAxisTheorem(), searchableSurfaceToFaceZone::applyToSet(), primitiveMeshTools::boundaryFaceSkewness(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), ThermoParcel< ParcelType >::calcHeatTransfer(), mappedPatchBase::calcMapping(), mapNearestMethod::calculateAddressing(), primitiveMeshGeometry::checkFaceDotProduct(), searchableSurfaces::checkIntersection(), edgeCollapser::checkMeshQuality(), NoPhaseChange< CloudType >::clone(), NoSurfaceReaction< CloudType >::clone(), NoBreakup< CloudType >::clone(), NoAtomization< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), AtomizationModel< Foam::SprayCloud< Foam::DsmcCloud > >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), SurfaceReactionModel< Foam::ReactingMultiphaseCloud< Foam::DsmcCloud > >::clone(), LISAAtomization< CloudType >::clone(), TAB< CloudType >::clone(), COxidationDiffusionLimitedRate< CloudType >::clone(), SHF< CloudType >::clone(), COxidationKineticDiffusionLimitedRate< CloudType >::clone(), COxidationHurtMitchell< CloudType >::clone(), PhaseChangeModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), COxidationIntrinsicRate< CloudType >::clone(), COxidationMurphyShaddix< CloudType >::clone(), cyclicAMIPolyPatch::clone(), TrajectoryCollision< CloudType >::collideParcels(), Foam::component(), VectorSpace< Vector< vector >, vector, 3 >::component(), autoSnapDriver::detectNearSurfaces(), Distribution< Type >::Distribution(), KinematicCloud< Foam::DsmcCloud >::Dmax(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), HarrisCrighton::dTaudTheta(), cellQuality::faceNonOrthogonality(), primitiveMeshTools::faceOrthogonality(), mappedPatchBase::facePoint(), primitiveMeshTools::faceSkewness(), mapNearestMethod::findNearestCell(), general::general(), geomDecomp::geomDecomp(), if(), linearInterpolationWeights::integrationWeights(), meshRefinement::isGap(), meshRefinement::isNormalGap(), Foam::LUDecompose(), meshRefinement::mergeBaffles(), Moment< Type >::Moment(), KinematicParcel< ParcelType >::move(), NamedEnum< directionType, 3 >::names(), line< Point, PointRef >::nearestDist(), cellQuality::nonOrthogonality(), listPlusEqOp< T >::operator()(), linearDirection::operator()(), sector::operator()(), TroeFallOffFunction::operator()(), anisotropicFilter::operator()(), distribution::operator=(), Distribution< Type >::operator=(), VectorSpace< Vector< vector >, vector, 3 >::operator[](), InflationInjection< CloudType >::parcelsToInject(), Foam::parseNASCoord(), KinematicCloud< Foam::DsmcCloud >::penetration(), searchableCylinder::points(), faceSource::processSameTypeValues(), cellSource::processValues(), quaternion::quaternion(), forces::read(), KinematicParcel< ParcelType >::readFields(), Foam::readLongLong(), fvMatrix< Type >::relax(), VectorSpace< Vector< vector >, vector, 3 >::replace(), general::sample(), PointHit< point >::setDistance(), patchInjectionBase::setPositionAndCell(), addPatchCellLayer::setRefinement(), EulerImplicit< ChemistryModel >::solve(), SprayParcel< ParcelType >::solveTABEq(), ThermoSurfaceFilm< CloudType >::splashInteraction(), splineInterpolationWeights::splineInterpolationWeights(), GeometricField< vector, pointPatchField, pointMesh >::T(), BreakupModel< Foam::SprayCloud< Foam::DsmcCloud > >::TABWeCrit(), tetCell::tetCell(), tetPoints::tetPoints(), ReitzKHRT< CloudType >::update(), ReitzDiwakar< CloudType >::update(), ETAB< CloudType >::update(), TAB< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), cylindricalInletVelocityFvPatchVectorField::updateCoeffs(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), dimensionSet::write(), KinematicParcel< ParcelType >::writeFields(), writer< Foam::SphericalTensor >::writeVS(), DimensionedField< Type, Foam::pointMesh >::~DimensionedField(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().