OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
const word cloudName (propsDict.lookup("cloudName"))
label sampleFrequency (readLabel(propsDict.lookup("sampleFrequency")))
label maxPositions (readLabel(propsDict.lookup("maxPositions")))
word setFormat (propsDict.lookupOrDefault< word >("setFormat", "vtk"))
Function Documentation
propsDict()
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
Referenced by pressureGradientExplicitSource::pressureGradientExplicitSource(), fieldAverage::readAveragingProperties(), and fieldAverage::writeAveragingProperties().
cloudName()
const word cloudName (propsDict. lookup"cloudName")
Referenced by Relaxation< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), KinematicCloud< Foam::DsmcCloud >::cloudReset(), if(), Foam::MapLagrangianFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), and cloudInfo::write().
sampleFrequency()
label sampleFrequency (readLabel(propsDict.lookup("sampleFrequency")))
maxPositions()
label maxPositions (readLabel(propsDict.lookup("maxPositions")))
setFormat()
word setFormat (propsDict.lookupOrDefault< word > "setFormat", "vtk")