OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
thermo validate (args.executable(), "h", "e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "\Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variables
psiThermo & thermo = pThermo()
volScalarField & p = thermo.p()
const volScalarField & psi = thermo.psi()
const volScalarField & T = thermo.T()
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n" << endl; autoPtr<psiThermo> pThermo (psiThermo::New(mesh))
validate()
thermo validate (args. executable(), "h" , "e")
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
turbulence()
Info<< "\nReading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Creating turbulence model\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variable Documentation
thermo
psiThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 23 of file createFields.H.
psi
const volScalarField& psi = thermo.psi()
Definition at line 24 of file createFields.H.
Referenced by Amultiplier< Type, LUType >::addAmul(), SemiImplicitSource< Type >::addSup(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), LduMatrix< Type, DType, LUType >::asymmetric(), lduMatrix::asymmetric(), rotorDiskSource::constructGeometry(), Foam::fvc::DDt(), Foam::MULES::explicitSolve(), for(), if(), Foam::MULES::implicitSolve(), lduMatrix::solver::interfaces(), lduMatrix::smoother::interfaces(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), LduMatrix< Type, DType, LUType >::solver::matrix(), LduMatrix< Type, DType, LUType >::smoother::matrix(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), interpolation< Foam::Vector >::New(), CrankNicolsonDdtScheme< Type >::ocCoeff(), fixedTrim::read(), diagonalSolver::read(), fvMatrix< Type >::setValuesFromList(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), targetCoeffTrim::thetag(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), EulerCoordinateRotation::transformVector(), while(), PBiCCCG< Type, DType, LUType >::~PBiCCCG(), PBiCG::~PBiCG(), PBiCICG< Type, DType, LUType >::~PBiCICG(), PCG::~PCG(), PCICG< Type, DType, LUType >::~PCICG(), and smoothSolver::~smoothSolver().
T
const volScalarField& T = thermo.T()
Definition at line 25 of file createFields.H.
Referenced by UList< Foam::wordRe >::assign(), UList< Foam::wordRe >::byteSize(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), FixedList< bool, Foam::pTraits< Type >::nComponents >::cdata(), SprayParcel< ParcelType >::chi(), MixedDiffuseSpecular< CloudType >::correct(), particle< Type >::correctAfterParallelTransfer(), Foam::createWithValues(), mapDistribute::distribute(), eddyViscosity< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), laminar< BasicTurbulenceModel >::divDevRhoReff(), Dictionary< simpleObjectRegistryEntry >::erase(), HashPtrTable< ThermoType >::erase(), ILList< DLListBase, Foam::molecule >::erase(), ILList< DLListBase, Foam::molecule >::eraseHead(), LPtrList< DLListBase, Foam::phaseModel >::eraseHead(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), for(), forAll(), forAllIter(), DictionaryBase< DLPtrList< T >, T >::found(), meshRefinement::gAverage(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::H(), HashPtrTable< ThermoType >::HashPtrTable(), CompositionModel< Foam::ReactingCloud< Foam::DsmcCloud > >::Hs(), if(), Dual< Type >::interpolateGrad(), thermo< Thermo, Type >::K(), hExponentialThermo< EquationOfState >::limit(), List< functionObject *>::List(), LList< DLListBase, Foam::entry * >::LList(), dictionary::lookupOrDefault(), Moment< Type >::Moment(), sutherlandTransport< Thermo >::mu(), radiationModel::New(), LandauTellerReactionRate::operator()(), JanevReactionRate::operator()(), autoPtr< Foam::lduMatrix::solver >::operator()(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator()(), StaticHashTable< T, Key, Hash >::operator()(), autoPtr< Foam::lduMatrix::solver >::operator->(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator->(), CompactIOList< face, label >::operator=(), HashPtrTable< ThermoType >::operator=(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator=(), List< functionObject *>::operator=(), UList< Foam::wordRe >::operator=(), PtrList< MRFZone >::operator=(), FixedList< bool, Foam::pTraits< Type >::nComponents >::operator==(), UList< Foam::wordRe >::operator==(), PtrList< MRFZone >::operator[](), StaticHashTable< T, Key, Hash >::operator[](), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), perfectFluid< Specie >::psi(), PengRobinsonGas< Specie >::psi(), autoPtr< Foam::lduMatrix::solver >::ptr(), tmp< Foam::surfaceInterpolationScheme< GType > >::ptr(), PtrList< MRFZone >::read(), ThermoParcel< ParcelType >::readFields(), Foam::ReadHex(), HashPtrTable< ThermoType >::remove(), DictionaryBase< DLPtrList< T >, T >::remove(), DynamicList< Foam::List< int > >::remove(), UPtrList< Foam::Field< Type > >::reorder(), PtrList< MRFZone >::reorder(), perfectFluid< Specie >::rho(), incompressiblePerfectGas< Specie >::rho(), PengRobinsonGas< Specie >::rho(), hExponentialThermo< EquationOfState >::s(), autoPtr< Foam::lduMatrix::solver >::set(), UPtrList< Foam::Field< Type > >::set(), List< functionObject *>::setSize(), PtrList< MRFZone >::setSize(), ode< ChemistryModel >::solve(), HashTable< Foam::phase *>::sortedToc(), FixedList< bool, Foam::pTraits< Type >::nComponents >::swap(), UList< Foam::wordRe >::swap(), FieldField< Foam::Field, LUType >::T(), Field< Foam::Vector2D >::T(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), meshRefinement::testSyncBoundaryFaceList(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THs(), tmp< Foam::surfaceInterpolationScheme< GType > >::tmp(), FixedList< bool, Foam::pTraits< Type >::nComponents >::transfer(), Foam::transform(), meshRefinement::updateList(), HashPtrTable< ThermoType >::write(), FixedList< bool, Foam::pTraits< Type >::nComponents >::writeEntry(), UList< Foam::wordRe >::writeEntry(), ThermoParcel< ParcelType >::writeFields(), and PengRobinsonGas< Specie >::Z().