OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
bool inviscid (true)
if (max(mu.internalField()) > 0.0)
Variables
psiThermo & thermo = pThermo()
volScalarField & p = thermo.p()
volScalarField & e = thermo.he()
Elementary charge.
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
const volScalarField & mu = thermo.mu()
Atomic mass unit.
Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);# 35 "/home/zt/OpenFOAM/OpenFOAM-2.3.x/applications/solvers/compressible/rhoCentralFoam/createFields.H" 2volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho(), rhoBoundaryTypes);volVectorField rhoU(IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *U);volScalarField rhoE(IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *(e+0.5 *magSqr(U)));surfaceScalarField pos(IOobject("pos", runTime.timeName(), mesh), mesh, dimensionedScalar("pos", dimless, 1.0));surfaceScalarField neg(IOobject("neg", runTime.timeName(), mesh), mesh, dimensionedScalar("neg", dimless, -1.0));surfaceScalarField phi("phi", mesh.Sf() &fvc::interpolate(rhoU));Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiThermo> pThermo (psiThermo::New(mesh))
inviscid()
bool inviscid (true)
Referenced by if().
if()
if (max(mu.internalField()) , 0. 0)
Definition at line 16 of file createFields.H.
References Foam::dimless, Foam::endl(), Foam::Info, Foam::MULES::interpolate(), inviscid(), magSqr(), mesh, neg(), phi, pos(), rho, rhoBoundaryTypes, rhoE, turbulence, and U().
Variable Documentation
thermo
psiThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 9 of file createFields.H.
e
volScalarField& e = thermo.he()
Elementary charge.
Definition at line 10 of file createFields.H.
T
const volScalarField& T = thermo.T()
Definition at line 11 of file createFields.H.
psi
const volScalarField& psi = thermo.psi()
Definition at line 12 of file createFields.H.
mu
const volScalarField& mu = thermo.mu()
Atomic mass unit.
Definition at line 13 of file createFields.H.
Referenced by interRegionExplicitPorositySource::addSup(), forces::calcForcesMoment(), incompressibleTwoPhaseMixture::calcNu(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), NoBreakup< CloudType >::clone(), NoAtomization< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), AtomizationModel< Foam::SprayCloud< Foam::DsmcCloud > >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), LISAAtomization< CloudType >::clone(), TAB< CloudType >::clone(), SHF< CloudType >::clone(), KinematicCloud< Foam::DsmcCloud >::cloudReset(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), if(), Foam::interpolateSplineXY(), sutherlandTransport< Thermo >::kappa(), filmViscosityModel::New(), porosityModel::iNew::operator()(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), SprayParcel< ParcelType >::readFields(), turbulenceModel::rhoEpsilonEff(), laminar::Su(), BreakupModel< Foam::SprayCloud< Foam::DsmcCloud > >::TABWeCrit(), porosityModel::transformModelData(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), splineInterpolationWeights::valueWeights(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), and SprayParcel< ParcelType >::writeFields().
turbulence
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);# 35 "/home/zt/OpenFOAM/OpenFOAM-2.3.x/applications/solvers/compressible/rhoCentralFoam/createFields.H" 2volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho(), rhoBoundaryTypes);volVectorField rhoU(IOobject ("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*U);volScalarField rhoE(IOobject ("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*(e + 0.5*magSqr(U)));surfaceScalarField pos(IOobject ("pos", runTime.timeName(), mesh), mesh, dimensionedScalar("pos", dimless, 1.0));surfaceScalarField neg(IOobject ("neg", runTime.timeName(), mesh), mesh, dimensionedScalar("neg", dimless, -1.0));surfaceScalarField phi("phi", mesh.Sf() & fvc::interpolate(rhoU));Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence(compressible::turbulenceModel::New(rho, U, phi, thermo))
Definition at line 105 of file createFields.H.