OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
const word dictName ("particleTrackDict")
IOdictionary propsDict (dictIO)
word cloudName (propsDict.lookup("cloudName"))
List< word > userFields (propsDict.lookup("fields"))
Function Documentation
dictName()
const word dictName ("particleTrackDict")
Referenced by if(), basicThermo::lookupThermo(), and basicThermo::New().
propsDict()
IOdictionary propsDict (dictIO)
cloudName()
word cloudName (propsDict. lookup"cloudName")
userFields()
List<word> userFields (propsDict. lookup"fields")