OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "\Reading transportProperties\"<< endl;IOdictionary transportProperties(IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));dimensionedScalar rhoInfValue(transportProperties.lookup("rhoInf"));volScalarField rhoInf(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, rhoInfValue);Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);singlePhaseTransportModel laminarTransport(U, phi);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
volScalarField mu (IOobject("mu", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), laminarTransport.nu() *rhoInfValue)
word kinematicCloudName ("kinematicCloud")
args optionReadIfPresent ("cloudName", kinematicCloudName)
if (Hheader.headerOk())
IOobject HdotGradHheader ("HdotGradH", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (HdotGradHheader.headerOk())
Variables
Info<< "Constructing kinematicCloud "<< kinematicCloudName<< endl;basicKinematicCollidingCloud kinematicCloud(kinematicCloudName, rhoInf, U, mu, g);IOobject Hheader("H", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE);autoPtr< volVectorField > HPtr
autoPtr< volVectorField > HdotGradHPtr
Function Documentation
turbulence()
Info<< "\nReading transportProperties\n" << endl; IOdictionary transportProperties (IOobject ("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); dimensionedScalar rhoInfValue (transportProperties.lookup("rhoInf")); volScalarField rhoInf (IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, rhoInfValue); Info<< "Reading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); singlePhaseTransportModel laminarTransport(U, phi); autoPtr<incompressible::turbulenceModel> turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
mu()
volScalarField mu (IOobject("mu", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , laminarTransport.nu() * rhoInfValue)
kinematicCloudName()
word kinematicCloudName ("kinematicCloud")
optionReadIfPresent()
args optionReadIfPresent ("cloudName" , kinematicCloudName)
if() [1/2]
if (Hheader. headerOk())
Definition at line 94 of file createFields.H.
References Foam::endl(), HdotGradHheader(), Foam::Info, and mesh.
HdotGradHheader()
IOobject HdotGradHheader ("HdotGradH" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if() [2/2]
if (HdotGradHheader. headerOk())
Definition at line 112 of file createFields.H.
References Foam::endl(), HdotGradHheader(), Foam::Info, and mesh.
Variable Documentation
HPtr
Info<< "Constructing kinematicCloud " << kinematicCloudName << endl; basicKinematicCollidingCloud kinematicCloud (kinematicCloudName, rhoInf, U, mu, g); IOobject Hheader ("H", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE); autoPtr<volVectorField> HPtr
Definition at line 92 of file createFields.H.
HdotGradHPtr
autoPtr<volVectorField> HdotGradHPtr
Definition at line 110 of file createFields.H.