OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating face flux\"<< endl;surfaceScalarField phi(IOobject("phi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("zero", mesh.Sf().dimensions() *U.dimensions(), 0.0));singlePhaseTransportModel laminarTransport(U, phi);autoPtr< incompressible::RASModel > turbulence (incompressible::RASModel::New(U, phi, laminarTransport))
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
dimensionedVector Ubar (transportProperties.lookup("Ubar"))
dimensionedVector gradP ("gradP", dimensionSet(0, 1, -2, 0, 0), vector::zero)
Variables
vector flowDirection = (Ubar/mag(Ubar)).value()
tensor flowMask = sqr(flowDirection)
Function Documentation
turbulence()
Info<< "Reading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Creating face flux\n" << endl; surfaceScalarField phi (IOobject ("phi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("zero", mesh.Sf().dimensions()*U.dimensions(), 0.0)); singlePhaseTransportModel laminarTransport(U, phi); autoPtr<incompressible::RASModel> turbulence (incompressible::RASModel::New(U, phi, laminarTransport))
transportProperties()
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Referenced by forces::devRhoReff(), forAll(), if(), forces::mu(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and turbulentHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
Ubar()
dimensionedVector Ubar (transportProperties. lookup"Ubar")
gradP()
dimensionedVector gradP ("gradP" , dimensionSet(0, 1, -2, 0, 0) , vector::zero)
Variable Documentation
flowDirection
vector flowDirection = (Ubar/mag(Ubar)).value()
Definition at line 54 of file createFields.H.
flowMask
tensor flowMask = sqr(flowDirection)
Definition at line 55 of file createFields.H.