OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Creating combustion model\"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(), "h", "e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.contains(inertSpecie))
forAll (Y, i)
fields add (thermo.he())
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField rhoEffLagrangian (IOobject("rhoEffLagrangian", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimDensity, 0.0))
volScalarField pDyn (IOobject("pDyn", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimPressure, 0.0))
Info<< "\Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
Variables
psiReactionThermo & thermo = combustion->thermo()
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
combustion()
Info<< "Creating combustion model\n" << endl; autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel::New(mesh))
validate()
thermo validate (args. executable(), "h" , "e")
slgThermo()
SLGThermo slgThermo (mesh , thermo)
inertSpecie()
const word inertSpecie (thermo. lookup"inertSpecie")
if()
if (!composition. containsinertSpecie)
Definition at line 18 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalError, FatalErrorIn, and inertSpecie().
forAll()
forAll (Y , i)
Definition at line 32 of file createFields.H.
References combustion(), Foam::dimDensity, Foam::dimEnergy, Foam::dimPressure, Foam::dimTime, dpdt, dQ(), Foam::endl(), Foam::Info, magSqr(), mesh, pDyn(), phi, rho, rhoEffLagrangian(), turbulence, and U().
add()
fields add (thermo. he())
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
rhoEffLagrangian()
volScalarField rhoEffLagrangian (IOobject("rhoEffLagrangian", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimDensity, 0.0))
Referenced by forAll().
pDyn()
volScalarField pDyn (IOobject("pDyn", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimPressure, 0.0))
Referenced by rotorDiskSource::calculate(), pressureTools::execute(), forAll(), and forceCoeffs::write().
turbulence()
Info<< "\nReading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Creating turbulence model\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
setTurbulence()
combustion setTurbulence (turbulence())
Variable Documentation
thermo
psiReactionThermo& thermo = combustion->thermo()
Definition at line 8 of file createFields.H.
composition
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 13 of file createFields.H.
Y
PtrList<volScalarField>& Y = composition.Y()
Definition at line 14 of file createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 26 of file createFields.H.
T
const volScalarField& T = thermo.T()
Definition at line 27 of file createFields.H.
psi
const volScalarField& psi = thermo.psi()
Definition at line 28 of file createFields.H.
fields
multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 30 of file createFields.H.