OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
volScalarField & alpha1 (mixture->alpha1())
volScalarField & alpha2 (mixture->alpha2())
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT), alpha1 *rho1+alpha2 *rho2, alpha1.boundaryField().types())
rho oldTime ()
interfaceProperties interface (alpha1, U, mixture())
autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, mixture()))
Variables
Info<< "Reading field p_rgh\"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating phaseChangeTwoPhaseMixture\"<< endl;autoPtr< phaseChangeTwoPhaseMixture > mixture
const dimensionedScalar & rho1 = mixture->rho1()
const dimensionedScalar & rho2 = mixture->rho2()
const dimensionedScalar & pSat = mixture->pSat()
Function Documentation
alpha1()
volScalarField& alpha1 (mixture-> alpha1())
Referenced by for(), if(), and while().
alpha2()
volScalarField& alpha2 (mixture-> alpha2())
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT) , alpha1 *rho1+alpha2 * rho2, alpha1. boundaryField).types()
oldTime()
rho oldTime ()
interface()
interfaceProperties interface (alpha1 , U , mixture())
Referenced by lduPrimitiveMesh::gather(), if(), and LUscalarMatrix::LUscalarMatrix().
turbulence()
autoPtr<incompressible::turbulenceModel> turbulence (incompressible::turbulenceModel::New(U, phi, mixture()))
Variable Documentation
mixture
Info<< "Reading field p_rgh\n" << endl; volScalarField p_rgh (IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Reading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Creating phaseChangeTwoPhaseMixture\n" << endl; autoPtr<phaseChangeTwoPhaseMixture> mixture
Initial value:
=
        phaseChangeTwoPhaseMixture::New(U, phi)
Definition at line 33 of file createFields.H.
Referenced by for(), if(), EulerImplicit< ChemistryModel >::solve(), and while().
rho1
const dimensionedScalar& rho1 = mixture->rho1()
Definition at line 39 of file createFields.H.
rho2
const dimensionedScalar& rho2 = mixture->rho2()
Definition at line 40 of file createFields.H.
pSat
const dimensionedScalar& pSat = mixture->pSat()
Definition at line 41 of file createFields.H.
Referenced by LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), standardPhaseChange::correctModel(), fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs(), and while().