OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readTransportProperties.H File Reference
Functions
singlePhaseTransportModel laminarTransport (U, phi)
dimensionedScalar beta (laminarTransport.lookup("beta"))
dimensionedScalar TRef (laminarTransport.lookup("TRef"))
dimensionedScalar Pr (laminarTransport.lookup("Pr"))
dimensionedScalar Prt (laminarTransport.lookup("Prt"))
Function Documentation
laminarTransport()
singlePhaseTransportModel laminarTransport (U , phi)
beta()
dimensionedScalar beta (laminarTransport. lookup"beta")
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), Euler< Type >::clone(), Analytical< Type >::clone(), IntegrationScheme< Type >::clone(), TrajectoryCollision< CloudType >::collideParcels(), rotorDiskSource::constructGeometry(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), Analytical< Type >::integrate(), triangleFuncs::intersectAxesBundle(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), PCICG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PCG::solve(), PBiCG::solve(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
TRef()
dimensionedScalar TRef (laminarTransport. lookup"TRef")
Referenced by StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::Iterator(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator!=(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator()(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator++(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator=(), and StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator==().
Pr()
dimensionedScalar Pr (laminarTransport. lookup"Pr")
Referenced by ThermoParcel< ParcelType >::calc(), RanzMarshall< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), HeatTransferModel< Foam::ThermoCloud< CloudType > >::clone(), LiquidEvaporationBoil< CloudType >::clone(), PhaseChangeModel< Foam::ReactingCloud< Foam::DsmcCloud > >::clone(), SRIFallOffFunction::operator()(), TroeFallOffFunction::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), SprayParcel< ParcelType >::iNew::operator()(), ThermoParcel< ParcelType >::iNew::operator()(), LindemannFallOffFunction::type(), TroeFallOffFunction::type(), SRIFallOffFunction::type(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
Prt()
dimensionedScalar Prt (laminarTransport. lookup"Prt")