var searchData=
[
  ['radial',['radial',['../a24794.html',1,'Foam::extrudeModels']]],
  ['radialactuationdisksource',['radialActuationDiskSource',['../a23478.html',1,'Foam::fv']]],
  ['radialmodel',['radialModel',['../a32290.html',1,'Foam::kineticTheoryModels']]],
  ['radiationcoupledbase',['radiationCoupledBase',['../a30006.html',1,'radiationCoupledBase'],['../a32806.html',1,'radiationCoupledBase']]],
  ['radiationmodel',['radiationModel',['../a30042.html',1,'Foam::radiation']]],
  ['radiativeintensityray',['radiativeIntensityRay',['../a30026.html',1,'Foam::radiation']]],
  ['rampholdfall',['rampHoldFall',['../a31566.html',1,'Foam']]],
  ['random',['Random',['../a28138.html',1,'Foam']]],
  ['randomcoalescence',['randomCoalescence',['../a32358.html',1,'Foam::diameterModels::IATEsources']]],
  ['randomise',['randomise',['../a28698.html',1,'Foam::calcTypes']]],
  ['randomrenumber',['randomRenumber',['../a29210.html',1,'Foam']]],
  ['ranzmarshall',['RanzMarshall',['../a32046.html',1,'RanzMarshall'],['../a24362.html',1,'RanzMarshall&lt; CloudType &gt;']]],
  ['rasmodel',['RASModel',['../a30758.html',1,'RASModel'],['../a31306.html',1,'RASModel&lt; BasicTurbulenceModel &gt;'],['../a31074.html',1,'RASModel']]],
  ['rasmodel_3c_20phasecompressibleturbulencemodel_3c_20phasemodel_20_3e_20_3e',['RASModel&lt; PhaseCompressibleTurbulenceModel&lt; phaseModel &gt; &gt;',['../a31306.html',1,'Foam']]],
  ['ravipetersen',['RaviPetersen',['../a29838.html',1,'Foam::laminarFlameSpeedModels']]],
  ['rawgraph',['rawGraph',['../a26718.html',1,'Foam']]],
  ['rawsetwriter',['rawSetWriter',['../a21870.html',1,'Foam']]],
  ['rawsurfacewriter',['rawSurfaceWriter',['../a29454.html',1,'Foam']]],
  ['rawtopochangerfvmesh',['rawTopoChangerFvMesh',['../a30466.html',1,'Foam']]],
  ['ray',['ray',['../a27574.html',1,'Foam::plane']]],
  ['rayshooting',['rayShooting',['../a31546.html',1,'Foam']]],
  ['reactingcloud',['reactingCloud',['../a23742.html',1,'reactingCloud'],['../a23814.html',1,'ReactingCloud&lt; CloudType &gt;']]],
  ['reactingcloud_3c_20foam_3a_3adsmccloud_20_3e',['ReactingCloud&lt; Foam::DsmcCloud &gt;',['../a23814.html',1,'Foam']]],
  ['reactinglookuptableinjection',['ReactingLookupTableInjection',['../a24306.html',1,'Foam']]],
  ['reactingmixture',['reactingMixture',['../a30150.html',1,'Foam']]],
  ['reactingmultiphasecloud',['reactingMultiphaseCloud',['../a23746.html',1,'reactingMultiphaseCloud'],['../a23826.html',1,'ReactingMultiphaseCloud&lt; CloudType &gt;']]],
  ['reactingmultiphasecloud_3c_20foam_3a_3adsmccloud_20_3e',['ReactingMultiphaseCloud&lt; Foam::DsmcCloud &gt;',['../a23826.html',1,'Foam']]],
  ['reactingmultiphaselookuptableinjection',['ReactingMultiphaseLookupTableInjection',['../a24342.html',1,'Foam']]],
  ['reactingmultiphaseparcel',['ReactingMultiphaseParcel',['../a23910.html',1,'Foam']]],
  ['reactingmultiphaseparcelinjectiondata',['reactingMultiphaseParcelInjectionData',['../a24346.html',1,'Foam']]],
  ['reactingmultiphaseparcelinjectiondataiolist',['reactingMultiphaseParcelInjectionDataIOList',['../a32590.html',1,'']]],
  ['reactingonedim',['reactingOneDim',['../a28978.html',1,'reactingOneDim'],['../a32642.html',1,'reactingOneDim']]],
  ['reactingparcel',['ReactingParcel',['../a23922.html',1,'Foam']]],
  ['reactingparcelinjectiondata',['reactingParcelInjectionData',['../a24310.html',1,'Foam']]],
  ['reactingparcelinjectiondataiolist',['reactingParcelInjectionDataIOList',['../a32586.html',1,'Foam']]],
  ['reaction',['Reaction',['../a30330.html',1,'Foam']]],
  ['reactionlist',['ReactionList',['../a30342.html',1,'Foam']]],
  ['reactionlist_3c_20foam_3a_3asutherlandtransport_20_3e',['ReactionList&lt; Foam::sutherlandTransport &gt;',['../a30342.html',1,'Foam']]],
  ['reactionrateflamearea',['reactionRateFlameArea',['../a21246.html',1,'Foam']]],
  ['readfields',['readFields',['../a28758.html',1,'Foam']]],
  ['realizableke',['realizableKE',['../a30762.html',1,'realizableKE'],['../a31078.html',1,'realizableKE']]],
  ['rebind_5ftds',['Rebind_TDS',['../a31466.html',1,'indexedCell&lt; Gt, Cb &gt;::Rebind_TDS&lt; TDS2 &gt;'],['../a31478.html',1,'indexedVertex&lt; Gt, Vb &gt;::Rebind_TDS&lt; TDS2 &gt;'],['../a31602.html',1,'indexedFace&lt; Gt, Fb &gt;::Rebind_TDS&lt; TDS2 &gt;']]],
  ['rebound',['Rebound',['../a24190.html',1,'Foam']]],
  ['rectangularmatrix',['RectangularMatrix',['../a27066.html',1,'Foam']]],
  ['rectangularmatrix_3c_20scalar_20_3e',['RectangularMatrix&lt; scalar &gt;',['../a27066.html',1,'Foam']]],
  ['reducedunits',['reducedUnits',['../a24410.html',1,'Foam']]],
  ['reducefilestates',['reduceFileStates',['../a28514.html',1,'Foam']]],
  ['refcount',['refCount',['../a27094.html',1,'Foam']]],
  ['referredwallface',['referredWallFace',['../a23582.html',1,'Foam']]],
  ['refinecell',['refineCell',['../a21522.html',1,'Foam']]],
  ['refinementdata',['refinementData',['../a21682.html',1,'Foam']]],
  ['refinementdistancedata',['refinementDistanceData',['../a21686.html',1,'Foam']]],
  ['refinementfeatures',['refinementFeatures',['../a24682.html',1,'Foam']]],
  ['refinementhistory',['refinementHistory',['../a21690.html',1,'Foam']]],
  ['refinementiterator',['refinementIterator',['../a21514.html',1,'Foam']]],
  ['refinementparameters',['refinementParameters',['../a24638.html',1,'Foam']]],
  ['refinementsurfaces',['refinementSurfaces',['../a24686.html',1,'Foam']]],
  ['reflectionvectors',['reflectionVectors',['../a22894.html',1,'Foam']]],
  ['regexp',['regExp',['../a28538.html',1,'Foam']]],
  ['regioncoupledbase',['regionCoupledBase',['../a25182.html',1,'Foam']]],
  ['regioncoupledbasefvpatch',['regionCoupledBaseFvPatch',['../a22854.html',1,'Foam']]],
  ['regioncoupledbasegamginterface',['regionCoupledBaseGAMGInterface',['../a25158.html',1,'Foam']]],
  ['regioncoupledfvpatch',['regionCoupledFvPatch',['../a22858.html',1,'Foam']]],
  ['regioncoupledgamginterface',['regionCoupledGAMGInterface',['../a25162.html',1,'Foam']]],
  ['regioncoupledgamginterfacefield',['regionCoupledGAMGInterfaceField',['../a25150.html',1,'Foam']]],
  ['regioncoupledlduinterface',['regionCoupledLduInterface',['../a25170.html',1,'Foam']]],
  ['regioncoupledpointpatch',['regionCoupledPointPatch',['../a25174.html',1,'Foam']]],
  ['regioncoupledpolypatch',['regionCoupledPolyPatch',['../a25186.html',1,'Foam']]],
  ['regioncoupledwallfvpatch',['regionCoupledWallFvPatch',['../a22862.html',1,'Foam']]],
  ['regioncoupledwallgamginterface',['regionCoupledWallGAMGInterface',['../a25166.html',1,'Foam']]],
  ['regioncoupledwallgamginterfacefield',['regionCoupledWallGAMGInterfaceField',['../a25154.html',1,'Foam']]],
  ['regioncoupledwallpointpatch',['regionCoupledWallPointPatch',['../a25178.html',1,'Foam']]],
  ['regioncoupledwallpolypatch',['regionCoupledWallPolyPatch',['../a25190.html',1,'Foam']]],
  ['regionmodel',['regionModel',['../a32646.html',1,'regionModel'],['../a28998.html',1,'regionModel']]],
  ['regionmodel1d',['regionModel1D',['../a32650.html',1,'regionModel1D'],['../a29002.html',1,'regionModel1D']]],
  ['regionmodelfunctionobject',['regionModelFunctionObject',['../a32654.html',1,'regionModelFunctionObject'],['../a29006.html',1,'regionModelFunctionObject']]],
  ['regionmodelfunctionobjectlist',['regionModelFunctionObjectList',['../a32658.html',1,'regionModelFunctionObjectList'],['../a29010.html',1,'regionModelFunctionObjectList']]],
  ['regionproperties',['regionProperties',['../a32662.html',1,'regionProperties'],['../a29014.html',1,'regionProperties']]],
  ['regionside',['regionSide',['../a31638.html',1,'Foam']]],
  ['regionsizedistribution',['regionSizeDistribution',['../a28766.html',1,'Foam']]],
  ['regionsplit',['regionSplit',['../a25202.html',1,'Foam']]],
  ['regiontocell',['regionToCell',['../a25310.html',1,'Foam']]],
  ['regiontoface',['regionToFace',['../a25374.html',1,'Foam']]],
  ['regioobject',['regIOobject',['../a26334.html',1,'Foam']]],
  ['reitzdiwakar',['ReitzDiwakar',['../a24570.html',1,'Foam']]],
  ['reitzkhrt',['ReitzKHRT',['../a24574.html',1,'Foam']]],
  ['relative',['relative',['../a24230.html',1,'Foam::CorrectionLimitingMethods']]],
  ['relativevelocitymodel',['relativeVelocityModel',['../a31966.html',1,'Foam']]],
  ['relaxation',['Relaxation',['../a24238.html',1,'Relaxation&lt; CloudType &gt;'],['../a21250.html',1,'relaxation']]],
  ['relaxationmodel',['relaxationModel',['../a31570.html',1,'Foam']]],
  ['removecells',['removeCells',['../a21698.html',1,'Foam']]],
  ['removeentry',['removeEntry',['../a26054.html',1,'Foam::functionEntries']]],
  ['removefaces',['removeFaces',['../a21702.html',1,'Foam']]],
  ['removepoints',['removePoints',['../a21722.html',1,'Foam']]],
  ['removeregisteredobject',['removeRegisteredObject',['../a28850.html',1,'Foam']]],
  ['renumbermethod',['renumberMethod',['../a29214.html',1,'Foam']]],
  ['repatchpolytopochanger',['repatchPolyTopoChanger',['../a21738.html',1,'Foam']]],
  ['residuals',['residuals',['../a28906.html',1,'Foam']]],
  ['restrainedharmonicspring',['restrainedHarmonicSpring',['../a24494.html',1,'Foam::tetherPotentials']]],
  ['reusetmp',['reuseTmp',['../a26478.html',1,'Foam']]],
  ['reusetmp_3c_20typer_2c_20typer_20_3e',['reuseTmp&lt; TypeR, TypeR &gt;',['../a26482.html',1,'Foam']]],
  ['reusetmpdimensionedfield',['reuseTmpDimensionedField',['../a26394.html',1,'Foam']]],
  ['reusetmpdimensionedfield_3c_20typer_2c_20typer_2c_20geomesh_20_3e',['reuseTmpDimensionedField&lt; TypeR, TypeR, GeoMesh &gt;',['../a26398.html',1,'Foam']]],
  ['reusetmpfieldfield',['reuseTmpFieldField',['../a26426.html',1,'Foam']]],
  ['reusetmpfieldfield_3c_20field_2c_20typer_2c_20typer_20_3e',['reuseTmpFieldField&lt; Field, TypeR, TypeR &gt;',['../a26430.html',1,'Foam']]],
  ['reusetmpgeometricfield',['reuseTmpGeometricField',['../a26518.html',1,'Foam']]],
  ['reusetmpgeometricfield_3c_20typer_2c_20typer_2c_20patchfield_2c_20geomesh_20_3e',['reuseTmpGeometricField&lt; TypeR, TypeR, PatchField, GeoMesh &gt;',['../a26522.html',1,'Foam']]],
  ['reusetmptmp',['reuseTmpTmp',['../a26486.html',1,'Foam']]],
  ['reusetmptmp_3c_20typer_2c_20type1_2c_20type12_2c_20typer_20_3e',['reuseTmpTmp&lt; TypeR, Type1, Type12, TypeR &gt;',['../a26490.html',1,'Foam']]],
  ['reusetmptmp_3c_20typer_2c_20typer_2c_20typer_2c_20type2_20_3e',['reuseTmpTmp&lt; TypeR, TypeR, TypeR, Type2 &gt;',['../a26494.html',1,'Foam']]],
  ['reusetmptmp_3c_20typer_2c_20typer_2c_20typer_2c_20typer_20_3e',['reuseTmpTmp&lt; TypeR, TypeR, TypeR, TypeR &gt;',['../a26498.html',1,'Foam']]],
  ['reusetmptmpdimensionedfield',['reuseTmpTmpDimensionedField',['../a26402.html',1,'Foam']]],
  ['reusetmptmpdimensionedfield_3c_20typer_2c_20type1_2c_20type12_2c_20typer_2c_20geomesh_20_3e',['reuseTmpTmpDimensionedField&lt; TypeR, Type1, Type12, TypeR, GeoMesh &gt;',['../a26406.html',1,'Foam']]],
  ['reusetmptmpdimensionedfield_3c_20typer_2c_20typer_2c_20typer_2c_20type2_2c_20geomesh_20_3e',['reuseTmpTmpDimensionedField&lt; TypeR, TypeR, TypeR, Type2, GeoMesh &gt;',['../a26410.html',1,'Foam']]],
  ['reusetmptmpdimensionedfield_3c_20typer_2c_20typer_2c_20typer_2c_20typer_2c_20geomesh_20_3e',['reuseTmpTmpDimensionedField&lt; TypeR, TypeR, TypeR, TypeR, GeoMesh &gt;',['../a26414.html',1,'Foam']]],
  ['reusetmptmpfieldfield',['reuseTmpTmpFieldField',['../a26434.html',1,'Foam']]],
  ['reusetmptmpfieldfield_3c_20field_2c_20typer_2c_20type1_2c_20type12_2c_20typer_20_3e',['reuseTmpTmpFieldField&lt; Field, TypeR, Type1, Type12, TypeR &gt;',['../a26438.html',1,'Foam']]],
  ['reusetmptmpfieldfield_3c_20field_2c_20typer_2c_20typer_2c_20typer_2c_20type2_20_3e',['reuseTmpTmpFieldField&lt; Field, TypeR, TypeR, TypeR, Type2 &gt;',['../a26442.html',1,'Foam']]],
  ['reusetmptmpfieldfield_3c_20field_2c_20typer_2c_20typer_2c_20typer_2c_20typer_20_3e',['reuseTmpTmpFieldField&lt; Field, TypeR, TypeR, TypeR, TypeR &gt;',['../a26446.html',1,'Foam']]],
  ['reusetmptmpgeometricfield',['reuseTmpTmpGeometricField',['../a26526.html',1,'Foam']]],
  ['reusetmptmpgeometricfield_3c_20typer_2c_20type1_2c_20type12_2c_20typer_2c_20patchfield_2c_20geomesh_20_3e',['reuseTmpTmpGeometricField&lt; TypeR, Type1, Type12, TypeR, PatchField, GeoMesh &gt;',['../a26530.html',1,'Foam']]],
  ['reusetmptmpgeometricfield_3c_20typer_2c_20typer_2c_20typer_2c_20type2_2c_20patchfield_2c_20geomesh_20_3e',['reuseTmpTmpGeometricField&lt; TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh &gt;',['../a26534.html',1,'Foam']]],
  ['reusetmptmpgeometricfield_3c_20typer_2c_20typer_2c_20typer_2c_20typer_2c_20patchfield_2c_20geomesh_20_3e',['reuseTmpTmpGeometricField&lt; TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh &gt;',['../a26538.html',1,'Foam']]],
  ['reverselinear',['reverseLinear',['../a23250.html',1,'Foam']]],
  ['reversiblereaction',['ReversibleReaction',['../a30346.html',1,'Foam']]],
  ['rhochemistrycombustion',['rhoChemistryCombustion',['../a21282.html',1,'rhoChemistryCombustion'],['../a32414.html',1,'rhoChemistryCombustion']]],
  ['rhochemistrymodel',['rhoChemistryModel',['../a29802.html',1,'Foam']]],
  ['rhocombustionmodel',['rhoCombustionModel',['../a21286.html',1,'rhoCombustionModel'],['../a32418.html',1,'rhoCombustionModel']]],
  ['rhoconst',['rhoConst',['../a30266.html',1,'Foam']]],
  ['rhomagsqr',['rhoMagSqr',['../a23026.html',1,'Foam::limitFuncs']]],
  ['rhoreactionthermo',['rhoReactionThermo',['../a30178.html',1,'Foam']]],
  ['rhothermo',['rhoThermo',['../a29786.html',1,'Foam']]],
  ['rhothermocombustion',['rhoThermoCombustion',['../a21290.html',1,'rhoThermoCombustion'],['../a32422.html',1,'rhoThermoCombustion']]],
  ['rkck45',['RKCK45',['../a25562.html',1,'Foam']]],
  ['rkdp45',['RKDP45',['../a25566.html',1,'Foam']]],
  ['rkf45',['RKF45',['../a25570.html',1,'Foam']]],
  ['rngkepsilon',['RNGkEpsilon',['../a30766.html',1,'RNGkEpsilon'],['../a31082.html',1,'RNGkEpsilon']]],
  ['rodas23',['rodas23',['../a25574.html',1,'Foam']]],
  ['rodas34',['rodas34',['../a25578.html',1,'Foam']]],
  ['rosenbrock12',['Rosenbrock12',['../a25582.html',1,'Foam']]],
  ['rosenbrock23',['Rosenbrock23',['../a25586.html',1,'Foam']]],
  ['rosenbrock34',['Rosenbrock34',['../a25590.html',1,'Foam']]],
  ['rosinrammler',['RosinRammler',['../a32514.html',1,'RosinRammler'],['../a23662.html',1,'RosinRammler']]],
  ['rotatedboxtocell',['rotatedBoxToCell',['../a25314.html',1,'Foam']]],
  ['rotatingmotion',['rotatingMotion',['../a21402.html',1,'Foam::solidBodyMotionFunctions']]],
  ['rotatingpressureinletoutletvelocityfvpatchvectorfield',['rotatingPressureInletOutletVelocityFvPatchVectorField',['../a22246.html',1,'Foam']]],
  ['rotatingtotalpressurefvpatchscalarfield',['rotatingTotalPressureFvPatchScalarField',['../a22250.html',1,'Foam']]],
  ['rotatingwallvelocityfvpatchvectorfield',['rotatingWallVelocityFvPatchVectorField',['../a22254.html',1,'Foam']]],
  ['rotordisksource',['rotorDiskSource',['../a23502.html',1,'Foam::fv']]],
  ['rpm',['rpm',['../a21958.html',1,'Foam::SRF']]]
];
